import { PatternCategory } from "@/types/pattern";

export const categoryA7: PatternCategory = {
  id: "A7",
  slug: "expressing-indifference",
  name: "Expressing Indifference",
  name_bn: "উদাসীনতা প্রকাশ করা",
  description:
    "Learn how to express that you have no preference, don't mind, or are neutral about something.",
  description_bn:
    "আপনার কোনো পছন্দ নেই, আপত্তি নেই, বা কিছু সম্পর্কে নিরপেক্ষ—এটা প্রকাশ করতে শিখুন।",
  icon: "😐",
  group: "A",
  groupName: "Wanting, Needing & Preferences",
  groupName_bn: "চাওয়া, প্রয়োজন এবং পছন্দ",
  difficulty: "beginner",
  prerequisites: ["A1", "A5"],
  patterns: [
    {
      id: "A7.1",
      formula: "I don't mind [THING/DOING]",
      formula_bn: "আমার [জিনিস/করতে] আপত্তি নেই",
      patternName: "No Objection",
      patternName_bn: "কোনো আপত্তি নেই",
      slots: [
        {
          name: "THING/DOING",
          description: "A noun, noun phrase, or gerund phrase you don't mind",
          description_bn:
            "একটি বিশেষ্য, বিশেষ্য পদবন্ধ, বা জেরান্ড পদবন্ধ যাতে আপনার আপত্তি নেই",
          acceptedTypes: ["noun", "gerund"],
          examples: ["waiting", "the cold", "sitting in the back"],
        },
      ],
      examples: [
        {
          en: "I don't mind waiting.",
          bn: "আমার অপেক্ষা করতে আপত্তি নেই।",
          slotValues: { "THING/DOING": "waiting" },
          topicArea: "daily_life",
        },
        {
          en: "I don't mind the cold.",
          bn: "আমার ঠান্ডায় আপত্তি নেই।",
          slotValues: { "THING/DOING": "the cold" },
          topicArea: "daily_life",
        },
        {
          en: "I don't mind sitting in the back.",
          bn: "আমার পেছনে বসতে আপত্তি নেই।",
          slotValues: { "THING/DOING": "sitting in the back" },
          topicArea: "travel",
        },
        {
          en: "I don't mind working late.",
          bn: "আমার দেরিতে কাজ করতে আপত্তি নেই।",
          slotValues: { "THING/DOING": "working late" },
          topicArea: "work",
        },
        {
          en: "I don't mind spicy food.",
          bn: "আমার ঝাল খাবারে আপত্তি নেই।",
          slotValues: { "THING/DOING": "spicy food" },
          topicArea: "food",
        },
        {
          en: "I don't mind studying on weekends.",
          bn: "আমার সাপ্তাহিক ছুটিতে পড়তে আপত্তি নেই।",
          slotValues: { "THING/DOING": "studying on weekends" },
          topicArea: "education",
        },
        {
          en: "I don't mind walking to the hotel.",
          bn: "আমার হোটেল পর্যন্ত হেঁটে যেতে আপত্তি নেই।",
          slotValues: { "THING/DOING": "walking to the hotel" },
          topicArea: "travel",
        },
        {
          en: "I don't mind taking the stairs.",
          bn: "আমার সিঁড়ি দিয়ে উঠতে আপত্তি নেই।",
          slotValues: { "THING/DOING": "taking the stairs" },
          topicArea: "health",
        },
        {
          en: "I don't mind lending you some money.",
          bn: "আমার তোমাকে কিছু টাকা ধার দিতে আপত্তি নেই।",
          slotValues: { "THING/DOING": "lending you some money" },
          topicArea: "relationships",
        },
        {
          en: "I don't mind a cheaper option.",
          bn: "আমার সস্তা বিকল্পে আপত্তি নেই।",
          slotValues: { "THING/DOING": "a cheaper option" },
          topicArea: "shopping",
        },
        {
          en: "I don't mind cooking tonight.",
          bn: "আমার আজ রাতে রান্না করতে আপত্তি নেই।",
          slotValues: { "THING/DOING": "cooking tonight" },
          topicArea: "food",
        },
        {
          en: "I don't mind the noise.",
          bn: "আমার শব্দে আপত্তি নেই।",
          slotValues: { "THING/DOING": "the noise" },
          topicArea: "daily_life",
        },
        {
          en: "I don't mind doing the extra assignment.",
          bn: "আমার অতিরিক্ত অ্যাসাইনমেন্ট করতে আপত্তি নেই।",
          slotValues: { "THING/DOING": "doing the extra assignment" },
          topicArea: "education",
        },
        {
          en: "I don't mind sharing a room.",
          bn: "আমার রুম শেয়ার করতে আপত্তি নেই।",
          slotValues: { "THING/DOING": "sharing a room" },
          topicArea: "travel",
        },
        {
          en: "I don't mind overtime on this project.",
          bn: "আমার এই প্রকল্পে ওভারটাইম করতে আপত্তি নেই।",
          slotValues: { "THING/DOING": "overtime on this project" },
          topicArea: "work",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "'I don't mind' means you have no objection. It can also be a polite way to volunteer: 'I don't mind helping.'",
      usageNote_bn:
        "'I don't mind' মানে আপনার কোনো আপত্তি নেই। এটি স্বেচ্ছায় সাহায্যের বিনয়ী উপায়ও হতে পারে: 'I don't mind helping.'",
      combinableWith: ["A7.3"],
      responsePatterns: ["B7.1"],
      banglaStructureMap:
        "আমার (Possessor) + [THING/DOING] (Object/Gerund) + আপত্তি নেই (No objection)",
    },
    {
      id: "A7.2",
      formula: "It doesn't matter to me",
      formula_bn: "আমার কাছে কোনো পার্থক্য নেই",
      patternName: "Complete Indifference",
      patternName_bn: "সম্পূর্ণ উদাসীনতা",
      slots: [],
      examples: [
        {
          en: "It doesn't matter to me.",
          bn: "আমার কাছে কোনো পার্থক্য নেই।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "It doesn't matter to me which restaurant we go to.",
          bn: "আমরা কোন রেস্তোরাঁয় যাই আমার কাছে কোনো পার্থক্য নেই।",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "It doesn't matter to me what time we leave.",
          bn: "আমরা কটায় রওনা দিই আমার কাছে কোনো পার্থক্য নেই।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "It doesn't matter to me who leads the project.",
          bn: "কে প্রকল্পের নেতৃত্ব দেয় আমার কাছে কোনো পার্থক্য নেই।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "It doesn't matter to me where we sit.",
          bn: "আমরা কোথায় বসি আমার কাছে কোনো পার্থক্য নেই।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "It doesn't matter to me what we eat tonight.",
          bn: "আজ রাতে আমরা কী খাই আমার কাছে কোনো পার্থক্য নেই।",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "It doesn't matter to me which hotel we book.",
          bn: "আমরা কোন হোটেল বুক করি আমার কাছে কোনো পার্থক্য নেই।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "It doesn't matter to me if it's online or offline.",
          bn: "এটা অনলাইন হোক বা অফলাইন, আমার কাছে কোনো পার্থক্য নেই।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "It doesn't matter to me which brand it is.",
          bn: "এটা কোন ব্র্যান্ড আমার কাছে কোনো পার্থক্য নেই।",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "It doesn't matter to me who comes along.",
          bn: "কে সাথে আসবে আমার কাছে কোনো পার্থক্য নেই।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "It doesn't matter to me how long it takes.",
          bn: "এতে কতক্ষণ লাগবে আমার কাছে কোনো পার্থক্য নেই।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "It doesn't matter to me which day we meet.",
          bn: "আমরা কোন দিন দেখা করি আমার কাছে কোনো পার্থক্য নেই।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "It doesn't matter to me whether it's morning or afternoon.",
          bn: "এটা সকাল হোক বা বিকাল, আমার কাছে কোনো পার্থক্য নেই।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "It doesn't matter to me if it rains.",
          bn: "বৃষ্টি হলেও আমার কাছে কোনো পার্থক্য নেই।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "It doesn't matter to me which subject we start with.",
          bn: "আমরা কোন বিষয় দিয়ে শুরু করি আমার কাছে কোনো পার্থক্য নেই।",
          slotValues: {},
          topicArea: "education",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Expresses that you truly have no preference. Can sometimes sound apathetic, so use tone carefully.",
      usageNote_bn:
        "প্রকাশ করে যে সত্যিই আপনার কোনো পছন্দ নেই। মাঝে মাঝে উদাসীন শোনাতে পারে, তাই স্বর সাবধানে ব্যবহার করুন।",
      combinableWith: ["A7.1", "A7.3"],
      banglaStructureMap:
        "আমার কাছে (Possessor + Locative) + কোনো পার্থক্য নেই (No difference)",
    },
    {
      id: "A7.3",
      formula: "Either one is fine",
      formula_bn: "যেকোনো একটি হলেই চলবে",
      patternName: "No Preference Between Two",
      patternName_bn: "দুটির মধ্যে কোনো পছন্দ নেই",
      slots: [],
      examples: [
        {
          en: "Either one is fine.",
          bn: "যেকোনো একটি হলেই চলবে।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Either one is fine with me.",
          bn: "আমার কাছে যেকোনো একটি হলেই চলবে।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Tea or coffee? Either one is fine.",
          bn: "চা না কফি? যেকোনো একটি হলেই চলবে।",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "Should we fly or take the train? Either one is fine.",
          bn: "আমরা কি বিমানে যাব না ট্রেনে? যেকোনো একটি হলেই চলবে।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "Morning or afternoon meeting? Either one is fine.",
          bn: "সকাল না বিকেলের মিটিং? যেকোনো একটি হলেই চলবে।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "The blue or the red one? Either one is fine.",
          bn: "নীল না লাল? যেকোনো একটি হলেই চলবে।",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "Study group or solo study? Either one is fine.",
          bn: "দলীয় পড়া না একা পড়া? যেকোনো একটি হলেই চলবে।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "Pizza or pasta? Either one is fine.",
          bn: "পিৎজা না পাস্তা? যেকোনো একটি হলেই চলবে।",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "Walking or cycling? Either one is fine.",
          bn: "হাঁটা না সাইকেল চালানো? যেকোনো একটি হলেই চলবে।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "Call or text? Either one is fine.",
          bn: "ফোন না মেসেজ? যেকোনো একটি হলেই চলবে।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "Cash or card? Either one is fine.",
          bn: "নগদ না কার্ড? যেকোনো একটি হলেই চলবে।",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "Beach or mountains? Either one is fine.",
          bn: "সমুদ্র সৈকত না পাহাড়? যেকোনো একটি হলেই চলবে।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "Monday or Tuesday? Either one is fine.",
          bn: "সোমবার না মঙ্গলবার? যেকোনো একটি হলেই চলবে।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "Should I come to you or you come to me? Either one is fine.",
          bn: "আমি তোমার কাছে আসব না তুমি আমার কাছে আসবে? যেকোনো একটি হলেই চলবে।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "English or Bengali medium? Either one is fine.",
          bn: "ইংরেজি না বাংলা মাধ্যম? যেকোনো একটি হলেই চলবে।",
          slotValues: {},
          topicArea: "education",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "A friendly, easygoing response when someone offers you two options. Shows you're flexible.",
      usageNote_bn:
        "কেউ দুটি বিকল্প দিলে একটি বন্ধুত্বপূর্ণ, নির্ভার উত্তর। দেখায় যে আপনি নমনীয়।",
      combinableWith: ["A7.1", "A7.2"],
      banglaStructureMap:
        "যেকোনো একটি (Either one) + হলেই চলবে (is fine)",
    },
    {
      id: "A7.4",
      formula: "Whatever you [ACTION] is fine",
      formula_bn: "তুমি যা [কাজ] করো সেটাই ঠিক আছে",
      patternName: "Deferring to Others",
      patternName_bn: "অন্যের উপর ছেড়ে দেওয়া",
      slots: [
        {
          name: "ACTION",
          description:
            "A base-form verb representing the decision being left to the other person",
          description_bn:
            "একটি মূল-রূপ ক্রিয়া যা অন্য ব্যক্তির উপর ছেড়ে দেওয়া সিদ্ধান্ত",
          acceptedTypes: ["verb"],
          examples: ["decide", "choose", "think is best"],
        },
      ],
      examples: [
        {
          en: "Whatever you decide is fine.",
          bn: "তুমি যা সিদ্ধান্ত নাও সেটাই ঠিক আছে।",
          slotValues: { ACTION: "decide" },
          topicArea: "daily_life",
        },
        {
          en: "Whatever you choose is fine.",
          bn: "তুমি যা বেছে নাও সেটাই ঠিক আছে।",
          slotValues: { ACTION: "choose" },
          topicArea: "daily_life",
        },
        {
          en: "Whatever you think is best is fine.",
          bn: "তুমি যা সবচেয়ে ভালো মনে করো সেটাই ঠিক আছে।",
          slotValues: { ACTION: "think is best" },
          topicArea: "daily_life",
        },
        {
          en: "Whatever you cook is fine.",
          bn: "তুমি যা রান্না করো সেটাই ঠিক আছে।",
          slotValues: { ACTION: "cook" },
          topicArea: "food",
        },
        {
          en: "Whatever you order is fine.",
          bn: "তুমি যা অর্ডার করো সেটাই ঠিক আছে।",
          slotValues: { ACTION: "order" },
          topicArea: "food",
        },
        {
          en: "Whatever you plan is fine.",
          bn: "তুমি যা পরিকল্পনা করো সেটাই ঠিক আছে।",
          slotValues: { ACTION: "plan" },
          topicArea: "travel",
        },
        {
          en: "Whatever you recommend is fine.",
          bn: "তুমি যা সুপারিশ করো সেটাই ঠিক আছে।",
          slotValues: { ACTION: "recommend" },
          topicArea: "health",
        },
        {
          en: "Whatever you suggest is fine.",
          bn: "তুমি যা পরামর্শ দাও সেটাই ঠিক আছে।",
          slotValues: { ACTION: "suggest" },
          topicArea: "work",
        },
        {
          en: "Whatever you prefer is fine.",
          bn: "তুমি যা পছন্দ করো সেটাই ঠিক আছে।",
          slotValues: { ACTION: "prefer" },
          topicArea: "relationships",
        },
        {
          en: "Whatever you pick is fine.",
          bn: "তুমি যা বাছাই করো সেটাই ঠিক আছে।",
          slotValues: { ACTION: "pick" },
          topicArea: "shopping",
        },
        {
          en: "Whatever you want to study is fine.",
          bn: "তুমি যা পড়তে চাও সেটাই ঠিক আছে।",
          slotValues: { ACTION: "want to study" },
          topicArea: "education",
        },
        {
          en: "Whatever you book is fine.",
          bn: "তুমি যা বুক করো সেটাই ঠিক আছে।",
          slotValues: { ACTION: "book" },
          topicArea: "travel",
        },
        {
          en: "Whatever you buy is fine.",
          bn: "তুমি যা কেনো সেটাই ঠিক আছে।",
          slotValues: { ACTION: "buy" },
          topicArea: "shopping",
        },
        {
          en: "Whatever you arrange is fine.",
          bn: "তুমি যা ব্যবস্থা করো সেটাই ঠিক আছে।",
          slotValues: { ACTION: "arrange" },
          topicArea: "work",
        },
        {
          en: "Whatever you feel like doing is fine.",
          bn: "তোমার যা করতে ইচ্ছা হয় সেটাই ঠিক আছে।",
          slotValues: { ACTION: "feel like doing" },
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Shows flexibility and trust. You're saying the other person can make the decision.",
      usageNote_bn:
        "নমনীয়তা এবং বিশ্বাস দেখায়। আপনি বলছেন অন্য ব্যক্তি সিদ্ধান্ত নিতে পারে।",
      combinableWith: ["A7.1", "A7.2"],
      banglaStructureMap:
        "তুমি যা (Whatever you) + [ACTION] (Verb) + করো (do) + সেটাই ঠিক আছে (that's fine)",
    },
    {
      id: "A7.5",
      formula: "It makes no difference whether [A] or [B]",
      formula_bn: "[A] না [B] তাতে কোনো পার্থক্য নেই",
      patternName: "No Difference Statement",
      patternName_bn: "কোনো পার্থক্য নেই বিবৃতি",
      slots: [
        {
          name: "A",
          description: "First option (clause or noun phrase)",
          description_bn: "প্রথম বিকল্প (উপবাক্য বা বিশেষ্য পদবন্ধ)",
          acceptedTypes: ["clause", "noun"],
          examples: ["we go today", "it's hot", "rice"],
        },
        {
          name: "B",
          description: "Second option (clause or noun phrase)",
          description_bn: "দ্বিতীয় বিকল্প (উপবাক্য বা বিশেষ্য পদবন্ধ)",
          acceptedTypes: ["clause", "noun"],
          examples: ["we go tomorrow", "it's cold", "bread"],
        },
      ],
      examples: [
        {
          en: "It makes no difference whether we go today or tomorrow.",
          bn: "আমরা আজ যাই বা কাল যাই তাতে কোনো পার্থক্য নেই।",
          slotValues: { A: "we go today", B: "tomorrow" },
          topicArea: "travel",
        },
        {
          en: "It makes no difference whether it's hot or cold.",
          bn: "গরম হোক বা ঠান্ডা তাতে কোনো পার্থক্য নেই।",
          slotValues: { A: "it's hot", B: "cold" },
          topicArea: "food",
        },
        {
          en: "It makes no difference whether we eat rice or bread.",
          bn: "আমরা ভাত খাই বা রুটি তাতে কোনো পার্থক্য নেই।",
          slotValues: { A: "we eat rice", B: "bread" },
          topicArea: "food",
        },
        {
          en: "It makes no difference whether we take a taxi or the bus.",
          bn: "আমরা ট্যাক্সি নিই বা বাস তাতে কোনো পার্থক্য নেই।",
          slotValues: { A: "we take a taxi", B: "the bus" },
          topicArea: "travel",
        },
        {
          en: "It makes no difference whether I work from home or the office.",
          bn: "আমি বাসা থেকে কাজ করি বা অফিস থেকে তাতে কোনো পার্থক্য নেই।",
          slotValues: { A: "I work from home", B: "the office" },
          topicArea: "work",
        },
        {
          en: "It makes no difference whether we meet online or in person.",
          bn: "আমরা অনলাইনে দেখা করি বা সশরীরে তাতে কোনো পার্থক্য নেই।",
          slotValues: { A: "we meet online", B: "in person" },
          topicArea: "work",
        },
        {
          en: "It makes no difference whether it rains or not.",
          bn: "বৃষ্টি হোক বা না হোক তাতে কোনো পার্থক্য নেই।",
          slotValues: { A: "it rains", B: "not" },
          topicArea: "daily_life",
        },
        {
          en: "It makes no difference whether we study now or later.",
          bn: "আমরা এখন পড়ি বা পরে তাতে কোনো পার্থক্য নেই।",
          slotValues: { A: "we study now", B: "later" },
          topicArea: "education",
        },
        {
          en: "It makes no difference whether you call or text me.",
          bn: "তুমি ফোন করো বা মেসেজ করো তাতে কোনো পার্থক্য নেই।",
          slotValues: { A: "you call", B: "text me" },
          topicArea: "relationships",
        },
        {
          en: "It makes no difference whether I buy it online or in the store.",
          bn: "আমি এটা অনলাইনে কিনি বা দোকানে তাতে কোনো পার্থক্য নেই।",
          slotValues: { A: "I buy it online", B: "in the store" },
          topicArea: "shopping",
        },
        {
          en: "It makes no difference whether we sit inside or outside.",
          bn: "আমরা ভেতরে বসি বা বাইরে তাতে কোনো পার্থক্য নেই।",
          slotValues: { A: "we sit inside", B: "outside" },
          topicArea: "food",
        },
        {
          en: "It makes no difference whether the doctor is male or female.",
          bn: "ডাক্তার পুরুষ হোক বা মহিলা তাতে কোনো পার্থক্য নেই।",
          slotValues: { A: "the doctor is male", B: "female" },
          topicArea: "health",
        },
        {
          en: "It makes no difference whether we start at 9 or 10.",
          bn: "আমরা ৯টায় শুরু করি বা ১০টায় তাতে কোনো পার্থক্য নেই।",
          slotValues: { A: "we start at 9", B: "10" },
          topicArea: "education",
        },
        {
          en: "It makes no difference whether he comes or not.",
          bn: "সে আসুক বা না আসুক তাতে কোনো পার্থক্য নেই।",
          slotValues: { A: "he comes", B: "not" },
          topicArea: "relationships",
        },
        {
          en: "It makes no difference whether I take the medicine before or after eating.",
          bn: "আমি খাওয়ার আগে ওষুধ খাই বা পরে তাতে কোনো পার্থক্য নেই।",
          slotValues: { A: "I take the medicine before", B: "after eating" },
          topicArea: "health",
        },
      ],
      formality: "polite",
      difficulty: "beginner",
      usageNote:
        "A more elaborate way to say you have no preference. Sounds neutral and considered.",
      usageNote_bn:
        "আপনার কোনো পছন্দ নেই বলার আরও বিস্তারিত উপায়। নিরপেক্ষ এবং চিন্তাশীল শোনায়।",
      combinableWith: ["A7.2"],
      banglaStructureMap:
        "[A] বা [B] (Options) + তাতে কোনো পার্থক্য নেই (No difference)",
    },
  ],
};
