import { PatternCategory } from "@/types/pattern";

export const categoryC13: PatternCategory = {
  id: "C13",
  slug: "infinitive-vs-gerund",
  name: "Infinitive vs Gerund",
  name_bn: "ইনফিনিটিভ বনাম জেরান্ড",
  description:
    "Learn when to use the infinitive (to + verb) and when to use the gerund (verb + -ing) after common verbs in English.",
  description_bn:
    "ইংরেজিতে সাধারণ ক্রিয়ার পরে কখন ইনফিনিটিভ (to + verb) এবং কখন জেরান্ড (verb + -ing) ব্যবহার করতে হয় শিখুন।",
  icon: "⚖️",
  group: "C",
  groupName: "Actions & Time Patterns",
  groupName_bn: "কর্ম ও সময় প্যাটার্ন",
  difficulty: "intermediate",
  patterns: [
    {
      id: "C13.1",
      formula: "I enjoy [DOING]",
      formula_bn: "আমি [কাজ করা] উপভোগ করি",
      patternName: "Enjoy + Gerund",
      patternName_bn: "Enjoy + জেরান্ড",
      slots: [
        {
          name: "DOING",
          description: "A verb in -ing form describing the activity you enjoy",
          description_bn: "একটি -ing রূপের ক্রিয়া যা আপনি উপভোগ করেন",
          acceptedTypes: ["gerund"],
          examples: ["reading books", "cooking dinner", "playing football"],
        },
      ],
      examples: [
        { en: "I enjoy reading books.", bn: "আমি বই পড়া উপভোগ করি।", slotValues: { DOING: "reading books" }, topicArea: "education" },
        { en: "I enjoy cooking dinner for my family.", bn: "আমি পরিবারের জন্য রাতের খাবার রান্না করা উপভোগ করি।", slotValues: { DOING: "cooking dinner for my family" }, topicArea: "food" },
        { en: "I enjoy playing football on weekends.", bn: "আমি সাপ্তাহিক ছুটিতে ফুটবল খেলা উপভোগ করি।", slotValues: { DOING: "playing football on weekends" }, topicArea: "daily_life" },
        { en: "I enjoy traveling to new places.", bn: "আমি নতুন জায়গায় ভ্রমণ করা উপভোগ করি।", slotValues: { DOING: "traveling to new places" }, topicArea: "travel" },
        { en: "I enjoy listening to music after work.", bn: "আমি কাজের পর গান শোনা উপভোগ করি।", slotValues: { DOING: "listening to music after work" }, topicArea: "daily_life" },
        { en: "I enjoy spending time with my friends.", bn: "আমি বন্ধুদের সাথে সময় কাটানো উপভোগ করি।", slotValues: { DOING: "spending time with my friends" }, topicArea: "relationships" },
        { en: "I enjoy working on creative projects.", bn: "আমি সৃজনশীল প্রকল্পে কাজ করা উপভোগ করি।", slotValues: { DOING: "working on creative projects" }, topicArea: "work" },
        { en: "I enjoy shopping for clothes.", bn: "আমি জামাকাপড় কেনাকাটা করা উপভোগ করি।", slotValues: { DOING: "shopping for clothes" }, topicArea: "shopping" },
        { en: "I enjoy swimming in the morning.", bn: "আমি সকালে সাঁতার কাটা উপভোগ করি।", slotValues: { DOING: "swimming in the morning" }, topicArea: "health" },
        { en: "I enjoy learning new languages.", bn: "আমি নতুন ভাষা শেখা উপভোগ করি।", slotValues: { DOING: "learning new languages" }, topicArea: "education" },
        { en: "I enjoy trying different cuisines.", bn: "আমি বিভিন্ন রান্নার স্বাদ নেওয়া উপভোগ করি।", slotValues: { DOING: "trying different cuisines" }, topicArea: "food" },
        { en: "I enjoy walking in the park.", bn: "আমি পার্কে হাঁটা উপভোগ করি।", slotValues: { DOING: "walking in the park" }, topicArea: "health" },
        { en: "I enjoy chatting with my colleagues.", bn: "আমি সহকর্মীদের সাথে আড্ডা দেওয়া উপভোগ করি।", slotValues: { DOING: "chatting with my colleagues" }, topicArea: "work" },
        { en: "I enjoy exploring local markets.", bn: "আমি স্থানীয় বাজার ঘুরে দেখা উপভোগ করি।", slotValues: { DOING: "exploring local markets" }, topicArea: "travel" },
        { en: "I enjoy hanging out with my siblings.", bn: "আমি ভাইবোনদের সাথে আড্ডা দেওয়া উপভোগ করি।", slotValues: { DOING: "hanging out with my siblings" }, topicArea: "relationships" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Enjoy' is always followed by a gerund (-ing form), never an infinitive. 'I enjoy to read' is incorrect.",
      usageNote_bn:
        "'Enjoy' এর পরে সবসময় জেরান্ড (-ing রূপ) আসে, কখনো ইনফিনিটিভ নয়। 'I enjoy to read' ভুল।",
    },
    {
      id: "C13.2",
      formula: "I want to [ACTION]",
      formula_bn: "আমি [কাজ] করতে চাই",
      patternName: "Want + Infinitive",
      patternName_bn: "Want + ইনফিনিটিভ",
      slots: [
        {
          name: "ACTION",
          description: "A base verb describing what you want to do",
          description_bn: "আপনি যা করতে চান তার জন্য একটি মূল ক্রিয়া",
          acceptedTypes: ["verb"],
          examples: ["learn English", "buy a house", "visit Japan"],
        },
      ],
      examples: [
        { en: "I want to learn English fluently.", bn: "আমি সাবলীলভাবে ইংরেজি শিখতে চাই।", slotValues: { ACTION: "learn English fluently" }, topicArea: "education" },
        { en: "I want to buy a new phone.", bn: "আমি একটা নতুন ফোন কিনতে চাই।", slotValues: { ACTION: "buy a new phone" }, topicArea: "shopping" },
        { en: "I want to visit Japan next year.", bn: "আমি আগামী বছর জাপান ভ্রমণ করতে চাই।", slotValues: { ACTION: "visit Japan next year" }, topicArea: "travel" },
        { en: "I want to eat something spicy.", bn: "আমি ঝাল কিছু খেতে চাই।", slotValues: { ACTION: "eat something spicy" }, topicArea: "food" },
        { en: "I want to get a promotion this year.", bn: "আমি এই বছর পদোন্নতি পেতে চাই।", slotValues: { ACTION: "get a promotion this year" }, topicArea: "work" },
        { en: "I want to spend more time with you.", bn: "আমি তোমার সাথে আরও বেশি সময় কাটাতে চাই।", slotValues: { ACTION: "spend more time with you" }, topicArea: "relationships" },
        { en: "I want to start exercising regularly.", bn: "আমি নিয়মিত ব্যায়াম শুরু করতে চাই।", slotValues: { ACTION: "start exercising regularly" }, topicArea: "health" },
        { en: "I want to clean the house today.", bn: "আমি আজ ঘর পরিষ্কার করতে চাই।", slotValues: { ACTION: "clean the house today" }, topicArea: "daily_life" },
        { en: "I want to try that new restaurant.", bn: "আমি ওই নতুন রেস্তোরাঁটি ট্রাই করতে চাই।", slotValues: { ACTION: "try that new restaurant" }, topicArea: "food" },
        { en: "I want to finish my assignment early.", bn: "আমি তাড়াতাড়ি আমার অ্যাসাইনমেন্ট শেষ করতে চাই।", slotValues: { ACTION: "finish my assignment early" }, topicArea: "education" },
        { en: "I want to take a vacation soon.", bn: "আমি শীঘ্রই ছুটি নিতে চাই।", slotValues: { ACTION: "take a vacation soon" }, topicArea: "travel" },
        { en: "I want to change my job.", bn: "আমি আমার চাকরি বদলাতে চাই।", slotValues: { ACTION: "change my job" }, topicArea: "work" },
        { en: "I want to lose some weight.", bn: "আমি কিছুটা ওজন কমাতে চাই।", slotValues: { ACTION: "lose some weight" }, topicArea: "health" },
        { en: "I want to call my mother tonight.", bn: "আমি আজ রাতে আমার মাকে ফোন করতে চাই।", slotValues: { ACTION: "call my mother tonight" }, topicArea: "relationships" },
        { en: "I want to return this shirt.", bn: "আমি এই শার্টটি ফেরত দিতে চাই।", slotValues: { ACTION: "return this shirt" }, topicArea: "shopping" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Want' is always followed by an infinitive (to + verb), never a gerund. 'I want going' is incorrect.",
      usageNote_bn:
        "'Want' এর পরে সবসময় ইনফিনিটিভ (to + verb) আসে, কখনো জেরান্ড নয়। 'I want going' ভুল।",
    },
    {
      id: "C13.3",
      formula: "I stopped [DOING]",
      formula_bn: "আমি [কাজ করা] বন্ধ করেছি",
      patternName: "Stop + Gerund (Quit Activity)",
      patternName_bn: "Stop + জেরান্ড (কার্যকলাপ বন্ধ করা)",
      slots: [
        {
          name: "DOING",
          description: "A verb in -ing form describing the activity you stopped",
          description_bn: "একটি -ing রূপের ক্রিয়া যা আপনি বন্ধ করেছেন",
          acceptedTypes: ["gerund"],
          examples: ["smoking", "eating junk food", "watching TV late"],
        },
      ],
      examples: [
        { en: "I stopped smoking last year.", bn: "আমি গত বছর ধূমপান বন্ধ করেছি।", slotValues: { DOING: "smoking last year" }, topicArea: "health" },
        { en: "I stopped eating junk food.", bn: "আমি জাঙ্ক ফুড খাওয়া বন্ধ করেছি।", slotValues: { DOING: "eating junk food" }, topicArea: "food" },
        { en: "I stopped watching TV late at night.", bn: "আমি রাত জেগে টিভি দেখা বন্ধ করেছি।", slotValues: { DOING: "watching TV late at night" }, topicArea: "daily_life" },
        { en: "I stopped going to that gym.", bn: "আমি ওই জিমে যাওয়া বন্ধ করেছি।", slotValues: { DOING: "going to that gym" }, topicArea: "health" },
        { en: "I stopped buying things online impulsively.", bn: "আমি তাড়াহুড়ো করে অনলাইনে জিনিস কেনা বন্ধ করেছি।", slotValues: { DOING: "buying things online impulsively" }, topicArea: "shopping" },
        { en: "I stopped talking to him after the argument.", bn: "আমি ঝগড়ার পর তার সাথে কথা বলা বন্ধ করেছি।", slotValues: { DOING: "talking to him after the argument" }, topicArea: "relationships" },
        { en: "I stopped working overtime.", bn: "আমি ওভারটাইম কাজ করা বন্ধ করেছি।", slotValues: { DOING: "working overtime" }, topicArea: "work" },
        { en: "I stopped drinking coffee after 6 PM.", bn: "আমি সন্ধ্যা ৬টার পর কফি পান করা বন্ধ করেছি।", slotValues: { DOING: "drinking coffee after 6 PM" }, topicArea: "food" },
        { en: "I stopped taking that bus route.", bn: "আমি ওই বাস রুটে যাওয়া বন্ধ করেছি।", slotValues: { DOING: "taking that bus route" }, topicArea: "travel" },
        { en: "I stopped skipping my classes.", bn: "আমি ক্লাস ফাঁকি দেওয়া বন্ধ করেছি।", slotValues: { DOING: "skipping my classes" }, topicArea: "education" },
        { en: "I stopped using social media so much.", bn: "আমি এত বেশি সোশ্যাল মিডিয়া ব্যবহার করা বন্ধ করেছি।", slotValues: { DOING: "using social media so much" }, topicArea: "daily_life" },
        { en: "I stopped complaining about the workload.", bn: "আমি কাজের চাপ নিয়ে অভিযোগ করা বন্ধ করেছি।", slotValues: { DOING: "complaining about the workload" }, topicArea: "work" },
        { en: "I stopped visiting that restaurant.", bn: "আমি ওই রেস্তোরাঁয় যাওয়া বন্ধ করেছি।", slotValues: { DOING: "visiting that restaurant" }, topicArea: "travel" },
        { en: "I stopped lending money to people.", bn: "আমি মানুষকে টাকা ধার দেওয়া বন্ধ করেছি।", slotValues: { DOING: "lending money to people" }, topicArea: "relationships" },
        { en: "I stopped procrastinating on my homework.", bn: "আমি হোমওয়ার্কে গড়িমসি করা বন্ধ করেছি।", slotValues: { DOING: "procrastinating on my homework" }, topicArea: "education" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Stop + gerund' means you quit doing an activity. Compare with 'stop to do' which means you paused in order to do something else.",
      usageNote_bn:
        "'Stop + gerund' মানে আপনি একটি কার্যকলাপ বন্ধ করেছেন। তুলনা করুন 'stop to do' এর সাথে যার অর্থ আপনি অন্য কিছু করার জন্য থামলেন।",
    },
    {
      id: "C13.4",
      formula: "I forgot to [ACTION]",
      formula_bn: "আমি [কাজ] করতে ভুলে গেছি",
      patternName: "Forget + Infinitive (Didn't Do)",
      patternName_bn: "Forget + ইনফিনিটিভ (করিনি)",
      slots: [
        {
          name: "ACTION",
          description: "A base verb describing what you failed to do",
          description_bn: "আপনি যা করতে ভুলে গেছেন তার জন্য একটি মূল ক্রিয়া",
          acceptedTypes: ["verb"],
          examples: ["lock the door", "call her", "bring my umbrella"],
        },
      ],
      examples: [
        { en: "I forgot to lock the door.", bn: "আমি দরজা বন্ধ করতে ভুলে গেছি।", slotValues: { ACTION: "lock the door" }, topicArea: "daily_life" },
        { en: "I forgot to call her on her birthday.", bn: "আমি তার জন্মদিনে ফোন করতে ভুলে গেছি।", slotValues: { ACTION: "call her on her birthday" }, topicArea: "relationships" },
        { en: "I forgot to bring my umbrella.", bn: "আমি ছাতা আনতে ভুলে গেছি।", slotValues: { ACTION: "bring my umbrella" }, topicArea: "daily_life" },
        { en: "I forgot to submit my assignment.", bn: "আমি অ্যাসাইনমেন্ট জমা দিতে ভুলে গেছি।", slotValues: { ACTION: "submit my assignment" }, topicArea: "education" },
        { en: "I forgot to take my medicine.", bn: "আমি ওষুধ খেতে ভুলে গেছি।", slotValues: { ACTION: "take my medicine" }, topicArea: "health" },
        { en: "I forgot to reply to the email.", bn: "আমি ইমেইলের উত্তর দিতে ভুলে গেছি।", slotValues: { ACTION: "reply to the email" }, topicArea: "work" },
        { en: "I forgot to buy milk.", bn: "আমি দুধ কিনতে ভুলে গেছি।", slotValues: { ACTION: "buy milk" }, topicArea: "shopping" },
        { en: "I forgot to turn off the stove.", bn: "আমি চুলা বন্ধ করতে ভুলে গেছি।", slotValues: { ACTION: "turn off the stove" }, topicArea: "food" },
        { en: "I forgot to book the hotel.", bn: "আমি হোটেল বুক করতে ভুলে গেছি।", slotValues: { ACTION: "book the hotel" }, topicArea: "travel" },
        { en: "I forgot to charge my phone.", bn: "আমি ফোন চার্জ দিতে ভুলে গেছি।", slotValues: { ACTION: "charge my phone" }, topicArea: "daily_life" },
        { en: "I forgot to wish him good luck.", bn: "আমি তাকে শুভকামনা জানাতে ভুলে গেছি।", slotValues: { ACTION: "wish him good luck" }, topicArea: "relationships" },
        { en: "I forgot to save the document.", bn: "আমি ডকুমেন্ট সেভ করতে ভুলে গেছি।", slotValues: { ACTION: "save the document" }, topicArea: "work" },
        { en: "I forgot to pack my toothbrush.", bn: "আমি টুথব্রাশ প্যাক করতে ভুলে গেছি।", slotValues: { ACTION: "pack my toothbrush" }, topicArea: "travel" },
        { en: "I forgot to return the library book.", bn: "আমি লাইব্রেরির বই ফেরত দিতে ভুলে গেছি।", slotValues: { ACTION: "return the library book" }, topicArea: "education" },
        { en: "I forgot to set my alarm.", bn: "আমি অ্যালার্ম সেট করতে ভুলে গেছি।", slotValues: { ACTION: "set my alarm" }, topicArea: "health" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Forget to do' means you didn't do it because you didn't remember. Compare with 'forget doing' which means you don't remember a past action.",
      usageNote_bn:
        "'Forget to do' মানে আপনি মনে না থাকায় করেননি। তুলনা করুন 'forget doing' এর সাথে যার অর্থ আপনি অতীতের একটি কাজ মনে করতে পারছেন না।",
    },
    {
      id: "C13.5",
      formula: "I remember [DOING]",
      formula_bn: "আমি [কাজ করার] কথা মনে আছে",
      patternName: "Remember + Gerund (Past Memory)",
      patternName_bn: "Remember + জেরান্ড (অতীত স্মৃতি)",
      slots: [
        {
          name: "DOING",
          description: "A verb in -ing form describing the past activity you remember",
          description_bn: "একটি -ing রূপের ক্রিয়া যা অতীতে করেছেন এবং মনে আছে",
          acceptedTypes: ["gerund"],
          examples: ["meeting her", "playing in the rain", "visiting that place"],
        },
      ],
      examples: [
        { en: "I remember meeting her for the first time.", bn: "আমি তার সাথে প্রথম দেখা হওয়ার কথা মনে আছে।", slotValues: { DOING: "meeting her for the first time" }, topicArea: "relationships" },
        { en: "I remember playing in the rain as a child.", bn: "আমি ছোটবেলায় বৃষ্টিতে খেলার কথা মনে আছে।", slotValues: { DOING: "playing in the rain as a child" }, topicArea: "daily_life" },
        { en: "I remember visiting that temple in Kyoto.", bn: "আমি কিয়োটোর ওই মন্দির দেখতে যাওয়ার কথা মনে আছে।", slotValues: { DOING: "visiting that temple in Kyoto" }, topicArea: "travel" },
        { en: "I remember eating the best biryani there.", bn: "আমি সেখানে সেরা বিরিয়ানি খাওয়ার কথা মনে আছে।", slotValues: { DOING: "eating the best biryani there" }, topicArea: "food" },
        { en: "I remember studying all night before the exam.", bn: "আমি পরীক্ষার আগে সারারাত পড়ার কথা মনে আছে।", slotValues: { DOING: "studying all night before the exam" }, topicArea: "education" },
        { en: "I remember locking the door this morning.", bn: "আমি আজ সকালে দরজা বন্ধ করার কথা মনে আছে।", slotValues: { DOING: "locking the door this morning" }, topicArea: "daily_life" },
        { en: "I remember working at that company years ago.", bn: "আমি বছর আগে ওই কোম্পানিতে কাজ করার কথা মনে আছে।", slotValues: { DOING: "working at that company years ago" }, topicArea: "work" },
        { en: "I remember buying this jacket on sale.", bn: "আমি এই জ্যাকেটটা সেলে কেনার কথা মনে আছে।", slotValues: { DOING: "buying this jacket on sale" }, topicArea: "shopping" },
        { en: "I remember feeling nervous on my first day.", bn: "আমি প্রথম দিনে নার্ভাস লাগার কথা মনে আছে।", slotValues: { DOING: "feeling nervous on my first day" }, topicArea: "work" },
        { en: "I remember running my first marathon.", bn: "আমি আমার প্রথম ম্যারাথন দৌড়ানোর কথা মনে আছে।", slotValues: { DOING: "running my first marathon" }, topicArea: "health" },
        { en: "I remember telling him the truth.", bn: "আমি তাকে সত্যি কথা বলার কথা মনে আছে।", slotValues: { DOING: "telling him the truth" }, topicArea: "relationships" },
        { en: "I remember taking that flight to Dubai.", bn: "আমি দুবাইয়ের ওই ফ্লাইট নেওয়ার কথা মনে আছে।", slotValues: { DOING: "taking that flight to Dubai" }, topicArea: "travel" },
        { en: "I remember cooking for twenty people at the party.", bn: "আমি পার্টিতে বিশ জনের জন্য রান্না করার কথা মনে আছে।", slotValues: { DOING: "cooking for twenty people at the party" }, topicArea: "food" },
        { en: "I remember reading that book in college.", bn: "আমি কলেজে ওই বই পড়ার কথা মনে আছে।", slotValues: { DOING: "reading that book in college" }, topicArea: "education" },
        { en: "I remember ordering that dress online.", bn: "আমি অনলাইনে ওই ড্রেস অর্ডার করার কথা মনে আছে।", slotValues: { DOING: "ordering that dress online" }, topicArea: "shopping" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Remember + gerund' means you have a memory of something you did in the past. Compare with 'remember to do' which means you didn't forget to do a task.",
      usageNote_bn:
        "'Remember + gerund' মানে অতীতে কিছু করার স্মৃতি আছে। তুলনা করুন 'remember to do' এর সাথে যার অর্থ আপনি একটি কাজ করতে ভোলেননি।",
    },
    {
      id: "C13.6",
      formula: "I stopped to [ACTION]",
      formula_bn: "আমি [কাজ] করতে থামলাম",
      patternName: "Stop + Infinitive (Pause to Do)",
      patternName_bn: "Stop + ইনফিনিটিভ (করার জন্য থামা)",
      slots: [
        {
          name: "ACTION",
          description: "A base verb describing what you paused to do",
          description_bn: "আপনি যা করতে থামলেন তার জন্য একটি মূল ক্রিয়া",
          acceptedTypes: ["verb"],
          examples: ["rest", "check my phone", "ask for directions"],
        },
      ],
      examples: [
        { en: "I stopped to rest.", bn: "আমি বিশ্রাম নিতে থামলাম।", slotValues: { ACTION: "rest" }, topicArea: "health" },
        { en: "I stopped to check my phone.", bn: "আমি ফোন চেক করতে থামলাম।", slotValues: { ACTION: "check my phone" }, topicArea: "daily_life" },
        { en: "I stopped to ask for directions.", bn: "আমি পথ জিজ্ঞেস করতে থামলাম।", slotValues: { ACTION: "ask for directions" }, topicArea: "travel" },
        { en: "She stopped to tie her shoe.", bn: "সে জুতার ফিতা বাঁধতে থামল।", slotValues: { ACTION: "tie her shoe" }, topicArea: "daily_life" },
        { en: "We stopped to get some water.", bn: "আমরা পানি নিতে থামলাম।", slotValues: { ACTION: "get some water" }, topicArea: "health" },
        { en: "He stopped to read the sign.", bn: "সে সাইনবোর্ড পড়তে থামল।", slotValues: { ACTION: "read the sign" }, topicArea: "travel" },
        { en: "I stopped to think about it.", bn: "আমি এটা নিয়ে ভাবতে থামলাম।", slotValues: { ACTION: "think about it" }, topicArea: "daily_life" },
        { en: "They stopped to take a photo.", bn: "তারা ছবি তুলতে থামল।", slotValues: { ACTION: "take a photo" }, topicArea: "travel" },
        { en: "I stopped to say hello.", bn: "আমি হ্যালো বলতে থামলাম।", slotValues: { ACTION: "say hello" }, topicArea: "relationships" },
        { en: "She stopped to buy some fruit.", bn: "সে কিছু ফল কিনতে থামল।", slotValues: { ACTION: "buy some fruit" }, topicArea: "shopping" },
        { en: "We stopped to look at the view.", bn: "আমরা দৃশ্য দেখতে থামলাম।", slotValues: { ACTION: "look at the view" }, topicArea: "travel" },
        { en: "He stopped to answer the phone.", bn: "সে ফোন ধরতে থামল।", slotValues: { ACTION: "answer the phone" }, topicArea: "work" },
        { en: "I stopped to pick up something.", bn: "আমি কিছু তুলতে থামলাম।", slotValues: { ACTION: "pick up something" }, topicArea: "daily_life" },
        { en: "They stopped to have lunch.", bn: "তারা দুপুরের খাবার খেতে থামল।", slotValues: { ACTION: "have lunch" }, topicArea: "food" },
        { en: "She stopped to catch her breath.", bn: "সে নিঃশ্বাস নিতে থামল।", slotValues: { ACTION: "catch her breath" }, topicArea: "health" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Stop to do' means you pause what you are doing in order to do something else. Contrasts with 'stop doing' which means you quit the activity.",
      usageNote_bn:
        "'Stop to do' মানে আপনি অন্য কিছু করার জন্য যা করছিলেন তা থামালেন। এটি 'stop doing' থেকে আলাদা যার অর্থ আপনি কার্যকলাপটি বন্ধ করলেন।",
    },
    {
      id: "C13.7",
      formula: "I remember to [ACTION]",
      formula_bn: "আমি [কাজ] করতে মনে রাখি",
      patternName: "Remember + Infinitive (Not Forget)",
      patternName_bn: "Remember + ইনফিনিটিভ (ভুলে না যাওয়া)",
      slots: [
        {
          name: "ACTION",
          description: "A base verb describing the task you don't forget to do",
          description_bn: "আপনি যা করতে ভোলেন না তার জন্য একটি মূল ক্রিয়া",
          acceptedTypes: ["verb"],
          examples: ["lock the door", "take your medicine", "bring your ID"],
        },
      ],
      examples: [
        { en: "I always remember to lock the door.", bn: "আমি সবসময় দরজা বন্ধ করতে মনে রাখি।", slotValues: { ACTION: "lock the door" }, topicArea: "daily_life" },
        { en: "Remember to take your medicine.", bn: "ওষুধ খেতে মনে রাখবে।", slotValues: { ACTION: "take your medicine" }, topicArea: "health" },
        { en: "I remembered to call my mother.", bn: "আমি আমার মাকে ফোন করতে মনে রেখেছিলাম।", slotValues: { ACTION: "call my mother" }, topicArea: "relationships" },
        { en: "Please remember to bring your ID.", bn: "দয়া করে আইডি আনতে মনে রাখবেন।", slotValues: { ACTION: "bring your ID" }, topicArea: "work" },
        { en: "She never remembers to charge her phone.", bn: "সে কখনো ফোন চার্জ দিতে মনে রাখে না।", slotValues: { ACTION: "charge her phone" }, topicArea: "daily_life" },
        { en: "Did you remember to buy milk?", bn: "তুমি কি দুধ কিনতে মনে রেখেছিলে?", slotValues: { ACTION: "buy milk" }, topicArea: "shopping" },
        { en: "I must remember to email the boss.", bn: "আমাকে বসকে ইমেইল করতে মনে রাখতে হবে।", slotValues: { ACTION: "email the boss" }, topicArea: "work" },
        { en: "He always remembers to say thank you.", bn: "সে সবসময় ধন্যবাদ বলতে মনে রাখে।", slotValues: { ACTION: "say thank you" }, topicArea: "relationships" },
        { en: "Remember to turn off the light.", bn: "বাতি বন্ধ করতে মনে রাখবে।", slotValues: { ACTION: "turn off the light" }, topicArea: "daily_life" },
        { en: "I forgot but then remembered to pay the bill.", bn: "আমি ভুলে গিয়েছিলাম কিন্তু পরে বিল দিতে মনে হয়েছিল।", slotValues: { ACTION: "pay the bill" }, topicArea: "shopping" },
        { en: "She remembered to set the alarm.", bn: "সে অ্যালার্ম সেট করতে মনে রেখেছিল।", slotValues: { ACTION: "set the alarm" }, topicArea: "daily_life" },
        { en: "Don't forget to remember to save the file.", bn: "ফাইল সেভ করতে ভুলো না।", slotValues: { ACTION: "save the file" }, topicArea: "work" },
        { en: "I need to remember to renew my passport.", bn: "আমাকে পাসপোর্ট নবায়ন করতে মনে রাখতে হবে।", slotValues: { ACTION: "renew my passport" }, topicArea: "travel" },
        { en: "He rarely remembers to water the plants.", bn: "সে খুব কমই গাছে পানি দিতে মনে রাখে।", slotValues: { ACTION: "water the plants" }, topicArea: "daily_life" },
        { en: "I remembered to bring an umbrella.", bn: "আমি ছাতা আনতে মনে রেখেছিলাম।", slotValues: { ACTION: "bring an umbrella" }, topicArea: "daily_life" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Remember to do' means you don't forget to do a task. Contrasts with 'remember doing' which means you have a memory of a past action.",
      usageNote_bn:
        "'Remember to do' মানে আপনি একটি কাজ করতে ভোলেননি। তুলনা করুন 'remember doing' এর সাথে যার অর্থ অতীতের একটি কাজের স্মৃতি আছে।",
    },
    {
      id: "C13.8",
      formula: "I look forward to [DOING]",
      formula_bn: "আমি [কাজ করার] জন্য অপেক্ষা করছি",
      patternName: "Look Forward To + Gerund",
      patternName_bn: "Look Forward To + জেরান্ড",
      slots: [
        {
          name: "DOING",
          description: "A verb in -ing form describing what you are excited about",
          description_bn: "একটি -ing রূপের ক্রিয়া যার জন্য আপনি উৎসুক",
          acceptedTypes: ["gerund"],
          examples: ["seeing you", "starting her new job", "hearing from you"],
        },
      ],
      examples: [
        { en: "I look forward to seeing you.", bn: "আমি তোমাকে দেখার অপেক্ষায় আছি।", slotValues: { DOING: "seeing you" }, topicArea: "relationships" },
        { en: "She looks forward to starting her new job.", bn: "সে তার নতুন চাকরি শুরু করার অপেক্ষায় আছে।", slotValues: { DOING: "starting her new job" }, topicArea: "work" },
        { en: "We look forward to hearing from you.", bn: "আমরা আপনার কাছ থেকে শোনার অপেক্ষায় আছি।", slotValues: { DOING: "hearing from you" }, topicArea: "work" },
        { en: "I'm looking forward to meeting everyone.", bn: "আমি সবার সাথে দেখা করার অপেক্ষায় আছি।", slotValues: { DOING: "meeting everyone" }, topicArea: "relationships" },
        { en: "He looks forward to retiring.", bn: "সে অবসর নেওয়ার অপেক্ষায় আছে।", slotValues: { DOING: "retiring" }, topicArea: "work" },
        { en: "I look forward to visiting Bangladesh.", bn: "আমি বাংলাদেশ ভ্রমণের অপেক্ষায় আছি।", slotValues: { DOING: "visiting Bangladesh" }, topicArea: "travel" },
        { en: "They look forward to celebrating Eid.", bn: "তারা ঈদ উদযাপনের অপেক্ষায় আছে।", slotValues: { DOING: "celebrating Eid" }, topicArea: "daily_life" },
        { en: "I'm looking forward to learning more.", bn: "আমি আরও শেখার অপেক্ষায় আছি।", slotValues: { DOING: "learning more" }, topicArea: "education" },
        { en: "We look forward to working together.", bn: "আমরা একসাথে কাজ করার অপেক্ষায় আছি।", slotValues: { DOING: "working together" }, topicArea: "work" },
        { en: "She's looking forward to graduating.", bn: "সে স্নাতক হওয়ার অপেক্ষায় আছে।", slotValues: { DOING: "graduating" }, topicArea: "education" },
        { en: "I look forward to spending time with family.", bn: "আমি পরিবারের সাথে সময় কাটানোর অপেক্ষায় আছি।", slotValues: { DOING: "spending time with family" }, topicArea: "relationships" },
        { en: "He's looking forward to the weekend.", bn: "সে সাপ্তাহিক ছুটির অপেক্ষায় আছে।", slotValues: { DOING: "the weekend" }, topicArea: "daily_life" },
        { en: "I look forward to trying the food.", bn: "আমি খাবার খেয়ে দেখার অপেক্ষায় আছি।", slotValues: { DOING: "trying the food" }, topicArea: "food" },
        { en: "We're looking forward to moving.", bn: "আমরা বাড়ি বদলানোর অপেক্ষায় আছি।", slotValues: { DOING: "moving" }, topicArea: "daily_life" },
        { en: "I look forward to receiving your reply.", bn: "আমি আপনার উত্তর পাওয়ার অপেক্ষায় আছি।", slotValues: { DOING: "receiving your reply" }, topicArea: "work" },
      ],
      formality: "formal",
      difficulty: "intermediate",
      usageNote:
        "'Look forward to' is always followed by a gerund (-ing form) or a noun, never an infinitive. 'I look forward to see you' is incorrect.",
      usageNote_bn:
        "'Look forward to' এর পরে সবসময় জেরান্ড (-ing রূপ) বা বিশেষ্য আসে, কখনো ইনফিনিটিভ নয়। 'I look forward to see you' ভুল।",
    },
    {
      id: "C13.9",
      formula: "I'm tired of [DOING]",
      formula_bn: "আমি [কাজ করতে] ক্লান্ত/বিরক্ত",
      patternName: "Tired Of + Gerund",
      patternName_bn: "Tired Of + জেরান্ড",
      slots: [
        {
          name: "DOING",
          description: "A verb in -ing form describing the activity you are fed up with",
          description_bn: "একটি -ing রূপের ক্রিয়া যা করতে আপনি ক্লান্ত বা বিরক্ত",
          acceptedTypes: ["gerund"],
          examples: ["waiting", "working overtime", "hearing excuses"],
        },
      ],
      examples: [
        { en: "I'm tired of waiting.", bn: "আমি অপেক্ষা করতে করতে ক্লান্ত।", slotValues: { DOING: "waiting" }, topicArea: "daily_life" },
        { en: "She's tired of working overtime.", bn: "সে ওভারটাইম কাজ করতে করতে ক্লান্ত।", slotValues: { DOING: "working overtime" }, topicArea: "work" },
        { en: "I'm tired of hearing excuses.", bn: "আমি অজুহাত শুনতে শুনতে বিরক্ত।", slotValues: { DOING: "hearing excuses" }, topicArea: "relationships" },
        { en: "He's tired of eating the same food.", bn: "সে একই খাবার খেতে খেতে বিরক্ত।", slotValues: { DOING: "eating the same food" }, topicArea: "food" },
        { en: "I'm tired of being stuck in traffic.", bn: "আমি ট্রাফিকে আটকে থাকতে থাকতে ক্লান্ত।", slotValues: { DOING: "being stuck in traffic" }, topicArea: "travel" },
        { en: "We're tired of dealing with this problem.", bn: "আমরা এই সমস্যা নিয়ে কাজ করতে করতে ক্লান্ত।", slotValues: { DOING: "dealing with this problem" }, topicArea: "work" },
        { en: "I'm tired of studying all day.", bn: "আমি সারাদিন পড়তে পড়তে ক্লান্ত।", slotValues: { DOING: "studying all day" }, topicArea: "education" },
        { en: "She's tired of explaining the same thing.", bn: "সে একই জিনিস ব্যাখ্যা করতে করতে ক্লান্ত।", slotValues: { DOING: "explaining the same thing" }, topicArea: "work" },
        { en: "I'm tired of waking up early.", bn: "আমি ভোরে উঠতে উঠতে ক্লান্ত।", slotValues: { DOING: "waking up early" }, topicArea: "daily_life" },
        { en: "He's tired of living alone.", bn: "সে একা থাকতে থাকতে ক্লান্ত।", slotValues: { DOING: "living alone" }, topicArea: "daily_life" },
        { en: "I'm tired of worrying about money.", bn: "আমি টাকা নিয়ে চিন্তা করতে করতে ক্লান্ত।", slotValues: { DOING: "worrying about money" }, topicArea: "shopping" },
        { en: "They're tired of arguing.", bn: "তারা তর্ক করতে করতে ক্লান্ত।", slotValues: { DOING: "arguing" }, topicArea: "relationships" },
        { en: "I'm tired of repeating myself.", bn: "আমি বারবার একই কথা বলতে বলতে ক্লান্ত।", slotValues: { DOING: "repeating myself" }, topicArea: "relationships" },
        { en: "She's tired of cooking every day.", bn: "সে প্রতিদিন রান্না করতে করতে ক্লান্ত।", slotValues: { DOING: "cooking every day" }, topicArea: "food" },
        { en: "I'm tired of missing my family.", bn: "আমি পরিবারকে মিস করতে করতে ক্লান্ত।", slotValues: { DOING: "missing my family" }, topicArea: "relationships" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Tired of' is always followed by a gerund (-ing form) or a noun. It expresses frustration or boredom with a repeated activity.",
      usageNote_bn:
        "'Tired of' এর পরে সবসময় জেরান্ড (-ing রূপ) বা বিশেষ্য আসে। এটি পুনরাবৃত্ত কার্যকলাপে হতাশা বা বিরক্তি প্রকাশ করে।",
    },
  ],
};
