import { PatternCategory } from "@/types/pattern";

export const categoryC14: PatternCategory = {
  id: "C14",
  slug: "phrasal-verbs",
  name: "Phrasal Verb Patterns",
  name_bn: "ফ্রেজাল ভার্ব প্যাটার্ন",
  description:
    "Learn common phrasal verbs that combine a verb with a preposition or adverb to create new meanings.",
  description_bn:
    "সাধারণ ফ্রেজাল ভার্ব শিখুন যেখানে একটি ক্রিয়ার সাথে একটি পদান্বয়ী অব্যয় বা ক্রিয়াবিশেষণ যুক্ত হয়ে নতুন অর্থ তৈরি করে।",
  icon: "🧩",
  group: "C",
  groupName: "Actions & Time Patterns",
  groupName_bn: "কর্ম ও সময় প্যাটার্ন",
  difficulty: "intermediate",
  patterns: [
    {
      id: "C14.1",
      formula: "I picked up [THING]",
      formula_bn: "আমি [জিনিস] তুলে নিয়েছি / শিখেছি",
      patternName: "Pick Up (Collect/Learn)",
      patternName_bn: "Pick Up (সংগ্রহ করা/শেখা)",
      slots: [
        {
          name: "THING",
          description: "A noun or noun phrase for what you picked up or learned",
          description_bn: "যা আপনি তুলেছেন বা শিখেছেন তার জন্য একটি বিশেষ্য",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["some groceries", "a few words of Spanish", "the kids"],
        },
      ],
      examples: [
        { en: "I picked up some groceries on the way home.", bn: "আমি বাড়ি ফেরার পথে কিছু মুদি জিনিস তুলে এনেছি।", slotValues: { THING: "some groceries" }, topicArea: "shopping" },
        { en: "I picked up a few words of Spanish during my trip.", bn: "আমি ভ্রমণের সময় কয়েকটা স্প্যানিশ শব্দ শিখেছি।", slotValues: { THING: "a few words of Spanish" }, topicArea: "travel" },
        { en: "I picked up the kids from school.", bn: "আমি বাচ্চাদের স্কুল থেকে তুলে এনেছি।", slotValues: { THING: "the kids from school" }, topicArea: "relationships" },
        { en: "I picked up a new hobby during lockdown.", bn: "আমি লকডাউনের সময় একটা নতুন শখ শিখেছি।", slotValues: { THING: "a new hobby" }, topicArea: "daily_life" },
        { en: "I picked up some cooking tips from the chef.", bn: "আমি শেফের কাছ থেকে কিছু রান্নার টিপস শিখেছি।", slotValues: { THING: "some cooking tips" }, topicArea: "food" },
        { en: "I picked up my prescription from the pharmacy.", bn: "আমি ফার্মেসি থেকে আমার প্রেসক্রিপশন তুলে এনেছি।", slotValues: { THING: "my prescription" }, topicArea: "health" },
        { en: "I picked up some useful skills at the workshop.", bn: "আমি ওয়ার্কশপে কিছু দরকারি দক্ষতা শিখেছি।", slotValues: { THING: "some useful skills" }, topicArea: "work" },
        { en: "I picked up a few books from the library.", bn: "আমি লাইব্রেরি থেকে কয়েকটা বই তুলে এনেছি।", slotValues: { THING: "a few books" }, topicArea: "education" },
        { en: "I picked up some souvenirs for my family.", bn: "আমি পরিবারের জন্য কিছু স্মারক কিনেছি।", slotValues: { THING: "some souvenirs" }, topicArea: "travel" },
        { en: "I picked up the dry cleaning yesterday.", bn: "আমি গতকাল ড্রাই ক্লিনিং তুলে এনেছি।", slotValues: { THING: "the dry cleaning" }, topicArea: "daily_life" },
        { en: "I picked up lunch for the whole team.", bn: "আমি পুরো দলের জন্য দুপুরের খাবার তুলে এনেছি।", slotValues: { THING: "lunch for the whole team" }, topicArea: "work" },
        { en: "I picked up a cold from someone at the office.", bn: "আমি অফিসে কারো থেকে সর্দি লাগিয়েছি।", slotValues: { THING: "a cold" }, topicArea: "health" },
        { en: "I picked up some great bargains at the sale.", bn: "আমি সেলে কিছু দারুণ সস্তা জিনিস পেয়েছি।", slotValues: { THING: "some great bargains" }, topicArea: "shopping" },
        { en: "I picked up guitar during college.", bn: "আমি কলেজে গিটার শিখেছি।", slotValues: { THING: "guitar" }, topicArea: "education" },
        { en: "I picked up a gift for my friend's birthday.", bn: "আমি আমার বন্ধুর জন্মদিনের জন্য একটা উপহার কিনেছি।", slotValues: { THING: "a gift for my friend's birthday" }, topicArea: "relationships" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Pick up' can mean to physically collect something, to learn something informally, or to catch an illness. Context determines the meaning.",
      usageNote_bn:
        "'Pick up' অর্থ হতে পারে কিছু শারীরিকভাবে সংগ্রহ করা, অনানুষ্ঠানিকভাবে কিছু শেখা, বা অসুখ লাগানো। প্রসঙ্গ অর্থ নির্ধারণ করে।",
    },
    {
      id: "C14.2",
      formula: "I looked for [THING]",
      formula_bn: "আমি [জিনিস] খুঁজেছি",
      patternName: "Look For (Search)",
      patternName_bn: "Look For (খোঁজা)",
      slots: [
        {
          name: "THING",
          description: "A noun or noun phrase for what you searched for",
          description_bn: "যা আপনি খুঁজেছেন তার জন্য একটি বিশেষ্য",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["my keys", "a new apartment", "a good restaurant"],
        },
      ],
      examples: [
        { en: "I looked for my keys everywhere.", bn: "আমি সব জায়গায় আমার চাবি খুঁজেছি।", slotValues: { THING: "my keys" }, topicArea: "daily_life" },
        { en: "I looked for a new apartment last month.", bn: "আমি গত মাসে নতুন অ্যাপার্টমেন্ট খুঁজেছি।", slotValues: { THING: "a new apartment" }, topicArea: "daily_life" },
        { en: "I looked for a good restaurant nearby.", bn: "আমি আশেপাশে একটা ভালো রেস্তোরাঁ খুঁজেছি।", slotValues: { THING: "a good restaurant" }, topicArea: "food" },
        { en: "I looked for a new job for three months.", bn: "আমি তিন মাস ধরে নতুন চাকরি খুঁজেছি।", slotValues: { THING: "a new job" }, topicArea: "work" },
        { en: "I looked for my passport before the trip.", bn: "আমি ভ্রমণের আগে পাসপোর্ট খুঁজেছি।", slotValues: { THING: "my passport" }, topicArea: "travel" },
        { en: "I looked for the book in three different shops.", bn: "আমি তিনটা আলাদা দোকানে বইটা খুঁজেছি।", slotValues: { THING: "the book" }, topicArea: "shopping" },
        { en: "I looked for information about the course.", bn: "আমি কোর্স সম্পর্কে তথ্য খুঁজেছি।", slotValues: { THING: "information about the course" }, topicArea: "education" },
        { en: "I looked for a good doctor in the area.", bn: "আমি এলাকায় একজন ভালো ডাক্তার খুঁজেছি।", slotValues: { THING: "a good doctor" }, topicArea: "health" },
        { en: "I looked for my old friend on social media.", bn: "আমি সোশ্যাল মিডিয়ায় আমার পুরোনো বন্ধুকে খুঁজেছি।", slotValues: { THING: "my old friend" }, topicArea: "relationships" },
        { en: "I looked for a recipe for chicken curry.", bn: "আমি চিকেন কারির রেসিপি খুঁজেছি।", slotValues: { THING: "a recipe for chicken curry" }, topicArea: "food" },
        { en: "I looked for a cheap flight to Bangkok.", bn: "আমি ব্যাংককের সস্তা ফ্লাইট খুঁজেছি।", slotValues: { THING: "a cheap flight to Bangkok" }, topicArea: "travel" },
        { en: "I looked for my phone for almost an hour.", bn: "আমি প্রায় এক ঘন্টা ধরে আমার ফোন খুঁজেছি।", slotValues: { THING: "my phone" }, topicArea: "daily_life" },
        { en: "I looked for the missing file all day.", bn: "আমি সারাদিন হারানো ফাইলটি খুঁজেছি।", slotValues: { THING: "the missing file" }, topicArea: "work" },
        { en: "I looked for a birthday gift for my sister.", bn: "আমি আমার বোনের জন্য জন্মদিনের উপহার খুঁজেছি।", slotValues: { THING: "a birthday gift for my sister" }, topicArea: "shopping" },
        { en: "I looked for a study guide for the exam.", bn: "আমি পরীক্ষার জন্য স্টাডি গাইড খুঁজেছি।", slotValues: { THING: "a study guide for the exam" }, topicArea: "education" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Look for' means to search or try to find something. It is different from 'look at' (to see) or 'look after' (to take care of).",
      usageNote_bn:
        "'Look for' অর্থ কিছু খোঁজা বা খুঁজে বের করার চেষ্টা করা। এটি 'look at' (দেখা) বা 'look after' (যত্ন নেওয়া) থেকে আলাদা।",
    },
    {
      id: "C14.3",
      formula: "I gave up [DOING]",
      formula_bn: "আমি [কাজ করা] ছেড়ে দিয়েছি",
      patternName: "Give Up (Quit/Stop Trying)",
      patternName_bn: "Give Up (ছেড়ে দেওয়া/চেষ্টা বন্ধ করা)",
      slots: [
        {
          name: "DOING",
          description: "A verb in -ing form describing what you quit or stopped trying",
          description_bn: "একটি -ing রূপের ক্রিয়া যা আপনি ছেড়ে দিয়েছেন বা চেষ্টা বন্ধ করেছেন",
          acceptedTypes: ["gerund"],
          examples: ["smoking", "trying to fix it", "learning French"],
        },
      ],
      examples: [
        { en: "I gave up smoking two years ago.", bn: "আমি দুই বছর আগে ধূমপান ছেড়ে দিয়েছি।", slotValues: { DOING: "smoking" }, topicArea: "health" },
        { en: "I gave up trying to fix the old computer.", bn: "আমি পুরোনো কম্পিউটার ঠিক করার চেষ্টা ছেড়ে দিয়েছি।", slotValues: { DOING: "trying to fix the old computer" }, topicArea: "daily_life" },
        { en: "I gave up learning French after a year.", bn: "আমি এক বছর পর ফরাসি শেখা ছেড়ে দিয়েছি।", slotValues: { DOING: "learning French" }, topicArea: "education" },
        { en: "I gave up eating sugar completely.", bn: "আমি সম্পূর্ণভাবে চিনি খাওয়া ছেড়ে দিয়েছি।", slotValues: { DOING: "eating sugar" }, topicArea: "food" },
        { en: "I gave up waiting for the bus and took a taxi.", bn: "আমি বাসের জন্য অপেক্ষা ছেড়ে দিয়ে ট্যাক্সি নিয়েছি।", slotValues: { DOING: "waiting for the bus" }, topicArea: "travel" },
        { en: "I gave up looking for the perfect job.", bn: "আমি নিখুঁত চাকরি খোঁজা ছেড়ে দিয়েছি।", slotValues: { DOING: "looking for the perfect job" }, topicArea: "work" },
        { en: "I gave up convincing him to come.", bn: "আমি তাকে আসতে রাজি করানো ছেড়ে দিয়েছি।", slotValues: { DOING: "convincing him to come" }, topicArea: "relationships" },
        { en: "I gave up searching for a discount.", bn: "আমি ছাড় খোঁজা ছেড়ে দিয়েছি।", slotValues: { DOING: "searching for a discount" }, topicArea: "shopping" },
        { en: "I gave up running because of my knee pain.", bn: "আমি হাঁটুর ব্যথার কারণে দৌড়ানো ছেড়ে দিয়েছি।", slotValues: { DOING: "running" }, topicArea: "health" },
        { en: "I gave up trying to cook Thai food at home.", bn: "আমি বাড়িতে থাই খাবার রান্নার চেষ্টা ছেড়ে দিয়েছি।", slotValues: { DOING: "trying to cook Thai food at home" }, topicArea: "food" },
        { en: "I gave up applying to that company.", bn: "আমি ওই কোম্পানিতে আবেদন করা ছেড়ে দিয়েছি।", slotValues: { DOING: "applying to that company" }, topicArea: "work" },
        { en: "I gave up arguing with my brother.", bn: "আমি আমার ভাইয়ের সাথে তর্ক করা ছেড়ে দিয়েছি।", slotValues: { DOING: "arguing with my brother" }, topicArea: "relationships" },
        { en: "I gave up staying up late on weeknights.", bn: "আমি কাজের দিনের রাতে জেগে থাকা ছেড়ে দিয়েছি।", slotValues: { DOING: "staying up late on weeknights" }, topicArea: "daily_life" },
        { en: "I gave up planning the trip myself.", bn: "আমি নিজে ভ্রমণ পরিকল্পনা করা ছেড়ে দিয়েছি।", slotValues: { DOING: "planning the trip myself" }, topicArea: "travel" },
        { en: "I gave up studying for the exam at midnight.", bn: "আমি মধ্যরাতে পরীক্ষার জন্য পড়া ছেড়ে দিয়েছি।", slotValues: { DOING: "studying for the exam" }, topicArea: "education" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Give up' means to quit or stop doing something, usually because it's too difficult. It's followed by a gerund or a noun.",
      usageNote_bn:
        "'Give up' অর্থ কিছু ছেড়ে দেওয়া বা বন্ধ করা, সাধারণত কারণ এটি খুব কঠিন। এর পরে জেরান্ড বা বিশেষ্য আসে।",
    },
    {
      id: "C14.4",
      formula: "I ran into [PERSON]",
      formula_bn: "আমি [ব্যক্তি]-র সাথে হঠাৎ দেখা হয়ে গেল",
      patternName: "Run Into (Meet Unexpectedly)",
      patternName_bn: "Run Into (অপ্রত্যাশিতভাবে দেখা হওয়া)",
      slots: [
        {
          name: "PERSON",
          description: "The person you met by chance",
          description_bn: "যে ব্যক্তির সাথে আকস্মিকভাবে দেখা হয়েছে",
          acceptedTypes: ["person"],
          examples: ["my old teacher", "an old friend", "my neighbor"],
        },
      ],
      examples: [
        { en: "I ran into my old teacher at the supermarket.", bn: "আমি সুপারমার্কেটে আমার পুরোনো শিক্ষকের সাথে হঠাৎ দেখা হয়ে গেল।", slotValues: { PERSON: "my old teacher" }, topicArea: "education" },
        { en: "I ran into an old friend at the airport.", bn: "আমি বিমানবন্দরে একজন পুরোনো বন্ধুর সাথে হঠাৎ দেখা হয়ে গেল।", slotValues: { PERSON: "an old friend" }, topicArea: "travel" },
        { en: "I ran into my neighbor at the grocery store.", bn: "আমি মুদি দোকানে আমার প্রতিবেশীর সাথে হঠাৎ দেখা হয়ে গেল।", slotValues: { PERSON: "my neighbor" }, topicArea: "shopping" },
        { en: "I ran into my cousin at the hospital.", bn: "আমি হাসপাতালে আমার কাজিনের সাথে হঠাৎ দেখা হয়ে গেল।", slotValues: { PERSON: "my cousin" }, topicArea: "health" },
        { en: "I ran into my boss at the restaurant.", bn: "আমি রেস্তোরাঁয় আমার বসের সাথে হঠাৎ দেখা হয়ে গেল।", slotValues: { PERSON: "my boss" }, topicArea: "food" },
        { en: "I ran into my ex-colleague at the conference.", bn: "আমি কনফারেন্সে আমার প্রাক্তন সহকর্মীর সাথে হঠাৎ দেখা হয়ে গেল।", slotValues: { PERSON: "my ex-colleague" }, topicArea: "work" },
        { en: "I ran into my childhood friend at the park.", bn: "আমি পার্কে আমার শৈশবের বন্ধুর সাথে হঠাৎ দেখা হয়ে গেল।", slotValues: { PERSON: "my childhood friend" }, topicArea: "relationships" },
        { en: "I ran into my uncle at the train station.", bn: "আমি ট্রেন স্টেশনে আমার চাচার সাথে হঠাৎ দেখা হয়ে গেল।", slotValues: { PERSON: "my uncle" }, topicArea: "travel" },
        { en: "I ran into a classmate at the bookstore.", bn: "আমি বইয়ের দোকানে একজন সহপাঠীর সাথে হঠাৎ দেখা হয়ে গেল।", slotValues: { PERSON: "a classmate" }, topicArea: "education" },
        { en: "I ran into my dentist at the shopping mall.", bn: "আমি শপিং মলে আমার ডেন্টিস্টের সাথে হঠাৎ দেখা হয়ে গেল।", slotValues: { PERSON: "my dentist" }, topicArea: "shopping" },
        { en: "I ran into my sister's friend at the gym.", bn: "আমি জিমে আমার বোনের বন্ধুর সাথে হঠাৎ দেখা হয়ে গেল।", slotValues: { PERSON: "my sister's friend" }, topicArea: "health" },
        { en: "I ran into my manager at the coffee shop.", bn: "আমি কফি শপে আমার ম্যানেজারের সাথে হঠাৎ দেখা হয়ে গেল।", slotValues: { PERSON: "my manager" }, topicArea: "food" },
        { en: "I ran into an old colleague while on vacation.", bn: "আমি ছুটিতে থাকাকালীন একজন পুরোনো সহকর্মীর সাথে হঠাৎ দেখা হয়ে গেল।", slotValues: { PERSON: "an old colleague" }, topicArea: "work" },
        { en: "I ran into my aunt at the morning walk.", bn: "আমি সকালের হাঁটায় আমার খালার সাথে হঠাৎ দেখা হয়ে গেল।", slotValues: { PERSON: "my aunt" }, topicArea: "daily_life" },
        { en: "I ran into my best friend's mom at the market.", bn: "আমি বাজারে আমার সবচেয়ে ভালো বন্ধুর মায়ের সাথে হঠাৎ দেখা হয়ে গেল।", slotValues: { PERSON: "my best friend's mom" }, topicArea: "relationships" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Run into' means to meet someone by chance, without planning. It is very common in everyday conversation.",
      usageNote_bn:
        "'Run into' অর্থ কারো সাথে আকস্মিকভাবে, পরিকল্পনা ছাড়াই দেখা হওয়া। এটি দৈনন্দিন কথোপকথনে খুবই সাধারণ।",
    },
    {
      id: "C14.5",
      formula: "I turned off [THING]",
      formula_bn: "আমি [জিনিস] বন্ধ করেছি",
      patternName: "Turn Off (Switch Off)",
      patternName_bn: "Turn Off (বন্ধ করা)",
      slots: [
        {
          name: "THING",
          description: "A noun for the device or thing you switched off",
          description_bn: "যে যন্ত্র বা জিনিস আপনি বন্ধ করেছেন তার জন্য একটি বিশেষ্য",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["the light", "my phone", "the TV"],
        },
      ],
      examples: [
        { en: "I turned off the light before going to bed.", bn: "আমি ঘুমাতে যাওয়ার আগে বাতি বন্ধ করেছি।", slotValues: { THING: "the light" }, topicArea: "daily_life" },
        { en: "I turned off my phone during the meeting.", bn: "আমি মিটিংয়ের সময় ফোন বন্ধ করেছি।", slotValues: { THING: "my phone" }, topicArea: "work" },
        { en: "I turned off the TV after the movie ended.", bn: "আমি সিনেমা শেষ হওয়ার পর টিভি বন্ধ করেছি।", slotValues: { THING: "the TV" }, topicArea: "daily_life" },
        { en: "I turned off the oven after baking the cake.", bn: "আমি কেক বেক করার পর ওভেন বন্ধ করেছি।", slotValues: { THING: "the oven" }, topicArea: "food" },
        { en: "I turned off the alarm and went back to sleep.", bn: "আমি অ্যালার্ম বন্ধ করে আবার ঘুমিয়ে পড়েছি।", slotValues: { THING: "the alarm" }, topicArea: "health" },
        { en: "I turned off the computer before leaving the office.", bn: "আমি অফিস ছাড়ার আগে কম্পিউটার বন্ধ করেছি।", slotValues: { THING: "the computer" }, topicArea: "work" },
        { en: "I turned off the air conditioner to save electricity.", bn: "আমি বিদ্যুৎ বাঁচাতে এসি বন্ধ করেছি।", slotValues: { THING: "the air conditioner" }, topicArea: "daily_life" },
        { en: "I turned off the stove after the water boiled.", bn: "আমি পানি ফুটে যাওয়ার পর চুলা বন্ধ করেছি।", slotValues: { THING: "the stove" }, topicArea: "food" },
        { en: "I turned off the music so the baby could sleep.", bn: "আমি গান বন্ধ করেছি যাতে বাচ্চা ঘুমাতে পারে।", slotValues: { THING: "the music" }, topicArea: "relationships" },
        { en: "I turned off my notifications during study time.", bn: "আমি পড়ার সময় নোটিফিকেশন বন্ধ করেছি।", slotValues: { THING: "my notifications" }, topicArea: "education" },
        { en: "I turned off the GPS after reaching the hotel.", bn: "আমি হোটেলে পৌঁছানোর পর জিপিএস বন্ধ করেছি।", slotValues: { THING: "the GPS" }, topicArea: "travel" },
        { en: "I turned off the Wi-Fi router before the storm.", bn: "আমি ঝড়ের আগে ওয়াই-ফাই রাউটার বন্ধ করেছি।", slotValues: { THING: "the Wi-Fi router" }, topicArea: "daily_life" },
        { en: "I turned off the treadmill after my workout.", bn: "আমি ব্যায়ামের পর ট্রেডমিল বন্ধ করেছি।", slotValues: { THING: "the treadmill" }, topicArea: "health" },
        { en: "I turned off the coffee machine after making my cup.", bn: "আমি কফি বানানোর পর কফি মেশিন বন্ধ করেছি।", slotValues: { THING: "the coffee machine" }, topicArea: "work" },
        { en: "I turned off the tablet and gave it back to my child.", bn: "আমি ট্যাবলেট বন্ধ করে বাচ্চাকে ফেরত দিয়েছি।", slotValues: { THING: "the tablet" }, topicArea: "relationships" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Turn off' means to stop a device or machine from operating. The opposite is 'turn on'. You can say 'turn off the light' or 'turn the light off'.",
      usageNote_bn:
        "'Turn off' অর্থ একটি যন্ত্র বা মেশিন বন্ধ করা। এর বিপরীত হলো 'turn on'। আপনি বলতে পারেন 'turn off the light' বা 'turn the light off'।",
    },
    {
      id: "C14.6",
      formula: "I looked up [THING]",
      formula_bn: "আমি [জিনিস] খুঁজে দেখেছি",
      patternName: "Look Up (Search for Information)",
      patternName_bn: "Look Up (তথ্য খোঁজা)",
      slots: [
        {
          name: "THING",
          description: "A noun or noun phrase for what you searched for information about",
          description_bn: "যে বিষয়ে আপনি তথ্য খুঁজেছেন তার জন্য একটি বিশেষ্য",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["the word in the dictionary", "the address online", "the phone number"],
        },
      ],
      examples: [
        { en: "I looked up the word in the dictionary.", bn: "আমি অভিধানে শব্দটি খুঁজে দেখেছি।", slotValues: { THING: "the word in the dictionary" }, topicArea: "education" },
        { en: "She looked up the address online.", bn: "সে অনলাইনে ঠিকানাটি খুঁজে দেখেছে।", slotValues: { THING: "the address online" }, topicArea: "daily_life" },
        { en: "Let me look up the phone number.", bn: "আমাকে ফোন নম্বরটা খুঁজে দেখতে দাও।", slotValues: { THING: "the phone number" }, topicArea: "daily_life" },
        { en: "He looked up the train schedule.", bn: "সে ট্রেনের সময়সূচি খুঁজে দেখেছে।", slotValues: { THING: "the train schedule" }, topicArea: "travel" },
        { en: "I looked up reviews before buying.", bn: "আমি কেনার আগে রিভিউ খুঁজে দেখেছি।", slotValues: { THING: "reviews" }, topicArea: "shopping" },
        { en: "Can you look up the meaning?", bn: "তুমি কি অর্থটা খুঁজে দেখতে পারো?", slotValues: { THING: "the meaning" }, topicArea: "education" },
        { en: "She looked up the recipe online.", bn: "সে অনলাইনে রেসিপিটা খুঁজে দেখেছে।", slotValues: { THING: "the recipe online" }, topicArea: "food" },
        { en: "I need to look up the bus route.", bn: "আমাকে বাসের রুট খুঁজে দেখতে হবে।", slotValues: { THING: "the bus route" }, topicArea: "travel" },
        { en: "He looked up the flight details.", bn: "সে ফ্লাইটের বিস্তারিত খুঁজে দেখেছে।", slotValues: { THING: "the flight details" }, topicArea: "travel" },
        { en: "I looked up the weather forecast.", bn: "আমি আবহাওয়ার পূর্বাভাস খুঁজে দেখেছি।", slotValues: { THING: "the weather forecast" }, topicArea: "daily_life" },
        { en: "She looked up his profile.", bn: "সে তার প্রোফাইল খুঁজে দেখেছে।", slotValues: { THING: "his profile" }, topicArea: "relationships" },
        { en: "Let me look up the opening hours.", bn: "আমাকে খোলার সময় খুঁজে দেখতে দাও।", slotValues: { THING: "the opening hours" }, topicArea: "shopping" },
        { en: "I looked up the nearest hospital.", bn: "আমি নিকটতম হাসপাতাল খুঁজে দেখেছি।", slotValues: { THING: "the nearest hospital" }, topicArea: "health" },
        { en: "He looked up the translation.", bn: "সে অনুবাদটা খুঁজে দেখেছে।", slotValues: { THING: "the translation" }, topicArea: "education" },
        { en: "I looked it up on Google.", bn: "আমি গুগলে খুঁজে দেখেছি।", slotValues: { THING: "it on Google" }, topicArea: "daily_life" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Look up' means to search for information, usually in a reference source or online. You can say 'look up the word' or 'look the word up'.",
      usageNote_bn:
        "'Look up' অর্থ তথ্য খোঁজা, সাধারণত কোনো রেফারেন্স সূত্র বা অনলাইনে। আপনি বলতে পারেন 'look up the word' বা 'look the word up'।",
    },
    {
      id: "C14.7",
      formula: "I look after [PERSON/THING]",
      formula_bn: "আমি [ব্যক্তি/জিনিস]-র দেখাশোনা করি",
      patternName: "Look After (Take Care Of)",
      patternName_bn: "Look After (যত্ন নেওয়া)",
      slots: [
        {
          name: "PERSON/THING",
          description: "The person or thing you take care of",
          description_bn: "যে ব্যক্তি বা জিনিসের যত্ন আপনি নেন",
          acceptedTypes: ["person", "noun", "noun_phrase"],
          examples: ["my younger sister", "the children", "the garden"],
        },
      ],
      examples: [
        { en: "I look after my younger sister.", bn: "আমি আমার ছোট বোনের দেখাশোনা করি।", slotValues: { "PERSON/THING": "my younger sister" }, topicArea: "relationships" },
        { en: "She looks after the children.", bn: "সে বাচ্চাদের দেখাশোনা করে।", slotValues: { "PERSON/THING": "the children" }, topicArea: "relationships" },
        { en: "Who looks after your parents?", bn: "তোমার বাবা-মায়ের দেখাশোনা কে করে?", slotValues: { "PERSON/THING": "your parents" }, topicArea: "relationships" },
        { en: "He looks after the garden.", bn: "সে বাগানের দেখাশোনা করে।", slotValues: { "PERSON/THING": "the garden" }, topicArea: "daily_life" },
        { en: "I look after the house when they travel.", bn: "তারা ভ্রমণে গেলে আমি বাড়ির দেখাশোনা করি।", slotValues: { "PERSON/THING": "the house" }, topicArea: "daily_life" },
        { en: "She looks after elderly patients.", bn: "সে বয়স্ক রোগীদের দেখাশোনা করে।", slotValues: { "PERSON/THING": "elderly patients" }, topicArea: "health" },
        { en: "Can you look after my bag?", bn: "তুমি কি আমার ব্যাগটা দেখাশোনা করতে পারো?", slotValues: { "PERSON/THING": "my bag" }, topicArea: "travel" },
        { en: "I look after my health carefully.", bn: "আমি সাবধানে আমার স্বাস্থ্যের যত্ন নিই।", slotValues: { "PERSON/THING": "my health" }, topicArea: "health" },
        { en: "He looks after the shop on weekends.", bn: "সে সাপ্তাহিক ছুটিতে দোকানের দেখাশোনা করে।", slotValues: { "PERSON/THING": "the shop" }, topicArea: "work" },
        { en: "I need someone to look after my cat.", bn: "আমার বিড়ালটির দেখাশোনা করার জন্য কাউকে দরকার।", slotValues: { "PERSON/THING": "my cat" }, topicArea: "daily_life" },
        { en: "She looks after everything at home.", bn: "সে বাড়িতে সবকিছুর দেখাশোনা করে।", slotValues: { "PERSON/THING": "everything at home" }, topicArea: "daily_life" },
        { en: "They look after each other.", bn: "তারা একে অপরের দেখাশোনা করে।", slotValues: { "PERSON/THING": "each other" }, topicArea: "relationships" },
        { en: "I look after my grandmother.", bn: "আমি আমার দাদির দেখাশোনা করি।", slotValues: { "PERSON/THING": "my grandmother" }, topicArea: "relationships" },
        { en: "He looks after the office plants.", bn: "সে অফিসের গাছগুলোর দেখাশোনা করে।", slotValues: { "PERSON/THING": "the office plants" }, topicArea: "work" },
        { en: "Who will look after the baby?", bn: "বাচ্চার দেখাশোনা কে করবে?", slotValues: { "PERSON/THING": "the baby" }, topicArea: "relationships" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Look after' means to take care of someone or something. It is commonly used in British English. 'Take care of' has the same meaning.",
      usageNote_bn:
        "'Look after' অর্থ কারো বা কিছুর যত্ন নেওয়া বা দেখাশোনা করা। এটি ব্রিটিশ ইংরেজিতে বেশি প্রচলিত। 'Take care of' একই অর্থে ব্যবহৃত হয়।",
    },
    {
      id: "C14.8",
      formula: "I turned on/turned up [THING]",
      formula_bn: "আমি [জিনিস] চালু করেছি / বাড়িয়েছি",
      patternName: "Turn On / Turn Up (Activate/Increase)",
      patternName_bn: "Turn On / Turn Up (চালু করা/বাড়ানো)",
      slots: [
        {
          name: "THING",
          description: "A noun for the device or thing you activated or increased",
          description_bn: "যে যন্ত্র বা জিনিস আপনি চালু করেছেন বা বাড়িয়েছেন তার জন্য একটি বিশেষ্য",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["the fan", "the volume", "the AC"],
        },
      ],
      examples: [
        { en: "I turned on the fan.", bn: "আমি ফ্যান চালু করেছি।", slotValues: { THING: "the fan" }, topicArea: "daily_life" },
        { en: "Can you turn on the light?", bn: "তুমি কি বাতি জ্বালাতে পারো?", slotValues: { THING: "the light" }, topicArea: "daily_life" },
        { en: "She turned up the volume.", bn: "সে ভলিউম বাড়িয়েছে।", slotValues: { THING: "the volume" }, topicArea: "daily_life" },
        { en: "Turn on the AC, it's hot.", bn: "এসি চালু করো, গরম লাগছে।", slotValues: { THING: "the AC" }, topicArea: "daily_life" },
        { en: "He turned on the computer.", bn: "সে কম্পিউটার চালু করেছে।", slotValues: { THING: "the computer" }, topicArea: "work" },
        { en: "I turned up the music.", bn: "আমি গানের শব্দ বাড়িয়েছি।", slotValues: { THING: "the music" }, topicArea: "daily_life" },
        { en: "Please turn on the TV.", bn: "দয়া করে টিভি চালু করুন।", slotValues: { THING: "the TV" }, topicArea: "daily_life" },
        { en: "She turned on the oven.", bn: "সে ওভেন চালু করেছে।", slotValues: { THING: "the oven" }, topicArea: "food" },
        { en: "Turn up the heater, it's cold.", bn: "হিটার বাড়াও, ঠান্ডা লাগছে।", slotValues: { THING: "the heater" }, topicArea: "daily_life" },
        { en: "He turned on the water.", bn: "সে পানি চালু করেছে।", slotValues: { THING: "the water" }, topicArea: "daily_life" },
        { en: "I need to turn on my phone.", bn: "আমার ফোন চালু করা দরকার।", slotValues: { THING: "my phone" }, topicArea: "daily_life" },
        { en: "Can you turn up the brightness?", bn: "তুমি কি উজ্জ্বলতা বাড়াতে পারো?", slotValues: { THING: "the brightness" }, topicArea: "work" },
        { en: "She turned on the washing machine.", bn: "সে ওয়াশিং মেশিন চালু করেছে।", slotValues: { THING: "the washing machine" }, topicArea: "daily_life" },
        { en: "Turn on the microphone.", bn: "মাইক্রোফোন চালু করো।", slotValues: { THING: "the microphone" }, topicArea: "work" },
        { en: "He turned up the speed.", bn: "সে গতি বাড়িয়েছে।", slotValues: { THING: "the speed" }, topicArea: "daily_life" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Turn on' means to activate a device. 'Turn up' means to increase the level or intensity of something. Both are separable phrasal verbs.",
      usageNote_bn:
        "'Turn on' অর্থ একটি যন্ত্র চালু করা। 'Turn up' অর্থ কিছুর মাত্রা বা তীব্রতা বাড়ানো। উভয়ই বিভাজনযোগ্য ফ্রেজাল ভার্ব।",
    },
    {
      id: "C14.9",
      formula: "I figured out [THING]",
      formula_bn: "আমি [জিনিস] বুঝতে পেরেছি / সমাধান করেছি",
      patternName: "Figure Out (Solve/Understand)",
      patternName_bn: "Figure Out (সমাধান করা/বোঝা)",
      slots: [
        {
          name: "THING",
          description: "A noun or clause for what you solved or understood",
          description_bn: "যা আপনি সমাধান করেছেন বা বুঝতে পেরেছেন তার জন্য একটি বিশেষ্য বা বাক্যাংশ",
          acceptedTypes: ["noun", "noun_phrase", "clause"],
          examples: ["the answer", "how to fix it", "the problem"],
        },
      ],
      examples: [
        { en: "I finally figured out the answer.", bn: "আমি অবশেষে উত্তরটা বুঝতে পেরেছি।", slotValues: { THING: "the answer" }, topicArea: "education" },
        { en: "She figured out how to fix it.", bn: "সে বুঝে গেছে কীভাবে এটা ঠিক করতে হয়।", slotValues: { THING: "how to fix it" }, topicArea: "daily_life" },
        { en: "Can you figure out this problem?", bn: "তুমি কি এই সমস্যার সমাধান করতে পারো?", slotValues: { THING: "this problem" }, topicArea: "education" },
        { en: "He figured out the directions.", bn: "সে দিকনির্দেশনা বুঝে গেছে।", slotValues: { THING: "the directions" }, topicArea: "travel" },
        { en: "I need to figure out what went wrong.", bn: "আমাকে বুঝতে হবে কী ভুল হয়েছে।", slotValues: { THING: "what went wrong" }, topicArea: "work" },
        { en: "We figured out a solution.", bn: "আমরা একটা সমাধান বের করেছি।", slotValues: { THING: "a solution" }, topicArea: "work" },
        { en: "She figured out the password.", bn: "সে পাসওয়ার্ড বের করেছে।", slotValues: { THING: "the password" }, topicArea: "daily_life" },
        { en: "I'm trying to figure out the schedule.", bn: "আমি সময়সূচি বোঝার চেষ্টা করছি।", slotValues: { THING: "the schedule" }, topicArea: "work" },
        { en: "He figured out the math problem.", bn: "সে গণিতের সমস্যাটি সমাধান করেছে।", slotValues: { THING: "the math problem" }, topicArea: "education" },
        { en: "I figured out why it wasn't working.", bn: "আমি বুঝে গেছি কেন এটা কাজ করছিল না।", slotValues: { THING: "why it wasn't working" }, topicArea: "daily_life" },
        { en: "Can you figure out the bill?", bn: "তুমি কি বিলটা হিসাব করতে পারো?", slotValues: { THING: "the bill" }, topicArea: "shopping" },
        { en: "She figured out how to use it.", bn: "সে বুঝে গেছে কীভাবে এটা ব্যবহার করতে হয়।", slotValues: { THING: "how to use it" }, topicArea: "daily_life" },
        { en: "I figured out the bus route.", bn: "আমি বাসের রুট বুঝে গেছি।", slotValues: { THING: "the bus route" }, topicArea: "travel" },
        { en: "He figured out the instructions.", bn: "সে নির্দেশনাগুলো বুঝে গেছে।", slotValues: { THING: "the instructions" }, topicArea: "education" },
        { en: "We need to figure out a plan.", bn: "আমাদের একটা পরিকল্পনা বের করা দরকার।", slotValues: { THING: "a plan" }, topicArea: "work" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Figure out' means to solve a problem or understand something after thinking about it. It is a separable phrasal verb: 'figure it out'.",
      usageNote_bn:
        "'Figure out' অর্থ চিন্তা করার পর কোনো সমস্যা সমাধান করা বা কিছু বোঝা। এটি একটি বিভাজনযোগ্য ফ্রেজাল ভার্ব: 'figure it out'।",
    },
    {
      id: "C14.10",
      formula: "I came up with [THING]",
      formula_bn: "আমি [জিনিস] বের করেছি / ভেবে বের করেছি",
      patternName: "Come Up With (Think of/Invent)",
      patternName_bn: "Come Up With (ভেবে বের করা/আবিষ্কার করা)",
      slots: [
        {
          name: "THING",
          description: "A noun or noun phrase for the idea or solution you thought of",
          description_bn: "আপনি যে ধারণা বা সমাধান ভেবে বের করেছেন তার জন্য একটি বিশেষ্য",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["a great idea", "a plan", "a solution"],
        },
      ],
      examples: [
        { en: "I came up with a great idea.", bn: "আমি একটা দারুণ আইডিয়া ভেবে বের করেছি।", slotValues: { THING: "a great idea" }, topicArea: "work" },
        { en: "She came up with a plan.", bn: "সে একটা পরিকল্পনা ভেবে বের করেছে।", slotValues: { THING: "a plan" }, topicArea: "work" },
        { en: "Can you come up with a solution?", bn: "তুমি কি একটা সমাধান ভেবে বের করতে পারো?", slotValues: { THING: "a solution" }, topicArea: "work" },
        { en: "He came up with an excuse.", bn: "সে একটা অজুহাত বের করেছে।", slotValues: { THING: "an excuse" }, topicArea: "relationships" },
        { en: "We need to come up with a name.", bn: "আমাদের একটা নাম ভেবে বের করা দরকার।", slotValues: { THING: "a name" }, topicArea: "work" },
        { en: "I came up with a new recipe.", bn: "আমি একটা নতুন রেসিপি বের করেছি।", slotValues: { THING: "a new recipe" }, topicArea: "food" },
        { en: "She came up with the answer quickly.", bn: "সে দ্রুত উত্তরটা বের করেছে।", slotValues: { THING: "the answer" }, topicArea: "education" },
        { en: "They came up with a better design.", bn: "তারা একটা আরও ভালো ডিজাইন ভেবে বের করেছে।", slotValues: { THING: "a better design" }, topicArea: "work" },
        { en: "I'm trying to come up with a topic.", bn: "আমি একটা বিষয় ভেবে বের করার চেষ্টা করছি।", slotValues: { THING: "a topic" }, topicArea: "education" },
        { en: "He came up with a creative approach.", bn: "সে একটা সৃজনশীল পদ্ধতি ভেবে বের করেছে।", slotValues: { THING: "a creative approach" }, topicArea: "work" },
        { en: "We came up with a way to save money.", bn: "আমরা টাকা বাঁচানোর একটা উপায় ভেবে বের করেছি।", slotValues: { THING: "a way to save money" }, topicArea: "shopping" },
        { en: "She came up with a clever trick.", bn: "সে একটা চালাক কৌশল ভেবে বের করেছে।", slotValues: { THING: "a clever trick" }, topicArea: "daily_life" },
        { en: "Can anyone come up with a suggestion?", bn: "কেউ কি একটা পরামর্শ দিতে পারো?", slotValues: { THING: "a suggestion" }, topicArea: "work" },
        { en: "I came up with a title for the project.", bn: "আমি প্রকল্পের জন্য একটা শিরোনাম ভেবে বের করেছি।", slotValues: { THING: "a title for the project" }, topicArea: "education" },
        { en: "He always comes up with something.", bn: "সে সবসময় কিছু না কিছু ভেবে বের করে।", slotValues: { THING: "something" }, topicArea: "daily_life" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Come up with' means to think of or produce an idea, plan, or solution. It is an inseparable phrasal verb: you cannot say 'come a plan up with'.",
      usageNote_bn:
        "'Come up with' অর্থ একটি ধারণা, পরিকল্পনা বা সমাধান ভেবে বের করা। এটি একটি অবিভাজনযোগ্য ফ্রেজাল ভার্ব: আপনি 'come a plan up with' বলতে পারবেন না।",
    },
    {
      id: "C14.11",
      formula: "I put up with [THING]",
      formula_bn: "আমি [জিনিস] সহ্য করি",
      patternName: "Put Up With (Tolerate)",
      patternName_bn: "Put Up With (সহ্য করা)",
      slots: [
        {
          name: "THING",
          description: "A noun or noun phrase for what you tolerate or endure",
          description_bn: "যা আপনি সহ্য করেন বা সইতে থাকেন তার জন্য একটি বিশেষ্য",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["the noise", "his bad habits", "the long commute"],
        },
      ],
      examples: [
        { en: "I can't put up with this noise anymore.", bn: "আমি আর এই শব্দ সহ্য করতে পারছি না।", slotValues: { THING: "this noise" }, topicArea: "daily_life" },
        { en: "She puts up with his bad habits.", bn: "সে তার খারাপ অভ্যাস সহ্য করে।", slotValues: { THING: "his bad habits" }, topicArea: "relationships" },
        { en: "How do you put up with the traffic every day?", bn: "তুমি প্রতিদিন যানজট কীভাবে সহ্য কর?", slotValues: { THING: "the traffic every day" }, topicArea: "travel" },
        { en: "I won't put up with rudeness.", bn: "আমি অভদ্রতা সহ্য করব না।", slotValues: { THING: "rudeness" }, topicArea: "relationships" },
        { en: "He has to put up with long hours at work.", bn: "তাকে কাজে দীর্ঘ সময় সহ্য করতে হয়।", slotValues: { THING: "long hours at work" }, topicArea: "work" },
        { en: "We put up with the heat because there's no AC.", bn: "এসি নেই বলে আমরা গরম সহ্য করি।", slotValues: { THING: "the heat" }, topicArea: "daily_life" },
        { en: "She can't put up with her noisy neighbors.", bn: "সে তার শব্দ করা প্রতিবেশীদের সহ্য করতে পারে না।", slotValues: { THING: "her noisy neighbors" }, topicArea: "daily_life" },
        { en: "I put up with the pain until I saw the doctor.", bn: "আমি ডাক্তার দেখানো পর্যন্ত ব্যথা সহ্য করেছি।", slotValues: { THING: "the pain" }, topicArea: "health" },
        { en: "He puts up with a lot of stress at work.", bn: "সে কাজে অনেক চাপ সহ্য করে।", slotValues: { THING: "a lot of stress" }, topicArea: "work" },
        { en: "They put up with the cold weather during the trip.", bn: "তারা ভ্রমণের সময় ঠান্ডা আবহাওয়া সহ্য করেছে।", slotValues: { THING: "the cold weather" }, topicArea: "travel" },
        { en: "I can't put up with this slow internet.", bn: "আমি এই ধীর ইন্টারনেট সহ্য করতে পারছি না।", slotValues: { THING: "this slow internet" }, topicArea: "daily_life" },
        { en: "She puts up with the boring lectures.", bn: "সে বিরক্তিকর লেকচার সহ্য করে।", slotValues: { THING: "the boring lectures" }, topicArea: "education" },
        { en: "How long can you put up with this situation?", bn: "তুমি কতদিন এই পরিস্থিতি সহ্য করতে পারবে?", slotValues: { THING: "this situation" }, topicArea: "daily_life" },
        { en: "I put up with the bad food at the canteen.", bn: "আমি ক্যান্টিনের খারাপ খাবার সহ্য করি।", slotValues: { THING: "the bad food" }, topicArea: "food" },
        { en: "He puts up with the high prices because the quality is good.", bn: "সে উচ্চ দাম সহ্য করে কারণ মান ভালো।", slotValues: { THING: "the high prices" }, topicArea: "shopping" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Put up with' means to tolerate or endure something unpleasant. It is an inseparable phrasal verb. It is commonly used to express frustration or patience.",
      usageNote_bn:
        "'Put up with' অর্থ অপ্রীতিকর কিছু সহ্য করা বা সইতে থাকা। এটি একটি অবিভাজনযোগ্য ফ্রেজাল ভার্ব। হতাশা বা ধৈর্য প্রকাশে এটি সাধারণত ব্যবহৃত হয়।",
    },
    {
      id: "C14.12",
      formula: "I got over [THING]",
      formula_bn: "আমি [জিনিস] কাটিয়ে উঠেছি",
      patternName: "Get Over (Recover/Move Past)",
      patternName_bn: "Get Over (কাটিয়ে ওঠা/সেরে ওঠা)",
      slots: [
        {
          name: "THING",
          description: "A noun or noun phrase for what you recovered from or moved past",
          description_bn: "যা থেকে আপনি সেরে উঠেছেন বা কাটিয়ে উঠেছেন তার জন্য একটি বিশেষ্য",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["my cold", "the breakup", "the shock"],
        },
      ],
      examples: [
        { en: "I finally got over my cold.", bn: "আমি অবশেষে আমার সর্দি কাটিয়ে উঠেছি।", slotValues: { THING: "my cold" }, topicArea: "health" },
        { en: "She got over the breakup quickly.", bn: "সে দ্রুত ব্রেকআপ কাটিয়ে উঠেছে।", slotValues: { THING: "the breakup" }, topicArea: "relationships" },
        { en: "He can't get over the shock.", bn: "সে আঘাত কাটিয়ে উঠতে পারছে না।", slotValues: { THING: "the shock" }, topicArea: "daily_life" },
        { en: "It takes time to get over a loss.", bn: "ক্ষতি কাটিয়ে উঠতে সময় লাগে।", slotValues: { THING: "a loss" }, topicArea: "relationships" },
        { en: "I got over my fear of public speaking.", bn: "আমি জনসম্মুখে কথা বলার ভয় কাটিয়ে উঠেছি।", slotValues: { THING: "my fear of public speaking" }, topicArea: "work" },
        { en: "She hasn't gotten over the accident yet.", bn: "সে এখনো দুর্ঘটনার ধাক্কা কাটিয়ে উঠতে পারেনি।", slotValues: { THING: "the accident" }, topicArea: "health" },
        { en: "He got over his disappointment about the exam.", bn: "সে পরীক্ষার হতাশা কাটিয়ে উঠেছে।", slotValues: { THING: "his disappointment about the exam" }, topicArea: "education" },
        { en: "I'm trying to get over my jet lag.", bn: "আমি আমার জেট ল্যাগ কাটিয়ে উঠার চেষ্টা করছি।", slotValues: { THING: "my jet lag" }, topicArea: "travel" },
        { en: "It's hard to get over a bad review at work.", bn: "কাজে খারাপ রিভিউ কাটিয়ে ওঠা কঠিন।", slotValues: { THING: "a bad review at work" }, topicArea: "work" },
        { en: "She got over her anger and forgave him.", bn: "সে রাগ কাটিয়ে উঠে তাকে মাফ করে দিয়েছে।", slotValues: { THING: "her anger" }, topicArea: "relationships" },
        { en: "I can't get over how expensive everything is.", bn: "আমি কাটিয়ে উঠতে পারছি না সবকিছু কত দামি।", slotValues: { THING: "how expensive everything is" }, topicArea: "shopping" },
        { en: "He got over his homesickness after a few weeks.", bn: "সে কয়েক সপ্তাহ পর গৃহকাতরতা কাটিয়ে উঠেছে।", slotValues: { THING: "his homesickness" }, topicArea: "daily_life" },
        { en: "I got over the flu just in time for my trip.", bn: "আমি ভ্রমণের ঠিক আগে ফ্লু কাটিয়ে উঠেছি।", slotValues: { THING: "the flu" }, topicArea: "health" },
        { en: "She can't get over the taste of that amazing dish.", bn: "সে সেই অসাধারণ পদের স্বাদ ভুলতে পারছে না।", slotValues: { THING: "the taste of that amazing dish" }, topicArea: "food" },
        { en: "He got over his failure and tried again.", bn: "সে ব্যর্থতা কাটিয়ে উঠে আবার চেষ্টা করেছে।", slotValues: { THING: "his failure" }, topicArea: "education" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Get over' means to recover from an illness, emotional setback, or surprise. It can also mean to move past something emotionally. It is an inseparable phrasal verb.",
      usageNote_bn:
        "'Get over' অর্থ অসুস্থতা, আবেগজনিত ধাক্কা বা বিস্ময় থেকে সেরে ওঠা। এটি আবেগতভাবে কিছু কাটিয়ে ওঠাও বোঝাতে পারে। এটি একটি অবিভাজনযোগ্য ফ্রেজাল ভার্ব।",
    },
    {
      id: "C14.13",
      formula: "I brought up [TOPIC]",
      formula_bn: "আমি [বিষয়] উত্থাপন করেছি",
      patternName: "Bring Up (Raise a Topic)",
      patternName_bn: "Bring Up (বিষয় উত্থাপন করা)",
      slots: [
        {
          name: "TOPIC",
          description: "A noun or noun phrase for the topic or issue you mentioned",
          description_bn: "যে বিষয় বা ইস্যু আপনি উল্লেখ করেছেন তার জন্য একটি বিশেষ্য",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["an interesting point", "politics", "the issue of pay"],
        },
      ],
      examples: [
        { en: "He brought up an interesting point during the meeting.", bn: "সে মিটিংয়ে একটি আকর্ষণীয় বিষয় উত্থাপন করেছে।", slotValues: { TOPIC: "an interesting point" }, topicArea: "work" },
        { en: "Don't bring up politics at dinner.", bn: "রাতের খাবারে রাজনীতির কথা তুলো না।", slotValues: { TOPIC: "politics" }, topicArea: "food" },
        { en: "She brought up the issue of pay.", bn: "সে বেতনের বিষয়টি উত্থাপন করেছে।", slotValues: { TOPIC: "the issue of pay" }, topicArea: "work" },
        { en: "I didn't want to bring up the past.", bn: "আমি অতীতের কথা তুলতে চাইনি।", slotValues: { TOPIC: "the past" }, topicArea: "relationships" },
        { en: "He brought up a good question in class.", bn: "সে ক্লাসে একটি ভালো প্রশ্ন উত্থাপন করেছে।", slotValues: { TOPIC: "a good question" }, topicArea: "education" },
        { en: "She brought up her health concerns to the doctor.", bn: "সে ডাক্তারের কাছে তার স্বাস্থ্য উদ্বেগের কথা তুলেছে।", slotValues: { TOPIC: "her health concerns" }, topicArea: "health" },
        { en: "Why did you bring up that embarrassing story?", bn: "তুমি কেন সেই বিব্রতকর গল্পটি তুললে?", slotValues: { TOPIC: "that embarrassing story" }, topicArea: "relationships" },
        { en: "He brought up the idea of traveling together.", bn: "সে একসাথে ভ্রমণের ধারণা তুলেছে।", slotValues: { TOPIC: "the idea of traveling together" }, topicArea: "travel" },
        { en: "I need to bring up something important with my boss.", bn: "আমাকে বসের সাথে একটি গুরুত্বপূর্ণ বিষয় তুলতে হবে।", slotValues: { TOPIC: "something important" }, topicArea: "work" },
        { en: "She brought up the topic of saving money.", bn: "সে টাকা বাঁচানোর বিষয়টি উত্থাপন করেছে।", slotValues: { TOPIC: "the topic of saving money" }, topicArea: "shopping" },
        { en: "Don't bring up his mistakes again.", bn: "তার ভুলগুলো আবার তুলো না।", slotValues: { TOPIC: "his mistakes" }, topicArea: "relationships" },
        { en: "The student brought up a point about homework.", bn: "ছাত্রটি বাড়ির কাজ সম্পর্কে একটি বিষয় উত্থাপন করেছে।", slotValues: { TOPIC: "a point about homework" }, topicArea: "education" },
        { en: "I brought up the problem with the food quality.", bn: "আমি খাবারের মানের সমস্যাটি উত্থাপন করেছি।", slotValues: { TOPIC: "the problem with the food quality" }, topicArea: "food" },
        { en: "She brought up the need for exercise.", bn: "সে ব্যায়ামের প্রয়োজনীয়তার কথা তুলেছে।", slotValues: { TOPIC: "the need for exercise" }, topicArea: "health" },
        { en: "He brought up the cost of the hotel.", bn: "সে হোটেলের খরচের বিষয়টি তুলেছে।", slotValues: { TOPIC: "the cost of the hotel" }, topicArea: "travel" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Bring up' means to mention or introduce a topic in conversation. It is a separable phrasal verb: 'bring it up' or 'bring up the topic'.",
      usageNote_bn:
        "'Bring up' অর্থ কথোপকথনে কোনো বিষয় উল্লেখ করা বা উত্থাপন করা। এটি একটি বিভাজনযোগ্য ফ্রেজাল ভার্ব: 'bring it up' বা 'bring up the topic'।",
    },
    {
      id: "C14.14",
      formula: "I pointed out [THING]",
      formula_bn: "আমি [জিনিস] নির্দেশ করেছি / দেখিয়ে দিয়েছি",
      patternName: "Point Out (Indicate/Highlight)",
      patternName_bn: "Point Out (নির্দেশ করা/দেখিয়ে দেওয়া)",
      slots: [
        {
          name: "THING",
          description: "A noun, noun phrase, or clause for what you indicated or highlighted",
          description_bn: "যা আপনি নির্দেশ করেছেন বা দেখিয়ে দিয়েছেন তার জন্য একটি বিশেষ্য বা বাক্যাংশ",
          acceptedTypes: ["noun", "noun_phrase", "clause"],
          examples: ["the mistake", "that we were late", "one thing"],
        },
      ],
      examples: [
        { en: "She pointed out the mistake in the report.", bn: "সে রিপোর্টের ভুলটি দেখিয়ে দিয়েছে।", slotValues: { THING: "the mistake in the report" }, topicArea: "work" },
        { en: "He pointed out that we were late.", bn: "সে দেখিয়ে দিয়েছে যে আমরা দেরি করেছি।", slotValues: { THING: "that we were late" }, topicArea: "daily_life" },
        { en: "Let me point out one thing.", bn: "আমাকে একটি জিনিস দেখিয়ে দিতে দাও।", slotValues: { THING: "one thing" }, topicArea: "daily_life" },
        { en: "The teacher pointed out the common errors.", bn: "শিক্ষক সাধারণ ভুলগুলো দেখিয়ে দিয়েছেন।", slotValues: { THING: "the common errors" }, topicArea: "education" },
        { en: "She pointed out the difference between the two products.", bn: "সে দুটি পণ্যের মধ্যে পার্থক্য দেখিয়ে দিয়েছে।", slotValues: { THING: "the difference between the two products" }, topicArea: "shopping" },
        { en: "He pointed out the health risks of smoking.", bn: "সে ধূমপানের স্বাস্থ্য ঝুঁকি দেখিয়ে দিয়েছে।", slotValues: { THING: "the health risks of smoking" }, topicArea: "health" },
        { en: "I pointed out that the directions were wrong.", bn: "আমি দেখিয়ে দিয়েছি যে দিকনির্দেশনা ভুল ছিল।", slotValues: { THING: "that the directions were wrong" }, topicArea: "travel" },
        { en: "She pointed out his strengths during the review.", bn: "সে রিভিউয়ের সময় তার শক্তির দিকগুলো দেখিয়ে দিয়েছে।", slotValues: { THING: "his strengths" }, topicArea: "work" },
        { en: "My friend pointed out a nice restaurant nearby.", bn: "আমার বন্ধু কাছাকাছি একটি সুন্দর রেস্তোরাঁ দেখিয়ে দিয়েছে।", slotValues: { THING: "a nice restaurant nearby" }, topicArea: "food" },
        { en: "He pointed out that we needed more practice.", bn: "সে দেখিয়ে দিয়েছে যে আমাদের আরও অনুশীলন দরকার।", slotValues: { THING: "that we needed more practice" }, topicArea: "education" },
        { en: "She pointed out the problem with the plan.", bn: "সে পরিকল্পনার সমস্যাটি দেখিয়ে দিয়েছে।", slotValues: { THING: "the problem with the plan" }, topicArea: "work" },
        { en: "I pointed out that the price had increased.", bn: "আমি দেখিয়ে দিয়েছি যে দাম বেড়ে গেছে।", slotValues: { THING: "that the price had increased" }, topicArea: "shopping" },
        { en: "The guide pointed out the historical landmarks.", bn: "গাইড ঐতিহাসিক স্থানগুলো দেখিয়ে দিয়েছেন।", slotValues: { THING: "the historical landmarks" }, topicArea: "travel" },
        { en: "He pointed out my brother's good qualities.", bn: "সে আমার ভাইয়ের ভালো গুণগুলো দেখিয়ে দিয়েছে।", slotValues: { THING: "my brother's good qualities" }, topicArea: "relationships" },
        { en: "The doctor pointed out the symptoms to watch for.", bn: "ডাক্তার লক্ষ্য রাখার মতো উপসর্গগুলো দেখিয়ে দিয়েছেন।", slotValues: { THING: "the symptoms to watch for" }, topicArea: "health" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Point out' means to draw attention to something, to indicate, or to highlight. It can be followed by a noun or a 'that' clause. It is a separable phrasal verb.",
      usageNote_bn:
        "'Point out' অর্থ কোনো কিছুর প্রতি মনোযোগ আকর্ষণ করা, নির্দেশ করা বা দেখিয়ে দেওয়া। এর পরে একটি বিশেষ্য বা 'that' ক্লজ আসতে পারে। এটি একটি বিভাজনযোগ্য ফ্রেজাল ভার্ব।",
    },
    {
      id: "C14.15",
      formula: "[THING] broke down",
      formula_bn: "[জিনিস] নষ্ট হয়ে গেছে / ভেঙে পড়েছে",
      patternName: "Break Down (Stop Working/Analyze)",
      patternName_bn: "Break Down (নষ্ট হওয়া/বিশ্লেষণ করা)",
      slots: [
        {
          name: "THING",
          description: "A noun for the machine, vehicle, or thing that stopped working, or the thing being analyzed",
          description_bn: "যে যন্ত্র, যানবাহন বা জিনিস কাজ বন্ধ করেছে, বা যা বিশ্লেষণ করা হচ্ছে তার জন্য একটি বিশেষ্য",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["my car", "the machine", "the problem"],
        },
      ],
      examples: [
        { en: "My car broke down on the highway.", bn: "আমার গাড়ি হাইওয়েতে নষ্ট হয়ে গেছে।", slotValues: { THING: "My car" }, topicArea: "travel" },
        { en: "She broke down the problem step by step.", bn: "সে সমস্যাটি ধাপে ধাপে বিশ্লেষণ করেছে।", slotValues: { THING: "the problem" }, topicArea: "education" },
        { en: "The machine broke down again.", bn: "যন্ত্রটি আবার নষ্ট হয়ে গেছে।", slotValues: { THING: "The machine" }, topicArea: "work" },
        { en: "The bus broke down in the middle of the road.", bn: "বাসটি রাস্তার মাঝখানে নষ্ট হয়ে গেছে।", slotValues: { THING: "The bus" }, topicArea: "travel" },
        { en: "He broke down the costs for the project.", bn: "সে প্রকল্পের খরচ বিশ্লেষণ করেছে।", slotValues: { THING: "the costs" }, topicArea: "work" },
        { en: "The washing machine broke down last week.", bn: "ওয়াশিং মেশিন গত সপ্তাহে নষ্ট হয়ে গেছে।", slotValues: { THING: "The washing machine" }, topicArea: "daily_life" },
        { en: "The teacher broke down the lesson into simple parts.", bn: "শিক্ষক পাঠটি সহজ অংশে ভাগ করে দিয়েছেন।", slotValues: { THING: "the lesson" }, topicArea: "education" },
        { en: "My phone broke down after I dropped it.", bn: "ফেলে দেওয়ার পর আমার ফোন নষ্ট হয়ে গেছে।", slotValues: { THING: "My phone" }, topicArea: "daily_life" },
        { en: "She broke down crying when she heard the news.", bn: "খবর শুনে সে কেঁদে ভেঙে পড়েছে।", slotValues: { THING: "She" }, topicArea: "relationships" },
        { en: "The elevator broke down this morning.", bn: "আজ সকালে লিফট নষ্ট হয়ে গেছে।", slotValues: { THING: "The elevator" }, topicArea: "daily_life" },
        { en: "He broke down the recipe into easy steps.", bn: "সে রেসিপিটি সহজ ধাপে ভাগ করেছে।", slotValues: { THING: "the recipe" }, topicArea: "food" },
        { en: "The air conditioner broke down during the heatwave.", bn: "তাপপ্রবাহের সময় এসি নষ্ট হয়ে গেছে।", slotValues: { THING: "The air conditioner" }, topicArea: "daily_life" },
        { en: "Communication broke down between the two teams.", bn: "দুই দলের মধ্যে যোগাযোগ ভেঙে পড়েছে।", slotValues: { THING: "Communication" }, topicArea: "work" },
        { en: "The doctor broke down the treatment options.", bn: "ডাক্তার চিকিৎসার বিকল্পগুলো বিশ্লেষণ করে দিয়েছেন।", slotValues: { THING: "the treatment options" }, topicArea: "health" },
        { en: "The truck broke down near the shopping center.", bn: "ট্রাকটি শপিং সেন্টারের কাছে নষ্ট হয়ে গেছে।", slotValues: { THING: "The truck" }, topicArea: "shopping" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Break down' has two main meanings: (1) to stop functioning (for machines/vehicles), and (2) to divide something into smaller parts for analysis. When meaning 'malfunction', it is intransitive. When meaning 'analyze', it is separable.",
      usageNote_bn:
        "'Break down'-এর দুটি প্রধান অর্থ আছে: (১) কাজ বন্ধ হওয়া (যন্ত্র/যানবাহনের জন্য), এবং (২) বিশ্লেষণের জন্য কিছুকে ছোট অংশে ভাগ করা। 'ত্রুটি' অর্থে এটি অকর্মক। 'বিশ্লেষণ' অর্থে এটি বিভাজনযোগ্য।",
    },
  ],
};
