import { PatternCategory } from "@/types/pattern";

export const categoryD4: PatternCategory = {
  id: "D4",
  slug: "certainty-uncertainty",
  name: "Certainty & Uncertainty",
  name_bn: "নিশ্চয়তা এবং অনিশ্চয়তা",
  description:
    "Learn how to express how sure or unsure you are about something in English.",
  description_bn:
    "ইংরেজিতে কোনো বিষয়ে আপনি কতটা নিশ্চিত বা অনিশ্চিত তা প্রকাশ করতে শিখুন।",
  icon: "🎯",
  group: "D",
  groupName: "Ability, Obligation & Possibility",
  groupName_bn: "সক্ষমতা, বাধ্যবাধকতা এবং সম্ভাবনা",
  difficulty: "intermediate",
  patterns: [
    {
      id: "D4.1",
      formula: "I'm sure [CLAUSE]",
      formula_bn: "আমি নিশ্চিত [বাক্যাংশ]",
      patternName: "Expressing Certainty",
      patternName_bn: "নিশ্চয়তা প্রকাশ",
      slots: [
        {
          name: "CLAUSE",
          description: "A clause describing what you are certain about",
          description_bn: "একটি উপবাক্য যা আপনি কী সম্পর্কে নিশ্চিত তা বর্ণনা করে",
          acceptedTypes: ["clause"],
          examples: [
            "he'll come",
            "it's the right decision",
            "everything will be fine",
          ],
        },
      ],
      examples: [
        {
          en: "I'm sure he'll come.",
          bn: "আমি নিশ্চিত সে আসবে।",
          slotValues: { CLAUSE: "he'll come" },
          topicArea: "relationships",
        },
        {
          en: "I'm sure it's the right decision.",
          bn: "আমি নিশ্চিত এটা সঠিক সিদ্ধান্ত।",
          slotValues: { CLAUSE: "it's the right decision" },
          topicArea: "daily_life",
        },
        {
          en: "I'm sure everything will be fine.",
          bn: "আমি নিশ্চিত সব ঠিক হয়ে যাবে।",
          slotValues: { CLAUSE: "everything will be fine" },
          topicArea: "daily_life",
        },
        {
          en: "I'm sure I locked the door.",
          bn: "আমি নিশ্চিত আমি দরজা তালা দিয়েছি।",
          slotValues: { CLAUSE: "I locked the door" },
          topicArea: "daily_life",
        },
        {
          en: "I'm sure you'll pass the exam.",
          bn: "আমি নিশ্চিত তুমি পরীক্ষায় পাশ করবে।",
          slotValues: { CLAUSE: "you'll pass the exam" },
          topicArea: "education",
        },
        {
          en: "I'm sure the food will be delicious.",
          bn: "আমি নিশ্চিত খাবারটা সুস্বাদু হবে।",
          slotValues: { CLAUSE: "the food will be delicious" },
          topicArea: "food",
        },
        {
          en: "I'm sure we'll get the project on time.",
          bn: "আমি নিশ্চিত আমরা সময়মতো প্রকল্পটি পাব।",
          slotValues: { CLAUSE: "we'll get the project on time" },
          topicArea: "work",
        },
        {
          en: "I'm sure the medicine will help.",
          bn: "আমি নিশ্চিত ওষুধটি কাজে আসবে।",
          slotValues: { CLAUSE: "the medicine will help" },
          topicArea: "health",
        },
        {
          en: "I'm sure the hotel is near the beach.",
          bn: "আমি নিশ্চিত হোটেলটি সমুদ্র সৈকতের কাছে।",
          slotValues: { CLAUSE: "the hotel is near the beach" },
          topicArea: "travel",
        },
        {
          en: "I'm sure this is the best price.",
          bn: "আমি নিশ্চিত এটাই সেরা দাম।",
          slotValues: { CLAUSE: "this is the best price" },
          topicArea: "shopping",
        },
        {
          en: "I'm sure she'll understand.",
          bn: "আমি নিশ্চিত সে বুঝবে।",
          slotValues: { CLAUSE: "she'll understand" },
          topicArea: "relationships",
        },
        {
          en: "I'm sure the boss will approve.",
          bn: "আমি নিশ্চিত বস অনুমোদন দেবেন।",
          slotValues: { CLAUSE: "the boss will approve" },
          topicArea: "work",
        },
        {
          en: "I'm sure we took the right turn.",
          bn: "আমি নিশ্চিত আমরা সঠিক মোড় নিয়েছি।",
          slotValues: { CLAUSE: "we took the right turn" },
          topicArea: "travel",
        },
        {
          en: "I'm sure you'll enjoy the course.",
          bn: "আমি নিশ্চিত তুমি কোর্সটি উপভোগ করবে।",
          slotValues: { CLAUSE: "you'll enjoy the course" },
          topicArea: "education",
        },
        {
          en: "I'm sure I'll feel better soon.",
          bn: "আমি নিশ্চিত আমি শীঘ্রই ভালো অনুভব করব।",
          slotValues: { CLAUSE: "I'll feel better soon" },
          topicArea: "health",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'I'm sure' expresses strong confidence about something. It is commonly used in everyday conversation.",
      usageNote_bn:
        "'I'm sure' কোনো বিষয়ে দৃঢ় আত্মবিশ্বাস প্রকাশ করে। এটি দৈনন্দিন কথোপকথনে প্রচলিত।",
      combinableWith: ["D4.4"],
      banglaStructureMap:
        "আমি নিশ্চিত (Subject + Adj) + [CLAUSE] (Subordinate clause)",
    },
    {
      id: "D4.2",
      formula: "I'm not sure if [CLAUSE]",
      formula_bn: "আমি নিশ্চিত নই [বাক্যাংশ] কিনা",
      patternName: "Expressing Uncertainty",
      patternName_bn: "অনিশ্চয়তা প্রকাশ",
      slots: [
        {
          name: "CLAUSE",
          description: "A clause describing what you are uncertain about",
          description_bn: "একটি উপবাক্য যা আপনি কী সম্পর্কে অনিশ্চিত তা বর্ণনা করে",
          acceptedTypes: ["clause"],
          examples: [
            "this is correct",
            "he got my message",
            "I should go",
          ],
        },
      ],
      examples: [
        {
          en: "I'm not sure if this is correct.",
          bn: "আমি নিশ্চিত নই এটা সঠিক কিনা।",
          slotValues: { CLAUSE: "this is correct" },
          topicArea: "education",
        },
        {
          en: "I'm not sure if he got my message.",
          bn: "আমি নিশ্চিত নই সে আমার বার্তা পেয়েছে কিনা।",
          slotValues: { CLAUSE: "he got my message" },
          topicArea: "relationships",
        },
        {
          en: "I'm not sure if I should go.",
          bn: "আমি নিশ্চিত নই আমার যাওয়া উচিত কিনা।",
          slotValues: { CLAUSE: "I should go" },
          topicArea: "daily_life",
        },
        {
          en: "I'm not sure if the shop is open today.",
          bn: "আমি নিশ্চিত নই দোকানটি আজ খোলা কিনা।",
          slotValues: { CLAUSE: "the shop is open today" },
          topicArea: "shopping",
        },
        {
          en: "I'm not sure if the deadline has changed.",
          bn: "আমি নিশ্চিত নই সময়সীমা বদলে গেছে কিনা।",
          slotValues: { CLAUSE: "the deadline has changed" },
          topicArea: "work",
        },
        {
          en: "I'm not sure if I can eat this.",
          bn: "আমি নিশ্চিত নই আমি এটা খেতে পারব কিনা।",
          slotValues: { CLAUSE: "I can eat this" },
          topicArea: "food",
        },
        {
          en: "I'm not sure if the train stops here.",
          bn: "আমি নিশ্চিত নই ট্রেনটি এখানে থামে কিনা।",
          slotValues: { CLAUSE: "the train stops here" },
          topicArea: "travel",
        },
        {
          en: "I'm not sure if I'm feeling better.",
          bn: "আমি নিশ্চিত নই আমি ভালো অনুভব করছি কিনা।",
          slotValues: { CLAUSE: "I'm feeling better" },
          topicArea: "health",
        },
        {
          en: "I'm not sure if she's coming to the wedding.",
          bn: "আমি নিশ্চিত নই সে বিয়েতে আসছে কিনা।",
          slotValues: { CLAUSE: "she's coming to the wedding" },
          topicArea: "relationships",
        },
        {
          en: "I'm not sure if this is the right size.",
          bn: "আমি নিশ্চিত নই এটা সঠিক সাইজ কিনা।",
          slotValues: { CLAUSE: "this is the right size" },
          topicArea: "shopping",
        },
        {
          en: "I'm not sure if the report is ready.",
          bn: "আমি নিশ্চিত নই রিপোর্টটি প্রস্তুত কিনা।",
          slotValues: { CLAUSE: "the report is ready" },
          topicArea: "work",
        },
        {
          en: "I'm not sure if I passed the test.",
          bn: "আমি নিশ্চিত নই আমি পরীক্ষায় পাশ করেছি কিনা।",
          slotValues: { CLAUSE: "I passed the test" },
          topicArea: "education",
        },
        {
          en: "I'm not sure if the water is safe to drink.",
          bn: "আমি নিশ্চিত নই পানিটা পান করা নিরাপদ কিনা।",
          slotValues: { CLAUSE: "the water is safe to drink" },
          topicArea: "health",
        },
        {
          en: "I'm not sure if we're going the right way.",
          bn: "আমি নিশ্চিত নই আমরা সঠিক পথে যাচ্ছি কিনা।",
          slotValues: { CLAUSE: "we're going the right way" },
          topicArea: "travel",
        },
        {
          en: "I'm not sure if this dish has nuts in it.",
          bn: "আমি নিশ্চিত নই এই খাবারে বাদাম আছে কিনা।",
          slotValues: { CLAUSE: "this dish has nuts in it" },
          topicArea: "food",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'I'm not sure if' is a common way to express doubt or uncertainty politely. It invites further discussion.",
      usageNote_bn:
        "'I'm not sure if' ভদ্রভাবে সন্দেহ বা অনিশ্চয়তা প্রকাশের একটি সাধারণ উপায়। এটি আরও আলোচনার আমন্ত্রণ জানায়।",
      combinableWith: ["D4.3"],
      banglaStructureMap:
        "আমি নিশ্চিত নই (Subject + Neg. Adj) + [CLAUSE] কিনা (Subordinate clause + Particle)",
    },
    {
      id: "D4.3",
      formula: "I doubt [CLAUSE]",
      formula_bn: "আমার সন্দেহ [বাক্যাংশ]",
      patternName: "Expressing Doubt",
      patternName_bn: "সন্দেহ প্রকাশ",
      slots: [
        {
          name: "CLAUSE",
          description: "A clause describing what you doubt",
          description_bn: "একটি উপবাক্য যা আপনি কী সম্পর্কে সন্দেহ করেন তা বর্ণনা করে",
          acceptedTypes: ["clause"],
          examples: [
            "he'll show up",
            "that's true",
            "it will work",
          ],
        },
      ],
      examples: [
        {
          en: "I doubt he'll show up.",
          bn: "আমার সন্দেহ সে আসবে।",
          slotValues: { CLAUSE: "he'll show up" },
          topicArea: "relationships",
        },
        {
          en: "I doubt that's true.",
          bn: "আমার সন্দেহ ওটা সত্যি।",
          slotValues: { CLAUSE: "that's true" },
          topicArea: "daily_life",
        },
        {
          en: "I doubt it will work.",
          bn: "আমার সন্দেহ এটা কাজ করবে।",
          slotValues: { CLAUSE: "it will work" },
          topicArea: "work",
        },
        {
          en: "I doubt the restaurant is still open.",
          bn: "আমার সন্দেহ রেস্তোরাঁটি এখনও খোলা আছে।",
          slotValues: { CLAUSE: "the restaurant is still open" },
          topicArea: "food",
        },
        {
          en: "I doubt we'll get seats on that train.",
          bn: "আমার সন্দেহ ওই ট্রেনে আমরা সিট পাব।",
          slotValues: { CLAUSE: "we'll get seats on that train" },
          topicArea: "travel",
        },
        {
          en: "I doubt the teacher will postpone the test.",
          bn: "আমার সন্দেহ শিক্ষক পরীক্ষা পিছিয়ে দেবেন।",
          slotValues: { CLAUSE: "the teacher will postpone the test" },
          topicArea: "education",
        },
        {
          en: "I doubt this medicine has any side effects.",
          bn: "আমার সন্দেহ এই ওষুধের কোনো পার্শ্বপ্রতিক্রিয়া আছে।",
          slotValues: { CLAUSE: "this medicine has any side effects" },
          topicArea: "health",
        },
        {
          en: "I doubt they'll give us a discount.",
          bn: "আমার সন্দেহ তারা আমাদের ছাড় দেবে।",
          slotValues: { CLAUSE: "they'll give us a discount" },
          topicArea: "shopping",
        },
        {
          en: "I doubt she knows about the meeting.",
          bn: "আমার সন্দেহ সে মিটিংয়ের কথা জানে।",
          slotValues: { CLAUSE: "she knows about the meeting" },
          topicArea: "work",
        },
        {
          en: "I doubt anyone will notice the difference.",
          bn: "আমার সন্দেহ কেউ পার্থক্যটা লক্ষ্য করবে।",
          slotValues: { CLAUSE: "anyone will notice the difference" },
          topicArea: "daily_life",
        },
        {
          en: "I doubt they'll finish the road by next month.",
          bn: "আমার সন্দেহ তারা আগামী মাসের মধ্যে রাস্তা শেষ করবে।",
          slotValues: { CLAUSE: "they'll finish the road by next month" },
          topicArea: "travel",
        },
        {
          en: "I doubt he studied for the exam.",
          bn: "আমার সন্দেহ সে পরীক্ষার জন্য পড়াশোনা করেছে।",
          slotValues: { CLAUSE: "he studied for the exam" },
          topicArea: "education",
        },
        {
          en: "I doubt the recipe will turn out well.",
          bn: "আমার সন্দেহ রেসিপিটা ভালো হবে।",
          slotValues: { CLAUSE: "the recipe will turn out well" },
          topicArea: "food",
        },
        {
          en: "I doubt she's feeling well enough to travel.",
          bn: "আমার সন্দেহ সে ভ্রমণের জন্য যথেষ্ট ভালো অনুভব করছে।",
          slotValues: { CLAUSE: "she's feeling well enough to travel" },
          topicArea: "health",
        },
        {
          en: "I doubt he'll apologize.",
          bn: "আমার সন্দেহ সে ক্ষমা চাইবে।",
          slotValues: { CLAUSE: "he'll apologize" },
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'I doubt' expresses skepticism. It means you think something is unlikely to be true or happen.",
      usageNote_bn:
        "'I doubt' সন্দেহ প্রকাশ করে। এটি বোঝায় আপনি মনে করেন কিছু সত্য হওয়া বা ঘটার সম্ভাবনা কম।",
      combinableWith: ["D4.2"],
      banglaStructureMap:
        "আমার সন্দেহ (Subject + Noun) + [CLAUSE] (Subordinate clause)",
    },
    {
      id: "D4.4",
      formula: "There's no doubt that [CLAUSE]",
      formula_bn: "কোনো সন্দেহ নেই যে [বাক্যাংশ]",
      patternName: "Absolute Certainty",
      patternName_bn: "পরম নিশ্চয়তা",
      slots: [
        {
          name: "CLAUSE",
          description: "A clause describing what is absolutely certain",
          description_bn: "একটি উপবাক্য যা সম্পূর্ণ নিশ্চিত বিষয় বর্ণনা করে",
          acceptedTypes: ["clause"],
          examples: [
            "she's talented",
            "education is important",
            "he worked hard",
          ],
        },
      ],
      examples: [
        {
          en: "There's no doubt that she's talented.",
          bn: "কোনো সন্দেহ নেই যে সে প্রতিভাবান।",
          slotValues: { CLAUSE: "she's talented" },
          topicArea: "education",
        },
        {
          en: "There's no doubt that education is important.",
          bn: "কোনো সন্দেহ নেই যে শিক্ষা গুরুত্বপূর্ণ।",
          slotValues: { CLAUSE: "education is important" },
          topicArea: "education",
        },
        {
          en: "There's no doubt that he worked hard for this.",
          bn: "কোনো সন্দেহ নেই যে সে এর জন্য কঠোর পরিশ্রম করেছে।",
          slotValues: { CLAUSE: "he worked hard for this" },
          topicArea: "work",
        },
        {
          en: "There's no doubt that the food here is excellent.",
          bn: "কোনো সন্দেহ নেই যে এখানকার খাবার চমৎকার।",
          slotValues: { CLAUSE: "the food here is excellent" },
          topicArea: "food",
        },
        {
          en: "There's no doubt that exercise is good for you.",
          bn: "কোনো সন্দেহ নেই যে ব্যায়াম আপনার জন্য ভালো।",
          slotValues: { CLAUSE: "exercise is good for you" },
          topicArea: "health",
        },
        {
          en: "There's no doubt that Dhaka is a busy city.",
          bn: "কোনো সন্দেহ নেই যে ঢাকা একটি ব্যস্ত শহর।",
          slotValues: { CLAUSE: "Dhaka is a busy city" },
          topicArea: "travel",
        },
        {
          en: "There's no doubt that this product is worth the price.",
          bn: "কোনো সন্দেহ নেই যে এই পণ্যটি দামের তুলনায় যোগ্য।",
          slotValues: { CLAUSE: "this product is worth the price" },
          topicArea: "shopping",
        },
        {
          en: "There's no doubt that they love each other.",
          bn: "কোনো সন্দেহ নেই যে তারা একে অপরকে ভালোবাসে।",
          slotValues: { CLAUSE: "they love each other" },
          topicArea: "relationships",
        },
        {
          en: "There's no doubt that the team did their best.",
          bn: "কোনো সন্দেহ নেই যে দলটি তাদের সর্বোচ্চ চেষ্টা করেছে।",
          slotValues: { CLAUSE: "the team did their best" },
          topicArea: "work",
        },
        {
          en: "There's no doubt that technology has changed our lives.",
          bn: "কোনো সন্দেহ নেই যে প্রযুক্তি আমাদের জীবন বদলে দিয়েছে।",
          slotValues: { CLAUSE: "technology has changed our lives" },
          topicArea: "daily_life",
        },
        {
          en: "There's no doubt that fresh vegetables are healthier.",
          bn: "কোনো সন্দেহ নেই যে তাজা সবজি বেশি স্বাস্থ্যকর।",
          slotValues: { CLAUSE: "fresh vegetables are healthier" },
          topicArea: "food",
        },
        {
          en: "There's no doubt that reading improves your vocabulary.",
          bn: "কোনো সন্দেহ নেই যে পড়া আপনার শব্দভান্ডার উন্নত করে।",
          slotValues: { CLAUSE: "reading improves your vocabulary" },
          topicArea: "education",
        },
        {
          en: "There's no doubt that clean water is essential.",
          bn: "কোনো সন্দেহ নেই যে বিশুদ্ধ পানি অপরিহার্য।",
          slotValues: { CLAUSE: "clean water is essential" },
          topicArea: "health",
        },
        {
          en: "There's no doubt that this place is beautiful.",
          bn: "কোনো সন্দেহ নেই যে এই জায়গাটি সুন্দর।",
          slotValues: { CLAUSE: "this place is beautiful" },
          topicArea: "travel",
        },
        {
          en: "There's no doubt that family support matters.",
          bn: "কোনো সন্দেহ নেই যে পারিবারিক সমর্থন গুরুত্বপূর্ণ।",
          slotValues: { CLAUSE: "family support matters" },
          topicArea: "relationships",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "'There's no doubt that' is a strong, emphatic way to state certainty. It's often used to make a convincing point.",
      usageNote_bn:
        "'There's no doubt that' নিশ্চয়তা বলার একটি শক্তিশালী, জোরালো উপায়। এটি প্রায়ই বিশ্বাসযোগ্য যুক্তি দিতে ব্যবহৃত হয়।",
      combinableWith: ["D4.1"],
      banglaStructureMap:
        "কোনো সন্দেহ নেই (Intro) + যে (Conjunction) + [CLAUSE] (Subordinate clause)",
    },
    {
      id: "D4.5",
      formula: "I bet [CLAUSE]",
      formula_bn: "আমি বাজি ধরে বলতে পারি [বাক্যাংশ]",
      patternName: "Confident Prediction (Informal)",
      patternName_bn: "আত্মবিশ্বাসী পূর্বাভাস (অনানুষ্ঠানিক)",
      slots: [
        {
          name: "CLAUSE",
          description: "A clause describing a confident guess or prediction",
          description_bn: "একটি উপবাক্য যা আত্মবিশ্বাসী অনুমান বা পূর্বাভাস বর্ণনা করে",
          acceptedTypes: ["clause"],
          examples: [
            "it's going to rain",
            "she forgot",
            "the traffic is terrible right now",
          ],
        },
      ],
      examples: [
        {
          en: "I bet it's going to rain.",
          bn: "আমি বাজি ধরে বলতে পারি বৃষ্টি হবে।",
          slotValues: { CLAUSE: "it's going to rain" },
          topicArea: "daily_life",
        },
        {
          en: "I bet she forgot about the meeting.",
          bn: "আমি বাজি ধরে বলতে পারি সে মিটিংয়ের কথা ভুলে গেছে।",
          slotValues: { CLAUSE: "she forgot about the meeting" },
          topicArea: "work",
        },
        {
          en: "I bet the traffic is terrible right now.",
          bn: "আমি বাজি ধরে বলতে পারি এখন যানজট ভয়ংকর।",
          slotValues: { CLAUSE: "the traffic is terrible right now" },
          topicArea: "travel",
        },
        {
          en: "I bet you're tired after that long flight.",
          bn: "আমি বাজি ধরে বলতে পারি দীর্ঘ ফ্লাইটের পর তুমি ক্লান্ত।",
          slotValues: { CLAUSE: "you're tired after that long flight" },
          topicArea: "travel",
        },
        {
          en: "I bet the kids are hungry.",
          bn: "আমি বাজি ধরে বলতে পারি বাচ্চারা ক্ষুধার্ত।",
          slotValues: { CLAUSE: "the kids are hungry" },
          topicArea: "food",
        },
        {
          en: "I bet he didn't study for the test.",
          bn: "আমি বাজি ধরে বলতে পারি সে পরীক্ষার জন্য পড়েনি।",
          slotValues: { CLAUSE: "he didn't study for the test" },
          topicArea: "education",
        },
        {
          en: "I bet you feel much better now.",
          bn: "আমি বাজি ধরে বলতে পারি তুমি এখন অনেক ভালো অনুভব করছ।",
          slotValues: { CLAUSE: "you feel much better now" },
          topicArea: "health",
        },
        {
          en: "I bet the price will go down next month.",
          bn: "আমি বাজি ধরে বলতে পারি আগামী মাসে দাম কমবে।",
          slotValues: { CLAUSE: "the price will go down next month" },
          topicArea: "shopping",
        },
        {
          en: "I bet he's really happy about the promotion.",
          bn: "আমি বাজি ধরে বলতে পারি সে পদোন্নতিতে সত্যিই খুশি।",
          slotValues: { CLAUSE: "he's really happy about the promotion" },
          topicArea: "work",
        },
        {
          en: "I bet they'll be surprised to see us.",
          bn: "আমি বাজি ধরে বলতে পারি আমাদের দেখে তারা অবাক হবে।",
          slotValues: { CLAUSE: "they'll be surprised to see us" },
          topicArea: "relationships",
        },
        {
          en: "I bet the biryani is amazing there.",
          bn: "আমি বাজি ধরে বলতে পারি ওখানকার বিরিয়ানি অসাধারণ।",
          slotValues: { CLAUSE: "the biryani is amazing there" },
          topicArea: "food",
        },
        {
          en: "I bet it was hard to learn that skill.",
          bn: "আমি বাজি ধরে বলতে পারি ওই দক্ষতা শেখা কঠিন ছিল।",
          slotValues: { CLAUSE: "it was hard to learn that skill" },
          topicArea: "education",
        },
        {
          en: "I bet she'll love the gift.",
          bn: "আমি বাজি ধরে বলতে পারি সে উপহারটি পছন্দ করবে।",
          slotValues: { CLAUSE: "she'll love the gift" },
          topicArea: "relationships",
        },
        {
          en: "I bet the gym is crowded in the evening.",
          bn: "আমি বাজি ধরে বলতে পারি সন্ধ্যায় জিম ভিড় থাকে।",
          slotValues: { CLAUSE: "the gym is crowded in the evening" },
          topicArea: "health",
        },
        {
          en: "I bet you can't find this cheaper anywhere else.",
          bn: "আমি বাজি ধরে বলতে পারি অন্য কোথাও এর চেয়ে সস্তায় পাবে না।",
          slotValues: { CLAUSE: "you can't find this cheaper anywhere else" },
          topicArea: "shopping",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'I bet' is an informal way to express confidence about a prediction. It doesn't literally mean gambling.",
      usageNote_bn:
        "'I bet' পূর্বাভাসে আত্মবিশ্বাস প্রকাশের একটি অনানুষ্ঠানিক উপায়। এটি আক্ষরিক অর্থে জুয়া বোঝায় না।",
      combinableWith: ["D4.1"],
      banglaStructureMap:
        "আমি বাজি ধরে বলতে পারি (Intro) + [CLAUSE] (Main clause)",
    },
    {
      id: "D4.6",
      formula: "I'm convinced that [CLAUSE]",
      formula_bn: "আমি নিশ্চিত যে [বাক্যাংশ]",
      patternName: "Strong Conviction (Convinced That)",
      patternName_bn: "দৃঢ় প্রত্যয় (নিশ্চিত যে)",
      slots: [
        {
          name: "CLAUSE",
          description: "A clause describing what you are firmly convinced about",
          description_bn: "একটি উপবাক্য যা আপনি কী সম্পর্কে দৃঢ়ভাবে নিশ্চিত তা বর্ণনা করে",
          acceptedTypes: ["clause"],
          examples: [
            "he's innocent",
            "it will work",
            "we made the right decision",
          ],
        },
      ],
      examples: [
        {
          en: "I'm convinced that he's innocent.",
          bn: "আমি নিশ্চিত যে সে নির্দোষ।",
          slotValues: { CLAUSE: "he's innocent" },
          topicArea: "daily_life",
        },
        {
          en: "She's convinced that it will work.",
          bn: "সে নিশ্চিত যে এটা কাজ করবে।",
          slotValues: { CLAUSE: "it will work" },
          topicArea: "work",
        },
        {
          en: "I'm convinced we made the right decision.",
          bn: "আমি নিশ্চিত আমরা সঠিক সিদ্ধান্ত নিয়েছি।",
          slotValues: { CLAUSE: "we made the right decision" },
          topicArea: "daily_life",
        },
        {
          en: "He's convinced that the exam will be easy.",
          bn: "সে নিশ্চিত যে পরীক্ষা সহজ হবে।",
          slotValues: { CLAUSE: "the exam will be easy" },
          topicArea: "education",
        },
        {
          en: "I'm convinced that exercise is the best medicine.",
          bn: "আমি নিশ্চিত যে ব্যায়াম সেরা ওষুধ।",
          slotValues: { CLAUSE: "exercise is the best medicine" },
          topicArea: "health",
        },
        {
          en: "She's convinced that homemade food is healthier.",
          bn: "সে নিশ্চিত যে ঘরে তৈরি খাবার বেশি স্বাস্থ্যকর।",
          slotValues: { CLAUSE: "homemade food is healthier" },
          topicArea: "food",
        },
        {
          en: "I'm convinced that this is the best route.",
          bn: "আমি নিশ্চিত যে এটাই সেরা পথ।",
          slotValues: { CLAUSE: "this is the best route" },
          topicArea: "travel",
        },
        {
          en: "He's convinced that the product is worth the price.",
          bn: "সে নিশ্চিত যে পণ্যটি দামের যোগ্য।",
          slotValues: { CLAUSE: "the product is worth the price" },
          topicArea: "shopping",
        },
        {
          en: "I'm convinced that she'll forgive him eventually.",
          bn: "আমি নিশ্চিত যে সে শেষ পর্যন্ত তাকে ক্ষমা করবে।",
          slotValues: { CLAUSE: "she'll forgive him eventually" },
          topicArea: "relationships",
        },
        {
          en: "I'm convinced that hard work always pays off.",
          bn: "আমি নিশ্চিত যে কঠোর পরিশ্রমের ফল সবসময় পাওয়া যায়।",
          slotValues: { CLAUSE: "hard work always pays off" },
          topicArea: "work",
        },
        {
          en: "She's convinced that the treatment will help.",
          bn: "সে নিশ্চিত যে চিকিৎসা কাজে আসবে।",
          slotValues: { CLAUSE: "the treatment will help" },
          topicArea: "health",
        },
        {
          en: "I'm convinced that this university is the best choice.",
          bn: "আমি নিশ্চিত যে এই বিশ্ববিদ্যালয় সেরা পছন্দ।",
          slotValues: { CLAUSE: "this university is the best choice" },
          topicArea: "education",
        },
        {
          en: "He's convinced that they're hiding something.",
          bn: "সে নিশ্চিত যে তারা কিছু লুকাচ্ছে।",
          slotValues: { CLAUSE: "they're hiding something" },
          topicArea: "relationships",
        },
        {
          en: "I'm convinced that this deal is too good to be true.",
          bn: "আমি নিশ্চিত যে এই চুক্তিটা সত্য হওয়ার জন্য অনেক ভালো।",
          slotValues: { CLAUSE: "this deal is too good to be true" },
          topicArea: "shopping",
        },
        {
          en: "I'm convinced that the train is faster than driving.",
          bn: "আমি নিশ্চিত যে গাড়ি চালানোর চেয়ে ট্রেন দ্রুত।",
          slotValues: { CLAUSE: "the train is faster than driving" },
          topicArea: "travel",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "'I'm convinced that' expresses a very strong belief. It's stronger than 'I'm sure' and implies you've thought carefully about it.",
      usageNote_bn:
        "'I'm convinced that' খুব দৃঢ় বিশ্বাস প্রকাশ করে। এটি 'I'm sure' এর চেয়ে শক্তিশালী এবং বোঝায় যে আপনি সাবধানে চিন্তা করেছেন।",
      combinableWith: ["D4.1", "D4.4"],
      banglaStructureMap:
        "আমি নিশ্চিত (Subject + Adj) + যে (Conjunction) + [CLAUSE] (Subordinate clause)",
    },
  ],
};
