import { PatternCategory } from "@/types/pattern";

export const categoryD7: PatternCategory = {
  id: "D7",
  slug: "expressing-expectations",
  name: "Expressing Expectations",
  name_bn: "প্রত্যাশা প্রকাশ করা",
  description:
    "Learn how to talk about what you expected to happen and what was supposed to happen in English.",
  description_bn:
    "ইংরেজিতে আপনি কী হবে বলে আশা করেছিলেন এবং কী হওয়ার কথা ছিল সে সম্পর্কে কথা বলতে শিখুন।",
  icon: "🔮",
  group: "D",
  groupName: "Ability, Obligation & Possibility",
  groupName_bn: "সক্ষমতা, বাধ্যবাধকতা এবং সম্ভাবনা",
  difficulty: "intermediate",
  patterns: [
    {
      id: "D7.1",
      formula: "I'm supposed to [ACTION]",
      formula_bn: "আমার [কাজ] করার কথা",
      patternName: "Current Expectation",
      patternName_bn: "বর্তমান প্রত্যাশা",
      slots: [
        {
          name: "ACTION",
          description: "A base verb or verb phrase describing what is expected of you now",
          description_bn: "একটি মূল ক্রিয়া বা ক্রিয়া পদবন্ধ যা এখন আপনার কাছ থেকে প্রত্যাশিত",
          acceptedTypes: ["verb"],
          examples: ["be at work by nine", "pick him up", "present the report"],
        },
      ],
      examples: [
        {
          en: "I'm supposed to be at work by nine.",
          bn: "আমার নয়টার মধ্যে কর্মস্থলে থাকার কথা।",
          slotValues: { ACTION: "be at work by nine" },
          topicArea: "work",
        },
        {
          en: "I'm supposed to pick him up from school.",
          bn: "আমার তাকে স্কুল থেকে নিয়ে আসার কথা।",
          slotValues: { ACTION: "pick him up from school" },
          topicArea: "relationships",
        },
        {
          en: "I'm supposed to present the report today.",
          bn: "আমার আজ রিপোর্ট উপস্থাপন করার কথা।",
          slotValues: { ACTION: "present the report today" },
          topicArea: "work",
        },
        {
          en: "I'm supposed to take a test this afternoon.",
          bn: "আমার আজ বিকেলে পরীক্ষা দেওয়ার কথা।",
          slotValues: { ACTION: "take a test this afternoon" },
          topicArea: "education",
        },
        {
          en: "I'm supposed to avoid fried food.",
          bn: "আমার ভাজা খাবার এড়িয়ে চলার কথা।",
          slotValues: { ACTION: "avoid fried food" },
          topicArea: "health",
        },
        {
          en: "I'm supposed to check in at the hotel by three.",
          bn: "আমার তিনটার মধ্যে হোটেলে চেক ইন করার কথা।",
          slotValues: { ACTION: "check in at the hotel by three" },
          topicArea: "travel",
        },
        {
          en: "I'm supposed to bring dessert to the party.",
          bn: "আমার পার্টিতে মিষ্টি নিয়ে যাওয়ার কথা।",
          slotValues: { ACTION: "bring dessert to the party" },
          topicArea: "food",
        },
        {
          en: "I'm supposed to return the dress today.",
          bn: "আমার আজ পোশাকটি ফেরত দেওয়ার কথা।",
          slotValues: { ACTION: "return the dress today" },
          topicArea: "shopping",
        },
        {
          en: "I'm supposed to call the doctor's office.",
          bn: "আমার ডাক্তারের অফিসে ফোন করার কথা।",
          slotValues: { ACTION: "call the doctor's office" },
          topicArea: "health",
        },
        {
          en: "I'm supposed to meet my friend at the café.",
          bn: "আমার বন্ধুর সাথে ক্যাফেতে দেখা করার কথা।",
          slotValues: { ACTION: "meet my friend at the café" },
          topicArea: "relationships",
        },
        {
          en: "I'm supposed to finish reading this chapter.",
          bn: "আমার এই অধ্যায় পড়া শেষ করার কথা।",
          slotValues: { ACTION: "finish reading this chapter" },
          topicArea: "education",
        },
        {
          en: "I'm supposed to water the plants.",
          bn: "আমার গাছে পানি দেওয়ার কথা।",
          slotValues: { ACTION: "water the plants" },
          topicArea: "daily_life",
        },
        {
          en: "I'm supposed to take the bus to the airport.",
          bn: "আমার বাসে করে বিমানবন্দরে যাওয়ার কথা।",
          slotValues: { ACTION: "take the bus to the airport" },
          topicArea: "travel",
        },
        {
          en: "I'm supposed to send the email by noon.",
          bn: "আমার দুপুরের মধ্যে ইমেইলটি পাঠানোর কথা।",
          slotValues: { ACTION: "send the email by noon" },
          topicArea: "work",
        },
        {
          en: "I'm supposed to cook for the family tonight.",
          bn: "আমার আজ রাতে পরিবারের জন্য রান্না করার কথা।",
          slotValues: { ACTION: "cook for the family tonight" },
          topicArea: "food",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'I'm supposed to' indicates an expectation or arrangement. It often implies you may not want to or might not actually do it.",
      usageNote_bn:
        "'I'm supposed to' একটি প্রত্যাশা বা ব্যবস্থা নির্দেশ করে। এটি প্রায়ই বোঝায় আপনি হয়তো চান না বা আসলে নাও করতে পারেন।",
      combinableWith: ["D7.2"],
      banglaStructureMap:
        "আমার (Subject) + [ACTION] (Object) + করার কথা (Verb + Noun)",
    },
    {
      id: "D7.2",
      formula: "I'm expected to [ACTION]",
      formula_bn: "আমার কাছে [কাজ] করা আশা করা হয়",
      patternName: "Formal Expectation",
      patternName_bn: "আনুষ্ঠানিক প্রত্যাশা",
      slots: [
        {
          name: "ACTION",
          description: "A base verb or verb phrase describing a formal expectation placed on you",
          description_bn: "একটি মূল ক্রিয়া বা ক্রিয়া পদবন্ধ যা আপনার উপর আনুষ্ঠানিক প্রত্যাশা বর্ণনা করে",
          acceptedTypes: ["verb"],
          examples: ["deliver results", "attend all sessions", "maintain standards"],
        },
      ],
      examples: [
        {
          en: "I'm expected to deliver results by the end of the month.",
          bn: "আমার কাছে মাসের শেষে ফলাফল দেওয়া আশা করা হয়।",
          slotValues: { ACTION: "deliver results by the end of the month" },
          topicArea: "work",
        },
        {
          en: "I'm expected to attend all the sessions.",
          bn: "আমার কাছে সব সেশনে উপস্থিত থাকা আশা করা হয়।",
          slotValues: { ACTION: "attend all the sessions" },
          topicArea: "education",
        },
        {
          en: "I'm expected to maintain high standards.",
          bn: "আমার কাছে উচ্চ মান বজায় রাখা আশা করা হয়।",
          slotValues: { ACTION: "maintain high standards" },
          topicArea: "work",
        },
        {
          en: "I'm expected to look after my younger siblings.",
          bn: "আমার কাছে ছোট ভাইবোনদের দেখাশোনা করা আশা করা হয়।",
          slotValues: { ACTION: "look after my younger siblings" },
          topicArea: "relationships",
        },
        {
          en: "I'm expected to follow a strict diet.",
          bn: "আমার কাছে কঠোর ডায়েট মেনে চলা আশা করা হয়।",
          slotValues: { ACTION: "follow a strict diet" },
          topicArea: "health",
        },
        {
          en: "I'm expected to represent the company abroad.",
          bn: "আমার কাছে বিদেশে কোম্পানির প্রতিনিধিত্ব করা আশা করা হয়।",
          slotValues: { ACTION: "represent the company abroad" },
          topicArea: "travel",
        },
        {
          en: "I'm expected to prepare meals for the guests.",
          bn: "আমার কাছে অতিথিদের জন্য খাবার তৈরি করা আশা করা হয়।",
          slotValues: { ACTION: "prepare meals for the guests" },
          topicArea: "food",
        },
        {
          en: "I'm expected to manage the budget carefully.",
          bn: "আমার কাছে সাবধানে বাজেট পরিচালনা করা আশা করা হয়।",
          slotValues: { ACTION: "manage the budget carefully" },
          topicArea: "shopping",
        },
        {
          en: "I'm expected to complete the training program.",
          bn: "আমার কাছে প্রশিক্ষণ কর্মসূচি সম্পন্ন করা আশা করা হয়।",
          slotValues: { ACTION: "complete the training program" },
          topicArea: "education",
        },
        {
          en: "I'm expected to work overtime this week.",
          bn: "আমার কাছে এই সপ্তাহে ওভারটাইম করা আশা করা হয়।",
          slotValues: { ACTION: "work overtime this week" },
          topicArea: "work",
        },
        {
          en: "I'm expected to keep the house clean.",
          bn: "আমার কাছে ঘর পরিষ্কার রাখা আশা করা হয়।",
          slotValues: { ACTION: "keep the house clean" },
          topicArea: "daily_life",
        },
        {
          en: "I'm expected to exercise regularly after the surgery.",
          bn: "আমার কাছে অপারেশনের পর নিয়মিত ব্যায়াম করা আশা করা হয়।",
          slotValues: { ACTION: "exercise regularly after the surgery" },
          topicArea: "health",
        },
        {
          en: "I'm expected to guide the new employees.",
          bn: "আমার কাছে নতুন কর্মীদের পথ দেখানো আশা করা হয়।",
          slotValues: { ACTION: "guide the new employees" },
          topicArea: "work",
        },
        {
          en: "I'm expected to arrange the venue for the event.",
          bn: "আমার কাছে অনুষ্ঠানের জন্য ভেন্যু সাজানো আশা করা হয়।",
          slotValues: { ACTION: "arrange the venue for the event" },
          topicArea: "relationships",
        },
        {
          en: "I'm expected to submit my thesis by March.",
          bn: "আমার কাছে মার্চের মধ্যে থিসিস জমা দেওয়া আশা করা হয়।",
          slotValues: { ACTION: "submit my thesis by March" },
          topicArea: "education",
        },
      ],
      formality: "formal",
      difficulty: "intermediate",
      usageNote:
        "'I'm expected to' sounds more formal and implies external pressure from an organization or society.",
      usageNote_bn:
        "'I'm expected to' বেশি আনুষ্ঠানিক শোনায় এবং সংস্থা বা সমাজ থেকে বাহ্যিক চাপ বোঝায়।",
      combinableWith: ["D7.1"],
      banglaStructureMap:
        "আমার কাছে (Subject) + [ACTION] (Object) + করা আশা করা হয় (Passive Verb)",
    },
    {
      id: "D7.3",
      formula: "[THING] was supposed to [HAPPEN]",
      formula_bn: "[জিনিস]-এর [ঘটনা] হওয়ার কথা ছিল",
      patternName: "Unmet Expectation",
      patternName_bn: "অপূর্ণ প্রত্যাশা",
      slots: [
        {
          name: "THING",
          description: "A noun or noun phrase representing the subject",
          description_bn: "একটি বিশেষ্য বা বিশেষ্য পদবন্ধ যা কর্তা প্রতিনিধিত্ব করে",
          acceptedTypes: ["noun"],
          examples: ["The bus", "The package", "The meeting"],
        },
        {
          name: "HAPPEN",
          description: "A base verb or verb phrase describing the expected outcome",
          description_bn: "একটি মূল ক্রিয়া বা ক্রিয়া পদবন্ধ যা প্রত্যাশিত ফলাফল বর্ণনা করে",
          acceptedTypes: ["verb"],
          examples: ["arrive at ten", "arrive yesterday", "start at three"],
        },
      ],
      examples: [
        {
          en: "The bus was supposed to arrive at ten.",
          bn: "বাসটির দশটায় আসার কথা ছিল।",
          slotValues: { THING: "The bus", HAPPEN: "arrive at ten" },
          topicArea: "travel",
        },
        {
          en: "The package was supposed to arrive yesterday.",
          bn: "প্যাকেজটি গতকাল পৌঁছানোর কথা ছিল।",
          slotValues: { THING: "The package", HAPPEN: "arrive yesterday" },
          topicArea: "shopping",
        },
        {
          en: "The meeting was supposed to start at three.",
          bn: "মিটিংটি তিনটায় শুরু হওয়ার কথা ছিল।",
          slotValues: { THING: "The meeting", HAPPEN: "start at three" },
          topicArea: "work",
        },
        {
          en: "The exam was supposed to be easy.",
          bn: "পরীক্ষাটি সহজ হওয়ার কথা ছিল।",
          slotValues: { THING: "The exam", HAPPEN: "be easy" },
          topicArea: "education",
        },
        {
          en: "The medicine was supposed to work by now.",
          bn: "ওষুধটির এতক্ষণে কাজ করার কথা ছিল।",
          slotValues: { THING: "The medicine", HAPPEN: "work by now" },
          topicArea: "health",
        },
        {
          en: "The restaurant was supposed to open at noon.",
          bn: "রেস্তোরাঁটি দুপুরে খোলার কথা ছিল।",
          slotValues: { THING: "The restaurant", HAPPEN: "open at noon" },
          topicArea: "food",
        },
        {
          en: "The weather was supposed to be sunny today.",
          bn: "আজ আবহাওয়া রোদেলা হওয়ার কথা ছিল।",
          slotValues: { THING: "The weather", HAPPEN: "be sunny today" },
          topicArea: "daily_life",
        },
        {
          en: "The project was supposed to be finished last week.",
          bn: "প্রকল্পটি গত সপ্তাহে শেষ হওয়ার কথা ছিল।",
          slotValues: { THING: "The project", HAPPEN: "be finished last week" },
          topicArea: "work",
        },
        {
          en: "The flight was supposed to depart at six.",
          bn: "ফ্লাইটটি ছয়টায় ছাড়ার কথা ছিল।",
          slotValues: { THING: "The flight", HAPPEN: "depart at six" },
          topicArea: "travel",
        },
        {
          en: "The class was supposed to end at four.",
          bn: "ক্লাস চারটায় শেষ হওয়ার কথা ছিল।",
          slotValues: { THING: "The class", HAPPEN: "end at four" },
          topicArea: "education",
        },
        {
          en: "The delivery was supposed to be free.",
          bn: "ডেলিভারি বিনামূল্যে হওয়ার কথা ছিল।",
          slotValues: { THING: "The delivery", HAPPEN: "be free" },
          topicArea: "shopping",
        },
        {
          en: "The pain was supposed to go away after the treatment.",
          bn: "চিকিৎসার পর ব্যথা চলে যাওয়ার কথা ছিল।",
          slotValues: { THING: "The pain", HAPPEN: "go away after the treatment" },
          topicArea: "health",
        },
        {
          en: "The cake was supposed to be chocolate flavored.",
          bn: "কেকটি চকলেট স্বাদের হওয়ার কথা ছিল।",
          slotValues: { THING: "The cake", HAPPEN: "be chocolate flavored" },
          topicArea: "food",
        },
        {
          en: "The party was supposed to be a surprise.",
          bn: "পার্টিটি সারপ্রাইজ হওয়ার কথা ছিল।",
          slotValues: { THING: "The party", HAPPEN: "be a surprise" },
          topicArea: "relationships",
        },
        {
          en: "The repair was supposed to take only an hour.",
          bn: "মেরামতে মাত্র এক ঘণ্টা লাগার কথা ছিল।",
          slotValues: { THING: "The repair", HAPPEN: "take only an hour" },
          topicArea: "daily_life",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "This pattern expresses disappointment that something did not go as planned. The past tense of 'supposed to' implies the expectation was not met.",
      usageNote_bn:
        "এই প্যাটার্ন প্রকাশ করে যে কিছু পরিকল্পনামতো হয়নি তাতে হতাশা। 'Supposed to'-এর অতীত কাল বোঝায় প্রত্যাশা পূরণ হয়নি।",
      combinableWith: ["D7.4"],
      banglaStructureMap:
        "[THING]-এর (Subject) + [HAPPEN] (Complement) + হওয়ার কথা ছিল (Verb phrase)",
    },
    {
      id: "D7.4",
      formula: "I expected [PERSON] to [ACTION]",
      formula_bn: "আমি আশা করেছিলাম [ব্যক্তি] [কাজ] করবে",
      patternName: "Expecting Someone's Action",
      patternName_bn: "কারো কাজের প্রত্যাশা",
      slots: [
        {
          name: "PERSON",
          description: "A noun or pronoun referring to the person you expected something from",
          description_bn: "একটি বিশেষ্য বা সর্বনাম যা আপনি যার কাছ থেকে কিছু আশা করেছিলেন তাকে নির্দেশ করে",
          acceptedTypes: ["person", "noun"],
          examples: ["him", "my boss", "the teacher"],
        },
        {
          name: "ACTION",
          description: "A base verb or verb phrase describing the expected action",
          description_bn: "একটি মূল ক্রিয়া বা ক্রিয়া পদবন্ধ যা প্রত্যাশিত কাজ বর্ণনা করে",
          acceptedTypes: ["verb"],
          examples: ["help me", "arrive on time", "keep the promise"],
        },
      ],
      examples: [
        {
          en: "I expected him to help me.",
          bn: "আমি আশা করেছিলাম সে আমাকে সাহায্য করবে।",
          slotValues: { PERSON: "him", ACTION: "help me" },
          topicArea: "relationships",
        },
        {
          en: "I expected my boss to approve the request.",
          bn: "আমি আশা করেছিলাম আমার বস অনুরোধটি অনুমোদন করবেন।",
          slotValues: { PERSON: "my boss", ACTION: "approve the request" },
          topicArea: "work",
        },
        {
          en: "I expected the teacher to explain it better.",
          bn: "আমি আশা করেছিলাম শিক্ষক এটি আরও ভালোভাবে ব্যাখ্যা করবেন।",
          slotValues: { PERSON: "the teacher", ACTION: "explain it better" },
          topicArea: "education",
        },
        {
          en: "I expected the doctor to call me back.",
          bn: "আমি আশা করেছিলাম ডাক্তার আমাকে আবার ফোন করবেন।",
          slotValues: { PERSON: "the doctor", ACTION: "call me back" },
          topicArea: "health",
        },
        {
          en: "I expected the waiter to bring the bill.",
          bn: "আমি আশা করেছিলাম ওয়েটার বিল আনবে।",
          slotValues: { PERSON: "the waiter", ACTION: "bring the bill" },
          topicArea: "food",
        },
        {
          en: "I expected the driver to know the way.",
          bn: "আমি আশা করেছিলাম ড্রাইভার রাস্তা চিনবে।",
          slotValues: { PERSON: "the driver", ACTION: "know the way" },
          topicArea: "travel",
        },
        {
          en: "I expected her to apologize.",
          bn: "আমি আশা করেছিলাম সে ক্ষমা চাইবে।",
          slotValues: { PERSON: "her", ACTION: "apologize" },
          topicArea: "relationships",
        },
        {
          en: "I expected the shop to offer a warranty.",
          bn: "আমি আশা করেছিলাম দোকান ওয়ারেন্টি দেবে।",
          slotValues: { PERSON: "the shop", ACTION: "offer a warranty" },
          topicArea: "shopping",
        },
        {
          en: "I expected my colleague to finish his part.",
          bn: "আমি আশা করেছিলাম আমার সহকর্মী তার অংশ শেষ করবে।",
          slotValues: { PERSON: "my colleague", ACTION: "finish his part" },
          topicArea: "work",
        },
        {
          en: "I expected the students to prepare for the quiz.",
          bn: "আমি আশা করেছিলাম ছাত্ররা কুইজের জন্য প্রস্তুতি নেবে।",
          slotValues: { PERSON: "the students", ACTION: "prepare for the quiz" },
          topicArea: "education",
        },
        {
          en: "I expected the nurse to explain the procedure.",
          bn: "আমি আশা করেছিলাম নার্স প্রক্রিয়াটি ব্যাখ্যা করবে।",
          slotValues: { PERSON: "the nurse", ACTION: "explain the procedure" },
          topicArea: "health",
        },
        {
          en: "I expected the hotel to have a pool.",
          bn: "আমি আশা করেছিলাম হোটেলে সুইমিং পুল থাকবে।",
          slotValues: { PERSON: "the hotel", ACTION: "have a pool" },
          topicArea: "travel",
        },
        {
          en: "I expected the chef to use fresh ingredients.",
          bn: "আমি আশা করেছিলাম শেফ তাজা উপাদান ব্যবহার করবে।",
          slotValues: { PERSON: "the chef", ACTION: "use fresh ingredients" },
          topicArea: "food",
        },
        {
          en: "I expected my friend to keep the secret.",
          bn: "আমি আশা করেছিলাম আমার বন্ধু গোপনীয়তা রক্ষা করবে।",
          slotValues: { PERSON: "my friend", ACTION: "keep the secret" },
          topicArea: "relationships",
        },
        {
          en: "I expected the seller to give a receipt.",
          bn: "আমি আশা করেছিলাম বিক্রেতা রসিদ দেবে।",
          slotValues: { PERSON: "the seller", ACTION: "give a receipt" },
          topicArea: "shopping",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "'I expected someone to' expresses that you had a specific expectation about someone's behavior. It often implies disappointment.",
      usageNote_bn:
        "'I expected someone to' প্রকাশ করে যে কারো আচরণ সম্পর্কে আপনার নির্দিষ্ট প্রত্যাশা ছিল। এটি প্রায়ই হতাশা বোঝায়।",
      combinableWith: ["D7.3"],
      banglaStructureMap:
        "আমি আশা করেছিলাম (Subject + Verb) + [PERSON] (Object) + [ACTION] করবে (Complement)",
    },
    {
      id: "D7.5",
      formula: "I was expecting [THING]",
      formula_bn: "আমি [জিনিস] আশা করছিলাম",
      patternName: "Expressing What You Anticipated",
      patternName_bn: "আপনি কী প্রত্যাশা করেছিলেন তা প্রকাশ",
      slots: [
        {
          name: "THING",
          description: "A noun, noun phrase, or clause describing what you anticipated",
          description_bn: "একটি বিশেষ্য, বিশেষ্য পদবন্ধ বা উপবাক্য যা আপনি কী প্রত্যাশা করেছিলেন তা বর্ণনা করে",
          acceptedTypes: ["noun", "clause"],
          examples: ["a bigger room", "better service", "more people"],
        },
      ],
      examples: [
        {
          en: "I was expecting a bigger room.",
          bn: "আমি আরও বড় ঘর আশা করছিলাম।",
          slotValues: { THING: "a bigger room" },
          topicArea: "travel",
        },
        {
          en: "I was expecting better service.",
          bn: "আমি আরও ভালো সেবা আশা করছিলাম।",
          slotValues: { THING: "better service" },
          topicArea: "food",
        },
        {
          en: "I was expecting more people at the event.",
          bn: "আমি অনুষ্ঠানে আরও বেশি মানুষ আশা করছিলাম।",
          slotValues: { THING: "more people at the event" },
          topicArea: "daily_life",
        },
        {
          en: "I was expecting a higher salary.",
          bn: "আমি আরও বেশি বেতন আশা করছিলাম।",
          slotValues: { THING: "a higher salary" },
          topicArea: "work",
        },
        {
          en: "I was expecting an easier exam.",
          bn: "আমি সহজ পরীক্ষা আশা করছিলাম।",
          slotValues: { THING: "an easier exam" },
          topicArea: "education",
        },
        {
          en: "I was expecting faster recovery.",
          bn: "আমি দ্রুত সুস্থতা আশা করছিলাম।",
          slotValues: { THING: "faster recovery" },
          topicArea: "health",
        },
        {
          en: "I was expecting a discount.",
          bn: "আমি ছাড় আশা করছিলাম।",
          slotValues: { THING: "a discount" },
          topicArea: "shopping",
        },
        {
          en: "I was expecting a warmer welcome.",
          bn: "আমি আরও উষ্ণ অভ্যর্থনা আশা করছিলাম।",
          slotValues: { THING: "a warmer welcome" },
          topicArea: "relationships",
        },
        {
          en: "I was expecting your call.",
          bn: "আমি তোমার ফোন আশা করছিলাম।",
          slotValues: { THING: "your call" },
          topicArea: "relationships",
        },
        {
          en: "I was expecting the delivery today.",
          bn: "আমি আজ ডেলিভারি আশা করছিলাম।",
          slotValues: { THING: "the delivery today" },
          topicArea: "shopping",
        },
        {
          en: "I was expecting a different result.",
          bn: "আমি ভিন্ন ফলাফল আশা করছিলাম।",
          slotValues: { THING: "a different result" },
          topicArea: "education",
        },
        {
          en: "I was expecting good weather for the trip.",
          bn: "আমি ভ্রমণের জন্য ভালো আবহাওয়া আশা করছিলাম।",
          slotValues: { THING: "good weather for the trip" },
          topicArea: "travel",
        },
        {
          en: "I was expecting a promotion this year.",
          bn: "আমি এই বছর পদোন্নতি আশা করছিলাম।",
          slotValues: { THING: "a promotion this year" },
          topicArea: "work",
        },
        {
          en: "I was expecting spicier food.",
          bn: "আমি আরও ঝালযুক্ত খাবার আশা করছিলাম।",
          slotValues: { THING: "spicier food" },
          topicArea: "food",
        },
        {
          en: "I was expecting fewer side effects.",
          bn: "আমি কম পার্শ্বপ্রতিক্রিয়া আশা করছিলাম।",
          slotValues: { THING: "fewer side effects" },
          topicArea: "health",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'I was expecting' uses the past continuous to describe an ongoing anticipation. It often implies reality didn't match the expectation.",
      usageNote_bn:
        "'I was expecting' চলমান প্রত্যাশা বর্ণনা করতে অতীত চলমান কাল ব্যবহার করে। এটি প্রায়ই বোঝায় বাস্তবতা প্রত্যাশার সাথে মিলেনি।",
      combinableWith: ["D7.3"],
      banglaStructureMap:
        "আমি (Subject) + [THING] (Object) + আশা করছিলাম (Verb)",
    },
  ],
};
