import { PatternCategory } from "@/types/pattern";

export const categoryE1: PatternCategory = {
  id: "E1",
  slug: "giving-opinions",
  name: "Giving Opinions",
  name_bn: "মতামত দেওয়া",
  description:
    "Learn how to express your opinions and thoughts clearly in English.",
  description_bn:
    "ইংরেজিতে আপনার মতামত ও চিন্তাভাবনা স্পষ্টভাবে প্রকাশ করতে শিখুন।",
  icon: "💭",
  group: "E",
  groupName: "Opinions, Emotions & Attitudes",
  groupName_bn: "মতামত, আবেগ এবং মনোভাব",
  difficulty: "intermediate",
  patterns: [
    {
      id: "E1.1",
      formula: "I think [CLAUSE]",
      formula_bn: "আমি মনে করি [বাক্যাংশ]",
      patternName: "Basic Opinion",
      patternName_bn: "সাধারণ মতামত",
      slots: [
        {
          name: "CLAUSE",
          description: "A clause expressing your opinion about something",
          description_bn: "একটি উপবাক্য যা কোনো বিষয়ে আপনার মতামত প্রকাশ করে",
          acceptedTypes: ["clause"],
          examples: [
            "it's a good idea",
            "we should leave early",
            "he's right",
          ],
        },
      ],
      examples: [
        {
          en: "I think it's a good idea.",
          bn: "আমি মনে করি এটা একটা ভালো আইডিয়া।",
          slotValues: { CLAUSE: "it's a good idea" },
          topicArea: "daily_life",
        },
        {
          en: "I think we should leave early.",
          bn: "আমি মনে করি আমাদের তাড়াতাড়ি রওনা দেওয়া উচিত।",
          slotValues: { CLAUSE: "we should leave early" },
          topicArea: "travel",
        },
        {
          en: "I think he's right.",
          bn: "আমি মনে করি সে ঠিক বলেছে।",
          slotValues: { CLAUSE: "he's right" },
          topicArea: "relationships",
        },
        {
          en: "I think this project needs more time.",
          bn: "আমি মনে করি এই প্রকল্পে আরও সময় দরকার।",
          slotValues: { CLAUSE: "this project needs more time" },
          topicArea: "work",
        },
        {
          en: "I think the exam was fair.",
          bn: "আমি মনে করি পরীক্ষাটি ন্যায্য ছিল।",
          slotValues: { CLAUSE: "the exam was fair" },
          topicArea: "education",
        },
        {
          en: "I think this restaurant has the best biryani.",
          bn: "আমি মনে করি এই রেস্তোরাঁর বিরিয়ানি সবচেয়ে ভালো।",
          slotValues: { CLAUSE: "this restaurant has the best biryani" },
          topicArea: "food",
        },
        {
          en: "I think walking is better than taking a car.",
          bn: "আমি মনে করি গাড়ি নেওয়ার চেয়ে হাঁটা ভালো।",
          slotValues: { CLAUSE: "walking is better than taking a car" },
          topicArea: "health",
        },
        {
          en: "I think online shopping saves time.",
          bn: "আমি মনে করি অনলাইন শপিং সময় বাঁচায়।",
          slotValues: { CLAUSE: "online shopping saves time" },
          topicArea: "shopping",
        },
        {
          en: "I think the weather will improve.",
          bn: "আমি মনে করি আবহাওয়া ভালো হবে।",
          slotValues: { CLAUSE: "the weather will improve" },
          topicArea: "daily_life",
        },
        {
          en: "I think the team did a great job.",
          bn: "আমি মনে করি দলটি দারুণ কাজ করেছে।",
          slotValues: { CLAUSE: "the team did a great job" },
          topicArea: "work",
        },
        {
          en: "I think children should read more books.",
          bn: "আমি মনে করি শিশুদের আরও বই পড়া উচিত।",
          slotValues: { CLAUSE: "children should read more books" },
          topicArea: "education",
        },
        {
          en: "I think Cox's Bazar is worth visiting.",
          bn: "আমি মনে করি কক্সবাজার দেখার যোগ্য।",
          slotValues: { CLAUSE: "Cox's Bazar is worth visiting" },
          topicArea: "travel",
        },
        {
          en: "I think home-cooked food is healthier.",
          bn: "আমি মনে করি ঘরে রান্না করা খাবার বেশি স্বাস্থ্যকর।",
          slotValues: { CLAUSE: "home-cooked food is healthier" },
          topicArea: "food",
        },
        {
          en: "I think she needs more support from the family.",
          bn: "আমি মনে করি তার পরিবার থেকে আরও সমর্থন দরকার।",
          slotValues: { CLAUSE: "she needs more support from the family" },
          topicArea: "relationships",
        },
        {
          en: "I think yoga helps with stress.",
          bn: "আমি মনে করি যোগব্যায়াম মানসিক চাপে সাহায্য করে।",
          slotValues: { CLAUSE: "yoga helps with stress" },
          topicArea: "health",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'I think' is the most common and versatile way to introduce an opinion. It's suitable for almost any context.",
      usageNote_bn:
        "'I think' মতামত উপস্থাপনের সবচেয়ে সাধারণ এবং বহুমুখী উপায়। এটি প্রায় যেকোনো প্রসঙ্গে উপযুক্ত।",
      combinableWith: ["E1.4"],
      banglaStructureMap:
        "আমি মনে করি (Subject + Verb) + [CLAUSE] (Subordinate clause)",
    },
    {
      id: "E1.2",
      formula: "In my opinion, [CLAUSE]",
      formula_bn: "আমার মতে, [বাক্যাংশ]",
      patternName: "Formal Opinion",
      patternName_bn: "আনুষ্ঠানিক মতামত",
      slots: [
        {
          name: "CLAUSE",
          description: "A clause expressing your considered opinion",
          description_bn: "একটি উপবাক্য যা আপনার সুচিন্তিত মতামত প্রকাশ করে",
          acceptedTypes: ["clause"],
          examples: [
            "this is the best solution",
            "the policy needs revision",
            "everyone deserves a second chance",
          ],
        },
      ],
      examples: [
        {
          en: "In my opinion, this is the best solution.",
          bn: "আমার মতে, এটাই সেরা সমাধান।",
          slotValues: { CLAUSE: "this is the best solution" },
          topicArea: "work",
        },
        {
          en: "In my opinion, the policy needs revision.",
          bn: "আমার মতে, নীতিটি সংশোধন প্রয়োজন।",
          slotValues: { CLAUSE: "the policy needs revision" },
          topicArea: "work",
        },
        {
          en: "In my opinion, everyone deserves a second chance.",
          bn: "আমার মতে, সবাই দ্বিতীয় সুযোগ পাওয়ার যোগ্য।",
          slotValues: { CLAUSE: "everyone deserves a second chance" },
          topicArea: "relationships",
        },
        {
          en: "In my opinion, public transport should be improved.",
          bn: "আমার মতে, গণপরিবহন উন্নত করা উচিত।",
          slotValues: { CLAUSE: "public transport should be improved" },
          topicArea: "travel",
        },
        {
          en: "In my opinion, the exam was too difficult.",
          bn: "আমার মতে, পরীক্ষাটি অনেক কঠিন ছিল।",
          slotValues: { CLAUSE: "the exam was too difficult" },
          topicArea: "education",
        },
        {
          en: "In my opinion, this dish needs more salt.",
          bn: "আমার মতে, এই খাবারে আরও লবণ দরকার।",
          slotValues: { CLAUSE: "this dish needs more salt" },
          topicArea: "food",
        },
        {
          en: "In my opinion, prevention is better than cure.",
          bn: "আমার মতে, প্রতিকারের চেয়ে প্রতিরোধ ভালো।",
          slotValues: { CLAUSE: "prevention is better than cure" },
          topicArea: "health",
        },
        {
          en: "In my opinion, quality matters more than price.",
          bn: "আমার মতে, দামের চেয়ে মান বেশি গুরুত্বপূর্ণ।",
          slotValues: { CLAUSE: "quality matters more than price" },
          topicArea: "shopping",
        },
        {
          en: "In my opinion, we should respect different cultures.",
          bn: "আমার মতে, আমাদের বিভিন্ন সংস্কৃতিকে সম্মান করা উচিত।",
          slotValues: { CLAUSE: "we should respect different cultures" },
          topicArea: "travel",
        },
        {
          en: "In my opinion, honesty is the foundation of any relationship.",
          bn: "আমার মতে, সততা যেকোনো সম্পর্কের ভিত্তি।",
          slotValues: { CLAUSE: "honesty is the foundation of any relationship" },
          topicArea: "relationships",
        },
        {
          en: "In my opinion, remote work has many advantages.",
          bn: "আমার মতে, রিমোট ওয়ার্কের অনেক সুবিধা আছে।",
          slotValues: { CLAUSE: "remote work has many advantages" },
          topicArea: "work",
        },
        {
          en: "In my opinion, practical experience is more valuable than theory.",
          bn: "আমার মতে, তত্ত্বের চেয়ে ব্যবহারিক অভিজ্ঞতা বেশি মূল্যবান।",
          slotValues: { CLAUSE: "practical experience is more valuable than theory" },
          topicArea: "education",
        },
        {
          en: "In my opinion, breakfast is the most important meal.",
          bn: "আমার মতে, সকালের নাস্তা সবচেয়ে গুরুত্বপূর্ণ খাবার।",
          slotValues: { CLAUSE: "breakfast is the most important meal" },
          topicArea: "food",
        },
        {
          en: "In my opinion, mental health is just as important as physical health.",
          bn: "আমার মতে, মানসিক স্বাস্থ্য শারীরিক স্বাস্থ্যের মতোই গুরুত্বপূর্ণ।",
          slotValues: { CLAUSE: "mental health is just as important as physical health" },
          topicArea: "health",
        },
        {
          en: "In my opinion, we spend too much on unnecessary things.",
          bn: "আমার মতে, আমরা অপ্রয়োজনীয় জিনিসে অনেক বেশি খরচ করি।",
          slotValues: { CLAUSE: "we spend too much on unnecessary things" },
          topicArea: "shopping",
        },
      ],
      formality: "formal",
      difficulty: "intermediate",
      usageNote:
        "'In my opinion' is a more formal and deliberate way to express a viewpoint. It's commonly used in discussions and essays.",
      usageNote_bn:
        "'In my opinion' মতামত প্রকাশের একটি আনুষ্ঠানিক ও সুচিন্তিত উপায়। এটি আলোচনা ও রচনায় সাধারণত ব্যবহৃত হয়।",
      combinableWith: ["E1.1"],
      banglaStructureMap:
        "আমার মতে (Intro) + [CLAUSE] (Main clause)",
    },
    {
      id: "E1.3",
      formula: "It seems to me that [CLAUSE]",
      formula_bn: "আমার মনে হয় [বাক্যাংশ]",
      patternName: "Tentative Opinion",
      patternName_bn: "অনিশ্চিত মতামত",
      slots: [
        {
          name: "CLAUSE",
          description: "A clause expressing a cautious or tentative opinion",
          description_bn: "একটি উপবাক্য যা সতর্ক বা অনিশ্চিত মতামত প্রকাশ করে",
          acceptedTypes: ["clause"],
          examples: [
            "something is wrong",
            "he's not interested",
            "we need a new plan",
          ],
        },
      ],
      examples: [
        {
          en: "It seems to me that something is wrong.",
          bn: "আমার মনে হয় কিছু একটা ভুল আছে।",
          slotValues: { CLAUSE: "something is wrong" },
          topicArea: "daily_life",
        },
        {
          en: "It seems to me that he's not interested.",
          bn: "আমার মনে হয় সে আগ্রহী নয়।",
          slotValues: { CLAUSE: "he's not interested" },
          topicArea: "relationships",
        },
        {
          en: "It seems to me that we need a new plan.",
          bn: "আমার মনে হয় আমাদের নতুন পরিকল্পনা দরকার।",
          slotValues: { CLAUSE: "we need a new plan" },
          topicArea: "work",
        },
        {
          en: "It seems to me that the prices have gone up.",
          bn: "আমার মনে হয় দাম বেড়ে গেছে।",
          slotValues: { CLAUSE: "the prices have gone up" },
          topicArea: "shopping",
        },
        {
          en: "It seems to me that the course is too advanced.",
          bn: "আমার মনে হয় কোর্সটি অনেক বেশি উন্নত।",
          slotValues: { CLAUSE: "the course is too advanced" },
          topicArea: "education",
        },
        {
          en: "It seems to me that this food is undercooked.",
          bn: "আমার মনে হয় এই খাবারটি কম রান্না হয়েছে।",
          slotValues: { CLAUSE: "this food is undercooked" },
          topicArea: "food",
        },
        {
          en: "It seems to me that you need some rest.",
          bn: "আমার মনে হয় তোমার কিছু বিশ্রাম দরকার।",
          slotValues: { CLAUSE: "you need some rest" },
          topicArea: "health",
        },
        {
          en: "It seems to me that the train is on a different platform.",
          bn: "আমার মনে হয় ট্রেনটি ভিন্ন প্ল্যাটফর্মে।",
          slotValues: { CLAUSE: "the train is on a different platform" },
          topicArea: "travel",
        },
        {
          en: "It seems to me that the company is growing fast.",
          bn: "আমার মনে হয় কোম্পানিটি দ্রুত বাড়ছে।",
          slotValues: { CLAUSE: "the company is growing fast" },
          topicArea: "work",
        },
        {
          en: "It seems to me that they don't communicate well.",
          bn: "আমার মনে হয় তারা ভালোভাবে যোগাযোগ করে না।",
          slotValues: { CLAUSE: "they don't communicate well" },
          topicArea: "relationships",
        },
        {
          en: "It seems to me that the students are confused.",
          bn: "আমার মনে হয় ছাত্ররা বিভ্রান্ত।",
          slotValues: { CLAUSE: "the students are confused" },
          topicArea: "education",
        },
        {
          en: "It seems to me that this road leads to the market.",
          bn: "আমার মনে হয় এই রাস্তাটি বাজারে যায়।",
          slotValues: { CLAUSE: "this road leads to the market" },
          topicArea: "travel",
        },
        {
          en: "It seems to me that the portion size is too small.",
          bn: "আমার মনে হয় পরিবেশনের পরিমাণ অনেক কম।",
          slotValues: { CLAUSE: "the portion size is too small" },
          topicArea: "food",
        },
        {
          en: "It seems to me that regular checkups are important.",
          bn: "আমার মনে হয় নিয়মিত চেকআপ গুরুত্বপূর্ণ।",
          slotValues: { CLAUSE: "regular checkups are important" },
          topicArea: "health",
        },
        {
          en: "It seems to me that this product is overpriced.",
          bn: "আমার মনে হয় এই পণ্যটির দাম বেশি।",
          slotValues: { CLAUSE: "this product is overpriced" },
          topicArea: "shopping",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "'It seems to me that' is a polite, cautious way to share an opinion. It avoids sounding too direct or assertive.",
      usageNote_bn:
        "'It seems to me that' মতামত শেয়ার করার একটি ভদ্র, সতর্ক উপায়। এটি অতিরিক্ত সরাসরি বা জোরালো শোনানো এড়ায়।",
      combinableWith: ["E1.1"],
      banglaStructureMap:
        "আমার মনে হয় (Subject + Verb) + [CLAUSE] (Subordinate clause)",
    },
    {
      id: "E1.4",
      formula: "I believe [CLAUSE]",
      formula_bn: "আমি বিশ্বাস করি [বাক্যাংশ]",
      patternName: "Strong Belief",
      patternName_bn: "দৃঢ় বিশ্বাস",
      slots: [
        {
          name: "CLAUSE",
          description: "A clause expressing a strongly held belief",
          description_bn: "একটি উপবাক্য যা দৃঢ়ভাবে ধারণকৃত বিশ্বাস প্রকাশ করে",
          acceptedTypes: ["clause"],
          examples: [
            "education changes lives",
            "hard work pays off",
            "we can do better",
          ],
        },
      ],
      examples: [
        {
          en: "I believe education changes lives.",
          bn: "আমি বিশ্বাস করি শিক্ষা জীবন বদলে দেয়।",
          slotValues: { CLAUSE: "education changes lives" },
          topicArea: "education",
        },
        {
          en: "I believe hard work pays off.",
          bn: "আমি বিশ্বাস করি কঠোর পরিশ্রম ফল দেয়।",
          slotValues: { CLAUSE: "hard work pays off" },
          topicArea: "work",
        },
        {
          en: "I believe we can do better.",
          bn: "আমি বিশ্বাস করি আমরা আরও ভালো করতে পারি।",
          slotValues: { CLAUSE: "we can do better" },
          topicArea: "daily_life",
        },
        {
          en: "I believe kindness is never wasted.",
          bn: "আমি বিশ্বাস করি দয়া কখনো বৃথা যায় না।",
          slotValues: { CLAUSE: "kindness is never wasted" },
          topicArea: "relationships",
        },
        {
          en: "I believe a balanced diet is key to good health.",
          bn: "আমি বিশ্বাস করি সুষম খাদ্য সুস্বাস্থ্যের চাবিকাঠি।",
          slotValues: { CLAUSE: "a balanced diet is key to good health" },
          topicArea: "health",
        },
        {
          en: "I believe traveling broadens the mind.",
          bn: "আমি বিশ্বাস করি ভ্রমণ মনকে প্রসারিত করে।",
          slotValues: { CLAUSE: "traveling broadens the mind" },
          topicArea: "travel",
        },
        {
          en: "I believe traditional cooking is an art.",
          bn: "আমি বিশ্বাস করি ঐতিহ্যবাহী রান্না একটি শিল্প।",
          slotValues: { CLAUSE: "traditional cooking is an art" },
          topicArea: "food",
        },
        {
          en: "I believe supporting local businesses is important.",
          bn: "আমি বিশ্বাস করি স্থানীয় ব্যবসায় সমর্থন করা গুরুত্বপূর্ণ।",
          slotValues: { CLAUSE: "supporting local businesses is important" },
          topicArea: "shopping",
        },
        {
          en: "I believe teamwork leads to success.",
          bn: "আমি বিশ্বাস করি দলগত কাজ সাফল্যের দিকে নিয়ে যায়।",
          slotValues: { CLAUSE: "teamwork leads to success" },
          topicArea: "work",
        },
        {
          en: "I believe every child deserves quality education.",
          bn: "আমি বিশ্বাস করি প্রতিটি শিশু মানসম্মত শিক্ষা পাওয়ার যোগ্য।",
          slotValues: { CLAUSE: "every child deserves quality education" },
          topicArea: "education",
        },
        {
          en: "I believe family comes first.",
          bn: "আমি বিশ্বাস করি পরিবার সবার আগে।",
          slotValues: { CLAUSE: "family comes first" },
          topicArea: "relationships",
        },
        {
          en: "I believe exercise should be part of daily life.",
          bn: "আমি বিশ্বাস করি ব্যায়াম দৈনন্দিন জীবনের অংশ হওয়া উচিত।",
          slotValues: { CLAUSE: "exercise should be part of daily life" },
          topicArea: "health",
        },
        {
          en: "I believe every country has something unique to offer.",
          bn: "আমি বিশ্বাস করি প্রতিটি দেশের কিছু অনন্য দেওয়ার আছে।",
          slotValues: { CLAUSE: "every country has something unique to offer" },
          topicArea: "travel",
        },
        {
          en: "I believe freshly cooked food is always better.",
          bn: "আমি বিশ্বাস করি তাজা রান্না করা খাবার সবসময় ভালো।",
          slotValues: { CLAUSE: "freshly cooked food is always better" },
          topicArea: "food",
        },
        {
          en: "I believe investing in yourself is the best investment.",
          bn: "আমি বিশ্বাস করি নিজের মধ্যে বিনিয়োগ সেরা বিনিয়োগ।",
          slotValues: { CLAUSE: "investing in yourself is the best investment" },
          topicArea: "daily_life",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "'I believe' is stronger than 'I think' and expresses a deeply held conviction. It sounds more serious and committed.",
      usageNote_bn:
        "'I believe' 'I think'-এর চেয়ে জোরালো এবং গভীরভাবে ধারণকৃত বিশ্বাস প্রকাশ করে। এটি বেশি গম্ভীর ও প্রতিশ্রুতিবদ্ধ শোনায়।",
      combinableWith: ["E1.1"],
      banglaStructureMap:
        "আমি বিশ্বাস করি (Subject + Verb) + [CLAUSE] (Subordinate clause)",
    },
    {
      id: "E1.5",
      formula: "I suppose [CLAUSE]",
      formula_bn: "আমার ধারণা [বাক্যাংশ]",
      patternName: "Reluctant / Uncertain Opinion",
      patternName_bn: "অনিচ্ছুক / অনিশ্চিত মতামত",
      slots: [
        {
          name: "CLAUSE",
          description: "A clause expressing a hesitant or reluctant opinion",
          description_bn: "একটি উপবাক্য যা দ্বিধাগ্রস্ত বা অনিচ্ছুক মতামত প্রকাশ করে",
          acceptedTypes: ["clause"],
          examples: [
            "you're right",
            "it could work",
            "we have no other choice",
          ],
        },
      ],
      examples: [
        {
          en: "I suppose you're right.",
          bn: "আমার ধারণা তুমি ঠিক বলেছ।",
          slotValues: { CLAUSE: "you're right" },
          topicArea: "daily_life",
        },
        {
          en: "I suppose it could work.",
          bn: "আমার ধারণা এটা কাজ করতে পারে।",
          slotValues: { CLAUSE: "it could work" },
          topicArea: "work",
        },
        {
          en: "I suppose we have no other choice.",
          bn: "আমার ধারণা আমাদের অন্য কোনো উপায় নেই।",
          slotValues: { CLAUSE: "we have no other choice" },
          topicArea: "daily_life",
        },
        {
          en: "I suppose the meeting will be boring.",
          bn: "আমার ধারণা মিটিংটা বিরক্তিকর হবে।",
          slotValues: { CLAUSE: "the meeting will be boring" },
          topicArea: "work",
        },
        {
          en: "I suppose I should study more.",
          bn: "আমার ধারণা আমার আরও পড়াশোনা করা উচিত।",
          slotValues: { CLAUSE: "I should study more" },
          topicArea: "education",
        },
        {
          en: "I suppose this place is alright for dinner.",
          bn: "আমার ধারণা রাতের খাবারের জন্য এই জায়গাটা মোটামুটি ঠিক আছে।",
          slotValues: { CLAUSE: "this place is alright for dinner" },
          topicArea: "food",
        },
        {
          en: "I suppose I should see a doctor.",
          bn: "আমার ধারণা আমার ডাক্তার দেখানো উচিত।",
          slotValues: { CLAUSE: "I should see a doctor" },
          topicArea: "health",
        },
        {
          en: "I suppose we can take the longer route.",
          bn: "আমার ধারণা আমরা লম্বা পথ নিতে পারি।",
          slotValues: { CLAUSE: "we can take the longer route" },
          topicArea: "travel",
        },
        {
          en: "I suppose I'll buy the cheaper one.",
          bn: "আমার ধারণা আমি সস্তাটা কিনব।",
          slotValues: { CLAUSE: "I'll buy the cheaper one" },
          topicArea: "shopping",
        },
        {
          en: "I suppose she's doing her best.",
          bn: "আমার ধারণা সে তার সর্বোচ্চ চেষ্টা করছে।",
          slotValues: { CLAUSE: "she's doing her best" },
          topicArea: "relationships",
        },
        {
          en: "I suppose the deadline is reasonable.",
          bn: "আমার ধারণা সময়সীমাটি যুক্তিসঙ্গত।",
          slotValues: { CLAUSE: "the deadline is reasonable" },
          topicArea: "work",
        },
        {
          en: "I suppose it's worth trying at least once.",
          bn: "আমার ধারণা অন্তত একবার চেষ্টা করার যোগ্য।",
          slotValues: { CLAUSE: "it's worth trying at least once" },
          topicArea: "food",
        },
        {
          en: "I suppose the textbook explains it well enough.",
          bn: "আমার ধারণা পাঠ্যবই এটি যথেষ্ট ভালোভাবে ব্যাখ্যা করে।",
          slotValues: { CLAUSE: "the textbook explains it well enough" },
          topicArea: "education",
        },
        {
          en: "I suppose the hotel will be fine for one night.",
          bn: "আমার ধারণা এক রাতের জন্য হোটেলটি ঠিকই হবে।",
          slotValues: { CLAUSE: "the hotel will be fine for one night" },
          topicArea: "travel",
        },
        {
          en: "I suppose walking would be good for my health.",
          bn: "আমার ধারণা হাঁটা আমার স্বাস্থ্যের জন্য ভালো হবে।",
          slotValues: { CLAUSE: "walking would be good for my health" },
          topicArea: "health",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'I suppose' expresses a reluctant or half-hearted agreement or opinion. It suggests you're not fully convinced.",
      usageNote_bn:
        "'I suppose' অনিচ্ছুক বা অর্ধ-মনে সম্মতি বা মতামত প্রকাশ করে। এটি বোঝায় আপনি পুরোপুরি নিশ্চিত নন।",
      combinableWith: ["E1.1"],
      banglaStructureMap:
        "আমার ধারণা (Subject + Verb) + [CLAUSE] (Subordinate clause)",
    },
  ],
};
