import { PatternCategory } from "@/types/pattern";

export const categoryE15: PatternCategory = {
  id: "E15",
  slug: "expressing-envy",
  name: "Expressing Envy & Jealousy",
  name_bn: "হিংসা ও ঈর্ষা প্রকাশ",
  description:
    "Learn how to express feelings of envy, jealousy, and admiration for what others have in English.",
  description_bn:
    "ইংরেজিতে অন্যদের যা আছে তার প্রতি হিংসা, ঈর্ষা এবং প্রশংসার অনুভূতি প্রকাশ করতে শিখুন।",
  icon: "😒",
  group: "E",
  groupName: "Opinions, Emotions & Attitudes",
  groupName_bn: "মতামত, আবেগ ও দৃষ্টিভঙ্গি",
  difficulty: "intermediate",
  patterns: [
    {
      id: "E15.1",
      formula: "I'm jealous of [PERSON]'s [THING]",
      formula_bn: "আমি [ব্যক্তি]-র [জিনিস] নিয়ে হিংসা করি",
      patternName: "Jealous Of Someone's Thing",
      patternName_bn: "কারো জিনিস নিয়ে ঈর্ষা",
      slots: [
        {
          name: "PERSON",
          description: "The person whose possession or quality you envy",
          description_bn: "যে ব্যক্তির সম্পত্তি বা গুণ নিয়ে আপনি ঈর্ষান্বিত",
          acceptedTypes: ["person"],
          examples: ["my friend", "her", "my colleague"],
        },
        {
          name: "THING",
          description: "The possession, quality, or achievement you envy",
          description_bn: "যে সম্পত্তি, গুণ বা অর্জন নিয়ে আপনি ঈর্ষান্বিত",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["new car", "cooking skills", "promotion"],
        },
      ],
      examples: [
        { en: "I'm jealous of my friend's new car.", bn: "আমি আমার বন্ধুর নতুন গাড়ি নিয়ে হিংসা করি।", slotValues: { PERSON: "my friend", THING: "new car" }, topicArea: "shopping" },
        { en: "I'm jealous of her cooking skills.", bn: "আমি তার রান্নার দক্ষতা নিয়ে হিংসা করি।", slotValues: { PERSON: "her", THING: "cooking skills" }, topicArea: "food" },
        { en: "I'm jealous of my colleague's promotion.", bn: "আমি আমার সহকর্মীর পদোন্নতি নিয়ে হিংসা করি।", slotValues: { PERSON: "my colleague", THING: "promotion" }, topicArea: "work" },
        { en: "I'm jealous of my brother's travel photos.", bn: "আমি আমার ভাইয়ের ভ্রমণের ছবি নিয়ে হিংসা করি।", slotValues: { PERSON: "my brother", THING: "travel photos" }, topicArea: "travel" },
        { en: "I'm jealous of my sister's perfect grades.", bn: "আমি আমার বোনের পারফেক্ট গ্রেড নিয়ে হিংসা করি।", slotValues: { PERSON: "my sister", THING: "perfect grades" }, topicArea: "education" },
        { en: "I'm jealous of his confidence.", bn: "আমি তার আত্মবিশ্বাস নিয়ে হিংসা করি।", slotValues: { PERSON: "his", THING: "confidence" }, topicArea: "daily_life" },
        { en: "I'm jealous of my neighbor's beautiful garden.", bn: "আমি আমার প্রতিবেশীর সুন্দর বাগান নিয়ে হিংসা করি।", slotValues: { PERSON: "my neighbor", THING: "beautiful garden" }, topicArea: "daily_life" },
        { en: "I'm jealous of her ability to speak five languages.", bn: "আমি তার পাঁচটি ভাষায় কথা বলার ক্ষমতা নিয়ে হিংসা করি।", slotValues: { PERSON: "her", THING: "ability to speak five languages" }, topicArea: "education" },
        { en: "I'm jealous of my cousin's fit body.", bn: "আমি আমার কাজিনের ফিট শরীর নিয়ে হিংসা করি।", slotValues: { PERSON: "my cousin", THING: "fit body" }, topicArea: "health" },
        { en: "I'm jealous of my friend's amazing wedding.", bn: "আমি আমার বন্ধুর অসাধারণ বিয়ে নিয়ে হিংসা করি।", slotValues: { PERSON: "my friend", THING: "amazing wedding" }, topicArea: "relationships" },
        { en: "I'm jealous of his corner office.", bn: "আমি তার কর্নার অফিস নিয়ে হিংসা করি।", slotValues: { PERSON: "his", THING: "corner office" }, topicArea: "work" },
        { en: "I'm jealous of her designer wardrobe.", bn: "আমি তার ডিজাইনার পোশাক সংগ্রহ নিয়ে হিংসা করি।", slotValues: { PERSON: "her", THING: "designer wardrobe" }, topicArea: "shopping" },
        { en: "I'm jealous of my friend's homemade pasta.", bn: "আমি আমার বন্ধুর ঘরে তৈরি পাস্তা নিয়ে হিংসা করি।", slotValues: { PERSON: "my friend", THING: "homemade pasta" }, topicArea: "food" },
        { en: "I'm jealous of my colleague's vacation in Maldives.", bn: "আমি আমার সহকর্মীর মালদ্বীপের ছুটি নিয়ে হিংসা করি।", slotValues: { PERSON: "my colleague", THING: "vacation in Maldives" }, topicArea: "travel" },
        { en: "I'm jealous of her natural beauty.", bn: "আমি তার স্বাভাবিক সৌন্দর্য নিয়ে হিংসা করি।", slotValues: { PERSON: "her", THING: "natural beauty" }, topicArea: "health" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'I'm jealous of someone's something' is commonly used in casual speech. In informal English, 'jealous' and 'envious' are often used interchangeably.",
      usageNote_bn:
        "'I'm jealous of someone's something' সাধারণ কথায় ব্যাপকভাবে ব্যবহৃত হয়। অনানুষ্ঠানিক ইংরেজিতে 'jealous' এবং 'envious' প্রায়ই একইভাবে ব্যবহৃত হয়।",
    },
    {
      id: "E15.2",
      formula: "I wish I had [THING] like [PERSON]",
      formula_bn: "আমি যদি [ব্যক্তি]-র মতো [জিনিস] থাকত",
      patternName: "Wish for Someone Else's Fortune",
      patternName_bn: "অন্যের সৌভাগ্যের কামনা",
      slots: [
        {
          name: "THING",
          description: "The possession or quality you wish you had",
          description_bn: "যে সম্পত্তি বা গুণ আপনি চান",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["a voice", "patience", "a house"],
        },
        {
          name: "PERSON",
          description: "The person who has what you wish for",
          description_bn: "যে ব্যক্তির কাছে আছে যা আপনি চান",
          acceptedTypes: ["person"],
          examples: ["her", "him", "my brother"],
        },
      ],
      examples: [
        { en: "I wish I had a voice like her.", bn: "আমি যদি তার মতো গলা থাকত।", slotValues: { THING: "a voice", PERSON: "her" }, topicArea: "daily_life" },
        { en: "I wish I had patience like my mother.", bn: "আমি যদি আমার মায়ের মতো ধৈর্য থাকত।", slotValues: { THING: "patience", PERSON: "my mother" }, topicArea: "relationships" },
        { en: "I wish I had a house like my uncle.", bn: "আমি যদি আমার চাচার মতো বাড়ি থাকত।", slotValues: { THING: "a house", PERSON: "my uncle" }, topicArea: "daily_life" },
        { en: "I wish I had cooking talent like my grandmother.", bn: "আমি যদি আমার দাদির মতো রান্নার প্রতিভা থাকত।", slotValues: { THING: "cooking talent", PERSON: "my grandmother" }, topicArea: "food" },
        { en: "I wish I had grades like my classmate.", bn: "আমি যদি আমার সহপাঠীর মতো গ্রেড থাকত।", slotValues: { THING: "grades", PERSON: "my classmate" }, topicArea: "education" },
        { en: "I wish I had a salary like him.", bn: "আমি যদি তার মতো বেতন থাকত।", slotValues: { THING: "a salary", PERSON: "him" }, topicArea: "work" },
        { en: "I wish I had travel opportunities like my cousin.", bn: "আমি যদি আমার কাজিনের মতো ভ্রমণের সুযোগ থাকত।", slotValues: { THING: "travel opportunities", PERSON: "my cousin" }, topicArea: "travel" },
        { en: "I wish I had energy like my younger brother.", bn: "আমি যদি আমার ছোট ভাইয়ের মতো শক্তি থাকত।", slotValues: { THING: "energy", PERSON: "my younger brother" }, topicArea: "health" },
        { en: "I wish I had a sense of style like her.", bn: "আমি যদি তার মতো স্টাইল সেন্স থাকত।", slotValues: { THING: "a sense of style", PERSON: "her" }, topicArea: "shopping" },
        { en: "I wish I had social skills like my friend.", bn: "আমি যদি আমার বন্ধুর মতো সামাজিক দক্ষতা থাকত।", slotValues: { THING: "social skills", PERSON: "my friend" }, topicArea: "relationships" },
        { en: "I wish I had a memory like my professor.", bn: "আমি যদি আমার প্রফেসরের মতো স্মৃতিশক্তি থাকত।", slotValues: { THING: "a memory", PERSON: "my professor" }, topicArea: "education" },
        { en: "I wish I had discipline like my gym trainer.", bn: "আমি যদি আমার জিম ট্রেইনারের মতো শৃঙ্খলা থাকত।", slotValues: { THING: "discipline", PERSON: "my gym trainer" }, topicArea: "health" },
        { en: "I wish I had leadership skills like my boss.", bn: "আমি যদি আমার বসের মতো নেতৃত্বের দক্ষতা থাকত।", slotValues: { THING: "leadership skills", PERSON: "my boss" }, topicArea: "work" },
        { en: "I wish I had a taste for food like him.", bn: "আমি যদি তার মতো খাবারের রুচি থাকত।", slotValues: { THING: "a taste for food", PERSON: "him" }, topicArea: "food" },
        { en: "I wish I had frequent flyer miles like my colleague.", bn: "আমি যদি আমার সহকর্মীর মতো ফ্রিকোয়েন্ট ফ্লায়ার মাইল থাকত।", slotValues: { THING: "frequent flyer miles", PERSON: "my colleague" }, topicArea: "travel" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'I wish I had... like...' uses the subjunctive mood to express an unreal desire. It compares what you lack with what someone else has.",
      usageNote_bn:
        "'I wish I had... like...' একটি অবাস্তব ইচ্ছা প্রকাশ করতে subjunctive mood ব্যবহার করে। এটি আপনার যা নেই তা অন্য কারো যা আছে তার সাথে তুলনা করে।",
    },
    {
      id: "E15.3",
      formula: "Lucky you!",
      formula_bn: "তুমি কত ভাগ্যবান!",
      patternName: "Exclamatory Envy",
      patternName_bn: "বিস্ময়সূচক ঈর্ষা",
      slots: [],
      examples: [
        { en: "Lucky you! You got the last ticket.", bn: "তুমি কত ভাগ্যবান! তুমি শেষ টিকেটটা পেয়ে গেছ।", slotValues: {}, topicArea: "travel" },
        { en: "Lucky you! Your boss gave you a day off.", bn: "তুমি কত ভাগ্যবান! তোমার বস তোমাকে একদিন ছুটি দিয়েছে।", slotValues: {}, topicArea: "work" },
        { en: "Lucky you! You found that dress on sale.", bn: "তুমি কত ভাগ্যবান! তুমি ওই ড্রেসটা সেলে পেয়ে গেছ।", slotValues: {}, topicArea: "shopping" },
        { en: "Lucky you! You got to eat at that famous restaurant.", bn: "তুমি কত ভাগ্যবান! তুমি ওই বিখ্যাত রেস্তোরাঁয় খেতে পেরেছ।", slotValues: {}, topicArea: "food" },
        { en: "Lucky you! You don't have any exams this week.", bn: "তুমি কত ভাগ্যবান! এই সপ্তাহে তোমার কোনো পরীক্ষা নেই।", slotValues: {}, topicArea: "education" },
        { en: "Lucky you! You never seem to get sick.", bn: "তুমি কত ভাগ্যবান! তুমি কখনো অসুস্থ হও না মনে হয়।", slotValues: {}, topicArea: "health" },
        { en: "Lucky you! Your family is so supportive.", bn: "তুমি কত ভাগ্যবান! তোমার পরিবার এত সহায়ক।", slotValues: {}, topicArea: "relationships" },
        { en: "Lucky you! You can work from home every day.", bn: "তুমি কত ভাগ্যবান! তুমি প্রতিদিন বাসা থেকে কাজ করতে পার।", slotValues: {}, topicArea: "work" },
        { en: "Lucky you! You live so close to the beach.", bn: "তুমি কত ভাগ্যবান! তুমি সমুদ্র সৈকতের এত কাছে থাক।", slotValues: {}, topicArea: "daily_life" },
        { en: "Lucky you! You're going to Paris next month.", bn: "তুমি কত ভাগ্যবান! তুমি আগামী মাসে প্যারিস যাচ্ছ।", slotValues: {}, topicArea: "travel" },
        { en: "Lucky you! You got free samples at the store.", bn: "তুমি কত ভাগ্যবান! তুমি দোকানে ফ্রি স্যাম্পল পেয়েছ।", slotValues: {}, topicArea: "shopping" },
        { en: "Lucky you! Your mom cooks amazing biryani.", bn: "তুমি কত ভাগ্যবান! তোমার মা অসাধারণ বিরিয়ানি রান্না করেন।", slotValues: {}, topicArea: "food" },
        { en: "Lucky you! You got a scholarship.", bn: "তুমি কত ভাগ্যবান! তুমি স্কলারশিপ পেয়েছ।", slotValues: {}, topicArea: "education" },
        { en: "Lucky you! You have such a loving partner.", bn: "তুমি কত ভাগ্যবান! তোমার এত ভালোবাসাময় সঙ্গী আছে।", slotValues: {}, topicArea: "relationships" },
        { en: "Lucky you! You can eat anything without gaining weight.", bn: "তুমি কত ভাগ্যবান! তুমি যা খুশি খেতে পার ওজন না বাড়িয়ে।", slotValues: {}, topicArea: "health" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Lucky you!' is a light-hearted exclamation expressing mild envy. It's usually friendly and not meant to be hurtful.",
      usageNote_bn:
        "'Lucky you!' হালকা মেজাজের বিস্ময়োক্তি যা হালকা ঈর্ষা প্রকাশ করে। এটি সাধারণত বন্ধুত্বপূর্ণ এবং আঘাত করার উদ্দেশ্যে নয়।",
    },
    {
      id: "E15.4",
      formula: "[PERSON] is so lucky to have [THING]",
      formula_bn: "[ব্যক্তি] [জিনিস] থাকায় খুব ভাগ্যবান",
      patternName: "Acknowledging Someone's Luck",
      patternName_bn: "কারো ভাগ্য স্বীকার করা",
      slots: [
        {
          name: "PERSON",
          description: "The person you consider lucky",
          description_bn: "যে ব্যক্তিকে আপনি ভাগ্যবান মনে করেন",
          acceptedTypes: ["person"],
          examples: ["she", "he", "my brother"],
        },
        {
          name: "THING",
          description: "What makes them lucky",
          description_bn: "যা তাদের ভাগ্যবান করে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["such a supportive family", "that job", "a beautiful home"],
        },
      ],
      examples: [
        { en: "She is so lucky to have such a supportive family.", bn: "সে এত সহায়ক পরিবার থাকায় খুব ভাগ্যবান।", slotValues: { PERSON: "She", THING: "such a supportive family" }, topicArea: "relationships" },
        { en: "He is so lucky to have that job.", bn: "সে ওই চাকরি থাকায় খুব ভাগ্যবান।", slotValues: { PERSON: "He", THING: "that job" }, topicArea: "work" },
        { en: "My brother is so lucky to have a beautiful home.", bn: "আমার ভাই সুন্দর বাড়ি থাকায় খুব ভাগ্যবান।", slotValues: { PERSON: "My brother", THING: "a beautiful home" }, topicArea: "daily_life" },
        { en: "She is so lucky to have access to great restaurants.", bn: "সে দুর্দান্ত রেস্তোরাঁয় যেতে পারায় খুব ভাগ্যবান।", slotValues: { PERSON: "She", THING: "access to great restaurants" }, topicArea: "food" },
        { en: "He is so lucky to have a scholarship to study abroad.", bn: "সে বিদেশে পড়ার স্কলারশিপ পাওয়ায় খুব ভাগ্যবান।", slotValues: { PERSON: "He", THING: "a scholarship to study abroad" }, topicArea: "education" },
        { en: "My friend is so lucky to have good health.", bn: "আমার বন্ধু ভালো স্বাস্থ্য থাকায় খুব ভাগ্যবান।", slotValues: { PERSON: "My friend", THING: "good health" }, topicArea: "health" },
        { en: "She is so lucky to have traveled to so many countries.", bn: "সে এত দেশ ভ্রমণ করেছে বলে খুব ভাগ্যবান।", slotValues: { PERSON: "She", THING: "traveled to so many countries" }, topicArea: "travel" },
        { en: "He is so lucky to have such a loving wife.", bn: "সে এত ভালোবাসাময় স্ত্রী থাকায় খুব ভাগ্যবান।", slotValues: { PERSON: "He", THING: "such a loving wife" }, topicArea: "relationships" },
        { en: "My sister is so lucky to have a flexible work schedule.", bn: "আমার বোন নমনীয় কাজের সময়সূচি থাকায় খুব ভাগ্যবান।", slotValues: { PERSON: "My sister", THING: "a flexible work schedule" }, topicArea: "work" },
        { en: "He is so lucky to have a personal chef.", bn: "সে ব্যক্তিগত শেফ থাকায় খুব ভাগ্যবান।", slotValues: { PERSON: "He", THING: "a personal chef" }, topicArea: "food" },
        { en: "She is so lucky to have such a great mentor.", bn: "সে এত দুর্দান্ত পরামর্শদাতা পাওয়ায় খুব ভাগ্যবান।", slotValues: { PERSON: "She", THING: "such a great mentor" }, topicArea: "education" },
        { en: "My cousin is so lucky to have unlimited shopping budget.", bn: "আমার কাজিন সীমাহীন কেনাকাটার বাজেট থাকায় খুব ভাগ্যবান।", slotValues: { PERSON: "My cousin", THING: "unlimited shopping budget" }, topicArea: "shopping" },
        { en: "He is so lucky to have a gym in his building.", bn: "সে তার বিল্ডিংয়ে জিম থাকায় খুব ভাগ্যবান।", slotValues: { PERSON: "He", THING: "a gym in his building" }, topicArea: "health" },
        { en: "She is so lucky to have a house near the mountains.", bn: "সে পাহাড়ের কাছে বাড়ি থাকায় খুব ভাগ্যবান।", slotValues: { PERSON: "She", THING: "a house near the mountains" }, topicArea: "travel" },
        { en: "My neighbor is so lucky to have such well-behaved kids.", bn: "আমার প্রতিবেশী এত ভদ্র বাচ্চা থাকায় খুব ভাগ্যবান।", slotValues: { PERSON: "My neighbor", THING: "such well-behaved kids" }, topicArea: "daily_life" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Someone is so lucky to have...' expresses admiration mixed with envy. It acknowledges another person's good fortune.",
      usageNote_bn:
        "'Someone is so lucky to have...' ঈর্ষা মিশ্রিত প্রশংসা প্রকাশ করে। এটি অন্য ব্যক্তির সৌভাগ্য স্বীকার করে।",
    },
    {
      id: "E15.5",
      formula: "I'd love to have [THING] like that",
      formula_bn: "আমি ওরকম [জিনিস] পেলে ভালো লাগত",
      patternName: "Desiring What Others Have",
      patternName_bn: "অন্যদের যা আছে তা কামনা করা",
      slots: [
        {
          name: "THING",
          description: "The thing you desire that someone else has",
          description_bn: "যে জিনিস আপনি চান যা অন্যের আছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["a garden", "a job", "a holiday"],
        },
      ],
      examples: [
        { en: "I'd love to have a garden like that.", bn: "আমি ওরকম বাগান পেলে ভালো লাগত।", slotValues: { THING: "a garden" }, topicArea: "daily_life" },
        { en: "I'd love to have a job like that.", bn: "আমি ওরকম চাকরি পেলে ভালো লাগত।", slotValues: { THING: "a job" }, topicArea: "work" },
        { en: "I'd love to have a holiday like that.", bn: "আমি ওরকম ছুটি পেলে ভালো লাগত।", slotValues: { THING: "a holiday" }, topicArea: "travel" },
        { en: "I'd love to have cooking skills like that.", bn: "আমি ওরকম রান্নার দক্ষতা পেলে ভালো লাগত।", slotValues: { THING: "cooking skills" }, topicArea: "food" },
        { en: "I'd love to have a scholarship like that.", bn: "আমি ওরকম স্কলারশিপ পেলে ভালো লাগত।", slotValues: { THING: "a scholarship" }, topicArea: "education" },
        { en: "I'd love to have a metabolism like that.", bn: "আমি ওরকম বিপাক ক্রিয়া পেলে ভালো লাগত।", slotValues: { THING: "a metabolism" }, topicArea: "health" },
        { en: "I'd love to have a relationship like that.", bn: "আমি ওরকম সম্পর্ক পেলে ভালো লাগত।", slotValues: { THING: "a relationship" }, topicArea: "relationships" },
        { en: "I'd love to have a wardrobe like that.", bn: "আমি ওরকম পোশাক সংগ্রহ পেলে ভালো লাগত।", slotValues: { THING: "a wardrobe" }, topicArea: "shopping" },
        { en: "I'd love to have an apartment like that.", bn: "আমি ওরকম অ্যাপার্টমেন্ট পেলে ভালো লাগত।", slotValues: { THING: "an apartment" }, topicArea: "daily_life" },
        { en: "I'd love to have a work-life balance like that.", bn: "আমি ওরকম কর্ম-জীবনের ভারসাম্য পেলে ভালো লাগত।", slotValues: { THING: "a work-life balance" }, topicArea: "work" },
        { en: "I'd love to have a kitchen like that.", bn: "আমি ওরকম রান্নাঘর পেলে ভালো লাগত।", slotValues: { THING: "a kitchen" }, topicArea: "food" },
        { en: "I'd love to have a passport with that many stamps.", bn: "আমি ওরকম অনেক স্ট্যাম্পওয়ালা পাসপোর্ট পেলে ভালো লাগত।", slotValues: { THING: "a passport with that many stamps" }, topicArea: "travel" },
        { en: "I'd love to have a talent like that.", bn: "আমি ওরকম প্রতিভা পেলে ভালো লাগত।", slotValues: { THING: "a talent" }, topicArea: "education" },
        { en: "I'd love to have a fitness routine like that.", bn: "আমি ওরকম ফিটনেস রুটিন পেলে ভালো লাগত।", slotValues: { THING: "a fitness routine" }, topicArea: "health" },
        { en: "I'd love to have friends like that.", bn: "আমি ওরকম বন্ধু পেলে ভালো লাগত।", slotValues: { THING: "friends" }, topicArea: "relationships" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'I'd love to have... like that' is a polite and indirect way of expressing envy. 'Like that' refers to something you've just seen or heard about.",
      usageNote_bn:
        "'I'd love to have... like that' ঈর্ষা প্রকাশের একটি ভদ্র ও পরোক্ষ উপায়। 'Like that' আপনি সবেমাত্র দেখেছেন বা শুনেছেন এমন কিছুকে নির্দেশ করে।",
    },
  ],
};
