import { PatternCategory } from "@/types/pattern";

export const categoryE2: PatternCategory = {
  id: "E2",
  slug: "agreeing-disagreeing",
  name: "Agreeing & Disagreeing",
  name_bn: "সম্মতি ও অসম্মতি",
  description:
    "Learn how to agree and disagree politely and effectively in English conversations.",
  description_bn:
    "ইংরেজি কথোপকথনে ভদ্রভাবে এবং কার্যকরভাবে সম্মতি ও অসম্মতি প্রকাশ করতে শিখুন।",
  icon: "🤝",
  group: "E",
  groupName: "Opinions, Emotions & Attitudes",
  groupName_bn: "মতামত, আবেগ এবং মনোভাব",
  difficulty: "intermediate",
  patterns: [
    {
      id: "E2.1",
      formula: "I agree with [IDEA]",
      formula_bn: "আমি [ধারণা]-এর সাথে একমত",
      patternName: "Expressing Agreement",
      patternName_bn: "সম্মতি প্রকাশ",
      slots: [
        {
          name: "IDEA",
          description: "A noun, noun phrase, or person whose idea you agree with",
          description_bn: "একটি বিশেষ্য, বিশেষ্য পদবন্ধ বা ব্যক্তি যার ধারণার সাথে আপনি একমত",
          acceptedTypes: ["noun", "person"],
          examples: ["you", "that plan", "the decision"],
        },
      ],
      examples: [
        { en: "I agree with you.", bn: "আমি তোমার সাথে একমত।", slotValues: { IDEA: "you" }, topicArea: "daily_life" },
        { en: "I agree with that plan.", bn: "আমি সেই পরিকল্পনার সাথে একমত।", slotValues: { IDEA: "that plan" }, topicArea: "work" },
        { en: "I agree with the decision.", bn: "আমি এই সিদ্ধান্তের সাথে একমত।", slotValues: { IDEA: "the decision" }, topicArea: "work" },
        { en: "I agree with the teacher's approach.", bn: "আমি শিক্ষকের পদ্ধতির সাথে একমত।", slotValues: { IDEA: "the teacher's approach" }, topicArea: "education" },
        { en: "I agree with the doctor's advice.", bn: "আমি ডাক্তারের পরামর্শের সাথে একমত।", slotValues: { IDEA: "the doctor's advice" }, topicArea: "health" },
        { en: "I agree with the suggestion to try local food.", bn: "আমি স্থানীয় খাবার চেষ্টা করার পরামর্শের সাথে একমত।", slotValues: { IDEA: "the suggestion to try local food" }, topicArea: "food" },
        { en: "I agree with the idea of traveling by train.", bn: "আমি ট্রেনে ভ্রমণের ধারণার সাথে একমত।", slotValues: { IDEA: "the idea of traveling by train" }, topicArea: "travel" },
        { en: "I agree with her opinion on this matter.", bn: "আমি এই বিষয়ে তার মতামতের সাথে একমত।", slotValues: { IDEA: "her opinion on this matter" }, topicArea: "relationships" },
        { en: "I agree with the need to save money.", bn: "আমি টাকা বাঁচানোর প্রয়োজনীয়তার সাথে একমত।", slotValues: { IDEA: "the need to save money" }, topicArea: "shopping" },
        { en: "I agree with the new company policy.", bn: "আমি কোম্পানির নতুন নীতির সাথে একমত।", slotValues: { IDEA: "the new company policy" }, topicArea: "work" },
        { en: "I agree with the importance of regular exercise.", bn: "আমি নিয়মিত ব্যায়ামের গুরুত্বের সাথে একমত।", slotValues: { IDEA: "the importance of regular exercise" }, topicArea: "health" },
        { en: "I agree with the school's new rules.", bn: "আমি স্কুলের নতুন নিয়মের সাথে একমত।", slotValues: { IDEA: "the school's new rules" }, topicArea: "education" },
        { en: "I agree with choosing the window seat.", bn: "আমি জানালার পাশের সিট বাছাইয়ের সাথে একমত।", slotValues: { IDEA: "choosing the window seat" }, topicArea: "travel" },
        { en: "I agree with cooking at home more often.", bn: "আমি আরও বেশি ঘরে রান্না করার সাথে একমত।", slotValues: { IDEA: "cooking at home more often" }, topicArea: "food" },
        { en: "I agree with my parents on this.", bn: "আমি এই বিষয়ে আমার বাবা-মায়ের সাথে একমত।", slotValues: { IDEA: "my parents on this" }, topicArea: "relationships" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "'I agree with' is a clear and direct way to show you share the same view. Follow it with a person or an idea.",
      usageNote_bn: "'I agree with' আপনি একই মত শেয়ার করেন তা দেখানোর একটি স্পষ্ট ও সরাসরি উপায়। এর পরে একজন ব্যক্তি বা ধারণা ব্যবহার করুন।",
      combinableWith: ["E2.5"],
      banglaStructureMap: "আমি (Subject) + [IDEA]-এর সাথে (Object + Postposition) + একমত (Predicate)",
    },
    {
      id: "E2.2",
      formula: "I see your point, but [CLAUSE]",
      formula_bn: "আমি তোমার বক্তব্য বুঝতে পারছি, কিন্তু [বাক্যাংশ]",
      patternName: "Partial Disagreement",
      patternName_bn: "আংশিক অসম্মতি",
      slots: [
        {
          name: "CLAUSE",
          description: "A clause introducing your differing perspective",
          description_bn: "একটি উপবাক্য যা আপনার ভিন্ন দৃষ্টিভঙ্গি উপস্থাপন করে",
          acceptedTypes: ["clause"],
          examples: ["I think there's a better way", "we should consider other options", "it might not work for everyone"],
        },
      ],
      examples: [
        { en: "I see your point, but I think there's a better way.", bn: "আমি তোমার বক্তব্য বুঝতে পারছি, কিন্তু আমি মনে করি আরও ভালো উপায় আছে।", slotValues: { CLAUSE: "I think there's a better way" }, topicArea: "work" },
        { en: "I see your point, but we should consider other options.", bn: "আমি তোমার বক্তব্য বুঝতে পারছি, কিন্তু আমাদের অন্য বিকল্প বিবেচনা করা উচিত।", slotValues: { CLAUSE: "we should consider other options" }, topicArea: "work" },
        { en: "I see your point, but it might not work for everyone.", bn: "আমি তোমার বক্তব্য বুঝতে পারছি, কিন্তু এটা সবার জন্য কাজ নাও করতে পারে।", slotValues: { CLAUSE: "it might not work for everyone" }, topicArea: "daily_life" },
        { en: "I see your point, but the budget is limited.", bn: "আমি তোমার বক্তব্য বুঝতে পারছি, কিন্তু বাজেট সীমিত।", slotValues: { CLAUSE: "the budget is limited" }, topicArea: "shopping" },
        { en: "I see your point, but studying alone isn't always effective.", bn: "আমি তোমার বক্তব্য বুঝতে পারছি, কিন্তু একা পড়াশোনা সবসময় কার্যকর নয়।", slotValues: { CLAUSE: "studying alone isn't always effective" }, topicArea: "education" },
        { en: "I see your point, but spicy food isn't good for your stomach.", bn: "আমি তোমার বক্তব্য বুঝতে পারছি, কিন্তু ঝাল খাবার তোমার পেটের জন্য ভালো না।", slotValues: { CLAUSE: "spicy food isn't good for your stomach" }, topicArea: "food" },
        { en: "I see your point, but rest is also important.", bn: "আমি তোমার বক্তব্য বুঝতে পারছি, কিন্তু বিশ্রামও গুরুত্বপূর্ণ।", slotValues: { CLAUSE: "rest is also important" }, topicArea: "health" },
        { en: "I see your point, but flying would save time.", bn: "আমি তোমার বক্তব্য বুঝতে পারছি, কিন্তু উড়ে গেলে সময় বাঁচবে।", slotValues: { CLAUSE: "flying would save time" }, topicArea: "travel" },
        { en: "I see your point, but I think she deserves another chance.", bn: "আমি তোমার বক্তব্য বুঝতে পারছি, কিন্তু আমি মনে করি সে আরেকটি সুযোগ পাওয়ার যোগ্য।", slotValues: { CLAUSE: "I think she deserves another chance" }, topicArea: "relationships" },
        { en: "I see your point, but quality should come first.", bn: "আমি তোমার বক্তব্য বুঝতে পারছি, কিন্তু মান প্রথমে আসা উচিত।", slotValues: { CLAUSE: "quality should come first" }, topicArea: "work" },
        { en: "I see your point, but we can't ignore the risks.", bn: "আমি তোমার বক্তব্য বুঝতে পারছি, কিন্তু আমরা ঝুঁকি উপেক্ষা করতে পারি না।", slotValues: { CLAUSE: "we can't ignore the risks" }, topicArea: "health" },
        { en: "I see your point, but the students need more practice.", bn: "আমি তোমার বক্তব্য বুঝতে পারছি, কিন্তু ছাত্রদের আরও অনুশীলন দরকার।", slotValues: { CLAUSE: "the students need more practice" }, topicArea: "education" },
        { en: "I see your point, but home-cooked is healthier.", bn: "আমি তোমার বক্তব্য বুঝতে পারছি, কিন্তু ঘরে রান্না করা বেশি স্বাস্থ্যকর।", slotValues: { CLAUSE: "home-cooked is healthier" }, topicArea: "food" },
        { en: "I see your point, but we should book in advance.", bn: "আমি তোমার বক্তব্য বুঝতে পারছি, কিন্তু আমাদের আগে থেকে বুকিং করা উচিত।", slotValues: { CLAUSE: "we should book in advance" }, topicArea: "travel" },
        { en: "I see your point, but online reviews can be misleading.", bn: "আমি তোমার বক্তব্য বুঝতে পারছি, কিন্তু অনলাইন রিভিউ বিভ্রান্তিকর হতে পারে।", slotValues: { CLAUSE: "online reviews can be misleading" }, topicArea: "shopping" },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote: "This is a diplomatic way to disagree. It acknowledges the other person's viewpoint before presenting your own.",
      usageNote_bn: "এটি মতবিরোধ প্রকাশের একটি কূটনৈতিক উপায়। এটি আপনার নিজের মতামত উপস্থাপনের আগে অন্য ব্যক্তির দৃষ্টিভঙ্গি স্বীকার করে।",
      combinableWith: ["E2.3"],
      banglaStructureMap: "আমি তোমার বক্তব্য বুঝতে পারছি (Intro) + কিন্তু (Conjunction) + [CLAUSE] (Main clause)",
    },
    {
      id: "E2.3",
      formula: "I don't think [CLAUSE]",
      formula_bn: "আমি মনে করি না [বাক্যাংশ]",
      patternName: "Polite Disagreement",
      patternName_bn: "ভদ্র অসম্মতি",
      slots: [
        {
          name: "CLAUSE",
          description: "A clause describing what you disagree with",
          description_bn: "একটি উপবাক্য যা আপনি কিসের সাথে একমত নন তা বর্ণনা করে",
          acceptedTypes: ["clause"],
          examples: ["that's a good idea", "we should wait any longer", "it's necessary"],
        },
      ],
      examples: [
        { en: "I don't think that's a good idea.", bn: "আমি মনে করি না এটা ভালো আইডিয়া।", slotValues: { CLAUSE: "that's a good idea" }, topicArea: "daily_life" },
        { en: "I don't think we should wait any longer.", bn: "আমি মনে করি না আমাদের আর অপেক্ষা করা উচিত।", slotValues: { CLAUSE: "we should wait any longer" }, topicArea: "work" },
        { en: "I don't think it's necessary.", bn: "আমি মনে করি না এটা প্রয়োজনীয়।", slotValues: { CLAUSE: "it's necessary" }, topicArea: "daily_life" },
        { en: "I don't think the exam was fair.", bn: "আমি মনে করি না পরীক্ষাটি ন্যায্য ছিল।", slotValues: { CLAUSE: "the exam was fair" }, topicArea: "education" },
        { en: "I don't think this diet will work for me.", bn: "আমি মনে করি না এই ডায়েট আমার জন্য কাজ করবে।", slotValues: { CLAUSE: "this diet will work for me" }, topicArea: "health" },
        { en: "I don't think this restaurant is worth the price.", bn: "আমি মনে করি না এই রেস্তোরাঁ দামের তুলনায় যোগ্য।", slotValues: { CLAUSE: "this restaurant is worth the price" }, topicArea: "food" },
        { en: "I don't think we need to book a guide.", bn: "আমি মনে করি না আমাদের গাইড বুক করার দরকার আছে।", slotValues: { CLAUSE: "we need to book a guide" }, topicArea: "travel" },
        { en: "I don't think he meant to hurt you.", bn: "আমি মনে করি না সে তোমাকে কষ্ট দিতে চেয়েছে।", slotValues: { CLAUSE: "he meant to hurt you" }, topicArea: "relationships" },
        { en: "I don't think this product is genuine.", bn: "আমি মনে করি না এই পণ্যটি আসল।", slotValues: { CLAUSE: "this product is genuine" }, topicArea: "shopping" },
        { en: "I don't think the deadline is realistic.", bn: "আমি মনে করি না সময়সীমাটি বাস্তবসম্মত।", slotValues: { CLAUSE: "the deadline is realistic" }, topicArea: "work" },
        { en: "I don't think memorizing is the best way to learn.", bn: "আমি মনে করি না মুখস্থ করা শেখার সেরা উপায়।", slotValues: { CLAUSE: "memorizing is the best way to learn" }, topicArea: "education" },
        { en: "I don't think skipping meals is healthy.", bn: "আমি মনে করি না খাবার বাদ দেওয়া স্বাস্থ্যকর।", slotValues: { CLAUSE: "skipping meals is healthy" }, topicArea: "health" },
        { en: "I don't think that hotel has good reviews.", bn: "আমি মনে করি না সেই হোটেলের ভালো রিভিউ আছে।", slotValues: { CLAUSE: "that hotel has good reviews" }, topicArea: "travel" },
        { en: "I don't think adding sugar is a good idea for this recipe.", bn: "আমি মনে করি না এই রেসিপিতে চিনি দেওয়া ভালো আইডিয়া।", slotValues: { CLAUSE: "adding sugar is a good idea for this recipe" }, topicArea: "food" },
        { en: "I don't think it's fair to blame her.", bn: "আমি মনে করি না তাকে দোষ দেওয়া ন্যায্য।", slotValues: { CLAUSE: "it's fair to blame her" }, topicArea: "relationships" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "'I don't think' is a softer way to disagree than saying 'That's wrong.' It's widely used in everyday English.",
      usageNote_bn: "'I don't think' 'That's wrong' বলার চেয়ে নরমভাবে মতবিরোধ প্রকাশের উপায়। এটি দৈনন্দিন ইংরেজিতে ব্যাপকভাবে ব্যবহৃত।",
      combinableWith: ["E2.2"],
      banglaStructureMap: "আমি মনে করি না (Subject + Neg. Verb) + [CLAUSE] (Subordinate clause)",
    },
    {
      id: "E2.4",
      formula: "Actually, [COUNTER]",
      formula_bn: "আসলে, [বিপরীত যুক্তি]",
      patternName: "Corrective Disagreement",
      patternName_bn: "সংশোধনমূলক অসম্মতি",
      slots: [
        {
          name: "COUNTER",
          description: "A clause presenting a contrasting or corrective viewpoint",
          description_bn: "একটি উপবাক্য যা বিপরীত বা সংশোধনমূলক দৃষ্টিভঙ্গি উপস্থাপন করে",
          acceptedTypes: ["clause"],
          examples: ["I think it's the other way around", "the deadline was yesterday", "she did mention it earlier"],
        },
      ],
      examples: [
        { en: "Actually, I think it's the other way around.", bn: "আসলে, আমি মনে করি ব্যাপারটা উল্টো।", slotValues: { COUNTER: "I think it's the other way around" }, topicArea: "daily_life" },
        { en: "Actually, the deadline was yesterday.", bn: "আসলে, সময়সীমা ছিল গতকাল।", slotValues: { COUNTER: "the deadline was yesterday" }, topicArea: "work" },
        { en: "Actually, she did mention it earlier.", bn: "আসলে, সে আগেই বলেছিল।", slotValues: { COUNTER: "she did mention it earlier" }, topicArea: "relationships" },
        { en: "Actually, the answer is different.", bn: "আসলে, উত্তরটা আলাদা।", slotValues: { COUNTER: "the answer is different" }, topicArea: "education" },
        { en: "Actually, this medicine needs a prescription.", bn: "আসলে, এই ওষুধের জন্য প্রেসক্রিপশন লাগবে।", slotValues: { COUNTER: "this medicine needs a prescription" }, topicArea: "health" },
        { en: "Actually, the restaurant closes at nine, not ten.", bn: "আসলে, রেস্তোরাঁটি নয়টায় বন্ধ হয়, দশটায় নয়।", slotValues: { COUNTER: "the restaurant closes at nine, not ten" }, topicArea: "food" },
        { en: "Actually, the flight leaves from a different terminal.", bn: "আসলে, ফ্লাইটটি ভিন্ন টার্মিনাল থেকে ছাড়বে।", slotValues: { COUNTER: "the flight leaves from a different terminal" }, topicArea: "travel" },
        { en: "Actually, the price has gone down.", bn: "আসলে, দাম কমে গেছে।", slotValues: { COUNTER: "the price has gone down" }, topicArea: "shopping" },
        { en: "Actually, the meeting was rescheduled.", bn: "আসলে, মিটিংটি পুনঃনির্ধারিত হয়েছে।", slotValues: { COUNTER: "the meeting was rescheduled" }, topicArea: "work" },
        { en: "Actually, the test is next week, not this week.", bn: "আসলে, পরীক্ষা আগামী সপ্তাহে, এই সপ্তাহে নয়।", slotValues: { COUNTER: "the test is next week, not this week" }, topicArea: "education" },
        { en: "Actually, walking is better for recovery.", bn: "আসলে, সুস্থতার জন্য হাঁটা ভালো।", slotValues: { COUNTER: "walking is better for recovery" }, topicArea: "health" },
        { en: "Actually, he apologized already.", bn: "আসলে, সে ইতিমধ্যে ক্ষমা চেয়েছে।", slotValues: { COUNTER: "he apologized already" }, topicArea: "relationships" },
        { en: "Actually, the hotel includes breakfast.", bn: "আসলে, হোটেলে সকালের নাস্তা অন্তর্ভুক্ত।", slotValues: { COUNTER: "the hotel includes breakfast" }, topicArea: "travel" },
        { en: "Actually, this brand is cheaper.", bn: "আসলে, এই ব্র্যান্ড সস্তা।", slotValues: { COUNTER: "this brand is cheaper" }, topicArea: "shopping" },
        { en: "Actually, the recipe calls for butter, not oil.", bn: "আসলে, রেসিপিতে তেল নয়, মাখন লাগে।", slotValues: { COUNTER: "the recipe calls for butter, not oil" }, topicArea: "food" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "'Actually' gently introduces a correction or a contrasting fact. It's not aggressive but signals you have different information.",
      usageNote_bn: "'Actually' মৃদুভাবে একটি সংশোধন বা বিপরীত তথ্য উপস্থাপন করে। এটি আক্রমণাত্মক নয় কিন্তু সংকেত দেয় আপনার কাছে ভিন্ন তথ্য আছে।",
      combinableWith: ["E2.3"],
      banglaStructureMap: "আসলে (Adverb) + [COUNTER] (Main clause)",
    },
    {
      id: "E2.5",
      formula: "You're right about [POINT]",
      formula_bn: "[বিষয়] সম্পর্কে তুমি ঠিক বলেছ",
      patternName: "Acknowledging a Valid Point",
      patternName_bn: "সঠিক বিষয় স্বীকার করা",
      slots: [
        {
          name: "POINT",
          description: "A noun or noun phrase describing the specific point you agree with",
          description_bn: "একটি বিশেষ্য বা বিশেষ্য পদবন্ধ যা আপনি যে নির্দিষ্ট বিষয়ে সম্মত তা বর্ণনা করে",
          acceptedTypes: ["noun", "gerund"],
          examples: ["that", "the timing", "the need for change"],
        },
      ],
      examples: [
        { en: "You're right about that.", bn: "তুমি সেটা সম্পর্কে ঠিক বলেছ।", slotValues: { POINT: "that" }, topicArea: "daily_life" },
        { en: "You're right about the timing.", bn: "তুমি সময় সম্পর্কে ঠিক বলেছ।", slotValues: { POINT: "the timing" }, topicArea: "work" },
        { en: "You're right about the need for change.", bn: "তুমি পরিবর্তনের প্রয়োজনীয়তা সম্পর্কে ঠিক বলেছ।", slotValues: { POINT: "the need for change" }, topicArea: "work" },
        { en: "You're right about the grammar rule.", bn: "তুমি ব্যাকরণের নিয়ম সম্পর্কে ঠিক বলেছ।", slotValues: { POINT: "the grammar rule" }, topicArea: "education" },
        { en: "You're right about the side effects.", bn: "তুমি পার্শ্বপ্রতিক্রিয়া সম্পর্কে ঠিক বলেছ।", slotValues: { POINT: "the side effects" }, topicArea: "health" },
        { en: "You're right about the food being too salty.", bn: "তুমি খাবারে অতিরিক্ত লবণ হওয়া সম্পর্কে ঠিক বলেছ।", slotValues: { POINT: "the food being too salty" }, topicArea: "food" },
        { en: "You're right about the route being shorter.", bn: "তুমি পথটি ছোট হওয়া সম্পর্কে ঠিক বলেছ।", slotValues: { POINT: "the route being shorter" }, topicArea: "travel" },
        { en: "You're right about the price difference.", bn: "তুমি দামের পার্থক্য সম্পর্কে ঠিক বলেছ।", slotValues: { POINT: "the price difference" }, topicArea: "shopping" },
        { en: "You're right about needing more communication.", bn: "তুমি আরও যোগাযোগের প্রয়োজনীয়তা সম্পর্কে ঠিক বলেছ।", slotValues: { POINT: "needing more communication" }, topicArea: "relationships" },
        { en: "You're right about the deadline being too tight.", bn: "তুমি সময়সীমা অনেক কঠোর হওয়া সম্পর্কে ঠিক বলেছ।", slotValues: { POINT: "the deadline being too tight" }, topicArea: "work" },
        { en: "You're right about the importance of practice.", bn: "তুমি অনুশীলনের গুরুত্ব সম্পর্কে ঠিক বলেছ।", slotValues: { POINT: "the importance of practice" }, topicArea: "education" },
        { en: "You're right about needing to rest more.", bn: "তুমি আরও বিশ্রামের প্রয়োজনীয়তা সম্পর্কে ঠিক বলেছ।", slotValues: { POINT: "needing to rest more" }, topicArea: "health" },
        { en: "You're right about the hotel being overpriced.", bn: "তুমি হোটেলের দাম বেশি হওয়া সম্পর্কে ঠিক বলেছ।", slotValues: { POINT: "the hotel being overpriced" }, topicArea: "travel" },
        { en: "You're right about the recipe needing more spice.", bn: "তুমি রেসিপিতে আরও মশলা দরকার সম্পর্কে ঠিক বলেছ।", slotValues: { POINT: "the recipe needing more spice" }, topicArea: "food" },
        { en: "You're right about the return policy.", bn: "তুমি ফেরতের নীতি সম্পর্কে ঠিক বলেছ।", slotValues: { POINT: "the return policy" }, topicArea: "shopping" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "'You're right about' validates a specific point someone made. It's a great way to build rapport even during disagreements.",
      usageNote_bn: "'You're right about' কেউ যে নির্দিষ্ট বিষয় বলেছে তা যথার্থ বলে স্বীকার করে। মতবিরোধের সময়ও সম্পর্ক গড়ার দারুণ উপায়।",
      combinableWith: ["E2.1"],
      banglaStructureMap: "[POINT] সম্পর্কে (Object + Postposition) + তুমি ঠিক বলেছ (Subject + Verb)",
    },
    {
      id: "E2.6",
      formula: "I couldn't agree more",
      formula_bn: "আমি আরও বেশি সম্মত হতে পারি না",
      patternName: "Strong Agreement (Couldn't Agree More)",
      patternName_bn: "দৃঢ় সম্মতি (আরও বেশি সম্মত হতে পারি না)",
      slots: [],
      examples: [
        { en: "\"Education is important.\" \"I couldn't agree more.\"", bn: "\"শিক্ষা গুরুত্বপূর্ণ।\" \"আমি আরও বেশি সম্মত হতে পারি না।\"", slotValues: {}, topicArea: "education" },
        { en: "\"We need to act now.\" \"I couldn't agree more.\"", bn: "\"আমাদের এখনই পদক্ষেপ নিতে হবে।\" \"আমি আরও বেশি সম্মত হতে পারি না।\"", slotValues: {}, topicArea: "work" },
        { en: "\"Health should be a priority.\" \"I couldn't agree more.\"", bn: "\"স্বাস্থ্যকে অগ্রাধিকার দেওয়া উচিত।\" \"আমি আরও বেশি সম্মত হতে পারি না।\"", slotValues: {}, topicArea: "health" },
        { en: "\"Family comes first.\" \"I couldn't agree more.\"", bn: "\"পরিবার সবার আগে।\" \"আমি আরও বেশি সম্মত হতে পারি না।\"", slotValues: {}, topicArea: "relationships" },
        { en: "\"Homemade food is the best.\" \"I couldn't agree more.\"", bn: "\"ঘরে তৈরি খাবার সেরা।\" \"আমি আরও বেশি সম্মত হতে পারি না।\"", slotValues: {}, topicArea: "food" },
        { en: "\"Traveling broadens the mind.\" \"I couldn't agree more.\"", bn: "\"ভ্রমণ মনকে বিস্তৃত করে।\" \"আমি আরও বেশি সম্মত হতে পারি না।\"", slotValues: {}, topicArea: "travel" },
        { en: "\"Quality matters more than price.\" \"I couldn't agree more.\"", bn: "\"দামের চেয়ে মান বেশি গুরুত্বপূর্ণ।\" \"আমি আরও বেশি সম্মত হতে পারি না।\"", slotValues: {}, topicArea: "shopping" },
        { en: "\"We should respect everyone.\" \"I couldn't agree more.\"", bn: "\"আমাদের সবাইকে সম্মান করা উচিত।\" \"আমি আরও বেশি সম্মত হতে পারি না।\"", slotValues: {}, topicArea: "daily_life" },
        { en: "\"Teamwork makes a huge difference.\" \"I couldn't agree more.\"", bn: "\"দলগত কাজ বিশাল পার্থক্য আনে।\" \"আমি আরও বেশি সম্মত হতে পারি না।\"", slotValues: {}, topicArea: "work" },
        { en: "\"Practice makes perfect.\" \"I couldn't agree more.\"", bn: "\"অনুশীলনেই পরিপূর্ণতা।\" \"আমি আরও বেশি সম্মত হতে পারি না।\"", slotValues: {}, topicArea: "education" },
        { en: "\"Getting enough sleep is essential.\" \"I couldn't agree more.\"", bn: "\"পর্যাপ্ত ঘুম অপরিহার্য।\" \"আমি আরও বেশি সম্মত হতে পারি না।\"", slotValues: {}, topicArea: "health" },
        { en: "\"Honesty is the best policy.\" \"I couldn't agree more.\"", bn: "\"সততাই সর্বোৎকৃষ্ট নীতি।\" \"আমি আরও বেশি সম্মত হতে পারি না।\"", slotValues: {}, topicArea: "relationships" },
        { en: "\"Fresh ingredients make all the difference.\" \"I couldn't agree more.\"", bn: "\"তাজা উপকরণ সব পার্থক্য গড়ে দেয়।\" \"আমি আরও বেশি সম্মত হতে পারি না।\"", slotValues: {}, topicArea: "food" },
        { en: "\"You should always plan before traveling.\" \"I couldn't agree more.\"", bn: "\"ভ্রমণের আগে সবসময় পরিকল্পনা করা উচিত।\" \"আমি আরও বেশি সম্মত হতে পারি না।\"", slotValues: {}, topicArea: "travel" },
        { en: "\"It's important to save money.\" \"I couldn't agree more.\"", bn: "\"টাকা সঞ্চয় করা গুরুত্বপূর্ণ।\" \"আমি আরও বেশি সম্মত হতে পারি না।\"", slotValues: {}, topicArea: "shopping" },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote: "'I couldn't agree more' is an emphatic way to express total agreement. It literally means 'it is impossible for me to agree more than I already do.'",
      usageNote_bn: "'I couldn't agree more' সম্পূর্ণ সম্মতি প্রকাশের একটি জোরালো উপায়। এর আক্ষরিক অর্থ 'আমি ইতিমধ্যে যতটুকু সম্মত তার চেয়ে বেশি সম্মত হওয়া আমার পক্ষে অসম্ভব।'",
      combinableWith: ["E2.1", "E2.5"],
      banglaStructureMap: "আমি (Subject) + আরও বেশি সম্মত হতে পারি না (Negative ability + Verb)",
    },
    {
      id: "E2.7",
      formula: "I beg to differ",
      formula_bn: "আমি ভিন্নমত পোষণ করি",
      patternName: "Formal Disagreement (Beg to Differ)",
      patternName_bn: "আনুষ্ঠানিক অসম্মতি (ভিন্নমত পোষণ)",
      slots: [],
      examples: [
        { en: "\"This is the best approach.\" \"I beg to differ.\"", bn: "\"এটাই সেরা পদ্ধতি।\" \"আমি ভিন্নমত পোষণ করি।\"", slotValues: {}, topicArea: "work" },
        { en: "\"Students don't need homework.\" \"I beg to differ.\"", bn: "\"ছাত্রদের হোমওয়ার্কের দরকার নেই।\" \"আমি ভিন্নমত পোষণ করি।\"", slotValues: {}, topicArea: "education" },
        { en: "\"Money can buy happiness.\" \"I beg to differ.\"", bn: "\"টাকা দিয়ে সুখ কেনা যায়।\" \"আমি ভিন্নমত পোষণ করি।\"", slotValues: {}, topicArea: "daily_life" },
        { en: "\"Dieting is the only way to lose weight.\" \"I beg to differ.\"", bn: "\"ডায়েটিংই ওজন কমানোর একমাত্র উপায়।\" \"আমি ভিন্নমত পোষণ করি।\"", slotValues: {}, topicArea: "health" },
        { en: "\"Fast food is always unhealthy.\" \"I beg to differ.\"", bn: "\"ফাস্ট ফুড সবসময় অস্বাস্থ্যকর।\" \"আমি ভিন্নমত পোষণ করি।\"", slotValues: {}, topicArea: "food" },
        { en: "\"Traveling alone is dangerous.\" \"I beg to differ.\"", bn: "\"একা ভ্রমণ করা বিপজ্জনক।\" \"আমি ভিন্নমত পোষণ করি।\"", slotValues: {}, topicArea: "travel" },
        { en: "\"Online shopping is a waste of time.\" \"I beg to differ.\"", bn: "\"অনলাইন কেনাকাটা সময়ের অপচয়।\" \"আমি ভিন্নমত পোষণ করি।\"", slotValues: {}, topicArea: "shopping" },
        { en: "\"Long-distance relationships never work.\" \"I beg to differ.\"", bn: "\"দূরের সম্পর্ক কখনো কাজ করে না।\" \"আমি ভিন্নমত পোষণ করি।\"", slotValues: {}, topicArea: "relationships" },
        { en: "\"The project is on track.\" \"I beg to differ.\"", bn: "\"প্রজেক্টটি ঠিকমতো চলছে।\" \"আমি ভিন্নমত পোষণ করি।\"", slotValues: {}, topicArea: "work" },
        { en: "\"Grammar isn't important for communication.\" \"I beg to differ.\"", bn: "\"যোগাযোগের জন্য ব্যাকরণ গুরুত্বপূর্ণ নয়।\" \"আমি ভিন্নমত পোষণ করি।\"", slotValues: {}, topicArea: "education" },
        { en: "\"You don't need exercise if you eat well.\" \"I beg to differ.\"", bn: "\"ভালো খেলে ব্যায়ামের দরকার নেই।\" \"আমি ভিন্নমত পোষণ করি।\"", slotValues: {}, topicArea: "health" },
        { en: "\"Spicy food is bad for you.\" \"I beg to differ.\"", bn: "\"ঝাল খাবার আপনার জন্য ক্ষতিকর।\" \"আমি ভিন্নমত পোষণ করি।\"", slotValues: {}, topicArea: "food" },
        { en: "\"Budget travel isn't enjoyable.\" \"I beg to differ.\"", bn: "\"বাজেট ভ্রমণ উপভোগ্য নয়।\" \"আমি ভিন্নমত পোষণ করি।\"", slotValues: {}, topicArea: "travel" },
        { en: "\"Expensive always means better.\" \"I beg to differ.\"", bn: "\"দামি মানেই সবসময় ভালো।\" \"আমি ভিন্নমত পোষণ করি।\"", slotValues: {}, topicArea: "shopping" },
        { en: "\"Age difference matters in friendship.\" \"I beg to differ.\"", bn: "\"বন্ধুত্বে বয়সের পার্থক্য গুরুত্বপূর্ণ।\" \"আমি ভিন্নমত পোষণ করি।\"", slotValues: {}, topicArea: "relationships" },
      ],
      formality: "very_formal",
      difficulty: "intermediate",
      usageNote: "'I beg to differ' is a very formal and polite way to express disagreement. It is often used in professional, academic, or debate settings.",
      usageNote_bn: "'I beg to differ' মতবিরোধ প্রকাশের একটি অত্যন্ত আনুষ্ঠানিক ও ভদ্র উপায়। এটি প্রায়ই পেশাদার, একাডেমিক বা বিতর্কের পরিবেশে ব্যবহৃত হয়।",
      combinableWith: ["E2.2", "E2.3"],
      banglaStructureMap: "আমি (Subject) + ভিন্নমত পোষণ করি (Verb phrase)",
    },
  ],
};
