import { PatternCategory } from "@/types/pattern";

export const categoryE5: PatternCategory = {
  id: "E5",
  slug: "expressing-disappointment",
  name: "Expressing Disappointment",
  name_bn: "হতাশা প্রকাশ করা",
  description:
    "Learn how to express disappointment and unmet expectations in English.",
  description_bn:
    "ইংরেজিতে হতাশা এবং অপূর্ণ প্রত্যাশা প্রকাশ করতে শিখুন।",
  icon: "😞",
  group: "E",
  groupName: "Opinions, Emotions & Attitudes",
  groupName_bn: "মতামত, আবেগ এবং মনোভাব",
  difficulty: "intermediate",
  patterns: [
    {
      id: "E5.1",
      formula: "I'm disappointed that [CLAUSE]",
      formula_bn: "আমি হতাশ যে [বাক্যাংশ]",
      patternName: "Direct Disappointment",
      patternName_bn: "সরাসরি হতাশা",
      slots: [
        {
          name: "CLAUSE",
          description: "A clause describing the cause of your disappointment",
          description_bn: "একটি উপবাক্য যা আপনার হতাশার কারণ বর্ণনা করে",
          acceptedTypes: ["clause"],
          examples: [
            "the event was canceled",
            "he didn't show up",
            "I didn't get the job",
          ],
        },
      ],
      examples: [
        {
          en: "I'm disappointed that the event was canceled.",
          bn: "আমি হতাশ যে অনুষ্ঠানটি বাতিল হয়ে গেছে।",
          slotValues: { CLAUSE: "the event was canceled" },
          topicArea: "daily_life",
        },
        {
          en: "I'm disappointed that he didn't show up.",
          bn: "আমি হতাশ যে সে আসেনি।",
          slotValues: { CLAUSE: "he didn't show up" },
          topicArea: "relationships",
        },
        {
          en: "I'm disappointed that I didn't get the job.",
          bn: "আমি হতাশ যে আমি চাকরিটা পাইনি।",
          slotValues: { CLAUSE: "I didn't get the job" },
          topicArea: "work",
        },
        {
          en: "I'm disappointed that my grade was so low.",
          bn: "আমি হতাশ যে আমার নম্বর এত কম ছিল।",
          slotValues: { CLAUSE: "my grade was so low" },
          topicArea: "education",
        },
        {
          en: "I'm disappointed that the food wasn't fresh.",
          bn: "আমি হতাশ যে খাবারটি তাজা ছিল না।",
          slotValues: { CLAUSE: "the food wasn't fresh" },
          topicArea: "food",
        },
        {
          en: "I'm disappointed that the treatment didn't work.",
          bn: "আমি হতাশ যে চিকিৎসা কাজ করেনি।",
          slotValues: { CLAUSE: "the treatment didn't work" },
          topicArea: "health",
        },
        {
          en: "I'm disappointed that our trip got postponed.",
          bn: "আমি হতাশ যে আমাদের ভ্রমণ পিছিয়ে গেছে।",
          slotValues: { CLAUSE: "our trip got postponed" },
          topicArea: "travel",
        },
        {
          en: "I'm disappointed that the product broke so quickly.",
          bn: "আমি হতাশ যে পণ্যটি এত তাড়াতাড়ি ভেঙে গেছে।",
          slotValues: { CLAUSE: "the product broke so quickly" },
          topicArea: "shopping",
        },
        {
          en: "I'm disappointed that the team lost.",
          bn: "আমি হতাশ যে দলটি হেরে গেছে।",
          slotValues: { CLAUSE: "the team lost" },
          topicArea: "daily_life",
        },
        {
          en: "I'm disappointed that my proposal was rejected.",
          bn: "আমি হতাশ যে আমার প্রস্তাব প্রত্যাখ্যান হয়েছে।",
          slotValues: { CLAUSE: "my proposal was rejected" },
          topicArea: "work",
        },
        {
          en: "I'm disappointed that nobody came to help.",
          bn: "আমি হতাশ যে কেউ সাহায্য করতে আসেনি।",
          slotValues: { CLAUSE: "nobody came to help" },
          topicArea: "relationships",
        },
        {
          en: "I'm disappointed that the library was closed.",
          bn: "আমি হতাশ যে লাইব্রেরি বন্ধ ছিল।",
          slotValues: { CLAUSE: "the library was closed" },
          topicArea: "education",
        },
        {
          en: "I'm disappointed that the weather ruined our plans.",
          bn: "আমি হতাশ যে আবহাওয়া আমাদের পরিকল্পনা নষ্ট করেছে।",
          slotValues: { CLAUSE: "the weather ruined our plans" },
          topicArea: "travel",
        },
        {
          en: "I'm disappointed that the restaurant ran out of fish.",
          bn: "আমি হতাশ যে রেস্তোরাঁয় মাছ শেষ হয়ে গেছে।",
          slotValues: { CLAUSE: "the restaurant ran out of fish" },
          topicArea: "food",
        },
        {
          en: "I'm disappointed that I still have a cough.",
          bn: "আমি হতাশ যে আমার এখনও কাশি আছে।",
          slotValues: { CLAUSE: "I still have a cough" },
          topicArea: "health",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "'I'm disappointed that' directly states your feeling. It's clear and appropriate for both formal and informal contexts.",
      usageNote_bn:
        "'I'm disappointed that' সরাসরি আপনার অনুভূতি বলে। এটি স্পষ্ট এবং আনুষ্ঠানিক ও অনানুষ্ঠানিক উভয় প্রসঙ্গে উপযুক্ত।",
      combinableWith: ["E5.2"],
      banglaStructureMap:
        "আমি হতাশ (Subject + Adj) + যে (Conjunction) + [CLAUSE] (Subordinate clause)",
    },
    {
      id: "E5.2",
      formula: "I was hoping for [THING]",
      formula_bn: "আমি [জিনিস] আশা করছিলাম",
      patternName: "Unmet Hope",
      patternName_bn: "অপূর্ণ আশা",
      slots: [
        {
          name: "THING",
          description: "A noun or noun phrase describing what you hoped for",
          description_bn: "একটি বিশেষ্য বা বিশেষ্য পদবন্ধ যা আপনি কী আশা করছিলেন তা বর্ণনা করে",
          acceptedTypes: ["noun"],
          examples: ["a better result", "good news", "a sunny day"],
        },
      ],
      examples: [
        {
          en: "I was hoping for a better result.",
          bn: "আমি আরও ভালো ফলাফল আশা করছিলাম।",
          slotValues: { THING: "a better result" },
          topicArea: "education",
        },
        {
          en: "I was hoping for good news.",
          bn: "আমি ভালো খবর আশা করছিলাম।",
          slotValues: { THING: "good news" },
          topicArea: "daily_life",
        },
        {
          en: "I was hoping for a sunny day.",
          bn: "আমি রোদেলা দিন আশা করছিলাম।",
          slotValues: { THING: "a sunny day" },
          topicArea: "travel",
        },
        {
          en: "I was hoping for a raise this year.",
          bn: "আমি এই বছর বেতন বৃদ্ধি আশা করছিলাম।",
          slotValues: { THING: "a raise this year" },
          topicArea: "work",
        },
        {
          en: "I was hoping for something more flavorful.",
          bn: "আমি আরও স্বাদযুক্ত কিছু আশা করছিলাম।",
          slotValues: { THING: "something more flavorful" },
          topicArea: "food",
        },
        {
          en: "I was hoping for a quicker recovery.",
          bn: "আমি আরও দ্রুত সুস্থতা আশা করছিলাম।",
          slotValues: { THING: "a quicker recovery" },
          topicArea: "health",
        },
        {
          en: "I was hoping for a window seat.",
          bn: "আমি জানালার পাশের সিট আশা করছিলাম।",
          slotValues: { THING: "a window seat" },
          topicArea: "travel",
        },
        {
          en: "I was hoping for a bigger discount.",
          bn: "আমি আরও বড় ছাড় আশা করছিলাম।",
          slotValues: { THING: "a bigger discount" },
          topicArea: "shopping",
        },
        {
          en: "I was hoping for a more understanding response.",
          bn: "আমি আরও বোঝাপড়াপূর্ণ সাড়া আশা করছিলাম।",
          slotValues: { THING: "a more understanding response" },
          topicArea: "relationships",
        },
        {
          en: "I was hoping for a positive review from the client.",
          bn: "আমি ক্লায়েন্টের কাছ থেকে ইতিবাচক রিভিউ আশা করছিলাম।",
          slotValues: { THING: "a positive review from the client" },
          topicArea: "work",
        },
        {
          en: "I was hoping for a higher score.",
          bn: "আমি আরও বেশি নম্বর আশা করছিলাম।",
          slotValues: { THING: "a higher score" },
          topicArea: "education",
        },
        {
          en: "I was hoping for fresher ingredients.",
          bn: "আমি আরও তাজা উপাদান আশা করছিলাম।",
          slotValues: { THING: "fresher ingredients" },
          topicArea: "food",
        },
        {
          en: "I was hoping for fewer side effects.",
          bn: "আমি কম পার্শ্বপ্রতিক্রিয়া আশা করছিলাম।",
          slotValues: { THING: "fewer side effects" },
          topicArea: "health",
        },
        {
          en: "I was hoping for a full refund.",
          bn: "আমি সম্পূর্ণ টাকা ফেরত আশা করছিলাম।",
          slotValues: { THING: "a full refund" },
          topicArea: "shopping",
        },
        {
          en: "I was hoping for an apology.",
          bn: "আমি একটি ক্ষমা প্রার্থনা আশা করছিলাম।",
          slotValues: { THING: "an apology" },
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'I was hoping for' gently expresses that reality didn't meet your expectations. It's softer than 'I'm disappointed'.",
      usageNote_bn:
        "'I was hoping for' মৃদুভাবে প্রকাশ করে যে বাস্তবতা আপনার প্রত্যাশা পূরণ করেনি। এটি 'I'm disappointed'-এর চেয়ে নরম।",
      combinableWith: ["E5.1"],
      banglaStructureMap:
        "আমি (Subject) + [THING] (Object) + আশা করছিলাম (Past Continuous Verb)",
    },
    {
      id: "E5.3",
      formula: "It's a shame that [CLAUSE]",
      formula_bn: "দুঃখের বিষয় যে [বাক্যাংশ]",
      patternName: "Expressing Regret",
      patternName_bn: "দুঃখ প্রকাশ",
      slots: [
        {
          name: "CLAUSE",
          description: "A clause describing the unfortunate situation",
          description_bn: "একটি উপবাক্য যা দুর্ভাগ্যজনক পরিস্থিতি বর্ণনা করে",
          acceptedTypes: ["clause"],
          examples: [
            "they closed the park",
            "you can't come",
            "the project failed",
          ],
        },
      ],
      examples: [
        {
          en: "It's a shame that they closed the park.",
          bn: "দুঃখের বিষয় যে তারা পার্কটি বন্ধ করে দিয়েছে।",
          slotValues: { CLAUSE: "they closed the park" },
          topicArea: "daily_life",
        },
        {
          en: "It's a shame that you can't come.",
          bn: "দুঃখের বিষয় যে তুমি আসতে পারছ না।",
          slotValues: { CLAUSE: "you can't come" },
          topicArea: "relationships",
        },
        {
          en: "It's a shame that the project failed.",
          bn: "দুঃখের বিষয় যে প্রকল্পটি ব্যর্থ হয়েছে।",
          slotValues: { CLAUSE: "the project failed" },
          topicArea: "work",
        },
        {
          en: "It's a shame that the school doesn't have a library.",
          bn: "দুঃখের বিষয় যে স্কুলে লাইব্রেরি নেই।",
          slotValues: { CLAUSE: "the school doesn't have a library" },
          topicArea: "education",
        },
        {
          en: "It's a shame that the restaurant stopped making this dish.",
          bn: "দুঃখের বিষয় যে রেস্তোরাঁটি এই খাবার বানানো বন্ধ করে দিয়েছে।",
          slotValues: { CLAUSE: "the restaurant stopped making this dish" },
          topicArea: "food",
        },
        {
          en: "It's a shame that the clinic is so far away.",
          bn: "দুঃখের বিষয় যে ক্লিনিকটি এত দূরে।",
          slotValues: { CLAUSE: "the clinic is so far away" },
          topicArea: "health",
        },
        {
          en: "It's a shame that we missed the sunset.",
          bn: "দুঃখের বিষয় যে আমরা সূর্যাস্ত দেখতে পাইনি।",
          slotValues: { CLAUSE: "we missed the sunset" },
          topicArea: "travel",
        },
        {
          en: "It's a shame that the sale ended yesterday.",
          bn: "দুঃখের বিষয় যে সেল গতকাল শেষ হয়ে গেছে।",
          slotValues: { CLAUSE: "the sale ended yesterday" },
          topicArea: "shopping",
        },
        {
          en: "It's a shame that the meeting was unproductive.",
          bn: "দুঃখের বিষয় যে মিটিংটি অনুৎপাদনশীল ছিল।",
          slotValues: { CLAUSE: "the meeting was unproductive" },
          topicArea: "work",
        },
        {
          en: "It's a shame that so many students dropped out.",
          bn: "দুঃখের বিষয় যে এত ছাত্র ঝরে পড়েছে।",
          slotValues: { CLAUSE: "so many students dropped out" },
          topicArea: "education",
        },
        {
          en: "It's a shame that the food got cold.",
          bn: "দুঃখের বিষয় যে খাবার ঠান্ডা হয়ে গেছে।",
          slotValues: { CLAUSE: "the food got cold" },
          topicArea: "food",
        },
        {
          en: "It's a shame that the hospital is understaffed.",
          bn: "দুঃখের বিষয় যে হাসপাতালে কর্মী ঘাটতি আছে।",
          slotValues: { CLAUSE: "the hospital is understaffed" },
          topicArea: "health",
        },
        {
          en: "It's a shame that the flight was overbooked.",
          bn: "দুঃখের বিষয় যে ফ্লাইটে ওভারবুকিং হয়েছিল।",
          slotValues: { CLAUSE: "the flight was overbooked" },
          topicArea: "travel",
        },
        {
          en: "It's a shame that they don't have my size.",
          bn: "দুঃখের বিষয় যে তাদের কাছে আমার সাইজ নেই।",
          slotValues: { CLAUSE: "they don't have my size" },
          topicArea: "shopping",
        },
        {
          en: "It's a shame that they couldn't resolve their differences.",
          bn: "দুঃখের বিষয় যে তারা তাদের মতপার্থক্য মেটাতে পারেনি।",
          slotValues: { CLAUSE: "they couldn't resolve their differences" },
          topicArea: "relationships",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "'It's a shame that' expresses sympathy or regret about an unfortunate situation. It can be used for both your own and others' situations.",
      usageNote_bn:
        "'It's a shame that' দুর্ভাগ্যজনক পরিস্থিতিতে সহানুভূতি বা দুঃখ প্রকাশ করে। এটি আপনার নিজের এবং অন্যদের পরিস্থিতি উভয়ের জন্য ব্যবহার করা যায়।",
      combinableWith: ["E5.1"],
      banglaStructureMap:
        "দুঃখের বিষয় (Intro) + যে (Conjunction) + [CLAUSE] (Subordinate clause)",
    },
    {
      id: "E5.4",
      formula: "Unfortunately, [CLAUSE]",
      formula_bn: "দুর্ভাগ্যবশত, [বাক্যাংশ]",
      patternName: "Formal Disappointment",
      patternName_bn: "আনুষ্ঠানিক হতাশা",
      slots: [
        {
          name: "CLAUSE",
          description: "A clause describing the unfortunate outcome",
          description_bn: "একটি উপবাক্য যা দুর্ভাগ্যজনক ফলাফল বর্ণনা করে",
          acceptedTypes: ["clause"],
          examples: [
            "the plan didn't work",
            "I won't be able to attend",
            "the store was closed",
          ],
        },
      ],
      examples: [
        {
          en: "Unfortunately, the plan didn't work.",
          bn: "দুর্ভাগ্যবশত, পরিকল্পনা কাজ করেনি।",
          slotValues: { CLAUSE: "the plan didn't work" },
          topicArea: "work",
        },
        {
          en: "Unfortunately, I won't be able to attend.",
          bn: "দুর্ভাগ্যবশত, আমি উপস্থিত থাকতে পারব না।",
          slotValues: { CLAUSE: "I won't be able to attend" },
          topicArea: "daily_life",
        },
        {
          en: "Unfortunately, the store was closed when we arrived.",
          bn: "দুর্ভাগ্যবশত, আমরা পৌঁছানোর সময় দোকান বন্ধ ছিল।",
          slotValues: { CLAUSE: "the store was closed when we arrived" },
          topicArea: "shopping",
        },
        {
          en: "Unfortunately, the scholarship was given to someone else.",
          bn: "দুর্ভাগ্যবশত, বৃত্তিটি অন্য কাউকে দেওয়া হয়েছে।",
          slotValues: { CLAUSE: "the scholarship was given to someone else" },
          topicArea: "education",
        },
        {
          en: "Unfortunately, the surgery was postponed.",
          bn: "দুর্ভাগ্যবশত, অপারেশন স্থগিত হয়েছে।",
          slotValues: { CLAUSE: "the surgery was postponed" },
          topicArea: "health",
        },
        {
          en: "Unfortunately, the dish was overcooked.",
          bn: "দুর্ভাগ্যবশত, খাবারটি অতিরিক্ত রান্না হয়ে গেছে।",
          slotValues: { CLAUSE: "the dish was overcooked" },
          topicArea: "food",
        },
        {
          en: "Unfortunately, the train was delayed by two hours.",
          bn: "দুর্ভাগ্যবশত, ট্রেন দুই ঘণ্টা দেরি হয়েছে।",
          slotValues: { CLAUSE: "the train was delayed by two hours" },
          topicArea: "travel",
        },
        {
          en: "Unfortunately, they couldn't come to the wedding.",
          bn: "দুর্ভাগ্যবশত, তারা বিয়েতে আসতে পারেনি।",
          slotValues: { CLAUSE: "they couldn't come to the wedding" },
          topicArea: "relationships",
        },
        {
          en: "Unfortunately, the budget was cut.",
          bn: "দুর্ভাগ্যবশত, বাজেট কমিয়ে দেওয়া হয়েছে।",
          slotValues: { CLAUSE: "the budget was cut" },
          topicArea: "work",
        },
        {
          en: "Unfortunately, the results won't be out until next month.",
          bn: "দুর্ভাগ্যবশত, আগামী মাস পর্যন্ত ফলাফল প্রকাশ হবে না।",
          slotValues: { CLAUSE: "the results won't be out until next month" },
          topicArea: "education",
        },
        {
          en: "Unfortunately, the medicine is out of stock.",
          bn: "দুর্ভাগ্যবশত, ওষুধটি স্টকে নেই।",
          slotValues: { CLAUSE: "the medicine is out of stock" },
          topicArea: "health",
        },
        {
          en: "Unfortunately, the cafe doesn't serve breakfast anymore.",
          bn: "দুর্ভাগ্যবশত, ক্যাফে আর সকালের নাস্তা পরিবেশন করে না।",
          slotValues: { CLAUSE: "the cafe doesn't serve breakfast anymore" },
          topicArea: "food",
        },
        {
          en: "Unfortunately, the hotel lost our reservation.",
          bn: "দুর্ভাগ্যবশত, হোটেল আমাদের বুকিং হারিয়ে ফেলেছে।",
          slotValues: { CLAUSE: "the hotel lost our reservation" },
          topicArea: "travel",
        },
        {
          en: "Unfortunately, the refund was denied.",
          bn: "দুর্ভাগ্যবশত, ফেরত প্রত্যাখ্যান করা হয়েছে।",
          slotValues: { CLAUSE: "the refund was denied" },
          topicArea: "shopping",
        },
        {
          en: "Unfortunately, we had to cancel the reunion.",
          bn: "দুর্ভাগ্যবশত, আমাদের পুনর্মিলন বাতিল করতে হয়েছে।",
          slotValues: { CLAUSE: "we had to cancel the reunion" },
          topicArea: "relationships",
        },
      ],
      formality: "formal",
      difficulty: "intermediate",
      usageNote:
        "'Unfortunately' is a formal adverb that introduces bad news or a disappointing fact. It's widely used in both speech and writing.",
      usageNote_bn:
        "'Unfortunately' একটি আনুষ্ঠানিক ক্রিয়াবিশেষণ যা খারাপ খবর বা হতাশাজনক তথ্য উপস্থাপন করে। এটি কথা ও লেখা উভয়ে ব্যাপকভাবে ব্যবহৃত।",
      combinableWith: ["E5.3"],
      banglaStructureMap:
        "দুর্ভাগ্যবশত (Adverb) + [CLAUSE] (Main clause)",
    },
    {
      id: "E5.5",
      formula: "I expected better",
      formula_bn: "আমি আরও ভালো আশা করেছিলাম",
      patternName: "Expressing High Expectations Not Met",
      patternName_bn: "উচ্চ প্রত্যাশা পূরণ না হওয়া প্রকাশ",
      slots: [],
      examples: [
        {
          en: "I expected better from this restaurant.",
          bn: "আমি এই রেস্তোরাঁ থেকে আরও ভালো আশা করেছিলাম।",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "I expected better from you.",
          bn: "আমি তোমার কাছ থেকে আরও ভালো আশা করেছিলাম।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "I expected better service at this hotel.",
          bn: "আমি এই হোটেলে আরও ভালো সেবা আশা করেছিলাম।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "I expected better quality for this price.",
          bn: "আমি এই দামে আরও ভালো মান আশা করেছিলাম।",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "I expected better results from the team.",
          bn: "আমি দলের কাছ থেকে আরও ভালো ফলাফল আশা করেছিলাম।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "I expected better grades after studying so hard.",
          bn: "আমি এত কঠোর পড়াশোনার পর আরও ভালো নম্বর আশা করেছিলাম।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "I expected better treatment at the hospital.",
          bn: "আমি হাসপাতালে আরও ভালো চিকিৎসা আশা করেছিলাম।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "I expected better communication from management.",
          bn: "আমি ম্যানেজমেন্টের কাছ থেকে আরও ভালো যোগাযোগ আশা করেছিলাম।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "Honestly, I expected better.",
          bn: "সত্যি বলতে, আমি আরও ভালো আশা করেছিলাম।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "I expected better food on this flight.",
          bn: "আমি এই ফ্লাইটে আরও ভালো খাবার আশা করেছিলাম।",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "I expected better from such a famous brand.",
          bn: "আমি এত নামকরা ব্র্যান্ড থেকে আরও ভালো আশা করেছিলাম।",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "I expected better from my own performance.",
          bn: "আমি আমার নিজের পারফরম্যান্স থেকে আরও ভালো আশা করেছিলাম।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "I expected better from a five-star hotel.",
          bn: "আমি একটি পাঁচ তারা হোটেল থেকে আরও ভালো আশা করেছিলাম।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "I expected better care from the doctor.",
          bn: "আমি ডাক্তারের কাছ থেকে আরও ভালো যত্ন আশা করেছিলাম।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "I expected better understanding between us.",
          bn: "আমি আমাদের মধ্যে আরও ভালো বোঝাপড়া আশা করেছিলাম।",
          slotValues: {},
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'I expected better' is a concise and impactful way to express that something fell below your standards. It can sound blunt.",
      usageNote_bn:
        "'I expected better' প্রকাশ করার একটি সংক্ষিপ্ত ও প্রভাবশালী উপায় যে কিছু আপনার মানের নিচে ছিল। এটি কিছুটা কঠোর শোনাতে পারে।",
      combinableWith: ["E5.1"],
      banglaStructureMap:
        "আমি (Subject) + আরও ভালো (Object) + আশা করেছিলাম (Past Verb)",
    },
  ],
};
