import { PatternCategory } from "@/types/pattern";

export const categoryE9: PatternCategory = {
  id: "E9",
  slug: "expressing-sympathy-condolence",
  name: "Expressing Sympathy & Condolence",
  name_bn: "সহানুভূতি ও সমবেদনা প্রকাশ",
  description: "Learn how to express sympathy and offer condolences in English.",
  description_bn: "ইংরেজিতে সহানুভূতি প্রকাশ ও সমবেদনা জানাতে শিখুন।",
  icon: "🤗",
  group: "E",
  groupName: "Opinions, Emotions & Attitudes",
  groupName_bn: "মতামত, আবেগ ও দৃষ্টিভঙ্গি",
  difficulty: "intermediate",
  patterns: [
    {
      id: "E9.1",
      formula: "I'm sorry to hear about [THING]",
      formula_bn: "আমি [বিষয়ের] কথা শুনে দুঃখিত",
      patternName: "Basic Sympathy",
      patternName_bn: "সাধারণ সহানুভূতি",
      slots: [
        {
          name: "THING",
          description: "A noun phrase describing the unfortunate situation",
          description_bn: "একটি বিশেষ্য পদবন্ধ যা দুর্ভাগ্যজনক পরিস্থিতি বর্ণনা করে",
          acceptedTypes: ["noun_phrase", "noun"],
          examples: ["your loss", "the accident", "your illness"],
        },
      ],
      examples: [
        { en: "I'm sorry to hear about your loss.", bn: "আমি তোমার ক্ষতির কথা শুনে দুঃখিত।", slotValues: { THING: "your loss" }, topicArea: "relationships" },
        { en: "I'm sorry to hear about the accident.", bn: "আমি দুর্ঘটনার কথা শুনে দুঃখিত।", slotValues: { THING: "the accident" }, topicArea: "daily_life" },
        { en: "I'm sorry to hear about your illness.", bn: "আমি তোমার অসুস্থতার কথা শুনে দুঃখিত।", slotValues: { THING: "your illness" }, topicArea: "health" },
        { en: "I'm sorry to hear about the job loss.", bn: "আমি চাকরি হারানোর কথা শুনে দুঃখিত।", slotValues: { THING: "the job loss" }, topicArea: "work" },
        { en: "I'm sorry to hear about the fire at the restaurant.", bn: "আমি রেস্তোরাঁয় আগুনের কথা শুনে দুঃখিত।", slotValues: { THING: "the fire at the restaurant" }, topicArea: "food" },
        { en: "I'm sorry to hear about the cancelled trip.", bn: "আমি ট্রিপ বাতিলের কথা শুনে দুঃখিত।", slotValues: { THING: "the cancelled trip" }, topicArea: "travel" },
        { en: "I'm sorry to hear about the failed exam.", bn: "আমি পরীক্ষায় ফেল করার কথা শুনে দুঃখিত।", slotValues: { THING: "the failed exam" }, topicArea: "education" },
        { en: "I'm sorry to hear about your breakup.", bn: "আমি তোমাদের সম্পর্ক ভাঙার কথা শুনে দুঃখিত।", slotValues: { THING: "your breakup" }, topicArea: "relationships" },
        { en: "I'm sorry to hear about the damaged goods.", bn: "আমি ক্ষতিগ্রস্ত পণ্যের কথা শুনে দুঃখিত।", slotValues: { THING: "the damaged goods" }, topicArea: "shopping" },
        { en: "I'm sorry to hear about the project failure.", bn: "আমি প্রকল্প ব্যর্থ হওয়ার কথা শুনে দুঃখিত।", slotValues: { THING: "the project failure" }, topicArea: "work" },
        { en: "I'm sorry to hear about your grandmother.", bn: "আমি তোমার দাদির কথা শুনে দুঃখিত।", slotValues: { THING: "your grandmother" }, topicArea: "relationships" },
        { en: "I'm sorry to hear about the surgery.", bn: "আমি অস্ত্রোপচারের কথা শুনে দুঃখিত।", slotValues: { THING: "the surgery" }, topicArea: "health" },
        { en: "I'm sorry to hear about the scholarship rejection.", bn: "আমি বৃত্তি প্রত্যাখ্যানের কথা শুনে দুঃখিত।", slotValues: { THING: "the scholarship rejection" }, topicArea: "education" },
        { en: "I'm sorry to hear about the flood damage.", bn: "আমি বন্যার ক্ষতির কথা শুনে দুঃখিত।", slotValues: { THING: "the flood damage" }, topicArea: "daily_life" },
        { en: "I'm sorry to hear about the hotel problems.", bn: "আমি হোটেলের সমস্যার কথা শুনে দুঃখিত।", slotValues: { THING: "the hotel problems" }, topicArea: "travel" },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote: "The most common way to express sympathy. Appropriate in almost any sad situation.",
      usageNote_bn: "সহানুভূতি প্রকাশের সবচেয়ে সাধারণ উপায়। প্রায় যেকোনো দুঃখজনক পরিস্থিতিতে উপযুক্ত।",
    },
    {
      id: "E9.2",
      formula: "That must be [ADJECTIVE]",
      formula_bn: "সেটা নিশ্চয়ই [বিশেষণ]",
      patternName: "Empathetic Response",
      patternName_bn: "সমানুভূতিমূলক প্রতিক্রিয়া",
      slots: [
        {
          name: "ADJECTIVE",
          description: "An adjective describing how the situation must feel",
          description_bn: "একটি বিশেষণ যা পরিস্থিতি কেমন লাগছে তা বর্ণনা করে",
          acceptedTypes: ["adjective", "adjective_phrase"],
          examples: ["really hard", "so frustrating", "very stressful"],
        },
      ],
      examples: [
        { en: "That must be really hard.", bn: "সেটা নিশ্চয়ই খুব কঠিন।", slotValues: { ADJECTIVE: "really hard" }, topicArea: "daily_life" },
        { en: "That must be so frustrating.", bn: "সেটা নিশ্চয়ই খুব হতাশাজনক।", slotValues: { ADJECTIVE: "so frustrating" }, topicArea: "work" },
        { en: "That must be very stressful.", bn: "সেটা নিশ্চয়ই খুব চাপের।", slotValues: { ADJECTIVE: "very stressful" }, topicArea: "work" },
        { en: "That must be really disappointing.", bn: "সেটা নিশ্চয়ই খুব হতাশাজনক।", slotValues: { ADJECTIVE: "really disappointing" }, topicArea: "food" },
        { en: "That must be exhausting.", bn: "সেটা নিশ্চয়ই ক্লান্তিকর।", slotValues: { ADJECTIVE: "exhausting" }, topicArea: "travel" },
        { en: "That must be overwhelming.", bn: "সেটা নিশ্চয়ই অসহনীয়।", slotValues: { ADJECTIVE: "overwhelming" }, topicArea: "education" },
        { en: "That must be painful.", bn: "সেটা নিশ্চয়ই কষ্টদায়ক।", slotValues: { ADJECTIVE: "painful" }, topicArea: "health" },
        { en: "That must be heartbreaking.", bn: "সেটা নিশ্চয়ই হৃদয়বিদারক।", slotValues: { ADJECTIVE: "heartbreaking" }, topicArea: "relationships" },
        { en: "That must be really annoying.", bn: "সেটা নিশ্চয়ই খুব বিরক্তিকর।", slotValues: { ADJECTIVE: "really annoying" }, topicArea: "shopping" },
        { en: "That must be terrifying.", bn: "সেটা নিশ্চয়ই ভয়ংকর।", slotValues: { ADJECTIVE: "terrifying" }, topicArea: "daily_life" },
        { en: "That must be lonely.", bn: "সেটা নিশ্চয়ই একাকীত্বের।", slotValues: { ADJECTIVE: "lonely" }, topicArea: "relationships" },
        { en: "That must be so scary.", bn: "সেটা নিশ্চয়ই খুব ভীতিকর।", slotValues: { ADJECTIVE: "so scary" }, topicArea: "health" },
        { en: "That must be incredibly difficult.", bn: "সেটা নিশ্চয়ই অবিশ্বাস্য রকম কঠিন।", slotValues: { ADJECTIVE: "incredibly difficult" }, topicArea: "work" },
        { en: "That must be confusing.", bn: "সেটা নিশ্চয়ই বিভ্রান্তিকর।", slotValues: { ADJECTIVE: "confusing" }, topicArea: "education" },
        { en: "That must be uncomfortable.", bn: "সেটা নিশ্চয়ই অস্বস্তিকর।", slotValues: { ADJECTIVE: "uncomfortable" }, topicArea: "travel" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "Shows empathy by acknowledging the other person's feelings. Very natural and supportive.",
      usageNote_bn: "অন্যের অনুভূতি স্বীকার করে সমানুভূতি দেখায়। খুবই স্বাভাবিক ও সহায়ক।",
    },
    {
      id: "E9.3",
      formula: "I'm here for you if [CLAUSE]",
      formula_bn: "আমি তোমার পাশে আছি যদি [উক্তি]",
      patternName: "Offering Support",
      patternName_bn: "সহায়তা প্রদান",
      slots: [
        {
          name: "CLAUSE",
          description: "A clause describing the kind of support you're offering",
          description_bn: "একটি উপবাক্য যা আপনি কী ধরনের সহায়তা দিচ্ছেন তা বর্ণনা করে",
          acceptedTypes: ["clause"],
          examples: ["you need anything", "you want to talk", "you need help"],
        },
      ],
      examples: [
        { en: "I'm here for you if you need anything.", bn: "তোমার কিছু দরকার হলে আমি তোমার পাশে আছি।", slotValues: { CLAUSE: "you need anything" }, topicArea: "relationships" },
        { en: "I'm here for you if you want to talk.", bn: "কথা বলতে চাইলে আমি তোমার পাশে আছি।", slotValues: { CLAUSE: "you want to talk" }, topicArea: "relationships" },
        { en: "I'm here for you if you need help.", bn: "সাহায্য লাগলে আমি তোমার পাশে আছি।", slotValues: { CLAUSE: "you need help" }, topicArea: "daily_life" },
        { en: "I'm here for you if you need someone to listen.", bn: "কেউ শুনবে দরকার হলে আমি তোমার পাশে আছি।", slotValues: { CLAUSE: "you need someone to listen" }, topicArea: "relationships" },
        { en: "I'm here for you if you need a hand with work.", bn: "কাজে হাত লাগলে আমি তোমার পাশে আছি।", slotValues: { CLAUSE: "you need a hand with work" }, topicArea: "work" },
        { en: "I'm here for you if you need a home-cooked meal.", bn: "ঘরের রান্না দরকার হলে আমি তোমার পাশে আছি।", slotValues: { CLAUSE: "you need a home-cooked meal" }, topicArea: "food" },
        { en: "I'm here for you if you need a ride to the airport.", bn: "বিমানবন্দরে যেতে লিফট দরকার হলে আমি তোমার পাশে আছি।", slotValues: { CLAUSE: "you need a ride to the airport" }, topicArea: "travel" },
        { en: "I'm here for you if you need help with your studies.", bn: "পড়াশোনায় সাহায্য দরকার হলে আমি তোমার পাশে আছি।", slotValues: { CLAUSE: "you need help with your studies" }, topicArea: "education" },
        { en: "I'm here for you if you need someone to come to the hospital.", bn: "হাসপাতালে কাউকে সাথে দরকার হলে আমি তোমার পাশে আছি।", slotValues: { CLAUSE: "you need someone to come to the hospital" }, topicArea: "health" },
        { en: "I'm here for you if you need to vent.", bn: "মন হালকা করতে চাইলে আমি তোমার পাশে আছি।", slotValues: { CLAUSE: "you need to vent" }, topicArea: "relationships" },
        { en: "I'm here for you if you need a second opinion.", bn: "দ্বিতীয় মতামত দরকার হলে আমি তোমার পাশে আছি।", slotValues: { CLAUSE: "you need a second opinion" }, topicArea: "work" },
        { en: "I'm here for you if things get difficult.", bn: "পরিস্থিতি কঠিন হলে আমি তোমার পাশে আছি।", slotValues: { CLAUSE: "things get difficult" }, topicArea: "daily_life" },
        { en: "I'm here for you if you need company.", bn: "সঙ্গ দরকার হলে আমি তোমার পাশে আছি।", slotValues: { CLAUSE: "you need company" }, topicArea: "relationships" },
        { en: "I'm here for you if you need advice on the treatment.", bn: "চিকিৎসা নিয়ে পরামর্শ দরকার হলে আমি তোমার পাশে আছি।", slotValues: { CLAUSE: "you need advice on the treatment" }, topicArea: "health" },
        { en: "I'm here for you if you ever feel overwhelmed.", bn: "কখনো অসহায় লাগলে আমি তোমার পাশে আছি।", slotValues: { CLAUSE: "you ever feel overwhelmed" }, topicArea: "education" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "Shows emotional availability and willingness to help. Very comforting in difficult times.",
      usageNote_bn: "আবেগীয় উপলব্ধতা ও সাহায্যের ইচ্ছা দেখায়। কঠিন সময়ে খুবই সান্ত্বনাদায়ক।",
    },
    {
      id: "E9.4",
      formula: "I can only imagine how [ADJECTIVE] that is",
      formula_bn: "আমি শুধু কল্পনা করতে পারি সেটা কতটা [বিশেষণ]",
      patternName: "Deep Empathy",
      patternName_bn: "গভীর সমানুভূতি",
      slots: [
        {
          name: "ADJECTIVE",
          description: "An adjective describing the emotional intensity",
          description_bn: "একটি বিশেষণ যা আবেগের তীব্রতা বর্ণনা করে",
          acceptedTypes: ["adjective", "adjective_phrase"],
          examples: ["difficult", "scary", "heartbreaking"],
        },
      ],
      examples: [
        { en: "I can only imagine how difficult that is.", bn: "আমি শুধু কল্পনা করতে পারি সেটা কতটা কঠিন।", slotValues: { ADJECTIVE: "difficult" }, topicArea: "daily_life" },
        { en: "I can only imagine how scary that is.", bn: "আমি শুধু কল্পনা করতে পারি সেটা কতটা ভীতিকর।", slotValues: { ADJECTIVE: "scary" }, topicArea: "health" },
        { en: "I can only imagine how heartbreaking that is.", bn: "আমি শুধু কল্পনা করতে পারি সেটা কতটা হৃদয়বিদারক।", slotValues: { ADJECTIVE: "heartbreaking" }, topicArea: "relationships" },
        { en: "I can only imagine how stressful that is.", bn: "আমি শুধু কল্পনা করতে পারি সেটা কতটা চাপের।", slotValues: { ADJECTIVE: "stressful" }, topicArea: "work" },
        { en: "I can only imagine how disappointing that is.", bn: "আমি শুধু কল্পনা করতে পারি সেটা কতটা হতাশাজনক।", slotValues: { ADJECTIVE: "disappointing" }, topicArea: "food" },
        { en: "I can only imagine how tiring that is.", bn: "আমি শুধু কল্পনা করতে পারি সেটা কতটা ক্লান্তিকর।", slotValues: { ADJECTIVE: "tiring" }, topicArea: "travel" },
        { en: "I can only imagine how frustrating that is.", bn: "আমি শুধু কল্পনা করতে পারি সেটা কতটা হতাশাজনক।", slotValues: { ADJECTIVE: "frustrating" }, topicArea: "education" },
        { en: "I can only imagine how painful that is.", bn: "আমি শুধু কল্পনা করতে পারি সেটা কতটা কষ্টদায়ক।", slotValues: { ADJECTIVE: "painful" }, topicArea: "health" },
        { en: "I can only imagine how lonely that feels.", bn: "আমি শুধু কল্পনা করতে পারি সেটা কতটা একাকীত্বের।", slotValues: { ADJECTIVE: "lonely" }, topicArea: "relationships" },
        { en: "I can only imagine how overwhelming that is.", bn: "আমি শুধু কল্পনা করতে পারি সেটা কতটা অসহনীয়।", slotValues: { ADJECTIVE: "overwhelming" }, topicArea: "work" },
        { en: "I can only imagine how confusing that must be.", bn: "আমি শুধু কল্পনা করতে পারি সেটা কতটা বিভ্রান্তিকর।", slotValues: { ADJECTIVE: "confusing" }, topicArea: "education" },
        { en: "I can only imagine how worrying that is.", bn: "আমি শুধু কল্পনা করতে পারি সেটা কতটা উদ্বেগজনক।", slotValues: { ADJECTIVE: "worrying" }, topicArea: "health" },
        { en: "I can only imagine how upsetting that is.", bn: "আমি শুধু কল্পনা করতে পারি সেটা কতটা মনঃক্ষুণ্ণকর।", slotValues: { ADJECTIVE: "upsetting" }, topicArea: "daily_life" },
        { en: "I can only imagine how draining that is.", bn: "আমি শুধু কল্পনা করতে পারি সেটা কতটা নিঃশেষ করে দেয়।", slotValues: { ADJECTIVE: "draining" }, topicArea: "work" },
        { en: "I can only imagine how anxious you must feel.", bn: "আমি শুধু কল্পনা করতে পারি তুমি কতটা উদ্বিগ্ন।", slotValues: { ADJECTIVE: "anxious" }, topicArea: "relationships" },
      ],
      formality: "polite",
      difficulty: "advanced",
      usageNote: "A deeply empathetic response that acknowledges you haven't experienced it yourself but understand the weight of it.",
      usageNote_bn: "গভীর সমানুভূতিমূলক প্রতিক্রিয়া যা স্বীকার করে আপনি নিজে অভিজ্ঞতা করেননি কিন্তু এর গুরুত্ব বোঝেন।",
    },
    {
      id: "E9.5",
      formula: "Please accept my condolences for [THING]",
      formula_bn: "[বিষয়ের] জন্য আমার সমবেদনা গ্রহণ করুন",
      patternName: "Formal Condolence",
      patternName_bn: "আনুষ্ঠানিক সমবেদনা",
      slots: [
        {
          name: "THING",
          description: "A noun phrase describing the loss or misfortune",
          description_bn: "একটি বিশেষ্য পদবন্ধ যা ক্ষতি বা দুর্ভাগ্য বর্ণনা করে",
          acceptedTypes: ["noun_phrase", "noun"],
          examples: ["your loss", "the passing of your father", "this difficult time"],
        },
      ],
      examples: [
        { en: "Please accept my condolences for your loss.", bn: "আপনার ক্ষতির জন্য আমার সমবেদনা গ্রহণ করুন।", slotValues: { THING: "your loss" }, topicArea: "relationships" },
        { en: "Please accept my condolences for the passing of your father.", bn: "আপনার বাবার মৃত্যুতে আমার সমবেদনা গ্রহণ করুন।", slotValues: { THING: "the passing of your father" }, topicArea: "relationships" },
        { en: "Please accept my condolences for this difficult time.", bn: "এই কঠিন সময়ে আমার সমবেদনা গ্রহণ করুন।", slotValues: { THING: "this difficult time" }, topicArea: "daily_life" },
        { en: "Please accept my condolences for the loss of your colleague.", bn: "আপনার সহকর্মীর মৃত্যুতে আমার সমবেদনা গ্রহণ করুন।", slotValues: { THING: "the loss of your colleague" }, topicArea: "work" },
        { en: "Please accept my condolences for the tragedy.", bn: "এই মর্মান্তিক ঘটনায় আমার সমবেদনা গ্রহণ করুন।", slotValues: { THING: "the tragedy" }, topicArea: "daily_life" },
        { en: "Please accept my condolences for the passing of your mother.", bn: "আপনার মায়ের মৃত্যুতে আমার সমবেদনা গ্রহণ করুন।", slotValues: { THING: "the passing of your mother" }, topicArea: "relationships" },
        { en: "Please accept my condolences for the loss of your beloved pet.", bn: "আপনার প্রিয় পোষা প্রাণীর মৃত্যুতে আমার সমবেদনা গ্রহণ করুন।", slotValues: { THING: "the loss of your beloved pet" }, topicArea: "relationships" },
        { en: "Please accept my condolences for the untimely loss.", bn: "অকাল মৃত্যুতে আমার সমবেদনা গ্রহণ করুন।", slotValues: { THING: "the untimely loss" }, topicArea: "daily_life" },
        { en: "Please accept my condolences for your family's loss.", bn: "আপনার পরিবারের ক্ষতিতে আমার সমবেদনা গ্রহণ করুন।", slotValues: { THING: "your family's loss" }, topicArea: "relationships" },
        { en: "Please accept my condolences for the devastating news.", bn: "এই বিধ্বংসী খবরে আমার সমবেদনা গ্রহণ করুন।", slotValues: { THING: "the devastating news" }, topicArea: "daily_life" },
        { en: "Please accept my condolences for the loss of your mentor.", bn: "আপনার পথপ্রদর্শকের মৃত্যুতে আমার সমবেদনা গ্রহণ করুন।", slotValues: { THING: "the loss of your mentor" }, topicArea: "work" },
        { en: "Please accept my condolences for the sad event.", bn: "এই দুঃখজনক ঘটনায় আমার সমবেদনা গ্রহণ করুন।", slotValues: { THING: "the sad event" }, topicArea: "daily_life" },
        { en: "Please accept my condolences for the passing of your teacher.", bn: "আপনার শিক্ষকের মৃত্যুতে আমার সমবেদনা গ্রহণ করুন।", slotValues: { THING: "the passing of your teacher" }, topicArea: "education" },
        { en: "Please accept my condolences for the sudden loss.", bn: "আকস্মিক মৃত্যুতে আমার সমবেদনা গ্রহণ করুন।", slotValues: { THING: "the sudden loss" }, topicArea: "relationships" },
        { en: "Please accept my condolences for everything you're going through.", bn: "আপনি যা কিছুর মধ্য দিয়ে যাচ্ছেন তার জন্য আমার সমবেদনা গ্রহণ করুন।", slotValues: { THING: "everything you're going through" }, topicArea: "daily_life" },
      ],
      formality: "very_formal",
      difficulty: "advanced",
      usageNote: "Very formal expression used in written condolences, official communications, and solemn occasions.",
      usageNote_bn: "খুবই আনুষ্ঠানিক প্রকাশ যা লিখিত সমবেদনা, সরকারি যোগাযোগ এবং গম্ভীর অনুষ্ঠানে ব্যবহৃত।",
    },
  ],
};
