import { PatternCategory } from "@/types/pattern";

export const categoryF1: PatternCategory = {
  id: "F1",
  slug: "making-suggestions",
  name: "Making Suggestions",
  name_bn: "পরামর্শ দেওয়া",
  description:
    "Learn how to make suggestions and propose ideas in English using common patterns.",
  description_bn:
    "সাধারণ প্যাটার্ন ব্যবহার করে ইংরেজিতে পরামর্শ দিতে ও ধারণা প্রস্তাব করতে শিখুন।",
  icon: "💡",
  group: "F",
  groupName: "Suggestions, Offers & Invitations",
  groupName_bn: "পরামর্শ, প্রস্তাব এবং আমন্ত্রণ",
  difficulty: "intermediate",
  patterns: [
    {
      id: "F1.1",
      formula: "Let's [ACTION]",
      formula_bn: "চলো [কাজ] করি",
      patternName: "Casual Suggestion with Let's",
      patternName_bn: "Let's দিয়ে সাধারণ পরামর্শ",
      slots: [
        {
          name: "ACTION",
          description: "Base form of a verb or verb phrase",
          description_bn: "ক্রিয়ার মূল রূপ বা ক্রিয়া পদবন্ধ",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["go for a walk", "eat out", "start the meeting"],
        },
      ],
      examples: [
        {
          en: "Let's go for a walk.",
          bn: "চলো হাঁটতে যাই।",
          slotValues: { ACTION: "go for a walk" },
          topicArea: "daily_life",
        },
        {
          en: "Let's eat out tonight.",
          bn: "চলো আজ রাতে বাইরে খাই।",
          slotValues: { ACTION: "eat out tonight" },
          topicArea: "food",
        },
        {
          en: "Let's start the meeting.",
          bn: "চলো মিটিং শুরু করি।",
          slotValues: { ACTION: "start the meeting" },
          topicArea: "work",
        },
        {
          en: "Let's take a break.",
          bn: "চলো একটু বিরতি নিই।",
          slotValues: { ACTION: "take a break" },
          topicArea: "work",
        },
        {
          en: "Let's study together.",
          bn: "চলো একসাথে পড়াশোনা করি।",
          slotValues: { ACTION: "study together" },
          topicArea: "education",
        },
        {
          en: "Let's visit the museum.",
          bn: "চলো জাদুঘর দেখতে যাই।",
          slotValues: { ACTION: "visit the museum" },
          topicArea: "travel",
        },
        {
          en: "Let's try that new restaurant.",
          bn: "চলো সেই নতুন রেস্তোরাঁটা ঘুরে দেখি।",
          slotValues: { ACTION: "try that new restaurant" },
          topicArea: "food",
        },
        {
          en: "Let's call Mom.",
          bn: "চলো মাকে ফোন করি।",
          slotValues: { ACTION: "call Mom" },
          topicArea: "relationships",
        },
        {
          en: "Let's go shopping this weekend.",
          bn: "চলো এই সপ্তাহান্তে কেনাকাটা করতে যাই।",
          slotValues: { ACTION: "go shopping this weekend" },
          topicArea: "shopping",
        },
        {
          en: "Let's exercise in the morning.",
          bn: "চলো সকালে ব্যায়াম করি।",
          slotValues: { ACTION: "exercise in the morning" },
          topicArea: "health",
        },
        {
          en: "Let's book the tickets early.",
          bn: "চলো আগেভাগে টিকিট বুক করি।",
          slotValues: { ACTION: "book the tickets early" },
          topicArea: "travel",
        },
        {
          en: "Let's finish this project today.",
          bn: "চলো আজকেই এই প্রজেক্টটা শেষ করি।",
          slotValues: { ACTION: "finish this project today" },
          topicArea: "work",
        },
        {
          en: "Let's watch a movie.",
          bn: "চলো একটা সিনেমা দেখি।",
          slotValues: { ACTION: "watch a movie" },
          topicArea: "daily_life",
        },
        {
          en: "Let's share the bill.",
          bn: "চলো বিল ভাগ করে দিই।",
          slotValues: { ACTION: "share the bill" },
          topicArea: "food",
        },
        {
          en: "Let's catch up over coffee.",
          bn: "চলো কফি খেতে খেতে কথা বলি।",
          slotValues: { ACTION: "catch up over coffee" },
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "The most common way to make an informal suggestion. It includes the speaker in the proposed action.",
      usageNote_bn:
        "অনানুষ্ঠানিক পরামর্শ দেওয়ার সবচেয়ে সাধারণ উপায়। এটি প্রস্তাবিত কাজে বক্তাকেও অন্তর্ভুক্ত করে।",
      combinableWith: ["F3.1"],
      responsePatterns: ["F3.1"],
      banglaStructureMap: "চলো (Let's) + [ACTION] (ক্রিয়া) + করি (Verb ending)",
    },
    {
      id: "F1.2",
      formula: "How about [DOING]?",
      formula_bn: "[করা] কেমন হয়?",
      patternName: "Suggestion with How About",
      patternName_bn: "How about দিয়ে পরামর্শ",
      slots: [
        {
          name: "DOING",
          description: "A gerund (verb+ing) or noun phrase",
          description_bn: "একটি gerund (verb+ing) বা বিশেষ্য পদবন্ধ",
          acceptedTypes: ["gerund", "noun"],
          examples: ["going to the park", "pizza", "a walk"],
        },
      ],
      examples: [
        {
          en: "How about going to the park?",
          bn: "পার্কে যাওয়া কেমন হয়?",
          slotValues: { DOING: "going to the park" },
          topicArea: "daily_life",
        },
        {
          en: "How about pizza for dinner?",
          bn: "রাতের খাবারে পিৎজা কেমন হয়?",
          slotValues: { DOING: "pizza for dinner" },
          topicArea: "food",
        },
        {
          en: "How about meeting at three o'clock?",
          bn: "তিনটায় দেখা করা কেমন হয়?",
          slotValues: { DOING: "meeting at three o'clock" },
          topicArea: "work",
        },
        {
          en: "How about taking the bus instead?",
          bn: "বরং বাসে যাওয়া কেমন হয়?",
          slotValues: { DOING: "taking the bus instead" },
          topicArea: "travel",
        },
        {
          en: "How about reading this chapter first?",
          bn: "আগে এই অধ্যায়টা পড়া কেমন হয়?",
          slotValues: { DOING: "reading this chapter first" },
          topicArea: "education",
        },
        {
          en: "How about trying yoga?",
          bn: "যোগব্যায়াম করে দেখা কেমন হয়?",
          slotValues: { DOING: "trying yoga" },
          topicArea: "health",
        },
        {
          en: "How about buying it online?",
          bn: "অনলাইনে কেনা কেমন হয়?",
          slotValues: { DOING: "buying it online" },
          topicArea: "shopping",
        },
        {
          en: "How about inviting your sister?",
          bn: "তোমার বোনকে আমন্ত্রণ জানানো কেমন হয়?",
          slotValues: { DOING: "inviting your sister" },
          topicArea: "relationships",
        },
        {
          en: "How about working from home tomorrow?",
          bn: "কাল বাসা থেকে কাজ করা কেমন হয়?",
          slotValues: { DOING: "working from home tomorrow" },
          topicArea: "work",
        },
        {
          en: "How about a cup of tea?",
          bn: "এক কাপ চা কেমন হয়?",
          slotValues: { DOING: "a cup of tea" },
          topicArea: "food",
        },
        {
          en: "How about visiting Grandma this weekend?",
          bn: "এই সপ্তাহান্তে দাদির বাড়ি যাওয়া কেমন হয়?",
          slotValues: { DOING: "visiting Grandma this weekend" },
          topicArea: "relationships",
        },
        {
          en: "How about swimming in the morning?",
          bn: "সকালে সাঁতার কাটা কেমন হয়?",
          slotValues: { DOING: "swimming in the morning" },
          topicArea: "health",
        },
        {
          en: "How about splitting the cost?",
          bn: "খরচ ভাগ করা কেমন হয়?",
          slotValues: { DOING: "splitting the cost" },
          topicArea: "shopping",
        },
        {
          en: "How about exploring the old town?",
          bn: "পুরোনো শহরটা ঘুরে দেখা কেমন হয়?",
          slotValues: { DOING: "exploring the old town" },
          topicArea: "travel",
        },
        {
          en: "How about joining an English class?",
          bn: "একটা ইংরেজি ক্লাসে ভর্তি হওয়া কেমন হয়?",
          slotValues: { DOING: "joining an English class" },
          topicArea: "education",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "A friendly, open-ended way to suggest something. Can be followed by a gerund or a noun.",
      usageNote_bn:
        "বন্ধুত্বপূর্ণ, খোলামেলা পরামর্শ দেওয়ার উপায়। এর পরে gerund বা বিশেষ্য আসতে পারে।",
      combinableWith: ["F1.1"],
      responsePatterns: ["F3.1"],
      banglaStructureMap: "[DOING] (করা/বিশেষ্য) + কেমন হয়? (Question)",
    },
    {
      id: "F1.3",
      formula: "Why don't we [ACTION]?",
      formula_bn: "আমরা কেন [কাজ] করি না?",
      patternName: "Suggestion with Why Don't We",
      patternName_bn: "Why don't we দিয়ে পরামর্শ",
      slots: [
        {
          name: "ACTION",
          description: "Base form of a verb or verb phrase",
          description_bn: "ক্রিয়ার মূল রূপ বা ক্রিয়া পদবন্ধ",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["take a taxi", "order online", "ask the teacher"],
        },
      ],
      examples: [
        {
          en: "Why don't we take a taxi?",
          bn: "আমরা কেন ট্যাক্সি নিই না?",
          slotValues: { ACTION: "take a taxi" },
          topicArea: "travel",
        },
        {
          en: "Why don't we order online?",
          bn: "আমরা কেন অনলাইনে অর্ডার করি না?",
          slotValues: { ACTION: "order online" },
          topicArea: "shopping",
        },
        {
          en: "Why don't we ask the teacher?",
          bn: "আমরা কেন শিক্ষককে জিজ্ঞেস করি না?",
          slotValues: { ACTION: "ask the teacher" },
          topicArea: "education",
        },
        {
          en: "Why don't we cook at home?",
          bn: "আমরা কেন বাসায় রান্না করি না?",
          slotValues: { ACTION: "cook at home" },
          topicArea: "food",
        },
        {
          en: "Why don't we go to bed early?",
          bn: "আমরা কেন তাড়াতাড়ি ঘুমাতে যাই না?",
          slotValues: { ACTION: "go to bed early" },
          topicArea: "health",
        },
        {
          en: "Why don't we reschedule the meeting?",
          bn: "আমরা কেন মিটিংটা পুনর্নির্ধারণ করি না?",
          slotValues: { ACTION: "reschedule the meeting" },
          topicArea: "work",
        },
        {
          en: "Why don't we invite them over?",
          bn: "আমরা কেন তাদের বাসায় ডাকি না?",
          slotValues: { ACTION: "invite them over" },
          topicArea: "relationships",
        },
        {
          en: "Why don't we walk instead of drive?",
          bn: "আমরা কেন গাড়ির বদলে হেঁটে যাই না?",
          slotValues: { ACTION: "walk instead of drive" },
          topicArea: "daily_life",
        },
        {
          en: "Why don't we compare prices first?",
          bn: "আমরা কেন আগে দাম তুলনা করি না?",
          slotValues: { ACTION: "compare prices first" },
          topicArea: "shopping",
        },
        {
          en: "Why don't we try a different approach?",
          bn: "আমরা কেন ভিন্ন পদ্ধতি চেষ্টা করি না?",
          slotValues: { ACTION: "try a different approach" },
          topicArea: "work",
        },
        {
          en: "Why don't we visit the beach?",
          bn: "আমরা কেন সমুদ্র সৈকতে যাই না?",
          slotValues: { ACTION: "visit the beach" },
          topicArea: "travel",
        },
        {
          en: "Why don't we practice speaking English?",
          bn: "আমরা কেন ইংরেজি বলার অনুশীলন করি না?",
          slotValues: { ACTION: "practice speaking English" },
          topicArea: "education",
        },
        {
          en: "Why don't we have lunch together?",
          bn: "আমরা কেন একসাথে দুপুরের খাবার খাই না?",
          slotValues: { ACTION: "have lunch together" },
          topicArea: "food",
        },
        {
          en: "Why don't we see a doctor about it?",
          bn: "আমরা কেন এটা নিয়ে ডাক্তার দেখাই না?",
          slotValues: { ACTION: "see a doctor about it" },
          topicArea: "health",
        },
        {
          en: "Why don't we plan a surprise party?",
          bn: "আমরা কেন একটা সারপ্রাইজ পার্টির পরিকল্পনা করি না?",
          slotValues: { ACTION: "plan a surprise party" },
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "Despite the negative form, this is a positive suggestion. It gently proposes an idea.",
      usageNote_bn:
        "নেতিবাচক রূপ সত্ত্বেও, এটি একটি ইতিবাচক পরামর্শ। এটি মৃদুভাবে একটি ধারণা প্রস্তাব করে।",
      combinableWith: ["F1.1"],
      responsePatterns: ["F3.1"],
      banglaStructureMap:
        "আমরা কেন (Subject + Why) + [ACTION] (ক্রিয়া) + করি না? (Neg. Question)",
    },
    {
      id: "F1.4",
      formula: "What if we [ACTION]?",
      formula_bn: "আমরা যদি [কাজ] করি তাহলে কেমন হয়?",
      patternName: "Tentative Suggestion",
      patternName_bn: "সতর্ক পরামর্শ",
      slots: [
        {
          name: "ACTION",
          description: "Base form of a verb or verb phrase (past tense also common)",
          description_bn: "ক্রিয়ার মূল রূপ বা ক্রিয়া পদবন্ধ (অতীত কাল ও সাধারণ)",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["leave early", "changed the plan", "tried something new"],
        },
      ],
      examples: [
        {
          en: "What if we leave early?",
          bn: "আমরা যদি তাড়াতাড়ি বের হই তাহলে কেমন হয়?",
          slotValues: { ACTION: "leave early" },
          topicArea: "daily_life",
        },
        {
          en: "What if we order takeout?",
          bn: "আমরা যদি টেকআউট অর্ডার করি তাহলে কেমন হয়?",
          slotValues: { ACTION: "order takeout" },
          topicArea: "food",
        },
        {
          en: "What if we postpone the trip?",
          bn: "আমরা যদি ভ্রমণটা পিছিয়ে দিই তাহলে কেমন হয়?",
          slotValues: { ACTION: "postpone the trip" },
          topicArea: "travel",
        },
        {
          en: "What if we hire an assistant?",
          bn: "আমরা যদি একজন সহকারী নিয়োগ করি তাহলে কেমন হয়?",
          slotValues: { ACTION: "hire an assistant" },
          topicArea: "work",
        },
        {
          en: "What if we study in the library?",
          bn: "আমরা যদি লাইব্রেরিতে পড়ি তাহলে কেমন হয়?",
          slotValues: { ACTION: "study in the library" },
          topicArea: "education",
        },
        {
          en: "What if we go jogging every morning?",
          bn: "আমরা যদি প্রতিদিন সকালে জগিং করি তাহলে কেমন হয়?",
          slotValues: { ACTION: "go jogging every morning" },
          topicArea: "health",
        },
        {
          en: "What if we buy it from the other store?",
          bn: "আমরা যদি অন্য দোকান থেকে কিনি তাহলে কেমন হয়?",
          slotValues: { ACTION: "buy it from the other store" },
          topicArea: "shopping",
        },
        {
          en: "What if we apologize first?",
          bn: "আমরা যদি আগে ক্ষমা চাই তাহলে কেমন হয়?",
          slotValues: { ACTION: "apologize first" },
          topicArea: "relationships",
        },
        {
          en: "What if we change the deadline?",
          bn: "আমরা যদি সময়সীমা পরিবর্তন করি তাহলে কেমন হয়?",
          slotValues: { ACTION: "change the deadline" },
          topicArea: "work",
        },
        {
          en: "What if we take the train instead?",
          bn: "আমরা যদি বরং ট্রেনে যাই তাহলে কেমন হয়?",
          slotValues: { ACTION: "take the train instead" },
          topicArea: "travel",
        },
        {
          en: "What if we make it a potluck?",
          bn: "আমরা যদি এটা পটলাক করি তাহলে কেমন হয়?",
          slotValues: { ACTION: "make it a potluck" },
          topicArea: "food",
        },
        {
          en: "What if we join a gym together?",
          bn: "আমরা যদি একসাথে জিমে ভর্তি হই তাহলে কেমন হয়?",
          slotValues: { ACTION: "join a gym together" },
          topicArea: "health",
        },
        {
          en: "What if we ask for a discount?",
          bn: "আমরা যদি ছাড় চাই তাহলে কেমন হয়?",
          slotValues: { ACTION: "ask for a discount" },
          topicArea: "shopping",
        },
        {
          en: "What if we talk to him about it?",
          bn: "আমরা যদি তার সাথে এটা নিয়ে কথা বলি তাহলে কেমন হয়?",
          slotValues: { ACTION: "talk to him about it" },
          topicArea: "relationships",
        },
        {
          en: "What if we review the notes together?",
          bn: "আমরা যদি একসাথে নোটগুলো রিভিউ করি তাহলে কেমন হয়?",
          slotValues: { ACTION: "review the notes together" },
          topicArea: "education",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "A softer, more tentative way to suggest something. It invites discussion rather than pushing an idea.",
      usageNote_bn:
        "কিছু পরামর্শ দেওয়ার একটি নরম, বেশি সতর্ক উপায়। এটি ধারণা চাপানোর বদলে আলোচনার আমন্ত্রণ জানায়।",
      combinableWith: ["F1.3"],
      responsePatterns: ["F3.1"],
      banglaStructureMap:
        "আমরা যদি (Subject + If) + [ACTION] (ক্রিয়া) + করি তাহলে কেমন হয়? (Conditional Question)",
    },
    {
      id: "F1.5",
      formula: "Shall we [ACTION]?",
      formula_bn: "আমরা কি [কাজ] করব?",
      patternName: "Polite Suggestion with Shall",
      patternName_bn: "Shall দিয়ে ভদ্র পরামর্শ",
      slots: [
        {
          name: "ACTION",
          description: "Base form of a verb or verb phrase",
          description_bn: "ক্রিয়ার মূল রূপ বা ক্রিয়া পদবন্ধ",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["begin", "move on", "go ahead"],
        },
      ],
      examples: [
        {
          en: "Shall we begin?",
          bn: "আমরা কি শুরু করব?",
          slotValues: { ACTION: "begin" },
          topicArea: "work",
        },
        {
          en: "Shall we order dessert?",
          bn: "আমরা কি ডেজার্ট অর্ডার করব?",
          slotValues: { ACTION: "order dessert" },
          topicArea: "food",
        },
        {
          en: "Shall we go inside?",
          bn: "আমরা কি ভেতরে যাব?",
          slotValues: { ACTION: "go inside" },
          topicArea: "daily_life",
        },
        {
          en: "Shall we take a taxi to the airport?",
          bn: "আমরা কি বিমানবন্দরে ট্যাক্সি নেব?",
          slotValues: { ACTION: "take a taxi to the airport" },
          topicArea: "travel",
        },
        {
          en: "Shall we review the homework?",
          bn: "আমরা কি হোমওয়ার্ক রিভিউ করব?",
          slotValues: { ACTION: "review the homework" },
          topicArea: "education",
        },
        {
          en: "Shall we take a short break?",
          bn: "আমরা কি একটু বিরতি নেব?",
          slotValues: { ACTION: "take a short break" },
          topicArea: "work",
        },
        {
          en: "Shall we go for a run?",
          bn: "আমরা কি দৌড়াতে যাব?",
          slotValues: { ACTION: "go for a run" },
          topicArea: "health",
        },
        {
          en: "Shall we invite the neighbors?",
          bn: "আমরা কি প্রতিবেশীদের ডাকব?",
          slotValues: { ACTION: "invite the neighbors" },
          topicArea: "relationships",
        },
        {
          en: "Shall we check the price?",
          bn: "আমরা কি দাম দেখব?",
          slotValues: { ACTION: "check the price" },
          topicArea: "shopping",
        },
        {
          en: "Shall we dance?",
          bn: "আমরা কি নাচব?",
          slotValues: { ACTION: "dance" },
          topicArea: "daily_life",
        },
        {
          en: "Shall we try the local food?",
          bn: "আমরা কি স্থানীয় খাবার চেষ্টা করব?",
          slotValues: { ACTION: "try the local food" },
          topicArea: "food",
        },
        {
          en: "Shall we book a hotel in advance?",
          bn: "আমরা কি আগেভাগে হোটেল বুক করব?",
          slotValues: { ACTION: "book a hotel in advance" },
          topicArea: "travel",
        },
        {
          en: "Shall we discuss this after class?",
          bn: "আমরা কি ক্লাসের পরে এটা আলোচনা করব?",
          slotValues: { ACTION: "discuss this after class" },
          topicArea: "education",
        },
        {
          en: "Shall we get matching outfits?",
          bn: "আমরা কি মিলিয়ে পোশাক কিনব?",
          slotValues: { ACTION: "get matching outfits" },
          topicArea: "shopping",
        },
        {
          en: "Shall we drink some water first?",
          bn: "আমরা কি আগে একটু পানি খাব?",
          slotValues: { ACTION: "drink some water first" },
          topicArea: "health",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "A more formal or polite way to make a suggestion. Common in British English. It always includes the other person.",
      usageNote_bn:
        "পরামর্শ দেওয়ার একটি বেশি আনুষ্ঠানিক বা ভদ্র উপায়। ব্রিটিশ ইংরেজিতে সাধারণ। এটি সবসময় অন্য ব্যক্তিকে অন্তর্ভুক্ত করে।",
      combinableWith: ["F1.1"],
      responsePatterns: ["F3.1"],
      banglaStructureMap:
        "আমরা কি (Subject + Question) + [ACTION] (ক্রিয়া) + করব? (Future Question)",
    },
    {
      id: "F1.6",
      formula: "Have you thought about [DOING]?",
      formula_bn: "তুমি কি [করার] কথা ভেবেছ?",
      patternName: "Indirect Suggestion",
      patternName_bn: "পরোক্ষ পরামর্শ",
      slots: [
        {
          name: "DOING",
          description: "A gerund (verb+ing) or noun phrase describing the suggestion",
          description_bn: "একটি gerund (verb+ing) বা বিশেষ্য পদবন্ধ যা পরামর্শ বর্ণনা করে",
          acceptedTypes: ["gerund", "noun"],
          examples: ["taking a break", "changing your approach", "seeing a doctor"],
        },
      ],
      examples: [
        {
          en: "Have you thought about taking a break?",
          bn: "তুমি কি একটু বিরতি নেওয়ার কথা ভেবেছ?",
          slotValues: { DOING: "taking a break" },
          topicArea: "daily_life",
        },
        {
          en: "Have you thought about trying a different recipe?",
          bn: "তুমি কি ভিন্ন রেসিপি চেষ্টা করার কথা ভেবেছ?",
          slotValues: { DOING: "trying a different recipe" },
          topicArea: "food",
        },
        {
          en: "Have you thought about visiting Japan?",
          bn: "তুমি কি জাপান ঘুরতে যাওয়ার কথা ভেবেছ?",
          slotValues: { DOING: "visiting Japan" },
          topicArea: "travel",
        },
        {
          en: "Have you thought about changing your major?",
          bn: "তুমি কি তোমার বিষয় বদলানোর কথা ভেবেছ?",
          slotValues: { DOING: "changing your major" },
          topicArea: "education",
        },
        {
          en: "Have you thought about freelancing?",
          bn: "তুমি কি ফ্রিল্যান্সিংয়ের কথা ভেবেছ?",
          slotValues: { DOING: "freelancing" },
          topicArea: "work",
        },
        {
          en: "Have you thought about seeing a specialist?",
          bn: "তুমি কি বিশেষজ্ঞ দেখানোর কথা ভেবেছ?",
          slotValues: { DOING: "seeing a specialist" },
          topicArea: "health",
        },
        {
          en: "Have you thought about buying it online?",
          bn: "তুমি কি অনলাইনে কেনার কথা ভেবেছ?",
          slotValues: { DOING: "buying it online" },
          topicArea: "shopping",
        },
        {
          en: "Have you thought about talking to her about it?",
          bn: "তুমি কি তার সাথে এটা নিয়ে কথা বলার কথা ভেবেছ?",
          slotValues: { DOING: "talking to her about it" },
          topicArea: "relationships",
        },
        {
          en: "Have you thought about joining a gym?",
          bn: "তুমি কি জিমে যোগ দেওয়ার কথা ভেবেছ?",
          slotValues: { DOING: "joining a gym" },
          topicArea: "health",
        },
        {
          en: "Have you thought about applying for that position?",
          bn: "তুমি কি সেই পদের জন্য আবেদন করার কথা ভেবেছ?",
          slotValues: { DOING: "applying for that position" },
          topicArea: "work",
        },
        {
          en: "Have you thought about learning to cook?",
          bn: "তুমি কি রান্না শেখার কথা ভেবেছ?",
          slotValues: { DOING: "learning to cook" },
          topicArea: "food",
        },
        {
          en: "Have you thought about studying abroad?",
          bn: "তুমি কি বিদেশে পড়ার কথা ভেবেছ?",
          slotValues: { DOING: "studying abroad" },
          topicArea: "education",
        },
        {
          en: "Have you thought about taking the train instead?",
          bn: "তুমি কি বরং ট্রেনে যাওয়ার কথা ভেবেছ?",
          slotValues: { DOING: "taking the train instead" },
          topicArea: "travel",
        },
        {
          en: "Have you thought about moving closer to your parents?",
          bn: "তুমি কি বাবা-মায়ের কাছে চলে যাওয়ার কথা ভেবেছ?",
          slotValues: { DOING: "moving closer to your parents" },
          topicArea: "relationships",
        },
        {
          en: "Have you thought about getting a second opinion?",
          bn: "তুমি কি দ্বিতীয় মতামত নেওয়ার কথা ভেবেছ?",
          slotValues: { DOING: "getting a second opinion" },
          topicArea: "daily_life",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "A very gentle and non-pushy way to make a suggestion. It respects the listener's autonomy by framing it as a question about their thoughts.",
      usageNote_bn:
        "পরামর্শ দেওয়ার একটি খুব মৃদু ও জোর না করার উপায়। এটি শ্রোতার চিন্তা সম্পর্কে প্রশ্ন হিসেবে উপস্থাপন করে তাদের স্বায়ত্তশাসনকে সম্মান করে।",
      combinableWith: ["F1.2"],
      responsePatterns: ["F3.1"],
      banglaStructureMap:
        "তুমি কি (Subject + Q) + [DOING] (করার) + কথা ভেবেছ? (Question about thought)",
    },
    {
      id: "F1.7",
      formula: "You might want to [ACTION]",
      formula_bn: "তুমি হয়তো [কাজ] করতে চাইবে",
      patternName: "Gentle Suggestion",
      patternName_bn: "মৃদু পরামর্শ",
      slots: [
        {
          name: "ACTION",
          description: "Base form of a verb or verb phrase",
          description_bn: "ক্রিয়ার মূল রূপ বা ক্রিয়া পদবন্ধ",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["check the weather", "bring an umbrella", "reconsider"],
        },
      ],
      examples: [
        {
          en: "You might want to check the weather before going out.",
          bn: "তুমি হয়তো বাইরে যাওয়ার আগে আবহাওয়া দেখতে চাইবে।",
          slotValues: { ACTION: "check the weather before going out" },
          topicArea: "daily_life",
        },
        {
          en: "You might want to try the biryani here. It's excellent.",
          bn: "তুমি হয়তো এখানকার বিরিয়ানি চেষ্টা করতে চাইবে। এটা চমৎকার।",
          slotValues: { ACTION: "try the biryani here" },
          topicArea: "food",
        },
        {
          en: "You might want to book your hotel early.",
          bn: "তুমি হয়তো আগেভাগে হোটেল বুক করতে চাইবে।",
          slotValues: { ACTION: "book your hotel early" },
          topicArea: "travel",
        },
        {
          en: "You might want to review the last chapter again.",
          bn: "তুমি হয়তো শেষ অধ্যায়টা আবার পড়তে চাইবে।",
          slotValues: { ACTION: "review the last chapter again" },
          topicArea: "education",
        },
        {
          en: "You might want to update your resume.",
          bn: "তুমি হয়তো তোমার জীবনবৃত্তান্ত আপডেট করতে চাইবে।",
          slotValues: { ACTION: "update your resume" },
          topicArea: "work",
        },
        {
          en: "You might want to see a doctor about that cough.",
          bn: "তুমি হয়তো সেই কাশি নিয়ে ডাক্তার দেখাতে চাইবে।",
          slotValues: { ACTION: "see a doctor about that cough" },
          topicArea: "health",
        },
        {
          en: "You might want to compare prices before buying.",
          bn: "তুমি হয়তো কেনার আগে দাম তুলনা করতে চাইবে।",
          slotValues: { ACTION: "compare prices before buying" },
          topicArea: "shopping",
        },
        {
          en: "You might want to apologize to her.",
          bn: "তুমি হয়তো তার কাছে ক্ষমা চাইতে চাইবে।",
          slotValues: { ACTION: "apologize to her" },
          topicArea: "relationships",
        },
        {
          en: "You might want to bring an umbrella today.",
          bn: "তুমি হয়তো আজ একটা ছাতা নিতে চাইবে।",
          slotValues: { ACTION: "bring an umbrella today" },
          topicArea: "daily_life",
        },
        {
          en: "You might want to avoid eating too much sugar.",
          bn: "তুমি হয়তো বেশি চিনি খাওয়া এড়াতে চাইবে।",
          slotValues: { ACTION: "avoid eating too much sugar" },
          topicArea: "health",
        },
        {
          en: "You might want to ask for a discount.",
          bn: "তুমি হয়তো ছাড় চাইতে চাইবে।",
          slotValues: { ACTION: "ask for a discount" },
          topicArea: "shopping",
        },
        {
          en: "You might want to leave a bit earlier for the airport.",
          bn: "তুমি হয়তো বিমানবন্দরের জন্য একটু আগে রওনা হতে চাইবে।",
          slotValues: { ACTION: "leave a bit earlier for the airport" },
          topicArea: "travel",
        },
        {
          en: "You might want to practice more before the test.",
          bn: "তুমি হয়তো পরীক্ষার আগে আরও অনুশীলন করতে চাইবে।",
          slotValues: { ACTION: "practice more before the test" },
          topicArea: "education",
        },
        {
          en: "You might want to speak to your manager about it.",
          bn: "তুমি হয়তো এটা নিয়ে তোমার ম্যানেজারের সাথে কথা বলতে চাইবে।",
          slotValues: { ACTION: "speak to your manager about it" },
          topicArea: "work",
        },
        {
          en: "You might want to call her before visiting.",
          bn: "তুমি হয়তো দেখা করার আগে তাকে ফোন করতে চাইবে।",
          slotValues: { ACTION: "call her before visiting" },
          topicArea: "relationships",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "'Might want to' is a soft, indirect way of giving advice. It sounds less commanding than 'should' or 'you need to'.",
      usageNote_bn:
        "'Might want to' উপদেশ দেওয়ার একটি নরম, পরোক্ষ উপায়। এটি 'should' বা 'you need to'-এর চেয়ে কম আদেশসূচক শোনায়।",
      combinableWith: ["F1.6"],
      responsePatterns: ["F3.1"],
      banglaStructureMap:
        "তুমি হয়তো (Subject + might) + [ACTION] (ক্রিয়া) + করতে চাইবে (want to + Verb ending)",
    },
  ],
};
