import { PatternCategory } from "@/types/pattern";

export const categoryF4: PatternCategory = {
  id: "F4",
  slug: "inviting-someone",
  name: "Inviting Someone",
  name_bn: "কাউকে আমন্ত্রণ জানানো",
  description:
    "Learn how to invite people to events and activities in English using common patterns.",
  description_bn:
    "সাধারণ প্যাটার্ন ব্যবহার করে ইংরেজিতে মানুষকে অনুষ্ঠান ও কার্যক্রমে আমন্ত্রণ জানাতে শিখুন।",
  icon: "📩",
  group: "F",
  groupName: "Suggestions, Offers & Invitations",
  groupName_bn: "পরামর্শ, প্রস্তাব এবং আমন্ত্রণ",
  difficulty: "intermediate",
  patterns: [
    {
      id: "F4.1",
      formula: "Would you like to [ACTION]?",
      formula_bn: "আপনি কি [কাজ] করতে চান?",
      patternName: "Polite Invitation",
      patternName_bn: "ভদ্র আমন্ত্রণ",
      slots: [
        {
          name: "ACTION",
          description: "Base form of a verb or verb phrase",
          description_bn: "ক্রিয়ার মূল রূপ বা ক্রিয়া পদবন্ধ",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["join us for dinner", "come to the party", "go for a walk"],
        },
      ],
      examples: [
        {
          en: "Would you like to join us for dinner?",
          bn: "আপনি কি আমাদের সাথে রাতের খাবারে যোগ দিতে চান?",
          slotValues: { ACTION: "join us for dinner" },
          topicArea: "food",
        },
        {
          en: "Would you like to come to the party?",
          bn: "আপনি কি পার্টিতে আসতে চান?",
          slotValues: { ACTION: "come to the party" },
          topicArea: "relationships",
        },
        {
          en: "Would you like to go for a walk?",
          bn: "আপনি কি হাঁটতে যেতে চান?",
          slotValues: { ACTION: "go for a walk" },
          topicArea: "daily_life",
        },
        {
          en: "Would you like to visit the museum with us?",
          bn: "আপনি কি আমাদের সাথে জাদুঘর দেখতে যেতে চান?",
          slotValues: { ACTION: "visit the museum with us" },
          topicArea: "travel",
        },
        {
          en: "Would you like to study together for the exam?",
          bn: "আপনি কি পরীক্ষার জন্য একসাথে পড়তে চান?",
          slotValues: { ACTION: "study together for the exam" },
          topicArea: "education",
        },
        {
          en: "Would you like to attend the workshop?",
          bn: "আপনি কি ওয়ার্কশপে যোগ দিতে চান?",
          slotValues: { ACTION: "attend the workshop" },
          topicArea: "work",
        },
        {
          en: "Would you like to try this yoga class?",
          bn: "আপনি কি এই যোগব্যায়াম ক্লাসটি চেষ্টা করতে চান?",
          slotValues: { ACTION: "try this yoga class" },
          topicArea: "health",
        },
        {
          en: "Would you like to go shopping with me?",
          bn: "আপনি কি আমার সাথে কেনাকাটা করতে যেতে চান?",
          slotValues: { ACTION: "go shopping with me" },
          topicArea: "shopping",
        },
        {
          en: "Would you like to grab a coffee?",
          bn: "আপনি কি একটু কফি খেতে চান?",
          slotValues: { ACTION: "grab a coffee" },
          topicArea: "food",
        },
        {
          en: "Would you like to meet my parents?",
          bn: "আপনি কি আমার বাবা-মায়ের সাথে দেখা করতে চান?",
          slotValues: { ACTION: "meet my parents" },
          topicArea: "relationships",
        },
        {
          en: "Would you like to see a movie tonight?",
          bn: "আপনি কি আজ রাতে সিনেমা দেখতে চান?",
          slotValues: { ACTION: "see a movie tonight" },
          topicArea: "daily_life",
        },
        {
          en: "Would you like to explore the old city?",
          bn: "আপনি কি পুরোনো শহরটা ঘুরে দেখতে চান?",
          slotValues: { ACTION: "explore the old city" },
          topicArea: "travel",
        },
        {
          en: "Would you like to join our book club?",
          bn: "আপনি কি আমাদের বই পড়ার ক্লাবে যোগ দিতে চান?",
          slotValues: { ACTION: "join our book club" },
          topicArea: "education",
        },
        {
          en: "Would you like to come to the gym with me?",
          bn: "আপনি কি আমার সাথে জিমে আসতে চান?",
          slotValues: { ACTION: "come to the gym with me" },
          topicArea: "health",
        },
        {
          en: "Would you like to join the team lunch?",
          bn: "আপনি কি টিমের দুপুরের খাবারে যোগ দিতে চান?",
          slotValues: { ACTION: "join the team lunch" },
          topicArea: "work",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "The most common and polite way to invite someone. It gives them freedom to accept or decline.",
      usageNote_bn:
        "কাউকে আমন্ত্রণ জানানোর সবচেয়ে সাধারণ ও ভদ্র উপায়। এটি তাদের গ্রহণ বা প্রত্যাখ্যানের স্বাধীনতা দেয়।",
      combinableWith: ["F5.1"],
      responsePatterns: ["F5.1"],
      banglaStructureMap:
        "আপনি কি (Subject + Question) + [ACTION] করতে (Infinitive) + চান? (Verb)",
    },
    {
      id: "F4.2",
      formula: "How about [DOING] together?",
      formula_bn: "একসাথে [করা] কেমন হয়?",
      patternName: "Casual Invitation",
      patternName_bn: "সাধারণ আমন্ত্রণ",
      slots: [
        {
          name: "DOING",
          description: "A gerund (verb+ing) or noun phrase",
          description_bn: "একটি gerund (verb+ing) বা বিশেষ্য পদবন্ধ",
          acceptedTypes: ["gerund", "noun"],
          examples: ["having lunch", "watching the game", "cooking"],
        },
      ],
      examples: [
        {
          en: "How about having lunch together?",
          bn: "একসাথে দুপুরের খাবার খাওয়া কেমন হয়?",
          slotValues: { DOING: "having lunch" },
          topicArea: "food",
        },
        {
          en: "How about watching the game together?",
          bn: "একসাথে খেলা দেখা কেমন হয়?",
          slotValues: { DOING: "watching the game" },
          topicArea: "daily_life",
        },
        {
          en: "How about traveling together this summer?",
          bn: "এই গ্রীষ্মে একসাথে ভ্রমণ করা কেমন হয়?",
          slotValues: { DOING: "traveling" },
          topicArea: "travel",
        },
        {
          en: "How about studying together at the library?",
          bn: "লাইব্রেরিতে একসাথে পড়া কেমন হয়?",
          slotValues: { DOING: "studying" },
          topicArea: "education",
        },
        {
          en: "How about working on the project together?",
          bn: "একসাথে প্রজেক্টে কাজ করা কেমন হয়?",
          slotValues: { DOING: "working on the project" },
          topicArea: "work",
        },
        {
          en: "How about going for a jog together?",
          bn: "একসাথে জগিং করতে যাওয়া কেমন হয়?",
          slotValues: { DOING: "going for a jog" },
          topicArea: "health",
        },
        {
          en: "How about going to the mall together?",
          bn: "একসাথে মলে যাওয়া কেমন হয়?",
          slotValues: { DOING: "going to the mall" },
          topicArea: "shopping",
        },
        {
          en: "How about cooking together this weekend?",
          bn: "এই সপ্তাহান্তে একসাথে রান্না করা কেমন হয়?",
          slotValues: { DOING: "cooking" },
          topicArea: "food",
        },
        {
          en: "How about celebrating together?",
          bn: "একসাথে উদযাপন করা কেমন হয়?",
          slotValues: { DOING: "celebrating" },
          topicArea: "relationships",
        },
        {
          en: "How about playing tennis together?",
          bn: "একসাথে টেনিস খেলা কেমন হয়?",
          slotValues: { DOING: "playing tennis" },
          topicArea: "health",
        },
        {
          en: "How about exploring the night market together?",
          bn: "একসাথে নাইট মার্কেট ঘুরে দেখা কেমন হয়?",
          slotValues: { DOING: "exploring the night market" },
          topicArea: "travel",
        },
        {
          en: "How about preparing for the presentation together?",
          bn: "একসাথে প্রেজেন্টেশনের প্রস্তুতি নেওয়া কেমন হয়?",
          slotValues: { DOING: "preparing for the presentation" },
          topicArea: "work",
        },
        {
          en: "How about doing the assignment together?",
          bn: "একসাথে অ্যাসাইনমেন্ট করা কেমন হয়?",
          slotValues: { DOING: "doing the assignment" },
          topicArea: "education",
        },
        {
          en: "How about taking a walk together after dinner?",
          bn: "রাতের খাবারের পর একসাথে হাঁটা কেমন হয়?",
          slotValues: { DOING: "taking a walk" },
          topicArea: "daily_life",
        },
        {
          en: "How about picking out gifts together?",
          bn: "একসাথে উপহার বাছাই করা কেমন হয়?",
          slotValues: { DOING: "picking out gifts" },
          topicArea: "shopping",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "A friendly, casual way to invite someone to do something with you. Less formal than 'Would you like to'.",
      usageNote_bn:
        "কাউকে কিছু করতে আমন্ত্রণ জানানোর বন্ধুত্বপূর্ণ, অনানুষ্ঠানিক উপায়। 'Would you like to'-এর চেয়ে কম আনুষ্ঠানিক।",
      combinableWith: ["F4.1"],
      responsePatterns: ["F5.1"],
      banglaStructureMap:
        "একসাথে (Together) + [DOING] (করা/বিশেষ্য) + কেমন হয়? (Question)",
    },
    {
      id: "F4.3",
      formula: "Are you free to [ACTION]?",
      formula_bn: "তুমি কি [কাজ] করতে ফ্রি আছো?",
      patternName: "Checking Availability",
      patternName_bn: "সময় আছে কিনা জানা",
      slots: [
        {
          name: "ACTION",
          description: "Base form of a verb or verb phrase",
          description_bn: "ক্রিয়ার মূল রূপ বা ক্রিয়া পদবন্ধ",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["come over", "hang out", "meet up"],
        },
      ],
      examples: [
        {
          en: "Are you free to come over tonight?",
          bn: "তুমি কি আজ রাতে আসতে ফ্রি আছো?",
          slotValues: { ACTION: "come over tonight" },
          topicArea: "relationships",
        },
        {
          en: "Are you free to hang out this afternoon?",
          bn: "তুমি কি আজ বিকেলে আড্ডা দিতে ফ্রি আছো?",
          slotValues: { ACTION: "hang out this afternoon" },
          topicArea: "daily_life",
        },
        {
          en: "Are you free to grab dinner?",
          bn: "তুমি কি রাতের খাবার খেতে ফ্রি আছো?",
          slotValues: { ACTION: "grab dinner" },
          topicArea: "food",
        },
        {
          en: "Are you free to go on a day trip?",
          bn: "তুমি কি একদিনের ভ্রমণে যেতে ফ্রি আছো?",
          slotValues: { ACTION: "go on a day trip" },
          topicArea: "travel",
        },
        {
          en: "Are you free to review this together?",
          bn: "তুমি কি একসাথে এটা রিভিউ করতে ফ্রি আছো?",
          slotValues: { ACTION: "review this together" },
          topicArea: "education",
        },
        {
          en: "Are you free to meet up after work?",
          bn: "তুমি কি কাজের পরে দেখা করতে ফ্রি আছো?",
          slotValues: { ACTION: "meet up after work" },
          topicArea: "work",
        },
        {
          en: "Are you free to go for a swim?",
          bn: "তুমি কি সাঁতার কাটতে যেতে ফ্রি আছো?",
          slotValues: { ACTION: "go for a swim" },
          topicArea: "health",
        },
        {
          en: "Are you free to check out the new store?",
          bn: "তুমি কি নতুন দোকানটা দেখতে ফ্রি আছো?",
          slotValues: { ACTION: "check out the new store" },
          topicArea: "shopping",
        },
        {
          en: "Are you free to join us for brunch?",
          bn: "তুমি কি আমাদের সাথে ব্রাঞ্চে যোগ দিতে ফ্রি আছো?",
          slotValues: { ACTION: "join us for brunch" },
          topicArea: "food",
        },
        {
          en: "Are you free to come to my birthday party?",
          bn: "তুমি কি আমার জন্মদিনের পার্টিতে আসতে ফ্রি আছো?",
          slotValues: { ACTION: "come to my birthday party" },
          topicArea: "relationships",
        },
        {
          en: "Are you free to play badminton?",
          bn: "তুমি কি ব্যাডমিন্টন খেলতে ফ্রি আছো?",
          slotValues: { ACTION: "play badminton" },
          topicArea: "health",
        },
        {
          en: "Are you free to visit the bookshop?",
          bn: "তুমি কি বইয়ের দোকানে যেতে ফ্রি আছো?",
          slotValues: { ACTION: "visit the bookshop" },
          topicArea: "education",
        },
        {
          en: "Are you free to go sightseeing tomorrow?",
          bn: "তুমি কি কাল দর্শনীয় স্থান ঘুরতে ফ্রি আছো?",
          slotValues: { ACTION: "go sightseeing tomorrow" },
          topicArea: "travel",
        },
        {
          en: "Are you free to discuss the project?",
          bn: "তুমি কি প্রজেক্ট নিয়ে আলোচনা করতে ফ্রি আছো?",
          slotValues: { ACTION: "discuss the project" },
          topicArea: "work",
        },
        {
          en: "Are you free to take a walk in the park?",
          bn: "তুমি কি পার্কে হাঁটতে যেতে ফ্রি আছো?",
          slotValues: { ACTION: "take a walk in the park" },
          topicArea: "daily_life",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "An indirect and considerate way to invite someone by first checking their availability.",
      usageNote_bn:
        "প্রথমে তাদের সময় আছে কিনা জেনে কাউকে আমন্ত্রণ জানানোর একটি পরোক্ষ ও বিবেচনাপূর্ণ উপায়।",
      combinableWith: ["F4.1"],
      responsePatterns: ["F5.1"],
      banglaStructureMap:
        "তুমি কি (Subject + Question) + [ACTION] করতে (Infinitive) + ফ্রি আছো? (Adj. + Verb)",
    },
    {
      id: "F4.4",
      formula: "Feel free to [ACTION]",
      formula_bn: "নির্দ্বিধায় [কাজ] করুন",
      patternName: "Open Invitation",
      patternName_bn: "খোলামেলা আমন্ত্রণ",
      slots: [
        {
          name: "ACTION",
          description: "Base form of a verb or verb phrase",
          description_bn: "ক্রিয়ার মূল রূপ বা ক্রিয়া পদবন্ধ",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["join us", "ask questions", "drop by anytime"],
        },
      ],
      examples: [
        {
          en: "Feel free to join us anytime.",
          bn: "নির্দ্বিধায় যেকোনো সময় আমাদের সাথে যোগ দিন।",
          slotValues: { ACTION: "join us anytime" },
          topicArea: "daily_life",
        },
        {
          en: "Feel free to help yourself to the food.",
          bn: "নির্দ্বিধায় খাবার নিয়ে নিন।",
          slotValues: { ACTION: "help yourself to the food" },
          topicArea: "food",
        },
        {
          en: "Feel free to visit us when you're in town.",
          bn: "নির্দ্বিধায় শহরে এলে আমাদের বাসায় আসুন।",
          slotValues: { ACTION: "visit us when you're in town" },
          topicArea: "travel",
        },
        {
          en: "Feel free to ask questions during the lecture.",
          bn: "নির্দ্বিধায় লেকচারের সময় প্রশ্ন করুন।",
          slotValues: { ACTION: "ask questions during the lecture" },
          topicArea: "education",
        },
        {
          en: "Feel free to use my office.",
          bn: "নির্দ্বিধায় আমার অফিস ব্যবহার করুন।",
          slotValues: { ACTION: "use my office" },
          topicArea: "work",
        },
        {
          en: "Feel free to take a break whenever you need.",
          bn: "নির্দ্বিধায় যখন দরকার বিরতি নিন।",
          slotValues: { ACTION: "take a break whenever you need" },
          topicArea: "health",
        },
        {
          en: "Feel free to try on anything you like.",
          bn: "নির্দ্বিধায় যা পছন্দ হয় পরে দেখুন।",
          slotValues: { ACTION: "try on anything you like" },
          topicArea: "shopping",
        },
        {
          en: "Feel free to bring your friends.",
          bn: "নির্দ্বিধায় তোমার বন্ধুদের নিয়ে আসো।",
          slotValues: { ACTION: "bring your friends" },
          topicArea: "relationships",
        },
        {
          en: "Feel free to drop by anytime.",
          bn: "নির্দ্বিধায় যেকোনো সময় চলে আসুন।",
          slotValues: { ACTION: "drop by anytime" },
          topicArea: "daily_life",
        },
        {
          en: "Feel free to taste the samples.",
          bn: "নির্দ্বিধায় নমুনা চেখে দেখুন।",
          slotValues: { ACTION: "taste the samples" },
          topicArea: "food",
        },
        {
          en: "Feel free to explore the area on your own.",
          bn: "নির্দ্বিধায় নিজে এলাকাটা ঘুরে দেখুন।",
          slotValues: { ACTION: "explore the area on your own" },
          topicArea: "travel",
        },
        {
          en: "Feel free to borrow any book from my shelf.",
          bn: "নির্দ্বিধায় আমার শেলফ থেকে যেকোনো বই ধার নিন।",
          slotValues: { ACTION: "borrow any book from my shelf" },
          topicArea: "education",
        },
        {
          en: "Feel free to reach out if you have concerns.",
          bn: "নির্দ্বিধায় কোনো উদ্বেগ থাকলে যোগাযোগ করুন।",
          slotValues: { ACTION: "reach out if you have concerns" },
          topicArea: "work",
        },
        {
          en: "Feel free to sit down and rest.",
          bn: "নির্দ্বিধায় বসুন এবং বিশ্রাম নিন।",
          slotValues: { ACTION: "sit down and rest" },
          topicArea: "health",
        },
        {
          en: "Feel free to call me whenever you want to talk.",
          bn: "নির্দ্বিধায় যখন কথা বলতে চান আমাকে ফোন করুন।",
          slotValues: { ACTION: "call me whenever you want to talk" },
          topicArea: "relationships",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "An open, no-pressure invitation. It tells the person they are welcome without obligating them.",
      usageNote_bn:
        "একটি খোলামেলা, চাপমুক্ত আমন্ত্রণ। এটি ব্যক্তিকে বলে যে তারা স্বাগত, কিন্তু বাধ্য করে না।",
      combinableWith: ["F4.1"],
      responsePatterns: ["F5.1"],
      banglaStructureMap:
        "নির্দ্বিধায় (Feel free) + [ACTION] (ক্রিয়া) + করুন (Verb ending)",
    },
    {
      id: "F4.5",
      formula: "You're welcome to [ACTION]",
      formula_bn: "আপনি [কাজ] করতে স্বাগত",
      patternName: "Warm Invitation",
      patternName_bn: "উষ্ণ আমন্ত্রণ",
      slots: [
        {
          name: "ACTION",
          description: "Base form of a verb or verb phrase",
          description_bn: "ক্রিয়ার মূল রূপ বা ক্রিয়া পদবন্ধ",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["stay with us", "use the kitchen", "come along"],
        },
      ],
      examples: [
        {
          en: "You're welcome to stay with us.",
          bn: "আপনি আমাদের সাথে থাকতে স্বাগত।",
          slotValues: { ACTION: "stay with us" },
          topicArea: "travel",
        },
        {
          en: "You're welcome to use the kitchen.",
          bn: "আপনি রান্নাঘর ব্যবহার করতে স্বাগত।",
          slotValues: { ACTION: "use the kitchen" },
          topicArea: "food",
        },
        {
          en: "You're welcome to come along.",
          bn: "আপনি সাথে আসতে স্বাগত।",
          slotValues: { ACTION: "come along" },
          topicArea: "daily_life",
        },
        {
          en: "You're welcome to attend the class.",
          bn: "আপনি ক্লাসে যোগ দিতে স্বাগত।",
          slotValues: { ACTION: "attend the class" },
          topicArea: "education",
        },
        {
          en: "You're welcome to use my desk while I'm away.",
          bn: "আমি না থাকলে আপনি আমার ডেস্ক ব্যবহার করতে স্বাগত।",
          slotValues: { ACTION: "use my desk while I'm away" },
          topicArea: "work",
        },
        {
          en: "You're welcome to join the morning walk.",
          bn: "আপনি সকালের হাঁটায় যোগ দিতে স্বাগত।",
          slotValues: { ACTION: "join the morning walk" },
          topicArea: "health",
        },
        {
          en: "You're welcome to try it on before buying.",
          bn: "আপনি কেনার আগে পরে দেখতে স্বাগত।",
          slotValues: { ACTION: "try it on before buying" },
          topicArea: "shopping",
        },
        {
          en: "You're welcome to bring your family.",
          bn: "আপনি আপনার পরিবার নিয়ে আসতে স্বাগত।",
          slotValues: { ACTION: "bring your family" },
          topicArea: "relationships",
        },
        {
          en: "You're welcome to borrow my car.",
          bn: "আপনি আমার গাড়ি ধার নিতে স্বাগত।",
          slotValues: { ACTION: "borrow my car" },
          topicArea: "daily_life",
        },
        {
          en: "You're welcome to have some cake.",
          bn: "আপনি কিছু কেক খেতে স্বাগত।",
          slotValues: { ACTION: "have some cake" },
          topicArea: "food",
        },
        {
          en: "You're welcome to stay as long as you want.",
          bn: "আপনি যতক্ষণ ইচ্ছা থাকতে স্বাগত।",
          slotValues: { ACTION: "stay as long as you want" },
          topicArea: "travel",
        },
        {
          en: "You're welcome to use the library anytime.",
          bn: "আপনি যেকোনো সময় লাইব্রেরি ব্যবহার করতে স্বাগত।",
          slotValues: { ACTION: "use the library anytime" },
          topicArea: "education",
        },
        {
          en: "You're welcome to share your ideas in the meeting.",
          bn: "আপনি মিটিংয়ে আপনার ধারণা শেয়ার করতে স্বাগত।",
          slotValues: { ACTION: "share your ideas in the meeting" },
          topicArea: "work",
        },
        {
          en: "You're welcome to use the swimming pool.",
          bn: "আপনি সুইমিং পুল ব্যবহার করতে স্বাগত।",
          slotValues: { ACTION: "use the swimming pool" },
          topicArea: "health",
        },
        {
          en: "You're welcome to return it if it doesn't fit.",
          bn: "আপনি না মানালে ফেরত দিতে স্বাগত।",
          slotValues: { ACTION: "return it if it doesn't fit" },
          topicArea: "shopping",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "A warm and hospitable way to invite someone. It makes them feel included and comfortable.",
      usageNote_bn:
        "কাউকে আমন্ত্রণ জানানোর একটি উষ্ণ ও আতিথেয় উপায়। এটি তাদের অন্তর্ভুক্ত ও স্বচ্ছন্দ বোধ করায়।",
      combinableWith: ["F4.4"],
      responsePatterns: ["F5.1"],
      banglaStructureMap:
        "আপনি (Subject) + [ACTION] করতে (Infinitive) + স্বাগত (Welcome)",
    },
  ],
};
