import { PatternCategory } from "@/types/pattern";

export const categoryG10: PatternCategory = {
  id: "G10",
  slug: "asking-for-explanations",
  name: "Asking for Explanations",
  name_bn: "ব্যাখ্যা চাওয়া",
  description:
    "Learn to ask for explanations and clarification about meanings, reasons, and processes.",
  description_bn:
    "অর্থ, কারণ এবং প্রক্রিয়া সম্পর্কে ব্যাখ্যা ও স্পষ্টীকরণ চাইতে শিখুন।",
  icon: "📖",
  group: "G",
  groupName: "All Question Types",
  groupName_bn: "সকল প্রশ্নের ধরন",
  difficulty: "intermediate",
  patterns: [
    {
      id: "G10.1",
      formula: "What do you mean by [THING]?",
      formula_bn: "[জিনিস] বলতে তুমি কী বোঝো?",
      patternName: "Asking for Meaning",
      patternName_bn: "অর্থ জিজ্ঞাসা",
      slots: [
        {
          name: "THING",
          description: "A word, phrase, or concept that needs clarification",
          description_bn: "একটি শব্দ, বাক্যাংশ, বা ধারণা যা স্পষ্টীকরণ দরকার",
          acceptedTypes: ["noun", "noun_phrase", "clause"],
          examples: ["that", "deadline", "flexible hours"],
        },
      ],
      examples: [
        { en: "What do you mean by that?", bn: "ওটা বলতে তুমি কী বোঝো?", slotValues: { THING: "that" }, topicArea: "daily_life" },
        { en: "What do you mean by 'deadline'?", bn: "'ডেডলাইন' বলতে তুমি কী বোঝো?", slotValues: { THING: "'deadline'" }, topicArea: "work" },
        { en: "What do you mean by 'flexible hours'?", bn: "'ফ্লেক্সিবল আওয়ারস' বলতে তুমি কী বোঝো?", slotValues: { THING: "'flexible hours'" }, topicArea: "work" },
        { en: "What do you mean by 'al dente'?", bn: "'আল দেন্তে' বলতে তুমি কী বোঝো?", slotValues: { THING: "'al dente'" }, topicArea: "food" },
        { en: "What do you mean by 'layover'?", bn: "'লেওভার' বলতে তুমি কী বোঝো?", slotValues: { THING: "'layover'" }, topicArea: "travel" },
        { en: "What do you mean by 'thesis statement'?", bn: "'থিসিস স্টেটমেন্ট' বলতে তুমি কী বোঝো?", slotValues: { THING: "'thesis statement'" }, topicArea: "education" },
        { en: "What do you mean by 'chronic'?", bn: "'ক্রনিক' বলতে তুমি কী বোঝো?", slotValues: { THING: "'chronic'" }, topicArea: "health" },
        { en: "What do you mean by 'give me space'?", bn: "'আমাকে স্পেস দাও' বলতে তুমি কী বোঝো?", slotValues: { THING: "'give me space'" }, topicArea: "relationships" },
        { en: "What do you mean by 'organic'?", bn: "'অর্গানিক' বলতে তুমি কী বোঝো?", slotValues: { THING: "'organic'" }, topicArea: "shopping" },
        { en: "What do you mean by 'it's complicated'?", bn: "'এটা জটিল' বলতে তুমি কী বোঝো?", slotValues: { THING: "'it's complicated'" }, topicArea: "daily_life" },
        { en: "What do you mean by 'gluten-free'?", bn: "'গ্লুটেন-ফ্রি' বলতে তুমি কী বোঝো?", slotValues: { THING: "'gluten-free'" }, topicArea: "food" },
        { en: "What do you mean by 'off the beaten path'?", bn: "'অফ দ্য বিটেন পাথ' বলতে তুমি কী বোঝো?", slotValues: { THING: "'off the beaten path'" }, topicArea: "travel" },
        { en: "What do you mean by 'peer review'?", bn: "'পিয়ার রিভিউ' বলতে তুমি কী বোঝো?", slotValues: { THING: "'peer review'" }, topicArea: "education" },
        { en: "What do you mean by 'side effects'?", bn: "'পার্শ্বপ্রতিক্রিয়া' বলতে তুমি কী বোঝো?", slotValues: { THING: "'side effects'" }, topicArea: "health" },
        { en: "What do you mean by 'KPI'?", bn: "'কেপিআই' বলতে তুমি কী বোঝো?", slotValues: { THING: "'KPI'" }, topicArea: "work" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "A direct way to ask for clarification of a word, phrase, or statement someone used.",
      usageNote_bn: "কেউ ব্যবহার করেছে এমন শব্দ, বাক্যাংশ বা বিবৃতির স্পষ্টীকরণ চাওয়ার সরাসরি উপায়।",
    },
    {
      id: "G10.2",
      formula: "Can you explain [THING]?",
      formula_bn: "তুমি কি [জিনিস] ব্যাখ্যা করতে পারো?",
      patternName: "Request for Explanation",
      patternName_bn: "ব্যাখ্যার অনুরোধ",
      slots: [
        {
          name: "THING",
          description: "A concept, process, or situation that needs explanation",
          description_bn: "একটি ধারণা, প্রক্রিয়া, বা পরিস্থিতি যার ব্যাখ্যা দরকার",
          acceptedTypes: ["noun", "noun_phrase", "clause"],
          examples: ["this to me", "how it works", "the rules"],
        },
      ],
      examples: [
        { en: "Can you explain this to me?", bn: "তুমি কি আমাকে এটা ব্যাখ্যা করতে পারো?", slotValues: { THING: "this to me" }, topicArea: "daily_life" },
        { en: "Can you explain how it works?", bn: "তুমি কি ব্যাখ্যা করতে পারো এটা কিভাবে কাজ করে?", slotValues: { THING: "how it works" }, topicArea: "daily_life" },
        { en: "Can you explain the rules?", bn: "তুমি কি নিয়মগুলো ব্যাখ্যা করতে পারো?", slotValues: { THING: "the rules" }, topicArea: "education" },
        { en: "Can you explain the recipe step by step?", bn: "তুমি কি ধাপে ধাপে রেসিপিটা ব্যাখ্যা করতে পারো?", slotValues: { THING: "the recipe step by step" }, topicArea: "food" },
        { en: "Can you explain the route to me?", bn: "তুমি কি আমাকে রাস্তাটা ব্যাখ্যা করতে পারো?", slotValues: { THING: "the route to me" }, topicArea: "travel" },
        { en: "Can you explain the new policy?", bn: "তুমি কি নতুন নীতিটা ব্যাখ্যা করতে পারো?", slotValues: { THING: "the new policy" }, topicArea: "work" },
        { en: "Can you explain the dosage instructions?", bn: "তুমি কি ওষুধের মাত্রার নির্দেশনা ব্যাখ্যা করতে পারো?", slotValues: { THING: "the dosage instructions" }, topicArea: "health" },
        { en: "Can you explain the return policy?", bn: "তুমি কি রিটার্ন পলিসি ব্যাখ্যা করতে পারো?", slotValues: { THING: "the return policy" }, topicArea: "shopping" },
        { en: "Can you explain why you are upset?", bn: "তুমি কি ব্যাখ্যা করতে পারো কেন মন খারাপ?", slotValues: { THING: "why you are upset" }, topicArea: "relationships" },
        { en: "Can you explain the difference between these two?", bn: "তুমি কি এই দুটোর মধ্যে পার্থক্য ব্যাখ্যা করতে পারো?", slotValues: { THING: "the difference between these two" }, topicArea: "education" },
        { en: "Can you explain the bill to me?", bn: "তুমি কি আমাকে বিলটা ব্যাখ্যা করতে পারো?", slotValues: { THING: "the bill to me" }, topicArea: "food" },
        { en: "Can you explain the itinerary?", bn: "তুমি কি ভ্রমণসূচী ব্যাখ্যা করতে পারো?", slotValues: { THING: "the itinerary" }, topicArea: "travel" },
        { en: "Can you explain the project requirements?", bn: "তুমি কি প্রজেক্টের প্রয়োজনীয়তা ব্যাখ্যা করতে পারো?", slotValues: { THING: "the project requirements" }, topicArea: "work" },
        { en: "Can you explain the test results?", bn: "তুমি কি পরীক্ষার ফলাফল ব্যাখ্যা করতে পারো?", slotValues: { THING: "the test results" }, topicArea: "health" },
        { en: "Can you explain the warranty terms?", bn: "তুমি কি ওয়ারেন্টির শর্তাবলী ব্যাখ্যা করতে পারো?", slotValues: { THING: "the warranty terms" }, topicArea: "shopping" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "'Can you explain' is a casual request for explanation. Use 'could you explain' for more politeness.",
      usageNote_bn: "'Can you explain' ব্যাখ্যার জন্য একটি সাধারণ অনুরোধ। আরো ভদ্রতার জন্য 'could you explain' ব্যবহার করুন।",
    },
    {
      id: "G10.3",
      formula: "Why is it that [CLAUSE]?",
      formula_bn: "কেন [উপবাক্য]?",
      patternName: "Emphatic Why Question",
      patternName_bn: "জোরালো কেন প্রশ্ন",
      slots: [
        {
          name: "CLAUSE",
          description: "A statement or situation you want explained",
          description_bn: "একটি বিবৃতি বা পরিস্থিতি যার ব্যাখ্যা চান",
          acceptedTypes: ["clause"],
          examples: ["prices keep going up", "the train is always late", "we have to wait so long"],
        },
      ],
      examples: [
        { en: "Why is it that prices keep going up?", bn: "কেন দাম বাড়তেই থাকে?", slotValues: { CLAUSE: "prices keep going up" }, topicArea: "shopping" },
        { en: "Why is it that the train is always late?", bn: "কেন ট্রেন সবসময় দেরি হয়?", slotValues: { CLAUSE: "the train is always late" }, topicArea: "travel" },
        { en: "Why is it that we have to wait so long?", bn: "কেন আমাদের এত দীর্ঘ সময় অপেক্ষা করতে হয়?", slotValues: { CLAUSE: "we have to wait so long" }, topicArea: "daily_life" },
        { en: "Why is it that this dish tastes different every time?", bn: "কেন এই খাবারটা প্রতিবার ভিন্ন স্বাদের হয়?", slotValues: { CLAUSE: "this dish tastes different every time" }, topicArea: "food" },
        { en: "Why is it that some people learn languages faster?", bn: "কেন কিছু মানুষ ভাষা দ্রুত শেখে?", slotValues: { CLAUSE: "some people learn languages faster" }, topicArea: "education" },
        { en: "Why is it that the office is always so cold?", bn: "কেন অফিস সবসময় এত ঠান্ডা?", slotValues: { CLAUSE: "the office is always so cold" }, topicArea: "work" },
        { en: "Why is it that I always feel tired?", bn: "কেন আমি সবসময় ক্লান্ত বোধ করি?", slotValues: { CLAUSE: "I always feel tired" }, topicArea: "health" },
        { en: "Why is it that he never calls first?", bn: "কেন সে কখনো প্রথমে ফোন করে না?", slotValues: { CLAUSE: "he never calls first" }, topicArea: "relationships" },
        { en: "Why is it that traffic is so bad here?", bn: "কেন এখানে ট্রাফিক এত খারাপ?", slotValues: { CLAUSE: "traffic is so bad here" }, topicArea: "travel" },
        { en: "Why is it that the internet is so slow today?", bn: "কেন আজ ইন্টারনেট এত ধীর?", slotValues: { CLAUSE: "the internet is so slow today" }, topicArea: "daily_life" },
        { en: "Why is it that organic food costs more?", bn: "কেন অর্গানিক খাবারের দাম বেশি?", slotValues: { CLAUSE: "organic food costs more" }, topicArea: "food" },
        { en: "Why is it that the exam is so difficult?", bn: "কেন পরীক্ষা এত কঠিন?", slotValues: { CLAUSE: "the exam is so difficult" }, topicArea: "education" },
        { en: "Why is it that meetings take so long?", bn: "কেন মিটিং এত দীর্ঘ হয়?", slotValues: { CLAUSE: "meetings take so long" }, topicArea: "work" },
        { en: "Why is it that I gain weight so easily?", bn: "কেন আমার ওজন এত সহজে বাড়ে?", slotValues: { CLAUSE: "I gain weight so easily" }, topicArea: "health" },
        { en: "Why is it that brand-name products are so expensive?", bn: "কেন ব্র্যান্ডের পণ্য এত দামি?", slotValues: { CLAUSE: "brand-name products are so expensive" }, topicArea: "shopping" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "'Why is it that' adds emphasis to a why question. It implies curiosity or frustration about a pattern.",
      usageNote_bn: "'Why is it that' একটি কেন প্রশ্নে জোর যোগ করে। এটি কোনো প্যাটার্ন সম্পর্কে কৌতূহল বা হতাশা বোঝায়।",
    },
    {
      id: "G10.4",
      formula: "What's the reason for [THING]?",
      formula_bn: "[জিনিসের] কারণ কী?",
      patternName: "Reason Inquiry",
      patternName_bn: "কারণ অনুসন্ধান",
      slots: [
        {
          name: "THING",
          description: "A noun or gerund phrase about something you want the reason for",
          description_bn: "যার কারণ জানতে চান সেই বিশেষ্য বা ক্রিয়াবাচক বিশেষ্য পদবন্ধ",
          acceptedTypes: ["noun", "noun_phrase", "gerund"],
          examples: ["the delay", "the change", "closing early"],
        },
      ],
      examples: [
        { en: "What's the reason for the delay?", bn: "বিলম্বের কারণ কী?", slotValues: { THING: "the delay" }, topicArea: "travel" },
        { en: "What's the reason for the change?", bn: "পরিবর্তনের কারণ কী?", slotValues: { THING: "the change" }, topicArea: "work" },
        { en: "What's the reason for closing early?", bn: "তাড়াতাড়ি বন্ধ করার কারণ কী?", slotValues: { THING: "closing early" }, topicArea: "shopping" },
        { en: "What's the reason for the extra charge?", bn: "অতিরিক্ত চার্জের কারণ কী?", slotValues: { THING: "the extra charge" }, topicArea: "shopping" },
        { en: "What's the reason for the cancellation?", bn: "বাতিলের কারণ কী?", slotValues: { THING: "the cancellation" }, topicArea: "travel" },
        { en: "What's the reason for serving this cold?", bn: "ঠান্ডা পরিবেশন করার কারণ কী?", slotValues: { THING: "serving this cold" }, topicArea: "food" },
        { en: "What's the reason for the low grade?", bn: "কম নম্বরের কারণ কী?", slotValues: { THING: "the low grade" }, topicArea: "education" },
        { en: "What's the reason for the meeting?", bn: "মিটিংয়ের কারণ কী?", slotValues: { THING: "the meeting" }, topicArea: "work" },
        { en: "What's the reason for this headache?", bn: "এই মাথাব্যথার কারণ কী?", slotValues: { THING: "this headache" }, topicArea: "health" },
        { en: "What's the reason for your silence?", bn: "তোমার চুপ থাকার কারণ কী?", slotValues: { THING: "your silence" }, topicArea: "relationships" },
        { en: "What's the reason for the noise?", bn: "এই শব্দের কারণ কী?", slotValues: { THING: "the noise" }, topicArea: "daily_life" },
        { en: "What's the reason for adding spice?", bn: "মশলা যোগ করার কারণ কী?", slotValues: { THING: "adding spice" }, topicArea: "food" },
        { en: "What's the reason for the homework?", bn: "হোমওয়ার্কের কারণ কী?", slotValues: { THING: "the homework" }, topicArea: "education" },
        { en: "What's the reason for the weight gain?", bn: "ওজন বৃদ্ধির কারণ কী?", slotValues: { THING: "the weight gain" }, topicArea: "health" },
        { en: "What's the reason for the new route?", bn: "নতুন রুটের কারণ কী?", slotValues: { THING: "the new route" }, topicArea: "travel" },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote: "'What's the reason for' is a neutral and polite way to ask why something happened or is happening.",
      usageNote_bn: "'What's the reason for' কোনো কিছু কেন ঘটেছে বা ঘটছে তা জিজ্ঞাসা করার নিরপেক্ষ ও ভদ্র উপায়।",
    },
    {
      id: "G10.5",
      formula: "Could you clarify what you mean by [THING]?",
      formula_bn: "তুমি কি স্পষ্ট করতে পারো [জিনিস] বলতে তুমি কী বোঝো?",
      patternName: "Polite Clarification Request",
      patternName_bn: "ভদ্র স্পষ্টীকরণ অনুরোধ",
      slots: [
        {
          name: "THING",
          description: "A word, phrase, or concept that is unclear",
          description_bn: "একটি শব্দ, বাক্যাংশ, বা ধারণা যা অস্পষ্ট",
          acceptedTypes: ["noun", "noun_phrase", "clause"],
          examples: ["'asap'", "'it depends'", "the third option"],
        },
      ],
      examples: [
        { en: "Could you clarify what you mean by 'asap'?", bn: "তুমি কি স্পষ্ট করতে পারো 'asap' বলতে কী বোঝো?", slotValues: { THING: "'asap'" }, topicArea: "work" },
        { en: "Could you clarify what you mean by 'it depends'?", bn: "তুমি কি স্পষ্ট করতে পারো 'এটা নির্ভর করে' বলতে কী বোঝো?", slotValues: { THING: "'it depends'" }, topicArea: "daily_life" },
        { en: "Could you clarify what you mean by the third option?", bn: "তুমি কি স্পষ্ট করতে পারো তৃতীয় বিকল্প বলতে কী বোঝো?", slotValues: { THING: "the third option" }, topicArea: "work" },
        { en: "Could you clarify what you mean by 'seasonal menu'?", bn: "তুমি কি স্পষ্ট করতে পারো 'সিজনাল মেনু' বলতে কী বোঝো?", slotValues: { THING: "'seasonal menu'" }, topicArea: "food" },
        { en: "Could you clarify what you mean by 'budget-friendly'?", bn: "তুমি কি স্পষ্ট করতে পারো 'বাজেট-ফ্রেন্ডলি' বলতে কী বোঝো?", slotValues: { THING: "'budget-friendly'" }, topicArea: "travel" },
        { en: "Could you clarify what you mean by 'advanced level'?", bn: "তুমি কি স্পষ্ট করতে পারো 'অ্যাডভান্সড লেভেল' বলতে কী বোঝো?", slotValues: { THING: "'advanced level'" }, topicArea: "education" },
        { en: "Could you clarify what you mean by 'take as needed'?", bn: "তুমি কি স্পষ্ট করতে পারো 'প্রয়োজন অনুযায়ী খান' বলতে কী বোঝো?", slotValues: { THING: "'take as needed'" }, topicArea: "health" },
        { en: "Could you clarify what you mean by 'final sale'?", bn: "তুমি কি স্পষ্ট করতে পারো 'ফাইনাল সেল' বলতে কী বোঝো?", slotValues: { THING: "'final sale'" }, topicArea: "shopping" },
        { en: "Could you clarify what you mean by 'let's take a break'?", bn: "তুমি কি স্পষ্ট করতে পারো 'চলো বিরতি নিই' বলতে কী বোঝো?", slotValues: { THING: "'let's take a break'" }, topicArea: "relationships" },
        { en: "Could you clarify what you mean by 'tentative schedule'?", bn: "তুমি কি স্পষ্ট করতে পারো 'অস্থায়ী সময়সূচী' বলতে কী বোঝো?", slotValues: { THING: "'tentative schedule'" }, topicArea: "work" },
        { en: "Could you clarify what you mean by 'well-done'?", bn: "তুমি কি স্পষ্ট করতে পারো 'ওয়েল-ডান' বলতে কী বোঝো?", slotValues: { THING: "'well-done'" }, topicArea: "food" },
        { en: "Could you clarify what you mean by 'direct flight'?", bn: "তুমি কি স্পষ্ট করতে পারো 'ডাইরেক্ট ফ্লাইট' বলতে কী বোঝো?", slotValues: { THING: "'direct flight'" }, topicArea: "travel" },
        { en: "Could you clarify what you mean by 'prerequisite'?", bn: "তুমি কি স্পষ্ট করতে পারো 'পূর্বশর্ত' বলতে কী বোঝো?", slotValues: { THING: "'prerequisite'" }, topicArea: "education" },
        { en: "Could you clarify what you mean by 'mild symptoms'?", bn: "তুমি কি স্পষ্ট করতে পারো 'হালকা লক্ষণ' বলতে কী বোঝো?", slotValues: { THING: "'mild symptoms'" }, topicArea: "health" },
        { en: "Could you clarify what you mean by 'no strings attached'?", bn: "তুমি কি স্পষ্ট করতে পারো 'কোনো শর্ত নেই' বলতে কী বোঝো?", slotValues: { THING: "'no strings attached'" }, topicArea: "daily_life" },
      ],
      formality: "formal",
      difficulty: "intermediate",
      usageNote: "'Could you clarify' is a formal and polite way to ask for explanation. Commonly used in professional settings.",
      usageNote_bn: "'Could you clarify' ব্যাখ্যা চাওয়ার একটি আনুষ্ঠানিক ও ভদ্র উপায়। পেশাদার পরিবেশে সাধারণত ব্যবহৃত।",
    },
  ],
};
