import { PatternCategory } from "@/types/pattern";

export const categoryG13: PatternCategory = {
  id: "G13",
  slug: "rhetorical-questions",
  name: "Rhetorical Questions",
  name_bn: "অলংকারিক প্রশ্ন",
  description: "Learn to use rhetorical questions that don't expect an answer but make a point.",
  description_bn: "অলংকারিক প্রশ্ন ব্যবহার করতে শিখুন যা উত্তর আশা করে না কিন্তু একটি বক্তব্য রাখে।",
  icon: "🎭",
  group: "G",
  groupName: "All Question Types",
  groupName_bn: "সকল প্রশ্নের ধরন",
  difficulty: "advanced",
  patterns: [
    {
      id: "G13.1",
      formula: "Who doesn't love [THING]?",
      formula_bn: "কে [জিনিস] পছন্দ করে না?",
      patternName: "Universal Agreement Rhetorical",
      patternName_bn: "সর্বজনীন সম্মতি অলংকারিক",
      slots: [{ name: "THING", description: "Something universally liked", description_bn: "সর্বজনীনভাবে পছন্দের কিছু", acceptedTypes: ["noun", "noun_phrase", "gerund"], examples: ["a good meal", "sunny days", "free stuff"] }],
      examples: [
        { en: "Who doesn't love a good meal?", bn: "কে ভালো খাবার পছন্দ করে না?", slotValues: { THING: "a good meal" }, topicArea: "food" },
        { en: "Who doesn't love sunny days?", bn: "কে রোদেলা দিন পছন্দ করে না?", slotValues: { THING: "sunny days" }, topicArea: "daily_life" },
        { en: "Who doesn't love free stuff?", bn: "কে ফ্রি জিনিস পছন্দ করে না?", slotValues: { THING: "free stuff" }, topicArea: "shopping" },
        { en: "Who doesn't love a vacation?", bn: "কে ছুটি পছন্দ করে না?", slotValues: { THING: "a vacation" }, topicArea: "travel" },
        { en: "Who doesn't love learning new things?", bn: "কে নতুন জিনিস শেখা পছন্দ করে না?", slotValues: { THING: "learning new things" }, topicArea: "education" },
        { en: "Who doesn't love a long weekend?", bn: "কে দীর্ঘ সাপ্তাহিক ছুটি পছন্দ করে না?", slotValues: { THING: "a long weekend" }, topicArea: "work" },
        { en: "Who doesn't love a good night's sleep?", bn: "কে ভালো রাতের ঘুম পছন্দ করে না?", slotValues: { THING: "a good night's sleep" }, topicArea: "health" },
        { en: "Who doesn't love spending time with family?", bn: "কে পরিবারের সাথে সময় কাটানো পছন্দ করে না?", slotValues: { THING: "spending time with family" }, topicArea: "relationships" },
        { en: "Who doesn't love chocolate cake?", bn: "কে চকলেট কেক পছন্দ করে না?", slotValues: { THING: "chocolate cake" }, topicArea: "food" },
        { en: "Who doesn't love a surprise party?", bn: "কে সারপ্রাইজ পার্টি পছন্দ করে না?", slotValues: { THING: "a surprise party" }, topicArea: "daily_life" },
        { en: "Who doesn't love a great deal?", bn: "কে দারুণ ডিল পছন্দ করে না?", slotValues: { THING: "a great deal" }, topicArea: "shopping" },
        { en: "Who doesn't love exploring new places?", bn: "কে নতুন জায়গা ঘুরে দেখা পছন্দ করে না?", slotValues: { THING: "exploring new places" }, topicArea: "travel" },
        { en: "Who doesn't love a pay raise?", bn: "কে বেতন বৃদ্ধি পছন্দ করে না?", slotValues: { THING: "a pay raise" }, topicArea: "work" },
        { en: "Who doesn't love a massage after a long day?", bn: "কে দীর্ঘ দিনের পর ম্যাসাজ পছন্দ করে না?", slotValues: { THING: "a massage after a long day" }, topicArea: "health" },
        { en: "Who doesn't love a heartfelt compliment?", bn: "কে হৃদয়গ্রাহী প্রশংসা পছন্দ করে না?", slotValues: { THING: "a heartfelt compliment" }, topicArea: "relationships" },
      ],
      formality: "casual",
      difficulty: "advanced",
      usageNote: "This implies 'everyone loves it.' The expected answer is 'nobody.' Used for emphasis and agreement.",
      usageNote_bn: "এটি বোঝায় 'সবাই এটা পছন্দ করে।' প্রত্যাশিত উত্তর 'কেউ না।' জোর ও সম্মতির জন্য ব্যবহৃত।",
    },
    {
      id: "G13.2",
      formula: "What's the point of [DOING]?",
      formula_bn: "[করার] কী লাভ?",
      patternName: "Futility Rhetorical Question",
      patternName_bn: "নিরর্থকতা অলংকারিক প্রশ্ন",
      slots: [{ name: "DOING", description: "A gerund phrase about something seemingly pointless", description_bn: "আপাতদৃষ্টিতে অর্থহীন কিছু সম্পর্কে ক্রিয়াবাচক বিশেষ্য পদবন্ধ", acceptedTypes: ["gerund", "noun_phrase"], examples: ["worrying", "complaining", "rushing"] }],
      examples: [
        { en: "What's the point of worrying?", bn: "চিন্তা করার কী লাভ?", slotValues: { DOING: "worrying" }, topicArea: "daily_life" },
        { en: "What's the point of cooking if nobody eats?", bn: "কেউ না খেলে রান্না করার কী লাভ?", slotValues: { DOING: "cooking if nobody eats" }, topicArea: "food" },
        { en: "What's the point of rushing to the airport?", bn: "বিমানবন্দরে তাড়াহুড়ো করার কী লাভ?", slotValues: { DOING: "rushing to the airport" }, topicArea: "travel" },
        { en: "What's the point of studying without understanding?", bn: "না বুঝে পড়ার কী লাভ?", slotValues: { DOING: "studying without understanding" }, topicArea: "education" },
        { en: "What's the point of a meeting with no agenda?", bn: "এজেন্ডা ছাড়া মিটিংয়ের কী লাভ?", slotValues: { DOING: "a meeting with no agenda" }, topicArea: "work" },
        { en: "What's the point of exercising if you don't eat well?", bn: "ভালো না খেলে ব্যায়াম করার কী লাভ?", slotValues: { DOING: "exercising if you don't eat well" }, topicArea: "health" },
        { en: "What's the point of buying things you don't need?", bn: "যা দরকার নেই তা কেনার কী লাভ?", slotValues: { DOING: "buying things you don't need" }, topicArea: "shopping" },
        { en: "What's the point of arguing about it?", bn: "এটা নিয়ে তর্ক করার কী লাভ?", slotValues: { DOING: "arguing about it" }, topicArea: "relationships" },
        { en: "What's the point of complaining?", bn: "অভিযোগ করার কী লাভ?", slotValues: { DOING: "complaining" }, topicArea: "daily_life" },
        { en: "What's the point of ordering the same thing every time?", bn: "প্রতিবার একই জিনিস অর্ডার করার কী লাভ?", slotValues: { DOING: "ordering the same thing every time" }, topicArea: "food" },
        { en: "What's the point of traveling if you don't explore?", bn: "ঘুরে না দেখলে ভ্রমণ করার কী লাভ?", slotValues: { DOING: "traveling if you don't explore" }, topicArea: "travel" },
        { en: "What's the point of memorizing without applying?", bn: "প্রয়োগ না করলে মুখস্থ করার কী লাভ?", slotValues: { DOING: "memorizing without applying" }, topicArea: "education" },
        { en: "What's the point of working overtime for no extra pay?", bn: "বাড়তি বেতন ছাড়া ওভারটাইম করার কী লাভ?", slotValues: { DOING: "working overtime for no extra pay" }, topicArea: "work" },
        { en: "What's the point of skipping breakfast?", bn: "সকালের নাস্তা বাদ দেওয়ার কী লাভ?", slotValues: { DOING: "skipping breakfast" }, topicArea: "health" },
        { en: "What's the point of holding a grudge?", bn: "রাগ ধরে রাখার কী লাভ?", slotValues: { DOING: "holding a grudge" }, topicArea: "relationships" },
      ],
      formality: "casual",
      difficulty: "advanced",
      usageNote: "'What's the point of' implies something is useless or not worth doing. No answer is expected.",
      usageNote_bn: "'What's the point of' বোঝায় কিছু অকেজো বা করার যোগ্য নয়। কোনো উত্তর আশা করা হয় না।",
    },
    {
      id: "G13.3",
      formula: "How hard can it be to [ACTION]?",
      formula_bn: "[কাজ] করা কতটা কঠিন হতে পারে?",
      patternName: "Simplicity Rhetorical",
      patternName_bn: "সরলতা অলংকারিক",
      slots: [{ name: "ACTION", description: "A verb phrase about something that should be easy", description_bn: "সহজ হওয়া উচিত এমন কাজ সম্পর্কে ক্রিয়া পদবন্ধ", acceptedTypes: ["verb", "verb_phrase"], examples: ["follow instructions", "be on time", "cook rice"] }],
      examples: [
        { en: "How hard can it be to follow instructions?", bn: "নির্দেশনা মানা কতটা কঠিন হতে পারে?", slotValues: { ACTION: "follow instructions" }, topicArea: "daily_life" },
        { en: "How hard can it be to cook rice?", bn: "ভাত রান্না করা কতটা কঠিন হতে পারে?", slotValues: { ACTION: "cook rice" }, topicArea: "food" },
        { en: "How hard can it be to read a map?", bn: "মানচিত্র পড়া কতটা কঠিন হতে পারে?", slotValues: { ACTION: "read a map" }, topicArea: "travel" },
        { en: "How hard can it be to pass this test?", bn: "এই পরীক্ষায় পাশ করা কতটা কঠিন হতে পারে?", slotValues: { ACTION: "pass this test" }, topicArea: "education" },
        { en: "How hard can it be to send an email?", bn: "ইমেইল পাঠানো কতটা কঠিন হতে পারে?", slotValues: { ACTION: "send an email" }, topicArea: "work" },
        { en: "How hard can it be to drink more water?", bn: "বেশি পানি খাওয়া কতটা কঠিন হতে পারে?", slotValues: { ACTION: "drink more water" }, topicArea: "health" },
        { en: "How hard can it be to find a good deal?", bn: "ভালো ডিল খুঁজে পাওয়া কতটা কঠিন হতে পারে?", slotValues: { ACTION: "find a good deal" }, topicArea: "shopping" },
        { en: "How hard can it be to say sorry?", bn: "দুঃখিত বলা কতটা কঠিন হতে পারে?", slotValues: { ACTION: "say sorry" }, topicArea: "relationships" },
        { en: "How hard can it be to be on time?", bn: "সময়মতো আসা কতটা কঠিন হতে পারে?", slotValues: { ACTION: "be on time" }, topicArea: "daily_life" },
        { en: "How hard can it be to boil an egg?", bn: "ডিম সেদ্ধ করা কতটা কঠিন হতে পারে?", slotValues: { ACTION: "boil an egg" }, topicArea: "food" },
        { en: "How hard can it be to book a ticket online?", bn: "অনলাইনে টিকিট বুক করা কতটা কঠিন হতে পারে?", slotValues: { ACTION: "book a ticket online" }, topicArea: "travel" },
        { en: "How hard can it be to memorize ten words?", bn: "দশটা শব্দ মুখস্থ করা কতটা কঠিন হতে পারে?", slotValues: { ACTION: "memorize ten words" }, topicArea: "education" },
        { en: "How hard can it be to reply to a message?", bn: "মেসেজের উত্তর দেওয়া কতটা কঠিন হতে পারে?", slotValues: { ACTION: "reply to a message" }, topicArea: "work" },
        { en: "How hard can it be to walk 10 minutes a day?", bn: "দিনে ১০ মিনিট হাঁটা কতটা কঠিন হতে পারে?", slotValues: { ACTION: "walk 10 minutes a day" }, topicArea: "health" },
        { en: "How hard can it be to remember an anniversary?", bn: "বার্ষিকী মনে রাখা কতটা কঠিন হতে পারে?", slotValues: { ACTION: "remember an anniversary" }, topicArea: "relationships" },
      ],
      formality: "casual",
      difficulty: "advanced",
      usageNote: "Implies something should be easy. Often used to express frustration that someone can't do something simple.",
      usageNote_bn: "বোঝায় কিছু সহজ হওয়া উচিত। কেউ সহজ কিছু করতে না পারলে হতাশা প্রকাশে প্রায়ই ব্যবহৃত।",
    },
    {
      id: "G13.4",
      formula: "Isn't that [ADJECTIVE]?",
      formula_bn: "সেটা কি [বিশেষণ] না?",
      patternName: "Shared Reaction Rhetorical",
      patternName_bn: "ভাগ করা প্রতিক্রিয়া অলংকারিক",
      slots: [{ name: "ADJECTIVE", description: "An adjective expressing a strong opinion", description_bn: "একটি শক্তিশালী মতামত প্রকাশ করে এমন বিশেষণ", acceptedTypes: ["adjective", "adjective_phrase"], examples: ["amazing", "ridiculous", "wonderful"] }],
      examples: [
        { en: "Isn't that amazing?", bn: "সেটা কি অসাধারণ না?", slotValues: { ADJECTIVE: "amazing" }, topicArea: "daily_life" },
        { en: "Isn't that delicious?", bn: "সেটা কি সুস্বাদু না?", slotValues: { ADJECTIVE: "delicious" }, topicArea: "food" },
        { en: "Isn't that a beautiful view?", bn: "সেটা কি সুন্দর দৃশ্য না?", slotValues: { ADJECTIVE: "a beautiful view" }, topicArea: "travel" },
        { en: "Isn't that interesting?", bn: "সেটা কি আকর্ষণীয় না?", slotValues: { ADJECTIVE: "interesting" }, topicArea: "education" },
        { en: "Isn't that impressive?", bn: "সেটা কি চমৎকার না?", slotValues: { ADJECTIVE: "impressive" }, topicArea: "work" },
        { en: "Isn't that refreshing?", bn: "সেটা কি সতেজকর না?", slotValues: { ADJECTIVE: "refreshing" }, topicArea: "health" },
        { en: "Isn't that a great price?", bn: "সেটা কি দারুণ দাম না?", slotValues: { ADJECTIVE: "a great price" }, topicArea: "shopping" },
        { en: "Isn't that sweet?", bn: "সেটা কি মিষ্টি না?", slotValues: { ADJECTIVE: "sweet" }, topicArea: "relationships" },
        { en: "Isn't that ridiculous?", bn: "সেটা কি হাস্যকর না?", slotValues: { ADJECTIVE: "ridiculous" }, topicArea: "daily_life" },
        { en: "Isn't that the best pizza you've ever had?", bn: "সেটা কি তুমি যা খেয়েছো তার মধ্যে সেরা পিৎজা না?", slotValues: { ADJECTIVE: "the best pizza you've ever had" }, topicArea: "food" },
        { en: "Isn't that breathtaking?", bn: "সেটা কি মনোমুগ্ধকর না?", slotValues: { ADJECTIVE: "breathtaking" }, topicArea: "travel" },
        { en: "Isn't that fascinating?", bn: "সেটা কি চিত্তাকর্ষক না?", slotValues: { ADJECTIVE: "fascinating" }, topicArea: "education" },
        { en: "Isn't that frustrating?", bn: "সেটা কি হতাশাজনক না?", slotValues: { ADJECTIVE: "frustrating" }, topicArea: "work" },
        { en: "Isn't that dangerous?", bn: "সেটা কি বিপজ্জনক না?", slotValues: { ADJECTIVE: "dangerous" }, topicArea: "health" },
        { en: "Isn't that romantic?", bn: "সেটা কি রোমান্টিক না?", slotValues: { ADJECTIVE: "romantic" }, topicArea: "relationships" },
      ],
      formality: "casual",
      difficulty: "advanced",
      usageNote: "Used to invite agreement with your reaction. The speaker clearly already holds this opinion.",
      usageNote_bn: "আপনার প্রতিক্রিয়ার সাথে সম্মতি আমন্ত্রণ জানাতে ব্যবহৃত। বক্তা স্পষ্টতই ইতিমধ্যে এই মত ধারণ করেন।",
    },
    {
      id: "G13.5",
      formula: "Why would anyone [ACTION]?",
      formula_bn: "কেউ কেন [কাজ] করবে?",
      patternName: "Disbelief Rhetorical Question",
      patternName_bn: "অবিশ্বাস অলংকারিক প্রশ্ন",
      slots: [{ name: "ACTION", description: "An action the speaker finds unreasonable", description_bn: "বক্তা যা অযৌক্তিক মনে করেন এমন কাজ", acceptedTypes: ["verb", "verb_phrase"], examples: ["do that", "skip breakfast", "pay that much"] }],
      examples: [
        { en: "Why would anyone do that?", bn: "কেউ কেন ওটা করবে?", slotValues: { ACTION: "do that" }, topicArea: "daily_life" },
        { en: "Why would anyone eat raw fish?", bn: "কেউ কেন কাঁচা মাছ খাবে?", slotValues: { ACTION: "eat raw fish" }, topicArea: "food" },
        { en: "Why would anyone travel without insurance?", bn: "কেউ কেন বীমা ছাড়া ভ্রমণ করবে?", slotValues: { ACTION: "travel without insurance" }, topicArea: "travel" },
        { en: "Why would anyone skip class before the exam?", bn: "কেউ কেন পরীক্ষার আগে ক্লাস বাদ দেবে?", slotValues: { ACTION: "skip class before the exam" }, topicArea: "education" },
        { en: "Why would anyone quit a well-paying job?", bn: "কেউ কেন ভালো বেতনের চাকরি ছাড়বে?", slotValues: { ACTION: "quit a well-paying job" }, topicArea: "work" },
        { en: "Why would anyone skip breakfast?", bn: "কেউ কেন সকালের নাস্তা বাদ দেবে?", slotValues: { ACTION: "skip breakfast" }, topicArea: "health" },
        { en: "Why would anyone pay that much for a shirt?", bn: "কেউ কেন একটা শার্টের জন্য এত টাকা দেবে?", slotValues: { ACTION: "pay that much for a shirt" }, topicArea: "shopping" },
        { en: "Why would anyone lie to their best friend?", bn: "কেউ কেন তার সবচেয়ে ভালো বন্ধুর কাছে মিথ্যা বলবে?", slotValues: { ACTION: "lie to their best friend" }, topicArea: "relationships" },
        { en: "Why would anyone go out in this storm?", bn: "কেউ কেন এই ঝড়ে বাইরে যাবে?", slotValues: { ACTION: "go out in this storm" }, topicArea: "daily_life" },
        { en: "Why would anyone add sugar to tea?", bn: "কেউ কেন চায়ে চিনি দেবে?", slotValues: { ACTION: "add sugar to tea" }, topicArea: "food" },
        { en: "Why would anyone drive in rush hour traffic?", bn: "কেউ কেন ব্যস্ত সময়ে গাড়ি চালাবে?", slotValues: { ACTION: "drive in rush hour traffic" }, topicArea: "travel" },
        { en: "Why would anyone cheat on a test?", bn: "কেউ কেন পরীক্ষায় নকল করবে?", slotValues: { ACTION: "cheat on a test" }, topicArea: "education" },
        { en: "Why would anyone work for free?", bn: "কেউ কেন বিনামূল্যে কাজ করবে?", slotValues: { ACTION: "work for free" }, topicArea: "work" },
        { en: "Why would anyone ignore a doctor's advice?", bn: "কেউ কেন ডাক্তারের পরামর্শ উপেক্ষা করবে?", slotValues: { ACTION: "ignore a doctor's advice" }, topicArea: "health" },
        { en: "Why would anyone ghost a friend?", bn: "কেউ কেন বন্ধুকে এড়িয়ে চলবে?", slotValues: { ACTION: "ghost a friend" }, topicArea: "relationships" },
      ],
      formality: "casual",
      difficulty: "advanced",
      usageNote: "Expresses disbelief or disapproval. Implies no reasonable person would do this. Often humorous or critical.",
      usageNote_bn: "অবিশ্বাস বা অসম্মতি প্রকাশ করে। বোঝায় কোনো যুক্তিবাদী মানুষ এটা করবে না। প্রায়ই রসিকতাপূর্ণ বা সমালোচনামূলক।",
    },
  ],
};
