import { PatternCategory } from "@/types/pattern";

export const categoryG14: PatternCategory = {
  id: "G14",
  slug: "asking-for-directions-instructions",
  name: "Asking for Directions & Instructions",
  name_bn: "দিকনির্দেশনা ও নির্দেশনা চাওয়া",
  description: "Learn to ask for directions to places and instructions for how to do things.",
  description_bn: "জায়গায় যাওয়ার পথ এবং কিভাবে কিছু করতে হয় তার নির্দেশনা চাইতে শিখুন।",
  icon: "🧭",
  group: "G",
  groupName: "All Question Types",
  groupName_bn: "সকল প্রশ্নের ধরন",
  difficulty: "intermediate",
  patterns: [
    {
      id: "G14.1",
      formula: "How do I get to [PLACE]?",
      formula_bn: "আমি কিভাবে [স্থানে] যাবো?",
      patternName: "Directions Question",
      patternName_bn: "দিকনির্দেশনা প্রশ্ন",
      slots: [{ name: "PLACE", description: "A destination you want to reach", description_bn: "যে গন্তব্যে পৌঁছাতে চান", acceptedTypes: ["place", "noun_phrase"], examples: ["the train station", "the nearest hospital", "your house"] }],
      examples: [
        { en: "How do I get to the train station?", bn: "আমি কিভাবে ট্রেন স্টেশনে যাবো?", slotValues: { PLACE: "the train station" }, topicArea: "travel" },
        { en: "How do I get to the nearest hospital?", bn: "আমি কিভাবে নিকটতম হাসপাতালে যাবো?", slotValues: { PLACE: "the nearest hospital" }, topicArea: "health" },
        { en: "How do I get to the food court?", bn: "আমি কিভাবে ফুড কোর্টে যাবো?", slotValues: { PLACE: "the food court" }, topicArea: "food" },
        { en: "How do I get to the main office?", bn: "আমি কিভাবে প্রধান অফিসে যাবো?", slotValues: { PLACE: "the main office" }, topicArea: "work" },
        { en: "How do I get to the university?", bn: "আমি কিভাবে বিশ্ববিদ্যালয়ে যাবো?", slotValues: { PLACE: "the university" }, topicArea: "education" },
        { en: "How do I get to the shopping mall?", bn: "আমি কিভাবে শপিং মলে যাবো?", slotValues: { PLACE: "the shopping mall" }, topicArea: "shopping" },
        { en: "How do I get to your house?", bn: "আমি কিভাবে তোমার বাড়িতে যাবো?", slotValues: { PLACE: "your house" }, topicArea: "relationships" },
        { en: "How do I get to the airport from here?", bn: "আমি এখান থেকে কিভাবে বিমানবন্দরে যাবো?", slotValues: { PLACE: "the airport from here" }, topicArea: "travel" },
        { en: "How do I get to the parking area?", bn: "আমি কিভাবে পার্কিং এলাকায় যাবো?", slotValues: { PLACE: "the parking area" }, topicArea: "daily_life" },
        { en: "How do I get to the pharmacy?", bn: "আমি কিভাবে ফার্মেসিতে যাবো?", slotValues: { PLACE: "the pharmacy" }, topicArea: "health" },
        { en: "How do I get to the market?", bn: "আমি কিভাবে বাজারে যাবো?", slotValues: { PLACE: "the market" }, topicArea: "food" },
        { en: "How do I get to the conference room?", bn: "আমি কিভাবে কনফারেন্স রুমে যাবো?", slotValues: { PLACE: "the conference room" }, topicArea: "work" },
        { en: "How do I get to the library?", bn: "আমি কিভাবে লাইব্রেরিতে যাবো?", slotValues: { PLACE: "the library" }, topicArea: "education" },
        { en: "How do I get to the customer service desk?", bn: "আমি কিভাবে কাস্টমার সার্ভিস ডেস্কে যাবো?", slotValues: { PLACE: "the customer service desk" }, topicArea: "shopping" },
        { en: "How do I get to the city center?", bn: "আমি কিভাবে শহরের কেন্দ্রে যাবো?", slotValues: { PLACE: "the city center" }, topicArea: "daily_life" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "The most direct way to ask for directions. Can be made politer by adding 'Excuse me' before it.",
      usageNote_bn: "দিকনির্দেশনা চাওয়ার সবচেয়ে সরাসরি উপায়। এর আগে 'Excuse me' যোগ করলে আরো ভদ্র হয়।",
    },
    {
      id: "G14.2",
      formula: "Can you show me how to [ACTION]?",
      formula_bn: "তুমি কি আমাকে দেখাতে পারো কিভাবে [কাজ] করতে হয়?",
      patternName: "Demonstration Request",
      patternName_bn: "প্রদর্শন অনুরোধ",
      slots: [{ name: "ACTION", description: "A task you need someone to demonstrate", description_bn: "যে কাজ কাউকে প্রদর্শন করতে হবে", acceptedTypes: ["verb", "verb_phrase"], examples: ["use this app", "tie a knot", "operate this machine"] }],
      examples: [
        { en: "Can you show me how to use this app?", bn: "তুমি কি আমাকে দেখাতে পারো কিভাবে এই অ্যাপ ব্যবহার করতে হয়?", slotValues: { ACTION: "use this app" }, topicArea: "daily_life" },
        { en: "Can you show me how to make this recipe?", bn: "তুমি কি আমাকে দেখাতে পারো কিভাবে এই রেসিপি বানাতে হয়?", slotValues: { ACTION: "make this recipe" }, topicArea: "food" },
        { en: "Can you show me how to read the subway map?", bn: "তুমি কি আমাকে দেখাতে পারো কিভাবে সাবওয়ের মানচিত্র পড়তে হয়?", slotValues: { ACTION: "read the subway map" }, topicArea: "travel" },
        { en: "Can you show me how to solve this problem?", bn: "তুমি কি আমাকে দেখাতে পারো কিভাবে এই সমস্যার সমাধান করতে হয়?", slotValues: { ACTION: "solve this problem" }, topicArea: "education" },
        { en: "Can you show me how to operate this machine?", bn: "তুমি কি আমাকে দেখাতে পারো কিভাবে এই মেশিন চালাতে হয়?", slotValues: { ACTION: "operate this machine" }, topicArea: "work" },
        { en: "Can you show me how to do this stretch?", bn: "তুমি কি আমাকে দেখাতে পারো কিভাবে এই স্ট্রেচ করতে হয়?", slotValues: { ACTION: "do this stretch" }, topicArea: "health" },
        { en: "Can you show me how to apply this coupon?", bn: "তুমি কি আমাকে দেখাতে পারো কিভাবে এই কুপন ব্যবহার করতে হয়?", slotValues: { ACTION: "apply this coupon" }, topicArea: "shopping" },
        { en: "Can you show me how to tie a tie?", bn: "তুমি কি আমাকে দেখাতে পারো কিভাবে টাই বাঁধতে হয়?", slotValues: { ACTION: "tie a tie" }, topicArea: "relationships" },
        { en: "Can you show me how to connect to the Wi-Fi?", bn: "তুমি কি আমাকে দেখাতে পারো কিভাবে ওয়াই-ফাই কানেক্ট করতে হয়?", slotValues: { ACTION: "connect to the Wi-Fi" }, topicArea: "daily_life" },
        { en: "Can you show me how to chop onions properly?", bn: "তুমি কি আমাকে দেখাতে পারো কিভাবে সঠিকভাবে পেঁয়াজ কাটতে হয়?", slotValues: { ACTION: "chop onions properly" }, topicArea: "food" },
        { en: "Can you show me how to buy tickets from this machine?", bn: "তুমি কি আমাকে দেখাতে পারো কিভাবে এই মেশিন থেকে টিকিট কিনতে হয়?", slotValues: { ACTION: "buy tickets from this machine" }, topicArea: "travel" },
        { en: "Can you show me how to format this document?", bn: "তুমি কি আমাকে দেখাতে পারো কিভাবে এই ডকুমেন্ট ফরম্যাট করতে হয়?", slotValues: { ACTION: "format this document" }, topicArea: "work" },
        { en: "Can you show me how to write a thesis?", bn: "তুমি কি আমাকে দেখাতে পারো কিভাবে থিসিস লিখতে হয়?", slotValues: { ACTION: "write a thesis" }, topicArea: "education" },
        { en: "Can you show me how to measure blood pressure?", bn: "তুমি কি আমাকে দেখাতে পারো কিভাবে রক্তচাপ মাপতে হয়?", slotValues: { ACTION: "measure blood pressure" }, topicArea: "health" },
        { en: "Can you show me how to set up the account?", bn: "তুমি কি আমাকে দেখাতে পারো কিভাবে অ্যাকাউন্ট সেটআপ করতে হয়?", slotValues: { ACTION: "set up the account" }, topicArea: "shopping" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "'Show me how to' asks for a visual demonstration, not just verbal explanation. Very practical for learning.",
      usageNote_bn: "'Show me how to' দৃশ্যমান প্রদর্শন চায়, শুধু মৌখিক ব্যাখ্যা নয়। শেখার জন্য খুবই কার্যকর।",
    },
    {
      id: "G14.3",
      formula: "Which way is [PLACE]?",
      formula_bn: "[স্থান] কোন দিকে?",
      patternName: "Quick Direction Question",
      patternName_bn: "দ্রুত দিক প্রশ্ন",
      slots: [{ name: "PLACE", description: "A nearby place or landmark", description_bn: "নিকটবর্তী স্থান বা ল্যান্ডমার্ক", acceptedTypes: ["place", "noun_phrase"], examples: ["the exit", "the beach", "downtown"] }],
      examples: [
        { en: "Which way is the exit?", bn: "বের হওয়ার পথ কোন দিকে?", slotValues: { PLACE: "the exit" }, topicArea: "daily_life" },
        { en: "Which way is the restaurant?", bn: "রেস্টুরেন্ট কোন দিকে?", slotValues: { PLACE: "the restaurant" }, topicArea: "food" },
        { en: "Which way is the beach?", bn: "সমুদ্র সৈকত কোন দিকে?", slotValues: { PLACE: "the beach" }, topicArea: "travel" },
        { en: "Which way is the auditorium?", bn: "অডিটোরিয়াম কোন দিকে?", slotValues: { PLACE: "the auditorium" }, topicArea: "education" },
        { en: "Which way is the HR department?", bn: "এইচআর বিভাগ কোন দিকে?", slotValues: { PLACE: "the HR department" }, topicArea: "work" },
        { en: "Which way is the emergency room?", bn: "ইমার্জেন্সি রুম কোন দিকে?", slotValues: { PLACE: "the emergency room" }, topicArea: "health" },
        { en: "Which way is the checkout counter?", bn: "চেকআউট কাউন্টার কোন দিকে?", slotValues: { PLACE: "the checkout counter" }, topicArea: "shopping" },
        { en: "Which way is downtown?", bn: "শহরের কেন্দ্র কোন দিকে?", slotValues: { PLACE: "downtown" }, topicArea: "travel" },
        { en: "Which way is the parking lot?", bn: "পার্কিং লট কোন দিকে?", slotValues: { PLACE: "the parking lot" }, topicArea: "daily_life" },
        { en: "Which way is the cafeteria?", bn: "ক্যাফেটেরিয়া কোন দিকে?", slotValues: { PLACE: "the cafeteria" }, topicArea: "food" },
        { en: "Which way is the bus stop?", bn: "বাস স্টপ কোন দিকে?", slotValues: { PLACE: "the bus stop" }, topicArea: "travel" },
        { en: "Which way is the science building?", bn: "সায়েন্স বিল্ডিং কোন দিকে?", slotValues: { PLACE: "the science building" }, topicArea: "education" },
        { en: "Which way is the meeting room?", bn: "মিটিং রুম কোন দিকে?", slotValues: { PLACE: "the meeting room" }, topicArea: "work" },
        { en: "Which way is the waiting room?", bn: "ওয়েটিং রুম কোন দিকে?", slotValues: { PLACE: "the waiting room" }, topicArea: "health" },
        { en: "Which way is the men's section?", bn: "পুরুষদের সেকশন কোন দিকে?", slotValues: { PLACE: "the men's section" }, topicArea: "shopping" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "'Which way is' is a quick, informal way to ask for a general direction. Good when you just need to know left/right/straight.",
      usageNote_bn: "'Which way is' সাধারণ দিক জানার দ্রুত, অনানুষ্ঠানিক উপায়। শুধু বাম/ডান/সোজা জানতে হলে ভালো।",
    },
    {
      id: "G14.4",
      formula: "What's the best way to [ACTION]?",
      formula_bn: "[কাজ] করার সবচেয়ে ভালো উপায় কী?",
      patternName: "Best Method Question",
      patternName_bn: "সেরা পদ্ধতি প্রশ্ন",
      slots: [{ name: "ACTION", description: "A task or goal you want the best approach for", description_bn: "যে কাজ বা লক্ষ্যের জন্য সেরা পদ্ধতি চান", acceptedTypes: ["verb", "verb_phrase"], examples: ["get downtown", "learn vocabulary", "save money"] }],
      examples: [
        { en: "What's the best way to get downtown?", bn: "শহরের কেন্দ্রে যাওয়ার সবচেয়ে ভালো উপায় কী?", slotValues: { ACTION: "get downtown" }, topicArea: "travel" },
        { en: "What's the best way to learn vocabulary?", bn: "শব্দভাণ্ডার শেখার সবচেয়ে ভালো উপায় কী?", slotValues: { ACTION: "learn vocabulary" }, topicArea: "education" },
        { en: "What's the best way to cook chicken?", bn: "মুরগি রান্না করার সবচেয়ে ভালো উপায় কী?", slotValues: { ACTION: "cook chicken" }, topicArea: "food" },
        { en: "What's the best way to save money?", bn: "টাকা বাঁচানোর সবচেয়ে ভালো উপায় কী?", slotValues: { ACTION: "save money" }, topicArea: "shopping" },
        { en: "What's the best way to stay healthy?", bn: "সুস্থ থাকার সবচেয়ে ভালো উপায় কী?", slotValues: { ACTION: "stay healthy" }, topicArea: "health" },
        { en: "What's the best way to manage a team?", bn: "টিম পরিচালনা করার সবচেয়ে ভালো উপায় কী?", slotValues: { ACTION: "manage a team" }, topicArea: "work" },
        { en: "What's the best way to start a conversation?", bn: "কথোপকথন শুরু করার সবচেয়ে ভালো উপায় কী?", slotValues: { ACTION: "start a conversation" }, topicArea: "relationships" },
        { en: "What's the best way to organize my desk?", bn: "আমার ডেস্ক গোছানোর সবচেয়ে ভালো উপায় কী?", slotValues: { ACTION: "organize my desk" }, topicArea: "daily_life" },
        { en: "What's the best way to peel garlic?", bn: "রসুন ছাড়ানোর সবচেয়ে ভালো উপায় কী?", slotValues: { ACTION: "peel garlic" }, topicArea: "food" },
        { en: "What's the best way to get from the airport to the city?", bn: "বিমানবন্দর থেকে শহরে যাওয়ার সবচেয়ে ভালো উপায় কী?", slotValues: { ACTION: "get from the airport to the city" }, topicArea: "travel" },
        { en: "What's the best way to prepare for an exam?", bn: "পরীক্ষার জন্য প্রস্তুতি নেওয়ার সবচেয়ে ভালো উপায় কী?", slotValues: { ACTION: "prepare for an exam" }, topicArea: "education" },
        { en: "What's the best way to ask for a raise?", bn: "বেতন বৃদ্ধি চাওয়ার সবচেয়ে ভালো উপায় কী?", slotValues: { ACTION: "ask for a raise" }, topicArea: "work" },
        { en: "What's the best way to lose weight safely?", bn: "নিরাপদে ওজন কমানোর সবচেয়ে ভালো উপায় কী?", slotValues: { ACTION: "lose weight safely" }, topicArea: "health" },
        { en: "What's the best way to compare prices?", bn: "দাম তুলনা করার সবচেয়ে ভালো উপায় কী?", slotValues: { ACTION: "compare prices" }, topicArea: "shopping" },
        { en: "What's the best way to apologize sincerely?", bn: "আন্তরিকভাবে ক্ষমা চাওয়ার সবচেয়ে ভালো উপায় কী?", slotValues: { ACTION: "apologize sincerely" }, topicArea: "relationships" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "Asks for the most effective or efficient method. Very versatile and used in many contexts.",
      usageNote_bn: "সবচেয়ে কার্যকর বা দক্ষ পদ্ধতি চায়। অনেক বহুমুখী এবং বিভিন্ন প্রসঙ্গে ব্যবহৃত।",
    },
    {
      id: "G14.5",
      formula: "Is there a [THING] near here?",
      formula_bn: "এখানে কাছাকাছি কি কোনো [জিনিস] আছে?",
      patternName: "Nearby Location Question",
      patternName_bn: "নিকটবর্তী অবস্থান প্রশ্ন",
      slots: [{ name: "THING", description: "A type of place or facility you are looking for", description_bn: "যে ধরনের স্থান বা সুবিধা খুঁজছেন", acceptedTypes: ["noun", "noun_phrase", "place"], examples: ["bank", "gas station", "good restaurant"] }],
      examples: [
        { en: "Is there a bank near here?", bn: "এখানে কাছাকাছি কি কোনো ব্যাংক আছে?", slotValues: { THING: "bank" }, topicArea: "daily_life" },
        { en: "Is there a good restaurant near here?", bn: "এখানে কাছাকাছি কি কোনো ভালো রেস্টুরেন্ট আছে?", slotValues: { THING: "good restaurant" }, topicArea: "food" },
        { en: "Is there a gas station near here?", bn: "এখানে কাছাকাছি কি কোনো পেট্রোল পাম্প আছে?", slotValues: { THING: "gas station" }, topicArea: "travel" },
        { en: "Is there a bookstore near here?", bn: "এখানে কাছাকাছি কি কোনো বইয়ের দোকান আছে?", slotValues: { THING: "bookstore" }, topicArea: "education" },
        { en: "Is there a copy shop near here?", bn: "এখানে কাছাকাছি কি কোনো ফটোকপির দোকান আছে?", slotValues: { THING: "copy shop" }, topicArea: "work" },
        { en: "Is there a pharmacy near here?", bn: "এখানে কাছাকাছি কি কোনো ফার্মেসি আছে?", slotValues: { THING: "pharmacy" }, topicArea: "health" },
        { en: "Is there a supermarket near here?", bn: "এখানে কাছাকাছি কি কোনো সুপারমার্কেট আছে?", slotValues: { THING: "supermarket" }, topicArea: "shopping" },
        { en: "Is there a park near here?", bn: "এখানে কাছাকাছি কি কোনো পার্ক আছে?", slotValues: { THING: "park" }, topicArea: "relationships" },
        { en: "Is there a public restroom near here?", bn: "এখানে কাছাকাছি কি কোনো পাবলিক টয়লেট আছে?", slotValues: { THING: "public restroom" }, topicArea: "daily_life" },
        { en: "Is there a coffee shop near here?", bn: "এখানে কাছাকাছি কি কোনো কফি শপ আছে?", slotValues: { THING: "coffee shop" }, topicArea: "food" },
        { en: "Is there a metro station near here?", bn: "এখানে কাছাকাছি কি কোনো মেট্রো স্টেশন আছে?", slotValues: { THING: "metro station" }, topicArea: "travel" },
        { en: "Is there a library near here?", bn: "এখানে কাছাকাছি কি কোনো লাইব্রেরি আছে?", slotValues: { THING: "library" }, topicArea: "education" },
        { en: "Is there a printing shop near here?", bn: "এখানে কাছাকাছি কি কোনো প্রিন্টিং শপ আছে?", slotValues: { THING: "printing shop" }, topicArea: "work" },
        { en: "Is there a clinic near here?", bn: "এখানে কাছাকাছি কি কোনো ক্লিনিক আছে?", slotValues: { THING: "clinic" }, topicArea: "health" },
        { en: "Is there a shoe store near here?", bn: "এখানে কাছাকাছি কি কোনো জুতোর দোকান আছে?", slotValues: { THING: "shoe store" }, topicArea: "shopping" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "'Is there a ... near here?' is essential for travelers and newcomers. Very practical and commonly used.",
      usageNote_bn: "'Is there a ... near here?' ভ্রমণকারী ও নতুনদের জন্য অপরিহার্য। খুবই কার্যকর এবং সাধারণভাবে ব্যবহৃত।",
    },
  ],
};
