import { PatternCategory } from "@/types/pattern";

export const categoryG15: PatternCategory = {
  id: "G15",
  slug: "choice-questions",
  name: "Choice Questions",
  name_bn: "পছন্দ প্রশ্ন",
  description: "Ask questions that offer choices between options",
  description_bn: "বিকল্পের মধ্যে পছন্দ দেওয়া প্রশ্ন জিজ্ঞাসা করুন",
  icon: "🔀",
  group: "G",
  groupName: "All Question Types",
  groupName_bn: "সকল প্রশ্নের ধরন",
  difficulty: "intermediate",
  patterns: [
    {
      id: "G15.1",
      formula: "Which [THING] do you prefer, [A] or [B]?",
      formula_bn: "তুমি কোন [জিনিস] পছন্দ করো, [ক] না [খ]?",
      patternName: "Preference Choice",
      patternName_bn: "পছন্দের বাছাই",
      slots: [
        { name: "THING", description: "Category of items", description_bn: "জিনিসের ধরন", acceptedTypes: ["noun"], examples: ["color", "season", "food"] },
        { name: "A", description: "First option", description_bn: "প্রথম বিকল্প", acceptedTypes: ["noun"], examples: ["red", "summer", "rice"] },
        { name: "B", description: "Second option", description_bn: "দ্বিতীয় বিকল্প", acceptedTypes: ["noun"], examples: ["blue", "winter", "bread"] },
      ],
      examples: [
        { en: "Which color do you prefer, red or blue?", bn: "তুমি কোন রঙ পছন্দ করো, লাল না নীল?", slotValues: { THING: "color", A: "red", B: "blue" }, topicArea: "daily_life" },
        { en: "Which season do you prefer, summer or winter?", bn: "তুমি কোন ঋতু পছন্দ করো, গ্রীষ্ম না শীত?", slotValues: { THING: "season", A: "summer", B: "winter" }, topicArea: "daily_life" },
        { en: "Which food do you prefer, rice or bread?", bn: "তুমি কোন খাবার পছন্দ করো, ভাত না রুটি?", slotValues: { THING: "food", A: "rice", B: "bread" }, topicArea: "food" },
        { en: "Which drink do you prefer, tea or coffee?", bn: "তুমি কোন পানীয় পছন্দ করো, চা না কফি?", slotValues: { THING: "drink", A: "tea", B: "coffee" }, topicArea: "food" },
        { en: "Which subject do you prefer, math or science?", bn: "তুমি কোন বিষয় পছন্দ করো, গণিত না বিজ্ঞান?", slotValues: { THING: "subject", A: "math", B: "science" }, topicArea: "education" },
        { en: "Which city do you prefer, Dhaka or Chittagong?", bn: "তুমি কোন শহর পছন্দ করো, ঢাকা না চট্টগ্রাম?", slotValues: { THING: "city", A: "Dhaka", B: "Chittagong" }, topicArea: "travel" },
        { en: "Which day do you prefer, Saturday or Friday?", bn: "তুমি কোন দিন পছন্দ করো, শনিবার না শুক্রবার?", slotValues: { THING: "day", A: "Saturday", B: "Friday" }, topicArea: "daily_life" },
        { en: "Which sport do you prefer, cricket or football?", bn: "তুমি কোন খেলা পছন্দ করো, ক্রিকেট না ফুটবল?", slotValues: { THING: "sport", A: "cricket", B: "football" }, topicArea: "daily_life" },
        { en: "Which phone do you prefer, iPhone or Samsung?", bn: "তুমি কোন ফোন পছন্দ করো, আইফোন না স্যামসাং?", slotValues: { THING: "phone", A: "iPhone", B: "Samsung" }, topicArea: "shopping" },
        { en: "Which shift do you prefer, morning or night?", bn: "তুমি কোন শিফট পছন্দ করো, সকাল না রাত?", slotValues: { THING: "shift", A: "morning", B: "night" }, topicArea: "work" },
        { en: "Which pet do you prefer, cats or dogs?", bn: "তুমি কোন পোষা প্রাণী পছন্দ করো, বিড়াল না কুকুর?", slotValues: { THING: "pet", A: "cats", B: "dogs" }, topicArea: "daily_life" },
        { en: "Which fabric do you prefer, cotton or silk?", bn: "তুমি কোন কাপড় পছন্দ করো, সুতি না রেশম?", slotValues: { THING: "fabric", A: "cotton", B: "silk" }, topicArea: "shopping" },
        { en: "Which hospital do you prefer, private or public?", bn: "তুমি কোন হাসপাতাল পছন্দ করো, বেসরকারি না সরকারি?", slotValues: { THING: "hospital", A: "private", B: "public" }, topicArea: "health" },
        { en: "Which transport do you prefer, bus or train?", bn: "তুমি কোন পরিবহন পছন্দ করো, বাস না ট্রেন?", slotValues: { THING: "transport", A: "bus", B: "train" }, topicArea: "travel" },
        { en: "Which movie do you prefer, comedy or action?", bn: "তুমি কোন মুভি পছন্দ করো, কমেডি না অ্যাকশন?", slotValues: { THING: "movie", A: "comedy", B: "action" }, topicArea: "daily_life" },
      ],
      formality: "casual",
      difficulty: "beginner",
    },
    {
      id: "G15.2",
      formula: "Would you rather [ACTION1] or [ACTION2]?",
      formula_bn: "তুমি কি বরং [কাজ১] করবে নাকি [কাজ২]?",
      patternName: "Would Rather Choice",
      patternName_bn: "বরং পছন্দ",
      slots: [
        { name: "ACTION1", description: "First action option", description_bn: "প্রথম কাজের বিকল্প", acceptedTypes: ["verb"], examples: ["stay home", "eat out"] },
        { name: "ACTION2", description: "Second action option", description_bn: "দ্বিতীয় কাজের বিকল্প", acceptedTypes: ["verb"], examples: ["go out", "cook at home"] },
      ],
      examples: [
        { en: "Would you rather stay home or go out?", bn: "তুমি কি বরং বাড়িতে থাকবে নাকি বাইরে যাবে?", slotValues: { ACTION1: "stay home", ACTION2: "go out" }, topicArea: "daily_life" },
        { en: "Would you rather eat out or cook at home?", bn: "তুমি কি বরং বাইরে খাবে নাকি বাড়িতে রান্না করবে?", slotValues: { ACTION1: "eat out", ACTION2: "cook at home" }, topicArea: "food" },
        { en: "Would you rather read a book or watch a movie?", bn: "তুমি কি বরং বই পড়বে নাকি মুভি দেখবে?", slotValues: { ACTION1: "read a book", ACTION2: "watch a movie" }, topicArea: "daily_life" },
        { en: "Would you rather travel by plane or by train?", bn: "তুমি কি বরং প্লেনে যাবে নাকি ট্রেনে?", slotValues: { ACTION1: "travel by plane", ACTION2: "travel by train" }, topicArea: "travel" },
        { en: "Would you rather work from home or go to the office?", bn: "তুমি কি বরং বাড়ি থেকে কাজ করবে নাকি অফিসে যাবে?", slotValues: { ACTION1: "work from home", ACTION2: "go to the office" }, topicArea: "work" },
        { en: "Would you rather study online or in a classroom?", bn: "তুমি কি বরং অনলাইনে পড়বে নাকি ক্লাসরুমে?", slotValues: { ACTION1: "study online", ACTION2: "study in a classroom" }, topicArea: "education" },
        { en: "Would you rather have tea or coffee?", bn: "তুমি কি বরং চা খাবে নাকি কফি?", slotValues: { ACTION1: "have tea", ACTION2: "have coffee" }, topicArea: "food" },
        { en: "Would you rather walk or take a taxi?", bn: "তুমি কি বরং হেঁটে যাবে নাকি ট্যাক্সি নেবে?", slotValues: { ACTION1: "walk", ACTION2: "take a taxi" }, topicArea: "travel" },
        { en: "Would you rather save money or spend it?", bn: "তুমি কি বরং টাকা জমাবে নাকি খরচ করবে?", slotValues: { ACTION1: "save money", ACTION2: "spend it" }, topicArea: "shopping" },
        { en: "Would you rather visit the mountains or the beach?", bn: "তুমি কি বরং পাহাড়ে যাবে নাকি সমুদ্রে?", slotValues: { ACTION1: "visit the mountains", ACTION2: "visit the beach" }, topicArea: "travel" },
        { en: "Would you rather call or text?", bn: "তুমি কি বরং কল করবে নাকি টেক্সট করবে?", slotValues: { ACTION1: "call", ACTION2: "text" }, topicArea: "relationships" },
        { en: "Would you rather exercise in the morning or evening?", bn: "তুমি কি বরং সকালে ব্যায়াম করবে নাকি সন্ধ্যায়?", slotValues: { ACTION1: "exercise in the morning", ACTION2: "exercise in the evening" }, topicArea: "health" },
        { en: "Would you rather lead a team or work alone?", bn: "তুমি কি বরং দল পরিচালনা করবে নাকি একা কাজ করবে?", slotValues: { ACTION1: "lead a team", ACTION2: "work alone" }, topicArea: "work" },
        { en: "Would you rather learn English or Arabic?", bn: "তুমি কি বরং ইংরেজি শিখবে নাকি আরবি?", slotValues: { ACTION1: "learn English", ACTION2: "learn Arabic" }, topicArea: "education" },
        { en: "Would you rather eat fish or chicken?", bn: "তুমি কি বরং মাছ খাবে নাকি মুরগি?", slotValues: { ACTION1: "eat fish", ACTION2: "eat chicken" }, topicArea: "food" },
      ],
      formality: "casual",
      difficulty: "intermediate",
    },
    {
      id: "G15.3",
      formula: "Do you want [A] or [B]?",
      formula_bn: "তুমি কি [ক] চাও নাকি [খ]?",
      patternName: "Direct Choice",
      patternName_bn: "সরাসরি পছন্দ",
      slots: [
        { name: "A", description: "First option", description_bn: "প্রথম বিকল্প", acceptedTypes: ["noun"], examples: ["this one", "milk"] },
        { name: "B", description: "Second option", description_bn: "দ্বিতীয় বিকল্প", acceptedTypes: ["noun"], examples: ["that one", "sugar"] },
      ],
      examples: [
        { en: "Do you want this one or that one?", bn: "তুমি কি এটা চাও নাকি ওটা?", slotValues: { A: "this one", B: "that one" }, topicArea: "shopping" },
        { en: "Do you want milk or sugar?", bn: "তুমি কি দুধ চাও নাকি চিনি?", slotValues: { A: "milk", B: "sugar" }, topicArea: "food" },
        { en: "Do you want rice or noodles?", bn: "তুমি কি ভাত চাও নাকি নুডলস?", slotValues: { A: "rice", B: "noodles" }, topicArea: "food" },
        { en: "Do you want the window seat or the aisle seat?", bn: "তুমি কি জানালার সিট চাও নাকি করিডোরের সিট?", slotValues: { A: "the window seat", B: "the aisle seat" }, topicArea: "travel" },
        { en: "Do you want the red one or the blue one?", bn: "তুমি কি লালটা চাও নাকি নীলটা?", slotValues: { A: "the red one", B: "the blue one" }, topicArea: "shopping" },
        { en: "Do you want to go now or later?", bn: "তুমি কি এখন যেতে চাও নাকি পরে?", slotValues: { A: "to go now", B: "later" }, topicArea: "daily_life" },
        { en: "Do you want hot water or cold water?", bn: "তুমি কি গরম পানি চাও নাকি ঠান্ডা পানি?", slotValues: { A: "hot water", B: "cold water" }, topicArea: "health" },
        { en: "Do you want a receipt or not?", bn: "তুমি কি রিসিট চাও নাকি না?", slotValues: { A: "a receipt", B: "not" }, topicArea: "shopping" },
        { en: "Do you want the small size or the large size?", bn: "তুমি কি ছোট সাইজ চাও নাকি বড় সাইজ?", slotValues: { A: "the small size", B: "the large size" }, topicArea: "shopping" },
        { en: "Do you want to sit inside or outside?", bn: "তুমি কি ভিতরে বসতে চাও নাকি বাইরে?", slotValues: { A: "to sit inside", B: "outside" }, topicArea: "food" },
        { en: "Do you want morning class or afternoon class?", bn: "তুমি কি সকালের ক্লাস চাও নাকি বিকেলের?", slotValues: { A: "morning class", B: "afternoon class" }, topicArea: "education" },
        { en: "Do you want to call him or message him?", bn: "তুমি কি তাকে কল করতে চাও নাকি মেসেজ করতে?", slotValues: { A: "to call him", B: "message him" }, topicArea: "relationships" },
        { en: "Do you want the full-time position or part-time?", bn: "তুমি কি ফুলটাইম পদ চাও নাকি পার্টটাইম?", slotValues: { A: "the full-time position", B: "part-time" }, topicArea: "work" },
        { en: "Do you want vanilla or chocolate?", bn: "তুমি কি ভ্যানিলা চাও নাকি চকলেট?", slotValues: { A: "vanilla", B: "chocolate" }, topicArea: "food" },
        { en: "Do you want to take medicine or rest?", bn: "তুমি কি ওষুধ খেতে চাও নাকি বিশ্রাম নিতে?", slotValues: { A: "to take medicine", B: "rest" }, topicArea: "health" },
      ],
      formality: "casual",
      difficulty: "beginner",
    },
    {
      id: "G15.4",
      formula: "Should we [ACTION1] or [ACTION2]?",
      formula_bn: "আমরা কি [কাজ১] করব নাকি [কাজ২]?",
      patternName: "Group Decision Choice",
      patternName_bn: "দলগত সিদ্ধান্তের পছন্দ",
      slots: [
        { name: "ACTION1", description: "First option", description_bn: "প্রথম বিকল্প", acceptedTypes: ["verb"], examples: ["leave now", "order pizza"] },
        { name: "ACTION2", description: "Second option", description_bn: "দ্বিতীয় বিকল্প", acceptedTypes: ["verb"], examples: ["wait", "cook something"] },
      ],
      examples: [
        { en: "Should we leave now or wait?", bn: "আমরা কি এখন রওনা দেব নাকি অপেক্ষা করব?", slotValues: { ACTION1: "leave now", ACTION2: "wait" }, topicArea: "daily_life" },
        { en: "Should we order pizza or cook something?", bn: "আমরা কি পিৎজা অর্ডার করব নাকি কিছু রান্না করব?", slotValues: { ACTION1: "order pizza", ACTION2: "cook something" }, topicArea: "food" },
        { en: "Should we take a taxi or walk?", bn: "আমরা কি ট্যাক্সি নেব নাকি হেঁটে যাব?", slotValues: { ACTION1: "take a taxi", ACTION2: "walk" }, topicArea: "travel" },
        { en: "Should we start the meeting or wait for everyone?", bn: "আমরা কি মিটিং শুরু করব নাকি সবার জন্য অপেক্ষা করব?", slotValues: { ACTION1: "start the meeting", ACTION2: "wait for everyone" }, topicArea: "work" },
        { en: "Should we study together or separately?", bn: "আমরা কি একসাথে পড়ব নাকি আলাদাভাবে?", slotValues: { ACTION1: "study together", ACTION2: "study separately" }, topicArea: "education" },
        { en: "Should we buy it online or from the store?", bn: "আমরা কি অনলাইনে কিনব নাকি দোকান থেকে?", slotValues: { ACTION1: "buy it online", ACTION2: "buy it from the store" }, topicArea: "shopping" },
        { en: "Should we eat here or take it away?", bn: "আমরা কি এখানে খাব নাকি নিয়ে যাব?", slotValues: { ACTION1: "eat here", ACTION2: "take it away" }, topicArea: "food" },
        { en: "Should we go by bus or train?", bn: "আমরা কি বাসে যাব নাকি ট্রেনে?", slotValues: { ACTION1: "go by bus", ACTION2: "go by train" }, topicArea: "travel" },
        { en: "Should we call a doctor or go to the hospital?", bn: "আমরা কি ডাক্তার ডাকব নাকি হাসপাতালে যাব?", slotValues: { ACTION1: "call a doctor", ACTION2: "go to the hospital" }, topicArea: "health" },
        { en: "Should we invite them or keep it small?", bn: "আমরা কি তাদের দাওয়াত দেব নাকি ছোট রাখব?", slotValues: { ACTION1: "invite them", ACTION2: "keep it small" }, topicArea: "relationships" },
        { en: "Should we present it today or tomorrow?", bn: "আমরা কি আজ উপস্থাপন করব নাকি কাল?", slotValues: { ACTION1: "present it today", ACTION2: "present it tomorrow" }, topicArea: "work" },
        { en: "Should we take the highway or the back road?", bn: "আমরা কি হাইওয়ে ধরব নাকি পিছনের রাস্তা?", slotValues: { ACTION1: "take the highway", ACTION2: "take the back road" }, topicArea: "travel" },
        { en: "Should we review it again or submit it now?", bn: "আমরা কি আবার রিভিউ করব নাকি এখনই জমা দেব?", slotValues: { ACTION1: "review it again", ACTION2: "submit it now" }, topicArea: "education" },
        { en: "Should we split the bill or pay separately?", bn: "আমরা কি বিল ভাগ করব নাকি আলাদাভাবে দেব?", slotValues: { ACTION1: "split the bill", ACTION2: "pay separately" }, topicArea: "food" },
        { en: "Should we get the cheaper one or the better one?", bn: "আমরা কি সস্তাটা নেব নাকি ভালোটা?", slotValues: { ACTION1: "get the cheaper one", ACTION2: "get the better one" }, topicArea: "shopping" },
      ],
      formality: "casual",
      difficulty: "beginner",
    },
    {
      id: "G15.5",
      formula: "Which one do you like better, [A] or [B]?",
      formula_bn: "[ক] আর [খ]-এর মধ্যে কোনটা তোমার বেশি পছন্দ?",
      patternName: "Comparative Choice",
      patternName_bn: "তুলনামূলক পছন্দ",
      slots: [
        { name: "A", description: "First option", description_bn: "প্রথম বিকল্প", acceptedTypes: ["noun"], examples: ["this design", "the first one"] },
        { name: "B", description: "Second option", description_bn: "দ্বিতীয় বিকল্প", acceptedTypes: ["noun"], examples: ["that design", "the second one"] },
      ],
      examples: [
        { en: "Which one do you like better, this design or that design?", bn: "এই ডিজাইন আর ওই ডিজাইনের মধ্যে কোনটা তোমার বেশি পছন্দ?", slotValues: { A: "this design", B: "that design" }, topicArea: "work" },
        { en: "Which one do you like better, the black shoes or the brown shoes?", bn: "কালো জুতা আর বাদামি জুতার মধ্যে কোনটা তোমার বেশি পছন্দ?", slotValues: { A: "the black shoes", B: "the brown shoes" }, topicArea: "shopping" },
        { en: "Which one do you like better, the first restaurant or the second one?", bn: "প্রথম রেস্তোরাঁ আর দ্বিতীয়টার মধ্যে কোনটা তোমার বেশি পছন্দ?", slotValues: { A: "the first restaurant", B: "the second one" }, topicArea: "food" },
        { en: "Which one do you like better, my old hair or the new style?", bn: "আমার পুরনো চুল আর নতুন স্টাইলের মধ্যে কোনটা তোমার বেশি পছন্দ?", slotValues: { A: "my old hair", B: "the new style" }, topicArea: "daily_life" },
        { en: "Which one do you like better, the morning flight or the evening flight?", bn: "সকালের ফ্লাইট আর সন্ধ্যার ফ্লাইটের মধ্যে কোনটা তোমার বেশি পছন্দ?", slotValues: { A: "the morning flight", B: "the evening flight" }, topicArea: "travel" },
        { en: "Which one do you like better, Plan A or Plan B?", bn: "প্ল্যান এ আর প্ল্যান বি-এর মধ্যে কোনটা তোমার বেশি পছন্দ?", slotValues: { A: "Plan A", B: "Plan B" }, topicArea: "work" },
        { en: "Which one do you like better, this song or that song?", bn: "এই গান আর ওই গানের মধ্যে কোনটা তোমার বেশি পছন্দ?", slotValues: { A: "this song", B: "that song" }, topicArea: "daily_life" },
        { en: "Which one do you like better, the small apartment or the big one?", bn: "ছোট অ্যাপার্টমেন্ট আর বড়টার মধ্যে কোনটা তোমার বেশি পছন্দ?", slotValues: { A: "the small apartment", B: "the big one" }, topicArea: "daily_life" },
        { en: "Which one do you like better, this course or that course?", bn: "এই কোর্স আর ওই কোর্সের মধ্যে কোনটা তোমার বেশি পছন্দ?", slotValues: { A: "this course", B: "that course" }, topicArea: "education" },
        { en: "Which one do you like better, chicken biryani or beef biryani?", bn: "চিকেন বিরিয়ানি আর গরুর বিরিয়ানির মধ্যে কোনটা তোমার বেশি পছন্দ?", slotValues: { A: "chicken biryani", B: "beef biryani" }, topicArea: "food" },
        { en: "Which one do you like better, this ring or that necklace?", bn: "এই আংটি আর ওই হারের মধ্যে কোনটা তোমার বেশি পছন্দ?", slotValues: { A: "this ring", B: "that necklace" }, topicArea: "shopping" },
        { en: "Which one do you like better, the beach hotel or the city hotel?", bn: "সৈকতের হোটেল আর শহরের হোটেলের মধ্যে কোনটা তোমার বেশি পছন্দ?", slotValues: { A: "the beach hotel", B: "the city hotel" }, topicArea: "travel" },
        { en: "Which one do you like better, the syrup or the tablets?", bn: "সিরাপ আর ট্যাবলেটের মধ্যে কোনটা তোমার বেশি পছন্দ?", slotValues: { A: "the syrup", B: "the tablets" }, topicArea: "health" },
        { en: "Which one do you like better, working early or working late?", bn: "সকালে কাজ করা আর রাতে কাজ করার মধ্যে কোনটা তোমার বেশি পছন্দ?", slotValues: { A: "working early", B: "working late" }, topicArea: "work" },
        { en: "Which one do you like better, texting or calling?", bn: "টেক্সট করা আর কল করার মধ্যে কোনটা তোমার বেশি পছন্দ?", slotValues: { A: "texting", B: "calling" }, topicArea: "relationships" },
      ],
      formality: "casual",
      difficulty: "beginner",
    },
  ],
};
