import { PatternCategory } from "@/types/pattern";

export const categoryG7: PatternCategory = {
  id: "G7",
  slug: "asking-about-quantity-amount",
  name: "Asking About Quantity & Amount",
  name_bn: "পরিমাণ সম্পর্কে জিজ্ঞাসা",
  description:
    "Learn to ask about quantity, amount, cost, and number using how much and how many.",
  description_bn:
    "how much এবং how many ব্যবহার করে পরিমাণ, পরিমাণ, খরচ এবং সংখ্যা সম্পর্কে জিজ্ঞাসা করতে শিখুন।",
  icon: "🔢",
  group: "G",
  groupName: "All Question Types",
  groupName_bn: "সকল প্রশ্নের ধরন",
  difficulty: "intermediate",
  patterns: [
    {
      id: "G7.1",
      formula: "How much does [THING] cost?",
      formula_bn: "[জিনিসের] দাম কত?",
      patternName: "Asking About Price",
      patternName_bn: "দাম সম্পর্কে জিজ্ঞাসা",
      slots: [
        {
          name: "THING",
          description: "A noun or noun phrase for an item or service",
          description_bn: "একটি পণ্য বা পরিষেবার জন্য বিশেষ্য বা বিশেষ্য পদবন্ধ",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["this shirt", "a round trip ticket", "the meal"],
        },
      ],
      examples: [
        {
          en: "How much does this shirt cost?",
          bn: "এই শার্টের দাম কত?",
          slotValues: { THING: "this shirt" },
          topicArea: "shopping",
        },
        {
          en: "How much does a round trip ticket cost?",
          bn: "যাওয়া-আসার টিকিটের দাম কত?",
          slotValues: { THING: "a round trip ticket" },
          topicArea: "travel",
        },
        {
          en: "How much does the meal cost?",
          bn: "খাবারের দাম কত?",
          slotValues: { THING: "the meal" },
          topicArea: "food",
        },
        {
          en: "How much does a cup of coffee cost here?",
          bn: "এখানে এক কাপ কফির দাম কত?",
          slotValues: { THING: "a cup of coffee" },
          topicArea: "food",
        },
        {
          en: "How much does the course cost?",
          bn: "কোর্সের দাম কত?",
          slotValues: { THING: "the course" },
          topicArea: "education",
        },
        {
          en: "How much does a consultation cost?",
          bn: "একটি পরামর্শের দাম কত?",
          slotValues: { THING: "a consultation" },
          topicArea: "health",
        },
        {
          en: "How much does the monthly subscription cost?",
          bn: "মাসিক সাবস্ক্রিপশনের দাম কত?",
          slotValues: { THING: "the monthly subscription" },
          topicArea: "daily_life",
        },
        {
          en: "How much does a taxi to the airport cost?",
          bn: "বিমানবন্দরে ট্যাক্সির দাম কত?",
          slotValues: { THING: "a taxi to the airport" },
          topicArea: "travel",
        },
        {
          en: "How much does this pair of shoes cost?",
          bn: "এই জোড়া জুতোর দাম কত?",
          slotValues: { THING: "this pair of shoes" },
          topicArea: "shopping",
        },
        {
          en: "How much does the repair cost?",
          bn: "মেরামতের খরচ কত?",
          slotValues: { THING: "the repair" },
          topicArea: "daily_life",
        },
        {
          en: "How much does overtime pay?",
          bn: "ওভারটাইমে কত টাকা পাওয়া যায়?",
          slotValues: { THING: "overtime" },
          topicArea: "work",
        },
        {
          en: "How much does a gym membership cost?",
          bn: "জিম মেম্বারশিপের দাম কত?",
          slotValues: { THING: "a gym membership" },
          topicArea: "health",
        },
        {
          en: "How much does the delivery cost?",
          bn: "ডেলিভারির খরচ কত?",
          slotValues: { THING: "the delivery" },
          topicArea: "shopping",
        },
        {
          en: "How much does a wedding typically cost?",
          bn: "একটি বিয়েতে সাধারণত কত খরচ হয়?",
          slotValues: { THING: "a wedding typically" },
          topicArea: "relationships",
        },
        {
          en: "How much does the textbook cost?",
          bn: "পাঠ্যবইয়ের দাম কত?",
          slotValues: { THING: "the textbook" },
          topicArea: "education",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'How much does ... cost?' is the standard way to ask about price. You can also say 'How much is this?'",
      usageNote_bn:
        "'How much does ... cost?' দাম জিজ্ঞাসা করার আদর্শ উপায়। আপনি 'How much is this?'-ও বলতে পারেন।",
    },
    {
      id: "G7.2",
      formula: "How many [THINGS] do you have?",
      formula_bn: "তোমার কতগুলো [জিনিস] আছে?",
      patternName: "Asking About Countable Quantity",
      patternName_bn: "গণনাযোগ্য পরিমাণ জিজ্ঞাসা",
      slots: [
        {
          name: "THINGS",
          description: "A countable plural noun or noun phrase",
          description_bn: "একটি গণনাযোগ্য বহুবচন বিশেষ্য বা বিশেষ্য পদবন্ধ",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["siblings", "books", "employees"],
        },
      ],
      examples: [
        {
          en: "How many siblings do you have?",
          bn: "তোমার কয়জন ভাইবোন আছে?",
          slotValues: { THINGS: "siblings" },
          topicArea: "relationships",
        },
        {
          en: "How many books do you have?",
          bn: "তোমার কতগুলো বই আছে?",
          slotValues: { THINGS: "books" },
          topicArea: "education",
        },
        {
          en: "How many employees do you have?",
          bn: "তোমার কতজন কর্মচারী আছে?",
          slotValues: { THINGS: "employees" },
          topicArea: "work",
        },
        {
          en: "How many bags do you have?",
          bn: "তোমার কতগুলো ব্যাগ আছে?",
          slotValues: { THINGS: "bags" },
          topicArea: "travel",
        },
        {
          en: "How many pairs of shoes do you have?",
          bn: "তোমার কত জোড়া জুতো আছে?",
          slotValues: { THINGS: "pairs of shoes" },
          topicArea: "shopping",
        },
        {
          en: "How many pets do you have?",
          bn: "তোমার কতগুলো পোষা প্রাণী আছে?",
          slotValues: { THINGS: "pets" },
          topicArea: "daily_life",
        },
        {
          en: "How many classes do you have today?",
          bn: "আজ তোমার কতগুলো ক্লাস আছে?",
          slotValues: { THINGS: "classes" },
          topicArea: "education",
        },
        {
          en: "How many cups of coffee do you have a day?",
          bn: "তুমি দিনে কত কাপ কফি খাও?",
          slotValues: { THINGS: "cups of coffee" },
          topicArea: "food",
        },
        {
          en: "How many close friends do you have?",
          bn: "তোমার কয়জন ঘনিষ্ঠ বন্ধু আছে?",
          slotValues: { THINGS: "close friends" },
          topicArea: "relationships",
        },
        {
          en: "How many rooms does your house have?",
          bn: "তোমার বাড়িতে কতগুলো ঘর আছে?",
          slotValues: { THINGS: "rooms" },
          topicArea: "daily_life",
        },
        {
          en: "How many languages do you speak?",
          bn: "তুমি কয়টা ভাষা বলতে পারো?",
          slotValues: { THINGS: "languages" },
          topicArea: "education",
        },
        {
          en: "How many meetings do you have this week?",
          bn: "এই সপ্তাহে তোমার কতগুলো মিটিং আছে?",
          slotValues: { THINGS: "meetings" },
          topicArea: "work",
        },
        {
          en: "How many suitcases do you have?",
          bn: "তোমার কতগুলো সুটকেস আছে?",
          slotValues: { THINGS: "suitcases" },
          topicArea: "travel",
        },
        {
          en: "How many medicines do you take daily?",
          bn: "তুমি প্রতিদিন কতগুলো ওষুধ খাও?",
          slotValues: { THINGS: "medicines" },
          topicArea: "health",
        },
        {
          en: "How many items are in your cart?",
          bn: "তোমার কার্টে কতগুলো জিনিস আছে?",
          slotValues: { THINGS: "items" },
          topicArea: "shopping",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'How many' is used with countable nouns (plural). Do not use it with uncountable nouns like water or money.",
      usageNote_bn:
        "'How many' গণনাযোগ্য বিশেষ্য (বহুবচন) এর সাথে ব্যবহৃত হয়। water বা money এর মতো অগণনযোগ্য বিশেষ্যের সাথে ব্যবহার করবেন না।",
    },
    {
      id: "G7.3",
      formula: "How much [UNCOUNTABLE] do you need?",
      formula_bn: "তোমার কতটুকু [অগণনযোগ্য] দরকার?",
      patternName: "Asking About Uncountable Quantity",
      patternName_bn: "অগণনযোগ্য পরিমাণ জিজ্ঞাসা",
      slots: [
        {
          name: "UNCOUNTABLE",
          description: "An uncountable noun like water, time, money, etc.",
          description_bn: "একটি অগণনযোগ্য বিশেষ্য যেমন পানি, সময়, টাকা ইত্যাদি",
          acceptedTypes: ["noun"],
          examples: ["water", "time", "money"],
        },
      ],
      examples: [
        {
          en: "How much water do you need?",
          bn: "তোমার কতটুকু পানি দরকার?",
          slotValues: { UNCOUNTABLE: "water" },
          topicArea: "daily_life",
        },
        {
          en: "How much time do you need?",
          bn: "তোমার কতটুকু সময় দরকার?",
          slotValues: { UNCOUNTABLE: "time" },
          topicArea: "work",
        },
        {
          en: "How much money do you need?",
          bn: "তোমার কত টাকা দরকার?",
          slotValues: { UNCOUNTABLE: "money" },
          topicArea: "shopping",
        },
        {
          en: "How much sugar do you need?",
          bn: "তোমার কতটুকু চিনি দরকার?",
          slotValues: { UNCOUNTABLE: "sugar" },
          topicArea: "food",
        },
        {
          en: "How much sleep do you need?",
          bn: "তোমার কতটুকু ঘুম দরকার?",
          slotValues: { UNCOUNTABLE: "sleep" },
          topicArea: "health",
        },
        {
          en: "How much space do you need?",
          bn: "তোমার কতটুকু জায়গা দরকার?",
          slotValues: { UNCOUNTABLE: "space" },
          topicArea: "daily_life",
        },
        {
          en: "How much luggage do you need to bring?",
          bn: "তোমার কতটুকু মালপত্র আনতে হবে?",
          slotValues: { UNCOUNTABLE: "luggage" },
          topicArea: "travel",
        },
        {
          en: "How much experience do you need for this job?",
          bn: "এই চাকরির জন্য কতটুকু অভিজ্ঞতা দরকার?",
          slotValues: { UNCOUNTABLE: "experience" },
          topicArea: "work",
        },
        {
          en: "How much rice do you need?",
          bn: "তোমার কতটুকু চাল দরকার?",
          slotValues: { UNCOUNTABLE: "rice" },
          topicArea: "food",
        },
        {
          en: "How much patience do you need to learn this?",
          bn: "এটা শিখতে কতটুকু ধৈর্য দরকার?",
          slotValues: { UNCOUNTABLE: "patience" },
          topicArea: "education",
        },
        {
          en: "How much milk do you need?",
          bn: "তোমার কতটুকু দুধ দরকার?",
          slotValues: { UNCOUNTABLE: "milk" },
          topicArea: "food",
        },
        {
          en: "How much rest do you need?",
          bn: "তোমার কতটুকু বিশ্রাম দরকার?",
          slotValues: { UNCOUNTABLE: "rest" },
          topicArea: "health",
        },
        {
          en: "How much fuel do you need for the trip?",
          bn: "ভ্রমণের জন্য কতটুকু জ্বালানি দরকার?",
          slotValues: { UNCOUNTABLE: "fuel" },
          topicArea: "travel",
        },
        {
          en: "How much effort do you need to put in?",
          bn: "তোমার কতটুকু প্রচেষ্টা দিতে হবে?",
          slotValues: { UNCOUNTABLE: "effort" },
          topicArea: "education",
        },
        {
          en: "How much love do you need to give a relationship?",
          bn: "একটি সম্পর্কে কতটুকু ভালোবাসা দিতে হয়?",
          slotValues: { UNCOUNTABLE: "love" },
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'How much' is used with uncountable nouns. These are things you cannot count individually.",
      usageNote_bn:
        "'How much' অগণনযোগ্য বিশেষ্যের সাথে ব্যবহৃত হয়। এগুলো এমন জিনিস যা আলাদাভাবে গণনা করা যায় না।",
    },
    {
      id: "G7.4",
      formula: "How many [THINGS] are there in [PLACE]?",
      formula_bn: "[স্থানে] কতগুলো [জিনিস] আছে?",
      patternName: "Existence Quantity Question",
      patternName_bn: "অস্তিত্ব পরিমাণ প্রশ্ন",
      slots: [
        {
          name: "THINGS",
          description: "A countable plural noun",
          description_bn: "একটি গণনাযোগ্য বহুবচন বিশেষ্য",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["students", "hospitals", "restaurants"],
        },
        {
          name: "PLACE",
          description: "A location or context",
          description_bn: "একটি অবস্থান বা প্রসঙ্গ",
          acceptedTypes: ["place", "noun_phrase"],
          examples: ["your class", "this city", "the building"],
        },
      ],
      examples: [
        {
          en: "How many students are there in your class?",
          bn: "তোমার ক্লাসে কতজন ছাত্র আছে?",
          slotValues: { THINGS: "students", PLACE: "your class" },
          topicArea: "education",
        },
        {
          en: "How many hospitals are there in this city?",
          bn: "এই শহরে কতগুলো হাসপাতাল আছে?",
          slotValues: { THINGS: "hospitals", PLACE: "this city" },
          topicArea: "health",
        },
        {
          en: "How many restaurants are there in this area?",
          bn: "এই এলাকায় কতগুলো রেস্টুরেন্ট আছে?",
          slotValues: { THINGS: "restaurants", PLACE: "this area" },
          topicArea: "food",
        },
        {
          en: "How many floors are there in the building?",
          bn: "বিল্ডিংয়ে কতগুলো তলা আছে?",
          slotValues: { THINGS: "floors", PLACE: "the building" },
          topicArea: "daily_life",
        },
        {
          en: "How many people are there in your team?",
          bn: "তোমার টিমে কতজন মানুষ আছে?",
          slotValues: { THINGS: "people", PLACE: "your team" },
          topicArea: "work",
        },
        {
          en: "How many gates are there at the airport?",
          bn: "বিমানবন্দরে কতগুলো গেট আছে?",
          slotValues: { THINGS: "gates", PLACE: "the airport" },
          topicArea: "travel",
        },
        {
          en: "How many shops are there in the mall?",
          bn: "মলে কতগুলো দোকান আছে?",
          slotValues: { THINGS: "shops", PLACE: "the mall" },
          topicArea: "shopping",
        },
        {
          en: "How many members are there in your family?",
          bn: "তোমার পরিবারে কতজন সদস্য আছে?",
          slotValues: { THINGS: "members", PLACE: "your family" },
          topicArea: "relationships",
        },
        {
          en: "How many chapters are there in this book?",
          bn: "এই বইয়ে কতগুলো অধ্যায় আছে?",
          slotValues: { THINGS: "chapters", PLACE: "this book" },
          topicArea: "education",
        },
        {
          en: "How many bedrooms are there in the hotel?",
          bn: "হোটেলে কতগুলো শোবার ঘর আছে?",
          slotValues: { THINGS: "bedrooms", PLACE: "the hotel" },
          topicArea: "travel",
        },
        {
          en: "How many departments are there in this company?",
          bn: "এই কোম্পানিতে কতগুলো বিভাগ আছে?",
          slotValues: { THINGS: "departments", PLACE: "this company" },
          topicArea: "work",
        },
        {
          en: "How many items are there on the menu?",
          bn: "মেনুতে কতগুলো আইটেম আছে?",
          slotValues: { THINGS: "items", PLACE: "the menu" },
          topicArea: "food",
        },
        {
          en: "How many clinics are there in the neighborhood?",
          bn: "পাড়ায় কতগুলো ক্লিনিক আছে?",
          slotValues: { THINGS: "clinics", PLACE: "the neighborhood" },
          topicArea: "health",
        },
        {
          en: "How many bathrooms are there in the house?",
          bn: "বাড়িতে কতগুলো বাথরুম আছে?",
          slotValues: { THINGS: "bathrooms", PLACE: "the house" },
          topicArea: "daily_life",
        },
        {
          en: "How many guests are there at the wedding?",
          bn: "বিয়েতে কতজন অতিথি আছে?",
          slotValues: { THINGS: "guests", PLACE: "the wedding" },
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'How many ... are there' asks about the number of things that exist in a place or context.",
      usageNote_bn:
        "'How many ... are there' কোনো স্থান বা প্রসঙ্গে বিদ্যমান জিনিসের সংখ্যা জিজ্ঞাসা করে।",
    },
    {
      id: "G7.5",
      formula: "How much [THING] is left?",
      formula_bn: "কতটুকু [জিনিস] বাকি আছে?",
      patternName: "Remaining Amount Question",
      patternName_bn: "অবশিষ্ট পরিমাণ প্রশ্ন",
      slots: [
        {
          name: "THING",
          description: "An uncountable noun or noun phrase for something remaining",
          description_bn: "অবশিষ্ট কিছুর জন্য একটি অগণনযোগ্য বিশেষ্য বা বিশেষ্য পদবন্ধ",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["time", "food", "battery"],
        },
      ],
      examples: [
        {
          en: "How much time is left?",
          bn: "কতটুকু সময় বাকি আছে?",
          slotValues: { THING: "time" },
          topicArea: "daily_life",
        },
        {
          en: "How much food is left?",
          bn: "কতটুকু খাবার বাকি আছে?",
          slotValues: { THING: "food" },
          topicArea: "food",
        },
        {
          en: "How much battery is left?",
          bn: "কতটুকু ব্যাটারি বাকি আছে?",
          slotValues: { THING: "battery" },
          topicArea: "daily_life",
        },
        {
          en: "How much fuel is left in the tank?",
          bn: "ট্যাঙ্কে কতটুকু জ্বালানি বাকি আছে?",
          slotValues: { THING: "fuel" },
          topicArea: "travel",
        },
        {
          en: "How much work is left to do?",
          bn: "কতটুকু কাজ বাকি আছে?",
          slotValues: { THING: "work" },
          topicArea: "work",
        },
        {
          en: "How much money is left in the budget?",
          bn: "বাজেটে কত টাকা বাকি আছে?",
          slotValues: { THING: "money" },
          topicArea: "work",
        },
        {
          en: "How much milk is left?",
          bn: "কতটুকু দুধ বাকি আছে?",
          slotValues: { THING: "milk" },
          topicArea: "food",
        },
        {
          en: "How much vacation time is left?",
          bn: "কতটুকু ছুটির সময় বাকি আছে?",
          slotValues: { THING: "vacation time" },
          topicArea: "travel",
        },
        {
          en: "How much paint is left?",
          bn: "কতটুকু রং বাকি আছে?",
          slotValues: { THING: "paint" },
          topicArea: "daily_life",
        },
        {
          en: "How much of the course is left?",
          bn: "কোর্সের কতটুকু বাকি আছে?",
          slotValues: { THING: "of the course" },
          topicArea: "education",
        },
        {
          en: "How much medicine is left?",
          bn: "কতটুকু ওষুধ বাকি আছে?",
          slotValues: { THING: "medicine" },
          topicArea: "health",
        },
        {
          en: "How much stock is left?",
          bn: "কতটুকু স্টক বাকি আছে?",
          slotValues: { THING: "stock" },
          topicArea: "shopping",
        },
        {
          en: "How much of the project is left?",
          bn: "প্রজেক্টের কতটুকু বাকি আছে?",
          slotValues: { THING: "of the project" },
          topicArea: "work",
        },
        {
          en: "How much storage is left on your phone?",
          bn: "তোমার ফোনে কতটুকু স্টোরেজ বাকি আছে?",
          slotValues: { THING: "storage" },
          topicArea: "daily_life",
        },
        {
          en: "How much patience is left in you?",
          bn: "তোমার কতটুকু ধৈর্য বাকি আছে?",
          slotValues: { THING: "patience" },
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'How much ... is left' asks about the remaining quantity of something. Very common in daily situations.",
      usageNote_bn:
        "'How much ... is left' কিছুর অবশিষ্ট পরিমাণ সম্পর্কে জিজ্ঞাসা করে। দৈনন্দিন পরিস্থিতিতে খুবই সাধারণ।",
    },
  ],
};
