import { PatternCategory } from "@/types/pattern";

export const categoryG8: PatternCategory = {
  id: "G8",
  slug: "asking-about-ability-knowledge",
  name: "Asking About Ability & Knowledge",
  name_bn: "সক্ষমতা ও জ্ঞান সম্পর্কে জিজ্ঞাসা",
  description:
    "Learn to ask about someone's ability, knowledge, and skills.",
  description_bn:
    "কারো সক্ষমতা, জ্ঞান এবং দক্ষতা সম্পর্কে জিজ্ঞাসা করতে শিখুন।",
  icon: "🧠",
  group: "G",
  groupName: "All Question Types",
  groupName_bn: "সকল প্রশ্নের ধরন",
  difficulty: "intermediate",
  patterns: [
    {
      id: "G8.1",
      formula: "Do you know how to [ACTION]?",
      formula_bn: "তুমি কি জানো কিভাবে [কাজ] করতে হয়?",
      patternName: "Knowledge/Skill Question",
      patternName_bn: "জ্ঞান/দক্ষতা প্রশ্ন",
      slots: [
        {
          name: "ACTION",
          description: "A base form verb or verb phrase for a skill or process",
          description_bn: "দক্ষতা বা প্রক্রিয়ার জন্য মূল ক্রিয়া বা ক্রিয়া পদবন্ধ",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["cook", "drive", "use this software"],
        },
      ],
      examples: [
        {
          en: "Do you know how to cook?",
          bn: "তুমি কি জানো কিভাবে রান্না করতে হয়?",
          slotValues: { ACTION: "cook" },
          topicArea: "food",
        },
        {
          en: "Do you know how to drive?",
          bn: "তুমি কি জানো কিভাবে গাড়ি চালাতে হয়?",
          slotValues: { ACTION: "drive" },
          topicArea: "travel",
        },
        {
          en: "Do you know how to use this software?",
          bn: "তুমি কি জানো কিভাবে এই সফটওয়্যার ব্যবহার করতে হয়?",
          slotValues: { ACTION: "use this software" },
          topicArea: "work",
        },
        {
          en: "Do you know how to swim?",
          bn: "তুমি কি জানো কিভাবে সাঁতার কাটতে হয়?",
          slotValues: { ACTION: "swim" },
          topicArea: "health",
        },
        {
          en: "Do you know how to play chess?",
          bn: "তুমি কি জানো কিভাবে দাবা খেলতে হয়?",
          slotValues: { ACTION: "play chess" },
          topicArea: "daily_life",
        },
        {
          en: "Do you know how to make biryani?",
          bn: "তুমি কি জানো কিভাবে বিরিয়ানি বানাতে হয়?",
          slotValues: { ACTION: "make biryani" },
          topicArea: "food",
        },
        {
          en: "Do you know how to read a map?",
          bn: "তুমি কি জানো কিভাবে মানচিত্র পড়তে হয়?",
          slotValues: { ACTION: "read a map" },
          topicArea: "travel",
        },
        {
          en: "Do you know how to write a resume?",
          bn: "তুমি কি জানো কিভাবে জীবনবৃত্তান্ত লিখতে হয়?",
          slotValues: { ACTION: "write a resume" },
          topicArea: "work",
        },
        {
          en: "Do you know how to solve this equation?",
          bn: "তুমি কি জানো কিভাবে এই সমীকরণ সমাধান করতে হয়?",
          slotValues: { ACTION: "solve this equation" },
          topicArea: "education",
        },
        {
          en: "Do you know how to do CPR?",
          bn: "তুমি কি জানো কিভাবে সিপিআর করতে হয়?",
          slotValues: { ACTION: "do CPR" },
          topicArea: "health",
        },
        {
          en: "Do you know how to change a tire?",
          bn: "তুমি কি জানো কিভাবে টায়ার পরিবর্তন করতে হয়?",
          slotValues: { ACTION: "change a tire" },
          topicArea: "daily_life",
        },
        {
          en: "Do you know how to bargain here?",
          bn: "তুমি কি জানো কিভাবে এখানে দরদাম করতে হয়?",
          slotValues: { ACTION: "bargain here" },
          topicArea: "shopping",
        },
        {
          en: "Do you know how to tie a tie?",
          bn: "তুমি কি জানো কিভাবে টাই বাঁধতে হয়?",
          slotValues: { ACTION: "tie a tie" },
          topicArea: "daily_life",
        },
        {
          en: "Do you know how to speak French?",
          bn: "তুমি কি জানো কিভাবে ফরাসি বলতে হয়?",
          slotValues: { ACTION: "speak French" },
          topicArea: "education",
        },
        {
          en: "Do you know how to comfort someone who is sad?",
          bn: "তুমি কি জানো কিভাবে কাউকে দুঃখে সান্ত্বনা দিতে হয়?",
          slotValues: { ACTION: "comfort someone who is sad" },
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Do you know how to' asks about knowledge of a process or skill. It is more about knowing than ability.",
      usageNote_bn:
        "'Do you know how to' প্রক্রিয়া বা দক্ষতার জ্ঞান সম্পর্কে জিজ্ঞাসা করে। এটি সক্ষমতার চেয়ে জানার বিষয়ে বেশি।",
    },
    {
      id: "G8.2",
      formula: "Can you [ACTION]?",
      formula_bn: "তুমি কি [কাজ] করতে পারো?",
      patternName: "Ability Question",
      patternName_bn: "সক্ষমতা প্রশ্ন",
      slots: [
        {
          name: "ACTION",
          description: "A base form verb or verb phrase about an ability",
          description_bn: "সক্ষমতা সম্পর্কে মূল ক্রিয়া বা ক্রিয়া পদবন্ধ",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["speak Japanese", "play the piano", "lift heavy things"],
        },
      ],
      examples: [
        {
          en: "Can you speak Japanese?",
          bn: "তুমি কি জাপানি বলতে পারো?",
          slotValues: { ACTION: "speak Japanese" },
          topicArea: "education",
        },
        {
          en: "Can you play the piano?",
          bn: "তুমি কি পিয়ানো বাজাতে পারো?",
          slotValues: { ACTION: "play the piano" },
          topicArea: "daily_life",
        },
        {
          en: "Can you lift heavy things?",
          bn: "তুমি কি ভারী জিনিস তুলতে পারো?",
          slotValues: { ACTION: "lift heavy things" },
          topicArea: "health",
        },
        {
          en: "Can you ride a bicycle?",
          bn: "তুমি কি সাইকেল চালাতে পারো?",
          slotValues: { ACTION: "ride a bicycle" },
          topicArea: "travel",
        },
        {
          en: "Can you type fast?",
          bn: "তুমি কি দ্রুত টাইপ করতে পারো?",
          slotValues: { ACTION: "type fast" },
          topicArea: "work",
        },
        {
          en: "Can you taste the difference?",
          bn: "তুমি কি পার্থক্য বুঝতে পারো?",
          slotValues: { ACTION: "taste the difference" },
          topicArea: "food",
        },
        {
          en: "Can you run a marathon?",
          bn: "তুমি কি ম্যারাথন দৌড়াতে পারো?",
          slotValues: { ACTION: "run a marathon" },
          topicArea: "health",
        },
        {
          en: "Can you understand this accent?",
          bn: "তুমি কি এই উচ্চারণ বুঝতে পারো?",
          slotValues: { ACTION: "understand this accent" },
          topicArea: "education",
        },
        {
          en: "Can you work under pressure?",
          bn: "তুমি কি চাপের মধ্যে কাজ করতে পারো?",
          slotValues: { ACTION: "work under pressure" },
          topicArea: "work",
        },
        {
          en: "Can you see the sign from here?",
          bn: "তুমি কি এখান থেকে সাইনটা দেখতে পাও?",
          slotValues: { ACTION: "see the sign from here" },
          topicArea: "travel",
        },
        {
          en: "Can you carry all those bags?",
          bn: "তুমি কি ওই সব ব্যাগ বহন করতে পারো?",
          slotValues: { ACTION: "carry all those bags" },
          topicArea: "shopping",
        },
        {
          en: "Can you forgive and forget?",
          bn: "তুমি কি ক্ষমা করতে ও ভুলে যেতে পারো?",
          slotValues: { ACTION: "forgive and forget" },
          topicArea: "relationships",
        },
        {
          en: "Can you make it to the meeting?",
          bn: "তুমি কি মিটিংয়ে আসতে পারবে?",
          slotValues: { ACTION: "make it to the meeting" },
          topicArea: "work",
        },
        {
          en: "Can you cook without a recipe?",
          bn: "তুমি কি রেসিপি ছাড়া রান্না করতে পারো?",
          slotValues: { ACTION: "cook without a recipe" },
          topicArea: "food",
        },
        {
          en: "Can you touch your toes?",
          bn: "তুমি কি তোমার পায়ের আঙুল ছুঁতে পারো?",
          slotValues: { ACTION: "touch your toes" },
          topicArea: "health",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Can you' asks about present ability. It can also be used for requests depending on context.",
      usageNote_bn:
        "'Can you' বর্তমান সক্ষমতা সম্পর্কে জিজ্ঞাসা করে। প্রসঙ্গ অনুযায়ী এটি অনুরোধের জন্যও ব্যবহার করা যায়।",
    },
    {
      id: "G8.3",
      formula: "Are you able to [ACTION]?",
      formula_bn: "তুমি কি [কাজ] করতে সক্ষম?",
      patternName: "Formal Ability Question",
      patternName_bn: "আনুষ্ঠানিক সক্ষমতা প্রশ্ন",
      slots: [
        {
          name: "ACTION",
          description: "A base form verb or verb phrase about ability or capacity",
          description_bn: "সক্ষমতা বা ক্ষমতা সম্পর্কে মূল ক্রিয়া বা ক্রিয়া পদবন্ধ",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["attend the meeting", "handle this project", "work nights"],
        },
      ],
      examples: [
        {
          en: "Are you able to attend the meeting?",
          bn: "তুমি কি মিটিংয়ে যোগ দিতে সক্ষম?",
          slotValues: { ACTION: "attend the meeting" },
          topicArea: "work",
        },
        {
          en: "Are you able to handle this project alone?",
          bn: "তুমি কি একা এই প্রজেক্ট সামলাতে সক্ষম?",
          slotValues: { ACTION: "handle this project alone" },
          topicArea: "work",
        },
        {
          en: "Are you able to work nights?",
          bn: "তুমি কি রাতে কাজ করতে সক্ষম?",
          slotValues: { ACTION: "work nights" },
          topicArea: "work",
        },
        {
          en: "Are you able to walk without pain?",
          bn: "তুমি কি ব্যথা ছাড়া হাঁটতে সক্ষম?",
          slotValues: { ACTION: "walk without pain" },
          topicArea: "health",
        },
        {
          en: "Are you able to understand the textbook?",
          bn: "তুমি কি পাঠ্যবই বুঝতে সক্ষম?",
          slotValues: { ACTION: "understand the textbook" },
          topicArea: "education",
        },
        {
          en: "Are you able to travel on short notice?",
          bn: "তুমি কি অল্প সময়ের নোটিসে ভ্রমণ করতে সক্ষম?",
          slotValues: { ACTION: "travel on short notice" },
          topicArea: "travel",
        },
        {
          en: "Are you able to finish by the deadline?",
          bn: "তুমি কি শেষ তারিখের মধ্যে শেষ করতে সক্ষম?",
          slotValues: { ACTION: "finish by the deadline" },
          topicArea: "work",
        },
        {
          en: "Are you able to eat solid food now?",
          bn: "তুমি কি এখন শক্ত খাবার খেতে সক্ষম?",
          slotValues: { ACTION: "eat solid food now" },
          topicArea: "health",
        },
        {
          en: "Are you able to prepare a presentation?",
          bn: "তুমি কি একটি উপস্থাপনা প্রস্তুত করতে সক্ষম?",
          slotValues: { ACTION: "prepare a presentation" },
          topicArea: "education",
        },
        {
          en: "Are you able to afford this?",
          bn: "তুমি কি এটা কিনতে সক্ষম?",
          slotValues: { ACTION: "afford this" },
          topicArea: "shopping",
        },
        {
          en: "Are you able to drive long distances?",
          bn: "তুমি কি দীর্ঘ দূরত্ব গাড়ি চালাতে সক্ষম?",
          slotValues: { ACTION: "drive long distances" },
          topicArea: "travel",
        },
        {
          en: "Are you able to cook for a large group?",
          bn: "তুমি কি বড় দলের জন্য রান্না করতে সক্ষম?",
          slotValues: { ACTION: "cook for a large group" },
          topicArea: "food",
        },
        {
          en: "Are you able to keep this confidential?",
          bn: "তুমি কি এটা গোপন রাখতে সক্ষম?",
          slotValues: { ACTION: "keep this confidential" },
          topicArea: "relationships",
        },
        {
          en: "Are you able to exercise regularly?",
          bn: "তুমি কি নিয়মিত ব্যায়াম করতে সক্ষম?",
          slotValues: { ACTION: "exercise regularly" },
          topicArea: "health",
        },
        {
          en: "Are you able to manage your time well?",
          bn: "তুমি কি তোমার সময় ভালোভাবে ব্যবস্থাপনা করতে সক্ষম?",
          slotValues: { ACTION: "manage your time well" },
          topicArea: "daily_life",
        },
      ],
      formality: "formal",
      difficulty: "intermediate",
      usageNote:
        "'Are you able to' is more formal than 'can you'. Often used in professional or medical contexts.",
      usageNote_bn:
        "'Are you able to' 'can you'-এর চেয়ে বেশি আনুষ্ঠানিক। পেশাদার বা চিকিৎসা প্রসঙ্গে প্রায়ই ব্যবহৃত।",
    },
    {
      id: "G8.4",
      formula: "Have you ever learned to [ACTION]?",
      formula_bn: "তুমি কি কখনো [কাজ] করতে শিখেছো?",
      patternName: "Past Learning Experience Question",
      patternName_bn: "অতীত শেখার অভিজ্ঞতা প্রশ্ন",
      slots: [
        {
          name: "ACTION",
          description: "A base form verb or verb phrase about a skill",
          description_bn: "দক্ষতা সম্পর্কে মূল ক্রিয়া বা ক্রিয়া পদবন্ধ",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["play an instrument", "cook Thai food", "code"],
        },
      ],
      examples: [
        {
          en: "Have you ever learned to play an instrument?",
          bn: "তুমি কি কখনো বাদ্যযন্ত্র বাজাতে শিখেছো?",
          slotValues: { ACTION: "play an instrument" },
          topicArea: "daily_life",
        },
        {
          en: "Have you ever learned to cook Thai food?",
          bn: "তুমি কি কখনো থাই খাবার রান্না করতে শিখেছো?",
          slotValues: { ACTION: "cook Thai food" },
          topicArea: "food",
        },
        {
          en: "Have you ever learned to code?",
          bn: "তুমি কি কখনো কোডিং শিখেছো?",
          slotValues: { ACTION: "code" },
          topicArea: "education",
        },
        {
          en: "Have you ever learned to ski?",
          bn: "তুমি কি কখনো স্কি করতে শিখেছো?",
          slotValues: { ACTION: "ski" },
          topicArea: "travel",
        },
        {
          en: "Have you ever learned to do yoga?",
          bn: "তুমি কি কখনো যোগব্যায়াম করতে শিখেছো?",
          slotValues: { ACTION: "do yoga" },
          topicArea: "health",
        },
        {
          en: "Have you ever learned to negotiate?",
          bn: "তুমি কি কখনো দরকষাকষি করতে শিখেছো?",
          slotValues: { ACTION: "negotiate" },
          topicArea: "work",
        },
        {
          en: "Have you ever learned to sew?",
          bn: "তুমি কি কখনো সেলাই করতে শিখেছো?",
          slotValues: { ACTION: "sew" },
          topicArea: "daily_life",
        },
        {
          en: "Have you ever learned to bake bread?",
          bn: "তুমি কি কখনো রুটি বেক করতে শিখেছো?",
          slotValues: { ACTION: "bake bread" },
          topicArea: "food",
        },
        {
          en: "Have you ever learned to speak another language?",
          bn: "তুমি কি কখনো অন্য ভাষায় কথা বলতে শিখেছো?",
          slotValues: { ACTION: "speak another language" },
          topicArea: "education",
        },
        {
          en: "Have you ever learned to navigate by the stars?",
          bn: "তুমি কি কখনো তারা দেখে পথ চলতে শিখেছো?",
          slotValues: { ACTION: "navigate by the stars" },
          topicArea: "travel",
        },
        {
          en: "Have you ever learned to give first aid?",
          bn: "তুমি কি কখনো প্রাথমিক চিকিৎসা দিতে শিখেছো?",
          slotValues: { ACTION: "give first aid" },
          topicArea: "health",
        },
        {
          en: "Have you ever learned to use a spreadsheet?",
          bn: "তুমি কি কখনো স্প্রেডশিট ব্যবহার করতে শিখেছো?",
          slotValues: { ACTION: "use a spreadsheet" },
          topicArea: "work",
        },
        {
          en: "Have you ever learned to haggle at a market?",
          bn: "তুমি কি কখনো বাজারে দরদাম করতে শিখেছো?",
          slotValues: { ACTION: "haggle at a market" },
          topicArea: "shopping",
        },
        {
          en: "Have you ever learned to dance?",
          bn: "তুমি কি কখনো নাচতে শিখেছো?",
          slotValues: { ACTION: "dance" },
          topicArea: "daily_life",
        },
        {
          en: "Have you ever learned to resolve conflicts?",
          bn: "তুমি কি কখনো দ্বন্দ্ব সমাধান করতে শিখেছো?",
          slotValues: { ACTION: "resolve conflicts" },
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "This asks about past learning experiences. 'Ever' emphasizes that you are asking about any time in their life.",
      usageNote_bn:
        "এটি অতীতের শেখার অভিজ্ঞতা সম্পর্কে জিজ্ঞাসা করে। 'Ever' জোর দেয় যে আপনি তাদের জীবনের যেকোনো সময়ের কথা জিজ্ঞাসা করছেন।",
    },
    {
      id: "G8.5",
      formula: "Would you be able to [ACTION]?",
      formula_bn: "তুমি কি [কাজ] করতে পারবে?",
      patternName: "Polite Ability/Request Question",
      patternName_bn: "ভদ্র সক্ষমতা/অনুরোধ প্রশ্ন",
      slots: [
        {
          name: "ACTION",
          description: "A base form verb or verb phrase for a hypothetical ability or request",
          description_bn: "অনুমানমূলক সক্ষমতা বা অনুরোধের জন্য মূল ক্রিয়া বা ক্রিয়া পদবন্ধ",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["help me tomorrow", "translate this document", "cover my shift"],
        },
      ],
      examples: [
        {
          en: "Would you be able to help me tomorrow?",
          bn: "তুমি কি আগামীকাল আমাকে সাহায্য করতে পারবে?",
          slotValues: { ACTION: "help me tomorrow" },
          topicArea: "daily_life",
        },
        {
          en: "Would you be able to translate this document?",
          bn: "তুমি কি এই ডকুমেন্টটা অনুবাদ করতে পারবে?",
          slotValues: { ACTION: "translate this document" },
          topicArea: "work",
        },
        {
          en: "Would you be able to cover my shift?",
          bn: "তুমি কি আমার শিফট কভার করতে পারবে?",
          slotValues: { ACTION: "cover my shift" },
          topicArea: "work",
        },
        {
          en: "Would you be able to pick me up from the airport?",
          bn: "তুমি কি আমাকে বিমানবন্দর থেকে নিয়ে আসতে পারবে?",
          slotValues: { ACTION: "pick me up from the airport" },
          topicArea: "travel",
        },
        {
          en: "Would you be able to cook dinner tonight?",
          bn: "তুমি কি আজ রাতে রাতের খাবার রান্না করতে পারবে?",
          slotValues: { ACTION: "cook dinner tonight" },
          topicArea: "food",
        },
        {
          en: "Would you be able to tutor me in math?",
          bn: "তুমি কি আমাকে গণিতে টিউশনি দিতে পারবে?",
          slotValues: { ACTION: "tutor me in math" },
          topicArea: "education",
        },
        {
          en: "Would you be able to drive me to the hospital?",
          bn: "তুমি কি আমাকে হাসপাতালে নিয়ে যেতে পারবে?",
          slotValues: { ACTION: "drive me to the hospital" },
          topicArea: "health",
        },
        {
          en: "Would you be able to lend me some money?",
          bn: "তুমি কি আমাকে কিছু টাকা ধার দিতে পারবে?",
          slotValues: { ACTION: "lend me some money" },
          topicArea: "daily_life",
        },
        {
          en: "Would you be able to recommend a good store?",
          bn: "তুমি কি একটা ভালো দোকান সুপারিশ করতে পারবে?",
          slotValues: { ACTION: "recommend a good store" },
          topicArea: "shopping",
        },
        {
          en: "Would you be able to babysit this weekend?",
          bn: "তুমি কি এই সপ্তাহান্তে বাচ্চা দেখাশোনা করতে পারবে?",
          slotValues: { ACTION: "babysit this weekend" },
          topicArea: "relationships",
        },
        {
          en: "Would you be able to finish this by Monday?",
          bn: "তুমি কি সোমবারের মধ্যে এটা শেষ করতে পারবে?",
          slotValues: { ACTION: "finish this by Monday" },
          topicArea: "work",
        },
        {
          en: "Would you be able to book the restaurant?",
          bn: "তুমি কি রেস্টুরেন্ট বুক করতে পারবে?",
          slotValues: { ACTION: "book the restaurant" },
          topicArea: "food",
        },
        {
          en: "Would you be able to guide us around the city?",
          bn: "তুমি কি শহরে আমাদের ঘুরিয়ে দেখাতে পারবে?",
          slotValues: { ACTION: "guide us around the city" },
          topicArea: "travel",
        },
        {
          en: "Would you be able to proofread my essay?",
          bn: "তুমি কি আমার রচনা পড়ে দেখতে পারবে?",
          slotValues: { ACTION: "proofread my essay" },
          topicArea: "education",
        },
        {
          en: "Would you be able to come to the appointment with me?",
          bn: "তুমি কি আমার সাথে অ্যাপয়েন্টমেন্টে আসতে পারবে?",
          slotValues: { ACTION: "come to the appointment with me" },
          topicArea: "health",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "'Would you be able to' is a very polite way to ask about ability or make a request. More formal than 'can you'.",
      usageNote_bn:
        "'Would you be able to' সক্ষমতা জিজ্ঞাসা বা অনুরোধ করার একটি খুবই ভদ্র উপায়। 'can you'-এর চেয়ে বেশি আনুষ্ঠানিক।",
    },
  ],
};
