import { PatternCategory } from "@/types/pattern";

export const categoryG9: PatternCategory = {
  id: "G9",
  slug: "asking-for-opinions-advice",
  name: "Asking for Opinions & Advice",
  name_bn: "মতামত ও পরামর্শ চাওয়া",
  description:
    "Learn to ask for someone's opinion, thoughts, and advice on various topics.",
  description_bn:
    "বিভিন্ন বিষয়ে কারো মতামত, চিন্তা এবং পরামর্শ চাইতে শিখুন।",
  icon: "💭",
  group: "G",
  groupName: "All Question Types",
  groupName_bn: "সকল প্রশ্নের ধরন",
  difficulty: "intermediate",
  patterns: [
    {
      id: "G9.1",
      formula: "What do you think about [THING]?",
      formula_bn: "[জিনিস] সম্পর্কে তুমি কী মনে করো?",
      patternName: "Asking for Opinion",
      patternName_bn: "মতামত চাওয়া",
      slots: [
        {
          name: "THING",
          description: "A noun, noun phrase, or gerund phrase you want an opinion about",
          description_bn: "একটি বিশেষ্য, বিশেষ্য পদবন্ধ, বা ক্রিয়াবাচক বিশেষ্য যার সম্পর্কে মতামত চান",
          acceptedTypes: ["noun", "noun_phrase", "gerund", "topic"],
          examples: ["this idea", "the new restaurant", "working from home"],
        },
      ],
      examples: [
        { en: "What do you think about this idea?", bn: "এই আইডিয়া সম্পর্কে তুমি কী মনে করো?", slotValues: { THING: "this idea" }, topicArea: "daily_life" },
        { en: "What do you think about the new restaurant?", bn: "নতুন রেস্টুরেন্ট সম্পর্কে তুমি কী মনে করো?", slotValues: { THING: "the new restaurant" }, topicArea: "food" },
        { en: "What do you think about working from home?", bn: "বাড়ি থেকে কাজ করা সম্পর্কে তুমি কী মনে করো?", slotValues: { THING: "working from home" }, topicArea: "work" },
        { en: "What do you think about this outfit?", bn: "এই পোশাক সম্পর্কে তুমি কী মনে করো?", slotValues: { THING: "this outfit" }, topicArea: "shopping" },
        { en: "What do you think about traveling solo?", bn: "একা ভ্রমণ সম্পর্কে তুমি কী মনে করো?", slotValues: { THING: "traveling solo" }, topicArea: "travel" },
        { en: "What do you think about online learning?", bn: "অনলাইন শিক্ষা সম্পর্কে তুমি কী মনে করো?", slotValues: { THING: "online learning" }, topicArea: "education" },
        { en: "What do you think about vegetarian diets?", bn: "নিরামিষ খাদ্যাভ্যাস সম্পর্কে তুমি কী মনে করো?", slotValues: { THING: "vegetarian diets" }, topicArea: "health" },
        { en: "What do you think about long-distance relationships?", bn: "দূরত্বের সম্পর্ক সম্পর্কে তুমি কী মনে করো?", slotValues: { THING: "long-distance relationships" }, topicArea: "relationships" },
        { en: "What do you think about the weather today?", bn: "আজকের আবহাওয়া সম্পর্কে তুমি কী মনে করো?", slotValues: { THING: "the weather today" }, topicArea: "daily_life" },
        { en: "What do you think about this recipe?", bn: "এই রেসিপি সম্পর্কে তুমি কী মনে করো?", slotValues: { THING: "this recipe" }, topicArea: "food" },
        { en: "What do you think about the new policy?", bn: "নতুন নীতি সম্পর্কে তুমি কী মনে করো?", slotValues: { THING: "the new policy" }, topicArea: "work" },
        { en: "What do you think about budget airlines?", bn: "বাজেট এয়ারলাইনস সম্পর্কে তুমি কী মনে করো?", slotValues: { THING: "budget airlines" }, topicArea: "travel" },
        { en: "What do you think about studying abroad?", bn: "বিদেশে পড়াশোনা সম্পর্কে তুমি কী মনে করো?", slotValues: { THING: "studying abroad" }, topicArea: "education" },
        { en: "What do you think about home remedies?", bn: "ঘরোয়া প্রতিকার সম্পর্কে তুমি কী মনে করো?", slotValues: { THING: "home remedies" }, topicArea: "health" },
        { en: "What do you think about this color for the room?", bn: "ঘরের জন্য এই রং সম্পর্কে তুমি কী মনে করো?", slotValues: { THING: "this color for the room" }, topicArea: "shopping" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "The most common way to ask for someone's opinion. Open-ended and conversational.",
      usageNote_bn: "কারো মতামত জানতে চাওয়ার সবচেয়ে সাধারণ উপায়। উন্মুক্ত এবং কথোপকথনমূলক।",
    },
    {
      id: "G9.2",
      formula: "What would you do if [CONDITION]?",
      formula_bn: "[শর্ত] হলে তুমি কী করতে?",
      patternName: "Hypothetical Advice Question",
      patternName_bn: "অনুমানমূলক পরামর্শ প্রশ্ন",
      slots: [
        {
          name: "CONDITION",
          description: "A hypothetical condition or situation",
          description_bn: "একটি অনুমানমূলক শর্ত বা পরিস্থিতি",
          acceptedTypes: ["clause", "condition"],
          examples: ["you were me", "you won the lottery", "you lost your job"],
        },
      ],
      examples: [
        { en: "What would you do if you were me?", bn: "তুমি আমার জায়গায় থাকলে কী করতে?", slotValues: { CONDITION: "you were me" }, topicArea: "daily_life" },
        { en: "What would you do if you won the lottery?", bn: "তুমি লটারি জিতলে কী করতে?", slotValues: { CONDITION: "you won the lottery" }, topicArea: "daily_life" },
        { en: "What would you do if you lost your job?", bn: "তুমি চাকরি হারালে কী করতে?", slotValues: { CONDITION: "you lost your job" }, topicArea: "work" },
        { en: "What would you do if you could travel anywhere?", bn: "তুমি যেকোনো জায়গায় ভ্রমণ করতে পারলে কী করতে?", slotValues: { CONDITION: "you could travel anywhere" }, topicArea: "travel" },
        { en: "What would you do if you found a wallet on the street?", bn: "তুমি রাস্তায় মানিব্যাগ পেলে কী করতে?", slotValues: { CONDITION: "you found a wallet on the street" }, topicArea: "daily_life" },
        { en: "What would you do if the food was terrible?", bn: "খাবার খুব খারাপ হলে তুমি কী করতে?", slotValues: { CONDITION: "the food was terrible" }, topicArea: "food" },
        { en: "What would you do if you failed the exam?", bn: "তুমি পরীক্ষায় ফেল করলে কী করতে?", slotValues: { CONDITION: "you failed the exam" }, topicArea: "education" },
        { en: "What would you do if you got sick abroad?", bn: "বিদেশে অসুস্থ হলে তুমি কী করতে?", slotValues: { CONDITION: "you got sick abroad" }, topicArea: "health" },
        { en: "What would you do if your best friend betrayed you?", bn: "তোমার সবচেয়ে ভালো বন্ধু বিশ্বাসঘাতকতা করলে তুমি কী করতে?", slotValues: { CONDITION: "your best friend betrayed you" }, topicArea: "relationships" },
        { en: "What would you do if you had more free time?", bn: "তোমার বেশি ফ্রি সময় থাকলে তুমি কী করতে?", slotValues: { CONDITION: "you had more free time" }, topicArea: "daily_life" },
        { en: "What would you do if you bought the wrong item?", bn: "ভুল জিনিস কিনলে তুমি কী করতে?", slotValues: { CONDITION: "you bought the wrong item" }, topicArea: "shopping" },
        { en: "What would you do if your boss asked you to work on a holiday?", bn: "তোমার বস ছুটির দিনে কাজ করতে বললে তুমি কী করতে?", slotValues: { CONDITION: "your boss asked you to work on a holiday" }, topicArea: "work" },
        { en: "What would you do if you missed your flight?", bn: "তুমি ফ্লাইট মিস করলে কী করতে?", slotValues: { CONDITION: "you missed your flight" }, topicArea: "travel" },
        { en: "What would you do if you could learn any skill instantly?", bn: "তুমি যেকোনো দক্ষতা সাথে সাথে শিখতে পারলে কী করতে?", slotValues: { CONDITION: "you could learn any skill instantly" }, topicArea: "education" },
        { en: "What would you do if a friend needed money urgently?", bn: "বন্ধুর জরুরি টাকা দরকার হলে তুমি কী করতে?", slotValues: { CONDITION: "a friend needed money urgently" }, topicArea: "relationships" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "Uses the second conditional to ask about hypothetical situations. Great for advice-seeking conversations.",
      usageNote_bn: "অনুমানমূলক পরিস্থিতি সম্পর্কে জিজ্ঞাসা করতে দ্বিতীয় শর্তসাপেক্ষ ব্যবহার করে। পরামর্শ চাওয়ার কথোপকথনের জন্য দুর্দান্ত।",
    },
    {
      id: "G9.3",
      formula: "What should I [ACTION]?",
      formula_bn: "আমার কী [কাজ] করা উচিত?",
      patternName: "Direct Advice Question",
      patternName_bn: "সরাসরি পরামর্শ প্রশ্ন",
      slots: [
        {
          name: "ACTION",
          description: "A base form verb or verb phrase you need advice about",
          description_bn: "যে বিষয়ে পরামর্শ দরকার সেই মূল ক্রিয়া বা ক্রিয়া পদবন্ধ",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["do", "wear to the interview", "order here"],
        },
      ],
      examples: [
        { en: "What should I do?", bn: "আমার কী করা উচিত?", slotValues: { ACTION: "do" }, topicArea: "daily_life" },
        { en: "What should I wear to the interview?", bn: "ইন্টারভিউতে আমার কী পরা উচিত?", slotValues: { ACTION: "wear to the interview" }, topicArea: "work" },
        { en: "What should I order here?", bn: "এখানে আমার কী অর্ডার করা উচিত?", slotValues: { ACTION: "order here" }, topicArea: "food" },
        { en: "What should I pack for the trip?", bn: "ভ্রমণের জন্য আমার কী প্যাক করা উচিত?", slotValues: { ACTION: "pack for the trip" }, topicArea: "travel" },
        { en: "What should I study for the exam?", bn: "পরীক্ষার জন্য আমার কী পড়া উচিত?", slotValues: { ACTION: "study for the exam" }, topicArea: "education" },
        { en: "What should I eat before the workout?", bn: "ব্যায়ামের আগে আমার কী খাওয়া উচিত?", slotValues: { ACTION: "eat before the workout" }, topicArea: "health" },
        { en: "What should I buy for her birthday?", bn: "তার জন্মদিনে আমার কী কেনা উচিত?", slotValues: { ACTION: "buy for her birthday" }, topicArea: "shopping" },
        { en: "What should I say to him?", bn: "তাকে আমার কী বলা উচিত?", slotValues: { ACTION: "say to him" }, topicArea: "relationships" },
        { en: "What should I bring to the party?", bn: "পার্টিতে আমার কী নিয়ে যাওয়া উচিত?", slotValues: { ACTION: "bring to the party" }, topicArea: "daily_life" },
        { en: "What should I cook for dinner?", bn: "রাতের খাবারে আমার কী রান্না করা উচিত?", slotValues: { ACTION: "cook for dinner" }, topicArea: "food" },
        { en: "What should I ask in the interview?", bn: "ইন্টারভিউতে আমার কী জিজ্ঞাসা করা উচিত?", slotValues: { ACTION: "ask in the interview" }, topicArea: "work" },
        { en: "What should I visit first in this city?", bn: "এই শহরে আমার প্রথমে কোথায় যাওয়া উচিত?", slotValues: { ACTION: "visit first in this city" }, topicArea: "travel" },
        { en: "What should I read to improve my English?", bn: "আমার ইংরেজি উন্নত করতে কী পড়া উচিত?", slotValues: { ACTION: "read to improve my English" }, topicArea: "education" },
        { en: "What should I tell the doctor?", bn: "ডাক্তারকে আমার কী বলা উচিত?", slotValues: { ACTION: "tell the doctor" }, topicArea: "health" },
        { en: "What should I get as a wedding gift?", bn: "বিয়ের উপহার হিসাবে আমার কী নেওয়া উচিত?", slotValues: { ACTION: "get as a wedding gift" }, topicArea: "relationships" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "'What should I' directly asks for advice or recommendations. Very common in everyday English.",
      usageNote_bn: "'What should I' সরাসরি পরামর্শ বা সুপারিশ চায়। দৈনন্দিন ইংরেজিতে খুবই সাধারণ।",
    },
    {
      id: "G9.4",
      formula: "Do you think I should [ACTION]?",
      formula_bn: "তুমি কি মনে করো আমার [কাজ] করা উচিত?",
      patternName: "Seeking Validation Question",
      patternName_bn: "বৈধতা চাওয়ার প্রশ্ন",
      slots: [
        {
          name: "ACTION",
          description: "A base form verb or verb phrase about a decision",
          description_bn: "সিদ্ধান্ত সম্পর্কে মূল ক্রিয়া বা ক্রিয়া পদবন্ধ",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["accept the offer", "go to the doctor", "apologize"],
        },
      ],
      examples: [
        { en: "Do you think I should accept the offer?", bn: "তুমি কি মনে করো আমার অফার গ্রহণ করা উচিত?", slotValues: { ACTION: "accept the offer" }, topicArea: "work" },
        { en: "Do you think I should go to the doctor?", bn: "তুমি কি মনে করো আমার ডাক্তারের কাছে যাওয়া উচিত?", slotValues: { ACTION: "go to the doctor" }, topicArea: "health" },
        { en: "Do you think I should apologize?", bn: "তুমি কি মনে করো আমার ক্ষমা চাওয়া উচিত?", slotValues: { ACTION: "apologize" }, topicArea: "relationships" },
        { en: "Do you think I should try the spicy dish?", bn: "তুমি কি মনে করো আমার ঝাল খাবারটা চেষ্টা করা উচিত?", slotValues: { ACTION: "try the spicy dish" }, topicArea: "food" },
        { en: "Do you think I should book the trip now?", bn: "তুমি কি মনে করো আমার এখনই ভ্রমণ বুক করা উচিত?", slotValues: { ACTION: "book the trip now" }, topicArea: "travel" },
        { en: "Do you think I should change my major?", bn: "তুমি কি মনে করো আমার বিষয় পরিবর্তন করা উচিত?", slotValues: { ACTION: "change my major" }, topicArea: "education" },
        { en: "Do you think I should buy this?", bn: "তুমি কি মনে করো আমার এটা কেনা উচিত?", slotValues: { ACTION: "buy this" }, topicArea: "shopping" },
        { en: "Do you think I should move to another city?", bn: "তুমি কি মনে করো আমার অন্য শহরে চলে যাওয়া উচিত?", slotValues: { ACTION: "move to another city" }, topicArea: "daily_life" },
        { en: "Do you think I should quit my job?", bn: "তুমি কি মনে করো আমার চাকরি ছেড়ে দেওয়া উচিত?", slotValues: { ACTION: "quit my job" }, topicArea: "work" },
        { en: "Do you think I should start exercising?", bn: "তুমি কি মনে করো আমার ব্যায়াম শুরু করা উচিত?", slotValues: { ACTION: "start exercising" }, topicArea: "health" },
        { en: "Do you think I should tell her the truth?", bn: "তুমি কি মনে করো আমার তাকে সত্যি কথা বলা উচিত?", slotValues: { ACTION: "tell her the truth" }, topicArea: "relationships" },
        { en: "Do you think I should rent or buy?", bn: "তুমি কি মনে করো আমার ভাড়া নেওয়া উচিত নাকি কেনা?", slotValues: { ACTION: "rent or buy" }, topicArea: "shopping" },
        { en: "Do you think I should take the shortcut?", bn: "তুমি কি মনে করো আমার শর্টকাটে যাওয়া উচিত?", slotValues: { ACTION: "take the shortcut" }, topicArea: "travel" },
        { en: "Do you think I should retake the course?", bn: "তুমি কি মনে করো আমার কোর্সটা আবার নেওয়া উচিত?", slotValues: { ACTION: "retake the course" }, topicArea: "education" },
        { en: "Do you think I should order dessert?", bn: "তুমি কি মনে করো আমার ডেজার্ট অর্ডার করা উচিত?", slotValues: { ACTION: "order dessert" }, topicArea: "food" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "This pattern asks for validation or guidance on a decision. It shows you value the other person's opinion.",
      usageNote_bn: "এই প্যাটার্ন সিদ্ধান্তে বৈধতা বা নির্দেশনা চায়। এটি দেখায় আপনি অন্য ব্যক্তির মতামতকে মূল্য দেন।",
    },
    {
      id: "G9.5",
      formula: "How do you feel about [THING]?",
      formula_bn: "[জিনিস] সম্পর্কে তোমার কেমন লাগে?",
      patternName: "Emotional Opinion Question",
      patternName_bn: "আবেগজনিত মতামত প্রশ্ন",
      slots: [
        {
          name: "THING",
          description: "A noun, noun phrase, or gerund phrase about a topic",
          description_bn: "একটি বিষয় সম্পর্কে বিশেষ্য, বিশেষ্য পদবন্ধ, বা ক্রিয়াবাচক বিশেষ্য পদবন্ধ",
          acceptedTypes: ["noun", "noun_phrase", "gerund", "topic"],
          examples: ["the plan", "moving abroad", "getting married"],
        },
      ],
      examples: [
        { en: "How do you feel about the plan?", bn: "পরিকল্পনাটা সম্পর্কে তোমার কেমন লাগে?", slotValues: { THING: "the plan" }, topicArea: "daily_life" },
        { en: "How do you feel about moving abroad?", bn: "বিদেশে চলে যাওয়া সম্পর্কে তোমার কেমন লাগে?", slotValues: { THING: "moving abroad" }, topicArea: "travel" },
        { en: "How do you feel about getting married?", bn: "বিয়ে করা সম্পর্কে তোমার কেমন লাগে?", slotValues: { THING: "getting married" }, topicArea: "relationships" },
        { en: "How do you feel about the new menu?", bn: "নতুন মেনু সম্পর্কে তোমার কেমন লাগে?", slotValues: { THING: "the new menu" }, topicArea: "food" },
        { en: "How do you feel about changing careers?", bn: "ক্যারিয়ার পরিবর্তন সম্পর্কে তোমার কেমন লাগে?", slotValues: { THING: "changing careers" }, topicArea: "work" },
        { en: "How do you feel about the exam results?", bn: "পরীক্ষার ফলাফল সম্পর্কে তোমার কেমন লাগে?", slotValues: { THING: "the exam results" }, topicArea: "education" },
        { en: "How do you feel about surgery?", bn: "অপারেশন সম্পর্কে তোমার কেমন লাগে?", slotValues: { THING: "surgery" }, topicArea: "health" },
        { en: "How do you feel about online shopping?", bn: "অনলাইন কেনাকাটা সম্পর্কে তোমার কেমন লাগে?", slotValues: { THING: "online shopping" }, topicArea: "shopping" },
        { en: "How do you feel about working late?", bn: "দেরি পর্যন্ত কাজ করা সম্পর্কে তোমার কেমন লাগে?", slotValues: { THING: "working late" }, topicArea: "work" },
        { en: "How do you feel about the upcoming holiday?", bn: "আসন্ন ছুটি সম্পর্কে তোমার কেমন লাগে?", slotValues: { THING: "the upcoming holiday" }, topicArea: "travel" },
        { en: "How do you feel about the situation?", bn: "পরিস্থিতি সম্পর্কে তোমার কেমন লাগে?", slotValues: { THING: "the situation" }, topicArea: "daily_life" },
        { en: "How do you feel about trying street food?", bn: "রাস্তার খাবার চেষ্টা করা সম্পর্কে তোমার কেমন লাগে?", slotValues: { THING: "trying street food" }, topicArea: "food" },
        { en: "How do you feel about homeschooling?", bn: "হোমস্কুলিং সম্পর্কে তোমার কেমন লাগে?", slotValues: { THING: "homeschooling" }, topicArea: "education" },
        { en: "How do you feel about alternative medicine?", bn: "বিকল্প চিকিৎসা সম্পর্কে তোমার কেমন লাগে?", slotValues: { THING: "alternative medicine" }, topicArea: "health" },
        { en: "How do you feel about living with your in-laws?", bn: "শ্বশুরবাড়ির সাথে থাকা সম্পর্কে তোমার কেমন লাগে?", slotValues: { THING: "living with your in-laws" }, topicArea: "relationships" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "'How do you feel about' asks for an emotional or personal reaction, deeper than 'what do you think'.",
      usageNote_bn: "'How do you feel about' আবেগজনিত বা ব্যক্তিগত প্রতিক্রিয়া চায়, 'what do you think'-এর চেয়ে গভীর।",
    },
  ],
};
