import { PatternCategory } from "@/types/pattern";

export const categoryH1: PatternCategory = {
  id: "H1",
  slug: "greetings-goodbyes",
  name: "Greeting & Saying Goodbye",
  name_bn: "অভিবাদন ও বিদায় জানানো",
  description:
    "Learn common English greetings and farewell expressions for everyday interactions.",
  description_bn:
    "দৈনন্দিন যোগাযোগের জন্য সাধারণ ইংরেজি অভিবাদন ও বিদায়ের অভিব্যক্তি শিখুন।",
  icon: "👋",
  group: "H",
  groupName: "Social Interactions",
  groupName_bn: "সামাজিক যোগাযোগ",
  difficulty: "beginner",
  patterns: [
    {
      id: "H1.1",
      formula: "How are you?",
      formula_bn: "আপনি কেমন আছেন?",
      patternName: "General Greeting Inquiry",
      patternName_bn: "সাধারণ কুশল জিজ্ঞাসা",
      slots: [],
      examples: [
        {
          en: "How are you?",
          bn: "আপনি কেমন আছেন?",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "How are you doing today?",
          bn: "আজ আপনি কেমন আছেন?",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "How are you feeling this morning?",
          bn: "আজ সকালে আপনার কেমন লাগছে?",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "How are you after the trip?",
          bn: "ভ্রমণের পর আপনি কেমন আছেন?",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "How are you holding up at work?",
          bn: "কর্মক্ষেত্রে আপনি কেমন আছেন?",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "How are you? Long time no see!",
          bn: "কেমন আছেন? অনেকদিন দেখা হয়নি!",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "How are you doing with your studies?",
          bn: "পড়াশোনা কেমন চলছে?",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "How are you? Is everything okay?",
          bn: "কেমন আছেন? সব ঠিক আছে?",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "How are you these days?",
          bn: "আজকাল কেমন আছেন?",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "How are you settling into the new office?",
          bn: "নতুন অফিসে কেমন মানিয়ে নিচ্ছেন?",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "How are you? I heard you were sick.",
          bn: "কেমন আছেন? শুনলাম আপনি অসুস্থ ছিলেন।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "How are you doing after the exam?",
          bn: "পরীক্ষার পর কেমন আছেন?",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "How are you? Did you enjoy the weekend?",
          bn: "কেমন আছেন? সপ্তাহান্ত উপভোগ করেছেন?",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "How are you? We missed you at the party.",
          bn: "কেমন আছেন? পার্টিতে আপনাকে মিস করেছি।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "How are you doing? Ready for the meeting?",
          bn: "কেমন আছেন? মিটিংয়ের জন্য প্রস্তুত?",
          slotValues: {},
          topicArea: "work",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "The most common English greeting. Often used as a conversation opener rather than a genuine health inquiry.",
      usageNote_bn:
        "সবচেয়ে সাধারণ ইংরেজি অভিবাদন। প্রায়ই প্রকৃত স্বাস্থ্য জিজ্ঞাসার চেয়ে কথোপকথন শুরু করতে ব্যবহৃত হয়।",
      responsePatterns: ["H1.1"],
      banglaStructureMap: "আপনি (Subject) + কেমন (How) + আছেন (Verb)",
    },
    {
      id: "H1.2",
      formula: "Good morning/afternoon/evening",
      formula_bn: "শুভ সকাল/বিকাল/সন্ধ্যা",
      patternName: "Time-Based Greeting",
      patternName_bn: "সময়ভিত্তিক অভিবাদন",
      slots: [],
      examples: [
        {
          en: "Good morning!",
          bn: "শুভ সকাল!",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Good morning, everyone.",
          bn: "সবাইকে শুভ সকাল।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "Good afternoon. How can I help you?",
          bn: "শুভ বিকাল। আমি কীভাবে আপনাকে সাহায্য করতে পারি?",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "Good evening, sir. Welcome to the restaurant.",
          bn: "শুভ সন্ধ্যা, স্যার। রেস্তোরাঁয় স্বাগতম।",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "Good morning! Did you sleep well?",
          bn: "শুভ সকাল! ভালো ঘুম হয়েছে?",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Good afternoon, class. Let's begin.",
          bn: "শুভ বিকাল, শ্রেণি। চলুন শুরু করি।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "Good morning, doctor.",
          bn: "শুভ সকাল, ডাক্তার সাহেব।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "Good evening! Are you ready for the show?",
          bn: "শুভ সন্ধ্যা! অনুষ্ঠানের জন্য প্রস্তুত?",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Good morning! Beautiful day, isn't it?",
          bn: "শুভ সকাল! সুন্দর দিন, তাই না?",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Good afternoon. I have a reservation.",
          bn: "শুভ বিকাল। আমার একটি রিজার্ভেশন আছে।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "Good evening, neighbor!",
          bn: "শুভ সন্ধ্যা, প্রতিবেশী!",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "Good morning! Welcome to the team.",
          bn: "শুভ সকাল! দলে স্বাগতম।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "Good afternoon. I'm here for the interview.",
          bn: "শুভ বিকাল। আমি ইন্টারভিউয়ের জন্য এসেছি।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "Good evening! Thanks for coming.",
          bn: "শুভ সন্ধ্যা! আসার জন্য ধন্যবাদ।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "Good morning! Ready for the hike?",
          bn: "শুভ সকাল! হাইকিংয়ের জন্য প্রস্তুত?",
          slotValues: {},
          topicArea: "travel",
        },
      ],
      formality: "polite",
      difficulty: "beginner",
      usageNote:
        "Time-appropriate greetings are polite and professional. Use 'good morning' until noon, 'good afternoon' until about 5-6 PM, and 'good evening' after that.",
      usageNote_bn:
        "সময় অনুযায়ী অভিবাদন ভদ্র ও পেশাদার। দুপুর পর্যন্ত 'good morning', বিকাল ৫-৬টা পর্যন্ত 'good afternoon', এবং তারপর 'good evening' ব্যবহার করুন।",
      banglaStructureMap: "শুভ (Good) + সকাল/বিকাল/সন্ধ্যা (Time of day)",
    },
    {
      id: "H1.3",
      formula: "Nice to meet you",
      formula_bn: "আপনার সাথে দেখা হয়ে ভালো লাগলো",
      patternName: "First Meeting Greeting",
      patternName_bn: "প্রথম সাক্ষাতের অভিবাদন",
      slots: [],
      examples: [
        {
          en: "Nice to meet you.",
          bn: "আপনার সাথে দেখা হয়ে ভালো লাগলো।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Nice to meet you. I've heard a lot about you.",
          bn: "আপনার সাথে দেখা হয়ে ভালো লাগলো। আপনার সম্পর্কে অনেক শুনেছি।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "Nice to meet you too!",
          bn: "আপনার সাথেও দেখা হয়ে ভালো লাগলো!",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Nice to meet you. Welcome to the company.",
          bn: "আপনার সাথে দেখা হয়ে ভালো লাগলো। কোম্পানিতে স্বাগতম।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "Nice to meet you, Professor.",
          bn: "আপনার সাথে দেখা হয়ে ভালো লাগলো, প্রফেসর।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "Nice to meet you. Are you new here?",
          bn: "আপনার সাথে দেখা হয়ে ভালো লাগলো। আপনি কি এখানে নতুন?",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Nice to meet you. I'm your new neighbor.",
          bn: "আপনার সাথে দেখা হয়ে ভালো লাগলো। আমি আপনার নতুন প্রতিবেশী।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "Nice to meet you in person finally!",
          bn: "অবশেষে সশরীরে দেখা হয়ে ভালো লাগলো!",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "Nice to meet you. I'm looking forward to working together.",
          bn: "আপনার সাথে দেখা হয়ে ভালো লাগলো। একসাথে কাজ করার অপেক্ষায় আছি।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "Nice to meet you! How do you know the host?",
          bn: "আপনার সাথে দেখা হয়ে ভালো লাগলো! আপনি হোস্টকে কীভাবে চেনেন?",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "Nice to meet you, doctor. I was referred by Dr. Khan.",
          bn: "আপনার সাথে দেখা হয়ে ভালো লাগলো, ডাক্তার। ড. খান আমাকে পাঠিয়েছেন।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "Nice to meet you! Is this your first time here?",
          bn: "আপনার সাথে দেখা হয়ে ভালো লাগলো! এটা কি আপনার প্রথমবার এখানে?",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "Nice to meet you. I'm a friend of your brother.",
          bn: "আপনার সাথে দেখা হয়ে ভালো লাগলো। আমি আপনার ভাইয়ের বন্ধু।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "Nice to meet you. Shall we grab a coffee?",
          bn: "আপনার সাথে দেখা হয়ে ভালো লাগলো। কফি খাবেন?",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "Nice to meet you! I just moved to this area.",
          bn: "আপনার সাথে দেখা হয়ে ভালো লাগলো! আমি এই এলাকায় নতুন এসেছি।",
          slotValues: {},
          topicArea: "daily_life",
        },
      ],
      formality: "polite",
      difficulty: "beginner",
      usageNote:
        "Used when meeting someone for the first time. 'Nice to meet you too' is the standard response.",
      usageNote_bn:
        "প্রথমবার কারো সাথে দেখা হলে ব্যবহৃত হয়। 'Nice to meet you too' হলো এর মানসম্মত উত্তর।",
      banglaStructureMap:
        "আপনার সাথে (With you) + দেখা হয়ে (Meeting) + ভালো লাগলো (Felt good)",
    },
    {
      id: "H1.4",
      formula: "See you later",
      formula_bn: "পরে দেখা হবে",
      patternName: "Casual Farewell",
      patternName_bn: "অনানুষ্ঠানিক বিদায়",
      slots: [],
      examples: [
        {
          en: "See you later!",
          bn: "পরে দেখা হবে!",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "See you later at the meeting.",
          bn: "মিটিংয়ে পরে দেখা হবে।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "See you later, have a good lunch!",
          bn: "পরে দেখা হবে, ভালো দুপুরের খাবার হোক!",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "See you later! I have to run to class.",
          bn: "পরে দেখা হবে! আমাকে ক্লাসে যেতে হবে।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "See you later tonight!",
          bn: "আজ রাতে পরে দেখা হবে!",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "See you later, buddy!",
          bn: "পরে দেখা হবে, বন্ধু!",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "See you later. Don't forget the documents.",
          bn: "পরে দেখা হবে। কাগজপত্র ভুলবেন না।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "See you later! Safe travels.",
          bn: "পরে দেখা হবে! শুভ যাত্রা।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "See you later at the gym.",
          bn: "জিমে পরে দেখা হবে।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "See you later. Let's catch up soon.",
          bn: "পরে দেখা হবে। শীঘ্রই আড্ডা দেব।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "See you later at the store.",
          bn: "দোকানে পরে দেখা হবে।",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "See you later! Good luck with the presentation.",
          bn: "পরে দেখা হবে! প্রেজেন্টেশনের জন্য শুভকামনা।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "See you later. I'll text you the address.",
          bn: "পরে দেখা হবে। ঠিকানাটা মেসেজ করব।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "See you later! Enjoy the movie.",
          bn: "পরে দেখা হবে! মুভি উপভোগ করো।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "See you later. Take it easy!",
          bn: "পরে দেখা হবে। আরাম করো!",
          slotValues: {},
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "A friendly, informal way to say goodbye. Implies you expect to see the person again relatively soon.",
      usageNote_bn:
        "বিদায় জানানোর একটি বন্ধুত্বপূর্ণ, অনানুষ্ঠানিক উপায়। বোঝায় যে আপনি শীঘ্রই আবার দেখা হবে বলে আশা করছেন।",
      banglaStructureMap: "পরে (Later) + দেখা হবে (Will meet)",
    },
    {
      id: "H1.5",
      formula: "Take care",
      formula_bn: "নিজের যত্ন নিন",
      patternName: "Caring Farewell",
      patternName_bn: "যত্নশীল বিদায়",
      slots: [],
      examples: [
        {
          en: "Take care!",
          bn: "নিজের যত্ন নিন!",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Take care. See you next week.",
          bn: "নিজের যত্ন নিন। আগামী সপ্তাহে দেখা হবে।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Take care of yourself. Get well soon!",
          bn: "নিজের যত্ন নিন। তাড়াতাড়ি সুস্থ হয়ে যান!",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "Take care on the road!",
          bn: "রাস্তায় সাবধানে থাকবেন!",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "Take care, and good luck with the new job.",
          bn: "নিজের যত্ন নিন, এবং নতুন চাকরির জন্য শুভকামনা।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "Take care! Don't study too hard.",
          bn: "নিজের যত্ন নিন! বেশি পড়াশোনা করবেন না।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "Take care. I'll miss you.",
          bn: "নিজের যত্ন নিন। আপনাকে মিস করব।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "Take care, Mom. I love you.",
          bn: "মা, নিজের যত্ন নিও। তোমাকে ভালোবাসি।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "Take care out there. The weather looks bad.",
          bn: "বাইরে সাবধানে থাকবেন। আবহাওয়া খারাপ মনে হচ্ছে।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Take care. Eat well and rest properly.",
          bn: "নিজের যত্ন নিন। ভালো করে খাবেন আর বিশ্রাম নেবেন।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "Take care, friend. Stay in touch!",
          bn: "বন্ধু, নিজের যত্ন নিও। যোগাযোগ রাখো!",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "Take care during the flight.",
          bn: "ফ্লাইটে সাবধানে থাকবেন।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "Take care. Don't overwork yourself.",
          bn: "নিজের যত্ন নিন। নিজেকে অতিরিক্ত কাজ করাবেন না।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "Take care! Have a wonderful vacation.",
          bn: "নিজের যত্ন নিন! চমৎকার ছুটি কাটান।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "Take care and call me if you need anything.",
          bn: "নিজের যত্ন নিন এবং কিছু লাগলে আমাকে ফোন করবেন।",
          slotValues: {},
          topicArea: "daily_life",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "A warm, caring way to say goodbye. Shows genuine concern for the other person's wellbeing.",
      usageNote_bn:
        "বিদায় জানানোর একটি উষ্ণ, যত্নশীল উপায়। অন্য ব্যক্তির সুস্থতার প্রতি প্রকৃত উদ্বেগ প্রকাশ করে।",
      banglaStructureMap: "নিজের (Self) + যত্ন (Care) + নিন (Take)",
    },
    {
      id: "H1.6",
      formula: "What's up?",
      formula_bn: "কী অবস্থা?",
      patternName: "Casual Greeting (What's Up)",
      patternName_bn: "অনানুষ্ঠানিক অভিবাদন (কী অবস্থা)",
      slots: [],
      examples: [
        {
          en: "What's up?",
          bn: "কী অবস্থা?",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Hey! What's up?",
          bn: "হেই! কী অবস্থা?",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "What's up? Haven't seen you in a while!",
          bn: "কী অবস্থা? অনেকদিন দেখা হয়নি!",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "What's up, guys? Ready for the meeting?",
          bn: "কী অবস্থা, বন্ধুরা? মিটিংয়ের জন্য প্রস্তুত?",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "Yo, what's up?",
          bn: "ইয়ো, কী অবস্থা?",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "What's up? Did you eat?",
          bn: "কী অবস্থা? খেয়েছো?",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "What's up? How was the exam?",
          bn: "কী অবস্থা? পরীক্ষা কেমন হলো?",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "What's up? Are you feeling better?",
          bn: "কী অবস্থা? এখন ভালো লাগছে?",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "What's up? How was your trip?",
          bn: "কী অবস্থা? ভ্রমণ কেমন হলো?",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "What's up, bro? Long time!",
          bn: "কী অবস্থা, ভাই? অনেকদিন পর!",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "What's up? Did you find anything good at the sale?",
          bn: "কী অবস্থা? সেলে কিছু ভালো পেয়েছো?",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "What's up? Not much, just chilling.",
          bn: "কী অবস্থা? বিশেষ কিছু না, আরাম করছি।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "What's up? Want to grab lunch?",
          bn: "কী অবস্থা? দুপুরে খেতে যাবে?",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "What's up? Any plans for the weekend?",
          bn: "কী অবস্থা? সপ্তাহান্তে কোনো পরিকল্পনা?",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "What's up? How's the new project going?",
          bn: "কী অবস্থা? নতুন প্রজেক্ট কেমন চলছে?",
          slotValues: {},
          topicArea: "work",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "'What's up?' is a very informal greeting mostly used among friends and young people. It can be answered with 'Not much' or by sharing what you are doing.",
      usageNote_bn:
        "'What's up?' একটি অত্যন্ত অনানুষ্ঠানিক অভিবাদন যা মূলত বন্ধু ও তরুণদের মধ্যে ব্যবহৃত হয়। 'Not much' বলে বা আপনি কী করছেন তা জানিয়ে উত্তর দেওয়া যায়।",
      banglaStructureMap: "কী (What) + অবস্থা (Condition)?",
    },
    {
      id: "H1.7",
      formula: "How's it going?",
      formula_bn: "কেমন চলছে?",
      patternName: "Casual Inquiry (How's It Going)",
      patternName_bn: "অনানুষ্ঠানিক কুশল (কেমন চলছে)",
      slots: [],
      examples: [
        {
          en: "How's it going?",
          bn: "কেমন চলছে?",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Hey, how's it going?",
          bn: "হেই, কেমন চলছে?",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "How's it going at work?",
          bn: "কর্মক্ষেত্রে কেমন চলছে?",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "How's it going? Keeping busy?",
          bn: "কেমন চলছে? ব্যস্ত আছো?",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "How's it going with the new course?",
          bn: "নতুন কোর্স কেমন চলছে?",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "How's it going? You look happy today!",
          bn: "কেমন চলছে? আজ তোমাকে খুশি মনে হচ্ছে!",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "How's it going? Did you try the new cafe?",
          bn: "কেমন চলছে? নতুন ক্যাফেটা চেষ্টা করেছো?",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "How's it going? Everything okay with your health?",
          bn: "কেমন চলছে? স্বাস্থ্য ঠিক আছে?",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "How's it going? How was the vacation?",
          bn: "কেমন চলছে? ছুটি কেমন ছিল?",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "How's it going? Pretty good, thanks!",
          bn: "কেমন চলছে? বেশ ভালো, ধন্যবাদ!",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "How's it going? Found any good deals lately?",
          bn: "কেমন চলছে? সম্প্রতি কোনো ভালো দাম পেয়েছো?",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "How's it going with the project?",
          bn: "প্রজেক্ট কেমন চলছে?",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "How's it going? Ready for the exam?",
          bn: "কেমন চলছে? পরীক্ষার জন্য প্রস্তুত?",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "How's it going? We should catch up soon.",
          bn: "কেমন চলছে? শীঘ্রই আড্ডা দেওয়া উচিত।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "How's it going? Can't complain!",
          bn: "কেমন চলছে? অভিযোগ করার কিছু নেই!",
          slotValues: {},
          topicArea: "daily_life",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "'How's it going?' is a friendly, informal greeting. It's slightly more specific than 'How are you?' but still functions as a casual opener. Common responses include 'Good', 'Not bad', or 'Can't complain'.",
      usageNote_bn:
        "'How's it going?' একটি বন্ধুত্বপূর্ণ, অনানুষ্ঠানিক অভিবাদন। এটি 'How are you?'-এর চেয়ে সামান্য বেশি নির্দিষ্ট কিন্তু তবুও অনানুষ্ঠানিক শুরু হিসেবে কাজ করে। সাধারণ উত্তরের মধ্যে রয়েছে 'Good', 'Not bad', বা 'Can't complain'।",
      banglaStructureMap: "কেমন (How) + চলছে (Going)?",
    },
    {
      id: "H1.8",
      formula: "Talk soon!",
      formula_bn: "শীঘ্রই কথা হবে!",
      patternName: "Informal Farewell (Talk Soon)",
      patternName_bn: "অনানুষ্ঠানিক বিদায় (শীঘ্রই কথা হবে)",
      slots: [],
      examples: [
        {
          en: "Talk soon!",
          bn: "শীঘ্রই কথা হবে!",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Alright, talk soon! Bye!",
          bn: "আচ্ছা, শীঘ্রই কথা হবে! বিদায়!",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "It was great seeing you. Talk soon!",
          bn: "তোমাকে দেখে ভালো লাগলো। শীঘ্রই কথা হবে!",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "I'll send you the details. Talk soon!",
          bn: "বিস্তারিত পাঠাবো। শীঘ্রই কথা হবে!",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "Good luck on the exam. Talk soon!",
          bn: "পরীক্ষায় শুভকামনা। শীঘ্রই কথা হবে!",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "Take care of yourself. Talk soon!",
          bn: "নিজের যত্ন নিও। শীঘ্রই কথা হবে!",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "Have a safe trip! Talk soon!",
          bn: "শুভ যাত্রা! শীঘ্রই কথা হবে!",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "Let me know how the dinner goes. Talk soon!",
          bn: "রাতের খাবার কেমন হয় জানাবে। শীঘ্রই কথা হবে!",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "I gotta go. Talk soon, okay?",
          bn: "আমাকে যেতে হবে। শীঘ্রই কথা হবে, ঠিক আছে?",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Let's plan something for the weekend. Talk soon!",
          bn: "সপ্তাহান্তের জন্য কিছু পরিকল্পনা করি। শীঘ্রই কথা হবে!",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "I'll check with the team. Talk soon!",
          bn: "দলের সাথে কথা বলব। শীঘ্রই কথা হবে!",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "Enjoy the new book! Talk soon!",
          bn: "নতুন বইটা উপভোগ করো! শীঘ্রই কথা হবে!",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "Hope you feel better. Talk soon!",
          bn: "আশা করি শীঘ্রই ভালো হয়ে যাবে। শীঘ্রই কথা হবে!",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "Let me know if you need anything from the store. Talk soon!",
          bn: "দোকান থেকে কিছু লাগলে জানাবে। শীঘ্রই কথা হবে!",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "Miss you already! Talk soon!",
          bn: "এখনই তোমাকে মিস করছি! শীঘ্রই কথা হবে!",
          slotValues: {},
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "'Talk soon' is a casual, friendly way to end a conversation, especially on phone calls, texts, or messaging. It implies you plan to communicate again in the near future.",
      usageNote_bn:
        "'Talk soon' কথোপকথন শেষ করার একটি অনানুষ্ঠানিক, বন্ধুত্বপূর্ণ উপায়, বিশেষ করে ফোন কল, টেক্সট বা মেসেজিংয়ে। এটি বোঝায় আপনি শীঘ্রই আবার যোগাযোগ করার পরিকল্পনা করছেন।",
      banglaStructureMap: "শীঘ্রই (Soon) + কথা হবে (Will talk)!",
    },
  ],
};
