import { PatternCategory } from "@/types/pattern";

export const categoryH10: PatternCategory = {
  id: "H10",
  slug: "changing-managing-topics",
  name: "Changing & Managing Topics",
  name_bn: "বিষয় পরিবর্তন ও পরিচালনা",
  description:
    "Learn how to smoothly change, redirect, or manage conversation topics in English.",
  description_bn:
    "ইংরেজিতে মসৃণভাবে কথোপকথনের বিষয় পরিবর্তন, পুনর্নির্দেশ বা পরিচালনা করতে শিখুন।",
  icon: "🔄",
  group: "H",
  groupName: "Social Interactions",
  groupName_bn: "সামাজিক যোগাযোগ",
  difficulty: "beginner",
  patterns: [
    {
      id: "H10.1",
      formula: "By the way, [NEW TOPIC].",
      formula_bn: "যাই হোক, [নতুন বিষয়]।",
      patternName: "Casual Topic Change",
      patternName_bn: "অনানুষ্ঠানিক বিষয় পরিবর্তন",
      slots: [
        {
          name: "NEW TOPIC",
          description: "New subject or question you want to bring up",
          description_bn: "নতুন বিষয় বা প্রশ্ন যা তুলতে চান",
          acceptedTypes: ["clause", "statement"],
          examples: [
            "have you seen the new movie?",
            "did you hear about the sale?",
            "how's your brother doing?",
          ],
        },
      ],
      examples: [
        {
          en: "By the way, have you seen the new movie everyone is talking about?",
          bn: "যাই হোক, সবাই যে নতুন সিনেমা নিয়ে কথা বলছে সেটা দেখেছো?",
          slotValues: { "NEW TOPIC": "have you seen the new movie everyone is talking about?" },
          topicArea: "daily_life",
        },
        {
          en: "By the way, did you hear about the sale at the mall?",
          bn: "যাই হোক, মলে সেলের কথা শুনেছো?",
          slotValues: { "NEW TOPIC": "did you hear about the sale at the mall?" },
          topicArea: "shopping",
        },
        {
          en: "By the way, how's your brother doing these days?",
          bn: "যাই হোক, আজকাল তোমার ভাই কেমন আছে?",
          slotValues: { "NEW TOPIC": "how's your brother doing these days?" },
          topicArea: "relationships",
        },
        {
          en: "By the way, the office is moving to a new building next month.",
          bn: "যাই হোক, অফিস আগামী মাসে নতুন বিল্ডিংয়ে যাচ্ছে।",
          slotValues: { "NEW TOPIC": "the office is moving to a new building next month" },
          topicArea: "work",
        },
        {
          en: "By the way, have you tried that new restaurant on Gulshan Avenue?",
          bn: "যাই হোক, গুলশান এভিনিউয়ের সেই নতুন রেস্তোরাঁ ট্রাই করেছো?",
          slotValues: { "NEW TOPIC": "have you tried that new restaurant on Gulshan Avenue?" },
          topicArea: "food",
        },
        {
          en: "By the way, the final exam date has been announced.",
          bn: "যাই হোক, ফাইনাল পরীক্ষার তারিখ ঘোষণা হয়েছে।",
          slotValues: { "NEW TOPIC": "the final exam date has been announced" },
          topicArea: "education",
        },
        {
          en: "By the way, I started going to the gym this week.",
          bn: "যাই হোক, এই সপ্তাহে আমি জিমে যাওয়া শুরু করেছি।",
          slotValues: { "NEW TOPIC": "I started going to the gym this week" },
          topicArea: "health",
        },
        {
          en: "By the way, are you planning any trips this summer?",
          bn: "যাই হোক, এই গরমে কোনো ভ্রমণের পরিকল্পনা আছে?",
          slotValues: { "NEW TOPIC": "are you planning any trips this summer?" },
          topicArea: "travel",
        },
        {
          en: "By the way, I got a new phone yesterday.",
          bn: "যাই হোক, গতকাল আমি একটা নতুন ফোন কিনেছি।",
          slotValues: { "NEW TOPIC": "I got a new phone yesterday" },
          topicArea: "shopping",
        },
        {
          en: "By the way, your mom called while you were out.",
          bn: "যাই হোক, তুমি বাইরে থাকতে তোমার মা ফোন করেছিলেন।",
          slotValues: { "NEW TOPIC": "your mom called while you were out" },
          topicArea: "relationships",
        },
        {
          en: "By the way, the boss wants to see us after lunch.",
          bn: "যাই হোক, দুপুরের খাবারের পর বস আমাদের দেখতে চান।",
          slotValues: { "NEW TOPIC": "the boss wants to see us after lunch" },
          topicArea: "work",
        },
        {
          en: "By the way, I learned a great recipe for chicken curry.",
          bn: "যাই হোক, আমি মুরগির তরকারির দারুণ একটা রেসিপি শিখেছি।",
          slotValues: { "NEW TOPIC": "I learned a great recipe for chicken curry" },
          topicArea: "food",
        },
        {
          en: "By the way, the library has extended its hours this month.",
          bn: "যাই হোক, এই মাসে লাইব্রেরি তাদের সময় বাড়িয়েছে।",
          slotValues: { "NEW TOPIC": "the library has extended its hours this month" },
          topicArea: "education",
        },
        {
          en: "By the way, you should drink more water in this heat.",
          bn: "যাই হোক, এই গরমে তোমার আরও পানি খাওয়া উচিত।",
          slotValues: { "NEW TOPIC": "you should drink more water in this heat" },
          topicArea: "health",
        },
        {
          en: "By the way, my cousin is coming from London next week.",
          bn: "যাই হোক, আমার কাজিন আগামী সপ্তাহে লন্ডন থেকে আসছে।",
          slotValues: { "NEW TOPIC": "my cousin is coming from London next week" },
          topicArea: "travel",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "'By the way' is the most common casual way to introduce a new topic. It signals that what follows is loosely related or entirely new.",
      usageNote_bn:
        "'By the way' নতুন বিষয় তোলার সবচেয়ে সাধারণ অনানুষ্ঠানিক উপায়। এটি ইঙ্গিত দেয় যে পরবর্তী কথা আলগাভাবে সম্পর্কিত বা সম্পূর্ণ নতুন।",
      banglaStructureMap:
        "যাই হোক (By the way) + [NEW TOPIC] (New topic)",
    },
    {
      id: "H10.2",
      formula: "Speaking of [THING], [CLAUSE].",
      formula_bn: "[জিনিস]-এর কথা বলতে গেলে, [বাক্যাংশ]।",
      patternName: "Related Topic Transition",
      patternName_bn: "সম্পর্কিত বিষয়ে যোগসূত্র",
      slots: [
        {
          name: "THING",
          description: "Topic word or phrase that connects to something just mentioned",
          description_bn: "এইমাত্র উল্লেখিত বিষয়ের সাথে সংযুক্ত শব্দ বা বাক্যাংশ",
          acceptedTypes: ["noun", "topic", "gerund"],
          examples: ["food", "travel", "work"],
        },
        {
          name: "CLAUSE",
          description: "Related point or question about the connecting topic",
          description_bn: "সংযোগকারী বিষয় সম্পর্কে সম্পর্কিত পয়েন্ট বা প্রশ্ন",
          acceptedTypes: ["clause"],
          examples: [
            "have you tried the new place?",
            "when is your next trip?",
            "did you finish the project?",
          ],
        },
      ],
      examples: [
        {
          en: "Speaking of food, have you tried the new biryani place near Dhanmondi?",
          bn: "খাবারের কথা বলতে গেলে, ধানমন্ডির কাছে নতুন বিরিয়ানির দোকান ট্রাই করেছো?",
          slotValues: { THING: "food", CLAUSE: "have you tried the new biryani place near Dhanmondi?" },
          topicArea: "food",
        },
        {
          en: "Speaking of travel, when is your next vacation?",
          bn: "ভ্রমণের কথা বলতে গেলে, তোমার পরবর্তী ছুটি কবে?",
          slotValues: { THING: "travel", CLAUSE: "when is your next vacation?" },
          topicArea: "travel",
        },
        {
          en: "Speaking of work, did you hear they're hiring for our team?",
          bn: "কাজের কথা বলতে গেলে, শুনেছো আমাদের টিমে নিয়োগ হচ্ছে?",
          slotValues: { THING: "work", CLAUSE: "did you hear they're hiring for our team?" },
          topicArea: "work",
        },
        {
          en: "Speaking of health, I've started drinking green tea every morning.",
          bn: "স্বাস্থ্যের কথা বলতে গেলে, আমি প্রতি সকালে গ্রিন টি খাওয়া শুরু করেছি।",
          slotValues: { THING: "health", CLAUSE: "I've started drinking green tea every morning" },
          topicArea: "health",
        },
        {
          en: "Speaking of shopping, there's a huge discount at the electronics store.",
          bn: "কেনাকাটার কথা বলতে গেলে, ইলেকট্রনিক্স দোকানে বিশাল ছাড় চলছে।",
          slotValues: { THING: "shopping", CLAUSE: "there's a huge discount at the electronics store" },
          topicArea: "shopping",
        },
        {
          en: "Speaking of exams, the study group is meeting tomorrow.",
          bn: "পরীক্ষার কথা বলতে গেলে, কাল স্টাডি গ্রুপের মিটিং আছে।",
          slotValues: { THING: "exams", CLAUSE: "the study group is meeting tomorrow" },
          topicArea: "education",
        },
        {
          en: "Speaking of family, my sister just had her baby.",
          bn: "পরিবারের কথা বলতে গেলে, আমার বোনের সদ্য বাচ্চা হয়েছে।",
          slotValues: { THING: "family", CLAUSE: "my sister just had her baby" },
          topicArea: "relationships",
        },
        {
          en: "Speaking of cooking, I tried making pasta last night.",
          bn: "রান্নার কথা বলতে গেলে, গত রাতে পাস্তা বানানোর চেষ্টা করেছি।",
          slotValues: { THING: "cooking", CLAUSE: "I tried making pasta last night" },
          topicArea: "food",
        },
        {
          en: "Speaking of exercise, do you want to join me for yoga tomorrow?",
          bn: "ব্যায়ামের কথা বলতে গেলে, কাল আমার সাথে যোগব্যায়ামে আসবে?",
          slotValues: { THING: "exercise", CLAUSE: "do you want to join me for yoga tomorrow?" },
          topicArea: "health",
        },
        {
          en: "Speaking of deadlines, we need to submit the report by Friday.",
          bn: "সময়সীমার কথা বলতে গেলে, আমাদের শুক্রবারের মধ্যে রিপোর্ট জমা দিতে হবে।",
          slotValues: { THING: "deadlines", CLAUSE: "we need to submit the report by Friday" },
          topicArea: "work",
        },
        {
          en: "Speaking of birthdays, we should plan something for Rahim.",
          bn: "জন্মদিনের কথা বলতে গেলে, রহিমের জন্য কিছু একটা পরিকল্পনা করা উচিত।",
          slotValues: { THING: "birthdays", CLAUSE: "we should plan something for Rahim" },
          topicArea: "relationships",
        },
        {
          en: "Speaking of books, have you read anything good lately?",
          bn: "বইয়ের কথা বলতে গেলে, ইদানীং ভালো কিছু পড়েছো?",
          slotValues: { THING: "books", CLAUSE: "have you read anything good lately?" },
          topicArea: "education",
        },
        {
          en: "Speaking of trains, the new metro line opens next month.",
          bn: "ট্রেনের কথা বলতে গেলে, আগামী মাসে নতুন মেট্রো লাইন খুলছে।",
          slotValues: { THING: "trains", CLAUSE: "the new metro line opens next month" },
          topicArea: "travel",
        },
        {
          en: "Speaking of prices, everything seems to be getting more expensive.",
          bn: "দামের কথা বলতে গেলে, সবকিছু আরও ব্যয়বহুল হয়ে যাচ্ছে মনে হচ্ছে।",
          slotValues: { THING: "prices", CLAUSE: "everything seems to be getting more expensive" },
          topicArea: "shopping",
        },
        {
          en: "Speaking of weekends, are you free this Saturday?",
          bn: "সপ্তাহান্তের কথা বলতে গেলে, এই শনিবার তুমি কি ফ্রি?",
          slotValues: { THING: "weekends", CLAUSE: "are you free this Saturday?" },
          topicArea: "daily_life",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "'Speaking of' creates a natural bridge between topics. Use it when something in the current conversation reminds you of a related subject.",
      usageNote_bn:
        "'Speaking of' বিষয়গুলোর মধ্যে স্বাভাবিক সেতু তৈরি করে। যখন বর্তমান কথোপকথনের কিছু আপনাকে সম্পর্কিত বিষয়ের কথা মনে করিয়ে দেয় তখন এটি ব্যবহার করুন।",
      banglaStructureMap:
        "[THING]-এর কথা বলতে গেলে (Speaking of thing) + [CLAUSE] (Clause)",
    },
    {
      id: "H10.3",
      formula: "Getting back to [TOPIC], [CLAUSE].",
      formula_bn: "[বিষয়]-এ ফিরে আসি, [বাক্যাংশ]।",
      patternName: "Returning to Previous Topic",
      patternName_bn: "আগের বিষয়ে ফিরে আসা",
      slots: [
        {
          name: "TOPIC",
          description: "Previous subject you want to return to",
          description_bn: "যে আগের বিষয়ে ফিরতে চান",
          acceptedTypes: ["noun", "topic"],
          examples: [
            "what you said earlier",
            "the meeting",
            "our plan",
          ],
        },
        {
          name: "CLAUSE",
          description: "What you want to say about the previous topic",
          description_bn: "আগের বিষয়ে যা বলতে চান",
          acceptedTypes: ["clause"],
          examples: [
            "I think we should finalize it today",
            "what was your suggestion again?",
            "we still need to decide",
          ],
        },
      ],
      examples: [
        {
          en: "Getting back to what you said earlier, I think you had a great point.",
          bn: "তুমি আগে যা বলেছিলে সেখানে ফিরে আসি, আমার মনে হয় তোমার কথায় যুক্তি ছিল।",
          slotValues: { TOPIC: "what you said earlier", CLAUSE: "I think you had a great point" },
          topicArea: "relationships",
        },
        {
          en: "Getting back to the meeting agenda, we still have three items left.",
          bn: "মিটিংয়ের এজেন্ডায় ফিরে আসি, আমাদের এখনও তিনটি বিষয় বাকি আছে।",
          slotValues: { TOPIC: "the meeting agenda", CLAUSE: "we still have three items left" },
          topicArea: "work",
        },
        {
          en: "Getting back to our travel plan, have we booked the hotel yet?",
          bn: "আমাদের ভ্রমণ পরিকল্পনায় ফিরে আসি, হোটেল কি বুক করা হয়েছে?",
          slotValues: { TOPIC: "our travel plan", CLAUSE: "have we booked the hotel yet?" },
          topicArea: "travel",
        },
        {
          en: "Getting back to the recipe, how much sugar do we need?",
          bn: "রেসিপিতে ফিরে আসি, কতটুকু চিনি লাগবে?",
          slotValues: { TOPIC: "the recipe", CLAUSE: "how much sugar do we need?" },
          topicArea: "food",
        },
        {
          en: "Getting back to the budget, we need to cut some expenses.",
          bn: "বাজেটে ফিরে আসি, আমাদের কিছু খরচ কমাতে হবে।",
          slotValues: { TOPIC: "the budget", CLAUSE: "we need to cut some expenses" },
          topicArea: "shopping",
        },
        {
          en: "Getting back to the homework, did you finish question five?",
          bn: "হোমওয়ার্কে ফিরে আসি, পাঁচ নম্বর প্রশ্ন শেষ করেছো?",
          slotValues: { TOPIC: "the homework", CLAUSE: "did you finish question five?" },
          topicArea: "education",
        },
        {
          en: "Getting back to your health, have you been sleeping well?",
          bn: "তোমার স্বাস্থ্যের বিষয়ে ফিরে আসি, ভালো ঘুম হচ্ছে?",
          slotValues: { TOPIC: "your health", CLAUSE: "have you been sleeping well?" },
          topicArea: "health",
        },
        {
          en: "Getting back to the project deadline, can we extend it by a week?",
          bn: "প্রজেক্টের সময়সীমায় ফিরে আসি, এক সপ্তাহ বাড়ানো যায়?",
          slotValues: { TOPIC: "the project deadline", CLAUSE: "can we extend it by a week?" },
          topicArea: "work",
        },
        {
          en: "Getting back to the wedding plans, have you chosen the venue?",
          bn: "বিয়ের পরিকল্পনায় ফিরে আসি, ভেন্যু ঠিক করেছো?",
          slotValues: { TOPIC: "the wedding plans", CLAUSE: "have you chosen the venue?" },
          topicArea: "relationships",
        },
        {
          en: "Getting back to dinner, should we order pizza or cook at home?",
          bn: "রাতের খাবারে ফিরে আসি, পিৎজা অর্ডার করবো নাকি বাড়িতে রান্না করবো?",
          slotValues: { TOPIC: "dinner", CLAUSE: "should we order pizza or cook at home?" },
          topicArea: "food",
        },
        {
          en: "Getting back to the class schedule, which time works best for everyone?",
          bn: "ক্লাসের সময়সূচিতে ফিরে আসি, কোন সময়টা সবার জন্য সবচেয়ে ভালো?",
          slotValues: { TOPIC: "the class schedule", CLAUSE: "which time works best for everyone?" },
          topicArea: "education",
        },
        {
          en: "Getting back to the doctor's advice, you really should exercise more.",
          bn: "ডাক্তারের পরামর্শে ফিরে আসি, তোমার সত্যিই বেশি ব্যায়াম করা উচিত।",
          slotValues: { TOPIC: "the doctor's advice", CLAUSE: "you really should exercise more" },
          topicArea: "health",
        },
        {
          en: "Getting back to the flight options, the morning one is cheaper.",
          bn: "ফ্লাইটের বিকল্পে ফিরে আসি, সকালেরটা সস্তা।",
          slotValues: { TOPIC: "the flight options", CLAUSE: "the morning one is cheaper" },
          topicArea: "travel",
        },
        {
          en: "Getting back to the grocery list, did we add milk?",
          bn: "মুদির তালিকায় ফিরে আসি, দুধ যোগ করেছি?",
          slotValues: { TOPIC: "the grocery list", CLAUSE: "did we add milk?" },
          topicArea: "shopping",
        },
        {
          en: "Getting back to our original discussion, I agree with your idea.",
          bn: "আমাদের মূল আলোচনায় ফিরে আসি, আমি তোমার ধারণার সাথে একমত।",
          slotValues: { TOPIC: "our original discussion", CLAUSE: "I agree with your idea" },
          topicArea: "daily_life",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "'Getting back to' is useful when a conversation has drifted and you want to return to the original or a previous topic. It keeps discussions focused.",
      usageNote_bn:
        "'Getting back to' কথোপকথন যখন অন্যদিকে চলে যায় এবং আপনি মূল বা আগের বিষয়ে ফিরতে চান তখন উপযোগী। এটি আলোচনাকে কেন্দ্রীভূত রাখে।",
      banglaStructureMap:
        "[TOPIC]-এ ফিরে আসি (Getting back to topic) + [CLAUSE] (Clause)",
    },
    {
      id: "H10.4",
      formula: "That reminds me, [STATEMENT].",
      formula_bn: "এটা মনে করিয়ে দিল, [বক্তব্য]।",
      patternName: "Association-Based Topic Change",
      patternName_bn: "সংযোগভিত্তিক বিষয় পরিবর্তন",
      slots: [
        {
          name: "STATEMENT",
          description: "Related thought or information triggered by the conversation",
          description_bn: "কথোপকথন থেকে উদ্ভূত সম্পর্কিত চিন্তা বা তথ্য",
          acceptedTypes: ["clause", "statement"],
          examples: [
            "I need to call the dentist",
            "we should buy groceries",
            "I forgot to tell you something",
          ],
        },
      ],
      examples: [
        {
          en: "That reminds me, I need to call the dentist tomorrow.",
          bn: "এটা মনে করিয়ে দিল, আমাকে কাল ডেন্টিস্টকে ফোন করতে হবে।",
          slotValues: { STATEMENT: "I need to call the dentist tomorrow" },
          topicArea: "health",
        },
        {
          en: "That reminds me, we should buy groceries on the way home.",
          bn: "এটা মনে করিয়ে দিল, বাড়ি ফেরার পথে মুদি কিনতে হবে।",
          slotValues: { STATEMENT: "we should buy groceries on the way home" },
          topicArea: "shopping",
        },
        {
          en: "That reminds me, I forgot to tell you about the party on Saturday.",
          bn: "এটা মনে করিয়ে দিল, শনিবারের পার্টির কথা তোমাকে বলতে ভুলে গিয়েছিলাম।",
          slotValues: { STATEMENT: "I forgot to tell you about the party on Saturday" },
          topicArea: "relationships",
        },
        {
          en: "That reminds me, I have to finish my report before the meeting.",
          bn: "এটা মনে করিয়ে দিল, মিটিংয়ের আগে আমার রিপোর্ট শেষ করতে হবে।",
          slotValues: { STATEMENT: "I have to finish my report before the meeting" },
          topicArea: "work",
        },
        {
          en: "That reminds me, I promised to bring dessert for dinner tonight.",
          bn: "এটা মনে করিয়ে দিল, আজ রাতের খাবারে ডেজার্ট আনার প্রতিশ্রুতি দিয়েছিলাম।",
          slotValues: { STATEMENT: "I promised to bring dessert for dinner tonight" },
          topicArea: "food",
        },
        {
          en: "That reminds me, the assignment is due tomorrow.",
          bn: "এটা মনে করিয়ে দিল, কালই অ্যাসাইনমেন্ট জমা দিতে হবে।",
          slotValues: { STATEMENT: "the assignment is due tomorrow" },
          topicArea: "education",
        },
        {
          en: "That reminds me, I need to renew my passport before the trip.",
          bn: "এটা মনে করিয়ে দিল, ভ্রমণের আগে আমার পাসপোর্ট নবায়ন করতে হবে।",
          slotValues: { STATEMENT: "I need to renew my passport before the trip" },
          topicArea: "travel",
        },
        {
          en: "That reminds me, I should pick up my medicine from the pharmacy.",
          bn: "এটা মনে করিয়ে দিল, ফার্মেসি থেকে আমার ওষুধ নিয়ে আসা উচিত।",
          slotValues: { STATEMENT: "I should pick up my medicine from the pharmacy" },
          topicArea: "health",
        },
        {
          en: "That reminds me, there's a sale on winter clothes this weekend.",
          bn: "এটা মনে করিয়ে দিল, এই সপ্তাহান্তে শীতের কাপড়ে সেল আছে।",
          slotValues: { STATEMENT: "there's a sale on winter clothes this weekend" },
          topicArea: "shopping",
        },
        {
          en: "That reminds me, I saw your old classmate at the market yesterday.",
          bn: "এটা মনে করিয়ে দিল, গতকাল বাজারে তোমার পুরনো সহপাঠীকে দেখেছি।",
          slotValues: { STATEMENT: "I saw your old classmate at the market yesterday" },
          topicArea: "relationships",
        },
        {
          en: "That reminds me, the boss mentioned a bonus at the end of the year.",
          bn: "এটা মনে করিয়ে দিল, বস বছরের শেষে বোনাসের কথা বলেছিলেন।",
          slotValues: { STATEMENT: "the boss mentioned a bonus at the end of the year" },
          topicArea: "work",
        },
        {
          en: "That reminds me, I wanted to try that new cake shop near our school.",
          bn: "এটা মনে করিয়ে দিল, আমাদের স্কুলের কাছে নতুন কেকের দোকান ট্রাই করতে চেয়েছিলাম।",
          slotValues: { STATEMENT: "I wanted to try that new cake shop near our school" },
          topicArea: "food",
        },
        {
          en: "That reminds me, I need to return my library books today.",
          bn: "এটা মনে করিয়ে দিল, আজ আমার লাইব্রেরির বই ফেরত দিতে হবে।",
          slotValues: { STATEMENT: "I need to return my library books today" },
          topicArea: "education",
        },
        {
          en: "That reminds me, we should book the train tickets early.",
          bn: "এটা মনে করিয়ে দিল, আমাদের তাড়াতাড়ি ট্রেনের টিকিট বুক করা উচিত।",
          slotValues: { STATEMENT: "we should book the train tickets early" },
          topicArea: "travel",
        },
        {
          en: "That reminds me, I need to water the plants before we leave.",
          bn: "এটা মনে করিয়ে দিল, যাওয়ার আগে গাছে পানি দিতে হবে।",
          slotValues: { STATEMENT: "I need to water the plants before we leave" },
          topicArea: "daily_life",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "'That reminds me' is a natural and effortless way to shift topics. It suggests the new topic popped into your mind because of something in the current conversation.",
      usageNote_bn:
        "'That reminds me' বিষয় পরিবর্তনের স্বাভাবিক ও সহজ উপায়। এটি ইঙ্গিত দেয় যে বর্তমান কথোপকথনের কারণে নতুন বিষয়টি মনে এসেছে।",
      banglaStructureMap:
        "এটা (That) + মনে করিয়ে দিল (Reminds me) + [STATEMENT] (Statement)",
    },
    {
      id: "H10.5",
      formula: "Anyway, [STATEMENT].",
      formula_bn: "যা-ই হোক, [বক্তব্য]।",
      patternName: "Redirecting the Conversation",
      patternName_bn: "কথোপকথন পুনর্নির্দেশ করা",
      slots: [
        {
          name: "STATEMENT",
          description: "The point you want to redirect the conversation to",
          description_bn: "যে পয়েন্টে কথোপকথন নিয়ে যেতে চান",
          acceptedTypes: ["clause", "statement"],
          examples: [
            "what I was trying to say is...",
            "let's focus on the main issue",
            "the point is...",
          ],
        },
      ],
      examples: [
        {
          en: "Anyway, what I was trying to say is we need more time.",
          bn: "যা-ই হোক, আমি যা বলতে চাইছিলাম তা হলো আমাদের আরও সময় দরকার।",
          slotValues: { STATEMENT: "what I was trying to say is we need more time" },
          topicArea: "work",
        },
        {
          en: "Anyway, let's focus on the main issue.",
          bn: "যা-ই হোক, মূল বিষয়ে মনোযোগ দিই।",
          slotValues: { STATEMENT: "let's focus on the main issue" },
          topicArea: "work",
        },
        {
          en: "Anyway, the point is we should leave by eight o'clock.",
          bn: "যা-ই হোক, মূল কথা হলো আমাদের আটটার মধ্যে বের হওয়া উচিত।",
          slotValues: { STATEMENT: "the point is we should leave by eight o'clock" },
          topicArea: "travel",
        },
        {
          en: "Anyway, how was your day at school?",
          bn: "যা-ই হোক, স্কুলে তোমার দিন কেমন ছিল?",
          slotValues: { STATEMENT: "how was your day at school?" },
          topicArea: "education",
        },
        {
          en: "Anyway, we still need to decide what to eat for dinner.",
          bn: "যা-ই হোক, রাতের খাবারে কী খাবো এখনও ঠিক করতে হবে।",
          slotValues: { STATEMENT: "we still need to decide what to eat for dinner" },
          topicArea: "food",
        },
        {
          en: "Anyway, are you feeling better now?",
          bn: "যা-ই হোক, এখন কি ভালো লাগছে?",
          slotValues: { STATEMENT: "are you feeling better now?" },
          topicArea: "health",
        },
        {
          en: "Anyway, I'm glad we could catch up today.",
          bn: "যা-ই হোক, আজ কথা বলতে পেরে ভালো লাগলো।",
          slotValues: { STATEMENT: "I'm glad we could catch up today" },
          topicArea: "relationships",
        },
        {
          en: "Anyway, did you find what you were looking for at the store?",
          bn: "যা-ই হোক, দোকানে যা খুঁজছিলে পেয়েছো?",
          slotValues: { STATEMENT: "did you find what you were looking for at the store?" },
          topicArea: "shopping",
        },
        {
          en: "Anyway, let's get back to work.",
          bn: "যা-ই হোক, কাজে ফিরি।",
          slotValues: { STATEMENT: "let's get back to work" },
          topicArea: "work",
        },
        {
          en: "Anyway, what time does the train leave?",
          bn: "যা-ই হোক, ট্রেন কটায় ছাড়ে?",
          slotValues: { STATEMENT: "what time does the train leave?" },
          topicArea: "travel",
        },
        {
          en: "Anyway, I wanted to ask you about the homework.",
          bn: "যা-ই হোক, হোমওয়ার্ক সম্পর্কে তোমাকে জিজ্ঞেস করতে চেয়েছিলাম।",
          slotValues: { STATEMENT: "I wanted to ask you about the homework" },
          topicArea: "education",
        },
        {
          en: "Anyway, shall we order some tea?",
          bn: "যা-ই হোক, চা অর্ডার করবো?",
          slotValues: { STATEMENT: "shall we order some tea?" },
          topicArea: "food",
        },
        {
          en: "Anyway, don't forget to take your vitamins.",
          bn: "যা-ই হোক, ভিটামিন খেতে ভুলো না।",
          slotValues: { STATEMENT: "don't forget to take your vitamins" },
          topicArea: "health",
        },
        {
          en: "Anyway, it was great seeing you again.",
          bn: "যা-ই হোক, তোমাকে আবার দেখে ভালো লাগলো।",
          slotValues: { STATEMENT: "it was great seeing you again" },
          topicArea: "relationships",
        },
        {
          en: "Anyway, let me know if you need any help with the shopping.",
          bn: "যা-ই হোক, কেনাকাটায় সাহায্য লাগলে আমাকে জানিও।",
          slotValues: { STATEMENT: "let me know if you need any help with the shopping" },
          topicArea: "shopping",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "'Anyway' signals you want to move past the current topic or wrap up a tangent. It can redirect to the main point or introduce something entirely new.",
      usageNote_bn:
        "'Anyway' ইঙ্গিত দেয় আপনি বর্তমান বিষয় থেকে এগিয়ে যেতে বা একটি বিচ্যুতি শেষ করতে চান। এটি মূল পয়েন্টে ফিরে যেতে বা সম্পূর্ণ নতুন কিছু তুলতে পারে।",
      banglaStructureMap: "যা-ই হোক (Anyway) + [STATEMENT] (Statement)",
    },
  ],
};
