import { PatternCategory } from "@/types/pattern";

export const categoryH4: PatternCategory = {
  id: "H4",
  slug: "thanking-responding",
  name: "Thanking & Responding",
  name_bn: "ধন্যবাদ দেওয়া ও সাড়া দেওয়া",
  description:
    "Learn how to express gratitude and respond to thanks naturally in English.",
  description_bn:
    "ইংরেজিতে স্বাভাবিকভাবে কৃতজ্ঞতা প্রকাশ করতে এবং ধন্যবাদের সাড়া দিতে শিখুন।",
  icon: "🙏",
  group: "H",
  groupName: "Social Interactions",
  groupName_bn: "সামাজিক যোগাযোগ",
  difficulty: "beginner",
  patterns: [
    {
      id: "H4.1",
      formula: "Thank you for [THING/DOING]",
      formula_bn: "[জিনিস/করার] জন্য ধন্যবাদ",
      patternName: "Expressing Gratitude",
      patternName_bn: "কৃতজ্ঞতা প্রকাশ",
      slots: [
        {
          name: "THING/DOING",
          description:
            "A noun or gerund phrase describing what you are thankful for",
          description_bn:
            "একটি বিশেষ্য বা ক্রিয়াবাচক বিশেষ্য পদবন্ধ যা আপনি কিসের জন্য কৃতজ্ঞ তা বর্ণনা করে",
          acceptedTypes: ["noun", "gerund"],
          examples: ["your help", "coming", "the gift"],
        },
      ],
      examples: [
        {
          en: "Thank you for your help.",
          bn: "আপনার সাহায্যের জন্য ধন্যবাদ।",
          slotValues: { "THING/DOING": "your help" },
          topicArea: "daily_life",
        },
        {
          en: "Thank you for coming to the meeting.",
          bn: "মিটিংয়ে আসার জন্য ধন্যবাদ।",
          slotValues: { "THING/DOING": "coming to the meeting" },
          topicArea: "work",
        },
        {
          en: "Thank you for the lovely gift.",
          bn: "সুন্দর উপহারের জন্য ধন্যবাদ।",
          slotValues: { "THING/DOING": "the lovely gift" },
          topicArea: "relationships",
        },
        {
          en: "Thank you for teaching me.",
          bn: "আমাকে শেখানোর জন্য ধন্যবাদ।",
          slotValues: { "THING/DOING": "teaching me" },
          topicArea: "education",
        },
        {
          en: "Thank you for the delicious dinner.",
          bn: "সুস্বাদু ডিনারের জন্য ধন্যবাদ।",
          slotValues: { "THING/DOING": "the delicious dinner" },
          topicArea: "food",
        },
        {
          en: "Thank you for taking care of me.",
          bn: "আমার যত্ন নেওয়ার জন্য ধন্যবাদ।",
          slotValues: { "THING/DOING": "taking care of me" },
          topicArea: "health",
        },
        {
          en: "Thank you for the ride to the airport.",
          bn: "বিমানবন্দরে পৌঁছে দেওয়ার জন্য ধন্যবাদ।",
          slotValues: { "THING/DOING": "the ride to the airport" },
          topicArea: "travel",
        },
        {
          en: "Thank you for waiting so patiently.",
          bn: "এত ধৈর্য ধরে অপেক্ষা করার জন্য ধন্যবাদ।",
          slotValues: { "THING/DOING": "waiting so patiently" },
          topicArea: "daily_life",
        },
        {
          en: "Thank you for helping me find the right size.",
          bn: "সঠিক সাইজ খুঁজে পেতে সাহায্য করার জন্য ধন্যবাদ।",
          slotValues: { "THING/DOING": "helping me find the right size" },
          topicArea: "shopping",
        },
        {
          en: "Thank you for your support during the project.",
          bn: "প্রজেক্টের সময় আপনার সহযোগিতার জন্য ধন্যবাদ।",
          slotValues: { "THING/DOING": "your support during the project" },
          topicArea: "work",
        },
        {
          en: "Thank you for being such a good friend.",
          bn: "এত ভালো বন্ধু হওয়ার জন্য ধন্যবাদ।",
          slotValues: { "THING/DOING": "being such a good friend" },
          topicArea: "relationships",
        },
        {
          en: "Thank you for the recommendation.",
          bn: "সুপারিশের জন্য ধন্যবাদ।",
          slotValues: { "THING/DOING": "the recommendation" },
          topicArea: "work",
        },
        {
          en: "Thank you for showing us around the city.",
          bn: "আমাদের শহর ঘুরিয়ে দেখানোর জন্য ধন্যবাদ।",
          slotValues: { "THING/DOING": "showing us around the city" },
          topicArea: "travel",
        },
        {
          en: "Thank you for lending me the book.",
          bn: "আমাকে বইটি ধার দেওয়ার জন্য ধন্যবাদ।",
          slotValues: { "THING/DOING": "lending me the book" },
          topicArea: "education",
        },
        {
          en: "Thank you for the medicine. I feel much better.",
          bn: "ওষুধের জন্য ধন্যবাদ। আমি অনেক ভালো বোধ করছি।",
          slotValues: { "THING/DOING": "the medicine" },
          topicArea: "health",
        },
      ],
      formality: "polite",
      difficulty: "beginner",
      usageNote:
        "The most common way to express gratitude. Adding what you're thankful for makes it more personal and sincere.",
      usageNote_bn:
        "কৃতজ্ঞতা প্রকাশের সবচেয়ে সাধারণ উপায়। কিসের জন্য কৃতজ্ঞ তা যোগ করলে এটি আরও ব্যক্তিগত ও আন্তরিক হয়।",
      combinableWith: ["H4.2"],
      responsePatterns: ["H4.3"],
      banglaStructureMap:
        "[THING/DOING]-এর জন্য (For thing) + ধন্যবাদ (Thank you)",
    },
    {
      id: "H4.2",
      formula: "I appreciate [THING]",
      formula_bn: "আমি [জিনিসের] প্রশংসা করি / [জিনিসকে] মূল্যায়ন করি",
      patternName: "Expressing Appreciation",
      patternName_bn: "প্রশংসা প্রকাশ",
      slots: [
        {
          name: "THING",
          description:
            "A noun or gerund describing what you appreciate",
          description_bn:
            "একটি বিশেষ্য বা ক্রিয়াবাচক বিশেষ্য যা আপনি প্রশংসা করেন তা বর্ণনা করে",
          acceptedTypes: ["noun", "gerund"],
          examples: ["your honesty", "the effort", "you helping me"],
        },
      ],
      examples: [
        {
          en: "I appreciate your honesty.",
          bn: "আমি আপনার সততার প্রশংসা করি।",
          slotValues: { THING: "your honesty" },
          topicArea: "relationships",
        },
        {
          en: "I appreciate the effort you put in.",
          bn: "আপনি যে পরিশ্রম করেছেন তার প্রশংসা করি।",
          slotValues: { THING: "the effort you put in" },
          topicArea: "work",
        },
        {
          en: "I appreciate you helping me with the assignment.",
          bn: "অ্যাসাইনমেন্টে আমাকে সাহায্য করার জন্য আপনাকে ধন্যবাদ।",
          slotValues: { THING: "you helping me with the assignment" },
          topicArea: "education",
        },
        {
          en: "I appreciate your patience.",
          bn: "আমি আপনার ধৈর্যের প্রশংসা করি।",
          slotValues: { THING: "your patience" },
          topicArea: "daily_life",
        },
        {
          en: "I appreciate the home-cooked meal.",
          bn: "আমি ঘরে রান্না করা খাবারের প্রশংসা করি।",
          slotValues: { THING: "the home-cooked meal" },
          topicArea: "food",
        },
        {
          en: "I appreciate you coming with me to the doctor.",
          bn: "আমার সাথে ডাক্তারের কাছে আসার জন্য আপনাকে ধন্যবাদ।",
          slotValues: { THING: "you coming with me to the doctor" },
          topicArea: "health",
        },
        {
          en: "I appreciate the travel tips you gave me.",
          bn: "আপনি যে ভ্রমণ পরামর্শ দিয়েছেন তার প্রশংসা করি।",
          slotValues: { THING: "the travel tips you gave me" },
          topicArea: "travel",
        },
        {
          en: "I appreciate your hard work on this project.",
          bn: "এই প্রজেক্টে আপনার পরিশ্রমের প্রশংসা করি।",
          slotValues: { THING: "your hard work on this project" },
          topicArea: "work",
        },
        {
          en: "I appreciate the discount you offered.",
          bn: "আপনি যে ছাড় দিয়েছেন তার প্রশংসা করি।",
          slotValues: { THING: "the discount you offered" },
          topicArea: "shopping",
        },
        {
          en: "I appreciate everything you've done for me.",
          bn: "আপনি আমার জন্য যা কিছু করেছেন সবকিছুর প্রশংসা করি।",
          slotValues: { THING: "everything you've done for me" },
          topicArea: "relationships",
        },
        {
          en: "I appreciate the feedback on my essay.",
          bn: "আমার প্রবন্ধের মতামতের প্রশংসা করি।",
          slotValues: { THING: "the feedback on my essay" },
          topicArea: "education",
        },
        {
          en: "I appreciate your kindness.",
          bn: "আমি আপনার দয়ার প্রশংসা করি।",
          slotValues: { THING: "your kindness" },
          topicArea: "daily_life",
        },
        {
          en: "I appreciate you looking after the house while I was away.",
          bn: "আমি দূরে থাকাকালীন বাড়ির দেখাশোনা করার জন্য আপনাকে ধন্যবাদ।",
          slotValues: { THING: "you looking after the house while I was away" },
          topicArea: "travel",
        },
        {
          en: "I appreciate the concern about my health.",
          bn: "আমার স্বাস্থ্য নিয়ে উদ্বেগের প্রশংসা করি।",
          slotValues: { THING: "the concern about my health" },
          topicArea: "health",
        },
        {
          en: "I appreciate you staying late to finish the work.",
          bn: "কাজ শেষ করার জন্য দেরি পর্যন্ত থাকার জন্য আপনাকে ধন্যবাদ।",
          slotValues: { THING: "you staying late to finish the work" },
          topicArea: "work",
        },
      ],
      formality: "polite",
      difficulty: "beginner",
      usageNote:
        "'I appreciate' sounds slightly more formal and heartfelt than 'thank you'. Great for professional settings.",
      usageNote_bn:
        "'I appreciate' 'thank you'-এর চেয়ে কিছুটা বেশি আনুষ্ঠানিক ও আন্তরিক শোনায়। পেশাদার পরিবেশের জন্য দুর্দান্ত।",
      combinableWith: ["H4.1"],
      banglaStructureMap:
        "আমি (Subject) + [THING]-এর (Object) + প্রশংসা করি (Verb)",
    },
    {
      id: "H4.3",
      formula: "You're welcome",
      formula_bn: "আপনাকে স্বাগতম / কিছু না",
      patternName: "Responding to Thanks (Formal)",
      patternName_bn: "ধন্যবাদের সাড়া (আনুষ্ঠানিক)",
      slots: [],
      examples: [
        {
          en: "You're welcome!",
          bn: "আপনাকে স্বাগতম!",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "You're welcome. Happy to help.",
          bn: "কিছু না। সাহায্য করে খুশি হলাম।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "You're welcome. It was a great team effort.",
          bn: "কিছু না। এটা দারুণ দলগত প্রচেষ্টা ছিল।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "You're welcome. I enjoyed cooking for you.",
          bn: "কিছু না। আপনার জন্য রান্না করে আমি মজা পেয়েছি।",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "You're welcome. That's what friends are for.",
          bn: "কিছু না। বন্ধু তো এজন্যই থাকে।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "You're welcome. I'm glad you're feeling better.",
          bn: "কিছু না। আপনি ভালো অনুভব করছেন জেনে খুশি হলাম।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "You're welcome. I hope the trip goes well.",
          bn: "কিছু না। আশা করি ভ্রমণ ভালো হবে।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "You're welcome. Come back anytime.",
          bn: "আপনাকে স্বাগতম। যেকোনো সময় আবার আসবেন।",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "You're welcome. Good luck with the exam!",
          bn: "কিছু না। পরীক্ষার জন্য শুভকামনা!",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "You're welcome. It was my pleasure to help.",
          bn: "কিছু না। সাহায্য করতে পেরে আমার আনন্দ হয়েছে।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "You're welcome. Let me know if you need anything else.",
          bn: "কিছু না। আর কিছু লাগলে জানাবেন।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "You're welcome. It was no trouble at all.",
          bn: "কিছু না। এতে কোনো কষ্ট হয়নি।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "You're welcome. Anytime!",
          bn: "কিছু না। যেকোনো সময়!",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "You're welcome. I hope the notes were helpful.",
          bn: "কিছু না। আশা করি নোটগুলো কাজে লেগেছে।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "You're welcome. Take care of your health.",
          bn: "কিছু না। আপনার স্বাস্থ্যের যত্ন নিন।",
          slotValues: {},
          topicArea: "health",
        },
      ],
      formality: "polite",
      difficulty: "beginner",
      usageNote:
        "The standard response to 'thank you'. Polite and universally appropriate in any setting.",
      usageNote_bn:
        "'Thank you'-এর মানসম্মত উত্তর। ভদ্র এবং যেকোনো পরিস্থিতিতে উপযুক্ত।",
      banglaStructureMap: "আপনাকে স্বাগতম (You're welcome)",
    },
    {
      id: "H4.4",
      formula: "No problem",
      formula_bn: "কোনো সমস্যা নেই",
      patternName: "Casual Response to Thanks",
      patternName_bn: "ধন্যবাদের অনানুষ্ঠানিক সাড়া",
      slots: [],
      examples: [
        {
          en: "No problem!",
          bn: "কোনো সমস্যা নেই!",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "No problem. I was heading that way anyway.",
          bn: "কোনো সমস্যা নেই। আমি ওদিকেই যাচ্ছিলাম।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "No problem at all. Glad I could help.",
          bn: "একদম কোনো সমস্যা নেই। সাহায্য করতে পেরে খুশি।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "No problem. We're a team, after all.",
          bn: "কোনো সমস্যা নেই। আমরা তো একটি দল।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "No problem. The recipe was easy.",
          bn: "কোনো সমস্যা নেই। রেসিপিটা সহজ ছিল।",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "No problem. That's what siblings do.",
          bn: "কোনো সমস্যা নেই। ভাইবোন তো এজন্যই থাকে।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "No problem. I hope the medicine works.",
          bn: "কোনো সমস্যা নেই। আশা করি ওষুধ কাজ করবে।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "No problem. I'll send you the study materials too.",
          bn: "কোনো সমস্যা নেই। আমি আপনাকে পড়ার উপকরণও পাঠাব।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "No problem. It only took a few minutes.",
          bn: "কোনো সমস্যা নেই। মাত্র কয়েক মিনিট লেগেছে।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "No problem. I can carry the bags for you.",
          bn: "কোনো সমস্যা নেই। আমি আপনার ব্যাগ বহন করতে পারি।",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "No problem. I enjoy explaining things.",
          bn: "কোনো সমস্যা নেই। আমি জিনিস ব্যাখ্যা করতে উপভোগ করি।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "No problem. I'll cover for you at work.",
          bn: "কোনো সমস্যা নেই। আমি অফিসে আপনার হয়ে সামলাব।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "No problem. Just let me know next time too.",
          bn: "কোনো সমস্যা নেই। পরের বারও জানাবেন।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "No problem. Happy to drive you to the station.",
          bn: "কোনো সমস্যা নেই। স্টেশনে পৌঁছে দিতে পেরে খুশি।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "No problem. Rest well and feel better soon.",
          bn: "কোনো সমস্যা নেই। ভালো করে বিশ্রাম নিন আর তাড়াতাড়ি সুস্থ হোন।",
          slotValues: {},
          topicArea: "health",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "A relaxed, informal response to thanks. Very common among younger speakers and in casual settings.",
      usageNote_bn:
        "ধন্যবাদের একটি স্বচ্ছন্দ, অনানুষ্ঠানিক সাড়া। তরুণ বক্তাদের মধ্যে এবং অনানুষ্ঠানিক পরিবেশে খুবই সাধারণ।",
      banglaStructureMap: "কোনো (Any) + সমস্যা (Problem) + নেই (Not)",
    },
    {
      id: "H4.5",
      formula: "My pleasure",
      formula_bn: "আমার আনন্দ / সৌভাগ্য আমার",
      patternName: "Gracious Response to Thanks",
      patternName_bn: "ধন্যবাদের সৌজন্যমূলক সাড়া",
      slots: [],
      examples: [
        {
          en: "My pleasure!",
          bn: "আমার আনন্দ!",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "My pleasure. It was a wonderful evening.",
          bn: "আমার আনন্দ। দারুণ একটা সন্ধ্যা ছিল।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "My pleasure. I'm always happy to help colleagues.",
          bn: "আমার আনন্দ। সহকর্মীদের সাহায্য করতে সবসময় খুশি।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "My pleasure. I love sharing recipes.",
          bn: "আমার আনন্দ। রেসিপি শেয়ার করতে আমি ভালোবাসি।",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "My pleasure. I hope you enjoy the tour.",
          bn: "আমার আনন্দ। আশা করি ট্যুর উপভোগ করবেন।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "My pleasure. Teaching is what I love.",
          bn: "আমার আনন্দ। পড়ানো আমার ভালোবাসার কাজ।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "My pleasure. Get well soon!",
          bn: "আমার আনন্দ। তাড়াতাড়ি সুস্থ হোন!",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "My pleasure. We should do this more often.",
          bn: "আমার আনন্দ। আমাদের এটা আরও বেশি করা উচিত।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "My pleasure. Let me know if you need a different size.",
          bn: "আমার আনন্দ। অন্য সাইজ লাগলে জানাবেন।",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "My pleasure. The presentation went well because of your input.",
          bn: "আমার আনন্দ। আপনার মতামতের কারণে প্রেজেন্টেশনটা ভালো হয়েছে।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "My pleasure. I enjoyed helping with the project.",
          bn: "আমার আনন্দ। প্রজেক্টে সাহায্য করে আনন্দ পেয়েছি।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "My pleasure. I'm glad the food was to your liking.",
          bn: "আমার আনন্দ। খুশি হলাম যে খাবার আপনার পছন্দ হয়েছে।",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "My pleasure. I hope the notes helped with your studying.",
          bn: "আমার আনন্দ। আশা করি নোটগুলো পড়াশোনায় কাজে লেগেছে।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "My pleasure. Safe journey home.",
          bn: "আমার আনন্দ। বাড়ি ফেরার শুভ যাত্রা।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "My pleasure. Don't hesitate to ask if you need anything else.",
          bn: "আমার আনন্দ। আর কিছু লাগলে দ্বিধা করবেন না।",
          slotValues: {},
          topicArea: "daily_life",
        },
      ],
      formality: "formal",
      difficulty: "beginner",
      usageNote:
        "'My pleasure' is more elegant and formal than 'no problem'. Often used in hospitality and professional settings.",
      usageNote_bn:
        "'My pleasure' 'no problem'-এর চেয়ে বেশি মার্জিত ও আনুষ্ঠানিক। প্রায়ই আতিথেয়তা ও পেশাদার পরিবেশে ব্যবহৃত হয়।",
      banglaStructureMap: "আমার (My) + আনন্দ (Pleasure)",
    },
    {
      id: "H4.6",
      formula: "Thanks a lot!",
      formula_bn: "অনেক ধন্যবাদ!",
      patternName: "Emphatic Casual Thanks",
      patternName_bn: "জোরালো অনানুষ্ঠানিক ধন্যবাদ",
      slots: [],
      examples: [
        {
          en: "Thanks a lot! I really needed that.",
          bn: "অনেক ধন্যবাদ! আমার সত্যিই এটা দরকার ছিল।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Thanks a lot for the recipe!",
          bn: "রেসিপির জন্য অনেক ধন্যবাদ!",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "Thanks a lot for the ride to the station!",
          bn: "স্টেশনে পৌঁছে দেওয়ার জন্য অনেক ধন্যবাদ!",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "Thanks a lot for explaining that so clearly!",
          bn: "এত পরিষ্কারভাবে ব্যাখ্যা করার জন্য অনেক ধন্যবাদ!",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "Thanks a lot for covering my shift!",
          bn: "আমার শিফট সামলে দেওয়ার জন্য অনেক ধন্যবাদ!",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "Thanks a lot for the advice. I feel much better.",
          bn: "পরামর্শের জন্য অনেক ধন্যবাদ। আমি অনেক ভালো বোধ করছি।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "Thanks a lot for helping me carry the bags!",
          bn: "ব্যাগ বহনে সাহায্য করার জন্য অনেক ধন্যবাদ!",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "Thanks a lot for being such a great friend!",
          bn: "এত ভালো বন্ধু হওয়ার জন্য অনেক ধন্যবাদ!",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "Thanks a lot! You saved my day.",
          bn: "অনেক ধন্যবাদ! তুমি আমার দিনটা বাঁচিয়ে দিলে।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Thanks a lot for the delicious dinner!",
          bn: "সুস্বাদু ডিনারের জন্য অনেক ধন্যবাদ!",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "Thanks a lot for the travel tips!",
          bn: "ভ্রমণ পরামর্শের জন্য অনেক ধন্যবাদ!",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "Thanks a lot for lending me the notes!",
          bn: "নোট ধার দেওয়ার জন্য অনেক ধন্যবাদ!",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "Thanks a lot for the recommendation!",
          bn: "সুপারিশের জন্য অনেক ধন্যবাদ!",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "Thanks a lot for taking care of me when I was sick!",
          bn: "আমি অসুস্থ থাকাকালীন যত্ন নেওয়ার জন্য অনেক ধন্যবাদ!",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "Thanks a lot for always being there for me!",
          bn: "সবসময় আমার পাশে থাকার জন্য অনেক ধন্যবাদ!",
          slotValues: {},
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "'Thanks a lot' is a warmer, more enthusiastic version of 'thank you'. It's casual and commonly used among friends and family.",
      usageNote_bn:
        "'Thanks a lot' 'thank you'-এর একটি উষ্ণতর, বেশি উৎসাহী সংস্করণ। এটি অনানুষ্ঠানিক এবং বন্ধু ও পরিবারের মধ্যে সাধারণত ব্যবহৃত হয়।",
      combinableWith: ["H4.1"],
      banglaStructureMap: "অনেক (A lot) + ধন্যবাদ (Thanks)",
    },
  ],
};
