import { PatternCategory } from "@/types/pattern";

export const categoryH5: PatternCategory = {
  id: "H5",
  slug: "apologizing-responding",
  name: "Apologizing & Responding",
  name_bn: "ক্ষমা চাওয়া ও সাড়া দেওয়া",
  description:
    "Learn how to apologize sincerely and respond to apologies gracefully in English.",
  description_bn:
    "ইংরেজিতে আন্তরিকভাবে ক্ষমা চাইতে এবং সুন্দরভাবে ক্ষমার সাড়া দিতে শিখুন।",
  icon: "😊",
  group: "H",
  groupName: "Social Interactions",
  groupName_bn: "সামাজিক যোগাযোগ",
  difficulty: "beginner",
  patterns: [
    {
      id: "H5.1",
      formula: "I'm sorry for [THING/DOING]",
      formula_bn: "[জিনিস/করার] জন্য আমি দুঃখিত",
      patternName: "Basic Apology",
      patternName_bn: "সাধারণ ক্ষমা প্রার্থনা",
      slots: [
        {
          name: "THING/DOING",
          description:
            "A noun or gerund phrase describing what you are apologizing for",
          description_bn:
            "একটি বিশেষ্য বা ক্রিয়াবাচক বিশেষ্য পদবন্ধ যা কিসের জন্য ক্ষমা চাইছেন তা বর্ণনা করে",
          acceptedTypes: ["noun", "gerund"],
          examples: ["being late", "the mistake", "bothering you"],
        },
      ],
      examples: [
        {
          en: "I'm sorry for being late.",
          bn: "দেরি করার জন্য আমি দুঃখিত।",
          slotValues: { "THING/DOING": "being late" },
          topicArea: "daily_life",
        },
        {
          en: "I'm sorry for the mistake in the report.",
          bn: "রিপোর্টের ভুলের জন্য আমি দুঃখিত।",
          slotValues: { "THING/DOING": "the mistake in the report" },
          topicArea: "work",
        },
        {
          en: "I'm sorry for forgetting your birthday.",
          bn: "তোমার জন্মদিন ভুলে যাওয়ার জন্য আমি দুঃখিত।",
          slotValues: { "THING/DOING": "forgetting your birthday" },
          topicArea: "relationships",
        },
        {
          en: "I'm sorry for missing the class.",
          bn: "ক্লাস মিস করার জন্য আমি দুঃখিত।",
          slotValues: { "THING/DOING": "missing the class" },
          topicArea: "education",
        },
        {
          en: "I'm sorry for the noise.",
          bn: "শব্দের জন্য আমি দুঃখিত।",
          slotValues: { "THING/DOING": "the noise" },
          topicArea: "daily_life",
        },
        {
          en: "I'm sorry for canceling the reservation.",
          bn: "রিজার্ভেশন বাতিল করার জন্য আমি দুঃখিত।",
          slotValues: { "THING/DOING": "canceling the reservation" },
          topicArea: "food",
        },
        {
          en: "I'm sorry for not calling you back sooner.",
          bn: "তাড়াতাড়ি ফোন ফেরত না দেওয়ার জন্য আমি দুঃখিত।",
          slotValues: { "THING/DOING": "not calling you back sooner" },
          topicArea: "relationships",
        },
        {
          en: "I'm sorry for the delay in the delivery.",
          bn: "ডেলিভারি দেরি হওয়ার জন্য আমি দুঃখিত।",
          slotValues: { "THING/DOING": "the delay in the delivery" },
          topicArea: "shopping",
        },
        {
          en: "I'm sorry for missing the appointment.",
          bn: "অ্যাপয়েন্টমেন্ট মিস করার জন্য আমি দুঃখিত।",
          slotValues: { "THING/DOING": "missing the appointment" },
          topicArea: "health",
        },
        {
          en: "I'm sorry for changing the travel plans last minute.",
          bn: "শেষ মুহূর্তে ভ্রমণ পরিকল্পনা পরিবর্তনের জন্য আমি দুঃখিত।",
          slotValues: { "THING/DOING": "changing the travel plans last minute" },
          topicArea: "travel",
        },
        {
          en: "I'm sorry for the inconvenience.",
          bn: "অসুবিধার জন্য আমি দুঃখিত।",
          slotValues: { "THING/DOING": "the inconvenience" },
          topicArea: "daily_life",
        },
        {
          en: "I'm sorry for not submitting the assignment on time.",
          bn: "সময়মতো অ্যাসাইনমেন্ট জমা না দেওয়ার জন্য আমি দুঃখিত।",
          slotValues: { "THING/DOING": "not submitting the assignment on time" },
          topicArea: "education",
        },
        {
          en: "I'm sorry for raising my voice.",
          bn: "গলা তোলার জন্য আমি দুঃখিত।",
          slotValues: { "THING/DOING": "raising my voice" },
          topicArea: "relationships",
        },
        {
          en: "I'm sorry for the confusion about the order.",
          bn: "অর্ডার নিয়ে বিভ্রান্তির জন্য আমি দুঃখিত।",
          slotValues: { "THING/DOING": "the confusion about the order" },
          topicArea: "shopping",
        },
        {
          en: "I'm sorry for not finishing the work on time.",
          bn: "সময়মতো কাজ শেষ না করার জন্য আমি দুঃখিত।",
          slotValues: { "THING/DOING": "not finishing the work on time" },
          topicArea: "work",
        },
      ],
      formality: "polite",
      difficulty: "beginner",
      usageNote:
        "The most common apology pattern. Adding the specific reason makes it more sincere and meaningful.",
      usageNote_bn:
        "সবচেয়ে সাধারণ ক্ষমা প্রার্থনার প্যাটার্ন। নির্দিষ্ট কারণ যোগ করলে এটি আরও আন্তরিক ও অর্থবহ হয়।",
      combinableWith: ["H5.2"],
      responsePatterns: ["H5.3"],
      banglaStructureMap:
        "[THING/DOING]-এর জন্য (For thing) + আমি (I) + দুঃখিত (Sorry)",
    },
    {
      id: "H5.2",
      formula: "I apologize for [THING]",
      formula_bn: "[জিনিসের] জন্য আমি ক্ষমাপ্রার্থী",
      patternName: "Formal Apology",
      patternName_bn: "আনুষ্ঠানিক ক্ষমা প্রার্থনা",
      slots: [
        {
          name: "THING",
          description:
            "A noun or gerund phrase describing what you are formally apologizing for",
          description_bn:
            "একটি বিশেষ্য বা ক্রিয়াবাচক বিশেষ্য পদবন্ধ যা আনুষ্ঠানিকভাবে কিসের জন্য ক্ষমা চাইছেন তা বর্ণনা করে",
          acceptedTypes: ["noun", "gerund"],
          examples: [
            "the misunderstanding",
            "any inconvenience",
            "the error",
          ],
        },
      ],
      examples: [
        {
          en: "I apologize for the misunderstanding.",
          bn: "ভুল বোঝাবুঝির জন্য আমি ক্ষমাপ্রার্থী।",
          slotValues: { THING: "the misunderstanding" },
          topicArea: "daily_life",
        },
        {
          en: "I apologize for any inconvenience caused.",
          bn: "যেকোনো অসুবিধার জন্য আমি ক্ষমাপ্রার্থী।",
          slotValues: { THING: "any inconvenience caused" },
          topicArea: "work",
        },
        {
          en: "I apologize for the error in the invoice.",
          bn: "চালানের ভুলের জন্য আমি ক্ষমাপ্রার্থী।",
          slotValues: { THING: "the error in the invoice" },
          topicArea: "shopping",
        },
        {
          en: "I apologize for not informing you earlier.",
          bn: "আপনাকে আগে জানাতে না পারার জন্য আমি ক্ষমাপ্রার্থী।",
          slotValues: { THING: "not informing you earlier" },
          topicArea: "work",
        },
        {
          en: "I apologize for the poor service.",
          bn: "খারাপ সেবার জন্য আমি ক্ষমাপ্রার্থী।",
          slotValues: { THING: "the poor service" },
          topicArea: "food",
        },
        {
          en: "I apologize for the scheduling conflict.",
          bn: "সময়সূচির সমস্যার জন্য আমি ক্ষমাপ্রার্থী।",
          slotValues: { THING: "the scheduling conflict" },
          topicArea: "health",
        },
        {
          en: "I apologize for my behavior.",
          bn: "আমার আচরণের জন্য আমি ক্ষমাপ্রার্থী।",
          slotValues: { THING: "my behavior" },
          topicArea: "relationships",
        },
        {
          en: "I apologize for the flight delay.",
          bn: "ফ্লাইট বিলম্বের জন্য আমি ক্ষমাপ্রার্থী।",
          slotValues: { THING: "the flight delay" },
          topicArea: "travel",
        },
        {
          en: "I apologize for the late response to your email.",
          bn: "আপনার ইমেইলের দেরিতে উত্তর দেওয়ার জন্য আমি ক্ষমাপ্রার্থী।",
          slotValues: { THING: "the late response to your email" },
          topicArea: "work",
        },
        {
          en: "I apologize for disrupting the class.",
          bn: "ক্লাসে বিঘ্ন ঘটানোর জন্য আমি ক্ষমাপ্রার্থী।",
          slotValues: { THING: "disrupting the class" },
          topicArea: "education",
        },
        {
          en: "I apologize for the wrong order.",
          bn: "ভুল অর্ডারের জন্য আমি ক্ষমাপ্রার্থী।",
          slotValues: { THING: "the wrong order" },
          topicArea: "food",
        },
        {
          en: "I apologize for the oversight.",
          bn: "অমনোযোগের জন্য আমি ক্ষমাপ্রার্থী।",
          slotValues: { THING: "the oversight" },
          topicArea: "work",
        },
        {
          en: "I apologize for the lack of communication.",
          bn: "যোগাযোগের অভাবের জন্য আমি ক্ষমাপ্রার্থী।",
          slotValues: { THING: "the lack of communication" },
          topicArea: "relationships",
        },
        {
          en: "I apologize for the wait at the hospital.",
          bn: "হাসপাতালে অপেক্ষা করানোর জন্য আমি ক্ষমাপ্রার্থী।",
          slotValues: { THING: "the wait at the hospital" },
          topicArea: "health",
        },
        {
          en: "I apologize for not meeting the deadline.",
          bn: "সময়সীমা পূরণ না করার জন্য আমি ক্ষমাপ্রার্থী।",
          slotValues: { THING: "not meeting the deadline" },
          topicArea: "education",
        },
      ],
      formality: "formal",
      difficulty: "beginner",
      usageNote:
        "'I apologize' is more formal than 'I'm sorry'. Best used in professional, business, or official contexts.",
      usageNote_bn:
        "'I apologize' 'I'm sorry'-এর চেয়ে বেশি আনুষ্ঠানিক। পেশাদার, ব্যবসায়িক বা সরকারি প্রসঙ্গে সর্বোত্তম।",
      combinableWith: ["H5.1"],
      banglaStructureMap:
        "[THING]-এর জন্য (For thing) + আমি (I) + ক্ষমাপ্রার্থী (Apologize)",
    },
    {
      id: "H5.3",
      formula: "That's okay",
      formula_bn: "ঠিক আছে / কোনো সমস্যা নেই",
      patternName: "Accepting an Apology",
      patternName_bn: "ক্ষমা গ্রহণ করা",
      slots: [],
      examples: [
        {
          en: "That's okay.",
          bn: "ঠিক আছে।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "That's okay. Everyone makes mistakes.",
          bn: "ঠিক আছে। সবাই ভুল করে।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "That's okay. I understand you were busy.",
          bn: "ঠিক আছে। আমি বুঝতে পারছি আপনি ব্যস্ত ছিলেন।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "That's okay. We can reschedule the appointment.",
          bn: "ঠিক আছে। আমরা অ্যাপয়েন্টমেন্ট পুনঃনির্ধারণ করতে পারি।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "That's okay. The food was still delicious.",
          bn: "ঠিক আছে। খাবার তখনও সুস্বাদু ছিল।",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "That's okay. You can submit it tomorrow.",
          bn: "ঠিক আছে। আগামীকাল জমা দিতে পারবেন।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "That's okay. We still have time to fix it.",
          bn: "ঠিক আছে। ঠিক করার এখনও সময় আছে।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "That's okay. It could happen to anyone.",
          bn: "ঠিক আছে। এটা যে কারো সাথে হতে পারে।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "That's okay. We'll find another hotel.",
          bn: "ঠিক আছে। আমরা অন্য হোটেল খুঁজব।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "That's okay. I can exchange it for another one.",
          bn: "ঠিক আছে। আমি এটা অন্যটার সাথে বদলে নিতে পারি।",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "That's okay. Let's not worry about it.",
          bn: "ঠিক আছে। এটা নিয়ে চিন্তা করি না।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "That's okay. I know it wasn't intentional.",
          bn: "ঠিক আছে। আমি জানি এটা ইচ্ছাকৃত ছিল না।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "That's okay. The delay wasn't too long.",
          bn: "ঠিক আছে। দেরিটা খুব বেশি ছিল না।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "That's okay. Just make sure to check next time.",
          bn: "ঠিক আছে। শুধু পরের বার যাচাই করবেন।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "That's okay. I appreciate you telling me.",
          bn: "ঠিক আছে। আমাকে জানানোর জন্য ধন্যবাদ।",
          slotValues: {},
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "A kind and reassuring way to accept an apology. Shows the person you are not upset.",
      usageNote_bn:
        "ক্ষমা গ্রহণের একটি সদয় ও আশ্বাসমূলক উপায়। ব্যক্তিকে দেখায় যে আপনি রাগান্বিত নন।",
      banglaStructureMap: "ঠিক (Fine) + আছে (Is)",
    },
    {
      id: "H5.4",
      formula: "Don't worry about it",
      formula_bn: "এটা নিয়ে চিন্তা করবেন না",
      patternName: "Dismissing the Need for Apology",
      patternName_bn: "ক্ষমার প্রয়োজন নেই বলা",
      slots: [],
      examples: [
        {
          en: "Don't worry about it.",
          bn: "এটা নিয়ে চিন্তা করবেন না।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Don't worry about it. These things happen.",
          bn: "এটা নিয়ে চিন্তা করবেন না। এসব তো হয়ই।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Don't worry about it. The project is still on track.",
          bn: "এটা নিয়ে চিন্তা করবেন না। প্রজেক্ট এখনও ঠিক আছে।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "Don't worry about it. I wasn't waiting long.",
          bn: "এটা নিয়ে চিন্তা করবেন না। আমি বেশিক্ষণ অপেক্ষা করিনি।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Don't worry about it. The exam can be retaken.",
          bn: "এটা নিয়ে চিন্তা করবেন না। পরীক্ষা আবার দেওয়া যাবে।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "Don't worry about it. I'll cook something else.",
          bn: "এটা নিয়ে চিন্তা করো না। আমি অন্য কিছু রান্না করব।",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "Don't worry about it. I know you had a health issue.",
          bn: "এটা নিয়ে চিন্তা করবেন না। আমি জানি আপনার স্বাস্থ্য সমস্যা ছিল।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "Don't worry about it. We can change the tickets.",
          bn: "এটা নিয়ে চিন্তা করো না। আমরা টিকিট পরিবর্তন করতে পারি।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "Don't worry about it. I've already forgotten.",
          bn: "এটা নিয়ে চিন্তা করো না। আমি ইতোমধ্যে ভুলে গেছি।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "Don't worry about it. We can return it to the store.",
          bn: "এটা নিয়ে চিন্তা করো না। আমরা দোকানে ফেরত দিতে পারি।",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "Don't worry about it. It's just a small scratch.",
          bn: "এটা নিয়ে চিন্তা করো না। এটা শুধু ছোট একটা আঁচড়।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Don't worry about it. You'll do better next time.",
          bn: "এটা নিয়ে চিন্তা করো না। পরের বার আরও ভালো করবে।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "Don't worry about it. I have a spare copy.",
          bn: "এটা নিয়ে চিন্তা করবেন না। আমার কাছে একটা অতিরিক্ত কপি আছে।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "Don't worry about it. We're family.",
          bn: "এটা নিয়ে চিন্তা করো না। আমরা তো পরিবার।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "Don't worry about it. Your health comes first.",
          bn: "এটা নিয়ে চিন্তা করবেন না। আপনার স্বাস্থ্যই আগে।",
          slotValues: {},
          topicArea: "health",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "A warm, casual way to tell someone their apology is unnecessary. Makes the person feel at ease.",
      usageNote_bn:
        "কাউকে বলার একটি উষ্ণ, অনানুষ্ঠানিক উপায় যে তাদের ক্ষমা প্রার্থনার প্রয়োজন নেই। ব্যক্তিকে স্বস্তি দেয়।",
      banglaStructureMap:
        "এটা নিয়ে (About it) + চিন্তা (Worry) + করবেন না (Don't do)",
    },
    {
      id: "H5.5",
      formula: "It happens",
      formula_bn: "এসব তো হয়ই / এটা স্বাভাবিক",
      patternName: "Normalizing the Mistake",
      patternName_bn: "ভুলকে স্বাভাবিক বলা",
      slots: [],
      examples: [
        {
          en: "It happens.",
          bn: "এসব তো হয়ই।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "It happens. No one is perfect.",
          bn: "এসব তো হয়ই। কেউ নিখুঁত নয়।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "It happens. We'll fix it together.",
          bn: "এসব তো হয়ই। আমরা একসাথে ঠিক করব।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "It happens. Don't be too hard on yourself.",
          bn: "এসব তো হয়ই। নিজেকে বেশি দোষ দিয়ো না।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "It happens. Missing a bus isn't the end of the world.",
          bn: "এসব তো হয়ই। একটা বাস মিস করা পৃথিবীর শেষ না।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "It happens. You can retake the test.",
          bn: "এসব তো হয়ই। পরীক্ষা আবার দিতে পারবে।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "It happens. The soup was a little salty, that's all.",
          bn: "এসব তো হয়ই। স্যুপটা একটু লবণাক্ত ছিল, এটুকুই।",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "It happens. Everyone forgets things sometimes.",
          bn: "এসব তো হয়ই। সবাই মাঝে মাঝে জিনিস ভুলে যায়।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "It happens. The appointment can be rescheduled.",
          bn: "এসব তো হয়ই। অ্যাপয়েন্টমেন্ট পুনঃনির্ধারণ করা যাবে।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "It happens. We'll get the right product next time.",
          bn: "এসব তো হয়ই। পরের বার সঠিক পণ্য পাব।",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "It happens. The important thing is you tried.",
          bn: "এসব তো হয়ই। গুরুত্বপূর্ণ বিষয় হলো তুমি চেষ্টা করেছ।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "It happens. We all have bad days at work.",
          bn: "এসব তো হয়ই। কাজে আমাদের সবার খারাপ দিন থাকে।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "It happens. Flights get delayed all the time.",
          bn: "এসব তো হয়ই। ফ্লাইট সব সময়ই দেরি হয়।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "It happens. I'm not upset at all.",
          bn: "এসব তো হয়ই। আমি মোটেও রাগান্বিত নই।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "It happens. Let's just move on.",
          bn: "এসব তো হয়ই। চলো সামনে এগিয়ে যাই।",
          slotValues: {},
          topicArea: "daily_life",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "A very relaxed response that normalizes the mistake. It tells the person that what happened is common and not a big deal.",
      usageNote_bn:
        "একটি খুব স্বচ্ছন্দ সাড়া যা ভুলকে স্বাভাবিক করে। ব্যক্তিকে বলে যে যা হয়েছে তা সাধারণ এবং বড় কিছু নয়।",
      banglaStructureMap: "এসব (These things) + তো হয়ই (Happen)",
    },
  ],
};
