import { PatternCategory } from "@/types/pattern";

export const categoryH6: PatternCategory = {
  id: "H6",
  slug: "making-small-talk",
  name: "Making Small Talk",
  name_bn: "হালকা আলাপ করা",
  description:
    "Learn common English small talk patterns for casual social situations.",
  description_bn:
    "অনানুষ্ঠানিক সামাজিক পরিস্থিতিতে সাধারণ ইংরেজি হালকা আলাপের প্যাটার্ন শিখুন।",
  icon: "☕",
  group: "H",
  groupName: "Social Interactions",
  groupName_bn: "সামাজিক যোগাযোগ",
  difficulty: "beginner",
  patterns: [
    {
      id: "H6.1",
      formula: "How's work going?",
      formula_bn: "কাজ কেমন চলছে?",
      patternName: "Work Small Talk",
      patternName_bn: "কাজ নিয়ে হালকা আলাপ",
      slots: [],
      examples: [
        {
          en: "How's work going?",
          bn: "কাজ কেমন চলছে?",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "How's work going? Are you still at the same company?",
          bn: "কাজ কেমন চলছে? এখনও একই কোম্পানিতে আছো?",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "How's work going? I heard you got a new project.",
          bn: "কাজ কেমন চলছে? শুনলাম নতুন প্রজেক্ট পেয়েছো।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "How's work going these days?",
          bn: "আজকাল কাজ কেমন চলছে?",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "How's work going? Must be busy this time of year.",
          bn: "কাজ কেমন চলছে? বছরের এই সময়ে নিশ্চয়ই ব্যস্ত।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "How's work going? Do you like the new office?",
          bn: "কাজ কেমন চলছে? নতুন অফিস পছন্দ হয়েছে?",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "How's work going since the promotion?",
          bn: "পদোন্নতির পর থেকে কাজ কেমন চলছে?",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "How's work going? Taking any time off soon?",
          bn: "কাজ কেমন চলছে? শীঘ্রই কি ছুটি নিচ্ছো?",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "How's work going? I hope it's not too stressful.",
          bn: "কাজ কেমন চলছে? আশা করি বেশি চাপ নেই।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "How's work going? Any exciting news?",
          bn: "কাজ কেমন চলছে? কোনো উত্তেজনাপূর্ণ খবর আছে?",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "How's work going? I remember you were looking for a change.",
          bn: "কাজ কেমন চলছে? মনে আছে তুমি পরিবর্তন খুঁজছিলে।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "How's work going? Still enjoying the teaching?",
          bn: "কাজ কেমন চলছে? এখনও পড়ানো উপভোগ করছো?",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "How's work going at the restaurant?",
          bn: "রেস্তোরাঁয় কাজ কেমন চলছে?",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "How's work going? Are they treating you well?",
          bn: "কাজ কেমন চলছে? তোমার সাথে ভালো ব্যবহার করছে তো?",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "How's work going? I bet the new shop is keeping you busy.",
          bn: "কাজ কেমন চলছে? নতুন দোকান নিশ্চয়ই তোমাকে ব্যস্ত রাখছে।",
          slotValues: {},
          topicArea: "shopping",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "One of the most popular small talk topics. People usually expect a brief, positive response rather than detailed complaints.",
      usageNote_bn:
        "সবচেয়ে জনপ্রিয় হালকা আলাপের বিষয়গুলোর মধ্যে একটি। মানুষ সাধারণত বিস্তারিত অভিযোগের বদলে সংক্ষিপ্ত, ইতিবাচক উত্তর আশা করে।",
      banglaStructureMap: "কাজ (Work) + কেমন (How) + চলছে (Going)",
    },
    {
      id: "H6.2",
      formula: "Any plans for the weekend?",
      formula_bn: "সপ্তাহান্তে কোনো পরিকল্পনা আছে?",
      patternName: "Weekend Plans Small Talk",
      patternName_bn: "সপ্তাহান্তের পরিকল্পনা নিয়ে আলাপ",
      slots: [],
      examples: [
        {
          en: "Any plans for the weekend?",
          bn: "সপ্তাহান্তে কোনো পরিকল্পনা আছে?",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Any plans for the weekend? The weather looks great.",
          bn: "সপ্তাহান্তে কোনো পরিকল্পনা আছে? আবহাওয়া দারুণ মনে হচ্ছে।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Any plans for the weekend? We should hang out.",
          bn: "সপ্তাহান্তে কোনো পরিকল্পনা আছে? আমাদের দেখা করা উচিত।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "Any plans for the weekend? I'm thinking of going to Cox's Bazar.",
          bn: "সপ্তাহান্তে কোনো পরিকল্পনা আছে? আমি কক্সবাজার যাওয়ার কথা ভাবছি।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "Any plans for the weekend? There's a new restaurant I want to try.",
          bn: "সপ্তাহান্তে কোনো পরিকল্পনা আছে? একটা নতুন রেস্তোরাঁ আছে যেটা চেষ্টা করতে চাই।",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "Any plans for the weekend? I need to study for finals.",
          bn: "সপ্তাহান্তে কোনো পরিকল্পনা আছে? আমাকে ফাইনালের জন্য পড়তে হবে।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "Any plans for the weekend? I was thinking of going to the gym.",
          bn: "সপ্তাহান্তে কোনো পরিকল্পনা আছে? আমি জিমে যাওয়ার কথা ভাবছিলাম।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "Any plans for the weekend? There's a big sale at the mall.",
          bn: "সপ্তাহান্তে কোনো পরিকল্পনা আছে? মলে বড় সেল চলছে।",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "Any plans for the weekend? My family is coming over.",
          bn: "সপ্তাহান্তে কোনো পরিকল্পনা আছে? আমার পরিবার আসছে।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "Any plans for the weekend? I'm just going to relax at home.",
          bn: "সপ্তাহান্তে কোনো পরিকল্পনা আছে? আমি শুধু বাসায় বিশ্রাম নেব।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Any plans for the weekend? Want to join us for a barbecue?",
          bn: "সপ্তাহান্তে কোনো পরিকল্পনা আছে? আমাদের সাথে বারবিকিউতে আসবে?",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "Any plans for the weekend? I heard there's a book fair.",
          bn: "সপ্তাহান্তে কোনো পরিকল্পনা আছে? শুনলাম বইমেলা হচ্ছে।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "Any plans for the weekend? The office is doing a team outing.",
          bn: "সপ্তাহান্তে কোনো পরিকল্পনা আছে? অফিস থেকে টিম আউটিং হচ্ছে।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "Any plans for the weekend? Let's go hiking!",
          bn: "সপ্তাহান্তে কোনো পরিকল্পনা আছে? চলো হাইকিংয়ে যাই!",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "Any plans for the weekend? I need to catch up on sleep.",
          bn: "সপ্তাহান্তে কোনো পরিকল্পনা আছে? আমাকে ঘুমের ঘাটতি পূরণ করতে হবে।",
          slotValues: {},
          topicArea: "health",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "A classic Friday small talk question. It's a great way to show interest in someone's life and can lead to deeper conversations.",
      usageNote_bn:
        "শুক্রবারের একটি ক্লাসিক হালকা আলাপের প্রশ্ন। কারো জীবনে আগ্রহ দেখানোর দুর্দান্ত উপায় এবং এটি গভীর কথোপকথনে নিয়ে যেতে পারে।",
      banglaStructureMap:
        "সপ্তাহান্তে (On weekend) + কোনো (Any) + পরিকল্পনা (Plans) + আছে (Have)",
    },
    {
      id: "H6.3",
      formula: "Beautiful weather, isn't it?",
      formula_bn: "সুন্দর আবহাওয়া, তাই না?",
      patternName: "Weather Small Talk",
      patternName_bn: "আবহাওয়া নিয়ে হালকা আলাপ",
      slots: [],
      examples: [
        {
          en: "Beautiful weather, isn't it?",
          bn: "সুন্দর আবহাওয়া, তাই না?",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Beautiful weather, isn't it? Perfect for a walk.",
          bn: "সুন্দর আবহাওয়া, তাই না? হাঁটার জন্য দারুণ।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "Beautiful weather, isn't it? Great day for a picnic.",
          bn: "সুন্দর আবহাওয়া, তাই না? পিকনিকের জন্য দারুণ দিন।",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "Beautiful weather, isn't it? I love this time of year.",
          bn: "সুন্দর আবহাওয়া, তাই না? বছরের এই সময়টা আমার ভালো লাগে।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Beautiful weather, isn't it? We should go to the beach.",
          bn: "সুন্দর আবহাওয়া, তাই না? আমাদের সমুদ্র সৈকতে যাওয়া উচিত।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "Beautiful weather, isn't it? Much better than last week.",
          bn: "সুন্দর আবহাওয়া, তাই না? গত সপ্তাহের চেয়ে অনেক ভালো।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Beautiful weather, isn't it? Finally some sunshine!",
          bn: "সুন্দর আবহাওয়া, তাই না? অবশেষে একটু রোদ!",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Beautiful weather, isn't it? The kids will love playing outside.",
          bn: "সুন্দর আবহাওয়া, তাই না? বাচ্চারা বাইরে খেলতে পছন্দ করবে।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "Beautiful weather, isn't it? Perfect for outdoor shopping.",
          bn: "সুন্দর আবহাওয়া, তাই না? বাইরে কেনাকাটার জন্য দারুণ।",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "Beautiful weather, isn't it? I hope it stays like this for the trip.",
          bn: "সুন্দর আবহাওয়া, তাই না? আশা করি ভ্রমণের সময়ও এমন থাকবে।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "Beautiful weather, isn't it? Makes me not want to work.",
          bn: "সুন্দর আবহাওয়া, তাই না? কাজ করতে ইচ্ছে করছে না।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "Beautiful weather, isn't it? Good day to study in the garden.",
          bn: "সুন্দর আবহাওয়া, তাই না? বাগানে বসে পড়ার জন্য ভালো দিন।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "Beautiful weather, isn't it? Let's eat outside today.",
          bn: "সুন্দর আবহাওয়া, তাই না? আজ বাইরে খাওয়া যাক।",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "Beautiful weather, isn't it? I hope the weekend is this nice too.",
          bn: "সুন্দর আবহাওয়া, তাই না? আশা করি সপ্তাহান্তেও এত সুন্দর থাকবে।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Beautiful weather, isn't it? It would be great for jogging.",
          bn: "সুন্দর আবহাওয়া, তাই না? জগিংয়ের জন্য দারুণ হবে।",
          slotValues: {},
          topicArea: "health",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Weather is the universal small talk topic. Tag questions ('isn't it?') invite the other person to agree and continue the conversation.",
      usageNote_bn:
        "আবহাওয়া হলো সার্বজনীন হালকা আলাপের বিষয়। ট্যাগ প্রশ্ন ('isn't it?') অন্য ব্যক্তিকে সম্মতি জানাতে এবং কথোপকথন চালিয়ে যেতে আমন্ত্রণ জানায়।",
      banglaStructureMap:
        "সুন্দর (Beautiful) + আবহাওয়া (Weather) + তাই না (Isn't it - Tag)",
    },
    {
      id: "H6.4",
      formula: "Have you been to [PLACE]?",
      formula_bn: "আপনি কি [জায়গায়] গেছেন?",
      patternName: "Place-Based Small Talk",
      patternName_bn: "জায়গা নিয়ে হালকা আলাপ",
      slots: [
        {
          name: "PLACE",
          description:
            "A restaurant, city, attraction, or any location you want to ask about",
          description_bn:
            "একটি রেস্তোরাঁ, শহর, আকর্ষণ, বা যেকোনো স্থান যার সম্পর্কে জিজ্ঞাসা করতে চান",
          acceptedTypes: ["place"],
          examples: [
            "that new café",
            "Cox's Bazar",
            "the bookstore on Main Street",
          ],
        },
      ],
      examples: [
        {
          en: "Have you been to that new café downtown?",
          bn: "শহরের কেন্দ্রে সেই নতুন ক্যাফেতে গেছেন?",
          slotValues: { PLACE: "that new café downtown" },
          topicArea: "food",
        },
        {
          en: "Have you been to Cox's Bazar?",
          bn: "আপনি কি কক্সবাজার গেছেন?",
          slotValues: { PLACE: "Cox's Bazar" },
          topicArea: "travel",
        },
        {
          en: "Have you been to the new shopping mall?",
          bn: "আপনি কি নতুন শপিং মলে গেছেন?",
          slotValues: { PLACE: "the new shopping mall" },
          topicArea: "shopping",
        },
        {
          en: "Have you been to the gym near the office?",
          bn: "অফিসের কাছের জিমে গেছেন?",
          slotValues: { PLACE: "the gym near the office" },
          topicArea: "health",
        },
        {
          en: "Have you been to that Italian restaurant on Park Road?",
          bn: "পার্ক রোডের সেই ইতালীয় রেস্তোরাঁয় গেছেন?",
          slotValues: { PLACE: "that Italian restaurant on Park Road" },
          topicArea: "food",
        },
        {
          en: "Have you been to the Sundarbans?",
          bn: "আপনি কি সুন্দরবন গেছেন?",
          slotValues: { PLACE: "the Sundarbans" },
          topicArea: "travel",
        },
        {
          en: "Have you been to the new library?",
          bn: "আপনি কি নতুন লাইব্রেরিতে গেছেন?",
          slotValues: { PLACE: "the new library" },
          topicArea: "education",
        },
        {
          en: "Have you been to the co-working space near Gulshan?",
          bn: "গুলশানের কাছে কো-ওয়ার্কিং স্পেসে গেছেন?",
          slotValues: { PLACE: "the co-working space near Gulshan" },
          topicArea: "work",
        },
        {
          en: "Have you been to the tea stall by the river?",
          bn: "নদীর ধারে চায়ের দোকানে গেছেন?",
          slotValues: { PLACE: "the tea stall by the river" },
          topicArea: "food",
        },
        {
          en: "Have you been to Srimangal? The tea gardens are beautiful.",
          bn: "আপনি কি শ্রীমঙ্গল গেছেন? চা বাগানগুলো সুন্দর।",
          slotValues: { PLACE: "Srimangal" },
          topicArea: "travel",
        },
        {
          en: "Have you been to the new pharmacy on our street?",
          bn: "আমাদের রাস্তায় নতুন ফার্মেসিতে গেছেন?",
          slotValues: { PLACE: "the new pharmacy on our street" },
          topicArea: "health",
        },
        {
          en: "Have you been to the electronics market in Elephant Road?",
          bn: "এলিফ্যান্ট রোডের ইলেকট্রনিক্স মার্কেটে গেছেন?",
          slotValues: { PLACE: "the electronics market in Elephant Road" },
          topicArea: "shopping",
        },
        {
          en: "Have you been to your cousin's new house?",
          bn: "তোমার কাজিনের নতুন বাড়িতে গেছো?",
          slotValues: { PLACE: "your cousin's new house" },
          topicArea: "relationships",
        },
        {
          en: "Have you been to the training center in Dhanmondi?",
          bn: "ধানমন্ডির ট্রেনিং সেন্টারে গেছেন?",
          slotValues: { PLACE: "the training center in Dhanmondi" },
          topicArea: "education",
        },
        {
          en: "Have you been to the park near our office? It's really nice.",
          bn: "আমাদের অফিসের কাছের পার্কে গেছেন? সত্যিই সুন্দর।",
          slotValues: { PLACE: "the park near our office" },
          topicArea: "work",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "A great way to start a conversation by asking about shared places or new spots. Often leads to recommendations and longer discussions.",
      usageNote_bn:
        "পরিচিত জায়গা বা নতুন স্থান সম্পর্কে জিজ্ঞাসা করে কথোপকথন শুরু করার দুর্দান্ত উপায়। প্রায়ই সুপারিশ ও দীর্ঘ আলোচনায় নিয়ে যায়।",
      banglaStructureMap:
        "আপনি কি (Have you) + [PLACE]-এ (To place) + গেছেন (Been)",
    },
    {
      id: "H6.5",
      formula: "What have you been up to?",
      formula_bn: "তুমি কী করছিলে?",
      patternName: "Activity Inquiry",
      patternName_bn: "কার্যকলাপ জিজ্ঞাসা",
      slots: [],
      examples: [
        {
          en: "What have you been up to? Long time no see!",
          bn: "তুমি কী করছিলে? অনেক দিন দেখা হয়নি!",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "What have you been up to lately?",
          bn: "ইদানীং তুমি কী করছিলে?",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "What have you been up to? Any new recipes?",
          bn: "তুমি কী করছিলে? কোনো নতুন রেসিপি?",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "What have you been up to? Any trips planned?",
          bn: "তুমি কী করছিলে? কোনো ভ্রমণ পরিকল্পনা আছে?",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "What have you been up to since graduation?",
          bn: "স্নাতকের পর থেকে তুমি কী করছিলে?",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "What have you been up to at work?",
          bn: "কাজে তুমি কী করছিলে?",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "What have you been up to? You look so fit!",
          bn: "তুমি কী করছিলে? তোমাকে খুব ফিট দেখাচ্ছে!",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "What have you been up to this weekend?",
          bn: "এই সপ্তাহান্তে তুমি কী করছিলে?",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "What have you been up to? I heard you opened a shop.",
          bn: "তুমি কী করছিলে? শুনলাম তুমি দোকান খুলেছো।",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "What have you been up to? We missed you at dinner.",
          bn: "তুমি কী করছিলে? ডিনারে তোমাকে মিস করেছি।",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "What have you been up to since the last trip?",
          bn: "শেষ ভ্রমণের পর থেকে তুমি কী করছিলে?",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "What have you been up to? Still studying for the exam?",
          bn: "তুমি কী করছিলে? এখনও পরীক্ষার জন্য পড়ছো?",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "What have you been up to? Any new projects?",
          bn: "তুমি কী করছিলে? কোনো নতুন প্রজেক্ট?",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "What have you been up to? I hope you're taking care of yourself.",
          bn: "তুমি কী করছিলে? আশা করি নিজের যত্ন নিচ্ছো।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "What have you been up to? The kids must be keeping you busy!",
          bn: "তুমি কী করছিলে? বাচ্চারা নিশ্চয়ই তোমাকে ব্যস্ত রাখছে!",
          slotValues: {},
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "A friendly, informal way to ask someone about their recent activities. Great for catching up with friends you haven't seen in a while.",
      usageNote_bn:
        "কারো সাম্প্রতিক কার্যকলাপ সম্পর্কে জানতে চাওয়ার একটি বন্ধুত্বপূর্ণ, অনানুষ্ঠানিক উপায়। দীর্ঘদিন পর বন্ধুদের সাথে কথা বলার জন্য দুর্দান্ত।",
      banglaStructureMap:
        "তুমি (Subject) + কী (What) + করছিলে (Have been up to)",
    },
    {
      id: "H6.6",
      formula: "How was your day?",
      formula_bn: "তোমার দিন কেমন ছিল?",
      patternName: "Day Inquiry",
      patternName_bn: "দিন সম্পর্কে জিজ্ঞাসা",
      slots: [],
      examples: [
        {
          en: "How was your day?",
          bn: "তোমার দিন কেমন ছিল?",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "How was your day? Did you eat well?",
          bn: "তোমার দিন কেমন ছিল? ভালো করে খেয়েছো?",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "How was your day? The commute must have been tiring.",
          bn: "তোমার দিন কেমন ছিল? যাতায়াত নিশ্চয়ই ক্লান্তিকর ছিল।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "How was your day at school?",
          bn: "স্কুলে তোমার দিন কেমন ছিল?",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "How was your day at the office?",
          bn: "অফিসে তোমার দিন কেমন ছিল?",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "How was your day? Are you feeling better?",
          bn: "তোমার দিন কেমন ছিল? ভালো লাগছে?",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "How was your day? Did you find anything good at the market?",
          bn: "তোমার দিন কেমন ছিল? বাজারে ভালো কিছু পেয়েছো?",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "How was your day? I missed you.",
          bn: "তোমার দিন কেমন ছিল? তোমাকে মিস করেছি।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "How was your day? You look tired.",
          bn: "তোমার দিন কেমন ছিল? তোমাকে ক্লান্ত দেখাচ্ছে।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "How was your day? Did you try that new restaurant?",
          bn: "তোমার দিন কেমন ছিল? সেই নতুন রেস্তোরাঁ চেষ্টা করেছো?",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "How was your day? How was the road?",
          bn: "তোমার দিন কেমন ছিল? রাস্তা কেমন ছিল?",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "How was your day? Did you learn anything new?",
          bn: "তোমার দিন কেমন ছিল? নতুন কিছু শিখেছো?",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "How was your day? Was the meeting productive?",
          bn: "তোমার দিন কেমন ছিল? মিটিং কি ফলপ্রসূ ছিল?",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "How was your day? I hope you got some rest.",
          bn: "তোমার দিন কেমন ছিল? আশা করি একটু বিশ্রাম নিয়েছো।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "How was your day? Tell me everything!",
          bn: "তোমার দিন কেমন ছিল? সব বলো!",
          slotValues: {},
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "A warm, caring question typically asked between close friends, family, or partners. It shows genuine interest in someone's well-being.",
      usageNote_bn:
        "ঘনিষ্ঠ বন্ধু, পরিবার বা সঙ্গীর মধ্যে সাধারণত জিজ্ঞাসা করা একটি উষ্ণ, যত্নশীল প্রশ্ন। এটি কারো সুস্থতায় প্রকৃত আগ্রহ দেখায়।",
      banglaStructureMap:
        "তোমার (Your) + দিন (Day) + কেমন (How) + ছিল (Was)",
    },
  ],
};
