import { PatternCategory } from "@/types/pattern";

export const categoryH8: PatternCategory = {
  id: "H8",
  slug: "complimenting",
  name: "Complimenting",
  name_bn: "প্রশংসা করা",
  description:
    "Learn natural ways to give compliments in everyday English conversations.",
  description_bn:
    "দৈনন্দিন ইংরেজি কথোপকথনে স্বাভাবিকভাবে প্রশংসা করার উপায় শিখুন।",
  icon: "💐",
  group: "H",
  groupName: "Social Interactions",
  groupName_bn: "সামাজিক যোগাযোগ",
  difficulty: "beginner",
  patterns: [
    {
      id: "H8.1",
      formula: "I like your [THING]!",
      formula_bn: "আমি তোমার [জিনিস] পছন্দ করি!",
      patternName: "Complimenting Possessions or Choices",
      patternName_bn: "জিনিস বা পছন্দের প্রশংসা",
      slots: [
        {
          name: "THING",
          description: "Item, feature, or quality to compliment",
          description_bn: "যে জিনিস, বৈশিষ্ট্য, বা গুণের প্রশংসা করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["shirt", "hairstyle", "new bag"],
        },
      ],
      examples: [
        {
          en: "I like your shirt! Where did you get it?",
          bn: "আমি তোমার শার্টটা পছন্দ করেছি! কোথা থেকে কিনেছো?",
          slotValues: { THING: "shirt" },
          topicArea: "shopping",
        },
        {
          en: "I like your hairstyle! It really suits you.",
          bn: "আমি তোমার চুলের স্টাইল পছন্দ করেছি! তোমাকে দারুণ মানিয়েছে।",
          slotValues: { THING: "hairstyle" },
          topicArea: "daily_life",
        },
        {
          en: "I like your new bag! It looks very stylish.",
          bn: "আমি তোমার নতুন ব্যাগটা পছন্দ করেছি! দেখতে খুব স্টাইলিশ।",
          slotValues: { THING: "new bag" },
          topicArea: "shopping",
        },
        {
          en: "I like your shoes! Are they new?",
          bn: "আমি তোমার জুতো পছন্দ করেছি! এগুলো কি নতুন?",
          slotValues: { THING: "shoes" },
          topicArea: "shopping",
        },
        {
          en: "I like your cooking! This biryani is amazing.",
          bn: "আমি তোমার রান্না পছন্দ করি! এই বিরিয়ানি অসাধারণ।",
          slotValues: { THING: "cooking" },
          topicArea: "food",
        },
        {
          en: "I like your handwriting! It's so neat.",
          bn: "আমি তোমার হাতের লেখা পছন্দ করি! খুব পরিষ্কার।",
          slotValues: { THING: "handwriting" },
          topicArea: "education",
        },
        {
          en: "I like your office! It's very organized.",
          bn: "আমি তোমার অফিস পছন্দ করেছি! খুব গোছানো।",
          slotValues: { THING: "office" },
          topicArea: "work",
        },
        {
          en: "I like your garden! The flowers are beautiful.",
          bn: "আমি তোমার বাগান পছন্দ করেছি! ফুলগুলো সুন্দর।",
          slotValues: { THING: "garden" },
          topicArea: "daily_life",
        },
        {
          en: "I like your attitude! You're always so positive.",
          bn: "আমি তোমার মনোভাব পছন্দ করি! তুমি সবসময় এত ইতিবাচক।",
          slotValues: { THING: "attitude" },
          topicArea: "relationships",
        },
        {
          en: "I like your phone case! The color is nice.",
          bn: "আমি তোমার ফোনের কেস পছন্দ করেছি! রংটা সুন্দর।",
          slotValues: { THING: "phone case" },
          topicArea: "shopping",
        },
        {
          en: "I like your presentation style! It's very clear.",
          bn: "আমি তোমার প্রেজেন্টেশনের ধরন পছন্দ করি! খুব স্পষ্ট।",
          slotValues: { THING: "presentation style" },
          topicArea: "work",
        },
        {
          en: "I like your travel photos! They look amazing.",
          bn: "আমি তোমার ভ্রমণের ছবিগুলো পছন্দ করেছি! দারুণ দেখাচ্ছে।",
          slotValues: { THING: "travel photos" },
          topicArea: "travel",
        },
        {
          en: "I like your recipe! Can you share it with me?",
          bn: "আমি তোমার রেসিপি পছন্দ করেছি! আমার সাথে শেয়ার করবে?",
          slotValues: { THING: "recipe" },
          topicArea: "food",
        },
        {
          en: "I like your sense of humor! You always make me laugh.",
          bn: "আমি তোমার রসবোধ পছন্দ করি! তুমি সবসময় আমাকে হাসাও।",
          slotValues: { THING: "sense of humor" },
          topicArea: "relationships",
        },
        {
          en: "I like your workout routine! It seems very effective.",
          bn: "আমি তোমার ব্যায়ামের রুটিন পছন্দ করি! খুব কার্যকর মনে হচ্ছে।",
          slotValues: { THING: "workout routine" },
          topicArea: "health",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "'I like your...' is the simplest and most common way to give a compliment. It works for both physical things and qualities.",
      usageNote_bn:
        "'I like your...' প্রশংসা করার সবচেয়ে সহজ ও সাধারণ উপায়। এটি বস্তুগত জিনিস এবং গুণ উভয়ের জন্যই কাজ করে।",
      banglaStructureMap:
        "আমি (I) + তোমার (Your) + [THING] (Thing) + পছন্দ করি (Like)",
    },
    {
      id: "H8.2",
      formula: "You look [ADJECTIVE] today!",
      formula_bn: "তুমি আজ [বিশেষণ] দেখাচ্ছো!",
      patternName: "Complimenting Appearance",
      patternName_bn: "চেহারার প্রশংসা",
      slots: [
        {
          name: "ADJECTIVE",
          description: "Positive word describing how someone looks",
          description_bn: "কেউ কেমন দেখাচ্ছে তা বর্ণনাকারী ইতিবাচক শব্দ",
          acceptedTypes: ["adjective"],
          examples: ["great", "nice", "lovely"],
        },
      ],
      examples: [
        {
          en: "You look great today!",
          bn: "তুমি আজ দারুণ দেখাচ্ছো!",
          slotValues: { ADJECTIVE: "great" },
          topicArea: "daily_life",
        },
        {
          en: "You look nice today! Is that a new outfit?",
          bn: "তুমি আজ সুন্দর দেখাচ্ছো! এটা কি নতুন পোশাক?",
          slotValues: { ADJECTIVE: "nice" },
          topicArea: "shopping",
        },
        {
          en: "You look lovely today! That color suits you.",
          bn: "তুমি আজ চমৎকার দেখাচ্ছো! এই রংটা তোমাকে মানিয়েছে।",
          slotValues: { ADJECTIVE: "lovely" },
          topicArea: "daily_life",
        },
        {
          en: "You look happy today! Did something good happen?",
          bn: "তুমি আজ খুশি দেখাচ্ছো! ভালো কিছু হয়েছে?",
          slotValues: { ADJECTIVE: "happy" },
          topicArea: "relationships",
        },
        {
          en: "You look amazing today! What's the occasion?",
          bn: "তুমি আজ অসাধারণ দেখাচ্ছো! কী উপলক্ষ?",
          slotValues: { ADJECTIVE: "amazing" },
          topicArea: "daily_life",
        },
        {
          en: "You look refreshed today! Did you have a good weekend?",
          bn: "তুমি আজ চাঙ্গা দেখাচ্ছো! সপ্তাহান্ত ভালো কেটেছে?",
          slotValues: { ADJECTIVE: "refreshed" },
          topicArea: "health",
        },
        {
          en: "You look sharp today! Ready for the meeting?",
          bn: "তুমি আজ দারুণ পরিপাটি দেখাচ্ছো! মিটিংয়ের জন্য তৈরি?",
          slotValues: { ADJECTIVE: "sharp" },
          topicArea: "work",
        },
        {
          en: "You look elegant today! That dress is beautiful.",
          bn: "তুমি আজ মার্জিত দেখাচ্ছো! পোশাকটা সুন্দর।",
          slotValues: { ADJECTIVE: "elegant" },
          topicArea: "shopping",
        },
        {
          en: "You look well-rested today! The vacation did you good.",
          bn: "তুমি আজ বিশ্রাম নেওয়া দেখাচ্ছো! ছুটি কাজে দিয়েছে।",
          slotValues: { ADJECTIVE: "well-rested" },
          topicArea: "travel",
        },
        {
          en: "You look cheerful today! Your smile is infectious.",
          bn: "তুমি আজ প্রফুল্ল দেখাচ্ছো! তোমার হাসি সংক্রামক।",
          slotValues: { ADJECTIVE: "cheerful" },
          topicArea: "relationships",
        },
        {
          en: "You look fit today! Have you been working out?",
          bn: "তুমি আজ ফিট দেখাচ্ছো! ব্যায়াম করছো নাকি?",
          slotValues: { ADJECTIVE: "fit" },
          topicArea: "health",
        },
        {
          en: "You look professional today! Perfect for the interview.",
          bn: "তুমি আজ পেশাদার দেখাচ্ছো! ইন্টারভিউয়ের জন্য পারফেক্ট।",
          slotValues: { ADJECTIVE: "professional" },
          topicArea: "work",
        },
        {
          en: "You look radiant today! What's your secret?",
          bn: "তুমি আজ উজ্জ্বল দেখাচ্ছো! তোমার রহস্য কী?",
          slotValues: { ADJECTIVE: "radiant" },
          topicArea: "daily_life",
        },
        {
          en: "You look energetic today! Ready for the hike?",
          bn: "তুমি আজ প্রাণবন্ত দেখাচ্ছো! হাইকিংয়ের জন্য তৈরি?",
          slotValues: { ADJECTIVE: "energetic" },
          topicArea: "travel",
        },
        {
          en: "You look wonderful today! The party will love you.",
          bn: "তুমি আজ অপূর্ব দেখাচ্ছো! পার্টিতে সবাই মুগ্ধ হবে।",
          slotValues: { ADJECTIVE: "wonderful" },
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "'You look [adjective] today' is a natural way to compliment someone's appearance. Adding 'today' makes it feel fresh and specific.",
      usageNote_bn:
        "'You look [adjective] today' কারো চেহারার প্রশংসা করার স্বাভাবিক উপায়। 'Today' যোগ করলে এটি নতুন ও নির্দিষ্ট মনে হয়।",
      banglaStructureMap:
        "তুমি (You) + আজ (Today) + [ADJECTIVE] (Adjective) + দেখাচ্ছো (Look)",
    },
    {
      id: "H8.3",
      formula: "You're really good at [DOING]!",
      formula_bn: "তুমি [কাজ]-এ সত্যিই ভালো!",
      patternName: "Complimenting Skills",
      patternName_bn: "দক্ষতার প্রশংসা",
      slots: [
        {
          name: "DOING",
          description: "Skill or activity the person excels at",
          description_bn: "যে দক্ষতা বা কাজে ব্যক্তি পারদর্শী",
          acceptedTypes: ["gerund"],
          examples: ["cooking", "speaking English", "drawing"],
        },
      ],
      examples: [
        {
          en: "You're really good at cooking! This tastes amazing.",
          bn: "তুমি রান্নায় সত্যিই ভালো! স্বাদ অসাধারণ।",
          slotValues: { DOING: "cooking" },
          topicArea: "food",
        },
        {
          en: "You're really good at speaking English! Your pronunciation is perfect.",
          bn: "তুমি ইংরেজি বলায় সত্যিই ভালো! তোমার উচ্চারণ নিখুঁত।",
          slotValues: { DOING: "speaking English" },
          topicArea: "education",
        },
        {
          en: "You're really good at drawing! Have you taken classes?",
          bn: "তুমি আঁকায় সত্যিই ভালো! ক্লাস করেছো?",
          slotValues: { DOING: "drawing" },
          topicArea: "education",
        },
        {
          en: "You're really good at explaining things! I understand now.",
          bn: "তুমি জিনিস বোঝানোয় সত্যিই ভালো! এখন বুঝতে পারছি।",
          slotValues: { DOING: "explaining things" },
          topicArea: "work",
        },
        {
          en: "You're really good at making people feel comfortable!",
          bn: "তুমি মানুষকে স্বচ্ছন্দ করানোয় সত্যিই ভালো!",
          slotValues: { DOING: "making people feel comfortable" },
          topicArea: "relationships",
        },
        {
          en: "You're really good at playing cricket! You should join a team.",
          bn: "তুমি ক্রিকেট খেলায় সত্যিই ভালো! একটা দলে যোগ দেওয়া উচিত।",
          slotValues: { DOING: "playing cricket" },
          topicArea: "health",
        },
        {
          en: "You're really good at managing your time!",
          bn: "তুমি সময় ব্যবস্থাপনায় সত্যিই ভালো!",
          slotValues: { DOING: "managing your time" },
          topicArea: "work",
        },
        {
          en: "You're really good at finding bargains!",
          bn: "তুমি দরকষাকষিতে সত্যিই ভালো!",
          slotValues: { DOING: "finding bargains" },
          topicArea: "shopping",
        },
        {
          en: "You're really good at planning trips! Everything was perfect.",
          bn: "তুমি ভ্রমণ পরিকল্পনায় সত্যিই ভালো! সবকিছু নিখুঁত ছিল।",
          slotValues: { DOING: "planning trips" },
          topicArea: "travel",
        },
        {
          en: "You're really good at remembering names!",
          bn: "তুমি নাম মনে রাখায় সত্যিই ভালো!",
          slotValues: { DOING: "remembering names" },
          topicArea: "relationships",
        },
        {
          en: "You're really good at solving problems!",
          bn: "তুমি সমস্যা সমাধানে সত্যিই ভালো!",
          slotValues: { DOING: "solving problems" },
          topicArea: "work",
        },
        {
          en: "You're really good at baking! This cake is delicious.",
          bn: "তুমি বেকিংয়ে সত্যিই ভালো! এই কেকটা দারুণ সুস্বাদু।",
          slotValues: { DOING: "baking" },
          topicArea: "food",
        },
        {
          en: "You're really good at staying healthy! What's your routine?",
          bn: "তুমি সুস্থ থাকায় সত্যিই ভালো! তোমার রুটিন কী?",
          slotValues: { DOING: "staying healthy" },
          topicArea: "health",
        },
        {
          en: "You're really good at teaching! The students love you.",
          bn: "তুমি পড়ানোয় সত্যিই ভালো! ছাত্ররা তোমাকে পছন্দ করে।",
          slotValues: { DOING: "teaching" },
          topicArea: "education",
        },
        {
          en: "You're really good at decorating! Your house looks wonderful.",
          bn: "তুমি সাজানোয় সত্যিই ভালো! তোমার বাড়ি অপূর্ব দেখাচ্ছে।",
          slotValues: { DOING: "decorating" },
          topicArea: "daily_life",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "This pattern directly praises a person's skill. It feels genuine and specific, especially when followed by evidence or an example.",
      usageNote_bn:
        "এই প্যাটার্ন সরাসরি একজন ব্যক্তির দক্ষতার প্রশংসা করে। প্রমাণ বা উদাহরণসহ বলা হলে এটি আন্তরিক ও নির্দিষ্ট মনে হয়।",
      banglaStructureMap:
        "তুমি (You) + [DOING]-এ (At doing) + সত্যিই ভালো (Really good)",
    },
    {
      id: "H8.4",
      formula: "That [THING] looks [ADJECTIVE]!",
      formula_bn: "ওই [জিনিস] [বিশেষণ] দেখাচ্ছে!",
      patternName: "Complimenting Something Specific",
      patternName_bn: "নির্দিষ্ট কিছুর প্রশংসা",
      slots: [
        {
          name: "THING",
          description: "The specific item being complimented",
          description_bn: "যে নির্দিষ্ট জিনিসের প্রশংসা করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["dress", "painting", "dish"],
        },
        {
          name: "ADJECTIVE",
          description: "Positive describing word",
          description_bn: "ইতিবাচক বর্ণনাকারী শব্দ",
          acceptedTypes: ["adjective"],
          examples: ["amazing", "beautiful", "delicious"],
        },
      ],
      examples: [
        {
          en: "That dress looks amazing on you!",
          bn: "ওই পোশাকটা তোমাকে অসাধারণ দেখাচ্ছে!",
          slotValues: { THING: "dress", ADJECTIVE: "amazing" },
          topicArea: "shopping",
        },
        {
          en: "That painting looks beautiful! Did you make it?",
          bn: "ওই ছবিটা সুন্দর দেখাচ্ছে! তুমি কি এটা বানিয়েছো?",
          slotValues: { THING: "painting", ADJECTIVE: "beautiful" },
          topicArea: "daily_life",
        },
        {
          en: "That dish looks delicious! I can't wait to try it.",
          bn: "ওই খাবারটা দারুণ সুস্বাদু দেখাচ্ছে! খেতে চাই অপেক্ষা করতে পারছি না।",
          slotValues: { THING: "dish", ADJECTIVE: "delicious" },
          topicArea: "food",
        },
        {
          en: "That report looks great! Very well structured.",
          bn: "ওই রিপোর্টটা দারুণ দেখাচ্ছে! খুব ভালো গঠন।",
          slotValues: { THING: "report", ADJECTIVE: "great" },
          topicArea: "work",
        },
        {
          en: "That garden looks fantastic! You must work hard on it.",
          bn: "ওই বাগানটা চমৎকার দেখাচ্ছে! তুমি নিশ্চয়ই অনেক পরিশ্রম করো।",
          slotValues: { THING: "garden", ADJECTIVE: "fantastic" },
          topicArea: "daily_life",
        },
        {
          en: "That cake looks wonderful! Is it homemade?",
          bn: "ওই কেকটা অপূর্ব দেখাচ্ছে! এটা কি ঘরে তৈরি?",
          slotValues: { THING: "cake", ADJECTIVE: "wonderful" },
          topicArea: "food",
        },
        {
          en: "That presentation looks impressive! You prepared well.",
          bn: "ওই প্রেজেন্টেশনটা চমৎকার দেখাচ্ছে! তুমি ভালো প্রস্তুতি নিয়েছো।",
          slotValues: { THING: "presentation", ADJECTIVE: "impressive" },
          topicArea: "work",
        },
        {
          en: "That necklace looks gorgeous! Where did you buy it?",
          bn: "ওই নেকলেসটা দারুণ সুন্দর দেখাচ্ছে! কোথা থেকে কিনেছো?",
          slotValues: { THING: "necklace", ADJECTIVE: "gorgeous" },
          topicArea: "shopping",
        },
        {
          en: "That essay looks excellent! You'll get a good grade.",
          bn: "ওই রচনাটা চমৎকার দেখাচ্ছে! তুমি ভালো গ্রেড পাবে।",
          slotValues: { THING: "essay", ADJECTIVE: "excellent" },
          topicArea: "education",
        },
        {
          en: "That smoothie looks healthy! What's in it?",
          bn: "ওই স্মুদিটা স্বাস্থ্যকর দেখাচ্ছে! এতে কী কী আছে?",
          slotValues: { THING: "smoothie", ADJECTIVE: "healthy" },
          topicArea: "health",
        },
        {
          en: "That photo looks stunning! Where was it taken?",
          bn: "ওই ছবিটা অসাধারণ দেখাচ্ছে! কোথায় তোলা?",
          slotValues: { THING: "photo", ADJECTIVE: "stunning" },
          topicArea: "travel",
        },
        {
          en: "That scarf looks lovely with your coat!",
          bn: "তোমার কোটের সাথে ওই স্কার্ফটা দারুণ দেখাচ্ছে!",
          slotValues: { THING: "scarf", ADJECTIVE: "lovely" },
          topicArea: "shopping",
        },
        {
          en: "That project looks promising! Keep it up.",
          bn: "ওই প্রজেক্টটা আশাব্যঞ্জক দেখাচ্ছে! চালিয়ে যাও।",
          slotValues: { THING: "project", ADJECTIVE: "promising" },
          topicArea: "work",
        },
        {
          en: "That handwriting looks neat! You must practice a lot.",
          bn: "ওই হাতের লেখা পরিষ্কার দেখাচ্ছে! তুমি নিশ্চয়ই অনেক অভ্যাস করো।",
          slotValues: { THING: "handwriting", ADJECTIVE: "neat" },
          topicArea: "education",
        },
        {
          en: "That lunch box looks colorful! Very appetizing.",
          bn: "ওই লাঞ্চ বক্সটা রংবেরঙের দেখাচ্ছে! খুব ক্ষুধা-উদ্দীপক।",
          slotValues: { THING: "lunch box", ADJECTIVE: "colorful" },
          topicArea: "food",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "This pattern lets you compliment a specific thing rather than the person directly. It feels natural and less personal, making it suitable for acquaintances too.",
      usageNote_bn:
        "এই প্যাটার্ন আপনাকে সরাসরি ব্যক্তির বদলে নির্দিষ্ট কিছুর প্রশংসা করতে দেয়। এটি স্বাভাবিক ও কম ব্যক্তিগত মনে হয়, তাই পরিচিতদের সাথেও উপযুক্ত।",
      banglaStructureMap:
        "ওই (That) + [THING] (Thing) + [ADJECTIVE] (Adjective) + দেখাচ্ছে (Looks)",
    },
    {
      id: "H8.5",
      formula: "You have such a great [THING]!",
      formula_bn: "তোমার কী দারুণ [জিনিস]!",
      patternName: "Emphatic Compliment",
      patternName_bn: "জোরালো প্রশংসা",
      slots: [
        {
          name: "THING",
          description: "Quality, talent, or possession being praised emphatically",
          description_bn: "যে গুণ, প্রতিভা, বা জিনিসের জোরালো প্রশংসা করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["voice", "smile", "taste in music"],
        },
      ],
      examples: [
        {
          en: "You have such a great voice! Have you ever thought of singing professionally?",
          bn: "তোমার কী দারুণ গলা! কখনো পেশাদারভাবে গান গাওয়ার কথা ভেবেছো?",
          slotValues: { THING: "voice" },
          topicArea: "daily_life",
        },
        {
          en: "You have such a great smile! It lights up the room.",
          bn: "তোমার কী দারুণ হাসি! ঘর আলোকিত হয়ে যায়।",
          slotValues: { THING: "smile" },
          topicArea: "relationships",
        },
        {
          en: "You have such a great taste in music!",
          bn: "সংগীতে তোমার কী দারুণ রুচি!",
          slotValues: { THING: "taste in music" },
          topicArea: "daily_life",
        },
        {
          en: "You have such a great memory! I wish I could remember things like you.",
          bn: "তোমার কী দারুণ স্মৃতিশক্তি! আমিও যদি তোমার মতো মনে রাখতে পারতাম।",
          slotValues: { THING: "memory" },
          topicArea: "education",
        },
        {
          en: "You have such a great work ethic! The boss must love you.",
          bn: "তোমার কী দারুণ কর্মনিষ্ঠা! বস নিশ্চয়ই তোমাকে পছন্দ করেন।",
          slotValues: { THING: "work ethic" },
          topicArea: "work",
        },
        {
          en: "You have such a great eye for fashion!",
          bn: "ফ্যাশনে তোমার কী দারুণ চোখ!",
          slotValues: { THING: "eye for fashion" },
          topicArea: "shopping",
        },
        {
          en: "You have such a great way with words!",
          bn: "তোমার কথা বলার কী দারুণ ধরন!",
          slotValues: { THING: "way with words" },
          topicArea: "relationships",
        },
        {
          en: "You have such a great energy! Everyone feels better around you.",
          bn: "তোমার কী দারুণ এনার্জি! তোমার কাছে থাকলে সবাই ভালো অনুভব করে।",
          slotValues: { THING: "energy" },
          topicArea: "health",
        },
        {
          en: "You have such a great talent for cooking!",
          bn: "রান্নায় তোমার কী দারুণ প্রতিভা!",
          slotValues: { THING: "talent for cooking" },
          topicArea: "food",
        },
        {
          en: "You have such a great sense of direction! I always get lost.",
          bn: "তোমার কী দারুণ দিকবোধ! আমি সবসময় হারিয়ে যাই।",
          slotValues: { THING: "sense of direction" },
          topicArea: "travel",
        },
        {
          en: "You have such a great imagination! Your stories are amazing.",
          bn: "তোমার কী দারুণ কল্পনাশক্তি! তোমার গল্পগুলো অসাধারণ।",
          slotValues: { THING: "imagination" },
          topicArea: "education",
        },
        {
          en: "You have such a great laugh! It's so contagious.",
          bn: "তোমার কী দারুণ হাসি! এত সংক্রামক।",
          slotValues: { THING: "laugh" },
          topicArea: "relationships",
        },
        {
          en: "You have such a great taste in food! Let's go to your pick next time.",
          bn: "খাবারে তোমার কী দারুণ রুচি! পরেরবার তোমার পছন্দের জায়গায় যাই।",
          slotValues: { THING: "taste in food" },
          topicArea: "food",
        },
        {
          en: "You have such a great attitude! Nothing seems to bring you down.",
          bn: "তোমার কী দারুণ মনোভাব! কিছুই তোমাকে দমাতে পারে না।",
          slotValues: { THING: "attitude" },
          topicArea: "daily_life",
        },
        {
          en: "You have such a great ability to focus! I get distracted so easily.",
          bn: "তোমার কী দারুণ মনোযোগের ক্ষমতা! আমি খুব সহজেই বিচলিত হয়ে যাই।",
          slotValues: { THING: "ability to focus" },
          topicArea: "work",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "'Such a great' adds emphasis and makes the compliment feel more enthusiastic. It's a way to show you're genuinely impressed.",
      usageNote_bn:
        "'Such a great' জোর দেয় এবং প্রশংসাকে আরও উৎসাহী মনে করায়। এটি দেখায় যে আপনি সত্যিই মুগ্ধ।",
      banglaStructureMap:
        "তোমার (Your) + কী দারুণ (Such a great) + [THING] (Thing)",
    },
  ],
};
