import { PatternCategory } from "@/types/pattern";

export const categoryI1: PatternCategory = {
  id: "I1",
  slug: "basic-comparisons",
  name: "Basic Comparisons",
  name_bn: "মৌলিক তুলনা",
  description:
    "Learn how to compare things using comparative and superlative forms in English.",
  description_bn:
    "ইংরেজিতে তুলনামূলক এবং সর্বোচ্চ মাত্রার রূপ ব্যবহার করে জিনিস তুলনা করতে শিখুন।",
  icon: "⚖️",
  group: "I",
  groupName: "Comparing & Contrasting",
  groupName_bn: "তুলনা এবং বৈপরীত্য",
  difficulty: "intermediate",
  patterns: [
    {
      id: "I1.1",
      formula: "[A] is [ADJECTIVE+ER] than [B]",
      formula_bn: "[ক] [খ]-এর চেয়ে বেশি [বিশেষণ]",
      patternName: "Comparative with -er",
      patternName_bn: "-er দিয়ে তুলনা",
      slots: [
        {
          name: "A",
          description: "The first thing being compared",
          description_bn: "প্রথম যে জিনিসটি তুলনা করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["This book", "My house", "Summer"],
        },
        {
          name: "ADJECTIVE+ER",
          description: "A short adjective with -er ending",
          description_bn: "একটি ছোট বিশেষণ যার শেষে -er আছে",
          acceptedTypes: ["adjective"],
          examples: ["taller", "cheaper", "faster"],
        },
        {
          name: "B",
          description: "The second thing being compared",
          description_bn: "দ্বিতীয় যে জিনিসটি তুলনা করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["that book", "your house", "winter"],
        },
      ],
      examples: [
        {
          en: "My brother is taller than me.",
          bn: "আমার ভাই আমার চেয়ে লম্বা।",
          slotValues: { A: "My brother", "ADJECTIVE+ER": "taller", B: "me" },
          topicArea: "relationships",
        },
        {
          en: "This phone is cheaper than that one.",
          bn: "এই ফোনটি ওটার চেয়ে সস্তা।",
          slotValues: { A: "This phone", "ADJECTIVE+ER": "cheaper", B: "that one" },
          topicArea: "shopping",
        },
        {
          en: "Summer is hotter than spring.",
          bn: "গ্রীষ্মকাল বসন্তের চেয়ে বেশি গরম।",
          slotValues: { A: "Summer", "ADJECTIVE+ER": "hotter", B: "spring" },
          topicArea: "daily_life",
        },
        {
          en: "The train is faster than the bus.",
          bn: "ট্রেন বাসের চেয়ে দ্রুত।",
          slotValues: { A: "The train", "ADJECTIVE+ER": "faster", B: "the bus" },
          topicArea: "travel",
        },
        {
          en: "English is easier than Chinese.",
          bn: "ইংরেজি চীনা ভাষার চেয়ে সহজ।",
          slotValues: { A: "English", "ADJECTIVE+ER": "easier", B: "Chinese" },
          topicArea: "education",
        },
        {
          en: "Today is colder than yesterday.",
          bn: "আজ গতকালের চেয়ে বেশি ঠান্ডা।",
          slotValues: { A: "Today", "ADJECTIVE+ER": "colder", B: "yesterday" },
          topicArea: "daily_life",
        },
        {
          en: "My new job is harder than my old one.",
          bn: "আমার নতুন চাকরি আমার পুরোনোটার চেয়ে কঠিন।",
          slotValues: { A: "My new job", "ADJECTIVE+ER": "harder", B: "my old one" },
          topicArea: "work",
        },
        {
          en: "This road is wider than that street.",
          bn: "এই রাস্তাটি ওই রাস্তার চেয়ে চওড়া।",
          slotValues: { A: "This road", "ADJECTIVE+ER": "wider", B: "that street" },
          topicArea: "travel",
        },
        {
          en: "Fresh juice is healthier than soda.",
          bn: "তাজা জুস সোডার চেয়ে বেশি স্বাস্থ্যকর।",
          slotValues: { A: "Fresh juice", "ADJECTIVE+ER": "healthier", B: "soda" },
          topicArea: "health",
        },
        {
          en: "My sister is younger than my brother.",
          bn: "আমার বোন আমার ভাইয়ের চেয়ে ছোট।",
          slotValues: { A: "My sister", "ADJECTIVE+ER": "younger", B: "my brother" },
          topicArea: "relationships",
        },
        {
          en: "This bag is lighter than that suitcase.",
          bn: "এই ব্যাগটি ওই সুটকেসের চেয়ে হালকা।",
          slotValues: { A: "This bag", "ADJECTIVE+ER": "lighter", B: "that suitcase" },
          topicArea: "shopping",
        },
        {
          en: "Walking is slower than cycling.",
          bn: "হাঁটা সাইকেল চালানোর চেয়ে ধীর।",
          slotValues: { A: "Walking", "ADJECTIVE+ER": "slower", B: "cycling" },
          topicArea: "health",
        },
        {
          en: "Rice is cheaper than meat.",
          bn: "ভাত মাংসের চেয়ে সস্তা।",
          slotValues: { A: "Rice", "ADJECTIVE+ER": "cheaper", B: "meat" },
          topicArea: "food",
        },
        {
          en: "This exam is longer than the last one.",
          bn: "এই পরীক্ষাটি আগেরটার চেয়ে দীর্ঘ।",
          slotValues: { A: "This exam", "ADJECTIVE+ER": "longer", B: "the last one" },
          topicArea: "education",
        },
        {
          en: "My room is smaller than yours.",
          bn: "আমার ঘর তোমারটার চেয়ে ছোট।",
          slotValues: { A: "My room", "ADJECTIVE+ER": "smaller", B: "yours" },
          topicArea: "daily_life",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "Use '-er than' with short (one-syllable) adjectives and some two-syllable adjectives ending in -y.",
      usageNote_bn:
        "ছোট (একটি সিলেবল) বিশেষণ এবং -y দিয়ে শেষ হওয়া কিছু দুই-সিলেবল বিশেষণের সাথে '-er than' ব্যবহার করুন।",
      combinableWith: ["I1.2"],
      banglaStructureMap:
        "[A] (Subject) + [B]-এর চেয়ে (Comparison marker) + বেশি [ADJ] (Predicate)",
    },
    {
      id: "I1.2",
      formula: "[A] is more [ADJECTIVE] than [B]",
      formula_bn: "[ক] [খ]-এর চেয়ে বেশি [বিশেষণ]",
      patternName: "Comparative with 'more'",
      patternName_bn: "'more' দিয়ে তুলনা",
      slots: [
        {
          name: "A",
          description: "The first thing being compared",
          description_bn: "প্রথম যে জিনিসটি তুলনা করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["This movie", "Dhaka", "Reading"],
        },
        {
          name: "ADJECTIVE",
          description: "A long adjective (two or more syllables)",
          description_bn: "একটি দীর্ঘ বিশেষণ (দুই বা তার বেশি সিলেবল)",
          acceptedTypes: ["adjective"],
          examples: ["expensive", "beautiful", "interesting"],
        },
        {
          name: "B",
          description: "The second thing being compared",
          description_bn: "দ্বিতীয় যে জিনিসটি তুলনা করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["that movie", "Chittagong", "watching TV"],
        },
      ],
      examples: [
        {
          en: "This restaurant is more expensive than that one.",
          bn: "এই রেস্তোরাঁটি ওটার চেয়ে বেশি দামি।",
          slotValues: { A: "This restaurant", ADJECTIVE: "expensive", B: "that one" },
          topicArea: "food",
        },
        {
          en: "Dhaka is more crowded than Sylhet.",
          bn: "ঢাকা সিলেটের চেয়ে বেশি জনবহুল।",
          slotValues: { A: "Dhaka", ADJECTIVE: "crowded", B: "Sylhet" },
          topicArea: "travel",
        },
        {
          en: "This book is more interesting than that one.",
          bn: "এই বইটি ওটার চেয়ে বেশি আকর্ষণীয়।",
          slotValues: { A: "This book", ADJECTIVE: "interesting", B: "that one" },
          topicArea: "education",
        },
        {
          en: "My new job is more stressful than my old one.",
          bn: "আমার নতুন চাকরি আমার পুরোনোটার চেয়ে বেশি চাপের।",
          slotValues: { A: "My new job", ADJECTIVE: "stressful", B: "my old one" },
          topicArea: "work",
        },
        {
          en: "Online shopping is more convenient than going to the store.",
          bn: "অনলাইন কেনাকাটা দোকানে যাওয়ার চেয়ে বেশি সুবিধাজনক।",
          slotValues: { A: "Online shopping", ADJECTIVE: "convenient", B: "going to the store" },
          topicArea: "shopping",
        },
        {
          en: "This problem is more difficult than the last one.",
          bn: "এই সমস্যাটি আগেরটার চেয়ে বেশি কঠিন।",
          slotValues: { A: "This problem", ADJECTIVE: "difficult", B: "the last one" },
          topicArea: "education",
        },
        {
          en: "Exercise is more important than dieting.",
          bn: "ডায়েটিংয়ের চেয়ে ব্যায়াম বেশি গুরুত্বপূর্ণ।",
          slotValues: { A: "Exercise", ADJECTIVE: "important", B: "dieting" },
          topicArea: "health",
        },
        {
          en: "This hotel is more comfortable than the last one.",
          bn: "এই হোটেলটি আগেরটার চেয়ে বেশি আরামদায়ক।",
          slotValues: { A: "This hotel", ADJECTIVE: "comfortable", B: "the last one" },
          topicArea: "travel",
        },
        {
          en: "She is more talented than her classmates.",
          bn: "সে তার সহপাঠীদের চেয়ে বেশি প্রতিভাবান।",
          slotValues: { A: "She", ADJECTIVE: "talented", B: "her classmates" },
          topicArea: "education",
        },
        {
          en: "This task is more complicated than I expected.",
          bn: "এই কাজটি আমার প্রত্যাশার চেয়ে বেশি জটিল।",
          slotValues: { A: "This task", ADJECTIVE: "complicated", B: "I expected" },
          topicArea: "work",
        },
        {
          en: "Cooking at home is more economical than eating out.",
          bn: "বাইরে খাওয়ার চেয়ে বাড়িতে রান্না করা বেশি সাশ্রয়ী।",
          slotValues: { A: "Cooking at home", ADJECTIVE: "economical", B: "eating out" },
          topicArea: "food",
        },
        {
          en: "My mother is more patient than my father.",
          bn: "আমার মা আমার বাবার চেয়ে বেশি ধৈর্যশীল।",
          slotValues: { A: "My mother", ADJECTIVE: "patient", B: "my father" },
          topicArea: "relationships",
        },
        {
          en: "This laptop is more powerful than that one.",
          bn: "এই ল্যাপটপটি ওটার চেয়ে বেশি শক্তিশালী।",
          slotValues: { A: "This laptop", ADJECTIVE: "powerful", B: "that one" },
          topicArea: "shopping",
        },
        {
          en: "Yoga is more relaxing than running.",
          bn: "দৌড়ানোর চেয়ে যোগব্যায়াম বেশি শান্তিদায়ক।",
          slotValues: { A: "Yoga", ADJECTIVE: "relaxing", B: "running" },
          topicArea: "health",
        },
        {
          en: "Living alone is more peaceful than living with roommates.",
          bn: "রুমমেটদের সাথে থাকার চেয়ে একা থাকা বেশি শান্তিপূর্ণ।",
          slotValues: { A: "Living alone", ADJECTIVE: "peaceful", B: "living with roommates" },
          topicArea: "daily_life",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "Use 'more...than' with longer adjectives (two or more syllables). Never add '-er' to long adjectives.",
      usageNote_bn:
        "দীর্ঘ বিশেষণের (দুই বা তার বেশি সিলেবল) সাথে 'more...than' ব্যবহার করুন। দীর্ঘ বিশেষণে কখনো '-er' যোগ করবেন না।",
      combinableWith: ["I1.1"],
      banglaStructureMap:
        "[A] (Subject) + [B]-এর চেয়ে (Comparison marker) + বেশি [ADJ] (Predicate)",
    },
    {
      id: "I1.3",
      formula: "[A] is the [ADJECTIVE+EST]",
      formula_bn: "[ক] সবচেয়ে [বিশেষণ]",
      patternName: "Superlative with -est",
      patternName_bn: "-est দিয়ে সর্বোচ্চ মাত্রা",
      slots: [
        {
          name: "A",
          description: "The thing being described as the highest degree",
          description_bn: "যে জিনিসটিকে সর্বোচ্চ মাত্রায় বর্ণনা করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["Mount Everest", "This", "She"],
        },
        {
          name: "ADJECTIVE+EST",
          description: "A short adjective with -est ending",
          description_bn: "একটি ছোট বিশেষণ যার শেষে -est আছে",
          acceptedTypes: ["adjective"],
          examples: ["tallest", "cheapest", "fastest"],
        },
      ],
      examples: [
        {
          en: "Mount Everest is the tallest mountain in the world.",
          bn: "মাউন্ট এভারেস্ট পৃথিবীর সবচেয়ে উঁচু পর্বত।",
          slotValues: { A: "Mount Everest", "ADJECTIVE+EST": "tallest" },
          topicArea: "education",
        },
        {
          en: "This is the cheapest option available.",
          bn: "এটি সবচেয়ে সস্তা বিকল্প।",
          slotValues: { A: "This", "ADJECTIVE+EST": "cheapest" },
          topicArea: "shopping",
        },
        {
          en: "She is the fastest runner in the team.",
          bn: "সে দলের সবচেয়ে দ্রুত দৌড়বিদ।",
          slotValues: { A: "She", "ADJECTIVE+EST": "fastest" },
          topicArea: "health",
        },
        {
          en: "January is the coldest month here.",
          bn: "এখানে জানুয়ারি সবচেয়ে ঠান্ডা মাস।",
          slotValues: { A: "January", "ADJECTIVE+EST": "coldest" },
          topicArea: "daily_life",
        },
        {
          en: "This is the longest road in the city.",
          bn: "এটি শহরের সবচেয়ে লম্বা রাস্তা।",
          slotValues: { A: "This", "ADJECTIVE+EST": "longest" },
          topicArea: "travel",
        },
        {
          en: "He is the oldest person in the office.",
          bn: "তিনি অফিসের সবচেয়ে বয়স্ক ব্যক্তি।",
          slotValues: { A: "He", "ADJECTIVE+EST": "oldest" },
          topicArea: "work",
        },
        {
          en: "This is the biggest mall in the country.",
          bn: "এটি দেশের সবচেয়ে বড় শপিং মল।",
          slotValues: { A: "This", "ADJECTIVE+EST": "biggest" },
          topicArea: "shopping",
        },
        {
          en: "Friday is the busiest day at work.",
          bn: "শুক্রবার কর্মক্ষেত্রে সবচেয়ে ব্যস্ত দিন।",
          slotValues: { A: "Friday", "ADJECTIVE+EST": "busiest" },
          topicArea: "work",
        },
        {
          en: "This is the sweetest mango I have ever tasted.",
          bn: "এটি আমার খাওয়া সবচেয়ে মিষ্টি আম।",
          slotValues: { A: "This", "ADJECTIVE+EST": "sweetest" },
          topicArea: "food",
        },
        {
          en: "She is the kindest person I know.",
          bn: "সে আমার পরিচিত সবচেয়ে দয়ালু মানুষ।",
          slotValues: { A: "She", "ADJECTIVE+EST": "kindest" },
          topicArea: "relationships",
        },
        {
          en: "This is the nearest hospital.",
          bn: "এটি সবচেয়ে কাছের হাসপাতাল।",
          slotValues: { A: "This", "ADJECTIVE+EST": "nearest" },
          topicArea: "health",
        },
        {
          en: "That was the hardest exam I have ever taken.",
          bn: "সেটি আমার দেওয়া সবচেয়ে কঠিন পরীক্ষা।",
          slotValues: { A: "That", "ADJECTIVE+EST": "hardest" },
          topicArea: "education",
        },
        {
          en: "He is the youngest player on the team.",
          bn: "সে দলের সবচেয়ে কম বয়সী খেলোয়াড়।",
          slotValues: { A: "He", "ADJECTIVE+EST": "youngest" },
          topicArea: "daily_life",
        },
        {
          en: "This is the safest route to take.",
          bn: "এটি নেওয়ার জন্য সবচেয়ে নিরাপদ রাস্তা।",
          slotValues: { A: "This", "ADJECTIVE+EST": "safest" },
          topicArea: "travel",
        },
        {
          en: "This is the hottest curry on the menu.",
          bn: "এটি মেনুতে সবচেয়ে ঝাল তরকারি।",
          slotValues: { A: "This", "ADJECTIVE+EST": "hottest" },
          topicArea: "food",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "Use 'the + adjective + -est' with short adjectives to express the highest degree. Always use 'the' before superlatives.",
      usageNote_bn:
        "সর্বোচ্চ মাত্রা প্রকাশ করতে ছোট বিশেষণের সাথে 'the + adjective + -est' ব্যবহার করুন। সুপারলেটিভের আগে সবসময় 'the' ব্যবহার করুন।",
      combinableWith: ["I1.4"],
      banglaStructureMap:
        "[A] (Subject) + সবচেয়ে (Superlative marker) + [ADJ] (Predicate)",
    },
    {
      id: "I1.4",
      formula: "[A] is the most [ADJECTIVE]",
      formula_bn: "[ক] সবচেয়ে [বিশেষণ]",
      patternName: "Superlative with 'most'",
      patternName_bn: "'most' দিয়ে সর্বোচ্চ মাত্রা",
      slots: [
        {
          name: "A",
          description: "The thing being described as the highest degree",
          description_bn: "যে জিনিসটিকে সর্বোচ্চ মাত্রায় বর্ণনা করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["This city", "She", "That movie"],
        },
        {
          name: "ADJECTIVE",
          description: "A long adjective (two or more syllables)",
          description_bn: "একটি দীর্ঘ বিশেষণ (দুই বা তার বেশি সিলেবল)",
          acceptedTypes: ["adjective"],
          examples: ["beautiful", "expensive", "interesting"],
        },
      ],
      examples: [
        {
          en: "This is the most beautiful place I have ever visited.",
          bn: "এটি আমার দেখা সবচেয়ে সুন্দর জায়গা।",
          slotValues: { A: "This", ADJECTIVE: "beautiful" },
          topicArea: "travel",
        },
        {
          en: "That was the most delicious meal I have ever had.",
          bn: "সেটি আমার খাওয়া সবচেয়ে সুস্বাদু খাবার।",
          slotValues: { A: "That", ADJECTIVE: "delicious" },
          topicArea: "food",
        },
        {
          en: "She is the most intelligent student in the class.",
          bn: "সে ক্লাসের সবচেয়ে বুদ্ধিমান ছাত্রী।",
          slotValues: { A: "She", ADJECTIVE: "intelligent" },
          topicArea: "education",
        },
        {
          en: "This is the most expensive watch in the shop.",
          bn: "এটি দোকানের সবচেয়ে দামি ঘড়ি।",
          slotValues: { A: "This", ADJECTIVE: "expensive" },
          topicArea: "shopping",
        },
        {
          en: "He is the most experienced doctor in this hospital.",
          bn: "তিনি এই হাসপাতালের সবচেয়ে অভিজ্ঞ ডাক্তার।",
          slotValues: { A: "He", ADJECTIVE: "experienced" },
          topicArea: "health",
        },
        {
          en: "That was the most interesting lecture I have attended.",
          bn: "সেটি আমার উপস্থিত হওয়া সবচেয়ে আকর্ষণীয় বক্তৃতা।",
          slotValues: { A: "That", ADJECTIVE: "interesting" },
          topicArea: "education",
        },
        {
          en: "This is the most comfortable chair in the office.",
          bn: "এটি অফিসের সবচেয়ে আরামদায়ক চেয়ার।",
          slotValues: { A: "This", ADJECTIVE: "comfortable" },
          topicArea: "work",
        },
        {
          en: "She is the most helpful person in my life.",
          bn: "সে আমার জীবনে সবচেয়ে সহায়ক মানুষ।",
          slotValues: { A: "She", ADJECTIVE: "helpful" },
          topicArea: "relationships",
        },
        {
          en: "This is the most popular restaurant in the city.",
          bn: "এটি শহরের সবচেয়ে জনপ্রিয় রেস্তোরাঁ।",
          slotValues: { A: "This", ADJECTIVE: "popular" },
          topicArea: "food",
        },
        {
          en: "That was the most difficult decision I have ever made.",
          bn: "সেটি আমার নেওয়া সবচেয়ে কঠিন সিদ্ধান্ত।",
          slotValues: { A: "That", ADJECTIVE: "difficult" },
          topicArea: "daily_life",
        },
        {
          en: "Tokyo is the most crowded city I have visited.",
          bn: "টোকিও আমার দেখা সবচেয়ে জনবহুল শহর।",
          slotValues: { A: "Tokyo", ADJECTIVE: "crowded" },
          topicArea: "travel",
        },
        {
          en: "This is the most important meeting of the year.",
          bn: "এটি বছরের সবচেয়ে গুরুত্বপূর্ণ সভা।",
          slotValues: { A: "This", ADJECTIVE: "important" },
          topicArea: "work",
        },
        {
          en: "He is the most generous person I know.",
          bn: "সে আমার পরিচিত সবচেয়ে উদার মানুষ।",
          slotValues: { A: "He", ADJECTIVE: "generous" },
          topicArea: "relationships",
        },
        {
          en: "Swimming is the most effective exercise for weight loss.",
          bn: "ওজন কমানোর জন্য সাঁতার সবচেয়ে কার্যকর ব্যায়াম।",
          slotValues: { A: "Swimming", ADJECTIVE: "effective" },
          topicArea: "health",
        },
        {
          en: "This is the most reliable brand for electronics.",
          bn: "ইলেকট্রনিক্সের জন্য এটি সবচেয়ে নির্ভরযোগ্য ব্র্যান্ড।",
          slotValues: { A: "This", ADJECTIVE: "reliable" },
          topicArea: "shopping",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "Use 'the most + adjective' with longer adjectives. Never add '-est' to long adjectives.",
      usageNote_bn:
        "দীর্ঘ বিশেষণের সাথে 'the most + adjective' ব্যবহার করুন। দীর্ঘ বিশেষণে কখনো '-est' যোগ করবেন না।",
      combinableWith: ["I1.3"],
      banglaStructureMap:
        "[A] (Subject) + সবচেয়ে (Superlative marker) + [ADJ] (Predicate)",
    },
    {
      id: "I1.5",
      formula: "[A] is less [ADJECTIVE] than [B]",
      formula_bn: "[ক] [খ]-এর চেয়ে কম [বিশেষণ]",
      patternName: "Less...Than Comparison",
      patternName_bn: "কম...চেয়ে তুলনা",
      slots: [
        {
          name: "A",
          description: "The first thing being compared",
          description_bn: "প্রথম যে জিনিসটি তুলনা করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["This movie", "Tea", "My job"],
        },
        {
          name: "ADJECTIVE",
          description: "Any adjective",
          description_bn: "যেকোনো বিশেষণ",
          acceptedTypes: ["adjective"],
          examples: ["interesting", "sweet", "stressful"],
        },
        {
          name: "B",
          description: "The second thing being compared",
          description_bn: "দ্বিতীয় যে জিনিসটি তুলনা করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["that movie", "coffee", "yours"],
        },
      ],
      examples: [
        {
          en: "This movie is less interesting than the book.",
          bn: "এই মুভিটি বইয়ের চেয়ে কম আকর্ষণীয়।",
          slotValues: { A: "This movie", ADJECTIVE: "interesting", B: "the book" },
          topicArea: "daily_life",
        },
        {
          en: "Tea is less expensive than coffee here.",
          bn: "এখানে চা কফির চেয়ে কম দামি।",
          slotValues: { A: "Tea", ADJECTIVE: "expensive", B: "coffee here" },
          topicArea: "food",
        },
        {
          en: "This route is less dangerous than that one.",
          bn: "এই রাস্তা ওটার চেয়ে কম বিপজ্জনক।",
          slotValues: { A: "This route", ADJECTIVE: "dangerous", B: "that one" },
          topicArea: "travel",
        },
        {
          en: "My new job is less stressful than my old one.",
          bn: "আমার নতুন চাকরি আমার পুরোনোটার চেয়ে কম চাপের।",
          slotValues: { A: "My new job", ADJECTIVE: "stressful", B: "my old one" },
          topicArea: "work",
        },
        {
          en: "This phone is less popular than the latest model.",
          bn: "এই ফোনটি সর্বশেষ মডেলের চেয়ে কম জনপ্রিয়।",
          slotValues: { A: "This phone", ADJECTIVE: "popular", B: "the latest model" },
          topicArea: "shopping",
        },
        {
          en: "Walking is less tiring than running.",
          bn: "হাঁটা দৌড়ানোর চেয়ে কম ক্লান্তিকর।",
          slotValues: { A: "Walking", ADJECTIVE: "tiring", B: "running" },
          topicArea: "health",
        },
        {
          en: "This exam is less difficult than the midterm.",
          bn: "এই পরীক্ষা মিডটার্মের চেয়ে কম কঠিন।",
          slotValues: { A: "This exam", ADJECTIVE: "difficult", B: "the midterm" },
          topicArea: "education",
        },
        {
          en: "He is less experienced than his colleague.",
          bn: "তিনি তার সহকর্মীর চেয়ে কম অভিজ্ঞ।",
          slotValues: { A: "He", ADJECTIVE: "experienced", B: "his colleague" },
          topicArea: "work",
        },
        {
          en: "This dish is less spicy than the other one.",
          bn: "এই পদটি অন্যটির চেয়ে কম ঝাল।",
          slotValues: { A: "This dish", ADJECTIVE: "spicy", B: "the other one" },
          topicArea: "food",
        },
        {
          en: "My apartment is less spacious than hers.",
          bn: "আমার অ্যাপার্টমেন্ট তার চেয়ে কম প্রশস্ত।",
          slotValues: { A: "My apartment", ADJECTIVE: "spacious", B: "hers" },
          topicArea: "daily_life",
        },
        {
          en: "This hotel is less comfortable than the previous one.",
          bn: "এই হোটেলটি আগেরটার চেয়ে কম আরামদায়ক।",
          slotValues: { A: "This hotel", ADJECTIVE: "comfortable", B: "the previous one" },
          topicArea: "travel",
        },
        {
          en: "He is less talkative than his brother.",
          bn: "সে তার ভাইয়ের চেয়ে কম কথা বলে।",
          slotValues: { A: "He", ADJECTIVE: "talkative", B: "his brother" },
          topicArea: "relationships",
        },
        {
          en: "This medicine is less effective than the other one.",
          bn: "এই ওষুধটি অন্যটির চেয়ে কম কার্যকর।",
          slotValues: { A: "This medicine", ADJECTIVE: "effective", B: "the other one" },
          topicArea: "health",
        },
        {
          en: "This brand is less reliable than that one.",
          bn: "এই ব্র্যান্ডটি ওটার চেয়ে কম নির্ভরযোগ্য।",
          slotValues: { A: "This brand", ADJECTIVE: "reliable", B: "that one" },
          topicArea: "shopping",
        },
        {
          en: "Online classes are less engaging than in-person ones.",
          bn: "অনলাইন ক্লাস সরাসরি ক্লাসের চেয়ে কম আকর্ষক।",
          slotValues: { A: "Online classes", ADJECTIVE: "engaging", B: "in-person ones" },
          topicArea: "education",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "Use 'less...than' to express a lower degree of comparison. This is a softer, more polite alternative to negative comparisons.",
      usageNote_bn:
        "তুলনায় কম মাত্রা প্রকাশ করতে 'less...than' ব্যবহার করুন। এটি নেতিবাচক তুলনার একটি নরম, বিনয়ী বিকল্প।",
      combinableWith: ["I1.1", "I1.2"],
      banglaStructureMap:
        "[A] (Subject) + [B]-এর চেয়ে (Comparison marker) + কম [ADJ] (Predicate)",
    },
    {
      id: "I1.6",
      formula: "The [MORE/ADJECTIVE-ER] [A], the [MORE/ADJECTIVE-ER] [B]",
      formula_bn: "যত বেশি [ক], তত বেশি [খ]",
      patternName: "Double Comparative (The more...the more)",
      patternName_bn: "দ্বৈত তুলনা (যত বেশি...তত বেশি)",
      slots: [
        {
          name: "MORE/ADJECTIVE-ER A",
          description: "A comparative form followed by a clause or phrase",
          description_bn: "একটি তুলনামূলক রূপ যার পরে একটি বাক্যাংশ",
          acceptedTypes: ["adjective", "clause"],
          examples: ["more you practice", "harder you work", "more I learn"],
        },
        {
          name: "MORE/ADJECTIVE-ER B",
          description: "A second comparative form followed by a clause or phrase",
          description_bn: "দ্বিতীয় তুলনামূলক রূপ যার পরে একটি বাক্যাংশ",
          acceptedTypes: ["adjective", "clause"],
          examples: ["better you get", "more you earn", "more I realize"],
        },
      ],
      examples: [
        {
          en: "The more you practice, the better you get.",
          bn: "তুমি যত বেশি অনুশীলন করবে, তত ভালো হবে।",
          slotValues: { "MORE/ADJECTIVE-ER A": "more you practice", "MORE/ADJECTIVE-ER B": "better you get" },
          topicArea: "education",
        },
        {
          en: "The harder you work, the more you earn.",
          bn: "তুমি যত কঠোর পরিশ্রম করবে, তত বেশি আয় করবে।",
          slotValues: { "MORE/ADJECTIVE-ER A": "harder you work", "MORE/ADJECTIVE-ER B": "more you earn" },
          topicArea: "work",
        },
        {
          en: "The more I learn, the more I realize I don't know.",
          bn: "আমি যত বেশি শিখি, তত বেশি বুঝি যে আমি জানি না।",
          slotValues: { "MORE/ADJECTIVE-ER A": "more I learn", "MORE/ADJECTIVE-ER B": "more I realize I don't know" },
          topicArea: "education",
        },
        {
          en: "The sooner we leave, the earlier we arrive.",
          bn: "আমরা যত তাড়াতাড়ি রওনা দেব, তত আগে পৌঁছাব।",
          slotValues: { "MORE/ADJECTIVE-ER A": "sooner we leave", "MORE/ADJECTIVE-ER B": "earlier we arrive" },
          topicArea: "travel",
        },
        {
          en: "The older he gets, the wiser he becomes.",
          bn: "সে যত বড় হয়, তত বুদ্ধিমান হয়।",
          slotValues: { "MORE/ADJECTIVE-ER A": "older he gets", "MORE/ADJECTIVE-ER B": "wiser he becomes" },
          topicArea: "daily_life",
        },
        {
          en: "The more you eat, the heavier you get.",
          bn: "তুমি যত বেশি খাবে, তত ভারী হবে।",
          slotValues: { "MORE/ADJECTIVE-ER A": "more you eat", "MORE/ADJECTIVE-ER B": "heavier you get" },
          topicArea: "health",
        },
        {
          en: "The more expensive the hotel, the better the service.",
          bn: "হোটেল যত দামি, সেবা তত ভালো।",
          slotValues: { "MORE/ADJECTIVE-ER A": "more expensive the hotel", "MORE/ADJECTIVE-ER B": "better the service" },
          topicArea: "travel",
        },
        {
          en: "The longer you wait, the harder it becomes.",
          bn: "তুমি যত দেরি করবে, তত কঠিন হবে।",
          slotValues: { "MORE/ADJECTIVE-ER A": "longer you wait", "MORE/ADJECTIVE-ER B": "harder it becomes" },
          topicArea: "daily_life",
        },
        {
          en: "The more I cook, the better I get at it.",
          bn: "আমি যত বেশি রান্না করি, তত ভালো হই।",
          slotValues: { "MORE/ADJECTIVE-ER A": "more I cook", "MORE/ADJECTIVE-ER B": "better I get at it" },
          topicArea: "food",
        },
        {
          en: "The cheaper the product, the lower the quality.",
          bn: "পণ্য যত সস্তা, মান তত কম।",
          slotValues: { "MORE/ADJECTIVE-ER A": "cheaper the product", "MORE/ADJECTIVE-ER B": "lower the quality" },
          topicArea: "shopping",
        },
        {
          en: "The more time you spend with family, the happier you feel.",
          bn: "পরিবারের সাথে যত বেশি সময় কাটাবে, তত সুখী অনুভব করবে।",
          slotValues: { "MORE/ADJECTIVE-ER A": "more time you spend with family", "MORE/ADJECTIVE-ER B": "happier you feel" },
          topicArea: "relationships",
        },
        {
          en: "The more you read, the more vocabulary you learn.",
          bn: "তুমি যত বেশি পড়বে, তত বেশি শব্দভাণ্ডার শিখবে।",
          slotValues: { "MORE/ADJECTIVE-ER A": "more you read", "MORE/ADJECTIVE-ER B": "more vocabulary you learn" },
          topicArea: "education",
        },
        {
          en: "The more exercise you do, the stronger you become.",
          bn: "তুমি যত বেশি ব্যায়াম করবে, তত শক্তিশালী হবে।",
          slotValues: { "MORE/ADJECTIVE-ER A": "more exercise you do", "MORE/ADJECTIVE-ER B": "stronger you become" },
          topicArea: "health",
        },
        {
          en: "The busier the restaurant, the longer the wait.",
          bn: "রেস্তোরাঁ যত ব্যস্ত, অপেক্ষা তত দীর্ঘ।",
          slotValues: { "MORE/ADJECTIVE-ER A": "busier the restaurant", "MORE/ADJECTIVE-ER B": "longer the wait" },
          topicArea: "food",
        },
        {
          en: "The more experience you have, the easier the job gets.",
          bn: "তোমার যত বেশি অভিজ্ঞতা থাকবে, কাজ তত সহজ হবে।",
          slotValues: { "MORE/ADJECTIVE-ER A": "more experience you have", "MORE/ADJECTIVE-ER B": "easier the job gets" },
          topicArea: "work",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "The double comparative pattern uses 'the + comparative, the + comparative' to show that two things change together. Use '-er' for short adjectives and 'more' for longer ones.",
      usageNote_bn:
        "দ্বৈত তুলনামূলক প্যাটার্ন 'the + comparative, the + comparative' ব্যবহার করে দেখায় যে দুটি জিনিস একসাথে পরিবর্তিত হয়। ছোট বিশেষণের জন্য '-er' এবং দীর্ঘ বিশেষণের জন্য 'more' ব্যবহার করুন।",
      combinableWith: ["I1.1", "I1.2"],
      banglaStructureMap:
        "যত বেশি (Correlative) + [A] (Clause) + তত বেশি (Correlative) + [B] (Clause)",
    },
    {
      id: "I1.7",
      formula: "[A] is not as [ADJECTIVE] as [B]",
      formula_bn: "[ক] [খ]-এর মতো [বিশেষণ] নয়",
      patternName: "Negative Comparison (not as...as)",
      patternName_bn: "নেতিবাচক তুলনা (not as...as)",
      slots: [
        {
          name: "A",
          description: "The first thing being compared",
          description_bn: "প্রথম যে জিনিসটি তুলনা করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["This movie", "She", "Today"],
        },
        {
          name: "ADJECTIVE",
          description: "Any adjective (no comparative form needed)",
          description_bn: "যেকোনো বিশেষণ (তুলনামূলক রূপের প্রয়োজন নেই)",
          acceptedTypes: ["adjective"],
          examples: ["good", "tall", "cold"],
        },
        {
          name: "B",
          description: "The second thing being compared",
          description_bn: "দ্বিতীয় যে জিনিসটি তুলনা করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["the book", "her sister", "yesterday"],
        },
      ],
      examples: [
        {
          en: "This movie is not as good as the book.",
          bn: "এই মুভিটি বইয়ের মতো ভালো নয়।",
          slotValues: { A: "This movie", ADJECTIVE: "good", B: "the book" },
          topicArea: "daily_life",
        },
        {
          en: "She is not as tall as her sister.",
          bn: "সে তার বোনের মতো লম্বা নয়।",
          slotValues: { A: "She", ADJECTIVE: "tall", B: "her sister" },
          topicArea: "relationships",
        },
        {
          en: "Today is not as cold as yesterday.",
          bn: "আজ গতকালের মতো ঠান্ডা নয়।",
          slotValues: { A: "Today", ADJECTIVE: "cold", B: "yesterday" },
          topicArea: "daily_life",
        },
        {
          en: "This restaurant is not as crowded as the other one.",
          bn: "এই রেস্তোরাঁটি অন্যটির মতো জনবহুল নয়।",
          slotValues: { A: "This restaurant", ADJECTIVE: "crowded", B: "the other one" },
          topicArea: "food",
        },
        {
          en: "My new job is not as stressful as my old one.",
          bn: "আমার নতুন চাকরি আমার পুরোনোটার মতো চাপের নয়।",
          slotValues: { A: "My new job", ADJECTIVE: "stressful", B: "my old one" },
          topicArea: "work",
        },
        {
          en: "This phone is not as expensive as that one.",
          bn: "এই ফোনটি ওটার মতো দামি নয়।",
          slotValues: { A: "This phone", ADJECTIVE: "expensive", B: "that one" },
          topicArea: "shopping",
        },
        {
          en: "The bus is not as fast as the train.",
          bn: "বাস ট্রেনের মতো দ্রুত নয়।",
          slotValues: { A: "The bus", ADJECTIVE: "fast", B: "the train" },
          topicArea: "travel",
        },
        {
          en: "This exam is not as difficult as the last one.",
          bn: "এই পরীক্ষাটি আগেরটার মতো কঠিন নয়।",
          slotValues: { A: "This exam", ADJECTIVE: "difficult", B: "the last one" },
          topicArea: "education",
        },
        {
          en: "Running is not as relaxing as yoga.",
          bn: "দৌড়ানো যোগব্যায়ামের মতো শান্তিদায়ক নয়।",
          slotValues: { A: "Running", ADJECTIVE: "relaxing", B: "yoga" },
          topicArea: "health",
        },
        {
          en: "He is not as patient as his mother.",
          bn: "সে তার মায়ের মতো ধৈর্যশীল নয়।",
          slotValues: { A: "He", ADJECTIVE: "patient", B: "his mother" },
          topicArea: "relationships",
        },
        {
          en: "Cooking at home is not as convenient as ordering online.",
          bn: "বাড়িতে রান্না করা অনলাইনে অর্ডার দেওয়ার মতো সুবিধাজনক নয়।",
          slotValues: { A: "Cooking at home", ADJECTIVE: "convenient", B: "ordering online" },
          topicArea: "food",
        },
        {
          en: "This hotel is not as comfortable as the last one.",
          bn: "এই হোটেলটি আগেরটার মতো আরামদায়ক নয়।",
          slotValues: { A: "This hotel", ADJECTIVE: "comfortable", B: "the last one" },
          topicArea: "travel",
        },
        {
          en: "This brand is not as reliable as that one.",
          bn: "এই ব্র্যান্ডটি ওটার মতো নির্ভরযোগ্য নয়।",
          slotValues: { A: "This brand", ADJECTIVE: "reliable", B: "that one" },
          topicArea: "shopping",
        },
        {
          en: "Working from home is not as productive as working in the office.",
          bn: "বাড়ি থেকে কাজ করা অফিসে কাজ করার মতো ফলপ্রসূ নয়।",
          slotValues: { A: "Working from home", ADJECTIVE: "productive", B: "working in the office" },
          topicArea: "work",
        },
        {
          en: "This chapter is not as long as the previous one.",
          bn: "এই অধ্যায়টি আগেরটার মতো দীর্ঘ নয়।",
          slotValues: { A: "This chapter", ADJECTIVE: "long", B: "the previous one" },
          topicArea: "education",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Not as...as' is used to say that two things are not equal. The adjective stays in its base form (not comparative). This is a softer way of saying something is less than something else.",
      usageNote_bn:
        "'Not as...as' দুটি জিনিস সমান নয় বলতে ব্যবহৃত হয়। বিশেষণটি তার মূল রূপে থাকে (তুলনামূলক নয়)। এটি অন্য কিছুর চেয়ে কম বলার একটি নরম উপায়।",
      combinableWith: ["I1.1", "I1.2", "I1.5"],
      banglaStructureMap:
        "[A] (Subject) + [B]-এর মতো (Comparison marker) + [ADJ] (Predicate) + নয় (Negation)",
    },
  ],
};
