import { PatternCategory } from "@/types/pattern";

export const categoryI10: PatternCategory = {
  id: "I10",
  slug: "expressing-addition",
  name: "Expressing Addition",
  name_bn: "সংযোজন প্রকাশ",
  description:
    "Learn how to add extra information and express additional points using common English patterns.",
  description_bn:
    "সাধারণ ইংরেজি প্যাটার্ন ব্যবহার করে অতিরিক্ত তথ্য যোগ করতে এবং সংযোজন প্রকাশ করতে শিখুন।",
  icon: "➕",
  group: "I",
  groupName: "Comparing & Contrasting",
  groupName_bn: "তুলনা ও বৈপরীত্য",
  difficulty: "intermediate",
  patterns: [
    {
      id: "I10.1",
      formula: "Besides [THING], [CLAUSE]",
      formula_bn: "[জিনিস] ছাড়াও, [উপবাক্য]",
      patternName: "Besides",
      patternName_bn: "ছাড়াও",
      slots: [
        {
          name: "THING",
          description: "The thing already known or mentioned",
          description_bn: "ইতিমধ্যে জানা বা উল্লেখিত জিনিস",
          acceptedTypes: ["noun", "noun_phrase", "gerund"],
          examples: ["English", "cooking", "the salary"],
        },
        {
          name: "CLAUSE",
          description: "The additional information",
          description_bn: "অতিরিক্ত তথ্য",
          acceptedTypes: ["clause"],
          examples: ["I also speak Bengali", "she enjoys painting", "the benefits are great"],
        },
      ],
      examples: [
        {
          en: "Besides English, I also speak Bengali and Hindi.",
          bn: "ইংরেজি ছাড়াও, আমি বাংলা এবং হিন্দিও বলি।",
          slotValues: { THING: "English", CLAUSE: "I also speak Bengali and Hindi" },
          topicArea: "education",
        },
        {
          en: "Besides cooking, she enjoys painting.",
          bn: "রান্না ছাড়াও, সে ছবি আঁকা উপভোগ করে।",
          slotValues: { THING: "cooking", CLAUSE: "she enjoys painting" },
          topicArea: "daily_life",
        },
        {
          en: "Besides the salary, the benefits are great.",
          bn: "বেতন ছাড়াও, সুবিধাগুলো দারুণ।",
          slotValues: { THING: "the salary", CLAUSE: "the benefits are great" },
          topicArea: "work",
        },
        {
          en: "Besides rice, we also eat roti and paratha.",
          bn: "ভাত ছাড়াও, আমরা রুটি এবং পরাটাও খাই।",
          slotValues: { THING: "rice", CLAUSE: "we also eat roti and paratha" },
          topicArea: "food",
        },
        {
          en: "Besides Dhaka, I've visited Sylhet and Chittagong.",
          bn: "ঢাকা ছাড়াও, আমি সিলেট এবং চট্টগ্রাম ঘুরেছি।",
          slotValues: { THING: "Dhaka", CLAUSE: "I've visited Sylhet and Chittagong" },
          topicArea: "travel",
        },
        {
          en: "Besides walking, swimming is also good exercise.",
          bn: "হাঁটা ছাড়াও, সাঁতারও ভালো ব্যায়াম।",
          slotValues: { THING: "walking", CLAUSE: "swimming is also good exercise" },
          topicArea: "health",
        },
        {
          en: "Besides my parents, my uncle also supported me.",
          bn: "আমার বাবা-মা ছাড়াও, আমার চাচাও আমাকে সাহায্য করেছে।",
          slotValues: { THING: "my parents", CLAUSE: "my uncle also supported me" },
          topicArea: "relationships",
        },
        {
          en: "Besides the phone, I also bought a case and charger.",
          bn: "ফোন ছাড়াও, আমি একটি কেস এবং চার্জারও কিনেছি।",
          slotValues: { THING: "the phone", CLAUSE: "I also bought a case and charger" },
          topicArea: "shopping",
        },
        {
          en: "Besides grammar, vocabulary is also important.",
          bn: "ব্যাকরণ ছাড়াও, শব্দভাণ্ডারও গুরুত্বপূর্ণ।",
          slotValues: { THING: "grammar", CLAUSE: "vocabulary is also important" },
          topicArea: "education",
        },
        {
          en: "Besides the beach, Cox's Bazar has great seafood.",
          bn: "সমুদ্র সৈকত ছাড়াও, কক্সবাজারে দারুণ সামুদ্রিক খাবার আছে।",
          slotValues: { THING: "the beach", CLAUSE: "Cox's Bazar has great seafood" },
          topicArea: "travel",
        },
        {
          en: "Besides tea, she offered us snacks and sweets.",
          bn: "চা ছাড়াও, সে আমাদের নাস্তা এবং মিষ্টি দিয়েছে।",
          slotValues: { THING: "tea", CLAUSE: "she offered us snacks and sweets" },
          topicArea: "food",
        },
        {
          en: "Besides his wife, his children also came to the event.",
          bn: "তার স্ত্রী ছাড়াও, তার সন্তানরাও অনুষ্ঠানে এসেছে।",
          slotValues: { THING: "his wife", CLAUSE: "his children also came to the event" },
          topicArea: "relationships",
        },
        {
          en: "Besides technical skills, soft skills are needed too.",
          bn: "প্রযুক্তিগত দক্ষতা ছাড়াও, সফট স্কিলও প্রয়োজন।",
          slotValues: { THING: "technical skills", CLAUSE: "soft skills are needed too" },
          topicArea: "work",
        },
        {
          en: "Besides medicine, rest is also essential for recovery.",
          bn: "ওষুধ ছাড়াও, সুস্থতার জন্য বিশ্রামও অপরিহার্য।",
          slotValues: { THING: "medicine", CLAUSE: "rest is also essential for recovery" },
          topicArea: "health",
        },
        {
          en: "Besides the discount, they also offered free delivery.",
          bn: "ছাড় ছাড়াও, তারা বিনামূল্যে ডেলিভারিও দিয়েছে।",
          slotValues: { THING: "the discount", CLAUSE: "they also offered free delivery" },
          topicArea: "shopping",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Besides' introduces additional information to what has already been mentioned. It means 'in addition to'.",
      usageNote_bn:
        "'Besides' ইতিমধ্যে উল্লেখিত বিষয়ের সাথে অতিরিক্ত তথ্য যোগ করে। এর অর্থ 'ছাড়াও'।",
      combinableWith: ["I10.2"],
      banglaStructureMap:
        "[THING] ছাড়াও (Besides marker) + [CLAUSE] (Additional information)",
    },
    {
      id: "I10.2",
      formula: "In addition to [THING]...",
      formula_bn: "[জিনিস]-এর পাশাপাশি...",
      patternName: "In Addition To",
      patternName_bn: "পাশাপাশি",
      slots: [
        {
          name: "THING",
          description: "The thing already mentioned",
          description_bn: "ইতিমধ্যে উল্লেখিত জিনিস",
          acceptedTypes: ["noun", "noun_phrase", "gerund"],
          examples: ["his regular duties", "the main course", "studying"],
        },
      ],
      examples: [
        {
          en: "In addition to his regular duties, he also manages the team.",
          bn: "তার নিয়মিত দায়িত্বের পাশাপাশি, সে দলও পরিচালনা করে।",
          slotValues: { THING: "his regular duties" },
          topicArea: "work",
        },
        {
          en: "In addition to the main course, we ordered dessert.",
          bn: "প্রধান পদের পাশাপাশি, আমরা মিষ্টিও অর্ডার করলাম।",
          slotValues: { THING: "the main course" },
          topicArea: "food",
        },
        {
          en: "In addition to studying, she works part-time.",
          bn: "পড়াশোনার পাশাপাশি, সে পার্ট-টাইম কাজ করে।",
          slotValues: { THING: "studying" },
          topicArea: "education",
        },
        {
          en: "In addition to the hotel, the trip included a guided tour.",
          bn: "হোটেলের পাশাপাশি, ভ্রমণে একটি গাইডেড ট্যুরও ছিল।",
          slotValues: { THING: "the hotel" },
          topicArea: "travel",
        },
        {
          en: "In addition to the warranty, you get free servicing.",
          bn: "ওয়ারেন্টির পাশাপাশি, আপনি বিনামূল্যে সার্ভিসিং পাবেন।",
          slotValues: { THING: "the warranty" },
          topicArea: "shopping",
        },
        {
          en: "In addition to medicine, the doctor recommended physiotherapy.",
          bn: "ওষুধের পাশাপাশি, ডাক্তার ফিজিওথেরাপি সুপারিশ করেছে।",
          slotValues: { THING: "medicine" },
          topicArea: "health",
        },
        {
          en: "In addition to my family, my friends also helped me move.",
          bn: "আমার পরিবারের পাশাপাশি, আমার বন্ধুরাও আমাকে বাসা বদলাতে সাহায্য করেছে।",
          slotValues: { THING: "my family" },
          topicArea: "relationships",
        },
        {
          en: "In addition to the morning walk, I do yoga in the evening.",
          bn: "সকালে হাঁটার পাশাপাশি, আমি সন্ধ্যায় যোগব্যায়াম করি।",
          slotValues: { THING: "the morning walk" },
          topicArea: "daily_life",
        },
        {
          en: "In addition to Bengali, they teach English and Arabic.",
          bn: "বাংলার পাশাপাশি, তারা ইংরেজি এবং আরবি শেখায়।",
          slotValues: { THING: "Bengali" },
          topicArea: "education",
        },
        {
          en: "In addition to the ticket price, there's a service fee.",
          bn: "টিকিটের দামের পাশাপাশি, একটি সার্ভিস ফি আছে।",
          slotValues: { THING: "the ticket price" },
          topicArea: "travel",
        },
        {
          en: "In addition to rice, they served fish curry and dal.",
          bn: "ভাতের পাশাপাশি, তারা মাছের তরকারি এবং ডাল পরিবেশন করেছে।",
          slotValues: { THING: "rice" },
          topicArea: "food",
        },
        {
          en: "In addition to love, a relationship needs trust.",
          bn: "ভালোবাসার পাশাপাশি, একটি সম্পর্কে বিশ্বাসও দরকার।",
          slotValues: { THING: "love" },
          topicArea: "relationships",
        },
        {
          en: "In addition to the salary, they offer health insurance.",
          bn: "বেতনের পাশাপাশি, তারা স্বাস্থ্য বীমাও দেয়।",
          slotValues: { THING: "the salary" },
          topicArea: "work",
        },
        {
          en: "In addition to regular check-ups, eat a balanced diet.",
          bn: "নিয়মিত চেকআপের পাশাপাশি, সুষম খাবার খান।",
          slotValues: { THING: "regular check-ups" },
          topicArea: "health",
        },
        {
          en: "In addition to the clothes, I bought shoes and a bag.",
          bn: "কাপড়ের পাশাপাশি, আমি জুতা এবং ব্যাগও কিনেছি।",
          slotValues: { THING: "the clothes" },
          topicArea: "shopping",
        },
      ],
      formality: "formal",
      difficulty: "intermediate",
      usageNote:
        "'In addition to' is more formal than 'besides'. It's commonly used in written English and professional settings.",
      usageNote_bn:
        "'In addition to' 'besides'-এর চেয়ে বেশি আনুষ্ঠানিক। এটি সাধারণত লিখিত ইংরেজি এবং পেশাদার পরিবেশে ব্যবহৃত হয়।",
      combinableWith: ["I10.1"],
      banglaStructureMap:
        "[THING]-এর পাশাপাশি (In addition to marker) + ... (Additional clause)",
    },
    {
      id: "I10.3",
      formula: "Not only [CLAUSE], but also...",
      formula_bn: "শুধু [উপবাক্য] নয়, বরং...-ও",
      patternName: "Not Only...But Also",
      patternName_bn: "শুধু...নয়, বরং...ও",
      slots: [
        {
          name: "CLAUSE",
          description: "The first point",
          description_bn: "প্রথম বিষয়",
          acceptedTypes: ["clause"],
          examples: ["is he smart", "did she cook", "does it look good"],
        },
      ],
      examples: [
        {
          en: "Not only is he smart, but he is also very kind.",
          bn: "সে শুধু বুদ্ধিমানই নয়, বরং খুব দয়ালুও।",
          slotValues: { CLAUSE: "is he smart" },
          topicArea: "relationships",
        },
        {
          en: "Not only did she cook dinner, but she also cleaned the kitchen.",
          bn: "সে শুধু রাতের খাবার রান্না করেনি, বরং রান্নাঘরও পরিষ্কার করেছে।",
          slotValues: { CLAUSE: "did she cook dinner" },
          topicArea: "food",
        },
        {
          en: "Not only does it look good, but it also tastes amazing.",
          bn: "এটা শুধু দেখতে ভালো নয়, বরং স্বাদও অসাধারণ।",
          slotValues: { CLAUSE: "does it look good" },
          topicArea: "food",
        },
        {
          en: "Not only is Dhaka the capital, but it's also the largest city.",
          bn: "ঢাকা শুধু রাজধানীই নয়, বরং সবচেয়ে বড় শহরও।",
          slotValues: { CLAUSE: "is Dhaka the capital" },
          topicArea: "travel",
        },
        {
          en: "Not only did he pass the exam, but he also got the highest marks.",
          bn: "সে শুধু পরীক্ষায় পাশ করেনি, বরং সর্বোচ্চ নম্বরও পেয়েছে।",
          slotValues: { CLAUSE: "did he pass the exam" },
          topicArea: "education",
        },
        {
          en: "Not only did they offer a discount, but they also gave free shipping.",
          bn: "তারা শুধু ছাড় দেয়নি, বরং বিনামূল্যে ডেলিভারিও দিয়েছে।",
          slotValues: { CLAUSE: "did they offer a discount" },
          topicArea: "shopping",
        },
        {
          en: "Not only does she manage the team, but she also handles client meetings.",
          bn: "সে শুধু দল পরিচালনা করে না, বরং ক্লায়েন্ট মিটিংও সামলায়।",
          slotValues: { CLAUSE: "does she manage the team" },
          topicArea: "work",
        },
        {
          en: "Not only is exercise good for the body, but it's also good for the mind.",
          bn: "ব্যায়াম শুধু শরীরের জন্য ভালো নয়, বরং মনের জন্যও ভালো।",
          slotValues: { CLAUSE: "is exercise good for the body" },
          topicArea: "health",
        },
        {
          en: "Not only does he speak English, but he also writes poetry in it.",
          bn: "সে শুধু ইংরেজি বলে না, বরং এতে কবিতাও লেখে।",
          slotValues: { CLAUSE: "does he speak English" },
          topicArea: "education",
        },
        {
          en: "Not only is the hotel affordable, but it's also well-located.",
          bn: "হোটেলটি শুধু সাশ্রয়ীই নয়, বরং ভালো জায়গায়ও অবস্থিত।",
          slotValues: { CLAUSE: "is the hotel affordable" },
          topicArea: "travel",
        },
        {
          en: "Not only did she help me, but she also encouraged me.",
          bn: "সে শুধু আমাকে সাহায্য করেনি, বরং উৎসাহিতও করেছে।",
          slotValues: { CLAUSE: "did she help me" },
          topicArea: "relationships",
        },
        {
          en: "Not only is this product durable, but it's also eco-friendly.",
          bn: "এই পণ্যটি শুধু টেকসইই নয়, বরং পরিবেশ-বান্ধবও।",
          slotValues: { CLAUSE: "is this product durable" },
          topicArea: "shopping",
        },
        {
          en: "Not only did he lose weight, but he also gained muscle.",
          bn: "সে শুধু ওজন কমায়নি, বরং পেশিও বাড়িয়েছে।",
          slotValues: { CLAUSE: "did he lose weight" },
          topicArea: "health",
        },
        {
          en: "Not only did they complete the project, but they also finished it early.",
          bn: "তারা শুধু প্রকল্প সম্পন্ন করেনি, বরং সময়ের আগেই শেষ করেছে।",
          slotValues: { CLAUSE: "did they complete the project" },
          topicArea: "work",
        },
        {
          en: "Not only is it raining, but it's also very cold.",
          bn: "শুধু বৃষ্টি হচ্ছে না, বরং খুব ঠান্ডাও পড়েছে।",
          slotValues: { CLAUSE: "is it raining" },
          topicArea: "daily_life",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "'Not only...but also...' adds emphasis by showing that two positive or notable things are true.",
      usageNote_bn:
        "'Not only...but also...' দুটি ইতিবাচক বা উল্লেখযোগ্য বিষয় সত্য দেখিয়ে জোর দেয়।",
      combinableWith: ["I10.1"],
      banglaStructureMap:
        "শুধু (Not only) + [CLAUSE] (First point) + নয়, বরং (But also) + ... (Additional point) + -ও (Also marker)",
    },
    {
      id: "I10.4",
      formula: "On top of that...",
      formula_bn: "তার উপরে...",
      patternName: "On Top Of That",
      patternName_bn: "তার উপরে",
      slots: [],
      examples: [
        {
          en: "The food was expensive. On top of that, the service was terrible.",
          bn: "খাবার দামি ছিল। তার উপরে, পরিষেবা ভয়ংকর ছিল।",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "I missed the bus. On top of that, it started raining.",
          bn: "আমি বাস মিস করেছি। তার উপরে, বৃষ্টি শুরু হলো।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "He got a promotion. On top of that, he received a bonus.",
          bn: "সে পদোন্নতি পেয়েছে। তার উপরে, সে বোনাসও পেয়েছে।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "The exam was difficult. On top of that, I didn't have enough time.",
          bn: "পরীক্ষা কঠিন ছিল। তার উপরে, আমার পর্যাপ্ত সময় ছিল না।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "The price was already high. On top of that, they charged delivery fees.",
          bn: "দাম আগে থেকেই বেশি ছিল। তার উপরে, তারা ডেলিভারি ফিও নিয়েছে।",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "I had a headache. On top of that, I couldn't sleep well.",
          bn: "আমার মাথাব্যথা ছিল। তার উপরে, ভালো ঘুমাতে পারিনি।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "She forgot my birthday. On top of that, she didn't even apologize.",
          bn: "সে আমার জন্মদিন ভুলে গেছে। তার উপরে, ক্ষমাও চায়নি।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "The weather was beautiful. On top of that, we found a great restaurant.",
          bn: "আবহাওয়া সুন্দর ছিল। তার উপরে, আমরা একটি দারুণ রেস্তোরাঁ পেলাম।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "She cooked biryani. On top of that, she made my favorite dessert.",
          bn: "সে বিরিয়ানি রান্না করেছে। তার উপরে, আমার প্রিয় মিষ্টিও তৈরি করেছে।",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "I learned English. On top of that, I picked up some Arabic too.",
          bn: "আমি ইংরেজি শিখেছি। তার উপরে, কিছু আরবিও শিখেছি।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "The traffic was terrible. On top of that, my car broke down.",
          bn: "যানজট ভয়ংকর ছিল। তার উপরে, আমার গাড়ি নষ্ট হয়ে গেল।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "He supported me financially. On top of that, he gave me career advice.",
          bn: "সে আমাকে আর্থিকভাবে সাহায্য করেছে। তার উপরে, ক্যারিয়ার পরামর্শও দিয়েছে।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "The deadline was moved up. On top of that, two team members called in sick.",
          bn: "সময়সীমা এগিয়ে আনা হয়েছে। তার উপরে, দুইজন দলের সদস্য অসুস্থ বলেছে।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "I caught a cold. On top of that, my fever got worse.",
          bn: "আমার সর্দি হয়েছে। তার উপরে, জ্বর আরো বেড়েছে।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "The bag was on sale. On top of that, I had a coupon for extra discount.",
          bn: "ব্যাগটি সেলে ছিল। তার উপরে, আমার কাছে অতিরিক্ত ছাড়ের কুপন ছিল।",
          slotValues: {},
          topicArea: "shopping",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'On top of that' is used in spoken English to add more information, often to emphasize that a situation is even more extreme.",
      usageNote_bn:
        "'On top of that' কথ্য ইংরেজিতে আরও তথ্য যোগ করতে ব্যবহৃত হয়, প্রায়ই পরিস্থিতি আরও চরম তা জোর দিতে।",
      combinableWith: ["I10.1"],
      banglaStructureMap:
        "তার উপরে (On top of that) + ... (Additional information)",
    },
    {
      id: "I10.5",
      formula: "Apart from [THING]...",
      formula_bn: "[জিনিস] বাদে...",
      patternName: "Apart From",
      patternName_bn: "বাদে",
      slots: [
        {
          name: "THING",
          description: "The thing being set aside or excluded",
          description_bn: "যে জিনিসটি আলাদা করা বা বাদ দেওয়া হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase", "gerund"],
          examples: ["the weather", "a few mistakes", "the price"],
        },
      ],
      examples: [
        {
          en: "Apart from the weather, the trip was wonderful.",
          bn: "আবহাওয়া বাদে, ভ্রমণটি চমৎকার ছিল।",
          slotValues: { THING: "the weather" },
          topicArea: "travel",
        },
        {
          en: "Apart from a few mistakes, your essay is excellent.",
          bn: "কয়েকটি ভুল বাদে, তোমার প্রবন্ধ চমৎকার।",
          slotValues: { THING: "a few mistakes" },
          topicArea: "education",
        },
        {
          en: "Apart from the price, this product is perfect.",
          bn: "দাম বাদে, এই পণ্যটি নিখুঁত।",
          slotValues: { THING: "the price" },
          topicArea: "shopping",
        },
        {
          en: "Apart from the spiciness, the food was delicious.",
          bn: "ঝালের কথা বাদে, খাবার সুস্বাদু ছিল।",
          slotValues: { THING: "the spiciness" },
          topicArea: "food",
        },
        {
          en: "Apart from being tired, I feel fine.",
          bn: "ক্লান্তি বাদে, আমি ভালো আছি।",
          slotValues: { THING: "being tired" },
          topicArea: "health",
        },
        {
          en: "Apart from the long hours, I enjoy my job.",
          bn: "দীর্ঘ কাজের সময় বাদে, আমি আমার চাকরি উপভোগ করি।",
          slotValues: { THING: "the long hours" },
          topicArea: "work",
        },
        {
          en: "Apart from one argument, our relationship is great.",
          bn: "একটি তর্ক বাদে, আমাদের সম্পর্ক দারুণ।",
          slotValues: { THING: "one argument" },
          topicArea: "relationships",
        },
        {
          en: "Apart from the noise, this neighborhood is lovely.",
          bn: "শব্দ বাদে, এই পাড়াটি সুন্দর।",
          slotValues: { THING: "the noise" },
          topicArea: "daily_life",
        },
        {
          en: "Apart from the delay, the flight was comfortable.",
          bn: "দেরি বাদে, ফ্লাইটটি আরামদায়ক ছিল।",
          slotValues: { THING: "the delay" },
          topicArea: "travel",
        },
        {
          en: "Apart from English, she speaks three other languages.",
          bn: "ইংরেজি বাদে, সে আরো তিনটি ভাষায় কথা বলে।",
          slotValues: { THING: "English" },
          topicArea: "education",
        },
        {
          en: "Apart from the dessert, the whole meal was healthy.",
          bn: "মিষ্টি বাদে, পুরো খাবার স্বাস্থ্যকর ছিল।",
          slotValues: { THING: "the dessert" },
          topicArea: "food",
        },
        {
          en: "Apart from a minor headache, I recovered quickly.",
          bn: "সামান্য মাথাব্যথা বাদে, আমি দ্রুত সুস্থ হয়ে গেছি।",
          slotValues: { THING: "a minor headache" },
          topicArea: "health",
        },
        {
          en: "Apart from the salary, the work environment is terrible.",
          bn: "বেতন বাদে, কাজের পরিবেশ ভয়ংকর।",
          slotValues: { THING: "the salary" },
          topicArea: "work",
        },
        {
          en: "Apart from my sister, no one understood me.",
          bn: "আমার বোন বাদে, কেউ আমাকে বোঝেনি।",
          slotValues: { THING: "my sister" },
          topicArea: "relationships",
        },
        {
          en: "Apart from the color, this shirt is exactly what I wanted.",
          bn: "রং বাদে, এই শার্টটি ঠিক আমি যা চেয়েছিলাম।",
          slotValues: { THING: "the color" },
          topicArea: "shopping",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "'Apart from' can mean both 'in addition to' and 'except for', depending on context.",
      usageNote_bn:
        "'Apart from' প্রসঙ্গ অনুযায়ী 'ছাড়াও' এবং 'বাদে' উভয় অর্থ বহন করতে পারে।",
      combinableWith: ["I10.1"],
      banglaStructureMap:
        "[THING] বাদে (Apart from marker) + ... (Remaining information)",
    },
  ],
};
