import { PatternCategory } from "@/types/pattern";

export const categoryI3: PatternCategory = {
  id: "I3",
  slug: "so-that-such-that",
  name: "So...That / Such...That",
  name_bn: "এতটাই...যে / এমন...যে",
  description:
    "Learn how to express cause and effect using 'so...that' and 'such...that' patterns in English.",
  description_bn:
    "ইংরেজিতে 'so...that' এবং 'such...that' প্যাটার্ন ব্যবহার করে কারণ ও ফলাফল প্রকাশ করতে শিখুন।",
  icon: "📊",
  group: "I",
  groupName: "Comparing & Contrasting",
  groupName_bn: "তুলনা এবং বৈপরীত্য",
  difficulty: "intermediate",
  patterns: [
    {
      id: "I3.1",
      formula: "[THING] is so [ADJECTIVE] that [CLAUSE]",
      formula_bn: "[জিনিস] এতটাই [বিশেষণ] যে [উপবাক্য]",
      patternName: "So + Adjective + That",
      patternName_bn: "So + বিশেষণ + That",
      slots: [
        {
          name: "THING",
          description: "The subject being described",
          description_bn: "যে বিষয়টি বর্ণনা করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["The weather", "This book", "The food"],
        },
        {
          name: "ADJECTIVE",
          description: "The adjective describing the extreme quality",
          description_bn: "চরম গুণ বর্ণনাকারী বিশেষণ",
          acceptedTypes: ["adjective"],
          examples: ["hot", "interesting", "spicy"],
        },
        {
          name: "CLAUSE",
          description: "The result of the extreme quality",
          description_bn: "চরম গুণের ফলাফল",
          acceptedTypes: ["clause"],
          examples: [
            "I can't go outside",
            "I couldn't put it down",
            "I needed water",
          ],
        },
      ],
      examples: [
        {
          en: "The weather is so hot that I can't go outside.",
          bn: "আবহাওয়া এতটাই গরম যে আমি বাইরে যেতে পারছি না।",
          slotValues: { THING: "The weather", ADJECTIVE: "hot", CLAUSE: "I can't go outside" },
          topicArea: "daily_life",
        },
        {
          en: "This book is so interesting that I couldn't put it down.",
          bn: "এই বইটি এতটাই আকর্ষণীয় যে আমি নামাতে পারিনি।",
          slotValues: { THING: "This book", ADJECTIVE: "interesting", CLAUSE: "I couldn't put it down" },
          topicArea: "education",
        },
        {
          en: "The food is so spicy that I needed water.",
          bn: "খাবারটি এতটাই ঝাল যে আমার পানি লাগল।",
          slotValues: { THING: "The food", ADJECTIVE: "spicy", CLAUSE: "I needed water" },
          topicArea: "food",
        },
        {
          en: "The exam was so difficult that many students failed.",
          bn: "পরীক্ষাটি এতটাই কঠিন ছিল যে অনেক ছাত্র ফেল করেছে।",
          slotValues: { THING: "The exam", ADJECTIVE: "difficult", CLAUSE: "many students failed" },
          topicArea: "education",
        },
        {
          en: "The hotel was so expensive that we chose another one.",
          bn: "হোটেলটি এতটাই দামি ছিল যে আমরা অন্য একটি বেছে নিলাম।",
          slotValues: { THING: "The hotel", ADJECTIVE: "expensive", CLAUSE: "we chose another one" },
          topicArea: "travel",
        },
        {
          en: "The movie was so boring that I fell asleep.",
          bn: "মুভিটি এতটাই বিরক্তিকর ছিল যে আমি ঘুমিয়ে পড়লাম।",
          slotValues: { THING: "The movie", ADJECTIVE: "boring", CLAUSE: "I fell asleep" },
          topicArea: "daily_life",
        },
        {
          en: "The traffic was so bad that I was late for work.",
          bn: "ট্রাফিক এতটাই খারাপ ছিল যে আমি কাজে দেরি করলাম।",
          slotValues: { THING: "The traffic", ADJECTIVE: "bad", CLAUSE: "I was late for work" },
          topicArea: "work",
        },
        {
          en: "She was so tired that she went to bed early.",
          bn: "সে এতটাই ক্লান্ত ছিল যে তাড়াতাড়ি ঘুমাতে গেল।",
          slotValues: { THING: "She", ADJECTIVE: "tired", CLAUSE: "she went to bed early" },
          topicArea: "health",
        },
        {
          en: "The bag was so heavy that I couldn't carry it.",
          bn: "ব্যাগটি এতটাই ভারী ছিল যে আমি বহন করতে পারিনি।",
          slotValues: { THING: "The bag", ADJECTIVE: "heavy", CLAUSE: "I couldn't carry it" },
          topicArea: "shopping",
        },
        {
          en: "He was so kind that everyone liked him.",
          bn: "সে এতটাই দয়ালু ছিল যে সবাই তাকে পছন্দ করত।",
          slotValues: { THING: "He", ADJECTIVE: "kind", CLAUSE: "everyone liked him" },
          topicArea: "relationships",
        },
        {
          en: "The noise was so loud that I couldn't sleep.",
          bn: "শব্দ এতটাই জোরে ছিল যে আমি ঘুমাতে পারিনি।",
          slotValues: { THING: "The noise", ADJECTIVE: "loud", CLAUSE: "I couldn't sleep" },
          topicArea: "daily_life",
        },
        {
          en: "The road was so narrow that two cars couldn't pass.",
          bn: "রাস্তাটি এতটাই সরু ছিল যে দুটি গাড়ি যেতে পারেনি।",
          slotValues: { THING: "The road", ADJECTIVE: "narrow", CLAUSE: "two cars couldn't pass" },
          topicArea: "travel",
        },
        {
          en: "The task was so simple that everyone finished early.",
          bn: "কাজটি এতটাই সহজ ছিল যে সবাই তাড়াতাড়ি শেষ করল।",
          slotValues: { THING: "The task", ADJECTIVE: "simple", CLAUSE: "everyone finished early" },
          topicArea: "work",
        },
        {
          en: "The cake was so delicious that I had a second piece.",
          bn: "কেকটি এতটাই সুস্বাদু ছিল যে আমি দ্বিতীয় টুকরো খেলাম।",
          slotValues: { THING: "The cake", ADJECTIVE: "delicious", CLAUSE: "I had a second piece" },
          topicArea: "food",
        },
        {
          en: "The pain was so severe that I went to the hospital.",
          bn: "ব্যথা এতটাই তীব্র ছিল যে আমি হাসপাতালে গেলাম।",
          slotValues: { THING: "The pain", ADJECTIVE: "severe", CLAUSE: "I went to the hospital" },
          topicArea: "health",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "Use 'so + adjective + that' to emphasize an extreme quality and its result. Very common in everyday speech.",
      usageNote_bn:
        "একটি চরম গুণ এবং তার ফলাফলের উপর জোর দিতে 'so + adjective + that' ব্যবহার করুন। দৈনন্দিন কথোপকথনে খুবই সাধারণ।",
      combinableWith: ["I3.2"],
      banglaStructureMap:
        "[THING] (Subject) + এতটাই (Intensifier) + [ADJ] (Adjective) + যে (Connector) + [CLAUSE] (Result)",
    },
    {
      id: "I3.2",
      formula: "It was such a [ADJECTIVE] [THING] that [CLAUSE]",
      formula_bn: "এটি এমন একটি [বিশেষণ] [জিনিস] ছিল যে [উপবাক্য]",
      patternName: "Such + Noun Phrase + That",
      patternName_bn: "Such + বিশেষ্য পদবন্ধ + That",
      slots: [
        {
          name: "ADJECTIVE",
          description: "The adjective modifying the noun",
          description_bn: "বিশেষ্যকে বিশেষিত করা বিশেষণ",
          acceptedTypes: ["adjective"],
          examples: ["beautiful", "difficult", "long"],
        },
        {
          name: "THING",
          description: "The noun being described",
          description_bn: "যে বিশেষ্যটি বর্ণনা করা হচ্ছে",
          acceptedTypes: ["noun"],
          examples: ["day", "exam", "journey"],
        },
        {
          name: "CLAUSE",
          description: "The result clause",
          description_bn: "ফলাফল উপবাক্য",
          acceptedTypes: ["clause"],
          examples: [
            "I took many photos",
            "half the class failed",
            "we were exhausted",
          ],
        },
      ],
      examples: [
        {
          en: "It was such a beautiful day that I took many photos.",
          bn: "এটি এমন একটি সুন্দর দিন ছিল যে আমি অনেক ছবি তুললাম।",
          slotValues: { ADJECTIVE: "beautiful", THING: "day", CLAUSE: "I took many photos" },
          topicArea: "daily_life",
        },
        {
          en: "It was such a difficult exam that half the class failed.",
          bn: "এটি এমন একটি কঠিন পরীক্ষা ছিল যে অর্ধেক ক্লাস ফেল করল।",
          slotValues: { ADJECTIVE: "difficult", THING: "exam", CLAUSE: "half the class failed" },
          topicArea: "education",
        },
        {
          en: "It was such a long journey that we were exhausted.",
          bn: "এটি এমন একটি দীর্ঘ যাত্রা ছিল যে আমরা ক্লান্ত হয়ে পড়লাম।",
          slotValues: { ADJECTIVE: "long", THING: "journey", CLAUSE: "we were exhausted" },
          topicArea: "travel",
        },
        {
          en: "It was such a delicious meal that everyone asked for the recipe.",
          bn: "এটি এমন একটি সুস্বাদু খাবার ছিল যে সবাই রেসিপি চাইল।",
          slotValues: { ADJECTIVE: "delicious", THING: "meal", CLAUSE: "everyone asked for the recipe" },
          topicArea: "food",
        },
        {
          en: "It was such a boring movie that we left early.",
          bn: "এটি এমন একটি বিরক্তিকর মুভি ছিল যে আমরা তাড়াতাড়ি চলে এলাম।",
          slotValues: { ADJECTIVE: "boring", THING: "movie", CLAUSE: "we left early" },
          topicArea: "daily_life",
        },
        {
          en: "It was such a stressful week that I needed a vacation.",
          bn: "এটি এমন একটি চাপের সপ্তাহ ছিল যে আমার ছুটি দরকার ছিল।",
          slotValues: { ADJECTIVE: "stressful", THING: "week", CLAUSE: "I needed a vacation" },
          topicArea: "work",
        },
        {
          en: "It was such a cold night that we stayed indoors.",
          bn: "এটি এমন একটি ঠান্ডা রাত ছিল যে আমরা ঘরেই থাকলাম।",
          slotValues: { ADJECTIVE: "cold", THING: "night", CLAUSE: "we stayed indoors" },
          topicArea: "daily_life",
        },
        {
          en: "It was such a heavy bag that I couldn't lift it.",
          bn: "এটি এমন একটি ভারী ব্যাগ ছিল যে আমি তুলতে পারিনি।",
          slotValues: { ADJECTIVE: "heavy", THING: "bag", CLAUSE: "I couldn't lift it" },
          topicArea: "shopping",
        },
        {
          en: "It was such a kind gesture that I was deeply touched.",
          bn: "এটি এমন একটি দয়ালু আচরণ ছিল যে আমি গভীরভাবে স্পর্শিত হলাম।",
          slotValues: { ADJECTIVE: "kind", THING: "gesture", CLAUSE: "I was deeply touched" },
          topicArea: "relationships",
        },
        {
          en: "It was such a painful experience that I still remember it.",
          bn: "এটি এমন একটি কষ্টদায়ক অভিজ্ঞতা ছিল যে আমি এখনও মনে রাখি।",
          slotValues: { ADJECTIVE: "painful", THING: "experience", CLAUSE: "I still remember it" },
          topicArea: "health",
        },
        {
          en: "It was such a useful course that I recommended it to everyone.",
          bn: "এটি এমন একটি উপকারী কোর্স ছিল যে আমি সবাইকে সুপারিশ করলাম।",
          slotValues: { ADJECTIVE: "useful", THING: "course", CLAUSE: "I recommended it to everyone" },
          topicArea: "education",
        },
        {
          en: "It was such a busy day that I skipped lunch.",
          bn: "এটি এমন একটি ব্যস্ত দিন ছিল যে আমি দুপুরের খাবার বাদ দিলাম।",
          slotValues: { ADJECTIVE: "busy", THING: "day", CLAUSE: "I skipped lunch" },
          topicArea: "work",
        },
        {
          en: "It was such a scary flight that I never wanted to fly again.",
          bn: "এটি এমন একটি ভয়ংকর ফ্লাইট ছিল যে আমি আর কখনো উড়তে চাইনি।",
          slotValues: { ADJECTIVE: "scary", THING: "flight", CLAUSE: "I never wanted to fly again" },
          topicArea: "travel",
        },
        {
          en: "It was such a spicy curry that my eyes watered.",
          bn: "এটি এমন একটি ঝাল তরকারি ছিল যে আমার চোখে পানি এল।",
          slotValues: { ADJECTIVE: "spicy", THING: "curry", CLAUSE: "my eyes watered" },
          topicArea: "food",
        },
        {
          en: "It was such a good deal that I bought two.",
          bn: "এটি এমন একটি ভালো দর ছিল যে আমি দুটো কিনলাম।",
          slotValues: { ADJECTIVE: "good", THING: "deal", CLAUSE: "I bought two" },
          topicArea: "shopping",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "Use 'such a + adjective + noun + that' with singular countable nouns. Drop 'a' for uncountable or plural nouns.",
      usageNote_bn:
        "একবচন গণনাযোগ্য বিশেষ্যের সাথে 'such a + adjective + noun + that' ব্যবহার করুন। অগণনীয় বা বহুবচন বিশেষ্যের জন্য 'a' বাদ দিন।",
      combinableWith: ["I3.1"],
      banglaStructureMap:
        "এটি (Subject) + এমন একটি (Intensifier) + [ADJ] [THING] (Noun phrase) + ছিল যে (Connector) + [CLAUSE] (Result)",
    },
    {
      id: "I3.3",
      formula: "There were so many [THINGS] that [CLAUSE]",
      formula_bn: "এত বেশি [জিনিস] ছিল যে [উপবাক্য]",
      patternName: "So Many + That",
      patternName_bn: "So Many + That",
      slots: [
        {
          name: "THINGS",
          description: "The plural noun being described",
          description_bn: "যে বহুবচন বিশেষ্যটি বর্ণনা করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["people", "cars", "questions"],
        },
        {
          name: "CLAUSE",
          description: "The result of the large quantity",
          description_bn: "বেশি পরিমাণের ফলাফল",
          acceptedTypes: ["clause"],
          examples: [
            "we couldn't find seats",
            "the road was blocked",
            "the teacher ran out of time",
          ],
        },
      ],
      examples: [
        {
          en: "There were so many people that we couldn't find seats.",
          bn: "এত বেশি মানুষ ছিল যে আমরা আসন খুঁজে পাইনি।",
          slotValues: { THINGS: "people", CLAUSE: "we couldn't find seats" },
          topicArea: "daily_life",
        },
        {
          en: "There were so many cars that the road was blocked.",
          bn: "এত বেশি গাড়ি ছিল যে রাস্তা বন্ধ হয়ে গেল।",
          slotValues: { THINGS: "cars", CLAUSE: "the road was blocked" },
          topicArea: "travel",
        },
        {
          en: "There were so many questions that the teacher ran out of time.",
          bn: "এত বেশি প্রশ্ন ছিল যে শিক্ষকের সময় শেষ হয়ে গেল।",
          slotValues: { THINGS: "questions", CLAUSE: "the teacher ran out of time" },
          topicArea: "education",
        },
        {
          en: "There were so many dishes that I couldn't decide.",
          bn: "এত বেশি পদ ছিল যে আমি সিদ্ধান্ত নিতে পারিনি।",
          slotValues: { THINGS: "dishes", CLAUSE: "I couldn't decide" },
          topicArea: "food",
        },
        {
          en: "There were so many tasks that I worked overtime.",
          bn: "এত বেশি কাজ ছিল যে আমি ওভারটাইম কাজ করলাম।",
          slotValues: { THINGS: "tasks", CLAUSE: "I worked overtime" },
          topicArea: "work",
        },
        {
          en: "There were so many options that I felt confused.",
          bn: "এত বেশি বিকল্প ছিল যে আমি বিভ্রান্ত হয়ে গেলাম।",
          slotValues: { THINGS: "options", CLAUSE: "I felt confused" },
          topicArea: "shopping",
        },
        {
          en: "There were so many patients that the doctor was exhausted.",
          bn: "এত বেশি রোগী ছিল যে ডাক্তার ক্লান্ত হয়ে পড়লেন।",
          slotValues: { THINGS: "patients", CLAUSE: "the doctor was exhausted" },
          topicArea: "health",
        },
        {
          en: "There were so many guests that we ran out of food.",
          bn: "এত বেশি অতিথি ছিল যে আমাদের খাবার শেষ হয়ে গেল।",
          slotValues: { THINGS: "guests", CLAUSE: "we ran out of food" },
          topicArea: "relationships",
        },
        {
          en: "There were so many tourists that the beach was crowded.",
          bn: "এত বেশি পর্যটক ছিল যে সমুদ্র সৈকত ভিড়ে ভরে গেল।",
          slotValues: { THINGS: "tourists", CLAUSE: "the beach was crowded" },
          topicArea: "travel",
        },
        {
          en: "There were so many books that the shelf collapsed.",
          bn: "এত বেশি বই ছিল যে তাক ভেঙে পড়ল।",
          slotValues: { THINGS: "books", CLAUSE: "the shelf collapsed" },
          topicArea: "education",
        },
        {
          en: "There were so many complaints that the manager apologized.",
          bn: "এত বেশি অভিযোগ ছিল যে ম্যানেজার ক্ষমা চাইলেন।",
          slotValues: { THINGS: "complaints", CLAUSE: "the manager apologized" },
          topicArea: "work",
        },
        {
          en: "There were so many mosquitoes that I couldn't sleep.",
          bn: "এত বেশি মশা ছিল যে আমি ঘুমাতে পারিনি।",
          slotValues: { THINGS: "mosquitoes", CLAUSE: "I couldn't sleep" },
          topicArea: "daily_life",
        },
        {
          en: "There were so many choices that shopping took hours.",
          bn: "এত বেশি পছন্দ ছিল যে কেনাকাটায় ঘণ্টার পর ঘণ্টা লাগল।",
          slotValues: { THINGS: "choices", CLAUSE: "shopping took hours" },
          topicArea: "shopping",
        },
        {
          en: "There were so many flavors that I tried five different ones.",
          bn: "এত বেশি ফ্লেভার ছিল যে আমি পাঁচটি ভিন্ন ফ্লেভার চেষ্টা করলাম।",
          slotValues: { THINGS: "flavors", CLAUSE: "I tried five different ones" },
          topicArea: "food",
        },
        {
          en: "There were so many friends at the party that I couldn't talk to everyone.",
          bn: "পার্টিতে এত বেশি বন্ধু ছিল যে আমি সবার সাথে কথা বলতে পারিনি।",
          slotValues: { THINGS: "friends at the party", CLAUSE: "I couldn't talk to everyone" },
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "Use 'so many + plural noun + that' to emphasize a large quantity and its effect. Use 'so much' with uncountable nouns.",
      usageNote_bn:
        "বেশি পরিমাণ এবং তার প্রভাবের উপর জোর দিতে 'so many + বহুবচন বিশেষ্য + that' ব্যবহার করুন। অগণনীয় বিশেষ্যের সাথে 'so much' ব্যবহার করুন।",
      combinableWith: ["I3.1"],
      banglaStructureMap:
        "এত বেশি (Intensifier) + [THINGS] (Subject) + ছিল যে (Connector) + [CLAUSE] (Result)",
    },
    {
      id: "I3.4",
      formula: "[PERSON] [VERB+ED] so [ADVERB] that [CLAUSE]",
      formula_bn: "[ব্যক্তি] এত [ক্রিয়াবিশেষণ] [ক্রিয়া করেছে] যে [উপবাক্য]",
      patternName: "So + Adverb + That",
      patternName_bn: "So + ক্রিয়াবিশেষণ + That",
      slots: [
        {
          name: "PERSON",
          description: "The person performing the action",
          description_bn: "যে ব্যক্তি কাজটি করছে",
          acceptedTypes: ["person", "noun"],
          examples: ["She", "He", "The teacher"],
        },
        {
          name: "VERB+ED",
          description: "A past tense verb",
          description_bn: "অতীত কালের ক্রিয়া",
          acceptedTypes: ["verb"],
          examples: ["spoke", "ran", "worked"],
        },
        {
          name: "ADVERB",
          description: "An adverb describing the manner",
          description_bn: "পদ্ধতি বর্ণনাকারী ক্রিয়াবিশেষণ",
          acceptedTypes: ["adverb"],
          examples: ["quickly", "loudly", "hard"],
        },
        {
          name: "CLAUSE",
          description: "The result of the action",
          description_bn: "কাজের ফলাফল",
          acceptedTypes: ["clause"],
          examples: [
            "nobody understood",
            "he won the race",
            "she got promoted",
          ],
        },
      ],
      examples: [
        {
          en: "She spoke so quickly that nobody understood her.",
          bn: "সে এত দ্রুত কথা বলেছিল যে কেউ তাকে বুঝতে পারেনি।",
          slotValues: { PERSON: "She", "VERB+ED": "spoke", ADVERB: "quickly", CLAUSE: "nobody understood her" },
          topicArea: "daily_life",
        },
        {
          en: "He ran so fast that he won the race.",
          bn: "সে এত দ্রুত দৌড়েছিল যে সে রেস জিতেছে।",
          slotValues: { PERSON: "He", "VERB+ED": "ran", ADVERB: "fast", CLAUSE: "he won the race" },
          topicArea: "health",
        },
        {
          en: "She worked so hard that she got promoted.",
          bn: "সে এত পরিশ্রম করেছিল যে তার পদোন্নতি হয়েছে।",
          slotValues: { PERSON: "She", "VERB+ED": "worked", ADVERB: "hard", CLAUSE: "she got promoted" },
          topicArea: "work",
        },
        {
          en: "He ate so quickly that he got a stomachache.",
          bn: "সে এত দ্রুত খেয়েছিল যে তার পেটে ব্যথা হয়েছে।",
          slotValues: { PERSON: "He", "VERB+ED": "ate", ADVERB: "quickly", CLAUSE: "he got a stomachache" },
          topicArea: "food",
        },
        {
          en: "The teacher explained so clearly that everyone understood.",
          bn: "শিক্ষক এত স্পষ্টভাবে ব্যাখ্যা করেছিলেন যে সবাই বুঝেছে।",
          slotValues: { PERSON: "The teacher", "VERB+ED": "explained", ADVERB: "clearly", CLAUSE: "everyone understood" },
          topicArea: "education",
        },
        {
          en: "He drove so carefully that we arrived safely.",
          bn: "সে এত সাবধানে গাড়ি চালিয়েছিল যে আমরা নিরাপদে পৌঁছেছি।",
          slotValues: { PERSON: "He", "VERB+ED": "drove", ADVERB: "carefully", CLAUSE: "we arrived safely" },
          topicArea: "travel",
        },
        {
          en: "She sang so beautifully that the audience was amazed.",
          bn: "সে এত সুন্দর গান গেয়েছিল যে দর্শক মুগ্ধ হয়ে গেল।",
          slotValues: { PERSON: "She", "VERB+ED": "sang", ADVERB: "beautifully", CLAUSE: "the audience was amazed" },
          topicArea: "daily_life",
        },
        {
          en: "He studied so diligently that he topped the class.",
          bn: "সে এত পরিশ্রমের সাথে পড়াশোনা করেছিল যে সে ক্লাসে প্রথম হয়েছে।",
          slotValues: { PERSON: "He", "VERB+ED": "studied", ADVERB: "diligently", CLAUSE: "he topped the class" },
          topicArea: "education",
        },
        {
          en: "She cooked so well that everyone complimented the food.",
          bn: "সে এত ভালো রান্না করেছিল যে সবাই খাবারের প্রশংসা করেছে।",
          slotValues: { PERSON: "She", "VERB+ED": "cooked", ADVERB: "well", CLAUSE: "everyone complimented the food" },
          topicArea: "food",
        },
        {
          en: "He typed so slowly that the boss got impatient.",
          bn: "সে এত ধীরে টাইপ করেছিল যে বস অধৈর্য হয়ে পড়েছে।",
          slotValues: { PERSON: "He", "VERB+ED": "typed", ADVERB: "slowly", CLAUSE: "the boss got impatient" },
          topicArea: "work",
        },
        {
          en: "She laughed so loudly that everyone turned around.",
          bn: "সে এত জোরে হেসেছিল যে সবাই ঘুরে তাকাল।",
          slotValues: { PERSON: "She", "VERB+ED": "laughed", ADVERB: "loudly", CLAUSE: "everyone turned around" },
          topicArea: "relationships",
        },
        {
          en: "He spent so freely that he ran out of money.",
          bn: "সে এত মুক্তভাবে খরচ করেছিল যে তার টাকা শেষ হয়ে গেল।",
          slotValues: { PERSON: "He", "VERB+ED": "spent", ADVERB: "freely", CLAUSE: "he ran out of money" },
          topicArea: "shopping",
        },
        {
          en: "She exercised so regularly that she lost ten kilograms.",
          bn: "সে এত নিয়মিত ব্যায়াম করেছিল যে সে দশ কিলো ওজন কমিয়েছে।",
          slotValues: { PERSON: "She", "VERB+ED": "exercised", ADVERB: "regularly", CLAUSE: "she lost ten kilograms" },
          topicArea: "health",
        },
        {
          en: "He packed so neatly that everything fit in one bag.",
          bn: "সে এত পরিপাটি করে গুছিয়েছিল যে সব কিছু একটি ব্যাগে ঢুকেছে।",
          slotValues: { PERSON: "He", "VERB+ED": "packed", ADVERB: "neatly", CLAUSE: "everything fit in one bag" },
          topicArea: "travel",
        },
        {
          en: "She talked so politely that the customer calmed down.",
          bn: "সে এত বিনয়ের সাথে কথা বলেছিল যে গ্রাহক শান্ত হয়ে গেল।",
          slotValues: { PERSON: "She", "VERB+ED": "talked", ADVERB: "politely", CLAUSE: "the customer calmed down" },
          topicArea: "work",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "Use 'so + adverb + that' to emphasize how an action was performed and its resulting effect.",
      usageNote_bn:
        "একটি কাজ কীভাবে সম্পাদিত হয়েছে এবং তার ফলাফলের উপর জোর দিতে 'so + adverb + that' ব্যবহার করুন।",
      combinableWith: ["I3.1"],
      banglaStructureMap:
        "[PERSON] (Subject) + এত (Intensifier) + [ADVERB] (Adverb) + [VERB] (Verb) + যে (Connector) + [CLAUSE] (Result)",
    },
    {
      id: "I3.5",
      formula: "It was such [THING] that [CLAUSE]",
      formula_bn: "এটি এমন [জিনিস] ছিল যে [উপবাক্য]",
      patternName: "Such + Uncountable/Plural Noun + That",
      patternName_bn: "Such + অগণনীয়/বহুবচন বিশেষ্য + That",
      slots: [
        {
          name: "THING",
          description: "An uncountable or modified noun phrase",
          description_bn: "একটি অগণনীয় বা পরিবর্তিত বিশেষ্য পদবন্ধ",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["good weather", "bad news", "great fun"],
        },
        {
          name: "CLAUSE",
          description: "The result clause",
          description_bn: "ফলাফল উপবাক্য",
          acceptedTypes: ["clause"],
          examples: [
            "we stayed outside all day",
            "everyone was upset",
            "nobody wanted to leave",
          ],
        },
      ],
      examples: [
        {
          en: "It was such good weather that we stayed outside all day.",
          bn: "আবহাওয়া এমন ভালো ছিল যে আমরা সারাদিন বাইরে থাকলাম।",
          slotValues: { THING: "good weather", CLAUSE: "we stayed outside all day" },
          topicArea: "daily_life",
        },
        {
          en: "It was such bad news that everyone was upset.",
          bn: "এটি এমন খারাপ খবর ছিল যে সবাই মন খারাপ করেছিল।",
          slotValues: { THING: "bad news", CLAUSE: "everyone was upset" },
          topicArea: "daily_life",
        },
        {
          en: "It was such great fun that nobody wanted to leave.",
          bn: "এটি এমন দারুণ মজা ছিল যে কেউ চলে যেতে চায়নি।",
          slotValues: { THING: "great fun", CLAUSE: "nobody wanted to leave" },
          topicArea: "relationships",
        },
        {
          en: "It was such heavy rain that the streets flooded.",
          bn: "এটি এমন ভারী বৃষ্টি ছিল যে রাস্তা ডুবে গেল।",
          slotValues: { THING: "heavy rain", CLAUSE: "the streets flooded" },
          topicArea: "daily_life",
        },
        {
          en: "It was such useful advice that I followed it immediately.",
          bn: "এটি এমন উপকারী পরামর্শ ছিল যে আমি সাথে সাথে মেনে চললাম।",
          slotValues: { THING: "useful advice", CLAUSE: "I followed it immediately" },
          topicArea: "education",
        },
        {
          en: "It was such loud music that the neighbors complained.",
          bn: "এটি এমন জোরে গান ছিল যে প্রতিবেশীরা অভিযোগ করেছে।",
          slotValues: { THING: "loud music", CLAUSE: "the neighbors complained" },
          topicArea: "daily_life",
        },
        {
          en: "It was such hard work that I was exhausted by evening.",
          bn: "এটি এমন কঠিন কাজ ছিল যে সন্ধ্যার মধ্যে আমি ক্লান্ত হয়ে পড়লাম।",
          slotValues: { THING: "hard work", CLAUSE: "I was exhausted by evening" },
          topicArea: "work",
        },
        {
          en: "It was such delicious food that I asked for more.",
          bn: "এটি এমন সুস্বাদু খাবার ছিল যে আমি আরও চেয়েছিলাম।",
          slotValues: { THING: "delicious food", CLAUSE: "I asked for more" },
          topicArea: "food",
        },
        {
          en: "It was such terrible traffic that we missed the flight.",
          bn: "এটি এমন ভয়ংকর ট্রাফিক ছিল যে আমরা ফ্লাইট মিস করেছি।",
          slotValues: { THING: "terrible traffic", CLAUSE: "we missed the flight" },
          topicArea: "travel",
        },
        {
          en: "It was such good news that we celebrated all night.",
          bn: "এটি এমন ভালো খবর ছিল যে আমরা সারারাত উদযাপন করেছি।",
          slotValues: { THING: "good news", CLAUSE: "we celebrated all night" },
          topicArea: "relationships",
        },
        {
          en: "It was such poor quality that I returned the product.",
          bn: "এটি এমন খারাপ মানের ছিল যে আমি পণ্যটি ফেরত দিয়েছি।",
          slotValues: { THING: "poor quality", CLAUSE: "I returned the product" },
          topicArea: "shopping",
        },
        {
          en: "It was such intense pain that I couldn't walk.",
          bn: "এটি এমন তীব্র ব্যথা ছিল যে আমি হাঁটতে পারিনি।",
          slotValues: { THING: "intense pain", CLAUSE: "I couldn't walk" },
          topicArea: "health",
        },
        {
          en: "It was such confusing information that nobody knew what to do.",
          bn: "এটি এমন বিভ্রান্তিকর তথ্য ছিল যে কেউ জানত না কী করতে হবে।",
          slotValues: { THING: "confusing information", CLAUSE: "nobody knew what to do" },
          topicArea: "education",
        },
        {
          en: "It was such important work that we stayed late.",
          bn: "এটি এমন গুরুত্বপূর্ণ কাজ ছিল যে আমরা দেরি করে থাকলাম।",
          slotValues: { THING: "important work", CLAUSE: "we stayed late" },
          topicArea: "work",
        },
        {
          en: "It was such cheap fabric that it tore quickly.",
          bn: "এটি এমন সস্তা কাপড় ছিল যে তা দ্রুত ছিঁড়ে গেল।",
          slotValues: { THING: "cheap fabric", CLAUSE: "it tore quickly" },
          topicArea: "shopping",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "Use 'such + uncountable/plural noun + that' without the article 'a'. This form works with uncountable and plural nouns.",
      usageNote_bn:
        "'a' প্রবন্ধ ছাড়া 'such + অগণনীয়/বহুবচন বিশেষ্য + that' ব্যবহার করুন। এই রূপটি অগণনীয় এবং বহুবচন বিশেষ্যের সাথে কাজ করে।",
      combinableWith: ["I3.2"],
      banglaStructureMap:
        "এটি (Subject) + এমন (Intensifier) + [THING] (Noun phrase) + ছিল যে (Connector) + [CLAUSE] (Result)",
    },
  ],
};
