import { PatternCategory } from "@/types/pattern";

export const categoryI4: PatternCategory = {
  id: "I4",
  slug: "too-to-enough-to",
  name: "Too...To / Enough To",
  name_bn: "খুব বেশি...করতে / যথেষ্ট...করতে",
  description:
    "Learn how to express limits and sufficiency using 'too...to' and 'enough to' patterns in English.",
  description_bn:
    "ইংরেজিতে 'too...to' এবং 'enough to' প্যাটার্ন ব্যবহার করে সীমা এবং পর্যাপ্ততা প্রকাশ করতে শিখুন।",
  icon: "📏",
  group: "I",
  groupName: "Comparing & Contrasting",
  groupName_bn: "তুলনা এবং বৈপরীত্য",
  difficulty: "intermediate",
  patterns: [
    {
      id: "I4.1",
      formula: "[THING] is too [ADJECTIVE] to [ACTION]",
      formula_bn: "[জিনিস] [কাজ] করার জন্য খুব বেশি [বিশেষণ]",
      patternName: "Too + Adjective + To",
      patternName_bn: "Too + বিশেষণ + To",
      slots: [
        {
          name: "THING",
          description: "The subject being described",
          description_bn: "যে বিষয়টি বর্ণনা করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["This coffee", "The water", "The bag"],
        },
        {
          name: "ADJECTIVE",
          description: "The adjective describing the excess",
          description_bn: "অতিরিক্ত বর্ণনাকারী বিশেষণ",
          acceptedTypes: ["adjective"],
          examples: ["hot", "cold", "heavy"],
        },
        {
          name: "ACTION",
          description: "The action that cannot be done",
          description_bn: "যে কাজটি করা সম্ভব নয়",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["drink", "swim in", "carry"],
        },
      ],
      examples: [
        {
          en: "This coffee is too hot to drink.",
          bn: "এই কফি পান করার জন্য খুব বেশি গরম।",
          slotValues: { THING: "This coffee", ADJECTIVE: "hot", ACTION: "drink" },
          topicArea: "food",
        },
        {
          en: "The water is too cold to swim in.",
          bn: "পানি সাঁতার কাটার জন্য খুব বেশি ঠান্ডা।",
          slotValues: { THING: "The water", ADJECTIVE: "cold", ACTION: "swim in" },
          topicArea: "travel",
        },
        {
          en: "The bag is too heavy to carry.",
          bn: "ব্যাগটি বহন করার জন্য খুব বেশি ভারী।",
          slotValues: { THING: "The bag", ADJECTIVE: "heavy", ACTION: "carry" },
          topicArea: "shopping",
        },
        {
          en: "This book is too difficult to understand.",
          bn: "এই বইটি বোঝার জন্য খুব বেশি কঠিন।",
          slotValues: { THING: "This book", ADJECTIVE: "difficult", ACTION: "understand" },
          topicArea: "education",
        },
        {
          en: "The music is too loud to concentrate.",
          bn: "মনোযোগ দেওয়ার জন্য গান খুব বেশি জোরে।",
          slotValues: { THING: "The music", ADJECTIVE: "loud", ACTION: "concentrate" },
          topicArea: "work",
        },
        {
          en: "This shirt is too small to wear.",
          bn: "এই শার্টটি পরার জন্য খুব বেশি ছোট।",
          slotValues: { THING: "This shirt", ADJECTIVE: "small", ACTION: "wear" },
          topicArea: "shopping",
        },
        {
          en: "The soup is too salty to eat.",
          bn: "স্যুপটি খাওয়ার জন্য খুব বেশি নোনতা।",
          slotValues: { THING: "The soup", ADJECTIVE: "salty", ACTION: "eat" },
          topicArea: "food",
        },
        {
          en: "The road is too narrow to drive on.",
          bn: "রাস্তাটি গাড়ি চালানোর জন্য খুব বেশি সরু।",
          slotValues: { THING: "The road", ADJECTIVE: "narrow", ACTION: "drive on" },
          topicArea: "travel",
        },
        {
          en: "It is too dark to read.",
          bn: "পড়ার জন্য খুব বেশি অন্ধকার।",
          slotValues: { THING: "It", ADJECTIVE: "dark", ACTION: "read" },
          topicArea: "daily_life",
        },
        {
          en: "The problem is too complex to solve alone.",
          bn: "সমস্যাটি একা সমাধান করার জন্য খুব বেশি জটিল।",
          slotValues: { THING: "The problem", ADJECTIVE: "complex", ACTION: "solve alone" },
          topicArea: "work",
        },
        {
          en: "She is too sick to go to school.",
          bn: "সে স্কুলে যাওয়ার জন্য খুব বেশি অসুস্থ।",
          slotValues: { THING: "She", ADJECTIVE: "sick", ACTION: "go to school" },
          topicArea: "health",
        },
        {
          en: "The movie is too scary to watch alone.",
          bn: "মুভিটি একা দেখার জন্য খুব বেশি ভয়ংকর।",
          slotValues: { THING: "The movie", ADJECTIVE: "scary", ACTION: "watch alone" },
          topicArea: "daily_life",
        },
        {
          en: "This question is too easy to ask in the exam.",
          bn: "এই প্রশ্নটি পরীক্ষায় জিজ্ঞাসা করার জন্য খুব বেশি সহজ।",
          slotValues: { THING: "This question", ADJECTIVE: "easy", ACTION: "ask in the exam" },
          topicArea: "education",
        },
        {
          en: "He is too tired to exercise.",
          bn: "সে ব্যায়াম করার জন্য খুব বেশি ক্লান্ত।",
          slotValues: { THING: "He", ADJECTIVE: "tired", ACTION: "exercise" },
          topicArea: "health",
        },
        {
          en: "The child is too young to stay up late.",
          bn: "শিশুটি দেরি করে জাগার জন্য খুব বেশি ছোট।",
          slotValues: { THING: "The child", ADJECTIVE: "young", ACTION: "stay up late" },
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Too...to' means something is excessive to the point where an action becomes impossible.",
      usageNote_bn:
        "'Too...to' মানে কিছু এতটাই বেশি যে কোনো কাজ অসম্ভব হয়ে যায়।",
      combinableWith: ["I4.2"],
      banglaStructureMap:
        "[THING] (Subject) + [ACTION] (Action) + করার জন্য (Purpose marker) + খুব বেশি (Intensifier) + [ADJ] (Adjective)",
    },
    {
      id: "I4.2",
      formula: "[THING] is [ADJECTIVE] enough to [ACTION]",
      formula_bn: "[জিনিস] [কাজ] করার জন্য যথেষ্ট [বিশেষণ]",
      patternName: "Adjective + Enough + To",
      patternName_bn: "বিশেষণ + Enough + To",
      slots: [
        {
          name: "THING",
          description: "The subject being described",
          description_bn: "যে বিষয়টি বর্ণনা করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["This room", "The soup", "She"],
        },
        {
          name: "ADJECTIVE",
          description: "The adjective describing sufficiency",
          description_bn: "পর্যাপ্ততা বর্ণনাকারী বিশেষণ",
          acceptedTypes: ["adjective"],
          examples: ["big", "cool", "smart"],
        },
        {
          name: "ACTION",
          description: "The action that is possible",
          description_bn: "যে কাজটি সম্ভব",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["hold fifty people", "drink", "solve the problem"],
        },
      ],
      examples: [
        {
          en: "This room is big enough to hold fifty people.",
          bn: "এই ঘরটি পঞ্চাশ জন ধারণ করার জন্য যথেষ্ট বড়।",
          slotValues: { THING: "This room", ADJECTIVE: "big", ACTION: "hold fifty people" },
          topicArea: "daily_life",
        },
        {
          en: "The soup is cool enough to drink.",
          bn: "স্যুপটি পান করার জন্য যথেষ্ট ঠান্ডা।",
          slotValues: { THING: "The soup", ADJECTIVE: "cool", ACTION: "drink" },
          topicArea: "food",
        },
        {
          en: "She is smart enough to solve the problem.",
          bn: "সে সমস্যাটি সমাধান করার জন্য যথেষ্ট বুদ্ধিমান।",
          slotValues: { THING: "She", ADJECTIVE: "smart", ACTION: "solve the problem" },
          topicArea: "education",
        },
        {
          en: "The car is fast enough to reach there on time.",
          bn: "গাড়িটি সময়মতো সেখানে পৌঁছানোর জন্য যথেষ্ট দ্রুত।",
          slotValues: { THING: "The car", ADJECTIVE: "fast", ACTION: "reach there on time" },
          topicArea: "travel",
        },
        {
          en: "He is strong enough to lift that box.",
          bn: "সে ওই বাক্সটি তোলার জন্য যথেষ্ট শক্তিশালী।",
          slotValues: { THING: "He", ADJECTIVE: "strong", ACTION: "lift that box" },
          topicArea: "daily_life",
        },
        {
          en: "The weather is warm enough to go swimming.",
          bn: "আবহাওয়া সাঁতার কাটতে যাওয়ার জন্য যথেষ্ট উষ্ণ।",
          slotValues: { THING: "The weather", ADJECTIVE: "warm", ACTION: "go swimming" },
          topicArea: "health",
        },
        {
          en: "This phone is cheap enough to buy.",
          bn: "এই ফোনটি কেনার জন্য যথেষ্ট সস্তা।",
          slotValues: { THING: "This phone", ADJECTIVE: "cheap", ACTION: "buy" },
          topicArea: "shopping",
        },
        {
          en: "The report is clear enough to present.",
          bn: "রিপোর্টটি উপস্থাপন করার জন্য যথেষ্ট স্পষ্ট।",
          slotValues: { THING: "The report", ADJECTIVE: "clear", ACTION: "present" },
          topicArea: "work",
        },
        {
          en: "The food is fresh enough to eat.",
          bn: "খাবারটি খাওয়ার জন্য যথেষ্ট তাজা।",
          slotValues: { THING: "The food", ADJECTIVE: "fresh", ACTION: "eat" },
          topicArea: "food",
        },
        {
          en: "She is old enough to drive.",
          bn: "সে গাড়ি চালানোর জন্য যথেষ্ট বয়স্ক।",
          slotValues: { THING: "She", ADJECTIVE: "old", ACTION: "drive" },
          topicArea: "daily_life",
        },
        {
          en: "The light is bright enough to read.",
          bn: "আলো পড়ার জন্য যথেষ্ট উজ্জ্বল।",
          slotValues: { THING: "The light", ADJECTIVE: "bright", ACTION: "read" },
          topicArea: "education",
        },
        {
          en: "This bag is durable enough to last for years.",
          bn: "এই ব্যাগটি বছরের পর বছর টেকার জন্য যথেষ্ট মজবুত।",
          slotValues: { THING: "This bag", ADJECTIVE: "durable", ACTION: "last for years" },
          topicArea: "shopping",
        },
        {
          en: "He is experienced enough to lead the team.",
          bn: "সে দল নেতৃত্ব দেওয়ার জন্য যথেষ্ট অভিজ্ঞ।",
          slotValues: { THING: "He", ADJECTIVE: "experienced", ACTION: "lead the team" },
          topicArea: "work",
        },
        {
          en: "The patient is stable enough to go home.",
          bn: "রোগী বাড়ি যাওয়ার জন্য যথেষ্ট স্থিতিশীল।",
          slotValues: { THING: "The patient", ADJECTIVE: "stable", ACTION: "go home" },
          topicArea: "health",
        },
        {
          en: "The road is wide enough to walk side by side.",
          bn: "রাস্তাটি পাশাপাশি হাঁটার জন্য যথেষ্ট চওড়া।",
          slotValues: { THING: "The road", ADJECTIVE: "wide", ACTION: "walk side by side" },
          topicArea: "travel",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Adjective + enough + to' means something has a sufficient degree of quality for an action to be possible.",
      usageNote_bn:
        "'Adjective + enough + to' মানে কোনো কিছু একটি কাজ সম্ভব হওয়ার জন্য যথেষ্ট মাত্রার গুণ রাখে।",
      combinableWith: ["I4.1"],
      banglaStructureMap:
        "[THING] (Subject) + [ACTION] (Action) + করার জন্য (Purpose marker) + যথেষ্ট (Sufficiency marker) + [ADJ] (Adjective)",
    },
    {
      id: "I4.3",
      formula: "I'm not [ADJECTIVE] enough to [ACTION]",
      formula_bn: "আমি [কাজ] করার জন্য যথেষ্ট [বিশেষণ] নই",
      patternName: "Not + Adjective + Enough",
      patternName_bn: "Not + বিশেষণ + Enough",
      slots: [
        {
          name: "ADJECTIVE",
          description: "The adjective describing what is lacking",
          description_bn: "যা অভাবে আছে তা বর্ণনাকারী বিশেষণ",
          acceptedTypes: ["adjective"],
          examples: ["tall", "rich", "brave"],
        },
        {
          name: "ACTION",
          description: "The action that cannot be done",
          description_bn: "যে কাজটি করা সম্ভব নয়",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["reach the shelf", "buy a house", "try skydiving"],
        },
      ],
      examples: [
        {
          en: "I'm not tall enough to reach the shelf.",
          bn: "আমি তাকে পৌঁছানোর জন্য যথেষ্ট লম্বা নই।",
          slotValues: { ADJECTIVE: "tall", ACTION: "reach the shelf" },
          topicArea: "daily_life",
        },
        {
          en: "I'm not rich enough to buy a house.",
          bn: "আমি বাড়ি কেনার জন্য যথেষ্ট ধনী নই।",
          slotValues: { ADJECTIVE: "rich", ACTION: "buy a house" },
          topicArea: "shopping",
        },
        {
          en: "I'm not brave enough to try skydiving.",
          bn: "আমি স্কাইডাইভিং চেষ্টা করার জন্য যথেষ্ট সাহসী নই।",
          slotValues: { ADJECTIVE: "brave", ACTION: "try skydiving" },
          topicArea: "travel",
        },
        {
          en: "I'm not fast enough to win the race.",
          bn: "আমি রেস জেতার জন্য যথেষ্ট দ্রুত নই।",
          slotValues: { ADJECTIVE: "fast", ACTION: "win the race" },
          topicArea: "health",
        },
        {
          en: "I'm not skilled enough to do this job.",
          bn: "আমি এই কাজ করার জন্য যথেষ্ট দক্ষ নই।",
          slotValues: { ADJECTIVE: "skilled", ACTION: "do this job" },
          topicArea: "work",
        },
        {
          en: "I'm not patient enough to teach children.",
          bn: "আমি শিশুদের শেখানোর জন্য যথেষ্ট ধৈর্যশীল নই।",
          slotValues: { ADJECTIVE: "patient", ACTION: "teach children" },
          topicArea: "education",
        },
        {
          en: "I'm not confident enough to speak in public.",
          bn: "আমি জনসমক্ষে কথা বলার জন্য যথেষ্ট আত্মবিশ্বাসী নই।",
          slotValues: { ADJECTIVE: "confident", ACTION: "speak in public" },
          topicArea: "daily_life",
        },
        {
          en: "I'm not creative enough to paint.",
          bn: "আমি আঁকার জন্য যথেষ্ট সৃজনশীল নই।",
          slotValues: { ADJECTIVE: "creative", ACTION: "paint" },
          topicArea: "education",
        },
        {
          en: "I'm not strong enough to lift that.",
          bn: "আমি ওটা তোলার জন্য যথেষ্ট শক্তিশালী নই।",
          slotValues: { ADJECTIVE: "strong", ACTION: "lift that" },
          topicArea: "health",
        },
        {
          en: "I'm not experienced enough to lead this project.",
          bn: "আমি এই প্রকল্প নেতৃত্ব দেওয়ার জন্য যথেষ্ট অভিজ্ঞ নই।",
          slotValues: { ADJECTIVE: "experienced", ACTION: "lead this project" },
          topicArea: "work",
        },
        {
          en: "I'm not good enough to join the team.",
          bn: "আমি দলে যোগ দেওয়ার জন্য যথেষ্ট ভালো নই।",
          slotValues: { ADJECTIVE: "good", ACTION: "join the team" },
          topicArea: "daily_life",
        },
        {
          en: "I'm not fluent enough to have a conversation in English.",
          bn: "আমি ইংরেজিতে কথোপকথন করার জন্য যথেষ্ট সাবলীল নই।",
          slotValues: { ADJECTIVE: "fluent", ACTION: "have a conversation in English" },
          topicArea: "education",
        },
        {
          en: "I'm not fit enough to run a marathon.",
          bn: "আমি ম্যারাথন দৌড়ানোর জন্য যথেষ্ট ফিট নই।",
          slotValues: { ADJECTIVE: "fit", ACTION: "run a marathon" },
          topicArea: "health",
        },
        {
          en: "I'm not organized enough to manage everything.",
          bn: "আমি সব কিছু পরিচালনা করার জন্য যথেষ্ট সংগঠিত নই।",
          slotValues: { ADJECTIVE: "organized", ACTION: "manage everything" },
          topicArea: "work",
        },
        {
          en: "I'm not close enough to ask him that.",
          bn: "আমি তাকে সেটা জিজ্ঞেস করার জন্য যথেষ্ট ঘনিষ্ঠ নই।",
          slotValues: { ADJECTIVE: "close", ACTION: "ask him that" },
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Not + adjective + enough' expresses that you lack the required quality for something.",
      usageNote_bn:
        "'Not + adjective + enough' প্রকাশ করে যে কোনো কিছুর জন্য আপনার প্রয়োজনীয় গুণের অভাব রয়েছে।",
      combinableWith: ["I4.2"],
      banglaStructureMap:
        "আমি (Subject) + [ACTION] (Action) + করার জন্য (Purpose marker) + যথেষ্ট (Sufficiency marker) + [ADJ] (Adjective) + নই (Negation)",
    },
    {
      id: "I4.4",
      formula: "There isn't enough [THING] to [ACTION]",
      formula_bn: "[কাজ] করার জন্য যথেষ্ট [জিনিস] নেই",
      patternName: "Not Enough + Noun",
      patternName_bn: "যথেষ্ট নয় + বিশেষ্য",
      slots: [
        {
          name: "THING",
          description: "The noun that is insufficient",
          description_bn: "যে বিশেষ্যটি অপর্যাপ্ত",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["time", "food", "space"],
        },
        {
          name: "ACTION",
          description: "The action that cannot be completed",
          description_bn: "যে কাজটি সম্পন্ন করা যায় না",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["finish the project", "feed everyone", "park the car"],
        },
      ],
      examples: [
        {
          en: "There isn't enough time to finish the project.",
          bn: "প্রকল্পটি শেষ করার জন্য যথেষ্ট সময় নেই।",
          slotValues: { THING: "time", ACTION: "finish the project" },
          topicArea: "work",
        },
        {
          en: "There isn't enough food to feed everyone.",
          bn: "সবাইকে খাওয়ানোর জন্য যথেষ্ট খাবার নেই।",
          slotValues: { THING: "food", ACTION: "feed everyone" },
          topicArea: "food",
        },
        {
          en: "There isn't enough space to park the car.",
          bn: "গাড়ি পার্ক করার জন্য যথেষ্ট জায়গা নেই।",
          slotValues: { THING: "space", ACTION: "park the car" },
          topicArea: "travel",
        },
        {
          en: "There isn't enough light to take a photo.",
          bn: "ছবি তোলার জন্য যথেষ্ট আলো নেই।",
          slotValues: { THING: "light", ACTION: "take a photo" },
          topicArea: "daily_life",
        },
        {
          en: "There isn't enough money to buy a new laptop.",
          bn: "নতুন ল্যাপটপ কেনার জন্য যথেষ্ট টাকা নেই।",
          slotValues: { THING: "money", ACTION: "buy a new laptop" },
          topicArea: "shopping",
        },
        {
          en: "There isn't enough water to drink.",
          bn: "পান করার জন্য যথেষ্ট পানি নেই।",
          slotValues: { THING: "water", ACTION: "drink" },
          topicArea: "health",
        },
        {
          en: "There isn't enough evidence to prove anything.",
          bn: "কিছু প্রমাণ করার জন্য যথেষ্ট প্রমাণ নেই।",
          slotValues: { THING: "evidence", ACTION: "prove anything" },
          topicArea: "education",
        },
        {
          en: "There isn't enough staff to handle the work.",
          bn: "কাজ সামলানোর জন্য যথেষ্ট কর্মী নেই।",
          slotValues: { THING: "staff", ACTION: "handle the work" },
          topicArea: "work",
        },
        {
          en: "There isn't enough sugar to make the cake.",
          bn: "কেক বানানোর জন্য যথেষ্ট চিনি নেই।",
          slotValues: { THING: "sugar", ACTION: "make the cake" },
          topicArea: "food",
        },
        {
          en: "There isn't enough fuel to reach the next town.",
          bn: "পরবর্তী শহরে পৌঁছানোর জন্য যথেষ্ট জ্বালানি নেই।",
          slotValues: { THING: "fuel", ACTION: "reach the next town" },
          topicArea: "travel",
        },
        {
          en: "There isn't enough room to sit.",
          bn: "বসার জন্য যথেষ্ট জায়গা নেই।",
          slotValues: { THING: "room", ACTION: "sit" },
          topicArea: "daily_life",
        },
        {
          en: "There isn't enough paint to finish the wall.",
          bn: "দেয়াল শেষ করার জন্য যথেষ্ট রং নেই।",
          slotValues: { THING: "paint", ACTION: "finish the wall" },
          topicArea: "daily_life",
        },
        {
          en: "There isn't enough medicine for all the patients.",
          bn: "সব রোগীদের জন্য যথেষ্ট ওষুধ নেই।",
          slotValues: { THING: "medicine", ACTION: "for all the patients" },
          topicArea: "health",
        },
        {
          en: "There isn't enough information to make a decision.",
          bn: "সিদ্ধান্ত নেওয়ার জন্য যথেষ্ট তথ্য নেই।",
          slotValues: { THING: "information", ACTION: "make a decision" },
          topicArea: "work",
        },
        {
          en: "There isn't enough fabric to make a dress.",
          bn: "একটি পোশাক তৈরি করার জন্য যথেষ্ট কাপড় নেই।",
          slotValues: { THING: "fabric", ACTION: "make a dress" },
          topicArea: "shopping",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "Use this pattern with uncountable or plural nouns to express an insufficient amount for an action.",
      usageNote_bn:
        "কোনো কাজের জন্য অপর্যাপ্ত পরিমাণ প্রকাশ করতে অগণনীয় বা বহুবচন বিশেষ্যের সাথে এই প্যাটার্ন ব্যবহার করুন।",
      combinableWith: ["I4.2"],
      banglaStructureMap:
        "[ACTION] (Action) + করার জন্য (Purpose marker) + যথেষ্ট (Sufficiency marker) + [THING] (Noun) + নেই (Negation)",
    },
    {
      id: "I4.5",
      formula: "[PERSON] is too [ADJECTIVE] for [THING]",
      formula_bn: "[ব্যক্তি] [জিনিসের] জন্য খুব বেশি [বিশেষণ]",
      patternName: "Too + Adjective + For",
      patternName_bn: "Too + বিশেষণ + For",
      slots: [
        {
          name: "PERSON",
          description: "The person being described",
          description_bn: "যে ব্যক্তিকে বর্ণনা করা হচ্ছে",
          acceptedTypes: ["person", "noun"],
          examples: ["He", "She", "I"],
        },
        {
          name: "ADJECTIVE",
          description: "The adjective describing excess",
          description_bn: "অতিরিক্ত বর্ণনাকারী বিশেষণ",
          acceptedTypes: ["adjective"],
          examples: ["young", "old", "qualified"],
        },
        {
          name: "THING",
          description: "The thing that doesn't match",
          description_bn: "যে জিনিসটি মানানসই নয়",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["this job", "this ride", "this position"],
        },
      ],
      examples: [
        {
          en: "He is too young for this job.",
          bn: "সে এই চাকরির জন্য খুব বেশি কম বয়সী।",
          slotValues: { PERSON: "He", ADJECTIVE: "young", THING: "this job" },
          topicArea: "work",
        },
        {
          en: "She is too old for this ride.",
          bn: "সে এই রাইডের জন্য খুব বেশি বয়স্ক।",
          slotValues: { PERSON: "She", ADJECTIVE: "old", THING: "this ride" },
          topicArea: "travel",
        },
        {
          en: "I am too tired for a workout.",
          bn: "আমি ব্যায়ামের জন্য খুব বেশি ক্লান্ত।",
          slotValues: { PERSON: "I", ADJECTIVE: "tired", THING: "a workout" },
          topicArea: "health",
        },
        {
          en: "He is too qualified for this position.",
          bn: "সে এই পদের জন্য খুব বেশি যোগ্য।",
          slotValues: { PERSON: "He", ADJECTIVE: "qualified", THING: "this position" },
          topicArea: "work",
        },
        {
          en: "She is too shy for public speaking.",
          bn: "সে জনসমক্ষে কথা বলার জন্য খুব বেশি লাজুক।",
          slotValues: { PERSON: "She", ADJECTIVE: "shy", THING: "public speaking" },
          topicArea: "education",
        },
        {
          en: "This food is too spicy for me.",
          bn: "এই খাবার আমার জন্য খুব বেশি ঝাল।",
          slotValues: { PERSON: "This food", ADJECTIVE: "spicy", THING: "me" },
          topicArea: "food",
        },
        {
          en: "He is too impatient for teaching.",
          bn: "সে শিক্ষকতার জন্য খুব বেশি অধৈর্য।",
          slotValues: { PERSON: "He", ADJECTIVE: "impatient", THING: "teaching" },
          topicArea: "education",
        },
        {
          en: "She is too sensitive for this kind of criticism.",
          bn: "সে এই ধরনের সমালোচনার জন্য খুব বেশি সংবেদনশীল।",
          slotValues: { PERSON: "She", ADJECTIVE: "sensitive", THING: "this kind of criticism" },
          topicArea: "relationships",
        },
        {
          en: "This movie is too scary for children.",
          bn: "এই মুভি শিশুদের জন্য খুব বেশি ভয়ংকর।",
          slotValues: { PERSON: "This movie", ADJECTIVE: "scary", THING: "children" },
          topicArea: "daily_life",
        },
        {
          en: "The price is too high for my budget.",
          bn: "আমার বাজেটের জন্য দাম খুব বেশি।",
          slotValues: { PERSON: "The price", ADJECTIVE: "high", THING: "my budget" },
          topicArea: "shopping",
        },
        {
          en: "He is too stubborn for compromise.",
          bn: "সে আপসের জন্য খুব বেশি জেদি।",
          slotValues: { PERSON: "He", ADJECTIVE: "stubborn", THING: "compromise" },
          topicArea: "relationships",
        },
        {
          en: "The course is too advanced for beginners.",
          bn: "কোর্সটি শুরুকারীদের জন্য খুব বেশি উন্নত।",
          slotValues: { PERSON: "The course", ADJECTIVE: "advanced", THING: "beginners" },
          topicArea: "education",
        },
        {
          en: "I am too busy for a vacation right now.",
          bn: "আমি এই মুহূর্তে ছুটির জন্য খুব বেশি ব্যস্ত।",
          slotValues: { PERSON: "I", ADJECTIVE: "busy", THING: "a vacation right now" },
          topicArea: "work",
        },
        {
          en: "This bag is too small for all my things.",
          bn: "এই ব্যাগটি আমার সব জিনিসের জন্য খুব বেশি ছোট।",
          slotValues: { PERSON: "This bag", ADJECTIVE: "small", THING: "all my things" },
          topicArea: "travel",
        },
        {
          en: "The weather is too cold for a picnic.",
          bn: "আবহাওয়া পিকনিকের জন্য খুব বেশি ঠান্ডা।",
          slotValues: { PERSON: "The weather", ADJECTIVE: "cold", THING: "a picnic" },
          topicArea: "daily_life",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Too + adjective + for' expresses that something is excessive for a particular person, thing, or situation.",
      usageNote_bn:
        "'Too + adjective + for' প্রকাশ করে যে কিছু একটি নির্দিষ্ট ব্যক্তি, জিনিস বা পরিস্থিতির জন্য অতিরিক্ত।",
      combinableWith: ["I4.1"],
      banglaStructureMap:
        "[PERSON] (Subject) + [THING]-এর জন্য (For marker) + খুব বেশি (Intensifier) + [ADJ] (Adjective)",
    },
  ],
};
