import { PatternCategory } from "@/types/pattern";

export const categoryI6: PatternCategory = {
  id: "I6",
  slug: "expressing-difference",
  name: "Expressing Difference",
  name_bn: "পার্থক্য প্রকাশ",
  description:
    "Learn how to express differences between people, things, and ideas using common English patterns.",
  description_bn:
    "সাধারণ ইংরেজি প্যাটার্ন ব্যবহার করে মানুষ, জিনিস এবং ধারণার মধ্যে পার্থক্য প্রকাশ করতে শিখুন।",
  icon: "↔️",
  group: "I",
  groupName: "Comparing & Contrasting",
  groupName_bn: "তুলনা ও বৈপরীত্য",
  difficulty: "intermediate",
  patterns: [
    {
      id: "I6.1",
      formula: "[A] is different from [B]",
      formula_bn: "[ক] [খ] থেকে আলাদা",
      patternName: "Basic Difference",
      patternName_bn: "মৌলিক পার্থক্য",
      slots: [
        {
          name: "A",
          description: "The first thing being compared",
          description_bn: "প্রথম যে জিনিসটি তুলনা করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["Dhaka", "Bengali culture", "This phone"],
        },
        {
          name: "B",
          description: "The second thing being compared",
          description_bn: "দ্বিতীয় যে জিনিসটি তুলনা করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["Chittagong", "Western culture", "that phone"],
        },
      ],
      examples: [
        {
          en: "Dhaka is different from Chittagong.",
          bn: "ঢাকা চট্টগ্রাম থেকে আলাদা।",
          slotValues: { A: "Dhaka", B: "Chittagong" },
          topicArea: "travel",
        },
        {
          en: "Bengali culture is different from Western culture.",
          bn: "বাঙালি সংস্কৃতি পশ্চিমা সংস্কৃতি থেকে আলাদা।",
          slotValues: { A: "Bengali culture", B: "Western culture" },
          topicArea: "daily_life",
        },
        {
          en: "This phone is different from that phone.",
          bn: "এই ফোনটি ওই ফোন থেকে আলাদা।",
          slotValues: { A: "This phone", B: "that phone" },
          topicArea: "shopping",
        },
        {
          en: "My cooking style is different from my mother's.",
          bn: "আমার রান্নার ধরন আমার মায়ের থেকে আলাদা।",
          slotValues: { A: "My cooking style", B: "my mother's" },
          topicArea: "food",
        },
        {
          en: "Working from home is different from working in an office.",
          bn: "বাড়ি থেকে কাজ করা অফিসে কাজ করা থেকে আলাদা।",
          slotValues: { A: "Working from home", B: "working in an office" },
          topicArea: "work",
        },
        {
          en: "British English is different from American English.",
          bn: "ব্রিটিশ ইংরেজি আমেরিকান ইংরেজি থেকে আলাদা।",
          slotValues: { A: "British English", B: "American English" },
          topicArea: "education",
        },
        {
          en: "His personality is different from his brother's.",
          bn: "তার ব্যক্তিত্ব তার ভাইয়ের থেকে আলাদা।",
          slotValues: { A: "His personality", B: "his brother's" },
          topicArea: "relationships",
        },
        {
          en: "Homeopathy is different from allopathy.",
          bn: "হোমিওপ্যাথি অ্যালোপ্যাথি থেকে আলাদা।",
          slotValues: { A: "Homeopathy", B: "allopathy" },
          topicArea: "health",
        },
        {
          en: "Online shopping is different from in-store shopping.",
          bn: "অনলাইন কেনাকাটা দোকানে কেনাকাটা থেকে আলাদা।",
          slotValues: { A: "Online shopping", B: "in-store shopping" },
          topicArea: "shopping",
        },
        {
          en: "The food here is different from what I expected.",
          bn: "এখানকার খাবার আমি যা আশা করেছিলাম তার থেকে আলাদা।",
          slotValues: { A: "The food here", B: "what I expected" },
          topicArea: "food",
        },
        {
          en: "This semester is different from the last one.",
          bn: "এই সেমিস্টার আগেরটি থেকে আলাদা।",
          slotValues: { A: "This semester", B: "the last one" },
          topicArea: "education",
        },
        {
          en: "Village life is different from city life.",
          bn: "গ্রামের জীবন শহরের জীবন থেকে আলাদা।",
          slotValues: { A: "Village life", B: "city life" },
          topicArea: "daily_life",
        },
        {
          en: "My relationship with her is different from yours.",
          bn: "তার সাথে আমার সম্পর্ক তোমার থেকে আলাদা।",
          slotValues: { A: "My relationship with her", B: "yours" },
          topicArea: "relationships",
        },
        {
          en: "Traveling by train is different from traveling by bus.",
          bn: "ট্রেনে ভ্রমণ বাসে ভ্রমণ থেকে আলাদা।",
          slotValues: { A: "Traveling by train", B: "traveling by bus" },
          topicArea: "travel",
        },
        {
          en: "The new manager is different from the previous one.",
          bn: "নতুন ম্যানেজার আগেরজনের থেকে আলাদা।",
          slotValues: { A: "The new manager", B: "the previous one" },
          topicArea: "work",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Different from' is the standard way to express difference. In American English, 'different than' is also used.",
      usageNote_bn:
        "'Different from' পার্থক্য প্রকাশ করার আদর্শ উপায়। আমেরিকান ইংরেজিতে 'different than'-ও ব্যবহৃত হয়।",
      combinableWith: ["I6.2"],
      banglaStructureMap: "[A] (Subject) + [B] থেকে (Comparison marker) + আলাদা (Predicate)",
    },
    {
      id: "I6.2",
      formula: "Unlike [A], [B]...",
      formula_bn: "[ক]-এর বিপরীতে, [খ]...",
      patternName: "Unlike Contrast",
      patternName_bn: "বিপরীতে তুলনা",
      slots: [
        {
          name: "A",
          description: "The thing being contrasted with",
          description_bn: "যার সাথে তুলনা করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase", "person"],
          examples: ["my brother", "Dhaka", "last year"],
        },
        {
          name: "B",
          description: "The contrasting statement",
          description_bn: "বিপরীত বিবৃতি",
          acceptedTypes: ["clause"],
          examples: ["I prefer tea", "Sylhet is quiet", "this year is better"],
        },
      ],
      examples: [
        {
          en: "Unlike my brother, I prefer tea over coffee.",
          bn: "আমার ভাইয়ের বিপরীতে, আমি কফির চেয়ে চা পছন্দ করি।",
          slotValues: { A: "my brother", B: "I prefer tea over coffee" },
          topicArea: "food",
        },
        {
          en: "Unlike Dhaka, Sylhet is very peaceful.",
          bn: "ঢাকার বিপরীতে, সিলেট খুব শান্তিপূর্ণ।",
          slotValues: { A: "Dhaka", B: "Sylhet is very peaceful" },
          topicArea: "travel",
        },
        {
          en: "Unlike last year, this year we have more students.",
          bn: "গত বছরের বিপরীতে, এই বছর আমাদের আরো বেশি ছাত্র আছে।",
          slotValues: { A: "last year", B: "this year we have more students" },
          topicArea: "education",
        },
        {
          en: "Unlike his father, he is very outgoing.",
          bn: "তার বাবার বিপরীতে, সে খুব মিশুক।",
          slotValues: { A: "his father", B: "he is very outgoing" },
          topicArea: "relationships",
        },
        {
          en: "Unlike weekdays, weekends are relaxing.",
          bn: "কর্মদিনের বিপরীতে, সপ্তাহান্ত আরামদায়ক।",
          slotValues: { A: "weekdays", B: "weekends are relaxing" },
          topicArea: "daily_life",
        },
        {
          en: "Unlike the old model, this one has a better camera.",
          bn: "পুরনো মডেলের বিপরীতে, এটিতে আরো ভালো ক্যামেরা আছে।",
          slotValues: { A: "the old model", B: "this one has a better camera" },
          topicArea: "shopping",
        },
        {
          en: "Unlike most people, she enjoys waking up early.",
          bn: "অধিকাংশ মানুষের বিপরীতে, সে সকালে উঠতে পছন্দ করে।",
          slotValues: { A: "most people", B: "she enjoys waking up early" },
          topicArea: "daily_life",
        },
        {
          en: "Unlike traditional medicine, this treatment has no side effects.",
          bn: "প্রচলিত ওষুধের বিপরীতে, এই চিকিৎসার কোনো পার্শ্বপ্রতিক্রিয়া নেই।",
          slotValues: { A: "traditional medicine", B: "this treatment has no side effects" },
          topicArea: "health",
        },
        {
          en: "Unlike my previous job, this one pays well.",
          bn: "আমার আগের চাকরির বিপরীতে, এটিতে ভালো বেতন দেয়।",
          slotValues: { A: "my previous job", B: "this one pays well" },
          topicArea: "work",
        },
        {
          en: "Unlike rice, bread is not common in Bangladesh.",
          bn: "ভাতের বিপরীতে, রুটি বাংলাদেশে এতটা প্রচলিত নয়।",
          slotValues: { A: "rice", B: "bread is not common in Bangladesh" },
          topicArea: "food",
        },
        {
          en: "Unlike her sister, she is very shy.",
          bn: "তার বোনের বিপরীতে, সে খুব লাজুক।",
          slotValues: { A: "her sister", B: "she is very shy" },
          topicArea: "relationships",
        },
        {
          en: "Unlike summer, winter is pleasant for traveling.",
          bn: "গ্রীষ্মের বিপরীতে, শীতকাল ভ্রমণের জন্য আরামদায়ক।",
          slotValues: { A: "summer", B: "winter is pleasant for traveling" },
          topicArea: "travel",
        },
        {
          en: "Unlike online classes, in-person classes are more interactive.",
          bn: "অনলাইন ক্লাসের বিপরীতে, সশরীর ক্লাস আরো বেশি ইন্টারেক্টিভ।",
          slotValues: { A: "online classes", B: "in-person classes are more interactive" },
          topicArea: "education",
        },
        {
          en: "Unlike branded products, local ones are affordable.",
          bn: "ব্র্যান্ডের পণ্যের বিপরীতে, স্থানীয় পণ্য সাশ্রয়ী।",
          slotValues: { A: "branded products", B: "local ones are affordable" },
          topicArea: "shopping",
        },
        {
          en: "Unlike painkillers, yoga treats the root cause.",
          bn: "ব্যথানাশকের বিপরীতে, যোগব্যায়াম মূল কারণের চিকিৎসা করে।",
          slotValues: { A: "painkillers", B: "yoga treats the root cause" },
          topicArea: "health",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "'Unlike' introduces a contrast at the beginning of a sentence. It is used to highlight how something is different from expectations.",
      usageNote_bn:
        "'Unlike' বাক্যের শুরুতে একটি বৈপরীত্য উপস্থাপন করে। এটি কীভাবে কিছু প্রত্যাশা থেকে আলাদা তা তুলে ধরতে ব্যবহৃত হয়।",
      combinableWith: ["I6.1"],
      banglaStructureMap: "[A]-এর বিপরীতে (Contrast marker) + [B] (Contrasting clause)",
    },
    {
      id: "I6.3",
      formula: "[A] and [B] have nothing in common",
      formula_bn: "[ক] এবং [খ]-এর মধ্যে কোনো মিল নেই",
      patternName: "No Similarity",
      patternName_bn: "কোনো মিল নেই",
      slots: [
        {
          name: "A",
          description: "The first thing or person",
          description_bn: "প্রথম জিনিস বা ব্যক্তি",
          acceptedTypes: ["noun", "noun_phrase", "person"],
          examples: ["My sister and I", "Tea", "This book"],
        },
        {
          name: "B",
          description: "The second thing or person",
          description_bn: "দ্বিতীয় জিনিস বা ব্যক্তি",
          acceptedTypes: ["noun", "noun_phrase", "person"],
          examples: ["my brother", "coffee", "that movie"],
        },
      ],
      examples: [
        {
          en: "My sister and my brother have nothing in common.",
          bn: "আমার বোন এবং আমার ভাইয়ের মধ্যে কোনো মিল নেই।",
          slotValues: { A: "My sister", B: "my brother" },
          topicArea: "relationships",
        },
        {
          en: "Tea and coffee have nothing in common except caffeine.",
          bn: "ক্যাফেইন ছাড়া চা এবং কফির মধ্যে কোনো মিল নেই।",
          slotValues: { A: "Tea", B: "coffee" },
          topicArea: "food",
        },
        {
          en: "This book and that movie have nothing in common.",
          bn: "এই বই এবং ওই সিনেমার মধ্যে কোনো মিল নেই।",
          slotValues: { A: "This book", B: "that movie" },
          topicArea: "daily_life",
        },
        {
          en: "My old job and my new job have nothing in common.",
          bn: "আমার পুরনো চাকরি এবং নতুন চাকরির মধ্যে কোনো মিল নেই।",
          slotValues: { A: "My old job", B: "my new job" },
          topicArea: "work",
        },
        {
          en: "Dhaka and Cox's Bazar have nothing in common.",
          bn: "ঢাকা এবং কক্সবাজারের মধ্যে কোনো মিল নেই।",
          slotValues: { A: "Dhaka", B: "Cox's Bazar" },
          topicArea: "travel",
        },
        {
          en: "Math and literature have nothing in common.",
          bn: "গণিত এবং সাহিত্যের মধ্যে কোনো মিল নেই।",
          slotValues: { A: "Math", B: "literature" },
          topicArea: "education",
        },
        {
          en: "These two medicines have nothing in common.",
          bn: "এই দুটি ওষুধের মধ্যে কোনো মিল নেই।",
          slotValues: { A: "These two medicines", B: "each other" },
          topicArea: "health",
        },
        {
          en: "Silk and cotton have nothing in common.",
          bn: "সিল্ক এবং সুতির মধ্যে কোনো মিল নেই।",
          slotValues: { A: "Silk", B: "cotton" },
          topicArea: "shopping",
        },
        {
          en: "He and his twin have nothing in common.",
          bn: "সে এবং তার যমজের মধ্যে কোনো মিল নেই।",
          slotValues: { A: "He", B: "his twin" },
          topicArea: "relationships",
        },
        {
          en: "Biryani and pasta have nothing in common.",
          bn: "বিরিয়ানি এবং পাস্তার মধ্যে কোনো মিল নেই।",
          slotValues: { A: "Biryani", B: "pasta" },
          topicArea: "food",
        },
        {
          en: "The two schools have nothing in common.",
          bn: "দুটি স্কুলের মধ্যে কোনো মিল নেই।",
          slotValues: { A: "The two schools", B: "each other" },
          topicArea: "education",
        },
        {
          en: "My morning routine and his have nothing in common.",
          bn: "আমার সকালের রুটিন এবং তার মধ্যে কোনো মিল নেই।",
          slotValues: { A: "My morning routine", B: "his" },
          topicArea: "daily_life",
        },
        {
          en: "This hotel and the previous one have nothing in common.",
          bn: "এই হোটেল এবং আগেরটির মধ্যে কোনো মিল নেই।",
          slotValues: { A: "This hotel", B: "the previous one" },
          topicArea: "travel",
        },
        {
          en: "Our team and their team have nothing in common.",
          bn: "আমাদের দল এবং তাদের দলের মধ্যে কোনো মিল নেই।",
          slotValues: { A: "Our team", B: "their team" },
          topicArea: "work",
        },
        {
          en: "Yoga and weightlifting have nothing in common.",
          bn: "যোগব্যায়াম এবং ভারোত্তোলনের মধ্যে কোনো মিল নেই।",
          slotValues: { A: "Yoga", B: "weightlifting" },
          topicArea: "health",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Have nothing in common' means two things are completely different with no shared qualities.",
      usageNote_bn:
        "'Have nothing in common' মানে দুটি জিনিসের মধ্যে কোনো ভাগ করা গুণ নেই, সম্পূর্ণ আলাদা।",
      combinableWith: ["I6.1"],
      banglaStructureMap:
        "[A] এবং [B] (Subjects) + -এর মধ্যে (Between marker) + কোনো মিল নেই (No similarity)",
    },
    {
      id: "I6.4",
      formula: "The difference between [A] and [B] is...",
      formula_bn: "[ক] এবং [খ]-এর মধ্যে পার্থক্য হলো...",
      patternName: "Specifying Difference",
      patternName_bn: "পার্থক্য নির্দিষ্ট করা",
      slots: [
        {
          name: "A",
          description: "The first thing being compared",
          description_bn: "প্রথম যে জিনিসটি তুলনা করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["spoken English", "Dhaka", "this product"],
        },
        {
          name: "B",
          description: "The second thing being compared",
          description_bn: "দ্বিতীয় যে জিনিসটি তুলনা করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["written English", "Rajshahi", "that product"],
        },
      ],
      examples: [
        {
          en: "The difference between spoken English and written English is the level of formality.",
          bn: "কথ্য ইংরেজি এবং লিখিত ইংরেজির মধ্যে পার্থক্য হলো আনুষ্ঠানিকতার স্তর।",
          slotValues: { A: "spoken English", B: "written English" },
          topicArea: "education",
        },
        {
          en: "The difference between Dhaka and Rajshahi is the pace of life.",
          bn: "ঢাকা এবং রাজশাহীর মধ্যে পার্থক্য হলো জীবনের গতি।",
          slotValues: { A: "Dhaka", B: "Rajshahi" },
          topicArea: "travel",
        },
        {
          en: "The difference between this product and that product is the quality.",
          bn: "এই পণ্য এবং ওই পণ্যের মধ্যে পার্থক্য হলো গুণমান।",
          slotValues: { A: "this product", B: "that product" },
          topicArea: "shopping",
        },
        {
          en: "The difference between my cooking and hers is the spices.",
          bn: "আমার রান্না এবং তার রান্নার মধ্যে পার্থক্য হলো মসলা।",
          slotValues: { A: "my cooking", B: "hers" },
          topicArea: "food",
        },
        {
          en: "The difference between a good boss and a bad boss is communication.",
          bn: "একজন ভালো বসের এবং খারাপ বসের মধ্যে পার্থক্য হলো যোগাযোগ।",
          slotValues: { A: "a good boss", B: "a bad boss" },
          topicArea: "work",
        },
        {
          en: "The difference between love and friendship is hard to explain.",
          bn: "ভালোবাসা এবং বন্ধুত্বের মধ্যে পার্থক্য ব্যাখ্যা করা কঠিন।",
          slotValues: { A: "love", B: "friendship" },
          topicArea: "relationships",
        },
        {
          en: "The difference between a cold and the flu is the severity.",
          bn: "সর্দি এবং ফ্লু-এর মধ্যে পার্থক্য হলো তীব্রতা।",
          slotValues: { A: "a cold", B: "the flu" },
          topicArea: "health",
        },
        {
          en: "The difference between morning and evening walks is the energy level.",
          bn: "সকালের এবং সন্ধ্যার হাঁটার মধ্যে পার্থক্য হলো শক্তির মাত্রা।",
          slotValues: { A: "morning", B: "evening walks" },
          topicArea: "daily_life",
        },
        {
          en: "The difference between these two schools is the teaching method.",
          bn: "এই দুটি স্কুলের মধ্যে পার্থক্য হলো শিক্ষাদান পদ্ধতি।",
          slotValues: { A: "these two schools", B: "each other" },
          topicArea: "education",
        },
        {
          en: "The difference between silk and polyester is the texture.",
          bn: "সিল্ক এবং পলিয়েস্টারের মধ্যে পার্থক্য হলো গঠন।",
          slotValues: { A: "silk", B: "polyester" },
          topicArea: "shopping",
        },
        {
          en: "The difference between homemade food and restaurant food is the taste.",
          bn: "ঘরের রান্না এবং রেস্তোরাঁর খাবারের মধ্যে পার্থক্য হলো স্বাদ।",
          slotValues: { A: "homemade food", B: "restaurant food" },
          topicArea: "food",
        },
        {
          en: "The difference between us is that I am more patient.",
          bn: "আমাদের মধ্যে পার্থক্য হলো আমি বেশি ধৈর্যশীল।",
          slotValues: { A: "us", B: "each other" },
          topicArea: "relationships",
        },
        {
          en: "The difference between flying and taking a train is the time.",
          bn: "বিমানে যাওয়া এবং ট্রেনে যাওয়ার মধ্যে পার্থক্য হলো সময়।",
          slotValues: { A: "flying", B: "taking a train" },
          topicArea: "travel",
        },
        {
          en: "The difference between a team leader and a manager is responsibility.",
          bn: "টিম লিডার এবং ম্যানেজারের মধ্যে পার্থক্য হলো দায়িত্ব।",
          slotValues: { A: "a team leader", B: "a manager" },
          topicArea: "work",
        },
        {
          en: "The difference between yoga and exercise is the mindfulness.",
          bn: "যোগব্যায়াম এবং ব্যায়ামের মধ্যে পার্থক্য হলো মনোযোগ।",
          slotValues: { A: "yoga", B: "exercise" },
          topicArea: "health",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "'The difference between...is...' is a clear way to state what makes two things distinct.",
      usageNote_bn:
        "'The difference between...is...' দুটি জিনিসকে কী আলাদা করে তা স্পষ্টভাবে বলার একটি উপায়।",
      combinableWith: ["I6.1"],
      banglaStructureMap:
        "[A] এবং [B]-এর মধ্যে (Between marker) + পার্থক্য হলো (Difference marker) + ... (Description)",
    },
    {
      id: "I6.5",
      formula: "While [A] is..., [B] is...",
      formula_bn: "যেখানে [ক]..., সেখানে [খ]...",
      patternName: "Contrastive While",
      patternName_bn: "বৈপরীত্যমূলক যেখানে",
      slots: [
        {
          name: "A",
          description: "The first clause with its description",
          description_bn: "প্রথম উপবাক্য ও তার বর্ণনা",
          acceptedTypes: ["clause"],
          examples: ["Dhaka is crowded", "tea is calming", "he is tall"],
        },
        {
          name: "B",
          description: "The contrasting clause",
          description_bn: "বিপরীত উপবাক্য",
          acceptedTypes: ["clause"],
          examples: ["Sylhet is quiet", "coffee is energizing", "she is short"],
        },
      ],
      examples: [
        {
          en: "While Dhaka is crowded, Sylhet is quiet and peaceful.",
          bn: "যেখানে ঢাকা জনবহুল, সেখানে সিলেট শান্ত ও শান্তিপূর্ণ।",
          slotValues: { A: "Dhaka is crowded", B: "Sylhet is quiet and peaceful" },
          topicArea: "travel",
        },
        {
          en: "While tea is calming, coffee is energizing.",
          bn: "যেখানে চা প্রশান্তিদায়ক, সেখানে কফি শক্তিদায়ক।",
          slotValues: { A: "tea is calming", B: "coffee is energizing" },
          topicArea: "food",
        },
        {
          en: "While he is very talkative, his wife is quiet.",
          bn: "যেখানে সে খুব কথাবার্তা বলে, সেখানে তার স্ত্রী চুপচাপ।",
          slotValues: { A: "he is very talkative", B: "his wife is quiet" },
          topicArea: "relationships",
        },
        {
          en: "While reading is a solo activity, group study is collaborative.",
          bn: "যেখানে পড়া একক কার্যক্রম, সেখানে দলীয় পড়া সহযোগিতামূলক।",
          slotValues: { A: "reading is a solo activity", B: "group study is collaborative" },
          topicArea: "education",
        },
        {
          en: "While my old job was boring, my new job is exciting.",
          bn: "যেখানে আমার পুরনো চাকরি বিরক্তিকর ছিল, সেখানে নতুন চাকরি উত্তেজনাপূর্ণ।",
          slotValues: { A: "my old job was boring", B: "my new job is exciting" },
          topicArea: "work",
        },
        {
          en: "While mornings are productive, evenings are relaxing.",
          bn: "যেখানে সকাল উৎপাদনশীল, সেখানে সন্ধ্যা আরামদায়ক।",
          slotValues: { A: "mornings are productive", B: "evenings are relaxing" },
          topicArea: "daily_life",
        },
        {
          en: "While this brand is expensive, that one is affordable.",
          bn: "যেখানে এই ব্র্যান্ড দামি, সেখানে ওটা সাশ্রয়ী।",
          slotValues: { A: "this brand is expensive", B: "that one is affordable" },
          topicArea: "shopping",
        },
        {
          en: "While running burns calories fast, walking is safer for joints.",
          bn: "যেখানে দৌড়ানো দ্রুত ক্যালোরি পোড়ায়, সেখানে হাঁটা জয়েন্টের জন্য নিরাপদ।",
          slotValues: { A: "running burns calories fast", B: "walking is safer for joints" },
          topicArea: "health",
        },
        {
          en: "While the city is noisy, the village is serene.",
          bn: "যেখানে শহর কোলাহলপূর্ণ, সেখানে গ্রাম শান্ত।",
          slotValues: { A: "the city is noisy", B: "the village is serene" },
          topicArea: "daily_life",
        },
        {
          en: "While biryani takes hours to cook, fried rice is quick.",
          bn: "যেখানে বিরিয়ানি রান্না করতে ঘণ্টা লাগে, সেখানে ফ্রাইড রাইস দ্রুত হয়।",
          slotValues: { A: "biryani takes hours to cook", B: "fried rice is quick" },
          topicArea: "food",
        },
        {
          en: "While she loves science, her brother prefers arts.",
          bn: "যেখানে সে বিজ্ঞান ভালোবাসে, সেখানে তার ভাই কলা পছন্দ করে।",
          slotValues: { A: "she loves science", B: "her brother prefers arts" },
          topicArea: "education",
        },
        {
          en: "While flying is faster, train travel is more scenic.",
          bn: "যেখানে বিমানে যাওয়া দ্রুত, সেখানে ট্রেনে ভ্রমণ বেশি মনোরম।",
          slotValues: { A: "flying is faster", B: "train travel is more scenic" },
          topicArea: "travel",
        },
        {
          en: "While the manager is strict, the team leader is friendly.",
          bn: "যেখানে ম্যানেজার কঠোর, সেখানে টিম লিডার বন্ধুসুলভ।",
          slotValues: { A: "the manager is strict", B: "the team leader is friendly" },
          topicArea: "work",
        },
        {
          en: "While he is generous, she is more careful with money.",
          bn: "যেখানে সে উদার, সেখানে সে টাকা নিয়ে বেশি সতর্ক।",
          slotValues: { A: "he is generous", B: "she is more careful with money" },
          topicArea: "relationships",
        },
        {
          en: "While online shopping is convenient, in-store shopping lets you try things.",
          bn: "যেখানে অনলাইন কেনাকাটা সুবিধাজনক, সেখানে দোকানে কেনাকাটায় জিনিস পরীক্ষা করা যায়।",
          slotValues: { A: "online shopping is convenient", B: "in-store shopping lets you try things" },
          topicArea: "shopping",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "'While' used at the start of a sentence introduces a contrast between two different situations or qualities.",
      usageNote_bn:
        "বাক্যের শুরুতে ব্যবহৃত 'While' দুটি ভিন্ন পরিস্থিতি বা গুণের মধ্যে বৈপরীত্য উপস্থাপন করে।",
      combinableWith: ["I6.2"],
      banglaStructureMap:
        "যেখানে (While marker) + [A] (First clause) + সেখানে (There marker) + [B] (Contrasting clause)",
    },
  ],
};
