import { PatternCategory } from "@/types/pattern";

export const categoryJ11: PatternCategory = {
  id: "J11",
  slug: "expressing-exceptions",
  name: "Expressing Exceptions",
  name_bn: "ব্যতিক্রম প্রকাশ",
  description:
    "Learn how to express exceptions, exclusions, and conditions that are the only barriers using common English patterns.",
  description_bn:
    "সাধারণ ইংরেজি প্যাটার্ন ব্যবহার করে ব্যতিক্রম, বাদ দেওয়া এবং একমাত্র বাধা শর্ত প্রকাশ করতে শিখুন।",
  icon: "❌",
  group: "J",
  groupName: "Explaining, Reasoning & Conditions",
  groupName_bn: "ব্যাখ্যা, যুক্তি ও শর্ত",
  difficulty: "intermediate",
  patterns: [
    {
      id: "J11.1",
      formula: "Everyone [ACTION+ED] except [PERSON]",
      formula_bn: "[ব্যক্তি] ছাড়া সবাই [কাজ+করেছে]",
      patternName: "Everyone Except",
      patternName_bn: "ছাড়া সবাই",
      slots: [
        {
          name: "ACTION+ED",
          description: "The action everyone did",
          description_bn: "সবাই যে কাজটি করেছে",
          acceptedTypes: ["verb_phrase"],
          examples: ["came to the party", "passed the exam", "agreed"],
        },
        {
          name: "PERSON",
          description: "The person who is the exception",
          description_bn: "যে ব্যক্তি ব্যতিক্রম",
          acceptedTypes: ["person", "noun_phrase"],
          examples: ["Rahim", "the new student", "my brother"],
        },
      ],
      examples: [
        {
          en: "Everyone came to the party except Rahim.",
          bn: "রহিম ছাড়া সবাই পার্টিতে এসেছে।",
          slotValues: { "ACTION+ED": "came to the party", PERSON: "Rahim" },
          topicArea: "relationships",
        },
        {
          en: "Everyone passed the exam except the new student.",
          bn: "নতুন ছাত্র ছাড়া সবাই পরীক্ষায় পাশ করেছে।",
          slotValues: { "ACTION+ED": "passed the exam", PERSON: "the new student" },
          topicArea: "education",
        },
        {
          en: "Everyone agreed except my brother.",
          bn: "আমার ভাই ছাড়া সবাই রাজি হয়েছে।",
          slotValues: { "ACTION+ED": "agreed", PERSON: "my brother" },
          topicArea: "relationships",
        },
        {
          en: "Everyone enjoyed the food except the vegetarian guest.",
          bn: "নিরামিষভোজী অতিথি ছাড়া সবাই খাবার উপভোগ করেছে।",
          slotValues: { "ACTION+ED": "enjoyed the food", PERSON: "the vegetarian guest" },
          topicArea: "food",
        },
        {
          en: "Everyone submitted the report except one team member.",
          bn: "একজন দলের সদস্য ছাড়া সবাই রিপোর্ট জমা দিয়েছে।",
          slotValues: { "ACTION+ED": "submitted the report", PERSON: "one team member" },
          topicArea: "work",
        },
        {
          en: "Everyone went to the beach except the elderly couple.",
          bn: "বয়স্ক দম্পতি ছাড়া সবাই সমুদ্র সৈকতে গেছে।",
          slotValues: { "ACTION+ED": "went to the beach", PERSON: "the elderly couple" },
          topicArea: "travel",
        },
        {
          en: "Everyone felt better except the patient in room three.",
          bn: "তিন নম্বর রুমের রোগী ছাড়া সবাই ভালো অনুভব করেছে।",
          slotValues: { "ACTION+ED": "felt better", PERSON: "the patient in room three" },
          topicArea: "health",
        },
        {
          en: "Everyone bought something except me.",
          bn: "আমি ছাড়া সবাই কিছু কিনেছে।",
          slotValues: { "ACTION+ED": "bought something", PERSON: "me" },
          topicArea: "shopping",
        },
        {
          en: "Everyone woke up on time except my roommate.",
          bn: "আমার রুমমেট ছাড়া সবাই সময়মতো উঠেছে।",
          slotValues: { "ACTION+ED": "woke up on time", PERSON: "my roommate" },
          topicArea: "daily_life",
        },
        {
          en: "Everyone understood the lesson except a few students.",
          bn: "কয়েকজন ছাত্র ছাড়া সবাই পাঠটি বুঝেছে।",
          slotValues: { "ACTION+ED": "understood the lesson", PERSON: "a few students" },
          topicArea: "education",
        },
        {
          en: "Everyone liked the biryani except the children.",
          bn: "বাচ্চারা ছাড়া সবাই বিরিয়ানি পছন্দ করেছে।",
          slotValues: { "ACTION+ED": "liked the biryani", PERSON: "the children" },
          topicArea: "food",
        },
        {
          en: "Everyone attended the meeting except the director.",
          bn: "পরিচালক ছাড়া সবাই মিটিংয়ে উপস্থিত ছিল।",
          slotValues: { "ACTION+ED": "attended the meeting", PERSON: "the director" },
          topicArea: "work",
        },
        {
          en: "Everyone visited the museum except the kids.",
          bn: "বাচ্চারা ছাড়া সবাই জাদুঘর দেখেছে।",
          slotValues: { "ACTION+ED": "visited the museum", PERSON: "the kids" },
          topicArea: "travel",
        },
        {
          en: "Everyone recovered quickly except the oldest patient.",
          bn: "সবচেয়ে বয়স্ক রোগী ছাড়া সবাই দ্রুত সুস্থ হয়েছে।",
          slotValues: { "ACTION+ED": "recovered quickly", PERSON: "the oldest patient" },
          topicArea: "health",
        },
        {
          en: "Everyone got a gift except the late arrivals.",
          bn: "যারা দেরিতে এসেছে তারা ছাড়া সবাই উপহার পেয়েছে।",
          slotValues: { "ACTION+ED": "got a gift", PERSON: "the late arrivals" },
          topicArea: "shopping",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Except' excludes one person or thing from a general statement. It usually comes at the end of the sentence.",
      usageNote_bn:
        "'Except' একটি সাধারণ বিবৃতি থেকে একজন ব্যক্তি বা জিনিসকে বাদ দেয়। এটি সাধারণত বাক্যের শেষে আসে।",
      combinableWith: ["J11.2"],
      banglaStructureMap:
        "[PERSON] ছাড়া (Except marker) + সবাই (Everyone) + [ACTION+ED] (Action done)",
    },
    {
      id: "J11.2",
      formula: "I like everything except [THING]",
      formula_bn: "আমি [জিনিস] ছাড়া সবকিছু পছন্দ করি",
      patternName: "Everything Except",
      patternName_bn: "ছাড়া সবকিছু",
      slots: [
        {
          name: "THING",
          description: "The exception",
          description_bn: "ব্যতিক্রম",
          acceptedTypes: ["noun", "noun_phrase", "gerund"],
          examples: ["the spicy ones", "the noise", "waiting in line"],
        },
      ],
      examples: [
        {
          en: "I like everything about this restaurant except the noise.",
          bn: "আমি এই রেস্তোরাঁর শব্দ ছাড়া সবকিছু পছন্দ করি।",
          slotValues: { THING: "the noise" },
          topicArea: "food",
        },
        {
          en: "I like everything about this hotel except the breakfast.",
          bn: "আমি এই হোটেলের সকালের নাস্তা ছাড়া সবকিছু পছন্দ করি।",
          slotValues: { THING: "the breakfast" },
          topicArea: "travel",
        },
        {
          en: "I like everything about my job except the long hours.",
          bn: "আমি আমার চাকরির দীর্ঘ কাজের সময় ছাড়া সবকিছু পছন্দ করি।",
          slotValues: { THING: "the long hours" },
          topicArea: "work",
        },
        {
          en: "I like everything about this course except the exams.",
          bn: "আমি এই কোর্সের পরীক্ষা ছাড়া সবকিছু পছন্দ করি।",
          slotValues: { THING: "the exams" },
          topicArea: "education",
        },
        {
          en: "I like everything about this phone except the battery life.",
          bn: "আমি এই ফোনের ব্যাটারি লাইফ ছাড়া সবকিছু পছন্দ করি।",
          slotValues: { THING: "the battery life" },
          topicArea: "shopping",
        },
        {
          en: "I like everything about him except his temper.",
          bn: "আমি তার রাগ ছাড়া সবকিছু পছন্দ করি।",
          slotValues: { THING: "his temper" },
          topicArea: "relationships",
        },
        {
          en: "I like everything about living here except the pollution.",
          bn: "আমি এখানে থাকার দূষণ ছাড়া সবকিছু পছন্দ করি।",
          slotValues: { THING: "the pollution" },
          topicArea: "daily_life",
        },
        {
          en: "I like everything about this gym except the crowded hours.",
          bn: "আমি এই জিমের ভিড়ের সময় ছাড়া সবকিছু পছন্দ করি।",
          slotValues: { THING: "the crowded hours" },
          topicArea: "health",
        },
        {
          en: "I eat everything except seafood.",
          bn: "আমি সামুদ্রিক খাবার ছাড়া সবকিছু খাই।",
          slotValues: { THING: "seafood" },
          topicArea: "food",
        },
        {
          en: "I like everything about traveling except the packing.",
          bn: "আমি ভ্রমণের ব্যাগ গোছানো ছাড়া সবকিছু পছন্দ করি।",
          slotValues: { THING: "the packing" },
          topicArea: "travel",
        },
        {
          en: "I like everything about weekends except Sunday evenings.",
          bn: "আমি সপ্তাহান্তের রবিবার সন্ধ্যা ছাড়া সবকিছু পছন্দ করি।",
          slotValues: { THING: "Sunday evenings" },
          topicArea: "daily_life",
        },
        {
          en: "I like everything about my school except the uniform.",
          bn: "আমি আমার স্কুলের ইউনিফর্ম ছাড়া সবকিছু পছন্দ করি।",
          slotValues: { THING: "the uniform" },
          topicArea: "education",
        },
        {
          en: "I like everything about her except that she is always late.",
          bn: "সে সবসময় দেরি করে এটা ছাড়া আমি তার সবকিছু পছন্দ করি।",
          slotValues: { THING: "that she is always late" },
          topicArea: "relationships",
        },
        {
          en: "I like everything about this product except the color options.",
          bn: "আমি এই পণ্যের রঙের বিকল্প ছাড়া সবকিছু পছন্দ করি।",
          slotValues: { THING: "the color options" },
          topicArea: "shopping",
        },
        {
          en: "I like everything about this clinic except the waiting time.",
          bn: "আমি এই ক্লিনিকের অপেক্ষার সময় ছাড়া সবকিছু পছন্দ করি।",
          slotValues: { THING: "the waiting time" },
          topicArea: "health",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "This pattern expresses general approval with one specific exception. 'Except' can be replaced with 'except for' with the same meaning.",
      usageNote_bn:
        "এই প্যাটার্নটি একটি নির্দিষ্ট ব্যতিক্রম সহ সাধারণ অনুমোদন প্রকাশ করে। 'Except' একই অর্থে 'except for' দিয়ে প্রতিস্থাপন করা যায়।",
      combinableWith: ["J11.1"],
      banglaStructureMap:
        "আমি (I) + [THING] ছাড়া (Except marker) + সবকিছু (Everything) + পছন্দ করি (Like)",
    },
    {
      id: "J11.3",
      formula: "Apart from [THING], everything...",
      formula_bn: "[জিনিস] বাদে, সবকিছু...",
      patternName: "Apart From Exception",
      patternName_bn: "বাদে ব্যতিক্রম",
      slots: [
        {
          name: "THING",
          description: "The exception being set aside",
          description_bn: "যে ব্যতিক্রমটি আলাদা করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["the weather", "one mistake", "the dessert"],
        },
      ],
      examples: [
        {
          en: "Apart from the weather, everything about the trip was perfect.",
          bn: "আবহাওয়া বাদে, ভ্রমণের সবকিছু নিখুঁত ছিল।",
          slotValues: { THING: "the weather" },
          topicArea: "travel",
        },
        {
          en: "Apart from one mistake, everything in the exam went well.",
          bn: "একটি ভুল বাদে, পরীক্ষায় সবকিছু ভালো গেছে।",
          slotValues: { THING: "one mistake" },
          topicArea: "education",
        },
        {
          en: "Apart from the dessert, everything at the restaurant was delicious.",
          bn: "মিষ্টি বাদে, রেস্তোরাঁর সবকিছু সুস্বাদু ছিল।",
          slotValues: { THING: "the dessert" },
          topicArea: "food",
        },
        {
          en: "Apart from the commute, everything about this job is great.",
          bn: "যাতায়াত বাদে, এই চাকরির সবকিছু দারুণ।",
          slotValues: { THING: "the commute" },
          topicArea: "work",
        },
        {
          en: "Apart from the price, everything about this product is excellent.",
          bn: "দাম বাদে, এই পণ্যের সবকিছু চমৎকার।",
          slotValues: { THING: "the price" },
          topicArea: "shopping",
        },
        {
          en: "Apart from his snoring, everything about my husband is perfect.",
          bn: "তার নাক ডাকা বাদে, আমার স্বামীর সবকিছু নিখুঁত।",
          slotValues: { THING: "his snoring" },
          topicArea: "relationships",
        },
        {
          en: "Apart from the mosquitoes, everything about the evening was lovely.",
          bn: "মশা বাদে, সন্ধ্যার সবকিছু সুন্দর ছিল।",
          slotValues: { THING: "the mosquitoes" },
          topicArea: "daily_life",
        },
        {
          en: "Apart from the side effects, everything about the treatment is positive.",
          bn: "পার্শ্বপ্রতিক্রিয়া বাদে, চিকিৎসার সবকিছু ইতিবাচক।",
          slotValues: { THING: "the side effects" },
          topicArea: "health",
        },
        {
          en: "Apart from the flight delay, everything was well planned.",
          bn: "ফ্লাইটের দেরি বাদে, সবকিছু ভালোভাবে পরিকল্পিত ছিল।",
          slotValues: { THING: "the flight delay" },
          topicArea: "travel",
        },
        {
          en: "Apart from the last chapter, everything in the book was interesting.",
          bn: "শেষ অধ্যায় বাদে, বইয়ের সবকিছু আকর্ষণীয় ছিল।",
          slotValues: { THING: "the last chapter" },
          topicArea: "education",
        },
        {
          en: "Apart from the spiciness, everything about the curry was great.",
          bn: "ঝাল বাদে, তরকারির সবকিছু দারুণ ছিল।",
          slotValues: { THING: "the spiciness" },
          topicArea: "food",
        },
        {
          en: "Apart from the deadline pressure, everything about the project was enjoyable.",
          bn: "ডেডলাইনের চাপ বাদে, প্রকল্পের সবকিছু উপভোগ্য ছিল।",
          slotValues: { THING: "the deadline pressure" },
          topicArea: "work",
        },
        {
          en: "Apart from the size, everything about the dress is beautiful.",
          bn: "সাইজ বাদে, পোশাকের সবকিছু সুন্দর।",
          slotValues: { THING: "the size" },
          topicArea: "shopping",
        },
        {
          en: "Apart from one disagreement, everything in our relationship is smooth.",
          bn: "একটি মতবিরোধ বাদে, আমাদের সম্পর্কের সবকিছু মসৃণ।",
          slotValues: { THING: "one disagreement" },
          topicArea: "relationships",
        },
        {
          en: "Apart from the long wait, everything at the hospital was fine.",
          bn: "দীর্ঘ অপেক্ষা বাদে, হাসপাতালের সবকিছু ঠিক ছিল।",
          slotValues: { THING: "the long wait" },
          topicArea: "health",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "'Apart from' when used with 'everything' means the same as 'except for'. It highlights a single exception in an otherwise positive statement.",
      usageNote_bn:
        "'Apart from' যখন 'everything'-এর সাথে ব্যবহৃত হয় তখন 'except for'-এর মতো অর্থ বহন করে। এটি একটি ইতিবাচক বিবৃতিতে একটি ব্যতিক্রম তুলে ধরে।",
      combinableWith: ["J11.2"],
      banglaStructureMap:
        "[THING] বাদে (Apart from marker) + সবকিছু (Everything) + ... (Positive statement)",
    },
    {
      id: "J11.4",
      formula: "Unless [CONDITION]...",
      formula_bn: "যদি না [শর্ত]...",
      patternName: "Unless Condition",
      patternName_bn: "যদি না শর্ত",
      slots: [
        {
          name: "CONDITION",
          description: "The condition that is the only exception",
          description_bn: "যে শর্তটি একমাত্র ব্যতিক্রম",
          acceptedTypes: ["clause", "condition"],
          examples: ["you study hard", "it rains", "you hurry"],
        },
      ],
      examples: [
        {
          en: "Unless you study hard, you won't pass the exam.",
          bn: "যদি না কঠোর পড়াশোনা করো, পরীক্ষায় পাশ করতে পারবে না।",
          slotValues: { CONDITION: "you study hard" },
          topicArea: "education",
        },
        {
          en: "Unless it rains, we'll go to the park.",
          bn: "যদি না বৃষ্টি হয়, আমরা পার্কে যাব।",
          slotValues: { CONDITION: "it rains" },
          topicArea: "daily_life",
        },
        {
          en: "Unless you hurry, we'll miss the flight.",
          bn: "যদি না তাড়াতাড়ি করো, আমরা ফ্লাইট মিস করব।",
          slotValues: { CONDITION: "you hurry" },
          topicArea: "travel",
        },
        {
          en: "Unless you eat properly, you'll feel weak.",
          bn: "যদি না ঠিকমতো খাও, দুর্বল লাগবে।",
          slotValues: { CONDITION: "you eat properly" },
          topicArea: "food",
        },
        {
          en: "Unless the boss approves, we can't start the project.",
          bn: "যদি না বস অনুমোদন দেয়, আমরা প্রকল্প শুরু করতে পারব না।",
          slotValues: { CONDITION: "the boss approves" },
          topicArea: "work",
        },
        {
          en: "Unless you take your medicine, you won't get better.",
          bn: "যদি না ওষুধ খাও, ভালো হবে না।",
          slotValues: { CONDITION: "you take your medicine" },
          topicArea: "health",
        },
        {
          en: "Unless you apologize, she won't forgive you.",
          bn: "যদি না ক্ষমা চাও, সে তোমাকে ক্ষমা করবে না।",
          slotValues: { CONDITION: "you apologize" },
          topicArea: "relationships",
        },
        {
          en: "Unless there's a discount, I won't buy it.",
          bn: "যদি না ছাড় থাকে, আমি কিনব না।",
          slotValues: { CONDITION: "there's a discount" },
          topicArea: "shopping",
        },
        {
          en: "Unless you practice daily, your English won't improve.",
          bn: "যদি না প্রতিদিন অনুশীলন করো, ইংরেজি উন্নত হবে না।",
          slotValues: { CONDITION: "you practice daily" },
          topicArea: "education",
        },
        {
          en: "Unless the weather improves, the trip will be canceled.",
          bn: "যদি না আবহাওয়া ভালো হয়, ভ্রমণ বাতিল হবে।",
          slotValues: { CONDITION: "the weather improves" },
          topicArea: "travel",
        },
        {
          en: "Unless you add salt, the food will be tasteless.",
          bn: "যদি না লবণ দাও, খাবার বিস্বাদ হবে।",
          slotValues: { CONDITION: "you add salt" },
          topicArea: "food",
        },
        {
          en: "Unless you submit the report, you'll face consequences.",
          bn: "যদি না রিপোর্ট জমা দাও, পরিণতি ভোগ করতে হবে।",
          slotValues: { CONDITION: "you submit the report" },
          topicArea: "work",
        },
        {
          en: "Unless you talk to each other, the problem won't be resolved.",
          bn: "যদি না একে অপরের সাথে কথা বলো, সমস্যা সমাধান হবে না।",
          slotValues: { CONDITION: "you talk to each other" },
          topicArea: "relationships",
        },
        {
          en: "Unless you drink enough water, you'll get dehydrated.",
          bn: "যদি না যথেষ্ট পানি পান করো, পানিশূন্যতা হবে।",
          slotValues: { CONDITION: "you drink enough water" },
          topicArea: "health",
        },
        {
          en: "Unless you set an alarm, you might oversleep.",
          bn: "যদি না অ্যালার্ম দাও, বেশি ঘুমিয়ে যেতে পারো।",
          slotValues: { CONDITION: "you set an alarm" },
          topicArea: "daily_life",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Unless' means 'if not' or 'except if'. It introduces the only condition that would change the outcome.",
      usageNote_bn:
        "'Unless' মানে 'যদি না' বা 'ব্যতীত যদি'। এটি একমাত্র শর্ত উপস্থাপন করে যা ফলাফল পরিবর্তন করবে।",
      combinableWith: ["J11.1"],
      banglaStructureMap:
        "যদি না (Unless) + [CONDITION] (Condition clause) + ... (Consequence)",
    },
    {
      id: "J11.5",
      formula: "Other than [THING]...",
      formula_bn: "[জিনিস] ছাড়া...",
      patternName: "Other Than",
      patternName_bn: "ছাড়া",
      slots: [
        {
          name: "THING",
          description: "The thing being excluded",
          description_bn: "যে জিনিসটি বাদ দেওয়া হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase", "gerund"],
          examples: ["Bengali", "the traffic", "some minor issues"],
        },
      ],
      examples: [
        {
          en: "Other than Bengali, I can also speak a little English.",
          bn: "বাংলা ছাড়া, আমি একটু ইংরেজিও বলতে পারি।",
          slotValues: { THING: "Bengali" },
          topicArea: "education",
        },
        {
          en: "Other than the traffic, Dhaka is a lively city.",
          bn: "যানজট ছাড়া, ঢাকা একটি প্রাণবন্ত শহর।",
          slotValues: { THING: "the traffic" },
          topicArea: "travel",
        },
        {
          en: "Other than some minor issues, the project is complete.",
          bn: "কিছু ছোট সমস্যা ছাড়া, প্রকল্পটি সম্পূর্ণ।",
          slotValues: { THING: "some minor issues" },
          topicArea: "work",
        },
        {
          en: "Other than rice, I don't have anything to eat.",
          bn: "ভাত ছাড়া, আমার কাছে খাওয়ার কিছু নেই।",
          slotValues: { THING: "rice" },
          topicArea: "food",
        },
        {
          en: "Other than my mother, nobody cooks like that.",
          bn: "আমার মা ছাড়া, কেউ এভাবে রান্না করে না।",
          slotValues: { THING: "my mother" },
          topicArea: "relationships",
        },
        {
          en: "Other than the color, this shirt is exactly what I wanted.",
          bn: "রং ছাড়া, এই শার্টটি ঠিক আমি যা চেয়েছিলাম।",
          slotValues: { THING: "the color" },
          topicArea: "shopping",
        },
        {
          en: "Other than a slight headache, I feel perfectly fine.",
          bn: "সামান্য মাথাব্যথা ছাড়া, আমি পুরোপুরি ভালো আছি।",
          slotValues: { THING: "a slight headache" },
          topicArea: "health",
        },
        {
          en: "Other than cleaning, I enjoy all household tasks.",
          bn: "পরিষ্কার করা ছাড়া, আমি সব ঘরের কাজ উপভোগ করি।",
          slotValues: { THING: "cleaning" },
          topicArea: "daily_life",
        },
        {
          en: "Other than the final exam, all assessments are done.",
          bn: "চূড়ান্ত পরীক্ষা ছাড়া, সব মূল্যায়ন শেষ হয়েছে।",
          slotValues: { THING: "the final exam" },
          topicArea: "education",
        },
        {
          en: "Other than the mosquitoes, the camping trip was amazing.",
          bn: "মশা ছাড়া, ক্যাম্পিং ভ্রমণটি অসাধারণ ছিল।",
          slotValues: { THING: "the mosquitoes" },
          topicArea: "travel",
        },
        {
          en: "Other than the salt, the soup needed nothing.",
          bn: "লবণ ছাড়া, স্যুপে আর কিছু দরকার ছিল না।",
          slotValues: { THING: "the salt" },
          topicArea: "food",
        },
        {
          en: "Other than the overtime, the job is manageable.",
          bn: "অতিরিক্ত সময় ছাড়া, চাকরিটি সামলানো যায়।",
          slotValues: { THING: "the overtime" },
          topicArea: "work",
        },
        {
          en: "Other than my sister, no one knows my secret.",
          bn: "আমার বোন ছাড়া, কেউ আমার গোপন কথা জানে না।",
          slotValues: { THING: "my sister" },
          topicArea: "relationships",
        },
        {
          en: "Other than the delivery charge, the price was reasonable.",
          bn: "ডেলিভারি চার্জ ছাড়া, দাম যুক্তিসঙ্গত ছিল।",
          slotValues: { THING: "the delivery charge" },
          topicArea: "shopping",
        },
        {
          en: "Other than the occasional back pain, my health is good.",
          bn: "মাঝে মাঝে পিঠ ব্যথা ছাড়া, আমার স্বাস্থ্য ভালো।",
          slotValues: { THING: "the occasional back pain" },
          topicArea: "health",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "'Other than' works like 'apart from' or 'except for'. It can introduce both additions and exceptions.",
      usageNote_bn:
        "'Other than' 'apart from' বা 'except for'-এর মতো কাজ করে। এটি সংযোজন এবং ব্যতিক্রম উভয়ই উপস্থাপন করতে পারে।",
      combinableWith: ["J11.2"],
      banglaStructureMap:
        "[THING] ছাড়া (Other than marker) + ... (Remaining statement)",
    },
  ],
};
