import { PatternCategory } from "@/types/pattern";

export const categoryJ12: PatternCategory = {
  id: "J12",
  slug: "sequencing-ordering",
  name: "Sequencing & Ordering",
  name_bn: "ধারাবাহিকতা ও ক্রম",
  description:
    "Learn how to describe the order of events and steps in a process using common English patterns.",
  description_bn:
    "সাধারণ ইংরেজি প্যাটার্ন ব্যবহার করে ঘটনার ক্রম এবং একটি প্রক্রিয়ার ধাপ বর্ণনা করতে শিখুন।",
  icon: "📊",
  group: "J",
  groupName: "Explaining, Reasoning & Conditions",
  groupName_bn: "ব্যাখ্যা, যুক্তি ও শর্ত",
  difficulty: "intermediate",
  patterns: [
    {
      id: "J12.1",
      formula: "First... Then... Finally...",
      formula_bn: "প্রথমে... তারপর... সবশেষে...",
      patternName: "Three-Step Sequence",
      patternName_bn: "তিন-ধাপ ক্রম",
      slots: [],
      examples: [
        {
          en: "First, wash the rice. Then, boil it. Finally, drain the water.",
          bn: "প্রথমে, চাল ধুয়ে নিন। তারপর, সেদ্ধ করুন। সবশেষে, পানি ঝরিয়ে নিন।",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "First, book the tickets. Then, pack your bags. Finally, head to the airport.",
          bn: "প্রথমে, টিকিট বুক করুন। তারপর, ব্যাগ গুছিয়ে নিন। সবশেষে, বিমানবন্দরে যান।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "First, read the chapter. Then, take notes. Finally, practice the exercises.",
          bn: "প্রথমে, অধ্যায়টি পড়ুন। তারপর, নোট নিন। সবশেষে, অনুশীলনী করুন।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "First, check your email. Then, attend the meeting. Finally, submit the report.",
          bn: "প্রথমে, ইমেইল দেখুন। তারপর, মিটিংয়ে যোগ দিন। সবশেষে, রিপোর্ট জমা দিন।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "First, warm up. Then, do the main exercises. Finally, stretch and cool down.",
          bn: "প্রথমে, ওয়ার্ম আপ করুন। তারপর, মূল ব্যায়াম করুন। সবশেষে, স্ট্রেচ করে শীতল হোন।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "First, compare prices. Then, read reviews. Finally, make your purchase.",
          bn: "প্রথমে, দাম তুলনা করুন। তারপর, রিভিউ পড়ুন। সবশেষে, কেনাকাটা করুন।",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "First, wake up early. Then, have breakfast. Finally, start your day.",
          bn: "প্রথমে, সকালে ওঠুন। তারপর, সকালের নাস্তা করুন। সবশেষে, দিন শুরু করুন।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "First, listen to the other person. Then, think about it. Finally, respond calmly.",
          bn: "প্রথমে, অন্যের কথা শুনুন। তারপর, চিন্তা করুন। সবশেষে, শান্তভাবে উত্তর দিন।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "First, marinate the chicken. Then, heat the oil. Finally, fry until golden.",
          bn: "প্রথমে, মুরগি মেরিনেট করুন। তারপর, তেল গরম করুন। সবশেষে, সোনালি হওয়া পর্যন্ত ভাজুন।",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "First, apply for a visa. Then, arrange accommodation. Finally, plan your itinerary.",
          bn: "প্রথমে, ভিসার আবেদন করুন। তারপর, থাকার ব্যবস্থা করুন। সবশেষে, ভ্রমণসূচি পরিকল্পনা করুন।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "First, learn the alphabet. Then, practice words. Finally, form sentences.",
          bn: "প্রথমে, বর্ণমালা শিখুন। তারপর, শব্দ অনুশীলন করুন। সবশেষে, বাক্য তৈরি করুন।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "First, identify the problem. Then, brainstorm solutions. Finally, implement the best one.",
          bn: "প্রথমে, সমস্যা চিহ্নিত করুন। তারপর, সমাধান নিয়ে চিন্তা করুন। সবশেষে, সেরাটি বাস্তবায়ন করুন।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "First, consult the doctor. Then, get the prescription. Finally, buy the medicine.",
          bn: "প্রথমে, ডাক্তারের পরামর্শ নিন। তারপর, প্রেসক্রিপশন নিন। সবশেষে, ওষুধ কিনুন।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "First, create an account. Then, browse the catalog. Finally, place your order.",
          bn: "প্রথমে, অ্যাকাউন্ট তৈরি করুন। তারপর, ক্যাটালগ দেখুন। সবশেষে, অর্ডার দিন।",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "First, introduce yourself. Then, share your feelings. Finally, listen to their response.",
          bn: "প্রথমে, নিজের পরিচয় দিন। তারপর, আপনার অনুভূতি শেয়ার করুন। সবশেষে, তাদের উত্তর শুনুন।",
          slotValues: {},
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'First...Then...Finally...' is the most common way to describe a sequence of steps. It helps organize information clearly.",
      usageNote_bn:
        "'First...Then...Finally...' ধাপের ক্রম বর্ণনার সবচেয়ে সাধারণ উপায়। এটি তথ্য স্পষ্টভাবে সংগঠিত করতে সাহায্য করে।",
      combinableWith: ["J12.2"],
      banglaStructureMap:
        "প্রথমে (First) + ... + তারপর (Then) + ... + সবশেষে (Finally) + ...",
    },
    {
      id: "J12.2",
      formula: "Before [DOING], [ACTION]",
      formula_bn: "[করা]-র আগে, [কাজ]",
      patternName: "Before Sequence",
      patternName_bn: "আগে ক্রম",
      slots: [
        {
          name: "DOING",
          description: "The later action",
          description_bn: "পরবর্তী কাজ",
          acceptedTypes: ["gerund", "verb_phrase"],
          examples: ["leaving", "cooking", "starting"],
        },
        {
          name: "ACTION",
          description: "The action that comes first",
          description_bn: "যে কাজটি আগে আসে",
          acceptedTypes: ["verb_phrase", "clause"],
          examples: ["check your bag", "wash the vegetables", "read the instructions"],
        },
      ],
      examples: [
        {
          en: "Before leaving the house, check your bag.",
          bn: "বাড়ি থেকে বের হওয়ার আগে, ব্যাগ দেখে নাও।",
          slotValues: { DOING: "leaving the house", ACTION: "check your bag" },
          topicArea: "daily_life",
        },
        {
          en: "Before cooking, wash the vegetables properly.",
          bn: "রান্না করার আগে, সবজি ভালোভাবে ধুয়ে নাও।",
          slotValues: { DOING: "cooking", ACTION: "wash the vegetables properly" },
          topicArea: "food",
        },
        {
          en: "Before starting the exam, read the instructions carefully.",
          bn: "পরীক্ষা শুরু করার আগে, নির্দেশনা ভালোভাবে পড়ো।",
          slotValues: { DOING: "starting the exam", ACTION: "read the instructions carefully" },
          topicArea: "education",
        },
        {
          en: "Before traveling, make sure your passport is valid.",
          bn: "ভ্রমণ করার আগে, নিশ্চিত হও যে পাসপোর্ট বৈধ।",
          slotValues: { DOING: "traveling", ACTION: "make sure your passport is valid" },
          topicArea: "travel",
        },
        {
          en: "Before buying, compare the prices online.",
          bn: "কেনার আগে, অনলাইনে দাম তুলনা করো।",
          slotValues: { DOING: "buying", ACTION: "compare the prices online" },
          topicArea: "shopping",
        },
        {
          en: "Before exercising, do a proper warm-up.",
          bn: "ব্যায়াম করার আগে, ভালোভাবে ওয়ার্ম-আপ করো।",
          slotValues: { DOING: "exercising", ACTION: "do a proper warm-up" },
          topicArea: "health",
        },
        {
          en: "Before submitting the report, proofread it once more.",
          bn: "রিপোর্ট জমা দেওয়ার আগে, আরেকবার প্রুফরিড করো।",
          slotValues: { DOING: "submitting the report", ACTION: "proofread it once more" },
          topicArea: "work",
        },
        {
          en: "Before making a decision, talk to your partner.",
          bn: "সিদ্ধান্ত নেওয়ার আগে, তোমার সঙ্গীর সাথে কথা বলো।",
          slotValues: { DOING: "making a decision", ACTION: "talk to your partner" },
          topicArea: "relationships",
        },
        {
          en: "Before serving the food, taste it first.",
          bn: "খাবার পরিবেশনের আগে, আগে স্বাদ দেখো।",
          slotValues: { DOING: "serving the food", ACTION: "taste it first" },
          topicArea: "food",
        },
        {
          en: "Before boarding the bus, check the route number.",
          bn: "বাসে ওঠার আগে, রুট নম্বর দেখে নাও।",
          slotValues: { DOING: "boarding the bus", ACTION: "check the route number" },
          topicArea: "travel",
        },
        {
          en: "Before sleeping, brush your teeth.",
          bn: "ঘুমানোর আগে, দাঁত মাজো।",
          slotValues: { DOING: "sleeping", ACTION: "brush your teeth" },
          topicArea: "daily_life",
        },
        {
          en: "Before answering, think about what you want to say.",
          bn: "উত্তর দেওয়ার আগে, কী বলতে চাও তা চিন্তা করো।",
          slotValues: { DOING: "answering", ACTION: "think about what you want to say" },
          topicArea: "education",
        },
        {
          en: "Before taking any medicine, consult a doctor.",
          bn: "কোনো ওষুধ খাওয়ার আগে, ডাক্তারের পরামর্শ নাও।",
          slotValues: { DOING: "taking any medicine", ACTION: "consult a doctor" },
          topicArea: "health",
        },
        {
          en: "Before signing the contract, read every clause.",
          bn: "চুক্তি সই করার আগে, প্রতিটি ধারা পড়ো।",
          slotValues: { DOING: "signing the contract", ACTION: "read every clause" },
          topicArea: "work",
        },
        {
          en: "Before returning the product, keep the receipt safe.",
          bn: "পণ্য ফেরত দেওয়ার আগে, রসিদ নিরাপদ রাখো।",
          slotValues: { DOING: "returning the product", ACTION: "keep the receipt safe" },
          topicArea: "shopping",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Before + gerund' introduces an action that should happen first. It sets up a time sequence.",
      usageNote_bn:
        "'Before + gerund' এমন একটি কাজ পরিচয় করায় যা আগে ঘটা উচিত। এটি একটি সময়ের ক্রম তৈরি করে।",
      combinableWith: ["J12.3"],
      banglaStructureMap:
        "[DOING]-র আগে (Before marker) + [ACTION] (Prior action)",
    },
    {
      id: "J12.3",
      formula: "After [DOING], [ACTION]",
      formula_bn: "[করা]-র পরে, [কাজ]",
      patternName: "After Sequence",
      patternName_bn: "পরে ক্রম",
      slots: [
        {
          name: "DOING",
          description: "The earlier action",
          description_bn: "আগের কাজ",
          acceptedTypes: ["gerund", "verb_phrase"],
          examples: ["finishing work", "eating dinner", "graduating"],
        },
        {
          name: "ACTION",
          description: "The action that follows",
          description_bn: "যে কাজটি পরে আসে",
          acceptedTypes: ["verb_phrase", "clause"],
          examples: ["I go for a walk", "we watch TV", "she got a job"],
        },
      ],
      examples: [
        {
          en: "After finishing work, I go for a walk.",
          bn: "কাজ শেষ করার পরে, আমি হাঁটতে যাই।",
          slotValues: { DOING: "finishing work", ACTION: "I go for a walk" },
          topicArea: "daily_life",
        },
        {
          en: "After eating dinner, we usually watch TV.",
          bn: "রাতের খাবার খাওয়ার পরে, আমরা সাধারণত টিভি দেখি।",
          slotValues: { DOING: "eating dinner", ACTION: "we usually watch TV" },
          topicArea: "food",
        },
        {
          en: "After graduating, she got a job at a bank.",
          bn: "গ্র্যাজুয়েশনের পরে, সে ব্যাংকে চাকরি পেয়েছে।",
          slotValues: { DOING: "graduating", ACTION: "she got a job at a bank" },
          topicArea: "education",
        },
        {
          en: "After arriving at the hotel, we went sightseeing.",
          bn: "হোটেলে পৌঁছানোর পরে, আমরা দর্শনীয় স্থান ঘুরতে গেলাম।",
          slotValues: { DOING: "arriving at the hotel", ACTION: "we went sightseeing" },
          topicArea: "travel",
        },
        {
          en: "After the meeting, the boss gave us feedback.",
          bn: "মিটিংয়ের পরে, বস আমাদের মতামত দিয়েছে।",
          slotValues: { DOING: "the meeting", ACTION: "the boss gave us feedback" },
          topicArea: "work",
        },
        {
          en: "After taking the medicine, I felt much better.",
          bn: "ওষুধ খাওয়ার পরে, আমি অনেক ভালো অনুভব করেছি।",
          slotValues: { DOING: "taking the medicine", ACTION: "I felt much better" },
          topicArea: "health",
        },
        {
          en: "After buying the groceries, we went home.",
          bn: "মুদি কেনার পরে, আমরা বাড়ি গেলাম।",
          slotValues: { DOING: "buying the groceries", ACTION: "we went home" },
          topicArea: "shopping",
        },
        {
          en: "After the argument, they didn't talk for a week.",
          bn: "তর্কের পরে, তারা এক সপ্তাহ কথা বলেনি।",
          slotValues: { DOING: "the argument", ACTION: "they didn't talk for a week" },
          topicArea: "relationships",
        },
        {
          en: "After cooking lunch, she cleaned the kitchen.",
          bn: "দুপুরের খাবার রান্নার পরে, সে রান্নাঘর পরিষ্কার করেছে।",
          slotValues: { DOING: "cooking lunch", ACTION: "she cleaned the kitchen" },
          topicArea: "food",
        },
        {
          en: "After checking in, we explored the old city.",
          bn: "চেক ইন করার পরে, আমরা পুরনো শহর ঘুরেছি।",
          slotValues: { DOING: "checking in", ACTION: "we explored the old city" },
          topicArea: "travel",
        },
        {
          en: "After reviewing the notes, the student felt more confident.",
          bn: "নোট পর্যালোচনার পরে, ছাত্রটি আরো আত্মবিশ্বাসী অনুভব করেছে।",
          slotValues: { DOING: "reviewing the notes", ACTION: "the student felt more confident" },
          topicArea: "education",
        },
        {
          en: "After waking up, I drink a glass of water.",
          bn: "ওঠার পরে, আমি এক গ্লাস পানি পান করি।",
          slotValues: { DOING: "waking up", ACTION: "I drink a glass of water" },
          topicArea: "daily_life",
        },
        {
          en: "After completing the training, he was promoted.",
          bn: "প্রশিক্ষণ সম্পন্ন করার পরে, তার পদোন্নতি হয়েছে।",
          slotValues: { DOING: "completing the training", ACTION: "he was promoted" },
          topicArea: "work",
        },
        {
          en: "After the surgery, she needed six weeks of rest.",
          bn: "অস্ত্রোপচারের পরে, তার ছয় সপ্তাহ বিশ্রাম দরকার ছিল।",
          slotValues: { DOING: "the surgery", ACTION: "she needed six weeks of rest" },
          topicArea: "health",
        },
        {
          en: "After saying sorry, he felt relieved.",
          bn: "দুঃখিত বলার পরে, সে স্বস্তি অনুভব করেছে।",
          slotValues: { DOING: "saying sorry", ACTION: "he felt relieved" },
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'After + gerund/noun' describes what happens next in a sequence. The action in the 'after' clause happens first.",
      usageNote_bn:
        "'After + gerund/noun' একটি ক্রমে পরবর্তীতে কী ঘটে তা বর্ণনা করে। 'after' ক্লজের কাজটি আগে ঘটে।",
      combinableWith: ["J12.2"],
      banglaStructureMap:
        "[DOING]-র পরে (After marker) + [ACTION] (Following action)",
    },
    {
      id: "J12.4",
      formula: "Once [CLAUSE]...",
      formula_bn: "একবার [উপবাক্য]...",
      patternName: "Once Trigger",
      patternName_bn: "একবার ট্রিগার",
      slots: [
        {
          name: "CLAUSE",
          description: "The triggering event",
          description_bn: "ট্রিগার করা ঘটনা",
          acceptedTypes: ["clause"],
          examples: ["you understand the basics", "the water boils", "you start"],
        },
      ],
      examples: [
        {
          en: "Once you understand the basics, everything becomes easier.",
          bn: "একবার মূল বিষয়গুলো বুঝলে, সবকিছু সহজ হয়ে যায়।",
          slotValues: { CLAUSE: "you understand the basics" },
          topicArea: "education",
        },
        {
          en: "Once the water boils, add the rice.",
          bn: "একবার পানি ফুটলে, চাল দিন।",
          slotValues: { CLAUSE: "the water boils" },
          topicArea: "food",
        },
        {
          en: "Once you start, you won't want to stop.",
          bn: "একবার শুরু করলে, থামতে চাইবে না।",
          slotValues: { CLAUSE: "you start" },
          topicArea: "daily_life",
        },
        {
          en: "Once you reach the airport, call me.",
          bn: "একবার বিমানবন্দরে পৌঁছালে, আমাকে ফোন করো।",
          slotValues: { CLAUSE: "you reach the airport" },
          topicArea: "travel",
        },
        {
          en: "Once the project is approved, we can begin immediately.",
          bn: "একবার প্রকল্প অনুমোদিত হলে, আমরা সাথে সাথে শুরু করতে পারি।",
          slotValues: { CLAUSE: "the project is approved" },
          topicArea: "work",
        },
        {
          en: "Once you start feeling better, reduce the dosage.",
          bn: "একবার ভালো লাগতে শুরু করলে, ডোজ কমান।",
          slotValues: { CLAUSE: "you start feeling better" },
          topicArea: "health",
        },
        {
          en: "Once you find the right product, the purchase is easy.",
          bn: "একবার সঠিক পণ্য পেলে, কেনা সহজ।",
          slotValues: { CLAUSE: "you find the right product" },
          topicArea: "shopping",
        },
        {
          en: "Once you build trust, the relationship grows stronger.",
          bn: "একবার বিশ্বাস তৈরি হলে, সম্পর্ক আরো মজবুত হয়।",
          slotValues: { CLAUSE: "you build trust" },
          topicArea: "relationships",
        },
        {
          en: "Once the chicken is golden, flip it over.",
          bn: "একবার মুরগি সোনালি হলে, উল্টে দিন।",
          slotValues: { CLAUSE: "the chicken is golden" },
          topicArea: "food",
        },
        {
          en: "Once you get your visa, start booking hotels.",
          bn: "একবার ভিসা পেলে, হোটেল বুকিং শুরু করো।",
          slotValues: { CLAUSE: "you get your visa" },
          topicArea: "travel",
        },
        {
          en: "Once you learn the grammar rules, speaking becomes natural.",
          bn: "একবার ব্যাকরণের নিয়ম শিখলে, কথা বলা স্বাভাবিক হয়ে যায়।",
          slotValues: { CLAUSE: "you learn the grammar rules" },
          topicArea: "education",
        },
        {
          en: "Once the deadline passes, no changes can be made.",
          bn: "একবার সময়সীমা পার হলে, কোনো পরিবর্তন করা যাবে না।",
          slotValues: { CLAUSE: "the deadline passes" },
          topicArea: "work",
        },
        {
          en: "Once the fever goes down, you can eat normally.",
          bn: "একবার জ্বর কমলে, স্বাভাবিকভাবে খেতে পারবে।",
          slotValues: { CLAUSE: "the fever goes down" },
          topicArea: "health",
        },
        {
          en: "Once you apologize sincerely, things will get better.",
          bn: "একবার আন্তরিকভাবে ক্ষমা চাইলে, জিনিস ভালো হবে।",
          slotValues: { CLAUSE: "you apologize sincerely" },
          topicArea: "relationships",
        },
        {
          en: "Once the sun sets, we'll head back home.",
          bn: "একবার সূর্য অস্ত গেলে, আমরা বাড়ি ফিরব।",
          slotValues: { CLAUSE: "the sun sets" },
          topicArea: "daily_life",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Once' means 'as soon as' or 'when'. It introduces a condition that triggers the next action. It implies the action only needs to happen one time.",
      usageNote_bn:
        "'Once' মানে 'যত তাড়াতাড়ি' বা 'যখন'। এটি এমন একটি শর্ত উপস্থাপন করে যা পরবর্তী কাজকে ট্রিগার করে। এটি বোঝায় কাজটি শুধু একবার ঘটতে হবে।",
      combinableWith: ["J12.2"],
      banglaStructureMap:
        "একবার (Once) + [CLAUSE] (Triggering event) + ... (Following action)",
    },
    {
      id: "J12.5",
      formula: "The next step is to [ACTION]",
      formula_bn: "পরবর্তী ধাপ হলো [কাজ] করা",
      patternName: "Next Step",
      patternName_bn: "পরবর্তী ধাপ",
      slots: [
        {
          name: "ACTION",
          description: "The next action in the sequence",
          description_bn: "ক্রমের পরবর্তী কাজ",
          acceptedTypes: ["verb_phrase", "to_verb"],
          examples: ["submit the form", "add the spices", "review the results"],
        },
      ],
      examples: [
        {
          en: "The next step is to submit the application form.",
          bn: "পরবর্তী ধাপ হলো আবেদন ফর্ম জমা দেওয়া।",
          slotValues: { ACTION: "submit the application form" },
          topicArea: "education",
        },
        {
          en: "The next step is to add the spices and stir well.",
          bn: "পরবর্তী ধাপ হলো মসলা যোগ করা এবং ভালো করে নাড়া।",
          slotValues: { ACTION: "add the spices and stir well" },
          topicArea: "food",
        },
        {
          en: "The next step is to review the test results.",
          bn: "পরবর্তী ধাপ হলো পরীক্ষার ফলাফল পর্যালোচনা করা।",
          slotValues: { ACTION: "review the test results" },
          topicArea: "health",
        },
        {
          en: "The next step is to book the flights.",
          bn: "পরবর্তী ধাপ হলো ফ্লাইট বুক করা।",
          slotValues: { ACTION: "book the flights" },
          topicArea: "travel",
        },
        {
          en: "The next step is to assign tasks to the team.",
          bn: "পরবর্তী ধাপ হলো দলকে কাজ বিতরণ করা।",
          slotValues: { ACTION: "assign tasks to the team" },
          topicArea: "work",
        },
        {
          en: "The next step is to compare different options.",
          bn: "পরবর্তী ধাপ হলো বিভিন্ন বিকল্প তুলনা করা।",
          slotValues: { ACTION: "compare different options" },
          topicArea: "shopping",
        },
        {
          en: "The next step is to talk openly about your feelings.",
          bn: "পরবর্তী ধাপ হলো তোমার অনুভূতি নিয়ে খোলামেলা কথা বলা।",
          slotValues: { ACTION: "talk openly about your feelings" },
          topicArea: "relationships",
        },
        {
          en: "The next step is to create a daily schedule.",
          bn: "পরবর্তী ধাপ হলো একটি দৈনিক সময়সূচি তৈরি করা।",
          slotValues: { ACTION: "create a daily schedule" },
          topicArea: "daily_life",
        },
        {
          en: "The next step is to let the dough rest for 30 minutes.",
          bn: "পরবর্তী ধাপ হলো মাখা আটা ৩০ মিনিট রেখে দেওয়া।",
          slotValues: { ACTION: "let the dough rest for 30 minutes" },
          topicArea: "food",
        },
        {
          en: "The next step is to confirm the hotel reservation.",
          bn: "পরবর্তী ধাপ হলো হোটেল রিজার্ভেশন নিশ্চিত করা।",
          slotValues: { ACTION: "confirm the hotel reservation" },
          topicArea: "travel",
        },
        {
          en: "The next step is to practice the new vocabulary.",
          bn: "পরবর্তী ধাপ হলো নতুন শব্দ অনুশীলন করা।",
          slotValues: { ACTION: "practice the new vocabulary" },
          topicArea: "education",
        },
        {
          en: "The next step is to schedule a follow-up appointment.",
          bn: "পরবর্তী ধাপ হলো ফলো-আপ অ্যাপয়েন্টমেন্ট নির্ধারণ করা।",
          slotValues: { ACTION: "schedule a follow-up appointment" },
          topicArea: "health",
        },
        {
          en: "The next step is to present the proposal to the board.",
          bn: "পরবর্তী ধাপ হলো বোর্ডে প্রস্তাব উপস্থাপন করা।",
          slotValues: { ACTION: "present the proposal to the board" },
          topicArea: "work",
        },
        {
          en: "The next step is to check out and pay the bill.",
          bn: "পরবর্তী ধাপ হলো চেকআউট করা এবং বিল পরিশোধ করা।",
          slotValues: { ACTION: "check out and pay the bill" },
          topicArea: "shopping",
        },
        {
          en: "The next step is to plan a proper date night.",
          bn: "পরবর্তী ধাপ হলো একটি সুন্দর ডেট নাইট পরিকল্পনা করা।",
          slotValues: { ACTION: "plan a proper date night" },
          topicArea: "relationships",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "'The next step is to...' clearly signals what should happen next in a process. It's commonly used in instructions and guides.",
      usageNote_bn:
        "'The next step is to...' স্পষ্টভাবে সংকেত দেয় একটি প্রক্রিয়ায় পরবর্তীতে কী ঘটা উচিত। এটি সাধারণত নির্দেশনা এবং গাইডে ব্যবহৃত হয়।",
      combinableWith: ["J12.1"],
      banglaStructureMap:
        "পরবর্তী ধাপ হলো (The next step is) + [ACTION] করা (To do action)",
    },
  ],
};
