import { PatternCategory } from "@/types/pattern";

export const categoryJ2: PatternCategory = {
  id: "J2",
  slug: "showing-results",
  name: "Showing Results",
  name_bn: "ফলাফল দেখানো",
  description:
    "Learn how to express results and consequences using common English patterns.",
  description_bn:
    "সাধারণ ইংরেজি প্যাটার্ন ব্যবহার করে ফলাফল এবং পরিণতি প্রকাশ করতে শিখুন।",
  icon: "➡️",
  group: "J",
  groupName: "Explaining, Reasoning & Conditions",
  groupName_bn: "ব্যাখ্যা, যুক্তি এবং শর্ত",
  difficulty: "intermediate",
  patterns: [
    {
      id: "J2.1",
      formula: "[REASON], so [RESULT]",
      formula_bn: "[কারণ], তাই [ফলাফল]",
      patternName: "Result with 'so'",
      patternName_bn: "'so' দিয়ে ফলাফল",
      slots: [
        {
          name: "REASON",
          description: "The cause or reason",
          description_bn: "কারণ বা উৎস",
          acceptedTypes: ["clause"],
          examples: ["It was raining", "I was hungry", "The bus was late"],
        },
        {
          name: "RESULT",
          description: "The result or consequence",
          description_bn: "ফলাফল বা পরিণতি",
          acceptedTypes: ["clause", "result"],
          examples: ["I took an umbrella", "I ordered food", "I walked to work"],
        },
      ],
      examples: [
        {
          en: "It was raining, so I took an umbrella.",
          bn: "বৃষ্টি হচ্ছিল, তাই আমি ছাতা নিলাম।",
          slotValues: { REASON: "It was raining", RESULT: "I took an umbrella" },
          topicArea: "daily_life",
        },
        {
          en: "I was hungry, so I ordered some food.",
          bn: "আমার ক্ষুধা লাগছিল, তাই আমি কিছু খাবার অর্ডার করলাম।",
          slotValues: { REASON: "I was hungry", RESULT: "I ordered some food" },
          topicArea: "food",
        },
        {
          en: "The bus was late, so I walked to work.",
          bn: "বাস দেরি করেছিল, তাই আমি হেঁটে কাজে গেলাম।",
          slotValues: { REASON: "The bus was late", RESULT: "I walked to work" },
          topicArea: "travel",
        },
        {
          en: "I studied hard, so I passed the exam.",
          bn: "আমি কঠোর পড়াশোনা করেছি, তাই পরীক্ষায় পাশ করেছি।",
          slotValues: { REASON: "I studied hard", RESULT: "I passed the exam" },
          topicArea: "education",
        },
        {
          en: "The deadline is tomorrow, so I need to finish today.",
          bn: "সময়সীমা আগামীকাল, তাই আমাকে আজ শেষ করতে হবে।",
          slotValues: { REASON: "The deadline is tomorrow", RESULT: "I need to finish today" },
          topicArea: "work",
        },
        {
          en: "I was feeling sick, so I went to the doctor.",
          bn: "আমার শরীর খারাপ লাগছিল, তাই আমি ডাক্তারের কাছে গেলাম।",
          slotValues: { REASON: "I was feeling sick", RESULT: "I went to the doctor" },
          topicArea: "health",
        },
        {
          en: "The shoes were on sale, so I bought two pairs.",
          bn: "জুতোগুলো সেলে ছিল, তাই আমি দুই জোড়া কিনলাম।",
          slotValues: { REASON: "The shoes were on sale", RESULT: "I bought two pairs" },
          topicArea: "shopping",
        },
        {
          en: "She missed me, so she called.",
          bn: "সে আমাকে মিস করছিল, তাই ফোন করেছে।",
          slotValues: { REASON: "She missed me", RESULT: "she called" },
          topicArea: "relationships",
        },
        {
          en: "The food was cold, so I heated it up.",
          bn: "খাবার ঠান্ডা ছিল, তাই আমি গরম করলাম।",
          slotValues: { REASON: "The food was cold", RESULT: "I heated it up" },
          topicArea: "food",
        },
        {
          en: "I didn't understand the lesson, so I asked the teacher.",
          bn: "আমি পাঠটি বুঝিনি, তাই শিক্ষককে জিজ্ঞেস করলাম।",
          slotValues: { REASON: "I didn't understand the lesson", RESULT: "I asked the teacher" },
          topicArea: "education",
        },
        {
          en: "The hotel was fully booked, so we found another one.",
          bn: "হোটেল পুরোপুরি বুক ছিল, তাই আমরা অন্য একটি খুঁজলাম।",
          slotValues: { REASON: "The hotel was fully booked", RESULT: "we found another one" },
          topicArea: "travel",
        },
        {
          en: "I finished my work early, so I went home.",
          bn: "আমি কাজ তাড়াতাড়ি শেষ করেছি, তাই বাড়ি চলে গেলাম।",
          slotValues: { REASON: "I finished my work early", RESULT: "I went home" },
          topicArea: "work",
        },
        {
          en: "It was a sunny day, so we went to the park.",
          bn: "রোদ ঝলমলে দিন ছিল, তাই আমরা পার্কে গেলাম।",
          slotValues: { REASON: "It was a sunny day", RESULT: "we went to the park" },
          topicArea: "daily_life",
        },
        {
          en: "I couldn't find the product in store, so I ordered it online.",
          bn: "আমি দোকানে পণ্যটি পাইনি, তাই অনলাইনে অর্ডার করলাম।",
          slotValues: { REASON: "I couldn't find the product in store", RESULT: "I ordered it online" },
          topicArea: "shopping",
        },
        {
          en: "The pain got worse, so I took some medicine.",
          bn: "ব্যথা আরও বাড়ল, তাই আমি কিছু ওষুধ খেলাম।",
          slotValues: { REASON: "The pain got worse", RESULT: "I took some medicine" },
          topicArea: "health",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'So' is the most common informal way to show a result. The cause comes first, then 'so', then the result.",
      usageNote_bn:
        "'So' ফলাফল দেখানোর সবচেয়ে সাধারণ অনানুষ্ঠানিক উপায়। প্রথমে কারণ আসে, তারপর 'so', তারপর ফলাফল।",
      combinableWith: ["J1.1"],
      banglaStructureMap:
        "[REASON] (Reason clause) + তাই (Result marker) + [RESULT] (Result clause)",
    },
    {
      id: "J2.2",
      formula: "As a result, [CLAUSE]",
      formula_bn: "ফলস্বরূপ, [উপবাক্য]",
      patternName: "Formal Result",
      patternName_bn: "আনুষ্ঠানিক ফলাফল",
      slots: [
        {
          name: "CLAUSE",
          description: "The result or consequence",
          description_bn: "ফলাফল বা পরিণতি",
          acceptedTypes: ["clause", "result"],
          examples: [
            "many people lost their jobs",
            "the company grew rapidly",
            "the project was delayed",
          ],
        },
      ],
      examples: [
        {
          en: "The factory closed. As a result, many people lost their jobs.",
          bn: "কারখানা বন্ধ হয়ে গেল। ফলস্বরূপ, অনেক মানুষ তাদের চাকরি হারাল।",
          slotValues: { CLAUSE: "many people lost their jobs" },
          topicArea: "work",
        },
        {
          en: "She practiced daily. As a result, her English improved.",
          bn: "সে প্রতিদিন অনুশীলন করেছে। ফলস্বরূপ, তার ইংরেজি উন্নত হয়েছে।",
          slotValues: { CLAUSE: "her English improved" },
          topicArea: "education",
        },
        {
          en: "It rained heavily. As a result, the roads were flooded.",
          bn: "ভারী বৃষ্টি হয়েছে। ফলস্বরূপ, রাস্তাগুলো প্লাবিত হয়েছে।",
          slotValues: { CLAUSE: "the roads were flooded" },
          topicArea: "daily_life",
        },
        {
          en: "He didn't follow the diet. As a result, his condition worsened.",
          bn: "সে ডায়েট মানেনি। ফলস্বরূপ, তার অবস্থা আরও খারাপ হয়েছে।",
          slotValues: { CLAUSE: "his condition worsened" },
          topicArea: "health",
        },
        {
          en: "The new route opened. As a result, travel time was reduced.",
          bn: "নতুন রুট খুলেছে। ফলস্বরূপ, ভ্রমণের সময় কমেছে।",
          slotValues: { CLAUSE: "travel time was reduced" },
          topicArea: "travel",
        },
        {
          en: "Prices dropped. As a result, more people started buying.",
          bn: "দাম কমেছে। ফলস্বরূপ, আরও বেশি মানুষ কেনাকাটা শুরু করেছে।",
          slotValues: { CLAUSE: "more people started buying" },
          topicArea: "shopping",
        },
        {
          en: "They argued. As a result, they stopped talking to each other.",
          bn: "তারা ঝগড়া করেছে। ফলস্বরূপ, তারা একে অপরের সাথে কথা বলা বন্ধ করেছে।",
          slotValues: { CLAUSE: "they stopped talking to each other" },
          topicArea: "relationships",
        },
        {
          en: "The chef used fresh ingredients. As a result, the food tasted amazing.",
          bn: "শেফ তাজা উপকরণ ব্যবহার করেছে। ফলস্বরূপ, খাবারের স্বাদ অসাধারণ ছিল।",
          slotValues: { CLAUSE: "the food tasted amazing" },
          topicArea: "food",
        },
        {
          en: "The team worked together. As a result, the project succeeded.",
          bn: "দল একসাথে কাজ করেছে। ফলস্বরূপ, প্রকল্প সফল হয়েছে।",
          slotValues: { CLAUSE: "the project succeeded" },
          topicArea: "work",
        },
        {
          en: "He read many books. As a result, he became very knowledgeable.",
          bn: "সে অনেক বই পড়েছে। ফলস্বরূপ, সে অনেক জ্ঞানী হয়েছে।",
          slotValues: { CLAUSE: "he became very knowledgeable" },
          topicArea: "education",
        },
        {
          en: "The weather was perfect. As a result, the event was a success.",
          bn: "আবহাওয়া চমৎকার ছিল। ফলস্বরূপ, অনুষ্ঠানটি সফল হয়েছে।",
          slotValues: { CLAUSE: "the event was a success" },
          topicArea: "daily_life",
        },
        {
          en: "She exercised daily. As a result, she felt healthier.",
          bn: "সে প্রতিদিন ব্যায়াম করেছে। ফলস্বরূপ, সে বেশি সুস্থ অনুভব করেছে।",
          slotValues: { CLAUSE: "she felt healthier" },
          topicArea: "health",
        },
        {
          en: "The airport was congested. As a result, many flights were delayed.",
          bn: "বিমানবন্দর জনাকীর্ণ ছিল। ফলস্বরূপ, অনেক ফ্লাইট দেরি হয়েছে।",
          slotValues: { CLAUSE: "many flights were delayed" },
          topicArea: "travel",
        },
        {
          en: "The brand launched a new collection. As a result, sales increased.",
          bn: "ব্র্যান্ড একটি নতুন কালেকশন চালু করেছে। ফলস্বরূপ, বিক্রি বেড়েছে।",
          slotValues: { CLAUSE: "sales increased" },
          topicArea: "shopping",
        },
        {
          en: "They communicated openly. As a result, their relationship grew stronger.",
          bn: "তারা খোলামেলা যোগাযোগ করেছে। ফলস্বরূপ, তাদের সম্পর্ক আরও মজবুত হয়েছে।",
          slotValues: { CLAUSE: "their relationship grew stronger" },
          topicArea: "relationships",
        },
      ],
      formality: "formal",
      difficulty: "intermediate",
      usageNote:
        "'As a result' is used in formal writing and speech. It connects a previous statement to its consequence.",
      usageNote_bn:
        "'As a result' আনুষ্ঠানিক লেখালেখি এবং বক্তৃতায় ব্যবহৃত হয়। এটি একটি পূর্ববর্তী বিবৃতিকে তার পরিণতির সাথে সংযুক্ত করে।",
      combinableWith: ["J2.1"],
      banglaStructureMap:
        "ফলস্বরূপ (Result marker) + [CLAUSE] (Result clause)",
    },
    {
      id: "J2.3",
      formula: "That's why [CLAUSE]",
      formula_bn: "এজন্যই [উপবাক্য]",
      patternName: "Explaining the Consequence",
      patternName_bn: "পরিণতি ব্যাখ্যা",
      slots: [
        {
          name: "CLAUSE",
          description: "The consequence being explained",
          description_bn: "যে পরিণতি ব্যাখ্যা করা হচ্ছে",
          acceptedTypes: ["clause", "result"],
          examples: [
            "I was late",
            "I love this place",
            "she is successful",
          ],
        },
      ],
      examples: [
        {
          en: "I missed the bus. That's why I was late.",
          bn: "আমি বাস মিস করেছি। এজন্যই আমি দেরি করেছি।",
          slotValues: { CLAUSE: "I was late" },
          topicArea: "daily_life",
        },
        {
          en: "The food is amazing. That's why I love this place.",
          bn: "খাবার অসাধারণ। এজন্যই আমি এই জায়গাটি ভালোবাসি।",
          slotValues: { CLAUSE: "I love this place" },
          topicArea: "food",
        },
        {
          en: "She works very hard. That's why she is successful.",
          bn: "সে খুব পরিশ্রম করে। এজন্যই সে সফল।",
          slotValues: { CLAUSE: "she is successful" },
          topicArea: "work",
        },
        {
          en: "He studies every day. That's why his English is so good.",
          bn: "সে প্রতিদিন পড়াশোনা করে। এজন্যই তার ইংরেজি এত ভালো।",
          slotValues: { CLAUSE: "his English is so good" },
          topicArea: "education",
        },
        {
          en: "The hotel has a great view. That's why it's so popular.",
          bn: "হোটেলটির দারুণ দৃশ্য আছে। এজন্যই এটি এত জনপ্রিয়।",
          slotValues: { CLAUSE: "it's so popular" },
          topicArea: "travel",
        },
        {
          en: "He eats healthy food. That's why he looks fit.",
          bn: "সে স্বাস্থ্যকর খাবার খায়। এজন্যই সে ফিট দেখায়।",
          slotValues: { CLAUSE: "he looks fit" },
          topicArea: "health",
        },
        {
          en: "The quality is excellent. That's why I always buy from this brand.",
          bn: "গুণমান চমৎকার। এজন্যই আমি সবসময় এই ব্র্যান্ড থেকে কিনি।",
          slotValues: { CLAUSE: "I always buy from this brand" },
          topicArea: "shopping",
        },
        {
          en: "She listens patiently. That's why everyone trusts her.",
          bn: "সে ধৈর্য ধরে শোনে। এজন্যই সবাই তাকে বিশ্বাস করে।",
          slotValues: { CLAUSE: "everyone trusts her" },
          topicArea: "relationships",
        },
        {
          en: "The weather was bad. That's why the match was canceled.",
          bn: "আবহাওয়া খারাপ ছিল। এজন্যই ম্যাচ বাতিল হয়েছে।",
          slotValues: { CLAUSE: "the match was canceled" },
          topicArea: "daily_life",
        },
        {
          en: "I didn't sleep well. That's why I'm so tired today.",
          bn: "আমি ভালো ঘুমাইনি। এজন্যই আমি আজ এত ক্লান্ত।",
          slotValues: { CLAUSE: "I'm so tired today" },
          topicArea: "health",
        },
        {
          en: "They use fresh ingredients. That's why the food tastes so good.",
          bn: "তারা তাজা উপকরণ ব্যবহার করে। এজন্যই খাবারের স্বাদ এত ভালো।",
          slotValues: { CLAUSE: "the food tastes so good" },
          topicArea: "food",
        },
        {
          en: "He had experience. That's why he got promoted quickly.",
          bn: "তার অভিজ্ঞতা ছিল। এজন্যই তার দ্রুত পদোন্নতি হয়েছে।",
          slotValues: { CLAUSE: "he got promoted quickly" },
          topicArea: "work",
        },
        {
          en: "The book was recommended. That's why I bought it.",
          bn: "বইটি সুপারিশ করা হয়েছিল। এজন্যই আমি কিনেছি।",
          slotValues: { CLAUSE: "I bought it" },
          topicArea: "education",
        },
        {
          en: "There was a big discount. That's why the shop was so crowded.",
          bn: "বড় ছাড় ছিল। এজন্যই দোকানে এত ভিড় ছিল।",
          slotValues: { CLAUSE: "the shop was so crowded" },
          topicArea: "shopping",
        },
        {
          en: "She always helps others. That's why people love her.",
          bn: "সে সবসময় অন্যদের সাহায্য করে। এজন্যই মানুষ তাকে ভালোবাসে।",
          slotValues: { CLAUSE: "people love her" },
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'That's why' is commonly used in spoken English to explain a result after giving the reason.",
      usageNote_bn:
        "'That's why' সাধারণত কথ্য ইংরেজিতে কারণ দেওয়ার পর ফলাফল ব্যাখ্যা করতে ব্যবহৃত হয়।",
      combinableWith: ["J2.1"],
      banglaStructureMap:
        "এজন্যই (Result marker) + [CLAUSE] (Result clause)",
    },
    {
      id: "J2.4",
      formula: "Therefore, [CLAUSE]",
      formula_bn: "তাই/সুতরাং, [উপবাক্য]",
      patternName: "Formal Conclusion",
      patternName_bn: "আনুষ্ঠানিক উপসংহার",
      slots: [
        {
          name: "CLAUSE",
          description: "The logical conclusion or result",
          description_bn: "যৌক্তিক উপসংহার বা ফলাফল",
          acceptedTypes: ["clause", "result"],
          examples: [
            "we need to plan carefully",
            "I decided to accept the offer",
            "it is important to act now",
          ],
        },
      ],
      examples: [
        {
          en: "The budget is limited. Therefore, we need to plan carefully.",
          bn: "বাজেট সীমিত। সুতরাং, আমাদের সাবধানে পরিকল্পনা করতে হবে।",
          slotValues: { CLAUSE: "we need to plan carefully" },
          topicArea: "work",
        },
        {
          en: "The offer was good. Therefore, I decided to accept it.",
          bn: "অফারটি ভালো ছিল। সুতরাং, আমি এটি গ্রহণ করার সিদ্ধান্ত নিলাম।",
          slotValues: { CLAUSE: "I decided to accept it" },
          topicArea: "work",
        },
        {
          en: "Regular exercise keeps you fit. Therefore, you should exercise daily.",
          bn: "নিয়মিত ব্যায়াম আপনাকে ফিট রাখে। সুতরাং, আপনার প্রতিদিন ব্যায়াম করা উচিত।",
          slotValues: { CLAUSE: "you should exercise daily" },
          topicArea: "health",
        },
        {
          en: "The evidence is clear. Therefore, we can draw a conclusion.",
          bn: "প্রমাণ স্পষ্ট। সুতরাং, আমরা একটি উপসংহার টানতে পারি।",
          slotValues: { CLAUSE: "we can draw a conclusion" },
          topicArea: "education",
        },
        {
          en: "The road is blocked. Therefore, we must take an alternative route.",
          bn: "রাস্তা বন্ধ। সুতরাং, আমাদের বিকল্প পথ নিতে হবে।",
          slotValues: { CLAUSE: "we must take an alternative route" },
          topicArea: "travel",
        },
        {
          en: "The product has many defects. Therefore, I'm returning it.",
          bn: "পণ্যটিতে অনেক ত্রুটি আছে। সুতরাং, আমি এটি ফেরত দিচ্ছি।",
          slotValues: { CLAUSE: "I'm returning it" },
          topicArea: "shopping",
        },
        {
          en: "Communication is key. Therefore, we must talk openly.",
          bn: "যোগাযোগ মূল বিষয়। সুতরাং, আমাদের খোলামেলা কথা বলতে হবে।",
          slotValues: { CLAUSE: "we must talk openly" },
          topicArea: "relationships",
        },
        {
          en: "Fresh food is important. Therefore, we should cook at home more often.",
          bn: "তাজা খাবার গুরুত্বপূর্ণ। সুতরাং, আমাদের বেশি করে বাড়িতে রান্না করা উচিত।",
          slotValues: { CLAUSE: "we should cook at home more often" },
          topicArea: "food",
        },
        {
          en: "Water is essential for health. Therefore, drink at least eight glasses a day.",
          bn: "স্বাস্থ্যের জন্য পানি অপরিহার্য। সুতরাং, দিনে কমপক্ষে আট গ্লাস পান করুন।",
          slotValues: { CLAUSE: "drink at least eight glasses a day" },
          topicArea: "health",
        },
        {
          en: "The situation is urgent. Therefore, we cannot wait any longer.",
          bn: "পরিস্থিতি জরুরি। সুতরাং, আমরা আর অপেক্ষা করতে পারি না।",
          slotValues: { CLAUSE: "we cannot wait any longer" },
          topicArea: "daily_life",
        },
        {
          en: "Reading improves vocabulary. Therefore, students should read regularly.",
          bn: "পড়া শব্দভান্ডার উন্নত করে। সুতরাং, ছাত্রদের নিয়মিত পড়া উচিত।",
          slotValues: { CLAUSE: "students should read regularly" },
          topicArea: "education",
        },
        {
          en: "The flight is expensive. Therefore, we decided to take the train.",
          bn: "ফ্লাইট দামি। সুতরাং, আমরা ট্রেনে যাওয়ার সিদ্ধান্ত নিলাম।",
          slotValues: { CLAUSE: "we decided to take the train" },
          topicArea: "travel",
        },
        {
          en: "The demand is high. Therefore, the price has increased.",
          bn: "চাহিদা বেশি। সুতরাং, দাম বেড়েছে।",
          slotValues: { CLAUSE: "the price has increased" },
          topicArea: "shopping",
        },
        {
          en: "Trust takes time. Therefore, we need to be patient.",
          bn: "বিশ্বাস তৈরি হতে সময় লাগে। সুতরাং, আমাদের ধৈর্য ধরতে হবে।",
          slotValues: { CLAUSE: "we need to be patient" },
          topicArea: "relationships",
        },
        {
          en: "The deadline has passed. Therefore, late submissions will not be accepted.",
          bn: "সময়সীমা পেরিয়ে গেছে। সুতরাং, দেরিতে জমা গ্রহণ করা হবে না।",
          slotValues: { CLAUSE: "late submissions will not be accepted" },
          topicArea: "work",
        },
      ],
      formality: "formal",
      difficulty: "intermediate",
      usageNote:
        "'Therefore' is a formal connector used in academic writing and professional communication to show a logical result.",
      usageNote_bn:
        "'Therefore' একটি আনুষ্ঠানিক সংযোগকারী যা একাডেমিক লেখালেখি এবং পেশাদার যোগাযোগে যৌক্তিক ফলাফল দেখাতে ব্যবহৃত হয়।",
      combinableWith: ["J2.2"],
      banglaStructureMap:
        "সুতরাং (Conclusion marker) + [CLAUSE] (Result clause)",
    },
    {
      id: "J2.5",
      formula: "Consequently, [CLAUSE]",
      formula_bn: "ফলে, [উপবাক্য]",
      patternName: "Formal Consequence",
      patternName_bn: "আনুষ্ঠানিক পরিণতি",
      slots: [
        {
          name: "CLAUSE",
          description: "The consequence of a previous event",
          description_bn: "পূর্ববর্তী ঘটনার পরিণতি",
          acceptedTypes: ["clause", "result"],
          examples: [
            "the company faced losses",
            "she had to change her plans",
            "they moved to a new city",
          ],
        },
      ],
      examples: [
        {
          en: "Sales dropped sharply. Consequently, the company faced losses.",
          bn: "বিক্রি তীব্রভাবে কমেছে। ফলে, কোম্পানি লোকসানের সম্মুখীন হয়েছে।",
          slotValues: { CLAUSE: "the company faced losses" },
          topicArea: "work",
        },
        {
          en: "The flight was canceled. Consequently, she had to change her plans.",
          bn: "ফ্লাইট বাতিল হয়েছে। ফলে, তাকে পরিকল্পনা পরিবর্তন করতে হয়েছে।",
          slotValues: { CLAUSE: "she had to change her plans" },
          topicArea: "travel",
        },
        {
          en: "He got a new job. Consequently, they moved to a new city.",
          bn: "সে নতুন চাকরি পেয়েছে। ফলে, তারা নতুন শহরে চলে গেছে।",
          slotValues: { CLAUSE: "they moved to a new city" },
          topicArea: "daily_life",
        },
        {
          en: "She didn't study enough. Consequently, she failed the exam.",
          bn: "সে যথেষ্ট পড়াশোনা করেনি। ফলে, সে পরীক্ষায় ফেল করেছে।",
          slotValues: { CLAUSE: "she failed the exam" },
          topicArea: "education",
        },
        {
          en: "He ignored his health. Consequently, he became very ill.",
          bn: "সে তার স্বাস্থ্য অবহেলা করেছে। ফলে, সে খুব অসুস্থ হয়ে পড়েছে।",
          slotValues: { CLAUSE: "he became very ill" },
          topicArea: "health",
        },
        {
          en: "The store raised prices. Consequently, customers went elsewhere.",
          bn: "দোকান দাম বাড়িয়েছে। ফলে, গ্রাহকরা অন্যত্র গেছে।",
          slotValues: { CLAUSE: "customers went elsewhere" },
          topicArea: "shopping",
        },
        {
          en: "They didn't communicate properly. Consequently, there was a big misunderstanding.",
          bn: "তারা সঠিকভাবে যোগাযোগ করেনি। ফলে, একটি বড় ভুল বোঝাবুঝি হয়েছে।",
          slotValues: { CLAUSE: "there was a big misunderstanding" },
          topicArea: "relationships",
        },
        {
          en: "The restaurant got bad reviews. Consequently, fewer people visited.",
          bn: "রেস্তোরাঁ খারাপ রিভিউ পেয়েছে। ফলে, কম মানুষ এসেছে।",
          slotValues: { CLAUSE: "fewer people visited" },
          topicArea: "food",
        },
        {
          en: "The team missed the deadline. Consequently, the client was unhappy.",
          bn: "দল সময়সীমা মিস করেছে। ফলে, ক্লায়েন্ট অসন্তুষ্ট ছিল।",
          slotValues: { CLAUSE: "the client was unhappy" },
          topicArea: "work",
        },
        {
          en: "He practiced speaking daily. Consequently, his fluency improved.",
          bn: "সে প্রতিদিন কথা বলার অনুশীলন করেছে। ফলে, তার সাবলীলতা উন্নত হয়েছে।",
          slotValues: { CLAUSE: "his fluency improved" },
          topicArea: "education",
        },
        {
          en: "The medicine was effective. Consequently, the patient recovered quickly.",
          bn: "ওষুধ কার্যকর ছিল। ফলে, রোগী দ্রুত সুস্থ হয়েছে।",
          slotValues: { CLAUSE: "the patient recovered quickly" },
          topicArea: "health",
        },
        {
          en: "It snowed heavily. Consequently, all flights were grounded.",
          bn: "ভারী তুষারপাত হয়েছে। ফলে, সব ফ্লাইট বন্ধ ছিল।",
          slotValues: { CLAUSE: "all flights were grounded" },
          topicArea: "travel",
        },
        {
          en: "The brand went viral. Consequently, they sold out within hours.",
          bn: "ব্র্যান্ড ভাইরাল হয়েছে। ফলে, কয়েক ঘণ্টার মধ্যে বিক্রি শেষ হয়েছে।",
          slotValues: { CLAUSE: "they sold out within hours" },
          topicArea: "shopping",
        },
        {
          en: "The power went out. Consequently, we had to cancel the dinner party.",
          bn: "বিদ্যুৎ চলে গেছে। ফলে, আমাদের ডিনার পার্টি বাতিল করতে হয়েছে।",
          slotValues: { CLAUSE: "we had to cancel the dinner party" },
          topicArea: "food",
        },
        {
          en: "He lied to her. Consequently, she lost trust in him.",
          bn: "সে তার কাছে মিথ্যা বলেছে। ফলে, সে তার উপর বিশ্বাস হারিয়েছে।",
          slotValues: { CLAUSE: "she lost trust in him" },
          topicArea: "relationships",
        },
      ],
      formality: "formal",
      difficulty: "intermediate",
      usageNote:
        "'Consequently' is very formal and is primarily used in written English to show a direct consequence of something.",
      usageNote_bn:
        "'Consequently' খুবই আনুষ্ঠানিক এবং প্রধানত লিখিত ইংরেজিতে কোনো কিছুর সরাসরি পরিণতি দেখাতে ব্যবহৃত হয়।",
      combinableWith: ["J2.2", "J2.4"],
      banglaStructureMap:
        "ফলে (Consequence marker) + [CLAUSE] (Result clause)",
    },
  ],
};
