import { PatternCategory } from "@/types/pattern";

export const categoryJ4: PatternCategory = {
  id: "J4",
  slug: "expressing-purpose",
  name: "Expressing Purpose",
  name_bn: "উদ্দেশ্য প্রকাশ",
  description:
    "Learn how to express purpose and intention using common English patterns.",
  description_bn:
    "সাধারণ ইংরেজি প্যাটার্ন ব্যবহার করে উদ্দেশ্য এবং অভিপ্রায় প্রকাশ করতে শিখুন।",
  icon: "🎯",
  group: "J",
  groupName: "Explaining, Reasoning & Conditions",
  groupName_bn: "ব্যাখ্যা, যুক্তি এবং শর্ত",
  difficulty: "intermediate",
  patterns: [
    {
      id: "J4.1",
      formula: "I [ACTION] to [ACTION]",
      formula_bn: "আমি [কাজ] করতে [কাজ] করি",
      patternName: "Simple Purpose with 'to'",
      patternName_bn: "'to' দিয়ে সাধারণ উদ্দেশ্য",
      slots: [
        {
          name: "ACTION",
          description: "The main action and its purpose",
          description_bn: "মূল কাজ এবং তার উদ্দেশ্য",
          acceptedTypes: ["verb_phrase"],
          examples: ["study hard / pass the exam", "exercise / stay healthy"],
        },
      ],
      examples: [
        {
          en: "I study hard to pass the exam.",
          bn: "আমি পরীক্ষায় পাশ করতে কঠোর পড়াশোনা করি।",
          slotValues: { ACTION: "study hard to pass the exam" },
          topicArea: "education",
        },
        {
          en: "I exercise daily to stay healthy.",
          bn: "আমি সুস্থ থাকতে প্রতিদিন ব্যায়াম করি।",
          slotValues: { ACTION: "exercise daily to stay healthy" },
          topicArea: "health",
        },
        {
          en: "I wake up early to avoid traffic.",
          bn: "আমি ট্রাফিক এড়াতে তাড়াতাড়ি উঠি।",
          slotValues: { ACTION: "wake up early to avoid traffic" },
          topicArea: "travel",
        },
        {
          en: "I work hard to support my family.",
          bn: "আমি পরিবারকে সাহায্য করতে কঠোর পরিশ্রম করি।",
          slotValues: { ACTION: "work hard to support my family" },
          topicArea: "work",
        },
        {
          en: "I save money to buy a new phone.",
          bn: "আমি নতুন ফোন কিনতে টাকা জমাই।",
          slotValues: { ACTION: "save money to buy a new phone" },
          topicArea: "shopping",
        },
        {
          en: "I cook at home to eat healthy food.",
          bn: "আমি স্বাস্থ্যকর খাবার খেতে বাড়িতে রান্না করি।",
          slotValues: { ACTION: "cook at home to eat healthy food" },
          topicArea: "food",
        },
        {
          en: "I called him to check on him.",
          bn: "আমি তার খবর নিতে তাকে ফোন করেছি।",
          slotValues: { ACTION: "called him to check on him" },
          topicArea: "relationships",
        },
        {
          en: "I went to the library to borrow some books.",
          bn: "আমি কিছু বই ধার করতে লাইব্রেরিতে গেছি।",
          slotValues: { ACTION: "went to the library to borrow some books" },
          topicArea: "education",
        },
        {
          en: "I drink water to stay hydrated.",
          bn: "আমি হাইড্রেটেড থাকতে পানি পান করি।",
          slotValues: { ACTION: "drink water to stay hydrated" },
          topicArea: "health",
        },
        {
          en: "I booked early to get a good seat.",
          bn: "আমি ভালো সিট পেতে আগে বুকিং দিয়েছি।",
          slotValues: { ACTION: "booked early to get a good seat" },
          topicArea: "travel",
        },
        {
          en: "I practice speaking to improve my English.",
          bn: "আমি ইংরেজি উন্নত করতে কথা বলার অনুশীলন করি।",
          slotValues: { ACTION: "practice speaking to improve my English" },
          topicArea: "education",
        },
        {
          en: "I take notes to remember important points.",
          bn: "আমি গুরুত্বপূর্ণ বিষয় মনে রাখতে নোট নিই।",
          slotValues: { ACTION: "take notes to remember important points" },
          topicArea: "work",
        },
        {
          en: "I use coupons to save money.",
          bn: "আমি টাকা বাঁচাতে কুপন ব্যবহার করি।",
          slotValues: { ACTION: "use coupons to save money" },
          topicArea: "shopping",
        },
        {
          en: "I add spices to make the food tastier.",
          bn: "আমি খাবার আরও সুস্বাদু করতে মশলা যোগ করি।",
          slotValues: { ACTION: "add spices to make the food tastier" },
          topicArea: "food",
        },
        {
          en: "I listen carefully to understand people better.",
          bn: "আমি মানুষকে আরও ভালো বুঝতে মনোযোগ দিয়ে শুনি।",
          slotValues: { ACTION: "listen carefully to understand people better" },
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "The infinitive 'to + verb' is the simplest way to express purpose. Very common in everyday English.",
      usageNote_bn:
        "'to + verb' ইনফিনিটিভ উদ্দেশ্য প্রকাশের সবচেয়ে সহজ উপায়। দৈনন্দিন ইংরেজিতে খুবই সাধারণ।",
      combinableWith: ["J4.2"],
      banglaStructureMap:
        "আমি (Subject) + [PURPOSE ACTION] (Purpose) + করতে (Purpose marker) + [MAIN ACTION] (Main verb) + করি (Verb ending)",
    },
    {
      id: "J4.2",
      formula: "I [ACTION] in order to [ACTION]",
      formula_bn: "আমি [কাজ] করার জন্য [কাজ] করি",
      patternName: "Formal Purpose with 'in order to'",
      patternName_bn: "'in order to' দিয়ে আনুষ্ঠানিক উদ্দেশ্য",
      slots: [
        {
          name: "ACTION",
          description: "The main action and its purpose",
          description_bn: "মূল কাজ এবং তার উদ্দেশ্য",
          acceptedTypes: ["verb_phrase"],
          examples: ["left early / avoid the rush", "studied abroad / gain international experience"],
        },
      ],
      examples: [
        {
          en: "I left early in order to avoid the rush.",
          bn: "আমি ভিড় এড়ানোর জন্য তাড়াতাড়ি রওনা দিয়েছি।",
          slotValues: { ACTION: "left early in order to avoid the rush" },
          topicArea: "travel",
        },
        {
          en: "She studied abroad in order to gain international experience.",
          bn: "সে আন্তর্জাতিক অভিজ্ঞতা অর্জন করার জন্য বিদেশে পড়াশোনা করেছে।",
          slotValues: { ACTION: "studied abroad in order to gain international experience" },
          topicArea: "education",
        },
        {
          en: "He works overtime in order to earn extra money.",
          bn: "সে অতিরিক্ত টাকা উপার্জন করার জন্য ওভারটাইম কাজ করে।",
          slotValues: { ACTION: "works overtime in order to earn extra money" },
          topicArea: "work",
        },
        {
          en: "I eat balanced meals in order to maintain good health.",
          bn: "আমি ভালো স্বাস্থ্য বজায় রাখার জন্য সুষম খাবার খাই।",
          slotValues: { ACTION: "eat balanced meals in order to maintain good health" },
          topicArea: "health",
        },
        {
          en: "We compare prices in order to find the best deal.",
          bn: "আমরা সেরা দর খুঁজে পাওয়ার জন্য দাম তুলনা করি।",
          slotValues: { ACTION: "compare prices in order to find the best deal" },
          topicArea: "shopping",
        },
        {
          en: "I marinate the chicken in order to add more flavor.",
          bn: "আমি আরও স্বাদ যোগ করার জন্য মুরগি ম্যারিনেট করি।",
          slotValues: { ACTION: "marinate the chicken in order to add more flavor" },
          topicArea: "food",
        },
        {
          en: "I apologized in order to fix our relationship.",
          bn: "আমি আমাদের সম্পর্ক ঠিক করার জন্য ক্ষমা চেয়েছি।",
          slotValues: { ACTION: "apologized in order to fix our relationship" },
          topicArea: "relationships",
        },
        {
          en: "She reads newspapers in order to improve her vocabulary.",
          bn: "সে শব্দভান্ডার উন্নত করার জন্য পত্রিকা পড়ে।",
          slotValues: { ACTION: "reads newspapers in order to improve her vocabulary" },
          topicArea: "education",
        },
        {
          en: "He set an alarm in order to wake up on time.",
          bn: "সে সময়মতো ঘুম থেকে উঠার জন্য অ্যালার্ম দিয়েছে।",
          slotValues: { ACTION: "set an alarm in order to wake up on time" },
          topicArea: "daily_life",
        },
        {
          en: "We hired more staff in order to handle the workload.",
          bn: "আমরা কাজের চাপ সামলানোর জন্য আরও কর্মী নিয়োগ করেছি।",
          slotValues: { ACTION: "hired more staff in order to handle the workload" },
          topicArea: "work",
        },
        {
          en: "I booked a direct flight in order to save time.",
          bn: "আমি সময় বাঁচানোর জন্য সরাসরি ফ্লাইট বুক করেছি।",
          slotValues: { ACTION: "booked a direct flight in order to save time" },
          topicArea: "travel",
        },
        {
          en: "She wears a mask in order to prevent getting sick.",
          bn: "সে অসুস্থ হওয়া প্রতিরোধ করার জন্য মাস্ক পরে।",
          slotValues: { ACTION: "wears a mask in order to prevent getting sick" },
          topicArea: "health",
        },
        {
          en: "I keep receipts in order to return items if needed.",
          bn: "আমি প্রয়োজনে পণ্য ফেরত দেওয়ার জন্য রসিদ রাখি।",
          slotValues: { ACTION: "keep receipts in order to return items if needed" },
          topicArea: "shopping",
        },
        {
          en: "We use fresh ingredients in order to make the food healthier.",
          bn: "আমরা খাবার আরও স্বাস্থ্যকর করার জন্য তাজা উপকরণ ব্যবহার করি।",
          slotValues: { ACTION: "use fresh ingredients in order to make the food healthier" },
          topicArea: "food",
        },
        {
          en: "I spend quality time in order to strengthen our bond.",
          bn: "আমি আমাদের বন্ধন শক্তিশালী করার জন্য মানসম্মত সময় কাটাই।",
          slotValues: { ACTION: "spend quality time in order to strengthen our bond" },
          topicArea: "relationships",
        },
      ],
      formality: "formal",
      difficulty: "intermediate",
      usageNote:
        "'In order to' is more formal than simple 'to'. Use it in writing and formal contexts for clarity.",
      usageNote_bn:
        "'In order to' সাধারণ 'to'-এর চেয়ে বেশি আনুষ্ঠানিক। স্পষ্টতার জন্য লেখালেখি এবং আনুষ্ঠানিক প্রসঙ্গে ব্যবহার করুন।",
      combinableWith: ["J4.1"],
      banglaStructureMap:
        "আমি (Subject) + [PURPOSE] (Purpose) + করার জন্য (Formal purpose marker) + [MAIN ACTION] (Main verb) + করি (Verb ending)",
    },
    {
      id: "J4.3",
      formula: "I [ACTION] so that [CLAUSE]",
      formula_bn: "আমি [কাজ] করি যাতে [উপবাক্য]",
      patternName: "Purpose with 'so that'",
      patternName_bn: "'so that' দিয়ে উদ্দেশ্য",
      slots: [
        {
          name: "ACTION",
          description: "The main action",
          description_bn: "মূল কাজ",
          acceptedTypes: ["verb_phrase"],
          examples: ["speak slowly", "set an alarm", "save money"],
        },
        {
          name: "CLAUSE",
          description: "The intended result",
          description_bn: "কাঙ্ক্ষিত ফলাফল",
          acceptedTypes: ["clause"],
          examples: [
            "everyone can understand",
            "I won't be late",
            "I can buy a house",
          ],
        },
      ],
      examples: [
        {
          en: "I speak slowly so that everyone can understand.",
          bn: "আমি ধীরে কথা বলি যাতে সবাই বুঝতে পারে।",
          slotValues: { ACTION: "speak slowly", CLAUSE: "everyone can understand" },
          topicArea: "education",
        },
        {
          en: "I set an alarm so that I won't be late.",
          bn: "আমি অ্যালার্ম দিই যাতে দেরি না হয়।",
          slotValues: { ACTION: "set an alarm", CLAUSE: "I won't be late" },
          topicArea: "daily_life",
        },
        {
          en: "I save money so that I can buy a house.",
          bn: "আমি টাকা জমাই যাতে বাড়ি কিনতে পারি।",
          slotValues: { ACTION: "save money", CLAUSE: "I can buy a house" },
          topicArea: "shopping",
        },
        {
          en: "She studies every day so that she can get good grades.",
          bn: "সে প্রতিদিন পড়াশোনা করে যাতে ভালো গ্রেড পেতে পারে।",
          slotValues: { ACTION: "studies every day", CLAUSE: "she can get good grades" },
          topicArea: "education",
        },
        {
          en: "I exercise regularly so that I can stay fit.",
          bn: "আমি নিয়মিত ব্যায়াম করি যাতে ফিট থাকতে পারি।",
          slotValues: { ACTION: "exercise regularly", CLAUSE: "I can stay fit" },
          topicArea: "health",
        },
        {
          en: "He left early so that he could catch the train.",
          bn: "সে তাড়াতাড়ি রওনা দিয়েছে যাতে ট্রেন ধরতে পারে।",
          slotValues: { ACTION: "left early", CLAUSE: "he could catch the train" },
          topicArea: "travel",
        },
        {
          en: "I work extra hours so that my team can meet the deadline.",
          bn: "আমি অতিরিক্ত ঘণ্টা কাজ করি যাতে আমার দল সময়সীমা পূরণ করতে পারে।",
          slotValues: { ACTION: "work extra hours", CLAUSE: "my team can meet the deadline" },
          topicArea: "work",
        },
        {
          en: "I cook extra food so that there is enough for everyone.",
          bn: "আমি বেশি রান্না করি যাতে সবার জন্য যথেষ্ট হয়।",
          slotValues: { ACTION: "cook extra food", CLAUSE: "there is enough for everyone" },
          topicArea: "food",
        },
        {
          en: "I call regularly so that they don't worry.",
          bn: "আমি নিয়মিত ফোন করি যাতে তারা চিন্তা না করে।",
          slotValues: { ACTION: "call regularly", CLAUSE: "they don't worry" },
          topicArea: "relationships",
        },
        {
          en: "I take vitamins so that I don't get sick easily.",
          bn: "আমি ভিটামিন খাই যাতে সহজে অসুস্থ না হই।",
          slotValues: { ACTION: "take vitamins", CLAUSE: "I don't get sick easily" },
          topicArea: "health",
        },
        {
          en: "I read the reviews so that I can make a good choice.",
          bn: "আমি রিভিউ পড়ি যাতে ভালো পছন্দ করতে পারি।",
          slotValues: { ACTION: "read the reviews", CLAUSE: "I can make a good choice" },
          topicArea: "shopping",
        },
        {
          en: "She writes notes so that she can remember later.",
          bn: "সে নোট লেখে যাতে পরে মনে রাখতে পারে।",
          slotValues: { ACTION: "writes notes", CLAUSE: "she can remember later" },
          topicArea: "education",
        },
        {
          en: "I pack early so that I don't forget anything.",
          bn: "আমি আগে গুছিয়ে রাখি যাতে কিছু ভুলে না যাই।",
          slotValues: { ACTION: "pack early", CLAUSE: "I don't forget anything" },
          topicArea: "travel",
        },
        {
          en: "I keep the documents organized so that I can find them quickly.",
          bn: "আমি নথিপত্র সাজিয়ে রাখি যাতে দ্রুত খুঁজে পেতে পারি।",
          slotValues: { ACTION: "keep the documents organized", CLAUSE: "I can find them quickly" },
          topicArea: "work",
        },
        {
          en: "I smile so that others feel comfortable around me.",
          bn: "আমি হাসি যাতে অন্যরা আমার কাছে স্বচ্ছন্দ বোধ করে।",
          slotValues: { ACTION: "smile", CLAUSE: "others feel comfortable around me" },
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'So that' is used when the purpose involves a different subject or uses modals like 'can', 'could', 'will'.",
      usageNote_bn:
        "'So that' ব্যবহৃত হয় যখন উদ্দেশ্যে একটি ভিন্ন কর্তা জড়িত থাকে বা 'can', 'could', 'will'-এর মতো মোডাল ব্যবহৃত হয়।",
      combinableWith: ["J4.1"],
      banglaStructureMap:
        "আমি (Subject) + [ACTION] (Main verb) + যাতে (Purpose marker) + [CLAUSE] (Purpose clause)",
    },
    {
      id: "J4.4",
      formula: "The purpose of [THING] is to [ACTION]",
      formula_bn: "[জিনিসের] উদ্দেশ্য হলো [কাজ] করা",
      patternName: "Stating Purpose Formally",
      patternName_bn: "আনুষ্ঠানিকভাবে উদ্দেশ্য বলা",
      slots: [
        {
          name: "THING",
          description: "The thing whose purpose is being stated",
          description_bn: "যে জিনিসের উদ্দেশ্য বলা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["this meeting", "education", "this exercise"],
        },
        {
          name: "ACTION",
          description: "The purpose or goal",
          description_bn: "উদ্দেশ্য বা লক্ষ্য",
          acceptedTypes: ["verb_phrase"],
          examples: ["discuss the budget", "prepare for the future", "strengthen your muscles"],
        },
      ],
      examples: [
        {
          en: "The purpose of this meeting is to discuss the budget.",
          bn: "এই সভার উদ্দেশ্য হলো বাজেট নিয়ে আলোচনা করা।",
          slotValues: { THING: "this meeting", ACTION: "discuss the budget" },
          topicArea: "work",
        },
        {
          en: "The purpose of education is to prepare for the future.",
          bn: "শিক্ষার উদ্দেশ্য হলো ভবিষ্যতের জন্য প্রস্তুতি নেওয়া।",
          slotValues: { THING: "education", ACTION: "prepare for the future" },
          topicArea: "education",
        },
        {
          en: "The purpose of this exercise is to strengthen your muscles.",
          bn: "এই ব্যায়ামের উদ্দেশ্য হলো আপনার পেশী শক্তিশালী করা।",
          slotValues: { THING: "this exercise", ACTION: "strengthen your muscles" },
          topicArea: "health",
        },
        {
          en: "The purpose of this app is to help you learn English.",
          bn: "এই অ্যাপের উদ্দেশ্য হলো আপনাকে ইংরেজি শিখতে সাহায্য করা।",
          slotValues: { THING: "this app", ACTION: "help you learn English" },
          topicArea: "education",
        },
        {
          en: "The purpose of the trip is to explore new places.",
          bn: "ভ্রমণের উদ্দেশ্য হলো নতুন জায়গা অন্বেষণ করা।",
          slotValues: { THING: "the trip", ACTION: "explore new places" },
          topicArea: "travel",
        },
        {
          en: "The purpose of this warranty is to protect the buyer.",
          bn: "এই ওয়ারেন্টির উদ্দেশ্য হলো ক্রেতাকে সুরক্ষিত করা।",
          slotValues: { THING: "this warranty", ACTION: "protect the buyer" },
          topicArea: "shopping",
        },
        {
          en: "The purpose of this diet is to control blood sugar.",
          bn: "এই ডায়েটের উদ্দেশ্য হলো রক্তে চিনি নিয়ন্ত্রণ করা।",
          slotValues: { THING: "this diet", ACTION: "control blood sugar" },
          topicArea: "health",
        },
        {
          en: "The purpose of seasoning is to enhance the flavor.",
          bn: "মশলা দেওয়ার উদ্দেশ্য হলো স্বাদ বাড়ানো।",
          slotValues: { THING: "seasoning", ACTION: "enhance the flavor" },
          topicArea: "food",
        },
        {
          en: "The purpose of this call is to update you on the project.",
          bn: "এই কলের উদ্দেশ্য হলো প্রকল্প সম্পর্কে আপনাকে আপডেট দেওয়া।",
          slotValues: { THING: "this call", ACTION: "update you on the project" },
          topicArea: "work",
        },
        {
          en: "The purpose of the ceremony is to celebrate their union.",
          bn: "অনুষ্ঠানের উদ্দেশ্য হলো তাদের মিলন উদযাপন করা।",
          slotValues: { THING: "the ceremony", ACTION: "celebrate their union" },
          topicArea: "relationships",
        },
        {
          en: "The purpose of feedback is to help you improve.",
          bn: "প্রতিক্রিয়ার উদ্দেশ্য হলো আপনাকে উন্নতি করতে সাহায্য করা।",
          slotValues: { THING: "feedback", ACTION: "help you improve" },
          topicArea: "work",
        },
        {
          en: "The purpose of a passport is to identify travelers.",
          bn: "পাসপোর্টের উদ্দেশ্য হলো ভ্রমণকারীদের শনাক্ত করা।",
          slotValues: { THING: "a passport", ACTION: "identify travelers" },
          topicArea: "travel",
        },
        {
          en: "The purpose of homework is to reinforce learning.",
          bn: "বাড়ির কাজের উদ্দেশ্য হলো শিক্ষা শক্তিশালী করা।",
          slotValues: { THING: "homework", ACTION: "reinforce learning" },
          topicArea: "education",
        },
        {
          en: "The purpose of this sale is to clear old stock.",
          bn: "এই সেলের উদ্দেশ্য হলো পুরোনো স্টক পরিষ্কার করা।",
          slotValues: { THING: "this sale", ACTION: "clear old stock" },
          topicArea: "shopping",
        },
        {
          en: "The purpose of cooking slowly is to develop deeper flavors.",
          bn: "ধীরে রান্না করার উদ্দেশ্য হলো গভীর স্বাদ তৈরি করা।",
          slotValues: { THING: "cooking slowly", ACTION: "develop deeper flavors" },
          topicArea: "food",
        },
      ],
      formality: "formal",
      difficulty: "intermediate",
      usageNote:
        "This pattern is formal and commonly used in presentations, official documents, and academic writing.",
      usageNote_bn:
        "এই প্যাটার্ন আনুষ্ঠানিক এবং সাধারণত উপস্থাপনা, সরকারি নথি এবং একাডেমিক লেখায় ব্যবহৃত হয়।",
      combinableWith: ["J4.2"],
      banglaStructureMap:
        "[THING]-এর (Possessive) + উদ্দেশ্য হলো (Purpose introducer) + [ACTION] (Purpose verb) + করা (Verb ending)",
    },
    {
      id: "J4.5",
      formula: "[THING] is meant for [DOING]",
      formula_bn: "[জিনিস] [কাজ করার] জন্য তৈরি",
      patternName: "Intended Purpose",
      patternName_bn: "অভিপ্রেত উদ্দেশ্য",
      slots: [
        {
          name: "THING",
          description: "The item whose purpose is being described",
          description_bn: "যে জিনিসের উদ্দেশ্য বর্ণনা করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["This tool", "This room", "This course"],
        },
        {
          name: "DOING",
          description: "The intended use (gerund or noun)",
          description_bn: "অভিপ্রেত ব্যবহার (জেরান্ড বা বিশেষ্য)",
          acceptedTypes: ["gerund", "noun", "noun_phrase"],
          examples: ["cutting", "reading", "beginners"],
        },
      ],
      examples: [
        {
          en: "This tool is meant for cutting wood.",
          bn: "এই যন্ত্রটি কাঠ কাটার জন্য তৈরি।",
          slotValues: { THING: "This tool", DOING: "cutting wood" },
          topicArea: "daily_life",
        },
        {
          en: "This room is meant for reading.",
          bn: "এই ঘরটি পড়ার জন্য তৈরি।",
          slotValues: { THING: "This room", DOING: "reading" },
          topicArea: "education",
        },
        {
          en: "This course is meant for beginners.",
          bn: "এই কোর্সটি শুরুকারীদের জন্য তৈরি।",
          slotValues: { THING: "This course", DOING: "beginners" },
          topicArea: "education",
        },
        {
          en: "This medicine is meant for headaches.",
          bn: "এই ওষুধটি মাথাব্যথার জন্য তৈরি।",
          slotValues: { THING: "This medicine", DOING: "headaches" },
          topicArea: "health",
        },
        {
          en: "This lane is meant for cycling.",
          bn: "এই লেনটি সাইকেল চালানোর জন্য তৈরি।",
          slotValues: { THING: "This lane", DOING: "cycling" },
          topicArea: "travel",
        },
        {
          en: "This bag is meant for carrying laptops.",
          bn: "এই ব্যাগটি ল্যাপটপ বহন করার জন্য তৈরি।",
          slotValues: { THING: "This bag", DOING: "carrying laptops" },
          topicArea: "shopping",
        },
        {
          en: "This knife is meant for slicing bread.",
          bn: "এই ছুরিটি রুটি কাটার জন্য তৈরি।",
          slotValues: { THING: "This knife", DOING: "slicing bread" },
          topicArea: "food",
        },
        {
          en: "This office is meant for client meetings.",
          bn: "এই অফিসটি ক্লায়েন্ট মিটিংয়ের জন্য তৈরি।",
          slotValues: { THING: "This office", DOING: "client meetings" },
          topicArea: "work",
        },
        {
          en: "This gift is meant for showing appreciation.",
          bn: "এই উপহারটি কৃতজ্ঞতা প্রকাশের জন্য তৈরি।",
          slotValues: { THING: "This gift", DOING: "showing appreciation" },
          topicArea: "relationships",
        },
        {
          en: "This cream is meant for sensitive skin.",
          bn: "এই ক্রিমটি সংবেদনশীল ত্বকের জন্য তৈরি।",
          slotValues: { THING: "This cream", DOING: "sensitive skin" },
          topicArea: "health",
        },
        {
          en: "This app is meant for tracking expenses.",
          bn: "এই অ্যাপটি খরচ ট্র্যাক করার জন্য তৈরি।",
          slotValues: { THING: "This app", DOING: "tracking expenses" },
          topicArea: "daily_life",
        },
        {
          en: "This section is meant for advanced students.",
          bn: "এই অংশটি উন্নত ছাত্রদের জন্য তৈরি।",
          slotValues: { THING: "This section", DOING: "advanced students" },
          topicArea: "education",
        },
        {
          en: "This pan is meant for deep frying.",
          bn: "এই প্যানটি ডিপ ফ্রাই করার জন্য তৈরি।",
          slotValues: { THING: "This pan", DOING: "deep frying" },
          topicArea: "food",
        },
        {
          en: "This area is meant for parking only.",
          bn: "এই এলাকাটি শুধুমাত্র পার্কিংয়ের জন্য তৈরি।",
          slotValues: { THING: "This area", DOING: "parking only" },
          topicArea: "travel",
        },
        {
          en: "This software is meant for project management.",
          bn: "এই সফটওয়্যারটি প্রকল্প ব্যবস্থাপনার জন্য তৈরি।",
          slotValues: { THING: "This software", DOING: "project management" },
          topicArea: "work",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Is meant for' describes the intended purpose or use of something. It can be followed by a gerund or a noun.",
      usageNote_bn:
        "'Is meant for' কোনো কিছুর অভিপ্রেত উদ্দেশ্য বা ব্যবহার বর্ণনা করে। এর পরে একটি জেরান্ড বা বিশেষ্য আসতে পারে।",
      combinableWith: ["J4.4"],
      banglaStructureMap:
        "[THING] (Subject) + [DOING] (Purpose) + এর জন্য (Purpose marker) + তৈরি (Predicate)",
    },
  ],
};
