import { PatternCategory } from "@/types/pattern";

export const categoryJ5: PatternCategory = {
  id: "J5",
  slug: "giving-examples",
  name: "Giving Examples",
  name_bn: "উদাহরণ দেওয়া",
  description:
    "Learn how to give examples and illustrate points using common English patterns.",
  description_bn:
    "সাধারণ ইংরেজি প্যাটার্ন ব্যবহার করে উদাহরণ দিতে এবং বিষয় ব্যাখ্যা করতে শিখুন।",
  icon: "📋",
  group: "J",
  groupName: "Explaining, Reasoning & Conditions",
  groupName_bn: "ব্যাখ্যা, যুক্তি এবং শর্ত",
  difficulty: "intermediate",
  patterns: [
    {
      id: "J5.1",
      formula: "For example, [EXAMPLE]",
      formula_bn: "উদাহরণস্বরূপ, [উদাহরণ]",
      patternName: "Standard Example",
      patternName_bn: "সাধারণ উদাহরণ",
      slots: [
        {
          name: "EXAMPLE",
          description: "A specific example to illustrate a point",
          description_bn: "একটি বিষয় ব্যাখ্যা করার জন্য একটি নির্দিষ্ট উদাহরণ",
          acceptedTypes: ["clause", "noun_phrase"],
          examples: [
            "you can take a bus or a train",
            "swimming is a great exercise",
            "Japan is known for its technology",
          ],
        },
      ],
      examples: [
        {
          en: "There are many ways to travel. For example, you can take a bus or a train.",
          bn: "ভ্রমণের অনেক উপায় আছে। উদাহরণস্বরূপ, আপনি বাস বা ট্রেনে যেতে পারেন।",
          slotValues: { EXAMPLE: "you can take a bus or a train" },
          topicArea: "travel",
        },
        {
          en: "Exercise has many benefits. For example, it reduces stress.",
          bn: "ব্যায়ামের অনেক উপকারিতা আছে। উদাহরণস্বরূপ, এটি মানসিক চাপ কমায়।",
          slotValues: { EXAMPLE: "it reduces stress" },
          topicArea: "health",
        },
        {
          en: "Bangladesh has many beautiful places. For example, Cox's Bazar has the longest beach.",
          bn: "বাংলাদেশে অনেক সুন্দর জায়গা আছে। উদাহরণস্বরূপ, কক্সবাজারে দীর্ঘতম সমুদ্র সৈকত আছে।",
          slotValues: { EXAMPLE: "Cox's Bazar has the longest beach" },
          topicArea: "travel",
        },
        {
          en: "There are many healthy foods. For example, fruits and vegetables are very nutritious.",
          bn: "অনেক স্বাস্থ্যকর খাবার আছে। উদাহরণস্বরূপ, ফল এবং সবজি খুব পুষ্টিকর।",
          slotValues: { EXAMPLE: "fruits and vegetables are very nutritious" },
          topicArea: "food",
        },
        {
          en: "Technology helps us every day. For example, we can shop online from home.",
          bn: "প্রযুক্তি প্রতিদিন আমাদের সাহায্য করে। উদাহরণস্বরূপ, আমরা বাড়ি থেকে অনলাইনে কেনাকাটা করতে পারি।",
          slotValues: { EXAMPLE: "we can shop online from home" },
          topicArea: "shopping",
        },
        {
          en: "There are many ways to learn. For example, you can watch videos or read books.",
          bn: "শেখার অনেক উপায় আছে। উদাহরণস্বরূপ, আপনি ভিডিও দেখতে পারেন বা বই পড়তে পারেন।",
          slotValues: { EXAMPLE: "you can watch videos or read books" },
          topicArea: "education",
        },
        {
          en: "Good habits lead to success. For example, waking up early helps you be more productive.",
          bn: "ভালো অভ্যাস সাফল্যের দিকে নিয়ে যায়। উদাহরণস্বরূপ, তাড়াতাড়ি ঘুম থেকে ওঠা বেশি উৎপাদনশীল হতে সাহায্য করে।",
          slotValues: { EXAMPLE: "waking up early helps you be more productive" },
          topicArea: "daily_life",
        },
        {
          en: "Communication is key at work. For example, clear emails prevent misunderstandings.",
          bn: "কর্মক্ষেত্রে যোগাযোগ মূল বিষয়। উদাহরণস্বরূপ, স্পষ্ট ইমেইল ভুল বোঝাবুঝি প্রতিরোধ করে।",
          slotValues: { EXAMPLE: "clear emails prevent misunderstandings" },
          topicArea: "work",
        },
        {
          en: "Small gestures matter in relationships. For example, a simple thank you can brighten someone's day.",
          bn: "সম্পর্কে ছোট অঙ্গভঙ্গি গুরুত্বপূর্ণ। উদাহরণস্বরূপ, একটি সাধারণ ধন্যবাদ কারো দিন উজ্জ্বল করতে পারে।",
          slotValues: { EXAMPLE: "a simple thank you can brighten someone's day" },
          topicArea: "relationships",
        },
        {
          en: "There are many ways to save money. For example, cooking at home is cheaper than eating out.",
          bn: "টাকা বাঁচানোর অনেক উপায় আছে। উদাহরণস্বরূপ, বাড়িতে রান্না করা বাইরে খাওয়ার চেয়ে সস্তা।",
          slotValues: { EXAMPLE: "cooking at home is cheaper than eating out" },
          topicArea: "food",
        },
        {
          en: "Some countries are very advanced. For example, Japan is known for its technology.",
          bn: "কিছু দেশ খুব উন্নত। উদাহরণস্বরূপ, জাপান তার প্রযুক্তির জন্য পরিচিত।",
          slotValues: { EXAMPLE: "Japan is known for its technology" },
          topicArea: "education",
        },
        {
          en: "Teamwork makes a difference. For example, our last project succeeded because we all contributed.",
          bn: "দলগত কাজ পার্থক্য তৈরি করে। উদাহরণস্বরূপ, আমাদের শেষ প্রকল্প সফল হয়েছে কারণ আমরা সবাই অবদান রেখেছি।",
          slotValues: { EXAMPLE: "our last project succeeded because we all contributed" },
          topicArea: "work",
        },
        {
          en: "Walking has many benefits. For example, it improves heart health.",
          bn: "হাঁটার অনেক উপকারিতা আছে। উদাহরণস্বরূপ, এটি হৃদরোগের স্বাস্থ্য উন্নত করে।",
          slotValues: { EXAMPLE: "it improves heart health" },
          topicArea: "health",
        },
        {
          en: "Online stores have great deals. For example, you can find up to 50% off during festivals.",
          bn: "অনলাইন দোকানে দারুণ অফার থাকে। উদাহরণস্বরূপ, উৎসবের সময় ৫০% পর্যন্ত ছাড় পেতে পারেন।",
          slotValues: { EXAMPLE: "you can find up to 50% off during festivals" },
          topicArea: "shopping",
        },
        {
          en: "There are many fun activities to do on vacation. For example, you can go snorkeling or hiking.",
          bn: "ছুটিতে অনেক মজার কাজ করা যায়। উদাহরণস্বরূপ, আপনি স্নোরকেলিং বা হাইকিং করতে পারেন।",
          slotValues: { EXAMPLE: "you can go snorkeling or hiking" },
          topicArea: "travel",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "'For example' is the most common way to introduce an example. It can appear at the beginning of a sentence.",
      usageNote_bn:
        "'For example' উদাহরণ পরিচয় করিয়ে দেওয়ার সবচেয়ে সাধারণ উপায়। এটি বাক্যের শুরুতে আসতে পারে।",
      combinableWith: ["J5.2"],
      banglaStructureMap:
        "উদাহরণস্বরূপ (Example marker) + [EXAMPLE] (Example clause)",
    },
    {
      id: "J5.2",
      formula: "For instance, [EXAMPLE]",
      formula_bn: "যেমন, [উদাহরণ]",
      patternName: "Alternative Example Phrase",
      patternName_bn: "বিকল্প উদাহরণ বাক্যাংশ",
      slots: [
        {
          name: "EXAMPLE",
          description: "A specific example",
          description_bn: "একটি নির্দিষ্ট উদাহরণ",
          acceptedTypes: ["clause", "noun_phrase"],
          examples: [
            "last year's sales dropped significantly",
            "many students prefer online classes",
          ],
        },
      ],
      examples: [
        {
          en: "Many people work from home now. For instance, my sister works entirely online.",
          bn: "অনেক মানুষ এখন বাড়ি থেকে কাজ করে। যেমন, আমার বোন সম্পূর্ণ অনলাইনে কাজ করে।",
          slotValues: { EXAMPLE: "my sister works entirely online" },
          topicArea: "work",
        },
        {
          en: "There are many ways to stay healthy. For instance, you can walk for thirty minutes daily.",
          bn: "সুস্থ থাকার অনেক উপায় আছে। যেমন, আপনি প্রতিদিন ত্রিশ মিনিট হাঁটতে পারেন।",
          slotValues: { EXAMPLE: "you can walk for thirty minutes daily" },
          topicArea: "health",
        },
        {
          en: "Asian food is very diverse. For instance, Thai food is very different from Japanese food.",
          bn: "এশীয় খাবার খুব বৈচিত্র্যময়। যেমন, থাই খাবার জাপানি খাবার থেকে খুব আলাদা।",
          slotValues: { EXAMPLE: "Thai food is very different from Japanese food" },
          topicArea: "food",
        },
        {
          en: "Students learn differently. For instance, some prefer visual learning while others prefer reading.",
          bn: "ছাত্ররা ভিন্নভাবে শেখে। যেমন, কেউ কেউ ভিজ্যুয়াল শিক্ষা পছন্দ করে আবার কেউ কেউ পড়া পছন্দ করে।",
          slotValues: { EXAMPLE: "some prefer visual learning while others prefer reading" },
          topicArea: "education",
        },
        {
          en: "You can explore nature in many ways. For instance, you can go trekking or bird watching.",
          bn: "আপনি অনেক উপায়ে প্রকৃতি অন্বেষণ করতে পারেন। যেমন, আপনি ট্রেকিং বা পাখি দেখতে যেতে পারেন।",
          slotValues: { EXAMPLE: "you can go trekking or bird watching" },
          topicArea: "travel",
        },
        {
          en: "Online shopping has advantages. For instance, you can compare prices from different stores.",
          bn: "অনলাইন কেনাকাটার সুবিধা আছে। যেমন, আপনি বিভিন্ন দোকান থেকে দাম তুলনা করতে পারেন।",
          slotValues: { EXAMPLE: "you can compare prices from different stores" },
          topicArea: "shopping",
        },
        {
          en: "Kindness has many forms. For instance, listening to someone can be a great act of kindness.",
          bn: "দয়ার অনেক রূপ আছে। যেমন, কারো কথা শোনা দয়ার একটি দারুণ কাজ হতে পারে।",
          slotValues: { EXAMPLE: "listening to someone can be a great act of kindness" },
          topicArea: "relationships",
        },
        {
          en: "Technology has changed daily life. For instance, we can order food with just a few taps.",
          bn: "প্রযুক্তি দৈনন্দিন জীবন পরিবর্তন করেছে। যেমন, আমরা মাত্র কয়েকটি ট্যাপে খাবার অর্ডার করতে পারি।",
          slotValues: { EXAMPLE: "we can order food with just a few taps" },
          topicArea: "daily_life",
        },
        {
          en: "Languages share similarities. For instance, Bengali and Hindi have many common words.",
          bn: "ভাষাগুলোর মিল আছে। যেমন, বাংলা এবং হিন্দিতে অনেক সাধারণ শব্দ আছে।",
          slotValues: { EXAMPLE: "Bengali and Hindi have many common words" },
          topicArea: "education",
        },
        {
          en: "Stress management is important. For instance, deep breathing can help you calm down quickly.",
          bn: "মানসিক চাপ ব্যবস্থাপনা গুরুত্বপূর্ণ। যেমন, গভীর শ্বাস আপনাকে দ্রুত শান্ত হতে সাহায্য করতে পারে।",
          slotValues: { EXAMPLE: "deep breathing can help you calm down quickly" },
          topicArea: "health",
        },
        {
          en: "Collaboration is valuable at work. For instance, brainstorming sessions generate creative ideas.",
          bn: "কর্মক্ষেত্রে সহযোগিতা মূল্যবান। যেমন, ব্রেইনস্টর্মিং সেশন সৃজনশীল ধারণা তৈরি করে।",
          slotValues: { EXAMPLE: "brainstorming sessions generate creative ideas" },
          topicArea: "work",
        },
        {
          en: "Street food can be delicious. For instance, the fuchka in Dhaka is famous.",
          bn: "রাস্তার খাবার সুস্বাদু হতে পারে। যেমন, ঢাকার ফুচকা বিখ্যাত।",
          slotValues: { EXAMPLE: "the fuchka in Dhaka is famous" },
          topicArea: "food",
        },
        {
          en: "Budget travel is possible. For instance, you can stay in hostels to save money.",
          bn: "বাজেট ভ্রমণ সম্ভব। যেমন, আপনি টাকা বাঁচাতে হোস্টেলে থাকতে পারেন।",
          slotValues: { EXAMPLE: "you can stay in hostels to save money" },
          topicArea: "travel",
        },
        {
          en: "Good customer service matters. For instance, a friendly greeting makes customers feel welcome.",
          bn: "ভালো গ্রাহক সেবা গুরুত্বপূর্ণ। যেমন, একটি বন্ধুত্বপূর্ণ অভিবাদন গ্রাহকদের স্বাগত বোধ করায়।",
          slotValues: { EXAMPLE: "a friendly greeting makes customers feel welcome" },
          topicArea: "shopping",
        },
        {
          en: "Quality time strengthens bonds. For instance, having dinner together regularly helps families connect.",
          bn: "মানসম্মত সময় বন্ধন শক্তিশালী করে। যেমন, নিয়মিত একসাথে রাতের খাবার খাওয়া পরিবারকে সংযুক্ত রাখতে সাহায্য করে।",
          slotValues: { EXAMPLE: "having dinner together regularly helps families connect" },
          topicArea: "relationships",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "'For instance' is interchangeable with 'for example'. It's slightly more formal and used in writing.",
      usageNote_bn:
        "'For instance' 'for example'-এর সাথে বিনিময়যোগ্য। এটি কিছুটা বেশি আনুষ্ঠানিক এবং লেখায় ব্যবহৃত হয়।",
      combinableWith: ["J5.1"],
      banglaStructureMap:
        "যেমন (Example marker) + [EXAMPLE] (Example clause)",
    },
    {
      id: "J5.3",
      formula: "Such as [EXAMPLE]",
      formula_bn: "যেমন [উদাহরণ]",
      patternName: "Listing Examples",
      patternName_bn: "উদাহরণ তালিকা",
      slots: [
        {
          name: "EXAMPLE",
          description: "One or more examples in a list",
          description_bn: "একটি তালিকায় এক বা একাধিক উদাহরণ",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: [
            "apples, oranges, and bananas",
            "swimming and running",
            "Japan, Korea, and China",
          ],
        },
      ],
      examples: [
        {
          en: "I like fruits such as apples, oranges, and bananas.",
          bn: "আমি ফল পছন্দ করি যেমন আপেল, কমলা এবং কলা।",
          slotValues: { EXAMPLE: "apples, oranges, and bananas" },
          topicArea: "food",
        },
        {
          en: "Cardio exercises such as swimming and running are great for health.",
          bn: "কার্ডিও ব্যায়াম যেমন সাঁতার এবং দৌড়ানো স্বাস্থ্যের জন্য দারুণ।",
          slotValues: { EXAMPLE: "swimming and running" },
          topicArea: "health",
        },
        {
          en: "Asian countries such as Japan, Korea, and China attract many tourists.",
          bn: "এশীয় দেশ যেমন জাপান, কোরিয়া এবং চীন অনেক পর্যটকদের আকৃষ্ট করে।",
          slotValues: { EXAMPLE: "Japan, Korea, and China" },
          topicArea: "travel",
        },
        {
          en: "Skills such as communication and teamwork are essential at work.",
          bn: "দক্ষতা যেমন যোগাযোগ এবং দলগত কাজ কর্মক্ষেত্রে অপরিহার্য।",
          slotValues: { EXAMPLE: "communication and teamwork" },
          topicArea: "work",
        },
        {
          en: "Subjects such as math and science require regular practice.",
          bn: "বিষয় যেমন গণিত এবং বিজ্ঞানে নিয়মিত অনুশীলন প্রয়োজন।",
          slotValues: { EXAMPLE: "math and science" },
          topicArea: "education",
        },
        {
          en: "Electronics such as phones and laptops are on sale.",
          bn: "ইলেকট্রনিক্স যেমন ফোন এবং ল্যাপটপ সেলে আছে।",
          slotValues: { EXAMPLE: "phones and laptops" },
          topicArea: "shopping",
        },
        {
          en: "Daily habits such as reading and exercising keep you sharp.",
          bn: "দৈনিক অভ্যাস যেমন পড়া এবং ব্যায়াম আপনাকে সতেজ রাখে।",
          slotValues: { EXAMPLE: "reading and exercising" },
          topicArea: "daily_life",
        },
        {
          en: "Spices such as turmeric, cumin, and chili are common in Bangladeshi cooking.",
          bn: "মশলা যেমন হলুদ, জিরা এবং মরিচ বাংলাদেশি রান্নায় সাধারণ।",
          slotValues: { EXAMPLE: "turmeric, cumin, and chili" },
          topicArea: "food",
        },
        {
          en: "Values such as respect and honesty are important in relationships.",
          bn: "মূল্যবোধ যেমন সম্মান এবং সততা সম্পর্কে গুরুত্বপূর্ণ।",
          slotValues: { EXAMPLE: "respect and honesty" },
          topicArea: "relationships",
        },
        {
          en: "Activities such as yoga and meditation help reduce stress.",
          bn: "কার্যকলাপ যেমন যোগব্যায়াম এবং ধ্যান মানসিক চাপ কমাতে সাহায্য করে।",
          slotValues: { EXAMPLE: "yoga and meditation" },
          topicArea: "health",
        },
        {
          en: "Documents such as your passport and visa are required.",
          bn: "নথিপত্র যেমন আপনার পাসপোর্ট এবং ভিসা প্রয়োজন।",
          slotValues: { EXAMPLE: "your passport and visa" },
          topicArea: "travel",
        },
        {
          en: "Tools such as spreadsheets and calendars help you stay organized.",
          bn: "সরঞ্জাম যেমন স্প্রেডশিট এবং ক্যালেন্ডার আপনাকে সংগঠিত থাকতে সাহায্য করে।",
          slotValues: { EXAMPLE: "spreadsheets and calendars" },
          topicArea: "work",
        },
        {
          en: "Languages such as English and Mandarin are widely spoken.",
          bn: "ভাষা যেমন ইংরেজি এবং ম্যান্ডারিন ব্যাপকভাবে কথ্য।",
          slotValues: { EXAMPLE: "English and Mandarin" },
          topicArea: "education",
        },
        {
          en: "Accessories such as bags and watches make great gifts.",
          bn: "আনুষাঙ্গিক যেমন ব্যাগ এবং ঘড়ি দারুণ উপহার হয়।",
          slotValues: { EXAMPLE: "bags and watches" },
          topicArea: "shopping",
        },
        {
          en: "Chores such as cleaning and cooking take up a lot of time.",
          bn: "ঘরের কাজ যেমন পরিষ্কার করা এবং রান্না অনেক সময় নেয়।",
          slotValues: { EXAMPLE: "cleaning and cooking" },
          topicArea: "daily_life",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "'Such as' is used mid-sentence to list examples. It directly follows the noun it exemplifies.",
      usageNote_bn:
        "'Such as' বাক্যের মাঝে উদাহরণ তালিকা করতে ব্যবহৃত হয়। এটি যে বিশেষ্যটির উদাহরণ দেয় তার পরে সরাসরি আসে।",
      combinableWith: ["J5.1"],
      banglaStructureMap:
        "[CATEGORY] (Category noun) + যেমন (Example marker) + [EXAMPLE] (Examples)",
    },
    {
      id: "J5.4",
      formula: "Take [THING] for example",
      formula_bn: "উদাহরণ হিসেবে [জিনিস] ধরো",
      patternName: "Highlighting a Specific Example",
      patternName_bn: "নির্দিষ্ট উদাহরণ তুলে ধরা",
      slots: [
        {
          name: "THING",
          description: "The specific example being highlighted",
          description_bn: "যে নির্দিষ্ট উদাহরণটি তুলে ধরা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["my friend Ahmed", "this phone", "Dhaka traffic"],
        },
      ],
      examples: [
        {
          en: "People can be very dedicated. Take my friend Ahmed for example. He works 12 hours a day.",
          bn: "মানুষ খুব নিবেদিত হতে পারে। উদাহরণ হিসেবে আমার বন্ধু আহমেদকে ধরো। সে দিনে ১২ ঘণ্টা কাজ করে।",
          slotValues: { THING: "my friend Ahmed" },
          topicArea: "work",
        },
        {
          en: "Technology is improving fast. Take this phone for example. It has more features than a computer.",
          bn: "প্রযুক্তি দ্রুত উন্নতি করছে। উদাহরণ হিসেবে এই ফোনটি ধরো। এতে কম্পিউটারের চেয়ে বেশি ফিচার আছে।",
          slotValues: { THING: "this phone" },
          topicArea: "shopping",
        },
        {
          en: "Traffic is a big problem. Take Dhaka for example. It takes hours to cross the city.",
          bn: "ট্রাফিক একটি বড় সমস্যা। উদাহরণ হিসেবে ঢাকাকে ধরো। শহর পার হতে ঘণ্টার পর ঘণ্টা লাগে।",
          slotValues: { THING: "Dhaka" },
          topicArea: "travel",
        },
        {
          en: "Education systems vary around the world. Take Finland for example. Their schools have no homework.",
          bn: "শিক্ষা ব্যবস্থা বিশ্বজুড়ে ভিন্ন। উদাহরণ হিসেবে ফিনল্যান্ডকে ধরো। তাদের স্কুলে বাড়ির কাজ নেই।",
          slotValues: { THING: "Finland" },
          topicArea: "education",
        },
        {
          en: "Street food can be amazing. Take Kolkata for example. The puchka there is legendary.",
          bn: "রাস্তার খাবার অসাধারণ হতে পারে। উদাহরণ হিসেবে কলকাতাকে ধরো। সেখানকার পুচকা কিংবদন্তি।",
          slotValues: { THING: "Kolkata" },
          topicArea: "food",
        },
        {
          en: "Small changes can improve health. Take walking for example. Just 30 minutes daily makes a big difference.",
          bn: "ছোট পরিবর্তন স্বাস্থ্য উন্নত করতে পারে। উদাহরণ হিসেবে হাঁটা ধরো। প্রতিদিন মাত্র ৩০ মিনিট বড় পার্থক্য তৈরি করে।",
          slotValues: { THING: "walking" },
          topicArea: "health",
        },
        {
          en: "True friends are rare. Take my best friend for example. She has been with me for 20 years.",
          bn: "সত্যিকারের বন্ধু বিরল। উদাহরণ হিসেবে আমার সেরা বন্ধুকে ধরো। সে ২০ বছর ধরে আমার সাথে আছে।",
          slotValues: { THING: "my best friend" },
          topicArea: "relationships",
        },
        {
          en: "Remote work is growing. Take IT companies for example. Most of them allow work from home now.",
          bn: "দূরবর্তী কাজ বাড়ছে। উদাহরণ হিসেবে আইটি কোম্পানিগুলো ধরো। তাদের বেশিরভাগ এখন বাড়ি থেকে কাজের অনুমতি দেয়।",
          slotValues: { THING: "IT companies" },
          topicArea: "work",
        },
        {
          en: "Natural beauty is everywhere. Take the Sundarbans for example. It's one of the most beautiful mangrove forests.",
          bn: "প্রাকৃতিক সৌন্দর্য সর্বত্র আছে। উদাহরণ হিসেবে সুন্দরবনকে ধরো। এটি সবচেয়ে সুন্দর ম্যানগ্রোভ বনগুলোর একটি।",
          slotValues: { THING: "the Sundarbans" },
          topicArea: "travel",
        },
        {
          en: "Prices keep rising. Take rice for example. It costs almost double what it did last year.",
          bn: "দাম বাড়তে থাকে। উদাহরণ হিসেবে চালকে ধরো। গত বছরের তুলনায় এর দাম প্রায় দ্বিগুণ।",
          slotValues: { THING: "rice" },
          topicArea: "food",
        },
        {
          en: "Self-study can be effective. Take online courses for example. Many people learn new skills through them.",
          bn: "স্ব-অধ্যয়ন কার্যকর হতে পারে। উদাহরণ হিসেবে অনলাইন কোর্সকে ধরো। অনেক মানুষ এর মাধ্যমে নতুন দক্ষতা শেখে।",
          slotValues: { THING: "online courses" },
          topicArea: "education",
        },
        {
          en: "Good products build trust. Take this brand for example. People keep coming back because of the quality.",
          bn: "ভালো পণ্য বিশ্বাস তৈরি করে। উদাহরণ হিসেবে এই ব্র্যান্ডকে ধরো। গুণমানের কারণে মানুষ বারবার ফিরে আসে।",
          slotValues: { THING: "this brand" },
          topicArea: "shopping",
        },
        {
          en: "Prevention is better than cure. Take vaccines for example. They protect millions of people every year.",
          bn: "প্রতিরোধ নিরাময়ের চেয়ে ভালো। উদাহরণ হিসেবে টিকাকে ধরো। এগুলো প্রতি বছর লক্ষ লক্ষ মানুষকে রক্ষা করে।",
          slotValues: { THING: "vaccines" },
          topicArea: "health",
        },
        {
          en: "Routines can be helpful. Take morning meditation for example. It sets a positive tone for the day.",
          bn: "রুটিন সহায়ক হতে পারে। উদাহরণ হিসেবে সকালের ধ্যানকে ধরো। এটি দিনের জন্য একটি ইতিবাচক সুর তৈরি করে।",
          slotValues: { THING: "morning meditation" },
          topicArea: "daily_life",
        },
        {
          en: "Patience is a virtue. Take parenting for example. It requires endless patience and love.",
          bn: "ধৈর্য একটি গুণ। উদাহরণ হিসেবে সন্তান লালন-পালনকে ধরো। এতে অসীম ধৈর্য এবং ভালোবাসা প্রয়োজন।",
          slotValues: { THING: "parenting" },
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Take...for example' is a conversational way to highlight a specific case. Very common in spoken English.",
      usageNote_bn:
        "'Take...for example' একটি নির্দিষ্ট ক্ষেত্র তুলে ধরার একটি কথোপকথনমূলক উপায়। কথ্য ইংরেজিতে খুবই সাধারণ।",
      combinableWith: ["J5.1"],
      banglaStructureMap:
        "উদাহরণ হিসেবে (Example marker) + [THING] (Specific example) + ধরো (Verb)",
    },
    {
      id: "J5.5",
      formula: "Including [EXAMPLE]",
      formula_bn: "সহ [উদাহরণ]",
      patternName: "Adding to a List",
      patternName_bn: "তালিকায় যোগ করা",
      slots: [
        {
          name: "EXAMPLE",
          description: "Items included in a larger group",
          description_bn: "একটি বড় গোষ্ঠীতে অন্তর্ভুক্ত আইটেম",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: [
            "English and French",
            "the manager",
            "weekends",
          ],
        },
      ],
      examples: [
        {
          en: "He speaks several languages, including English and French.",
          bn: "সে বেশ কয়েকটি ভাষায় কথা বলে, ইংরেজি এবং ফরাসি সহ।",
          slotValues: { EXAMPLE: "English and French" },
          topicArea: "education",
        },
        {
          en: "Everyone attended the event, including the manager.",
          bn: "সবাই অনুষ্ঠানে যোগ দিয়েছে, ম্যানেজার সহ।",
          slotValues: { EXAMPLE: "the manager" },
          topicArea: "work",
        },
        {
          en: "The restaurant is open every day, including weekends.",
          bn: "রেস্তোরাঁটি প্রতিদিন খোলা, সপ্তাহান্ত সহ।",
          slotValues: { EXAMPLE: "weekends" },
          topicArea: "food",
        },
        {
          en: "Many countries were represented, including Bangladesh and India.",
          bn: "অনেক দেশের প্রতিনিধিত্ব ছিল, বাংলাদেশ এবং ভারত সহ।",
          slotValues: { EXAMPLE: "Bangladesh and India" },
          topicArea: "travel",
        },
        {
          en: "The package includes many features, including free delivery.",
          bn: "প্যাকেজে অনেক ফিচার অন্তর্ভুক্ত, বিনামূল্যে ডেলিভারি সহ।",
          slotValues: { EXAMPLE: "free delivery" },
          topicArea: "shopping",
        },
        {
          en: "She has won many awards, including the best teacher award.",
          bn: "সে অনেক পুরস্কার জিতেছে, সেরা শিক্ষক পুরস্কার সহ।",
          slotValues: { EXAMPLE: "the best teacher award" },
          topicArea: "education",
        },
        {
          en: "The gym offers many classes, including yoga and pilates.",
          bn: "জিমটি অনেক ক্লাস দেয়, যোগব্যায়াম এবং পিলাটেস সহ।",
          slotValues: { EXAMPLE: "yoga and pilates" },
          topicArea: "health",
        },
        {
          en: "All family members came, including my grandmother.",
          bn: "সব পরিবারের সদস্যরা এসেছে, আমার দাদি সহ।",
          slotValues: { EXAMPLE: "my grandmother" },
          topicArea: "relationships",
        },
        {
          en: "The hotel provides many amenities, including a swimming pool.",
          bn: "হোটেলটি অনেক সুবিধা দেয়, সুইমিং পুল সহ।",
          slotValues: { EXAMPLE: "a swimming pool" },
          topicArea: "travel",
        },
        {
          en: "Many items were damaged, including the television.",
          bn: "অনেক জিনিস ক্ষতিগ্রস্ত হয়েছে, টেলিভিশন সহ।",
          slotValues: { EXAMPLE: "the television" },
          topicArea: "daily_life",
        },
        {
          en: "The team has many skilled members, including two engineers.",
          bn: "দলে অনেক দক্ষ সদস্য আছে, দুজন ইঞ্জিনিয়ার সহ।",
          slotValues: { EXAMPLE: "two engineers" },
          topicArea: "work",
        },
        {
          en: "The menu has many options, including vegetarian dishes.",
          bn: "মেনুতে অনেক বিকল্প আছে, নিরামিষ পদ সহ।",
          slotValues: { EXAMPLE: "vegetarian dishes" },
          topicArea: "food",
        },
        {
          en: "Several products are discounted, including shoes and bags.",
          bn: "বেশ কয়েকটি পণ্যে ছাড় আছে, জুতো এবং ব্যাগ সহ।",
          slotValues: { EXAMPLE: "shoes and bags" },
          topicArea: "shopping",
        },
        {
          en: "The plan covers many aspects, including nutrition and sleep.",
          bn: "পরিকল্পনাটি অনেক দিক কভার করে, পুষ্টি এবং ঘুম সহ।",
          slotValues: { EXAMPLE: "nutrition and sleep" },
          topicArea: "health",
        },
        {
          en: "Many people helped with the event, including my neighbors.",
          bn: "অনেক মানুষ অনুষ্ঠানে সাহায্য করেছে, আমার প্রতিবেশীরা সহ।",
          slotValues: { EXAMPLE: "my neighbors" },
          topicArea: "relationships",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "'Including' highlights specific items that are part of a larger group. Often used after a general statement.",
      usageNote_bn:
        "'Including' একটি বড় গোষ্ঠীর অংশ এমন নির্দিষ্ট আইটেম তুলে ধরে। প্রায়ই একটি সাধারণ বিবৃতির পরে ব্যবহৃত হয়।",
      combinableWith: ["J5.3"],
      banglaStructureMap:
        "[GENERAL STATEMENT] (Main clause) + সহ (Inclusion marker) + [EXAMPLE] (Specific items)",
    },
  ],
};
