import { PatternCategory } from "@/types/pattern";

export const categoryJ6: PatternCategory = {
  id: "J6",
  slug: "generalizing-specifying",
  name: "Generalizing & Specifying",
  name_bn: "সাধারণীকরণ এবং নির্দিষ্টকরণ",
  description:
    "Learn how to make general statements and then narrow down to specifics in English.",
  description_bn:
    "ইংরেজিতে সাধারণ বিবৃতি দিতে এবং তারপর নির্দিষ্ট বিষয়ে সংকুচিত করতে শিখুন।",
  icon: "🔍",
  group: "J",
  groupName: "Explaining, Reasoning & Conditions",
  groupName_bn: "ব্যাখ্যা, যুক্তি এবং শর্ত",
  difficulty: "intermediate",
  patterns: [
    {
      id: "J6.1",
      formula: "In general, [CLAUSE]",
      formula_bn: "সাধারণভাবে, [উপবাক্য]",
      patternName: "Making a General Statement",
      patternName_bn: "সাধারণ বিবৃতি দেওয়া",
      slots: [
        {
          name: "CLAUSE",
          description: "A broad, general statement",
          description_bn: "একটি ব্যাপক, সাধারণ বিবৃতি",
          acceptedTypes: ["clause"],
          examples: [
            "people prefer to shop online",
            "Bangladeshi food is spicy",
            "exercise is good for health",
          ],
        },
      ],
      examples: [
        {
          en: "In general, people prefer to shop online these days.",
          bn: "সাধারণভাবে, আজকাল মানুষ অনলাইনে কেনাকাটা করতে পছন্দ করে।",
          slotValues: { CLAUSE: "people prefer to shop online these days" },
          topicArea: "shopping",
        },
        {
          en: "In general, Bangladeshi food is spicy.",
          bn: "সাধারণভাবে, বাংলাদেশি খাবার ঝাল।",
          slotValues: { CLAUSE: "Bangladeshi food is spicy" },
          topicArea: "food",
        },
        {
          en: "In general, exercise is good for health.",
          bn: "সাধারণভাবে, ব্যায়াম স্বাস্থ্যের জন্য ভালো।",
          slotValues: { CLAUSE: "exercise is good for health" },
          topicArea: "health",
        },
        {
          en: "In general, students who study regularly perform better.",
          bn: "সাধারণভাবে, যে ছাত্ররা নিয়মিত পড়াশোনা করে তারা ভালো ফলাফল করে।",
          slotValues: { CLAUSE: "students who study regularly perform better" },
          topicArea: "education",
        },
        {
          en: "In general, traveling broadens your mind.",
          bn: "সাধারণভাবে, ভ্রমণ আপনার মনকে প্রশস্ত করে।",
          slotValues: { CLAUSE: "traveling broadens your mind" },
          topicArea: "travel",
        },
        {
          en: "In general, teamwork leads to better results.",
          bn: "সাধারণভাবে, দলগত কাজ ভালো ফলাফলের দিকে নিয়ে যায়।",
          slotValues: { CLAUSE: "teamwork leads to better results" },
          topicArea: "work",
        },
        {
          en: "In general, people are kind when you treat them well.",
          bn: "সাধারণভাবে, মানুষ দয়ালু হয় যখন আপনি তাদের সাথে ভালো ব্যবহার করেন।",
          slotValues: { CLAUSE: "people are kind when you treat them well" },
          topicArea: "relationships",
        },
        {
          en: "In general, morning is the best time to exercise.",
          bn: "সাধারণভাবে, সকাল ব্যায়ামের সেরা সময়।",
          slotValues: { CLAUSE: "morning is the best time to exercise" },
          topicArea: "health",
        },
        {
          en: "In general, homemade food is healthier than restaurant food.",
          bn: "সাধারণভাবে, ঘরে তৈরি খাবার রেস্তোরাঁর খাবারের চেয়ে বেশি স্বাস্থ্যকর।",
          slotValues: { CLAUSE: "homemade food is healthier than restaurant food" },
          topicArea: "food",
        },
        {
          en: "In general, early planning saves money on travel.",
          bn: "সাধারণভাবে, আগে থেকে পরিকল্পনা করলে ভ্রমণে টাকা বাঁচে।",
          slotValues: { CLAUSE: "early planning saves money on travel" },
          topicArea: "travel",
        },
        {
          en: "In general, reading improves your language skills.",
          bn: "সাধারণভাবে, পড়া আপনার ভাষা দক্ষতা উন্নত করে।",
          slotValues: { CLAUSE: "reading improves your language skills" },
          topicArea: "education",
        },
        {
          en: "In general, expensive products don't always mean better quality.",
          bn: "সাধারণভাবে, দামি পণ্য সবসময় ভালো মানের মানে নয়।",
          slotValues: { CLAUSE: "expensive products don't always mean better quality" },
          topicArea: "shopping",
        },
        {
          en: "In general, a good work-life balance leads to happiness.",
          bn: "সাধারণভাবে, ভালো কর্ম-জীবন ভারসাম্য সুখের দিকে নিয়ে যায়।",
          slotValues: { CLAUSE: "a good work-life balance leads to happiness" },
          topicArea: "work",
        },
        {
          en: "In general, children learn faster than adults.",
          bn: "সাধারণভাবে, শিশুরা প্রাপ্তবয়স্কদের চেয়ে দ্রুত শেখে।",
          slotValues: { CLAUSE: "children learn faster than adults" },
          topicArea: "daily_life",
        },
        {
          en: "In general, communication is the key to a strong relationship.",
          bn: "সাধারণভাবে, যোগাযোগ একটি শক্তিশালী সম্পর্কের চাবিকাঠি।",
          slotValues: { CLAUSE: "communication is the key to a strong relationship" },
          topicArea: "relationships",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "'In general' introduces a broad statement that is usually true. It acknowledges that there may be exceptions.",
      usageNote_bn:
        "'In general' একটি ব্যাপক বিবৃতি পরিচয় করিয়ে দেয় যা সাধারণত সত্য। এটি স্বীকার করে যে ব্যতিক্রম থাকতে পারে।",
      combinableWith: ["J6.3"],
      banglaStructureMap:
        "সাধারণভাবে (Generalizing marker) + [CLAUSE] (General statement)",
    },
    {
      id: "J6.2",
      formula: "Overall, [CLAUSE]",
      formula_bn: "সামগ্রিকভাবে, [উপবাক্য]",
      patternName: "Summarizing Overall",
      patternName_bn: "সামগ্রিক সংক্ষেপ",
      slots: [
        {
          name: "CLAUSE",
          description: "A summary or overall assessment",
          description_bn: "একটি সারসংক্ষেপ বা সামগ্রিক মূল্যায়ন",
          acceptedTypes: ["clause"],
          examples: [
            "it was a good experience",
            "the project was successful",
            "I am satisfied with the service",
          ],
        },
      ],
      examples: [
        {
          en: "Overall, it was a good experience.",
          bn: "সামগ্রিকভাবে, এটি একটি ভালো অভিজ্ঞতা ছিল।",
          slotValues: { CLAUSE: "it was a good experience" },
          topicArea: "daily_life",
        },
        {
          en: "Overall, the project was successful.",
          bn: "সামগ্রিকভাবে, প্রকল্পটি সফল ছিল।",
          slotValues: { CLAUSE: "the project was successful" },
          topicArea: "work",
        },
        {
          en: "Overall, I am satisfied with the service.",
          bn: "সামগ্রিকভাবে, আমি সেবায় সন্তুষ্ট।",
          slotValues: { CLAUSE: "I am satisfied with the service" },
          topicArea: "shopping",
        },
        {
          en: "Overall, the food was delicious.",
          bn: "সামগ্রিকভাবে, খাবার সুস্বাদু ছিল।",
          slotValues: { CLAUSE: "the food was delicious" },
          topicArea: "food",
        },
        {
          en: "Overall, the trip was worth every penny.",
          bn: "সামগ্রিকভাবে, ভ্রমণটি প্রতিটি পয়সার মূল্যবান ছিল।",
          slotValues: { CLAUSE: "the trip was worth every penny" },
          topicArea: "travel",
        },
        {
          en: "Overall, the course helped me a lot.",
          bn: "সামগ্রিকভাবে, কোর্সটি আমাকে অনেক সাহায্য করেছে।",
          slotValues: { CLAUSE: "the course helped me a lot" },
          topicArea: "education",
        },
        {
          en: "Overall, my health has improved this year.",
          bn: "সামগ্রিকভাবে, এই বছর আমার স্বাস্থ্যের উন্নতি হয়েছে।",
          slotValues: { CLAUSE: "my health has improved this year" },
          topicArea: "health",
        },
        {
          en: "Overall, the team performed very well.",
          bn: "সামগ্রিকভাবে, দলটি খুব ভালো পারফর্ম করেছে।",
          slotValues: { CLAUSE: "the team performed very well" },
          topicArea: "work",
        },
        {
          en: "Overall, I think the product is worth buying.",
          bn: "সামগ্রিকভাবে, আমি মনে করি পণ্যটি কেনার যোগ্য।",
          slotValues: { CLAUSE: "I think the product is worth buying" },
          topicArea: "shopping",
        },
        {
          en: "Overall, the event was well-organized.",
          bn: "সামগ্রিকভাবে, অনুষ্ঠানটি সুসংগঠিত ছিল।",
          slotValues: { CLAUSE: "the event was well-organized" },
          topicArea: "daily_life",
        },
        {
          en: "Overall, the students showed great improvement.",
          bn: "সামগ্রিকভাবে, ছাত্ররা দারুণ উন্নতি দেখিয়েছে।",
          slotValues: { CLAUSE: "the students showed great improvement" },
          topicArea: "education",
        },
        {
          en: "Overall, the restaurant offers good value for money.",
          bn: "সামগ্রিকভাবে, রেস্তোরাঁটি টাকার তুলনায় ভালো মূল্য দেয়।",
          slotValues: { CLAUSE: "the restaurant offers good value for money" },
          topicArea: "food",
        },
        {
          en: "Overall, the hotel met our expectations.",
          bn: "সামগ্রিকভাবে, হোটেলটি আমাদের প্রত্যাশা পূরণ করেছে।",
          slotValues: { CLAUSE: "the hotel met our expectations" },
          topicArea: "travel",
        },
        {
          en: "Overall, I feel much better after the treatment.",
          bn: "সামগ্রিকভাবে, চিকিৎসার পর আমি অনেক ভালো অনুভব করছি।",
          slotValues: { CLAUSE: "I feel much better after the treatment" },
          topicArea: "health",
        },
        {
          en: "Overall, we had a wonderful time together.",
          bn: "সামগ্রিকভাবে, আমরা একসাথে দারুণ সময় কাটিয়েছি।",
          slotValues: { CLAUSE: "we had a wonderful time together" },
          topicArea: "relationships",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "'Overall' is used to give a summary or final assessment. It considers everything together.",
      usageNote_bn:
        "'Overall' একটি সারসংক্ষেপ বা চূড়ান্ত মূল্যায়ন দিতে ব্যবহৃত হয়। এটি সব কিছু একসাথে বিবেচনা করে।",
      combinableWith: ["J6.1"],
      banglaStructureMap:
        "সামগ্রিকভাবে (Summary marker) + [CLAUSE] (Summary statement)",
    },
    {
      id: "J6.3",
      formula: "Specifically, [CLAUSE]",
      formula_bn: "নির্দিষ্টভাবে, [উপবাক্য]",
      patternName: "Being Specific",
      patternName_bn: "নির্দিষ্ট হওয়া",
      slots: [
        {
          name: "CLAUSE",
          description: "A specific detail or point",
          description_bn: "একটি নির্দিষ্ট বিবরণ বা বিষয়",
          acceptedTypes: ["clause"],
          examples: [
            "I need help with grammar",
            "the problem is in the budget",
            "I want the blue one",
          ],
        },
      ],
      examples: [
        {
          en: "I need help with my English. Specifically, I need help with grammar.",
          bn: "আমার ইংরেজিতে সাহায্য দরকার। নির্দিষ্টভাবে, আমার ব্যাকরণে সাহায্য দরকার।",
          slotValues: { CLAUSE: "I need help with grammar" },
          topicArea: "education",
        },
        {
          en: "The project has some issues. Specifically, the problem is in the budget.",
          bn: "প্রকল্পে কিছু সমস্যা আছে। নির্দিষ্টভাবে, সমস্যাটি বাজেটে।",
          slotValues: { CLAUSE: "the problem is in the budget" },
          topicArea: "work",
        },
        {
          en: "I want a phone. Specifically, I want the blue one with 128GB storage.",
          bn: "আমি একটি ফোন চাই। নির্দিষ্টভাবে, আমি ১২৮জিবি স্টোরেজ সহ নীলটি চাই।",
          slotValues: { CLAUSE: "I want the blue one with 128GB storage" },
          topicArea: "shopping",
        },
        {
          en: "I want to visit Asia. Specifically, I want to go to Thailand.",
          bn: "আমি এশিয়া ভ্রমণ করতে চাই। নির্দিষ্টভাবে, আমি থাইল্যান্ডে যেতে চাই।",
          slotValues: { CLAUSE: "I want to go to Thailand" },
          topicArea: "travel",
        },
        {
          en: "I have a health concern. Specifically, I have been having back pain.",
          bn: "আমার একটি স্বাস্থ্য সমস্যা আছে। নির্দিষ্টভাবে, আমার পিঠে ব্যথা হচ্ছে।",
          slotValues: { CLAUSE: "I have been having back pain" },
          topicArea: "health",
        },
        {
          en: "The food needs improvement. Specifically, the rice was undercooked.",
          bn: "খাবারের উন্নতি দরকার। নির্দিষ্টভাবে, ভাত কম সেদ্ধ ছিল।",
          slotValues: { CLAUSE: "the rice was undercooked" },
          topicArea: "food",
        },
        {
          en: "I want to improve our relationship. Specifically, I want us to communicate more.",
          bn: "আমি আমাদের সম্পর্ক উন্নত করতে চাই। নির্দিষ্টভাবে, আমি চাই আমরা আরও বেশি যোগাযোগ করি।",
          slotValues: { CLAUSE: "I want us to communicate more" },
          topicArea: "relationships",
        },
        {
          en: "I need some changes at work. Specifically, I need a more flexible schedule.",
          bn: "আমার কাজে কিছু পরিবর্তন দরকার। নির্দিষ্টভাবে, আমার আরও নমনীয় সময়সূচি দরকার।",
          slotValues: { CLAUSE: "I need a more flexible schedule" },
          topicArea: "work",
        },
        {
          en: "I'm looking for a good school. Specifically, one with a strong English program.",
          bn: "আমি একটি ভালো স্কুল খুঁজছি। নির্দিষ্টভাবে, একটি শক্তিশালী ইংরেজি প্রোগ্রামসহ।",
          slotValues: { CLAUSE: "one with a strong English program" },
          topicArea: "education",
        },
        {
          en: "I want to buy a jacket. Specifically, a waterproof one for hiking.",
          bn: "আমি একটি জ্যাকেট কিনতে চাই। নির্দিষ্টভাবে, হাইকিংয়ের জন্য একটি জলরোধী।",
          slotValues: { CLAUSE: "a waterproof one for hiking" },
          topicArea: "shopping",
        },
        {
          en: "I enjoy cooking. Specifically, I love making desserts.",
          bn: "আমি রান্না উপভোগ করি। নির্দিষ্টভাবে, আমি মিষ্টি তৈরি করতে ভালোবাসি।",
          slotValues: { CLAUSE: "I love making desserts" },
          topicArea: "food",
        },
        {
          en: "I need to exercise more. Specifically, I should focus on cardio.",
          bn: "আমার আরও ব্যায়াম করা দরকার। নির্দিষ্টভাবে, আমার কার্ডিওতে মনোযোগ দেওয়া উচিত।",
          slotValues: { CLAUSE: "I should focus on cardio" },
          topicArea: "health",
        },
        {
          en: "The trip was amazing. Specifically, the sunset cruise was unforgettable.",
          bn: "ভ্রমণটি অসাধারণ ছিল। নির্দিষ্টভাবে, সূর্যাস্তের ক্রুজটি অবিস্মরণীয় ছিল।",
          slotValues: { CLAUSE: "the sunset cruise was unforgettable" },
          topicArea: "travel",
        },
        {
          en: "We need to improve. Specifically, we need better coordination between teams.",
          bn: "আমাদের উন্নতি করতে হবে। নির্দিষ্টভাবে, দলগুলোর মধ্যে আরও ভালো সমন্বয় দরকার।",
          slotValues: { CLAUSE: "we need better coordination between teams" },
          topicArea: "work",
        },
        {
          en: "I appreciate my friends. Specifically, I value their honesty the most.",
          bn: "আমি আমার বন্ধুদের প্রশংসা করি। নির্দিষ্টভাবে, আমি তাদের সততাকে সবচেয়ে বেশি মূল্য দিই।",
          slotValues: { CLAUSE: "I value their honesty the most" },
          topicArea: "relationships",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "'Specifically' narrows down from a general topic to a particular point. It adds precision to your statement.",
      usageNote_bn:
        "'Specifically' একটি সাধারণ বিষয় থেকে একটি নির্দিষ্ট বিষয়ে সংকুচিত করে। এটি আপনার বিবৃতিতে নির্ভুলতা যোগ করে।",
      combinableWith: ["J6.1"],
      banglaStructureMap:
        "নির্দিষ্টভাবে (Specifying marker) + [CLAUSE] (Specific detail)",
    },
    {
      id: "J6.4",
      formula: "In particular, [CLAUSE]",
      formula_bn: "বিশেষ করে, [উপবাক্য]",
      patternName: "Highlighting a Particular Point",
      patternName_bn: "একটি নির্দিষ্ট বিষয় তুলে ধরা",
      slots: [
        {
          name: "CLAUSE",
          description: "The particular point being highlighted",
          description_bn: "যে নির্দিষ্ট বিষয়টি তুলে ধরা হচ্ছে",
          acceptedTypes: ["clause"],
          examples: [
            "the customer service was excellent",
            "chapter three was very informative",
            "the dessert was outstanding",
          ],
        },
      ],
      examples: [
        {
          en: "The hotel was great. In particular, the customer service was excellent.",
          bn: "হোটেলটি দারুণ ছিল। বিশেষ করে, গ্রাহক সেবা চমৎকার ছিল।",
          slotValues: { CLAUSE: "the customer service was excellent" },
          topicArea: "travel",
        },
        {
          en: "The book was useful. In particular, chapter three was very informative.",
          bn: "বইটি উপকারী ছিল। বিশেষ করে, তৃতীয় অধ্যায় খুব তথ্যপূর্ণ ছিল।",
          slotValues: { CLAUSE: "chapter three was very informative" },
          topicArea: "education",
        },
        {
          en: "The dinner was wonderful. In particular, the dessert was outstanding.",
          bn: "রাতের খাবার দারুণ ছিল। বিশেষ করে, মিষ্টান্নটি অসাধারণ ছিল।",
          slotValues: { CLAUSE: "the dessert was outstanding" },
          topicArea: "food",
        },
        {
          en: "I enjoyed the trip. In particular, the boat ride was amazing.",
          bn: "আমি ভ্রমণটি উপভোগ করেছি। বিশেষ করে, নৌকা ভ্রমণটি অসাধারণ ছিল।",
          slotValues: { CLAUSE: "the boat ride was amazing" },
          topicArea: "travel",
        },
        {
          en: "The meeting was productive. In particular, the brainstorming session was helpful.",
          bn: "সভাটি উৎপাদনশীল ছিল। বিশেষ করে, ব্রেইনস্টর্মিং সেশনটি সহায়ক ছিল।",
          slotValues: { CLAUSE: "the brainstorming session was helpful" },
          topicArea: "work",
        },
        {
          en: "The treatment helped. In particular, the physiotherapy made a big difference.",
          bn: "চিকিৎসা সাহায্য করেছে। বিশেষ করে, ফিজিওথেরাপি বড় পার্থক্য তৈরি করেছে।",
          slotValues: { CLAUSE: "the physiotherapy made a big difference" },
          topicArea: "health",
        },
        {
          en: "The store has good products. In particular, their organic section is impressive.",
          bn: "দোকানে ভালো পণ্য আছে। বিশেষ করে, তাদের জৈব সেকশন চিত্তাকর্ষক।",
          slotValues: { CLAUSE: "their organic section is impressive" },
          topicArea: "shopping",
        },
        {
          en: "I love my family. In particular, my mother has always been my biggest supporter.",
          bn: "আমি আমার পরিবারকে ভালোবাসি। বিশেষ করে, আমার মা সবসময় আমার সবচেয়ে বড় সমর্থক।",
          slotValues: { CLAUSE: "my mother has always been my biggest supporter" },
          topicArea: "relationships",
        },
        {
          en: "The app has many features. In particular, the voice recognition is very accurate.",
          bn: "অ্যাপটিতে অনেক ফিচার আছে। বিশেষ করে, ভয়েস রিকগনিশন খুব নির্ভুল।",
          slotValues: { CLAUSE: "the voice recognition is very accurate" },
          topicArea: "education",
        },
        {
          en: "The weather was nice all week. In particular, Saturday was perfect for a picnic.",
          bn: "সারা সপ্তাহ আবহাওয়া ভালো ছিল। বিশেষ করে, শনিবার পিকনিকের জন্য নিখুঁত ছিল।",
          slotValues: { CLAUSE: "Saturday was perfect for a picnic" },
          topicArea: "daily_life",
        },
        {
          en: "The menu was varied. In particular, the seafood options were excellent.",
          bn: "মেনুতে বৈচিত্র্য ছিল। বিশেষ করে, সামুদ্রিক খাবারের বিকল্পগুলো চমৎকার ছিল।",
          slotValues: { CLAUSE: "the seafood options were excellent" },
          topicArea: "food",
        },
        {
          en: "My health has improved. In particular, my blood pressure is now normal.",
          bn: "আমার স্বাস্থ্যের উন্নতি হয়েছে। বিশেষ করে, আমার রক্তচাপ এখন স্বাভাবিক।",
          slotValues: { CLAUSE: "my blood pressure is now normal" },
          topicArea: "health",
        },
        {
          en: "The company is doing well. In particular, the marketing department exceeded targets.",
          bn: "কোম্পানি ভালো করছে। বিশেষ করে, মার্কেটিং বিভাগ লক্ষ্যমাত্রা ছাড়িয়েছে।",
          slotValues: { CLAUSE: "the marketing department exceeded targets" },
          topicArea: "work",
        },
        {
          en: "I like this brand. In particular, their winter collection is very stylish.",
          bn: "আমি এই ব্র্যান্ড পছন্দ করি। বিশেষ করে, তাদের শীতকালীন কালেকশন খুব স্টাইলিশ।",
          slotValues: { CLAUSE: "their winter collection is very stylish" },
          topicArea: "shopping",
        },
        {
          en: "I admire many qualities in people. In particular, I respect those who are honest.",
          bn: "আমি মানুষের অনেক গুণ প্রশংসা করি। বিশেষ করে, আমি তাদের সম্মান করি যারা সৎ।",
          slotValues: { CLAUSE: "I respect those who are honest" },
          topicArea: "relationships",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "'In particular' highlights one specific item or aspect from a larger group. It's similar to 'especially'.",
      usageNote_bn:
        "'In particular' একটি বড় গোষ্ঠী থেকে একটি নির্দিষ্ট আইটেম বা দিক তুলে ধরে। এটি 'especially'-এর মতো।",
      combinableWith: ["J6.3"],
      banglaStructureMap:
        "বিশেষ করে (Particular marker) + [CLAUSE] (Highlighted detail)",
    },
    {
      id: "J6.5",
      formula: "Especially [THING]",
      formula_bn: "বিশেষত [জিনিস]",
      patternName: "Emphasizing One Item",
      patternName_bn: "একটি আইটেমে জোর দেওয়া",
      slots: [
        {
          name: "THING",
          description: "The item being emphasized",
          description_bn: "যে আইটেমটির উপর জোর দেওয়া হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase", "clause"],
          examples: [
            "during winter",
            "the biryani",
            "when you are stressed",
          ],
        },
      ],
      examples: [
        {
          en: "I love hot drinks, especially during winter.",
          bn: "আমি গরম পানীয় ভালোবাসি, বিশেষত শীতকালে।",
          slotValues: { THING: "during winter" },
          topicArea: "food",
        },
        {
          en: "The food here is great, especially the biryani.",
          bn: "এখানকার খাবার দারুণ, বিশেষত বিরিয়ানি।",
          slotValues: { THING: "the biryani" },
          topicArea: "food",
        },
        {
          en: "Exercise is important, especially when you are stressed.",
          bn: "ব্যায়াম গুরুত্বপূর্ণ, বিশেষত যখন আপনি চাপে থাকেন।",
          slotValues: { THING: "when you are stressed" },
          topicArea: "health",
        },
        {
          en: "I enjoy traveling, especially to hill stations.",
          bn: "আমি ভ্রমণ উপভোগ করি, বিশেষত পাহাড়ি এলাকায়।",
          slotValues: { THING: "to hill stations" },
          topicArea: "travel",
        },
        {
          en: "Punctuality matters at work, especially during meetings.",
          bn: "কর্মক্ষেত্রে সময়ানুবর্তিতা গুরুত্বপূর্ণ, বিশেষত সভার সময়।",
          slotValues: { THING: "during meetings" },
          topicArea: "work",
        },
        {
          en: "Reading is helpful, especially for improving vocabulary.",
          bn: "পড়া সহায়ক, বিশেষত শব্দভান্ডার উন্নতির জন্য।",
          slotValues: { THING: "for improving vocabulary" },
          topicArea: "education",
        },
        {
          en: "I appreciate honest people, especially those who are kind.",
          bn: "আমি সৎ মানুষদের প্রশংসা করি, বিশেষত যারা দয়ালু।",
          slotValues: { THING: "those who are kind" },
          topicArea: "relationships",
        },
        {
          en: "This store has good deals, especially on electronics.",
          bn: "এই দোকানে ভালো দর আছে, বিশেষত ইলেকট্রনিক্সে।",
          slotValues: { THING: "on electronics" },
          topicArea: "shopping",
        },
        {
          en: "Sleep is essential, especially for children.",
          bn: "ঘুম অপরিহার্য, বিশেষত শিশুদের জন্য।",
          slotValues: { THING: "for children" },
          topicArea: "health",
        },
        {
          en: "Mornings are beautiful here, especially in spring.",
          bn: "এখানকার সকাল সুন্দর, বিশেষত বসন্তে।",
          slotValues: { THING: "in spring" },
          topicArea: "daily_life",
        },
        {
          en: "I miss my family, especially during holidays.",
          bn: "আমি আমার পরিবারকে মিস করি, বিশেষত ছুটির সময়।",
          slotValues: { THING: "during holidays" },
          topicArea: "relationships",
        },
        {
          en: "This city is beautiful, especially at night.",
          bn: "এই শহরটি সুন্দর, বিশেষত রাতে।",
          slotValues: { THING: "at night" },
          topicArea: "travel",
        },
        {
          en: "Deadlines can be stressful, especially at the end of the quarter.",
          bn: "সময়সীমা চাপের হতে পারে, বিশেষত ত্রৈমাসিকের শেষে।",
          slotValues: { THING: "at the end of the quarter" },
          topicArea: "work",
        },
        {
          en: "Practice helps, especially with speaking skills.",
          bn: "অনুশীলন সাহায্য করে, বিশেষত কথা বলার দক্ষতায়।",
          slotValues: { THING: "with speaking skills" },
          topicArea: "education",
        },
        {
          en: "I love sweets, especially rasgulla.",
          bn: "আমি মিষ্টি ভালোবাসি, বিশেষত রসগোল্লা।",
          slotValues: { THING: "rasgulla" },
          topicArea: "food",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Especially' emphasizes one thing above others. It comes after the general statement and before the specific item.",
      usageNote_bn:
        "'Especially' অন্যদের উপরে একটি জিনিসের উপর জোর দেয়। এটি সাধারণ বিবৃতির পরে এবং নির্দিষ্ট আইটেমের আগে আসে।",
      combinableWith: ["J6.4"],
      banglaStructureMap:
        "[GENERAL STATEMENT] (Main clause) + বিশেষত (Emphasis marker) + [THING] (Specific item)",
    },
  ],
};
