import { PatternCategory } from "@/types/pattern";

export const categoryJ9: PatternCategory = {
  id: "J9",
  slug: "unreal-past-conditions",
  name: "Unreal Past Conditions",
  name_bn: "অবাস্তব অতীত শর্ত",
  description:
    "Learn how to talk about imaginary past situations and regrets using third conditional patterns.",
  description_bn:
    "তৃতীয় শর্তাধীন প্যাটার্ন ব্যবহার করে কাল্পনিক অতীত পরিস্থিতি এবং অনুতাপ সম্পর্কে কথা বলতে শিখুন।",
  icon: "⏪",
  group: "J",
  groupName: "Explaining, Reasoning & Conditions",
  groupName_bn: "ব্যাখ্যা, যুক্তি ও শর্ত",
  difficulty: "advanced",
  patterns: [
    {
      id: "J9.1",
      formula: "If I had [PP], I would have [PP]",
      formula_bn: "আমি যদি [অতীত কৃদন্ত] করতাম, আমি [অতীত কৃদন্ত] করতাম",
      patternName: "Third Conditional",
      patternName_bn: "তৃতীয় শর্তাধীন",
      slots: [
        {
          name: "PP",
          description: "Past participle forms",
          description_bn: "অতীত কৃদন্ত রূপ",
          acceptedTypes: ["past_participle", "verb_phrase"],
          examples: ["studied harder", "known about it", "saved more money"],
        },
      ],
      examples: [
        {
          en: "If I had studied harder, I would have passed the exam.",
          bn: "আমি যদি আরো কঠোর পড়াশোনা করতাম, পরীক্ষায় পাশ করতাম।",
          slotValues: { PP: "studied harder" },
          topicArea: "education",
        },
        {
          en: "If I had known about the sale, I would have bought it.",
          bn: "আমি যদি সেলের কথা জানতাম, কিনে নিতাম।",
          slotValues: { PP: "known about the sale" },
          topicArea: "shopping",
        },
        {
          en: "If I had saved more money, I would have traveled to Europe.",
          bn: "আমি যদি আরো টাকা জমাতাম, ইউরোপ ভ্রমণ করতাম।",
          slotValues: { PP: "saved more money" },
          topicArea: "travel",
        },
        {
          en: "If I had woken up earlier, I would have caught the train.",
          bn: "আমি যদি আরো আগে উঠতাম, ট্রেন ধরতে পারতাম।",
          slotValues: { PP: "woken up earlier" },
          topicArea: "daily_life",
        },
        {
          en: "If I had taken the medicine on time, I would have recovered faster.",
          bn: "আমি যদি সময়মতো ওষুধ খেতাম, দ্রুত সুস্থ হতাম।",
          slotValues: { PP: "taken the medicine on time" },
          topicArea: "health",
        },
        {
          en: "If I had prepared better, I would have gotten the promotion.",
          bn: "আমি যদি আরো ভালো প্রস্তুতি নিতাম, পদোন্নতি পেতাম।",
          slotValues: { PP: "prepared better" },
          topicArea: "work",
        },
        {
          en: "If I had listened to her, I would have avoided the mistake.",
          bn: "আমি যদি তার কথা শুনতাম, ভুলটা এড়াতে পারতাম।",
          slotValues: { PP: "listened to her" },
          topicArea: "relationships",
        },
        {
          en: "If I had added more spices, the food would have tasted better.",
          bn: "আমি যদি আরো মসলা দিতাম, খাবারের স্বাদ আরো ভালো হতো।",
          slotValues: { PP: "added more spices" },
          topicArea: "food",
        },
        {
          en: "If I had booked earlier, I would have gotten a cheaper ticket.",
          bn: "আমি যদি আগে বুক করতাম, সস্তা টিকিট পেতাম।",
          slotValues: { PP: "booked earlier" },
          topicArea: "travel",
        },
        {
          en: "If I had practiced more, I would have spoken better English.",
          bn: "আমি যদি আরো অনুশীলন করতাম, আরো ভালো ইংরেজি বলতে পারতাম।",
          slotValues: { PP: "practiced more" },
          topicArea: "education",
        },
        {
          en: "If I had checked the reviews, I would have chosen a different product.",
          bn: "আমি যদি রিভিউ দেখতাম, অন্য একটি পণ্য বেছে নিতাম।",
          slotValues: { PP: "checked the reviews" },
          topicArea: "shopping",
        },
        {
          en: "If I had exercised regularly, I would have been in better shape.",
          bn: "আমি যদি নিয়মিত ব্যায়াম করতাম, আরো ভালো শারীরিক অবস্থায় থাকতাম।",
          slotValues: { PP: "exercised regularly" },
          topicArea: "health",
        },
        {
          en: "If I had applied on time, I would have gotten the job.",
          bn: "আমি যদি সময়মতো আবেদন করতাম, চাকরিটা পেতাম।",
          slotValues: { PP: "applied on time" },
          topicArea: "work",
        },
        {
          en: "If I had been more understanding, we would have stayed together.",
          bn: "আমি যদি আরো বোঝাপড়া করতাম, আমরা একসাথে থাকতাম।",
          slotValues: { PP: "been more understanding" },
          topicArea: "relationships",
        },
        {
          en: "If I had followed the recipe exactly, the cake would have turned out better.",
          bn: "আমি যদি রেসিপি ঠিকভাবে অনুসরণ করতাম, কেকটি আরো ভালো হতো।",
          slotValues: { PP: "followed the recipe exactly" },
          topicArea: "food",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
      usageNote:
        "The third conditional talks about unreal past situations. 'If + had + PP' in the condition, 'would have + PP' in the result.",
      usageNote_bn:
        "তৃতীয় শর্তাধীন অবাস্তব অতীত পরিস্থিতি সম্পর্কে কথা বলে। শর্তে 'If + had + PP', ফলাফলে 'would have + PP'।",
      combinableWith: ["J9.2"],
      banglaStructureMap:
        "আমি যদি (If I had) + [PP] (Past participle) + করতাম (Had done) + আমি (I) + [PP] (Past participle) + করতাম (Would have done)",
    },
    {
      id: "J9.2",
      formula: "I wouldn't have [PP] if...",
      formula_bn: "আমি [অতীত কৃদন্ত] করতাম না যদি...",
      patternName: "Negative Third Conditional",
      patternName_bn: "নেতিবাচক তৃতীয় শর্তাধীন",
      slots: [
        {
          name: "PP",
          description: "Past participle of the action",
          description_bn: "কাজের অতীত কৃদন্ত",
          acceptedTypes: ["past_participle", "verb_phrase"],
          examples: ["been late", "failed", "gotten sick"],
        },
      ],
      examples: [
        {
          en: "I wouldn't have been late if the traffic wasn't so bad.",
          bn: "যানজট এত খারাপ না হলে আমি দেরি করতাম না।",
          slotValues: { PP: "been late" },
          topicArea: "daily_life",
        },
        {
          en: "I wouldn't have failed if I had studied properly.",
          bn: "ঠিকমতো পড়াশোনা করলে আমি ফেল করতাম না।",
          slotValues: { PP: "failed" },
          topicArea: "education",
        },
        {
          en: "I wouldn't have gotten sick if I had worn warm clothes.",
          bn: "গরম কাপড় পরলে আমি অসুস্থ হতাম না।",
          slotValues: { PP: "gotten sick" },
          topicArea: "health",
        },
        {
          en: "I wouldn't have bought it if I had known the price.",
          bn: "দাম জানলে আমি কিনতাম না।",
          slotValues: { PP: "bought it" },
          topicArea: "shopping",
        },
        {
          en: "I wouldn't have missed the flight if I had left earlier.",
          bn: "আগে বের হলে আমি ফ্লাইট মিস করতাম না।",
          slotValues: { PP: "missed the flight" },
          topicArea: "travel",
        },
        {
          en: "I wouldn't have quit if the manager had been fair.",
          bn: "ম্যানেজার ন্যায্য হলে আমি চাকরি ছাড়তাম না।",
          slotValues: { PP: "quit" },
          topicArea: "work",
        },
        {
          en: "I wouldn't have argued if she had told me the truth.",
          bn: "সে সত্য বললে আমি তর্ক করতাম না।",
          slotValues: { PP: "argued" },
          topicArea: "relationships",
        },
        {
          en: "I wouldn't have burned the food if I had set the timer.",
          bn: "টাইমার সেট করলে আমি খাবার পুড়িয়ে ফেলতাম না।",
          slotValues: { PP: "burned the food" },
          topicArea: "food",
        },
        {
          en: "I wouldn't have wasted money if I had compared prices.",
          bn: "দাম তুলনা করলে আমি টাকা নষ্ট করতাম না।",
          slotValues: { PP: "wasted money" },
          topicArea: "shopping",
        },
        {
          en: "I wouldn't have struggled if I had learned English earlier.",
          bn: "আগে ইংরেজি শিখলে আমি কষ্ট পেতাম না।",
          slotValues: { PP: "struggled" },
          topicArea: "education",
        },
        {
          en: "I wouldn't have gotten lost if I had followed the map.",
          bn: "মানচিত্র অনুসরণ করলে আমি পথ হারাতাম না।",
          slotValues: { PP: "gotten lost" },
          topicArea: "travel",
        },
        {
          en: "I wouldn't have had surgery if I had taken care of my health.",
          bn: "স্বাস্থ্যের যত্ন নিলে আমার অস্ত্রোপচার লাগত না।",
          slotValues: { PP: "had surgery" },
          topicArea: "health",
        },
        {
          en: "I wouldn't have resigned if they had given me a raise.",
          bn: "তারা বেতন বাড়ালে আমি পদত্যাগ করতাম না।",
          slotValues: { PP: "resigned" },
          topicArea: "work",
        },
        {
          en: "I wouldn't have hurt her feelings if I had chosen my words carefully.",
          bn: "সাবধানে কথা বললে আমি তার মনে কষ্ট দিতাম না।",
          slotValues: { PP: "hurt her feelings" },
          topicArea: "relationships",
        },
        {
          en: "I wouldn't have overcooked the rice if I had watched it carefully.",
          bn: "সাবধানে দেখলে আমি ভাত বেশি সিদ্ধ করতাম না।",
          slotValues: { PP: "overcooked the rice" },
          topicArea: "food",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
      usageNote:
        "The negative form 'wouldn't have' expresses that something bad happened because the condition wasn't met.",
      usageNote_bn:
        "নেতিবাচক রূপ 'wouldn't have' প্রকাশ করে যে শর্ত পূরণ না হওয়ায় খারাপ কিছু ঘটেছে।",
      combinableWith: ["J9.1"],
      banglaStructureMap:
        "আমি (I) + [PP] (Past participle) + করতাম না (Wouldn't have) + যদি (If) + ... (Past condition)",
    },
    {
      id: "J9.3",
      formula: "If only I had [PP]",
      formula_bn: "যদি আমি [অতীত কৃদন্ত] করতাম!",
      patternName: "Expressing Regret",
      patternName_bn: "অনুতাপ প্রকাশ",
      slots: [
        {
          name: "PP",
          description: "Past participle of the regretted action",
          description_bn: "অনুতাপের কাজের অতীত কৃদন্ত",
          acceptedTypes: ["past_participle", "verb_phrase"],
          examples: ["listened to my parents", "started earlier", "been more careful"],
        },
      ],
      examples: [
        {
          en: "If only I had listened to my parents.",
          bn: "যদি আমি আমার বাবা-মায়ের কথা শুনতাম!",
          slotValues: { PP: "listened to my parents" },
          topicArea: "relationships",
        },
        {
          en: "If only I had started learning English earlier.",
          bn: "যদি আমি আগে ইংরেজি শেখা শুরু করতাম!",
          slotValues: { PP: "started learning English earlier" },
          topicArea: "education",
        },
        {
          en: "If only I had been more careful with my spending.",
          bn: "যদি আমি খরচে আরো সতর্ক হতাম!",
          slotValues: { PP: "been more careful with my spending" },
          topicArea: "shopping",
        },
        {
          en: "If only I had taken that job offer.",
          bn: "যদি আমি সেই চাকরির অফারটি নিতাম!",
          slotValues: { PP: "taken that job offer" },
          topicArea: "work",
        },
        {
          en: "If only I had visited my grandmother more often.",
          bn: "যদি আমি আরো বেশি আমার দাদিকে দেখতে যেতাম!",
          slotValues: { PP: "visited my grandmother more often" },
          topicArea: "relationships",
        },
        {
          en: "If only I had booked the hotel earlier.",
          bn: "যদি আমি আগে হোটেল বুক করতাম!",
          slotValues: { PP: "booked the hotel earlier" },
          topicArea: "travel",
        },
        {
          en: "If only I had eaten healthier when I was young.",
          bn: "যদি আমি ছোটবেলায় আরো স্বাস্থ্যকর খেতাম!",
          slotValues: { PP: "eaten healthier when I was young" },
          topicArea: "health",
        },
        {
          en: "If only I had learned to cook from my mother.",
          bn: "যদি আমি আমার মায়ের কাছ থেকে রান্না শিখতাম!",
          slotValues: { PP: "learned to cook from my mother" },
          topicArea: "food",
        },
        {
          en: "If only I had saved money from my first salary.",
          bn: "যদি আমি প্রথম বেতন থেকে টাকা জমাতাম!",
          slotValues: { PP: "saved money from my first salary" },
          topicArea: "daily_life",
        },
        {
          en: "If only I had studied for the test properly.",
          bn: "যদি আমি পরীক্ষার জন্য ঠিকমতো পড়তাম!",
          slotValues: { PP: "studied for the test properly" },
          topicArea: "education",
        },
        {
          en: "If only I had brought warmer clothes for the trip.",
          bn: "যদি আমি ভ্রমণের জন্য গরম কাপড় আনতাম!",
          slotValues: { PP: "brought warmer clothes for the trip" },
          topicArea: "travel",
        },
        {
          en: "If only I had gone to the doctor sooner.",
          bn: "যদি আমি আরো আগে ডাক্তারের কাছে যেতাম!",
          slotValues: { PP: "gone to the doctor sooner" },
          topicArea: "health",
        },
        {
          en: "If only I had applied for the scholarship.",
          bn: "যদি আমি বৃত্তির জন্য আবেদন করতাম!",
          slotValues: { PP: "applied for the scholarship" },
          topicArea: "work",
        },
        {
          en: "If only I had bought that property when it was cheap.",
          bn: "যদি আমি সস্তায় সেই জমি কিনতাম!",
          slotValues: { PP: "bought that property when it was cheap" },
          topicArea: "shopping",
        },
        {
          en: "If only I had tried my mother's recipe before she passed away.",
          bn: "যদি মায়ের চলে যাওয়ার আগে তার রেসিপি শিখে নিতাম!",
          slotValues: { PP: "tried my mother's recipe before she passed away" },
          topicArea: "food",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
      usageNote:
        "'If only I had...' expresses deep regret about something that didn't happen in the past. It's more emotional than the standard third conditional.",
      usageNote_bn:
        "'If only I had...' অতীতে না ঘটা কিছু সম্পর্কে গভীর অনুতাপ প্রকাশ করে। এটি সাধারণ তৃতীয় শর্তাধীনের চেয়ে বেশি আবেগপূর্ণ।",
      combinableWith: ["J9.1"],
      banglaStructureMap:
        "যদি (If only) + আমি (I) + [PP] (Past participle) + করতাম! (Had done - with regret!)",
    },
    {
      id: "J9.4",
      formula: "Things would have been different if...",
      formula_bn: "জিনিসগুলো আলাদা হতো যদি...",
      patternName: "Reflecting on Past",
      patternName_bn: "অতীত নিয়ে প্রতিফলন",
      slots: [],
      examples: [
        {
          en: "Things would have been different if I had taken that opportunity.",
          bn: "সেই সুযোগ নিলে জিনিসগুলো আলাদা হতো।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "Things would have been different if I had studied abroad.",
          bn: "বিদেশে পড়লে জিনিসগুলো আলাদা হতো।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "Things would have been different if we had moved to Dhaka earlier.",
          bn: "আগে ঢাকায় চলে আসলে জিনিসগুলো আলাদা হতো।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "Things would have been different if I had married someone else.",
          bn: "অন্য কাউকে বিয়ে করলে জিনিসগুলো আলাদা হতো।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "Things would have been different if I had saved money from the start.",
          bn: "শুরু থেকে টাকা জমালে জিনিসগুলো আলাদা হতো।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Things would have been different if I had eaten healthier.",
          bn: "স্বাস্থ্যকর খেলে জিনিসগুলো আলাদা হতো।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "Things would have been different if I had chosen a different career.",
          bn: "ভিন্ন ক্যারিয়ার বেছে নিলে জিনিসগুলো আলাদা হতো।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "Things would have been different if the shop had given a refund.",
          bn: "দোকান রিফান্ড দিলে জিনিসগুলো আলাদা হতো।",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "Things would have been different if I had learned cooking properly.",
          bn: "ঠিকভাবে রান্না শিখলে জিনিসগুলো আলাদা হতো।",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "Things would have been different if I had attended university.",
          bn: "বিশ্ববিদ্যালয়ে গেলে জিনিসগুলো আলাদা হতো।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "Things would have been different if we had communicated better.",
          bn: "আরো ভালো যোগাযোগ করলে জিনিসগুলো আলাদা হতো।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "Things would have been different if I had visited the doctor earlier.",
          bn: "আগে ডাক্তারের কাছে গেলে জিনিসগুলো আলাদা হতো।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "Things would have been different if I had traveled when I was young.",
          bn: "ছোটবেলায় ভ্রমণ করলে জিনিসগুলো আলাদা হতো।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "Things would have been different if my boss had been supportive.",
          bn: "আমার বস সহায়ক হলে জিনিসগুলো আলাদা হতো।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "Things would have been different if I had not wasted my time.",
          bn: "সময় নষ্ট না করলে জিনিসগুলো আলাদা হতো।",
          slotValues: {},
          topicArea: "daily_life",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
      usageNote:
        "'Things would have been different if...' is a reflective statement used to imagine how the past could have changed the present.",
      usageNote_bn:
        "'Things would have been different if...' একটি প্রতিফলনমূলক বিবৃতি যা কল্পনা করতে ব্যবহৃত হয় কিভাবে অতীত বর্তমানকে পরিবর্তন করতে পারত।",
      combinableWith: ["J9.1"],
      banglaStructureMap:
        "জিনিসগুলো আলাদা হতো (Things would have been different) + যদি (If) + ... (Past condition)",
    },
    {
      id: "J9.5",
      formula: "Had I [PP], I would have [PP]",
      formula_bn: "আমি [অতীত কৃদন্ত] করলে, আমি [অতীত কৃদন্ত] করতাম",
      patternName: "Formal Inverted Conditional",
      patternName_bn: "আনুষ্ঠানিক বিপরীত শর্তাধীন",
      slots: [
        {
          name: "PP",
          description: "Past participle forms",
          description_bn: "অতীত কৃদন্ত রূপ",
          acceptedTypes: ["past_participle", "verb_phrase"],
          examples: ["known", "arrived earlier", "been told"],
        },
      ],
      examples: [
        {
          en: "Had I known, I would have come earlier.",
          bn: "জানলে, আমি আরো আগে আসতাম।",
          slotValues: { PP: "known" },
          topicArea: "daily_life",
        },
        {
          en: "Had I arrived earlier, I would have met the professor.",
          bn: "আগে পৌঁছালে, আমি অধ্যাপকের সাথে দেখা করতাম।",
          slotValues: { PP: "arrived earlier" },
          topicArea: "education",
        },
        {
          en: "Had I been told about the delay, I would have changed my plans.",
          bn: "দেরির কথা জানানো হলে, আমি পরিকল্পনা পরিবর্তন করতাম।",
          slotValues: { PP: "been told about the delay" },
          topicArea: "travel",
        },
        {
          en: "Had I prepared the dish with less oil, it would have been healthier.",
          bn: "কম তেলে রান্না করলে, এটি আরো স্বাস্থ্যকর হতো।",
          slotValues: { PP: "prepared the dish with less oil" },
          topicArea: "food",
        },
        {
          en: "Had I negotiated better, I would have gotten a higher salary.",
          bn: "ভালো দরকষাকষি করলে, আরো বেশি বেতন পেতাম।",
          slotValues: { PP: "negotiated better" },
          topicArea: "work",
        },
        {
          en: "Had I seen the doctor sooner, the treatment would have been easier.",
          bn: "আগে ডাক্তারের কাছে গেলে, চিকিৎসা সহজ হতো।",
          slotValues: { PP: "seen the doctor sooner" },
          topicArea: "health",
        },
        {
          en: "Had I apologized immediately, she would have forgiven me.",
          bn: "সাথে সাথে ক্ষমা চাইলে, সে আমাকে ক্ষমা করত।",
          slotValues: { PP: "apologized immediately" },
          topicArea: "relationships",
        },
        {
          en: "Had I checked the price online, I would have saved money.",
          bn: "অনলাইনে দাম দেখলে, টাকা বাঁচাতে পারতাম।",
          slotValues: { PP: "checked the price online" },
          topicArea: "shopping",
        },
        {
          en: "Had I studied the grammar rules, I would have written a better essay.",
          bn: "ব্যাকরণের নিয়ম পড়লে, আরো ভালো প্রবন্ধ লিখতে পারতাম।",
          slotValues: { PP: "studied the grammar rules" },
          topicArea: "education",
        },
        {
          en: "Had I planned the trip properly, we would have had more fun.",
          bn: "ঠিকভাবে ভ্রমণ পরিকল্পনা করলে, আমরা আরো মজা পেতাম।",
          slotValues: { PP: "planned the trip properly" },
          topicArea: "travel",
        },
        {
          en: "Had I marinated the chicken longer, it would have been tastier.",
          bn: "মুরগি আরো বেশিক্ষণ মেরিনেট করলে, আরো সুস্বাদু হতো।",
          slotValues: { PP: "marinated the chicken longer" },
          topicArea: "food",
        },
        {
          en: "Had I been more patient, the outcome would have been better.",
          bn: "আরো ধৈর্যশীল হলে, ফলাফল আরো ভালো হতো।",
          slotValues: { PP: "been more patient" },
          topicArea: "relationships",
        },
        {
          en: "Had I joined the meeting on time, I would have understood the project.",
          bn: "সময়মতো মিটিংয়ে যোগ দিলে, প্রকল্পটি বুঝতে পারতাম।",
          slotValues: { PP: "joined the meeting on time" },
          topicArea: "work",
        },
        {
          en: "Had I taken vitamins, I might not have fallen ill.",
          bn: "ভিটামিন খেলে, হয়তো অসুস্থ হতাম না।",
          slotValues: { PP: "taken vitamins" },
          topicArea: "health",
        },
        {
          en: "Had I read the instructions, I would have assembled it correctly.",
          bn: "নির্দেশনা পড়লে, সঠিকভাবে জোড়া লাগাতে পারতাম।",
          slotValues: { PP: "read the instructions" },
          topicArea: "shopping",
        },
      ],
      formality: "formal",
      difficulty: "advanced",
      usageNote:
        "'Had I [PP]' is an inverted form of 'If I had [PP]'. It sounds more formal and literary. The 'if' is dropped and 'had' comes before the subject.",
      usageNote_bn:
        "'Had I [PP]' হলো 'If I had [PP]'-এর বিপরীত রূপ। এটি আরো আনুষ্ঠানিক এবং সাহিত্যিক শোনায়। 'if' বাদ দেওয়া হয় এবং 'had' কর্তার আগে আসে।",
      combinableWith: ["J9.1"],
      banglaStructureMap:
        "আমি (I) + [PP] (Past participle) + করলে (Had done - inverted) + আমি (I) + [PP] (Past participle) + করতাম (Would have done)",
    },
  ],
};
