import { PatternCategory } from "@/types/pattern";

export const categoryL1: PatternCategory = {
  id: "L1",
  slug: "time-prepositions",
  name: "Time Prepositions (At/In/On)",
  name_bn: "সময়ের অব্যয় (At/In/On)",
  description:
    "Master when to use at, in, and on with time expressions.",
  description_bn:
    "সময়ের প্রকাশে at, in, on এর সঠিক ব্যবহার শিখুন।",
  icon: "⏰",
  group: "L",
  groupName: "Time Expression Patterns",
  groupName_bn: "সময় প্রকাশের প্যাটার্ন",
  difficulty: "beginner",
  patterns: [
    {
      id: "L1.1",
      formula: "at [TIME]",
      formula_bn: "[সময়]-এ",
      patternName: "At + Specific Time",
      patternName_bn: "At + নির্দিষ্ট সময়",
      slots: [
        {
          name: "TIME",
          description: "Specific clock time or time point",
          description_bn: "নির্দিষ্ট ঘড়ির সময় বা সময়ের বিন্দু",
          acceptedTypes: ["time"],
          examples: ["5 o'clock", "noon", "midnight", "sunrise"],
        },
      ],
      examples: [
        { en: "The meeting is at 3 o'clock.", bn: "মিটিং ৩টায়।", slotValues: { TIME: "3 o'clock" } },
        { en: "I wake up at 6 a.m. every day.", bn: "আমি প্রতিদিন সকাল ৬টায় ঘুম থেকে উঠি।", slotValues: { TIME: "6 a.m." } },
        { en: "The train arrives at noon.", bn: "ট্রেন দুপুরে আসে।", slotValues: { TIME: "noon" } },
        { en: "She called me at midnight.", bn: "সে আমাকে মধ্যরাতে ফোন করেছিল।", slotValues: { TIME: "midnight" } },
        { en: "Lunch is at 12:30.", bn: "দুপুরের খাবার ১২:৩০-এ।", slotValues: { TIME: "12:30" } },
        { en: "The movie starts at 7 p.m.", bn: "মুভি সন্ধ্যা ৭টায় শুরু হয়।", slotValues: { TIME: "7 p.m." } },
        { en: "I'll meet you at 5 o'clock.", bn: "আমি তোমার সাথে ৫টায় দেখা করব।", slotValues: { TIME: "5 o'clock" } },
        { en: "The shop closes at 9 p.m.", bn: "দোকান রাত ৯টায় বন্ধ হয়।", slotValues: { TIME: "9 p.m." } },
        { en: "We eat dinner at 8 o'clock.", bn: "আমরা ৮টায় রাতের খাবার খাই।", slotValues: { TIME: "8 o'clock" } },
        { en: "The sun rises at dawn.", bn: "সূর্য ভোরে ওঠে।", slotValues: { TIME: "dawn" } },
        { en: "The class begins at 10 a.m.", bn: "ক্লাস সকাল ১০টায় শুরু হয়।", slotValues: { TIME: "10 a.m." } },
        { en: "I go to bed at 11 p.m.", bn: "আমি রাত ১১টায় ঘুমাতে যাই।", slotValues: { TIME: "11 p.m." } },
        { en: "The ceremony starts at sunset.", bn: "অনুষ্ঠান সূর্যাস্তে শুরু হয়।", slotValues: { TIME: "sunset" } },
        { en: "He always arrives at exactly 9 o'clock.", bn: "সে সবসময় ঠিক ৯টায় আসে।", slotValues: { TIME: "exactly 9 o'clock" } },
        { en: "The alarm rings at 5:30 a.m.", bn: "অ্যালার্ম সকাল ৫:৩০-এ বাজে।", slotValues: { TIME: "5:30 a.m." } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Use 'at' with specific clock times, noon, midnight, dawn, and sunset.",
      usageNote_bn:
        "নির্দিষ্ট ঘড়ির সময়, দুপুর, মধ্যরাত, ভোর এবং সূর্যাস্তের সাথে 'at' ব্যবহার করুন।",
    },
    {
      id: "L1.2",
      formula: "on [DAY/DATE]",
      formula_bn: "[দিন/তারিখ]-এ",
      patternName: "On + Day or Date",
      patternName_bn: "On + দিন বা তারিখ",
      slots: [
        {
          name: "DAY/DATE",
          description: "Day of the week or specific date",
          description_bn: "সপ্তাহের দিন বা নির্দিষ্ট তারিখ",
          acceptedTypes: ["time_expression"],
          examples: ["Monday", "March 5th", "my birthday", "Friday evening"],
        },
      ],
      examples: [
        { en: "The exam is on Monday.", bn: "পরীক্ষা সোমবারে।", slotValues: { "DAY/DATE": "Monday" } },
        { en: "I was born on March 15th.", bn: "আমি ১৫ই মার্চে জন্মেছিলাম।", slotValues: { "DAY/DATE": "March 15th" } },
        { en: "We have a party on Saturday.", bn: "শনিবারে আমাদের পার্টি আছে।", slotValues: { "DAY/DATE": "Saturday" } },
        { en: "The shop is closed on Sundays.", bn: "রবিবারে দোকান বন্ধ থাকে।", slotValues: { "DAY/DATE": "Sundays" } },
        { en: "I'll visit you on Friday.", bn: "আমি শুক্রবারে তোমার কাছে আসব।", slotValues: { "DAY/DATE": "Friday" } },
        { en: "School starts on September 1st.", bn: "স্কুল ১লা সেপ্টেম্বরে শুরু হয়।", slotValues: { "DAY/DATE": "September 1st" } },
        { en: "We got married on June 20th.", bn: "আমরা ২০শে জুনে বিয়ে করেছিলাম।", slotValues: { "DAY/DATE": "June 20th" } },
        { en: "The concert is on Wednesday evening.", bn: "কনসার্ট বুধবার সন্ধ্যায়।", slotValues: { "DAY/DATE": "Wednesday evening" } },
        { en: "I have a dentist appointment on Thursday.", bn: "বৃহস্পতিবারে আমার ডেন্টিস্টের অ্যাপয়েন্টমেন্ট আছে।", slotValues: { "DAY/DATE": "Thursday" } },
        { en: "The holiday falls on a Tuesday this year.", bn: "এই বছর ছুটি মঙ্গলবারে পড়েছে।", slotValues: { "DAY/DATE": "a Tuesday" } },
        { en: "We always go out on Friday nights.", bn: "আমরা সবসময় শুক্রবার রাতে বাইরে যাই।", slotValues: { "DAY/DATE": "Friday nights" } },
        { en: "My birthday is on the 10th of April.", bn: "আমার জন্মদিন ১০ই এপ্রিলে।", slotValues: { "DAY/DATE": "the 10th of April" } },
        { en: "They arrived on New Year's Day.", bn: "তারা নববর্ষের দিনে এসেছিল।", slotValues: { "DAY/DATE": "New Year's Day" } },
        { en: "The meeting is on the 25th.", bn: "মিটিং ২৫ তারিখে।", slotValues: { "DAY/DATE": "the 25th" } },
        { en: "I start my new job on Monday morning.", bn: "আমি সোমবার সকালে নতুন চাকরি শুরু করব।", slotValues: { "DAY/DATE": "Monday morning" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Use 'on' with days of the week, specific dates, and special days like holidays.",
      usageNote_bn:
        "সপ্তাহের দিন, নির্দিষ্ট তারিখ এবং ছুটির মতো বিশেষ দিনের সাথে 'on' ব্যবহার করুন।",
    },
    {
      id: "L1.3",
      formula: "in [MONTH/YEAR/PERIOD]",
      formula_bn: "[মাস/বছর/সময়কাল]-এ",
      patternName: "In + Month, Year, or Period",
      patternName_bn: "In + মাস, বছর বা সময়কাল",
      slots: [
        {
          name: "MONTH/YEAR/PERIOD",
          description: "Month, year, season, or longer time period",
          description_bn: "মাস, বছর, ঋতু বা দীর্ঘ সময়কাল",
          acceptedTypes: ["time_expression"],
          examples: ["January", "2024", "the morning", "summer", "the 1990s"],
        },
      ],
      examples: [
        { en: "I was born in 1995.", bn: "আমি ১৯৯৫ সালে জন্মেছিলাম।", slotValues: { "MONTH/YEAR/PERIOD": "1995" } },
        { en: "It rains a lot in July.", bn: "জুলাই মাসে অনেক বৃষ্টি হয়।", slotValues: { "MONTH/YEAR/PERIOD": "July" } },
        { en: "We go swimming in the summer.", bn: "আমরা গ্রীষ্মকালে সাঁতার কাটতে যাই।", slotValues: { "MONTH/YEAR/PERIOD": "the summer" } },
        { en: "I study best in the morning.", bn: "আমি সকালে সবচেয়ে ভালো পড়তে পারি।", slotValues: { "MONTH/YEAR/PERIOD": "the morning" } },
        { en: "The project will finish in December.", bn: "প্রজেক্ট ডিসেম্বরে শেষ হবে।", slotValues: { "MONTH/YEAR/PERIOD": "December" } },
        { en: "He moved to Dhaka in 2010.", bn: "সে ২০১০ সালে ঢাকায় চলে এসেছিল।", slotValues: { "MONTH/YEAR/PERIOD": "2010" } },
        { en: "Flowers bloom in spring.", bn: "বসন্তে ফুল ফোটে।", slotValues: { "MONTH/YEAR/PERIOD": "spring" } },
        { en: "It gets dark early in the winter.", bn: "শীতকালে তাড়াতাড়ি অন্ধকার হয়ে যায়।", slotValues: { "MONTH/YEAR/PERIOD": "the winter" } },
        { en: "I'll call you in the afternoon.", bn: "আমি বিকালে তোমাকে ফোন করব।", slotValues: { "MONTH/YEAR/PERIOD": "the afternoon" } },
        { en: "The festival is in October.", bn: "উৎসব অক্টোবরে।", slotValues: { "MONTH/YEAR/PERIOD": "October" } },
        { en: "Technology changed a lot in the 21st century.", bn: "২১শ শতকে প্রযুক্তি অনেক বদলে গেছে।", slotValues: { "MONTH/YEAR/PERIOD": "the 21st century" } },
        { en: "We usually take a vacation in August.", bn: "আমরা সাধারণত আগস্টে ছুটি নিই।", slotValues: { "MONTH/YEAR/PERIOD": "August" } },
        { en: "I feel sleepy in the evening.", bn: "সন্ধ্যায় আমার ঘুম পায়।", slotValues: { "MONTH/YEAR/PERIOD": "the evening" } },
        { en: "The company was founded in 2005.", bn: "কোম্পানি ২০০৫ সালে প্রতিষ্ঠিত হয়েছিল।", slotValues: { "MONTH/YEAR/PERIOD": "2005" } },
        { en: "It snows a lot in January.", bn: "জানুয়ারিতে অনেক তুষারপাত হয়।", slotValues: { "MONTH/YEAR/PERIOD": "January" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Use 'in' with months, years, seasons, centuries, and parts of the day (morning, afternoon, evening).",
      usageNote_bn:
        "মাস, বছর, ঋতু, শতক এবং দিনের অংশের (সকাল, বিকাল, সন্ধ্যা) সাথে 'in' ব্যবহার করুন।",
    },
    {
      id: "L1.4",
      formula: "at [TIME] on [DAY]",
      formula_bn: "[দিন]-এ [সময়]-এ",
      patternName: "Combining At + On",
      patternName_bn: "At + On একসাথে ব্যবহার",
      slots: [
        {
          name: "TIME",
          description: "Specific clock time",
          description_bn: "নির্দিষ্ট ঘড়ির সময়",
          acceptedTypes: ["time"],
          examples: ["3 p.m.", "10 a.m.", "noon"],
        },
        {
          name: "DAY",
          description: "Day of the week or date",
          description_bn: "সপ্তাহের দিন বা তারিখ",
          acceptedTypes: ["time_expression"],
          examples: ["Monday", "the 5th", "Friday"],
        },
      ],
      examples: [
        { en: "The meeting is at 3 p.m. on Monday.", bn: "মিটিং সোমবার বিকাল ৩টায়।", slotValues: { TIME: "3 p.m.", DAY: "Monday" } },
        { en: "I have a class at 9 a.m. on Wednesday.", bn: "বুধবার সকাল ৯টায় আমার ক্লাস আছে।", slotValues: { TIME: "9 a.m.", DAY: "Wednesday" } },
        { en: "The flight is at 6 p.m. on Friday.", bn: "ফ্লাইট শুক্রবার সন্ধ্যা ৬টায়।", slotValues: { TIME: "6 p.m.", DAY: "Friday" } },
        { en: "We'll meet at noon on Saturday.", bn: "আমরা শনিবার দুপুরে দেখা করব।", slotValues: { TIME: "noon", DAY: "Saturday" } },
        { en: "The show starts at 8 p.m. on the 15th.", bn: "অনুষ্ঠান ১৫ তারিখে রাত ৮টায় শুরু হয়।", slotValues: { TIME: "8 p.m.", DAY: "the 15th" } },
        { en: "The interview is at 10 a.m. on Thursday.", bn: "ইন্টারভিউ বৃহস্পতিবার সকাল ১০টায়।", slotValues: { TIME: "10 a.m.", DAY: "Thursday" } },
        { en: "Dinner is at 7 p.m. on Sunday.", bn: "রবিবার সন্ধ্যা ৭টায় রাতের খাবার।", slotValues: { TIME: "7 p.m.", DAY: "Sunday" } },
        { en: "The exam starts at 2 p.m. on Tuesday.", bn: "পরীক্ষা মঙ্গলবার বিকাল ২টায় শুরু হয়।", slotValues: { TIME: "2 p.m.", DAY: "Tuesday" } },
        { en: "The bus leaves at 5 a.m. on the 1st.", bn: "বাস ১ তারিখে সকাল ৫টায় ছাড়ে।", slotValues: { TIME: "5 a.m.", DAY: "the 1st" } },
        { en: "My appointment is at 11 a.m. on Monday.", bn: "আমার অ্যাপয়েন্টমেন্ট সোমবার সকাল ১১টায়।", slotValues: { TIME: "11 a.m.", DAY: "Monday" } },
        { en: "The wedding is at 4 p.m. on June 10th.", bn: "বিয়ে ১০ই জুন বিকাল ৪টায়।", slotValues: { TIME: "4 p.m.", DAY: "June 10th" } },
        { en: "The store opens at 8 a.m. on weekdays.", bn: "দোকান সপ্তাহের দিনে সকাল ৮টায় খোলে।", slotValues: { TIME: "8 a.m.", DAY: "weekdays" } },
        { en: "The game is at 3:30 p.m. on Saturday.", bn: "খেলা শনিবার বিকাল ৩:৩০-এ।", slotValues: { TIME: "3:30 p.m.", DAY: "Saturday" } },
        { en: "We have lunch at 1 p.m. on Fridays.", bn: "শুক্রবারে আমরা দুপুর ১টায় লাঞ্চ করি।", slotValues: { TIME: "1 p.m.", DAY: "Fridays" } },
        { en: "The concert is at 9 p.m. on New Year's Eve.", bn: "কনসার্ট নববর্ষের আগের রাতে রাত ৯টায়।", slotValues: { TIME: "9 p.m.", DAY: "New Year's Eve" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "When combining time and day, use 'at' for the clock time and 'on' for the day. The order can vary.",
      usageNote_bn:
        "সময় এবং দিন একসাথে বলতে ঘড়ির সময়ের জন্য 'at' এবং দিনের জন্য 'on' ব্যবহার করুন।",
    },
    {
      id: "L1.5",
      formula: "in [PERIOD] on [DAY]",
      formula_bn: "[দিন]-এর [সময়কাল]-এ",
      patternName: "Combining In + On",
      patternName_bn: "In + On একসাথে ব্যবহার",
      slots: [
        {
          name: "PERIOD",
          description: "Part of the day (morning, afternoon, evening)",
          description_bn: "দিনের অংশ (সকাল, বিকাল, সন্ধ্যা)",
          acceptedTypes: ["time_expression"],
          examples: ["the morning", "the afternoon", "the evening"],
        },
        {
          name: "DAY",
          description: "Day of the week",
          description_bn: "সপ্তাহের দিন",
          acceptedTypes: ["time_expression"],
          examples: ["Monday", "Saturday", "Wednesday"],
        },
      ],
      examples: [
        { en: "I exercise in the morning on weekdays.", bn: "আমি সপ্তাহের দিনে সকালে ব্যায়াম করি।", slotValues: { PERIOD: "the morning", DAY: "weekdays" } },
        { en: "We have meetings in the afternoon on Tuesdays.", bn: "আমাদের মঙ্গলবারে বিকালে মিটিং থাকে।", slotValues: { PERIOD: "the afternoon", DAY: "Tuesdays" } },
        { en: "I relax in the evening on Sundays.", bn: "আমি রবিবারে সন্ধ্যায় বিশ্রাম নিই।", slotValues: { PERIOD: "the evening", DAY: "Sundays" } },
        { en: "The market is busiest in the morning on Saturdays.", bn: "শনিবারে সকালে বাজারে সবচেয়ে বেশি ভিড় থাকে।", slotValues: { PERIOD: "the morning", DAY: "Saturdays" } },
        { en: "I study in the afternoon on Fridays.", bn: "শুক্রবারে বিকালে আমি পড়াশোনা করি।", slotValues: { PERIOD: "the afternoon", DAY: "Fridays" } },
        { en: "We go to the park in the evening on weekends.", bn: "আমরা সপ্তাহান্তে সন্ধ্যায় পার্কে যাই।", slotValues: { PERIOD: "the evening", DAY: "weekends" } },
        { en: "He plays football in the afternoon on Thursdays.", bn: "সে বৃহস্পতিবারে বিকালে ফুটবল খেলে।", slotValues: { PERIOD: "the afternoon", DAY: "Thursdays" } },
        { en: "I cook breakfast in the morning on Sundays.", bn: "রবিবারে সকালে আমি সকালের নাস্তা রান্না করি।", slotValues: { PERIOD: "the morning", DAY: "Sundays" } },
        { en: "The library is quiet in the evening on Mondays.", bn: "সোমবারে সন্ধ্যায় লাইব্রেরি শান্ত থাকে।", slotValues: { PERIOD: "the evening", DAY: "Mondays" } },
        { en: "We have yoga in the morning on Wednesdays.", bn: "বুধবারে সকালে আমাদের যোগব্যায়াম আছে।", slotValues: { PERIOD: "the morning", DAY: "Wednesdays" } },
        { en: "I do laundry in the afternoon on Saturdays.", bn: "শনিবারে বিকালে আমি কাপড় ধুই।", slotValues: { PERIOD: "the afternoon", DAY: "Saturdays" } },
        { en: "Traffic is heavy in the morning on weekdays.", bn: "সপ্তাহের দিনে সকালে যানজট থাকে।", slotValues: { PERIOD: "the morning", DAY: "weekdays" } },
        { en: "We watch movies in the evening on Fridays.", bn: "শুক্রবারে সন্ধ্যায় আমরা মুভি দেখি।", slotValues: { PERIOD: "the evening", DAY: "Fridays" } },
        { en: "I clean the house in the morning on Saturdays.", bn: "শনিবারে সকালে আমি ঘর পরিষ্কার করি।", slotValues: { PERIOD: "the morning", DAY: "Saturdays" } },
        { en: "She reads books in the evening on Tuesdays.", bn: "সে মঙ্গলবারে সন্ধ্যায় বই পড়ে।", slotValues: { PERIOD: "the evening", DAY: "Tuesdays" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "When combining a part of the day with a specific day, use 'in' for the period and 'on' for the day.",
      usageNote_bn:
        "দিনের অংশ এবং নির্দিষ্ট দিন একসাথে বলতে সময়কালের জন্য 'in' এবং দিনের জন্য 'on' ব্যবহার করুন।",
    },
    {
      id: "L1.6",
      formula: "During [EVENT/PERIOD], [CLAUSE]",
      formula_bn: "[ঘটনা/সময়কাল]-এর সময়, [বাক্যাংশ]",
      patternName: "During",
      patternName_bn: "During (সময়কালে)",
      slots: [
        {
          name: "EVENT/PERIOD",
          description: "An event, activity, or time period",
          description_bn: "একটি ঘটনা, কার্যকলাপ বা সময়কাল",
          acceptedTypes: ["noun", "time_expression"],
          examples: ["the meeting", "summer vacation", "lunch"],
        },
        {
          name: "CLAUSE",
          description: "What happened during that time",
          description_bn: "সেই সময়ে কী ঘটেছিল",
          acceptedTypes: ["clause"],
          examples: ["I took notes", "we visited many places", "it started raining"],
        },
      ],
      examples: [
        { en: "During the meeting, I took detailed notes.", bn: "মিটিংয়ের সময়, আমি বিস্তারিত নোট নিয়েছিলাম।", slotValues: { "EVENT/PERIOD": "the meeting", CLAUSE: "I took detailed notes" }, topicArea: "work" },
        { en: "During summer vacation, we visited Cox's Bazar.", bn: "গ্রীষ্মের ছুটির সময়, আমরা কক্সবাজার ঘুরেছিলাম।", slotValues: { "EVENT/PERIOD": "summer vacation", CLAUSE: "we visited Cox's Bazar" }, topicArea: "travel" },
        { en: "During lunch, we talked about the project.", bn: "দুপুরের খাবারের সময়, আমরা প্রজেক্ট নিয়ে কথা বলেছিলাম।", slotValues: { "EVENT/PERIOD": "lunch", CLAUSE: "we talked about the project" }, topicArea: "food" },
        { en: "During the exam, the room was completely silent.", bn: "পরীক্ষার সময়, ঘরটা সম্পূর্ণ নীরব ছিল।", slotValues: { "EVENT/PERIOD": "the exam", CLAUSE: "the room was completely silent" }, topicArea: "education" },
        { en: "During the storm, we stayed inside.", bn: "ঝড়ের সময়, আমরা ভেতরে থেকেছিলাম।", slotValues: { "EVENT/PERIOD": "the storm", CLAUSE: "we stayed inside" }, topicArea: "daily_life" },
        { en: "During my recovery, I read many books.", bn: "সুস্থতার সময়, আমি অনেক বই পড়েছিলাম।", slotValues: { "EVENT/PERIOD": "my recovery", CLAUSE: "I read many books" }, topicArea: "health" },
        { en: "During the sale, everything was half price.", bn: "সেলের সময়, সবকিছু অর্ধেক দামে ছিল।", slotValues: { "EVENT/PERIOD": "the sale", CLAUSE: "everything was half price" }, topicArea: "shopping" },
        { en: "During our conversation, I realized something important.", bn: "আমাদের কথোপকথনের সময়, আমি কিছু গুরুত্বপূর্ণ বিষয় বুঝতে পেরেছিলাম।", slotValues: { "EVENT/PERIOD": "our conversation", CLAUSE: "I realized something important" }, topicArea: "relationships" },
        { en: "During the workshop, we learned new techniques.", bn: "কর্মশালার সময়, আমরা নতুন কৌশল শিখেছিলাম।", slotValues: { "EVENT/PERIOD": "the workshop", CLAUSE: "we learned new techniques" }, topicArea: "education" },
        { en: "During Ramadan, we eat iftar together.", bn: "রমজানের সময়, আমরা একসাথে ইফতার করি।", slotValues: { "EVENT/PERIOD": "Ramadan", CLAUSE: "we eat iftar together" }, topicArea: "food" },
        { en: "During the flight, I watched two movies.", bn: "ফ্লাইটের সময়, আমি দুটো সিনেমা দেখেছিলাম।", slotValues: { "EVENT/PERIOD": "the flight", CLAUSE: "I watched two movies" }, topicArea: "travel" },
        { en: "During the presentation, the projector stopped working.", bn: "প্রেজেন্টেশনের সময়, প্রজেক্টর কাজ করা বন্ধ করে দিয়েছিল।", slotValues: { "EVENT/PERIOD": "the presentation", CLAUSE: "the projector stopped working" }, topicArea: "work" },
        { en: "During the walk, we enjoyed the fresh air.", bn: "হাঁটার সময়, আমরা তাজা বাতাস উপভোগ করেছিলাম।", slotValues: { "EVENT/PERIOD": "the walk", CLAUSE: "we enjoyed the fresh air" }, topicArea: "health" },
        { en: "During the party, everyone was dancing.", bn: "পার্টির সময়, সবাই নাচছিল।", slotValues: { "EVENT/PERIOD": "the party", CLAUSE: "everyone was dancing" }, topicArea: "relationships" },
        { en: "During the weekend, I cleaned the entire house.", bn: "সপ্তাহান্তের সময়, আমি পুরো ঘর পরিষ্কার করেছিলাম।", slotValues: { "EVENT/PERIOD": "the weekend", CLAUSE: "I cleaned the entire house" }, topicArea: "daily_life" },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "'During' is followed by a noun (not a clause). It tells us WHEN something happens, not HOW LONG. For duration, use 'for' instead (e.g., 'for two hours').",
      usageNote_bn:
        "'During'-এর পরে বিশেষ্য আসে (উপবাক্য নয়)। এটি বলে কখন কিছু ঘটে, কতক্ষণ নয়। সময়কালের জন্য 'for' ব্যবহার করুন (যেমন, 'for two hours')।",
    },
  ],
};
