import { PatternCategory } from "@/types/pattern";

export const categoryL4: PatternCategory = {
  id: "L4",
  slug: "timing-relationships",
  name: "Timing Relationships",
  name_bn: "সময়ের সম্পর্ক",
  description:
    "Learn to describe the timing between two events.",
  description_bn:
    "দুটি ঘটনার মধ্যে সময়ের সম্পর্ক বর্ণনা করতে শিখুন।",
  icon: "🔗",
  group: "L",
  groupName: "Time Expression Patterns",
  groupName_bn: "সময় প্রকাশের প্যাটার্ন",
  difficulty: "beginner",
  patterns: [
    {
      id: "L4.1",
      formula: "While I was [DOING], [EVENT]",
      formula_bn: "আমি যখন [কাজ] করছিলাম, [ঘটনা]",
      patternName: "While + Past Continuous",
      patternName_bn: "While + অতীত চলমান কাল",
      slots: [
        {
          name: "DOING",
          description: "An ongoing past action",
          description_bn: "একটি চলমান অতীত কাজ",
          acceptedTypes: ["gerund"],
          examples: ["sleeping", "cooking", "studying", "walking"],
        },
        {
          name: "EVENT",
          description: "An event that interrupted or happened simultaneously",
          description_bn: "একটি ঘটনা যা বাধা দিয়েছিল বা একই সময়ে ঘটেছিল",
          acceptedTypes: ["clause"],
          examples: ["the phone rang", "it started raining", "someone knocked"],
        },
      ],
      examples: [
        { en: "While I was sleeping, the phone rang.", bn: "আমি যখন ঘুমাচ্ছিলাম, ফোন বেজে উঠল।", slotValues: { DOING: "sleeping", EVENT: "the phone rang" } },
        { en: "While I was cooking, the fire alarm went off.", bn: "আমি যখন রান্না করছিলাম, ফায়ার অ্যালার্ম বেজে উঠল।", slotValues: { DOING: "cooking", EVENT: "the fire alarm went off" } },
        { en: "While I was studying, someone knocked on the door.", bn: "আমি যখন পড়াশোনা করছিলাম, কেউ দরজায় নক করল।", slotValues: { DOING: "studying", EVENT: "someone knocked on the door" } },
        { en: "While I was walking home, it started raining.", bn: "আমি যখন বাড়ি হেঁটে যাচ্ছিলাম, বৃষ্টি শুরু হলো।", slotValues: { DOING: "walking home", EVENT: "it started raining" } },
        { en: "While I was taking a shower, the power went out.", bn: "আমি যখন গোসল করছিলাম, বিদ্যুৎ চলে গেল।", slotValues: { DOING: "taking a shower", EVENT: "the power went out" } },
        { en: "While I was driving, I saw an accident.", bn: "আমি যখন গাড়ি চালাচ্ছিলাম, একটি দুর্ঘটনা দেখলাম।", slotValues: { DOING: "driving", EVENT: "I saw an accident" } },
        { en: "While I was eating lunch, my boss called.", bn: "আমি যখন দুপুরের খাবার খাচ্ছিলাম, বস ফোন করলেন।", slotValues: { DOING: "eating lunch", EVENT: "my boss called" } },
        { en: "While I was watching TV, the doorbell rang.", bn: "আমি যখন টিভি দেখছিলাম, দরজার ঘণ্টা বাজল।", slotValues: { DOING: "watching TV", EVENT: "the doorbell rang" } },
        { en: "While I was reading, I fell asleep.", bn: "আমি যখন পড়ছিলাম, ঘুমিয়ে পড়লাম।", slotValues: { DOING: "reading", EVENT: "I fell asleep" } },
        { en: "While I was shopping, I met an old friend.", bn: "আমি যখন কেনাকাটা করছিলাম, একজন পুরনো বন্ধুর সাথে দেখা হলো।", slotValues: { DOING: "shopping", EVENT: "I met an old friend" } },
        { en: "While I was waiting for the bus, a taxi stopped.", bn: "আমি যখন বাসের জন্য অপেক্ষা করছিলাম, একটি ট্যাক্সি থামল।", slotValues: { DOING: "waiting for the bus", EVENT: "a taxi stopped" } },
        { en: "While I was jogging, I twisted my ankle.", bn: "আমি যখন জগিং করছিলাম, পায়ের গোড়ালি মচকে গেল।", slotValues: { DOING: "jogging", EVENT: "I twisted my ankle" } },
        { en: "While I was cleaning, I found my lost ring.", bn: "আমি যখন পরিষ্কার করছিলাম, হারানো আংটি খুঁজে পেলাম।", slotValues: { DOING: "cleaning", EVENT: "I found my lost ring" } },
        { en: "While I was working, the internet went down.", bn: "আমি যখন কাজ করছিলাম, ইন্টারনেট বন্ধ হয়ে গেল।", slotValues: { DOING: "working", EVENT: "the internet went down" } },
        { en: "While I was talking on the phone, the baby woke up.", bn: "আমি যখন ফোনে কথা বলছিলাম, বাচ্চা ঘুম থেকে উঠে গেল।", slotValues: { DOING: "talking on the phone", EVENT: "the baby woke up" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Use 'while' with an ongoing action (past continuous) when another event interrupts it (simple past).",
      usageNote_bn:
        "একটি চলমান কাজের (অতীত চলমান কাল) সময় অন্য ঘটনা (সাধারণ অতীত) ঘটলে 'while' ব্যবহার করুন।",
    },
    {
      id: "L4.2",
      formula: "By the time [EVENT], [CLAUSE]",
      formula_bn: "[ঘটনা] হওয়ার আগেই, [বাক্যাংশ]",
      patternName: "By the Time + Clause",
      patternName_bn: "By the Time + বাক্যাংশ",
      slots: [
        {
          name: "EVENT",
          description: "A reference event or point in time",
          description_bn: "একটি রেফারেন্স ঘটনা বা সময়ের বিন্দু",
          acceptedTypes: ["clause"],
          examples: ["I arrived", "the movie started", "we finished"],
        },
        {
          name: "CLAUSE",
          description: "What had already happened or will happen",
          description_bn: "যা ইতিমধ্যে ঘটেছিল বা ঘটবে",
          acceptedTypes: ["clause"],
          examples: ["they had left", "it was too late", "everyone was ready"],
        },
      ],
      examples: [
        { en: "By the time I arrived, they had already left.", bn: "আমি পৌঁছানোর আগেই তারা চলে গিয়েছিল।", slotValues: { EVENT: "I arrived", CLAUSE: "they had already left" } },
        { en: "By the time the ambulance came, the patient had recovered.", bn: "অ্যাম্বুলেন্স আসার আগেই রোগী সুস্থ হয়ে গিয়েছিল।", slotValues: { EVENT: "the ambulance came", CLAUSE: "the patient had recovered" } },
        { en: "By the time we got to the theater, the movie had started.", bn: "আমরা থিয়েটারে পৌঁছানোর আগেই মুভি শুরু হয়ে গিয়েছিল।", slotValues: { EVENT: "we got to the theater", CLAUSE: "the movie had started" } },
        { en: "By the time I finished cooking, everyone was hungry.", bn: "আমি রান্না শেষ করার সময়, সবাই ক্ষুধার্ত ছিল।", slotValues: { EVENT: "I finished cooking", CLAUSE: "everyone was hungry" } },
        { en: "By the time he woke up, the sun had already risen.", bn: "সে ঘুম থেকে ওঠার আগেই সূর্য উঠে গিয়েছিল।", slotValues: { EVENT: "he woke up", CLAUSE: "the sun had already risen" } },
        { en: "By the time you read this, I'll be on the plane.", bn: "তুমি এটা পড়ার সময়, আমি প্লেনে থাকব।", slotValues: { EVENT: "you read this", CLAUSE: "I'll be on the plane" } },
        { en: "By the time I learned to drive, I was 25.", bn: "আমি গাড়ি চালানো শেখার সময়, আমার বয়স ২৫ ছিল।", slotValues: { EVENT: "I learned to drive", CLAUSE: "I was 25" } },
        { en: "By the time the rain stopped, we were completely wet.", bn: "বৃষ্টি থামার আগেই আমরা পুরোপুরি ভিজে গিয়েছিলাম।", slotValues: { EVENT: "the rain stopped", CLAUSE: "we were completely wet" } },
        { en: "By the time school ended, the bus had gone.", bn: "স্কুল শেষ হওয়ার আগেই বাস চলে গিয়েছিল।", slotValues: { EVENT: "school ended", CLAUSE: "the bus had gone" } },
        { en: "By the time she called back, I had fallen asleep.", bn: "সে ফোন করার আগেই আমি ঘুমিয়ে পড়েছিলাম।", slotValues: { EVENT: "she called back", CLAUSE: "I had fallen asleep" } },
        { en: "By the time we arrived at the party, most people had left.", bn: "আমরা পার্টিতে পৌঁছানোর আগেই বেশিরভাগ মানুষ চলে গিয়েছিল।", slotValues: { EVENT: "we arrived at the party", CLAUSE: "most people had left" } },
        { en: "By the time I saved enough money, the price had gone up.", bn: "আমি পর্যাপ্ত টাকা জমানোর আগেই দাম বেড়ে গিয়েছিল।", slotValues: { EVENT: "I saved enough money", CLAUSE: "the price had gone up" } },
        { en: "By the time dinner was ready, the guests had arrived.", bn: "রাতের খাবার তৈরি হওয়ার সময়, অতিথিরা এসে গিয়েছিল।", slotValues: { EVENT: "dinner was ready", CLAUSE: "the guests had arrived" } },
        { en: "By the time I got home, it was already dark.", bn: "আমি বাড়ি পৌঁছানোর সময়, ইতিমধ্যে অন্ধকার হয়ে গিয়েছিল।", slotValues: { EVENT: "I got home", CLAUSE: "it was already dark" } },
        { en: "By the time the teacher came, the students were seated.", bn: "শিক্ষক আসার আগেই ছাত্ররা বসে গিয়েছিল।", slotValues: { EVENT: "the teacher came", CLAUSE: "the students were seated" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "'By the time' means 'before or at the moment when.' It often pairs with the past perfect (had + past participle).",
      usageNote_bn:
        "'By the time' মানে 'যখন বা তার আগে।' এটি প্রায়ই অতীত পূর্ণ কালের (had + past participle) সাথে ব্যবহৃত হয়।",
    },
    {
      id: "L4.3",
      formula: "Before [EVENT], [CLAUSE]",
      formula_bn: "[ঘটনা]-র আগে, [বাক্যাংশ]",
      patternName: "Before + Event",
      patternName_bn: "Before + ঘটনা",
      slots: [
        {
          name: "EVENT",
          description: "A reference event",
          description_bn: "একটি রেফারেন্স ঘটনা",
          acceptedTypes: ["clause", "gerund"],
          examples: ["leaving", "the meeting", "I go to bed"],
        },
        {
          name: "CLAUSE",
          description: "What happens first",
          description_bn: "যা আগে ঘটে",
          acceptedTypes: ["clause"],
          examples: ["I check my bag", "make sure to eat", "I always pray"],
        },
      ],
      examples: [
        { en: "Before leaving, I check my bag.", bn: "বের হওয়ার আগে, আমি ব্যাগ চেক করি।", slotValues: { EVENT: "leaving", CLAUSE: "I check my bag" } },
        { en: "Before the exam, I review my notes.", bn: "পরীক্ষার আগে, আমি নোটগুলো রিভিউ করি।", slotValues: { EVENT: "the exam", CLAUSE: "I review my notes" } },
        { en: "Before I go to bed, I brush my teeth.", bn: "ঘুমাতে যাওয়ার আগে, আমি দাঁত মাজি।", slotValues: { EVENT: "I go to bed", CLAUSE: "I brush my teeth" } },
        { en: "Before cooking, wash your hands.", bn: "রান্না করার আগে, হাত ধুয়ে নিন।", slotValues: { EVENT: "cooking", CLAUSE: "wash your hands" } },
        { en: "Before the meeting starts, prepare your report.", bn: "মিটিং শুরু হওয়ার আগে, রিপোর্ট তৈরি করুন।", slotValues: { EVENT: "the meeting starts", CLAUSE: "prepare your report" } },
        { en: "Before eating, we say a prayer.", bn: "খাওয়ার আগে, আমরা প্রার্থনা করি।", slotValues: { EVENT: "eating", CLAUSE: "we say a prayer" } },
        { en: "Before sunrise, the birds start singing.", bn: "সূর্যোদয়ের আগে, পাখিরা গান শুরু করে।", slotValues: { EVENT: "sunrise", CLAUSE: "the birds start singing" } },
        { en: "Before I started this job, I was a student.", bn: "এই চাকরি শুরু করার আগে, আমি ছাত্র ছিলাম।", slotValues: { EVENT: "I started this job", CLAUSE: "I was a student" } },
        { en: "Before crossing the road, look both ways.", bn: "রাস্তা পার হওয়ার আগে, দুই দিকে দেখুন।", slotValues: { EVENT: "crossing the road", CLAUSE: "look both ways" } },
        { en: "Before the movie, let's grab some popcorn.", bn: "মুভির আগে, চলো পপকর্ন কিনি।", slotValues: { EVENT: "the movie", CLAUSE: "let's grab some popcorn" } },
        { en: "Before going out, check the weather.", bn: "বাইরে যাওয়ার আগে, আবহাওয়া দেখে নিন।", slotValues: { EVENT: "going out", CLAUSE: "check the weather" } },
        { en: "Before the guests arrive, clean the living room.", bn: "অতিথিরা আসার আগে, বসার ঘর পরিষ্কার করুন।", slotValues: { EVENT: "the guests arrive", CLAUSE: "clean the living room" } },
        { en: "Before submitting, proofread your essay.", bn: "জমা দেওয়ার আগে, প্রবন্ধটি প্রুফরিড করুন।", slotValues: { EVENT: "submitting", CLAUSE: "proofread your essay" } },
        { en: "Before winter comes, buy warm clothes.", bn: "শীত আসার আগে, গরম কাপড় কিনুন।", slotValues: { EVENT: "winter comes", CLAUSE: "buy warm clothes" } },
        { en: "Before I forget, let me write it down.", bn: "ভুলে যাওয়ার আগে, আমাকে লিখে রাখতে দাও।", slotValues: { EVENT: "I forget", CLAUSE: "let me write it down" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "'Before' introduces the later event. The main clause describes what happens first.",
      usageNote_bn:
        "'Before' পরের ঘটনাটি উপস্থাপন করে। প্রধান বাক্যাংশটি বর্ণনা করে কী আগে ঘটে।",
    },
    {
      id: "L4.4",
      formula: "After [EVENT], [CLAUSE]",
      formula_bn: "[ঘটনা]-র পরে, [বাক্যাংশ]",
      patternName: "After + Event",
      patternName_bn: "After + ঘটনা",
      slots: [
        {
          name: "EVENT",
          description: "An event that happens first",
          description_bn: "একটি ঘটনা যা আগে ঘটে",
          acceptedTypes: ["clause", "gerund"],
          examples: ["lunch", "finishing work", "the rain stops"],
        },
        {
          name: "CLAUSE",
          description: "What happens next",
          description_bn: "এরপর কী ঘটে",
          acceptedTypes: ["clause"],
          examples: ["I take a nap", "we went home", "let's go for a walk"],
        },
      ],
      examples: [
        { en: "After lunch, I take a short nap.", bn: "দুপুরের খাবারের পরে, আমি একটু ঘুমাই।", slotValues: { EVENT: "lunch", CLAUSE: "I take a short nap" } },
        { en: "After finishing work, I go to the gym.", bn: "কাজ শেষ করার পরে, আমি জিমে যাই।", slotValues: { EVENT: "finishing work", CLAUSE: "I go to the gym" } },
        { en: "After the rain stopped, we went outside.", bn: "বৃষ্টি থামার পরে, আমরা বাইরে গেলাম।", slotValues: { EVENT: "the rain stopped", CLAUSE: "we went outside" } },
        { en: "After breakfast, I read the newspaper.", bn: "সকালের নাস্তার পরে, আমি পত্রিকা পড়ি।", slotValues: { EVENT: "breakfast", CLAUSE: "I read the newspaper" } },
        { en: "After graduating, she got a job.", bn: "স্নাতক হওয়ার পরে, সে চাকরি পেল।", slotValues: { EVENT: "graduating", CLAUSE: "she got a job" } },
        { en: "After the movie, let's get dinner.", bn: "মুভির পরে, চলো রাতের খাবার খাই।", slotValues: { EVENT: "the movie", CLAUSE: "let's get dinner" } },
        { en: "After I exercise, I feel energetic.", bn: "ব্যায়াম করার পরে, আমি সতেজ বোধ করি।", slotValues: { EVENT: "I exercise", CLAUSE: "I feel energetic" } },
        { en: "After the meeting ended, we had tea.", bn: "মিটিং শেষ হওয়ার পরে, আমরা চা খেলাম।", slotValues: { EVENT: "the meeting ended", CLAUSE: "we had tea" } },
        { en: "After dinner, we watch TV together.", bn: "রাতের খাবারের পরে, আমরা একসাথে টিভি দেখি।", slotValues: { EVENT: "dinner", CLAUSE: "we watch TV together" } },
        { en: "After cleaning the house, I took a shower.", bn: "ঘর পরিষ্কার করার পরে, আমি গোসল করলাম।", slotValues: { EVENT: "cleaning the house", CLAUSE: "I took a shower" } },
        { en: "After school, the children play outside.", bn: "স্কুলের পরে, বাচ্চারা বাইরে খেলে।", slotValues: { EVENT: "school", CLAUSE: "the children play outside" } },
        { en: "After the exam, I felt relieved.", bn: "পরীক্ষার পরে, আমি স্বস্তি বোধ করলাম।", slotValues: { EVENT: "the exam", CLAUSE: "I felt relieved" } },
        { en: "After shopping, we stopped for coffee.", bn: "কেনাকাটার পরে, আমরা কফি খেতে থামলাম।", slotValues: { EVENT: "shopping", CLAUSE: "we stopped for coffee" } },
        { en: "After taking the medicine, I felt better.", bn: "ওষুধ খাওয়ার পরে, আমি ভালো অনুভব করলাম।", slotValues: { EVENT: "taking the medicine", CLAUSE: "I felt better" } },
        { en: "After the sun sets, it gets cool.", bn: "সূর্য ডোবার পরে, ঠান্ডা পড়ে।", slotValues: { EVENT: "the sun sets", CLAUSE: "it gets cool" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "'After' introduces the event that happens first. The main clause describes what follows.",
      usageNote_bn:
        "'After' আগের ঘটনাটি উপস্থাপন করে। প্রধান বাক্যাংশটি বর্ণনা করে এরপর কী ঘটে।",
    },
    {
      id: "L4.5",
      formula: "As soon as [EVENT], [CLAUSE]",
      formula_bn: "[ঘটনা] হওয়া মাত্রই, [বাক্যাংশ]",
      patternName: "As Soon As + Event",
      patternName_bn: "হওয়া মাত্রই + ঘটনা",
      slots: [
        {
          name: "EVENT",
          description: "A triggering event",
          description_bn: "একটি ট্রিগারকারী ঘটনা",
          acceptedTypes: ["clause"],
          examples: ["I get home", "the bell rings", "he heard the news"],
        },
        {
          name: "CLAUSE",
          description: "Immediate reaction or result",
          description_bn: "তাৎক্ষণিক প্রতিক্রিয়া বা ফলাফল",
          acceptedTypes: ["clause"],
          examples: ["I'll call you", "everyone ran out", "she started crying"],
        },
      ],
      examples: [
        { en: "As soon as I get home, I'll call you.", bn: "বাড়ি পৌঁছানো মাত্রই, তোমাকে ফোন করব।", slotValues: { EVENT: "I get home", CLAUSE: "I'll call you" } },
        { en: "As soon as the bell rang, the students ran out.", bn: "ঘণ্টা বাজা মাত্রই, ছাত্ররা বের হয়ে গেল।", slotValues: { EVENT: "the bell rang", CLAUSE: "the students ran out" } },
        { en: "As soon as she heard the news, she started crying.", bn: "খবর শোনা মাত্রই, সে কাঁদতে শুরু করল।", slotValues: { EVENT: "she heard the news", CLAUSE: "she started crying" } },
        { en: "As soon as the sun comes up, I go for a walk.", bn: "সূর্য ওঠা মাত্রই, আমি হাঁটতে যাই।", slotValues: { EVENT: "the sun comes up", CLAUSE: "I go for a walk" } },
        { en: "As soon as it stops raining, we'll leave.", bn: "বৃষ্টি থামা মাত্রই, আমরা রওনা দেব।", slotValues: { EVENT: "it stops raining", CLAUSE: "we'll leave" } },
        { en: "As soon as I saw him, I recognized him.", bn: "তাকে দেখা মাত্রই, আমি চিনতে পারলাম।", slotValues: { EVENT: "I saw him", CLAUSE: "I recognized him" } },
        { en: "As soon as the food arrived, we started eating.", bn: "খাবার আসা মাত্রই, আমরা খেতে শুরু করলাম।", slotValues: { EVENT: "the food arrived", CLAUSE: "we started eating" } },
        { en: "As soon as I finish this, I'll help you.", bn: "এটা শেষ করা মাত্রই, তোমাকে সাহায্য করব।", slotValues: { EVENT: "I finish this", CLAUSE: "I'll help you" } },
        { en: "As soon as the doctor came, the patient felt better.", bn: "ডাক্তার আসা মাত্রই, রোগী ভালো অনুভব করল।", slotValues: { EVENT: "the doctor came", CLAUSE: "the patient felt better" } },
        { en: "As soon as I wake up, I drink a glass of water.", bn: "ঘুম থেকে ওঠা মাত্রই, আমি এক গ্লাস পানি খাই।", slotValues: { EVENT: "I wake up", CLAUSE: "I drink a glass of water" } },
        { en: "As soon as the meeting ended, everyone left.", bn: "মিটিং শেষ হওয়া মাত্রই, সবাই চলে গেল।", slotValues: { EVENT: "the meeting ended", CLAUSE: "everyone left" } },
        { en: "As soon as the plane landed, passengers clapped.", bn: "প্লেন নামা মাত্রই, যাত্রীরা হাততালি দিল।", slotValues: { EVENT: "the plane landed", CLAUSE: "passengers clapped" } },
        { en: "As soon as I heard the alarm, I got up.", bn: "অ্যালার্ম শোনা মাত্রই, আমি উঠে পড়লাম।", slotValues: { EVENT: "I heard the alarm", CLAUSE: "I got up" } },
        { en: "As soon as he arrived, the meeting began.", bn: "সে পৌঁছানো মাত্রই, মিটিং শুরু হলো।", slotValues: { EVENT: "he arrived", CLAUSE: "the meeting began" } },
        { en: "As soon as you're ready, let me know.", bn: "তুমি প্রস্তুত হওয়া মাত্রই, আমাকে জানাও।", slotValues: { EVENT: "you're ready", CLAUSE: "let me know" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "'As soon as' emphasizes that something happens immediately after another event.",
      usageNote_bn:
        "'As soon as' জোর দেয় যে একটি ঘটনার ঠিক পরেই আরেকটি ঘটনা ঘটে।",
    },
  ],
};
