import { PatternCategory } from "@/types/pattern";

export const categoryL5: PatternCategory = {
  id: "L5",
  slug: "deadlines-schedules",
  name: "Deadlines & Schedules",
  name_bn: "সময়সীমা ও সময়সূচি",
  description:
    "Learn to talk about deadlines, schedules, and time limits.",
  description_bn:
    "সময়সীমা, সময়সূচি এবং সময়ের সীমাবদ্ধতা সম্পর্কে বলতে শিখুন।",
  icon: "📅",
  group: "L",
  groupName: "Time Expression Patterns",
  groupName_bn: "সময় প্রকাশের প্যাটার্ন",
  difficulty: "beginner",
  patterns: [
    {
      id: "L5.1",
      formula: "[EVENT] is on [DATE]",
      formula_bn: "[ইভেন্ট] [তারিখ]-এ",
      patternName: "Scheduled Event on Date",
      patternName_bn: "তারিখে নির্ধারিত ইভেন্ট",
      slots: [
        {
          name: "EVENT",
          description: "A planned event or occasion",
          description_bn: "একটি পরিকল্পিত ইভেন্ট বা উপলক্ষ",
          acceptedTypes: ["noun_phrase", "event"],
          examples: ["The meeting", "My exam", "The wedding"],
        },
        {
          name: "DATE",
          description: "A specific date or day",
          description_bn: "একটি নির্দিষ্ট তারিখ বা দিন",
          acceptedTypes: ["time_expression"],
          examples: ["March 10th", "Monday", "the 25th"],
        },
      ],
      examples: [
        { en: "The meeting is on Monday.", bn: "মিটিং সোমবারে।", slotValues: { EVENT: "The meeting", DATE: "Monday" } },
        { en: "My exam is on March 15th.", bn: "আমার পরীক্ষা ১৫ই মার্চে।", slotValues: { EVENT: "My exam", DATE: "March 15th" } },
        { en: "The wedding is on Saturday.", bn: "বিয়ে শনিবারে।", slotValues: { EVENT: "The wedding", DATE: "Saturday" } },
        { en: "The concert is on December 20th.", bn: "কনসার্ট ২০শে ডিসেম্বরে।", slotValues: { EVENT: "The concert", DATE: "December 20th" } },
        { en: "Our anniversary is on June 5th.", bn: "আমাদের বার্ষিকী ৫ই জুনে।", slotValues: { EVENT: "Our anniversary", DATE: "June 5th" } },
        { en: "The interview is on Wednesday.", bn: "ইন্টারভিউ বুধবারে।", slotValues: { EVENT: "The interview", DATE: "Wednesday" } },
        { en: "The festival is on the 25th.", bn: "উৎসব ২৫ তারিখে।", slotValues: { EVENT: "The festival", DATE: "the 25th" } },
        { en: "The presentation is on Thursday.", bn: "প্রেজেন্টেশন বৃহস্পতিবারে।", slotValues: { EVENT: "The presentation", DATE: "Thursday" } },
        { en: "The school picnic is on April 1st.", bn: "স্কুল পিকনিক ১লা এপ্রিলে।", slotValues: { EVENT: "The school picnic", DATE: "April 1st" } },
        { en: "The deadline is on Friday.", bn: "সময়সীমা শুক্রবারে।", slotValues: { EVENT: "The deadline", DATE: "Friday" } },
        { en: "My flight is on Tuesday morning.", bn: "আমার ফ্লাইট মঙ্গলবার সকালে।", slotValues: { EVENT: "My flight", DATE: "Tuesday morning" } },
        { en: "The parent-teacher meeting is on the 10th.", bn: "অভিভাবক-শিক্ষক সভা ১০ তারিখে।", slotValues: { EVENT: "The parent-teacher meeting", DATE: "the 10th" } },
        { en: "Independence Day is on March 26th.", bn: "স্বাধীনতা দিবস ২৬শে মার্চে।", slotValues: { EVENT: "Independence Day", DATE: "March 26th" } },
        { en: "The sports day is on November 15th.", bn: "ক্রীড়া দিবস ১৫ই নভেম্বরে।", slotValues: { EVENT: "The sports day", DATE: "November 15th" } },
        { en: "The doctor's appointment is on Monday afternoon.", bn: "ডাক্তারের অ্যাপয়েন্টমেন্ট সোমবার বিকালে।", slotValues: { EVENT: "The doctor's appointment", DATE: "Monday afternoon" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Use this pattern to state when a scheduled event takes place.",
      usageNote_bn:
        "একটি নির্ধারিত ইভেন্ট কখন হবে তা বলতে এই প্যাটার্নটি ব্যবহার করুন।",
    },
    {
      id: "L5.2",
      formula: "I have until [TIME] to [ACTION]",
      formula_bn: "[কাজ] করতে আমার [সময়] পর্যন্ত সময় আছে",
      patternName: "Deadline with Until",
      patternName_bn: "Until দিয়ে সময়সীমা",
      slots: [
        {
          name: "TIME",
          description: "The deadline or time limit",
          description_bn: "সময়সীমা বা সময়ের সীমা",
          acceptedTypes: ["time_expression", "time"],
          examples: ["Friday", "5 p.m.", "the end of the month"],
        },
        {
          name: "ACTION",
          description: "The task to be completed",
          description_bn: "সম্পন্ন করার কাজ",
          acceptedTypes: ["to_verb"],
          examples: ["finish", "submit", "decide"],
        },
      ],
      examples: [
        { en: "I have until Friday to finish the report.", bn: "রিপোর্ট শেষ করতে আমার শুক্রবার পর্যন্ত সময় আছে।", slotValues: { TIME: "Friday", ACTION: "finish the report" } },
        { en: "I have until 5 p.m. to submit the application.", bn: "আবেদন জমা দিতে আমার বিকাল ৫টা পর্যন্ত সময় আছে।", slotValues: { TIME: "5 p.m.", ACTION: "submit the application" } },
        { en: "I have until next week to decide.", bn: "সিদ্ধান্ত নিতে আমার আগামী সপ্তাহ পর্যন্ত সময় আছে।", slotValues: { TIME: "next week", ACTION: "decide" } },
        { en: "I have until tomorrow to pay the bill.", bn: "বিল দিতে আমার আগামীকাল পর্যন্ত সময় আছে।", slotValues: { TIME: "tomorrow", ACTION: "pay the bill" } },
        { en: "I have until the end of the month to move out.", bn: "বের হতে আমার মাসের শেষ পর্যন্ত সময় আছে।", slotValues: { TIME: "the end of the month", ACTION: "move out" } },
        { en: "I have until noon to register.", bn: "রেজিস্ট্রেশন করতে আমার দুপুর পর্যন্ত সময় আছে।", slotValues: { TIME: "noon", ACTION: "register" } },
        { en: "She has until Monday to return the book.", bn: "বই ফেরত দিতে তার সোমবার পর্যন্ত সময় আছে।", slotValues: { TIME: "Monday", ACTION: "return the book" } },
        { en: "We have until 10 a.m. to check out.", bn: "চেক আউট করতে আমাদের সকাল ১০টা পর্যন্ত সময় আছে।", slotValues: { TIME: "10 a.m.", ACTION: "check out" } },
        { en: "I have until March to complete the course.", bn: "কোর্স শেষ করতে আমার মার্চ পর্যন্ত সময় আছে।", slotValues: { TIME: "March", ACTION: "complete the course" } },
        { en: "He has until tonight to give an answer.", bn: "উত্তর দিতে তার আজ রাত পর্যন্ত সময় আছে।", slotValues: { TIME: "tonight", ACTION: "give an answer" } },
        { en: "I have until Wednesday to fix the bug.", bn: "বাগ ঠিক করতে আমার বুধবার পর্যন্ত সময় আছে।", slotValues: { TIME: "Wednesday", ACTION: "fix the bug" } },
        { en: "They have until June to finish construction.", bn: "নির্মাণ শেষ করতে তাদের জুন পর্যন্ত সময় আছে।", slotValues: { TIME: "June", ACTION: "finish construction" } },
        { en: "I have until 3 p.m. to pick up the package.", bn: "প্যাকেজ নিতে আমার বিকাল ৩টা পর্যন্ত সময় আছে।", slotValues: { TIME: "3 p.m.", ACTION: "pick up the package" } },
        { en: "We have until Saturday to RSVP.", bn: "RSVP করতে আমাদের শনিবার পর্যন্ত সময় আছে।", slotValues: { TIME: "Saturday", ACTION: "RSVP" } },
        { en: "I have until the 15th to renew my license.", bn: "লাইসেন্স নবায়ন করতে আমার ১৫ তারিখ পর্যন্ত সময় আছে।", slotValues: { TIME: "the 15th", ACTION: "renew my license" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "'Until' marks the deadline — the latest time by which the action must be done.",
      usageNote_bn:
        "'Until' সময়সীমা চিহ্নিত করে — সর্বশেষ সময় যার মধ্যে কাজটি সম্পন্ন করতে হবে।",
    },
    {
      id: "L5.3",
      formula: "[EVENT] starts at [TIME]",
      formula_bn: "[ইভেন্ট] [সময়]-এ শুরু হয়",
      patternName: "Event Start Time",
      patternName_bn: "ইভেন্ট শুরুর সময়",
      slots: [
        {
          name: "EVENT",
          description: "A scheduled activity",
          description_bn: "একটি নির্ধারিত কার্যকলাপ",
          acceptedTypes: ["noun_phrase", "event"],
          examples: ["The class", "The show", "The game"],
        },
        {
          name: "TIME",
          description: "Starting time",
          description_bn: "শুরুর সময়",
          acceptedTypes: ["time"],
          examples: ["9 a.m.", "7:30 p.m.", "noon"],
        },
      ],
      examples: [
        { en: "The class starts at 9 a.m.", bn: "ক্লাস সকাল ৯টায় শুরু হয়।", slotValues: { EVENT: "The class", TIME: "9 a.m." } },
        { en: "The show starts at 7:30 p.m.", bn: "অনুষ্ঠান সন্ধ্যা ৭:৩০-এ শুরু হয়।", slotValues: { EVENT: "The show", TIME: "7:30 p.m." } },
        { en: "The game starts at noon.", bn: "খেলা দুপুরে শুরু হয়।", slotValues: { EVENT: "The game", TIME: "noon" } },
        { en: "Work starts at 8 a.m. sharp.", bn: "কাজ ঠিক সকাল ৮টায় শুরু হয়।", slotValues: { EVENT: "Work", TIME: "8 a.m. sharp" } },
        { en: "The ceremony starts at 4 p.m.", bn: "অনুষ্ঠান বিকাল ৪টায় শুরু হয়।", slotValues: { EVENT: "The ceremony", TIME: "4 p.m." } },
        { en: "The bus service starts at 6 a.m.", bn: "বাস সার্ভিস সকাল ৬টায় শুরু হয়।", slotValues: { EVENT: "The bus service", TIME: "6 a.m." } },
        { en: "The movie starts at 3:15 p.m.", bn: "মুভি বিকাল ৩:১৫-এ শুরু হয়।", slotValues: { EVENT: "The movie", TIME: "3:15 p.m." } },
        { en: "Breakfast starts at 7 a.m.", bn: "সকালের নাস্তা সকাল ৭টায় শুরু হয়।", slotValues: { EVENT: "Breakfast", TIME: "7 a.m." } },
        { en: "The workshop starts at 10 a.m.", bn: "ওয়ার্কশপ সকাল ১০টায় শুরু হয়।", slotValues: { EVENT: "The workshop", TIME: "10 a.m." } },
        { en: "The exam starts at 2 p.m.", bn: "পরীক্ষা বিকাল ২টায় শুরু হয়।", slotValues: { EVENT: "The exam", TIME: "2 p.m." } },
        { en: "The concert starts at 8 p.m.", bn: "কনসার্ট রাত ৮টায় শুরু হয়।", slotValues: { EVENT: "The concert", TIME: "8 p.m." } },
        { en: "The flight starts boarding at 11 a.m.", bn: "ফ্লাইটে বোর্ডিং সকাল ১১টায় শুরু হয়।", slotValues: { EVENT: "The flight", TIME: "11 a.m." } },
        { en: "The sale starts at midnight.", bn: "সেল মধ্যরাতে শুরু হয়।", slotValues: { EVENT: "The sale", TIME: "midnight" } },
        { en: "The prayer starts at 1:30 p.m.", bn: "নামাজ দুপুর ১:৩০-এ শুরু হয়।", slotValues: { EVENT: "The prayer", TIME: "1:30 p.m." } },
        { en: "The training starts at 9:30 a.m.", bn: "প্রশিক্ষণ সকাল ৯:৩০-এ শুরু হয়।", slotValues: { EVENT: "The training", TIME: "9:30 a.m." } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Use 'starts at' to indicate the beginning time of a scheduled event.",
      usageNote_bn:
        "একটি নির্ধারিত ইভেন্টের শুরুর সময় বলতে 'starts at' ব্যবহার করুন।",
    },
    {
      id: "L5.4",
      formula: "The deadline is [DATE/TIME]",
      formula_bn: "সময়সীমা হলো [তারিখ/সময়]",
      patternName: "Stating a Deadline",
      patternName_bn: "সময়সীমা বলা",
      slots: [
        {
          name: "DATE/TIME",
          description: "When the deadline is",
          description_bn: "সময়সীমা কখন",
          acceptedTypes: ["time_expression", "time"],
          examples: ["next Friday", "May 1st", "tomorrow at 5 p.m."],
        },
      ],
      examples: [
        { en: "The deadline is next Friday.", bn: "সময়সীমা আগামী শুক্রবার।", slotValues: { "DATE/TIME": "next Friday" } },
        { en: "The deadline is May 1st.", bn: "সময়সীমা ১লা মে।", slotValues: { "DATE/TIME": "May 1st" } },
        { en: "The deadline is tomorrow at 5 p.m.", bn: "সময়সীমা আগামীকাল বিকাল ৫টা।", slotValues: { "DATE/TIME": "tomorrow at 5 p.m." } },
        { en: "The deadline is the end of this week.", bn: "সময়সীমা এই সপ্তাহের শেষ।", slotValues: { "DATE/TIME": "the end of this week" } },
        { en: "The deadline is in two days.", bn: "সময়সীমা দুই দিনের মধ্যে।", slotValues: { "DATE/TIME": "in two days" } },
        { en: "The deadline is March 31st.", bn: "সময়সীমা ৩১শে মার্চ।", slotValues: { "DATE/TIME": "March 31st" } },
        { en: "The deadline is tonight at midnight.", bn: "সময়সীমা আজ রাতে মধ্যরাতে।", slotValues: { "DATE/TIME": "tonight at midnight" } },
        { en: "The deadline is next Monday morning.", bn: "সময়সীমা আগামী সোমবার সকাল।", slotValues: { "DATE/TIME": "next Monday morning" } },
        { en: "The deadline is the 15th of this month.", bn: "সময়সীমা এই মাসের ১৫ তারিখ।", slotValues: { "DATE/TIME": "the 15th of this month" } },
        { en: "The deadline is January 10th.", bn: "সময়সীমা ১০ই জানুয়ারি।", slotValues: { "DATE/TIME": "January 10th" } },
        { en: "The deadline is this Wednesday.", bn: "সময়সীমা এই বুধবার।", slotValues: { "DATE/TIME": "this Wednesday" } },
        { en: "The deadline is at the end of the semester.", bn: "সময়সীমা সেমিস্টারের শেষে।", slotValues: { "DATE/TIME": "at the end of the semester" } },
        { en: "The deadline is in three hours.", bn: "সময়সীমা তিন ঘণ্টার মধ্যে।", slotValues: { "DATE/TIME": "in three hours" } },
        { en: "The deadline is December 25th.", bn: "সময়সীমা ২৫শে ডিসেম্বর।", slotValues: { "DATE/TIME": "December 25th" } },
        { en: "The deadline is next month.", bn: "সময়সীমা আগামী মাসে।", slotValues: { "DATE/TIME": "next month" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "A simple, direct way to state when something must be completed.",
      usageNote_bn:
        "কিছু কখন সম্পন্ন করতে হবে তা বলার একটি সরল, সরাসরি উপায়।",
    },
    {
      id: "L5.5",
      formula: "[EVENT] is from [TIME] to [TIME]",
      formula_bn: "[ইভেন্ট] [সময়] থেকে [সময়] পর্যন্ত",
      patternName: "Event Time Range",
      patternName_bn: "ইভেন্টের সময়সীমা",
      slots: [
        {
          name: "EVENT",
          description: "A scheduled activity",
          description_bn: "একটি নির্ধারিত কার্যকলাপ",
          acceptedTypes: ["noun_phrase", "event"],
          examples: ["The class", "Office hours", "The sale"],
        },
        {
          name: "TIME",
          description: "Start and end times",
          description_bn: "শুরু এবং শেষ সময়",
          acceptedTypes: ["time", "time_expression"],
          examples: ["9 a.m.", "5 p.m.", "Monday", "Friday"],
        },
      ],
      examples: [
        { en: "The class is from 9 a.m. to 11 a.m.", bn: "ক্লাস সকাল ৯টা থেকে ১১টা পর্যন্ত।", slotValues: { EVENT: "The class", TIME: "9 a.m. to 11 a.m." } },
        { en: "Office hours are from 8 a.m. to 5 p.m.", bn: "অফিসের সময় সকাল ৮টা থেকে বিকাল ৫টা পর্যন্ত।", slotValues: { EVENT: "Office hours", TIME: "8 a.m. to 5 p.m." } },
        { en: "The sale is from Monday to Friday.", bn: "সেল সোমবার থেকে শুক্রবার পর্যন্ত।", slotValues: { EVENT: "The sale", TIME: "Monday to Friday" } },
        { en: "Lunch break is from 12 to 1 p.m.", bn: "লাঞ্চ ব্রেক ১২টা থেকে ১টা পর্যন্ত।", slotValues: { EVENT: "Lunch break", TIME: "12 to 1 p.m." } },
        { en: "The exam is from 2 p.m. to 4 p.m.", bn: "পরীক্ষা বিকাল ২টা থেকে ৪টা পর্যন্ত।", slotValues: { EVENT: "The exam", TIME: "2 p.m. to 4 p.m." } },
        { en: "The workshop is from July 1st to July 5th.", bn: "ওয়ার্কশপ ১লা জুলাই থেকে ৫ই জুলাই পর্যন্ত।", slotValues: { EVENT: "The workshop", TIME: "July 1st to July 5th" } },
        { en: "The library is open from 8 a.m. to 9 p.m.", bn: "লাইব্রেরি সকাল ৮টা থেকে রাত ৯টা পর্যন্ত খোলা।", slotValues: { EVENT: "The library", TIME: "8 a.m. to 9 p.m." } },
        { en: "The training is from March to June.", bn: "প্রশিক্ষণ মার্চ থেকে জুন পর্যন্ত।", slotValues: { EVENT: "The training", TIME: "March to June" } },
        { en: "The festival is from the 10th to the 15th.", bn: "উৎসব ১০ তারিখ থেকে ১৫ তারিখ পর্যন্ত।", slotValues: { EVENT: "The festival", TIME: "the 10th to the 15th" } },
        { en: "The meeting is from 3 p.m. to 4:30 p.m.", bn: "মিটিং বিকাল ৩টা থেকে ৪:৩০ পর্যন্ত।", slotValues: { EVENT: "The meeting", TIME: "3 p.m. to 4:30 p.m." } },
        { en: "Summer vacation is from May to July.", bn: "গ্রীষ্মের ছুটি মে থেকে জুলাই পর্যন্ত।", slotValues: { EVENT: "Summer vacation", TIME: "May to July" } },
        { en: "The store is open from 10 a.m. to 8 p.m.", bn: "দোকান সকাল ১০টা থেকে রাত ৮টা পর্যন্ত খোলা।", slotValues: { EVENT: "The store", TIME: "10 a.m. to 8 p.m." } },
        { en: "The seminar is from 10 a.m. to 1 p.m.", bn: "সেমিনার সকাল ১০টা থেকে দুপুর ১টা পর্যন্ত।", slotValues: { EVENT: "The seminar", TIME: "10 a.m. to 1 p.m." } },
        { en: "The Ramadan holiday is from April 1st to April 3rd.", bn: "রমজানের ছুটি ১লা এপ্রিল থেকে ৩রা এপ্রিল পর্যন্ত।", slotValues: { EVENT: "The Ramadan holiday", TIME: "April 1st to April 3rd" } },
        { en: "The gym is open from 6 a.m. to 10 p.m.", bn: "জিম সকাল ৬টা থেকে রাত ১০টা পর্যন্ত খোলা।", slotValues: { EVENT: "The gym", TIME: "6 a.m. to 10 p.m." } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Use 'from...to...' to describe a time range when something occurs or is available.",
      usageNote_bn:
        "কিছু কখন ঘটে বা পাওয়া যায় তার সময়সীমা বর্ণনা করতে 'from...to...' ব্যবহার করুন।",
    },
  ],
};
