import { PatternCategory } from "@/types/pattern";

export const categoryL6: PatternCategory = {
  id: "L6",
  slug: "clock-calendar",
  name: "Clock & Calendar",
  name_bn: "ঘড়ি ও ক্যালেন্ডার",
  description:
    "Learn how to tell time and talk about days and dates.",
  description_bn:
    "সময় বলতে এবং দিন ও তারিখ সম্পর্কে কথা বলতে শিখুন।",
  icon: "🕐",
  group: "L",
  groupName: "Time Expression Patterns",
  groupName_bn: "সময় প্রকাশের প্যাটার্ন",
  difficulty: "beginner",
  patterns: [
    {
      id: "L6.1",
      formula: "It's [TIME]",
      formula_bn: "এখন [সময়]",
      patternName: "Telling the Time",
      patternName_bn: "সময় বলা",
      slots: [
        {
          name: "TIME",
          description: "The current time",
          description_bn: "বর্তমান সময়",
          acceptedTypes: ["time"],
          examples: ["3 o'clock", "half past 5", "quarter to 8"],
        },
      ],
      examples: [
        { en: "It's 3 o'clock.", bn: "এখন ৩টা বাজে।", slotValues: { TIME: "3 o'clock" } },
        { en: "It's half past 5.", bn: "এখন সাড়ে ৫টা বাজে।", slotValues: { TIME: "half past 5" } },
        { en: "It's quarter to 8.", bn: "এখন ৮টা বাজতে ১৫ মিনিট বাকি।", slotValues: { TIME: "quarter to 8" } },
        { en: "It's quarter past 9.", bn: "এখন সোয়া ৯টা বাজে।", slotValues: { TIME: "quarter past 9" } },
        { en: "It's 10:30 a.m.", bn: "এখন সকাল ১০:৩০।", slotValues: { TIME: "10:30 a.m." } },
        { en: "It's noon.", bn: "এখন দুপুর।", slotValues: { TIME: "noon" } },
        { en: "It's midnight.", bn: "এখন মধ্যরাত।", slotValues: { TIME: "midnight" } },
        { en: "It's five minutes to 7.", bn: "এখন ৭টা বাজতে ৫ মিনিট বাকি।", slotValues: { TIME: "five minutes to 7" } },
        { en: "It's twenty past 4.", bn: "এখন ৪টা বেজে ২০ মিনিট।", slotValues: { TIME: "twenty past 4" } },
        { en: "It's almost 6 o'clock.", bn: "এখন প্রায় ৬টা বাজে।", slotValues: { TIME: "almost 6 o'clock" } },
        { en: "It's exactly 2 p.m.", bn: "এখন ঠিক দুপুর ২টা।", slotValues: { TIME: "exactly 2 p.m." } },
        { en: "It's 7:45.", bn: "এখন ৭:৪৫।", slotValues: { TIME: "7:45" } },
        { en: "It's ten to 11.", bn: "এখন ১১টা বাজতে ১০ মিনিট বাকি।", slotValues: { TIME: "ten to 11" } },
        { en: "It's half past 12.", bn: "এখন সাড়ে ১২টা বাজে।", slotValues: { TIME: "half past 12" } },
        { en: "It's just after 1 o'clock.", bn: "এখন ১টা বেজে গেছে।", slotValues: { TIME: "just after 1 o'clock" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Use 'It's' to tell the current time. 'Past' = after the hour, 'to' = before the next hour.",
      usageNote_bn:
        "বর্তমান সময় বলতে 'It's' ব্যবহার করুন। 'Past' = ঘণ্টার পরে, 'to' = পরের ঘণ্টার আগে।",
    },
    {
      id: "L6.2",
      formula: "What time is it?",
      formula_bn: "এখন কয়টা বাজে?",
      patternName: "Asking the Time",
      patternName_bn: "সময় জিজ্ঞাসা করা",
      slots: [],
      examples: [
        { en: "What time is it?", bn: "এখন কয়টা বাজে?", slotValues: {} },
        { en: "What time is it now?", bn: "এখন কয়টা বাজে?", slotValues: {} },
        { en: "Excuse me, what time is it?", bn: "মাফ করবেন, এখন কয়টা বাজে?", slotValues: {} },
        { en: "Do you know what time it is?", bn: "আপনি কি জানেন এখন কয়টা বাজে?", slotValues: {} },
        { en: "Could you tell me the time?", bn: "আপনি কি সময়টা বলতে পারবেন?", slotValues: {} },
        { en: "Do you have the time?", bn: "আপনার কাছে কি সময় আছে?", slotValues: {} },
        { en: "What time is it? I think I'm late.", bn: "কয়টা বাজে? মনে হচ্ছে দেরি হয়ে গেছে।", slotValues: {} },
        { en: "What time is it? My watch stopped.", bn: "কয়টা বাজে? আমার ঘড়ি বন্ধ হয়ে গেছে।", slotValues: {} },
        { en: "What time is it in London right now?", bn: "এখন লন্ডনে কয়টা বাজে?", slotValues: {} },
        { en: "What time is it? Is it time for lunch?", bn: "কয়টা বাজে? লাঞ্চের সময় হয়েছে কি?", slotValues: {} },
        { en: "Hey, what time is it?", bn: "এই, কয়টা বাজে?", slotValues: {} },
        { en: "What time is it already?", bn: "কয়টা বেজে গেছে?", slotValues: {} },
        { en: "Can you check what time it is?", bn: "দেখবে কয়টা বাজে?", slotValues: {} },
        { en: "What time is it? I need to leave soon.", bn: "কয়টা বাজে? আমাকে শীঘ্রই যেতে হবে।", slotValues: {} },
        { en: "What time is it? The class starts at 10.", bn: "কয়টা বাজে? ক্লাস ১০টায় শুরু হয়।", slotValues: {} },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "The most common way to ask the time. 'Could you tell me the time?' is more polite.",
      usageNote_bn:
        "সময় জিজ্ঞাসা করার সবচেয়ে সাধারণ উপায়। 'Could you tell me the time?' আরও ভদ্র।",
    },
    {
      id: "L6.3",
      formula: "Today is [DAY], [DATE]",
      formula_bn: "আজ [দিন], [তারিখ]",
      patternName: "Stating the Day and Date",
      patternName_bn: "দিন ও তারিখ বলা",
      slots: [
        {
          name: "DAY",
          description: "Day of the week",
          description_bn: "সপ্তাহের দিন",
          acceptedTypes: ["time_expression"],
          examples: ["Monday", "Friday", "Sunday"],
        },
        {
          name: "DATE",
          description: "The calendar date",
          description_bn: "ক্যালেন্ডারের তারিখ",
          acceptedTypes: ["time_expression"],
          examples: ["March 6th", "January 1st", "the 15th of July"],
        },
      ],
      examples: [
        { en: "Today is Monday, March 6th.", bn: "আজ সোমবার, ৬ই মার্চ।", slotValues: { DAY: "Monday", DATE: "March 6th" } },
        { en: "Today is Friday, January 1st.", bn: "আজ শুক্রবার, ১লা জানুয়ারি।", slotValues: { DAY: "Friday", DATE: "January 1st" } },
        { en: "Today is Sunday, the 15th of July.", bn: "আজ রবিবার, ১৫ই জুলাই।", slotValues: { DAY: "Sunday", DATE: "the 15th of July" } },
        { en: "Today is Wednesday, April 10th.", bn: "আজ বুধবার, ১০ই এপ্রিল।", slotValues: { DAY: "Wednesday", DATE: "April 10th" } },
        { en: "Today is Thursday, November 25th.", bn: "আজ বৃহস্পতিবার, ২৫শে নভেম্বর।", slotValues: { DAY: "Thursday", DATE: "November 25th" } },
        { en: "Today is Saturday, December 31st.", bn: "আজ শনিবার, ৩১শে ডিসেম্বর।", slotValues: { DAY: "Saturday", DATE: "December 31st" } },
        { en: "Today is Tuesday, February 14th.", bn: "আজ মঙ্গলবার, ১৪ই ফেব্রুয়ারি।", slotValues: { DAY: "Tuesday", DATE: "February 14th" } },
        { en: "Today is Monday, August 21st.", bn: "আজ সোমবার, ২১শে আগস্ট।", slotValues: { DAY: "Monday", DATE: "August 21st" } },
        { en: "Today is Friday, October 3rd.", bn: "আজ শুক্রবার, ৩রা অক্টোবর।", slotValues: { DAY: "Friday", DATE: "October 3rd" } },
        { en: "Today is Sunday, May 1st.", bn: "আজ রবিবার, ১লা মে।", slotValues: { DAY: "Sunday", DATE: "May 1st" } },
        { en: "Today is Wednesday, September 9th.", bn: "আজ বুধবার, ৯ই সেপ্টেম্বর।", slotValues: { DAY: "Wednesday", DATE: "September 9th" } },
        { en: "Today is Thursday, June 20th.", bn: "আজ বৃহস্পতিবার, ২০শে জুন।", slotValues: { DAY: "Thursday", DATE: "June 20th" } },
        { en: "Today is Saturday, March 26th.", bn: "আজ শনিবার, ২৬শে মার্চ।", slotValues: { DAY: "Saturday", DATE: "March 26th" } },
        { en: "Today is Tuesday, the 8th of April.", bn: "আজ মঙ্গলবার, ৮ই এপ্রিল।", slotValues: { DAY: "Tuesday", DATE: "the 8th of April" } },
        { en: "Today is Monday, the 2nd of January.", bn: "আজ সোমবার, ২রা জানুয়ারি।", slotValues: { DAY: "Monday", DATE: "the 2nd of January" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Use this pattern to state the current day and date. In English, the day of the week usually comes before the date.",
      usageNote_bn:
        "বর্তমান দিন ও তারিখ বলতে এই প্যাটার্ন ব্যবহার করুন। ইংরেজিতে সাধারণত সপ্তাহের দিন তারিখের আগে আসে।",
    },
    {
      id: "L6.4",
      formula: "What day is it today?",
      formula_bn: "আজ কী বার?",
      patternName: "Asking the Day",
      patternName_bn: "দিন জিজ্ঞাসা করা",
      slots: [],
      examples: [
        { en: "What day is it today?", bn: "আজ কী বার?", slotValues: {} },
        { en: "What day is it? I've lost track.", bn: "আজ কী বার? আমি হিসাব হারিয়ে ফেলেছি।", slotValues: {} },
        { en: "Is today Monday or Tuesday?", bn: "আজ কি সোমবার নাকি মঙ্গলবার?", slotValues: {} },
        { en: "What's today's date?", bn: "আজকের তারিখ কত?", slotValues: {} },
        { en: "What day of the week is it?", bn: "সপ্তাহের কোন দিন আজ?", slotValues: {} },
        { en: "Do you know what day it is today?", bn: "তুমি কি জানো আজ কী বার?", slotValues: {} },
        { en: "What's the date today?", bn: "আজকের তারিখ কত?", slotValues: {} },
        { en: "Is it Friday already?", bn: "শুক্রবার হয়ে গেছে?", slotValues: {} },
        { en: "What day is tomorrow?", bn: "আগামীকাল কী বার?", slotValues: {} },
        { en: "Is today a holiday?", bn: "আজ কি ছুটির দিন?", slotValues: {} },
        { en: "What month are we in?", bn: "এখন কোন মাস চলছে?", slotValues: {} },
        { en: "Is today the 5th or the 6th?", bn: "আজ কি ৫ তারিখ নাকি ৬ তারিখ?", slotValues: {} },
        { en: "What year is it?", bn: "এখন কোন সাল?", slotValues: {} },
        { en: "What day was yesterday?", bn: "গতকাল কী বার ছিল?", slotValues: {} },
        { en: "Is today a weekday or weekend?", bn: "আজ কি কর্মদিবস নাকি সপ্তাহান্ত?", slotValues: {} },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Use these questions to ask about the current day, date, or month.",
      usageNote_bn:
        "বর্তমান দিন, তারিখ বা মাস সম্পর্কে জিজ্ঞাসা করতে এই প্রশ্নগুলো ব্যবহার করুন।",
    },
    {
      id: "L6.5",
      formula: "It's [MONTH/SEASON] now",
      formula_bn: "এখন [মাস/ঋতু]",
      patternName: "Current Month or Season",
      patternName_bn: "বর্তমান মাস বা ঋতু",
      slots: [
        {
          name: "MONTH/SEASON",
          description: "Current month or season",
          description_bn: "বর্তমান মাস বা ঋতু",
          acceptedTypes: ["time_expression"],
          examples: ["March", "summer", "winter", "the rainy season"],
        },
      ],
      examples: [
        { en: "It's March now.", bn: "এখন মার্চ মাস।", slotValues: { "MONTH/SEASON": "March" } },
        { en: "It's summer now.", bn: "এখন গ্রীষ্মকাল।", slotValues: { "MONTH/SEASON": "summer" } },
        { en: "It's winter now.", bn: "এখন শীতকাল।", slotValues: { "MONTH/SEASON": "winter" } },
        { en: "It's the rainy season now.", bn: "এখন বর্ষাকাল।", slotValues: { "MONTH/SEASON": "the rainy season" } },
        { en: "It's January now. Happy New Year!", bn: "এখন জানুয়ারি মাস। শুভ নববর্ষ!", slotValues: { "MONTH/SEASON": "January" } },
        { en: "It's spring now. The flowers are blooming.", bn: "এখন বসন্তকাল। ফুল ফুটছে।", slotValues: { "MONTH/SEASON": "spring" } },
        { en: "It's autumn now. The leaves are falling.", bn: "এখন শরৎকাল। পাতা ঝরছে।", slotValues: { "MONTH/SEASON": "autumn" } },
        { en: "It's December now. Christmas is coming.", bn: "এখন ডিসেম্বর মাস। ক্রিসমাস আসছে।", slotValues: { "MONTH/SEASON": "December" } },
        { en: "It's Ramadan now.", bn: "এখন রমজান মাস।", slotValues: { "MONTH/SEASON": "Ramadan" } },
        { en: "It's February now. It's still cold.", bn: "এখন ফেব্রুয়ারি মাস। এখনো ঠান্ডা।", slotValues: { "MONTH/SEASON": "February" } },
        { en: "It's October now. The weather is nice.", bn: "এখন অক্টোবর মাস। আবহাওয়া ভালো।", slotValues: { "MONTH/SEASON": "October" } },
        { en: "It's the harvest season now.", bn: "এখন ফসল কাটার মৌসুম।", slotValues: { "MONTH/SEASON": "the harvest season" } },
        { en: "It's April now. Spring is here.", bn: "এখন এপ্রিল মাস। বসন্ত এসেছে।", slotValues: { "MONTH/SEASON": "April" } },
        { en: "It's the monsoon season now.", bn: "এখন বর্ষা মৌসুম।", slotValues: { "MONTH/SEASON": "the monsoon season" } },
        { en: "It's July now. Schools are on vacation.", bn: "এখন জুলাই মাস। স্কুলে ছুটি চলছে।", slotValues: { "MONTH/SEASON": "July" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "A simple way to state the current month or season.",
      usageNote_bn:
        "বর্তমান মাস বা ঋতু বলার একটি সহজ উপায়।",
    },
  ],
};
