import { PatternCategory } from "@/types/pattern";

export const categoryM1: PatternCategory = {
  id: "M1",
  slug: "location-prepositions",
  name: "Location Prepositions (At/In/On)",
  name_bn: "অবস্থানের অব্যয় (At/In/On)",
  description:
    "Master when to use at, in, and on to describe locations.",
  description_bn:
    "অবস্থান বর্ণনায় at, in, on এর সঠিক ব্যবহার শিখুন।",
  icon: "📍",
  group: "M",
  groupName: "Place & Preposition Patterns",
  groupName_bn: "স্থান ও অব্যয়ের প্যাটার্ন",
  difficulty: "beginner",
  patterns: [
    {
      id: "M1.1",
      formula: "[THING] is at [SPECIFIC PLACE]",
      formula_bn: "[জিনিস] [নির্দিষ্ট স্থানে] আছে",
      patternName: "At + Specific Location",
      patternName_bn: "At + নির্দিষ্ট স্থান",
      slots: [
        {
          name: "THING",
          description: "A person or object",
          description_bn: "একটি ব্যক্তি বা বস্তু",
          acceptedTypes: ["noun", "noun_phrase", "person"],
          examples: ["He", "The meeting", "She"],
        },
        {
          name: "SPECIFIC PLACE",
          description: "A specific point or location",
          description_bn: "একটি নির্দিষ্ট বিন্দু বা স্থান",
          acceptedTypes: ["place"],
          examples: ["the bus stop", "the airport", "home", "school"],
        },
      ],
      examples: [
        { en: "He is at the bus stop.", bn: "সে বাস স্টপে আছে।", slotValues: { THING: "He", "SPECIFIC PLACE": "the bus stop" } },
        { en: "She is at the airport.", bn: "সে বিমানবন্দরে আছে।", slotValues: { THING: "She", "SPECIFIC PLACE": "the airport" } },
        { en: "I am at home.", bn: "আমি বাড়িতে আছি।", slotValues: { THING: "I", "SPECIFIC PLACE": "home" } },
        { en: "The children are at school.", bn: "বাচ্চারা স্কুলে আছে।", slotValues: { THING: "The children", "SPECIFIC PLACE": "school" } },
        { en: "We are at the hospital.", bn: "আমরা হাসপাতালে আছি।", slotValues: { THING: "We", "SPECIFIC PLACE": "the hospital" } },
        { en: "The meeting is at the office.", bn: "মিটিং অফিসে।", slotValues: { THING: "The meeting", "SPECIFIC PLACE": "the office" } },
        { en: "He is at the door.", bn: "সে দরজায় আছে।", slotValues: { THING: "He", "SPECIFIC PLACE": "the door" } },
        { en: "She is at the reception desk.", bn: "সে রিসেপশন ডেস্কে আছে।", slotValues: { THING: "She", "SPECIFIC PLACE": "the reception desk" } },
        { en: "They are at the restaurant.", bn: "তারা রেস্তোরাঁয় আছে।", slotValues: { THING: "They", "SPECIFIC PLACE": "the restaurant" } },
        { en: "I'll be at the station.", bn: "আমি স্টেশনে থাকব।", slotValues: { THING: "I", "SPECIFIC PLACE": "the station" } },
        { en: "The taxi is at the gate.", bn: "ট্যাক্সি গেটে আছে।", slotValues: { THING: "The taxi", "SPECIFIC PLACE": "the gate" } },
        { en: "My father is at work.", bn: "আমার বাবা কর্মস্থলে আছেন।", slotValues: { THING: "My father", "SPECIFIC PLACE": "work" } },
        { en: "The party is at his house.", bn: "পার্টি তার বাড়িতে।", slotValues: { THING: "The party", "SPECIFIC PLACE": "his house" } },
        { en: "We met at the market.", bn: "আমরা বাজারে দেখা করেছি।", slotValues: { THING: "We", "SPECIFIC PLACE": "the market" } },
        { en: "She is at the checkout counter.", bn: "সে চেকআউট কাউন্টারে আছে।", slotValues: { THING: "She", "SPECIFIC PLACE": "the checkout counter" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Use 'at' for specific points or locations. It treats a place as a single point rather than an enclosed space.",
      usageNote_bn:
        "নির্দিষ্ট বিন্দু বা স্থানের জন্য 'at' ব্যবহার করুন। এটি স্থানকে আবদ্ধ জায়গার বদলে একটি একক বিন্দু হিসেবে দেখে।",
    },
    {
      id: "M1.2",
      formula: "[THING] is in [ENCLOSED SPACE]",
      formula_bn: "[জিনিস] [আবদ্ধ স্থানে] আছে",
      patternName: "In + Enclosed Space",
      patternName_bn: "In + আবদ্ধ স্থান",
      slots: [
        {
          name: "THING",
          description: "A person or object",
          description_bn: "একটি ব্যক্তি বা বস্তু",
          acceptedTypes: ["noun", "noun_phrase", "person"],
          examples: ["The keys", "She", "The cat"],
        },
        {
          name: "ENCLOSED SPACE",
          description: "An enclosed or bounded area",
          description_bn: "একটি আবদ্ধ বা সীমাবদ্ধ এলাকা",
          acceptedTypes: ["place"],
          examples: ["the box", "the room", "the car", "Dhaka"],
        },
      ],
      examples: [
        { en: "The keys are in my pocket.", bn: "চাবিগুলো আমার পকেটে আছে।", slotValues: { THING: "The keys", "ENCLOSED SPACE": "my pocket" } },
        { en: "She is in the kitchen.", bn: "সে রান্নাঘরে আছে।", slotValues: { THING: "She", "ENCLOSED SPACE": "the kitchen" } },
        { en: "The cat is in the box.", bn: "বিড়ালটি বাক্সে আছে।", slotValues: { THING: "The cat", "ENCLOSED SPACE": "the box" } },
        { en: "He lives in Dhaka.", bn: "সে ঢাকায় থাকে।", slotValues: { THING: "He", "ENCLOSED SPACE": "Dhaka" } },
        { en: "The milk is in the fridge.", bn: "দুধ ফ্রিজে আছে।", slotValues: { THING: "The milk", "ENCLOSED SPACE": "the fridge" } },
        { en: "The children are in the garden.", bn: "বাচ্চারা বাগানে আছে।", slotValues: { THING: "The children", "ENCLOSED SPACE": "the garden" } },
        { en: "My phone is in my bag.", bn: "আমার ফোন ব্যাগে আছে।", slotValues: { THING: "My phone", "ENCLOSED SPACE": "my bag" } },
        { en: "The money is in the drawer.", bn: "টাকা ড্রয়ারে আছে।", slotValues: { THING: "The money", "ENCLOSED SPACE": "the drawer" } },
        { en: "We are in the classroom.", bn: "আমরা শ্রেণিকক্ষে আছি।", slotValues: { THING: "We", "ENCLOSED SPACE": "the classroom" } },
        { en: "The dog is in the yard.", bn: "কুকুরটি উঠোনে আছে।", slotValues: { THING: "The dog", "ENCLOSED SPACE": "the yard" } },
        { en: "He is in the car.", bn: "সে গাড়িতে আছে।", slotValues: { THING: "He", "ENCLOSED SPACE": "the car" } },
        { en: "The book is in my backpack.", bn: "বইটি আমার ব্যাকপ্যাকে আছে।", slotValues: { THING: "The book", "ENCLOSED SPACE": "my backpack" } },
        { en: "She was born in Bangladesh.", bn: "সে বাংলাদেশে জন্মেছিল।", slotValues: { THING: "She", "ENCLOSED SPACE": "Bangladesh" } },
        { en: "The fish is in the pond.", bn: "মাছ পুকুরে আছে।", slotValues: { THING: "The fish", "ENCLOSED SPACE": "the pond" } },
        { en: "The clothes are in the wardrobe.", bn: "জামাকাপড় আলমারিতে আছে।", slotValues: { THING: "The clothes", "ENCLOSED SPACE": "the wardrobe" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Use 'in' for enclosed or bounded spaces — rooms, buildings, cities, countries, containers.",
      usageNote_bn:
        "আবদ্ধ বা সীমাবদ্ধ স্থানের জন্য 'in' ব্যবহার করুন — ঘর, ভবন, শহর, দেশ, পাত্র।",
    },
    {
      id: "M1.3",
      formula: "[THING] is on [SURFACE]",
      formula_bn: "[জিনিস] [পৃষ্ঠে] আছে",
      patternName: "On + Surface",
      patternName_bn: "On + পৃষ্ঠ",
      slots: [
        {
          name: "THING",
          description: "A person or object",
          description_bn: "একটি ব্যক্তি বা বস্তু",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["The book", "The cup", "The painting"],
        },
        {
          name: "SURFACE",
          description: "A flat surface or top",
          description_bn: "একটি সমতল পৃষ্ঠ বা উপরিভাগ",
          acceptedTypes: ["place", "noun_phrase"],
          examples: ["the table", "the wall", "the floor", "the shelf"],
        },
      ],
      examples: [
        { en: "The book is on the table.", bn: "বইটি টেবিলের উপর আছে।", slotValues: { THING: "The book", SURFACE: "the table" } },
        { en: "The cup is on the counter.", bn: "কাপটি কাউন্টারের উপর আছে।", slotValues: { THING: "The cup", SURFACE: "the counter" } },
        { en: "The painting is on the wall.", bn: "ছবিটি দেয়ালে আছে।", slotValues: { THING: "The painting", SURFACE: "the wall" } },
        { en: "The cat is on the roof.", bn: "বিড়ালটি ছাদের উপর আছে।", slotValues: { THING: "The cat", SURFACE: "the roof" } },
        { en: "The phone is on the desk.", bn: "ফোনটি ডেস্কের উপর আছে।", slotValues: { THING: "The phone", SURFACE: "the desk" } },
        { en: "The rug is on the floor.", bn: "গালিচাটি মেঝেতে আছে।", slotValues: { THING: "The rug", SURFACE: "the floor" } },
        { en: "There's a sticker on the laptop.", bn: "ল্যাপটপের উপর একটি স্টিকার আছে।", slotValues: { THING: "A sticker", SURFACE: "the laptop" } },
        { en: "The food is on the plate.", bn: "খাবার প্লেটের উপর আছে।", slotValues: { THING: "The food", SURFACE: "the plate" } },
        { en: "The towel is on the bed.", bn: "তোয়ালে বিছানার উপর আছে।", slotValues: { THING: "The towel", SURFACE: "the bed" } },
        { en: "The clock is on the wall.", bn: "ঘড়িটি দেয়ালে আছে।", slotValues: { THING: "The clock", SURFACE: "the wall" } },
        { en: "The shoes are on the shelf.", bn: "জুতাগুলো তাকে আছে।", slotValues: { THING: "The shoes", SURFACE: "the shelf" } },
        { en: "The newspaper is on the sofa.", bn: "পত্রিকাটি সোফার উপর আছে।", slotValues: { THING: "The newspaper", SURFACE: "the sofa" } },
        { en: "There's dust on the mirror.", bn: "আয়নায় ধুলো আছে।", slotValues: { THING: "Dust", SURFACE: "the mirror" } },
        { en: "The vase is on the windowsill.", bn: "ফুলদানিটি জানালার তাকে আছে।", slotValues: { THING: "The vase", SURFACE: "the windowsill" } },
        { en: "The map is on the wall.", bn: "মানচিত্রটি দেয়ালে আছে।", slotValues: { THING: "The map", SURFACE: "the wall" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Use 'on' when something is touching a surface — tables, walls, floors, shelves.",
      usageNote_bn:
        "কিছু যখন কোনো পৃষ্ঠ স্পর্শ করছে তখন 'on' ব্যবহার করুন — টেবিল, দেয়াল, মেঝে, তাক।",
    },
    {
      id: "M1.4",
      formula: "[THING] is next to [PLACE]",
      formula_bn: "[জিনিস] [স্থানের] পাশে আছে",
      patternName: "Next To + Location",
      patternName_bn: "পাশে + অবস্থান",
      slots: [
        {
          name: "THING",
          description: "A person or object",
          description_bn: "একটি ব্যক্তি বা বস্তু",
          acceptedTypes: ["noun", "noun_phrase", "person"],
          examples: ["The bank", "My house", "The park"],
        },
        {
          name: "PLACE",
          description: "A reference location",
          description_bn: "একটি রেফারেন্স স্থান",
          acceptedTypes: ["place", "noun_phrase"],
          examples: ["the post office", "the school", "the river"],
        },
      ],
      examples: [
        { en: "The bank is next to the post office.", bn: "ব্যাংক পোস্ট অফিসের পাশে।", slotValues: { THING: "The bank", PLACE: "the post office" } },
        { en: "My house is next to the school.", bn: "আমার বাড়ি স্কুলের পাশে।", slotValues: { THING: "My house", PLACE: "the school" } },
        { en: "The park is next to the hospital.", bn: "পার্ক হাসপাতালের পাশে।", slotValues: { THING: "The park", PLACE: "the hospital" } },
        { en: "Sit next to me.", bn: "আমার পাশে বসো।", slotValues: { THING: "You", PLACE: "me" } },
        { en: "The pharmacy is next to the clinic.", bn: "ফার্মেসি ক্লিনিকের পাশে।", slotValues: { THING: "The pharmacy", PLACE: "the clinic" } },
        { en: "The lamp is next to the bed.", bn: "বাতিটি বিছানার পাশে।", slotValues: { THING: "The lamp", PLACE: "the bed" } },
        { en: "The supermarket is next to the gas station.", bn: "সুপারমার্কেট গ্যাস স্টেশনের পাশে।", slotValues: { THING: "The supermarket", PLACE: "the gas station" } },
        { en: "He sat next to his friend.", bn: "সে তার বন্ধুর পাশে বসেছিল।", slotValues: { THING: "He", PLACE: "his friend" } },
        { en: "The chair is next to the window.", bn: "চেয়ারটি জানালার পাশে।", slotValues: { THING: "The chair", PLACE: "the window" } },
        { en: "The mosque is next to the library.", bn: "মসজিদ লাইব্রেরির পাশে।", slotValues: { THING: "The mosque", PLACE: "the library" } },
        { en: "Our car is parked next to yours.", bn: "আমাদের গাড়ি তোমার গাড়ির পাশে পার্ক করা।", slotValues: { THING: "Our car", PLACE: "yours" } },
        { en: "The café is next to the bookshop.", bn: "ক্যাফে বইয়ের দোকানের পাশে।", slotValues: { THING: "The café", PLACE: "the bookshop" } },
        { en: "The garden is next to the main road.", bn: "বাগান মূল রাস্তার পাশে।", slotValues: { THING: "The garden", PLACE: "the main road" } },
        { en: "The ATM is next to the entrance.", bn: "ATM প্রবেশদ্বারের পাশে।", slotValues: { THING: "The ATM", PLACE: "the entrance" } },
        { en: "Put the glass next to the plate.", bn: "গ্লাসটি প্লেটের পাশে রাখো।", slotValues: { THING: "The glass", PLACE: "the plate" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "'Next to' means beside or immediately adjacent to something.",
      usageNote_bn:
        "'Next to' মানে কোনো কিছুর পাশে বা ঠিক পাশে।",
    },
    {
      id: "M1.5",
      formula: "[THING] is between [PLACE] and [PLACE]",
      formula_bn: "[জিনিস] [স্থান] এবং [স্থানের] মাঝে আছে",
      patternName: "Between + Two Places",
      patternName_bn: "মাঝে + দুটি স্থান",
      slots: [
        {
          name: "THING",
          description: "A person or object in the middle",
          description_bn: "মাঝখানে থাকা ব্যক্তি বা বস্তু",
          acceptedTypes: ["noun", "noun_phrase", "person"],
          examples: ["The park", "My seat", "The shop"],
        },
        {
          name: "PLACE",
          description: "Two reference points on either side",
          description_bn: "দুই পাশের দুটি রেফারেন্স বিন্দু",
          acceptedTypes: ["place", "noun_phrase"],
          examples: ["the bank", "the school", "the mosque"],
        },
      ],
      examples: [
        { en: "The park is between the bank and the school.", bn: "পার্কটি ব্যাংক এবং স্কুলের মাঝে।", slotValues: { THING: "The park", PLACE: "the bank and the school" } },
        { en: "My house is between the mosque and the market.", bn: "আমার বাড়ি মসজিদ এবং বাজারের মাঝে।", slotValues: { THING: "My house", PLACE: "the mosque and the market" } },
        { en: "The shop is between two restaurants.", bn: "দোকানটি দুটি রেস্তোরাঁর মাঝে।", slotValues: { THING: "The shop", PLACE: "two restaurants" } },
        { en: "I sat between my parents.", bn: "আমি আমার বাবা-মায়ের মাঝে বসেছিলাম।", slotValues: { THING: "I", PLACE: "my parents" } },
        { en: "The river flows between the two cities.", bn: "নদীটি দুটি শহরের মাঝে প্রবাহিত হয়।", slotValues: { THING: "The river", PLACE: "the two cities" } },
        { en: "The library is between the gym and the cafeteria.", bn: "লাইব্রেরি জিম এবং ক্যাফেটেরিয়ার মাঝে।", slotValues: { THING: "The library", PLACE: "the gym and the cafeteria" } },
        { en: "The road is between the fields.", bn: "রাস্তাটি মাঠগুলোর মাঝে।", slotValues: { THING: "The road", PLACE: "the fields" } },
        { en: "The hotel is between the airport and the beach.", bn: "হোটেল বিমানবন্দর এবং সৈকতের মাঝে।", slotValues: { THING: "The hotel", PLACE: "the airport and the beach" } },
        { en: "Put the table between the two chairs.", bn: "টেবিলটি দুটি চেয়ারের মাঝে রাখো।", slotValues: { THING: "The table", PLACE: "the two chairs" } },
        { en: "The pharmacy is between the hospital and the park.", bn: "ফার্মেসি হাসপাতাল এবং পার্কের মাঝে।", slotValues: { THING: "The pharmacy", PLACE: "the hospital and the park" } },
        { en: "The garden is between our house and the neighbor's.", bn: "বাগানটি আমাদের বাড়ি এবং প্রতিবেশীর বাড়ির মাঝে।", slotValues: { THING: "The garden", PLACE: "our house and the neighbor's" } },
        { en: "The bus stop is between the school and the store.", bn: "বাস স্টপ স্কুল এবং দোকানের মাঝে।", slotValues: { THING: "The bus stop", PLACE: "the school and the store" } },
        { en: "The bridge is between the two villages.", bn: "সেতুটি দুটি গ্রামের মাঝে।", slotValues: { THING: "The bridge", PLACE: "the two villages" } },
        { en: "My office is between a café and a bookshop.", bn: "আমার অফিস একটি ক্যাফে এবং একটি বইয়ের দোকানের মাঝে।", slotValues: { THING: "My office", PLACE: "a café and a bookshop" } },
        { en: "The child sat between her parents.", bn: "শিশুটি তার বাবা-মায়ের মাঝে বসেছিল।", slotValues: { THING: "The child", PLACE: "her parents" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "'Between' is used when something is in the middle of two reference points. Always use 'and' with 'between'.",
      usageNote_bn:
        "'Between' ব্যবহার করা হয় যখন কিছু দুটি রেফারেন্স বিন্দুর মাঝে থাকে। 'between' এর সাথে সবসময় 'and' ব্যবহার করুন।",
    },
  ],
};
