import { PatternCategory } from "@/types/pattern";

export const categoryM5: PatternCategory = {
  id: "M5",
  slug: "origin-destination",
  name: "Origin & Destination",
  name_bn: "উৎপত্তি ও গন্তব্য",
  description:
    "Learn to talk about where you come from and where you are going.",
  description_bn:
    "আপনি কোথা থেকে এসেছেন এবং কোথায় যাচ্ছেন তা বলতে শিখুন।",
  icon: "✈️",
  group: "M",
  groupName: "Place & Preposition Patterns",
  groupName_bn: "স্থান ও অব্যয়ের প্যাটার্ন",
  difficulty: "beginner",
  patterns: [
    {
      id: "M5.1",
      formula: "I'm from [PLACE]",
      formula_bn: "আমি [স্থান] থেকে এসেছি",
      patternName: "Stating Origin",
      patternName_bn: "উৎপত্তি বলা",
      slots: [
        {
          name: "PLACE",
          description: "Your hometown, city, or country",
          description_bn: "আপনার জন্মস্থান, শহর বা দেশ",
          acceptedTypes: ["place"],
          examples: ["Dhaka", "Bangladesh", "Sylhet"],
        },
      ],
      examples: [
        { en: "I'm from Bangladesh.", bn: "আমি বাংলাদেশ থেকে এসেছি।", slotValues: { PLACE: "Bangladesh" } },
        { en: "I'm from Dhaka.", bn: "আমি ঢাকা থেকে এসেছি।", slotValues: { PLACE: "Dhaka" } },
        { en: "I'm from Sylhet.", bn: "আমি সিলেট থেকে এসেছি।", slotValues: { PLACE: "Sylhet" } },
        { en: "She's from Chittagong.", bn: "সে চট্টগ্রাম থেকে এসেছে।", slotValues: { PLACE: "Chittagong" } },
        { en: "He's from a small village.", bn: "সে একটি ছোট গ্রাম থেকে এসেছে।", slotValues: { PLACE: "a small village" } },
        { en: "We're from Rajshahi.", bn: "আমরা রাজশাহী থেকে এসেছি।", slotValues: { PLACE: "Rajshahi" } },
        { en: "They're from India.", bn: "তারা ভারত থেকে এসেছে।", slotValues: { PLACE: "India" } },
        { en: "I'm originally from Khulna.", bn: "আমি মূলত খুলনা থেকে।", slotValues: { PLACE: "Khulna" } },
        { en: "She's from the United States.", bn: "সে যুক্তরাষ্ট্র থেকে এসেছে।", slotValues: { PLACE: "the United States" } },
        { en: "I'm from a town near Comilla.", bn: "আমি কুমিল্লার কাছে একটি শহর থেকে এসেছি।", slotValues: { PLACE: "a town near Comilla" } },
        { en: "He's from London.", bn: "সে লন্ডন থেকে এসেছে।", slotValues: { PLACE: "London" } },
        { en: "We're from the same city.", bn: "আমরা একই শহর থেকে।", slotValues: { PLACE: "the same city" } },
        { en: "I'm from the northern part of the country.", bn: "আমি দেশের উত্তরাঞ্চল থেকে এসেছি।", slotValues: { PLACE: "the northern part of the country" } },
        { en: "She's from a coastal area.", bn: "সে উপকূলীয় এলাকা থেকে এসেছে।", slotValues: { PLACE: "a coastal area" } },
        { en: "I'm from Barisal, near the rivers.", bn: "আমি বরিশাল থেকে, নদীগুলোর কাছে।", slotValues: { PLACE: "Barisal" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Use 'I'm from' to tell someone your hometown or country of origin.",
      usageNote_bn:
        "কাউকে আপনার জন্মস্থান বা দেশ বলতে 'I'm from' ব্যবহার করুন।",
    },
    {
      id: "M5.2",
      formula: "I'm headed to [PLACE]",
      formula_bn: "আমি [স্থানে] যাচ্ছি",
      patternName: "Stating Destination",
      patternName_bn: "গন্তব্য বলা",
      slots: [
        {
          name: "PLACE",
          description: "Where you are going",
          description_bn: "আপনি কোথায় যাচ্ছেন",
          acceptedTypes: ["place"],
          examples: ["the office", "home", "the airport"],
        },
      ],
      examples: [
        { en: "I'm headed to the office.", bn: "আমি অফিসে যাচ্ছি।", slotValues: { PLACE: "the office" } },
        { en: "I'm headed to home.", bn: "আমি বাড়ি যাচ্ছি।", slotValues: { PLACE: "home" } },
        { en: "I'm headed to the airport.", bn: "আমি বিমানবন্দরে যাচ্ছি।", slotValues: { PLACE: "the airport" } },
        { en: "She's headed to the market.", bn: "সে বাজারে যাচ্ছে।", slotValues: { PLACE: "the market" } },
        { en: "We're headed to the restaurant.", bn: "আমরা রেস্তোরাঁয় যাচ্ছি।", slotValues: { PLACE: "the restaurant" } },
        { en: "He's headed to the gym.", bn: "সে জিমে যাচ্ছে।", slotValues: { PLACE: "the gym" } },
        { en: "I'm headed to Chittagong.", bn: "আমি চট্টগ্রামে যাচ্ছি।", slotValues: { PLACE: "Chittagong" } },
        { en: "They're headed to the hospital.", bn: "তারা হাসপাতালে যাচ্ছে।", slotValues: { PLACE: "the hospital" } },
        { en: "I'm headed to the library.", bn: "আমি লাইব্রেরিতে যাচ্ছি।", slotValues: { PLACE: "the library" } },
        { en: "She's headed to her friend's house.", bn: "সে তার বন্ধুর বাড়িতে যাচ্ছে।", slotValues: { PLACE: "her friend's house" } },
        { en: "We're headed to the beach for the weekend.", bn: "আমরা সপ্তাহান্তে সৈকতে যাচ্ছি।", slotValues: { PLACE: "the beach" } },
        { en: "I'm headed to the bank before it closes.", bn: "বন্ধ হওয়ার আগে আমি ব্যাংকে যাচ্ছি।", slotValues: { PLACE: "the bank" } },
        { en: "He's headed to the train station.", bn: "সে ট্রেন স্টেশনে যাচ্ছে।", slotValues: { PLACE: "the train station" } },
        { en: "I'm headed to a meeting.", bn: "আমি একটি মিটিংয়ে যাচ্ছি।", slotValues: { PLACE: "a meeting" } },
        { en: "We're headed to the park after lunch.", bn: "দুপুরের খাবারের পর আমরা পার্কে যাচ্ছি।", slotValues: { PLACE: "the park" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "'I'm headed to' is a casual way to say where you're going right now.",
      usageNote_bn:
        "'I'm headed to' আপনি এখন কোথায় যাচ্ছেন তা বলার একটি অনানুষ্ঠানিক উপায়।",
    },
    {
      id: "M5.3",
      formula: "Where are you from?",
      formula_bn: "আপনি কোথা থেকে এসেছেন?",
      patternName: "Asking About Origin",
      patternName_bn: "উৎপত্তি সম্পর্কে জিজ্ঞাসা",
      slots: [],
      examples: [
        { en: "Where are you from?", bn: "আপনি কোথা থেকে এসেছেন?", slotValues: {} },
        { en: "Where are you from originally?", bn: "আপনি মূলত কোথা থেকে?", slotValues: {} },
        { en: "Where are you from? I love your accent.", bn: "আপনি কোথা থেকে? আমার আপনার উচ্চারণ ভালো লাগছে।", slotValues: {} },
        { en: "Where in Bangladesh are you from?", bn: "আপনি বাংলাদেশের কোথা থেকে?", slotValues: {} },
        { en: "Where are you from? I'm from Dhaka.", bn: "আপনি কোথা থেকে? আমি ঢাকা থেকে।", slotValues: {} },
        { en: "Where are you from? Are you local?", bn: "আপনি কোথা থেকে? আপনি কি এখানকার?", slotValues: {} },
        { en: "May I ask where you're from?", bn: "জিজ্ঞাসা করতে পারি আপনি কোথা থেকে?", slotValues: {} },
        { en: "Where are you from? You look familiar.", bn: "আপনি কোথা থেকে? আপনাকে চেনা মনে হচ্ছে।", slotValues: {} },
        { en: "So, where are you from?", bn: "তো, আপনি কোথা থেকে?", slotValues: {} },
        { en: "Which city are you from?", bn: "আপনি কোন শহর থেকে?", slotValues: {} },
        { en: "What country are you from?", bn: "আপনি কোন দেশ থেকে?", slotValues: {} },
        { en: "Where are you from? I've never been there.", bn: "আপনি কোথা থেকে? আমি কখনো সেখানে যাইনি।", slotValues: {} },
        { en: "Where did you grow up?", bn: "আপনি কোথায় বড় হয়েছেন?", slotValues: {} },
        { en: "Where are you from? It's nice to meet someone from there.", bn: "আপনি কোথা থেকে? সেখান থেকে কাউকে পেয়ে ভালো লাগছে।", slotValues: {} },
        { en: "Where is your hometown?", bn: "আপনার জন্মস্থান কোথায়?", slotValues: {} },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "This is a very common question when meeting someone new. It asks about their hometown or country.",
      usageNote_bn:
        "নতুন কারো সাথে দেখা হলে এটি একটি খুব সাধারণ প্রশ্ন। এটি তাদের জন্মস্থান বা দেশ সম্পর্কে জিজ্ঞাসা করে।",
    },
    {
      id: "M5.4",
      formula: "Where are you going?",
      formula_bn: "আপনি কোথায় যাচ্ছেন?",
      patternName: "Asking About Destination",
      patternName_bn: "গন্তব্য সম্পর্কে জিজ্ঞাসা",
      slots: [],
      examples: [
        { en: "Where are you going?", bn: "তুমি কোথায় যাচ্ছো?", slotValues: {} },
        { en: "Where are you going this weekend?", bn: "এই সপ্তাহান্তে কোথায় যাচ্ছো?", slotValues: {} },
        { en: "Where are you going so early?", bn: "এত সকালে কোথায় যাচ্ছো?", slotValues: {} },
        { en: "Where are you going in such a hurry?", bn: "এত তাড়াতাড়ি কোথায় যাচ্ছো?", slotValues: {} },
        { en: "Where are you headed?", bn: "কোন দিকে যাচ্ছো?", slotValues: {} },
        { en: "Where are you going after work?", bn: "কাজের পর কোথায় যাচ্ছো?", slotValues: {} },
        { en: "Where are you going on vacation?", bn: "ছুটিতে কোথায় যাচ্ছো?", slotValues: {} },
        { en: "Where are you going for lunch?", bn: "দুপুরের খাবারে কোথায় যাচ্ছো?", slotValues: {} },
        { en: "Where is everyone going?", bn: "সবাই কোথায় যাচ্ছে?", slotValues: {} },
        { en: "Where are you going? Can I come along?", bn: "কোথায় যাচ্ছো? আমিও যেতে পারি?", slotValues: {} },
        { en: "Where are you going tomorrow?", bn: "আগামীকাল কোথায় যাচ্ছো?", slotValues: {} },
        { en: "Where are you going? Do you need a ride?", bn: "কোথায় যাচ্ছো? লিফট লাগবে?", slotValues: {} },
        { en: "Where are you going at this hour?", bn: "এই সময়ে কোথায় যাচ্ছো?", slotValues: {} },
        { en: "Where are you going? Let me walk with you.", bn: "কোথায় যাচ্ছো? তোমার সাথে হাঁটি।", slotValues: {} },
        { en: "Where are you off to?", bn: "কোথায় রওনা হচ্ছো?", slotValues: {} },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "'Where are you going?' and 'Where are you headed?' are both common ways to ask about someone's destination.",
      usageNote_bn:
        "'Where are you going?' এবং 'Where are you headed?' দুটোই কারো গন্তব্য জিজ্ঞাসা করার সাধারণ উপায়।",
    },
    {
      id: "M5.5",
      formula: "I came from [PLACE]",
      formula_bn: "আমি [স্থান] থেকে এসেছি",
      patternName: "Stating Where You Came From",
      patternName_bn: "কোথা থেকে এসেছেন তা বলা",
      slots: [
        {
          name: "PLACE",
          description: "The place you just left or traveled from",
          description_bn: "যে স্থান থেকে সবে এসেছেন বা ভ্রমণ করেছেন",
          acceptedTypes: ["place"],
          examples: ["the office", "home", "Dhaka", "the airport"],
        },
      ],
      examples: [
        { en: "I came from the office.", bn: "আমি অফিস থেকে এসেছি।", slotValues: { PLACE: "the office" } },
        { en: "I just came from home.", bn: "আমি সবে বাড়ি থেকে এসেছি।", slotValues: { PLACE: "home" } },
        { en: "She came from the market.", bn: "সে বাজার থেকে এসেছে।", slotValues: { PLACE: "the market" } },
        { en: "We came from Dhaka this morning.", bn: "আমরা আজ সকালে ঢাকা থেকে এসেছি।", slotValues: { PLACE: "Dhaka" } },
        { en: "He came from the airport.", bn: "সে বিমানবন্দর থেকে এসেছে।", slotValues: { PLACE: "the airport" } },
        { en: "I came from the hospital.", bn: "আমি হাসপাতাল থেকে এসেছি।", slotValues: { PLACE: "the hospital" } },
        { en: "They came from the wedding ceremony.", bn: "তারা বিয়ের অনুষ্ঠান থেকে এসেছে।", slotValues: { PLACE: "the wedding ceremony" } },
        { en: "I came from the gym.", bn: "আমি জিম থেকে এসেছি।", slotValues: { PLACE: "the gym" } },
        { en: "She came straight from work.", bn: "সে সরাসরি কাজ থেকে এসেছে।", slotValues: { PLACE: "work" } },
        { en: "We came from the restaurant.", bn: "আমরা রেস্তোরাঁ থেকে এসেছি।", slotValues: { PLACE: "the restaurant" } },
        { en: "I came from my friend's house.", bn: "আমি বন্ধুর বাড়ি থেকে এসেছি।", slotValues: { PLACE: "my friend's house" } },
        { en: "He came from a long trip.", bn: "সে দীর্ঘ ভ্রমণ থেকে এসেছে।", slotValues: { PLACE: "a long trip" } },
        { en: "I came from the bank.", bn: "আমি ব্যাংক থেকে এসেছি।", slotValues: { PLACE: "the bank" } },
        { en: "She came from the library.", bn: "সে লাইব্রেরি থেকে এসেছে।", slotValues: { PLACE: "the library" } },
        { en: "We came from Sylhet yesterday.", bn: "আমরা গতকাল সিলেট থেকে এসেছি।", slotValues: { PLACE: "Sylhet" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "'I came from' describes where you just traveled from, not your hometown (use 'I'm from' for that).",
      usageNote_bn:
        "'I came from' বর্ণনা করে আপনি সবে কোথা থেকে এসেছেন, জন্মস্থান নয় (সেজন্য 'I'm from' ব্যবহার করুন)।",
    },
  ],
};
