import { PatternCategory } from "@/types/pattern";

export const categoryM7: PatternCategory = {
  id: "M7",
  slug: "giving-directions",
  name: "Giving Directions",
  name_bn: "দিকনির্দেশনা দেওয়া",
  description:
    "Learn to give and understand directions to places.",
  description_bn:
    "স্থানের দিকনির্দেশনা দিতে এবং বুঝতে শিখুন।",
  icon: "🧭",
  group: "M",
  groupName: "Place & Preposition Patterns",
  groupName_bn: "স্থান ও অব্যয়ের প্যাটার্ন",
  difficulty: "beginner",
  patterns: [
    {
      id: "M7.1",
      formula: "Go straight",
      formula_bn: "সোজা যান",
      patternName: "Going Straight",
      patternName_bn: "সোজা যাওয়া",
      slots: [],
      examples: [
        { en: "Go straight.", bn: "সোজা যান।", slotValues: {} },
        { en: "Go straight ahead.", bn: "সামনে সোজা যান।", slotValues: {} },
        { en: "Go straight for two blocks.", bn: "দুটো ব্লক সোজা যান।", slotValues: {} },
        { en: "Go straight down this road.", bn: "এই রাস্তা ধরে সোজা যান।", slotValues: {} },
        { en: "Go straight until you see the mosque.", bn: "মসজিদ দেখা পর্যন্ত সোজা যান।", slotValues: {} },
        { en: "Go straight and you'll see it on your left.", bn: "সোজা যান, বাঁ দিকে দেখতে পাবেন।", slotValues: {} },
        { en: "Go straight for about 100 meters.", bn: "প্রায় ১০০ মিটার সোজা যান।", slotValues: {} },
        { en: "Go straight past the traffic signal.", bn: "ট্রাফিক সিগনাল পার হয়ে সোজা যান।", slotValues: {} },
        { en: "Go straight and then turn right.", bn: "সোজা যান, তারপর ডানে ঘুরুন।", slotValues: {} },
        { en: "Just go straight. You can't miss it.", bn: "শুধু সোজা যান। আপনি মিস করবেন না।", slotValues: {} },
        { en: "Go straight along the river.", bn: "নদীর ধারে সোজা যান।", slotValues: {} },
        { en: "Go straight for 5 minutes.", bn: "৫ মিনিট সোজা যান।", slotValues: {} },
        { en: "Keep going straight until the end of the road.", bn: "রাস্তার শেষ পর্যন্ত সোজা যান।", slotValues: {} },
        { en: "Go straight through the intersection.", bn: "মোড় পার হয়ে সোজা যান।", slotValues: {} },
        { en: "Go straight and it's on the right side.", bn: "সোজা যান, ডান দিকে পাবেন।", slotValues: {} },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "'Go straight' means continue in the same direction without turning.",
      usageNote_bn:
        "'Go straight' মানে না ঘুরে একই দিকে চলতে থাকুন।",
    },
    {
      id: "M7.2",
      formula: "Turn left/right at [LANDMARK]",
      formula_bn: "[ল্যান্ডমার্কে] বাঁয়ে/ডানে ঘুরুন",
      patternName: "Turning at a Landmark",
      patternName_bn: "ল্যান্ডমার্কে ঘোরা",
      slots: [
        {
          name: "LANDMARK",
          description: "A noticeable reference point",
          description_bn: "একটি লক্ষণীয় রেফারেন্স পয়েন্ট",
          acceptedTypes: ["place", "noun_phrase"],
          examples: ["the traffic light", "the mosque", "the corner"],
        },
      ],
      examples: [
        { en: "Turn left at the traffic light.", bn: "ট্রাফিক লাইটে বাঁয়ে ঘুরুন।", slotValues: { LANDMARK: "the traffic light" } },
        { en: "Turn right at the mosque.", bn: "মসজিদে ডানে ঘুরুন।", slotValues: { LANDMARK: "the mosque" } },
        { en: "Turn left at the corner.", bn: "কোণায় বাঁয়ে ঘুরুন।", slotValues: { LANDMARK: "the corner" } },
        { en: "Turn right at the school.", bn: "স্কুলে ডানে ঘুরুন।", slotValues: { LANDMARK: "the school" } },
        { en: "Turn left at the gas station.", bn: "গ্যাস স্টেশনে বাঁয়ে ঘুরুন।", slotValues: { LANDMARK: "the gas station" } },
        { en: "Turn right at the big tree.", bn: "বড় গাছে ডানে ঘুরুন।", slotValues: { LANDMARK: "the big tree" } },
        { en: "Turn left at the bridge.", bn: "সেতুতে বাঁয়ে ঘুরুন।", slotValues: { LANDMARK: "the bridge" } },
        { en: "Turn right at the pharmacy.", bn: "ফার্মেসিতে ডানে ঘুরুন।", slotValues: { LANDMARK: "the pharmacy" } },
        { en: "Turn left at the intersection.", bn: "মোড়ে বাঁয়ে ঘুরুন।", slotValues: { LANDMARK: "the intersection" } },
        { en: "Turn right at the bank.", bn: "ব্যাংকে ডানে ঘুরুন।", slotValues: { LANDMARK: "the bank" } },
        { en: "Turn left at the supermarket.", bn: "সুপারমার্কেটে বাঁয়ে ঘুরুন।", slotValues: { LANDMARK: "the supermarket" } },
        { en: "Turn right at the cinema hall.", bn: "সিনেমা হলে ডানে ঘুরুন।", slotValues: { LANDMARK: "the cinema hall" } },
        { en: "Turn left at the second traffic light.", bn: "দ্বিতীয় ট্রাফিক লাইটে বাঁয়ে ঘুরুন।", slotValues: { LANDMARK: "the second traffic light" } },
        { en: "Turn right at the park entrance.", bn: "পার্কের প্রবেশদ্বারে ডানে ঘুরুন।", slotValues: { LANDMARK: "the park entrance" } },
        { en: "Turn left at the roundabout.", bn: "রাউন্ডঅ্যাবাউটে বাঁয়ে ঘুরুন।", slotValues: { LANDMARK: "the roundabout" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Use a well-known landmark as a reference point to make directions clearer.",
      usageNote_bn:
        "দিকনির্দেশনা স্পষ্ট করতে একটি পরিচিত ল্যান্ডমার্ককে রেফারেন্স পয়েন্ট হিসেবে ব্যবহার করুন।",
    },
    {
      id: "M7.3",
      formula: "It's on the left/right",
      formula_bn: "এটি বাঁ/ডান দিকে",
      patternName: "Location on Left or Right",
      patternName_bn: "বাঁ বা ডান দিকে অবস্থান",
      slots: [],
      examples: [
        { en: "It's on the left.", bn: "এটি বাঁ দিকে।", slotValues: {} },
        { en: "It's on the right.", bn: "এটি ডান দিকে।", slotValues: {} },
        { en: "It's on your left side.", bn: "এটি আপনার বাঁ দিকে।", slotValues: {} },
        { en: "It's on your right side.", bn: "এটি আপনার ডান দিকে।", slotValues: {} },
        { en: "The bank is on the left.", bn: "ব্যাংক বাঁ দিকে।", slotValues: {} },
        { en: "The hospital is on the right.", bn: "হাসপাতাল ডান দিকে।", slotValues: {} },
        { en: "You'll see it on the left after the bridge.", bn: "সেতুর পরে বাঁ দিকে দেখতে পাবেন।", slotValues: {} },
        { en: "The restaurant is on the right, past the mosque.", bn: "রেস্তোরাঁ মসজিদ পার হয়ে ডান দিকে।", slotValues: {} },
        { en: "It's right there on your left.", bn: "ওই তো, আপনার বাঁ দিকে।", slotValues: {} },
        { en: "The entrance is on the left side of the building.", bn: "প্রবেশদ্বার বিল্ডিংয়ের বাঁ দিকে।", slotValues: {} },
        { en: "The ATM is on the right, near the entrance.", bn: "ATM ডান দিকে, প্রবেশদ্বারের কাছে।", slotValues: {} },
        { en: "The pharmacy is on the left side of the street.", bn: "ফার্মেসি রাস্তার বাঁ দিকে।", slotValues: {} },
        { en: "It's on the right, you can't miss it.", bn: "ডান দিকে, আপনি মিস করবেন না।", slotValues: {} },
        { en: "The parking lot is on the left.", bn: "পার্কিং লট বাঁ দিকে।", slotValues: {} },
        { en: "The school gate is on the right.", bn: "স্কুলের গেট ডান দিকে।", slotValues: {} },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Use 'on the left/right' to tell someone which side a place is on.",
      usageNote_bn:
        "কাউকে বলতে 'on the left/right' ব্যবহার করুন যে কোন দিকে একটি স্থান আছে।",
    },
    {
      id: "M7.4",
      formula: "Take the first/second [TURN]",
      formula_bn: "প্রথম/দ্বিতীয় [বাঁক] নিন",
      patternName: "Counting Turns",
      patternName_bn: "বাঁক গণনা করা",
      slots: [
        {
          name: "TURN",
          description: "Direction of the turn (left/right)",
          description_bn: "বাঁকের দিক (বাঁ/ডান)",
          acceptedTypes: ["noun_phrase"],
          examples: ["left", "right", "turning on the left"],
        },
      ],
      examples: [
        { en: "Take the first left.", bn: "প্রথম বাঁয়ে ঘুরুন।", slotValues: { TURN: "left" } },
        { en: "Take the second right.", bn: "দ্বিতীয় ডানে ঘুরুন।", slotValues: { TURN: "right" } },
        { en: "Take the first right after the mosque.", bn: "মসজিদের পর প্রথম ডানে ঘুরুন।", slotValues: { TURN: "right after the mosque" } },
        { en: "Take the third left.", bn: "তৃতীয় বাঁয়ে ঘুরুন।", slotValues: { TURN: "left" } },
        { en: "Take the second left and you'll see it.", bn: "দ্বিতীয় বাঁয়ে ঘুরুন, দেখতে পাবেন।", slotValues: { TURN: "left" } },
        { en: "Take the first turning on the right.", bn: "ডানে প্রথম বাঁক নিন।", slotValues: { TURN: "turning on the right" } },
        { en: "Take the second turning on the left.", bn: "বাঁয়ে দ্বিতীয় বাঁক নিন।", slotValues: { TURN: "turning on the left" } },
        { en: "Take the first right after the traffic light.", bn: "ট্রাফিক লাইটের পর প্রথম ডানে ঘুরুন।", slotValues: { TURN: "right after the traffic light" } },
        { en: "Take the first exit at the roundabout.", bn: "রাউন্ডঅ্যাবাউটে প্রথম বের হন।", slotValues: { TURN: "exit at the roundabout" } },
        { en: "Take the second road on your right.", bn: "আপনার ডানে দ্বিতীয় রাস্তা নিন।", slotValues: { TURN: "road on your right" } },
        { en: "Take the first left, then go straight.", bn: "প্রথম বাঁয়ে ঘুরুন, তারপর সোজা যান।", slotValues: { TURN: "left, then go straight" } },
        { en: "Take the third right past the bridge.", bn: "সেতু পার হয়ে তৃতীয় ডানে ঘুরুন।", slotValues: { TURN: "right past the bridge" } },
        { en: "Take the first left after the school.", bn: "স্কুলের পর প্রথম বাঁয়ে ঘুরুন।", slotValues: { TURN: "left after the school" } },
        { en: "Take the second exit.", bn: "দ্বিতীয় বের হন।", slotValues: { TURN: "exit" } },
        { en: "Take the first right and it's right there.", bn: "প্রথম ডানে ঘুরুন, ওখানেই।", slotValues: { TURN: "right" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Use ordinal numbers (first, second, third) with left/right to count turns.",
      usageNote_bn:
        "বাঁক গণনা করতে বাঁ/ডানের সাথে ক্রমবাচক সংখ্যা (প্রথম, দ্বিতীয়, তৃতীয়) ব্যবহার করুন।",
    },
    {
      id: "M7.5",
      formula: "How do I get to [PLACE]?",
      formula_bn: "আমি [স্থানে] কীভাবে যাব?",
      patternName: "Asking for Directions",
      patternName_bn: "দিকনির্দেশনা চাওয়া",
      slots: [
        {
          name: "PLACE",
          description: "The destination",
          description_bn: "গন্তব্য",
          acceptedTypes: ["place"],
          examples: ["the station", "the hospital", "the market"],
        },
      ],
      examples: [
        { en: "How do I get to the station?", bn: "আমি স্টেশনে কীভাবে যাব?", slotValues: { PLACE: "the station" } },
        { en: "How do I get to the hospital?", bn: "আমি হাসপাতালে কীভাবে যাব?", slotValues: { PLACE: "the hospital" } },
        { en: "How do I get to the market?", bn: "আমি বাজারে কীভাবে যাব?", slotValues: { PLACE: "the market" } },
        { en: "How do I get to the nearest bank?", bn: "আমি নিকটতম ব্যাংকে কীভাবে যাব?", slotValues: { PLACE: "the nearest bank" } },
        { en: "How do I get to the airport from here?", bn: "এখান থেকে আমি বিমানবন্দরে কীভাবে যাব?", slotValues: { PLACE: "the airport" } },
        { en: "Can you tell me how to get to the mosque?", bn: "আপনি কি বলতে পারবেন মসজিদে কীভাবে যেতে হয়?", slotValues: { PLACE: "the mosque" } },
        { en: "Excuse me, how do I get to the post office?", bn: "মাফ করবেন, পোস্ট অফিসে কীভাবে যাব?", slotValues: { PLACE: "the post office" } },
        { en: "How do I get to the bus terminal?", bn: "আমি বাস টার্মিনালে কীভাবে যাব?", slotValues: { PLACE: "the bus terminal" } },
        { en: "How do I get to the university?", bn: "আমি বিশ্ববিদ্যালয়ে কীভাবে যাব?", slotValues: { PLACE: "the university" } },
        { en: "How do I get to the park?", bn: "আমি পার্কে কীভাবে যাব?", slotValues: { PLACE: "the park" } },
        { en: "How do I get to this address?", bn: "আমি এই ঠিকানায় কীভাবে যাব?", slotValues: { PLACE: "this address" } },
        { en: "How do I get to the shopping mall?", bn: "আমি শপিং মলে কীভাবে যাব?", slotValues: { PLACE: "the shopping mall" } },
        { en: "How do I get to the ferry terminal?", bn: "আমি ফেরি টার্মিনালে কীভাবে যাব?", slotValues: { PLACE: "the ferry terminal" } },
        { en: "How do I get to the police station?", bn: "আমি থানায় কীভাবে যাব?", slotValues: { PLACE: "the police station" } },
        { en: "How do I get to the main road?", bn: "আমি মূল রাস্তায় কীভাবে যাব?", slotValues: { PLACE: "the main road" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Use 'How do I get to...?' when you need directions to a place. Starting with 'Excuse me' is polite.",
      usageNote_bn:
        "কোনো স্থানে কীভাবে যেতে হয় জানতে 'How do I get to...?' ব্যবহার করুন। 'Excuse me' দিয়ে শুরু করা ভদ্র।",
    },
  ],
};
