import { PatternCategory } from "@/types/pattern";

export const categoryM8: PatternCategory = {
  id: "M8",
  slug: "indoor-locations",
  name: "Indoor Locations",
  name_bn: "ভবনের ভিতরের স্থান",
  description:
    "Learn to describe locations inside buildings and homes.",
  description_bn:
    "ভবন ও বাড়ির ভিতরের অবস্থান বর্ণনা করতে শিখুন।",
  icon: "🏠",
  group: "M",
  groupName: "Place & Preposition Patterns",
  groupName_bn: "স্থান ও অব্যয়ের প্যাটার্ন",
  difficulty: "beginner",
  patterns: [
    {
      id: "M8.1",
      formula: "[THING] is upstairs / downstairs",
      formula_bn: "[জিনিস] উপরে / নিচে আছে",
      patternName: "Upstairs / Downstairs",
      patternName_bn: "উপরতলা / নিচতলা",
      slots: [
        {
          name: "THING",
          description: "A person, room, or object",
          description_bn: "একটি ব্যক্তি, ঘর বা বস্তু",
          acceptedTypes: ["noun", "noun_phrase", "person"],
          examples: ["The bedroom", "He", "The bathroom"],
        },
      ],
      examples: [
        { en: "The bedroom is upstairs.", bn: "শোবার ঘর উপরে।", slotValues: { THING: "The bedroom" } },
        { en: "He is downstairs.", bn: "সে নিচে আছে।", slotValues: { THING: "He" } },
        { en: "The bathroom is upstairs.", bn: "বাথরুম উপরে।", slotValues: { THING: "The bathroom" } },
        { en: "The kitchen is downstairs.", bn: "রান্নাঘর নিচে।", slotValues: { THING: "The kitchen" } },
        { en: "My room is upstairs.", bn: "আমার ঘর উপরে।", slotValues: { THING: "My room" } },
        { en: "The kids are playing upstairs.", bn: "বাচ্চারা উপরে খেলছে।", slotValues: { THING: "The kids" } },
        { en: "Grandma is downstairs in the living room.", bn: "দাদি নিচে বসার ঘরে আছেন।", slotValues: { THING: "Grandma" } },
        { en: "The office is upstairs.", bn: "অফিস উপরে।", slotValues: { THING: "The office" } },
        { en: "Go downstairs. Dinner is ready.", bn: "নিচে যাও। রাতের খাবার তৈরি।", slotValues: { THING: "You" } },
        { en: "The storage room is downstairs.", bn: "স্টোরেজ রুম নিচে।", slotValues: { THING: "The storage room" } },
        { en: "Come upstairs. I need your help.", bn: "উপরে এসো। আমার তোমার সাহায্য দরকার।", slotValues: { THING: "You" } },
        { en: "The meeting room is upstairs.", bn: "মিটিং রুম উপরে।", slotValues: { THING: "The meeting room" } },
        { en: "The laundry room is downstairs.", bn: "কাপড় ধোয়ার ঘর নিচে।", slotValues: { THING: "The laundry room" } },
        { en: "She went upstairs to sleep.", bn: "সে ঘুমাতে উপরে গেল।", slotValues: { THING: "She" } },
        { en: "The guest room is upstairs, second door on the left.", bn: "অতিথি ঘর উপরে, বাঁয়ে দ্বিতীয় দরজা।", slotValues: { THING: "The guest room" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "'Upstairs' means on a higher floor. 'Downstairs' means on a lower floor.",
      usageNote_bn:
        "'Upstairs' মানে উপরের তলায়। 'Downstairs' মানে নিচের তলায়।",
    },
    {
      id: "M8.2",
      formula: "[THING] is on the [FLOOR] floor",
      formula_bn: "[জিনিস] [তলায়] আছে",
      patternName: "Floor Number",
      patternName_bn: "তলার নম্বর",
      slots: [
        {
          name: "THING",
          description: "A room, office, or place",
          description_bn: "একটি ঘর, অফিস বা স্থান",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["The office", "My apartment", "The gym"],
        },
        {
          name: "FLOOR",
          description: "Which floor (ordinal number)",
          description_bn: "কোন তলা (ক্রমবাচক সংখ্যা)",
          acceptedTypes: ["noun_phrase"],
          examples: ["first", "second", "third", "ground", "top"],
        },
      ],
      examples: [
        { en: "The office is on the 3rd floor.", bn: "অফিস ৩য় তলায়।", slotValues: { THING: "The office", FLOOR: "3rd" } },
        { en: "My apartment is on the 5th floor.", bn: "আমার অ্যাপার্টমেন্ট ৫ম তলায়।", slotValues: { THING: "My apartment", FLOOR: "5th" } },
        { en: "The gym is on the ground floor.", bn: "জিম নিচতলায়।", slotValues: { THING: "The gym", FLOOR: "ground" } },
        { en: "The restaurant is on the top floor.", bn: "রেস্তোরাঁ সবচেয়ে উপরের তলায়।", slotValues: { THING: "The restaurant", FLOOR: "top" } },
        { en: "The library is on the 2nd floor.", bn: "লাইব্রেরি ২য় তলায়।", slotValues: { THING: "The library", FLOOR: "2nd" } },
        { en: "We live on the 4th floor.", bn: "আমরা ৪র্থ তলায় থাকি।", slotValues: { THING: "We", FLOOR: "4th" } },
        { en: "The meeting room is on the 1st floor.", bn: "মিটিং রুম ১ম তলায়।", slotValues: { THING: "The meeting room", FLOOR: "1st" } },
        { en: "The parking is on the basement floor.", bn: "পার্কিং বেসমেন্টে।", slotValues: { THING: "The parking", FLOOR: "basement" } },
        { en: "The manager's office is on the 6th floor.", bn: "ম্যানেজারের অফিস ৬ষ্ঠ তলায়।", slotValues: { THING: "The manager's office", FLOOR: "6th" } },
        { en: "The reception is on the ground floor.", bn: "রিসেপশন নিচতলায়।", slotValues: { THING: "The reception", FLOOR: "ground" } },
        { en: "My room is on the 7th floor.", bn: "আমার ঘর ৭ম তলায়।", slotValues: { THING: "My room", FLOOR: "7th" } },
        { en: "The rooftop garden is on the 10th floor.", bn: "ছাদের বাগান ১০ম তলায়।", slotValues: { THING: "The rooftop garden", FLOOR: "10th" } },
        { en: "The shop is on the 1st floor of the mall.", bn: "দোকানটি মলের ১ম তলায়।", slotValues: { THING: "The shop", FLOOR: "1st" } },
        { en: "The clinic is on the 2nd floor.", bn: "ক্লিনিক ২য় তলায়।", slotValues: { THING: "The clinic", FLOOR: "2nd" } },
        { en: "The conference hall is on the 8th floor.", bn: "কনফারেন্স হল ৮ম তলায়।", slotValues: { THING: "The conference hall", FLOOR: "8th" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Use 'on the + ordinal number + floor' to specify which level of a building.",
      usageNote_bn:
        "একটি ভবনের কোন তলায় তা নির্দিষ্ট করতে 'on the + ক্রমবাচক সংখ্যা + floor' ব্যবহার করুন।",
    },
    {
      id: "M8.3",
      formula: "[THING] is in the [ROOM]",
      formula_bn: "[জিনিস] [ঘরে] আছে",
      patternName: "In the Room",
      patternName_bn: "ঘরে",
      slots: [
        {
          name: "THING",
          description: "A person or object",
          description_bn: "একটি ব্যক্তি বা বস্তু",
          acceptedTypes: ["noun", "noun_phrase", "person"],
          examples: ["Mom", "The towels", "He"],
        },
        {
          name: "ROOM",
          description: "A room inside a building",
          description_bn: "একটি ভবনের ভিতরের ঘর",
          acceptedTypes: ["place", "noun_phrase"],
          examples: ["kitchen", "bedroom", "bathroom", "living room"],
        },
      ],
      examples: [
        { en: "Mom is in the kitchen.", bn: "মা রান্নাঘরে আছেন।", slotValues: { THING: "Mom", ROOM: "kitchen" } },
        { en: "The towels are in the bathroom.", bn: "তোয়ালেগুলো বাথরুমে আছে।", slotValues: { THING: "The towels", ROOM: "bathroom" } },
        { en: "He is in the bedroom.", bn: "সে শোবার ঘরে আছে।", slotValues: { THING: "He", ROOM: "bedroom" } },
        { en: "The TV is in the living room.", bn: "টিভি বসার ঘরে আছে।", slotValues: { THING: "The TV", ROOM: "living room" } },
        { en: "The food is in the dining room.", bn: "খাবার ডাইনিং রুমে আছে।", slotValues: { THING: "The food", ROOM: "dining room" } },
        { en: "The books are in the study.", bn: "বইগুলো পড়ার ঘরে আছে।", slotValues: { THING: "The books", ROOM: "study" } },
        { en: "The guests are in the drawing room.", bn: "অতিথিরা ড্রয়িং রুমে আছেন।", slotValues: { THING: "The guests", ROOM: "drawing room" } },
        { en: "The washing machine is in the laundry room.", bn: "ওয়াশিং মেশিন লন্ড্রি রুমে আছে।", slotValues: { THING: "The washing machine", ROOM: "laundry room" } },
        { en: "The children are in the playroom.", bn: "বাচ্চারা খেলার ঘরে আছে।", slotValues: { THING: "The children", ROOM: "playroom" } },
        { en: "The files are in the office.", bn: "ফাইলগুলো অফিসে আছে।", slotValues: { THING: "The files", ROOM: "office" } },
        { en: "Dad is in the garage.", bn: "বাবা গ্যারেজে আছেন।", slotValues: { THING: "Dad", ROOM: "garage" } },
        { en: "The medicine is in the cabinet in the bathroom.", bn: "ওষুধ বাথরুমের ক্যাবিনেটে আছে।", slotValues: { THING: "The medicine", ROOM: "cabinet in the bathroom" } },
        { en: "The cat is in the hallway.", bn: "বিড়ালটি হলওয়েতে আছে।", slotValues: { THING: "The cat", ROOM: "hallway" } },
        { en: "The mirror is in the dressing room.", bn: "আয়না ড্রেসিং রুমে আছে।", slotValues: { THING: "The mirror", ROOM: "dressing room" } },
        { en: "She's in the prayer room.", bn: "সে নামাজের ঘরে আছে।", slotValues: { THING: "She", ROOM: "prayer room" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Use 'in the + room name' to describe which room something or someone is in.",
      usageNote_bn:
        "কিছু বা কেউ কোন ঘরে আছে তা বর্ণনা করতে 'in the + ঘরের নাম' ব্যবহার করুন।",
    },
    {
      id: "M8.4",
      formula: "Go to the [ROOM]",
      formula_bn: "[ঘরে] যাও",
      patternName: "Directing to a Room",
      patternName_bn: "একটি ঘরে দিকনির্দেশনা",
      slots: [
        {
          name: "ROOM",
          description: "A room or area inside the building",
          description_bn: "ভবনের ভিতরের একটি ঘর বা এলাকা",
          acceptedTypes: ["place", "noun_phrase"],
          examples: ["kitchen", "bedroom", "front desk", "waiting room"],
        },
      ],
      examples: [
        { en: "Go to the kitchen.", bn: "রান্নাঘরে যাও।", slotValues: { ROOM: "kitchen" } },
        { en: "Go to the bedroom and rest.", bn: "শোবার ঘরে গিয়ে বিশ্রাম নাও।", slotValues: { ROOM: "bedroom" } },
        { en: "Go to the front desk.", bn: "ফ্রন্ট ডেস্কে যান।", slotValues: { ROOM: "front desk" } },
        { en: "Please go to the waiting room.", bn: "অনুগ্রহ করে ওয়েটিং রুমে যান।", slotValues: { ROOM: "waiting room" } },
        { en: "Go to the living room. Everyone is there.", bn: "বসার ঘরে যাও। সবাই সেখানে আছে।", slotValues: { ROOM: "living room" } },
        { en: "Go to the bathroom and wash your hands.", bn: "বাথরুমে গিয়ে হাত ধুয়ে নাও।", slotValues: { ROOM: "bathroom" } },
        { en: "Go to the dining room for dinner.", bn: "রাতের খাবারের জন্য ডাইনিং রুমে যাও।", slotValues: { ROOM: "dining room" } },
        { en: "Go to the office on the 3rd floor.", bn: "৩য় তলার অফিসে যান।", slotValues: { ROOM: "office on the 3rd floor" } },
        { en: "Go to the conference room, please.", bn: "অনুগ্রহ করে কনফারেন্স রুমে যান।", slotValues: { ROOM: "conference room" } },
        { en: "Go to the balcony. The view is beautiful.", bn: "বারান্দায় যাও। দৃশ্য সুন্দর।", slotValues: { ROOM: "balcony" } },
        { en: "Go to the reception and ask for the key.", bn: "রিসেপশনে যান এবং চাবি চান।", slotValues: { ROOM: "reception" } },
        { en: "Go to the rooftop.", bn: "ছাদে যাও।", slotValues: { ROOM: "rooftop" } },
        { en: "Go to the exam hall. It's on the 2nd floor.", bn: "পরীক্ষার হলে যাও। ২য় তলায়।", slotValues: { ROOM: "exam hall" } },
        { en: "Go to the pharmacy counter.", bn: "ফার্মেসি কাউন্টারে যান।", slotValues: { ROOM: "pharmacy counter" } },
        { en: "Go to the teacher's room.", bn: "শিক্ষকদের রুমে যাও।", slotValues: { ROOM: "teacher's room" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Use 'Go to the + room' to direct someone to a specific area inside a building.",
      usageNote_bn:
        "কাউকে ভবনের ভিতরে একটি নির্দিষ্ট এলাকায় পাঠাতে 'Go to the + ঘর' ব্যবহার করুন।",
    },
    {
      id: "M8.5",
      formula: "It's at the end of the [AREA]",
      formula_bn: "এটি [এলাকার] শেষে",
      patternName: "At the End of + Area",
      patternName_bn: "শেষে + এলাকা",
      slots: [
        {
          name: "AREA",
          description: "A hallway, corridor, or passageway",
          description_bn: "একটি হলওয়ে, করিডোর বা পথ",
          acceptedTypes: ["place", "noun_phrase"],
          examples: ["the hallway", "the corridor", "the street"],
        },
      ],
      examples: [
        { en: "It's at the end of the hallway.", bn: "এটি হলওয়ের শেষে।", slotValues: { AREA: "the hallway" } },
        { en: "It's at the end of the corridor.", bn: "এটি করিডোরের শেষে।", slotValues: { AREA: "the corridor" } },
        { en: "The bathroom is at the end of the hall.", bn: "বাথরুম হলের শেষে।", slotValues: { AREA: "the hall" } },
        { en: "The office is at the end of the passage.", bn: "অফিস প্যাসেজের শেষে।", slotValues: { AREA: "the passage" } },
        { en: "The exit is at the end of the building.", bn: "বের হওয়ার পথ বিল্ডিংয়ের শেষে।", slotValues: { AREA: "the building" } },
        { en: "The meeting room is at the end of this floor.", bn: "মিটিং রুম এই তলার শেষে।", slotValues: { AREA: "this floor" } },
        { en: "His room is at the end of the corridor, on the left.", bn: "তার ঘর করিডোরের শেষে, বাঁ দিকে।", slotValues: { AREA: "the corridor" } },
        { en: "The elevator is at the end of the hallway.", bn: "লিফট হলওয়ের শেষে।", slotValues: { AREA: "the hallway" } },
        { en: "The staircase is at the end of the wing.", bn: "সিঁড়ি উইংয়ের শেষে।", slotValues: { AREA: "the wing" } },
        { en: "The library is at the end of the road.", bn: "লাইব্রেরি রাস্তার শেষে।", slotValues: { AREA: "the road" } },
        { en: "The emergency exit is at the end of the hall.", bn: "জরুরি বের হওয়ার পথ হলের শেষে।", slotValues: { AREA: "the hall" } },
        { en: "The principal's office is at the end of the corridor.", bn: "অধ্যক্ষের অফিস করিডোরের শেষে।", slotValues: { AREA: "the corridor" } },
        { en: "There's a garden at the end of the path.", bn: "পথের শেষে একটি বাগান আছে।", slotValues: { AREA: "the path" } },
        { en: "The parking garage is at the end of the building.", bn: "পার্কিং গ্যারেজ বিল্ডিংয়ের শেষে।", slotValues: { AREA: "the building" } },
        { en: "The cafeteria is at the end of the second floor.", bn: "ক্যাফেটেরিয়া দ্বিতীয় তলার শেষে।", slotValues: { AREA: "the second floor" } },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Use 'at the end of' to indicate something is located at the far point of a corridor, hallway, or path.",
      usageNote_bn:
        "করিডোর, হলওয়ে বা পথের দূরবর্তী বিন্দুতে কিছু অবস্থিত তা বোঝাতে 'at the end of' ব্যবহার করুন।",
    },
  ],
};
