import { PatternCategory } from "@/types/pattern";

export const categoryN2: PatternCategory = {
  id: "N2",
  slug: "quantifier-patterns",
  name: "Quantifier Patterns",
  name_bn: "পরিমাণবাচক প্যাটার্ন",
  description:
    "Learn to use some, any, much, many, and other quantifiers correctly.",
  description_bn:
    "some, any, much, many এবং অন্যান্য পরিমাণবাচক শব্দ সঠিকভাবে ব্যবহার করতে শিখুন।",
  icon: "🔢",
  group: "N",
  groupName: "Articles, Determiners & Quantifiers",
  groupName_bn: "আর্টিকেল, নির্ধারক ও পরিমাণবাচক",
  difficulty: "intermediate",
  patterns: [
    {
      id: "N2.1",
      formula: "I have some [THING]",
      formula_bn: "আমার কিছু [জিনিস] আছে",
      patternName: "Some (Positive Statements)",
      patternName_bn: "Some (ইতিবাচক বাক্য)",
      slots: [
        {
          name: "THING",
          description: "A plural countable or uncountable noun",
          description_bn: "বহুবচন গণনাযোগ্য বা অগণনীয় বিশেষ্য",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["money", "friends", "rice"],
        },
      ],
      examples: [
        {
          en: "I have some money.",
          bn: "আমার কিছু টাকা আছে।",
          slotValues: { THING: "money" },
          topicArea: "daily_life",
        },
        {
          en: "I have some friends in London.",
          bn: "লন্ডনে আমার কিছু বন্ধু আছে।",
          slotValues: { THING: "friends in London" },
          topicArea: "relationships",
        },
        {
          en: "I have some rice left over.",
          bn: "আমার কিছু ভাত বাকি আছে।",
          slotValues: { THING: "rice left over" },
          topicArea: "food",
        },
        {
          en: "I have some free time today.",
          bn: "আজ আমার কিছু ফ্রি টাইম আছে।",
          slotValues: { THING: "free time today" },
          topicArea: "daily_life",
        },
        {
          en: "I have some experience in marketing.",
          bn: "মার্কেটিংয়ে আমার কিছু অভিজ্ঞতা আছে।",
          slotValues: { THING: "experience in marketing" },
          topicArea: "work",
        },
        {
          en: "I have some good news.",
          bn: "আমার কিছু ভালো খবর আছে।",
          slotValues: { THING: "good news" },
          topicArea: "daily_life",
        },
        {
          en: "I have some questions about the project.",
          bn: "প্রকল্প সম্পর্কে আমার কিছু প্রশ্ন আছে।",
          slotValues: { THING: "questions about the project" },
          topicArea: "work",
        },
        {
          en: "I have some pain in my shoulder.",
          bn: "আমার কাঁধে কিছু ব্যথা আছে।",
          slotValues: { THING: "pain in my shoulder" },
          topicArea: "health",
        },
        {
          en: "I have some photos from the trip.",
          bn: "ভ্রমণের কিছু ছবি আমার কাছে আছে।",
          slotValues: { THING: "photos from the trip" },
          topicArea: "travel",
        },
        {
          en: "I have some suggestions for you.",
          bn: "তোমার জন্য আমার কিছু পরামর্শ আছে।",
          slotValues: { THING: "suggestions for you" },
          topicArea: "work",
        },
        {
          en: "I have some milk in the fridge.",
          bn: "ফ্রিজে আমার কিছু দুধ আছে।",
          slotValues: { THING: "milk in the fridge" },
          topicArea: "food",
        },
        {
          en: "I have some cousins in Chittagong.",
          bn: "চট্টগ্রামে আমার কিছু কাজিন আছে।",
          slotValues: { THING: "cousins in Chittagong" },
          topicArea: "relationships",
        },
        {
          en: "I have some extra pens.",
          bn: "আমার কিছু বাড়তি কলম আছে।",
          slotValues: { THING: "extra pens" },
          topicArea: "education",
        },
        {
          en: "I have some homework to finish.",
          bn: "আমার কিছু হোমওয়ার্ক শেষ করতে হবে।",
          slotValues: { THING: "homework to finish" },
          topicArea: "education",
        },
        {
          en: "I have some change in my pocket.",
          bn: "আমার পকেটে কিছু খুচরো আছে।",
          slotValues: { THING: "change in my pocket" },
          topicArea: "shopping",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Some' is used in positive statements with both countable plurals and uncountable nouns to mean 'an unspecified amount'.",
      usageNote_bn:
        "'Some' ইতিবাচক বাক্যে গণনাযোগ্য বহুবচন এবং অগণনীয় বিশেষ্যের সাথে 'অনির্দিষ্ট পরিমাণ' বোঝাতে ব্যবহৃত হয়।",
    },
    {
      id: "N2.2",
      formula: "Do you have any [THING]?",
      formula_bn: "তোমার কি কোনো [জিনিস] আছে?",
      patternName: "Any (Questions)",
      patternName_bn: "Any (প্রশ্ন)",
      slots: [
        {
          name: "THING",
          description: "A plural countable or uncountable noun",
          description_bn: "বহুবচন গণনাযোগ্য বা অগণনীয় বিশেষ্য",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["questions", "water", "ideas"],
        },
      ],
      examples: [
        {
          en: "Do you have any questions?",
          bn: "তোমার কি কোনো প্রশ্ন আছে?",
          slotValues: { THING: "questions" },
          topicArea: "education",
        },
        {
          en: "Do you have any water?",
          bn: "তোমার কাছে কি কোনো পানি আছে?",
          slotValues: { THING: "water" },
          topicArea: "food",
        },
        {
          en: "Do you have any ideas?",
          bn: "তোমার কি কোনো আইডিয়া আছে?",
          slotValues: { THING: "ideas" },
          topicArea: "work",
        },
        {
          en: "Do you have any siblings?",
          bn: "তোমার কি কোনো ভাইবোন আছে?",
          slotValues: { THING: "siblings" },
          topicArea: "relationships",
        },
        {
          en: "Do you have any plans for the weekend?",
          bn: "সপ্তাহান্তের জন্য তোমার কি কোনো পরিকল্পনা আছে?",
          slotValues: { THING: "plans for the weekend" },
          topicArea: "daily_life",
        },
        {
          en: "Do you have any allergies?",
          bn: "তোমার কি কোনো অ্যালার্জি আছে?",
          slotValues: { THING: "allergies" },
          topicArea: "health",
        },
        {
          en: "Do you have any experience with coding?",
          bn: "কোডিংয়ে তোমার কি কোনো অভিজ্ঞতা আছে?",
          slotValues: { THING: "experience with coding" },
          topicArea: "work",
        },
        {
          en: "Do you have any sugar?",
          bn: "তোমার কাছে কি কোনো চিনি আছে?",
          slotValues: { THING: "sugar" },
          topicArea: "food",
        },
        {
          en: "Do you have any recommendations?",
          bn: "তোমার কি কোনো সুপারিশ আছে?",
          slotValues: { THING: "recommendations" },
          topicArea: "travel",
        },
        {
          en: "Do you have any complaints?",
          bn: "তোমার কি কোনো অভিযোগ আছে?",
          slotValues: { THING: "complaints" },
          topicArea: "work",
        },
        {
          en: "Do you have any pets?",
          bn: "তোমার কি কোনো পোষা প্রাণী আছে?",
          slotValues: { THING: "pets" },
          topicArea: "daily_life",
        },
        {
          en: "Do you have any change?",
          bn: "তোমার কাছে কি কোনো খুচরো আছে?",
          slotValues: { THING: "change" },
          topicArea: "shopping",
        },
        {
          en: "Do you have any proof?",
          bn: "তোমার কাছে কি কোনো প্রমাণ আছে?",
          slotValues: { THING: "proof" },
          topicArea: "daily_life",
        },
        {
          en: "Do you have any seats available?",
          bn: "আপনাদের কি কোনো সিট খালি আছে?",
          slotValues: { THING: "seats available" },
          topicArea: "travel",
        },
        {
          en: "Do you have any homework tonight?",
          bn: "আজ রাতে তোমার কি কোনো হোমওয়ার্ক আছে?",
          slotValues: { THING: "homework tonight" },
          topicArea: "education",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Any' is typically used in questions and negative sentences instead of 'some'.",
      usageNote_bn:
        "'Any' সাধারণত প্রশ্ন এবং নেতিবাচক বাক্যে 'some'-এর বদলে ব্যবহৃত হয়।",
    },
    {
      id: "N2.3",
      formula: "I don't have much [UNCOUNTABLE]",
      formula_bn: "আমার বেশি [অগণনীয়] নেই",
      patternName: "Much (Uncountable)",
      patternName_bn: "Much (অগণনীয়)",
      slots: [
        {
          name: "UNCOUNTABLE",
          description: "An uncountable noun",
          description_bn: "একটি অগণনীয় বিশেষ্য",
          acceptedTypes: ["noun"],
          examples: ["time", "money", "patience"],
        },
      ],
      examples: [
        {
          en: "I don't have much time.",
          bn: "আমার বেশি সময় নেই।",
          slotValues: { UNCOUNTABLE: "time" },
          topicArea: "daily_life",
        },
        {
          en: "I don't have much money left.",
          bn: "আমার বেশি টাকা বাকি নেই।",
          slotValues: { UNCOUNTABLE: "money left" },
          topicArea: "shopping",
        },
        {
          en: "I don't have much patience today.",
          bn: "আজ আমার বেশি ধৈর্য নেই।",
          slotValues: { UNCOUNTABLE: "patience today" },
          topicArea: "daily_life",
        },
        {
          en: "I don't have much experience in this field.",
          bn: "এই ক্ষেত্রে আমার বেশি অভিজ্ঞতা নেই।",
          slotValues: { UNCOUNTABLE: "experience in this field" },
          topicArea: "work",
        },
        {
          en: "I don't have much energy today.",
          bn: "আজ আমার বেশি শক্তি নেই।",
          slotValues: { UNCOUNTABLE: "energy today" },
          topicArea: "health",
        },
        {
          en: "I don't have much information about it.",
          bn: "এ ব্যাপারে আমার কাছে বেশি তথ্য নেই।",
          slotValues: { UNCOUNTABLE: "information about it" },
          topicArea: "work",
        },
        {
          en: "I don't have much knowledge of history.",
          bn: "ইতিহাস সম্পর্কে আমার বেশি জ্ঞান নেই।",
          slotValues: { UNCOUNTABLE: "knowledge of history" },
          topicArea: "education",
        },
        {
          en: "I don't have much luggage.",
          bn: "আমার বেশি মালপত্র নেই।",
          slotValues: { UNCOUNTABLE: "luggage" },
          topicArea: "travel",
        },
        {
          en: "I don't have much faith in that plan.",
          bn: "সেই পরিকল্পনায় আমার বেশি বিশ্বাস নেই।",
          slotValues: { UNCOUNTABLE: "faith in that plan" },
          topicArea: "work",
        },
        {
          en: "I don't have much furniture in my room.",
          bn: "আমার ঘরে বেশি আসবাবপত্র নেই।",
          slotValues: { UNCOUNTABLE: "furniture in my room" },
          topicArea: "daily_life",
        },
        {
          en: "I don't have much appetite.",
          bn: "আমার বেশি ক্ষুধা নেই।",
          slotValues: { UNCOUNTABLE: "appetite" },
          topicArea: "health",
        },
        {
          en: "I don't have much homework this week.",
          bn: "এই সপ্তাহে আমার বেশি হোমওয়ার্ক নেই।",
          slotValues: { UNCOUNTABLE: "homework this week" },
          topicArea: "education",
        },
        {
          en: "I don't have much sugar at home.",
          bn: "বাড়িতে আমার বেশি চিনি নেই।",
          slotValues: { UNCOUNTABLE: "sugar at home" },
          topicArea: "food",
        },
        {
          en: "I don't have much space in my bag.",
          bn: "আমার ব্যাগে বেশি জায়গা নেই।",
          slotValues: { UNCOUNTABLE: "space in my bag" },
          topicArea: "travel",
        },
        {
          en: "I don't have much interest in politics.",
          bn: "রাজনীতিতে আমার বেশি আগ্রহ নেই।",
          slotValues: { UNCOUNTABLE: "interest in politics" },
          topicArea: "daily_life",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Much' is used with uncountable nouns, mostly in questions and negative sentences. In positive sentences, use 'a lot of' instead.",
      usageNote_bn:
        "'Much' অগণনীয় বিশেষ্যের সাথে ব্যবহৃত হয়, বেশিরভাগ প্রশ্ন ও নেতিবাচক বাক্যে। ইতিবাচক বাক্যে 'a lot of' ব্যবহার করুন।",
    },
    {
      id: "N2.4",
      formula: "There aren't many [COUNTABLE THINGS]",
      formula_bn: "বেশি [গণনীয় জিনিস] নেই",
      patternName: "Many (Countable)",
      patternName_bn: "Many (গণনীয়)",
      slots: [
        {
          name: "COUNTABLE THINGS",
          description: "A plural countable noun",
          description_bn: "একটি বহুবচন গণনাযোগ্য বিশেষ্য",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["people", "options", "shops"],
        },
      ],
      examples: [
        {
          en: "There aren't many people here.",
          bn: "এখানে বেশি মানুষ নেই।",
          slotValues: { "COUNTABLE THINGS": "people here" },
          topicArea: "daily_life",
        },
        {
          en: "There aren't many options to choose from.",
          bn: "বেছে নেওয়ার মতো বেশি অপশন নেই।",
          slotValues: { "COUNTABLE THINGS": "options to choose from" },
          topicArea: "shopping",
        },
        {
          en: "There aren't many shops open on Friday.",
          bn: "শুক্রবারে বেশি দোকান খোলা থাকে না।",
          slotValues: { "COUNTABLE THINGS": "shops open on Friday" },
          topicArea: "shopping",
        },
        {
          en: "There aren't many buses after 10 PM.",
          bn: "রাত ১০টার পর বেশি বাস নেই।",
          slotValues: { "COUNTABLE THINGS": "buses after 10 PM" },
          topicArea: "travel",
        },
        {
          en: "There aren't many students in this class.",
          bn: "এই ক্লাসে বেশি ছাত্র নেই।",
          slotValues: { "COUNTABLE THINGS": "students in this class" },
          topicArea: "education",
        },
        {
          en: "There aren't many restaurants nearby.",
          bn: "কাছাকাছি বেশি রেস্তোরাঁ নেই।",
          slotValues: { "COUNTABLE THINGS": "restaurants nearby" },
          topicArea: "food",
        },
        {
          en: "There aren't many doctors available.",
          bn: "বেশি ডাক্তার পাওয়া যাচ্ছে না।",
          slotValues: { "COUNTABLE THINGS": "doctors available" },
          topicArea: "health",
        },
        {
          en: "There aren't many good jobs in this area.",
          bn: "এই এলাকায় বেশি ভালো চাকরি নেই।",
          slotValues: { "COUNTABLE THINGS": "good jobs in this area" },
          topicArea: "work",
        },
        {
          en: "There aren't many days left before the exam.",
          bn: "পরীক্ষার আগে বেশি দিন বাকি নেই।",
          slotValues: { "COUNTABLE THINGS": "days left before the exam" },
          topicArea: "education",
        },
        {
          en: "There aren't many tickets left.",
          bn: "বেশি টিকিট বাকি নেই।",
          slotValues: { "COUNTABLE THINGS": "tickets left" },
          topicArea: "travel",
        },
        {
          en: "There aren't many trees in this neighborhood.",
          bn: "এই মহল্লায় বেশি গাছ নেই।",
          slotValues: { "COUNTABLE THINGS": "trees in this neighborhood" },
          topicArea: "daily_life",
        },
        {
          en: "There aren't many hospitals in the village.",
          bn: "গ্রামে বেশি হাসপাতাল নেই।",
          slotValues: { "COUNTABLE THINGS": "hospitals in the village" },
          topicArea: "health",
        },
        {
          en: "There aren't many parking spaces.",
          bn: "বেশি পার্কিংয়ের জায়গা নেই।",
          slotValues: { "COUNTABLE THINGS": "parking spaces" },
          topicArea: "travel",
        },
        {
          en: "There aren't many friends I can trust.",
          bn: "এমন বেশি বন্ধু নেই যাদের আমি বিশ্বাস করতে পারি।",
          slotValues: { "COUNTABLE THINGS": "friends I can trust" },
          topicArea: "relationships",
        },
        {
          en: "There aren't many chances like this.",
          bn: "এরকম বেশি সুযোগ আসে না।",
          slotValues: { "COUNTABLE THINGS": "chances like this" },
          topicArea: "work",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Many' is used with countable plural nouns. Like 'much', it's more common in questions and negatives. Use 'a lot of' in positive sentences.",
      usageNote_bn:
        "'Many' গণনাযোগ্য বহুবচন বিশেষ্যের সাথে ব্যবহৃত হয়। 'much'-এর মতো এটিও প্রশ্ন ও নেতিবাচক বাক্যে বেশি দেখা যায়।",
    },
    {
      id: "N2.5",
      formula: "There is a lot of / lots of [THING]",
      formula_bn: "অনেক [জিনিস] আছে",
      patternName: "A Lot Of / Lots Of",
      patternName_bn: "অনেক / প্রচুর",
      slots: [
        {
          name: "THING",
          description:
            "Any plural countable or uncountable noun",
          description_bn:
            "যেকোনো বহুবচন গণনাযোগ্য বা অগণনীয় বিশেষ্য",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["traffic", "students", "work"],
        },
      ],
      examples: [
        {
          en: "There is a lot of traffic today.",
          bn: "আজ অনেক ট্রাফিক।",
          slotValues: { THING: "traffic today" },
          topicArea: "travel",
        },
        {
          en: "There are lots of students in the library.",
          bn: "লাইব্রেরিতে অনেক ছাত্র আছে।",
          slotValues: { THING: "students in the library" },
          topicArea: "education",
        },
        {
          en: "I have a lot of work to do.",
          bn: "আমার অনেক কাজ করতে হবে।",
          slotValues: { THING: "work to do" },
          topicArea: "work",
        },
        {
          en: "There are lots of things to see here.",
          bn: "এখানে দেখার মতো অনেক জিনিস আছে।",
          slotValues: { THING: "things to see here" },
          topicArea: "travel",
        },
        {
          en: "She has a lot of patience.",
          bn: "তার অনেক ধৈর্য আছে।",
          slotValues: { THING: "patience" },
          topicArea: "relationships",
        },
        {
          en: "There are lots of options on the menu.",
          bn: "মেনুতে অনেক অপশন আছে।",
          slotValues: { THING: "options on the menu" },
          topicArea: "food",
        },
        {
          en: "I spent a lot of money on groceries.",
          bn: "আমি বাজারে অনেক টাকা খরচ করেছি।",
          slotValues: { THING: "money on groceries" },
          topicArea: "shopping",
        },
        {
          en: "There is a lot of noise outside.",
          bn: "বাইরে অনেক শব্দ হচ্ছে।",
          slotValues: { THING: "noise outside" },
          topicArea: "daily_life",
        },
        {
          en: "He has lots of friends at school.",
          bn: "স্কুলে তার অনেক বন্ধু আছে।",
          slotValues: { THING: "friends at school" },
          topicArea: "relationships",
        },
        {
          en: "There is a lot of stress at work.",
          bn: "কাজে অনেক চাপ আছে।",
          slotValues: { THING: "stress at work" },
          topicArea: "work",
        },
        {
          en: "We have lots of time before the flight.",
          bn: "ফ্লাইটের আগে আমাদের অনেক সময় আছে।",
          slotValues: { THING: "time before the flight" },
          topicArea: "travel",
        },
        {
          en: "There are a lot of books on that shelf.",
          bn: "ওই তাকে অনেক বই আছে।",
          slotValues: { THING: "books on that shelf" },
          topicArea: "education",
        },
        {
          en: "I drink a lot of water every day.",
          bn: "আমি প্রতিদিন অনেক পানি পান করি।",
          slotValues: { THING: "water every day" },
          topicArea: "health",
        },
        {
          en: "There are lots of mosquitoes in summer.",
          bn: "গরমে অনেক মশা থাকে।",
          slotValues: { THING: "mosquitoes in summer" },
          topicArea: "daily_life",
        },
        {
          en: "She puts a lot of effort into her cooking.",
          bn: "সে রান্নায় অনেক পরিশ্রম দেয়।",
          slotValues: { THING: "effort into her cooking" },
          topicArea: "food",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'A lot of' and 'lots of' work with both countable and uncountable nouns. They are the preferred choice in positive casual sentences.",
      usageNote_bn:
        "'A lot of' এবং 'lots of' গণনাযোগ্য ও অগণনীয় উভয় বিশেষ্যের সাথে কাজ করে। ইতিবাচক অনানুষ্ঠানিক বাক্যে এগুলো বেশি ব্যবহৃত হয়।",
    },
  ],
};
