import { PatternCategory } from "@/types/pattern";

export const categoryN3: PatternCategory = {
  id: "N3",
  slug: "demonstrative-patterns",
  name: "Demonstrative Patterns",
  name_bn: "নির্দেশক প্যাটার্ন",
  description:
    "Use this, that, these, and those to point to specific things near or far.",
  description_bn:
    "কাছের বা দূরের নির্দিষ্ট জিনিস নির্দেশ করতে this, that, these, those ব্যবহার শিখুন।",
  icon: "👉",
  group: "N",
  groupName: "Articles, Determiners & Quantifiers",
  groupName_bn: "আর্টিকেল, নির্ধারক ও পরিমাণবাচক",
  difficulty: "intermediate",
  patterns: [
    {
      id: "N3.1",
      formula: "This [THING] is [DESC]",
      formula_bn: "এই [জিনিসটা] [বর্ণনা]",
      patternName: "This (Near Singular)",
      patternName_bn: "This (কাছে একবচন)",
      slots: [
        {
          name: "THING",
          description: "A singular noun near the speaker",
          description_bn: "বক্তার কাছের একবচন বিশেষ্য",
          acceptedTypes: ["noun"],
          examples: ["book", "soup", "shirt"],
        },
        {
          name: "DESC",
          description: "An adjective or descriptive phrase",
          description_bn: "একটি বিশেষণ বা বর্ণনামূলক পদবন্ধ",
          acceptedTypes: ["adjective", "adjective_phrase"],
          examples: ["interesting", "delicious", "too tight"],
        },
      ],
      examples: [
        {
          en: "This book is interesting.",
          bn: "এই বইটা আকর্ষণীয়।",
          slotValues: { THING: "book", DESC: "interesting" },
          topicArea: "education",
        },
        {
          en: "This soup is delicious.",
          bn: "এই স্যুপটা অসাধারণ।",
          slotValues: { THING: "soup", DESC: "delicious" },
          topicArea: "food",
        },
        {
          en: "This shirt is too tight.",
          bn: "এই শার্টটা অনেক টাইট।",
          slotValues: { THING: "shirt", DESC: "too tight" },
          topicArea: "shopping",
        },
        {
          en: "This road is very bumpy.",
          bn: "এই রাস্তাটা অনেক এবড়োখেবড়ো।",
          slotValues: { THING: "road", DESC: "very bumpy" },
          topicArea: "travel",
        },
        {
          en: "This medicine is really effective.",
          bn: "এই ওষুধটা সত্যিই কার্যকর।",
          slotValues: { THING: "medicine", DESC: "really effective" },
          topicArea: "health",
        },
        {
          en: "This idea is brilliant.",
          bn: "এই আইডিয়াটা চমৎকার।",
          slotValues: { THING: "idea", DESC: "brilliant" },
          topicArea: "work",
        },
        {
          en: "This weather is perfect.",
          bn: "এই আবহাওয়াটা দারুণ।",
          slotValues: { THING: "weather", DESC: "perfect" },
          topicArea: "daily_life",
        },
        {
          en: "This phone is very fast.",
          bn: "এই ফোনটা অনেক দ্রুত।",
          slotValues: { THING: "phone", DESC: "very fast" },
          topicArea: "shopping",
        },
        {
          en: "This movie is boring.",
          bn: "এই সিনেমাটা বিরক্তিকর।",
          slotValues: { THING: "movie", DESC: "boring" },
          topicArea: "daily_life",
        },
        {
          en: "This tea is too sweet.",
          bn: "এই চা-টা অনেক মিষ্টি।",
          slotValues: { THING: "tea", DESC: "too sweet" },
          topicArea: "food",
        },
        {
          en: "This question is tricky.",
          bn: "এই প্রশ্নটা কঠিন।",
          slotValues: { THING: "question", DESC: "tricky" },
          topicArea: "education",
        },
        {
          en: "This hotel is quite expensive.",
          bn: "এই হোটেলটা বেশ দামি।",
          slotValues: { THING: "hotel", DESC: "quite expensive" },
          topicArea: "travel",
        },
        {
          en: "This pain is unbearable.",
          bn: "এই ব্যথাটা অসহনীয়।",
          slotValues: { THING: "pain", DESC: "unbearable" },
          topicArea: "health",
        },
        {
          en: "This project is almost done.",
          bn: "এই প্রকল্পটা প্রায় শেষ।",
          slotValues: { THING: "project", DESC: "almost done" },
          topicArea: "work",
        },
        {
          en: "This neighborhood is very safe.",
          bn: "এই মহল্লাটা অনেক নিরাপদ।",
          slotValues: { THING: "neighborhood", DESC: "very safe" },
          topicArea: "daily_life",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'This' refers to a singular thing close to the speaker in space or time.",
      usageNote_bn:
        "'This' বক্তার কাছে (স্থান বা সময়ে) একটি একবচন জিনিস বোঝায়।",
    },
    {
      id: "N3.2",
      formula: "That [THING] is [DESC]",
      formula_bn: "ওই [জিনিসটা] [বর্ণনা]",
      patternName: "That (Far Singular)",
      patternName_bn: "That (দূরে একবচন)",
      slots: [
        {
          name: "THING",
          description: "A singular noun far from the speaker",
          description_bn: "বক্তার থেকে দূরের একবচন বিশেষ্য",
          acceptedTypes: ["noun"],
          examples: ["building", "car", "mountain"],
        },
        {
          name: "DESC",
          description: "An adjective or descriptive phrase",
          description_bn: "একটি বিশেষণ বা বর্ণনামূলক পদবন্ধ",
          acceptedTypes: ["adjective", "adjective_phrase"],
          examples: ["very tall", "nice", "beautiful"],
        },
      ],
      examples: [
        {
          en: "That building is very tall.",
          bn: "ওই বিল্ডিংটা অনেক উঁচু।",
          slotValues: { THING: "building", DESC: "very tall" },
          topicArea: "travel",
        },
        {
          en: "That car is nice.",
          bn: "ওই গাড়িটা সুন্দর।",
          slotValues: { THING: "car", DESC: "nice" },
          topicArea: "daily_life",
        },
        {
          en: "That mountain is beautiful.",
          bn: "ওই পাহাড়টা সুন্দর।",
          slotValues: { THING: "mountain", DESC: "beautiful" },
          topicArea: "travel",
        },
        {
          en: "That restaurant is always crowded.",
          bn: "ওই রেস্তোরাঁটা সবসময় ভিড় থাকে।",
          slotValues: { THING: "restaurant", DESC: "always crowded" },
          topicArea: "food",
        },
        {
          en: "That man is my uncle.",
          bn: "ওই লোকটা আমার চাচা।",
          slotValues: { THING: "man", DESC: "my uncle" },
          topicArea: "relationships",
        },
        {
          en: "That store is cheaper.",
          bn: "ওই দোকানটা সস্তা।",
          slotValues: { THING: "store", DESC: "cheaper" },
          topicArea: "shopping",
        },
        {
          en: "That sound is annoying.",
          bn: "ওই শব্দটা বিরক্তিকর।",
          slotValues: { THING: "sound", DESC: "annoying" },
          topicArea: "daily_life",
        },
        {
          en: "That hospital is very good.",
          bn: "ওই হাসপাতালটা অনেক ভালো।",
          slotValues: { THING: "hospital", DESC: "very good" },
          topicArea: "health",
        },
        {
          en: "That school is famous.",
          bn: "ওই স্কুলটা বিখ্যাত।",
          slotValues: { THING: "school", DESC: "famous" },
          topicArea: "education",
        },
        {
          en: "That meeting was a waste of time.",
          bn: "ওই মিটিংটা সময়ের অপচয় ছিল।",
          slotValues: { THING: "meeting", DESC: "a waste of time" },
          topicArea: "work",
        },
        {
          en: "That bridge is very old.",
          bn: "ওই সেতুটা অনেক পুরোনো।",
          slotValues: { THING: "bridge", DESC: "very old" },
          topicArea: "travel",
        },
        {
          en: "That cake looks amazing.",
          bn: "ওই কেকটা দেখতে অসাধারণ।",
          slotValues: { THING: "cake", DESC: "amazing" },
          topicArea: "food",
        },
        {
          en: "That dog is friendly.",
          bn: "ওই কুকুরটা বন্ধুসুলভ।",
          slotValues: { THING: "dog", DESC: "friendly" },
          topicArea: "daily_life",
        },
        {
          en: "That pharmacy is open 24 hours.",
          bn: "ওই ফার্মেসিটা ২৪ ঘণ্টা খোলা।",
          slotValues: { THING: "pharmacy", DESC: "open 24 hours" },
          topicArea: "health",
        },
        {
          en: "That office is on the fifth floor.",
          bn: "ওই অফিসটা পঞ্চম তলায়।",
          slotValues: { THING: "office", DESC: "on the fifth floor" },
          topicArea: "work",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'That' refers to a singular thing far from the speaker, or something mentioned earlier in conversation.",
      usageNote_bn:
        "'That' বক্তা থেকে দূরের একটি একবচন জিনিস, বা কথোপকথনে আগে উল্লেখিত কিছু বোঝায়।",
    },
    {
      id: "N3.3",
      formula: "These [THINGS] are [DESC]",
      formula_bn: "এই [জিনিসগুলো] [বর্ণনা]",
      patternName: "These (Near Plural)",
      patternName_bn: "These (কাছে বহুবচন)",
      slots: [
        {
          name: "THINGS",
          description: "A plural noun near the speaker",
          description_bn: "বক্তার কাছের বহুবচন বিশেষ্য",
          acceptedTypes: ["noun"],
          examples: ["cookies", "shoes", "flowers"],
        },
        {
          name: "DESC",
          description: "An adjective or descriptive phrase",
          description_bn: "একটি বিশেষণ বা বর্ণনামূলক পদবন্ধ",
          acceptedTypes: ["adjective", "adjective_phrase"],
          examples: ["fresh", "comfortable", "beautiful"],
        },
      ],
      examples: [
        {
          en: "These cookies are fresh.",
          bn: "এই কুকিগুলো তাজা।",
          slotValues: { THINGS: "cookies", DESC: "fresh" },
          topicArea: "food",
        },
        {
          en: "These shoes are comfortable.",
          bn: "এই জুতোগুলো আরামদায়ক।",
          slotValues: { THINGS: "shoes", DESC: "comfortable" },
          topicArea: "shopping",
        },
        {
          en: "These flowers are beautiful.",
          bn: "এই ফুলগুলো সুন্দর।",
          slotValues: { THINGS: "flowers", DESC: "beautiful" },
          topicArea: "daily_life",
        },
        {
          en: "These questions are difficult.",
          bn: "এই প্রশ্নগুলো কঠিন।",
          slotValues: { THINGS: "questions", DESC: "difficult" },
          topicArea: "education",
        },
        {
          en: "These mangoes are very sweet.",
          bn: "এই আমগুলো অনেক মিষ্টি।",
          slotValues: { THINGS: "mangoes", DESC: "very sweet" },
          topicArea: "food",
        },
        {
          en: "These reports are ready.",
          bn: "এই রিপোর্টগুলো তৈরি।",
          slotValues: { THINGS: "reports", DESC: "ready" },
          topicArea: "work",
        },
        {
          en: "These pills are for headaches.",
          bn: "এই ওষুধগুলো মাথা ব্যথার জন্য।",
          slotValues: { THINGS: "pills", DESC: "for headaches" },
          topicArea: "health",
        },
        {
          en: "These photos are from our vacation.",
          bn: "এই ছবিগুলো আমাদের ছুটির।",
          slotValues: { THINGS: "photos", DESC: "from our vacation" },
          topicArea: "travel",
        },
        {
          en: "These chairs are broken.",
          bn: "এই চেয়ারগুলো ভাঙা।",
          slotValues: { THINGS: "chairs", DESC: "broken" },
          topicArea: "daily_life",
        },
        {
          en: "These prices are too high.",
          bn: "এই দামগুলো অনেক বেশি।",
          slotValues: { THINGS: "prices", DESC: "too high" },
          topicArea: "shopping",
        },
        {
          en: "These students are very talented.",
          bn: "এই ছাত্ররা অনেক মেধাবী।",
          slotValues: { THINGS: "students", DESC: "very talented" },
          topicArea: "education",
        },
        {
          en: "These samosas are spicy.",
          bn: "এই সমুচাগুলো ঝাল।",
          slotValues: { THINGS: "samosas", DESC: "spicy" },
          topicArea: "food",
        },
        {
          en: "These files are confidential.",
          bn: "এই ফাইলগুলো গোপনীয়।",
          slotValues: { THINGS: "files", DESC: "confidential" },
          topicArea: "work",
        },
        {
          en: "These symptoms are common.",
          bn: "এই লক্ষণগুলো সাধারণ।",
          slotValues: { THINGS: "symptoms", DESC: "common" },
          topicArea: "health",
        },
        {
          en: "These neighbors are very kind.",
          bn: "এই প্রতিবেশীরা অনেক দয়ালু।",
          slotValues: { THINGS: "neighbors", DESC: "very kind" },
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'These' is the plural of 'this' — used for multiple things close to the speaker.",
      usageNote_bn:
        "'These' হলো 'this'-এর বহুবচন — বক্তার কাছে একাধিক জিনিস বোঝাতে ব্যবহৃত হয়।",
    },
    {
      id: "N3.4",
      formula: "Those [THINGS] are [DESC]",
      formula_bn: "ওই [জিনিসগুলো] [বর্ণনা]",
      patternName: "Those (Far Plural)",
      patternName_bn: "Those (দূরে বহুবচন)",
      slots: [
        {
          name: "THINGS",
          description: "A plural noun far from the speaker",
          description_bn: "বক্তা থেকে দূরের বহুবচন বিশেষ্য",
          acceptedTypes: ["noun"],
          examples: ["houses", "birds", "lights"],
        },
        {
          name: "DESC",
          description: "An adjective or descriptive phrase",
          description_bn: "একটি বিশেষণ বা বর্ণনামূলক পদবন্ধ",
          acceptedTypes: ["adjective", "adjective_phrase"],
          examples: ["expensive", "beautiful", "very bright"],
        },
      ],
      examples: [
        {
          en: "Those houses are expensive.",
          bn: "ওই বাড়িগুলো দামি।",
          slotValues: { THINGS: "houses", DESC: "expensive" },
          topicArea: "daily_life",
        },
        {
          en: "Those birds are beautiful.",
          bn: "ওই পাখিগুলো সুন্দর।",
          slotValues: { THINGS: "birds", DESC: "beautiful" },
          topicArea: "daily_life",
        },
        {
          en: "Those lights are very bright.",
          bn: "ওই আলোগুলো অনেক উজ্জ্বল।",
          slotValues: { THINGS: "lights", DESC: "very bright" },
          topicArea: "daily_life",
        },
        {
          en: "Those kids are playing in the park.",
          bn: "ওই বাচ্চারা পার্কে খেলছে।",
          slotValues: { THINGS: "kids", DESC: "playing in the park" },
          topicArea: "daily_life",
        },
        {
          en: "Those apples are rotten.",
          bn: "ওই আপেলগুলো পচা।",
          slotValues: { THINGS: "apples", DESC: "rotten" },
          topicArea: "food",
        },
        {
          en: "Those bags are on sale.",
          bn: "ওই ব্যাগগুলো সেলে আছে।",
          slotValues: { THINGS: "bags", DESC: "on sale" },
          topicArea: "shopping",
        },
        {
          en: "Those mountains are covered with snow.",
          bn: "ওই পাহাড়গুলো বরফে ঢাকা।",
          slotValues: { THINGS: "mountains", DESC: "covered with snow" },
          topicArea: "travel",
        },
        {
          en: "Those tablets are for blood pressure.",
          bn: "ওই ট্যাবলেটগুলো রক্তচাপের জন্য।",
          slotValues: { THINGS: "tablets", DESC: "for blood pressure" },
          topicArea: "health",
        },
        {
          en: "Those books are from the old library.",
          bn: "ওই বইগুলো পুরোনো লাইব্রেরির।",
          slotValues: { THINGS: "books", DESC: "from the old library" },
          topicArea: "education",
        },
        {
          en: "Those people are waiting for the bus.",
          bn: "ওই লোকগুলো বাসের জন্য অপেক্ষা করছে।",
          slotValues: { THINGS: "people", DESC: "waiting for the bus" },
          topicArea: "travel",
        },
        {
          en: "Those chairs are reserved.",
          bn: "ওই চেয়ারগুলো রিজার্ভ করা।",
          slotValues: { THINGS: "chairs", DESC: "reserved" },
          topicArea: "food",
        },
        {
          en: "Those documents are outdated.",
          bn: "ওই কাগজপত্রগুলো পুরোনো।",
          slotValues: { THINGS: "documents", DESC: "outdated" },
          topicArea: "work",
        },
        {
          en: "Those clothes are too small for me.",
          bn: "ওই জামাকাপড়গুলো আমার জন্য ছোট।",
          slotValues: { THINGS: "clothes", DESC: "too small for me" },
          topicArea: "shopping",
        },
        {
          en: "Those days were wonderful.",
          bn: "ওই দিনগুলো অসাধারণ ছিল।",
          slotValues: { THINGS: "days", DESC: "wonderful" },
          topicArea: "relationships",
        },
        {
          en: "Those problems are hard to solve.",
          bn: "ওই সমস্যাগুলো সমাধান করা কঠিন।",
          slotValues: { THINGS: "problems", DESC: "hard to solve" },
          topicArea: "work",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Those' is the plural of 'that' — used for multiple things far from the speaker or in the past.",
      usageNote_bn:
        "'Those' হলো 'that'-এর বহুবচন — বক্তা থেকে দূরে একাধিক জিনিস বা অতীতের কিছু বোঝাতে ব্যবহৃত হয়।",
    },
    {
      id: "N3.5",
      formula: "Is this/that your [THING]?",
      formula_bn: "এটা/ওটা কি তোমার [জিনিস]?",
      patternName: "Demonstrative Questions",
      patternName_bn: "নির্দেশক প্রশ্ন",
      slots: [
        {
          name: "THING",
          description: "A singular noun being identified",
          description_bn: "চিহ্নিত করা হচ্ছে এমন একবচন বিশেষ্য",
          acceptedTypes: ["noun"],
          examples: ["bag", "seat", "phone"],
        },
      ],
      examples: [
        {
          en: "Is this your bag?",
          bn: "এটা কি তোমার ব্যাগ?",
          slotValues: { THING: "bag" },
          topicArea: "daily_life",
        },
        {
          en: "Is that your seat?",
          bn: "ওটা কি তোমার সিট?",
          slotValues: { THING: "seat" },
          topicArea: "travel",
        },
        {
          en: "Is this your phone?",
          bn: "এটা কি তোমার ফোন?",
          slotValues: { THING: "phone" },
          topicArea: "daily_life",
        },
        {
          en: "Is that your car outside?",
          bn: "বাইরে ওটা কি তোমার গাড়ি?",
          slotValues: { THING: "car outside" },
          topicArea: "daily_life",
        },
        {
          en: "Is this your umbrella?",
          bn: "এটা কি তোমার ছাতা?",
          slotValues: { THING: "umbrella" },
          topicArea: "daily_life",
        },
        {
          en: "Is that your order?",
          bn: "ওটা কি তোমার অর্ডার?",
          slotValues: { THING: "order" },
          topicArea: "food",
        },
        {
          en: "Is this your prescription?",
          bn: "এটা কি তোমার প্রেসক্রিপশন?",
          slotValues: { THING: "prescription" },
          topicArea: "health",
        },
        {
          en: "Is that your jacket on the chair?",
          bn: "চেয়ারে ওটা কি তোমার জ্যাকেট?",
          slotValues: { THING: "jacket on the chair" },
          topicArea: "daily_life",
        },
        {
          en: "Is this your homework?",
          bn: "এটা কি তোমার হোমওয়ার্ক?",
          slotValues: { THING: "homework" },
          topicArea: "education",
        },
        {
          en: "Is that your office over there?",
          bn: "ওখানে ওটা কি তোমার অফিস?",
          slotValues: { THING: "office over there" },
          topicArea: "work",
        },
        {
          en: "Is this your receipt?",
          bn: "এটা কি তোমার রসিদ?",
          slotValues: { THING: "receipt" },
          topicArea: "shopping",
        },
        {
          en: "Is that your dog?",
          bn: "ওটা কি তোমার কুকুর?",
          slotValues: { THING: "dog" },
          topicArea: "daily_life",
        },
        {
          en: "Is this your final answer?",
          bn: "এটা কি তোমার চূড়ান্ত উত্তর?",
          slotValues: { THING: "final answer" },
          topicArea: "education",
        },
        {
          en: "Is that your suitcase at the counter?",
          bn: "কাউন্টারে ওটা কি তোমার সুটকেস?",
          slotValues: { THING: "suitcase at the counter" },
          topicArea: "travel",
        },
        {
          en: "Is this your lunch box?",
          bn: "এটা কি তোমার লাঞ্চ বক্স?",
          slotValues: { THING: "lunch box" },
          topicArea: "food",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "Use 'this' for things near you and 'that' for things farther away when asking about ownership.",
      usageNote_bn:
        "মালিকানা জানতে চাইলে কাছের জিনিসের জন্য 'this' এবং দূরের জিনিসের জন্য 'that' ব্যবহার করুন।",
    },
  ],
};
