import { PatternCategory } from "@/types/pattern";

export const categoryN5: PatternCategory = {
  id: "N5",
  slug: "indefinite-pronouns",
  name: "Indefinite Pronouns",
  name_bn: "অনির্দিষ্ট সর্বনাম",
  description:
    "Use someone, anyone, no one, everyone, and something/anything/nothing/everything correctly.",
  description_bn:
    "someone, anyone, no one, everyone এবং something/anything/nothing/everything সঠিকভাবে ব্যবহার শিখুন।",
  icon: "👤",
  group: "N",
  groupName: "Articles, Determiners & Quantifiers",
  groupName_bn: "আর্টিকেল, নির্ধারক ও পরিমাণবাচক",
  difficulty: "intermediate",
  patterns: [
    {
      id: "N5.1",
      formula: "Someone [ACTION+ED]",
      formula_bn: "কেউ [কাজ করেছে]",
      patternName: "Someone (Unknown Person)",
      patternName_bn: "Someone (অজানা ব্যক্তি)",
      slots: [
        {
          name: "ACTION+ED",
          description: "A past tense verb or verb phrase",
          description_bn: "একটি অতীত কাল ক্রিয়া বা ক্রিয়া পদবন্ধ",
          acceptedTypes: ["verb_phrase"],
          examples: ["called you", "left a message", "stole my wallet"],
        },
      ],
      examples: [
        {
          en: "Someone called you.",
          bn: "কেউ তোমাকে ফোন করেছে।",
          slotValues: { "ACTION+ED": "called you" },
          topicArea: "daily_life",
        },
        {
          en: "Someone left a message for you.",
          bn: "কেউ তোমার জন্য একটা মেসেজ রেখে গেছে।",
          slotValues: { "ACTION+ED": "left a message for you" },
          topicArea: "work",
        },
        {
          en: "Someone stole my wallet.",
          bn: "কেউ আমার মানিব্যাগ চুরি করেছে।",
          slotValues: { "ACTION+ED": "stole my wallet" },
          topicArea: "daily_life",
        },
        {
          en: "Someone knocked on the door.",
          bn: "কেউ দরজায় নক করেছে।",
          slotValues: { "ACTION+ED": "knocked on the door" },
          topicArea: "daily_life",
        },
        {
          en: "Someone ate my lunch.",
          bn: "কেউ আমার দুপুরের খাবার খেয়ে ফেলেছে।",
          slotValues: { "ACTION+ED": "ate my lunch" },
          topicArea: "food",
        },
        {
          en: "Someone recommended this doctor.",
          bn: "কেউ এই ডাক্তারকে সুপারিশ করেছে।",
          slotValues: { "ACTION+ED": "recommended this doctor" },
          topicArea: "health",
        },
        {
          en: "Someone forgot their umbrella.",
          bn: "কেউ তার ছাতা রেখে গেছে।",
          slotValues: { "ACTION+ED": "forgot their umbrella" },
          topicArea: "daily_life",
        },
        {
          en: "Someone booked the last seat.",
          bn: "কেউ শেষ সিটটা বুক করে ফেলেছে।",
          slotValues: { "ACTION+ED": "booked the last seat" },
          topicArea: "travel",
        },
        {
          en: "Someone sent you a gift.",
          bn: "কেউ তোমাকে একটা উপহার পাঠিয়েছে।",
          slotValues: { "ACTION+ED": "sent you a gift" },
          topicArea: "relationships",
        },
        {
          en: "Someone complained about the noise.",
          bn: "কেউ শব্দের ব্যাপারে অভিযোগ করেছে।",
          slotValues: { "ACTION+ED": "complained about the noise" },
          topicArea: "daily_life",
        },
        {
          en: "Someone borrowed my charger.",
          bn: "কেউ আমার চার্জার ধার নিয়েছে।",
          slotValues: { "ACTION+ED": "borrowed my charger" },
          topicArea: "daily_life",
        },
        {
          en: "Someone parked in my spot.",
          bn: "কেউ আমার জায়গায় গাড়ি রেখেছে।",
          slotValues: { "ACTION+ED": "parked in my spot" },
          topicArea: "daily_life",
        },
        {
          en: "Someone ordered pizza for the office.",
          bn: "কেউ অফিসের জন্য পিৎজা অর্ডার করেছে।",
          slotValues: { "ACTION+ED": "ordered pizza for the office" },
          topicArea: "work",
        },
        {
          en: "Someone returned your book.",
          bn: "কেউ তোমার বই ফেরত দিয়েছে।",
          slotValues: { "ACTION+ED": "returned your book" },
          topicArea: "education",
        },
        {
          en: "Someone paid for my coffee.",
          bn: "কেউ আমার কফির টাকা দিয়ে দিয়েছে।",
          slotValues: { "ACTION+ED": "paid for my coffee" },
          topicArea: "food",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Someone' refers to an unknown or unspecified person. It's used in positive statements.",
      usageNote_bn:
        "'Someone' অজানা বা অনির্দিষ্ট ব্যক্তি বোঝায়। ইতিবাচক বাক্যে ব্যবহৃত হয়।",
    },
    {
      id: "N5.2",
      formula: "Did anyone [ACTION]?",
      formula_bn: "কেউ কি [কাজ করেছে]?",
      patternName: "Anyone (Questions & Negatives)",
      patternName_bn: "Anyone (প্রশ্ন ও নেতিবাচক)",
      slots: [
        {
          name: "ACTION",
          description: "A base verb or verb phrase",
          description_bn: "একটি মূল ক্রিয়া বা ক্রিয়া পদবন্ধ",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["see that", "call me", "finish the report"],
        },
      ],
      examples: [
        {
          en: "Did anyone see that?",
          bn: "কেউ কি ওটা দেখেছে?",
          slotValues: { ACTION: "see that" },
          topicArea: "daily_life",
        },
        {
          en: "Did anyone call me?",
          bn: "কেউ কি আমাকে ফোন করেছে?",
          slotValues: { ACTION: "call me" },
          topicArea: "daily_life",
        },
        {
          en: "Did anyone finish the report?",
          bn: "কেউ কি রিপোর্ট শেষ করেছে?",
          slotValues: { ACTION: "finish the report" },
          topicArea: "work",
        },
        {
          en: "Did anyone bring water?",
          bn: "কেউ কি পানি এনেছে?",
          slotValues: { ACTION: "bring water" },
          topicArea: "food",
        },
        {
          en: "Did anyone notice the mistake?",
          bn: "কেউ কি ভুলটা লক্ষ্য করেছে?",
          slotValues: { ACTION: "notice the mistake" },
          topicArea: "work",
        },
        {
          en: "Did anyone go to the doctor?",
          bn: "কেউ কি ডাক্তারের কাছে গেছে?",
          slotValues: { ACTION: "go to the doctor" },
          topicArea: "health",
        },
        {
          en: "Did anyone book the tickets?",
          bn: "কেউ কি টিকিট বুক করেছে?",
          slotValues: { ACTION: "book the tickets" },
          topicArea: "travel",
        },
        {
          en: "Did anyone remember the homework?",
          bn: "কেউ কি হোমওয়ার্কের কথা মনে রেখেছে?",
          slotValues: { ACTION: "remember the homework" },
          topicArea: "education",
        },
        {
          en: "Did anyone feed the cat?",
          bn: "কেউ কি বিড়ালকে খাবার দিয়েছে?",
          slotValues: { ACTION: "feed the cat" },
          topicArea: "daily_life",
        },
        {
          en: "Did anyone reply to the email?",
          bn: "কেউ কি ইমেইলের উত্তর দিয়েছে?",
          slotValues: { ACTION: "reply to the email" },
          topicArea: "work",
        },
        {
          en: "Did anyone taste the soup?",
          bn: "কেউ কি স্যুপ চেখে দেখেছে?",
          slotValues: { ACTION: "taste the soup" },
          topicArea: "food",
        },
        {
          en: "Did anyone lock the door?",
          bn: "কেউ কি দরজা লক করেছে?",
          slotValues: { ACTION: "lock the door" },
          topicArea: "daily_life",
        },
        {
          en: "Did anyone check the weather?",
          bn: "কেউ কি আবহাওয়া দেখেছে?",
          slotValues: { ACTION: "check the weather" },
          topicArea: "travel",
        },
        {
          en: "Did anyone invite Rahim?",
          bn: "কেউ কি রহিমকে আমন্ত্রণ করেছে?",
          slotValues: { ACTION: "invite Rahim" },
          topicArea: "relationships",
        },
        {
          en: "Did anyone buy groceries?",
          bn: "কেউ কি বাজার করেছে?",
          slotValues: { ACTION: "buy groceries" },
          topicArea: "shopping",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Anyone' is used in questions and negative sentences. In questions, it asks about any person at all.",
      usageNote_bn:
        "'Anyone' প্রশ্ন ও নেতিবাচক বাক্যে ব্যবহৃত হয়। প্রশ্নে এটি যেকোনো ব্যক্তি সম্পর্কে জানতে চায়।",
    },
    {
      id: "N5.3",
      formula: "No one [ACTION+ED]",
      formula_bn: "কেউ [কাজ করে]নি",
      patternName: "No One (Negative)",
      patternName_bn: "No One (নেতিবাচক)",
      slots: [
        {
          name: "ACTION+ED",
          description: "A past tense verb or verb phrase",
          description_bn: "একটি অতীত কাল ক্রিয়া বা ক্রিয়া পদবন্ধ",
          acceptedTypes: ["verb_phrase"],
          examples: ["came to help", "told me", "knew the answer"],
        },
      ],
      examples: [
        {
          en: "No one came to help.",
          bn: "কেউ সাহায্য করতে আসেনি।",
          slotValues: { "ACTION+ED": "came to help" },
          topicArea: "daily_life",
        },
        {
          en: "No one told me about the meeting.",
          bn: "কেউ আমাকে মিটিংয়ের কথা বলেনি।",
          slotValues: { "ACTION+ED": "told me about the meeting" },
          topicArea: "work",
        },
        {
          en: "No one knew the answer.",
          bn: "কেউ উত্তর জানত না।",
          slotValues: { "ACTION+ED": "knew the answer" },
          topicArea: "education",
        },
        {
          en: "No one brought food.",
          bn: "কেউ খাবার আনেনি।",
          slotValues: { "ACTION+ED": "brought food" },
          topicArea: "food",
        },
        {
          en: "No one noticed the problem.",
          bn: "কেউ সমস্যাটা লক্ষ্য করেনি।",
          slotValues: { "ACTION+ED": "noticed the problem" },
          topicArea: "work",
        },
        {
          en: "No one was home.",
          bn: "বাড়িতে কেউ ছিল না।",
          slotValues: { "ACTION+ED": "was home" },
          topicArea: "daily_life",
        },
        {
          en: "No one asked for directions.",
          bn: "কেউ রাস্তা জিজ্ঞেস করেনি।",
          slotValues: { "ACTION+ED": "asked for directions" },
          topicArea: "travel",
        },
        {
          en: "No one wanted to go to the hospital.",
          bn: "কেউ হাসপাতালে যেতে চায়নি।",
          slotValues: { "ACTION+ED": "wanted to go to the hospital" },
          topicArea: "health",
        },
        {
          en: "No one remembered my birthday.",
          bn: "কেউ আমার জন্মদিন মনে রাখেনি।",
          slotValues: { "ACTION+ED": "remembered my birthday" },
          topicArea: "relationships",
        },
        {
          en: "No one finished the assignment.",
          bn: "কেউ অ্যাসাইনমেন্ট শেষ করেনি।",
          slotValues: { "ACTION+ED": "finished the assignment" },
          topicArea: "education",
        },
        {
          en: "No one complained about the food.",
          bn: "কেউ খাবার নিয়ে অভিযোগ করেনি।",
          slotValues: { "ACTION+ED": "complained about the food" },
          topicArea: "food",
        },
        {
          en: "No one showed up for the event.",
          bn: "ইভেন্টে কেউ আসেনি।",
          slotValues: { "ACTION+ED": "showed up for the event" },
          topicArea: "daily_life",
        },
        {
          en: "No one paid attention in class.",
          bn: "ক্লাসে কেউ মনোযোগ দেয়নি।",
          slotValues: { "ACTION+ED": "paid attention in class" },
          topicArea: "education",
        },
        {
          en: "No one offered to drive.",
          bn: "কেউ গাড়ি চালানোর প্রস্তাব দেয়নি।",
          slotValues: { "ACTION+ED": "offered to drive" },
          topicArea: "travel",
        },
        {
          en: "No one believed the story.",
          bn: "কেউ গল্পটা বিশ্বাস করেনি।",
          slotValues: { "ACTION+ED": "believed the story" },
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'No one' is a negative subject — the verb stays positive. Don't use double negatives: 'No one came' (not 'No one didn't come').",
      usageNote_bn:
        "'No one' নেতিবাচক কর্তা — ক্রিয়া ইতিবাচক থাকে। দ্বৈত নেতিবাচক ব্যবহার করবেন না: 'No one came' ('No one didn't come' নয়)।",
    },
    {
      id: "N5.4",
      formula: "Everyone [ACTION+ED]",
      formula_bn: "সবাই [কাজ করেছে]",
      patternName: "Everyone (All People)",
      patternName_bn: "Everyone (সবাই)",
      slots: [
        {
          name: "ACTION+ED",
          description: "A past tense verb or verb phrase (singular agreement)",
          description_bn:
            "একটি অতীত কাল ক্রিয়া বা ক্রিয়া পদবন্ধ (একবচন সমতা)",
          acceptedTypes: ["verb_phrase"],
          examples: ["enjoyed the party", "agreed", "passed the exam"],
        },
      ],
      examples: [
        {
          en: "Everyone enjoyed the party.",
          bn: "সবাই পার্টিটা উপভোগ করেছে।",
          slotValues: { "ACTION+ED": "enjoyed the party" },
          topicArea: "relationships",
        },
        {
          en: "Everyone agreed with the plan.",
          bn: "সবাই পরিকল্পনায় রাজি ছিল।",
          slotValues: { "ACTION+ED": "agreed with the plan" },
          topicArea: "work",
        },
        {
          en: "Everyone passed the exam.",
          bn: "সবাই পরীক্ষায় পাশ করেছে।",
          slotValues: { "ACTION+ED": "passed the exam" },
          topicArea: "education",
        },
        {
          en: "Everyone loved the food.",
          bn: "সবাই খাবারটা পছন্দ করেছে।",
          slotValues: { "ACTION+ED": "loved the food" },
          topicArea: "food",
        },
        {
          en: "Everyone arrived on time.",
          bn: "সবাই সময়মতো এসেছে।",
          slotValues: { "ACTION+ED": "arrived on time" },
          topicArea: "daily_life",
        },
        {
          en: "Everyone needs a vacation sometimes.",
          bn: "সবারই কখনো কখনো ছুটি দরকার।",
          slotValues: { "ACTION+ED": "needs a vacation sometimes" },
          topicArea: "travel",
        },
        {
          en: "Everyone felt better after the medicine.",
          bn: "ওষুধ খাওয়ার পরে সবাই ভালো অনুভব করেছে।",
          slotValues: { "ACTION+ED": "felt better after the medicine" },
          topicArea: "health",
        },
        {
          en: "Everyone contributed to the project.",
          bn: "সবাই প্রকল্পে অবদান রেখেছে।",
          slotValues: { "ACTION+ED": "contributed to the project" },
          topicArea: "work",
        },
        {
          en: "Everyone brought something to share.",
          bn: "সবাই ভাগ করার জন্য কিছু এনেছে।",
          slotValues: { "ACTION+ED": "brought something to share" },
          topicArea: "food",
        },
        {
          en: "Everyone respected the teacher.",
          bn: "সবাই শিক্ষককে সম্মান করত।",
          slotValues: { "ACTION+ED": "respected the teacher" },
          topicArea: "education",
        },
        {
          en: "Everyone clapped after the speech.",
          bn: "বক্তৃতার পরে সবাই হাততালি দিয়েছে।",
          slotValues: { "ACTION+ED": "clapped after the speech" },
          topicArea: "daily_life",
        },
        {
          en: "Everyone wanted to visit the new mall.",
          bn: "সবাই নতুন মলটা দেখতে চেয়েছিল।",
          slotValues: { "ACTION+ED": "wanted to visit the new mall" },
          topicArea: "shopping",
        },
        {
          en: "Everyone missed the old neighborhood.",
          bn: "সবাই পুরোনো মহল্লাকে মিস করেছে।",
          slotValues: { "ACTION+ED": "missed the old neighborhood" },
          topicArea: "relationships",
        },
        {
          en: "Everyone stayed calm during the earthquake.",
          bn: "ভূমিকম্পের সময় সবাই শান্ত ছিল।",
          slotValues: { "ACTION+ED": "stayed calm during the earthquake" },
          topicArea: "daily_life",
        },
        {
          en: "Everyone had a great time at the wedding.",
          bn: "বিয়েতে সবাই দারুণ সময় কাটিয়েছে।",
          slotValues: { "ACTION+ED": "had a great time at the wedding" },
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Everyone' is grammatically singular, so use singular verbs: 'Everyone is here' (not 'Everyone are here').",
      usageNote_bn:
        "'Everyone' ব্যাকরণগতভাবে একবচন, তাই একবচন ক্রিয়া ব্যবহার করুন: 'Everyone is here' ('Everyone are here' নয়)।",
    },
    {
      id: "N5.5",
      formula: "Something is [DESC]",
      formula_bn: "কিছু একটা [বর্ণনা]",
      patternName: "Something/Anything/Nothing",
      patternName_bn: "Something/Anything/Nothing",
      slots: [
        {
          name: "DESC",
          description: "An adjective or descriptive phrase",
          description_bn: "একটি বিশেষণ বা বর্ণনামূলক পদবন্ধ",
          acceptedTypes: ["adjective", "adjective_phrase"],
          examples: ["wrong", "missing", "different"],
        },
      ],
      examples: [
        {
          en: "Something is wrong.",
          bn: "কিছু একটা সমস্যা আছে।",
          slotValues: { DESC: "wrong" },
          topicArea: "daily_life",
        },
        {
          en: "Something is missing from the report.",
          bn: "রিপোর্ট থেকে কিছু একটা বাদ পড়েছে।",
          slotValues: { DESC: "missing from the report" },
          topicArea: "work",
        },
        {
          en: "Something is different about you today.",
          bn: "আজ তোমার মধ্যে কিছু একটা আলাদা।",
          slotValues: { DESC: "different about you today" },
          topicArea: "relationships",
        },
        {
          en: "Something is burning in the kitchen.",
          bn: "রান্নাঘরে কিছু একটা পুড়ছে।",
          slotValues: { DESC: "burning in the kitchen" },
          topicArea: "food",
        },
        {
          en: "Nothing is impossible.",
          bn: "কিছুই অসম্ভব নয়।",
          slotValues: { DESC: "impossible" },
          topicArea: "daily_life",
        },
        {
          en: "Is anything wrong?",
          bn: "কোনো সমস্যা আছে কি?",
          slotValues: { DESC: "wrong" },
          topicArea: "health",
        },
        {
          en: "Something is stuck in the machine.",
          bn: "মেশিনে কিছু একটা আটকে গেছে।",
          slotValues: { DESC: "stuck in the machine" },
          topicArea: "work",
        },
        {
          en: "Nothing is open this late.",
          bn: "এত রাতে কিছুই খোলা নেই।",
          slotValues: { DESC: "open this late" },
          topicArea: "shopping",
        },
        {
          en: "Something is making a strange noise.",
          bn: "কিছু একটা অদ্ভুত শব্দ করছে।",
          slotValues: { DESC: "making a strange noise" },
          topicArea: "daily_life",
        },
        {
          en: "Is anything available for tomorrow?",
          bn: "আগামীকালের জন্য কিছু কি আছে?",
          slotValues: { DESC: "available for tomorrow" },
          topicArea: "travel",
        },
        {
          en: "Nothing is free in this world.",
          bn: "এই দুনিয়ায় কিছুই বিনামূল্যে নয়।",
          slotValues: { DESC: "free in this world" },
          topicArea: "daily_life",
        },
        {
          en: "Something is bothering me.",
          bn: "কিছু একটা আমাকে বিরক্ত করছে।",
          slotValues: { DESC: "bothering me" },
          topicArea: "health",
        },
        {
          en: "Is anything planned for the weekend?",
          bn: "সপ্তাহান্তে কিছু পরিকল্পনা আছে কি?",
          slotValues: { DESC: "planned for the weekend" },
          topicArea: "daily_life",
        },
        {
          en: "Something is not right with this order.",
          bn: "এই অর্ডারে কিছু একটা ঠিক নেই।",
          slotValues: { DESC: "not right with this order" },
          topicArea: "food",
        },
        {
          en: "Nothing is more important than health.",
          bn: "স্বাস্থ্যের চেয়ে গুরুত্বপূর্ণ কিছু নেই।",
          slotValues: { DESC: "more important than health" },
          topicArea: "health",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "'Something' is for positive sentences, 'anything' for questions/negatives, and 'nothing' for negation without 'not'.",
      usageNote_bn:
        "'Something' ইতিবাচক বাক্যে, 'anything' প্রশ্ন/নেতিবাচকে এবং 'nothing' 'not' ছাড়া নেতিবাচক বোঝাতে ব্যবহৃত হয়।",
    },
  ],
};
