import { PatternCategory } from "@/types/pattern";

export const categoryO3: PatternCategory = {
  id: "O3",
  slug: "adding-background",
  name: "Adding Background",
  name_bn: "পটভূমি যোগ করা",
  description:
    "Provide context and background information when telling a story.",
  description_bn:
    "গল্প বলার সময় প্রেক্ষাপট ও পটভূমির তথ্য প্রদান করুন।",
  icon: "🌅",
  group: "O",
  groupName: "Narrating & Storytelling",
  groupName_bn: "বর্ণনা ও গল্প বলা",
  difficulty: "intermediate",
  patterns: [
    {
      id: "O3.1",
      formula: "At that time, [CLAUSE]",
      formula_bn: "সেই সময়, [বাক্যাংশ]",
      patternName: "At That Time",
      patternName_bn: "সেই সময়",
      slots: [{ name: "CLAUSE", description: "Background situation or context", description_bn: "পটভূমি পরিস্থিতি বা প্রসঙ্গ", acceptedTypes: ["clause"], examples: ["I was living in Dhaka", "we didn't have much money", "I was still a student"] }],
      examples: [
        { en: "At that time, I was living in Dhaka.", bn: "সেই সময়, আমি ঢাকায় থাকতাম।", slotValues: { CLAUSE: "I was living in Dhaka" }, topicArea: "daily_life" },
        { en: "At that time, we didn't have much money.", bn: "সেই সময়, আমাদের বেশি টাকা ছিল না।", slotValues: { CLAUSE: "we didn't have much money" }, topicArea: "daily_life" },
        { en: "At that time, I was still a student.", bn: "সেই সময়, আমি তখনও ছাত্র ছিলাম।", slotValues: { CLAUSE: "I was still a student" }, topicArea: "education" },
        { en: "At that time, my father was working abroad.", bn: "সেই সময়, আমার বাবা বিদেশে কাজ করতেন।", slotValues: { CLAUSE: "my father was working abroad" }, topicArea: "relationships" },
        { en: "At that time, I didn't know how to cook.", bn: "সেই সময়, আমি রান্না করতে জানতাম না।", slotValues: { CLAUSE: "I didn't know how to cook" }, topicArea: "food" },
        { en: "At that time, public transport was very poor.", bn: "সেই সময়, গণপরিবহন অনেক খারাপ ছিল।", slotValues: { CLAUSE: "public transport was very poor" }, topicArea: "travel" },
        { en: "At that time, I was dealing with health issues.", bn: "সেই সময়, আমি স্বাস্থ্য সমস্যা নিয়ে ভুগছিলাম।", slotValues: { CLAUSE: "I was dealing with health issues" }, topicArea: "health" },
        { en: "At that time, I had just started my first job.", bn: "সেই সময়, আমি সবে প্রথম চাকরি শুরু করেছিলাম।", slotValues: { CLAUSE: "I had just started my first job" }, topicArea: "work" },
        { en: "At that time, smartphones didn't exist.", bn: "সেই সময়, স্মার্টফোন ছিল না।", slotValues: { CLAUSE: "smartphones didn't exist" }, topicArea: "daily_life" },
        { en: "At that time, everything was cheaper.", bn: "সেই সময়, সবকিছু সস্তা ছিল।", slotValues: { CLAUSE: "everything was cheaper" }, topicArea: "shopping" },
        { en: "At that time, we lived in a small village.", bn: "সেই সময়, আমরা একটা ছোট গ্রামে থাকতাম।", slotValues: { CLAUSE: "we lived in a small village" }, topicArea: "daily_life" },
        { en: "At that time, I was preparing for my exams.", bn: "সেই সময়, আমি পরীক্ষার প্রস্তুতি নিচ্ছিলাম।", slotValues: { CLAUSE: "I was preparing for my exams" }, topicArea: "education" },
        { en: "At that time, my grandmother used to cook for us.", bn: "সেই সময়, আমার দাদি আমাদের জন্য রান্না করতেন।", slotValues: { CLAUSE: "my grandmother used to cook for us" }, topicArea: "food" },
        { en: "At that time, I was very shy.", bn: "সেই সময়, আমি অনেক লাজুক ছিলাম।", slotValues: { CLAUSE: "I was very shy" }, topicArea: "relationships" },
        { en: "At that time, the company was very small.", bn: "সেই সময়, কোম্পানিটা অনেক ছোট ছিল।", slotValues: { CLAUSE: "the company was very small" }, topicArea: "work" },
      ],
      formality: "casual",
      difficulty: "intermediate",
    },
    {
      id: "O3.2",
      formula: "Back then, [CLAUSE]",
      formula_bn: "তখনকার দিনে, [বাক্যাংশ]",
      patternName: "Back Then",
      patternName_bn: "তখনকার দিনে",
      slots: [{ name: "CLAUSE", description: "A past context or habitual situation", description_bn: "অতীতের একটি প্রেক্ষাপট বা অভ্যাসগত পরিস্থিতি", acceptedTypes: ["clause"], examples: ["things were different", "we used to walk everywhere", "life was simpler"] }],
      examples: [
        { en: "Back then, things were different.", bn: "তখনকার দিনে, জিনিসপত্র আলাদা ছিল।", slotValues: { CLAUSE: "things were different" }, topicArea: "daily_life" },
        { en: "Back then, we used to walk everywhere.", bn: "তখনকার দিনে, আমরা সব জায়গায় হেঁটে যেতাম।", slotValues: { CLAUSE: "we used to walk everywhere" }, topicArea: "travel" },
        { en: "Back then, life was simpler.", bn: "তখনকার দিনে, জীবন সহজ ছিল।", slotValues: { CLAUSE: "life was simpler" }, topicArea: "daily_life" },
        { en: "Back then, we cooked on a wood stove.", bn: "তখনকার দিনে, আমরা কাঠের চুলায় রান্না করতাম।", slotValues: { CLAUSE: "we cooked on a wood stove" }, topicArea: "food" },
        { en: "Back then, I didn't speak any English.", bn: "তখনকার দিনে, আমি একটুও ইংরেজি বলতে পারতাম না।", slotValues: { CLAUSE: "I didn't speak any English" }, topicArea: "education" },
        { en: "Back then, there were no hospitals nearby.", bn: "তখনকার দিনে, কাছাকাছি কোনো হাসপাতাল ছিল না।", slotValues: { CLAUSE: "there were no hospitals nearby" }, topicArea: "health" },
        { en: "Back then, everyone knew their neighbors.", bn: "তখনকার দিনে, সবাই তাদের প্রতিবেশীদের চিনত।", slotValues: { CLAUSE: "everyone knew their neighbors" }, topicArea: "relationships" },
        { en: "Back then, jobs were hard to find.", bn: "তখনকার দিনে, চাকরি খুঁজে পাওয়া কঠিন ছিল।", slotValues: { CLAUSE: "jobs were hard to find" }, topicArea: "work" },
        { en: "Back then, there were no shopping malls.", bn: "তখনকার দিনে, কোনো শপিং মল ছিল না।", slotValues: { CLAUSE: "there were no shopping malls" }, topicArea: "shopping" },
        { en: "Back then, we traveled by boat.", bn: "তখনকার দিনে, আমরা নৌকায় ভ্রমণ করতাম।", slotValues: { CLAUSE: "we traveled by boat" }, topicArea: "travel" },
        { en: "Back then, I was afraid of the dark.", bn: "তখনকার দিনে, আমি অন্ধকার ভয় পেতাম।", slotValues: { CLAUSE: "I was afraid of the dark" }, topicArea: "daily_life" },
        { en: "Back then, my mother made everything from scratch.", bn: "তখনকার দিনে, আমার মা সবকিছু একদম শুরু থেকে বানাতেন।", slotValues: { CLAUSE: "my mother made everything from scratch" }, topicArea: "food" },
        { en: "Back then, we studied under kerosene lamps.", bn: "তখনকার দিনে, আমরা কেরোসিনের বাতিতে পড়তাম।", slotValues: { CLAUSE: "we studied under kerosene lamps" }, topicArea: "education" },
        { en: "Back then, my grandfather was the head of the family.", bn: "তখনকার দিনে, আমার দাদা পরিবারের প্রধান ছিলেন।", slotValues: { CLAUSE: "my grandfather was the head of the family" }, topicArea: "relationships" },
        { en: "Back then, there were only a few offices in town.", bn: "তখনকার দিনে, শহরে মাত্র কয়েকটা অফিস ছিল।", slotValues: { CLAUSE: "there were only a few offices in town" }, topicArea: "work" },
      ],
      formality: "casual",
      difficulty: "intermediate",
    },
    {
      id: "O3.3",
      formula: "I remember [CLAUSE/DOING]",
      formula_bn: "আমার মনে আছে [বাক্যাংশ/করার কথা]",
      patternName: "I Remember",
      patternName_bn: "আমার মনে আছে",
      slots: [{ name: "CLAUSE/DOING", description: "A past memory or action", description_bn: "একটি অতীত স্মৃতি বা কাজ", acceptedTypes: ["clause", "gerund"], examples: ["playing in the rain", "when we first moved here", "my first day at school"] }],
      examples: [
        { en: "I remember playing in the rain as a child.", bn: "আমার মনে আছে ছোটবেলায় বৃষ্টিতে খেলার কথা।", slotValues: { "CLAUSE/DOING": "playing in the rain as a child" }, topicArea: "daily_life" },
        { en: "I remember when we first moved here.", bn: "আমার মনে আছে যখন আমরা প্রথম এখানে এসেছিলাম।", slotValues: { "CLAUSE/DOING": "when we first moved here" }, topicArea: "daily_life" },
        { en: "I remember my first day at school.", bn: "আমার মনে আছে স্কুলে আমার প্রথম দিনের কথা।", slotValues: { "CLAUSE/DOING": "my first day at school" }, topicArea: "education" },
        { en: "I remember eating my grandmother's hilsa fish.", bn: "আমার মনে আছে দাদির রান্না করা ইলিশ মাছ খাওয়ার কথা।", slotValues: { "CLAUSE/DOING": "eating my grandmother's hilsa fish" }, topicArea: "food" },
        { en: "I remember traveling by train for the first time.", bn: "আমার মনে আছে প্রথমবার ট্রেনে ভ্রমণ করার কথা।", slotValues: { "CLAUSE/DOING": "traveling by train for the first time" }, topicArea: "travel" },
        { en: "I remember being scared of injections.", bn: "আমার মনে আছে ইনজেকশনে ভয় পেতাম।", slotValues: { "CLAUSE/DOING": "being scared of injections" }, topicArea: "health" },
        { en: "I remember getting my first paycheck.", bn: "আমার মনে আছে আমার প্রথম বেতন পাওয়ার কথা।", slotValues: { "CLAUSE/DOING": "getting my first paycheck" }, topicArea: "work" },
        { en: "I remember buying my first bicycle.", bn: "আমার মনে আছে আমার প্রথম সাইকেল কেনার কথা।", slotValues: { "CLAUSE/DOING": "buying my first bicycle" }, topicArea: "shopping" },
        { en: "I remember when this road was a dirt path.", bn: "আমার মনে আছে যখন এই রাস্তা কাঁচা ছিল।", slotValues: { "CLAUSE/DOING": "when this road was a dirt path" }, topicArea: "travel" },
        { en: "I remember spending Eid with my whole family.", bn: "আমার মনে আছে পুরো পরিবারের সাথে ঈদ কাটানোর কথা।", slotValues: { "CLAUSE/DOING": "spending Eid with my whole family" }, topicArea: "relationships" },
        { en: "I remember studying all night before exams.", bn: "আমার মনে আছে পরীক্ষার আগে সারা রাত পড়ার কথা।", slotValues: { "CLAUSE/DOING": "studying all night before exams" }, topicArea: "education" },
        { en: "I remember when a kilogram of rice cost very little.", bn: "আমার মনে আছে যখন এক কেজি চালের দাম অনেক কম ছিল।", slotValues: { "CLAUSE/DOING": "when a kilogram of rice cost very little" }, topicArea: "shopping" },
        { en: "I remember feeling nervous at my interview.", bn: "আমার মনে আছে ইন্টারভিউতে নার্ভাস লাগছিল।", slotValues: { "CLAUSE/DOING": "feeling nervous at my interview" }, topicArea: "work" },
        { en: "I remember when my baby brother was born.", bn: "আমার মনে আছে যখন আমার ছোট ভাই জন্মেছিল।", slotValues: { "CLAUSE/DOING": "when my baby brother was born" }, topicArea: "relationships" },
        { en: "I remember the smell of my mother's cooking.", bn: "আমার মনে আছে আমার মায়ের রান্নার গন্ধ।", slotValues: { "CLAUSE/DOING": "the smell of my mother's cooking" }, topicArea: "food" },
      ],
      formality: "casual",
      difficulty: "intermediate",
    },
    {
      id: "O3.4",
      formula: "You have to understand, [CLAUSE]",
      formula_bn: "তোমাকে বুঝতে হবে, [বাক্যাংশ]",
      patternName: "Setting Context",
      patternName_bn: "প্রসঙ্গ সেট করা",
      slots: [{ name: "CLAUSE", description: "Important background that explains the story", description_bn: "গল্পকে ব্যাখ্যা করে এমন গুরুত্বপূর্ণ পটভূমি", acceptedTypes: ["clause"], examples: ["I was only 15 at the time", "this was before mobile phones", "we had no choice"] }],
      examples: [
        { en: "You have to understand, I was only 15 at the time.", bn: "তোমাকে বুঝতে হবে, আমি তখন মাত্র ১৫ বছর ছিলাম।", slotValues: { CLAUSE: "I was only 15 at the time" }, topicArea: "daily_life" },
        { en: "You have to understand, this was before mobile phones.", bn: "তোমাকে বুঝতে হবে, এটা মোবাইল ফোনের আগের কথা।", slotValues: { CLAUSE: "this was before mobile phones" }, topicArea: "daily_life" },
        { en: "You have to understand, we had no choice.", bn: "তোমাকে বুঝতে হবে, আমাদের কোনো উপায় ছিল না।", slotValues: { CLAUSE: "we had no choice" }, topicArea: "daily_life" },
        { en: "You have to understand, the road was completely flooded.", bn: "তোমাকে বুঝতে হবে, রাস্তা পুরোপুরি ডুবে ছিল।", slotValues: { CLAUSE: "the road was completely flooded" }, topicArea: "travel" },
        { en: "You have to understand, I had never cooked before.", bn: "তোমাকে বুঝতে হবে, আমি আগে কখনো রান্না করিনি।", slotValues: { CLAUSE: "I had never cooked before" }, topicArea: "food" },
        { en: "You have to understand, I was very sick at the time.", bn: "তোমাকে বুঝতে হবে, আমি তখন অনেক অসুস্থ ছিলাম।", slotValues: { CLAUSE: "I was very sick at the time" }, topicArea: "health" },
        { en: "You have to understand, it was my first job.", bn: "তোমাকে বুঝতে হবে, এটা আমার প্রথম চাকরি ছিল।", slotValues: { CLAUSE: "it was my first job" }, topicArea: "work" },
        { en: "You have to understand, nobody supported my decision.", bn: "তোমাকে বুঝতে হবে, কেউ আমার সিদ্ধান্ত সমর্থন করেনি।", slotValues: { CLAUSE: "nobody supported my decision" }, topicArea: "relationships" },
        { en: "You have to understand, I didn't have any money.", bn: "তোমাকে বুঝতে হবে, আমার কোনো টাকা ছিল না।", slotValues: { CLAUSE: "I didn't have any money" }, topicArea: "shopping" },
        { en: "You have to understand, the exam system was very different.", bn: "তোমাকে বুঝতে হবে, পরীক্ষা ব্যবস্থা তখন অনেক আলাদা ছিল।", slotValues: { CLAUSE: "the exam system was very different" }, topicArea: "education" },
        { en: "You have to understand, I was new to the city.", bn: "তোমাকে বুঝতে হবে, আমি তখন শহরে নতুন ছিলাম।", slotValues: { CLAUSE: "I was new to the city" }, topicArea: "travel" },
        { en: "You have to understand, there was no internet back then.", bn: "তোমাকে বুঝতে হবে, তখন ইন্টারনেট ছিল না।", slotValues: { CLAUSE: "there was no internet back then" }, topicArea: "daily_life" },
        { en: "You have to understand, my whole family depended on me.", bn: "তোমাকে বুঝতে হবে, আমার পুরো পরিবার আমার উপর নির্ভরশীল ছিল।", slotValues: { CLAUSE: "my whole family depended on me" }, topicArea: "relationships" },
        { en: "You have to understand, the nearest hospital was 50 kilometers away.", bn: "তোমাকে বুঝতে হবে, নিকটতম হাসপাতাল ছিল ৫০ কিলোমিটার দূরে।", slotValues: { CLAUSE: "the nearest hospital was 50 kilometers away" }, topicArea: "health" },
        { en: "You have to understand, I was managing everything alone.", bn: "তোমাকে বুঝতে হবে, আমি একাই সব সামলাচ্ছিলাম।", slotValues: { CLAUSE: "I was managing everything alone" }, topicArea: "work" },
      ],
      formality: "casual",
      difficulty: "intermediate",
    },
    {
      id: "O3.5",
      formula: "The thing is, [CLAUSE]",
      formula_bn: "ব্যাপারটা হলো, [বাক্যাংশ]",
      patternName: "The Thing Is (Key Detail)",
      patternName_bn: "ব্যাপারটা হলো (মূল বিষয়)",
      slots: [{ name: "CLAUSE", description: "An important detail or complication", description_bn: "একটি গুরুত্বপূর্ণ বিবরণ বা জটিলতা", acceptedTypes: ["clause"], examples: ["I didn't know the way", "nobody told me", "it was already too late"] }],
      examples: [
        { en: "The thing is, I didn't know the way.", bn: "ব্যাপারটা হলো, আমি রাস্তা জানতাম না।", slotValues: { CLAUSE: "I didn't know the way" }, topicArea: "travel" },
        { en: "The thing is, nobody told me about the change.", bn: "ব্যাপারটা হলো, কেউ আমাকে পরিবর্তনের কথা বলেনি।", slotValues: { CLAUSE: "nobody told me about the change" }, topicArea: "work" },
        { en: "The thing is, it was already too late.", bn: "ব্যাপারটা হলো, ততক্ষণে অনেক দেরি হয়ে গেছিল।", slotValues: { CLAUSE: "it was already too late" }, topicArea: "daily_life" },
        { en: "The thing is, I can't eat spicy food.", bn: "ব্যাপারটা হলো, আমি ঝাল খাবার খেতে পারি না।", slotValues: { CLAUSE: "I can't eat spicy food" }, topicArea: "food" },
        { en: "The thing is, I hadn't studied for the exam.", bn: "ব্যাপারটা হলো, আমি পরীক্ষার জন্য পড়িনি।", slotValues: { CLAUSE: "I hadn't studied for the exam" }, topicArea: "education" },
        { en: "The thing is, I'm allergic to that medicine.", bn: "ব্যাপারটা হলো, আমার ওই ওষুধে অ্যালার্জি।", slotValues: { CLAUSE: "I'm allergic to that medicine" }, topicArea: "health" },
        { en: "The thing is, I was already committed to another project.", bn: "ব্যাপারটা হলো, আমি আগেই আরেকটা প্রকল্পে প্রতিশ্রুতিবদ্ধ ছিলাম।", slotValues: { CLAUSE: "I was already committed to another project" }, topicArea: "work" },
        { en: "The thing is, I forgot to bring my wallet.", bn: "ব্যাপারটা হলো, আমি মানিব্যাগ আনতে ভুলে গেছিলাম।", slotValues: { CLAUSE: "I forgot to bring my wallet" }, topicArea: "shopping" },
        { en: "The thing is, we were already late.", bn: "ব্যাপারটা হলো, আমরা আগেই দেরি করে ফেলেছিলাম।", slotValues: { CLAUSE: "we were already late" }, topicArea: "travel" },
        { en: "The thing is, she didn't want to go.", bn: "ব্যাপারটা হলো, সে যেতে চায়নি।", slotValues: { CLAUSE: "she didn't want to go" }, topicArea: "relationships" },
        { en: "The thing is, the recipe needed ingredients I didn't have.", bn: "ব্যাপারটা হলো, রেসিপিতে এমন উপকরণ লাগত যা আমার ছিল না।", slotValues: { CLAUSE: "the recipe needed ingredients I didn't have" }, topicArea: "food" },
        { en: "The thing is, I didn't have the right qualifications.", bn: "ব্যাপারটা হলো, আমার সঠিক যোগ্যতা ছিল না।", slotValues: { CLAUSE: "I didn't have the right qualifications" }, topicArea: "education" },
        { en: "The thing is, the symptoms kept coming back.", bn: "ব্যাপারটা হলো, লক্ষণগুলো বারবার ফিরে আসছিল।", slotValues: { CLAUSE: "the symptoms kept coming back" }, topicArea: "health" },
        { en: "The thing is, I had promised someone else first.", bn: "ব্যাপারটা হলো, আমি আগেই অন্য কাউকে কথা দিয়ে ফেলেছিলাম।", slotValues: { CLAUSE: "I had promised someone else first" }, topicArea: "relationships" },
        { en: "The thing is, the budget had already been spent.", bn: "ব্যাপারটা হলো, বাজেট আগেই খরচ হয়ে গিয়েছিল।", slotValues: { CLAUSE: "the budget had already been spent" }, topicArea: "work" },
      ],
      formality: "casual",
      difficulty: "intermediate",
    },
  ],
};
