import { PatternCategory } from "@/types/pattern";

export const categoryO5: PatternCategory = {
  id: "O5",
  slug: "unexpected-events",
  name: "Unexpected Events",
  name_bn: "অপ্রত্যাশিত ঘটনা",
  description: "Describe surprising twists and unexpected turns in a story.",
  description_bn: "গল্পে আশ্চর্যজনক মোড় ও অপ্রত্যাশিত পরিবর্তন বর্ণনা করুন।",
  icon: "😲",
  group: "O",
  groupName: "Narrating & Storytelling",
  groupName_bn: "বর্ণনা ও গল্প বলা",
  difficulty: "intermediate",
  patterns: [
    {
      id: "O5.1", formula: "I was about to [ACTION] when [EVENT]", formula_bn: "আমি [কাজ] করতে যাচ্ছিলাম যখন [ঘটনা]", patternName: "About To... When", patternName_bn: "করতে যাচ্ছিলাম... যখন",
      slots: [
        { name: "ACTION", description: "An action you were about to do", description_bn: "আপনি যে কাজটি করতে যাচ্ছিলেন", acceptedTypes: ["verb", "verb_phrase"], examples: ["leave", "call him", "start eating"] },
        { name: "EVENT", description: "The interrupting event", description_bn: "বাধাদানকারী ঘটনা", acceptedTypes: ["clause", "event"], examples: ["the phone rang", "it started raining", "I heard a scream"] },
      ],
      examples: [
        { en: "I was about to leave when the phone rang.", bn: "আমি বের হতে যাচ্ছিলাম যখন ফোন বেজে উঠল।", slotValues: { ACTION: "leave", EVENT: "the phone rang" }, topicArea: "daily_life" },
        { en: "I was about to call him when he showed up.", bn: "আমি তাকে ফোন করতে যাচ্ছিলাম যখন সে হাজির হলো।", slotValues: { ACTION: "call him", EVENT: "he showed up" }, topicArea: "relationships" },
        { en: "I was about to start eating when I got an urgent email.", bn: "আমি খেতে শুরু করতে যাচ্ছিলাম যখন একটা জরুরি ইমেইল এলো।", slotValues: { ACTION: "start eating", EVENT: "I got an urgent email" }, topicArea: "work" },
        { en: "I was about to board the plane when they announced a delay.", bn: "আমি প্লেনে উঠতে যাচ্ছিলাম যখন তারা দেরির ঘোষণা দিল।", slotValues: { ACTION: "board the plane", EVENT: "they announced a delay" }, topicArea: "travel" },
        { en: "I was about to serve the food when the power went out.", bn: "আমি খাবার পরিবেশন করতে যাচ্ছিলাম যখন বিদ্যুৎ চলে গেল।", slotValues: { ACTION: "serve the food", EVENT: "the power went out" }, topicArea: "food" },
        { en: "I was about to submit the exam when I found a mistake.", bn: "আমি পরীক্ষা জমা দিতে যাচ্ছিলাম যখন একটা ভুল পেলাম।", slotValues: { ACTION: "submit the exam", EVENT: "I found a mistake" }, topicArea: "education" },
        { en: "I was about to take the medicine when I read the expiry date.", bn: "আমি ওষুধ খেতে যাচ্ছিলাম যখন মেয়াদ দেখলাম।", slotValues: { ACTION: "take the medicine", EVENT: "I read the expiry date" }, topicArea: "health" },
        { en: "I was about to pay when I realized my wallet was missing.", bn: "আমি পেমেন্ট করতে যাচ্ছিলাম যখন বুঝলাম মানিব্যাগ নেই।", slotValues: { ACTION: "pay", EVENT: "I realized my wallet was missing" }, topicArea: "shopping" },
        { en: "I was about to sleep when my neighbor started singing.", bn: "আমি ঘুমাতে যাচ্ছিলাম যখন প্রতিবেশী গান শুরু করল।", slotValues: { ACTION: "sleep", EVENT: "my neighbor started singing" }, topicArea: "daily_life" },
        { en: "I was about to cross the road when a car sped by.", bn: "আমি রাস্তা পার হতে যাচ্ছিলাম যখন একটা গাড়ি দ্রুত চলে গেল।", slotValues: { ACTION: "cross the road", EVENT: "a car sped by" }, topicArea: "travel" },
        { en: "I was about to order when the waiter said they were closing.", bn: "আমি অর্ডার দিতে যাচ্ছিলাম যখন ওয়েটার বলল তারা বন্ধ করছে।", slotValues: { ACTION: "order", EVENT: "the waiter said they were closing" }, topicArea: "food" },
        { en: "I was about to propose when she brought up another topic.", bn: "আমি প্রস্তাব দিতে যাচ্ছিলাম যখন সে অন্য বিষয় তুলল।", slotValues: { ACTION: "propose", EVENT: "she brought up another topic" }, topicArea: "relationships" },
        { en: "I was about to send the email when I noticed a typo.", bn: "আমি ইমেইল পাঠাতে যাচ্ছিলাম যখন একটা টাইপো দেখলাম।", slotValues: { ACTION: "send the email", EVENT: "I noticed a typo" }, topicArea: "work" },
        { en: "I was about to give up when I found the answer.", bn: "আমি হাল ছেড়ে দিতে যাচ্ছিলাম যখন উত্তর পেলাম।", slotValues: { ACTION: "give up", EVENT: "I found the answer" }, topicArea: "education" },
        { en: "I was about to go to the pharmacy when I found the medicine at home.", bn: "আমি ফার্মেসিতে যেতে যাচ্ছিলাম যখন বাড়িতে ওষুধ পেলাম।", slotValues: { ACTION: "go to the pharmacy", EVENT: "I found the medicine at home" }, topicArea: "health" },
      ],
      formality: "casual", difficulty: "intermediate",
    },
    {
      id: "O5.2", formula: "To my surprise, [CLAUSE]", formula_bn: "আমার আশ্চর্যের বিষয়, [বাক্যাংশ]", patternName: "To My Surprise", patternName_bn: "আমার আশ্চর্যের বিষয়",
      slots: [{ name: "CLAUSE", description: "A surprising outcome", description_bn: "একটি আশ্চর্যজনক ফলাফল", acceptedTypes: ["clause"], examples: ["she already knew", "it was free", "I won first place"] }],
      examples: [
        { en: "To my surprise, she already knew about it.", bn: "আমার আশ্চর্যের বিষয়, সে আগেই জানত।", slotValues: { CLAUSE: "she already knew about it" }, topicArea: "relationships" },
        { en: "To my surprise, the concert was free.", bn: "আমার আশ্চর্যের বিষয়, কনসার্টটা বিনামূল্যে ছিল।", slotValues: { CLAUSE: "the concert was free" }, topicArea: "daily_life" },
        { en: "To my surprise, I won first place.", bn: "আমার আশ্চর্যের বিষয়, আমি প্রথম স্থান পেলাম।", slotValues: { CLAUSE: "I won first place" }, topicArea: "education" },
        { en: "To my surprise, the food was delicious.", bn: "আমার আশ্চর্যের বিষয়, খাবারটা অসাধারণ ছিল।", slotValues: { CLAUSE: "the food was delicious" }, topicArea: "food" },
        { en: "To my surprise, the flight was on time.", bn: "আমার আশ্চর্যের বিষয়, ফ্লাইট সময়মতো ছিল।", slotValues: { CLAUSE: "the flight was on time" }, topicArea: "travel" },
        { en: "To my surprise, the test results were normal.", bn: "আমার আশ্চর্যের বিষয়, পরীক্ষার ফলাফল স্বাভাবিক ছিল।", slotValues: { CLAUSE: "the test results were normal" }, topicArea: "health" },
        { en: "To my surprise, I got the promotion.", bn: "আমার আশ্চর্যের বিষয়, আমি পদোন্নতি পেলাম।", slotValues: { CLAUSE: "I got the promotion" }, topicArea: "work" },
        { en: "To my surprise, the price dropped significantly.", bn: "আমার আশ্চর্যের বিষয়, দাম অনেক কমে গেল।", slotValues: { CLAUSE: "the price dropped significantly" }, topicArea: "shopping" },
        { en: "To my surprise, everyone remembered my birthday.", bn: "আমার আশ্চর্যের বিষয়, সবাই আমার জন্মদিন মনে রেখেছিল।", slotValues: { CLAUSE: "everyone remembered my birthday" }, topicArea: "relationships" },
        { en: "To my surprise, the hotel upgraded our room.", bn: "আমার আশ্চর্যের বিষয়, হোটেল আমাদের রুম আপগ্রেড করে দিল।", slotValues: { CLAUSE: "the hotel upgraded our room" }, topicArea: "travel" },
        { en: "To my surprise, the cake turned out perfectly.", bn: "আমার আশ্চর্যের বিষয়, কেকটা একদম পারফেক্ট হয়েছে।", slotValues: { CLAUSE: "the cake turned out perfectly" }, topicArea: "food" },
        { en: "To my surprise, I understood the whole lecture.", bn: "আমার আশ্চর্যের বিষয়, আমি পুরো লেকচারটা বুঝেছি।", slotValues: { CLAUSE: "I understood the whole lecture" }, topicArea: "education" },
        { en: "To my surprise, the pain disappeared overnight.", bn: "আমার আশ্চর্যের বিষয়, রাতারাতি ব্যথা চলে গেল।", slotValues: { CLAUSE: "the pain disappeared overnight" }, topicArea: "health" },
        { en: "To my surprise, the boss agreed immediately.", bn: "আমার আশ্চর্যের বিষয়, বস সাথে সাথেই রাজি হলেন।", slotValues: { CLAUSE: "the boss agreed immediately" }, topicArea: "work" },
        { en: "To my surprise, they had exactly what I was looking for.", bn: "আমার আশ্চর্যের বিষয়, আমি যা খুঁজছিলাম ঠিক সেটাই তাদের কাছে ছিল।", slotValues: { CLAUSE: "they had exactly what I was looking for" }, topicArea: "shopping" },
      ],
      formality: "polite", difficulty: "intermediate",
    },
    {
      id: "O5.3", formula: "Suddenly, [EVENT]", formula_bn: "হঠাৎ, [ঘটনা]", patternName: "Suddenly", patternName_bn: "হঠাৎ",
      slots: [{ name: "EVENT", description: "An abrupt event", description_bn: "একটি আকস্মিক ঘটনা", acceptedTypes: ["clause", "event"], examples: ["the lights went off", "I heard a loud crash", "everyone started running"] }],
      examples: [
        { en: "Suddenly, the lights went off.", bn: "হঠাৎ, বাতি চলে গেল।", slotValues: { EVENT: "the lights went off" }, topicArea: "daily_life" },
        { en: "Suddenly, I heard a loud crash.", bn: "হঠাৎ, জোরে ধাক্কার শব্দ শুনলাম।", slotValues: { EVENT: "I heard a loud crash" }, topicArea: "daily_life" },
        { en: "Suddenly, everyone started running.", bn: "হঠাৎ, সবাই দৌড়াতে শুরু করল।", slotValues: { EVENT: "everyone started running" }, topicArea: "daily_life" },
        { en: "Suddenly, a dog appeared from nowhere.", bn: "হঠাৎ, কোথা থেকে একটা কুকুর হাজির হলো।", slotValues: { EVENT: "a dog appeared from nowhere" }, topicArea: "travel" },
        { en: "Suddenly, the fire alarm went off.", bn: "হঠাৎ, ফায়ার অ্যালার্ম বেজে উঠল।", slotValues: { EVENT: "the fire alarm went off" }, topicArea: "work" },
        { en: "Suddenly, she fainted.", bn: "হঠাৎ, সে অজ্ঞান হয়ে গেল।", slotValues: { EVENT: "she fainted" }, topicArea: "health" },
        { en: "Suddenly, he burst out laughing.", bn: "হঠাৎ, সে হেসে গড়িয়ে পড়ল।", slotValues: { EVENT: "he burst out laughing" }, topicArea: "relationships" },
        { en: "Suddenly, the pot boiled over.", bn: "হঠাৎ, হাঁড়ি উথলে পড়ল।", slotValues: { EVENT: "the pot boiled over" }, topicArea: "food" },
        { en: "Suddenly, it started pouring.", bn: "হঠাৎ, মুষলধারে বৃষ্টি শুরু হলো।", slotValues: { EVENT: "it started pouring" }, topicArea: "travel" },
        { en: "Suddenly, the answer came to me.", bn: "হঠাৎ, উত্তরটা মনে পড়ে গেল।", slotValues: { EVENT: "the answer came to me" }, topicArea: "education" },
        { en: "Suddenly, the bus stopped in the middle of the road.", bn: "হঠাৎ, বাস রাস্তার মাঝখানে থেমে গেল।", slotValues: { EVENT: "the bus stopped in the middle of the road" }, topicArea: "travel" },
        { en: "Suddenly, the baby started crying.", bn: "হঠাৎ, বাচ্চা কাঁদতে শুরু করল।", slotValues: { EVENT: "the baby started crying" }, topicArea: "relationships" },
        { en: "Suddenly, my laptop screen went black.", bn: "হঠাৎ, আমার ল্যাপটপের স্ক্রিন কালো হয়ে গেল।", slotValues: { EVENT: "my laptop screen went black" }, topicArea: "work" },
        { en: "Suddenly, I felt dizzy.", bn: "হঠাৎ, আমার মাথা ঘুরতে লাগল।", slotValues: { EVENT: "I felt dizzy" }, topicArea: "health" },
        { en: "Suddenly, the shelf collapsed.", bn: "হঠাৎ, তাকটা ভেঙে পড়ল।", slotValues: { EVENT: "the shelf collapsed" }, topicArea: "shopping" },
      ],
      formality: "casual", difficulty: "intermediate",
    },
    {
      id: "O5.4", formula: "Out of nowhere, [EVENT]", formula_bn: "অকস্মাৎ, [ঘটনা]", patternName: "Out of Nowhere", patternName_bn: "অকস্মাৎ / কোথা থেকে",
      slots: [{ name: "EVENT", description: "A completely unexpected event", description_bn: "সম্পূর্ণ অপ্রত্যাশিত ঘটনা", acceptedTypes: ["clause", "event"], examples: ["a car appeared", "she called me", "an opportunity came"] }],
      examples: [
        { en: "Out of nowhere, a car appeared.", bn: "অকস্মাৎ, একটা গাড়ি এসে হাজির।", slotValues: { EVENT: "a car appeared" }, topicArea: "travel" },
        { en: "Out of nowhere, she called me after ten years.", bn: "অকস্মাৎ, দশ বছর পর সে আমাকে ফোন করল।", slotValues: { EVENT: "she called me after ten years" }, topicArea: "relationships" },
        { en: "Out of nowhere, an opportunity came my way.", bn: "অকস্মাৎ, একটা সুযোগ আমার কাছে এলো।", slotValues: { EVENT: "an opportunity came my way" }, topicArea: "work" },
        { en: "Out of nowhere, a storm hit the city.", bn: "অকস্মাৎ, শহরে ঝড় আঘাত হানল।", slotValues: { EVENT: "a storm hit the city" }, topicArea: "daily_life" },
        { en: "Out of nowhere, a cat jumped on the table.", bn: "অকস্মাৎ, একটা বিড়াল টেবিলে লাফিয়ে উঠল।", slotValues: { EVENT: "a cat jumped on the table" }, topicArea: "food" },
        { en: "Out of nowhere, the teacher gave us a pop quiz.", bn: "অকস্মাৎ, শিক্ষক আমাদের হুট করে কুইজ দিলেন।", slotValues: { EVENT: "the teacher gave us a pop quiz" }, topicArea: "education" },
        { en: "Out of nowhere, my headache went away.", bn: "অকস্মাৎ, আমার মাথা ব্যথা চলে গেল।", slotValues: { EVENT: "my headache went away" }, topicArea: "health" },
        { en: "Out of nowhere, the client changed their mind.", bn: "অকস্মাৎ, ক্লায়েন্ট মত পাল্টাল।", slotValues: { EVENT: "the client changed their mind" }, topicArea: "work" },
        { en: "Out of nowhere, a huge sale appeared online.", bn: "অকস্মাৎ, অনলাইনে বিশাল সেল দেখা দিল।", slotValues: { EVENT: "a huge sale appeared online" }, topicArea: "shopping" },
        { en: "Out of nowhere, my friend showed up at my door.", bn: "অকস্মাৎ, আমার বন্ধু দরজায় হাজির।", slotValues: { EVENT: "my friend showed up at my door" }, topicArea: "relationships" },
        { en: "Out of nowhere, the bus driver took a wrong turn.", bn: "অকস্মাৎ, বাস ড্রাইভার ভুল বাঁকে ঘুরল।", slotValues: { EVENT: "the bus driver took a wrong turn" }, topicArea: "travel" },
        { en: "Out of nowhere, I got a craving for biryani.", bn: "অকস্মাৎ, বিরিয়ানি খাওয়ার তীব্র ইচ্ছা হলো।", slotValues: { EVENT: "I got a craving for biryani" }, topicArea: "food" },
        { en: "Out of nowhere, I remembered the formula.", bn: "অকস্মাৎ, সূত্রটা মনে পড়ে গেল।", slotValues: { EVENT: "I remembered the formula" }, topicArea: "education" },
        { en: "Out of nowhere, my back started hurting.", bn: "অকস্মাৎ, পিঠে ব্যথা শুরু হলো।", slotValues: { EVENT: "my back started hurting" }, topicArea: "health" },
        { en: "Out of nowhere, the electricity came back.", bn: "অকস্মাৎ, বিদ্যুৎ ফিরে এলো।", slotValues: { EVENT: "the electricity came back" }, topicArea: "daily_life" },
      ],
      formality: "casual", difficulty: "intermediate",
    },
    {
      id: "O5.5", formula: "Little did I know, [CLAUSE]", formula_bn: "আমি তখন জানতাম না যে, [বাক্যাংশ]", patternName: "Little Did I Know", patternName_bn: "তখন জানতাম না",
      slots: [{ name: "CLAUSE", description: "Something the speaker didn't realize at the time", description_bn: "বক্তা সেই সময় যা বুঝতে পারেননি", acceptedTypes: ["clause"], examples: ["that would change my life", "it was the wrong address", "she was planning a surprise"] }],
      examples: [
        { en: "Little did I know, that decision would change my life.", bn: "আমি তখন জানতাম না যে, সেই সিদ্ধান্ত আমার জীবন বদলে দেবে।", slotValues: { CLAUSE: "that decision would change my life" }, topicArea: "daily_life" },
        { en: "Little did I know, it was the wrong address.", bn: "আমি তখন জানতাম না যে, ঠিকানাটা ভুল ছিল।", slotValues: { CLAUSE: "it was the wrong address" }, topicArea: "travel" },
        { en: "Little did I know, she was planning a surprise party.", bn: "আমি তখন জানতাম না যে, সে সারপ্রাইজ পার্টি প্ল্যান করছে।", slotValues: { CLAUSE: "she was planning a surprise party" }, topicArea: "relationships" },
        { en: "Little did I know, the dish had peanuts in it.", bn: "আমি তখন জানতাম না যে, খাবারে বাদাম ছিল।", slotValues: { CLAUSE: "the dish had peanuts in it" }, topicArea: "food" },
        { en: "Little did I know, the exam pattern had changed.", bn: "আমি তখন জানতাম না যে, পরীক্ষার ধরন বদলে গেছে।", slotValues: { CLAUSE: "the exam pattern had changed" }, topicArea: "education" },
        { en: "Little did I know, the symptoms were serious.", bn: "আমি তখন জানতাম না যে, লক্ষণগুলো গুরুতর ছিল।", slotValues: { CLAUSE: "the symptoms were serious" }, topicArea: "health" },
        { en: "Little did I know, the company was about to close.", bn: "আমি তখন জানতাম না যে, কোম্পানি বন্ধ হতে যাচ্ছে।", slotValues: { CLAUSE: "the company was about to close" }, topicArea: "work" },
        { en: "Little did I know, the product was defective.", bn: "আমি তখন জানতাম না যে, পণ্যটিতে ত্রুটি ছিল।", slotValues: { CLAUSE: "the product was defective" }, topicArea: "shopping" },
        { en: "Little did I know, he had been my neighbor all along.", bn: "আমি তখন জানতাম না যে, সে পুরোটা সময়ই আমার প্রতিবেশী ছিল।", slotValues: { CLAUSE: "he had been my neighbor all along" }, topicArea: "relationships" },
        { en: "Little did I know, the train would be delayed by hours.", bn: "আমি তখন জানতাম না যে, ট্রেন ঘণ্টার পর ঘণ্টা দেরি হবে।", slotValues: { CLAUSE: "the train would be delayed by hours" }, topicArea: "travel" },
        { en: "Little did I know, the recipe needed overnight preparation.", bn: "আমি তখন জানতাম না যে, রেসিপিতে সারারাত প্রস্তুতি দরকার।", slotValues: { CLAUSE: "the recipe needed overnight preparation" }, topicArea: "food" },
        { en: "Little did I know, the scholarship would cover everything.", bn: "আমি তখন জানতাম না যে, বৃত্তি সবকিছু কভার করবে।", slotValues: { CLAUSE: "the scholarship would cover everything" }, topicArea: "education" },
        { en: "Little did I know, the allergy would get worse.", bn: "আমি তখন জানতাম না যে, অ্যালার্জি আরো খারাপ হবে।", slotValues: { CLAUSE: "the allergy would get worse" }, topicArea: "health" },
        { en: "Little did I know, that meeting would lead to a promotion.", bn: "আমি তখন জানতাম না যে, সেই মিটিং পদোন্নতির দিকে নিয়ে যাবে।", slotValues: { CLAUSE: "that meeting would lead to a promotion" }, topicArea: "work" },
        { en: "Little did I know, the item would be sold out the next day.", bn: "আমি তখন জানতাম না যে, পরের দিনই জিনিসটা শেষ হয়ে যাবে।", slotValues: { CLAUSE: "the item would be sold out the next day" }, topicArea: "shopping" },
      ],
      formality: "polite", difficulty: "advanced",
    },
    {
      id: "O5.6",
      formula: "Little did I know, [CLAUSE]",
      formula_bn: "আমি জানতামই না, [বাক্যাংশ]",
      patternName: "Dramatic Narrative",
      patternName_bn: "নাটকীয় বর্ণনা",
      slots: [
        {
          name: "CLAUSE",
          description: "A dramatic revelation the speaker didn't anticipate",
          description_bn: "একটি নাটকীয় প্রকাশ যা বক্তা প্রত্যাশা করেননি",
          acceptedTypes: ["clause"],
          examples: ["it was just the beginning", "everything was about to change", "the best was yet to come"],
        },
      ],
      examples: [
        { en: "Little did I know, it was just the beginning.", bn: "আমি জানতামই না, এটা ছিল শুধু শুরু।", slotValues: { CLAUSE: "it was just the beginning" }, topicArea: "daily_life" },
        { en: "Little did I know, that meal would become my signature dish.", bn: "আমি জানতামই না, সেই খাবার আমার স্বাক্ষরযুক্ত পদ হয়ে যাবে।", slotValues: { CLAUSE: "that meal would become my signature dish" }, topicArea: "food" },
        { en: "Little did I know, that trip would change everything.", bn: "আমি জানতামই না, সেই ভ্রমণ সবকিছু বদলে দেবে।", slotValues: { CLAUSE: "that trip would change everything" }, topicArea: "travel" },
        { en: "Little did I know, that teacher would inspire my whole career.", bn: "আমি জানতামই না, সেই শিক্ষক আমার পুরো ক্যারিয়ারকে অনুপ্রাণিত করবে।", slotValues: { CLAUSE: "that teacher would inspire my whole career" }, topicArea: "education" },
        { en: "Little did I know, that interview would land me my dream job.", bn: "আমি জানতামই না, সেই ইন্টারভিউ আমাকে আমার স্বপ্নের চাকরি এনে দেবে।", slotValues: { CLAUSE: "that interview would land me my dream job" }, topicArea: "work" },
        { en: "Little did I know, that small symptom was a warning sign.", bn: "আমি জানতামই না, সেই ছোট লক্ষণ একটি সতর্ক সংকেত ছিল।", slotValues: { CLAUSE: "that small symptom was a warning sign" }, topicArea: "health" },
        { en: "Little did I know, that was the last one in stock.", bn: "আমি জানতামই না, সেটা ছিল স্টকের শেষ পণ্য।", slotValues: { CLAUSE: "that was the last one in stock" }, topicArea: "shopping" },
        { en: "Little did I know, she would become my best friend.", bn: "আমি জানতামই না, সে আমার সবচেয়ে ভালো বন্ধু হয়ে যাবে।", slotValues: { CLAUSE: "she would become my best friend" }, topicArea: "relationships" },
        { en: "Little did I know, that day would be unforgettable.", bn: "আমি জানতামই না, সেই দিনটা অবিস্মরণীয় হবে।", slotValues: { CLAUSE: "that day would be unforgettable" }, topicArea: "daily_life" },
        { en: "Little did I know, cooking would become my greatest passion.", bn: "আমি জানতামই না, রান্না আমার সবচেয়ে বড় আবেগ হয়ে যাবে।", slotValues: { CLAUSE: "cooking would become my greatest passion" }, topicArea: "food" },
        { en: "Little did I know, I would end up living in that country.", bn: "আমি জানতামই না, শেষ পর্যন্ত আমি সেই দেশে থাকব।", slotValues: { CLAUSE: "I would end up living in that country" }, topicArea: "travel" },
        { en: "Little did I know, that course would open so many doors.", bn: "আমি জানতামই না, সেই কোর্স অনেক দরজা খুলে দেবে।", slotValues: { CLAUSE: "that course would open so many doors" }, topicArea: "education" },
        { en: "Little did I know, the company would double in size.", bn: "আমি জানতামই না, কোম্পানি আকারে দ্বিগুণ হয়ে যাবে।", slotValues: { CLAUSE: "the company would double in size" }, topicArea: "work" },
        { en: "Little did I know, that exercise routine would save my back.", bn: "আমি জানতামই না, সেই ব্যায়ামের রুটিন আমার পিঠ বাঁচিয়ে দেবে।", slotValues: { CLAUSE: "that exercise routine would save my back" }, topicArea: "health" },
        { en: "Little did I know, we would still be friends twenty years later.", bn: "আমি জানতামই না, বিশ বছর পরেও আমরা বন্ধু থাকব।", slotValues: { CLAUSE: "we would still be friends twenty years later" }, topicArea: "relationships" },
      ],
      formality: "polite",
      difficulty: "advanced",
      usageNote:
        "This pattern uses inverted word order for dramatic effect. It's commonly used in storytelling to build suspense and reveal unexpected outcomes.",
      usageNote_bn:
        "এই প্যাটার্নটি নাটকীয় প্রভাবের জন্য উল্টো শব্দক্রম ব্যবহার করে। গল্প বলায় সাসপেন্স তৈরি করতে এবং অপ্রত্যাশিত ফলাফল প্রকাশ করতে সাধারণত ব্যবহৃত হয়।",
      combinableWith: ["O5.2", "O5.3"],
      banglaStructureMap:
        "আমি জানতামই না (Little did I know) + [CLAUSE] (বাক্যাংশ)",
    },
  ],
};
