import { PatternCategory } from "@/types/pattern";

export const categoryO6: PatternCategory = {
  id: "O6",
  slug: "reporting-hearsay",
  name: "Reporting Hearsay",
  name_bn: "শোনা কথা জানানো",
  description: "Report what you've heard from others using hearsay patterns.",
  description_bn: "শোনা কথা ও গুজব অন্যদের কাছে জানানোর প্যাটার্ন ব্যবহার করুন।",
  icon: "👂",
  group: "O",
  groupName: "Narrating & Storytelling",
  groupName_bn: "বর্ণনা ও গল্প বলা",
  difficulty: "intermediate",
  patterns: [
    {
      id: "O6.1",
      formula: "I heard that [CLAUSE]",
      formula_bn: "আমি শুনেছি যে [উপবাক্য]",
      patternName: "I Heard That",
      patternName_bn: "আমি শুনেছি যে",
      slots: [
        {
          name: "CLAUSE",
          description: "Something you heard from someone else",
          description_bn: "অন্য কারো কাছ থেকে শোনা কিছু",
          acceptedTypes: ["clause"],
          examples: ["they're closing the shop", "she got promoted", "it's going to rain tomorrow"],
        },
      ],
      examples: [
        { en: "I heard that they're closing the shop next month.", bn: "আমি শুনেছি যে তারা আগামী মাসে দোকানটি বন্ধ করে দিচ্ছে।", slotValues: { CLAUSE: "they're closing the shop next month" }, topicArea: "daily_life" },
        { en: "I heard that she got promoted.", bn: "আমি শুনেছি যে তার পদোন্নতি হয়েছে।", slotValues: { CLAUSE: "she got promoted" }, topicArea: "work" },
        { en: "I heard that it's going to rain tomorrow.", bn: "আমি শুনেছি যে আগামীকাল বৃষ্টি হবে।", slotValues: { CLAUSE: "it's going to rain tomorrow" }, topicArea: "daily_life" },
        { en: "I heard that the new restaurant is amazing.", bn: "আমি শুনেছি যে নতুন রেস্তোরাঁটি অসাধারণ।", slotValues: { CLAUSE: "the new restaurant is amazing" }, topicArea: "food" },
        { en: "I heard that the exam has been postponed.", bn: "আমি শুনেছি যে পরীক্ষা স্থগিত হয়ে গেছে।", slotValues: { CLAUSE: "the exam has been postponed" }, topicArea: "education" },
        { en: "I heard that they broke up.", bn: "আমি শুনেছি যে তাদের সম্পর্ক ভেঙে গেছে।", slotValues: { CLAUSE: "they broke up" }, topicArea: "relationships" },
        { en: "I heard that the flight was cancelled.", bn: "আমি শুনেছি যে ফ্লাইটটি বাতিল হয়ে গেছে।", slotValues: { CLAUSE: "the flight was cancelled" }, topicArea: "travel" },
        { en: "I heard that the medicine has side effects.", bn: "আমি শুনেছি যে ওষুধটির পার্শ্বপ্রতিক্রিয়া আছে।", slotValues: { CLAUSE: "the medicine has side effects" }, topicArea: "health" },
        { en: "I heard that the company is hiring.", bn: "আমি শুনেছি যে কোম্পানিটি লোক নিচ্ছে।", slotValues: { CLAUSE: "the company is hiring" }, topicArea: "work" },
        { en: "I heard that the sale starts this weekend.", bn: "আমি শুনেছি যে এই সপ্তাহান্তে সেল শুরু হচ্ছে।", slotValues: { CLAUSE: "the sale starts this weekend" }, topicArea: "shopping" },
        { en: "I heard that he moved to another city.", bn: "আমি শুনেছি যে সে অন্য শহরে চলে গেছে।", slotValues: { CLAUSE: "he moved to another city" }, topicArea: "daily_life" },
        { en: "I heard that the teacher is very strict.", bn: "আমি শুনেছি যে শিক্ষক খুব কঠোর।", slotValues: { CLAUSE: "the teacher is very strict" }, topicArea: "education" },
        { en: "I heard that the hotel is fully booked.", bn: "আমি শুনেছি যে হোটেলে কোনো রুম খালি নেই।", slotValues: { CLAUSE: "the hotel is fully booked" }, topicArea: "travel" },
        { en: "I heard that walking daily improves health.", bn: "আমি শুনেছি যে প্রতিদিন হাঁটা স্বাস্থ্যের উন্নতি করে।", slotValues: { CLAUSE: "walking daily improves health" }, topicArea: "health" },
        { en: "I heard that they're getting married next spring.", bn: "আমি শুনেছি যে তারা আগামী বসন্তে বিয়ে করছে।", slotValues: { CLAUSE: "they're getting married next spring" }, topicArea: "relationships" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "A common way to share secondhand information. Signals that the speaker did not witness the event personally.",
      usageNote_bn: "দ্বিতীয় হাত থেকে পাওয়া তথ্য শেয়ার করার একটি সাধারণ উপায়। ইঙ্গিত দেয় যে বক্তা ব্যক্তিগতভাবে ঘটনাটি দেখেননি।",
      banglaStructureMap: "আমি শুনেছি যে (Fixed phrase) + [CLAUSE] (Complete statement)",
    },
    {
      id: "O6.2",
      formula: "Apparently, [CLAUSE]",
      formula_bn: "মনে হচ্ছে/শোনা যাচ্ছে, [উপবাক্য]",
      patternName: "Apparently",
      patternName_bn: "মনে হচ্ছে/শোনা যাচ্ছে",
      slots: [
        {
          name: "CLAUSE",
          description: "Information you believe to be true based on what you've heard",
          description_bn: "শোনা কথার ভিত্তিতে আপনি যা সত্য বলে মনে করেন",
          acceptedTypes: ["clause"],
          examples: ["the boss is unhappy", "they changed the rules", "the store closed down"],
        },
      ],
      examples: [
        { en: "Apparently, the boss is unhappy with the results.", bn: "মনে হচ্ছে, বস ফলাফলে অসন্তুষ্ট।", slotValues: { CLAUSE: "the boss is unhappy with the results" }, topicArea: "work" },
        { en: "Apparently, they changed the rules.", bn: "শোনা যাচ্ছে, তারা নিয়ম পরিবর্তন করেছে।", slotValues: { CLAUSE: "they changed the rules" }, topicArea: "daily_life" },
        { en: "Apparently, the store closed down last week.", bn: "শোনা যাচ্ছে, দোকানটি গত সপ্তাহে বন্ধ হয়ে গেছে।", slotValues: { CLAUSE: "the store closed down last week" }, topicArea: "shopping" },
        { en: "Apparently, he's been sick for a while.", bn: "মনে হচ্ছে, সে বেশ কিছুদিন ধরে অসুস্থ।", slotValues: { CLAUSE: "he's been sick for a while" }, topicArea: "health" },
        { en: "Apparently, the concert is sold out.", bn: "শোনা যাচ্ছে, কনসার্টের টিকিট শেষ।", slotValues: { CLAUSE: "the concert is sold out" }, topicArea: "daily_life" },
        { en: "Apparently, they serve the best biryani in town.", bn: "শোনা যাচ্ছে, তারা শহরের সেরা বিরিয়ানি পরিবেশন করে।", slotValues: { CLAUSE: "they serve the best biryani in town" }, topicArea: "food" },
        { en: "Apparently, the university is offering scholarships.", bn: "মনে হচ্ছে, বিশ্ববিদ্যালয় বৃত্তি দিচ্ছে।", slotValues: { CLAUSE: "the university is offering scholarships" }, topicArea: "education" },
        { en: "Apparently, they had a big argument.", bn: "শোনা যাচ্ছে, তাদের বড় ঝগড়া হয়েছে।", slotValues: { CLAUSE: "they had a big argument" }, topicArea: "relationships" },
        { en: "Apparently, the train service has been disrupted.", bn: "শোনা যাচ্ছে, ট্রেন সেবা বিঘ্নিত হয়েছে।", slotValues: { CLAUSE: "the train service has been disrupted" }, topicArea: "travel" },
        { en: "Apparently, the project deadline has been extended.", bn: "মনে হচ্ছে, প্রকল্পের সময়সীমা বাড়ানো হয়েছে।", slotValues: { CLAUSE: "the project deadline has been extended" }, topicArea: "work" },
        { en: "Apparently, green tea helps with weight loss.", bn: "শোনা যাচ্ছে, গ্রিন টি ওজন কমাতে সাহায্য করে।", slotValues: { CLAUSE: "green tea helps with weight loss" }, topicArea: "health" },
        { en: "Apparently, the new teacher is from abroad.", bn: "শোনা যাচ্ছে, নতুন শিক্ষক বিদেশ থেকে এসেছেন।", slotValues: { CLAUSE: "the new teacher is from abroad" }, topicArea: "education" },
        { en: "Apparently, they're building a new mall here.", bn: "মনে হচ্ছে, তারা এখানে একটি নতুন মল তৈরি করছে।", slotValues: { CLAUSE: "they're building a new mall here" }, topicArea: "shopping" },
        { en: "Apparently, she travels to Japan every year.", bn: "শোনা যাচ্ছে, সে প্রতি বছর জাপানে যায়।", slotValues: { CLAUSE: "she travels to Japan every year" }, topicArea: "travel" },
        { en: "Apparently, they've been friends since childhood.", bn: "মনে হচ্ছে, তারা ছোটবেলা থেকেই বন্ধু।", slotValues: { CLAUSE: "they've been friends since childhood" }, topicArea: "relationships" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "Used to report something you believe to be true but haven't confirmed yourself. Slightly more informal than 'I heard that'.",
      usageNote_bn: "এমন কিছু জানাতে ব্যবহৃত হয় যা আপনি সত্য বলে মনে করেন কিন্তু নিজে নিশ্চিত করেননি। 'I heard that'-এর চেয়ে একটু বেশি অনানুষ্ঠানিক।",
      banglaStructureMap: "মনে হচ্ছে/শোনা যাচ্ছে (Adverb) + [CLAUSE] (Complete statement)",
    },
    {
      id: "O6.3",
      formula: "Rumor has it that [CLAUSE]",
      formula_bn: "গুজব আছে যে [উপবাক্য]",
      patternName: "Rumor Has It",
      patternName_bn: "গুজব আছে",
      slots: [
        {
          name: "CLAUSE",
          description: "An unconfirmed piece of information spreading among people",
          description_bn: "মানুষের মধ্যে ছড়িয়ে পড়া একটি অনিশ্চিত তথ্য",
          acceptedTypes: ["clause"],
          examples: ["the CEO is resigning", "they're opening a new branch", "the price will go up"],
        },
      ],
      examples: [
        { en: "Rumor has it that the CEO is resigning.", bn: "গুজব আছে যে সিইও পদত্যাগ করছেন।", slotValues: { CLAUSE: "the CEO is resigning" }, topicArea: "work" },
        { en: "Rumor has it that they're opening a new branch.", bn: "গুজব আছে যে তারা একটি নতুন শাখা খুলছে।", slotValues: { CLAUSE: "they're opening a new branch" }, topicArea: "work" },
        { en: "Rumor has it that the price will go up next month.", bn: "গুজব আছে যে আগামী মাসে দাম বাড়বে।", slotValues: { CLAUSE: "the price will go up next month" }, topicArea: "shopping" },
        { en: "Rumor has it that they're secretly dating.", bn: "গুজব আছে যে তারা গোপনে ডেটিং করছে।", slotValues: { CLAUSE: "they're secretly dating" }, topicArea: "relationships" },
        { en: "Rumor has it that a famous chef is opening a restaurant here.", bn: "গুজব আছে যে একজন বিখ্যাত শেফ এখানে রেস্তোরাঁ খুলছেন।", slotValues: { CLAUSE: "a famous chef is opening a restaurant here" }, topicArea: "food" },
        { en: "Rumor has it that the school will switch to online classes.", bn: "গুজব আছে যে স্কুল অনলাইন ক্লাসে চলে যাবে।", slotValues: { CLAUSE: "the school will switch to online classes" }, topicArea: "education" },
        { en: "Rumor has it that there's a new vaccine coming out.", bn: "গুজব আছে যে নতুন একটি ভ্যাকসিন আসছে।", slotValues: { CLAUSE: "there's a new vaccine coming out" }, topicArea: "health" },
        { en: "Rumor has it that the airport will be expanded.", bn: "গুজব আছে যে বিমানবন্দর বড় করা হবে।", slotValues: { CLAUSE: "the airport will be expanded" }, topicArea: "travel" },
        { en: "Rumor has it that he won the lottery.", bn: "গুজব আছে যে সে লটারি জিতেছে।", slotValues: { CLAUSE: "he won the lottery" }, topicArea: "daily_life" },
        { en: "Rumor has it that the company is being sold.", bn: "গুজব আছে যে কোম্পানিটি বিক্রি হচ্ছে।", slotValues: { CLAUSE: "the company is being sold" }, topicArea: "work" },
        { en: "Rumor has it that they're planning a surprise party.", bn: "গুজব আছে যে তারা সারপ্রাইজ পার্টির পরিকল্পনা করছে।", slotValues: { CLAUSE: "they're planning a surprise party" }, topicArea: "relationships" },
        { en: "Rumor has it that the old market is being demolished.", bn: "গুজব আছে যে পুরনো বাজারটি ভেঙে ফেলা হচ্ছে।", slotValues: { CLAUSE: "the old market is being demolished" }, topicArea: "daily_life" },
        { en: "Rumor has it that the new phone will be half the price.", bn: "গুজব আছে যে নতুন ফোনটির দাম অর্ধেক হবে।", slotValues: { CLAUSE: "the new phone will be half the price" }, topicArea: "shopping" },
        { en: "Rumor has it that the professor is retiring this year.", bn: "গুজব আছে যে অধ্যাপক এই বছর অবসর নিচ্ছেন।", slotValues: { CLAUSE: "the professor is retiring this year" }, topicArea: "education" },
        { en: "Rumor has it that the beach resort is haunted.", bn: "গুজব আছে যে সমুদ্র সৈকতের রিসোর্টটিতে ভূত আছে।", slotValues: { CLAUSE: "the beach resort is haunted" }, topicArea: "travel" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "A dramatic way to introduce gossip or unverified information. More colorful than 'I heard that'.",
      usageNote_bn: "গুজব বা অনিশ্চিত তথ্য জানানোর একটি নাটকীয় উপায়। 'I heard that'-এর চেয়ে বেশি রঙিন।",
      banglaStructureMap: "গুজব আছে যে (Fixed phrase) + [CLAUSE] (Complete statement)",
    },
    {
      id: "O6.4",
      formula: "Word is that [CLAUSE]",
      formula_bn: "কথা হচ্ছে যে [উপবাক্য]",
      patternName: "Word Is That",
      patternName_bn: "কথা হচ্ছে যে",
      slots: [
        {
          name: "CLAUSE",
          description: "Information that is circulating informally",
          description_bn: "অনানুষ্ঠানিকভাবে ছড়িয়ে পড়া তথ্য",
          acceptedTypes: ["clause"],
          examples: ["they're merging the departments", "the rent is going up", "she's leaving the team"],
        },
      ],
      examples: [
        { en: "Word is that they're merging the departments.", bn: "কথা হচ্ছে যে তারা বিভাগগুলো একত্রিত করছে।", slotValues: { CLAUSE: "they're merging the departments" }, topicArea: "work" },
        { en: "Word is that the rent is going up.", bn: "কথা হচ্ছে যে ভাড়া বাড়ছে।", slotValues: { CLAUSE: "the rent is going up" }, topicArea: "daily_life" },
        { en: "Word is that she's leaving the team.", bn: "কথা হচ্ছে যে সে দল ছেড়ে যাচ্ছে।", slotValues: { CLAUSE: "she's leaving the team" }, topicArea: "work" },
        { en: "Word is that the bakery has the best cakes.", bn: "কথা হচ্ছে যে বেকারিতে সেরা কেক পাওয়া যায়।", slotValues: { CLAUSE: "the bakery has the best cakes" }, topicArea: "food" },
        { en: "Word is that the finals are going to be harder this year.", bn: "কথা হচ্ছে যে এই বছর ফাইনাল পরীক্ষা কঠিন হবে।", slotValues: { CLAUSE: "the finals are going to be harder this year" }, topicArea: "education" },
        { en: "Word is that they've reconciled.", bn: "কথা হচ্ছে যে তারা মিটমাট করেছে।", slotValues: { CLAUSE: "they've reconciled" }, topicArea: "relationships" },
        { en: "Word is that the clinic is offering free checkups.", bn: "কথা হচ্ছে যে ক্লিনিকে বিনামূল্যে চেকআপ দিচ্ছে।", slotValues: { CLAUSE: "the clinic is offering free checkups" }, topicArea: "health" },
        { en: "Word is that the new highway will cut travel time in half.", bn: "কথা হচ্ছে যে নতুন মহাসড়ক ভ্রমণের সময় অর্ধেক করবে।", slotValues: { CLAUSE: "the new highway will cut travel time in half" }, topicArea: "travel" },
        { en: "Word is that the store is having a clearance sale.", bn: "কথা হচ্ছে যে দোকানে ক্লিয়ারেন্স সেল চলছে।", slotValues: { CLAUSE: "the store is having a clearance sale" }, topicArea: "shopping" },
        { en: "Word is that they're planning a community event.", bn: "কথা হচ্ছে যে তারা একটি সম্প্রদায়িক অনুষ্ঠানের পরিকল্পনা করছে।", slotValues: { CLAUSE: "they're planning a community event" }, topicArea: "daily_life" },
        { en: "Word is that the manager is being transferred.", bn: "কথা হচ্ছে যে ম্যানেজারকে বদলি করা হচ্ছে।", slotValues: { CLAUSE: "the manager is being transferred" }, topicArea: "work" },
        { en: "Word is that the food truck has amazing tacos.", bn: "কথা হচ্ছে যে ফুড ট্রাকে অসাধারণ ট্যাকো পাওয়া যায়।", slotValues: { CLAUSE: "the food truck has amazing tacos" }, topicArea: "food" },
        { en: "Word is that the library is getting renovated.", bn: "কথা হচ্ছে যে লাইব্রেরি সংস্কার করা হচ্ছে।", slotValues: { CLAUSE: "the library is getting renovated" }, topicArea: "education" },
        { en: "Word is that yoga helps with back pain.", bn: "কথা হচ্ছে যে যোগব্যায়াম পিঠের ব্যথায় সাহায্য করে।", slotValues: { CLAUSE: "yoga helps with back pain" }, topicArea: "health" },
        { en: "Word is that the island is a hidden gem for tourists.", bn: "কথা হচ্ছে যে দ্বীপটি পর্যটকদের জন্য একটি লুকানো রত্ন।", slotValues: { CLAUSE: "the island is a hidden gem for tourists" }, topicArea: "travel" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "An informal way to share news or gossip. Similar to 'Rumor has it' but slightly more neutral.",
      usageNote_bn: "খবর বা গুজব শেয়ার করার একটি অনানুষ্ঠানিক উপায়। 'Rumor has it'-এর মতো কিন্তু একটু বেশি নিরপেক্ষ।",
      banglaStructureMap: "কথা হচ্ছে যে (Fixed phrase) + [CLAUSE] (Complete statement)",
    },
    {
      id: "O6.5",
      formula: "People say that [CLAUSE]",
      formula_bn: "মানুষ বলে যে [উপবাক্য]",
      patternName: "People Say That",
      patternName_bn: "মানুষ বলে যে",
      slots: [
        {
          name: "CLAUSE",
          description: "A widely held belief or commonly shared opinion",
          description_bn: "ব্যাপকভাবে প্রচলিত বিশ্বাস বা সাধারণভাবে শেয়ার করা মতামত",
          acceptedTypes: ["clause"],
          examples: ["money can't buy happiness", "this place is haunted", "he's the best doctor in town"],
        },
      ],
      examples: [
        { en: "People say that money can't buy happiness.", bn: "মানুষ বলে যে টাকা দিয়ে সুখ কেনা যায় না।", slotValues: { CLAUSE: "money can't buy happiness" }, topicArea: "daily_life" },
        { en: "People say that this place is haunted.", bn: "মানুষ বলে যে এই জায়গাটিতে ভূত আছে।", slotValues: { CLAUSE: "this place is haunted" }, topicArea: "travel" },
        { en: "People say that he's the best doctor in town.", bn: "মানুষ বলে যে তিনি শহরের সেরা ডাক্তার।", slotValues: { CLAUSE: "he's the best doctor in town" }, topicArea: "health" },
        { en: "People say that the early bird catches the worm.", bn: "মানুষ বলে যে যে আগে ওঠে সেই লাভ পায়।", slotValues: { CLAUSE: "the early bird catches the worm" }, topicArea: "daily_life" },
        { en: "People say that the new manager is very fair.", bn: "মানুষ বলে যে নতুন ম্যানেজার খুব ন্যায্য।", slotValues: { CLAUSE: "the new manager is very fair" }, topicArea: "work" },
        { en: "People say that the street food here is the best.", bn: "মানুষ বলে যে এখানকার রাস্তার খাবার সেরা।", slotValues: { CLAUSE: "the street food here is the best" }, topicArea: "food" },
        { en: "People say that practice makes perfect.", bn: "মানুষ বলে যে অনুশীলনে পরিপূর্ণতা আসে।", slotValues: { CLAUSE: "practice makes perfect" }, topicArea: "education" },
        { en: "People say that honesty is the best policy.", bn: "মানুষ বলে যে সততাই সর্বোত্তম নীতি।", slotValues: { CLAUSE: "honesty is the best policy" }, topicArea: "relationships" },
        { en: "People say that laughter is the best medicine.", bn: "মানুষ বলে যে হাসি সেরা ওষুধ।", slotValues: { CLAUSE: "laughter is the best medicine" }, topicArea: "health" },
        { en: "People say that this brand is overpriced.", bn: "মানুষ বলে যে এই ব্র্যান্ডের দাম বেশি।", slotValues: { CLAUSE: "this brand is overpriced" }, topicArea: "shopping" },
        { en: "People say that hard work pays off eventually.", bn: "মানুষ বলে যে পরিশ্রম শেষ পর্যন্ত ফল দেয়।", slotValues: { CLAUSE: "hard work pays off eventually" }, topicArea: "work" },
        { en: "People say that the sunset from this hill is breathtaking.", bn: "মানুষ বলে যে এই পাহাড় থেকে সূর্যাস্ত অসাধারণ।", slotValues: { CLAUSE: "the sunset from this hill is breathtaking" }, topicArea: "travel" },
        { en: "People say that breakfast is the most important meal.", bn: "মানুষ বলে যে সকালের নাস্তা সবচেয়ে গুরুত্বপূর্ণ খাবার।", slotValues: { CLAUSE: "breakfast is the most important meal" }, topicArea: "food" },
        { en: "People say that reading expands the mind.", bn: "মানুষ বলে যে পড়া মনকে প্রসারিত করে।", slotValues: { CLAUSE: "reading expands the mind" }, topicArea: "education" },
        { en: "People say that true friends are hard to find.", bn: "মানুষ বলে যে সত্যিকারের বন্ধু পাওয়া কঠিন।", slotValues: { CLAUSE: "true friends are hard to find" }, topicArea: "relationships" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "Used to cite common wisdom or general opinion. Less specific than 'I heard that' since it doesn't imply a particular source.",
      usageNote_bn: "সাধারণ জ্ঞান বা সাধারণ মতামত উদ্ধৃত করতে ব্যবহৃত হয়। 'I heard that'-এর চেয়ে কম নির্দিষ্ট কারণ এটি কোনো নির্দিষ্ট উৎস বোঝায় না।",
      banglaStructureMap: "মানুষ বলে যে (Subject + Verb) + [CLAUSE] (Complete statement)",
    },
  ],
};
