import { PatternCategory } from "@/types/pattern";

export const categoryO7: PatternCategory = {
  id: "O7",
  slug: "describing-experiences",
  name: "Describing Experiences",
  name_bn: "অভিজ্ঞতা বর্ণনা",
  description: "Share and describe memorable experiences using vivid patterns.",
  description_bn: "প্রাণবন্ত প্যাটার্ন ব্যবহার করে স্মরণীয় অভিজ্ঞতা শেয়ার ও বর্ণনা করুন।",
  icon: "🌟",
  group: "O",
  groupName: "Narrating & Storytelling",
  groupName_bn: "বর্ণনা ও গল্প বলা",
  difficulty: "intermediate",
  patterns: [
    {
      id: "O7.1",
      formula: "It was [ADJ] to [ACTION]",
      formula_bn: "[কাজ] করা [বিশেষণ] ছিল",
      patternName: "It Was... To...",
      patternName_bn: "এটি ছিল... করতে...",
      slots: [
        {
          name: "ADJ",
          description: "An adjective describing the experience",
          description_bn: "অভিজ্ঞতা বর্ণনাকারী একটি বিশেষণ",
          acceptedTypes: ["adjective"],
          examples: ["amazing", "terrifying", "wonderful"],
        },
        {
          name: "ACTION",
          description: "The activity or action experienced",
          description_bn: "যে কাজ বা কার্যকলাপ অভিজ্ঞতা হয়েছে",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["see the mountains", "meet her", "travel alone"],
        },
      ],
      examples: [
        { en: "It was amazing to see the mountains.", bn: "পাহাড়গুলো দেখা অসাধারণ ছিল।", slotValues: { ADJ: "amazing", ACTION: "see the mountains" }, topicArea: "travel" },
        { en: "It was terrifying to drive in that storm.", bn: "সেই ঝড়ের মধ্যে গাড়ি চালানো ভয়ংকর ছিল।", slotValues: { ADJ: "terrifying", ACTION: "drive in that storm" }, topicArea: "travel" },
        { en: "It was wonderful to meet her in person.", bn: "তার সাথে সামনাসামনি দেখা হওয়া চমৎকার ছিল।", slotValues: { ADJ: "wonderful", ACTION: "meet her in person" }, topicArea: "relationships" },
        { en: "It was exciting to start a new job.", bn: "নতুন চাকরি শুরু করা উত্তেজনাপূর্ণ ছিল।", slotValues: { ADJ: "exciting", ACTION: "start a new job" }, topicArea: "work" },
        { en: "It was difficult to say goodbye.", bn: "বিদায় জানানো কঠিন ছিল।", slotValues: { ADJ: "difficult", ACTION: "say goodbye" }, topicArea: "relationships" },
        { en: "It was refreshing to try the local food.", bn: "স্থানীয় খাবার চেষ্টা করা সতেজকর ছিল।", slotValues: { ADJ: "refreshing", ACTION: "try the local food" }, topicArea: "food" },
        { en: "It was inspiring to attend the lecture.", bn: "বক্তৃতায় অংশ নেওয়া অনুপ্রেরণামূলক ছিল।", slotValues: { ADJ: "inspiring", ACTION: "attend the lecture" }, topicArea: "education" },
        { en: "It was stressful to prepare for the exam.", bn: "পরীক্ষার প্রস্তুতি নেওয়া চাপের ছিল।", slotValues: { ADJ: "stressful", ACTION: "prepare for the exam" }, topicArea: "education" },
        { en: "It was heartwarming to see them reunite.", bn: "তাদের পুনর্মিলন দেখা হৃদয়স্পর্শী ছিল।", slotValues: { ADJ: "heartwarming", ACTION: "see them reunite" }, topicArea: "relationships" },
        { en: "It was painful to recover from the surgery.", bn: "অস্ত্রোপচার থেকে সুস্থ হওয়া কষ্টকর ছিল।", slotValues: { ADJ: "painful", ACTION: "recover from the surgery" }, topicArea: "health" },
        { en: "It was delightful to taste the homemade cake.", bn: "ঘরে তৈরি কেক খাওয়া আনন্দদায়ক ছিল।", slotValues: { ADJ: "delightful", ACTION: "taste the homemade cake" }, topicArea: "food" },
        { en: "It was challenging to learn a new language.", bn: "নতুন ভাষা শেখা চ্যালেঞ্জিং ছিল।", slotValues: { ADJ: "challenging", ACTION: "learn a new language" }, topicArea: "education" },
        { en: "It was rewarding to finish the project on time.", bn: "সময়মতো প্রকল্প শেষ করা পুরস্কারমূলক ছিল।", slotValues: { ADJ: "rewarding", ACTION: "finish the project on time" }, topicArea: "work" },
        { en: "It was scary to go bungee jumping.", bn: "বাঞ্জি জাম্পিং করতে যাওয়া ভীতিকর ছিল।", slotValues: { ADJ: "scary", ACTION: "go bungee jumping" }, topicArea: "travel" },
        { en: "It was satisfying to find a great deal.", bn: "দারুণ দাম পাওয়া সন্তোষজনক ছিল।", slotValues: { ADJ: "satisfying", ACTION: "find a great deal" }, topicArea: "shopping" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "A versatile pattern to evaluate past experiences. The adjective sets the emotional tone.",
      usageNote_bn: "অতীত অভিজ্ঞতা মূল্যায়ন করার একটি বহুমুখী প্যাটার্ন। বিশেষণটি আবেগের সুর নির্ধারণ করে।",
      banglaStructureMap: "[কাজ] করা (Gerund) + [বিশেষণ] (Adjective) + ছিল (was)",
    },
    {
      id: "O7.2",
      formula: "I'll never forget [EVENT]",
      formula_bn: "আমি কখনো ভুলব না [ঘটনা]",
      patternName: "I'll Never Forget",
      patternName_bn: "আমি কখনো ভুলব না",
      slots: [
        {
          name: "EVENT",
          description: "A memorable event or moment",
          description_bn: "একটি স্মরণীয় ঘটনা বা মুহূর্ত",
          acceptedTypes: ["event", "noun_phrase", "gerund"],
          examples: ["my first day at work", "the look on her face", "that sunset in Bali"],
        },
      ],
      examples: [
        { en: "I'll never forget my first day at work.", bn: "আমি কখনো ভুলব না আমার কর্মজীবনের প্রথম দিন।", slotValues: { EVENT: "my first day at work" }, topicArea: "work" },
        { en: "I'll never forget the look on her face.", bn: "আমি কখনো ভুলব না তার মুখের অভিব্যক্তি।", slotValues: { EVENT: "the look on her face" }, topicArea: "relationships" },
        { en: "I'll never forget that sunset in Cox's Bazar.", bn: "আমি কখনো ভুলব না কক্সবাজারের সেই সূর্যাস্ত।", slotValues: { EVENT: "that sunset in Cox's Bazar" }, topicArea: "travel" },
        { en: "I'll never forget the taste of my grandmother's cooking.", bn: "আমি কখনো ভুলব না আমার দাদির রান্নার স্বাদ।", slotValues: { EVENT: "the taste of my grandmother's cooking" }, topicArea: "food" },
        { en: "I'll never forget the day I graduated.", bn: "আমি কখনো ভুলব না যেদিন আমি স্নাতক হয়েছিলাম।", slotValues: { EVENT: "the day I graduated" }, topicArea: "education" },
        { en: "I'll never forget how kind the nurses were.", bn: "আমি কখনো ভুলব না নার্সরা কত দয়ালু ছিল।", slotValues: { EVENT: "how kind the nurses were" }, topicArea: "health" },
        { en: "I'll never forget finding that perfect gift.", bn: "আমি কখনো ভুলব না সেই নিখুঁত উপহারটি খুঁজে পাওয়া।", slotValues: { EVENT: "finding that perfect gift" }, topicArea: "shopping" },
        { en: "I'll never forget the moment we met.", bn: "আমি কখনো ভুলব না আমাদের প্রথম দেখা হওয়ার মুহূর্তটি।", slotValues: { EVENT: "the moment we met" }, topicArea: "relationships" },
        { en: "I'll never forget my trip to the Sundarbans.", bn: "আমি কখনো ভুলব না সুন্দরবনে আমার ভ্রমণ।", slotValues: { EVENT: "my trip to the Sundarbans" }, topicArea: "travel" },
        { en: "I'll never forget the first meal I cooked myself.", bn: "আমি কখনো ভুলব না নিজে রান্না করা প্রথম খাবার।", slotValues: { EVENT: "the first meal I cooked myself" }, topicArea: "food" },
        { en: "I'll never forget the pressure of that final exam.", bn: "আমি কখনো ভুলব না সেই চূড়ান্ত পরীক্ষার চাপ।", slotValues: { EVENT: "the pressure of that final exam" }, topicArea: "education" },
        { en: "I'll never forget my first presentation at the office.", bn: "আমি কখনো ভুলব না অফিসে আমার প্রথম উপস্থাপনা।", slotValues: { EVENT: "my first presentation at the office" }, topicArea: "work" },
        { en: "I'll never forget the joy of hearing the good news.", bn: "আমি কখনো ভুলব না সুখবর শোনার আনন্দ।", slotValues: { EVENT: "the joy of hearing the good news" }, topicArea: "daily_life" },
        { en: "I'll never forget how scared I was during the earthquake.", bn: "আমি কখনো ভুলব না ভূমিকম্পের সময় কতটা ভয় পেয়েছিলাম।", slotValues: { EVENT: "how scared I was during the earthquake" }, topicArea: "daily_life" },
        { en: "I'll never forget the relief I felt after the surgery.", bn: "আমি কখনো ভুলব না অস্ত্রোপচারের পর যে স্বস্তি অনুভব করেছিলাম।", slotValues: { EVENT: "the relief I felt after the surgery" }, topicArea: "health" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "A strong emotional statement emphasizing that a memory is permanently etched in mind.",
      usageNote_bn: "একটি শক্তিশালী আবেগপূর্ণ বক্তব্য যা জোর দেয় যে একটি স্মৃতি স্থায়ীভাবে মনে গেঁথে আছে।",
      banglaStructureMap: "আমি কখনো ভুলব না (Fixed phrase) + [EVENT] (Noun phrase / event)",
    },
    {
      id: "O7.3",
      formula: "One of the best experiences was [DOING]",
      formula_bn: "সেরা অভিজ্ঞতাগুলোর একটি ছিল [কাজ করা]",
      patternName: "One of the Best",
      patternName_bn: "সেরাগুলোর একটি",
      slots: [
        {
          name: "DOING",
          description: "A gerund phrase describing the experience",
          description_bn: "অভিজ্ঞতা বর্ণনাকারী একটি ক্রিয়াবাচক বাক্যাংশ",
          acceptedTypes: ["gerund", "verb_phrase"],
          examples: ["visiting the old city", "learning to cook", "hiking in the mountains"],
        },
      ],
      examples: [
        { en: "One of the best experiences was visiting the old city.", bn: "সেরা অভিজ্ঞতাগুলোর একটি ছিল পুরনো শহর ঘুরে দেখা।", slotValues: { DOING: "visiting the old city" }, topicArea: "travel" },
        { en: "One of the best experiences was learning to cook biryani.", bn: "সেরা অভিজ্ঞতাগুলোর একটি ছিল বিরিয়ানি রান্না শেখা।", slotValues: { DOING: "learning to cook biryani" }, topicArea: "food" },
        { en: "One of the best experiences was hiking in the mountains.", bn: "সেরা অভিজ্ঞতাগুলোর একটি ছিল পাহাড়ে হাইকিং করা।", slotValues: { DOING: "hiking in the mountains" }, topicArea: "travel" },
        { en: "One of the best experiences was working with that team.", bn: "সেরা অভিজ্ঞতাগুলোর একটি ছিল সেই দলের সাথে কাজ করা।", slotValues: { DOING: "working with that team" }, topicArea: "work" },
        { en: "One of the best experiences was attending the music festival.", bn: "সেরা অভিজ্ঞতাগুলোর একটি ছিল মিউজিক ফেস্টিভ্যালে যোগ দেওয়া।", slotValues: { DOING: "attending the music festival" }, topicArea: "daily_life" },
        { en: "One of the best experiences was studying abroad.", bn: "সেরা অভিজ্ঞতাগুলোর একটি ছিল বিদেশে পড়াশোনা করা।", slotValues: { DOING: "studying abroad" }, topicArea: "education" },
        { en: "One of the best experiences was volunteering at the hospital.", bn: "সেরা অভিজ্ঞতাগুলোর একটি ছিল হাসপাতালে স্বেচ্ছাসেবা করা।", slotValues: { DOING: "volunteering at the hospital" }, topicArea: "health" },
        { en: "One of the best experiences was meeting my childhood friend again.", bn: "সেরা অভিজ্ঞতাগুলোর একটি ছিল আমার ছোটবেলার বন্ধুর সাথে আবার দেখা হওয়া।", slotValues: { DOING: "meeting my childhood friend again" }, topicArea: "relationships" },
        { en: "One of the best experiences was bargaining at the local market.", bn: "সেরা অভিজ্ঞতাগুলোর একটি ছিল স্থানীয় বাজারে দরদাম করা।", slotValues: { DOING: "bargaining at the local market" }, topicArea: "shopping" },
        { en: "One of the best experiences was presenting at the conference.", bn: "সেরা অভিজ্ঞতাগুলোর একটি ছিল সম্মেলনে উপস্থাপনা দেওয়া।", slotValues: { DOING: "presenting at the conference" }, topicArea: "work" },
        { en: "One of the best experiences was trying street food in Bangkok.", bn: "সেরা অভিজ্ঞতাগুলোর একটি ছিল ব্যাংককে রাস্তার খাবার চেষ্টা করা।", slotValues: { DOING: "trying street food in Bangkok" }, topicArea: "food" },
        { en: "One of the best experiences was completing my first marathon.", bn: "সেরা অভিজ্ঞতাগুলোর একটি ছিল আমার প্রথম ম্যারাথন সম্পন্ন করা।", slotValues: { DOING: "completing my first marathon" }, topicArea: "health" },
        { en: "One of the best experiences was watching the sunrise from the hilltop.", bn: "সেরা অভিজ্ঞতাগুলোর একটি ছিল পাহাড়ের চূড়া থেকে সূর্যোদয় দেখা।", slotValues: { DOING: "watching the sunrise from the hilltop" }, topicArea: "travel" },
        { en: "One of the best experiences was teaching my younger brother.", bn: "সেরা অভিজ্ঞতাগুলোর একটি ছিল আমার ছোট ভাইকে পড়ানো।", slotValues: { DOING: "teaching my younger brother" }, topicArea: "education" },
        { en: "One of the best experiences was celebrating Eid with the whole family.", bn: "সেরা অভিজ্ঞতাগুলোর একটি ছিল পুরো পরিবারের সাথে ঈদ উদযাপন করা।", slotValues: { DOING: "celebrating Eid with the whole family" }, topicArea: "relationships" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "Used to highlight a standout experience from a collection of memories. Great for storytelling.",
      usageNote_bn: "স্মৃতির সংগ্রহ থেকে একটি বিশেষ অভিজ্ঞতা তুলে ধরতে ব্যবহৃত হয়। গল্প বলার জন্য দারুণ।",
      banglaStructureMap: "সেরা অভিজ্ঞতাগুলোর একটি ছিল (Fixed phrase) + [DOING] (Gerund phrase)",
    },
    {
      id: "O7.4",
      formula: "I had a great time [DOING]",
      formula_bn: "আমি [কাজ করে] দারুণ সময় কাটিয়েছি",
      patternName: "Had a Great Time",
      patternName_bn: "দারুণ সময় কাটানো",
      slots: [
        {
          name: "DOING",
          description: "An activity you enjoyed",
          description_bn: "আপনি যে কাজ উপভোগ করেছেন",
          acceptedTypes: ["gerund", "verb_phrase"],
          examples: ["exploring the city", "playing with the kids", "shopping at the mall"],
        },
      ],
      examples: [
        { en: "I had a great time exploring the city.", bn: "আমি শহর ঘুরে দেখে দারুণ সময় কাটিয়েছি।", slotValues: { DOING: "exploring the city" }, topicArea: "travel" },
        { en: "I had a great time playing with the kids.", bn: "আমি বাচ্চাদের সাথে খেলে দারুণ সময় কাটিয়েছি।", slotValues: { DOING: "playing with the kids" }, topicArea: "relationships" },
        { en: "I had a great time shopping at the mall.", bn: "আমি মলে কেনাকাটা করে দারুণ সময় কাটিয়েছি।", slotValues: { DOING: "shopping at the mall" }, topicArea: "shopping" },
        { en: "I had a great time cooking with my friends.", bn: "আমি বন্ধুদের সাথে রান্না করে দারুণ সময় কাটিয়েছি।", slotValues: { DOING: "cooking with my friends" }, topicArea: "food" },
        { en: "I had a great time attending the workshop.", bn: "আমি কর্মশালায় অংশ নিয়ে দারুণ সময় কাটিয়েছি।", slotValues: { DOING: "attending the workshop" }, topicArea: "education" },
        { en: "I had a great time working on the project.", bn: "আমি প্রকল্পে কাজ করে দারুণ সময় কাটিয়েছি।", slotValues: { DOING: "working on the project" }, topicArea: "work" },
        { en: "I had a great time swimming in the ocean.", bn: "আমি সমুদ্রে সাঁতার কেটে দারুণ সময় কাটিয়েছি।", slotValues: { DOING: "swimming in the ocean" }, topicArea: "travel" },
        { en: "I had a great time catching up with old friends.", bn: "আমি পুরনো বন্ধুদের সাথে গল্প করে দারুণ সময় কাটিয়েছি।", slotValues: { DOING: "catching up with old friends" }, topicArea: "relationships" },
        { en: "I had a great time jogging in the park.", bn: "আমি পার্কে জগিং করে দারুণ সময় কাটিয়েছি।", slotValues: { DOING: "jogging in the park" }, topicArea: "health" },
        { en: "I had a great time trying out new recipes.", bn: "আমি নতুন রেসিপি চেষ্টা করে দারুণ সময় কাটিয়েছি।", slotValues: { DOING: "trying out new recipes" }, topicArea: "food" },
        { en: "I had a great time decorating the house.", bn: "আমি ঘর সাজিয়ে দারুণ সময় কাটিয়েছি।", slotValues: { DOING: "decorating the house" }, topicArea: "daily_life" },
        { en: "I had a great time volunteering at the event.", bn: "আমি অনুষ্ঠানে স্বেচ্ছাসেবা করে দারুণ সময় কাটিয়েছি।", slotValues: { DOING: "volunteering at the event" }, topicArea: "daily_life" },
        { en: "I had a great time learning pottery.", bn: "আমি মৃৎশিল্প শিখে দারুণ সময় কাটিয়েছি।", slotValues: { DOING: "learning pottery" }, topicArea: "education" },
        { en: "I had a great time brainstorming ideas with the team.", bn: "আমি দলের সাথে আইডিয়া নিয়ে আলোচনা করে দারুণ সময় কাটিয়েছি।", slotValues: { DOING: "brainstorming ideas with the team" }, topicArea: "work" },
        { en: "I had a great time hiking through the tea gardens.", bn: "আমি চা বাগানের মধ্য দিয়ে হাইকিং করে দারুণ সময় কাটিয়েছি।", slotValues: { DOING: "hiking through the tea gardens" }, topicArea: "travel" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "A cheerful way to express enjoyment of an activity. Very common in casual conversation.",
      usageNote_bn: "একটি কাজ উপভোগ করা প্রকাশ করার একটি প্রফুল্ল উপায়। অনানুষ্ঠানিক কথোপকথনে খুব সাধারণ।",
      banglaStructureMap: "আমি (Subject) + [DOING] করে (Gerund) + দারুণ সময় কাটিয়েছি (had a great time)",
    },
    {
      id: "O7.5",
      formula: "That was the first time I [PAST]",
      formula_bn: "সেটাই প্রথমবার ছিল যখন আমি [অতীত ক্রিয়া]",
      patternName: "First Time I...",
      patternName_bn: "প্রথমবার আমি...",
      slots: [
        {
          name: "PAST",
          description: "A past tense action done for the first time",
          description_bn: "প্রথমবার করা একটি অতীতকালের কাজ",
          acceptedTypes: ["clause", "verb_phrase"],
          examples: ["flew on a plane", "tried sushi", "spoke in public"],
        },
      ],
      examples: [
        { en: "That was the first time I flew on a plane.", bn: "সেটাই প্রথমবার ছিল যখন আমি প্লেনে উড়েছিলাম।", slotValues: { PAST: "flew on a plane" }, topicArea: "travel" },
        { en: "That was the first time I tried sushi.", bn: "সেটাই প্রথমবার ছিল যখন আমি সুশি খেয়েছিলাম।", slotValues: { PAST: "tried sushi" }, topicArea: "food" },
        { en: "That was the first time I spoke in public.", bn: "সেটাই প্রথমবার ছিল যখন আমি জনসমক্ষে কথা বলেছিলাম।", slotValues: { PAST: "spoke in public" }, topicArea: "education" },
        { en: "That was the first time I managed a project alone.", bn: "সেটাই প্রথমবার ছিল যখন আমি একা একটি প্রকল্প পরিচালনা করেছিলাম।", slotValues: { PAST: "managed a project alone" }, topicArea: "work" },
        { en: "That was the first time I saw snow.", bn: "সেটাই প্রথমবার ছিল যখন আমি তুষারপাত দেখেছিলাম।", slotValues: { PAST: "saw snow" }, topicArea: "travel" },
        { en: "That was the first time I cooked for someone.", bn: "সেটাই প্রথমবার ছিল যখন আমি কারো জন্য রান্না করেছিলাম।", slotValues: { PAST: "cooked for someone" }, topicArea: "relationships" },
        { en: "That was the first time I went to a gym.", bn: "সেটাই প্রথমবার ছিল যখন আমি জিমে গিয়েছিলাম।", slotValues: { PAST: "went to a gym" }, topicArea: "health" },
        { en: "That was the first time I bargained at a market.", bn: "সেটাই প্রথমবার ছিল যখন আমি বাজারে দরদাম করেছিলাম।", slotValues: { PAST: "bargained at a market" }, topicArea: "shopping" },
        { en: "That was the first time I stayed up all night studying.", bn: "সেটাই প্রথমবার ছিল যখন আমি সারারাত পড়ে কাটিয়েছিলাম।", slotValues: { PAST: "stayed up all night studying" }, topicArea: "education" },
        { en: "That was the first time I received a promotion.", bn: "সেটাই প্রথমবার ছিল যখন আমি পদোন্নতি পেয়েছিলাম।", slotValues: { PAST: "received a promotion" }, topicArea: "work" },
        { en: "That was the first time I ate at a five-star restaurant.", bn: "সেটাই প্রথমবার ছিল যখন আমি পাঁচতারা রেস্তোরাঁয় খেয়েছিলাম।", slotValues: { PAST: "ate at a five-star restaurant" }, topicArea: "food" },
        { en: "That was the first time I lived away from my family.", bn: "সেটাই প্রথমবার ছিল যখন আমি পরিবার থেকে দূরে থেকেছিলাম।", slotValues: { PAST: "lived away from my family" }, topicArea: "relationships" },
        { en: "That was the first time I donated blood.", bn: "সেটাই প্রথমবার ছিল যখন আমি রক্তদান করেছিলাম।", slotValues: { PAST: "donated blood" }, topicArea: "health" },
        { en: "That was the first time I traveled alone.", bn: "সেটাই প্রথমবার ছিল যখন আমি একা ভ্রমণ করেছিলাম।", slotValues: { PAST: "traveled alone" }, topicArea: "travel" },
        { en: "That was the first time I used an online shopping app.", bn: "সেটাই প্রথমবার ছিল যখন আমি অনলাইন শপিং অ্যাপ ব্যবহার করেছিলাম।", slotValues: { PAST: "used an online shopping app" }, topicArea: "shopping" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "Used to highlight the novelty of a past experience. Often followed by a description of how it felt.",
      usageNote_bn: "একটি অতীত অভিজ্ঞতার অভিনবত্ব তুলে ধরতে ব্যবহৃত হয়। প্রায়ই এরপর কেমন লেগেছিল তার বর্ণনা থাকে।",
      banglaStructureMap: "সেটাই প্রথমবার ছিল (Fixed phrase) + যখন আমি (when I) + [PAST] (Past tense verb phrase)",
    },
  ],
};
