import { PatternCategory } from "@/types/pattern";

export const categoryO8: PatternCategory = {
  id: "O8",
  slug: "how-something-happened",
  name: "How Something Happened",
  name_bn: "কিভাবে কিছু ঘটল",
  description: "Explain the manner and cause of events using descriptive patterns.",
  description_bn: "বর্ণনামূলক প্যাটার্ন ব্যবহার করে ঘটনার ধরন ও কারণ ব্যাখ্যা করুন।",
  icon: "🔍",
  group: "O",
  groupName: "Narrating & Storytelling",
  groupName_bn: "বর্ণনা ও গল্প বলা",
  difficulty: "intermediate",
  patterns: [
    {
      id: "O8.1",
      formula: "[PERSON] [PAST] by [DOING]",
      formula_bn: "[ব্যক্তি] [কাজ করে] [অতীত ক্রিয়া]",
      patternName: "Did Something By Doing",
      patternName_bn: "কিছু করে কিছু করেছিল",
      slots: [
        {
          name: "PERSON",
          description: "The person who performed the action",
          description_bn: "যে ব্যক্তি কাজটি করেছে",
          acceptedTypes: ["person", "noun"],
          examples: ["She", "He", "My brother"],
        },
        {
          name: "PAST",
          description: "The result or achievement in past tense",
          description_bn: "অতীতকালে ফলাফল বা অর্জন",
          acceptedTypes: ["verb_phrase"],
          examples: ["solved the problem", "won the prize", "saved money"],
        },
        {
          name: "DOING",
          description: "The method or means used",
          description_bn: "ব্যবহৃত পদ্ধতি বা উপায়",
          acceptedTypes: ["gerund", "verb_phrase"],
          examples: ["working hard", "studying every night", "cutting expenses"],
        },
      ],
      examples: [
        { en: "She solved the problem by thinking creatively.", bn: "সে সৃজনশীলভাবে চিন্তা করে সমস্যাটি সমাধান করেছিল।", slotValues: { PERSON: "She", PAST: "solved the problem", DOING: "thinking creatively" }, topicArea: "work" },
        { en: "He won the prize by practicing every day.", bn: "সে প্রতিদিন অনুশীলন করে পুরস্কার জিতেছিল।", slotValues: { PERSON: "He", PAST: "won the prize", DOING: "practicing every day" }, topicArea: "education" },
        { en: "My brother saved money by cooking at home.", bn: "আমার ভাই বাড়িতে রান্না করে টাকা বাঁচিয়েছিল।", slotValues: { PERSON: "My brother", PAST: "saved money", DOING: "cooking at home" }, topicArea: "food" },
        { en: "She improved her health by exercising regularly.", bn: "সে নিয়মিত ব্যায়াম করে তার স্বাস্থ্যের উন্নতি করেছিল।", slotValues: { PERSON: "She", PAST: "improved her health", DOING: "exercising regularly" }, topicArea: "health" },
        { en: "He got the promotion by taking on extra responsibilities.", bn: "সে অতিরিক্ত দায়িত্ব নিয়ে পদোন্নতি পেয়েছিল।", slotValues: { PERSON: "He", PAST: "got the promotion", DOING: "taking on extra responsibilities" }, topicArea: "work" },
        { en: "My friend found the hotel by asking locals.", bn: "আমার বন্ধু স্থানীয়দের জিজ্ঞেস করে হোটেলটি খুঁজে পেয়েছিল।", slotValues: { PERSON: "My friend", PAST: "found the hotel", DOING: "asking locals" }, topicArea: "travel" },
        { en: "She earned respect by being honest.", bn: "সে সৎ থেকে সম্মান অর্জন করেছিল।", slotValues: { PERSON: "She", PAST: "earned respect", DOING: "being honest" }, topicArea: "relationships" },
        { en: "He passed the exam by studying all night.", bn: "সে সারারাত পড়ে পরীক্ষায় পাস করেছিল।", slotValues: { PERSON: "He", PAST: "passed the exam", DOING: "studying all night" }, topicArea: "education" },
        { en: "My mother made delicious food by using fresh spices.", bn: "আমার মা তাজা মশলা ব্যবহার করে সুস্বাদু খাবার তৈরি করেছিলেন।", slotValues: { PERSON: "My mother", PAST: "made delicious food", DOING: "using fresh spices" }, topicArea: "food" },
        { en: "She got a discount by negotiating with the seller.", bn: "সে বিক্রেতার সাথে দরদাম করে ছাড় পেয়েছিল।", slotValues: { PERSON: "She", PAST: "got a discount", DOING: "negotiating with the seller" }, topicArea: "shopping" },
        { en: "He recovered quickly by following the doctor's advice.", bn: "সে ডাক্তারের পরামর্শ মেনে দ্রুত সুস্থ হয়ে গিয়েছিল।", slotValues: { PERSON: "He", PAST: "recovered quickly", DOING: "following the doctor's advice" }, topicArea: "health" },
        { en: "They built trust by communicating openly.", bn: "তারা খোলামেলা যোগাযোগ করে আস্থা তৈরি করেছিল।", slotValues: { PERSON: "They", PAST: "built trust", DOING: "communicating openly" }, topicArea: "relationships" },
        { en: "She explored the island by renting a scooter.", bn: "সে স্কুটার ভাড়া করে দ্বীপটি ঘুরে দেখেছিল।", slotValues: { PERSON: "She", PAST: "explored the island", DOING: "renting a scooter" }, topicArea: "travel" },
        { en: "He managed the stress by meditating daily.", bn: "সে প্রতিদিন ধ্যান করে মানসিক চাপ সামলেছিল।", slotValues: { PERSON: "He", PAST: "managed the stress", DOING: "meditating daily" }, topicArea: "daily_life" },
        { en: "My sister found the best deal by comparing prices online.", bn: "আমার বোন অনলাইনে দাম তুলনা করে সেরা ডিল খুঁজে পেয়েছিল।", slotValues: { PERSON: "My sister", PAST: "found the best deal", DOING: "comparing prices online" }, topicArea: "shopping" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "Explains the method or process someone used to achieve a result. The 'by + gerund' structure is very common.",
      usageNote_bn: "কেউ একটি ফলাফল অর্জনে যে পদ্ধতি বা প্রক্রিয়া ব্যবহার করেছে তা ব্যাখ্যা করে। 'by + gerund' গঠনটি খুবই সাধারণ।",
      banglaStructureMap: "[ব্যক্তি] (Subject) + [করে] (by doing) + [অতীত ক্রিয়া] (Past verb phrase)",
    },
    {
      id: "O8.2",
      formula: "Without [DOING], [CLAUSE]",
      formula_bn: "[কাজ] ছাড়া, [উপবাক্য]",
      patternName: "Without Doing",
      patternName_bn: "না করে / ছাড়া",
      slots: [
        {
          name: "DOING",
          description: "An action that was absent or not performed",
          description_bn: "যে কাজটি অনুপস্থিত ছিল বা করা হয়নি",
          acceptedTypes: ["gerund", "verb_phrase"],
          examples: ["studying", "telling anyone", "thinking twice"],
        },
        {
          name: "CLAUSE",
          description: "The consequence or result",
          description_bn: "ফলাফল বা পরিণতি",
          acceptedTypes: ["clause"],
          examples: ["he passed the exam", "she left the country", "they made the decision"],
        },
      ],
      examples: [
        { en: "Without studying, he still passed the exam.", bn: "না পড়েও সে পরীক্ষায় পাস করেছিল।", slotValues: { DOING: "studying", CLAUSE: "he still passed the exam" }, topicArea: "education" },
        { en: "Without telling anyone, she left the country.", bn: "কাউকে না বলে সে দেশ ছেড়ে চলে গিয়েছিল।", slotValues: { DOING: "telling anyone", CLAUSE: "she left the country" }, topicArea: "travel" },
        { en: "Without thinking twice, they made the decision.", bn: "দ্বিতীয়বার না ভেবেই তারা সিদ্ধান্ত নিয়েছিল।", slotValues: { DOING: "thinking twice", CLAUSE: "they made the decision" }, topicArea: "daily_life" },
        { en: "Without proper training, the team struggled.", bn: "সঠিক প্রশিক্ষণ ছাড়া দলটি হিমশিম খেয়েছিল।", slotValues: { DOING: "proper training", CLAUSE: "the team struggled" }, topicArea: "work" },
        { en: "Without checking the recipe, she cooked a perfect meal.", bn: "রেসিপি না দেখেই সে নিখুঁত খাবার রান্না করেছিল।", slotValues: { DOING: "checking the recipe", CLAUSE: "she cooked a perfect meal" }, topicArea: "food" },
        { en: "Without hesitating, he jumped into the water to save the child.", bn: "দ্বিধা না করে সে শিশুটিকে বাঁচাতে পানিতে ঝাঁপ দিয়েছিল।", slotValues: { DOING: "hesitating", CLAUSE: "he jumped into the water to save the child" }, topicArea: "daily_life" },
        { en: "Without exercising, you can't expect to stay healthy.", bn: "ব্যায়াম ছাড়া সুস্থ থাকার আশা করা যায় না।", slotValues: { DOING: "exercising", CLAUSE: "you can't expect to stay healthy" }, topicArea: "health" },
        { en: "Without communicating, relationships fall apart.", bn: "যোগাযোগ ছাড়া সম্পর্ক ভেঙে যায়।", slotValues: { DOING: "communicating", CLAUSE: "relationships fall apart" }, topicArea: "relationships" },
        { en: "Without comparing prices, I bought the wrong phone.", bn: "দাম তুলনা না করে আমি ভুল ফোন কিনে ফেলেছিলাম।", slotValues: { DOING: "comparing prices", CLAUSE: "I bought the wrong phone" }, topicArea: "shopping" },
        { en: "Without a map, we got lost in the city.", bn: "মানচিত্র ছাড়া আমরা শহরে হারিয়ে গিয়েছিলাম।", slotValues: { DOING: "a map", CLAUSE: "we got lost in the city" }, topicArea: "travel" },
        { en: "Without preparing, he gave an amazing presentation.", bn: "প্রস্তুতি ছাড়াই সে একটি অসাধারণ উপস্থাপনা দিয়েছিল।", slotValues: { DOING: "preparing", CLAUSE: "he gave an amazing presentation" }, topicArea: "work" },
        { en: "Without adding sugar, the tea tastes bitter.", bn: "চিনি না দিলে চা তিতো লাগে।", slotValues: { DOING: "adding sugar", CLAUSE: "the tea tastes bitter" }, topicArea: "food" },
        { en: "Without resting, the injury got worse.", bn: "বিশ্রাম না নিয়ে আঘাত আরও খারাপ হয়ে গিয়েছিল।", slotValues: { DOING: "resting", CLAUSE: "the injury got worse" }, topicArea: "health" },
        { en: "Without apologizing, he expected forgiveness.", bn: "ক্ষমা না চেয়েই সে ক্ষমা আশা করেছিল।", slotValues: { DOING: "apologizing", CLAUSE: "he expected forgiveness" }, topicArea: "relationships" },
        { en: "Without reviewing the notes, she aced the quiz.", bn: "নোট না দেখেই সে কুইজে পূর্ণ নম্বর পেয়েছিল।", slotValues: { DOING: "reviewing the notes", CLAUSE: "she aced the quiz" }, topicArea: "education" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "Shows what happened in the absence of an action. Can express surprise, consequence, or emphasis.",
      usageNote_bn: "একটি কাজের অনুপস্থিতিতে কী ঘটেছিল তা দেখায়। বিস্ময়, পরিণতি বা জোর প্রকাশ করতে পারে।",
      banglaStructureMap: "[কাজ] ছাড়া/না করে (Without + gerund) + [উপবাক্য] (Result clause)",
    },
    {
      id: "O8.3",
      formula: "[PERSON] [PAST] [ADVERB]",
      formula_bn: "[ব্যক্তি] [ক্রিয়াবিশেষণ] [অতীত ক্রিয়া]",
      patternName: "Did Something in a Way",
      patternName_bn: "কোনোভাবে কিছু করেছিল",
      slots: [
        {
          name: "PERSON",
          description: "The person who performed the action",
          description_bn: "যে ব্যক্তি কাজটি করেছে",
          acceptedTypes: ["person", "noun"],
          examples: ["She", "He", "The teacher"],
        },
        {
          name: "PAST",
          description: "A past tense action",
          description_bn: "একটি অতীতকালের কাজ",
          acceptedTypes: ["verb_phrase"],
          examples: ["spoke", "walked away", "completed the task"],
        },
        {
          name: "ADVERB",
          description: "An adverb describing how the action was done",
          description_bn: "কাজটি কীভাবে করা হয়েছিল তা বর্ণনাকারী একটি ক্রিয়াবিশেষণ",
          acceptedTypes: ["adverb"],
          examples: ["quietly", "confidently", "reluctantly"],
        },
      ],
      examples: [
        { en: "She spoke confidently at the meeting.", bn: "সে সভায় আত্মবিশ্বাসের সাথে কথা বলেছিল।", slotValues: { PERSON: "She", PAST: "spoke", ADVERB: "confidently at the meeting" }, topicArea: "work" },
        { en: "He walked away quietly.", bn: "সে চুপচাপ চলে গিয়েছিল।", slotValues: { PERSON: "He", PAST: "walked away", ADVERB: "quietly" }, topicArea: "daily_life" },
        { en: "The teacher explained the lesson patiently.", bn: "শিক্ষক ধৈর্য ধরে পাঠটি ব্যাখ্যা করেছিলেন।", slotValues: { PERSON: "The teacher", PAST: "explained the lesson", ADVERB: "patiently" }, topicArea: "education" },
        { en: "She ate her food slowly.", bn: "সে ধীরে ধীরে খাবার খেয়েছিল।", slotValues: { PERSON: "She", PAST: "ate her food", ADVERB: "slowly" }, topicArea: "food" },
        { en: "He completed the project efficiently.", bn: "সে দক্ষতার সাথে প্রকল্পটি সম্পন্ন করেছিল।", slotValues: { PERSON: "He", PAST: "completed the project", ADVERB: "efficiently" }, topicArea: "work" },
        { en: "She traveled independently across Europe.", bn: "সে স্বাধীনভাবে ইউরোপ জুড়ে ভ্রমণ করেছিল।", slotValues: { PERSON: "She", PAST: "traveled", ADVERB: "independently across Europe" }, topicArea: "travel" },
        { en: "He apologized sincerely.", bn: "সে আন্তরিকভাবে ক্ষমা চেয়েছিল।", slotValues: { PERSON: "He", PAST: "apologized", ADVERB: "sincerely" }, topicArea: "relationships" },
        { en: "The doctor examined the patient carefully.", bn: "ডাক্তার সাবধানে রোগীকে পরীক্ষা করেছিলেন।", slotValues: { PERSON: "The doctor", PAST: "examined the patient", ADVERB: "carefully" }, topicArea: "health" },
        { en: "She shopped wisely during the sale.", bn: "সে সেলের সময় বুদ্ধিমত্তার সাথে কেনাকাটা করেছিল।", slotValues: { PERSON: "She", PAST: "shopped", ADVERB: "wisely during the sale" }, topicArea: "shopping" },
        { en: "He answered the questions brilliantly.", bn: "সে উজ্জ্বলভাবে প্রশ্নগুলোর উত্তর দিয়েছিল।", slotValues: { PERSON: "He", PAST: "answered the questions", ADVERB: "brilliantly" }, topicArea: "education" },
        { en: "She cooked the meal effortlessly.", bn: "সে অনায়াসে খাবার রান্না করেছিল।", slotValues: { PERSON: "She", PAST: "cooked the meal", ADVERB: "effortlessly" }, topicArea: "food" },
        { en: "He drove cautiously on the icy road.", bn: "সে বরফে ঢাকা রাস্তায় সতর্কভাবে গাড়ি চালিয়েছিল।", slotValues: { PERSON: "He", PAST: "drove", ADVERB: "cautiously on the icy road" }, topicArea: "travel" },
        { en: "She listened attentively to her friend.", bn: "সে মনোযোগ দিয়ে তার বন্ধুর কথা শুনেছিল।", slotValues: { PERSON: "She", PAST: "listened", ADVERB: "attentively to her friend" }, topicArea: "relationships" },
        { en: "The manager handled the situation calmly.", bn: "ম্যানেজার শান্তভাবে পরিস্থিতি সামলেছিলেন।", slotValues: { PERSON: "The manager", PAST: "handled the situation", ADVERB: "calmly" }, topicArea: "work" },
        { en: "He recovered remarkably after the treatment.", bn: "চিকিৎসার পর সে অসাধারণভাবে সুস্থ হয়ে উঠেছিল।", slotValues: { PERSON: "He", PAST: "recovered", ADVERB: "remarkably after the treatment" }, topicArea: "health" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "Describes the manner of an action. Adverbs add vividness and detail to storytelling.",
      usageNote_bn: "একটি কাজের ধরন বর্ণনা করে। ক্রিয়াবিশেষণ গল্প বলায় প্রাণবন্ততা ও বিস্তারিত যোগ করে।",
      banglaStructureMap: "[ব্যক্তি] (Subject) + [ক্রিয়াবিশেষণ] (Adverb) + [অতীত ক্রিয়া] (Past verb phrase)",
    },
    {
      id: "O8.4",
      formula: "It happened because [CLAUSE]",
      formula_bn: "এটা ঘটেছিল কারণ [উপবাক্য]",
      patternName: "It Happened Because",
      patternName_bn: "এটা ঘটেছিল কারণ",
      slots: [
        {
          name: "CLAUSE",
          description: "The reason or cause of an event",
          description_bn: "একটি ঘটনার কারণ",
          acceptedTypes: ["clause"],
          examples: ["no one was paying attention", "the road was wet", "he forgot to set the alarm"],
        },
      ],
      examples: [
        { en: "It happened because no one was paying attention.", bn: "এটা ঘটেছিল কারণ কেউ মনোযোগ দিচ্ছিল না।", slotValues: { CLAUSE: "no one was paying attention" }, topicArea: "daily_life" },
        { en: "It happened because the road was wet.", bn: "এটা ঘটেছিল কারণ রাস্তা ভেজা ছিল।", slotValues: { CLAUSE: "the road was wet" }, topicArea: "travel" },
        { en: "It happened because he forgot to set the alarm.", bn: "এটা ঘটেছিল কারণ সে অ্যালার্ম দিতে ভুলে গিয়েছিল।", slotValues: { CLAUSE: "he forgot to set the alarm" }, topicArea: "daily_life" },
        { en: "It happened because the team didn't communicate well.", bn: "এটা ঘটেছিল কারণ দলটি ভালোভাবে যোগাযোগ করেনি।", slotValues: { CLAUSE: "the team didn't communicate well" }, topicArea: "work" },
        { en: "It happened because I ate something bad.", bn: "এটা ঘটেছিল কারণ আমি খারাপ কিছু খেয়েছিলাম।", slotValues: { CLAUSE: "I ate something bad" }, topicArea: "health" },
        { en: "It happened because she didn't read the instructions.", bn: "এটা ঘটেছিল কারণ সে নির্দেশনা পড়েনি।", slotValues: { CLAUSE: "she didn't read the instructions" }, topicArea: "education" },
        { en: "It happened because they misunderstood each other.", bn: "এটা ঘটেছিল কারণ তারা একে অপরকে ভুল বুঝেছিল।", slotValues: { CLAUSE: "they misunderstood each other" }, topicArea: "relationships" },
        { en: "It happened because the food wasn't stored properly.", bn: "এটা ঘটেছিল কারণ খাবার সঠিকভাবে সংরক্ষণ করা হয়নি।", slotValues: { CLAUSE: "the food wasn't stored properly" }, topicArea: "food" },
        { en: "It happened because the flight was overbooked.", bn: "এটা ঘটেছিল কারণ ফ্লাইটে বেশি বুকিং হয়ে গিয়েছিল।", slotValues: { CLAUSE: "the flight was overbooked" }, topicArea: "travel" },
        { en: "It happened because no one checked the quality.", bn: "এটা ঘটেছিল কারণ কেউ গুণমান পরীক্ষা করেনি।", slotValues: { CLAUSE: "no one checked the quality" }, topicArea: "shopping" },
        { en: "It happened because the deadline was too tight.", bn: "এটা ঘটেছিল কারণ সময়সীমা খুব কম ছিল।", slotValues: { CLAUSE: "the deadline was too tight" }, topicArea: "work" },
        { en: "It happened because he skipped his medication.", bn: "এটা ঘটেছিল কারণ সে ওষুধ খেতে ভুলে গিয়েছিল।", slotValues: { CLAUSE: "he skipped his medication" }, topicArea: "health" },
        { en: "It happened because the recipe called for too much salt.", bn: "এটা ঘটেছিল কারণ রেসিপিতে বেশি লবণ দিতে বলা ছিল।", slotValues: { CLAUSE: "the recipe called for too much salt" }, topicArea: "food" },
        { en: "It happened because she wasn't prepared for the test.", bn: "এটা ঘটেছিল কারণ সে পরীক্ষার জন্য প্রস্তুত ছিল না।", slotValues: { CLAUSE: "she wasn't prepared for the test" }, topicArea: "education" },
        { en: "It happened because they stopped talking to each other.", bn: "এটা ঘটেছিল কারণ তারা একে অপরের সাথে কথা বলা বন্ধ করে দিয়েছিল।", slotValues: { CLAUSE: "they stopped talking to each other" }, topicArea: "relationships" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "A straightforward way to explain the cause of an event. Often used in storytelling and explanations.",
      usageNote_bn: "একটি ঘটনার কারণ ব্যাখ্যা করার সরাসরি উপায়। প্রায়ই গল্প বলা এবং ব্যাখ্যায় ব্যবহৃত হয়।",
      banglaStructureMap: "এটা ঘটেছিল (It happened) + কারণ (because) + [CLAUSE] (Reason clause)",
    },
    {
      id: "O8.5",
      formula: "The way [PERSON] [PAST] was [ADJ]",
      formula_bn: "যেভাবে [ব্যক্তি] [অতীত ক্রিয়া] তা ছিল [বিশেষণ]",
      patternName: "The Way Someone Did",
      patternName_bn: "যেভাবে কেউ করেছিল",
      slots: [
        {
          name: "PERSON",
          description: "The person whose action is being described",
          description_bn: "যার কাজ বর্ণনা করা হচ্ছে",
          acceptedTypes: ["person", "noun"],
          examples: ["she", "he", "the chef"],
        },
        {
          name: "PAST",
          description: "The action performed in past tense",
          description_bn: "অতীতকালে সম্পন্ন কাজ",
          acceptedTypes: ["verb_phrase"],
          examples: ["handled it", "cooked the dish", "explained the topic"],
        },
        {
          name: "ADJ",
          description: "An adjective evaluating the manner of the action",
          description_bn: "কাজের ধরন মূল্যায়নকারী একটি বিশেষণ",
          acceptedTypes: ["adjective"],
          examples: ["impressive", "incredible", "disappointing"],
        },
      ],
      examples: [
        { en: "The way she handled it was impressive.", bn: "যেভাবে সে এটা সামলেছিল তা ছিল চমৎকার।", slotValues: { PERSON: "she", PAST: "handled it", ADJ: "impressive" }, topicArea: "work" },
        { en: "The way he cooked the dish was incredible.", bn: "যেভাবে সে রান্নাটি করেছিল তা ছিল অবিশ্বাস্য।", slotValues: { PERSON: "he", PAST: "cooked the dish", ADJ: "incredible" }, topicArea: "food" },
        { en: "The way the teacher explained the topic was brilliant.", bn: "যেভাবে শিক্ষক বিষয়টি ব্যাখ্যা করেছিলেন তা ছিল অসাধারণ।", slotValues: { PERSON: "the teacher", PAST: "explained the topic", ADJ: "brilliant" }, topicArea: "education" },
        { en: "The way she spoke to him was rude.", bn: "যেভাবে সে তার সাথে কথা বলেছিল তা ছিল অভদ্র।", slotValues: { PERSON: "she", PAST: "spoke to him", ADJ: "rude" }, topicArea: "relationships" },
        { en: "The way he managed the crisis was admirable.", bn: "যেভাবে সে সংকট সামলেছিল তা ছিল প্রশংসনীয়।", slotValues: { PERSON: "he", PAST: "managed the crisis", ADJ: "admirable" }, topicArea: "work" },
        { en: "The way she described the trip was fascinating.", bn: "যেভাবে সে ভ্রমণের বর্ণনা দিয়েছিল তা ছিল মনোমুগ্ধকর।", slotValues: { PERSON: "she", PAST: "described the trip", ADJ: "fascinating" }, topicArea: "travel" },
        { en: "The way the doctor treated the patient was kind.", bn: "যেভাবে ডাক্তার রোগীর চিকিৎসা করেছিলেন তা ছিল দয়ালু।", slotValues: { PERSON: "the doctor", PAST: "treated the patient", ADJ: "kind" }, topicArea: "health" },
        { en: "The way he presented the dessert was beautiful.", bn: "যেভাবে সে মিষ্টান্নটি পরিবেশন করেছিল তা ছিল সুন্দর।", slotValues: { PERSON: "he", PAST: "presented the dessert", ADJ: "beautiful" }, topicArea: "food" },
        { en: "The way she organized the event was professional.", bn: "যেভাবে সে অনুষ্ঠানটি আয়োজন করেছিল তা ছিল পেশাদার।", slotValues: { PERSON: "she", PAST: "organized the event", ADJ: "professional" }, topicArea: "daily_life" },
        { en: "The way he apologized was touching.", bn: "যেভাবে সে ক্ষমা চেয়েছিল তা ছিল হৃদয়স্পর্শী।", slotValues: { PERSON: "he", PAST: "apologized", ADJ: "touching" }, topicArea: "relationships" },
        { en: "The way the guide led the tour was informative.", bn: "যেভাবে গাইড ট্যুর পরিচালনা করেছিলেন তা ছিল তথ্যবহুল।", slotValues: { PERSON: "the guide", PAST: "led the tour", ADJ: "informative" }, topicArea: "travel" },
        { en: "The way she wrapped the gift was creative.", bn: "যেভাবে সে উপহারটি মুড়িয়েছিল তা ছিল সৃজনশীল।", slotValues: { PERSON: "she", PAST: "wrapped the gift", ADJ: "creative" }, topicArea: "shopping" },
        { en: "The way he solved the problem was clever.", bn: "যেভাবে সে সমস্যাটি সমাধান করেছিল তা ছিল চতুর।", slotValues: { PERSON: "he", PAST: "solved the problem", ADJ: "clever" }, topicArea: "education" },
        { en: "The way she cared for the elderly was compassionate.", bn: "যেভাবে সে বয়স্কদের যত্ন নিয়েছিল তা ছিল সহানুভূতিশীল।", slotValues: { PERSON: "she", PAST: "cared for the elderly", ADJ: "compassionate" }, topicArea: "health" },
        { en: "The way the shopkeeper treated us was disappointing.", bn: "যেভাবে দোকানদার আমাদের সাথে ব্যবহার করেছিল তা ছিল হতাশাজনক।", slotValues: { PERSON: "the shopkeeper", PAST: "treated us", ADJ: "disappointing" }, topicArea: "shopping" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "Used to comment on or evaluate how someone did something. Adds emphasis to the manner of an action.",
      usageNote_bn: "কেউ কীভাবে কিছু করেছে তা মন্তব্য বা মূল্যায়ন করতে ব্যবহৃত হয়। কাজের ধরনে জোর দেয়।",
      banglaStructureMap: "যেভাবে (The way) + [ব্যক্তি] (Subject) + [অতীত ক্রিয়া] (Past verb) + তা ছিল (was) + [বিশেষণ] (Adjective)",
    },
  ],
};
