import { PatternCategory } from "@/types/pattern";

export const categoryO9: PatternCategory = {
  id: "O9",
  slug: "describing-changes",
  name: "Describing Changes",
  name_bn: "পরিবর্তন বর্ণনা",
  description: "Describe how things have changed over time using comparative patterns.",
  description_bn: "তুলনামূলক প্যাটার্ন ব্যবহার করে সময়ের সাথে কীভাবে জিনিসগুলো পরিবর্তিত হয়েছে তা বর্ণনা করুন।",
  icon: "🔄",
  group: "O",
  groupName: "Narrating & Storytelling",
  groupName_bn: "বর্ণনা ও গল্প বলা",
  difficulty: "intermediate",
  patterns: [
    {
      id: "O9.1",
      formula: "[THING] used to be [DESC], but now...",
      formula_bn: "[জিনিস] আগে [বর্ণনা] ছিল, কিন্তু এখন...",
      patternName: "Used To Be... But Now",
      patternName_bn: "আগে ছিল... কিন্তু এখন",
      slots: [
        {
          name: "THING",
          description: "The subject that has changed",
          description_bn: "যে বিষয়টি পরিবর্তিত হয়েছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["This neighborhood", "The school", "My job"],
        },
        {
          name: "DESC",
          description: "How it was in the past, followed by how it is now",
          description_bn: "অতীতে কেমন ছিল, তারপর এখন কেমন",
          acceptedTypes: ["adjective", "adjective_phrase", "description"],
          examples: ["quiet, but now it's noisy", "small, but now it's huge", "cheap, but now it's expensive"],
        },
      ],
      examples: [
        { en: "This neighborhood used to be quiet, but now it's very noisy.", bn: "এই পাড়া আগে শান্ত ছিল, কিন্তু এখন খুব কোলাহলপূর্ণ।", slotValues: { THING: "This neighborhood", DESC: "quiet, but now it's very noisy" }, topicArea: "daily_life" },
        { en: "The school used to be small, but now it has thousands of students.", bn: "স্কুলটি আগে ছোট ছিল, কিন্তু এখন হাজার হাজার ছাত্র আছে।", slotValues: { THING: "The school", DESC: "small, but now it has thousands of students" }, topicArea: "education" },
        { en: "My job used to be easy, but now it's very demanding.", bn: "আমার চাকরি আগে সহজ ছিল, কিন্তু এখন খুব চাহিদাপূর্ণ।", slotValues: { THING: "My job", DESC: "easy, but now it's very demanding" }, topicArea: "work" },
        { en: "The market used to be cheap, but now everything is expensive.", bn: "বাজার আগে সস্তা ছিল, কিন্তু এখন সবকিছু দামি।", slotValues: { THING: "The market", DESC: "cheap, but now everything is expensive" }, topicArea: "shopping" },
        { en: "This place used to be a forest, but now it's a shopping mall.", bn: "এই জায়গা আগে বন ছিল, কিন্তু এখন শপিং মল।", slotValues: { THING: "This place", DESC: "a forest, but now it's a shopping mall" }, topicArea: "daily_life" },
        { en: "The restaurant used to be empty, but now it's always full.", bn: "রেস্তোরাঁটি আগে খালি থাকত, কিন্তু এখন সবসময় ভরা।", slotValues: { THING: "The restaurant", DESC: "empty, but now it's always full" }, topicArea: "food" },
        { en: "Our relationship used to be strong, but now it's complicated.", bn: "আমাদের সম্পর্ক আগে মজবুত ছিল, কিন্তু এখন জটিল।", slotValues: { THING: "Our relationship", DESC: "strong, but now it's complicated" }, topicArea: "relationships" },
        { en: "The hospital used to be far away, but now there's one nearby.", bn: "হাসপাতাল আগে অনেক দূরে ছিল, কিন্তু এখন কাছেই একটা আছে।", slotValues: { THING: "The hospital", DESC: "far away, but now there's one nearby" }, topicArea: "health" },
        { en: "This road used to be dangerous, but now it's much safer.", bn: "এই রাস্তা আগে বিপজ্জনক ছিল, কিন্তু এখন অনেক নিরাপদ।", slotValues: { THING: "This road", DESC: "dangerous, but now it's much safer" }, topicArea: "travel" },
        { en: "The office used to be downtown, but now it's moved to the suburbs.", bn: "অফিস আগে শহরের কেন্দ্রে ছিল, কিন্তু এখন উপকণ্ঠে চলে গেছে।", slotValues: { THING: "The office", DESC: "downtown, but now it's moved to the suburbs" }, topicArea: "work" },
        { en: "The food here used to be bland, but now it's delicious.", bn: "এখানকার খাবার আগে বিস্বাদ ছিল, কিন্তু এখন সুস্বাদু।", slotValues: { THING: "The food here", DESC: "bland, but now it's delicious" }, topicArea: "food" },
        { en: "The university used to be free, but now tuition is very high.", bn: "বিশ্ববিদ্যালয় আগে বিনামূল্যে ছিল, কিন্তু এখন টিউশন ফি অনেক বেশি।", slotValues: { THING: "The university", DESC: "free, but now tuition is very high" }, topicArea: "education" },
        { en: "He used to be shy, but now he's very outgoing.", bn: "সে আগে লাজুক ছিল, কিন্তু এখন খুব বহির্মুখী।", slotValues: { THING: "He", DESC: "shy, but now he's very outgoing" }, topicArea: "relationships" },
        { en: "The air quality used to be good, but now it's terrible.", bn: "বায়ুর মান আগে ভালো ছিল, কিন্তু এখন ভয়ংকর।", slotValues: { THING: "The air quality", DESC: "good, but now it's terrible" }, topicArea: "health" },
        { en: "This brand used to be affordable, but now it's a luxury.", bn: "এই ব্র্যান্ড আগে সাশ্রয়ী ছিল, কিন্তু এখন এটি বিলাসিতা।", slotValues: { THING: "This brand", DESC: "affordable, but now it's a luxury" }, topicArea: "shopping" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "Contrasts past and present states. Very useful for describing personal or societal changes.",
      usageNote_bn: "অতীত ও বর্তমান অবস্থার তুলনা করে। ব্যক্তিগত বা সামাজিক পরিবর্তন বর্ণনা করতে খুবই কার্যকর।",
      banglaStructureMap: "[জিনিস] (Subject) + আগে (used to) + [বর্ণনা] ছিল (was DESC) + কিন্তু এখন (but now) + ...",
    },
    {
      id: "O9.2",
      formula: "[THING] has changed a lot since [TIME]",
      formula_bn: "[জিনিস] [সময়] থেকে অনেক পরিবর্তিত হয়েছে",
      patternName: "Has Changed Since",
      patternName_bn: "থেকে পরিবর্তিত হয়েছে",
      slots: [
        {
          name: "THING",
          description: "The subject that has changed",
          description_bn: "যে বিষয়টি পরিবর্তিত হয়েছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["The city", "Technology", "The education system"],
        },
        {
          name: "TIME",
          description: "A point in time from which changes are measured",
          description_bn: "যে সময় থেকে পরিবর্তন মাপা হয়",
          acceptedTypes: ["time", "time_expression"],
          examples: ["last year", "the pandemic", "I was a child"],
        },
      ],
      examples: [
        { en: "The city has changed a lot since last year.", bn: "শহরটি গত বছর থেকে অনেক পরিবর্তিত হয়েছে।", slotValues: { THING: "The city", TIME: "last year" }, topicArea: "daily_life" },
        { en: "Technology has changed a lot since the 90s.", bn: "প্রযুক্তি ৯০-এর দশক থেকে অনেক পরিবর্তিত হয়েছে।", slotValues: { THING: "Technology", TIME: "the 90s" }, topicArea: "daily_life" },
        { en: "The education system has changed a lot since I was a student.", bn: "শিক্ষা ব্যবস্থা আমি যখন ছাত্র ছিলাম তখন থেকে অনেক পরিবর্তিত হয়েছে।", slotValues: { THING: "The education system", TIME: "I was a student" }, topicArea: "education" },
        { en: "The workplace has changed a lot since the pandemic.", bn: "কর্মক্ষেত্র মহামারীর পর থেকে অনেক পরিবর্তিত হয়েছে।", slotValues: { THING: "The workplace", TIME: "the pandemic" }, topicArea: "work" },
        { en: "Food trends have changed a lot since ten years ago.", bn: "খাদ্যের প্রবণতা দশ বছর আগে থেকে অনেক পরিবর্তিত হয়েছে।", slotValues: { THING: "Food trends", TIME: "ten years ago" }, topicArea: "food" },
        { en: "Relationships have changed a lot since social media arrived.", bn: "সম্পর্কগুলো সোশ্যাল মিডিয়া আসার পর থেকে অনেক পরিবর্তিত হয়েছে।", slotValues: { THING: "Relationships", TIME: "social media arrived" }, topicArea: "relationships" },
        { en: "Healthcare has changed a lot since my parents' time.", bn: "স্বাস্থ্যসেবা আমার বাবা-মায়ের সময় থেকে অনেক পরিবর্তিত হয়েছে।", slotValues: { THING: "Healthcare", TIME: "my parents' time" }, topicArea: "health" },
        { en: "Shopping habits have changed a lot since online stores appeared.", bn: "কেনাকাটার অভ্যাস অনলাইন দোকান আসার পর থেকে অনেক পরিবর্তিত হয়েছে।", slotValues: { THING: "Shopping habits", TIME: "online stores appeared" }, topicArea: "shopping" },
        { en: "Travel has changed a lot since budget airlines started.", bn: "ভ্রমণ বাজেট এয়ারলাইন শুরু হওয়ার পর থেকে অনেক পরিবর্তিত হয়েছে।", slotValues: { THING: "Travel", TIME: "budget airlines started" }, topicArea: "travel" },
        { en: "The company culture has changed a lot since the new CEO took over.", bn: "কোম্পানির সংস্কৃতি নতুন সিইও দায়িত্ব নেওয়ার পর থেকে অনেক পরিবর্তিত হয়েছে।", slotValues: { THING: "The company culture", TIME: "the new CEO took over" }, topicArea: "work" },
        { en: "The neighborhood has changed a lot since we moved here.", bn: "পাড়াটি আমরা এখানে আসার পর থেকে অনেক পরিবর্তিত হয়েছে।", slotValues: { THING: "The neighborhood", TIME: "we moved here" }, topicArea: "daily_life" },
        { en: "Teaching methods have changed a lot since the internet became common.", bn: "শিক্ষাদান পদ্ধতি ইন্টারনেট সাধারণ হওয়ার পর থেকে অনেক পরিবর্তিত হয়েছে।", slotValues: { THING: "Teaching methods", TIME: "the internet became common" }, topicArea: "education" },
        { en: "The menu has changed a lot since the new chef arrived.", bn: "মেনু নতুন শেফ আসার পর থেকে অনেক পরিবর্তিত হয়েছে।", slotValues: { THING: "The menu", TIME: "the new chef arrived" }, topicArea: "food" },
        { en: "Attitudes toward mental health have changed a lot since the 2000s.", bn: "মানসিক স্বাস্থ্যের প্রতি মনোভাব ২০০০-এর দশক থেকে অনেক পরিবর্তিত হয়েছে।", slotValues: { THING: "Attitudes toward mental health", TIME: "the 2000s" }, topicArea: "health" },
        { en: "Fashion has changed a lot since our grandparents' generation.", bn: "ফ্যাশন আমাদের দাদা-দাদির প্রজন্ম থেকে অনেক পরিবর্তিত হয়েছে।", slotValues: { THING: "Fashion", TIME: "our grandparents' generation" }, topicArea: "shopping" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "Highlights significant change over a period. The time reference gives context to how much has shifted.",
      usageNote_bn: "একটি সময়কালে উল্লেখযোগ্য পরিবর্তন তুলে ধরে। সময়ের উল্লেখ কতটা পরিবর্তন হয়েছে তার প্রসঙ্গ দেয়।",
      banglaStructureMap: "[জিনিস] (Subject) + [সময়] থেকে (since TIME) + অনেক পরিবর্তিত হয়েছে (has changed a lot)",
    },
    {
      id: "O9.3",
      formula: "[THING] is becoming more [ADJ]",
      formula_bn: "[জিনিস] আরও [বিশেষণ] হয়ে যাচ্ছে",
      patternName: "Is Becoming More",
      patternName_bn: "আরও হয়ে যাচ্ছে",
      slots: [
        {
          name: "THING",
          description: "The subject undergoing change",
          description_bn: "যে বিষয়টি পরিবর্তনের মধ্য দিয়ে যাচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["Life", "The weather", "Online learning"],
        },
        {
          name: "ADJ",
          description: "The quality that is increasing",
          description_bn: "যে গুণটি বাড়ছে",
          acceptedTypes: ["adjective"],
          examples: ["expensive", "popular", "difficult"],
        },
      ],
      examples: [
        { en: "Life is becoming more expensive every year.", bn: "জীবনযাত্রা প্রতি বছর আরও ব্যয়বহুল হয়ে যাচ্ছে।", slotValues: { THING: "Life", ADJ: "expensive every year" }, topicArea: "daily_life" },
        { en: "The weather is becoming more unpredictable.", bn: "আবহাওয়া আরও অনিশ্চিত হয়ে যাচ্ছে।", slotValues: { THING: "The weather", ADJ: "unpredictable" }, topicArea: "daily_life" },
        { en: "Online learning is becoming more popular.", bn: "অনলাইন শিক্ষা আরও জনপ্রিয় হয়ে যাচ্ছে।", slotValues: { THING: "Online learning", ADJ: "popular" }, topicArea: "education" },
        { en: "Remote work is becoming more common.", bn: "দূরবর্তী কাজ আরও সাধারণ হয়ে যাচ্ছে।", slotValues: { THING: "Remote work", ADJ: "common" }, topicArea: "work" },
        { en: "Organic food is becoming more accessible.", bn: "জৈব খাদ্য আরও সহজলভ্য হয়ে যাচ্ছে।", slotValues: { THING: "Organic food", ADJ: "accessible" }, topicArea: "food" },
        { en: "People are becoming more health-conscious.", bn: "মানুষ আরও স্বাস্থ্য সচেতন হয়ে যাচ্ছে।", slotValues: { THING: "People", ADJ: "health-conscious" }, topicArea: "health" },
        { en: "Online shopping is becoming more convenient.", bn: "অনলাইন কেনাকাটা আরও সুবিধাজনক হয়ে যাচ্ছে।", slotValues: { THING: "Online shopping", ADJ: "convenient" }, topicArea: "shopping" },
        { en: "Air travel is becoming more affordable.", bn: "বিমান ভ্রমণ আরও সাশ্রয়ী হয়ে যাচ্ছে।", slotValues: { THING: "Air travel", ADJ: "affordable" }, topicArea: "travel" },
        { en: "Long-distance relationships are becoming more accepted.", bn: "দূরত্বের সম্পর্ক আরও গ্রহণযোগ্য হয়ে যাচ্ছে।", slotValues: { THING: "Long-distance relationships", ADJ: "accepted" }, topicArea: "relationships" },
        { en: "The job market is becoming more competitive.", bn: "চাকরির বাজার আরও প্রতিযোগিতামূলক হয়ে যাচ্ছে।", slotValues: { THING: "The job market", ADJ: "competitive" }, topicArea: "work" },
        { en: "Street food is becoming more diverse.", bn: "রাস্তার খাবার আরও বৈচিত্র্যময় হয়ে যাচ্ছে।", slotValues: { THING: "Street food", ADJ: "diverse" }, topicArea: "food" },
        { en: "Mental health awareness is becoming more widespread.", bn: "মানসিক স্বাস্থ্য সচেতনতা আরও ব্যাপক হয়ে যাচ্ছে।", slotValues: { THING: "Mental health awareness", ADJ: "widespread" }, topicArea: "health" },
        { en: "Education is becoming more technology-driven.", bn: "শিক্ষা আরও প্রযুক্তিনির্ভর হয়ে যাচ্ছে।", slotValues: { THING: "Education", ADJ: "technology-driven" }, topicArea: "education" },
        { en: "Eco-tourism is becoming more important.", bn: "ইকো-ট্যুরিজম আরও গুরুত্বপূর্ণ হয়ে যাচ্ছে।", slotValues: { THING: "Eco-tourism", ADJ: "important" }, topicArea: "travel" },
        { en: "Sustainable shopping is becoming more trendy.", bn: "টেকসই কেনাকাটা আরও ট্রেন্ডি হয়ে যাচ্ছে।", slotValues: { THING: "Sustainable shopping", ADJ: "trendy" }, topicArea: "shopping" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "Describes an ongoing trend or gradual change. Present continuous shows the change is still happening.",
      usageNote_bn: "একটি চলমান প্রবণতা বা ধীরে ধীরে পরিবর্তন বর্ণনা করে। বর্তমান চলমান কাল দেখায় যে পরিবর্তন এখনও ঘটছে।",
      banglaStructureMap: "[জিনিস] (Subject) + আরও (more) + [বিশেষণ] (Adjective) + হয়ে যাচ্ছে (is becoming)",
    },
    {
      id: "O9.4",
      formula: "[THING] isn't what it used to be",
      formula_bn: "[জিনিস] আগে যেমন ছিল তেমন নেই",
      patternName: "Isn't What It Used To Be",
      patternName_bn: "আগে যেমন ছিল তেমন নেই",
      slots: [
        {
          name: "THING",
          description: "Something that has deteriorated or changed significantly",
          description_bn: "যে জিনিসটি উল্লেখযোগ্যভাবে খারাপ হয়েছে বা পরিবর্তিত হয়েছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["The quality", "This restaurant", "Customer service"],
        },
      ],
      examples: [
        { en: "The quality isn't what it used to be.", bn: "মান আগে যেমন ছিল তেমন নেই।", slotValues: { THING: "The quality" }, topicArea: "shopping" },
        { en: "This restaurant isn't what it used to be.", bn: "এই রেস্তোরাঁ আগে যেমন ছিল তেমন নেই।", slotValues: { THING: "This restaurant" }, topicArea: "food" },
        { en: "Customer service isn't what it used to be.", bn: "গ্রাহক সেবা আগে যেমন ছিল তেমন নেই।", slotValues: { THING: "Customer service" }, topicArea: "shopping" },
        { en: "The neighborhood isn't what it used to be.", bn: "পাড়াটি আগে যেমন ছিল তেমন নেই।", slotValues: { THING: "The neighborhood" }, topicArea: "daily_life" },
        { en: "The school isn't what it used to be.", bn: "স্কুলটি আগে যেমন ছিল তেমন নেই।", slotValues: { THING: "The school" }, topicArea: "education" },
        { en: "The company isn't what it used to be.", bn: "কোম্পানিটি আগে যেমন ছিল তেমন নেই।", slotValues: { THING: "The company" }, topicArea: "work" },
        { en: "His health isn't what it used to be.", bn: "তার স্বাস্থ্য আগে যেমন ছিল তেমন নেই।", slotValues: { THING: "His health" }, topicArea: "health" },
        { en: "Our friendship isn't what it used to be.", bn: "আমাদের বন্ধুত্ব আগে যেমন ছিল তেমন নেই।", slotValues: { THING: "Our friendship" }, topicArea: "relationships" },
        { en: "The beach isn't what it used to be.", bn: "সমুদ্র সৈকত আগে যেমন ছিল তেমন নেই।", slotValues: { THING: "The beach" }, topicArea: "travel" },
        { en: "The food here isn't what it used to be.", bn: "এখানকার খাবার আগে যেমন ছিল তেমন নেই।", slotValues: { THING: "The food here" }, topicArea: "food" },
        { en: "The exam system isn't what it used to be.", bn: "পরীক্ষা পদ্ধতি আগে যেমন ছিল তেমন নেই।", slotValues: { THING: "The exam system" }, topicArea: "education" },
        { en: "Team spirit isn't what it used to be.", bn: "দলীয় মনোভাব আগে যেমন ছিল তেমন নেই।", slotValues: { THING: "Team spirit" }, topicArea: "work" },
        { en: "The air quality isn't what it used to be.", bn: "বায়ুর মান আগে যেমন ছিল তেমন নেই।", slotValues: { THING: "The air quality" }, topicArea: "health" },
        { en: "Family gatherings aren't what they used to be.", bn: "পারিবারিক সমাবেশ আগে যেমন ছিল তেমন নেই।", slotValues: { THING: "Family gatherings" }, topicArea: "relationships" },
        { en: "The tourist spot isn't what it used to be.", bn: "পর্যটন স্থানটি আগে যেমন ছিল তেমন নেই।", slotValues: { THING: "The tourist spot" }, topicArea: "travel" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "Expresses nostalgia or disappointment about how something has changed, usually for the worse.",
      usageNote_bn: "কিছু কীভাবে পরিবর্তিত হয়েছে সে সম্পর্কে নস্টালজিয়া বা হতাশা প্রকাশ করে, সাধারণত খারাপের দিকে।",
      banglaStructureMap: "[জিনিস] (Subject) + আগে যেমন ছিল তেমন নেই (isn't what it used to be)",
    },
    {
      id: "O9.5",
      formula: "Things have gotten [COMPARATIVE]",
      formula_bn: "জিনিসগুলো [তুলনামূলক] হয়ে গেছে",
      patternName: "Things Have Gotten",
      patternName_bn: "জিনিসগুলো হয়ে গেছে",
      slots: [
        {
          name: "COMPARATIVE",
          description: "A comparative adjective or phrase",
          description_bn: "একটি তুলনামূলক বিশেষণ বা বাক্যাংশ",
          acceptedTypes: ["adjective", "adjective_phrase"],
          examples: ["better", "worse", "more complicated"],
        },
      ],
      examples: [
        { en: "Things have gotten better since the new policy.", bn: "নতুন নীতির পর থেকে জিনিসগুলো ভালো হয়ে গেছে।", slotValues: { COMPARATIVE: "better since the new policy" }, topicArea: "work" },
        { en: "Things have gotten worse in the neighborhood.", bn: "পাড়ায় জিনিসগুলো খারাপ হয়ে গেছে।", slotValues: { COMPARATIVE: "worse in the neighborhood" }, topicArea: "daily_life" },
        { en: "Things have gotten more complicated at work.", bn: "কাজে জিনিসগুলো আরও জটিল হয়ে গেছে।", slotValues: { COMPARATIVE: "more complicated at work" }, topicArea: "work" },
        { en: "Things have gotten more expensive lately.", bn: "সম্প্রতি জিনিসগুলো আরও দামি হয়ে গেছে।", slotValues: { COMPARATIVE: "more expensive lately" }, topicArea: "shopping" },
        { en: "Things have gotten easier with technology.", bn: "প্রযুক্তির সাথে জিনিসগুলো সহজ হয়ে গেছে।", slotValues: { COMPARATIVE: "easier with technology" }, topicArea: "daily_life" },
        { en: "Things have gotten more competitive in the food industry.", bn: "খাদ্য শিল্পে জিনিসগুলো আরও প্রতিযোগিতামূলক হয়ে গেছে।", slotValues: { COMPARATIVE: "more competitive in the food industry" }, topicArea: "food" },
        { en: "Things have gotten harder for students.", bn: "ছাত্রদের জন্য জিনিসগুলো কঠিন হয়ে গেছে।", slotValues: { COMPARATIVE: "harder for students" }, topicArea: "education" },
        { en: "Things have gotten more stressful between us.", bn: "আমাদের মধ্যে জিনিসগুলো আরও চাপের হয়ে গেছে।", slotValues: { COMPARATIVE: "more stressful between us" }, topicArea: "relationships" },
        { en: "Things have gotten better after the treatment.", bn: "চিকিৎসার পর জিনিসগুলো ভালো হয়ে গেছে।", slotValues: { COMPARATIVE: "better after the treatment" }, topicArea: "health" },
        { en: "Things have gotten more crowded at tourist spots.", bn: "পর্যটন স্থানগুলোতে জিনিসগুলো আরও ভিড়পূর্ণ হয়ে গেছে।", slotValues: { COMPARATIVE: "more crowded at tourist spots" }, topicArea: "travel" },
        { en: "Things have gotten smoother since the new manager started.", bn: "নতুন ম্যানেজার শুরু করার পর থেকে জিনিসগুলো মসৃণ হয়ে গেছে।", slotValues: { COMPARATIVE: "smoother since the new manager started" }, topicArea: "work" },
        { en: "Things have gotten quieter in the evenings.", bn: "সন্ধ্যায় জিনিসগুলো শান্ত হয়ে গেছে।", slotValues: { COMPARATIVE: "quieter in the evenings" }, topicArea: "daily_life" },
        { en: "Things have gotten more affordable online.", bn: "অনলাইনে জিনিসগুলো আরও সাশ্রয়ী হয়ে গেছে।", slotValues: { COMPARATIVE: "more affordable online" }, topicArea: "shopping" },
        { en: "Things have gotten more inclusive in education.", bn: "শিক্ষায় জিনিসগুলো আরও অন্তর্ভুক্তিমূলক হয়ে গেছে।", slotValues: { COMPARATIVE: "more inclusive in education" }, topicArea: "education" },
        { en: "Things have gotten closer between the two families.", bn: "দুই পরিবারের মধ্যে জিনিসগুলো ঘনিষ্ঠ হয়ে গেছে।", slotValues: { COMPARATIVE: "closer between the two families" }, topicArea: "relationships" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "A general way to describe overall improvement or decline in a situation.",
      usageNote_bn: "একটি পরিস্থিতিতে সামগ্রিক উন্নতি বা অবনতি বর্ণনা করার একটি সাধারণ উপায়।",
      banglaStructureMap: "জিনিসগুলো (Things) + [তুলনামূলক] (Comparative) + হয়ে গেছে (have gotten)",
    },
  ],
};
