import { PatternCategory } from "@/types/pattern";

export const categoryP1: PatternCategory = {
  id: "P1",
  slug: "exclamatory-patterns",
  name: "Exclamatory Patterns",
  name_bn: "বিস্ময়সূচক প্যাটার্ন",
  description: "Express strong emotions with exclamations",
  description_bn: "বিস্ময়সূচক বাক্য দিয়ে শক্তিশালী আবেগ প্রকাশ করুন",
  icon: "❗",
  group: "P",
  groupName: "Exclamations & Emphasis",
  groupName_bn: "বিস্ময়সূচক ও জোর দেওয়া",
  difficulty: "intermediate",
  patterns: [
    {
      id: "P1.1",
      formula: "What a [ADJECTIVE] [THING]!",
      formula_bn: "কী [বিশেষণ] [জিনিস]!",
      patternName: "What + Noun Exclamation",
      patternName_bn: "What + বিশেষ্য বিস্ময়",
      slots: [
        { name: "ADJECTIVE", description: "Descriptive word", description_bn: "বর্ণনামূলক শব্দ", acceptedTypes: ["adjective"], examples: ["beautiful", "terrible", "amazing"] },
        { name: "THING", description: "Any noun", description_bn: "যেকোনো বিশেষ্য", acceptedTypes: ["noun"], examples: ["day", "movie", "idea"] },
      ],
      examples: [
        { en: "What a beautiful day!", bn: "কী সুন্দর দিন!", slotValues: { ADJECTIVE: "beautiful", THING: "day" } },
        { en: "What a terrible mistake!", bn: "কী ভয়ংকর ভুল!", slotValues: { ADJECTIVE: "terrible", THING: "mistake" } },
        { en: "What a wonderful surprise!", bn: "কী চমৎকার চমক!", slotValues: { ADJECTIVE: "wonderful", THING: "surprise" } },
        { en: "What a brilliant idea!", bn: "কী দারুণ আইডিয়া!", slotValues: { ADJECTIVE: "brilliant", THING: "idea" } },
        { en: "What a delicious meal!", bn: "কী সুস্বাদু খাবার!", slotValues: { ADJECTIVE: "delicious", THING: "meal" } },
        { en: "What a gorgeous view!", bn: "কী অসাধারণ দৃশ্য!", slotValues: { ADJECTIVE: "gorgeous", THING: "view" } },
        { en: "What a horrible experience!", bn: "কী ভয়াবহ অভিজ্ঞতা!", slotValues: { ADJECTIVE: "horrible", THING: "experience" } },
        { en: "What a cute puppy!", bn: "কী আদুরে কুকুরছানা!", slotValues: { ADJECTIVE: "cute", THING: "puppy" } },
        { en: "What a fantastic performance!", bn: "কী অসাধারণ পারফরম্যান্স!", slotValues: { ADJECTIVE: "fantastic", THING: "performance" } },
        { en: "What a strange coincidence!", bn: "কী অদ্ভুত কাকতালীয়!", slotValues: { ADJECTIVE: "strange", THING: "coincidence" } },
        { en: "What a long journey!", bn: "কী দীর্ঘ যাত্রা!", slotValues: { ADJECTIVE: "long", THING: "journey" } },
        { en: "What a great movie!", bn: "কী দারুণ সিনেমা!", slotValues: { ADJECTIVE: "great", THING: "movie" } },
        { en: "What a ridiculous excuse!", bn: "কী হাস্যকর অজুহাত!", slotValues: { ADJECTIVE: "ridiculous", THING: "excuse" } },
        { en: "What a lovely garden!", bn: "কী সুন্দর বাগান!", slotValues: { ADJECTIVE: "lovely", THING: "garden" } },
        { en: "What a tough decision!", bn: "কী কঠিন সিদ্ধান্ত!", slotValues: { ADJECTIVE: "tough", THING: "decision" } },
      ],
      formality: "casual",
      difficulty: "intermediate",
    },
    {
      id: "P1.2",
      formula: "How [ADJECTIVE]!",
      formula_bn: "কতটা [বিশেষণ]!",
      patternName: "How + Adjective Exclamation",
      patternName_bn: "How + বিশেষণ বিস্ময়",
      slots: [
        { name: "ADJECTIVE", description: "Descriptive word expressing emotion", description_bn: "আবেগ প্রকাশকারী বর্ণনামূলক শব্দ", acceptedTypes: ["adjective"], examples: ["wonderful", "exciting", "awful"] },
      ],
      examples: [
        { en: "How wonderful!", bn: "কতটা চমৎকার!", slotValues: { ADJECTIVE: "wonderful" } },
        { en: "How exciting!", bn: "কতটা উত্তেজনাপূর্ণ!", slotValues: { ADJECTIVE: "exciting" } },
        { en: "How awful!", bn: "কতটা ভয়াবহ!", slotValues: { ADJECTIVE: "awful" } },
        { en: "How beautiful!", bn: "কতটা সুন্দর!", slotValues: { ADJECTIVE: "beautiful" } },
        { en: "How interesting!", bn: "কতটা মজার!", slotValues: { ADJECTIVE: "interesting" } },
        { en: "How embarrassing!", bn: "কতটা লজ্জাজনক!", slotValues: { ADJECTIVE: "embarrassing" } },
        { en: "How disappointing!", bn: "কতটা হতাশাজনক!", slotValues: { ADJECTIVE: "disappointing" } },
        { en: "How thoughtful!", bn: "কতটা চিন্তাশীল!", slotValues: { ADJECTIVE: "thoughtful" } },
        { en: "How annoying!", bn: "কতটা বিরক্তিকর!", slotValues: { ADJECTIVE: "annoying" } },
        { en: "How generous!", bn: "কতটা উদার!", slotValues: { ADJECTIVE: "generous" } },
        { en: "How tragic!", bn: "কতটা করুণ!", slotValues: { ADJECTIVE: "tragic" } },
        { en: "How incredible!", bn: "কতটা অবিশ্বাস্য!", slotValues: { ADJECTIVE: "incredible" } },
        { en: "How sweet!", bn: "কতটা মিষ্টি!", slotValues: { ADJECTIVE: "sweet" } },
        { en: "How frustrating!", bn: "কতটা হতাশাকর!", slotValues: { ADJECTIVE: "frustrating" } },
        { en: "How delightful!", bn: "কতটা আনন্দদায়ক!", slotValues: { ADJECTIVE: "delightful" } },
      ],
      formality: "casual",
      difficulty: "intermediate",
    },
    {
      id: "P1.3",
      formula: "[THING] is so [ADJECTIVE]!",
      formula_bn: "[জিনিস] এত [বিশেষণ]!",
      patternName: "So + Adjective Exclamation",
      patternName_bn: "এত + বিশেষণ বিস্ময়",
      slots: [
        { name: "THING", description: "Subject being described", description_bn: "যে বিষয় বর্ণনা করা হচ্ছে", acceptedTypes: ["noun", "noun_phrase"], examples: ["the weather", "this food", "your dress"] },
        { name: "ADJECTIVE", description: "Strong descriptive word", description_bn: "শক্তিশালী বর্ণনামূলক শব্দ", acceptedTypes: ["adjective"], examples: ["amazing", "cool", "boring"] },
      ],
      examples: [
        { en: "This cake is so delicious!", bn: "এই কেকটা এত সুস্বাদু!", slotValues: { THING: "this cake", ADJECTIVE: "delicious" } },
        { en: "The weather is so nice today!", bn: "আজকে আবহাওয়া এত সুন্দর!", slotValues: { THING: "the weather", ADJECTIVE: "nice" } },
        { en: "Your house is so beautiful!", bn: "তোমার বাড়িটা এত সুন্দর!", slotValues: { THING: "your house", ADJECTIVE: "beautiful" } },
        { en: "That movie was so boring!", bn: "ওই সিনেমাটা এত বিরক্তিকর ছিল!", slotValues: { THING: "that movie", ADJECTIVE: "boring" } },
        { en: "This book is so interesting!", bn: "এই বইটা এত মজার!", slotValues: { THING: "this book", ADJECTIVE: "interesting" } },
        { en: "The traffic is so terrible!", bn: "ট্রাফিক এত ভয়ংকর!", slotValues: { THING: "the traffic", ADJECTIVE: "terrible" } },
        { en: "Her voice is so soothing!", bn: "তার গলার স্বর এত প্রশান্তিদায়ক!", slotValues: { THING: "her voice", ADJECTIVE: "soothing" } },
        { en: "This song is so catchy!", bn: "এই গানটা এত আকর্ষণীয়!", slotValues: { THING: "this song", ADJECTIVE: "catchy" } },
        { en: "The exam was so hard!", bn: "পরীক্ষাটা এত কঠিন ছিল!", slotValues: { THING: "the exam", ADJECTIVE: "hard" } },
        { en: "Your garden is so lovely!", bn: "তোমার বাগানটা এত চমৎকার!", slotValues: { THING: "your garden", ADJECTIVE: "lovely" } },
        { en: "This coffee is so strong!", bn: "এই কফিটা এত কড়া!", slotValues: { THING: "this coffee", ADJECTIVE: "strong" } },
        { en: "The sunset is so breathtaking!", bn: "সূর্যাস্তটা এত মনোমুগ্ধকর!", slotValues: { THING: "the sunset", ADJECTIVE: "breathtaking" } },
        { en: "That joke was so funny!", bn: "ওই কৌতুকটা এত মজার ছিল!", slotValues: { THING: "that joke", ADJECTIVE: "funny" } },
        { en: "This place is so peaceful!", bn: "এই জায়গাটা এত শান্তিপূর্ণ!", slotValues: { THING: "this place", ADJECTIVE: "peaceful" } },
        { en: "The baby is so adorable!", bn: "বাচ্চাটা এত আদুরে!", slotValues: { THING: "the baby", ADJECTIVE: "adorable" } },
      ],
      formality: "casual",
      difficulty: "intermediate",
    },
    {
      id: "P1.4",
      formula: "Such a [ADJECTIVE] [THING]!",
      formula_bn: "এতটা [বিশেষণ] [জিনিস]!",
      patternName: "Such + Noun Exclamation",
      patternName_bn: "Such + বিশেষ্য বিস্ময়",
      slots: [
        { name: "ADJECTIVE", description: "Descriptive word", description_bn: "বর্ণনামূলক শব্দ", acceptedTypes: ["adjective"], examples: ["kind", "talented", "brave"] },
        { name: "THING", description: "Noun being emphasized", description_bn: "যে বিশেষ্যে জোর দেওয়া হচ্ছে", acceptedTypes: ["noun"], examples: ["person", "moment", "story"] },
      ],
      examples: [
        { en: "She is such a kind person!", bn: "সে এতটা দয়ালু মানুষ!", slotValues: { ADJECTIVE: "kind", THING: "person" } },
        { en: "It was such a memorable night!", bn: "এটা এতটা স্মরণীয় রাত ছিল!", slotValues: { ADJECTIVE: "memorable", THING: "night" } },
        { en: "He told such a funny story!", bn: "সে এতটা মজার গল্প বলল!", slotValues: { ADJECTIVE: "funny", THING: "story" } },
        { en: "That was such a brave thing to do!", bn: "এটা এতটা সাহসী কাজ ছিল!", slotValues: { ADJECTIVE: "brave", THING: "thing" } },
        { en: "It's such a hot day!", bn: "এতটা গরমের দিন!", slotValues: { ADJECTIVE: "hot", THING: "day" } },
        { en: "She has such a lovely smile!", bn: "তার এতটা সুন্দর হাসি!", slotValues: { ADJECTIVE: "lovely", THING: "smile" } },
        { en: "That was such a silly mistake!", bn: "এটা এতটা বোকামির ভুল ছিল!", slotValues: { ADJECTIVE: "silly", THING: "mistake" } },
        { en: "He's such a talented singer!", bn: "সে এতটা প্রতিভাবান গায়ক!", slotValues: { ADJECTIVE: "talented", THING: "singer" } },
        { en: "It was such a long wait!", bn: "এতটা দীর্ঘ অপেক্ষা ছিল!", slotValues: { ADJECTIVE: "long", THING: "wait" } },
        { en: "You have such a big heart!", bn: "তোমার এতটা বড় মন!", slotValues: { ADJECTIVE: "big", THING: "heart" } },
        { en: "This is such a difficult problem!", bn: "এটা এতটা কঠিন সমস্যা!", slotValues: { ADJECTIVE: "difficult", THING: "problem" } },
        { en: "She wore such a gorgeous dress!", bn: "সে এতটা জমকালো পোশাক পরেছিল!", slotValues: { ADJECTIVE: "gorgeous", THING: "dress" } },
        { en: "It was such a touching moment!", bn: "এটা এতটা মর্মস্পর্শী মুহূর্ত ছিল!", slotValues: { ADJECTIVE: "touching", THING: "moment" } },
        { en: "He made such a smart choice!", bn: "সে এতটা বুদ্ধিমান পছন্দ করেছিল!", slotValues: { ADJECTIVE: "smart", THING: "choice" } },
        { en: "That was such a close game!", bn: "এটা এতটা টানটান খেলা ছিল!", slotValues: { ADJECTIVE: "close", THING: "game" } },
      ],
      formality: "casual",
      difficulty: "intermediate",
    },
    {
      id: "P1.5",
      formula: "I can't believe how [ADJECTIVE] [THING] is!",
      formula_bn: "বিশ্বাস করতে পারছি না [জিনিস] কতটা [বিশেষণ]!",
      patternName: "Can't Believe Exclamation",
      patternName_bn: "অবিশ্বাস বিস্ময়",
      slots: [
        { name: "ADJECTIVE", description: "Descriptive word for emphasis", description_bn: "জোর দেওয়ার জন্য বর্ণনামূলক শব্দ", acceptedTypes: ["adjective"], examples: ["fast", "cheap", "talented"] },
        { name: "THING", description: "Subject of amazement", description_bn: "বিস্ময়ের বিষয়", acceptedTypes: ["noun", "noun_phrase", "person"], examples: ["this car", "she", "the food"] },
      ],
      examples: [
        { en: "I can't believe how fast this car is!", bn: "বিশ্বাস করতে পারছি না এই গাড়িটা কতটা দ্রুত!", slotValues: { ADJECTIVE: "fast", THING: "this car" } },
        { en: "I can't believe how cheap this restaurant is!", bn: "বিশ্বাস করতে পারছি না এই রেস্তোরাঁটা কতটা সস্তা!", slotValues: { ADJECTIVE: "cheap", THING: "this restaurant" } },
        { en: "I can't believe how talented she is!", bn: "বিশ্বাস করতে পারছি না সে কতটা প্রতিভাবান!", slotValues: { ADJECTIVE: "talented", THING: "she" } },
        { en: "I can't believe how big this house is!", bn: "বিশ্বাস করতে পারছি না এই বাড়িটা কতটা বড়!", slotValues: { ADJECTIVE: "big", THING: "this house" } },
        { en: "I can't believe how cold it is outside!", bn: "বিশ্বাস করতে পারছি না বাইরে কতটা ঠান্ডা!", slotValues: { ADJECTIVE: "cold", THING: "it" } },
        { en: "I can't believe how rude he was!", bn: "বিশ্বাস করতে পারছি না সে কতটা অভদ্র ছিল!", slotValues: { ADJECTIVE: "rude", THING: "he" } },
        { en: "I can't believe how beautiful this place is!", bn: "বিশ্বাস করতে পারছি না এই জায়গাটা কতটা সুন্দর!", slotValues: { ADJECTIVE: "beautiful", THING: "this place" } },
        { en: "I can't believe how quiet the library is!", bn: "বিশ্বাস করতে পারছি না লাইব্রেরিটা কতটা শান্ত!", slotValues: { ADJECTIVE: "quiet", THING: "the library" } },
        { en: "I can't believe how expensive this phone is!", bn: "বিশ্বাস করতে পারছি না এই ফোনটা কতটা দামি!", slotValues: { ADJECTIVE: "expensive", THING: "this phone" } },
        { en: "I can't believe how tall he has grown!", bn: "বিশ্বাস করতে পারছি না সে কতটা লম্বা হয়ে গেছে!", slotValues: { ADJECTIVE: "tall", THING: "he" } },
        { en: "I can't believe how crowded this place is!", bn: "বিশ্বাস করতে পারছি না এই জায়গাটা কতটা ভিড়!", slotValues: { ADJECTIVE: "crowded", THING: "this place" } },
        { en: "I can't believe how easy this test is!", bn: "বিশ্বাস করতে পারছি না এই পরীক্ষাটা কতটা সহজ!", slotValues: { ADJECTIVE: "easy", THING: "this test" } },
        { en: "I can't believe how spicy this curry is!", bn: "বিশ্বাস করতে পারছি না এই তরকারিটা কতটা ঝাল!", slotValues: { ADJECTIVE: "spicy", THING: "this curry" } },
        { en: "I can't believe how smart your kids are!", bn: "বিশ্বাস করতে পারছি না তোমার বাচ্চারা কতটা বুদ্ধিমান!", slotValues: { ADJECTIVE: "smart", THING: "your kids" } },
        { en: "I can't believe how quickly time flies!", bn: "বিশ্বাস করতে পারছি না সময় কতটা দ্রুত চলে যায়!", slotValues: { ADJECTIVE: "quickly", THING: "time" } },
      ],
      formality: "casual",
      difficulty: "intermediate",
    },
  ],
};
