import { PatternCategory } from "@/types/pattern";

export const categoryP3: PatternCategory = {
  id: "P3",
  slug: "emphasizing-with-adverbs",
  name: "Emphasizing with Adverbs",
  name_bn: "ক্রিয়াবিশেষণ দিয়ে জোর দেওয়া",
  description: "Strengthen statements using emphatic adverbs",
  description_bn: "জোরদার ক্রিয়াবিশেষণ ব্যবহার করে বক্তব্য শক্তিশালী করুন",
  icon: "🔊",
  group: "P",
  groupName: "Exclamations & Emphasis",
  groupName_bn: "বিস্ময়সূচক ও জোর দেওয়া",
  difficulty: "intermediate",
  patterns: [
    {
      id: "P3.1",
      formula: "I really [ACTION]",
      formula_bn: "আমি সত্যিই [কাজ]",
      patternName: "Emphasis with Really",
      patternName_bn: "Really দিয়ে জোর",
      slots: [
        { name: "ACTION", description: "Verb phrase to emphasize", description_bn: "জোর দেওয়ার ক্রিয়া", acceptedTypes: ["verb_phrase"], examples: ["enjoy it", "need this", "appreciate it"] },
      ],
      examples: [
        { en: "I really enjoy spending time with you.", bn: "আমি সত্যিই তোমার সাথে সময় কাটাতে উপভোগ করি।", slotValues: { ACTION: "enjoy spending time with you" } },
        { en: "I really need a vacation.", bn: "আমার সত্যিই একটা ছুটি দরকার।", slotValues: { ACTION: "need a vacation" } },
        { en: "I really appreciate your help.", bn: "আমি সত্যিই তোমার সাহায্যের প্রশংসা করি।", slotValues: { ACTION: "appreciate your help" } },
        { en: "I really love this song.", bn: "আমি সত্যিই এই গানটা ভালোবাসি।", slotValues: { ACTION: "love this song" } },
        { en: "I really miss my family.", bn: "আমি সত্যিই আমার পরিবারকে মিস করি।", slotValues: { ACTION: "miss my family" } },
        { en: "I really hope it works out.", bn: "আমি সত্যিই আশা করি এটা কাজ করবে।", slotValues: { ACTION: "hope it works out" } },
        { en: "I really want to learn guitar.", bn: "আমি সত্যিই গিটার শিখতে চাই।", slotValues: { ACTION: "want to learn guitar" } },
        { en: "I really hate waking up early.", bn: "আমি সত্যিই তাড়াতাড়ি উঠতে ঘৃণা করি।", slotValues: { ACTION: "hate waking up early" } },
        { en: "I really think you should apply.", bn: "আমি সত্যিই মনে করি তোমার আবেদন করা উচিত।", slotValues: { ACTION: "think you should apply" } },
        { en: "I really admire her courage.", bn: "আমি সত্যিই তার সাহসের প্রশংসা করি।", slotValues: { ACTION: "admire her courage" } },
        { en: "I really liked the movie.", bn: "আমি সত্যিই সিনেমাটা পছন্দ করেছি।", slotValues: { ACTION: "liked the movie" } },
        { en: "I really don't understand this problem.", bn: "আমি সত্যিই এই সমস্যাটা বুঝি না।", slotValues: { ACTION: "don't understand this problem" } },
        { en: "I really feel grateful for everything.", bn: "আমি সত্যিই সবকিছুর জন্য কৃতজ্ঞ।", slotValues: { ACTION: "feel grateful for everything" } },
        { en: "I really regret not studying harder.", bn: "আমি সত্যিই আরও পড়াশোনা না করার জন্য আফসোস করি।", slotValues: { ACTION: "regret not studying harder" } },
        { en: "I really believe we can win.", bn: "আমি সত্যিই বিশ্বাস করি আমরা জিততে পারব।", slotValues: { ACTION: "believe we can win" } },
      ],
      formality: "casual",
      difficulty: "intermediate",
    },
    {
      id: "P3.2",
      formula: "I absolutely [DESCRIPTION]",
      formula_bn: "আমি পুরোপুরি [বর্ণনা]",
      patternName: "Emphasis with Absolutely",
      patternName_bn: "Absolutely দিয়ে জোর",
      slots: [
        { name: "DESCRIPTION", description: "Verb or adjective phrase", description_bn: "ক্রিয়া বা বিশেষণ বাক্যাংশ", acceptedTypes: ["verb_phrase", "adjective_phrase"], examples: ["love it", "agree", "adore this place"] },
      ],
      examples: [
        { en: "I absolutely love this place!", bn: "আমি পুরোপুরি এই জায়গাটা ভালোবাসি!", slotValues: { DESCRIPTION: "love this place" } },
        { en: "I absolutely agree with you.", bn: "আমি পুরোপুরি তোমার সাথে একমত।", slotValues: { DESCRIPTION: "agree with you" } },
        { en: "I absolutely adore her cooking.", bn: "আমি পুরোপুরি তার রান্না পছন্দ করি।", slotValues: { DESCRIPTION: "adore her cooking" } },
        { en: "I absolutely refuse to accept this.", bn: "আমি পুরোপুরি এটা মানতে অস্বীকার করি।", slotValues: { DESCRIPTION: "refuse to accept this" } },
        { en: "I'm absolutely certain about it.", bn: "আমি এ ব্যাপারে পুরোপুরি নিশ্চিত।", slotValues: { DESCRIPTION: "certain about it" } },
        { en: "I absolutely need this done by Friday.", bn: "আমার পুরোপুরি শুক্রবারের মধ্যে এটা শেষ করা দরকার।", slotValues: { DESCRIPTION: "need this done by Friday" } },
        { en: "I absolutely hate being lied to.", bn: "আমি পুরোপুরি মিথ্যা শুনতে ঘৃণা করি।", slotValues: { DESCRIPTION: "hate being lied to" } },
        { en: "I'm absolutely thrilled about the news!", bn: "আমি খবরটায় পুরোপুরি রোমাঞ্চিত!", slotValues: { DESCRIPTION: "thrilled about the news" } },
        { en: "I absolutely trust her judgment.", bn: "আমি পুরোপুরি তার বিচারে বিশ্বাস করি।", slotValues: { DESCRIPTION: "trust her judgment" } },
        { en: "I absolutely cannot wait for the concert.", bn: "আমি পুরোপুরি কনসার্টের জন্য অপেক্ষা করতে পারছি না।", slotValues: { DESCRIPTION: "cannot wait for the concert" } },
        { en: "I absolutely promise to be there.", bn: "আমি পুরোপুরি প্রতিশ্রুতি দিচ্ছি সেখানে থাকব।", slotValues: { DESCRIPTION: "promise to be there" } },
        { en: "I'm absolutely exhausted today.", bn: "আমি আজ পুরোপুরি ক্লান্ত।", slotValues: { DESCRIPTION: "exhausted today" } },
        { en: "I absolutely recommend this book.", bn: "আমি পুরোপুরি এই বইটি সুপারিশ করি।", slotValues: { DESCRIPTION: "recommend this book" } },
        { en: "I absolutely must see that movie.", bn: "আমাকে পুরোপুরি ওই সিনেমাটা দেখতে হবে।", slotValues: { DESCRIPTION: "must see that movie" } },
        { en: "I'm absolutely delighted to meet you.", bn: "আপনার সাথে দেখা হয়ে আমি পুরোপুরি আনন্দিত।", slotValues: { DESCRIPTION: "delighted to meet you" } },
      ],
      formality: "casual",
      difficulty: "intermediate",
    },
    {
      id: "P3.3",
      formula: "I completely [DESCRIPTION]",
      formula_bn: "আমি সম্পূর্ণভাবে [বর্ণনা]",
      patternName: "Emphasis with Completely",
      patternName_bn: "Completely দিয়ে জোর",
      slots: [
        { name: "DESCRIPTION", description: "Verb or adjective phrase", description_bn: "ক্রিয়া বা বিশেষণ বাক্যাংশ", acceptedTypes: ["verb_phrase", "adjective_phrase"], examples: ["understand", "forgot", "agree"] },
      ],
      examples: [
        { en: "I completely understand your situation.", bn: "আমি সম্পূর্ণভাবে তোমার পরিস্থিতি বুঝি।", slotValues: { DESCRIPTION: "understand your situation" } },
        { en: "I completely forgot about the meeting.", bn: "আমি সম্পূর্ণভাবে মিটিংয়ের কথা ভুলে গেছি।", slotValues: { DESCRIPTION: "forgot about the meeting" } },
        { en: "I completely agree with the decision.", bn: "আমি সম্পূর্ণভাবে সিদ্ধান্তের সাথে একমত।", slotValues: { DESCRIPTION: "agree with the decision" } },
        { en: "I completely changed my mind.", bn: "আমি সম্পূর্ণভাবে মত পরিবর্তন করেছি।", slotValues: { DESCRIPTION: "changed my mind" } },
        { en: "I completely trust your judgment.", bn: "আমি সম্পূর্ণভাবে তোমার বিচারে বিশ্বাস করি।", slotValues: { DESCRIPTION: "trust your judgment" } },
        { en: "I completely messed up the recipe.", bn: "আমি সম্পূর্ণভাবে রেসিপিটা গোলমাল করে ফেলেছি।", slotValues: { DESCRIPTION: "messed up the recipe" } },
        { en: "I completely disagree with that statement.", bn: "আমি সম্পূর্ণভাবে ওই বক্তব্যের সাথে অসম্মত।", slotValues: { DESCRIPTION: "disagree with that statement" } },
        { en: "I completely lost track of time.", bn: "আমি সম্পূর্ণভাবে সময়ের ট্র্যাক হারিয়ে ফেলেছি।", slotValues: { DESCRIPTION: "lost track of time" } },
        { en: "I'm completely satisfied with the result.", bn: "আমি ফলাফলে সম্পূর্ণভাবে সন্তুষ্ট।", slotValues: { DESCRIPTION: "satisfied with the result" } },
        { en: "I completely misunderstood the instructions.", bn: "আমি সম্পূর্ণভাবে নির্দেশনাগুলো ভুল বুঝেছি।", slotValues: { DESCRIPTION: "misunderstood the instructions" } },
        { en: "I completely ignored his advice.", bn: "আমি সম্পূর্ণভাবে তার উপদেশ উপেক্ষা করেছি।", slotValues: { DESCRIPTION: "ignored his advice" } },
        { en: "I completely support your decision.", bn: "আমি সম্পূর্ণভাবে তোমার সিদ্ধান্ত সমর্থন করি।", slotValues: { DESCRIPTION: "support your decision" } },
        { en: "I'm completely overwhelmed right now.", bn: "আমি এই মুহূর্তে সম্পূর্ণভাবে অভিভূত।", slotValues: { DESCRIPTION: "overwhelmed right now" } },
        { en: "I completely ruined the surprise.", bn: "আমি সম্পূর্ণভাবে চমকটা নষ্ট করে দিয়েছি।", slotValues: { DESCRIPTION: "ruined the surprise" } },
        { en: "I completely failed the driving test.", bn: "আমি সম্পূর্ণভাবে ড্রাইভিং পরীক্ষায় ফেল করেছি।", slotValues: { DESCRIPTION: "failed the driving test" } },
      ],
      formality: "casual",
      difficulty: "intermediate",
    },
    {
      id: "P3.4",
      formula: "I truly [ACTION]",
      formula_bn: "আমি প্রকৃতপক্ষে [কাজ]",
      patternName: "Emphasis with Truly",
      patternName_bn: "Truly দিয়ে জোর",
      slots: [
        { name: "ACTION", description: "Sincere action or feeling", description_bn: "আন্তরিক কাজ বা অনুভূতি", acceptedTypes: ["verb_phrase"], examples: ["believe", "appreciate", "care"] },
      ],
      examples: [
        { en: "I truly believe in you.", bn: "আমি প্রকৃতপক্ষে তোমার উপর বিশ্বাস করি।", slotValues: { ACTION: "believe in you" } },
        { en: "I truly appreciate everything you've done.", bn: "তুমি যা কিছু করেছ তার সবকিছুর জন্য আমি প্রকৃতপক্ষে কৃতজ্ঞ।", slotValues: { ACTION: "appreciate everything you've done" } },
        { en: "I truly care about your happiness.", bn: "আমি প্রকৃতপক্ষে তোমার সুখের ব্যাপারে চিন্তা করি।", slotValues: { ACTION: "care about your happiness" } },
        { en: "I truly admire your dedication.", bn: "আমি প্রকৃতপক্ষে তোমার নিষ্ঠার প্রশংসা করি।", slotValues: { ACTION: "admire your dedication" } },
        { en: "I truly love what I do.", bn: "আমি প্রকৃতপক্ষে আমি যা করি তা ভালোবাসি।", slotValues: { ACTION: "love what I do" } },
        { en: "I truly regret my words.", bn: "আমি প্রকৃতপক্ষে আমার কথার জন্য আফসোস করি।", slotValues: { ACTION: "regret my words" } },
        { en: "I truly hope you find peace.", bn: "আমি প্রকৃতপক্ষে আশা করি তুমি শান্তি পাবে।", slotValues: { ACTION: "hope you find peace" } },
        { en: "I truly understand how you feel.", bn: "আমি প্রকৃতপক্ষে বুঝি তুমি কেমন অনুভব করছ।", slotValues: { ACTION: "understand how you feel" } },
        { en: "I truly value our friendship.", bn: "আমি প্রকৃতপক্ষে আমাদের বন্ধুত্বকে মূল্যবান মনে করি।", slotValues: { ACTION: "value our friendship" } },
        { en: "I truly missed you while you were away.", bn: "তুমি দূরে থাকতে আমি প্রকৃতপক্ষে তোমাকে মিস করেছি।", slotValues: { ACTION: "missed you while you were away" } },
        { en: "I truly want the best for my children.", bn: "আমি প্রকৃতপক্ষে আমার সন্তানদের জন্য সেরাটা চাই।", slotValues: { ACTION: "want the best for my children" } },
        { en: "I truly respect his opinion.", bn: "আমি প্রকৃতপক্ষে তার মতামতকে সম্মান করি।", slotValues: { ACTION: "respect his opinion" } },
        { en: "I truly enjoy our conversations.", bn: "আমি প্রকৃতপক্ষে আমাদের কথোপকথন উপভোগ করি।", slotValues: { ACTION: "enjoy our conversations" } },
        { en: "I'm truly sorry for what happened.", bn: "যা হয়েছে তার জন্য আমি প্রকৃতপক্ষে দুঃখিত।", slotValues: { ACTION: "sorry for what happened" } },
        { en: "I truly wish you all the best.", bn: "আমি প্রকৃতপক্ষে তোমার জন্য সব শুভকামনা জানাই।", slotValues: { ACTION: "wish you all the best" } },
      ],
      formality: "polite",
      difficulty: "intermediate",
    },
    {
      id: "P3.5",
      formula: "I definitely [ACTION]",
      formula_bn: "আমি অবশ্যই [কাজ]",
      patternName: "Emphasis with Definitely",
      patternName_bn: "Definitely দিয়ে জোর",
      slots: [
        { name: "ACTION", description: "Certain action or opinion", description_bn: "নিশ্চিত কাজ বা মতামত", acceptedTypes: ["verb_phrase"], examples: ["want to go", "agree", "recommend it"] },
      ],
      examples: [
        { en: "I definitely want to go to the concert.", bn: "আমি অবশ্যই কনসার্টে যেতে চাই।", slotValues: { ACTION: "want to go to the concert" } },
        { en: "I definitely recommend this restaurant.", bn: "আমি অবশ্যই এই রেস্তোরাঁটি সুপারিশ করি।", slotValues: { ACTION: "recommend this restaurant" } },
        { en: "I definitely need to exercise more.", bn: "আমার অবশ্যই আরও ব্যায়াম করা দরকার।", slotValues: { ACTION: "need to exercise more" } },
        { en: "I'm definitely coming to the party.", bn: "আমি অবশ্যই পার্টিতে আসছি।", slotValues: { ACTION: "coming to the party" } },
        { en: "I definitely prefer tea over coffee.", bn: "আমি অবশ্যই কফির চেয়ে চা পছন্দ করি।", slotValues: { ACTION: "prefer tea over coffee" } },
        { en: "I definitely saw him at the store.", bn: "আমি অবশ্যই তাকে দোকানে দেখেছি।", slotValues: { ACTION: "saw him at the store" } },
        { en: "I definitely won't forget this.", bn: "আমি অবশ্যই এটা ভুলব না।", slotValues: { ACTION: "won't forget this" } },
        { en: "I definitely think we should try.", bn: "আমি অবশ্যই মনে করি আমাদের চেষ্টা করা উচিত।", slotValues: { ACTION: "think we should try" } },
        { en: "I definitely learned a lot today.", bn: "আমি আজ অবশ্যই অনেক কিছু শিখেছি।", slotValues: { ACTION: "learned a lot today" } },
        { en: "I definitely plan to visit again.", bn: "আমি অবশ্যই আবার যাওয়ার পরিকল্পনা করছি।", slotValues: { ACTION: "plan to visit again" } },
        { en: "I definitely feel better now.", bn: "আমি এখন অবশ্যই ভালো অনুভব করছি।", slotValues: { ACTION: "feel better now" } },
        { en: "I definitely noticed a difference.", bn: "আমি অবশ্যই একটা পার্থক্য লক্ষ্য করেছি।", slotValues: { ACTION: "noticed a difference" } },
        { en: "I'm definitely not eating there again.", bn: "আমি অবশ্যই আর সেখানে খাব না।", slotValues: { ACTION: "not eating there again" } },
        { en: "I definitely agree with your proposal.", bn: "আমি অবশ্যই তোমার প্রস্তাবের সাথে একমত।", slotValues: { ACTION: "agree with your proposal" } },
        { en: "I definitely owe you one.", bn: "আমি অবশ্যই তোমার কাছে ঋণী।", slotValues: { ACTION: "owe you one" } },
      ],
      formality: "casual",
      difficulty: "intermediate",
    },
  ],
};
