import { PatternCategory } from "@/types/pattern";

export const categoryP7: PatternCategory = {
  id: "P7",
  slug: "understating-hedging",
  name: "Understating (Hedging)",
  name_bn: "কম করে বলা (হেজিং)",
  description: "Express opinions softly using understatement and hedging",
  description_bn: "কম করে বলা ও হেজিং ব্যবহার করে মৃদুভাবে মতামত প্রকাশ করুন",
  icon: "🤏",
  group: "P",
  groupName: "Exclamations & Emphasis",
  groupName_bn: "বিস্ময়সূচক ও জোর দেওয়া",
  difficulty: "intermediate",
  patterns: [
    {
      id: "P7.1",
      formula: "It's not bad",
      formula_bn: "এটা মন্দ না",
      patternName: "Understatement with Not Bad",
      patternName_bn: "Not Bad দিয়ে কম করে বলা",
      slots: [],
      examples: [
        { en: "The food here? It's not bad, actually.", bn: "এখানকার খাবার? আসলে মন্দ না।", slotValues: {} },
        { en: "His presentation was not bad at all.", bn: "তার প্রেজেন্টেশনটা মোটেও মন্দ ছিল না।", slotValues: {} },
        { en: "The salary is not bad for a first job.", bn: "প্রথম চাকরির জন্য বেতনটা মন্দ না।", slotValues: {} },
        { en: "The movie? It's not bad. Worth watching.", bn: "সিনেমাটা? মন্দ না। দেখার মতো।", slotValues: {} },
        { en: "Her singing is not bad. She has potential.", bn: "তার গান মন্দ না। তার সম্ভাবনা আছে।", slotValues: {} },
        { en: "The hotel room was not bad for the price.", bn: "দামের তুলনায় হোটেলের রুমটা মন্দ ছিল না।", slotValues: {} },
        { en: "The weather today is not bad. Let's go out.", bn: "আজকের আবহাওয়া মন্দ না। চলো বাইরে যাই।", slotValues: {} },
        { en: "My exam results were not bad, I suppose.", bn: "আমার পরীক্ষার ফলাফল মন্দ ছিল না, মনে হয়।", slotValues: {} },
        { en: "The coffee here is not bad. I've had worse.", bn: "এখানকার কফি মন্দ না। আমি আরও খারাপ খেয়েছি।", slotValues: {} },
        { en: "His cooking is not bad once you get used to it.", bn: "অভ্যস্ত হয়ে গেলে তার রান্না মন্দ না।", slotValues: {} },
        { en: "The commute is not bad. Only thirty minutes.", bn: "যাতায়াতটা মন্দ না। মাত্র ত্রিশ মিনিট।", slotValues: {} },
        { en: "The new phone is not bad. Quite decent, really.", bn: "নতুন ফোনটা মন্দ না। আসলে বেশ ভালো।", slotValues: {} },
        { en: "For a beginner, your work is not bad.", bn: "একজন নবীনের জন্য তোমার কাজ মন্দ না।", slotValues: {} },
        { en: "The neighborhood is not bad. Quite safe, actually.", bn: "পাড়াটা মন্দ না। আসলে বেশ নিরাপদ।", slotValues: {} },
        { en: "The test wasn't bad. I think I passed.", bn: "পরীক্ষাটা মন্দ ছিল না। মনে হয় পাস করেছি।", slotValues: {} },
      ],
      formality: "casual",
      difficulty: "intermediate",
    },
    {
      id: "P7.2",
      formula: "[THING] could be better",
      formula_bn: "[জিনিস] আরও ভালো হতে পারত",
      patternName: "Mild Criticism with Could Be Better",
      patternName_bn: "Could Be Better দিয়ে মৃদু সমালোচনা",
      slots: [
        { name: "THING", description: "Subject being evaluated", description_bn: "মূল্যায়নের বিষয়", acceptedTypes: ["noun", "noun_phrase"], examples: ["the service", "my grades", "the design"] },
      ],
      examples: [
        { en: "The service here could be better.", bn: "এখানকার সেবা আরও ভালো হতে পারত।", slotValues: { THING: "the service here" } },
        { en: "My grades could be better, honestly.", bn: "সত্যি বলতে, আমার গ্রেড আরও ভালো হতে পারত।", slotValues: { THING: "my grades" } },
        { en: "The design could be better. It needs more color.", bn: "ডিজাইনটা আরও ভালো হতে পারত। আরও রঙ দরকার।", slotValues: { THING: "the design" } },
        { en: "The Wi-Fi speed could be better.", bn: "ওয়াই-ফাই গতি আরও ভালো হতে পারত।", slotValues: { THING: "the Wi-Fi speed" } },
        { en: "His attitude could be better.", bn: "তার মনোভাব আরও ভালো হতে পারত।", slotValues: { THING: "his attitude" } },
        { en: "The parking situation could be better.", bn: "পার্কিং পরিস্থিতি আরও ভালো হতে পারত।", slotValues: { THING: "the parking situation" } },
        { en: "My health could be better these days.", bn: "আজকাল আমার স্বাস্থ্য আরও ভালো হতে পারত।", slotValues: { THING: "my health" } },
        { en: "The communication between teams could be better.", bn: "দলগুলোর মধ্যে যোগাযোগ আরও ভালো হতে পারত।", slotValues: { THING: "the communication between teams" } },
        { en: "The lighting in this room could be better.", bn: "এই ঘরের আলো আরও ভালো হতে পারত।", slotValues: { THING: "the lighting in this room" } },
        { en: "Our sales numbers could be better.", bn: "আমাদের বিক্রির সংখ্যা আরও ভালো হতে পারত।", slotValues: { THING: "our sales numbers" } },
        { en: "The instructions could be better. They're confusing.", bn: "নির্দেশনাগুলো আরও ভালো হতে পারত। এগুলো বিভ্রান্তিকর।", slotValues: { THING: "the instructions" } },
        { en: "The timing could be better. It's too early.", bn: "সময়টা আরও ভালো হতে পারত। এটা খুব তাড়াতাড়ি।", slotValues: { THING: "the timing" } },
        { en: "The selection could be better at this shop.", bn: "এই দোকানে বাছাই আরও ভালো হতে পারত।", slotValues: { THING: "the selection" } },
        { en: "The sound quality could be better.", bn: "শব্দের মান আরও ভালো হতে পারত।", slotValues: { THING: "the sound quality" } },
        { en: "The organization of the event could be better.", bn: "অনুষ্ঠানের আয়োজন আরও ভালো হতে পারত।", slotValues: { THING: "the organization of the event" } },
      ],
      formality: "polite",
      difficulty: "intermediate",
    },
    {
      id: "P7.3",
      formula: "It's kind of [ADJECTIVE]",
      formula_bn: "এটা একটু [বিশেষণ]",
      patternName: "Hedging with Kind Of",
      patternName_bn: "Kind Of দিয়ে হেজিং",
      slots: [
        { name: "ADJECTIVE", description: "Softened descriptive word", description_bn: "নরম বর্ণনামূলক শব্দ", acceptedTypes: ["adjective"], examples: ["boring", "weird", "nice"] },
      ],
      examples: [
        { en: "The lecture was kind of boring.", bn: "লেকচারটা একটু বিরক্তিকর ছিল।", slotValues: { ADJECTIVE: "boring" } },
        { en: "This situation is kind of weird.", bn: "এই পরিস্থিতিটা একটু অদ্ভুত।", slotValues: { ADJECTIVE: "weird" } },
        { en: "The restaurant is kind of expensive.", bn: "রেস্তোরাঁটা একটু দামি।", slotValues: { ADJECTIVE: "expensive" } },
        { en: "It's kind of cold outside today.", bn: "আজ বাইরে একটু ঠান্ডা।", slotValues: { ADJECTIVE: "cold" } },
        { en: "The movie was kind of long.", bn: "সিনেমাটা একটু লম্বা ছিল।", slotValues: { ADJECTIVE: "long" } },
        { en: "He's kind of shy around new people.", bn: "নতুন মানুষের কাছে সে একটু লাজুক।", slotValues: { ADJECTIVE: "shy" } },
        { en: "The question is kind of tricky.", bn: "প্রশ্নটা একটু কঠিন।", slotValues: { ADJECTIVE: "tricky" } },
        { en: "The area is kind of noisy at night.", bn: "রাতে এলাকাটা একটু কোলাহলপূর্ণ।", slotValues: { ADJECTIVE: "noisy" } },
        { en: "His jokes are kind of funny.", bn: "তার কৌতুকগুলো একটু মজার।", slotValues: { ADJECTIVE: "funny" } },
        { en: "The traffic is kind of bad today.", bn: "আজ ট্রাফিক একটু খারাপ।", slotValues: { ADJECTIVE: "bad" } },
        { en: "The deadline is kind of tight.", bn: "সময়সীমাটা একটু চাপের।", slotValues: { ADJECTIVE: "tight" } },
        { en: "She's kind of strict as a teacher.", bn: "শিক্ষক হিসেবে সে একটু কঠোর।", slotValues: { ADJECTIVE: "strict" } },
        { en: "The color is kind of dull.", bn: "রংটা একটু ফ্যাকাশে।", slotValues: { ADJECTIVE: "dull" } },
        { en: "It's kind of difficult to explain.", bn: "ব্যাখ্যা করা একটু কঠিন।", slotValues: { ADJECTIVE: "difficult" } },
        { en: "The neighborhood is kind of quiet.", bn: "পাড়াটা একটু শান্ত।", slotValues: { ADJECTIVE: "quiet" } },
      ],
      formality: "casual",
      difficulty: "intermediate",
    },
    {
      id: "P7.4",
      formula: "It's not exactly [ADJECTIVE]",
      formula_bn: "এটা ঠিক [বিশেষণ] নয়",
      patternName: "Hedging with Not Exactly",
      patternName_bn: "Not Exactly দিয়ে হেজিং",
      slots: [
        { name: "ADJECTIVE", description: "Negated quality", description_bn: "অস্বীকৃত গুণ", acceptedTypes: ["adjective", "adjective_phrase"], examples: ["cheap", "perfect", "what I expected"] },
      ],
      examples: [
        { en: "It's not exactly cheap, but it's worth it.", bn: "এটা ঠিক সস্তা নয়, তবে এটা মূল্যবান।", slotValues: { ADJECTIVE: "cheap" } },
        { en: "The result is not exactly what I expected.", bn: "ফলাফলটা ঠিক আমি যা আশা করেছিলাম তা নয়।", slotValues: { ADJECTIVE: "what I expected" } },
        { en: "He's not exactly the friendliest person.", bn: "সে ঠিক সবচেয়ে বন্ধুত্বপূর্ণ মানুষ নয়।", slotValues: { ADJECTIVE: "the friendliest person" } },
        { en: "This place is not exactly a five-star hotel.", bn: "এই জায়গাটা ঠিক পাঁচতারা হোটেল নয়।", slotValues: { ADJECTIVE: "a five-star hotel" } },
        { en: "The plan is not exactly foolproof.", bn: "পরিকল্পনাটা ঠিক নিখুঁত নয়।", slotValues: { ADJECTIVE: "foolproof" } },
        { en: "Her cooking is not exactly gourmet.", bn: "তার রান্না ঠিক উচ্চমানের নয়।", slotValues: { ADJECTIVE: "gourmet" } },
        { en: "The weather is not exactly ideal for a picnic.", bn: "পিকনিকের জন্য আবহাওয়া ঠিক আদর্শ নয়।", slotValues: { ADJECTIVE: "ideal for a picnic" } },
        { en: "He's not exactly known for his punctuality.", bn: "সে ঠিক তার সময়ানুবর্তিতার জন্য পরিচিত নয়।", slotValues: { ADJECTIVE: "known for his punctuality" } },
        { en: "The movie was not exactly a masterpiece.", bn: "সিনেমাটা ঠিক একটা মাস্টারপিস ছিল না।", slotValues: { ADJECTIVE: "a masterpiece" } },
        { en: "The apartment is not exactly spacious.", bn: "অ্যাপার্টমেন্টটা ঠিক প্রশস্ত নয়।", slotValues: { ADJECTIVE: "spacious" } },
        { en: "His excuse was not exactly convincing.", bn: "তার অজুহাত ঠিক বিশ্বাসযোগ্য ছিল না।", slotValues: { ADJECTIVE: "convincing" } },
        { en: "The journey was not exactly comfortable.", bn: "যাত্রাটা ঠিক আরামদায়ক ছিল না।", slotValues: { ADJECTIVE: "comfortable" } },
        { en: "Her response was not exactly enthusiastic.", bn: "তার সাড়া ঠিক উৎসাহী ছিল না।", slotValues: { ADJECTIVE: "enthusiastic" } },
        { en: "The report is not exactly what we needed.", bn: "রিপোর্টটা ঠিক আমাদের যা দরকার ছিল তা নয়।", slotValues: { ADJECTIVE: "what we needed" } },
        { en: "The neighborhood is not exactly safe at night.", bn: "রাতে পাড়াটা ঠিক নিরাপদ নয়।", slotValues: { ADJECTIVE: "safe at night" } },
      ],
      formality: "polite",
      difficulty: "intermediate",
    },
    {
      id: "P7.5",
      formula: "I suppose [CLAUSE]",
      formula_bn: "আমার ধারণা [বাক্যাংশ]",
      patternName: "Reluctant Agreement",
      patternName_bn: "অনিচ্ছুক সম্মতি",
      slots: [
        { name: "CLAUSE", description: "Tentative statement", description_bn: "সাময়িক বক্তব্য", acceptedTypes: ["clause"], examples: ["it's okay", "we could try", "that's fair"] },
      ],
      examples: [
        { en: "I suppose it's okay to try.", bn: "আমার ধারণা চেষ্টা করা ঠিক আছে।", slotValues: { CLAUSE: "it's okay to try" } },
        { en: "I suppose we could give it a chance.", bn: "আমার ধারণা আমরা এটাকে একটা সুযোগ দিতে পারি।", slotValues: { CLAUSE: "we could give it a chance" } },
        { en: "I suppose that's fair enough.", bn: "আমার ধারণা এটা যথেষ্ট ন্যায্য।", slotValues: { CLAUSE: "that's fair enough" } },
        { en: "I suppose you have a point.", bn: "আমার ধারণা তোমার কথায় যুক্তি আছে।", slotValues: { CLAUSE: "you have a point" } },
        { en: "I suppose it could have been worse.", bn: "আমার ধারণা এটা আরও খারাপ হতে পারত।", slotValues: { CLAUSE: "it could have been worse" } },
        { en: "I suppose there's nothing we can do about it.", bn: "আমার ধারণা এ ব্যাপারে আমাদের কিছু করার নেই।", slotValues: { CLAUSE: "there's nothing we can do about it" } },
        { en: "I suppose he meant well.", bn: "আমার ধারণা সে ভালো উদ্দেশ্যেই করেছে।", slotValues: { CLAUSE: "he meant well" } },
        { en: "I suppose we should leave early.", bn: "আমার ধারণা আমাদের তাড়াতাড়ি রওনা হওয়া উচিত।", slotValues: { CLAUSE: "we should leave early" } },
        { en: "I suppose the weather might clear up later.", bn: "আমার ধারণা আবহাওয়া পরে পরিষ্কার হতে পারে।", slotValues: { CLAUSE: "the weather might clear up later" } },
        { en: "I suppose one more day won't hurt.", bn: "আমার ধারণা আরেকটা দিন ক্ষতি করবে না।", slotValues: { CLAUSE: "one more day won't hurt" } },
        { en: "I suppose you're right about that.", bn: "আমার ধারণা তুমি সেটা নিয়ে ঠিক বলেছ।", slotValues: { CLAUSE: "you're right about that" } },
        { en: "I suppose we should accept the offer.", bn: "আমার ধারণা আমাদের অফারটা গ্রহণ করা উচিত।", slotValues: { CLAUSE: "we should accept the offer" } },
        { en: "I suppose things will get better eventually.", bn: "আমার ধারণা জিনিসগুলো শেষ পর্যন্ত ভালো হবে।", slotValues: { CLAUSE: "things will get better eventually" } },
        { en: "I suppose I should apologize first.", bn: "আমার ধারণা আমার আগে ক্ষমা চাওয়া উচিত।", slotValues: { CLAUSE: "I should apologize first" } },
        { en: "I suppose it's time to move on.", bn: "আমার ধারণা এগিয়ে যাওয়ার সময় হয়েছে।", slotValues: { CLAUSE: "it's time to move on" } },
      ],
      formality: "polite",
      difficulty: "intermediate",
    },
    {
      id: "P7.6",
      formula: "Not particularly [ADJECTIVE]",
      formula_bn: "বিশেষভাবে [বিশেষণ] না",
      patternName: "Soft Negation",
      patternName_bn: "মৃদু নেতিবাচকতা",
      slots: [
        {
          name: "ADJECTIVE",
          description: "A softened negative quality",
          description_bn: "একটি নরম নেতিবাচক গুণ",
          acceptedTypes: ["adjective"],
          examples: ["interested", "hungry", "impressed"],
        },
      ],
      examples: [
        { en: "I'm not particularly interested in that topic.", bn: "আমি সেই বিষয়ে বিশেষভাবে আগ্রহী না।", slotValues: { ADJECTIVE: "interested" } },
        { en: "The food was not particularly tasty.", bn: "খাবারটা বিশেষভাবে সুস্বাদু ছিল না।", slotValues: { ADJECTIVE: "tasty" } },
        { en: "The hotel was not particularly comfortable.", bn: "হোটেলটা বিশেষভাবে আরামদায়ক ছিল না।", slotValues: { ADJECTIVE: "comfortable" } },
        { en: "The lecture was not particularly engaging.", bn: "লেকচারটা বিশেষভাবে আকর্ষণীয় ছিল না।", slotValues: { ADJECTIVE: "engaging" } },
        { en: "The project was not particularly challenging.", bn: "প্রজেক্টটা বিশেষভাবে চ্যালেঞ্জিং ছিল না।", slotValues: { ADJECTIVE: "challenging" } },
        { en: "I'm not particularly hungry right now.", bn: "আমি এই মুহূর্তে বিশেষভাবে ক্ষুধার্ত না।", slotValues: { ADJECTIVE: "hungry" } },
        { en: "The prices are not particularly cheap here.", bn: "এখানে দাম বিশেষভাবে সস্তা না।", slotValues: { ADJECTIVE: "cheap" } },
        { en: "He's not particularly friendly with strangers.", bn: "সে অপরিচিতদের সাথে বিশেষভাবে বন্ধুত্বপূর্ণ না।", slotValues: { ADJECTIVE: "friendly" } },
        { en: "I'm not particularly excited about the plan.", bn: "আমি পরিকল্পনা নিয়ে বিশেষভাবে উত্তেজিত না।", slotValues: { ADJECTIVE: "excited" } },
        { en: "The restaurant was not particularly crowded.", bn: "রেস্তোরাঁটা বিশেষভাবে ভিড় ছিল না।", slotValues: { ADJECTIVE: "crowded" } },
        { en: "The journey was not particularly long.", bn: "যাত্রাটা বিশেষভাবে লম্বা ছিল না।", slotValues: { ADJECTIVE: "long" } },
        { en: "The book was not particularly difficult.", bn: "বইটা বিশেষভাবে কঠিন ছিল না।", slotValues: { ADJECTIVE: "difficult" } },
        { en: "I'm not particularly worried about it.", bn: "আমি এটা নিয়ে বিশেষভাবে চিন্তিত না।", slotValues: { ADJECTIVE: "worried" } },
        { en: "The manager was not particularly impressed.", bn: "ম্যানেজার বিশেষভাবে মুগ্ধ ছিলেন না।", slotValues: { ADJECTIVE: "impressed" } },
        { en: "The weather is not particularly warm today.", bn: "আজকের আবহাওয়া বিশেষভাবে গরম না।", slotValues: { ADJECTIVE: "warm" } },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "'Not particularly' is a polite way to express a mild negative opinion. It softens direct criticism and sounds more diplomatic than saying 'not at all'.",
      usageNote_bn:
        "'Not particularly' মৃদু নেতিবাচক মতামত প্রকাশের ভদ্র উপায়। এটি সরাসরি সমালোচনা নরম করে এবং 'not at all' বলার চেয়ে বেশি কূটনৈতিক শোনায়।",
      combinableWith: ["P7.3", "P7.4"],
      banglaStructureMap:
        "বিশেষভাবে (Particularly) + [ADJECTIVE] (বিশেষণ) + না (Negation)",
    },
  ],
};
