import { PatternCategory } from "@/types/pattern";

export const categoryQ2: PatternCategory = {
  id: "Q2",
  slug: "giving-instructions",
  name: "Giving Instructions",
  name_bn: "নির্দেশনা দেওয়া",
  description: "Learn to give clear step-by-step instructions",
  description_bn: "পরিষ্কার ধাপে ধাপে নির্দেশনা দিতে শিখুন",
  icon: "📋",
  group: "Q",
  groupName: "Advice, Instructions & Commands",
  groupName_bn: "উপদেশ, নির্দেশনা ও আদেশ",
  difficulty: "beginner",
  patterns: [
    {
      id: "Q2.1",
      formula: "First, [ACTION]. Then, [ACTION]",
      formula_bn: "প্রথমে, [কাজ]। তারপর, [কাজ]",
      patternName: "Sequential Instructions",
      patternName_bn: "ক্রমানুসারে নির্দেশনা",
      slots: [
        { name: "ACTION", description: "Steps in a sequence", description_bn: "ক্রমানুসারে ধাপ", acceptedTypes: ["verb_phrase"], examples: ["wash your hands", "add the spices", "turn left"] },
      ],
      examples: [
        { en: "First, wash your hands. Then, start cooking.", bn: "প্রথমে, হাত ধুয়ে নাও। তারপর, রান্না শুরু করো।", slotValues: { ACTION: "wash your hands / start cooking" } },
        { en: "First, read the question carefully. Then, write your answer.", bn: "প্রথমে, প্রশ্নটি সাবধানে পড়ো। তারপর, তোমার উত্তর লেখো।", slotValues: { ACTION: "read the question carefully / write your answer" } },
        { en: "First, turn on the computer. Then, open the browser.", bn: "প্রথমে, কম্পিউটার চালু করো। তারপর, ব্রাউজার খোলো।", slotValues: { ACTION: "turn on the computer / open the browser" } },
        { en: "First, boil the water. Then, add the tea leaves.", bn: "প্রথমে, পানি ফুটাও। তারপর, চা পাতা দাও।", slotValues: { ACTION: "boil the water / add the tea leaves" } },
        { en: "First, take a left turn. Then, go straight for two blocks.", bn: "প্রথমে, বামে মোড় নাও। তারপর, দুই ব্লক সোজা যাও।", slotValues: { ACTION: "take a left turn / go straight for two blocks" } },
        { en: "First, preheat the oven. Then, prepare the batter.", bn: "প্রথমে, ওভেন গরম করো। তারপর, ব্যাটার তৈরি করো।", slotValues: { ACTION: "preheat the oven / prepare the batter" } },
        { en: "First, save the document. Then, close the application.", bn: "প্রথমে, ডকুমেন্টটা সেভ করো। তারপর, অ্যাপ্লিকেশন বন্ধ করো।", slotValues: { ACTION: "save the document / close the application" } },
        { en: "First, introduce yourself. Then, explain your project.", bn: "প্রথমে, নিজের পরিচয় দাও। তারপর, তোমার প্রকল্প ব্যাখ্যা করো।", slotValues: { ACTION: "introduce yourself / explain your project" } },
        { en: "First, fill out the form. Then, submit it at the counter.", bn: "প্রথমে, ফর্মটি পূরণ করো। তারপর, কাউন্টারে জমা দাও।", slotValues: { ACTION: "fill out the form / submit it at the counter" } },
        { en: "First, cut the vegetables. Then, fry them in oil.", bn: "প্রথমে, সবজি কাটো। তারপর, তেলে ভাজো।", slotValues: { ACTION: "cut the vegetables / fry them in oil" } },
        { en: "First, charge the phone. Then, install the updates.", bn: "প্রথমে, ফোন চার্জ দাও। তারপর, আপডেটগুলো ইনস্টল করো।", slotValues: { ACTION: "charge the phone / install the updates" } },
        { en: "First, take off your shoes. Then, enter the room.", bn: "প্রথমে, জুতো খোলো। তারপর, ঘরে ঢোকো।", slotValues: { ACTION: "take off your shoes / enter the room" } },
        { en: "First, measure the ingredients. Then, mix them together.", bn: "প্রথমে, উপকরণ মেপে নাও। তারপর, একসাথে মেশাও।", slotValues: { ACTION: "measure the ingredients / mix them together" } },
        { en: "First, listen to the audio. Then, answer the questions.", bn: "প্রথমে, অডিও শোনো। তারপর, প্রশ্নগুলোর উত্তর দাও।", slotValues: { ACTION: "listen to the audio / answer the questions" } },
        { en: "First, unlock the door. Then, switch on the lights.", bn: "প্রথমে, দরজা খোলো। তারপর, বাতি জ্বালাও।", slotValues: { ACTION: "unlock the door / switch on the lights" } },
      ],
      formality: "casual",
      difficulty: "beginner",
    },
    {
      id: "Q2.2",
      formula: "Make sure to [ACTION]",
      formula_bn: "অবশ্যই [কাজ] করবে",
      patternName: "Ensuring an Action",
      patternName_bn: "কাজ নিশ্চিত করা",
      slots: [
        { name: "ACTION", description: "Important action to remember", description_bn: "মনে রাখার গুরুত্বপূর্ণ কাজ", acceptedTypes: ["verb_phrase"], examples: ["lock the door", "check your email", "turn off the stove"] },
      ],
      examples: [
        { en: "Make sure to lock the door before you leave.", bn: "যাওয়ার আগে অবশ্যই দরজা বন্ধ করবে।", slotValues: { ACTION: "lock the door before you leave" } },
        { en: "Make sure to check your email regularly.", bn: "অবশ্যই নিয়মিত তোমার ইমেইল চেক করবে।", slotValues: { ACTION: "check your email regularly" } },
        { en: "Make sure to turn off the stove after cooking.", bn: "রান্নার পরে অবশ্যই চুলা বন্ধ করবে।", slotValues: { ACTION: "turn off the stove after cooking" } },
        { en: "Make sure to bring your ID card.", bn: "অবশ্যই তোমার আইডি কার্ড আনবে।", slotValues: { ACTION: "bring your ID card" } },
        { en: "Make sure to save your work before closing.", bn: "বন্ধ করার আগে অবশ্যই তোমার কাজ সেভ করবে।", slotValues: { ACTION: "save your work before closing" } },
        { en: "Make sure to arrive at least ten minutes early.", bn: "অবশ্যই কমপক্ষে দশ মিনিট আগে পৌঁছাবে।", slotValues: { ACTION: "arrive at least ten minutes early" } },
        { en: "Make sure to wear comfortable shoes for the hike.", bn: "হাইকিংয়ের জন্য অবশ্যই আরামদায়ক জুতো পরবে।", slotValues: { ACTION: "wear comfortable shoes for the hike" } },
        { en: "Make sure to take your medicine on time.", bn: "অবশ্যই সময়মতো ওষুধ খাবে।", slotValues: { ACTION: "take your medicine on time" } },
        { en: "Make sure to proofread your essay.", bn: "অবশ্যই তোমার রচনাটি প্রুফরিড করবে।", slotValues: { ACTION: "proofread your essay" } },
        { en: "Make sure to drink plenty of water.", bn: "অবশ্যই প্রচুর পানি খাবে।", slotValues: { ACTION: "drink plenty of water" } },
        { en: "Make sure to set your alarm for tomorrow.", bn: "অবশ্যই আগামীকালের জন্য অ্যালার্ম সেট করবে।", slotValues: { ACTION: "set your alarm for tomorrow" } },
        { en: "Make sure to thank the host before leaving.", bn: "যাওয়ার আগে অবশ্যই হোস্টকে ধন্যবাদ দেবে।", slotValues: { ACTION: "thank the host before leaving" } },
        { en: "Make sure to back up your data regularly.", bn: "অবশ্যই নিয়মিত তোমার ডেটা ব্যাকআপ করবে।", slotValues: { ACTION: "back up your data regularly" } },
        { en: "Make sure to call me when you get home.", bn: "বাড়ি পৌঁছালে অবশ্যই আমাকে ফোন করবে।", slotValues: { ACTION: "call me when you get home" } },
        { en: "Make sure to follow the safety guidelines.", bn: "অবশ্যই নিরাপত্তা নির্দেশিকা মানবে।", slotValues: { ACTION: "follow the safety guidelines" } },
      ],
      formality: "casual",
      difficulty: "beginner",
    },
    {
      id: "Q2.3",
      formula: "Don't forget to [ACTION]",
      formula_bn: "[কাজ] করতে ভুলো না",
      patternName: "Reminder Instruction",
      patternName_bn: "স্মরণকারী নির্দেশনা",
      slots: [
        { name: "ACTION", description: "Action to remember", description_bn: "মনে রাখার কাজ", acceptedTypes: ["verb_phrase"], examples: ["pack your lunch", "water the plants", "sign the form"] },
      ],
      examples: [
        { en: "Don't forget to pack your lunch.", bn: "দুপুরের খাবার গুছিয়ে নিতে ভুলো না।", slotValues: { ACTION: "pack your lunch" } },
        { en: "Don't forget to water the plants.", bn: "গাছে পানি দিতে ভুলো না।", slotValues: { ACTION: "water the plants" } },
        { en: "Don't forget to sign the form at the bottom.", bn: "ফর্মের নিচে সাক্ষর করতে ভুলো না।", slotValues: { ACTION: "sign the form at the bottom" } },
        { en: "Don't forget to buy milk on your way home.", bn: "বাড়ি ফেরার পথে দুধ কিনতে ভুলো না।", slotValues: { ACTION: "buy milk on your way home" } },
        { en: "Don't forget to charge your phone tonight.", bn: "আজ রাতে ফোন চার্জ দিতে ভুলো না।", slotValues: { ACTION: "charge your phone tonight" } },
        { en: "Don't forget to submit the report by Friday.", bn: "শুক্রবারের মধ্যে রিপোর্ট জমা দিতে ভুলো না।", slotValues: { ACTION: "submit the report by Friday" } },
        { en: "Don't forget to turn off the fan before leaving.", bn: "যাওয়ার আগে ফ্যান বন্ধ করতে ভুলো না।", slotValues: { ACTION: "turn off the fan before leaving" } },
        { en: "Don't forget to pick up the kids from school.", bn: "স্কুল থেকে বাচ্চাদের আনতে ভুলো না।", slotValues: { ACTION: "pick up the kids from school" } },
        { en: "Don't forget to wish her a happy birthday.", bn: "তাকে জন্মদিনের শুভেচ্ছা জানাতে ভুলো না।", slotValues: { ACTION: "wish her a happy birthday" } },
        { en: "Don't forget to return the library book.", bn: "লাইব্রেরির বই ফেরত দিতে ভুলো না।", slotValues: { ACTION: "return the library book" } },
        { en: "Don't forget to feed the cat.", bn: "বিড়ালকে খাবার দিতে ভুলো না।", slotValues: { ACTION: "feed the cat" } },
        { en: "Don't forget to update your password.", bn: "তোমার পাসওয়ার্ড আপডেট করতে ভুলো না।", slotValues: { ACTION: "update your password" } },
        { en: "Don't forget to bring the receipt.", bn: "রসিদটা আনতে ভুলো না।", slotValues: { ACTION: "bring the receipt" } },
        { en: "Don't forget to double-check your answers.", bn: "তোমার উত্তরগুলো আবার যাচাই করতে ভুলো না।", slotValues: { ACTION: "double-check your answers" } },
        { en: "Don't forget to take your umbrella.", bn: "তোমার ছাতা নিতে ভুলো না।", slotValues: { ACTION: "take your umbrella" } },
      ],
      formality: "casual",
      difficulty: "beginner",
    },
    {
      id: "Q2.4",
      formula: "Be sure to [ACTION]",
      formula_bn: "নিশ্চিত হও যে [কাজ] করেছ",
      patternName: "Firm Instruction",
      patternName_bn: "দৃঢ় নির্দেশনা",
      slots: [
        { name: "ACTION", description: "Important action to ensure", description_bn: "নিশ্চিত করার গুরুত্বপূর্ণ কাজ", acceptedTypes: ["verb_phrase"], examples: ["read the terms", "keep quiet", "follow up"] },
      ],
      examples: [
        { en: "Be sure to read the terms and conditions.", bn: "নিশ্চিত হও যে শর্তাবলী পড়েছ।", slotValues: { ACTION: "read the terms and conditions" } },
        { en: "Be sure to keep your voice down in the library.", bn: "নিশ্চিত হও যে লাইব্রেরিতে কম আওয়াজ করছ।", slotValues: { ACTION: "keep your voice down in the library" } },
        { en: "Be sure to follow up with the client.", bn: "নিশ্চিত হও যে ক্লায়েন্টের সাথে ফলোআপ করেছ।", slotValues: { ACTION: "follow up with the client" } },
        { en: "Be sure to label all the boxes.", bn: "নিশ্চিত হও যে সব বাক্সে লেবেল লাগিয়েছ।", slotValues: { ACTION: "label all the boxes" } },
        { en: "Be sure to let me know if anything changes.", bn: "নিশ্চিত হও যে কিছু বদলালে আমাকে জানিয়েছ।", slotValues: { ACTION: "let me know if anything changes" } },
        { en: "Be sure to practice before the presentation.", bn: "নিশ্চিত হও যে প্রেজেন্টেশনের আগে অনুশীলন করেছ।", slotValues: { ACTION: "practice before the presentation" } },
        { en: "Be sure to include your contact information.", bn: "নিশ্চিত হও যে তোমার যোগাযোগের তথ্য দিয়েছ।", slotValues: { ACTION: "include your contact information" } },
        { en: "Be sure to clean up after yourself.", bn: "নিশ্চিত হও যে নিজের পরে পরিষ্কার করেছ।", slotValues: { ACTION: "clean up after yourself" } },
        { en: "Be sure to ask questions if you don't understand.", bn: "নিশ্চিত হও যে না বুঝলে প্রশ্ন করেছ।", slotValues: { ACTION: "ask questions if you don't understand" } },
        { en: "Be sure to stretch before exercising.", bn: "নিশ্চিত হও যে ব্যায়ামের আগে স্ট্রেচ করেছ।", slotValues: { ACTION: "stretch before exercising" } },
        { en: "Be sure to close the windows if it rains.", bn: "নিশ্চিত হও যে বৃষ্টি হলে জানালা বন্ধ করেছ।", slotValues: { ACTION: "close the windows if it rains" } },
        { en: "Be sure to test the equipment before the event.", bn: "নিশ্চিত হও যে অনুষ্ঠানের আগে যন্ত্রপাতি পরীক্ষা করেছ।", slotValues: { ACTION: "test the equipment before the event" } },
        { en: "Be sure to confirm the booking.", bn: "নিশ্চিত হও যে বুকিং নিশ্চিত করেছ।", slotValues: { ACTION: "confirm the booking" } },
        { en: "Be sure to eat something before the meeting.", bn: "নিশ্চিত হও যে মিটিংয়ের আগে কিছু খেয়েছ।", slotValues: { ACTION: "eat something before the meeting" } },
        { en: "Be sure to wear the safety helmet.", bn: "নিশ্চিত হও যে নিরাপত্তা হেলমেট পরেছ।", slotValues: { ACTION: "wear the safety helmet" } },
      ],
      formality: "polite",
      difficulty: "beginner",
    },
    {
      id: "Q2.5",
      formula: "After [ACTION], [ACTION]",
      formula_bn: "[কাজ]-এর পরে, [কাজ]",
      patternName: "After-Step Instruction",
      patternName_bn: "পরবর্তী-ধাপ নির্দেশনা",
      slots: [
        { name: "ACTION", description: "Actions in order", description_bn: "ক্রমানুসারে কাজ", acceptedTypes: ["verb_phrase", "gerund"], examples: ["mixing the flour", "you finish", "adding water"] },
      ],
      examples: [
        { en: "After mixing the flour, add the eggs.", bn: "ময়দা মেশানোর পরে, ডিম দাও।", slotValues: { ACTION: "mixing the flour / add the eggs" } },
        { en: "After you finish eating, wash the dishes.", bn: "খাওয়া শেষ করার পরে, থালা ধুয়ে ফেলো।", slotValues: { ACTION: "you finish eating / wash the dishes" } },
        { en: "After adding water, stir the mixture well.", bn: "পানি দেওয়ার পরে, মিশ্রণটা ভালো করে নাড়ো।", slotValues: { ACTION: "adding water / stir the mixture well" } },
        { en: "After turning left, walk for about five minutes.", bn: "বামে ঘোরার পরে, প্রায় পাঁচ মিনিট হাঁটো।", slotValues: { ACTION: "turning left / walk for about five minutes" } },
        { en: "After pressing the button, wait for the light to turn green.", bn: "বোতাম চাপার পরে, সবুজ বাতি জ্বলা পর্যন্ত অপেক্ষা করো।", slotValues: { ACTION: "pressing the button / wait for the light to turn green" } },
        { en: "After logging in, click on settings.", bn: "লগইন করার পরে, সেটিংসে ক্লিক করো।", slotValues: { ACTION: "logging in / click on settings" } },
        { en: "After the paint dries, apply the second coat.", bn: "রং শুকানোর পরে, দ্বিতীয় কোট দাও।", slotValues: { ACTION: "the paint dries / apply the second coat" } },
        { en: "After reviewing the document, send it to the manager.", bn: "ডকুমেন্টটা পর্যালোচনা করার পরে, ম্যানেজারকে পাঠাও।", slotValues: { ACTION: "reviewing the document / send it to the manager" } },
        { en: "After the meeting, update the spreadsheet.", bn: "মিটিংয়ের পরে, স্প্রেডশিট আপডেট করো।", slotValues: { ACTION: "the meeting / update the spreadsheet" } },
        { en: "After cleaning the surface, apply the polish.", bn: "পৃষ্ঠ পরিষ্কার করার পরে, পলিশ লাগাও।", slotValues: { ACTION: "cleaning the surface / apply the polish" } },
        { en: "After ironing the clothes, fold them neatly.", bn: "কাপড় ইস্ত্রি করার পরে, গুছিয়ে ভাঁজ করো।", slotValues: { ACTION: "ironing the clothes / fold them neatly" } },
        { en: "After breakfast, take your vitamins.", bn: "সকালের নাস্তার পরে, ভিটামিন খাও।", slotValues: { ACTION: "breakfast / take your vitamins" } },
        { en: "After downloading the file, extract it.", bn: "ফাইলটি ডাউনলোড করার পরে, এক্সট্র্যাক্ট করো।", slotValues: { ACTION: "downloading the file / extract it" } },
        { en: "After the interview, send a thank-you email.", bn: "ইন্টারভিউয়ের পরে, ধন্যবাদ ইমেইল পাঠাও।", slotValues: { ACTION: "the interview / send a thank-you email" } },
        { en: "After planting the seeds, water them gently.", bn: "বীজ বোনার পরে, আস্তে আস্তে পানি দাও।", slotValues: { ACTION: "planting the seeds / water them gently" } },
      ],
      formality: "casual",
      difficulty: "beginner",
    },
  ],
};
