import { PatternCategory } from "@/types/pattern";

export const categoryQ3: PatternCategory = {
  id: "Q3",
  slug: "orders-commands",
  name: "Orders & Commands",
  name_bn: "আদেশ ও নির্দেশ",
  description: "Give direct orders and commands in English",
  description_bn: "ইংরেজিতে সরাসরি আদেশ ও নির্দেশ দিন",
  icon: "🛑",
  group: "Q",
  groupName: "Advice, Instructions & Commands",
  groupName_bn: "উপদেশ, নির্দেশনা ও আদেশ",
  difficulty: "beginner",
  patterns: [
    {
      id: "Q3.1",
      formula: "[ACTION]!",
      formula_bn: "[কাজ] করো!",
      patternName: "Direct Command",
      patternName_bn: "সরাসরি আদেশ",
      slots: [
        { name: "ACTION", description: "Urgent imperative action", description_bn: "জরুরি আদেশমূলক কাজ", acceptedTypes: ["verb_phrase"], examples: ["stop", "wait", "hurry up"] },
      ],
      examples: [
        { en: "Stop!", bn: "থামো!", slotValues: { ACTION: "stop" } },
        { en: "Wait!", bn: "দাঁড়াও!", slotValues: { ACTION: "wait" } },
        { en: "Hurry up!", bn: "তাড়াতাড়ি করো!", slotValues: { ACTION: "hurry up" } },
        { en: "Listen carefully!", bn: "মনোযোগ দিয়ে শোনো!", slotValues: { ACTION: "listen carefully" } },
        { en: "Sit down!", bn: "বসো!", slotValues: { ACTION: "sit down" } },
        { en: "Stand up!", bn: "দাঁড়াও!", slotValues: { ACTION: "stand up" } },
        { en: "Come here!", bn: "এখানে এসো!", slotValues: { ACTION: "come here" } },
        { en: "Be quiet!", bn: "চুপ করো!", slotValues: { ACTION: "be quiet" } },
        { en: "Open the door!", bn: "দরজা খোলো!", slotValues: { ACTION: "open the door" } },
        { en: "Close the window!", bn: "জানালা বন্ধ করো!", slotValues: { ACTION: "close the window" } },
        { en: "Look out!", bn: "সাবধান!", slotValues: { ACTION: "look out" } },
        { en: "Run!", bn: "দৌড়াও!", slotValues: { ACTION: "run" } },
        { en: "Get up!", bn: "উঠো!", slotValues: { ACTION: "get up" } },
        { en: "Move aside!", bn: "পাশে সরো!", slotValues: { ACTION: "move aside" } },
        { en: "Pay attention!", bn: "মনোযোগ দাও!", slotValues: { ACTION: "pay attention" } },
      ],
      formality: "casual",
      difficulty: "beginner",
    },
    {
      id: "Q3.2",
      formula: "Don't [ACTION]!",
      formula_bn: "[কাজ] করো না!",
      patternName: "Negative Command",
      patternName_bn: "নেতিবাচক আদেশ",
      slots: [
        { name: "ACTION", description: "Prohibited action", description_bn: "নিষিদ্ধ কাজ", acceptedTypes: ["verb_phrase"], examples: ["touch that", "move", "be late"] },
      ],
      examples: [
        { en: "Don't touch that!", bn: "ওটা ধরো না!", slotValues: { ACTION: "touch that" } },
        { en: "Don't move!", bn: "নড়ো না!", slotValues: { ACTION: "move" } },
        { en: "Don't be late!", bn: "দেরি করো না!", slotValues: { ACTION: "be late" } },
        { en: "Don't forget your keys!", bn: "তোমার চাবি ভুলো না!", slotValues: { ACTION: "forget your keys" } },
        { en: "Don't talk during the exam!", bn: "পরীক্ষার সময় কথা বলো না!", slotValues: { ACTION: "talk during the exam" } },
        { en: "Don't run in the hallway!", bn: "করিডরে দৌড়ো না!", slotValues: { ACTION: "run in the hallway" } },
        { en: "Don't eat with your mouth open!", bn: "মুখ খোলা রেখে খেও না!", slotValues: { ACTION: "eat with your mouth open" } },
        { en: "Don't worry about it!", bn: "এটা নিয়ে চিন্তা করো না!", slotValues: { ACTION: "worry about it" } },
        { en: "Don't tell anyone!", bn: "কাউকে বলো না!", slotValues: { ACTION: "tell anyone" } },
        { en: "Don't slam the door!", bn: "দরজা জোরে বন্ধ করো না!", slotValues: { ACTION: "slam the door" } },
        { en: "Don't give up!", bn: "হাল ছেড়ো না!", slotValues: { ACTION: "give up" } },
        { en: "Don't cross the street without looking!", bn: "না দেখে রাস্তা পার হোও না!", slotValues: { ACTION: "cross the street without looking" } },
        { en: "Don't interrupt me!", bn: "আমাকে থামিও না!", slotValues: { ACTION: "interrupt me" } },
        { en: "Don't use your phone in class!", bn: "ক্লাসে ফোন ব্যবহার করো না!", slotValues: { ACTION: "use your phone in class" } },
        { en: "Don't throw garbage on the floor!", bn: "মেঝেতে ময়লা ফেলো না!", slotValues: { ACTION: "throw garbage on the floor" } },
      ],
      formality: "casual",
      difficulty: "beginner",
    },
    {
      id: "Q3.3",
      formula: "Please [ACTION]",
      formula_bn: "দয়া করে [কাজ] করুন",
      patternName: "Polite Command",
      patternName_bn: "ভদ্র আদেশ",
      slots: [
        { name: "ACTION", description: "Politely requested action", description_bn: "ভদ্রভাবে অনুরোধকৃত কাজ", acceptedTypes: ["verb_phrase"], examples: ["sit down", "be on time", "close the door"] },
      ],
      examples: [
        { en: "Please sit down.", bn: "দয়া করে বসুন।", slotValues: { ACTION: "sit down" } },
        { en: "Please be on time for the meeting.", bn: "দয়া করে মিটিংয়ে সময়মতো আসুন।", slotValues: { ACTION: "be on time for the meeting" } },
        { en: "Please close the door behind you.", bn: "দয়া করে আপনার পিছনে দরজা বন্ধ করুন।", slotValues: { ACTION: "close the door behind you" } },
        { en: "Please wait in the lobby.", bn: "দয়া করে লবিতে অপেক্ষা করুন।", slotValues: { ACTION: "wait in the lobby" } },
        { en: "Please hand in your assignment.", bn: "দয়া করে আপনার অ্যাসাইনমেন্ট জমা দিন।", slotValues: { ACTION: "hand in your assignment" } },
        { en: "Please speak slowly.", bn: "দয়া করে ধীরে কথা বলুন।", slotValues: { ACTION: "speak slowly" } },
        { en: "Please fill in this form.", bn: "দয়া করে এই ফর্মটি পূরণ করুন।", slotValues: { ACTION: "fill in this form" } },
        { en: "Please keep your voice down.", bn: "দয়া করে আস্তে কথা বলুন।", slotValues: { ACTION: "keep your voice down" } },
        { en: "Please turn off your mobile phones.", bn: "দয়া করে আপনাদের মোবাইল ফোন বন্ধ করুন।", slotValues: { ACTION: "turn off your mobile phones" } },
        { en: "Please line up in an orderly fashion.", bn: "দয়া করে সুশৃঙ্খলভাবে লাইনে দাঁড়ান।", slotValues: { ACTION: "line up in an orderly fashion" } },
        { en: "Please take a seat.", bn: "দয়া করে আসন নিন।", slotValues: { ACTION: "take a seat" } },
        { en: "Please show me your ticket.", bn: "দয়া করে আপনার টিকিট দেখান।", slotValues: { ACTION: "show me your ticket" } },
        { en: "Please send me the report by email.", bn: "দয়া করে আমাকে ইমেইলে রিপোর্টটি পাঠান।", slotValues: { ACTION: "send me the report by email" } },
        { en: "Please leave your shoes at the door.", bn: "দয়া করে দরজায় আপনার জুতো রাখুন।", slotValues: { ACTION: "leave your shoes at the door" } },
        { en: "Please make sure everything is ready.", bn: "দয়া করে নিশ্চিত করুন সবকিছু প্রস্তুত।", slotValues: { ACTION: "make sure everything is ready" } },
      ],
      formality: "polite",
      difficulty: "beginner",
    },
    {
      id: "Q3.4",
      formula: "I need you to [ACTION]",
      formula_bn: "আমার দরকার তুমি [কাজ] করো",
      patternName: "Firm Request",
      patternName_bn: "দৃঢ় অনুরোধ",
      slots: [
        { name: "ACTION", description: "Required action", description_bn: "প্রয়োজনীয় কাজ", acceptedTypes: ["verb_phrase"], examples: ["finish this", "stay focused", "help me"] },
      ],
      examples: [
        { en: "I need you to finish this by tomorrow.", bn: "আমার দরকার তুমি কাল এর মধ্যে এটা শেষ করো।", slotValues: { ACTION: "finish this by tomorrow" } },
        { en: "I need you to stay focused.", bn: "আমার দরকার তুমি মনোযোগী থাকো।", slotValues: { ACTION: "stay focused" } },
        { en: "I need you to help me with this project.", bn: "আমার দরকার তুমি এই প্রকল্পে আমাকে সাহায্য করো।", slotValues: { ACTION: "help me with this project" } },
        { en: "I need you to clean your room right now.", bn: "আমার দরকার তুমি এখনই তোমার ঘর পরিষ্কার করো।", slotValues: { ACTION: "clean your room right now" } },
        { en: "I need you to listen to what I'm saying.", bn: "আমার দরকার তুমি আমার কথা শোনো।", slotValues: { ACTION: "listen to what I'm saying" } },
        { en: "I need you to be more responsible.", bn: "আমার দরকার তুমি আরও দায়িত্বশীল হও।", slotValues: { ACTION: "be more responsible" } },
        { en: "I need you to send the documents today.", bn: "আমার দরকার তুমি আজই কাগজপত্র পাঠাও।", slotValues: { ACTION: "send the documents today" } },
        { en: "I need you to call the supplier.", bn: "আমার দরকার তুমি সরবরাহকারীকে ফোন করো।", slotValues: { ACTION: "call the supplier" } },
        { en: "I need you to explain this clearly.", bn: "আমার দরকার তুমি এটা পরিষ্কারভাবে ব্যাখ্যা করো।", slotValues: { ACTION: "explain this clearly" } },
        { en: "I need you to work overtime today.", bn: "আমার দরকার তুমি আজ ওভারটাইম কাজ করো।", slotValues: { ACTION: "work overtime today" } },
        { en: "I need you to prepare the presentation.", bn: "আমার দরকার তুমি প্রেজেন্টেশন তৈরি করো।", slotValues: { ACTION: "prepare the presentation" } },
        { en: "I need you to take this seriously.", bn: "আমার দরকার তুমি এটা গুরুত্বের সাথে নাও।", slotValues: { ACTION: "take this seriously" } },
        { en: "I need you to wait here for five minutes.", bn: "আমার দরকার তুমি পাঁচ মিনিট এখানে অপেক্ষা করো।", slotValues: { ACTION: "wait here for five minutes" } },
        { en: "I need you to double-check the numbers.", bn: "আমার দরকার তুমি সংখ্যাগুলো আবার যাচাই করো।", slotValues: { ACTION: "double-check the numbers" } },
        { en: "I need you to be quiet during the ceremony.", bn: "আমার দরকার তুমি অনুষ্ঠানের সময় চুপ থাকো।", slotValues: { ACTION: "be quiet during the ceremony" } },
      ],
      formality: "casual",
      difficulty: "intermediate",
    },
    {
      id: "Q3.5",
      formula: "Stop [DOING]!",
      formula_bn: "[করা] বন্ধ করো!",
      patternName: "Stop Command",
      patternName_bn: "বন্ধ করার আদেশ",
      slots: [
        { name: "DOING", description: "Action to stop (gerund)", description_bn: "বন্ধ করার কাজ (gerund)", acceptedTypes: ["gerund"], examples: ["talking", "running", "making noise"] },
      ],
      examples: [
        { en: "Stop talking and listen!", bn: "কথা বলা বন্ধ করো এবং শোনো!", slotValues: { DOING: "talking" } },
        { en: "Stop running in the house!", bn: "ঘরের মধ্যে দৌড়ানো বন্ধ করো!", slotValues: { DOING: "running in the house" } },
        { en: "Stop making so much noise!", bn: "এত শব্দ করা বন্ধ করো!", slotValues: { DOING: "making so much noise" } },
        { en: "Stop wasting time!", bn: "সময় নষ্ট করা বন্ধ করো!", slotValues: { DOING: "wasting time" } },
        { en: "Stop complaining about everything!", bn: "সবকিছু নিয়ে অভিযোগ করা বন্ধ করো!", slotValues: { DOING: "complaining about everything" } },
        { en: "Stop eating junk food!", bn: "জাঙ্ক ফুড খাওয়া বন্ধ করো!", slotValues: { DOING: "eating junk food" } },
        { en: "Stop staring at your phone!", bn: "ফোনের দিকে তাকিয়ে থাকা বন্ধ করো!", slotValues: { DOING: "staring at your phone" } },
        { en: "Stop fighting with your brother!", bn: "তোমার ভাইয়ের সাথে মারামারি করা বন্ধ করো!", slotValues: { DOING: "fighting with your brother" } },
        { en: "Stop worrying about things you can't control!", bn: "যা নিয়ন্ত্রণ করতে পারো না তা নিয়ে চিন্তা করা বন্ধ করো!", slotValues: { DOING: "worrying about things you can't control" } },
        { en: "Stop being so negative!", bn: "এত নেতিবাচক হওয়া বন্ধ করো!", slotValues: { DOING: "being so negative" } },
        { en: "Stop ignoring my calls!", bn: "আমার ফোন উপেক্ষা করা বন্ধ করো!", slotValues: { DOING: "ignoring my calls" } },
        { en: "Stop playing games during class!", bn: "ক্লাসের সময় গেম খেলা বন্ধ করো!", slotValues: { DOING: "playing games during class" } },
        { en: "Stop throwing things around!", bn: "জিনিসপত্র ছুঁড়ে ফেলা বন্ধ করো!", slotValues: { DOING: "throwing things around" } },
        { en: "Stop being lazy and do your homework!", bn: "অলস হওয়া বন্ধ করো এবং হোমওয়ার্ক করো!", slotValues: { DOING: "being lazy" } },
        { en: "Stop interrupting when I'm speaking!", bn: "আমি কথা বলার সময় বাধা দেওয়া বন্ধ করো!", slotValues: { DOING: "interrupting when I'm speaking" } },
      ],
      formality: "casual",
      difficulty: "beginner",
    },
  ],
};
