import { PatternCategory } from "@/types/pattern";

export const categoryQ4: PatternCategory = {
  id: "Q4",
  slug: "making-rules",
  name: "Making Rules",
  name_bn: "নিয়ম তৈরি করা",
  description: "Express rules, restrictions and regulations",
  description_bn: "নিয়ম, বিধিনিষেধ ও প্রবিধান প্রকাশ করুন",
  icon: "📜",
  group: "Q",
  groupName: "Advice, Instructions & Commands",
  groupName_bn: "উপদেশ, নির্দেশনা ও আদেশ",
  difficulty: "intermediate",
  patterns: [
    {
      id: "Q4.1",
      formula: "You must [ACTION]",
      formula_bn: "তোমাকে অবশ্যই [কাজ] করতে হবে",
      patternName: "Obligation with Must",
      patternName_bn: "Must দিয়ে বাধ্যবাধকতা",
      slots: [
        { name: "ACTION", description: "Required action", description_bn: "বাধ্যতামূলক কাজ", acceptedTypes: ["verb_phrase"], examples: ["wear a seatbelt", "follow the rules", "pay the fine"] },
      ],
      examples: [
        { en: "You must wear a seatbelt in the car.", bn: "তোমাকে অবশ্যই গাড়িতে সিটবেল্ট পরতে হবে।", slotValues: { ACTION: "wear a seatbelt in the car" } },
        { en: "You must follow the rules.", bn: "তোমাকে অবশ্যই নিয়ম মানতে হবে।", slotValues: { ACTION: "follow the rules" } },
        { en: "You must pay the fine within thirty days.", bn: "তোমাকে অবশ্যই ত্রিশ দিনের মধ্যে জরিমানা দিতে হবে।", slotValues: { ACTION: "pay the fine within thirty days" } },
        { en: "You must show your ID at the entrance.", bn: "তোমাকে অবশ্যই প্রবেশদ্বারে আইডি দেখাতে হবে।", slotValues: { ACTION: "show your ID at the entrance" } },
        { en: "You must arrive before eight o'clock.", bn: "তোমাকে অবশ্যই আটটার আগে পৌঁছাতে হবে।", slotValues: { ACTION: "arrive before eight o'clock" } },
        { en: "You must complete the training program.", bn: "তোমাকে অবশ্যই প্রশিক্ষণ কার্যক্রম সম্পন্ন করতে হবে।", slotValues: { ACTION: "complete the training program" } },
        { en: "You must report any suspicious activity.", bn: "তোমাকে অবশ্যই যেকোনো সন্দেহজনক কার্যকলাপ রিপোর্ট করতে হবে।", slotValues: { ACTION: "report any suspicious activity" } },
        { en: "You must keep your password confidential.", bn: "তোমাকে অবশ্যই তোমার পাসওয়ার্ড গোপন রাখতে হবে।", slotValues: { ACTION: "keep your password confidential" } },
        { en: "You must wear a helmet while riding a bike.", bn: "তোমাকে অবশ্যই বাইক চালানোর সময় হেলমেট পরতে হবে।", slotValues: { ACTION: "wear a helmet while riding a bike" } },
        { en: "You must submit the application before the deadline.", bn: "তোমাকে অবশ্যই সময়সীমার আগে আবেদন জমা দিতে হবে।", slotValues: { ACTION: "submit the application before the deadline" } },
        { en: "You must attend all mandatory classes.", bn: "তোমাকে অবশ্যই সব বাধ্যতামূলক ক্লাসে উপস্থিত থাকতে হবে।", slotValues: { ACTION: "attend all mandatory classes" } },
        { en: "You must get permission from the principal.", bn: "তোমাকে অবশ্যই প্রধান শিক্ষকের অনুমতি নিতে হবে।", slotValues: { ACTION: "get permission from the principal" } },
        { en: "You must return the equipment by five PM.", bn: "তোমাকে অবশ্যই বিকাল পাঁচটার মধ্যে সরঞ্জাম ফেরত দিতে হবে।", slotValues: { ACTION: "return the equipment by five PM" } },
        { en: "You must be at least eighteen to enter.", bn: "ঢুকতে হলে তোমাকে অবশ্যই কমপক্ষে আঠারো বছর হতে হবে।", slotValues: { ACTION: "be at least eighteen to enter" } },
        { en: "You must wash your hands before handling food.", bn: "তোমাকে অবশ্যই খাবার ধরার আগে হাত ধুতে হবে।", slotValues: { ACTION: "wash your hands before handling food" } },
      ],
      formality: "polite",
      difficulty: "intermediate",
    },
    {
      id: "Q4.2",
      formula: "[DOING] is not allowed",
      formula_bn: "[করা] অনুমোদিত নয়",
      patternName: "Prohibition Statement",
      patternName_bn: "নিষেধাজ্ঞা বিবৃতি",
      slots: [
        { name: "DOING", description: "Prohibited activity", description_bn: "নিষিদ্ধ কার্যকলাপ", acceptedTypes: ["gerund"], examples: ["smoking", "parking", "running"] },
      ],
      examples: [
        { en: "Smoking is not allowed inside the building.", bn: "ভবনের ভিতরে ধূমপান অনুমোদিত নয়।", slotValues: { DOING: "smoking" } },
        { en: "Parking is not allowed on this street.", bn: "এই রাস্তায় পার্কিং অনুমোদিত নয়।", slotValues: { DOING: "parking" } },
        { en: "Running is not allowed near the pool.", bn: "পুলের কাছে দৌড়ানো অনুমোদিত নয়।", slotValues: { DOING: "running" } },
        { en: "Photography is not allowed in the museum.", bn: "জাদুঘরে ছবি তোলা অনুমোদিত নয়।", slotValues: { DOING: "photography" } },
        { en: "Eating is not allowed in the laboratory.", bn: "ল্যাবরেটরিতে খাওয়া অনুমোদিত নয়।", slotValues: { DOING: "eating" } },
        { en: "Using mobile phones is not allowed during class.", bn: "ক্লাসের সময় মোবাইল ফোন ব্যবহার অনুমোদিত নয়।", slotValues: { DOING: "using mobile phones" } },
        { en: "Cheating is not allowed in any exam.", bn: "কোনো পরীক্ষায় নকল করা অনুমোদিত নয়।", slotValues: { DOING: "cheating" } },
        { en: "Feeding the animals is not allowed in the zoo.", bn: "চিড়িয়াখানায় পশুদের খাওয়ানো অনুমোদিত নয়।", slotValues: { DOING: "feeding the animals" } },
        { en: "Littering is not allowed on the beach.", bn: "সমুদ্র সৈকতে ময়লা ফেলা অনুমোদিত নয়।", slotValues: { DOING: "littering" } },
        { en: "Swimming is not allowed after sunset.", bn: "সূর্যাস্তের পরে সাঁতার কাটা অনুমোদিত নয়।", slotValues: { DOING: "swimming" } },
        { en: "Talking loudly is not allowed in the hospital.", bn: "হাসপাতালে জোরে কথা বলা অনুমোদিত নয়।", slotValues: { DOING: "talking loudly" } },
        { en: "Bringing pets is not allowed in the restaurant.", bn: "রেস্তোরাঁয় পোষা প্রাণী আনা অনুমোদিত নয়।", slotValues: { DOING: "bringing pets" } },
        { en: "Copying homework is not allowed.", bn: "হোমওয়ার্ক কপি করা অনুমোদিত নয়।", slotValues: { DOING: "copying homework" } },
        { en: "Recording the lecture is not allowed.", bn: "লেকচার রেকর্ড করা অনুমোদিত নয়।", slotValues: { DOING: "recording the lecture" } },
        { en: "Wearing casual clothes is not allowed in the office.", bn: "অফিসে ক্যাজুয়াল পোশাক পরা অনুমোদিত নয়।", slotValues: { DOING: "wearing casual clothes" } },
      ],
      formality: "formal",
      difficulty: "intermediate",
    },
    {
      id: "Q4.3",
      formula: "No [DOING] in [PLACE]",
      formula_bn: "[জায়গায়] [করা] নিষেধ",
      patternName: "No + Gerund Rule",
      patternName_bn: "No + Gerund নিয়ম",
      slots: [
        { name: "DOING", description: "Prohibited activity", description_bn: "নিষিদ্ধ কার্যকলাপ", acceptedTypes: ["gerund"], examples: ["smoking", "running", "eating"] },
        { name: "PLACE", description: "Location of the rule", description_bn: "নিয়মের স্থান", acceptedTypes: ["place"], examples: ["the library", "this area", "the classroom"] },
      ],
      examples: [
        { en: "No smoking in the restaurant.", bn: "রেস্তোরাঁয় ধূমপান নিষেধ।", slotValues: { DOING: "smoking", PLACE: "the restaurant" } },
        { en: "No running in the hallway.", bn: "করিডরে দৌড়ানো নিষেধ।", slotValues: { DOING: "running", PLACE: "the hallway" } },
        { en: "No eating in the library.", bn: "লাইব্রেরিতে খাওয়া নিষেধ।", slotValues: { DOING: "eating", PLACE: "the library" } },
        { en: "No talking in the examination hall.", bn: "পরীক্ষার হলে কথা বলা নিষেধ।", slotValues: { DOING: "talking", PLACE: "the examination hall" } },
        { en: "No swimming in this pond.", bn: "এই পুকুরে সাঁতার কাটা নিষেধ।", slotValues: { DOING: "swimming", PLACE: "this pond" } },
        { en: "No parking in front of the gate.", bn: "গেটের সামনে পার্কিং নিষেধ।", slotValues: { DOING: "parking", PLACE: "front of the gate" } },
        { en: "No playing in the construction site.", bn: "নির্মাণস্থলে খেলা নিষেধ।", slotValues: { DOING: "playing", PLACE: "the construction site" } },
        { en: "No fishing in the reservoir.", bn: "জলাধারে মাছ ধরা নিষেধ।", slotValues: { DOING: "fishing", PLACE: "the reservoir" } },
        { en: "No littering in the park.", bn: "পার্কে ময়লা ফেলা নিষেধ।", slotValues: { DOING: "littering", PLACE: "the park" } },
        { en: "No trespassing on private property.", bn: "ব্যক্তিগত সম্পত্তিতে অনুপ্রবেশ নিষেধ।", slotValues: { DOING: "trespassing", PLACE: "private property" } },
        { en: "No drinking in the mosque.", bn: "মসজিদে পানীয় পান করা নিষেধ।", slotValues: { DOING: "drinking", PLACE: "the mosque" } },
        { en: "No photography in this gallery.", bn: "এই গ্যালারিতে ছবি তোলা নিষেধ।", slotValues: { DOING: "photography", PLACE: "this gallery" } },
        { en: "No shouting in the hospital.", bn: "হাসপাতালে চিৎকার করা নিষেধ।", slotValues: { DOING: "shouting", PLACE: "the hospital" } },
        { en: "No cycling in the pedestrian zone.", bn: "পথচারী এলাকায় সাইকেল চালানো নিষেধ।", slotValues: { DOING: "cycling", PLACE: "the pedestrian zone" } },
        { en: "No camping in the national forest.", bn: "জাতীয় বনে ক্যাম্পিং করা নিষেধ।", slotValues: { DOING: "camping", PLACE: "the national forest" } },
      ],
      formality: "formal",
      difficulty: "beginner",
    },
    {
      id: "Q4.4",
      formula: "You are not supposed to [ACTION]",
      formula_bn: "তোমার [কাজ] করার কথা নয়",
      patternName: "Expectation-Based Rule",
      patternName_bn: "প্রত্যাশাভিত্তিক নিয়ম",
      slots: [
        { name: "ACTION", description: "Action against expectations", description_bn: "প্রত্যাশার বিরুদ্ধে কাজ", acceptedTypes: ["verb_phrase"], examples: ["be here", "use that", "share your password"] },
      ],
      examples: [
        { en: "You are not supposed to be here after hours.", bn: "কর্মঘণ্টার পরে তোমার এখানে থাকার কথা নয়।", slotValues: { ACTION: "be here after hours" } },
        { en: "You are not supposed to use the elevator during a fire.", bn: "আগুনের সময় তোমার লিফট ব্যবহার করার কথা নয়।", slotValues: { ACTION: "use the elevator during a fire" } },
        { en: "You are not supposed to share your password with anyone.", bn: "তোমার কারো সাথে পাসওয়ার্ড শেয়ার করার কথা নয়।", slotValues: { ACTION: "share your password with anyone" } },
        { en: "You are not supposed to enter without permission.", bn: "তোমার অনুমতি ছাড়া ঢোকার কথা নয়।", slotValues: { ACTION: "enter without permission" } },
        { en: "You are not supposed to talk to strangers.", bn: "তোমার অপরিচিতদের সাথে কথা বলার কথা নয়।", slotValues: { ACTION: "talk to strangers" } },
        { en: "You are not supposed to leave early.", bn: "তোমার তাড়াতাড়ি যাওয়ার কথা নয়।", slotValues: { ACTION: "leave early" } },
        { en: "You are not supposed to park in the disabled spot.", bn: "তোমার প্রতিবন্ধী স্থানে পার্ক করার কথা নয়।", slotValues: { ACTION: "park in the disabled spot" } },
        { en: "You are not supposed to bring food into the lab.", bn: "তোমার ল্যাবে খাবার আনার কথা নয়।", slotValues: { ACTION: "bring food into the lab" } },
        { en: "You are not supposed to wear shoes indoors.", bn: "তোমার ভিতরে জুতো পরার কথা নয়।", slotValues: { ACTION: "wear shoes indoors" } },
        { en: "You are not supposed to start before the signal.", bn: "তোমার সংকেতের আগে শুরু করার কথা নয়।", slotValues: { ACTION: "start before the signal" } },
        { en: "You are not supposed to discuss the exam questions.", bn: "তোমার পরীক্ষার প্রশ্ন নিয়ে আলোচনা করার কথা নয়।", slotValues: { ACTION: "discuss the exam questions" } },
        { en: "You are not supposed to use your phone while driving.", bn: "গাড়ি চালানোর সময় তোমার ফোন ব্যবহার করার কথা নয়।", slotValues: { ACTION: "use your phone while driving" } },
        { en: "You are not supposed to open other people's mail.", bn: "তোমার অন্যদের চিঠি খোলার কথা নয়।", slotValues: { ACTION: "open other people's mail" } },
        { en: "You are not supposed to feed wildlife in the park.", bn: "তোমার পার্কে বন্যপ্রাণীকে খাওয়ানোর কথা নয়।", slotValues: { ACTION: "feed wildlife in the park" } },
        { en: "You are not supposed to make personal calls at work.", bn: "তোমার কর্মক্ষেত্রে ব্যক্তিগত ফোন করার কথা নয়।", slotValues: { ACTION: "make personal calls at work" } },
      ],
      formality: "polite",
      difficulty: "intermediate",
    },
    {
      id: "Q4.5",
      formula: "It is required that [CLAUSE]",
      formula_bn: "এটা আবশ্যক যে [বাক্যাংশ]",
      patternName: "Formal Requirement",
      patternName_bn: "আনুষ্ঠানিক প্রয়োজনীয়তা",
      slots: [
        { name: "CLAUSE", description: "Required condition", description_bn: "আবশ্যক শর্ত", acceptedTypes: ["clause"], examples: ["all students attend", "visitors sign in", "masks be worn"] },
      ],
      examples: [
        { en: "It is required that all students attend the orientation.", bn: "এটা আবশ্যক যে সব শিক্ষার্থী ওরিয়েন্টেশনে উপস্থিত থাকবে।", slotValues: { CLAUSE: "all students attend the orientation" } },
        { en: "It is required that visitors sign in at the front desk.", bn: "এটা আবশ্যক যে দর্শনার্থীরা সামনের ডেস্কে সাইন ইন করবে।", slotValues: { CLAUSE: "visitors sign in at the front desk" } },
        { en: "It is required that all employees wear uniforms.", bn: "এটা আবশ্যক যে সব কর্মচারী ইউনিফর্ম পরবে।", slotValues: { CLAUSE: "all employees wear uniforms" } },
        { en: "It is required that passengers show valid identification.", bn: "এটা আবশ্যক যে যাত্রীরা বৈধ পরিচয়পত্র দেখাবে।", slotValues: { CLAUSE: "passengers show valid identification" } },
        { en: "It is required that assignments be submitted on time.", bn: "এটা আবশ্যক যে অ্যাসাইনমেন্ট সময়মতো জমা দেওয়া হবে।", slotValues: { CLAUSE: "assignments be submitted on time" } },
        { en: "It is required that all food handlers wash their hands.", bn: "এটা আবশ্যক যে সব খাদ্য পরিচালক হাত ধোবে।", slotValues: { CLAUSE: "all food handlers wash their hands" } },
        { en: "It is required that safety gear be worn at all times.", bn: "এটা আবশ্যক যে সর্বদা নিরাপত্তা সরঞ্জাম পরা থাকবে।", slotValues: { CLAUSE: "safety gear be worn at all times" } },
        { en: "It is required that candidates pass a background check.", bn: "এটা আবশ্যক যে প্রার্থীরা ব্যাকগ্রাউন্ড চেকে পাস করবে।", slotValues: { CLAUSE: "candidates pass a background check" } },
        { en: "It is required that vehicles undergo annual inspection.", bn: "এটা আবশ্যক যে যানবাহন বার্ষিক পরিদর্শনে যাবে।", slotValues: { CLAUSE: "vehicles undergo annual inspection" } },
        { en: "It is required that members pay their dues monthly.", bn: "এটা আবশ্যক যে সদস্যরা মাসিক পাওনা পরিশোধ করবে।", slotValues: { CLAUSE: "members pay their dues monthly" } },
        { en: "It is required that all residents follow the building rules.", bn: "এটা আবশ্যক যে সব বাসিন্দা ভবনের নিয়ম মানবে।", slotValues: { CLAUSE: "all residents follow the building rules" } },
        { en: "It is required that children be accompanied by an adult.", bn: "এটা আবশ্যক যে শিশুদের সাথে একজন প্রাপ্তবয়স্ক থাকবে।", slotValues: { CLAUSE: "children be accompanied by an adult" } },
        { en: "It is required that applications be filled out completely.", bn: "এটা আবশ্যক যে আবেদনপত্র সম্পূর্ণভাবে পূরণ করা হবে।", slotValues: { CLAUSE: "applications be filled out completely" } },
        { en: "It is required that all exits remain clear.", bn: "এটা আবশ্যক যে সব বের হওয়ার পথ পরিষ্কার থাকবে।", slotValues: { CLAUSE: "all exits remain clear" } },
        { en: "It is required that noise be kept to a minimum after ten PM.", bn: "এটা আবশ্যক যে রাত দশটার পরে শব্দ কমিয়ে রাখা হবে।", slotValues: { CLAUSE: "noise be kept to a minimum after ten PM" } },
      ],
      formality: "formal",
      difficulty: "intermediate",
    },
  ],
};
