import { PatternCategory } from "@/types/pattern";

export const categoryQ5: PatternCategory = {
  id: "Q5",
  slug: "giving-permission",
  name: "Giving Permission",
  name_bn: "অনুমতি দেওয়া",
  description: "Learn how to give permission in various ways",
  description_bn: "বিভিন্নভাবে অনুমতি দেওয়া শিখুন",
  icon: "👍",
  group: "Q",
  groupName: "Advice, Instructions & Commands",
  groupName_bn: "উপদেশ, নির্দেশনা ও আদেশ",
  difficulty: "beginner",
  patterns: [
    {
      id: "Q5.1",
      formula: "You can [ACTION]",
      formula_bn: "তুমি [কাজ] করতে পারো",
      patternName: "Simple Permission",
      patternName_bn: "সাধারণ অনুমতি",
      slots: [
        { name: "ACTION", description: "Permitted action", description_bn: "অনুমোদিত কাজ", acceptedTypes: ["verb_phrase"], examples: ["sit here", "use my phone", "go now"] },
      ],
      examples: [
        { en: "You can sit here if you want.", bn: "তুমি চাইলে এখানে বসতে পারো।", slotValues: { ACTION: "sit here if you want" } },
        { en: "You can use my phone to make a call.", bn: "তুমি আমার ফোন ব্যবহার করে ফোন করতে পারো।", slotValues: { ACTION: "use my phone to make a call" } },
        { en: "You can go home early today.", bn: "তুমি আজ তাড়াতাড়ি বাড়ি যেতে পারো।", slotValues: { ACTION: "go home early today" } },
        { en: "You can take as long as you need.", bn: "তুমি যত সময় দরকার নিতে পারো।", slotValues: { ACTION: "take as long as you need" } },
        { en: "You can borrow my car this weekend.", bn: "তুমি এই সপ্তাহান্তে আমার গাড়ি ধার নিতে পারো।", slotValues: { ACTION: "borrow my car this weekend" } },
        { en: "You can park in the guest parking lot.", bn: "তুমি অতিথি পার্কিং লটে পার্ক করতে পারো।", slotValues: { ACTION: "park in the guest parking lot" } },
        { en: "You can bring a friend to the party.", bn: "তুমি পার্টিতে একজন বন্ধু আনতে পারো।", slotValues: { ACTION: "bring a friend to the party" } },
        { en: "You can start the exam now.", bn: "তুমি এখন পরীক্ষা শুরু করতে পারো।", slotValues: { ACTION: "start the exam now" } },
        { en: "You can leave your bag here.", bn: "তুমি তোমার ব্যাগ এখানে রাখতে পারো।", slotValues: { ACTION: "leave your bag here" } },
        { en: "You can eat in the break room.", bn: "তুমি ব্রেক রুমে খেতে পারো।", slotValues: { ACTION: "eat in the break room" } },
        { en: "You can choose any topic for the essay.", bn: "তুমি রচনার জন্য যেকোনো বিষয় বেছে নিতে পারো।", slotValues: { ACTION: "choose any topic for the essay" } },
        { en: "You can ask me anything.", bn: "তুমি আমাকে যেকোনো কিছু জিজ্ঞেস করতে পারো।", slotValues: { ACTION: "ask me anything" } },
        { en: "You can use the pool after three PM.", bn: "তুমি বিকাল তিনটার পরে পুল ব্যবহার করতে পারো।", slotValues: { ACTION: "use the pool after three PM" } },
        { en: "You can keep the change.", bn: "তুমি বাকি টাকাটা রেখে দিতে পারো।", slotValues: { ACTION: "keep the change" } },
        { en: "You can come to the office any time tomorrow.", bn: "তুমি কাল যেকোনো সময় অফিসে আসতে পারো।", slotValues: { ACTION: "come to the office any time tomorrow" } },
      ],
      formality: "casual",
      difficulty: "beginner",
    },
    {
      id: "Q5.2",
      formula: "Go ahead and [ACTION]",
      formula_bn: "এগিয়ে যাও এবং [কাজ] করো",
      patternName: "Encouraging Permission",
      patternName_bn: "উৎসাহমূলক অনুমতি",
      slots: [
        { name: "ACTION", description: "Action being permitted", description_bn: "যে কাজে অনুমতি দেওয়া হচ্ছে", acceptedTypes: ["verb_phrase"], examples: ["take a break", "open it", "start eating"] },
      ],
      examples: [
        { en: "Go ahead and take a break.", bn: "এগিয়ে যাও এবং বিশ্রাম নাও।", slotValues: { ACTION: "take a break" } },
        { en: "Go ahead and open the present!", bn: "এগিয়ে যাও এবং উপহারটা খোলো!", slotValues: { ACTION: "open the present" } },
        { en: "Go ahead and start eating. Don't wait for me.", bn: "এগিয়ে যাও এবং খাওয়া শুরু করো। আমার জন্য অপেক্ষা করো না।", slotValues: { ACTION: "start eating" } },
        { en: "Go ahead and ask your question.", bn: "এগিয়ে যাও এবং তোমার প্রশ্ন করো।", slotValues: { ACTION: "ask your question" } },
        { en: "Go ahead and try the sample.", bn: "এগিয়ে যাও এবং নমুনাটা খেয়ে দেখো।", slotValues: { ACTION: "try the sample" } },
        { en: "Go ahead and use the conference room.", bn: "এগিয়ে যাও এবং কনফারেন্স রুম ব্যবহার করো।", slotValues: { ACTION: "use the conference room" } },
        { en: "Go ahead and call them right now.", bn: "এগিয়ে যাও এবং এখনই তাদের ফোন করো।", slotValues: { ACTION: "call them right now" } },
        { en: "Go ahead and share your ideas.", bn: "এগিয়ে যাও এবং তোমার আইডিয়াগুলো শেয়ার করো।", slotValues: { ACTION: "share your ideas" } },
        { en: "Go ahead and sign the document.", bn: "এগিয়ে যাও এবং ডকুমেন্টে সাক্ষর করো।", slotValues: { ACTION: "sign the document" } },
        { en: "Go ahead and take a seat anywhere.", bn: "এগিয়ে যাও এবং যেকোনো জায়গায় বসো।", slotValues: { ACTION: "take a seat anywhere" } },
        { en: "Go ahead and order whatever you like.", bn: "এগিয়ে যাও এবং যা ইচ্ছা অর্ডার করো।", slotValues: { ACTION: "order whatever you like" } },
        { en: "Go ahead and invite your friends.", bn: "এগিয়ে যাও এবং তোমার বন্ধুদের আমন্ত্রণ জানাও।", slotValues: { ACTION: "invite your friends" } },
        { en: "Go ahead and turn on the lights.", bn: "এগিয়ে যাও এবং বাতি জ্বালাও।", slotValues: { ACTION: "turn on the lights" } },
        { en: "Go ahead and change the channel.", bn: "এগিয়ে যাও এবং চ্যানেল বদলাও।", slotValues: { ACTION: "change the channel" } },
        { en: "Go ahead and submit your application.", bn: "এগিয়ে যাও এবং তোমার আবেদন জমা দাও।", slotValues: { ACTION: "submit your application" } },
      ],
      formality: "casual",
      difficulty: "beginner",
    },
    {
      id: "Q5.3",
      formula: "Feel free to [ACTION]",
      formula_bn: "নির্দ্বিধায় [কাজ] করুন",
      patternName: "Open Permission",
      patternName_bn: "উন্মুক্ত অনুমতি",
      slots: [
        { name: "ACTION", description: "Action being freely permitted", description_bn: "যে কাজে অবাধ অনুমতি দেওয়া হচ্ছে", acceptedTypes: ["verb_phrase"], examples: ["ask questions", "contact me", "look around"] },
      ],
      examples: [
        { en: "Feel free to ask questions at any time.", bn: "নির্দ্বিধায় যেকোনো সময় প্রশ্ন করুন।", slotValues: { ACTION: "ask questions at any time" } },
        { en: "Feel free to contact me if you need help.", bn: "সাহায্য লাগলে নির্দ্বিধায় আমার সাথে যোগাযোগ করুন।", slotValues: { ACTION: "contact me if you need help" } },
        { en: "Feel free to look around the shop.", bn: "নির্দ্বিধায় দোকানটা ঘুরে দেখুন।", slotValues: { ACTION: "look around the shop" } },
        { en: "Feel free to help yourself to more food.", bn: "নির্দ্বিধায় আরও খাবার নিন।", slotValues: { ACTION: "help yourself to more food" } },
        { en: "Feel free to use the Wi-Fi.", bn: "নির্দ্বিধায় ওয়াই-ফাই ব্যবহার করুন।", slotValues: { ACTION: "use the Wi-Fi" } },
        { en: "Feel free to come and go as you please.", bn: "নির্দ্বিধায় ইচ্ছামতো আসুন এবং যান।", slotValues: { ACTION: "come and go as you please" } },
        { en: "Feel free to take a brochure.", bn: "নির্দ্বিধায় একটা ব্রোশিওর নিন।", slotValues: { ACTION: "take a brochure" } },
        { en: "Feel free to share your feedback.", bn: "নির্দ্বিধায় আপনার মতামত শেয়ার করুন।", slotValues: { ACTION: "share your feedback" } },
        { en: "Feel free to call me anytime.", bn: "নির্দ্বিধায় যেকোনো সময় আমাকে ফোন করুন।", slotValues: { ACTION: "call me anytime" } },
        { en: "Feel free to bring your family.", bn: "নির্দ্বিধায় আপনার পরিবার নিয়ে আসুন।", slotValues: { ACTION: "bring your family" } },
        { en: "Feel free to use my office while I'm away.", bn: "আমি দূরে থাকাকালীন নির্দ্বিধায় আমার অফিস ব্যবহার করুন।", slotValues: { ACTION: "use my office while I'm away" } },
        { en: "Feel free to take notes during the lecture.", bn: "নির্দ্বিধায় লেকচারের সময় নোট নিন।", slotValues: { ACTION: "take notes during the lecture" } },
        { en: "Feel free to drop by whenever you like.", bn: "নির্দ্বিধায় যখন ইচ্ছা আসুন।", slotValues: { ACTION: "drop by whenever you like" } },
        { en: "Feel free to express your opinions.", bn: "নির্দ্বিধায় আপনার মতামত প্রকাশ করুন।", slotValues: { ACTION: "express your opinions" } },
        { en: "Feel free to make yourself at home.", bn: "নির্দ্বিধায় নিজেকে বাড়ির মতো মনে করুন।", slotValues: { ACTION: "make yourself at home" } },
      ],
      formality: "polite",
      difficulty: "beginner",
    },
    {
      id: "Q5.4",
      formula: "You're welcome to [ACTION]",
      formula_bn: "আপনি [কাজ] করতে স্বাগত",
      patternName: "Welcoming Permission",
      patternName_bn: "স্বাগতমূলক অনুমতি",
      slots: [
        { name: "ACTION", description: "Welcomed action", description_bn: "স্বাগত জানানো কাজ", acceptedTypes: ["verb_phrase"], examples: ["join us", "stay longer", "visit anytime"] },
      ],
      examples: [
        { en: "You're welcome to join us for dinner.", bn: "আপনি আমাদের সাথে রাতের খাবারে যোগ দিতে স্বাগত।", slotValues: { ACTION: "join us for dinner" } },
        { en: "You're welcome to stay as long as you want.", bn: "আপনি যতক্ষণ চান থাকতে স্বাগত।", slotValues: { ACTION: "stay as long as you want" } },
        { en: "You're welcome to visit us anytime.", bn: "আপনি যেকোনো সময় আমাদের কাছে আসতে স্বাগত।", slotValues: { ACTION: "visit us anytime" } },
        { en: "You're welcome to use the facilities.", bn: "আপনি সুবিধাগুলো ব্যবহার করতে স্বাগত।", slotValues: { ACTION: "use the facilities" } },
        { en: "You're welcome to bring your children.", bn: "আপনি আপনার সন্তানদের নিয়ে আসতে স্বাগত।", slotValues: { ACTION: "bring your children" } },
        { en: "You're welcome to try a sample.", bn: "আপনি একটা নমুনা খেয়ে দেখতে স্বাগত।", slotValues: { ACTION: "try a sample" } },
        { en: "You're welcome to attend the workshop.", bn: "আপনি কর্মশালায় যোগ দিতে স্বাগত।", slotValues: { ACTION: "attend the workshop" } },
        { en: "You're welcome to share this with others.", bn: "আপনি এটা অন্যদের সাথে শেয়ার করতে স্বাগত।", slotValues: { ACTION: "share this with others" } },
        { en: "You're welcome to borrow any book from my shelf.", bn: "আপনি আমার তাক থেকে যেকোনো বই ধার নিতে স্বাগত।", slotValues: { ACTION: "borrow any book from my shelf" } },
        { en: "You're welcome to take photos here.", bn: "আপনি এখানে ছবি তুলতে স্বাগত।", slotValues: { ACTION: "take photos here" } },
        { en: "You're welcome to come back whenever you need.", bn: "আপনি যখনই দরকার আবার আসতে স্বাগত।", slotValues: { ACTION: "come back whenever you need" } },
        { en: "You're welcome to use my notes.", bn: "আপনি আমার নোটস ব্যবহার করতে স্বাগত।", slotValues: { ACTION: "use my notes" } },
        { en: "You're welcome to sit in on the meeting.", bn: "আপনি মিটিংয়ে বসে থাকতে স্বাগত।", slotValues: { ACTION: "sit in on the meeting" } },
        { en: "You're welcome to ask for a refund.", bn: "আপনি ফেরত চাইতে স্বাগত।", slotValues: { ACTION: "ask for a refund" } },
        { en: "You're welcome to explore the garden.", bn: "আপনি বাগানটা ঘুরে দেখতে স্বাগত।", slotValues: { ACTION: "explore the garden" } },
      ],
      formality: "polite",
      difficulty: "beginner",
    },
    {
      id: "Q5.5",
      formula: "Sure, you may [ACTION]",
      formula_bn: "অবশ্যই, তুমি [কাজ] করতে পারো",
      patternName: "Formal Permission Grant",
      patternName_bn: "আনুষ্ঠানিক অনুমতি প্রদান",
      slots: [
        { name: "ACTION", description: "Formally permitted action", description_bn: "আনুষ্ঠানিকভাবে অনুমোদিত কাজ", acceptedTypes: ["verb_phrase"], examples: ["leave early", "use the printer", "take the day off"] },
      ],
      examples: [
        { en: "Sure, you may leave early today.", bn: "অবশ্যই, তুমি আজ তাড়াতাড়ি যেতে পারো।", slotValues: { ACTION: "leave early today" } },
        { en: "Sure, you may use the office printer.", bn: "অবশ্যই, তুমি অফিস প্রিন্টার ব্যবহার করতে পারো।", slotValues: { ACTION: "use the office printer" } },
        { en: "Sure, you may take the day off.", bn: "অবশ্যই, তুমি একদিন ছুটি নিতে পারো।", slotValues: { ACTION: "take the day off" } },
        { en: "Sure, you may bring a guest to the event.", bn: "অবশ্যই, তুমি অনুষ্ঠানে একজন অতিথি আনতে পারো।", slotValues: { ACTION: "bring a guest to the event" } },
        { en: "Sure, you may speak first.", bn: "অবশ্যই, তুমি প্রথমে কথা বলতে পারো।", slotValues: { ACTION: "speak first" } },
        { en: "Sure, you may take a copy of the report.", bn: "অবশ্যই, তুমি রিপোর্টের একটা কপি নিতে পারো।", slotValues: { ACTION: "take a copy of the report" } },
        { en: "Sure, you may reschedule the appointment.", bn: "অবশ্যই, তুমি অ্যাপয়েন্টমেন্ট পুনঃনির্ধারণ করতে পারো।", slotValues: { ACTION: "reschedule the appointment" } },
        { en: "Sure, you may work from home tomorrow.", bn: "অবশ্যই, তুমি কাল বাড়ি থেকে কাজ করতে পারো।", slotValues: { ACTION: "work from home tomorrow" } },
        { en: "Sure, you may present your idea to the team.", bn: "অবশ্যই, তুমি দলের কাছে তোমার আইডিয়া উপস্থাপন করতে পারো।", slotValues: { ACTION: "present your idea to the team" } },
        { en: "Sure, you may change your seat.", bn: "অবশ্যই, তুমি তোমার আসন বদলাতে পারো।", slotValues: { ACTION: "change your seat" } },
        { en: "Sure, you may use a calculator for the test.", bn: "অবশ্যই, তুমি পরীক্ষায় ক্যালকুলেটর ব্যবহার করতে পারো।", slotValues: { ACTION: "use a calculator for the test" } },
        { en: "Sure, you may extend the deadline.", bn: "অবশ্যই, তুমি সময়সীমা বাড়াতে পারো।", slotValues: { ACTION: "extend the deadline" } },
        { en: "Sure, you may take your lunch break now.", bn: "অবশ্যই, তুমি এখন দুপুরের বিরতি নিতে পারো।", slotValues: { ACTION: "take your lunch break now" } },
        { en: "Sure, you may submit the assignment late.", bn: "অবশ্যই, তুমি অ্যাসাইনমেন্ট দেরিতে জমা দিতে পারো।", slotValues: { ACTION: "submit the assignment late" } },
        { en: "Sure, you may switch to a different class.", bn: "অবশ্যই, তুমি অন্য ক্লাসে যেতে পারো।", slotValues: { ACTION: "switch to a different class" } },
      ],
      formality: "polite",
      difficulty: "beginner",
    },
  ],
};
