import { PatternCategory } from "@/types/pattern";

export const categoryQ7: PatternCategory = {
  id: "Q7",
  slug: "expressing-obligation-duty",
  name: "Expressing Obligation & Duty",
  name_bn: "বাধ্যবাধকতা ও কর্তব্য প্রকাশ",
  description: "Express obligations, duties and responsibilities",
  description_bn: "বাধ্যবাধকতা, কর্তব্য ও দায়িত্ব প্রকাশ করুন",
  icon: "⚖️",
  group: "Q",
  groupName: "Advice, Instructions & Commands",
  groupName_bn: "উপদেশ, নির্দেশনা ও আদেশ",
  difficulty: "intermediate",
  patterns: [
    {
      id: "Q7.1",
      formula: "I'm supposed to [ACTION]",
      formula_bn: "আমার [কাজ] করার কথা",
      patternName: "Expected Obligation",
      patternName_bn: "প্রত্যাশিত বাধ্যবাধকতা",
      slots: [
        { name: "ACTION", description: "Expected action", description_bn: "প্রত্যাশিত কাজ", acceptedTypes: ["verb_phrase"], examples: ["be at work by nine", "finish the report", "meet him today"] },
      ],
      examples: [
        { en: "I'm supposed to be at work by nine.", bn: "আমার নয়টার মধ্যে কাজে থাকার কথা।", slotValues: { ACTION: "be at work by nine" } },
        { en: "I'm supposed to finish the report today.", bn: "আমার আজকেই রিপোর্ট শেষ করার কথা।", slotValues: { ACTION: "finish the report today" } },
        { en: "I'm supposed to meet him at the airport.", bn: "আমার বিমানবন্দরে তার সাথে দেখা করার কথা।", slotValues: { ACTION: "meet him at the airport" } },
        { en: "I'm supposed to pick up the kids at three.", bn: "আমার তিনটায় বাচ্চাদের আনার কথা।", slotValues: { ACTION: "pick up the kids at three" } },
        { en: "I'm supposed to attend the ceremony.", bn: "আমার অনুষ্ঠানে যোগ দেওয়ার কথা।", slotValues: { ACTION: "attend the ceremony" } },
        { en: "I'm supposed to call the doctor back.", bn: "আমার ডাক্তারকে আবার ফোন করার কথা।", slotValues: { ACTION: "call the doctor back" } },
        { en: "I'm supposed to hand in my assignment tomorrow.", bn: "আমার কাল অ্যাসাইনমেন্ট জমা দেওয়ার কথা।", slotValues: { ACTION: "hand in my assignment tomorrow" } },
        { en: "I'm supposed to take my medicine twice a day.", bn: "আমার দিনে দুইবার ওষুধ খাওয়ার কথা।", slotValues: { ACTION: "take my medicine twice a day" } },
        { en: "I'm supposed to help my mother with groceries.", bn: "আমার মাকে বাজার করতে সাহায্য করার কথা।", slotValues: { ACTION: "help my mother with groceries" } },
        { en: "I'm supposed to attend a training session.", bn: "আমার একটা প্রশিক্ষণ সেশনে যোগ দেওয়ার কথা।", slotValues: { ACTION: "attend a training session" } },
        { en: "I'm supposed to wear a uniform at school.", bn: "আমার স্কুলে ইউনিফর্ম পরার কথা।", slotValues: { ACTION: "wear a uniform at school" } },
        { en: "I'm supposed to prepare dinner tonight.", bn: "আমার আজ রাতে রাতের খাবার তৈরি করার কথা।", slotValues: { ACTION: "prepare dinner tonight" } },
        { en: "I'm supposed to water the garden every morning.", bn: "আমার প্রতি সকালে বাগানে পানি দেওয়ার কথা।", slotValues: { ACTION: "water the garden every morning" } },
        { en: "I'm supposed to submit the tax forms by April.", bn: "আমার এপ্রিলের মধ্যে ট্যাক্স ফর্ম জমা দেওয়ার কথা।", slotValues: { ACTION: "submit the tax forms by April" } },
        { en: "I'm supposed to give a presentation next week.", bn: "আমার আগামী সপ্তাহে একটা প্রেজেন্টেশন দেওয়ার কথা।", slotValues: { ACTION: "give a presentation next week" } },
      ],
      formality: "casual",
      difficulty: "intermediate",
    },
    {
      id: "Q7.2",
      formula: "It's my responsibility to [ACTION]",
      formula_bn: "[কাজ] করা আমার দায়িত্ব",
      patternName: "Personal Responsibility",
      patternName_bn: "ব্যক্তিগত দায়িত্ব",
      slots: [
        { name: "ACTION", description: "Responsible action", description_bn: "দায়িত্বপূর্ণ কাজ", acceptedTypes: ["verb_phrase"], examples: ["take care of", "make sure", "provide for"] },
      ],
      examples: [
        { en: "It's my responsibility to take care of my family.", bn: "আমার পরিবারের যত্ন নেওয়া আমার দায়িত্ব।", slotValues: { ACTION: "take care of my family" } },
        { en: "It's my responsibility to make sure the project is done on time.", bn: "প্রকল্পটি সময়মতো শেষ হয়েছে তা নিশ্চিত করা আমার দায়িত্ব।", slotValues: { ACTION: "make sure the project is done on time" } },
        { en: "It's my responsibility to provide for my children.", bn: "আমার সন্তানদের ভরণপোষণ দেওয়া আমার দায়িত্ব।", slotValues: { ACTION: "provide for my children" } },
        { en: "It's my responsibility to keep the office clean.", bn: "অফিস পরিষ্কার রাখা আমার দায়িত্ব।", slotValues: { ACTION: "keep the office clean" } },
        { en: "It's my responsibility to lock up at night.", bn: "রাতে তালা দেওয়া আমার দায়িত্ব।", slotValues: { ACTION: "lock up at night" } },
        { en: "It's my responsibility to train the new employees.", bn: "নতুন কর্মচারীদের প্রশিক্ষণ দেওয়া আমার দায়িত্ব।", slotValues: { ACTION: "train the new employees" } },
        { en: "It's my responsibility to report any issues.", bn: "যেকোনো সমস্যা রিপোর্ট করা আমার দায়িত্ব।", slotValues: { ACTION: "report any issues" } },
        { en: "It's my responsibility to ensure everyone's safety.", bn: "সবার নিরাপত্তা নিশ্চিত করা আমার দায়িত্ব।", slotValues: { ACTION: "ensure everyone's safety" } },
        { en: "It's my responsibility to organize the event.", bn: "অনুষ্ঠান আয়োজন করা আমার দায়িত্ব।", slotValues: { ACTION: "organize the event" } },
        { en: "It's my responsibility to maintain the equipment.", bn: "যন্ত্রপাতি রক্ষণাবেক্ষণ করা আমার দায়িত্ব।", slotValues: { ACTION: "maintain the equipment" } },
        { en: "It's my responsibility to manage the budget.", bn: "বাজেট পরিচালনা করা আমার দায়িত্ব।", slotValues: { ACTION: "manage the budget" } },
        { en: "It's my responsibility to answer customer complaints.", bn: "গ্রাহকের অভিযোগের উত্তর দেওয়া আমার দায়িত্ব।", slotValues: { ACTION: "answer customer complaints" } },
        { en: "It's my responsibility to teach my students well.", bn: "আমার ছাত্রদের ভালোভাবে শেখানো আমার দায়িত্ব।", slotValues: { ACTION: "teach my students well" } },
        { en: "It's my responsibility to keep the records updated.", bn: "রেকর্ড আপডেট রাখা আমার দায়িত্ব।", slotValues: { ACTION: "keep the records updated" } },
        { en: "It's my responsibility to set a good example.", bn: "ভালো উদাহরণ স্থাপন করা আমার দায়িত্ব।", slotValues: { ACTION: "set a good example" } },
      ],
      formality: "polite",
      difficulty: "intermediate",
    },
    {
      id: "Q7.3",
      formula: "I have to [ACTION]",
      formula_bn: "আমাকে [কাজ] করতে হবে",
      patternName: "Necessity Obligation",
      patternName_bn: "প্রয়োজনীয়তার বাধ্যবাধকতা",
      slots: [
        { name: "ACTION", description: "Necessary action", description_bn: "প্রয়োজনীয় কাজ", acceptedTypes: ["verb_phrase"], examples: ["go now", "work late", "study tonight"] },
      ],
      examples: [
        { en: "I have to go now or I'll miss the bus.", bn: "আমাকে এখন যেতে হবে নাহলে বাস মিস হবে।", slotValues: { ACTION: "go now" } },
        { en: "I have to work late tonight.", bn: "আমাকে আজ রাতে দেরিতে কাজ করতে হবে।", slotValues: { ACTION: "work late tonight" } },
        { en: "I have to study for my exam.", bn: "আমাকে পরীক্ষার জন্য পড়তে হবে।", slotValues: { ACTION: "study for my exam" } },
        { en: "I have to pay the electricity bill today.", bn: "আমাকে আজ বিদ্যুৎ বিল দিতে হবে।", slotValues: { ACTION: "pay the electricity bill today" } },
        { en: "I have to visit my grandmother this weekend.", bn: "আমাকে এই সপ্তাহান্তে দাদির কাছে যেতে হবে।", slotValues: { ACTION: "visit my grandmother this weekend" } },
        { en: "I have to wake up early tomorrow.", bn: "আমাকে কাল তাড়াতাড়ি উঠতে হবে।", slotValues: { ACTION: "wake up early tomorrow" } },
        { en: "I have to finish my homework before dinner.", bn: "আমাকে রাতের খাবারের আগে হোমওয়ার্ক শেষ করতে হবে।", slotValues: { ACTION: "finish my homework before dinner" } },
        { en: "I have to renew my passport next month.", bn: "আমাকে আগামী মাসে পাসপোর্ট নবায়ন করতে হবে।", slotValues: { ACTION: "renew my passport next month" } },
        { en: "I have to cook something for the potluck.", bn: "আমাকে পটলাকের জন্য কিছু রান্না করতে হবে।", slotValues: { ACTION: "cook something for the potluck" } },
        { en: "I have to take my car to the mechanic.", bn: "আমাকে আমার গাড়ি মেকানিকের কাছে নিতে হবে।", slotValues: { ACTION: "take my car to the mechanic" } },
        { en: "I have to clean the house before the guests arrive.", bn: "অতিথিরা আসার আগে আমাকে ঘর পরিষ্কার করতে হবে।", slotValues: { ACTION: "clean the house before the guests arrive" } },
        { en: "I have to apologize for my behavior.", bn: "আমাকে আমার আচরণের জন্য ক্ষমা চাইতে হবে।", slotValues: { ACTION: "apologize for my behavior" } },
        { en: "I have to return the library books.", bn: "আমাকে লাইব্রেরির বই ফেরত দিতে হবে।", slotValues: { ACTION: "return the library books" } },
        { en: "I have to attend a wedding this Saturday.", bn: "আমাকে এই শনিবারে একটা বিয়েতে যোগ দিতে হবে।", slotValues: { ACTION: "attend a wedding this Saturday" } },
        { en: "I have to get my eyes checked.", bn: "আমাকে চোখ পরীক্ষা করাতে হবে।", slotValues: { ACTION: "get my eyes checked" } },
      ],
      formality: "casual",
      difficulty: "beginner",
    },
    {
      id: "Q7.4",
      formula: "I'm obligated to [ACTION]",
      formula_bn: "আমি [কাজ] করতে বাধ্য",
      patternName: "Formal Obligation",
      patternName_bn: "আনুষ্ঠানিক বাধ্যবাধকতা",
      slots: [
        { name: "ACTION", description: "Legally or formally required action", description_bn: "আইনগত বা আনুষ্ঠানিকভাবে প্রয়োজনীয় কাজ", acceptedTypes: ["verb_phrase"], examples: ["report this", "inform you", "comply with the law"] },
      ],
      examples: [
        { en: "I'm obligated to report this to the authorities.", bn: "আমি কর্তৃপক্ষের কাছে এটা রিপোর্ট করতে বাধ্য।", slotValues: { ACTION: "report this to the authorities" } },
        { en: "I'm obligated to inform you of your rights.", bn: "আমি আপনার অধিকার সম্পর্কে জানাতে বাধ্য।", slotValues: { ACTION: "inform you of your rights" } },
        { en: "I'm obligated to comply with the law.", bn: "আমি আইন মানতে বাধ্য।", slotValues: { ACTION: "comply with the law" } },
        { en: "I'm obligated to attend the court hearing.", bn: "আমি আদালতের শুনানিতে উপস্থিত থাকতে বাধ্য।", slotValues: { ACTION: "attend the court hearing" } },
        { en: "I'm obligated to pay my taxes on time.", bn: "আমি সময়মতো কর দিতে বাধ্য।", slotValues: { ACTION: "pay my taxes on time" } },
        { en: "I'm obligated to fulfill the contract.", bn: "আমি চুক্তি পূরণ করতে বাধ্য।", slotValues: { ACTION: "fulfill the contract" } },
        { en: "I'm obligated to keep this information confidential.", bn: "আমি এই তথ্য গোপন রাখতে বাধ্য।", slotValues: { ACTION: "keep this information confidential" } },
        { en: "I'm obligated to complete the mandatory training.", bn: "আমি বাধ্যতামূলক প্রশিক্ষণ সম্পন্ন করতে বাধ্য।", slotValues: { ACTION: "complete the mandatory training" } },
        { en: "I'm obligated to serve on the jury.", bn: "আমি জুরিতে সেবা দিতে বাধ্য।", slotValues: { ACTION: "serve on the jury" } },
        { en: "I'm obligated to disclose any conflicts of interest.", bn: "আমি যেকোনো স্বার্থের সংঘাত প্রকাশ করতে বাধ্য।", slotValues: { ACTION: "disclose any conflicts of interest" } },
        { en: "I'm obligated to follow the safety regulations.", bn: "আমি নিরাপত্তা বিধি মানতে বাধ্য।", slotValues: { ACTION: "follow the safety regulations" } },
        { en: "I'm obligated to provide accurate information.", bn: "আমি সঠিক তথ্য প্রদান করতে বাধ্য।", slotValues: { ACTION: "provide accurate information" } },
        { en: "I'm obligated to maintain professional standards.", bn: "আমি পেশাদার মান বজায় রাখতে বাধ্য।", slotValues: { ACTION: "maintain professional standards" } },
        { en: "I'm obligated to repay the loan within five years.", bn: "আমি পাঁচ বছরের মধ্যে ঋণ পরিশোধ করতে বাধ্য।", slotValues: { ACTION: "repay the loan within five years" } },
        { en: "I'm obligated to notify you of any changes.", bn: "আমি যেকোনো পরিবর্তন সম্পর্কে আপনাকে জানাতে বাধ্য।", slotValues: { ACTION: "notify you of any changes" } },
      ],
      formality: "formal",
      difficulty: "intermediate",
    },
    {
      id: "Q7.5",
      formula: "It's my duty to [ACTION]",
      formula_bn: "[কাজ] করা আমার কর্তব্য",
      patternName: "Sense of Duty",
      patternName_bn: "কর্তব্যবোধ",
      slots: [
        { name: "ACTION", description: "Duty-bound action", description_bn: "কর্তব্যবদ্ধ কাজ", acceptedTypes: ["verb_phrase"], examples: ["serve my country", "protect the environment", "help the needy"] },
      ],
      examples: [
        { en: "It's my duty to serve my country.", bn: "দেশের সেবা করা আমার কর্তব্য।", slotValues: { ACTION: "serve my country" } },
        { en: "It's my duty to protect the environment.", bn: "পরিবেশ রক্ষা করা আমার কর্তব্য।", slotValues: { ACTION: "protect the environment" } },
        { en: "It's my duty to help those in need.", bn: "যাদের সাহায্য দরকার তাদের সাহায্য করা আমার কর্তব্য।", slotValues: { ACTION: "help those in need" } },
        { en: "It's my duty to uphold the law.", bn: "আইন বজায় রাখা আমার কর্তব্য।", slotValues: { ACTION: "uphold the law" } },
        { en: "It's my duty to inform you about this matter.", bn: "এই বিষয়ে আপনাকে জানানো আমার কর্তব্য।", slotValues: { ACTION: "inform you about this matter" } },
        { en: "It's my duty to ensure the safety of all passengers.", bn: "সকল যাত্রীর নিরাপত্তা নিশ্চিত করা আমার কর্তব্য।", slotValues: { ACTION: "ensure the safety of all passengers" } },
        { en: "It's my duty to represent the company professionally.", bn: "কোম্পানিকে পেশাদারভাবে প্রতিনিধিত্ব করা আমার কর্তব্য।", slotValues: { ACTION: "represent the company professionally" } },
        { en: "It's my duty to respect my elders.", bn: "বড়দের সম্মান করা আমার কর্তব্য।", slotValues: { ACTION: "respect my elders" } },
        { en: "It's my duty to vote in every election.", bn: "প্রতিটি নির্বাচনে ভোট দেওয়া আমার কর্তব্য।", slotValues: { ACTION: "vote in every election" } },
        { en: "It's my duty to guide the younger generation.", bn: "তরুণ প্রজন্মকে পথ দেখানো আমার কর্তব্য।", slotValues: { ACTION: "guide the younger generation" } },
        { en: "It's my duty to stand up against injustice.", bn: "অবিচারের বিরুদ্ধে দাঁড়ানো আমার কর্তব্য।", slotValues: { ACTION: "stand up against injustice" } },
        { en: "It's my duty to care for the patients.", bn: "রোগীদের যত্ন নেওয়া আমার কর্তব্য।", slotValues: { ACTION: "care for the patients" } },
        { en: "It's my duty to be honest and transparent.", bn: "সৎ ও স্বচ্ছ থাকা আমার কর্তব্য।", slotValues: { ACTION: "be honest and transparent" } },
        { en: "It's my duty to complete the task assigned to me.", bn: "আমাকে দেওয়া কাজ সম্পন্ন করা আমার কর্তব্য।", slotValues: { ACTION: "complete the task assigned to me" } },
        { en: "It's my duty to keep our traditions alive.", bn: "আমাদের ঐতিহ্য জীবিত রাখা আমার কর্তব্য।", slotValues: { ACTION: "keep our traditions alive" } },
      ],
      formality: "formal",
      difficulty: "intermediate",
    },
  ],
};
