import { PatternCategory } from "@/types/pattern";

export const categoryR11: PatternCategory = {
  id: "R11",
  slug: "even-patterns",
  name: "Even Patterns",
  name_bn: "'এমনকি' প্যাটার্ন",
  description: "Use 'even' to add emphasis, surprise, or extreme cases to your statements.",
  description_bn: "'এমনকি' ব্যবহার করে আপনার বক্তব্যে জোর, বিস্ময় বা চরম ঘটনা যোগ করুন।",
  icon: "❗",
  group: "R",
  groupName: "Logical & Discourse Patterns",
  groupName_bn: "যৌক্তিক ও বক্তৃতা প্যাটার্ন",
  difficulty: "advanced",
  patterns: [
    {
      id: "R11.1",
      formula: "Even [PERSON] can [ACTION]",
      formula_bn: "এমনকি [ব্যক্তি]-ও [কাজ] করতে পারে",
      patternName: "Even Someone Can",
      patternName_bn: "এমনকি কেউও পারে",
      slots: [
        {
          name: "PERSON",
          description: "A person who is unexpectedly able to do something",
          description_bn: "যে ব্যক্তি অপ্রত্যাশিতভাবে কিছু করতে পারে",
          acceptedTypes: ["person", "noun"],
          examples: ["a child", "beginners", "my grandmother"],
        },
        {
          name: "ACTION",
          description: "The action they can perform",
          description_bn: "যে কাজটি তারা করতে পারে",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["do it", "understand this", "cook this dish"],
        },
      ],
      examples: [
        { en: "Even a child can understand this.", bn: "এমনকি একটি শিশুও এটি বুঝতে পারে।", slotValues: { PERSON: "a child", ACTION: "understand this" }, topicArea: "education" },
        { en: "Even beginners can learn this quickly.", bn: "এমনকি নতুনরাও এটি দ্রুত শিখতে পারে।", slotValues: { PERSON: "beginners", ACTION: "learn this quickly" }, topicArea: "education" },
        { en: "Even my grandmother can use a smartphone.", bn: "এমনকি আমার দাদিও স্মার্টফোন ব্যবহার করতে পারেন।", slotValues: { PERSON: "my grandmother", ACTION: "use a smartphone" }, topicArea: "daily_life" },
        { en: "Even the new employee can handle this task.", bn: "এমনকি নতুন কর্মচারীও এই কাজটি সামলাতে পারে।", slotValues: { PERSON: "the new employee", ACTION: "handle this task" }, topicArea: "work" },
        { en: "Even someone with no experience can cook this dish.", bn: "এমনকি অভিজ্ঞতাহীন কেউও এই পদটি রান্না করতে পারে।", slotValues: { PERSON: "someone with no experience", ACTION: "cook this dish" }, topicArea: "food" },
        { en: "Even a stranger can see they're in love.", bn: "এমনকি একজন অপরিচিত ব্যক্তিও দেখতে পারে তারা প্রেমে পড়েছে।", slotValues: { PERSON: "a stranger", ACTION: "see they're in love" }, topicArea: "relationships" },
        { en: "Even a non-athlete can finish this trail.", bn: "এমনকি একজন অ-ক্রীড়াবিদও এই ট্রেইল শেষ করতে পারে।", slotValues: { PERSON: "a non-athlete", ACTION: "finish this trail" }, topicArea: "health" },
        { en: "Even kids can find good deals online.", bn: "এমনকি বাচ্চারাও অনলাইনে ভালো ডিল খুঁজে পেতে পারে।", slotValues: { PERSON: "kids", ACTION: "find good deals online" }, topicArea: "shopping" },
        { en: "Even a first-time traveler can navigate this city.", bn: "এমনকি প্রথমবার ভ্রমণকারীও এই শহরে ঘুরে বেড়াতে পারে।", slotValues: { PERSON: "a first-time traveler", ACTION: "navigate this city" }, topicArea: "travel" },
        { en: "Even the intern can run the meeting.", bn: "এমনকি ইন্টার্নও মিটিং পরিচালনা করতে পারে।", slotValues: { PERSON: "the intern", ACTION: "run the meeting" }, topicArea: "work" },
        { en: "Even my little sister can bake this cake.", bn: "এমনকি আমার ছোট বোনও এই কেক বানাতে পারে।", slotValues: { PERSON: "my little sister", ACTION: "bake this cake" }, topicArea: "food" },
        { en: "Even a busy person can find time for exercise.", bn: "এমনকি একজন ব্যস্ত ব্যক্তিও ব্যায়ামের জন্য সময় বের করতে পারে।", slotValues: { PERSON: "a busy person", ACTION: "find time for exercise" }, topicArea: "health" },
        { en: "Even students can afford this product.", bn: "এমনকি ছাত্ররাও এই পণ্যটি কিনতে পারে।", slotValues: { PERSON: "students", ACTION: "afford this product" }, topicArea: "shopping" },
        { en: "Even someone who hates studying can enjoy this course.", bn: "এমনকি যে পড়তে পছন্দ করে না সেও এই কোর্সটি উপভোগ করতে পারে।", slotValues: { PERSON: "someone who hates studying", ACTION: "enjoy this course" }, topicArea: "education" },
        { en: "Even my parents can appreciate modern music.", bn: "এমনকি আমার বাবা-মাও আধুনিক সংগীতের কদর করতে পারেন।", slotValues: { PERSON: "my parents", ACTION: "appreciate modern music" }, topicArea: "daily_life" },
      ],
      formality: "casual",
      difficulty: "advanced",
      usageNote: "Emphasizes that something is so easy or obvious that an unlikely person can do it.",
      usageNote_bn: "জোর দেয় যে কিছু এতই সহজ বা স্পষ্ট যে একজন অসম্ভাব্য ব্যক্তিও এটি করতে পারে।",
      banglaStructureMap: "এমনকি (Even) + [ব্যক্তি]-ও (PERSON) + [কাজ] করতে পারে (can ACTION)",
    },
    {
      id: "R11.2",
      formula: "Even if [CONDITION], [CLAUSE]",
      formula_bn: "এমনকি যদি [শর্ত], [উপবাক্য]",
      patternName: "Even If",
      patternName_bn: "এমনকি যদি",
      slots: [
        {
          name: "CONDITION",
          description: "A hypothetical condition",
          description_bn: "একটি অনুমানমূলক শর্ত",
          acceptedTypes: ["clause", "condition"],
          examples: ["it rains", "they disagree", "the price goes up"],
        },
        {
          name: "CLAUSE",
          description: "What will happen regardless",
          description_bn: "তা সত্ত্বেও যা ঘটবে",
          acceptedTypes: ["clause"],
          examples: ["I'll go", "we should continue", "I won't change my mind"],
        },
      ],
      examples: [
        { en: "Even if it rains, I'll go to the park.", bn: "এমনকি যদি বৃষ্টি হয়, আমি পার্কে যাব।", slotValues: { CONDITION: "it rains", CLAUSE: "I'll go to the park" }, topicArea: "daily_life" },
        { en: "Even if they disagree, we should continue.", bn: "এমনকি যদি তারা একমত না হয়, আমাদের চালিয়ে যাওয়া উচিত।", slotValues: { CONDITION: "they disagree", CLAUSE: "we should continue" }, topicArea: "work" },
        { en: "Even if the price goes up, I'll buy it.", bn: "এমনকি যদি দাম বাড়ে, আমি এটি কিনব।", slotValues: { CONDITION: "the price goes up", CLAUSE: "I'll buy it" }, topicArea: "shopping" },
        { en: "Even if the food isn't great, the experience will be worth it.", bn: "এমনকি যদি খাবার দারুণ না হয়, অভিজ্ঞতাটি মূল্যবান হবে।", slotValues: { CONDITION: "the food isn't great", CLAUSE: "the experience will be worth it" }, topicArea: "food" },
        { en: "Even if I fail, I'll learn something.", bn: "এমনকি যদি আমি ব্যর্থ হই, আমি কিছু শিখব।", slotValues: { CONDITION: "I fail", CLAUSE: "I'll learn something" }, topicArea: "education" },
        { en: "Even if she's angry, she'll come around eventually.", bn: "এমনকি যদি সে রাগান্বিত হয়, শেষ পর্যন্ত সে মানবে।", slotValues: { CONDITION: "she's angry", CLAUSE: "she'll come around eventually" }, topicArea: "relationships" },
        { en: "Even if it hurts, I'll keep exercising.", bn: "এমনকি যদি ব্যথা লাগে, আমি ব্যায়াম চালিয়ে যাব।", slotValues: { CONDITION: "it hurts", CLAUSE: "I'll keep exercising" }, topicArea: "health" },
        { en: "Even if the flight is delayed, I'll wait.", bn: "এমনকি যদি ফ্লাইট দেরি হয়, আমি অপেক্ষা করব।", slotValues: { CONDITION: "the flight is delayed", CLAUSE: "I'll wait" }, topicArea: "travel" },
        { en: "Even if the project fails, we gained experience.", bn: "এমনকি যদি প্রকল্পটি ব্যর্থ হয়, আমরা অভিজ্ঞতা অর্জন করেছি।", slotValues: { CONDITION: "the project fails", CLAUSE: "we gained experience" }, topicArea: "work" },
        { en: "Even if nobody comes, I'll still host the party.", bn: "এমনকি যদি কেউ না আসে, আমি তবুও পার্টি দেব।", slotValues: { CONDITION: "nobody comes", CLAUSE: "I'll still host the party" }, topicArea: "daily_life" },
        { en: "Even if the exam is hard, I'm prepared.", bn: "এমনকি যদি পরীক্ষা কঠিন হয়, আমি প্রস্তুত।", slotValues: { CONDITION: "the exam is hard", CLAUSE: "I'm prepared" }, topicArea: "education" },
        { en: "Even if the restaurant is full, let's try.", bn: "এমনকি যদি রেস্তোরাঁ ভরা থাকে, চলো চেষ্টা করি।", slotValues: { CONDITION: "the restaurant is full", CLAUSE: "let's try" }, topicArea: "food" },
        { en: "Even if we argue, I'll still care about you.", bn: "এমনকি যদি আমরা ঝগড়া করি, আমি তবুও তোমার কথা ভাবব।", slotValues: { CONDITION: "we argue", CLAUSE: "I'll still care about you" }, topicArea: "relationships" },
        { en: "Even if the doctor says it's minor, I'm worried.", bn: "এমনকি যদি ডাক্তার বলেন এটা ছোটখাট, আমি চিন্তিত।", slotValues: { CONDITION: "the doctor says it's minor", CLAUSE: "I'm worried" }, topicArea: "health" },
        { en: "Even if the hotel is expensive, the location is perfect.", bn: "এমনকি যদি হোটেল ব্যয়বহুল হয়, অবস্থানটি নিখুঁত।", slotValues: { CONDITION: "the hotel is expensive", CLAUSE: "the location is perfect" }, topicArea: "travel" },
      ],
      formality: "casual",
      difficulty: "advanced",
      usageNote: "Shows determination or certainty regardless of a hypothetical condition. Stronger than a simple 'if'.",
      usageNote_bn: "একটি অনুমানমূলক শর্ত নির্বিশেষে সংকল্প বা নিশ্চয়তা দেখায়। সাধারণ 'if'-এর চেয়ে শক্তিশালী।",
      banglaStructureMap: "এমনকি যদি (Even if) + [শর্ত] (Condition) + [উপবাক্য] (Result clause)",
    },
    {
      id: "R11.3",
      formula: "Even though [CLAUSE], [CLAUSE]",
      formula_bn: "যদিও [উপবাক্য], [উপবাক্য]",
      patternName: "Even Though",
      patternName_bn: "যদিও",
      slots: [
        {
          name: "CLAUSE",
          description: "A true fact that contrasts with the result",
          description_bn: "একটি সত্য তথ্য যা ফলাফলের সাথে বিপরীত",
          acceptedTypes: ["clause"],
          examples: ["he was tired, he kept working", "it was expensive, she bought it", "they warned him, he went anyway"],
        },
      ],
      examples: [
        { en: "Even though he was tired, he kept working.", bn: "যদিও সে ক্লান্ত ছিল, সে কাজ চালিয়ে গেল।", slotValues: { CLAUSE: "he was tired, he kept working" }, topicArea: "work" },
        { en: "Even though it was expensive, she bought it.", bn: "যদিও এটি দামি ছিল, সে এটি কিনেছিল।", slotValues: { CLAUSE: "it was expensive, she bought it" }, topicArea: "shopping" },
        { en: "Even though they warned him, he went anyway.", bn: "যদিও তারা তাকে সতর্ক করেছিল, সে তবুও গিয়েছিল।", slotValues: { CLAUSE: "they warned him, he went anyway" }, topicArea: "daily_life" },
        { en: "Even though the food was cold, it was still delicious.", bn: "যদিও খাবার ঠান্ডা ছিল, এটি তবুও সুস্বাদু ছিল।", slotValues: { CLAUSE: "the food was cold, it was still delicious" }, topicArea: "food" },
        { en: "Even though the exam was hard, most students passed.", bn: "যদিও পরীক্ষা কঠিন ছিল, বেশিরভাগ ছাত্র পাস করেছিল।", slotValues: { CLAUSE: "the exam was hard, most students passed" }, topicArea: "education" },
        { en: "Even though they had differences, they stayed friends.", bn: "যদিও তাদের মতপার্থক্য ছিল, তারা বন্ধু থেকে গিয়েছিল।", slotValues: { CLAUSE: "they had differences, they stayed friends" }, topicArea: "relationships" },
        { en: "Even though the doctor advised rest, she went to work.", bn: "যদিও ডাক্তার বিশ্রামের পরামর্শ দিয়েছিলেন, সে কাজে গিয়েছিল।", slotValues: { CLAUSE: "the doctor advised rest, she went to work" }, topicArea: "health" },
        { en: "Even though the weather was bad, the trip was wonderful.", bn: "যদিও আবহাওয়া খারাপ ছিল, ভ্রমণটি চমৎকার ছিল।", slotValues: { CLAUSE: "the weather was bad, the trip was wonderful" }, topicArea: "travel" },
        { en: "Even though the deadline was tight, we delivered on time.", bn: "যদিও সময়সীমা কম ছিল, আমরা সময়মতো সরবরাহ করেছিলাম।", slotValues: { CLAUSE: "the deadline was tight, we delivered on time" }, topicArea: "work" },
        { en: "Even though she didn't study, she scored well.", bn: "যদিও সে পড়েনি, সে ভালো নম্বর পেয়েছিল।", slotValues: { CLAUSE: "she didn't study, she scored well" }, topicArea: "education" },
        { en: "Even though the portions were small, the flavors were incredible.", bn: "যদিও পরিমাণ কম ছিল, স্বাদ অবিশ্বাস্য ছিল।", slotValues: { CLAUSE: "the portions were small, the flavors were incredible" }, topicArea: "food" },
        { en: "Even though the product was cheap, the quality was great.", bn: "যদিও পণ্যটি সস্তা ছিল, মান দারুণ ছিল।", slotValues: { CLAUSE: "the product was cheap, the quality was great" }, topicArea: "shopping" },
        { en: "Even though I was scared, I enjoyed the adventure.", bn: "যদিও আমি ভয় পেয়েছিলাম, আমি সাহসিক অভিযানটি উপভোগ করেছিলাম।", slotValues: { CLAUSE: "I was scared, I enjoyed the adventure" }, topicArea: "travel" },
        { en: "Even though he apologized, she was still upset.", bn: "যদিও সে ক্ষমা চেয়েছিল, সে তখনও মন খারাপ ছিল।", slotValues: { CLAUSE: "he apologized, she was still upset" }, topicArea: "relationships" },
        { en: "Even though the treatment was painful, it worked.", bn: "যদিও চিকিৎসা কষ্টকর ছিল, এটি কাজ করেছিল।", slotValues: { CLAUSE: "the treatment was painful, it worked" }, topicArea: "health" },
      ],
      formality: "casual",
      difficulty: "advanced",
      usageNote: "Concedes a real fact while presenting a contrasting result. Stronger and more emphatic than 'although'.",
      usageNote_bn: "একটি বাস্তব তথ্য স্বীকার করে একটি বিপরীত ফলাফল উপস্থাপন করে। 'although'-এর চেয়ে শক্তিশালী ও জোরালো।",
      banglaStructureMap: "যদিও (Even though) + [উপবাক্য] (Concessive clause) + [উপবাক্য] (Main clause)",
    },
    {
      id: "R11.4",
      formula: "Not even [PERSON] could [ACTION]",
      formula_bn: "এমনকি [ব্যক্তি]-ও [কাজ] করতে পারেনি",
      patternName: "Not Even Someone Could",
      patternName_bn: "এমনকি কেউও পারেনি",
      slots: [
        {
          name: "PERSON",
          description: "A person expected to succeed but couldn't",
          description_bn: "যার সফল হওয়ার কথা ছিল কিন্তু পারেনি",
          acceptedTypes: ["person", "noun"],
          examples: ["the experts", "my best friend", "the teacher"],
        },
        {
          name: "ACTION",
          description: "The action that couldn't be done",
          description_bn: "যে কাজটি করা সম্ভব হয়নি",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["solve this problem", "fix the issue", "convince him"],
        },
      ],
      examples: [
        { en: "Not even the experts could solve this problem.", bn: "এমনকি বিশেষজ্ঞরাও এই সমস্যার সমাধান করতে পারেননি।", slotValues: { PERSON: "the experts", ACTION: "solve this problem" }, topicArea: "work" },
        { en: "Not even my best friend could cheer me up.", bn: "এমনকি আমার সেরা বন্ধুও আমাকে আনন্দিত করতে পারেনি।", slotValues: { PERSON: "my best friend", ACTION: "cheer me up" }, topicArea: "relationships" },
        { en: "Not even the teacher could answer that question.", bn: "এমনকি শিক্ষকও সেই প্রশ্নের উত্তর দিতে পারেননি।", slotValues: { PERSON: "the teacher", ACTION: "answer that question" }, topicArea: "education" },
        { en: "Not even the best chef could save this dish.", bn: "এমনকি সেরা শেফও এই পদটি বাঁচাতে পারেননি।", slotValues: { PERSON: "the best chef", ACTION: "save this dish" }, topicArea: "food" },
        { en: "Not even the doctor could explain the symptoms.", bn: "এমনকি ডাক্তারও লক্ষণগুলো ব্যাখ্যা করতে পারেননি।", slotValues: { PERSON: "the doctor", ACTION: "explain the symptoms" }, topicArea: "health" },
        { en: "Not even the travel agent could find a cheap flight.", bn: "এমনকি ট্রাভেল এজেন্টও সস্তা ফ্লাইট খুঁজে পাননি।", slotValues: { PERSON: "the travel agent", ACTION: "find a cheap flight" }, topicArea: "travel" },
        { en: "Not even the manager could fix the issue.", bn: "এমনকি ম্যানেজারও সমস্যাটি ঠিক করতে পারেননি।", slotValues: { PERSON: "the manager", ACTION: "fix the issue" }, topicArea: "work" },
        { en: "Not even the shopkeeper could match that price.", bn: "এমনকি দোকানদারও সেই দাম দিতে পারেননি।", slotValues: { PERSON: "the shopkeeper", ACTION: "match that price" }, topicArea: "shopping" },
        { en: "Not even his mother could convince him.", bn: "এমনকি তার মাও তাকে বোঝাতে পারেননি।", slotValues: { PERSON: "his mother", ACTION: "convince him" }, topicArea: "relationships" },
        { en: "Not even the top student could finish the test on time.", bn: "এমনকি সেরা ছাত্রও সময়মতো পরীক্ষা শেষ করতে পারেনি।", slotValues: { PERSON: "the top student", ACTION: "finish the test on time" }, topicArea: "education" },
        { en: "Not even the local guide could find the trail.", bn: "এমনকি স্থানীয় গাইডও পথটি খুঁজে পাননি।", slotValues: { PERSON: "the local guide", ACTION: "find the trail" }, topicArea: "travel" },
        { en: "Not even experienced cooks could replicate her recipe.", bn: "এমনকি অভিজ্ঞ রাঁধুনিরাও তার রেসিপি অনুকরণ করতে পারেননি।", slotValues: { PERSON: "experienced cooks", ACTION: "replicate her recipe" }, topicArea: "food" },
        { en: "Not even the pharmacist could suggest a remedy.", bn: "এমনকি ফার্মাসিস্টও কোনো প্রতিকার পরামর্শ দিতে পারেননি।", slotValues: { PERSON: "the pharmacist", ACTION: "suggest a remedy" }, topicArea: "health" },
        { en: "Not even the neighbors could hear anything.", bn: "এমনকি প্রতিবেশীরাও কিছু শুনতে পায়নি।", slotValues: { PERSON: "the neighbors", ACTION: "hear anything" }, topicArea: "daily_life" },
        { en: "Not even a big discount could make me buy it.", bn: "এমনকি বড় ছাড়ও আমাকে এটি কিনতে রাজি করাতে পারেনি।", slotValues: { PERSON: "a big discount", ACTION: "make me buy it" }, topicArea: "shopping" },
      ],
      formality: "casual",
      difficulty: "advanced",
      usageNote: "Emphasizes difficulty or impossibility by showing that even the most likely person failed.",
      usageNote_bn: "কঠিনতা বা অসম্ভবতা জোর দেয় দেখিয়ে যে সবচেয়ে সম্ভাব্য ব্যক্তিও ব্যর্থ হয়েছে।",
      banglaStructureMap: "এমনকি (Not even) + [ব্যক্তি]-ও (PERSON) + [কাজ] করতে পারেনি (couldn't ACTION)",
    },
    {
      id: "R11.5",
      formula: "I can't even [ACTION]",
      formula_bn: "আমি [কাজ]-ও করতে পারি না",
      patternName: "Can't Even",
      patternName_bn: "এমনকি পারি না",
      slots: [
        {
          name: "ACTION",
          description: "A basic action you're unable to do, expressing frustration or disbelief",
          description_bn: "একটি মৌলিক কাজ যা আপনি করতে পারছেন না, হতাশা বা অবিশ্বাস প্রকাশ করে",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["think straight", "imagine", "believe it"],
        },
      ],
      examples: [
        { en: "I can't even think straight right now.", bn: "আমি এখন ঠিকমতো চিন্তাও করতে পারছি না।", slotValues: { ACTION: "think straight right now" }, topicArea: "daily_life" },
        { en: "I can't even imagine how hard that was.", bn: "আমি কল্পনাও করতে পারি না সেটা কতটা কঠিন ছিল।", slotValues: { ACTION: "imagine how hard that was" }, topicArea: "daily_life" },
        { en: "I can't even believe they won the match.", bn: "আমি বিশ্বাসও করতে পারছি না তারা ম্যাচ জিতেছে।", slotValues: { ACTION: "believe they won the match" }, topicArea: "daily_life" },
        { en: "I can't even focus on work today.", bn: "আজ আমি কাজেও মনোযোগ দিতে পারছি না।", slotValues: { ACTION: "focus on work today" }, topicArea: "work" },
        { en: "I can't even describe how good the food was.", bn: "খাবারটা কত ভালো ছিল তা বর্ণনাও করতে পারি না।", slotValues: { ACTION: "describe how good the food was" }, topicArea: "food" },
        { en: "I can't even remember the last time I studied.", bn: "আমি মনেও করতে পারি না শেষ কবে পড়েছিলাম।", slotValues: { ACTION: "remember the last time I studied" }, topicArea: "education" },
        { en: "I can't even explain how I feel about this.", bn: "আমি এই বিষয়ে কেমন অনুভব করছি তা ব্যাখ্যাও করতে পারি না।", slotValues: { ACTION: "explain how I feel about this" }, topicArea: "relationships" },
        { en: "I can't even walk after that workout.", bn: "সেই ব্যায়ামের পর আমি হাঁটতেও পারছি না।", slotValues: { ACTION: "walk after that workout" }, topicArea: "health" },
        { en: "I can't even afford a cup of coffee there.", bn: "আমি সেখানে এক কাপ কফিও কিনতে পারি না।", slotValues: { ACTION: "afford a cup of coffee there" }, topicArea: "shopping" },
        { en: "I can't even begin to explain the beauty of that place.", bn: "সেই জায়গার সৌন্দর্য ব্যাখ্যা করা শুরুও করতে পারি না।", slotValues: { ACTION: "begin to explain the beauty of that place" }, topicArea: "travel" },
        { en: "I can't even keep up with all the changes at work.", bn: "কর্মক্ষেত্রে সব পরিবর্তনের সাথে তাল মেলাতেও পারি না।", slotValues: { ACTION: "keep up with all the changes at work" }, topicArea: "work" },
        { en: "I can't even boil an egg properly.", bn: "আমি ঠিকমতো একটা ডিমও সেদ্ধ করতে পারি না।", slotValues: { ACTION: "boil an egg properly" }, topicArea: "food" },
        { en: "I can't even look at him after what happened.", bn: "যা ঘটেছে তার পর আমি তার দিকে তাকাতেও পারি না।", slotValues: { ACTION: "look at him after what happened" }, topicArea: "relationships" },
        { en: "I can't even sleep because of the pain.", bn: "ব্যথার কারণে আমি ঘুমাতেও পারছি না।", slotValues: { ACTION: "sleep because of the pain" }, topicArea: "health" },
        { en: "I can't even understand the textbook.", bn: "আমি পাঠ্যবইটাও বুঝতে পারি না।", slotValues: { ACTION: "understand the textbook" }, topicArea: "education" },
      ],
      formality: "casual",
      difficulty: "advanced",
      usageNote: "Expresses extreme frustration, disbelief, or inability. Very common in informal speech.",
      usageNote_bn: "চরম হতাশা, অবিশ্বাস বা অক্ষমতা প্রকাশ করে। অনানুষ্ঠানিক কথায় খুবই সাধারণ।",
      banglaStructureMap: "আমি (I) + [কাজ]-ও করতে পারি না/পারছি না (can't even ACTION)",
    },
  ],
};
