import { PatternCategory } from "@/types/pattern";

export const categoryR15: PatternCategory = {
  id: "R15",
  slug: "expressing-importance",
  name: "Expressing Importance",
  name_bn: "গুরুত্ব প্রকাশ",
  description: "Highlight the significance and importance of things using emphatic patterns.",
  description_bn: "জোরালো প্যাটার্ন ব্যবহার করে জিনিসের তাৎপর্য ও গুরুত্ব তুলে ধরুন।",
  icon: "⭐",
  group: "R",
  groupName: "Logical & Discourse Patterns",
  groupName_bn: "যৌক্তিক ও বক্তৃতা প্যাটার্ন",
  difficulty: "advanced",
  patterns: [
    {
      id: "R15.1",
      formula: "[THING] is important because [REASON]",
      formula_bn: "[জিনিস] গুরুত্বপূর্ণ কারণ [কারণ]",
      patternName: "Important Because",
      patternName_bn: "গুরুত্বপূর্ণ কারণ",
      slots: [
        {
          name: "THING",
          description: "The subject whose importance is being stated",
          description_bn: "যে বিষয়ের গুরুত্ব বলা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["Education", "Sleep", "Teamwork"],
        },
        {
          name: "REASON",
          description: "The reason it is important",
          description_bn: "এটি কেন গুরুত্বপূর্ণ তার কারণ",
          acceptedTypes: ["clause", "reason"],
          examples: ["it opens doors", "the body needs it to recover", "it brings different perspectives"],
        },
      ],
      examples: [
        { en: "Education is important because it opens doors.", bn: "শিক্ষা গুরুত্বপূর্ণ কারণ এটি দরজা খুলে দেয়।", slotValues: { THING: "Education", REASON: "it opens doors" }, topicArea: "education" },
        { en: "Sleep is important because the body needs it to recover.", bn: "ঘুম গুরুত্বপূর্ণ কারণ শরীরের সুস্থ হতে এটি দরকার।", slotValues: { THING: "Sleep", REASON: "the body needs it to recover" }, topicArea: "health" },
        { en: "Teamwork is important because it brings different perspectives.", bn: "দলবদ্ধ কাজ গুরুত্বপূর্ণ কারণ এটি ভিন্ন দৃষ্টিভঙ্গি আনে।", slotValues: { THING: "Teamwork", REASON: "it brings different perspectives" }, topicArea: "work" },
        { en: "Breakfast is important because it gives you energy for the day.", bn: "সকালের নাস্তা গুরুত্বপূর্ণ কারণ এটি সারাদিনের শক্তি দেয়।", slotValues: { THING: "Breakfast", REASON: "it gives you energy for the day" }, topicArea: "food" },
        { en: "Communication is important because misunderstandings can ruin relationships.", bn: "যোগাযোগ গুরুত্বপূর্ণ কারণ ভুল বোঝাবুঝি সম্পর্ক নষ্ট করতে পারে।", slotValues: { THING: "Communication", REASON: "misunderstandings can ruin relationships" }, topicArea: "relationships" },
        { en: "Saving money is important because you never know what might happen.", bn: "টাকা সঞ্চয় গুরুত্বপূর্ণ কারণ আপনি জানেন না কী হতে পারে।", slotValues: { THING: "Saving money", REASON: "you never know what might happen" }, topicArea: "shopping" },
        { en: "Planning is important because it makes travel smoother.", bn: "পরিকল্পনা গুরুত্বপূর্ণ কারণ এটি ভ্রমণ সুগম করে।", slotValues: { THING: "Planning", REASON: "it makes travel smoother" }, topicArea: "travel" },
        { en: "Punctuality is important because it shows respect.", bn: "সময়ানুবর্তিতা গুরুত্বপূর্ণ কারণ এটি সম্মান দেখায়।", slotValues: { THING: "Punctuality", REASON: "it shows respect" }, topicArea: "work" },
        { en: "Hydration is important because it helps your body function properly.", bn: "পানি পান গুরুত্বপূর্ণ কারণ এটি শরীরকে সঠিকভাবে কাজ করতে সাহায্য করে।", slotValues: { THING: "Hydration", REASON: "it helps your body function properly" }, topicArea: "health" },
        { en: "Reading is important because it expands your vocabulary.", bn: "পড়া গুরুত্বপূর্ণ কারণ এটি আপনার শব্দভাণ্ডার বাড়ায়।", slotValues: { THING: "Reading", REASON: "it expands your vocabulary" }, topicArea: "education" },
        { en: "Nutrition is important because food affects your mood.", bn: "পুষ্টি গুরুত্বপূর্ণ কারণ খাবার আপনার মেজাজ প্রভাবিত করে।", slotValues: { THING: "Nutrition", REASON: "food affects your mood" }, topicArea: "food" },
        { en: "Trust is important because it's the foundation of any relationship.", bn: "বিশ্বাস গুরুত্বপূর্ণ কারণ এটি যেকোনো সম্পর্কের ভিত্তি।", slotValues: { THING: "Trust", REASON: "it's the foundation of any relationship" }, topicArea: "relationships" },
        { en: "Budgeting is important because it prevents overspending.", bn: "বাজেট করা গুরুত্বপূর্ণ কারণ এটি অতিরিক্ত খরচ রোধ করে।", slotValues: { THING: "Budgeting", REASON: "it prevents overspending" }, topicArea: "shopping" },
        { en: "Cultural awareness is important because it enriches your travel experience.", bn: "সাংস্কৃতিক সচেতনতা গুরুত্বপূর্ণ কারণ এটি আপনার ভ্রমণ অভিজ্ঞতা সমৃদ্ধ করে।", slotValues: { THING: "Cultural awareness", REASON: "it enriches your travel experience" }, topicArea: "travel" },
        { en: "Feedback is important because it helps you improve.", bn: "প্রতিক্রিয়া গুরুত্বপূর্ণ কারণ এটি আপনাকে উন্নতি করতে সাহায্য করে।", slotValues: { THING: "Feedback", REASON: "it helps you improve" }, topicArea: "work" },
      ],
      formality: "polite",
      difficulty: "advanced",
      usageNote: "A clear and direct way to state why something matters. Common in essays, speeches, and discussions.",
      usageNote_bn: "কিছু কেন গুরুত্বপূর্ণ তা বলার একটি স্পষ্ট ও সরাসরি উপায়। প্রবন্ধ, বক্তৃতা ও আলোচনায় সাধারণ।",
      banglaStructureMap: "[জিনিস] (Subject) + গুরুত্বপূর্ণ (is important) + কারণ (because) + [কারণ] (Reason clause)",
    },
    {
      id: "R15.2",
      formula: "[THING] plays a key role in [THING]",
      formula_bn: "[জিনিস] [জিনিস]-এ মূল ভূমিকা পালন করে",
      patternName: "Plays a Key Role",
      patternName_bn: "মূল ভূমিকা পালন করে",
      slots: [
        {
          name: "THING",
          description: "Two things: the first is the important factor, the second is the area it affects",
          description_bn: "দুটি জিনিস: প্রথমটি গুরুত্বপূর্ণ বিষয়, দ্বিতীয়টি এটি যে ক্ষেত্রকে প্রভাবিত করে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["Technology, modern education", "Diet, overall health", "Trust, building strong teams"],
        },
      ],
      examples: [
        { en: "Technology plays a key role in modern education.", bn: "প্রযুক্তি আধুনিক শিক্ষায় মূল ভূমিকা পালন করে।", slotValues: { THING: "Technology, modern education" }, topicArea: "education" },
        { en: "Diet plays a key role in overall health.", bn: "খাদ্যাভ্যাস সামগ্রিক স্বাস্থ্যে মূল ভূমিকা পালন করে।", slotValues: { THING: "Diet, overall health" }, topicArea: "health" },
        { en: "Trust plays a key role in building strong teams.", bn: "বিশ্বাস শক্তিশালী দল গড়ায় মূল ভূমিকা পালন করে।", slotValues: { THING: "Trust, building strong teams" }, topicArea: "work" },
        { en: "Spices play a key role in Bengali cooking.", bn: "মশলা বাঙালি রান্নায় মূল ভূমিকা পালন করে।", slotValues: { THING: "Spices, Bengali cooking" }, topicArea: "food" },
        { en: "Patience plays a key role in maintaining relationships.", bn: "ধৈর্য সম্পর্ক রক্ষায় মূল ভূমিকা পালন করে।", slotValues: { THING: "Patience, maintaining relationships" }, topicArea: "relationships" },
        { en: "Reviews play a key role in online shopping decisions.", bn: "রিভিউ অনলাইন কেনাকাটার সিদ্ধান্তে মূল ভূমিকা পালন করে।", slotValues: { THING: "Reviews, online shopping decisions" }, topicArea: "shopping" },
        { en: "Weather plays a key role in travel planning.", bn: "আবহাওয়া ভ্রমণ পরিকল্পনায় মূল ভূমিকা পালন করে।", slotValues: { THING: "Weather, travel planning" }, topicArea: "travel" },
        { en: "Leadership plays a key role in project success.", bn: "নেতৃত্ব প্রকল্পের সাফল্যে মূল ভূমিকা পালন করে।", slotValues: { THING: "Leadership, project success" }, topicArea: "work" },
        { en: "Exercise plays a key role in mental health.", bn: "ব্যায়াম মানসিক স্বাস্থ্যে মূল ভূমিকা পালন করে।", slotValues: { THING: "Exercise, mental health" }, topicArea: "health" },
        { en: "Teachers play a key role in shaping young minds.", bn: "শিক্ষকরা তরুণ মন গড়ায় মূল ভূমিকা পালন করেন।", slotValues: { THING: "Teachers, shaping young minds" }, topicArea: "education" },
        { en: "Freshness plays a key role in the taste of sushi.", bn: "তাজা হওয়া সুশির স্বাদে মূল ভূমিকা পালন করে।", slotValues: { THING: "Freshness, the taste of sushi" }, topicArea: "food" },
        { en: "Communication plays a key role in conflict resolution.", bn: "যোগাযোগ দ্বন্দ্ব সমাধানে মূল ভূমিকা পালন করে।", slotValues: { THING: "Communication, conflict resolution" }, topicArea: "relationships" },
        { en: "Price comparison plays a key role in smart shopping.", bn: "দাম তুলনা বুদ্ধিমান কেনাকাটায় মূল ভূমিকা পালন করে।", slotValues: { THING: "Price comparison, smart shopping" }, topicArea: "shopping" },
        { en: "Local guides play a key role in authentic travel experiences.", bn: "স্থানীয় গাইড প্রকৃত ভ্রমণ অভিজ্ঞতায় মূল ভূমিকা পালন করে।", slotValues: { THING: "Local guides, authentic travel experiences" }, topicArea: "travel" },
        { en: "Routine plays a key role in staying productive.", bn: "রুটিন উৎপাদনশীল থাকায় মূল ভূমিকা পালন করে।", slotValues: { THING: "Routine, staying productive" }, topicArea: "daily_life" },
      ],
      formality: "formal",
      difficulty: "advanced",
      usageNote: "A sophisticated way to describe the importance of a factor within a larger system or context.",
      usageNote_bn: "একটি বৃহত্তর পদ্ধতি বা প্রসঙ্গে একটি বিষয়ের গুরুত্ব বর্ণনা করার একটি পরিশীলিত উপায়।",
      banglaStructureMap: "[জিনিস] (Subject) + [জিনিস]-এ (in THING) + মূল ভূমিকা পালন করে (plays a key role)",
    },
    {
      id: "R15.3",
      formula: "The most important thing is [CLAUSE]",
      formula_bn: "সবচেয়ে গুরুত্বপূর্ণ বিষয় হলো [উপবাক্য]",
      patternName: "The Most Important Thing",
      patternName_bn: "সবচেয়ে গুরুত্বপূর্ণ বিষয়",
      slots: [
        {
          name: "CLAUSE",
          description: "The single most important point or factor",
          description_bn: "একক সবচেয়ে গুরুত্বপূর্ণ বিষয় বা বিষয়",
          acceptedTypes: ["clause"],
          examples: ["to stay consistent", "that everyone is safe", "that you enjoy what you do"],
        },
      ],
      examples: [
        { en: "The most important thing is to stay consistent.", bn: "সবচেয়ে গুরুত্বপূর্ণ বিষয় হলো ধারাবাহিক থাকা।", slotValues: { CLAUSE: "to stay consistent" }, topicArea: "daily_life" },
        { en: "The most important thing is that everyone is safe.", bn: "সবচেয়ে গুরুত্বপূর্ণ বিষয় হলো সবাই নিরাপদ থাকা।", slotValues: { CLAUSE: "that everyone is safe" }, topicArea: "daily_life" },
        { en: "The most important thing is that you enjoy what you do.", bn: "সবচেয়ে গুরুত্বপূর্ণ বিষয় হলো তুমি যা করো তা উপভোগ করো।", slotValues: { CLAUSE: "that you enjoy what you do" }, topicArea: "work" },
        { en: "The most important thing is to use fresh ingredients.", bn: "সবচেয়ে গুরুত্বপূর্ণ বিষয় হলো তাজা উপকরণ ব্যবহার করা।", slotValues: { CLAUSE: "to use fresh ingredients" }, topicArea: "food" },
        { en: "The most important thing is to understand the concept.", bn: "সবচেয়ে গুরুত্বপূর্ণ বিষয় হলো ধারণাটি বোঝা।", slotValues: { CLAUSE: "to understand the concept" }, topicArea: "education" },
        { en: "The most important thing is to be honest with each other.", bn: "সবচেয়ে গুরুত্বপূর্ণ বিষয় হলো একে অপরের সাথে সৎ থাকা।", slotValues: { CLAUSE: "to be honest with each other" }, topicArea: "relationships" },
        { en: "The most important thing is to get enough rest.", bn: "সবচেয়ে গুরুত্বপূর্ণ বিষয় হলো পর্যাপ্ত বিশ্রাম নেওয়া।", slotValues: { CLAUSE: "to get enough rest" }, topicArea: "health" },
        { en: "The most important thing is to compare prices before buying.", bn: "সবচেয়ে গুরুত্বপূর্ণ বিষয় হলো কেনার আগে দাম তুলনা করা।", slotValues: { CLAUSE: "to compare prices before buying" }, topicArea: "shopping" },
        { en: "The most important thing is to have travel insurance.", bn: "সবচেয়ে গুরুত্বপূর্ণ বিষয় হলো ভ্রমণ বীমা থাকা।", slotValues: { CLAUSE: "to have travel insurance" }, topicArea: "travel" },
        { en: "The most important thing is to meet the client's expectations.", bn: "সবচেয়ে গুরুত্বপূর্ণ বিষয় হলো ক্লায়েন্টের প্রত্যাশা পূরণ করা।", slotValues: { CLAUSE: "to meet the client's expectations" }, topicArea: "work" },
        { en: "The most important thing is to eat a balanced diet.", bn: "সবচেয়ে গুরুত্বপূর্ণ বিষয় হলো সুষম খাদ্য খাওয়া।", slotValues: { CLAUSE: "to eat a balanced diet" }, topicArea: "food" },
        { en: "The most important thing is to never stop asking questions.", bn: "সবচেয়ে গুরুত্বপূর্ণ বিষয় হলো প্রশ্ন করা কখনো বন্ধ না করা।", slotValues: { CLAUSE: "to never stop asking questions" }, topicArea: "education" },
        { en: "The most important thing is to listen to each other.", bn: "সবচেয়ে গুরুত্বপূর্ণ বিষয় হলো একে অপরের কথা শোনা।", slotValues: { CLAUSE: "to listen to each other" }, topicArea: "relationships" },
        { en: "The most important thing is to follow your doctor's advice.", bn: "সবচেয়ে গুরুত্বপূর্ণ বিষয় হলো ডাক্তারের পরামর্শ মেনে চলা।", slotValues: { CLAUSE: "to follow your doctor's advice" }, topicArea: "health" },
        { en: "The most important thing is to enjoy the experience.", bn: "সবচেয়ে গুরুত্বপূর্ণ বিষয় হলো অভিজ্ঞতাটি উপভোগ করা।", slotValues: { CLAUSE: "to enjoy the experience" }, topicArea: "travel" },
      ],
      formality: "casual",
      difficulty: "advanced",
      usageNote: "Highlights the single most critical factor. Very effective for summarizing advice or priorities.",
      usageNote_bn: "একক সবচেয়ে গুরুত্বপূর্ণ বিষয় তুলে ধরে। পরামর্শ বা অগ্রাধিকার সংক্ষেপ করার জন্য খুবই কার্যকর।",
      banglaStructureMap: "সবচেয়ে গুরুত্বপূর্ণ বিষয় হলো (The most important thing is) + [উপবাক্য] (CLAUSE)",
    },
    {
      id: "R15.4",
      formula: "It matters whether [CLAUSE]",
      formula_bn: "[উপবাক্য] কিনা তা গুরুত্বপূর্ণ",
      patternName: "It Matters Whether",
      patternName_bn: "গুরুত্বপূর্ণ কিনা",
      slots: [
        {
          name: "CLAUSE",
          description: "A condition or choice that has significance",
          description_bn: "একটি শর্ত বা পছন্দ যার তাৎপর্য আছে",
          acceptedTypes: ["clause"],
          examples: ["you arrive on time", "the food is fresh", "the team communicates well"],
        },
      ],
      examples: [
        { en: "It matters whether you arrive on time.", bn: "তুমি সময়মতো পৌঁছাও কিনা তা গুরুত্বপূর্ণ।", slotValues: { CLAUSE: "you arrive on time" }, topicArea: "work" },
        { en: "It matters whether the food is fresh or not.", bn: "খাবার তাজা কিনা তা গুরুত্বপূর্ণ।", slotValues: { CLAUSE: "the food is fresh or not" }, topicArea: "food" },
        { en: "It matters whether the team communicates well.", bn: "দল ভালোভাবে যোগাযোগ করে কিনা তা গুরুত্বপূর্ণ।", slotValues: { CLAUSE: "the team communicates well" }, topicArea: "work" },
        { en: "It matters whether you study regularly.", bn: "তুমি নিয়মিত পড়ো কিনা তা গুরুত্বপূর্ণ।", slotValues: { CLAUSE: "you study regularly" }, topicArea: "education" },
        { en: "It matters whether you say sorry or not.", bn: "তুমি দুঃখিত বলো কিনা তা গুরুত্বপূর্ণ।", slotValues: { CLAUSE: "you say sorry or not" }, topicArea: "relationships" },
        { en: "It matters whether you get enough sleep.", bn: "তুমি পর্যাপ্ত ঘুম পাও কিনা তা গুরুত্বপূর্ণ।", slotValues: { CLAUSE: "you get enough sleep" }, topicArea: "health" },
        { en: "It matters whether you read reviews before buying.", bn: "কেনার আগে রিভিউ পড়ো কিনা তা গুরুত্বপূর্ণ।", slotValues: { CLAUSE: "you read reviews before buying" }, topicArea: "shopping" },
        { en: "It matters whether you book early or last minute.", bn: "তুমি আগে বুক করো নাকি শেষ মুহূর্তে তা গুরুত্বপূর্ণ।", slotValues: { CLAUSE: "you book early or last minute" }, topicArea: "travel" },
        { en: "It matters whether the recipe uses butter or oil.", bn: "রেসিপিতে মাখন ব্যবহার হয় নাকি তেল তা গুরুত্বপূর্ণ।", slotValues: { CLAUSE: "the recipe uses butter or oil" }, topicArea: "food" },
        { en: "It matters whether students understand or just memorize.", bn: "ছাত্ররা বোঝে নাকি শুধু মুখস্থ করে তা গুরুত্বপূর্ণ।", slotValues: { CLAUSE: "students understand or just memorize" }, topicArea: "education" },
        { en: "It matters whether you show up for the people you love.", bn: "তুমি তোমার প্রিয়জনদের জন্য উপস্থিত থাকো কিনা তা গুরুত্বপূর্ণ।", slotValues: { CLAUSE: "you show up for the people you love" }, topicArea: "relationships" },
        { en: "It matters whether you warm up before exercising.", bn: "ব্যায়ামের আগে ওয়ার্ম আপ করো কিনা তা গুরুত্বপূর্ণ।", slotValues: { CLAUSE: "you warm up before exercising" }, topicArea: "health" },
        { en: "It matters whether the product has a warranty.", bn: "পণ্যটির ওয়ারেন্টি আছে কিনা তা গুরুত্বপূর্ণ।", slotValues: { CLAUSE: "the product has a warranty" }, topicArea: "shopping" },
        { en: "It matters whether you prepare for the presentation.", bn: "তুমি উপস্থাপনার জন্য প্রস্তুতি নাও কিনা তা গুরুত্বপূর্ণ।", slotValues: { CLAUSE: "you prepare for the presentation" }, topicArea: "work" },
        { en: "It matters whether you travel during peak season or off-season.", bn: "তুমি পিক সিজনে ভ্রমণ করো নাকি অফ-সিজনে তা গুরুত্বপূর্ণ।", slotValues: { CLAUSE: "you travel during peak season or off-season" }, topicArea: "travel" },
      ],
      formality: "polite",
      difficulty: "advanced",
      usageNote: "Draws attention to a specific condition or choice that has real consequences.",
      usageNote_bn: "একটি নির্দিষ্ট শর্ত বা পছন্দের দিকে মনোযোগ আকর্ষণ করে যার প্রকৃত ফলাফল আছে।",
      banglaStructureMap: "[উপবাক্য] কিনা (whether CLAUSE) + তা গুরুত্বপূর্ণ (it matters)",
    },
    {
      id: "R15.5",
      formula: "[THING] is essential for [THING]",
      formula_bn: "[জিনিস] [জিনিস]-এর জন্য অপরিহার্য",
      patternName: "Is Essential For",
      patternName_bn: "অপরিহার্য",
      slots: [
        {
          name: "THING",
          description: "Two things: the first is the essential element, the second is what it's essential for",
          description_bn: "দুটি জিনিস: প্রথমটি অপরিহার্য উপাদান, দ্বিতীয়টি এটি কিসের জন্য অপরিহার্য",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["Practice, mastering any skill", "Water, good health", "Feedback, professional growth"],
        },
      ],
      examples: [
        { en: "Practice is essential for mastering any skill.", bn: "যেকোনো দক্ষতা আয়ত্ত করার জন্য অনুশীলন অপরিহার্য।", slotValues: { THING: "Practice, mastering any skill" }, topicArea: "education" },
        { en: "Water is essential for good health.", bn: "সুস্বাস্থ্যের জন্য পানি অপরিহার্য।", slotValues: { THING: "Water, good health" }, topicArea: "health" },
        { en: "Feedback is essential for professional growth.", bn: "পেশাদার বৃদ্ধির জন্য প্রতিক্রিয়া অপরিহার্য।", slotValues: { THING: "Feedback, professional growth" }, topicArea: "work" },
        { en: "Fresh herbs are essential for authentic flavor.", bn: "প্রকৃত স্বাদের জন্য তাজা ভেষজ অপরিহার্য।", slotValues: { THING: "Fresh herbs, authentic flavor" }, topicArea: "food" },
        { en: "Respect is essential for any healthy relationship.", bn: "যেকোনো সুস্থ সম্পর্কের জন্য সম্মান অপরিহার্য।", slotValues: { THING: "Respect, any healthy relationship" }, topicArea: "relationships" },
        { en: "Research is essential for making smart purchases.", bn: "বুদ্ধিমান কেনাকাটার জন্য গবেষণা অপরিহার্য।", slotValues: { THING: "Research, making smart purchases" }, topicArea: "shopping" },
        { en: "A valid passport is essential for international travel.", bn: "আন্তর্জাতিক ভ্রমণের জন্য বৈধ পাসপোর্ট অপরিহার্য।", slotValues: { THING: "A valid passport, international travel" }, topicArea: "travel" },
        { en: "Time management is essential for meeting deadlines.", bn: "সময়সীমা পূরণের জন্য সময় ব্যবস্থাপনা অপরিহার্য।", slotValues: { THING: "Time management, meeting deadlines" }, topicArea: "work" },
        { en: "Sleep is essential for physical recovery.", bn: "শারীরিক পুনরুদ্ধারের জন্য ঘুম অপরিহার্য।", slotValues: { THING: "Sleep, physical recovery" }, topicArea: "health" },
        { en: "Curiosity is essential for lifelong learning.", bn: "আজীবন শেখার জন্য কৌতূহল অপরিহার্য।", slotValues: { THING: "Curiosity, lifelong learning" }, topicArea: "education" },
        { en: "Good timing is essential for baking.", bn: "বেকিংয়ের জন্য সঠিক সময় অপরিহার্য।", slotValues: { THING: "Good timing, baking" }, topicArea: "food" },
        { en: "Empathy is essential for understanding others.", bn: "অন্যদের বোঝার জন্য সহানুভূতি অপরিহার্য।", slotValues: { THING: "Empathy, understanding others" }, topicArea: "relationships" },
        { en: "A budget is essential for controlling expenses.", bn: "খরচ নিয়ন্ত্রণের জন্য বাজেট অপরিহার্য।", slotValues: { THING: "A budget, controlling expenses" }, topicArea: "shopping" },
        { en: "Flexibility is essential for enjoyable travel.", bn: "আনন্দদায়ক ভ্রমণের জন্য নমনীয়তা অপরিহার্য।", slotValues: { THING: "Flexibility, enjoyable travel" }, topicArea: "travel" },
        { en: "Discipline is essential for achieving any goal.", bn: "যেকোনো লক্ষ্য অর্জনের জন্য শৃঙ্খলা অপরিহার্য।", slotValues: { THING: "Discipline, achieving any goal" }, topicArea: "daily_life" },
      ],
      formality: "formal",
      difficulty: "advanced",
      usageNote: "Stronger than 'important'. States that something is absolutely necessary, not just helpful.",
      usageNote_bn: "'important'-এর চেয়ে শক্তিশালী। বলে যে কিছু একেবারে প্রয়োজনীয়, শুধু সহায়ক নয়।",
      banglaStructureMap: "[জিনিস] (Subject) + [জিনিস]-এর জন্য (for THING) + অপরিহার্য (is essential)",
    },
  ],
};
