import { PatternCategory } from "@/types/pattern";

export const categoryR3: PatternCategory = {
  id: "R3",
  slug: "expressing-assumptions",
  name: "Expressing Assumptions",
  name_bn: "অনুমান প্রকাশ করা",
  description:
    "Express what you believe or assume to be true based on available information.",
  description_bn:
    "উপলব্ধ তথ্যের ভিত্তিতে আপনি যা সত্য বলে বিশ্বাস বা অনুমান করেন তা প্রকাশ করুন।",
  icon: "🤔",
  group: "R",
  groupName: "Logical & Discourse Patterns",
  groupName_bn: "যৌক্তিক ও বক্তৃতা প্যাটার্ন",
  difficulty: "intermediate",
  patterns: [
    {
      id: "R3.1",
      formula: "I assume [CLAUSE]",
      formula_bn: "আমি ধরে নিচ্ছি [উপবাক্য]",
      patternName: "Making an Assumption",
      patternName_bn: "অনুমান করা",
      slots: [
        {
          name: "CLAUSE",
          description: "Something you believe to be true without confirmation",
          description_bn: "এমন কিছু যা আপনি নিশ্চিতকরণ ছাড়াই সত্য বলে বিশ্বাস করেন",
          acceptedTypes: ["clause"],
          examples: [
            "you've already eaten",
            "the meeting is at 10",
            "everyone knows about it",
          ],
        },
      ],
      examples: [
        {
          en: "I assume you've already eaten.",
          bn: "আমি ধরে নিচ্ছি তুমি ইতিমধ্যে খেয়েছ।",
          slotValues: { CLAUSE: "you've already eaten" },
          topicArea: "food",
        },
        {
          en: "I assume the meeting is at 10.",
          bn: "আমি ধরে নিচ্ছি মিটিং ১০টায়।",
          slotValues: { CLAUSE: "the meeting is at 10" },
          topicArea: "work",
        },
        {
          en: "I assume everyone knows about it.",
          bn: "আমি ধরে নিচ্ছি সবাই এটা জানে।",
          slotValues: { CLAUSE: "everyone knows about it" },
          topicArea: "daily_life",
        },
        {
          en: "I assume you're coming to the party.",
          bn: "আমি ধরে নিচ্ছি তুমি পার্টিতে আসছ।",
          slotValues: { CLAUSE: "you're coming to the party" },
          topicArea: "relationships",
        },
        {
          en: "I assume the report is ready.",
          bn: "আমি ধরে নিচ্ছি রিপোর্টটি প্রস্তুত।",
          slotValues: { CLAUSE: "the report is ready" },
          topicArea: "work",
        },
        {
          en: "I assume the store is open on Sundays.",
          bn: "আমি ধরে নিচ্ছি দোকানটি রবিবারে খোলা থাকে।",
          slotValues: { CLAUSE: "the store is open on Sundays" },
          topicArea: "shopping",
        },
        {
          en: "I assume you have travel insurance.",
          bn: "আমি ধরে নিচ্ছি আপনার ট্রাভেল ইন্স্যুরেন্স আছে।",
          slotValues: { CLAUSE: "you have travel insurance" },
          topicArea: "travel",
        },
        {
          en: "I assume the exam results are out.",
          bn: "আমি ধরে নিচ্ছি পরীক্ষার ফলাফল প্রকাশিত হয়েছে।",
          slotValues: { CLAUSE: "the exam results are out" },
          topicArea: "education",
        },
        {
          en: "I assume you've taken your medicine.",
          bn: "আমি ধরে নিচ্ছি তুমি তোমার ওষুধ খেয়েছ।",
          slotValues: { CLAUSE: "you've taken your medicine" },
          topicArea: "health",
        },
        {
          en: "I assume the reservation is confirmed.",
          bn: "আমি ধরে নিচ্ছি রিজার্ভেশন নিশ্চিত হয়েছে।",
          slotValues: { CLAUSE: "the reservation is confirmed" },
          topicArea: "food",
        },
        {
          en: "I assume you've read the email.",
          bn: "আমি ধরে নিচ্ছি তুমি ইমেইলটি পড়েছ।",
          slotValues: { CLAUSE: "you've read the email" },
          topicArea: "work",
        },
        {
          en: "I assume the taxi is on its way.",
          bn: "আমি ধরে নিচ্ছি ট্যাক্সি আসছে।",
          slotValues: { CLAUSE: "the taxi is on its way" },
          topicArea: "travel",
        },
        {
          en: "I assume they're still together.",
          bn: "আমি ধরে নিচ্ছি তারা এখনও একসাথে আছে।",
          slotValues: { CLAUSE: "they're still together" },
          topicArea: "relationships",
        },
        {
          en: "I assume the homework is due tomorrow.",
          bn: "আমি ধরে নিচ্ছি হোমওয়ার্ক আগামীকাল জমা দিতে হবে।",
          slotValues: { CLAUSE: "the homework is due tomorrow" },
          topicArea: "education",
        },
        {
          en: "I assume there's no dress code.",
          bn: "আমি ধরে নিচ্ছি কোনো পোশাকের নিয়ম নেই।",
          slotValues: { CLAUSE: "there's no dress code" },
          topicArea: "daily_life",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "Used to state something you believe to be true. It invites the other person to confirm or correct you.",
      usageNote_bn:
        "আপনি যা সত্য বলে বিশ্বাস করেন তা বলতে ব্যবহৃত হয়। এটি অন্য ব্যক্তিকে নিশ্চিত করতে বা সংশোধন করতে আমন্ত্রণ জানায়।",
      combinableWith: ["R3.2", "R3.3"],
      banglaStructureMap:
        "আমি (Subject) + ধরে নিচ্ছি (Verb) + [CLAUSE] (Object clause)",
    },
    {
      id: "R3.2",
      formula: "I take it that [CLAUSE]",
      formula_bn: "আমি মনে করছি যে [উপবাক্য]",
      patternName: "Inferring from Context",
      patternName_bn: "প্রসঙ্গ থেকে অনুমান",
      slots: [
        {
          name: "CLAUSE",
          description: "Something you infer from the situation or context",
          description_bn: "পরিস্থিতি বা প্রসঙ্গ থেকে আপনি যা অনুমান করেন",
          acceptedTypes: ["clause"],
          examples: [
            "you don't agree",
            "the deal is off",
            "you're not interested",
          ],
        },
      ],
      examples: [
        {
          en: "I take it that you don't agree.",
          bn: "আমি মনে করছি যে তুমি একমত নও।",
          slotValues: { CLAUSE: "you don't agree" },
          topicArea: "work",
        },
        {
          en: "I take it that the deal is off.",
          bn: "আমি মনে করছি যে চুক্তিটি বাতিল।",
          slotValues: { CLAUSE: "the deal is off" },
          topicArea: "work",
        },
        {
          en: "I take it that you're not interested.",
          bn: "আমি মনে করছি যে তুমি আগ্রহী নও।",
          slotValues: { CLAUSE: "you're not interested" },
          topicArea: "relationships",
        },
        {
          en: "I take it that the flight was delayed.",
          bn: "আমি মনে করছি যে ফ্লাইট দেরি হয়েছিল।",
          slotValues: { CLAUSE: "the flight was delayed" },
          topicArea: "travel",
        },
        {
          en: "I take it that you've finished the assignment.",
          bn: "আমি মনে করছি যে তুমি অ্যাসাইনমেন্ট শেষ করেছ।",
          slotValues: { CLAUSE: "you've finished the assignment" },
          topicArea: "education",
        },
        {
          en: "I take it that the food wasn't good.",
          bn: "আমি মনে করছি যে খাবার ভালো ছিল না।",
          slotValues: { CLAUSE: "the food wasn't good" },
          topicArea: "food",
        },
        {
          en: "I take it that you're feeling better.",
          bn: "আমি মনে করছি যে তুমি ভালো অনুভব করছ।",
          slotValues: { CLAUSE: "you're feeling better" },
          topicArea: "health",
        },
        {
          en: "I take it that you've already spoken to him.",
          bn: "আমি মনে করছি যে তুমি ইতিমধ্যে তার সাথে কথা বলেছ।",
          slotValues: { CLAUSE: "you've already spoken to him" },
          topicArea: "relationships",
        },
        {
          en: "I take it that the project has been approved.",
          bn: "আমি মনে করছি যে প্রকল্পটি অনুমোদিত হয়েছে।",
          slotValues: { CLAUSE: "the project has been approved" },
          topicArea: "work",
        },
        {
          en: "I take it that you found a good deal.",
          bn: "আমি মনে করছি যে তুমি একটি ভালো দাম পেয়েছ।",
          slotValues: { CLAUSE: "you found a good deal" },
          topicArea: "shopping",
        },
        {
          en: "I take it that the test went well.",
          bn: "আমি মনে করছি যে পরীক্ষা ভালো হয়েছে।",
          slotValues: { CLAUSE: "the test went well" },
          topicArea: "education",
        },
        {
          en: "I take it that you've booked the hotel.",
          bn: "আমি মনে করছি যে তুমি হোটেল বুক করেছ।",
          slotValues: { CLAUSE: "you've booked the hotel" },
          topicArea: "travel",
        },
        {
          en: "I take it that the meeting is off.",
          bn: "আমি মনে করছি যে মিটিং বাতিল।",
          slotValues: { CLAUSE: "the meeting is off" },
          topicArea: "work",
        },
        {
          en: "I take it that the weather will clear up.",
          bn: "আমি মনে করছি যে আবহাওয়া পরিষ্কার হবে।",
          slotValues: { CLAUSE: "the weather will clear up" },
          topicArea: "daily_life",
        },
        {
          en: "I take it that you're ready to order.",
          bn: "আমি মনে করছি যে আপনি অর্ডার দিতে প্রস্তুত।",
          slotValues: { CLAUSE: "you're ready to order" },
          topicArea: "food",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "A slightly more sophisticated way to express an assumption. Implies you have observed clues that led you to this conclusion.",
      usageNote_bn:
        "অনুমান প্রকাশের একটি সামান্য বেশি পরিশীলিত উপায়। ইঙ্গিত দেয় যে আপনি এমন সূত্র পর্যবেক্ষণ করেছেন যা আপনাকে এই সিদ্ধান্তে নিয়ে এসেছে।",
      combinableWith: ["R3.1"],
      banglaStructureMap:
        "আমি (Subject) + মনে করছি যে (Verb phrase) + [CLAUSE] (Object clause)",
    },
    {
      id: "R3.3",
      formula: "I suppose [CLAUSE]",
      formula_bn: "আমি মনে করি [উপবাক্য]",
      patternName: "Tentative Assumption",
      patternName_bn: "সতর্ক অনুমান",
      slots: [
        {
          name: "CLAUSE",
          description: "Something you think is probably true but are not certain",
          description_bn: "এমন কিছু যা আপনি সম্ভবত সত্য মনে করেন কিন্তু নিশ্চিত নন",
          acceptedTypes: ["clause"],
          examples: [
            "that's fair enough",
            "we should try",
            "it could work",
          ],
        },
      ],
      examples: [
        {
          en: "I suppose that's fair enough.",
          bn: "আমি মনে করি এটা যথেষ্ট ন্যায্য।",
          slotValues: { CLAUSE: "that's fair enough" },
          topicArea: "daily_life",
        },
        {
          en: "I suppose we should try.",
          bn: "আমি মনে করি আমাদের চেষ্টা করা উচিত।",
          slotValues: { CLAUSE: "we should try" },
          topicArea: "work",
        },
        {
          en: "I suppose it could work.",
          bn: "আমি মনে করি এটা কাজ করতে পারে।",
          slotValues: { CLAUSE: "it could work" },
          topicArea: "work",
        },
        {
          en: "I suppose you're right about that.",
          bn: "আমি মনে করি তুমি এ ব্যাপারে ঠিক বলছ।",
          slotValues: { CLAUSE: "you're right about that" },
          topicArea: "relationships",
        },
        {
          en: "I suppose the traffic will be bad.",
          bn: "আমি মনে করি যানজট খারাপ হবে।",
          slotValues: { CLAUSE: "the traffic will be bad" },
          topicArea: "travel",
        },
        {
          en: "I suppose we can skip the appetizer.",
          bn: "আমি মনে করি আমরা অ্যাপেটাইজার বাদ দিতে পারি।",
          slotValues: { CLAUSE: "we can skip the appetizer" },
          topicArea: "food",
        },
        {
          en: "I suppose it's worth a shot.",
          bn: "আমি মনে করি চেষ্টা করে দেখা যায়।",
          slotValues: { CLAUSE: "it's worth a shot" },
          topicArea: "daily_life",
        },
        {
          en: "I suppose the doctor knows best.",
          bn: "আমি মনে করি ডাক্তার সবচেয়ে ভালো জানেন।",
          slotValues: { CLAUSE: "the doctor knows best" },
          topicArea: "health",
        },
        {
          en: "I suppose we'll have to wait and see.",
          bn: "আমি মনে করি আমাদের অপেক্ষা করতে হবে।",
          slotValues: { CLAUSE: "we'll have to wait and see" },
          topicArea: "daily_life",
        },
        {
          en: "I suppose the price is negotiable.",
          bn: "আমি মনে করি দাম আলোচনাসাপেক্ষ।",
          slotValues: { CLAUSE: "the price is negotiable" },
          topicArea: "shopping",
        },
        {
          en: "I suppose the homework isn't too difficult.",
          bn: "আমি মনে করি হোমওয়ার্কটি খুব কঠিন নয়।",
          slotValues: { CLAUSE: "the homework isn't too difficult" },
          topicArea: "education",
        },
        {
          en: "I suppose he'll call back later.",
          bn: "আমি মনে করি সে পরে আবার ফোন করবে।",
          slotValues: { CLAUSE: "he'll call back later" },
          topicArea: "relationships",
        },
        {
          en: "I suppose we could take the bus.",
          bn: "আমি মনে করি আমরা বাসে যেতে পারি।",
          slotValues: { CLAUSE: "we could take the bus" },
          topicArea: "travel",
        },
        {
          en: "I suppose the interview went okay.",
          bn: "আমি মনে করি ইন্টারভিউটা ঠিকঠাক হয়েছে।",
          slotValues: { CLAUSE: "the interview went okay" },
          topicArea: "work",
        },
        {
          en: "I suppose a bit of exercise wouldn't hurt.",
          bn: "আমি মনে করি একটু ব্যায়াম করলে ক্ষতি হবে না।",
          slotValues: { CLAUSE: "a bit of exercise wouldn't hurt" },
          topicArea: "health",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "Expresses a tentative or reluctant assumption. Often used when you are not fully convinced but accept the possibility.",
      usageNote_bn:
        "একটি সতর্ক বা অনিচ্ছুক অনুমান প্রকাশ করে। প্রায়ই ব্যবহৃত হয় যখন আপনি পুরোপুরি নিশ্চিত নন কিন্তু সম্ভাবনা মেনে নেন।",
      combinableWith: ["R3.1"],
      banglaStructureMap:
        "আমি (Subject) + মনে করি (Verb) + [CLAUSE] (Object clause)",
    },
    {
      id: "R3.4",
      formula: "Presumably, [CLAUSE]",
      formula_bn: "সম্ভবত, [উপবাক্য]",
      patternName: "Educated Guess",
      patternName_bn: "তথ্যভিত্তিক অনুমান",
      slots: [
        {
          name: "CLAUSE",
          description: "Something that is likely true based on what you know",
          description_bn: "আপনি যা জানেন তার ভিত্তিতে সম্ভবত সত্য কিছু",
          acceptedTypes: ["clause"],
          examples: [
            "they'll announce it soon",
            "the price includes tax",
            "she already knows",
          ],
        },
      ],
      examples: [
        {
          en: "Presumably, they'll announce it soon.",
          bn: "সম্ভবত, তারা শীঘ্রই এটা ঘোষণা করবে।",
          slotValues: { CLAUSE: "they'll announce it soon" },
          topicArea: "work",
        },
        {
          en: "Presumably, the price includes tax.",
          bn: "সম্ভবত, দামের মধ্যে ট্যাক্স অন্তর্ভুক্ত।",
          slotValues: { CLAUSE: "the price includes tax" },
          topicArea: "shopping",
        },
        {
          en: "Presumably, she already knows.",
          bn: "সম্ভবত, সে ইতিমধ্যে জানে।",
          slotValues: { CLAUSE: "she already knows" },
          topicArea: "relationships",
        },
        {
          en: "Presumably, the bus will arrive on time.",
          bn: "সম্ভবত, বাস সময়মতো আসবে।",
          slotValues: { CLAUSE: "the bus will arrive on time" },
          topicArea: "travel",
        },
        {
          en: "Presumably, the test will cover all chapters.",
          bn: "সম্ভবত, পরীক্ষায় সব অধ্যায় থাকবে।",
          slotValues: { CLAUSE: "the test will cover all chapters" },
          topicArea: "education",
        },
        {
          en: "Presumably, the restaurant takes reservations.",
          bn: "সম্ভবত, রেস্তোরাঁ রিজার্ভেশন নেয়।",
          slotValues: { CLAUSE: "the restaurant takes reservations" },
          topicArea: "food",
        },
        {
          en: "Presumably, the side effects are temporary.",
          bn: "সম্ভবত, পার্শ্বপ্রতিক্রিয়াগুলো সাময়িক।",
          slotValues: { CLAUSE: "the side effects are temporary" },
          topicArea: "health",
        },
        {
          en: "Presumably, someone will be there to help.",
          bn: "সম্ভবত, সেখানে কেউ সাহায্য করতে থাকবে।",
          slotValues: { CLAUSE: "someone will be there to help" },
          topicArea: "daily_life",
        },
        {
          en: "Presumably, the contract has been signed.",
          bn: "সম্ভবত, চুক্তিটি স্বাক্ষরিত হয়েছে।",
          slotValues: { CLAUSE: "the contract has been signed" },
          topicArea: "work",
        },
        {
          en: "Presumably, the flights are more expensive in summer.",
          bn: "সম্ভবত, গ্রীষ্মে ফ্লাইট বেশি ব্যয়বহুল।",
          slotValues: { CLAUSE: "the flights are more expensive in summer" },
          topicArea: "travel",
        },
        {
          en: "Presumably, the warranty covers this issue.",
          bn: "সম্ভবত, ওয়ারেন্টি এই সমস্যাটি কভার করে।",
          slotValues: { CLAUSE: "the warranty covers this issue" },
          topicArea: "shopping",
        },
        {
          en: "Presumably, they're planning a surprise.",
          bn: "সম্ভবত, তারা একটি চমক পরিকল্পনা করছে।",
          slotValues: { CLAUSE: "they're planning a surprise" },
          topicArea: "relationships",
        },
        {
          en: "Presumably, the results will be published online.",
          bn: "সম্ভবত, ফলাফল অনলাইনে প্রকাশ করা হবে।",
          slotValues: { CLAUSE: "the results will be published online" },
          topicArea: "education",
        },
        {
          en: "Presumably, the clinic is closed on weekends.",
          bn: "সম্ভবত, ক্লিনিকটি সপ্তাহান্তে বন্ধ থাকে।",
          slotValues: { CLAUSE: "the clinic is closed on weekends" },
          topicArea: "health",
        },
        {
          en: "Presumably, the deadline won't change.",
          bn: "সম্ভবত, সময়সীমা পরিবর্তন হবে না।",
          slotValues: { CLAUSE: "the deadline won't change" },
          topicArea: "work",
        },
      ],
      formality: "formal",
      difficulty: "intermediate",
      usageNote:
        "A more formal way of expressing an assumption. Often used in professional or academic contexts.",
      usageNote_bn:
        "অনুমান প্রকাশের একটি আরও আনুষ্ঠানিক উপায়। প্রায়ই পেশাদার বা একাডেমিক প্রসঙ্গে ব্যবহৃত হয়।",
      combinableWith: ["R3.1"],
      banglaStructureMap:
        "সম্ভবত (Adverb) + [CLAUSE] (Complete statement)",
    },
    {
      id: "R3.5",
      formula: "I would imagine [CLAUSE]",
      formula_bn: "আমার ধারণা [উপবাক্য]",
      patternName: "Speculative Assumption",
      patternName_bn: "অনুমানমূলক ধারণা",
      slots: [
        {
          name: "CLAUSE",
          description: "Something you speculate based on your understanding",
          description_bn: "আপনার বোঝাপড়ার ভিত্তিতে আপনি যা অনুমান করেন",
          acceptedTypes: ["clause"],
          examples: [
            "it's quite expensive",
            "they'd want to know",
            "the traffic is bad right now",
          ],
        },
      ],
      examples: [
        {
          en: "I would imagine it's quite expensive.",
          bn: "আমার ধারণা এটা বেশ ব্যয়বহুল।",
          slotValues: { CLAUSE: "it's quite expensive" },
          topicArea: "shopping",
        },
        {
          en: "I would imagine they'd want to know.",
          bn: "আমার ধারণা তারা জানতে চাইবে।",
          slotValues: { CLAUSE: "they'd want to know" },
          topicArea: "relationships",
        },
        {
          en: "I would imagine the traffic is bad right now.",
          bn: "আমার ধারণা এখন যানজট খারাপ।",
          slotValues: { CLAUSE: "the traffic is bad right now" },
          topicArea: "travel",
        },
        {
          en: "I would imagine the boss will approve.",
          bn: "আমার ধারণা বস অনুমোদন দেবেন।",
          slotValues: { CLAUSE: "the boss will approve" },
          topicArea: "work",
        },
        {
          en: "I would imagine the exam is next Friday.",
          bn: "আমার ধারণা পরীক্ষা আগামী শুক্রবার।",
          slotValues: { CLAUSE: "the exam is next Friday" },
          topicArea: "education",
        },
        {
          en: "I would imagine the restaurant is packed on weekends.",
          bn: "আমার ধারণা সপ্তাহান্তে রেস্তোরাঁ ভিড় থাকে।",
          slotValues: { CLAUSE: "the restaurant is packed on weekends" },
          topicArea: "food",
        },
        {
          en: "I would imagine the recovery will take time.",
          bn: "আমার ধারণা সুস্থ হতে সময় লাগবে।",
          slotValues: { CLAUSE: "the recovery will take time" },
          topicArea: "health",
        },
        {
          en: "I would imagine most people would agree.",
          bn: "আমার ধারণা বেশিরভাগ মানুষ একমত হবে।",
          slotValues: { CLAUSE: "most people would agree" },
          topicArea: "daily_life",
        },
        {
          en: "I would imagine the hotel is fully booked.",
          bn: "আমার ধারণা হোটেলে জায়গা নেই।",
          slotValues: { CLAUSE: "the hotel is fully booked" },
          topicArea: "travel",
        },
        {
          en: "I would imagine you'd need at least a week.",
          bn: "আমার ধারণা তোমার কমপক্ষে এক সপ্তাহ লাগবে।",
          slotValues: { CLAUSE: "you'd need at least a week" },
          topicArea: "work",
        },
        {
          en: "I would imagine they sell out quickly.",
          bn: "আমার ধারণা এগুলো দ্রুত শেষ হয়ে যায়।",
          slotValues: { CLAUSE: "they sell out quickly" },
          topicArea: "shopping",
        },
        {
          en: "I would imagine the kids would love it.",
          bn: "আমার ধারণা বাচ্চারা এটা পছন্দ করবে।",
          slotValues: { CLAUSE: "the kids would love it" },
          topicArea: "relationships",
        },
        {
          en: "I would imagine the library has that book.",
          bn: "আমার ধারণা লাইব্রেরিতে সেই বইটি আছে।",
          slotValues: { CLAUSE: "the library has that book" },
          topicArea: "education",
        },
        {
          en: "I would imagine the symptoms will fade.",
          bn: "আমার ধারণা উপসর্গগুলো কমে যাবে।",
          slotValues: { CLAUSE: "the symptoms will fade" },
          topicArea: "health",
        },
        {
          en: "I would imagine it's the best option available.",
          bn: "আমার ধারণা এটাই উপলব্ধ সেরা বিকল্প।",
          slotValues: { CLAUSE: "it's the best option available" },
          topicArea: "daily_life",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "A softer and more speculative way to express what you think is likely. Sounds thoughtful and non-assertive.",
      usageNote_bn:
        "আপনি যা সম্ভাব্য মনে করেন তা প্রকাশের একটি নরম ও অনুমানমূলক উপায়। চিন্তাশীল ও অদৃঢ় শোনায়।",
      combinableWith: ["R3.3"],
      banglaStructureMap:
        "আমার ধারণা (Subject + Noun) + [CLAUSE] (Object clause)",
    },
  ],
};
