import { PatternCategory } from "@/types/pattern";

export const categoryR4: PatternCategory = {
  id: "R4",
  slug: "correcting-misunderstandings",
  name: "Correcting Misunderstandings",
  name_bn: "ভুল বোঝাবুঝি সংশোধন",
  description:
    "Politely correct misunderstandings and clarify what you actually meant.",
  description_bn:
    "বিনয়ের সাথে ভুল বোঝাবুঝি সংশোধন করুন এবং আপনি আসলে কী বোঝাতে চেয়েছিলেন তা স্পষ্ট করুন।",
  icon: "🔄",
  group: "R",
  groupName: "Logical & Discourse Patterns",
  groupName_bn: "যৌক্তিক ও বক্তৃতা প্যাটার্ন",
  difficulty: "intermediate",
  patterns: [
    {
      id: "R4.1",
      formula: "Actually, [CORRECTION]",
      formula_bn: "আসলে, [সংশোধন]",
      patternName: "Quick Correction",
      patternName_bn: "দ্রুত সংশোধন",
      slots: [
        {
          name: "CORRECTION",
          description: "The correct information or statement",
          description_bn: "সঠিক তথ্য বা বিবৃতি",
          acceptedTypes: ["clause"],
          examples: [
            "I meant next Friday",
            "it's the other way around",
            "that's not quite right",
          ],
        },
      ],
      examples: [
        {
          en: "Actually, I meant next Friday.",
          bn: "আসলে, আমি আগামী শুক্রবার বোঝাতে চেয়েছিলাম।",
          slotValues: { CORRECTION: "I meant next Friday" },
          topicArea: "work",
        },
        {
          en: "Actually, it's the other way around.",
          bn: "আসলে, ব্যাপারটা উল্টো।",
          slotValues: { CORRECTION: "it's the other way around" },
          topicArea: "daily_life",
        },
        {
          en: "Actually, the meeting is at 3, not 2.",
          bn: "আসলে, মিটিং ৩টায়, ২টায় নয়।",
          slotValues: { CORRECTION: "the meeting is at 3, not 2" },
          topicArea: "work",
        },
        {
          en: "Actually, she's my cousin, not my sister.",
          bn: "আসলে, সে আমার কাজিন, আমার বোন নয়।",
          slotValues: { CORRECTION: "she's my cousin, not my sister" },
          topicArea: "relationships",
        },
        {
          en: "Actually, I ordered the chicken, not the fish.",
          bn: "আসলে, আমি মুরগি অর্ডার করেছিলাম, মাছ নয়।",
          slotValues: { CORRECTION: "I ordered the chicken, not the fish" },
          topicArea: "food",
        },
        {
          en: "Actually, the exam is on Monday.",
          bn: "আসলে, পরীক্ষা সোমবারে।",
          slotValues: { CORRECTION: "the exam is on Monday" },
          topicArea: "education",
        },
        {
          en: "Actually, the flight leaves at 6 AM.",
          bn: "আসলে, ফ্লাইট সকাল ৬টায় ছাড়ে।",
          slotValues: { CORRECTION: "the flight leaves at 6 AM" },
          topicArea: "travel",
        },
        {
          en: "Actually, the dosage is two tablets, not one.",
          bn: "আসলে, ডোজ দুটি ট্যাবলেট, একটি নয়।",
          slotValues: { CORRECTION: "the dosage is two tablets, not one" },
          topicArea: "health",
        },
        {
          en: "Actually, the sale ended yesterday.",
          bn: "আসলে, সেল গতকাল শেষ হয়ে গেছে।",
          slotValues: { CORRECTION: "the sale ended yesterday" },
          topicArea: "shopping",
        },
        {
          en: "Actually, I'm from Dhaka, not Chittagong.",
          bn: "আসলে, আমি ঢাকা থেকে, চট্টগ্রাম থেকে নয়।",
          slotValues: { CORRECTION: "I'm from Dhaka, not Chittagong" },
          topicArea: "daily_life",
        },
        {
          en: "Actually, we need five copies, not three.",
          bn: "আসলে, আমাদের পাঁচটি কপি দরকার, তিনটি নয়।",
          slotValues: { CORRECTION: "we need five copies, not three" },
          topicArea: "work",
        },
        {
          en: "Actually, the recipe calls for butter, not oil.",
          bn: "আসলে, রেসিপিতে মাখন লাগে, তেল নয়।",
          slotValues: { CORRECTION: "the recipe calls for butter, not oil" },
          topicArea: "food",
        },
        {
          en: "Actually, the train departs from platform 5.",
          bn: "আসলে, ট্রেন প্ল্যাটফর্ম ৫ থেকে ছাড়ে।",
          slotValues: { CORRECTION: "the train departs from platform 5" },
          topicArea: "travel",
        },
        {
          en: "Actually, the class starts at 9, not 10.",
          bn: "আসলে, ক্লাস ৯টায় শুরু, ১০টায় নয়।",
          slotValues: { CORRECTION: "the class starts at 9, not 10" },
          topicArea: "education",
        },
        {
          en: "Actually, it was his idea, not mine.",
          bn: "আসলে, এটা তার ধারণা ছিল, আমার নয়।",
          slotValues: { CORRECTION: "it was his idea, not mine" },
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "The most common way to gently correct someone. 'Actually' softens the correction and avoids sounding rude.",
      usageNote_bn:
        "কাউকে মৃদুভাবে সংশোধন করার সবচেয়ে সাধারণ উপায়। 'Actually' সংশোধনকে নরম করে এবং অভদ্র শোনানো এড়ায়।",
      combinableWith: ["R4.2"],
      banglaStructureMap:
        "আসলে (Adverb) + [CORRECTION] (Corrected statement)",
    },
    {
      id: "R4.2",
      formula: "What I meant was [CLAUSE]",
      formula_bn: "আমি যা বোঝাতে চেয়েছিলাম তা হলো [উপবাক্য]",
      patternName: "Clarifying Intent",
      patternName_bn: "উদ্দেশ্য স্পষ্টকরণ",
      slots: [
        {
          name: "CLAUSE",
          description: "The intended meaning you want to clarify",
          description_bn: "আপনি যে অর্থ স্পষ্ট করতে চান",
          acceptedTypes: ["clause"],
          examples: [
            "we should postpone it",
            "I need more time",
            "let's do it differently",
          ],
        },
      ],
      examples: [
        {
          en: "What I meant was we should postpone it.",
          bn: "আমি যা বোঝাতে চেয়েছিলাম তা হলো আমাদের এটা স্থগিত রাখা উচিত।",
          slotValues: { CLAUSE: "we should postpone it" },
          topicArea: "work",
        },
        {
          en: "What I meant was I need more time.",
          bn: "আমি যা বোঝাতে চেয়েছিলাম তা হলো আমার আরও সময় দরকার।",
          slotValues: { CLAUSE: "I need more time" },
          topicArea: "work",
        },
        {
          en: "What I meant was let's do it differently.",
          bn: "আমি যা বোঝাতে চেয়েছিলাম তা হলো চলো অন্যভাবে করি।",
          slotValues: { CLAUSE: "let's do it differently" },
          topicArea: "daily_life",
        },
        {
          en: "What I meant was the hotel near the beach.",
          bn: "আমি যা বোঝাতে চেয়েছিলাম তা হলো সমুদ্র সৈকতের কাছের হোটেল।",
          slotValues: { CLAUSE: "the hotel near the beach" },
          topicArea: "travel",
        },
        {
          en: "What I meant was you should study the first chapter.",
          bn: "আমি যা বোঝাতে চেয়েছিলাম তা হলো তোমার প্রথম অধ্যায় পড়া উচিত।",
          slotValues: { CLAUSE: "you should study the first chapter" },
          topicArea: "education",
        },
        {
          en: "What I meant was the vegetarian option.",
          bn: "আমি যা বোঝাতে চেয়েছিলাম তা হলো নিরামিষ অপশন।",
          slotValues: { CLAUSE: "the vegetarian option" },
          topicArea: "food",
        },
        {
          en: "What I meant was you should rest more.",
          bn: "আমি যা বোঝাতে চেয়েছিলাম তা হলো তোমার আরও বিশ্রাম নেওয়া উচিত।",
          slotValues: { CLAUSE: "you should rest more" },
          topicArea: "health",
        },
        {
          en: "What I meant was we should talk about it later.",
          bn: "আমি যা বোঝাতে চেয়েছিলাম তা হলো আমরা এটা পরে আলোচনা করব।",
          slotValues: { CLAUSE: "we should talk about it later" },
          topicArea: "relationships",
        },
        {
          en: "What I meant was the blue one, not the red.",
          bn: "আমি যা বোঝাতে চেয়েছিলাম তা হলো নীলটা, লালটা নয়।",
          slotValues: { CLAUSE: "the blue one, not the red" },
          topicArea: "shopping",
        },
        {
          en: "What I meant was we need a backup plan.",
          bn: "আমি যা বোঝাতে চেয়েছিলাম তা হলো আমাদের একটি বিকল্প পরিকল্পনা দরকার।",
          slotValues: { CLAUSE: "we need a backup plan" },
          topicArea: "work",
        },
        {
          en: "What I meant was Saturday afternoon, not morning.",
          bn: "আমি যা বোঝাতে চেয়েছিলাম তা হলো শনিবার বিকাল, সকাল নয়।",
          slotValues: { CLAUSE: "Saturday afternoon, not morning" },
          topicArea: "daily_life",
        },
        {
          en: "What I meant was the direct flight.",
          bn: "আমি যা বোঝাতে চেয়েছিলাম তা হলো সরাসরি ফ্লাইট।",
          slotValues: { CLAUSE: "the direct flight" },
          topicArea: "travel",
        },
        {
          en: "What I meant was you should see a specialist.",
          bn: "আমি যা বোঝাতে চেয়েছিলাম তা হলো তোমার একজন বিশেষজ্ঞ দেখানো উচিত।",
          slotValues: { CLAUSE: "you should see a specialist" },
          topicArea: "health",
        },
        {
          en: "What I meant was the online version of the course.",
          bn: "আমি যা বোঝাতে চেয়েছিলাম তা হলো কোর্সের অনলাইন সংস্করণ।",
          slotValues: { CLAUSE: "the online version of the course" },
          topicArea: "education",
        },
        {
          en: "What I meant was I value your opinion.",
          bn: "আমি যা বোঝাতে চেয়েছিলাম তা হলো আমি তোমার মতামতকে মূল্য দিই।",
          slotValues: { CLAUSE: "I value your opinion" },
          topicArea: "relationships",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "Used when someone has misunderstood you and you want to clarify your original intention.",
      usageNote_bn:
        "যখন কেউ আপনাকে ভুল বুঝেছে এবং আপনি আপনার মূল উদ্দেশ্য স্পষ্ট করতে চান তখন ব্যবহৃত হয়।",
      combinableWith: ["R4.1"],
      banglaStructureMap:
        "আমি যা বোঝাতে চেয়েছিলাম (Subject + Relative clause) + তা হলো (that is) + [CLAUSE]",
    },
    {
      id: "R4.3",
      formula: "No, that's not what I said. I said [CLAUSE]",
      formula_bn: "না, আমি তা বলিনি। আমি বলেছিলাম [উপবাক্য]",
      patternName: "Direct Correction",
      patternName_bn: "সরাসরি সংশোধন",
      slots: [
        {
          name: "CLAUSE",
          description: "What you actually said or meant",
          description_bn: "আপনি আসলে যা বলেছিলেন বা বোঝাতে চেয়েছিলেন",
          acceptedTypes: ["clause"],
          examples: [
            "we should wait",
            "the deadline is Friday",
            "I'm not going",
          ],
        },
      ],
      examples: [
        {
          en: "No, that's not what I said. I said we should wait.",
          bn: "না, আমি তা বলিনি। আমি বলেছিলাম আমাদের অপেক্ষা করা উচিত।",
          slotValues: { CLAUSE: "we should wait" },
          topicArea: "work",
        },
        {
          en: "No, that's not what I said. I said the deadline is Friday.",
          bn: "না, আমি তা বলিনি। আমি বলেছিলাম সময়সীমা শুক্রবার।",
          slotValues: { CLAUSE: "the deadline is Friday" },
          topicArea: "work",
        },
        {
          en: "No, that's not what I said. I said I'm not going.",
          bn: "না, আমি তা বলিনি। আমি বলেছিলাম আমি যাচ্ছি না।",
          slotValues: { CLAUSE: "I'm not going" },
          topicArea: "daily_life",
        },
        {
          en: "No, that's not what I said. I said the price is 500, not 50.",
          bn: "না, আমি তা বলিনি। আমি বলেছিলাম দাম ৫০০, ৫০ নয়।",
          slotValues: { CLAUSE: "the price is 500, not 50" },
          topicArea: "shopping",
        },
        {
          en: "No, that's not what I said. I said the train, not the bus.",
          bn: "না, আমি তা বলিনি। আমি বলেছিলাম ট্রেন, বাস নয়।",
          slotValues: { CLAUSE: "the train, not the bus" },
          topicArea: "travel",
        },
        {
          en: "No, that's not what I said. I said chapter five.",
          bn: "না, আমি তা বলিনি। আমি বলেছিলাম পঞ্চম অধ্যায়।",
          slotValues: { CLAUSE: "chapter five" },
          topicArea: "education",
        },
        {
          en: "No, that's not what I said. I said grilled fish.",
          bn: "না, আমি তা বলিনি। আমি বলেছিলাম গ্রিলড মাছ।",
          slotValues: { CLAUSE: "grilled fish" },
          topicArea: "food",
        },
        {
          en: "No, that's not what I said. I said take it twice a day.",
          bn: "না, আমি তা বলিনি। আমি বলেছিলাম দিনে দুবার খান।",
          slotValues: { CLAUSE: "take it twice a day" },
          topicArea: "health",
        },
        {
          en: "No, that's not what I said. I said I like him as a friend.",
          bn: "না, আমি তা বলিনি। আমি বলেছিলাম আমি তাকে বন্ধু হিসেবে পছন্দ করি।",
          slotValues: { CLAUSE: "I like him as a friend" },
          topicArea: "relationships",
        },
        {
          en: "No, that's not what I said. I said after lunch.",
          bn: "না, আমি তা বলিনি। আমি বলেছিলাম দুপুরের খাবারের পরে।",
          slotValues: { CLAUSE: "after lunch" },
          topicArea: "daily_life",
        },
        {
          en: "No, that's not what I said. I said the budget needs approval.",
          bn: "না, আমি তা বলিনি। আমি বলেছিলাম বাজেটের অনুমোদন দরকার।",
          slotValues: { CLAUSE: "the budget needs approval" },
          topicArea: "work",
        },
        {
          en: "No, that's not what I said. I said medium, not large.",
          bn: "না, আমি তা বলিনি। আমি বলেছিলাম মিডিয়াম, লার্জ নয়।",
          slotValues: { CLAUSE: "medium, not large" },
          topicArea: "shopping",
        },
        {
          en: "No, that's not what I said. I said the 8 o'clock flight.",
          bn: "না, আমি তা বলিনি। আমি বলেছিলাম ৮টার ফ্লাইট।",
          slotValues: { CLAUSE: "the 8 o'clock flight" },
          topicArea: "travel",
        },
        {
          en: "No, that's not what I said. I said the assignment is optional.",
          bn: "না, আমি তা বলিনি। আমি বলেছিলাম অ্যাসাইনমেন্টটি ঐচ্ছিক।",
          slotValues: { CLAUSE: "the assignment is optional" },
          topicArea: "education",
        },
        {
          en: "No, that's not what I said. I said mild pain, not severe.",
          bn: "না, আমি তা বলিনি। আমি বলেছিলাম হালকা ব্যথা, তীব্র নয়।",
          slotValues: { CLAUSE: "mild pain, not severe" },
          topicArea: "health",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "A more direct way to correct a misunderstanding. Use when someone has clearly misquoted or misinterpreted you.",
      usageNote_bn:
        "ভুল বোঝাবুঝি সংশোধন করার একটি আরও সরাসরি উপায়। কেউ আপনাকে স্পষ্টভাবে ভুল উদ্ধৃত বা ভুল ব্যাখ্যা করলে ব্যবহার করুন।",
      combinableWith: ["R4.1"],
      banglaStructureMap:
        "না, আমি তা বলিনি (Negation) + আমি বলেছিলাম (Subject + Verb) + [CLAUSE]",
    },
    {
      id: "R4.4",
      formula: "Let me rephrase that. [CLAUSE]",
      formula_bn: "আমাকে আবার বলতে দিন। [উপবাক্য]",
      patternName: "Self-Correction",
      patternName_bn: "আত্ম-সংশোধন",
      slots: [
        {
          name: "CLAUSE",
          description: "A clearer version of what you want to say",
          description_bn: "আপনি যা বলতে চান তার একটি স্পষ্ট সংস্করণ",
          acceptedTypes: ["clause"],
          examples: [
            "we need more resources",
            "the plan needs adjusting",
            "I think we should reconsider",
          ],
        },
      ],
      examples: [
        {
          en: "Let me rephrase that. We need more resources.",
          bn: "আমাকে আবার বলতে দিন। আমাদের আরও সম্পদ দরকার।",
          slotValues: { CLAUSE: "We need more resources" },
          topicArea: "work",
        },
        {
          en: "Let me rephrase that. The plan needs adjusting.",
          bn: "আমাকে আবার বলতে দিন। পরিকল্পনাটি সামঞ্জস্য করা দরকার।",
          slotValues: { CLAUSE: "The plan needs adjusting" },
          topicArea: "work",
        },
        {
          en: "Let me rephrase that. I think we should reconsider.",
          bn: "আমাকে আবার বলতে দিন। আমি মনে করি আমাদের পুনর্বিবেচনা করা উচিত।",
          slotValues: { CLAUSE: "I think we should reconsider" },
          topicArea: "daily_life",
        },
        {
          en: "Let me rephrase that. The food was okay, just not great.",
          bn: "আমাকে আবার বলতে দিন। খাবার ঠিক ছিল, শুধু দারুণ ছিল না।",
          slotValues: { CLAUSE: "The food was okay, just not great" },
          topicArea: "food",
        },
        {
          en: "Let me rephrase that. I meant we should leave at noon.",
          bn: "আমাকে আবার বলতে দিন। আমি বোঝাতে চেয়েছিলাম আমাদের দুপুরে বের হওয়া উচিত।",
          slotValues: { CLAUSE: "I meant we should leave at noon" },
          topicArea: "travel",
        },
        {
          en: "Let me rephrase that. The test was challenging, not impossible.",
          bn: "আমাকে আবার বলতে দিন। পরীক্ষাটি চ্যালেঞ্জিং ছিল, অসম্ভব নয়।",
          slotValues: { CLAUSE: "The test was challenging, not impossible" },
          topicArea: "education",
        },
        {
          en: "Let me rephrase that. I'm concerned about your health.",
          bn: "আমাকে আবার বলতে দিন। আমি তোমার স্বাস্থ্য নিয়ে চিন্তিত।",
          slotValues: { CLAUSE: "I'm concerned about your health" },
          topicArea: "health",
        },
        {
          en: "Let me rephrase that. It's a bit overpriced for the quality.",
          bn: "আমাকে আবার বলতে দিন। মানের তুলনায় এটা একটু বেশি দামি।",
          slotValues: { CLAUSE: "It's a bit overpriced for the quality" },
          topicArea: "shopping",
        },
        {
          en: "Let me rephrase that. I appreciate your effort.",
          bn: "আমাকে আবার বলতে দিন। আমি তোমার প্রচেষ্টার প্রশংসা করি।",
          slotValues: { CLAUSE: "I appreciate your effort" },
          topicArea: "relationships",
        },
        {
          en: "Let me rephrase that. We need the report by end of day.",
          bn: "আমাকে আবার বলতে দিন। আমাদের দিনের শেষের মধ্যে রিপোর্ট দরকার।",
          slotValues: { CLAUSE: "We need the report by end of day" },
          topicArea: "work",
        },
        {
          en: "Let me rephrase that. I prefer a window seat.",
          bn: "আমাকে আবার বলতে দিন। আমি জানালার পাশের সিট পছন্দ করি।",
          slotValues: { CLAUSE: "I prefer a window seat" },
          topicArea: "travel",
        },
        {
          en: "Let me rephrase that. The course has a prerequisite.",
          bn: "আমাকে আবার বলতে দিন। কোর্সটির একটি পূর্বশর্ত আছে।",
          slotValues: { CLAUSE: "The course has a prerequisite" },
          topicArea: "education",
        },
        {
          en: "Let me rephrase that. The pain comes and goes.",
          bn: "আমাকে আবার বলতে দিন। ব্যথা আসে আর যায়।",
          slotValues: { CLAUSE: "The pain comes and goes" },
          topicArea: "health",
        },
        {
          en: "Let me rephrase that. I'd like a refund, not an exchange.",
          bn: "আমাকে আবার বলতে দিন। আমি ফেরত চাই, বিনিময় নয়।",
          slotValues: { CLAUSE: "I'd like a refund, not an exchange" },
          topicArea: "shopping",
        },
        {
          en: "Let me rephrase that. I enjoy spending time with you.",
          bn: "আমাকে আবার বলতে দিন। তোমার সাথে সময় কাটাতে আমি উপভোগ করি।",
          slotValues: { CLAUSE: "I enjoy spending time with you" },
          topicArea: "relationships",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "Used when you realize your own words were unclear. Shows self-awareness and good communication skills.",
      usageNote_bn:
        "যখন আপনি বুঝতে পারেন যে আপনার নিজের কথা অস্পষ্ট ছিল তখন ব্যবহৃত হয়। আত্মসচেতনতা ও ভালো যোগাযোগ দক্ষতা দেখায়।",
      combinableWith: ["R4.2"],
      banglaStructureMap:
        "আমাকে আবার বলতে দিন (Request) + [CLAUSE] (Rephrased statement)",
    },
    {
      id: "R4.5",
      formula: "I think there's been a misunderstanding. [CLAUSE]",
      formula_bn: "আমার মনে হয় একটা ভুল বোঝাবুঝি হয়েছে। [উপবাক্য]",
      patternName: "Diplomatic Correction",
      patternName_bn: "কূটনৈতিক সংশোধন",
      slots: [
        {
          name: "CLAUSE",
          description: "The clarification or correct version",
          description_bn: "স্পষ্টীকরণ বা সঠিক সংস্করণ",
          acceptedTypes: ["clause"],
          examples: [
            "I was talking about next month",
            "the offer was for new customers only",
            "the appointment is tomorrow",
          ],
        },
      ],
      examples: [
        {
          en: "I think there's been a misunderstanding. I was talking about next month.",
          bn: "আমার মনে হয় একটা ভুল বোঝাবুঝি হয়েছে। আমি আগামী মাসের কথা বলছিলাম।",
          slotValues: { CLAUSE: "I was talking about next month" },
          topicArea: "work",
        },
        {
          en: "I think there's been a misunderstanding. The offer was for new customers only.",
          bn: "আমার মনে হয় একটা ভুল বোঝাবুঝি হয়েছে। অফারটি শুধু নতুন গ্রাহকদের জন্য ছিল।",
          slotValues: { CLAUSE: "The offer was for new customers only" },
          topicArea: "shopping",
        },
        {
          en: "I think there's been a misunderstanding. The appointment is tomorrow.",
          bn: "আমার মনে হয় একটা ভুল বোঝাবুঝি হয়েছে। অ্যাপয়েন্টমেন্ট আগামীকাল।",
          slotValues: { CLAUSE: "The appointment is tomorrow" },
          topicArea: "health",
        },
        {
          en: "I think there's been a misunderstanding. We booked for four people.",
          bn: "আমার মনে হয় একটা ভুল বোঝাবুঝি হয়েছে। আমরা চারজনের জন্য বুক করেছি।",
          slotValues: { CLAUSE: "We booked for four people" },
          topicArea: "food",
        },
        {
          en: "I think there's been a misunderstanding. The trip is next week.",
          bn: "আমার মনে হয় একটা ভুল বোঝাবুঝি হয়েছে। ভ্রমণ আগামী সপ্তাহে।",
          slotValues: { CLAUSE: "The trip is next week" },
          topicArea: "travel",
        },
        {
          en: "I think there's been a misunderstanding. I didn't say I was leaving.",
          bn: "আমার মনে হয় একটা ভুল বোঝাবুঝি হয়েছে। আমি বলিনি যে আমি চলে যাচ্ছি।",
          slotValues: { CLAUSE: "I didn't say I was leaving" },
          topicArea: "relationships",
        },
        {
          en: "I think there's been a misunderstanding. The deadline is next Friday.",
          bn: "আমার মনে হয় একটা ভুল বোঝাবুঝি হয়েছে। সময়সীমা আগামী শুক্রবার।",
          slotValues: { CLAUSE: "The deadline is next Friday" },
          topicArea: "education",
        },
        {
          en: "I think there's been a misunderstanding. I only asked for an estimate.",
          bn: "আমার মনে হয় একটা ভুল বোঝাবুঝি হয়েছে। আমি শুধু একটি আনুমানিক হিসাব চেয়েছিলাম।",
          slotValues: { CLAUSE: "I only asked for an estimate" },
          topicArea: "shopping",
        },
        {
          en: "I think there's been a misunderstanding. The event is free of charge.",
          bn: "আমার মনে হয় একটা ভুল বোঝাবুঝি হয়েছে। অনুষ্ঠানটি বিনামূল্যে।",
          slotValues: { CLAUSE: "The event is free of charge" },
          topicArea: "daily_life",
        },
        {
          en: "I think there's been a misunderstanding. I requested a single room.",
          bn: "আমার মনে হয় একটা ভুল বোঝাবুঝি হয়েছে। আমি একটি সিঙ্গেল রুম চেয়েছিলাম।",
          slotValues: { CLAUSE: "I requested a single room" },
          topicArea: "travel",
        },
        {
          en: "I think there's been a misunderstanding. The report is for internal use.",
          bn: "আমার মনে হয় একটা ভুল বোঝাবুঝি হয়েছে। রিপোর্টটি অভ্যন্তরীণ ব্যবহারের জন্য।",
          slotValues: { CLAUSE: "The report is for internal use" },
          topicArea: "work",
        },
        {
          en: "I think there's been a misunderstanding. The medicine is for after meals.",
          bn: "আমার মনে হয় একটা ভুল বোঝাবুঝি হয়েছে। ওষুধটি খাবার পরে খেতে হবে।",
          slotValues: { CLAUSE: "The medicine is for after meals" },
          topicArea: "health",
        },
        {
          en: "I think there's been a misunderstanding. I was joking earlier.",
          bn: "আমার মনে হয় একটা ভুল বোঝাবুঝি হয়েছে। আমি আগে মজা করছিলাম।",
          slotValues: { CLAUSE: "I was joking earlier" },
          topicArea: "relationships",
        },
        {
          en: "I think there's been a misunderstanding. The class is online, not in person.",
          bn: "আমার মনে হয় একটা ভুল বোঝাবুঝি হয়েছে। ক্লাস অনলাইনে, সশরীরে নয়।",
          slotValues: { CLAUSE: "The class is online, not in person" },
          topicArea: "education",
        },
        {
          en: "I think there's been a misunderstanding. The reservation is for dinner, not lunch.",
          bn: "আমার মনে হয় একটা ভুল বোঝাবুঝি হয়েছে। রিজার্ভেশন রাতের খাবারের জন্য, দুপুরের নয়।",
          slotValues: { CLAUSE: "The reservation is for dinner, not lunch" },
          topicArea: "food",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "A diplomatic way to address misunderstandings. Avoids blaming anyone and focuses on clearing up confusion.",
      usageNote_bn:
        "ভুল বোঝাবুঝি মোকাবেলার একটি কূটনৈতিক উপায়। কাউকে দোষারোপ করা এড়ায় এবং বিভ্রান্তি দূর করায় মনোযোগ দেয়।",
      combinableWith: ["R4.2", "R4.4"],
      banglaStructureMap:
        "আমার মনে হয় একটা ভুল বোঝাবুঝি হয়েছে (Fixed phrase) + [CLAUSE] (Clarification)",
    },
    {
      id: "R4.6",
      formula: "To be exact, [CORRECTION]",
      formula_bn: "সঠিকভাবে বলতে গেলে, [সংশোধন]",
      patternName: "Precision Correction (To Be Exact)",
      patternName_bn: "সুনির্দিষ্ট সংশোধন (সঠিকভাবে বলতে গেলে)",
      slots: [
        {
          name: "CORRECTION",
          description: "A precise detail or correction",
          description_bn: "একটি সুনির্দিষ্ট বিবরণ বা সংশোধন",
          acceptedTypes: ["clause"],
          examples: [
            "there were 47 people",
            "it happened on March 5th",
            "the meeting starts at 9:15",
          ],
        },
      ],
      examples: [
        {
          en: "To be exact, there were 47 people.",
          bn: "সঠিকভাবে বলতে গেলে, ৪৭ জন মানুষ ছিল।",
          slotValues: { CORRECTION: "there were 47 people" },
          topicArea: "daily_life",
        },
        {
          en: "To be exact, it happened on March 5th.",
          bn: "সঠিকভাবে বলতে গেলে, এটা ৫ই মার্চ ঘটেছিল।",
          slotValues: { CORRECTION: "it happened on March 5th" },
          topicArea: "daily_life",
        },
        {
          en: "To be exact, the meeting starts at 9:15, not 9.",
          bn: "সঠিকভাবে বলতে গেলে, মিটিং ৯:১৫-তে শুরু, ৯টায় নয়।",
          slotValues: { CORRECTION: "the meeting starts at 9:15, not 9" },
          topicArea: "work",
        },
        {
          en: "To be exact, the flight takes 3 hours and 20 minutes.",
          bn: "সঠিকভাবে বলতে গেলে, ফ্লাইটে ৩ ঘণ্টা ২০ মিনিট লাগে।",
          slotValues: { CORRECTION: "the flight takes 3 hours and 20 minutes" },
          topicArea: "travel",
        },
        {
          en: "To be exact, the price is 1,250 taka, not 1,200.",
          bn: "সঠিকভাবে বলতে গেলে, দাম ১,২৫০ টাকা, ১,২০০ নয়।",
          slotValues: { CORRECTION: "the price is 1,250 taka, not 1,200" },
          topicArea: "shopping",
        },
        {
          en: "To be exact, the exam has 60 questions.",
          bn: "সঠিকভাবে বলতে গেলে, পরীক্ষায় ৬০টি প্রশ্ন আছে।",
          slotValues: { CORRECTION: "the exam has 60 questions" },
          topicArea: "education",
        },
        {
          en: "To be exact, the recipe calls for 250 grams of flour.",
          bn: "সঠিকভাবে বলতে গেলে, রেসিপিতে ২৫০ গ্রাম ময়দা লাগে।",
          slotValues: { CORRECTION: "the recipe calls for 250 grams of flour" },
          topicArea: "food",
        },
        {
          en: "To be exact, my blood pressure was 130 over 85.",
          bn: "সঠিকভাবে বলতে গেলে, আমার রক্তচাপ ছিল ১৩০/৮৫।",
          slotValues: { CORRECTION: "my blood pressure was 130 over 85" },
          topicArea: "health",
        },
        {
          en: "To be exact, we've been friends for 12 years.",
          bn: "সঠিকভাবে বলতে গেলে, আমরা ১২ বছর ধরে বন্ধু।",
          slotValues: { CORRECTION: "we've been friends for 12 years" },
          topicArea: "relationships",
        },
        {
          en: "To be exact, the report has 32 pages.",
          bn: "সঠিকভাবে বলতে গেলে, রিপোর্টে ৩২ পৃষ্ঠা আছে।",
          slotValues: { CORRECTION: "the report has 32 pages" },
          topicArea: "work",
        },
        {
          en: "To be exact, the hotel is 2.5 kilometers from the beach.",
          bn: "সঠিকভাবে বলতে গেলে, হোটেল সমুদ্র সৈকত থেকে ২.৫ কিলোমিটার দূরে।",
          slotValues: { CORRECTION: "the hotel is 2.5 kilometers from the beach" },
          topicArea: "travel",
        },
        {
          en: "To be exact, I scored 87 out of 100.",
          bn: "সঠিকভাবে বলতে গেলে, আমি ১০০-তে ৮৭ পেয়েছি।",
          slotValues: { CORRECTION: "I scored 87 out of 100" },
          topicArea: "education",
        },
        {
          en: "To be exact, the discount is 15%, not 20%.",
          bn: "সঠিকভাবে বলতে গেলে, ছাড় ১৫%, ২০% নয়।",
          slotValues: { CORRECTION: "the discount is 15%, not 20%" },
          topicArea: "shopping",
        },
        {
          en: "To be exact, the appointment is at 2:30 PM.",
          bn: "সঠিকভাবে বলতে গেলে, অ্যাপয়েন্টমেন্ট বিকাল ২:৩০-এ।",
          slotValues: { CORRECTION: "the appointment is at 2:30 PM" },
          topicArea: "health",
        },
        {
          en: "To be exact, there are 8 servings in this dish.",
          bn: "সঠিকভাবে বলতে গেলে, এই পদে ৮ পরিবেশন আছে।",
          slotValues: { CORRECTION: "there are 8 servings in this dish" },
          topicArea: "food",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "'To be exact' is used to provide a precise detail or to correct an approximation with an accurate figure.",
      usageNote_bn:
        "'To be exact' একটি সুনির্দিষ্ট বিবরণ দিতে বা একটি আনুমানিক তথ্যকে সঠিক সংখ্যা দিয়ে সংশোধন করতে ব্যবহৃত হয়।",
      combinableWith: ["R4.1"],
      banglaStructureMap:
        "সঠিকভাবে বলতে গেলে (Adverb phrase) + [CORRECTION] (Precise statement)",
    },
  ],
};
