import { PatternCategory } from "@/types/pattern";

export const categoryR8: PatternCategory = {
  id: "R8",
  slug: "hedging-softening",
  name: "Hedging & Softening",
  name_bn: "দোলাচল ও নরমকরণ",
  description:
    "Express uncertainty politely and soften your statements to sound more diplomatic.",
  description_bn:
    "বিনয়ের সাথে অনিশ্চয়তা প্রকাশ করুন এবং আরও কূটনৈতিক শোনাতে আপনার বিবৃতি নরম করুন।",
  icon: "🌊",
  group: "R",
  groupName: "Logical & Discourse Patterns",
  groupName_bn: "যৌক্তিক ও বক্তৃতা প্যাটার্ন",
  difficulty: "intermediate",
  patterns: [
    {
      id: "R8.1",
      formula: "I'm not 100% sure, but [CLAUSE]",
      formula_bn: "আমি ১০০% নিশ্চিত নই, তবে [উপবাক্য]",
      patternName: "Uncertain Statement",
      patternName_bn: "অনিশ্চিত বিবৃতি",
      slots: [
        {
          name: "CLAUSE",
          description: "Something you think might be true",
          description_bn: "এমন কিছু যা আপনি সত্য হতে পারে বলে মনে করেন",
          acceptedTypes: ["clause"],
          examples: [
            "I think the store closes at 9",
            "she mentioned it last week",
            "the meeting is on Thursday",
          ],
        },
      ],
      examples: [
        {
          en: "I'm not 100% sure, but I think the store closes at 9.",
          bn: "আমি ১০০% নিশ্চিত নই, তবে আমার মনে হয় দোকান ৯টায় বন্ধ হয়।",
          slotValues: { CLAUSE: "I think the store closes at 9" },
          topicArea: "shopping",
        },
        {
          en: "I'm not 100% sure, but she mentioned it last week.",
          bn: "আমি ১০০% নিশ্চিত নই, তবে সে গত সপ্তাহে এটা উল্লেখ করেছিল।",
          slotValues: { CLAUSE: "she mentioned it last week" },
          topicArea: "relationships",
        },
        {
          en: "I'm not 100% sure, but the meeting is on Thursday.",
          bn: "আমি ১০০% নিশ্চিত নই, তবে মিটিং বৃহস্পতিবারে।",
          slotValues: { CLAUSE: "the meeting is on Thursday" },
          topicArea: "work",
        },
        {
          en: "I'm not 100% sure, but I think the train leaves at 2.",
          bn: "আমি ১০০% নিশ্চিত নই, তবে আমার মনে হয় ট্রেন ২টায় ছাড়ে।",
          slotValues: { CLAUSE: "I think the train leaves at 2" },
          topicArea: "travel",
        },
        {
          en: "I'm not 100% sure, but the exam covers chapters 1 to 5.",
          bn: "আমি ১০০% নিশ্চিত নই, তবে পরীক্ষায় ১ থেকে ৫ অধ্যায় আসবে।",
          slotValues: { CLAUSE: "the exam covers chapters 1 to 5" },
          topicArea: "education",
        },
        {
          en: "I'm not 100% sure, but that restaurant is halal.",
          bn: "আমি ১০০% নিশ্চিত নই, তবে সেই রেস্তোরাঁ হালাল।",
          slotValues: { CLAUSE: "that restaurant is halal" },
          topicArea: "food",
        },
        {
          en: "I'm not 100% sure, but I think the clinic is open on Saturdays.",
          bn: "আমি ১০০% নিশ্চিত নই, তবে আমার মনে হয় ক্লিনিক শনিবারে খোলা থাকে।",
          slotValues: { CLAUSE: "I think the clinic is open on Saturdays" },
          topicArea: "health",
        },
        {
          en: "I'm not 100% sure, but there might be a sale this weekend.",
          bn: "আমি ১০০% নিশ্চিত নই, তবে এই সপ্তাহান্তে সেল হতে পারে।",
          slotValues: { CLAUSE: "there might be a sale this weekend" },
          topicArea: "shopping",
        },
        {
          en: "I'm not 100% sure, but I believe he's the new manager.",
          bn: "আমি ১০০% নিশ্চিত নই, তবে আমি বিশ্বাস করি সে নতুন ম্যানেজার।",
          slotValues: { CLAUSE: "I believe he's the new manager" },
          topicArea: "work",
        },
        {
          en: "I'm not 100% sure, but I think they moved to London.",
          bn: "আমি ১০০% নিশ্চিত নই, তবে আমার মনে হয় তারা লন্ডনে চলে গেছে।",
          slotValues: { CLAUSE: "I think they moved to London" },
          topicArea: "relationships",
        },
        {
          en: "I'm not 100% sure, but the library closes at 8 PM.",
          bn: "আমি ১০০% নিশ্চিত নই, তবে লাইব্রেরি রাত ৮টায় বন্ধ হয়।",
          slotValues: { CLAUSE: "the library closes at 8 PM" },
          topicArea: "education",
        },
        {
          en: "I'm not 100% sure, but I think the ferry runs every hour.",
          bn: "আমি ১০০% নিশ্চিত নই, তবে আমার মনে হয় ফেরি প্রতি ঘণ্টায় চলে।",
          slotValues: { CLAUSE: "I think the ferry runs every hour" },
          topicArea: "travel",
        },
        {
          en: "I'm not 100% sure, but the side effects are mild.",
          bn: "আমি ১০০% নিশ্চিত নই, তবে পার্শ্বপ্রতিক্রিয়া হালকা।",
          slotValues: { CLAUSE: "the side effects are mild" },
          topicArea: "health",
        },
        {
          en: "I'm not 100% sure, but I think today's special is pasta.",
          bn: "আমি ১০০% নিশ্চিত নই, তবে আমার মনে হয় আজকের স্পেশাল পাস্তা।",
          slotValues: { CLAUSE: "I think today's special is pasta" },
          topicArea: "food",
        },
        {
          en: "I'm not 100% sure, but the concert starts at 7.",
          bn: "আমি ১০০% নিশ্চিত নই, তবে কনসার্ট ৭টায় শুরু।",
          slotValues: { CLAUSE: "the concert starts at 7" },
          topicArea: "daily_life",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "A very natural way to share information while acknowledging you could be wrong. Common in everyday speech.",
      usageNote_bn:
        "আপনি ভুল হতে পারেন তা স্বীকার করে তথ্য শেয়ার করার একটি খুবই স্বাভাবিক উপায়। দৈনন্দিন কথোপকথনে সাধারণ।",
      combinableWith: ["R8.2"],
      banglaStructureMap:
        "আমি ১০০% নিশ্চিত নই (Hedging phrase) + তবে (but) + [CLAUSE]",
    },
    {
      id: "R8.2",
      formula: "As far as I know, [CLAUSE]",
      formula_bn: "আমি যতদূর জানি, [উপবাক্য]",
      patternName: "Limited Knowledge Hedge",
      patternName_bn: "সীমিত জ্ঞানের দোলাচল",
      slots: [
        {
          name: "CLAUSE",
          description: "Information you believe is correct based on your knowledge",
          description_bn: "আপনার জ্ঞানের ভিত্তিতে সঠিক বলে বিশ্বাস করা তথ্য",
          acceptedTypes: ["clause"],
          examples: [
            "the project is on schedule",
            "they haven't decided yet",
            "the office is moving",
          ],
        },
      ],
      examples: [
        {
          en: "As far as I know, the project is on schedule.",
          bn: "আমি যতদূর জানি, প্রকল্পটি সময়সূচিতে আছে।",
          slotValues: { CLAUSE: "the project is on schedule" },
          topicArea: "work",
        },
        {
          en: "As far as I know, they haven't decided yet.",
          bn: "আমি যতদূর জানি, তারা এখনও সিদ্ধান্ত নেয়নি।",
          slotValues: { CLAUSE: "they haven't decided yet" },
          topicArea: "daily_life",
        },
        {
          en: "As far as I know, the restaurant is still open.",
          bn: "আমি যতদূর জানি, রেস্তোরাঁ এখনও খোলা আছে।",
          slotValues: { CLAUSE: "the restaurant is still open" },
          topicArea: "food",
        },
        {
          en: "As far as I know, the flight hasn't been canceled.",
          bn: "আমি যতদূর জানি, ফ্লাইট বাতিল হয়নি।",
          slotValues: { CLAUSE: "the flight hasn't been canceled" },
          topicArea: "travel",
        },
        {
          en: "As far as I know, the deadline hasn't changed.",
          bn: "আমি যতদূর জানি, সময়সীমা পরিবর্তন হয়নি।",
          slotValues: { CLAUSE: "the deadline hasn't changed" },
          topicArea: "education",
        },
        {
          en: "As far as I know, the product is still under warranty.",
          bn: "আমি যতদূর জানি, পণ্যটি এখনও ওয়ারেন্টির আওতায়।",
          slotValues: { CLAUSE: "the product is still under warranty" },
          topicArea: "shopping",
        },
        {
          en: "As far as I know, the treatment is safe.",
          bn: "আমি যতদূর জানি, চিকিৎসাটি নিরাপদ।",
          slotValues: { CLAUSE: "the treatment is safe" },
          topicArea: "health",
        },
        {
          en: "As far as I know, they're still dating.",
          bn: "আমি যতদূর জানি, তারা এখনও ডেটিং করছে।",
          slotValues: { CLAUSE: "they're still dating" },
          topicArea: "relationships",
        },
        {
          en: "As far as I know, the new policy starts next month.",
          bn: "আমি যতদূর জানি, নতুন নীতি আগামী মাসে শুরু হবে।",
          slotValues: { CLAUSE: "the new policy starts next month" },
          topicArea: "work",
        },
        {
          en: "As far as I know, the museum is free on Fridays.",
          bn: "আমি যতদূর জানি, শুক্রবারে জাদুঘর বিনামূল্যে।",
          slotValues: { CLAUSE: "the museum is free on Fridays" },
          topicArea: "travel",
        },
        {
          en: "As far as I know, the enrollment is still open.",
          bn: "আমি যতদূর জানি, ভর্তি এখনও চালু আছে।",
          slotValues: { CLAUSE: "the enrollment is still open" },
          topicArea: "education",
        },
        {
          en: "As far as I know, the ingredients are all natural.",
          bn: "আমি যতদূর জানি, উপকরণগুলো সবই প্রাকৃতিক।",
          slotValues: { CLAUSE: "the ingredients are all natural" },
          topicArea: "food",
        },
        {
          en: "As far as I know, the refund has been processed.",
          bn: "আমি যতদূর জানি, ফেরত প্রক্রিয়া সম্পন্ন হয়েছে।",
          slotValues: { CLAUSE: "the refund has been processed" },
          topicArea: "shopping",
        },
        {
          en: "As far as I know, the appointment hasn't been rescheduled.",
          bn: "আমি যতদূর জানি, অ্যাপয়েন্টমেন্টের সময় পরিবর্তন হয়নি।",
          slotValues: { CLAUSE: "the appointment hasn't been rescheduled" },
          topicArea: "health",
        },
        {
          en: "As far as I know, the event is still happening.",
          bn: "আমি যতদূর জানি, অনুষ্ঠানটি এখনও হচ্ছে।",
          slotValues: { CLAUSE: "the event is still happening" },
          topicArea: "daily_life",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "Used to qualify your statement by indicating your knowledge may be limited. Very common and useful in professional settings.",
      usageNote_bn:
        "আপনার জ্ঞান সীমিত হতে পারে বলে ইঙ্গিত দিয়ে আপনার বিবৃতিকে যোগ্যতা দেওয়ার জন্য ব্যবহৃত হয়। পেশাদার পরিবেশে খুবই সাধারণ ও কার্যকর।",
      combinableWith: ["R8.1"],
      banglaStructureMap:
        "আমি যতদূর জানি (Hedging phrase) + [CLAUSE] (Statement)",
    },
    {
      id: "R8.3",
      formula: "It seems like [CLAUSE]",
      formula_bn: "মনে হচ্ছে [উপবাক্য]",
      patternName: "Appearance-Based Hedge",
      patternName_bn: "বাহ্যিক আভাসভিত্তিক দোলাচল",
      slots: [
        {
          name: "CLAUSE",
          description: "Something that appears to be the case",
          description_bn: "যা হচ্ছে বলে মনে হয়",
          acceptedTypes: ["clause"],
          examples: [
            "the rain has stopped",
            "everyone is ready",
            "the plan is working",
          ],
        },
      ],
      examples: [
        {
          en: "It seems like the rain has stopped.",
          bn: "মনে হচ্ছে বৃষ্টি থেমেছে।",
          slotValues: { CLAUSE: "the rain has stopped" },
          topicArea: "daily_life",
        },
        {
          en: "It seems like everyone is ready.",
          bn: "মনে হচ্ছে সবাই প্রস্তুত।",
          slotValues: { CLAUSE: "everyone is ready" },
          topicArea: "work",
        },
        {
          en: "It seems like the plan is working.",
          bn: "মনে হচ্ছে পরিকল্পনা কাজ করছে।",
          slotValues: { CLAUSE: "the plan is working" },
          topicArea: "work",
        },
        {
          en: "It seems like the restaurant is closed today.",
          bn: "মনে হচ্ছে রেস্তোরাঁ আজ বন্ধ।",
          slotValues: { CLAUSE: "the restaurant is closed today" },
          topicArea: "food",
        },
        {
          en: "It seems like the flight is delayed.",
          bn: "মনে হচ্ছে ফ্লাইট দেরি হচ্ছে।",
          slotValues: { CLAUSE: "the flight is delayed" },
          topicArea: "travel",
        },
        {
          en: "It seems like the exam was easy.",
          bn: "মনে হচ্ছে পরীক্ষা সহজ ছিল।",
          slotValues: { CLAUSE: "the exam was easy" },
          topicArea: "education",
        },
        {
          en: "It seems like the medicine is helping.",
          bn: "মনে হচ্ছে ওষুধ কাজ করছে।",
          slotValues: { CLAUSE: "the medicine is helping" },
          topicArea: "health",
        },
        {
          en: "It seems like they had a great time.",
          bn: "মনে হচ্ছে তারা দারুণ সময় কাটিয়েছে।",
          slotValues: { CLAUSE: "they had a great time" },
          topicArea: "relationships",
        },
        {
          en: "It seems like the prices have gone up.",
          bn: "মনে হচ্ছে দাম বেড়ে গেছে।",
          slotValues: { CLAUSE: "the prices have gone up" },
          topicArea: "shopping",
        },
        {
          en: "It seems like the project needs more time.",
          bn: "মনে হচ্ছে প্রকল্পে আরও সময় দরকার।",
          slotValues: { CLAUSE: "the project needs more time" },
          topicArea: "work",
        },
        {
          en: "It seems like the bus is late again.",
          bn: "মনে হচ্ছে বাস আবার দেরি করছে।",
          slotValues: { CLAUSE: "the bus is late again" },
          topicArea: "travel",
        },
        {
          en: "It seems like the students enjoyed the lesson.",
          bn: "মনে হচ্ছে ছাত্ররা পাঠটি উপভোগ করেছে।",
          slotValues: { CLAUSE: "the students enjoyed the lesson" },
          topicArea: "education",
        },
        {
          en: "It seems like the fever has gone down.",
          bn: "মনে হচ্ছে জ্বর কমেছে।",
          slotValues: { CLAUSE: "the fever has gone down" },
          topicArea: "health",
        },
        {
          en: "It seems like they're getting along well.",
          bn: "মনে হচ্ছে তারা ভালোভাবে চলছে।",
          slotValues: { CLAUSE: "they're getting along well" },
          topicArea: "relationships",
        },
        {
          en: "It seems like the weather is improving.",
          bn: "মনে হচ্ছে আবহাওয়া ভালো হচ্ছে।",
          slotValues: { CLAUSE: "the weather is improving" },
          topicArea: "daily_life",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "Used when you observe something but want to avoid making a definitive statement. Very natural in casual conversation.",
      usageNote_bn:
        "যখন আপনি কিছু পর্যবেক্ষণ করেন কিন্তু চূড়ান্ত বিবৃতি দেওয়া এড়াতে চান তখন ব্যবহৃত হয়। সাধারণ কথোপকথনে খুবই স্বাভাবিক।",
      combinableWith: ["R8.1"],
      banglaStructureMap:
        "মনে হচ্ছে (It seems) + [CLAUSE] (Observed statement)",
    },
    {
      id: "R8.4",
      formula: "I could be wrong, but [CLAUSE]",
      formula_bn: "আমি ভুল হতে পারি, তবে [উপবাক্য]",
      patternName: "Modest Hedge",
      patternName_bn: "বিনয়ী দোলাচল",
      slots: [
        {
          name: "CLAUSE",
          description: "Your opinion or belief expressed modestly",
          description_bn: "বিনয়ের সাথে প্রকাশিত আপনার মতামত বা বিশ্বাস",
          acceptedTypes: ["clause"],
          examples: [
            "I think this is the wrong road",
            "the answer might be different",
            "she seemed upset",
          ],
        },
      ],
      examples: [
        {
          en: "I could be wrong, but I think this is the wrong road.",
          bn: "আমি ভুল হতে পারি, তবে আমার মনে হয় এটা ভুল রাস্তা।",
          slotValues: { CLAUSE: "I think this is the wrong road" },
          topicArea: "travel",
        },
        {
          en: "I could be wrong, but the answer might be different.",
          bn: "আমি ভুল হতে পারি, তবে উত্তরটা ভিন্ন হতে পারে।",
          slotValues: { CLAUSE: "the answer might be different" },
          topicArea: "education",
        },
        {
          en: "I could be wrong, but she seemed upset.",
          bn: "আমি ভুল হতে পারি, তবে সে মন খারাপ মনে হচ্ছিল।",
          slotValues: { CLAUSE: "she seemed upset" },
          topicArea: "relationships",
        },
        {
          en: "I could be wrong, but I think the meeting was moved to 4.",
          bn: "আমি ভুল হতে পারি, তবে আমার মনে হয় মিটিং ৪টায় সরানো হয়েছে।",
          slotValues: { CLAUSE: "I think the meeting was moved to 4" },
          topicArea: "work",
        },
        {
          en: "I could be wrong, but that doesn't look fresh.",
          bn: "আমি ভুল হতে পারি, তবে ওটা তাজা মনে হচ্ছে না।",
          slotValues: { CLAUSE: "that doesn't look fresh" },
          topicArea: "food",
        },
        {
          en: "I could be wrong, but I think they overcharged us.",
          bn: "আমি ভুল হতে পারি, তবে আমার মনে হয় তারা আমাদের থেকে বেশি নিয়েছে।",
          slotValues: { CLAUSE: "I think they overcharged us" },
          topicArea: "shopping",
        },
        {
          en: "I could be wrong, but the dosage seems too high.",
          bn: "আমি ভুল হতে পারি, তবে ডোজ বেশি মনে হচ্ছে।",
          slotValues: { CLAUSE: "the dosage seems too high" },
          topicArea: "health",
        },
        {
          en: "I could be wrong, but I think the event starts at 5.",
          bn: "আমি ভুল হতে পারি, তবে আমার মনে হয় অনুষ্ঠান ৫টায় শুরু।",
          slotValues: { CLAUSE: "I think the event starts at 5" },
          topicArea: "daily_life",
        },
        {
          en: "I could be wrong, but the deadline was last week.",
          bn: "আমি ভুল হতে পারি, তবে সময়সীমা গত সপ্তাহে ছিল।",
          slotValues: { CLAUSE: "the deadline was last week" },
          topicArea: "work",
        },
        {
          en: "I could be wrong, but I've seen this place before.",
          bn: "আমি ভুল হতে পারি, তবে আমি এই জায়গাটা আগে দেখেছি।",
          slotValues: { CLAUSE: "I've seen this place before" },
          topicArea: "travel",
        },
        {
          en: "I could be wrong, but the formula looks incorrect.",
          bn: "আমি ভুল হতে পারি, তবে সূত্রটি ভুল মনে হচ্ছে।",
          slotValues: { CLAUSE: "the formula looks incorrect" },
          topicArea: "education",
        },
        {
          en: "I could be wrong, but I think there's too much salt.",
          bn: "আমি ভুল হতে পারি, তবে আমার মনে হয় অনেক বেশি লবণ হয়েছে।",
          slotValues: { CLAUSE: "I think there's too much salt" },
          topicArea: "food",
        },
        {
          en: "I could be wrong, but the warranty may have expired.",
          bn: "আমি ভুল হতে পারি, তবে ওয়ারেন্টির মেয়াদ শেষ হয়ে থাকতে পারে।",
          slotValues: { CLAUSE: "the warranty may have expired" },
          topicArea: "shopping",
        },
        {
          en: "I could be wrong, but these symptoms sound like allergies.",
          bn: "আমি ভুল হতে পারি, তবে এই উপসর্গগুলো অ্যালার্জি মনে হচ্ছে।",
          slotValues: { CLAUSE: "these symptoms sound like allergies" },
          topicArea: "health",
        },
        {
          en: "I could be wrong, but he seemed very happy.",
          bn: "আমি ভুল হতে পারি, তবে সে খুব খুশি মনে হচ্ছিল।",
          slotValues: { CLAUSE: "he seemed very happy" },
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote:
        "A humble way to share an opinion while leaving room for correction. Shows good social awareness.",
      usageNote_bn:
        "সংশোধনের সুযোগ রেখে মতামত শেয়ার করার একটি বিনয়ী উপায়। ভালো সামাজিক সচেতনতা দেখায়।",
      combinableWith: ["R8.1", "R8.3"],
      banglaStructureMap:
        "আমি ভুল হতে পারি (Hedge) + তবে (but) + [CLAUSE] (Opinion/Observation)",
    },
    {
      id: "R8.5",
      formula: "If I'm not mistaken, [CLAUSE]",
      formula_bn: "আমি যদি ভুল না করি, [উপবাক্য]",
      patternName: "Polite Qualification",
      patternName_bn: "ভদ্র যোগ্যতা",
      slots: [
        {
          name: "CLAUSE",
          description: "A statement you believe to be true but want to be cautious about",
          description_bn: "একটি বিবৃতি যা আপনি সত্য বলে বিশ্বাস করেন কিন্তু সতর্ক থাকতে চান",
          acceptedTypes: ["clause"],
          examples: [
            "you used to work at that company",
            "the discount applies to all items",
            "the event is next Saturday",
          ],
        },
      ],
      examples: [
        {
          en: "If I'm not mistaken, you used to work at that company.",
          bn: "আমি যদি ভুল না করি, আপনি সেই কোম্পানিতে কাজ করতেন।",
          slotValues: { CLAUSE: "you used to work at that company" },
          topicArea: "work",
        },
        {
          en: "If I'm not mistaken, the discount applies to all items.",
          bn: "আমি যদি ভুল না করি, ছাড় সব পণ্যে প্রযোজ্য।",
          slotValues: { CLAUSE: "the discount applies to all items" },
          topicArea: "shopping",
        },
        {
          en: "If I'm not mistaken, the event is next Saturday.",
          bn: "আমি যদি ভুল না করি, অনুষ্ঠান আগামী শনিবারে।",
          slotValues: { CLAUSE: "the event is next Saturday" },
          topicArea: "daily_life",
        },
        {
          en: "If I'm not mistaken, the hotel has a rooftop pool.",
          bn: "আমি যদি ভুল না করি, হোটেলের ছাদে সুইমিং পুল আছে।",
          slotValues: { CLAUSE: "the hotel has a rooftop pool" },
          topicArea: "travel",
        },
        {
          en: "If I'm not mistaken, the exam is open book.",
          bn: "আমি যদি ভুল না করি, পরীক্ষায় বই দেখে লেখা যায়।",
          slotValues: { CLAUSE: "the exam is open book" },
          topicArea: "education",
        },
        {
          en: "If I'm not mistaken, this dish contains peanuts.",
          bn: "আমি যদি ভুল না করি, এই খাবারে চিনাবাদাম আছে।",
          slotValues: { CLAUSE: "this dish contains peanuts" },
          topicArea: "food",
        },
        {
          en: "If I'm not mistaken, the prescription is for 10 days.",
          bn: "আমি যদি ভুল না করি, প্রেসক্রিপশন ১০ দিনের জন্য।",
          slotValues: { CLAUSE: "the prescription is for 10 days" },
          topicArea: "health",
        },
        {
          en: "If I'm not mistaken, you two went to the same school.",
          bn: "আমি যদি ভুল না করি, তোমরা দুজন একই স্কুলে পড়তে।",
          slotValues: { CLAUSE: "you two went to the same school" },
          topicArea: "relationships",
        },
        {
          en: "If I'm not mistaken, the report is due on Friday.",
          bn: "আমি যদি ভুল না করি, রিপোর্ট শুক্রবারের মধ্যে জমা দিতে হবে।",
          slotValues: { CLAUSE: "the report is due on Friday" },
          topicArea: "work",
        },
        {
          en: "If I'm not mistaken, this is the longest bridge in the country.",
          bn: "আমি যদি ভুল না করি, এটি দেশের সবচেয়ে দীর্ঘ সেতু।",
          slotValues: { CLAUSE: "this is the longest bridge in the country" },
          topicArea: "travel",
        },
        {
          en: "If I'm not mistaken, the tuition went up this year.",
          bn: "আমি যদি ভুল না করি, এই বছর টিউশন বেড়েছে।",
          slotValues: { CLAUSE: "the tuition went up this year" },
          topicArea: "education",
        },
        {
          en: "If I'm not mistaken, that brand is organic.",
          bn: "আমি যদি ভুল না করি, সেই ব্র্যান্ডটি জৈব।",
          slotValues: { CLAUSE: "that brand is organic" },
          topicArea: "food",
        },
        {
          en: "If I'm not mistaken, the store offers free returns.",
          bn: "আমি যদি ভুল না করি, দোকানটি বিনামূল্যে ফেরত দেয়।",
          slotValues: { CLAUSE: "the store offers free returns" },
          topicArea: "shopping",
        },
        {
          en: "If I'm not mistaken, the doctor's office is on the third floor.",
          bn: "আমি যদি ভুল না করি, ডাক্তারের চেম্বার তৃতীয় তলায়।",
          slotValues: { CLAUSE: "the doctor's office is on the third floor" },
          topicArea: "health",
        },
        {
          en: "If I'm not mistaken, they celebrated their anniversary last week.",
          bn: "আমি যদি ভুল না করি, তারা গত সপ্তাহে তাদের বার্ষিকী উদযাপন করেছে।",
          slotValues: { CLAUSE: "they celebrated their anniversary last week" },
          topicArea: "relationships",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "A polite and sophisticated way to present information while acknowledging you might be incorrect. Works well in formal settings.",
      usageNote_bn:
        "আপনি ভুল হতে পারেন তা স্বীকার করে তথ্য উপস্থাপনের একটি ভদ্র ও পরিশীলিত উপায়। আনুষ্ঠানিক পরিবেশে ভালো কাজ করে।",
      combinableWith: ["R8.2"],
      banglaStructureMap:
        "আমি যদি ভুল না করি (Conditional hedge) + [CLAUSE] (Statement)",
    },
  ],
};
