import { PatternCategory } from "@/types/pattern";

export const categoryR9: PatternCategory = {
  id: "R9",
  slug: "inclusion-exclusion",
  name: "Inclusion & Exclusion",
  name_bn: "অন্তর্ভুক্তি ও বর্জন",
  description:
    "Specify what is included, excluded, or counts as part of something.",
  description_bn:
    "কিছু কী অন্তর্ভুক্ত, বর্জিত বা কোনো কিছুর অংশ হিসেবে গণ্য তা নির্দিষ্ট করুন।",
  icon: "🔲",
  group: "R",
  groupName: "Logical & Discourse Patterns",
  groupName_bn: "যৌক্তিক ও বক্তৃতা প্যাটার্ন",
  difficulty: "advanced",
  patterns: [
    {
      id: "R9.1",
      formula: "Including [THING]",
      formula_bn: "[বিষয়] সহ",
      patternName: "Inclusion",
      patternName_bn: "অন্তর্ভুক্তি",
      slots: [
        {
          name: "THING",
          description: "Something specifically included",
          description_bn: "নির্দিষ্টভাবে অন্তর্ভুক্ত কিছু",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["tax", "breakfast", "shipping"],
        },
      ],
      examples: [
        {
          en: "The price is 5000 taka, including tax.",
          bn: "দাম ৫০০০ টাকা, ট্যাক্স সহ।",
          slotValues: { THING: "tax" },
          topicArea: "shopping",
        },
        {
          en: "The hotel package covers everything, including breakfast.",
          bn: "হোটেল প্যাকেজে সবকিছু আছে, সকালের নাস্তা সহ।",
          slotValues: { THING: "breakfast" },
          topicArea: "travel",
        },
        {
          en: "Everyone is invited, including the new employees.",
          bn: "সবাই আমন্ত্রিত, নতুন কর্মচারী সহ।",
          slotValues: { THING: "the new employees" },
          topicArea: "work",
        },
        {
          en: "All topics will be covered, including grammar.",
          bn: "সব বিষয় কভার করা হবে, ব্যাকরণ সহ।",
          slotValues: { THING: "grammar" },
          topicArea: "education",
        },
        {
          en: "The meal plan covers all meals, including snacks.",
          bn: "খাদ্য পরিকল্পনায় সব খাবার আছে, স্ন্যাকস সহ।",
          slotValues: { THING: "snacks" },
          topicArea: "food",
        },
        {
          en: "The insurance covers many things, including dental care.",
          bn: "বীমায় অনেক কিছু আছে, দন্ত চিকিৎসা সহ।",
          slotValues: { THING: "dental care" },
          topicArea: "health",
        },
        {
          en: "The whole family came, including the grandparents.",
          bn: "পুরো পরিবার এসেছিল, দাদা-দাদি সহ।",
          slotValues: { THING: "the grandparents" },
          topicArea: "relationships",
        },
        {
          en: "The apartment comes furnished, including appliances.",
          bn: "অ্যাপার্টমেন্টটি আসবাবপত্র সহ আসে, যন্ত্রপাতি সহ।",
          slotValues: { THING: "appliances" },
          topicArea: "daily_life",
        },
        {
          en: "The fee covers all services, including consultation.",
          bn: "ফি-তে সব সেবা অন্তর্ভুক্ত, পরামর্শ সহ।",
          slotValues: { THING: "consultation" },
          topicArea: "health",
        },
        {
          en: "The tour covers all major sites, including the palace.",
          bn: "ট্যুরে সব প্রধান স্থান আছে, প্রাসাদ সহ।",
          slotValues: { THING: "the palace" },
          topicArea: "travel",
        },
        {
          en: "All departments will participate, including marketing.",
          bn: "সব বিভাগ অংশগ্রহণ করবে, বিপণন সহ।",
          slotValues: { THING: "marketing" },
          topicArea: "work",
        },
        {
          en: "The order comes with everything, including free shipping.",
          bn: "অর্ডারে সবকিছু আছে, বিনামূল্যে শিপিং সহ।",
          slotValues: { THING: "free shipping" },
          topicArea: "shopping",
        },
        {
          en: "The syllabus includes all chapters, including the appendix.",
          bn: "সিলেবাসে সব অধ্যায় আছে, পরিশিষ্ট সহ।",
          slotValues: { THING: "the appendix" },
          topicArea: "education",
        },
        {
          en: "The buffet offers many options, including vegan dishes.",
          bn: "বুফেতে অনেক অপশন আছে, ভেগান খাবার সহ।",
          slotValues: { THING: "vegan dishes" },
          topicArea: "food",
        },
        {
          en: "All guests are welcome, including children.",
          bn: "সব অতিথি স্বাগত, শিশুদের সহ।",
          slotValues: { THING: "children" },
          topicArea: "relationships",
        },
      ],
      formality: "polite",
      difficulty: "advanced",
      usageNote:
        "Used to specify that something is part of a larger group or total. Very common in commercial and professional contexts.",
      usageNote_bn:
        "কিছু একটি বৃহত্তর গোষ্ঠী বা মোটের অংশ তা নির্দিষ্ট করতে ব্যবহৃত হয়। বাণিজ্যিক ও পেশাদার প্রসঙ্গে খুবই সাধারণ।",
      combinableWith: ["R9.2"],
      banglaStructureMap:
        "[THING] সহ (Including + Object)",
    },
    {
      id: "R9.2",
      formula: "Not including [THING]",
      formula_bn: "[বিষয়] ছাড়া",
      patternName: "Exclusion",
      patternName_bn: "বর্জন",
      slots: [
        {
          name: "THING",
          description: "Something specifically excluded",
          description_bn: "নির্দিষ্টভাবে বর্জিত কিছু",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["delivery charges", "weekends", "accessories"],
        },
      ],
      examples: [
        {
          en: "The price is 3000 taka, not including delivery charges.",
          bn: "দাম ৩০০০ টাকা, ডেলিভারি চার্জ ছাড়া।",
          slotValues: { THING: "delivery charges" },
          topicArea: "shopping",
        },
        {
          en: "We're open every day, not including weekends.",
          bn: "আমরা প্রতিদিন খোলা, সপ্তাহান্ত ছাড়া।",
          slotValues: { THING: "weekends" },
          topicArea: "work",
        },
        {
          en: "The package comes with a phone, not including accessories.",
          bn: "প্যাকেজে ফোন আছে, আনুষাঙ্গিক ছাড়া।",
          slotValues: { THING: "accessories" },
          topicArea: "shopping",
        },
        {
          en: "The hotel rate is per night, not including meals.",
          bn: "হোটেলের রেট প্রতি রাতের জন্য, খাবার ছাড়া।",
          slotValues: { THING: "meals" },
          topicArea: "travel",
        },
        {
          en: "The course fee is 10,000 taka, not including books.",
          bn: "কোর্স ফি ১০,০০০ টাকা, বই ছাড়া।",
          slotValues: { THING: "books" },
          topicArea: "education",
        },
        {
          en: "The set menu is 500 taka, not including drinks.",
          bn: "সেট মেনু ৫০০ টাকা, পানীয় ছাড়া।",
          slotValues: { THING: "drinks" },
          topicArea: "food",
        },
        {
          en: "The treatment costs 20,000 taka, not including medication.",
          bn: "চিকিৎসায় ২০,০০০ টাকা খরচ, ওষুধ ছাড়া।",
          slotValues: { THING: "medication" },
          topicArea: "health",
        },
        {
          en: "Everyone was there, not including the boss.",
          bn: "সবাই সেখানে ছিল, বস ছাড়া।",
          slotValues: { THING: "the boss" },
          topicArea: "work",
        },
        {
          en: "The trip costs 50,000 taka, not including airfare.",
          bn: "ভ্রমণে ৫০,০০০ টাকা খরচ, বিমানের টিকিট ছাড়া।",
          slotValues: { THING: "airfare" },
          topicArea: "travel",
        },
        {
          en: "There are 30 students in class, not including exchange students.",
          bn: "ক্লাসে ৩০ জন ছাত্র আছে, বিনিময় ছাত্র ছাড়া।",
          slotValues: { THING: "exchange students" },
          topicArea: "education",
        },
        {
          en: "The family dinner has 10 people, not including the kids.",
          bn: "পারিবারিক রাতের খাবারে ১০ জন আছে, বাচ্চাদের ছাড়া।",
          slotValues: { THING: "the kids" },
          topicArea: "relationships",
        },
        {
          en: "The bill is 2000 taka, not including service charge.",
          bn: "বিল ২০০০ টাকা, সার্ভিস চার্জ ছাড়া।",
          slotValues: { THING: "service charge" },
          topicArea: "food",
        },
        {
          en: "The building has 50 apartments, not including the penthouses.",
          bn: "ভবনে ৫০টি অ্যাপার্টমেন্ট আছে, পেন্টহাউস ছাড়া।",
          slotValues: { THING: "the penthouses" },
          topicArea: "daily_life",
        },
        {
          en: "The consultation fee is 500 taka, not including tests.",
          bn: "পরামর্শ ফি ৫০০ টাকা, পরীক্ষা ছাড়া।",
          slotValues: { THING: "tests" },
          topicArea: "health",
        },
        {
          en: "The rent is 12,000 taka, not including utilities.",
          bn: "ভাড়া ১২,০০০ টাকা, ইউটিলিটি ছাড়া।",
          slotValues: { THING: "utilities" },
          topicArea: "daily_life",
        },
      ],
      formality: "polite",
      difficulty: "advanced",
      usageNote:
        "Used to specify something that is explicitly left out of a total or group. Important for clarity in transactions.",
      usageNote_bn:
        "কোনো মোট বা গোষ্ঠী থেকে স্পষ্টভাবে বাদ দেওয়া কিছু নির্দিষ্ট করতে ব্যবহৃত হয়। লেনদেনে স্পষ্টতার জন্য গুরুত্বপূর্ণ।",
      combinableWith: ["R9.1"],
      banglaStructureMap:
        "[THING] ছাড়া (Excluding + Object)",
    },
    {
      id: "R9.3",
      formula: "[THING] counts as [THING2]",
      formula_bn: "[বিষয়] [বিষয়২] হিসেবে গণ্য",
      patternName: "Classification",
      patternName_bn: "শ্রেণিবিন্যাস",
      slots: [
        {
          name: "THING",
          description: "The item being classified",
          description_bn: "যে আইটেম শ্রেণিবদ্ধ করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase", "gerund"],
          examples: ["Walking", "This internship", "Tea"],
        },
        {
          name: "THING2",
          description: "The category it belongs to",
          description_bn: "যে শ্রেণিতে এটি পড়ে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["exercise", "work experience", "a beverage"],
        },
      ],
      examples: [
        {
          en: "Walking counts as exercise.",
          bn: "হাঁটা ব্যায়াম হিসেবে গণ্য।",
          slotValues: { THING: "Walking", THING2: "exercise" },
          topicArea: "health",
        },
        {
          en: "This internship counts as work experience.",
          bn: "এই ইন্টার্নশিপ কাজের অভিজ্ঞতা হিসেবে গণ্য।",
          slotValues: { THING: "This internship", THING2: "work experience" },
          topicArea: "work",
        },
        {
          en: "Tea counts as a beverage.",
          bn: "চা পানীয় হিসেবে গণ্য।",
          slotValues: { THING: "Tea", THING2: "a beverage" },
          topicArea: "food",
        },
        {
          en: "Reading counts as studying.",
          bn: "পড়া অধ্যয়ন হিসেবে গণ্য।",
          slotValues: { THING: "Reading", THING2: "studying" },
          topicArea: "education",
        },
        {
          en: "A layover counts as a stop.",
          bn: "লে-ওভার একটি থামা হিসেবে গণ্য।",
          slotValues: { THING: "A layover", THING2: "a stop" },
          topicArea: "travel",
        },
        {
          en: "Online shopping counts as a transaction.",
          bn: "অনলাইন কেনাকাটা একটি লেনদেন হিসেবে গণ্য।",
          slotValues: { THING: "Online shopping", THING2: "a transaction" },
          topicArea: "shopping",
        },
        {
          en: "Cooking together counts as quality time.",
          bn: "একসাথে রান্না করা মানসম্পন্ন সময় হিসেবে গণ্য।",
          slotValues: { THING: "Cooking together", THING2: "quality time" },
          topicArea: "relationships",
        },
        {
          en: "Yoga counts as physical activity.",
          bn: "যোগব্যায়াম শারীরিক কার্যকলাপ হিসেবে গণ্য।",
          slotValues: { THING: "Yoga", THING2: "physical activity" },
          topicArea: "health",
        },
        {
          en: "Volunteering counts as community service.",
          bn: "স্বেচ্ছাসেবা সমাজসেবা হিসেবে গণ্য।",
          slotValues: { THING: "Volunteering", THING2: "community service" },
          topicArea: "daily_life",
        },
        {
          en: "This project counts as your final assignment.",
          bn: "এই প্রকল্প তোমার চূড়ান্ত অ্যাসাইনমেন্ট হিসেবে গণ্য।",
          slotValues: { THING: "This project", THING2: "your final assignment" },
          topicArea: "education",
        },
        {
          en: "Freelancing counts as self-employment.",
          bn: "ফ্রিল্যান্সিং স্ব-কর্মসংস্থান হিসেবে গণ্য।",
          slotValues: { THING: "Freelancing", THING2: "self-employment" },
          topicArea: "work",
        },
        {
          en: "A smoothie counts as a meal replacement.",
          bn: "স্মুদি খাবারের বিকল্প হিসেবে গণ্য।",
          slotValues: { THING: "A smoothie", THING2: "a meal replacement" },
          topicArea: "food",
        },
        {
          en: "A gift card counts as a valid payment method.",
          bn: "গিফট কার্ড একটি বৈধ পেমেন্ট পদ্ধতি হিসেবে গণ্য।",
          slotValues: { THING: "A gift card", THING2: "a valid payment method" },
          topicArea: "shopping",
        },
        {
          en: "A road trip counts as a vacation.",
          bn: "রোড ট্রিপ ছুটি হিসেবে গণ্য।",
          slotValues: { THING: "A road trip", THING2: "a vacation" },
          topicArea: "travel",
        },
        {
          en: "Listening counts as a form of support.",
          bn: "শোনা সমর্থনের একটি রূপ হিসেবে গণ্য।",
          slotValues: { THING: "Listening", THING2: "a form of support" },
          topicArea: "relationships",
        },
      ],
      formality: "polite",
      difficulty: "advanced",
      usageNote:
        "Used to classify or categorize something. Common in rules, policies, and definitions.",
      usageNote_bn:
        "কিছু শ্রেণিবদ্ধ বা শ্রেণিকরণ করতে ব্যবহৃত হয়। নিয়ম, নীতি ও সংজ্ঞায় সাধারণ।",
      combinableWith: ["R9.1"],
      banglaStructureMap:
        "[THING] (Subject) + [THING2] হিসেবে গণ্য (counts as + Category)",
    },
    {
      id: "R9.4",
      formula: "Aside from [THING], [CLAUSE]",
      formula_bn: "[বিষয়] ছাড়া, [উপবাক্য]",
      patternName: "Setting Aside",
      patternName_bn: "পাশে রেখে",
      slots: [
        {
          name: "THING",
          description: "Something you are setting aside or excluding from the statement",
          description_bn: "এমন কিছু যা আপনি বিবৃতি থেকে বাদ রাখছেন",
          acceptedTypes: ["noun", "noun_phrase", "gerund"],
          examples: ["the weather", "the price", "a few issues"],
        },
        {
          name: "CLAUSE",
          description: "Your main statement",
          description_bn: "আপনার মূল বিবৃতি",
          acceptedTypes: ["clause"],
          examples: [
            "the trip was great",
            "everything went well",
            "I enjoyed it",
          ],
        },
      ],
      examples: [
        {
          en: "Aside from the weather, the trip was great.",
          bn: "আবহাওয়া ছাড়া, ভ্রমণটি দারুণ ছিল।",
          slotValues: { THING: "the weather", CLAUSE: "the trip was great" },
          topicArea: "travel",
        },
        {
          en: "Aside from the price, everything was perfect.",
          bn: "দাম ছাড়া, সবকিছু নিখুঁত ছিল।",
          slotValues: { THING: "the price", CLAUSE: "everything was perfect" },
          topicArea: "shopping",
        },
        {
          en: "Aside from a few issues, the project went well.",
          bn: "কয়েকটি সমস্যা ছাড়া, প্রকল্পটি ভালো হয়েছে।",
          slotValues: { THING: "a few issues", CLAUSE: "the project went well" },
          topicArea: "work",
        },
        {
          en: "Aside from the final exam, the course was enjoyable.",
          bn: "চূড়ান্ত পরীক্ষা ছাড়া, কোর্সটি উপভোগ্য ছিল।",
          slotValues: { THING: "the final exam", CLAUSE: "the course was enjoyable" },
          topicArea: "education",
        },
        {
          en: "Aside from the spice level, the food was delicious.",
          bn: "মসলার পরিমাণ ছাড়া, খাবারটি সুস্বাদু ছিল।",
          slotValues: { THING: "the spice level", CLAUSE: "the food was delicious" },
          topicArea: "food",
        },
        {
          en: "Aside from the waiting time, the service was excellent.",
          bn: "অপেক্ষার সময় ছাড়া, সেবা চমৎকার ছিল।",
          slotValues: { THING: "the waiting time", CLAUSE: "the service was excellent" },
          topicArea: "health",
        },
        {
          en: "Aside from the distance, the apartment is ideal.",
          bn: "দূরত্ব ছাড়া, অ্যাপার্টমেন্টটি আদর্শ।",
          slotValues: { THING: "the distance", CLAUSE: "the apartment is ideal" },
          topicArea: "daily_life",
        },
        {
          en: "Aside from that one argument, we get along very well.",
          bn: "সেই একটি ঝগড়া ছাড়া, আমরা খুব ভালোভাবে চলি।",
          slotValues: { THING: "that one argument", CLAUSE: "we get along very well" },
          topicArea: "relationships",
        },
        {
          en: "Aside from the long hours, I love my job.",
          bn: "দীর্ঘ কাজের সময় ছাড়া, আমি আমার চাকরি পছন্দ করি।",
          slotValues: { THING: "the long hours", CLAUSE: "I love my job" },
          topicArea: "work",
        },
        {
          en: "Aside from the noise, the hotel was comfortable.",
          bn: "শব্দ ছাড়া, হোটেলটি আরামদায়ক ছিল।",
          slotValues: { THING: "the noise", CLAUSE: "the hotel was comfortable" },
          topicArea: "travel",
        },
        {
          en: "Aside from the homework, the class is fun.",
          bn: "হোমওয়ার্ক ছাড়া, ক্লাসটি মজার।",
          slotValues: { THING: "the homework", CLAUSE: "the class is fun" },
          topicArea: "education",
        },
        {
          en: "Aside from the dessert, I didn't enjoy the meal.",
          bn: "মিষ্টান্ন ছাড়া, আমি খাবারটি উপভোগ করিনি।",
          slotValues: { THING: "the dessert", CLAUSE: "I didn't enjoy the meal" },
          topicArea: "food",
        },
        {
          en: "Aside from the cost, the treatment was effective.",
          bn: "খরচ ছাড়া, চিকিৎসা কার্যকর ছিল।",
          slotValues: { THING: "the cost", CLAUSE: "the treatment was effective" },
          topicArea: "health",
        },
        {
          en: "Aside from the color, the product is exactly what I wanted.",
          bn: "রং ছাড়া, পণ্যটি ঠিক তাই যা আমি চেয়েছিলাম।",
          slotValues: { THING: "the color", CLAUSE: "the product is exactly what I wanted" },
          topicArea: "shopping",
        },
        {
          en: "Aside from being a bit shy, he's a great person.",
          bn: "একটু লাজুক হওয়া ছাড়া, সে একজন দারুণ মানুষ।",
          slotValues: { THING: "being a bit shy", CLAUSE: "he's a great person" },
          topicArea: "relationships",
        },
      ],
      formality: "polite",
      difficulty: "advanced",
      usageNote:
        "Used to acknowledge an exception before making your main point. Shows nuanced thinking.",
      usageNote_bn:
        "আপনার মূল বক্তব্য বলার আগে একটি ব্যতিক্রম স্বীকার করতে ব্যবহৃত হয়। সূক্ষ্ম চিন্তাভাবনা দেখায়।",
      combinableWith: ["R9.2"],
      banglaStructureMap:
        "[THING] ছাড়া (Aside from + Exception) + [CLAUSE] (Main statement)",
    },
    {
      id: "R9.5",
      formula: "With the exception of [THING], [CLAUSE]",
      formula_bn: "[বিষয়] ব্যতীত, [উপবাক্য]",
      patternName: "Formal Exception",
      patternName_bn: "আনুষ্ঠানিক ব্যতিক্রম",
      slots: [
        {
          name: "THING",
          description: "The exception being noted",
          description_bn: "যে ব্যতিক্রমটি উল্লেখ করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["public holidays", "senior citizens", "perishable items"],
        },
        {
          name: "CLAUSE",
          description: "The general rule or statement",
          description_bn: "সাধারণ নিয়ম বা বিবৃতি",
          acceptedTypes: ["clause"],
          examples: [
            "all offices are open",
            "everyone must pay full price",
            "all items are returnable",
          ],
        },
      ],
      examples: [
        {
          en: "With the exception of public holidays, all offices are open.",
          bn: "সরকারি ছুটি ব্যতীত, সব অফিস খোলা।",
          slotValues: { THING: "public holidays", CLAUSE: "all offices are open" },
          topicArea: "work",
        },
        {
          en: "With the exception of senior citizens, everyone must pay full price.",
          bn: "প্রবীণ নাগরিক ব্যতীত, সবাইকে পুরো দাম দিতে হবে।",
          slotValues: { THING: "senior citizens", CLAUSE: "everyone must pay full price" },
          topicArea: "shopping",
        },
        {
          en: "With the exception of perishable items, all products are returnable.",
          bn: "পচনশীল পণ্য ব্যতীত, সব পণ্য ফেরতযোগ্য।",
          slotValues: { THING: "perishable items", CLAUSE: "all products are returnable" },
          topicArea: "shopping",
        },
        {
          en: "With the exception of the final chapter, I've read the entire book.",
          bn: "শেষ অধ্যায় ব্যতীত, আমি পুরো বইটি পড়ে ফেলেছি।",
          slotValues: { THING: "the final chapter", CLAUSE: "I've read the entire book" },
          topicArea: "education",
        },
        {
          en: "With the exception of rainy days, we go for a walk every evening.",
          bn: "বৃষ্টির দিন ব্যতীত, আমরা প্রতি সন্ধ্যায় হাঁটতে যাই।",
          slotValues: { THING: "rainy days", CLAUSE: "we go for a walk every evening" },
          topicArea: "health",
        },
        {
          en: "With the exception of seafood, I eat everything.",
          bn: "সামুদ্রিক খাবার ব্যতীত, আমি সবকিছু খাই।",
          slotValues: { THING: "seafood", CLAUSE: "I eat everything" },
          topicArea: "food",
        },
        {
          en: "With the exception of the monsoon season, the weather is pleasant.",
          bn: "বর্ষাকাল ব্যতীত, আবহাওয়া মনোরম।",
          slotValues: { THING: "the monsoon season", CLAUSE: "the weather is pleasant" },
          topicArea: "travel",
        },
        {
          en: "With the exception of my brother, no one knows about this.",
          bn: "আমার ভাই ব্যতীত, কেউ এটা জানে না।",
          slotValues: { THING: "my brother", CLAUSE: "no one knows about this" },
          topicArea: "relationships",
        },
        {
          en: "With the exception of emergency cases, appointments are required.",
          bn: "জরুরি ক্ষেত্র ব্যতীত, অ্যাপয়েন্টমেন্ট প্রয়োজন।",
          slotValues: { THING: "emergency cases", CLAUSE: "appointments are required" },
          topicArea: "health",
        },
        {
          en: "With the exception of the parking lot, the building was renovated.",
          bn: "পার্কিং লট ব্যতীত, পুরো ভবন সংস্কার করা হয়েছে।",
          slotValues: { THING: "the parking lot", CLAUSE: "the building was renovated" },
          topicArea: "daily_life",
        },
        {
          en: "With the exception of interns, all employees get benefits.",
          bn: "ইন্টার্ন ব্যতীত, সব কর্মচারী সুবিধা পান।",
          slotValues: { THING: "interns", CLAUSE: "all employees get benefits" },
          topicArea: "work",
        },
        {
          en: "With the exception of economy class, all seats are spacious.",
          bn: "ইকোনমি ক্লাস ব্যতীত, সব আসন প্রশস্ত।",
          slotValues: { THING: "economy class", CLAUSE: "all seats are spacious" },
          topicArea: "travel",
        },
        {
          en: "With the exception of math, I enjoy all subjects.",
          bn: "গণিত ব্যতীত, আমি সব বিষয় উপভোগ করি।",
          slotValues: { THING: "math", CLAUSE: "I enjoy all subjects" },
          topicArea: "education",
        },
        {
          en: "With the exception of spicy dishes, the menu is suitable for everyone.",
          bn: "ঝাল খাবার ব্যতীত, মেনু সবার জন্য উপযুক্ত।",
          slotValues: { THING: "spicy dishes", CLAUSE: "the menu is suitable for everyone" },
          topicArea: "food",
        },
        {
          en: "With the exception of sale items, all products can be exchanged.",
          bn: "সেলের পণ্য ব্যতীত, সব পণ্য বিনিময় করা যায়।",
          slotValues: { THING: "sale items", CLAUSE: "all products can be exchanged" },
          topicArea: "shopping",
        },
      ],
      formality: "formal",
      difficulty: "advanced",
      usageNote:
        "A formal way to note an exception to a general rule. Common in policies, contracts, and official announcements.",
      usageNote_bn:
        "সাধারণ নিয়মের ব্যতিক্রম উল্লেখ করার একটি আনুষ্ঠানিক উপায়। নীতি, চুক্তি ও সরকারি ঘোষণায় সাধারণ।",
      combinableWith: ["R9.2"],
      banglaStructureMap:
        "[THING] ব্যতীত (With the exception of) + [CLAUSE] (General rule)",
    },
  ],
};
