import { PatternCategory } from "@/types/pattern";

export const categoryS1: PatternCategory = {
  id: "S1",
  slug: "non-defining-relative-clauses",
  name: "Non-Defining Relative Clauses",
  name_bn: "অ-নির্ধারক সম্পর্কমূলক উপবাক্য",
  description: "Add extra information with commas and who/which",
  description_bn: "কমা এবং who/which দিয়ে অতিরিক্ত তথ্য যোগ করুন",
  icon: "📌",
  group: "S",
  groupName: "Advanced Structural Patterns",
  groupName_bn: "উন্নত গঠনমূলক প্যাটার্ন",
  difficulty: "advanced",
  patterns: [
    {
      id: "S1.1",
      formula: "[PERSON], who [CLAUSE], is [DESCRIPTION]",
      formula_bn: "[ব্যক্তি], যিনি [উপবাক্য], [বর্ণনা]",
      patternName: "Who + Non-Defining (Subject)",
      patternName_bn: "Who + অ-নির্ধারক (কর্তা)",
      slots: [
        {
          name: "PERSON",
          description: "A specific person being described",
          description_bn: "একটি নির্দিষ্ট ব্যক্তি যাকে বর্ণনা করা হচ্ছে",
          acceptedTypes: ["person", "noun_phrase"],
          examples: ["My teacher", "Our manager", "My sister"],
        },
        {
          name: "CLAUSE",
          description: "Extra information about the person",
          description_bn: "ব্যক্তি সম্পর্কে অতিরিক্ত তথ্য",
          acceptedTypes: ["clause"],
          examples: ["is from England", "lives next door", "studied abroad"],
        },
        {
          name: "DESCRIPTION",
          description: "A description or quality of the person",
          description_bn: "ব্যক্তির একটি বর্ণনা বা গুণ",
          acceptedTypes: ["adjective", "adjective_phrase", "description"],
          examples: ["very kind", "extremely talented", "always helpful"],
        },
      ],
      examples: [
        {
          en: "My teacher, who is from England, is very kind.",
          bn: "আমার শিক্ষক, যিনি ইংল্যান্ড থেকে এসেছেন, খুব দয়ালু।",
          slotValues: { PERSON: "My teacher", CLAUSE: "is from England", DESCRIPTION: "very kind" },
        },
        {
          en: "Our manager, who joined last year, is very efficient.",
          bn: "আমাদের ম্যানেজার, যিনি গত বছর যোগ দিয়েছেন, খুব দক্ষ।",
          slotValues: { PERSON: "Our manager", CLAUSE: "joined last year", DESCRIPTION: "very efficient" },
        },
        {
          en: "My sister, who lives in London, is a doctor.",
          bn: "আমার বোন, যিনি লন্ডনে থাকেন, একজন ডাক্তার।",
          slotValues: { PERSON: "My sister", CLAUSE: "lives in London", DESCRIPTION: "a doctor" },
        },
        {
          en: "The professor, who wrote that book, is world-famous.",
          bn: "সেই অধ্যাপক, যিনি ওই বইটি লিখেছেন, বিশ্ববিখ্যাত।",
          slotValues: { PERSON: "The professor", CLAUSE: "wrote that book", DESCRIPTION: "world-famous" },
        },
        {
          en: "My neighbor, who is a retired pilot, is very friendly.",
          bn: "আমার প্রতিবেশী, যিনি একজন অবসরপ্রাপ্ত পাইলট, খুব বন্ধুত্বপূর্ণ।",
          slotValues: { PERSON: "My neighbor", CLAUSE: "is a retired pilot", DESCRIPTION: "very friendly" },
        },
        {
          en: "Dr. Rahman, who treated my father, is highly respected.",
          bn: "ডাঃ রহমান, যিনি আমার বাবার চিকিৎসা করেছেন, অত্যন্ত সম্মানিত।",
          slotValues: { PERSON: "Dr. Rahman", CLAUSE: "treated my father", DESCRIPTION: "highly respected" },
        },
        {
          en: "My uncle, who owns a restaurant, is an excellent cook.",
          bn: "আমার চাচা, যিনি একটি রেস্তোরাঁর মালিক, একজন চমৎকার রাঁধুনি।",
          slotValues: { PERSON: "My uncle", CLAUSE: "owns a restaurant", DESCRIPTION: "an excellent cook" },
        },
        {
          en: "The president, who visited yesterday, is very charismatic.",
          bn: "রাষ্ট্রপতি, যিনি গতকাল পরিদর্শনে এসেছিলেন, অত্যন্ত ক্যারিশম্যাটিক।",
          slotValues: { PERSON: "The president", CLAUSE: "visited yesterday", DESCRIPTION: "very charismatic" },
        },
        {
          en: "My cousin, who studies engineering, is incredibly smart.",
          bn: "আমার কাজিন, যিনি ইঞ্জিনিয়ারিং পড়েন, অবিশ্বাস্যভাবে মেধাবী।",
          slotValues: { PERSON: "My cousin", CLAUSE: "studies engineering", DESCRIPTION: "incredibly smart" },
        },
        {
          en: "The CEO, who started from nothing, is an inspiration.",
          bn: "সিইও, যিনি শূন্য থেকে শুরু করেছেন, একটি অনুপ্রেরণা।",
          slotValues: { PERSON: "The CEO", CLAUSE: "started from nothing", DESCRIPTION: "an inspiration" },
        },
        {
          en: "Her mother, who speaks five languages, is a translator.",
          bn: "তার মা, যিনি পাঁচটি ভাষায় কথা বলেন, একজন অনুবাদক।",
          slotValues: { PERSON: "Her mother", CLAUSE: "speaks five languages", DESCRIPTION: "a translator" },
        },
        {
          en: "My best friend, who moved to Canada, is really happy there.",
          bn: "আমার সবচেয়ে ভালো বন্ধু, যে কানাডায় চলে গেছে, সেখানে সত্যিই সুখী।",
          slotValues: { PERSON: "My best friend", CLAUSE: "moved to Canada", DESCRIPTION: "really happy there" },
        },
        {
          en: "The artist, who painted this mural, is quite young.",
          bn: "শিল্পী, যিনি এই দেয়ালচিত্রটি এঁকেছেন, বেশ তরুণ।",
          slotValues: { PERSON: "The artist", CLAUSE: "painted this mural", DESCRIPTION: "quite young" },
        },
        {
          en: "Our coach, who won the championship twice, is retiring soon.",
          bn: "আমাদের কোচ, যিনি দুবার চ্যাম্পিয়নশিপ জিতেছেন, শীঘ্রই অবসর নিচ্ছেন।",
          slotValues: { PERSON: "Our coach", CLAUSE: "won the championship twice", DESCRIPTION: "retiring soon" },
        },
        {
          en: "The chef, who trained in Paris, is exceptionally talented.",
          bn: "শেফ, যিনি প্যারিসে প্রশিক্ষণ নিয়েছেন, ব্যতিক্রমীভাবে প্রতিভাবান।",
          slotValues: { PERSON: "The chef", CLAUSE: "trained in Paris", DESCRIPTION: "exceptionally talented" },
        },
      ],
      formality: "formal",
      difficulty: "advanced",
    },
    {
      id: "S1.2",
      formula: "[THING], which [CLAUSE], is [DESCRIPTION]",
      formula_bn: "[বস্তু], যা [উপবাক্য], [বর্ণনা]",
      patternName: "Which + Non-Defining (Thing)",
      patternName_bn: "Which + অ-নির্ধারক (বস্তু)",
      slots: [
        {
          name: "THING",
          description: "A specific thing or place being described",
          description_bn: "একটি নির্দিষ্ট বস্তু বা স্থান যা বর্ণনা করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["The Eiffel Tower", "This book", "Our office"],
        },
        {
          name: "CLAUSE",
          description: "Extra information about the thing",
          description_bn: "বস্তু সম্পর্কে অতিরিক্ত তথ্য",
          acceptedTypes: ["clause"],
          examples: ["was built in 1889", "I bought yesterday", "is on Main Street"],
        },
        {
          name: "DESCRIPTION",
          description: "A description of the thing",
          description_bn: "বস্তুর একটি বর্ণনা",
          acceptedTypes: ["adjective", "adjective_phrase", "description"],
          examples: ["very impressive", "quite interesting", "really useful"],
        },
      ],
      examples: [
        {
          en: "The Eiffel Tower, which was built in 1889, is a famous landmark.",
          bn: "আইফেল টাওয়ার, যা ১৮৮৯ সালে নির্মিত হয়েছিল, একটি বিখ্যাত ল্যান্ডমার্ক।",
          slotValues: { THING: "The Eiffel Tower", CLAUSE: "was built in 1889", DESCRIPTION: "a famous landmark" },
        },
        {
          en: "This book, which I bought yesterday, is really fascinating.",
          bn: "এই বইটি, যা আমি গতকাল কিনেছি, সত্যিই চমকপ্রদ।",
          slotValues: { THING: "This book", CLAUSE: "I bought yesterday", DESCRIPTION: "really fascinating" },
        },
        {
          en: "Our office, which is on the top floor, is very spacious.",
          bn: "আমাদের অফিস, যা উপরের তলায়, খুব প্রশস্ত।",
          slotValues: { THING: "Our office", CLAUSE: "is on the top floor", DESCRIPTION: "very spacious" },
        },
        {
          en: "The project, which took six months, is finally complete.",
          bn: "প্রকল্পটি, যা ছয় মাস লেগেছিল, অবশেষে সম্পূর্ণ।",
          slotValues: { THING: "The project", CLAUSE: "took six months", DESCRIPTION: "finally complete" },
        },
        {
          en: "His car, which he bought last week, is already broken.",
          bn: "তার গাড়ি, যা সে গত সপ্তাহে কিনেছে, ইতিমধ্যে নষ্ট হয়ে গেছে।",
          slotValues: { THING: "His car", CLAUSE: "he bought last week", DESCRIPTION: "already broken" },
        },
        {
          en: "The report, which was submitted on Friday, is very detailed.",
          bn: "রিপোর্টটি, যা শুক্রবার জমা দেওয়া হয়েছিল, খুব বিস্তারিত।",
          slotValues: { THING: "The report", CLAUSE: "was submitted on Friday", DESCRIPTION: "very detailed" },
        },
        {
          en: "The museum, which opened last month, is attracting many visitors.",
          bn: "জাদুঘরটি, যা গত মাসে খোলা হয়েছে, অনেক দর্শককে আকৃষ্ট করছে।",
          slotValues: { THING: "The museum", CLAUSE: "opened last month", DESCRIPTION: "attracting many visitors" },
        },
        {
          en: "The new policy, which affects all employees, is quite strict.",
          bn: "নতুন নীতিটি, যা সব কর্মচারীদের প্রভাবিত করে, বেশ কঠোর।",
          slotValues: { THING: "The new policy", CLAUSE: "affects all employees", DESCRIPTION: "quite strict" },
        },
        {
          en: "This restaurant, which serves Italian food, is very popular.",
          bn: "এই রেস্তোরাঁটি, যা ইতালীয় খাবার পরিবেশন করে, খুব জনপ্রিয়।",
          slotValues: { THING: "This restaurant", CLAUSE: "serves Italian food", DESCRIPTION: "very popular" },
        },
        {
          en: "The movie, which won three awards, is now streaming online.",
          bn: "সিনেমাটি, যা তিনটি পুরস্কার জিতেছে, এখন অনলাইনে স্ট্রিমিং হচ্ছে।",
          slotValues: { THING: "The movie", CLAUSE: "won three awards", DESCRIPTION: "now streaming online" },
        },
        {
          en: "The bridge, which connects two cities, is an engineering marvel.",
          bn: "সেতুটি, যা দুটি শহরকে সংযুক্ত করে, একটি প্রকৌশল বিস্ময়।",
          slotValues: { THING: "The bridge", CLAUSE: "connects two cities", DESCRIPTION: "an engineering marvel" },
        },
        {
          en: "Their house, which overlooks the lake, is absolutely beautiful.",
          bn: "তাদের বাড়ি, যা হ্রদের দিকে তাকিয়ে আছে, একেবারে সুন্দর।",
          slotValues: { THING: "Their house", CLAUSE: "overlooks the lake", DESCRIPTION: "absolutely beautiful" },
        },
        {
          en: "The software, which was updated recently, is much faster now.",
          bn: "সফটওয়্যারটি, যা সম্প্রতি আপডেট করা হয়েছে, এখন অনেক দ্রুত।",
          slotValues: { THING: "The software", CLAUSE: "was updated recently", DESCRIPTION: "much faster now" },
        },
        {
          en: "The exam, which covers three chapters, is scheduled for Monday.",
          bn: "পরীক্ষাটি, যা তিনটি অধ্যায় জুড়ে, সোমবারের জন্য নির্ধারিত।",
          slotValues: { THING: "The exam", CLAUSE: "covers three chapters", DESCRIPTION: "scheduled for Monday" },
        },
        {
          en: "The concert, which was sold out, is being held at the stadium.",
          bn: "কনসার্টটি, যার টিকেট শেষ হয়ে গেছে, স্টেডিয়ামে অনুষ্ঠিত হচ্ছে।",
          slotValues: { THING: "The concert", CLAUSE: "was sold out", DESCRIPTION: "being held at the stadium" },
        },
      ],
      formality: "formal",
      difficulty: "advanced",
    },
    {
      id: "S1.3",
      formula: "[PERSON], whose [NOUN] [CLAUSE], [ACTION]",
      formula_bn: "[ব্যক্তি], যার [বিশেষ্য] [উপবাক্য], [ক্রিয়া]",
      patternName: "Whose + Non-Defining (Possession)",
      patternName_bn: "Whose + অ-নির্ধারক (অধিকার)",
      slots: [
        {
          name: "PERSON",
          description: "A specific person being described",
          description_bn: "একটি নির্দিষ্ট ব্যক্তি যাকে বর্ণনা করা হচ্ছে",
          acceptedTypes: ["person", "noun_phrase"],
          examples: ["My colleague", "The student", "The woman"],
        },
        {
          name: "NOUN",
          description: "Something belonging to the person",
          description_bn: "ব্যক্তির অধিকারভুক্ত কিছু",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["car", "father", "book"],
        },
        {
          name: "CLAUSE",
          description: "Information about the possession",
          description_bn: "অধিকারভুক্ত বস্তু সম্পর্কে তথ্য",
          acceptedTypes: ["clause"],
          examples: ["was stolen", "is a doctor", "won a prize"],
        },
        {
          name: "ACTION",
          description: "What the person did or does",
          description_bn: "ব্যক্তি কী করেছেন বা করেন",
          acceptedTypes: ["verb_phrase", "clause"],
          examples: ["reported it to the police", "is very proud", "thanked everyone"],
        },
      ],
      examples: [
        {
          en: "My colleague, whose wife is a doctor, often gives us health tips.",
          bn: "আমার সহকর্মী, যার স্ত্রী একজন ডাক্তার, প্রায়ই আমাদের স্বাস্থ্য পরামর্শ দেন।",
          slotValues: { PERSON: "My colleague", NOUN: "wife", CLAUSE: "is a doctor", ACTION: "often gives us health tips" },
        },
        {
          en: "The student, whose project won first prize, was congratulated by everyone.",
          bn: "ছাত্রটি, যার প্রকল্প প্রথম পুরস্কার জিতেছে, সবার কাছ থেকে অভিনন্দন পেয়েছে।",
          slotValues: { PERSON: "The student", NOUN: "project", CLAUSE: "won first prize", ACTION: "was congratulated by everyone" },
        },
        {
          en: "The woman, whose bag was stolen, reported it to the police.",
          bn: "মহিলাটি, যার ব্যাগ চুরি হয়েছিল, পুলিশে রিপোর্ট করেছেন।",
          slotValues: { PERSON: "The woman", NOUN: "bag", CLAUSE: "was stolen", ACTION: "reported it to the police" },
        },
        {
          en: "The author, whose novel became a bestseller, is giving a talk today.",
          bn: "লেখক, যার উপন্যাস বেস্টসেলার হয়েছে, আজ একটি বক্তৃতা দিচ্ছেন।",
          slotValues: { PERSON: "The author", NOUN: "novel", CLAUSE: "became a bestseller", ACTION: "is giving a talk today" },
        },
        {
          en: "Mr. Khan, whose son studies abroad, misses him very much.",
          bn: "মি. খান, যার ছেলে বিদেশে পড়ে, তাকে খুব মিস করেন।",
          slotValues: { PERSON: "Mr. Khan", NOUN: "son", CLAUSE: "studies abroad", ACTION: "misses him very much" },
        },
        {
          en: "The singer, whose voice is amazing, performed at the concert.",
          bn: "গায়ক, যার কণ্ঠস্বর অসাধারণ, কনসার্টে পরিবেশন করেছেন।",
          slotValues: { PERSON: "The singer", NOUN: "voice", CLAUSE: "is amazing", ACTION: "performed at the concert" },
        },
        {
          en: "The teacher, whose methods are innovative, won the best teacher award.",
          bn: "শিক্ষক, যার পদ্ধতিগুলো উদ্ভাবনী, সেরা শিক্ষক পুরস্কার জিতেছেন।",
          slotValues: { PERSON: "The teacher", NOUN: "methods", CLAUSE: "are innovative", ACTION: "won the best teacher award" },
        },
        {
          en: "The family, whose house was damaged in the storm, needs help.",
          bn: "পরিবারটি, যাদের বাড়ি ঝড়ে ক্ষতিগ্রস্ত হয়েছে, সাহায্য প্রয়োজন।",
          slotValues: { PERSON: "The family", NOUN: "house", CLAUSE: "was damaged in the storm", ACTION: "needs help" },
        },
        {
          en: "The athlete, whose record still stands, retired last year.",
          bn: "ক্রীড়াবিদ, যার রেকর্ড এখনও টিকে আছে, গত বছর অবসর নিয়েছেন।",
          slotValues: { PERSON: "The athlete", NOUN: "record", CLAUSE: "still stands", ACTION: "retired last year" },
        },
        {
          en: "My aunt, whose cooking is legendary, is hosting dinner tonight.",
          bn: "আমার খালা, যার রান্না কিংবদন্তি, আজ রাতে ডিনার হোস্ট করছেন।",
          slotValues: { PERSON: "My aunt", NOUN: "cooking", CLAUSE: "is legendary", ACTION: "is hosting dinner tonight" },
        },
        {
          en: "The company, whose profits doubled, is expanding overseas.",
          bn: "কোম্পানিটি, যার মুনাফা দ্বিগুণ হয়েছে, বিদেশে সম্প্রসারণ করছে।",
          slotValues: { PERSON: "The company", NOUN: "profits", CLAUSE: "doubled", ACTION: "is expanding overseas" },
        },
        {
          en: "The director, whose film won an Oscar, is making a new movie.",
          bn: "পরিচালক, যার চলচ্চিত্র অস্কার জিতেছে, একটি নতুন সিনেমা বানাচ্ছেন।",
          slotValues: { PERSON: "The director", NOUN: "film", CLAUSE: "won an Oscar", ACTION: "is making a new movie" },
        },
        {
          en: "The patient, whose condition improved, was discharged today.",
          bn: "রোগী, যার অবস্থার উন্নতি হয়েছে, আজ ছাড়া পেয়েছেন।",
          slotValues: { PERSON: "The patient", NOUN: "condition", CLAUSE: "improved", ACTION: "was discharged today" },
        },
        {
          en: "The scientist, whose research is groundbreaking, received a grant.",
          bn: "বিজ্ঞানী, যার গবেষণা যুগান্তকারী, একটি অনুদান পেয়েছেন।",
          slotValues: { PERSON: "The scientist", NOUN: "research", CLAUSE: "is groundbreaking", ACTION: "received a grant" },
        },
        {
          en: "The couple, whose wedding was last month, just returned from their honeymoon.",
          bn: "দম্পতিটি, যাদের বিয়ে গত মাসে হয়েছিল, সবেমাত্র মধুচন্দ্রিমা থেকে ফিরেছেন।",
          slotValues: { PERSON: "The couple", NOUN: "wedding", CLAUSE: "was last month", ACTION: "just returned from their honeymoon" },
        },
      ],
      formality: "formal",
      difficulty: "advanced",
    },
    {
      id: "S1.4",
      formula: "[PERSON] [ACTION+ED] [PLACE], where [CLAUSE]",
      formula_bn: "[ব্যক্তি] [ক্রিয়া] [স্থান], যেখানে [উপবাক্য]",
      patternName: "Where + Non-Defining (Place)",
      patternName_bn: "Where + অ-নির্ধারক (স্থান)",
      slots: [
        {
          name: "PERSON",
          description: "The person performing the action",
          description_bn: "যে ব্যক্তি কাজটি করছেন",
          acceptedTypes: ["person", "noun_phrase"],
          examples: ["We", "She", "They"],
        },
        {
          name: "ACTION+ED",
          description: "A past action verb",
          description_bn: "একটি অতীত ক্রিয়া",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["visited", "went to", "stayed at"],
        },
        {
          name: "PLACE",
          description: "A specific place",
          description_bn: "একটি নির্দিষ্ট স্থান",
          acceptedTypes: ["place", "noun_phrase"],
          examples: ["Paris", "the old library", "that hotel"],
        },
        {
          name: "CLAUSE",
          description: "Extra information about the place",
          description_bn: "স্থান সম্পর্কে অতিরিক্ত তথ্য",
          acceptedTypes: ["clause"],
          examples: ["we first met", "my parents got married", "the food is amazing"],
        },
      ],
      examples: [
        {
          en: "We visited Paris, where we first met ten years ago.",
          bn: "আমরা প্যারিস ঘুরতে গেলাম, যেখানে দশ বছর আগে আমাদের প্রথম দেখা হয়েছিল।",
          slotValues: { PERSON: "We", "ACTION+ED": "visited", PLACE: "Paris", CLAUSE: "we first met ten years ago" },
        },
        {
          en: "She returned to her hometown, where she grew up.",
          bn: "সে তার জন্মভূমিতে ফিরে গেল, যেখানে সে বড় হয়েছে।",
          slotValues: { PERSON: "She", "ACTION+ED": "returned to", PLACE: "her hometown", CLAUSE: "she grew up" },
        },
        {
          en: "They moved to Dhaka, where the job opportunities are better.",
          bn: "তারা ঢাকায় চলে গেল, যেখানে চাকরির সুযোগ ভালো।",
          slotValues: { PERSON: "They", "ACTION+ED": "moved to", PLACE: "Dhaka", CLAUSE: "the job opportunities are better" },
        },
        {
          en: "I stayed at the Grand Hotel, where the service was excellent.",
          bn: "আমি গ্র্যান্ড হোটেলে ছিলাম, যেখানে সেবা চমৎকার ছিল।",
          slotValues: { PERSON: "I", "ACTION+ED": "stayed at", PLACE: "the Grand Hotel", CLAUSE: "the service was excellent" },
        },
        {
          en: "He went to Oxford, where he studied literature.",
          bn: "সে অক্সফোর্ডে গেল, যেখানে সে সাহিত্য পড়েছে।",
          slotValues: { PERSON: "He", "ACTION+ED": "went to", PLACE: "Oxford", CLAUSE: "he studied literature" },
        },
        {
          en: "We ate at that restaurant, where the pasta is incredible.",
          bn: "আমরা ওই রেস্তোরাঁয় খেলাম, যেখানে পাস্তা অসাধারণ।",
          slotValues: { PERSON: "We", "ACTION+ED": "ate at", PLACE: "that restaurant", CLAUSE: "the pasta is incredible" },
        },
        {
          en: "She worked at the hospital, where she saved many lives.",
          bn: "সে হাসপাতালে কাজ করেছে, যেখানে সে অনেক জীবন বাঁচিয়েছে।",
          slotValues: { PERSON: "She", "ACTION+ED": "worked at", PLACE: "the hospital", CLAUSE: "she saved many lives" },
        },
        {
          en: "They visited the museum, where ancient artifacts are displayed.",
          bn: "তারা জাদুঘর পরিদর্শন করেছে, যেখানে প্রাচীন নিদর্শন প্রদর্শিত হয়।",
          slotValues: { PERSON: "They", "ACTION+ED": "visited", PLACE: "the museum", CLAUSE: "ancient artifacts are displayed" },
        },
        {
          en: "I went back to my school, where I spent the happiest years of my life.",
          bn: "আমি আমার স্কুলে ফিরে গেলাম, যেখানে আমি জীবনের সবচেয়ে সুখের বছরগুলো কাটিয়েছি।",
          slotValues: { PERSON: "I", "ACTION+ED": "went back to", PLACE: "my school", CLAUSE: "I spent the happiest years of my life" },
        },
        {
          en: "We traveled to Japan, where the cherry blossoms were in full bloom.",
          bn: "আমরা জাপান ভ্রমণ করেছি, যেখানে চেরি ফুল পূর্ণ প্রস্ফুটিত ছিল।",
          slotValues: { PERSON: "We", "ACTION+ED": "traveled to", PLACE: "Japan", CLAUSE: "the cherry blossoms were in full bloom" },
        },
        {
          en: "He moved to the countryside, where life is much quieter.",
          bn: "সে গ্রামে চলে গেল, যেখানে জীবন অনেক শান্ত।",
          slotValues: { PERSON: "He", "ACTION+ED": "moved to", PLACE: "the countryside", CLAUSE: "life is much quieter" },
        },
        {
          en: "She studied at Cambridge, where many Nobel laureates have studied.",
          bn: "সে কেমব্রিজে পড়েছে, যেখানে অনেক নোবেল বিজয়ী পড়েছেন।",
          slotValues: { PERSON: "She", "ACTION+ED": "studied at", PLACE: "Cambridge", CLAUSE: "many Nobel laureates have studied" },
        },
        {
          en: "They spent their vacation in Bali, where the beaches are stunning.",
          bn: "তারা বালিতে ছুটি কাটিয়েছে, যেখানে সৈকতগুলো অত্যাশ্চর্য।",
          slotValues: { PERSON: "They", "ACTION+ED": "spent their vacation in", PLACE: "Bali", CLAUSE: "the beaches are stunning" },
        },
        {
          en: "I grew up in a small village, where everyone knew each other.",
          bn: "আমি একটি ছোট গ্রামে বড় হয়েছি, যেখানে সবাই সবাইকে চিনত।",
          slotValues: { PERSON: "I", "ACTION+ED": "grew up in", PLACE: "a small village", CLAUSE: "everyone knew each other" },
        },
        {
          en: "We attended the conference in Singapore, where many experts presented their findings.",
          bn: "আমরা সিঙ্গাপুরে সম্মেলনে যোগ দিয়েছি, যেখানে অনেক বিশেষজ্ঞ তাদের গবেষণার ফলাফল উপস্থাপন করেছেন।",
          slotValues: { PERSON: "We", "ACTION+ED": "attended the conference in", PLACE: "Singapore", CLAUSE: "many experts presented their findings" },
        },
      ],
      formality: "formal",
      difficulty: "advanced",
    },
    {
      id: "S1.5",
      formula: "[PERSON] [ACTION+ED] in [TIME], when [CLAUSE]",
      formula_bn: "[ব্যক্তি] [ক্রিয়া] [সময়], যখন [উপবাক্য]",
      patternName: "When + Non-Defining (Time)",
      patternName_bn: "When + অ-নির্ধারক (সময়)",
      slots: [
        {
          name: "PERSON",
          description: "The person performing the action",
          description_bn: "যে ব্যক্তি কাজটি করছেন",
          acceptedTypes: ["person", "noun_phrase"],
          examples: ["He", "She", "We"],
        },
        {
          name: "ACTION+ED",
          description: "A past action",
          description_bn: "একটি অতীত ক্রিয়া",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["graduated", "got married", "started working"],
        },
        {
          name: "TIME",
          description: "A specific time period",
          description_bn: "একটি নির্দিষ্ট সময়কাল",
          acceptedTypes: ["time", "time_expression"],
          examples: ["2015", "the summer", "March"],
        },
        {
          name: "CLAUSE",
          description: "Extra information about that time",
          description_bn: "সেই সময় সম্পর্কে অতিরিক্ত তথ্য",
          acceptedTypes: ["clause"],
          examples: ["the economy was booming", "everything changed", "life was simpler"],
        },
      ],
      examples: [
        {
          en: "He graduated in 2015, when the economy was still recovering.",
          bn: "সে ২০১৫ সালে স্নাতক হয়েছে, যখন অর্থনীতি তখনও পুনরুদ্ধার হচ্ছিল।",
          slotValues: { PERSON: "He", "ACTION+ED": "graduated", TIME: "2015", CLAUSE: "the economy was still recovering" },
        },
        {
          en: "She got married in June, when the weather was perfect.",
          bn: "সে জুন মাসে বিয়ে করেছে, যখন আবহাওয়া নিখুঁত ছিল।",
          slotValues: { PERSON: "She", "ACTION+ED": "got married", TIME: "June", CLAUSE: "the weather was perfect" },
        },
        {
          en: "We moved here in 2010, when this area was still undeveloped.",
          bn: "আমরা ২০১০ সালে এখানে এসেছি, যখন এই এলাকা এখনও অনুন্নত ছিল।",
          slotValues: { PERSON: "We", "ACTION+ED": "moved here", TIME: "2010", CLAUSE: "this area was still undeveloped" },
        },
        {
          en: "They started the company in 2005, when nobody believed in them.",
          bn: "তারা ২০০৫ সালে কোম্পানিটি শুরু করেছে, যখন কেউ তাদের বিশ্বাস করেনি।",
          slotValues: { PERSON: "They", "ACTION+ED": "started the company", TIME: "2005", CLAUSE: "nobody believed in them" },
        },
        {
          en: "I visited India in the monsoon season, when the rains were heavy.",
          bn: "আমি বর্ষাকালে ভারত ঘুরতে গেছি, যখন ভারী বৃষ্টি হচ্ছিল।",
          slotValues: { PERSON: "I", "ACTION+ED": "visited India", TIME: "the monsoon season", CLAUSE: "the rains were heavy" },
        },
        {
          en: "He retired in December, when he turned sixty-five.",
          bn: "সে ডিসেম্বরে অবসর নিয়েছে, যখন তার পঁয়ষট্টি বছর হয়েছে।",
          slotValues: { PERSON: "He", "ACTION+ED": "retired", TIME: "December", CLAUSE: "he turned sixty-five" },
        },
        {
          en: "She arrived in the evening, when everyone was already asleep.",
          bn: "সে সন্ধ্যায় পৌঁছেছে, যখন সবাই ইতিমধ্যে ঘুমিয়ে গিয়েছিল।",
          slotValues: { PERSON: "She", "ACTION+ED": "arrived", TIME: "the evening", CLAUSE: "everyone was already asleep" },
        },
        {
          en: "We celebrated Eid in April, when the whole family was together.",
          bn: "আমরা এপ্রিলে ঈদ উদযাপন করেছি, যখন পুরো পরিবার একসাথে ছিল।",
          slotValues: { PERSON: "We", "ACTION+ED": "celebrated Eid", TIME: "April", CLAUSE: "the whole family was together" },
        },
        {
          en: "They bought the house in 2018, when prices were much lower.",
          bn: "তারা ২০১৮ সালে বাড়িটি কিনেছে, যখন দাম অনেক কম ছিল।",
          slotValues: { PERSON: "They", "ACTION+ED": "bought the house", TIME: "2018", CLAUSE: "prices were much lower" },
        },
        {
          en: "I started learning English in childhood, when my mother taught me.",
          bn: "আমি শৈশবে ইংরেজি শিখতে শুরু করেছি, যখন আমার মা আমাকে শেখাতেন।",
          slotValues: { PERSON: "I", "ACTION+ED": "started learning English", TIME: "childhood", CLAUSE: "my mother taught me" },
        },
        {
          en: "He joined the army in 2008, when the country needed soldiers.",
          bn: "সে ২০০৮ সালে সেনাবাহিনীতে যোগ দিয়েছে, যখন দেশের সৈন্য দরকার ছিল।",
          slotValues: { PERSON: "He", "ACTION+ED": "joined the army", TIME: "2008", CLAUSE: "the country needed soldiers" },
        },
        {
          en: "She published her first novel in her twenties, when she was still a student.",
          bn: "সে কুড়ির দশকে তার প্রথম উপন্যাস প্রকাশ করেছে, যখন সে এখনও ছাত্রী ছিল।",
          slotValues: { PERSON: "She", "ACTION+ED": "published her first novel", TIME: "her twenties", CLAUSE: "she was still a student" },
        },
        {
          en: "We held the event in winter, when fewer tourists visit.",
          bn: "আমরা শীতকালে অনুষ্ঠানটি করেছি, যখন কম পর্যটক আসে।",
          slotValues: { PERSON: "We", "ACTION+ED": "held the event", TIME: "winter", CLAUSE: "fewer tourists visit" },
        },
        {
          en: "They launched the product in January, when demand was at its peak.",
          bn: "তারা জানুয়ারিতে পণ্যটি লঞ্চ করেছে, যখন চাহিদা সর্বোচ্চ ছিল।",
          slotValues: { PERSON: "They", "ACTION+ED": "launched the product", TIME: "January", CLAUSE: "demand was at its peak" },
        },
        {
          en: "I left the country in 2019, when things were still normal.",
          bn: "আমি ২০১৯ সালে দেশ ছেড়েছি, যখন সবকিছু এখনও স্বাভাবিক ছিল।",
          slotValues: { PERSON: "I", "ACTION+ED": "left the country", TIME: "2019", CLAUSE: "things were still normal" },
        },
      ],
      formality: "formal",
      difficulty: "advanced",
    },
  ],
};
