import { PatternCategory } from "@/types/pattern";

export const categoryS10: PatternCategory = {
  id: "S10",
  slug: "it-as-preparatory-subject-extended",
  name: "\"It\" as Preparatory Subject (Extended)",
  name_bn: "প্রস্তুতিমূলক কর্তা হিসেবে \"It\" (বিস্তারিত)",
  description: "Use 'it' to introduce beliefs, appearances, and reports",
  description_bn: "'it' ব্যবহার করে বিশ্বাস, উপস্থিতি এবং রিপোর্ট উপস্থাপন করুন",
  icon: "🔍",
  group: "S",
  groupName: "Advanced Structural Patterns",
  groupName_bn: "উন্নত গঠনমূলক প্যাটার্ন",
  difficulty: "advanced",
  patterns: [
    {
      id: "S10.1",
      formula: "It appears that [CLAUSE]",
      formula_bn: "মনে হচ্ছে যে [উপবাক্য]",
      patternName: "It appears that...",
      patternName_bn: "মনে হচ্ছে যে...",
      slots: [
        { name: "CLAUSE", description: "An observation or finding", description_bn: "একটি পর্যবেক্ষণ বা আবিষ্কার", acceptedTypes: ["clause"], examples: ["he has left", "the problem is solved", "they disagree"] },
      ],
      examples: [
        { en: "It appears that he has already left the building.", bn: "মনে হচ্ছে সে ইতিমধ্যে ভবন ছেড়ে চলে গেছে।", slotValues: { CLAUSE: "he has already left the building" } },
        { en: "It appears that the problem has been solved.", bn: "মনে হচ্ছে সমস্যাটি সমাধান হয়ে গেছে।", slotValues: { CLAUSE: "the problem has been solved" } },
        { en: "It appears that they disagree on the budget.", bn: "মনে হচ্ছে তারা বাজেট নিয়ে দ্বিমত পোষণ করছে।", slotValues: { CLAUSE: "they disagree on the budget" } },
        { en: "It appears that the weather will improve tomorrow.", bn: "মনে হচ্ছে আগামীকাল আবহাওয়ার উন্নতি হবে।", slotValues: { CLAUSE: "the weather will improve tomorrow" } },
        { en: "It appears that someone has broken into the office.", bn: "মনে হচ্ছে কেউ অফিসে ঢুকে পড়েছে।", slotValues: { CLAUSE: "someone has broken into the office" } },
        { en: "It appears that the company is making a profit.", bn: "মনে হচ্ছে কোম্পানি মুনাফা করছে।", slotValues: { CLAUSE: "the company is making a profit" } },
        { en: "It appears that the train has been delayed.", bn: "মনে হচ্ছে ট্রেনটি বিলম্ব হয়েছে।", slotValues: { CLAUSE: "the train has been delayed" } },
        { en: "It appears that she changed her mind.", bn: "মনে হচ্ছে সে তার মন পরিবর্তন করেছে।", slotValues: { CLAUSE: "she changed her mind" } },
        { en: "It appears that the information was incorrect.", bn: "মনে হচ্ছে তথ্যটি ভুল ছিল।", slotValues: { CLAUSE: "the information was incorrect" } },
        { en: "It appears that nobody noticed the error.", bn: "মনে হচ্ছে কেউ ত্রুটিটি লক্ষ্য করেনি।", slotValues: { CLAUSE: "nobody noticed the error" } },
        { en: "It appears that the patient is recovering well.", bn: "মনে হচ্ছে রোগী ভালোভাবে সুস্থ হচ্ছে।", slotValues: { CLAUSE: "the patient is recovering well" } },
        { en: "It appears that we underestimated the difficulty.", bn: "মনে হচ্ছে আমরা কাজের কঠিনতাকে অবমূল্যায়ন করেছি।", slotValues: { CLAUSE: "we underestimated the difficulty" } },
        { en: "It appears that the negotiations have failed.", bn: "মনে হচ্ছে আলোচনা ব্যর্থ হয়েছে।", slotValues: { CLAUSE: "the negotiations have failed" } },
        { en: "It appears that the test results are positive.", bn: "মনে হচ্ছে পরীক্ষার ফলাফল ইতিবাচক।", slotValues: { CLAUSE: "the test results are positive" } },
        { en: "It appears that the situation is under control.", bn: "মনে হচ্ছে পরিস্থিতি নিয়ন্ত্রণে আছে।", slotValues: { CLAUSE: "the situation is under control" } },
      ],
      formality: "formal",
      difficulty: "advanced",
    },
    {
      id: "S10.2",
      formula: "It is believed that [CLAUSE]",
      formula_bn: "বিশ্বাস করা হয় যে [উপবাক্য]",
      patternName: "It is believed that...",
      patternName_bn: "বিশ্বাস করা হয় যে...",
      slots: [
        { name: "CLAUSE", description: "A commonly held belief", description_bn: "একটি সাধারণভাবে ধারণকৃত বিশ্বাস", acceptedTypes: ["clause"], examples: ["he is innocent", "the earth is 4.5 billion years old", "exercise prevents disease"] },
      ],
      examples: [
        { en: "It is believed that exercise prevents many diseases.", bn: "বিশ্বাস করা হয় যে ব্যায়াম অনেক রোগ প্রতিরোধ করে।", slotValues: { CLAUSE: "exercise prevents many diseases" } },
        { en: "It is believed that the universe is constantly expanding.", bn: "বিশ্বাস করা হয় যে মহাবিশ্ব ক্রমাগত প্রসারিত হচ্ছে।", slotValues: { CLAUSE: "the universe is constantly expanding" } },
        { en: "It is believed that he is innocent.", bn: "বিশ্বাস করা হয় যে সে নির্দোষ।", slotValues: { CLAUSE: "he is innocent" } },
        { en: "It is believed that green tea has many health benefits.", bn: "বিশ্বাস করা হয় যে গ্রিন টি এর অনেক স্বাস্থ্য উপকারিতা আছে।", slotValues: { CLAUSE: "green tea has many health benefits" } },
        { en: "It is believed that education is the key to success.", bn: "বিশ্বাস করা হয় যে শিক্ষা সাফল্যের চাবিকাঠি।", slotValues: { CLAUSE: "education is the key to success" } },
        { en: "It is believed that the ancient city was destroyed by an earthquake.", bn: "বিশ্বাস করা হয় যে প্রাচীন শহরটি ভূমিকম্পে ধ্বংস হয়েছিল।", slotValues: { CLAUSE: "the ancient city was destroyed by an earthquake" } },
        { en: "It is believed that honey has healing properties.", bn: "বিশ্বাস করা হয় যে মধুর নিরাময় গুণ আছে।", slotValues: { CLAUSE: "honey has healing properties" } },
        { en: "It is believed that reading improves brain function.", bn: "বিশ্বাস করা হয় যে পড়া মস্তিষ্কের কার্যক্ষমতা উন্নত করে।", slotValues: { CLAUSE: "reading improves brain function" } },
        { en: "It is believed that the treasure is hidden somewhere in the mountains.", bn: "বিশ্বাস করা হয় যে ধনসম্পদ পাহাড়ে কোথাও লুকানো আছে।", slotValues: { CLAUSE: "the treasure is hidden somewhere in the mountains" } },
        { en: "It is believed that children learn best through play.", bn: "বিশ্বাস করা হয় যে শিশুরা খেলার মাধ্যমে সবচেয়ে ভালো শেখে।", slotValues: { CLAUSE: "children learn best through play" } },
        { en: "It is believed that the company will merge next year.", bn: "বিশ্বাস করা হয় যে কোম্পানিটি আগামী বছর একীভূত হবে।", slotValues: { CLAUSE: "the company will merge next year" } },
        { en: "It is believed that laughter is the best medicine.", bn: "বিশ্বাস করা হয় যে হাসি সবচেয়ে ভালো ওষুধ।", slotValues: { CLAUSE: "laughter is the best medicine" } },
        { en: "It is believed that the pyramids were built by thousands of workers.", bn: "বিশ্বাস করা হয় যে পিরামিডগুলো হাজার হাজার শ্রমিক দ্বারা নির্মিত হয়েছিল।", slotValues: { CLAUSE: "the pyramids were built by thousands of workers" } },
        { en: "It is believed that music can reduce stress.", bn: "বিশ্বাস করা হয় যে সঙ্গীত মানসিক চাপ কমাতে পারে।", slotValues: { CLAUSE: "music can reduce stress" } },
        { en: "It is believed that the vaccine is safe and effective.", bn: "বিশ্বাস করা হয় যে টিকাটি নিরাপদ এবং কার্যকর।", slotValues: { CLAUSE: "the vaccine is safe and effective" } },
      ],
      formality: "very_formal",
      difficulty: "advanced",
    },
    {
      id: "S10.3",
      formula: "It is said that [CLAUSE]",
      formula_bn: "বলা হয় যে [উপবাক্য]",
      patternName: "It is said that...",
      patternName_bn: "বলা হয় যে...",
      slots: [
        { name: "CLAUSE", description: "Something commonly reported or said", description_bn: "যা সাধারণভাবে রিপোর্ট করা হয় বা বলা হয়", acceptedTypes: ["clause"], examples: ["practice makes perfect", "he was a great leader", "the city never sleeps"] },
      ],
      examples: [
        { en: "It is said that practice makes perfect.", bn: "বলা হয় যে অনুশীলনে নিপুণতা আসে।", slotValues: { CLAUSE: "practice makes perfect" } },
        { en: "It is said that he was one of the greatest leaders.", bn: "বলা হয় যে তিনি সবচেয়ে মহান নেতাদের একজন ছিলেন।", slotValues: { CLAUSE: "he was one of the greatest leaders" } },
        { en: "It is said that the city never sleeps.", bn: "বলা হয় যে শহরটি কখনো ঘুমায় না।", slotValues: { CLAUSE: "the city never sleeps" } },
        { en: "It is said that actions speak louder than words.", bn: "বলা হয় যে কাজ কথার চেয়ে বেশি কথা বলে।", slotValues: { CLAUSE: "actions speak louder than words" } },
        { en: "It is said that the temple is over a thousand years old.", bn: "বলা হয় যে মন্দিরটি এক হাজার বছরেরও বেশি পুরোনো।", slotValues: { CLAUSE: "the temple is over a thousand years old" } },
        { en: "It is said that first impressions last.", bn: "বলা হয় যে প্রথম ধারণা স্থায়ী হয়।", slotValues: { CLAUSE: "first impressions last" } },
        { en: "It is said that patience is a virtue.", bn: "বলা হয় যে ধৈর্য একটি গুণ।", slotValues: { CLAUSE: "patience is a virtue" } },
        { en: "It is said that the lake is haunted.", bn: "বলা হয় যে হ্রদটি ভূতুড়ে।", slotValues: { CLAUSE: "the lake is haunted" } },
        { en: "It is said that time heals all wounds.", bn: "বলা হয় যে সময় সব ক্ষত সারিয়ে দেয়।", slotValues: { CLAUSE: "time heals all wounds" } },
        { en: "It is said that the company started in a small garage.", bn: "বলা হয় যে কোম্পানিটি একটি ছোট গ্যারেজে শুরু হয়েছিল।", slotValues: { CLAUSE: "the company started in a small garage" } },
        { en: "It is said that knowledge is power.", bn: "বলা হয় যে জ্ঞানই শক্তি।", slotValues: { CLAUSE: "knowledge is power" } },
        { en: "It is said that the village has a hidden waterfall.", bn: "বলা হয় যে গ্রামটিতে একটি লুকানো জলপ্রপাত আছে।", slotValues: { CLAUSE: "the village has a hidden waterfall" } },
        { en: "It is said that she can speak seven languages.", bn: "বলা হয় যে সে সাতটি ভাষায় কথা বলতে পারে।", slotValues: { CLAUSE: "she can speak seven languages" } },
        { en: "It is said that the recipe has been passed down for generations.", bn: "বলা হয় যে রেসিপিটি প্রজন্ম থেকে প্রজন্মে চলে এসেছে।", slotValues: { CLAUSE: "the recipe has been passed down for generations" } },
        { en: "It is said that travel broadens the mind.", bn: "বলা হয় যে ভ্রমণ মনকে প্রসারিত করে।", slotValues: { CLAUSE: "travel broadens the mind" } },
      ],
      formality: "formal",
      difficulty: "advanced",
    },
    {
      id: "S10.4",
      formula: "It turned out that [CLAUSE]",
      formula_bn: "দেখা গেল যে [উপবাক্য]",
      patternName: "It turned out that...",
      patternName_bn: "দেখা গেল যে...",
      slots: [
        { name: "CLAUSE", description: "An unexpected discovery", description_bn: "একটি অপ্রত্যাশিত আবিষ্কার", acceptedTypes: ["clause"], examples: ["he was right", "the test was easy", "we were wrong"] },
      ],
      examples: [
        { en: "It turned out that he was right all along.", bn: "দেখা গেল যে সে শুরু থেকেই ঠিক ছিল।", slotValues: { CLAUSE: "he was right all along" } },
        { en: "It turned out that the test was easier than expected.", bn: "দেখা গেল যে পরীক্ষা প্রত্যাশার চেয়ে সহজ ছিল।", slotValues: { CLAUSE: "the test was easier than expected" } },
        { en: "It turned out that we had been going in the wrong direction.", bn: "দেখা গেল যে আমরা ভুল দিকে যাচ্ছিলাম।", slotValues: { CLAUSE: "we had been going in the wrong direction" } },
        { en: "It turned out that she already knew the secret.", bn: "দেখা গেল যে সে ইতিমধ্যে গোপন কথাটি জানত।", slotValues: { CLAUSE: "she already knew the secret" } },
        { en: "It turned out that the restaurant was closed on Mondays.", bn: "দেখা গেল যে রেস্তোরাঁটি সোমবারে বন্ধ থাকে।", slotValues: { CLAUSE: "the restaurant was closed on Mondays" } },
        { en: "It turned out that the cheap product was actually very good.", bn: "দেখা গেল যে সস্তা পণ্যটি আসলে খুব ভালো ছিল।", slotValues: { CLAUSE: "the cheap product was actually very good" } },
        { en: "It turned out that they were related.", bn: "দেখা গেল যে তারা আত্মীয় ছিল।", slotValues: { CLAUSE: "they were related" } },
        { en: "It turned out that the rumor was false.", bn: "দেখা গেল যে গুজবটি মিথ্যা ছিল।", slotValues: { CLAUSE: "the rumor was false" } },
        { en: "It turned out that the interview went very well.", bn: "দেখা গেল যে সাক্ষাৎকার খুব ভালো হয়েছে।", slotValues: { CLAUSE: "the interview went very well" } },
        { en: "It turned out that the missing key was in my pocket.", bn: "দেখা গেল যে হারানো চাবি আমার পকেটেই ছিল।", slotValues: { CLAUSE: "the missing key was in my pocket" } },
        { en: "It turned out that the flight was cancelled.", bn: "দেখা গেল যে ফ্লাইট বাতিল হয়ে গেছে।", slotValues: { CLAUSE: "the flight was cancelled" } },
        { en: "It turned out that they had met before.", bn: "দেখা গেল যে তাদের আগে দেখা হয়েছিল।", slotValues: { CLAUSE: "they had met before" } },
        { en: "It turned out that the medicine worked perfectly.", bn: "দেখা গেল যে ওষুধটি পুরোপুরি কাজ করেছে।", slotValues: { CLAUSE: "the medicine worked perfectly" } },
        { en: "It turned out that the noise was just a cat.", bn: "দেখা গেল যে শব্দটি শুধু একটি বিড়ালের ছিল।", slotValues: { CLAUSE: "the noise was just a cat" } },
        { en: "It turned out that he had been lying the whole time.", bn: "দেখা গেল যে সে পুরো সময় মিথ্যা বলছিল।", slotValues: { CLAUSE: "he had been lying the whole time" } },
      ],
      formality: "polite",
      difficulty: "advanced",
    },
    {
      id: "S10.5",
      formula: "It seems likely that [CLAUSE]",
      formula_bn: "মনে হচ্ছে সম্ভবত [উপবাক্য]",
      patternName: "It seems likely that...",
      patternName_bn: "মনে হচ্ছে সম্ভবত...",
      slots: [
        { name: "CLAUSE", description: "A probable outcome", description_bn: "একটি সম্ভাব্য ফলাফল", acceptedTypes: ["clause"], examples: ["it will rain", "they will agree", "prices will rise"] },
      ],
      examples: [
        { en: "It seems likely that it will rain this afternoon.", bn: "মনে হচ্ছে সম্ভবত আজ বিকেলে বৃষ্টি হবে।", slotValues: { CLAUSE: "it will rain this afternoon" } },
        { en: "It seems likely that they will agree to the proposal.", bn: "মনে হচ্ছে সম্ভবত তারা প্রস্তাবে রাজি হবে।", slotValues: { CLAUSE: "they will agree to the proposal" } },
        { en: "It seems likely that prices will continue to rise.", bn: "মনে হচ্ছে সম্ভবত দাম বাড়তে থাকবে।", slotValues: { CLAUSE: "prices will continue to rise" } },
        { en: "It seems likely that the project will be completed on time.", bn: "মনে হচ্ছে সম্ভবত প্রকল্পটি সময়মতো সম্পন্ন হবে।", slotValues: { CLAUSE: "the project will be completed on time" } },
        { en: "It seems likely that she will get the promotion.", bn: "মনে হচ্ছে সম্ভবত সে পদোন্নতি পাবে।", slotValues: { CLAUSE: "she will get the promotion" } },
        { en: "It seems likely that the meeting will be postponed.", bn: "মনে হচ্ছে সম্ভবত মিটিং স্থগিত হবে।", slotValues: { CLAUSE: "the meeting will be postponed" } },
        { en: "It seems likely that the economy will recover next year.", bn: "মনে হচ্ছে সম্ভবত আগামী বছর অর্থনীতি পুনরুদ্ধার হবে।", slotValues: { CLAUSE: "the economy will recover next year" } },
        { en: "It seems likely that he will resign soon.", bn: "মনে হচ্ছে সম্ভবত সে শীঘ্রই পদত্যাগ করবে।", slotValues: { CLAUSE: "he will resign soon" } },
        { en: "It seems likely that the store will close early today.", bn: "মনে হচ্ছে সম্ভবত দোকান আজ তাড়াতাড়ি বন্ধ হবে।", slotValues: { CLAUSE: "the store will close early today" } },
        { en: "It seems likely that we'll need more time.", bn: "মনে হচ্ছে সম্ভবত আমাদের আরও সময় লাগবে।", slotValues: { CLAUSE: "we'll need more time" } },
        { en: "It seems likely that the team will win the tournament.", bn: "মনে হচ্ছে সম্ভবত দল টুর্নামেন্ট জিতবে।", slotValues: { CLAUSE: "the team will win the tournament" } },
        { en: "It seems likely that the company will hire more people.", bn: "মনে হচ্ছে সম্ভবত কোম্পানি আরও লোক নিয়োগ করবে।", slotValues: { CLAUSE: "the company will hire more people" } },
        { en: "It seems likely that the road will be congested during rush hour.", bn: "মনে হচ্ছে সম্ভবত রাশ আওয়ারে রাস্তায় যানজট হবে।", slotValues: { CLAUSE: "the road will be congested during rush hour" } },
        { en: "It seems likely that the school will remain closed this week.", bn: "মনে হচ্ছে সম্ভবত এই সপ্তাহে স্কুল বন্ধ থাকবে।", slotValues: { CLAUSE: "the school will remain closed this week" } },
        { en: "It seems likely that they will accept our terms.", bn: "মনে হচ্ছে সম্ভবত তারা আমাদের শর্ত মেনে নেবে।", slotValues: { CLAUSE: "they will accept our terms" } },
      ],
      formality: "formal",
      difficulty: "advanced",
    },
  ],
};
