import { PatternCategory } from "@/types/pattern";

export const categoryS14: PatternCategory = {
  id: "S14",
  slug: "seem-appear-turn-out",
  name: "Seem, Appear & Turn Out Patterns",
  name_bn: "মনে হওয়া, প্রতীয়মান হওয়া ও ফলাফল বের হওয়া প্যাটার্ন",
  description:
    "Express appearances, impressions, and unexpected outcomes",
  description_bn:
    "চেহারা, ধারণা এবং অপ্রত্যাশিত ফলাফল প্রকাশ করুন",
  icon: "👁️",
  group: "S",
  groupName: "Advanced Structural Patterns",
  groupName_bn: "উন্নত গঠনমূলক প্যাটার্ন",
  difficulty: "advanced",
  patterns: [
    {
      id: "S14.1",
      formula: "[THING] seems [ADJ]",
      formula_bn: "[বস্তু] [বিশেষণ] মনে হচ্ছে",
      patternName: "Seems + Adjective",
      patternName_bn: "মনে হচ্ছে + বিশেষণ",
      slots: [
        {
          name: "THING",
          description: "The subject that appears a certain way",
          description_bn: "যে বিষয়টি একটি নির্দিষ্ট উপায়ে প্রতীয়মান হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase", "person"],
          examples: ["He", "The plan", "Everything"],
        },
        {
          name: "ADJ",
          description: "How it seems or appears",
          description_bn: "এটি কেমন মনে হচ্ছে বা প্রতীয়মান হচ্ছে",
          acceptedTypes: ["adjective", "adjective_phrase"],
          examples: ["happy", "complicated", "fine"],
        },
      ],
      examples: [
        {
          en: "He seems happy today.",
          bn: "সে আজ খুশি মনে হচ্ছে।",
          slotValues: { THING: "He", ADJ: "happy today" },
          topicArea: "daily_life",
        },
        {
          en: "The plan seems complicated.",
          bn: "পরিকল্পনাটি জটিল মনে হচ্ছে।",
          slotValues: { THING: "The plan", ADJ: "complicated" },
          topicArea: "work",
        },
        {
          en: "Everything seems fine.",
          bn: "সবকিছু ঠিক মনে হচ্ছে।",
          slotValues: { THING: "Everything", ADJ: "fine" },
          topicArea: "daily_life",
        },
        {
          en: "She seems tired.",
          bn: "সে ক্লান্ত মনে হচ্ছে।",
          slotValues: { THING: "She", ADJ: "tired" },
          topicArea: "health",
        },
        {
          en: "The weather seems nice.",
          bn: "আবহাওয়া সুন্দর মনে হচ্ছে।",
          slotValues: { THING: "The weather", ADJ: "nice" },
          topicArea: "daily_life",
        },
        {
          en: "The exam seems easy.",
          bn: "পরীক্ষা সহজ মনে হচ্ছে।",
          slotValues: { THING: "The exam", ADJ: "easy" },
          topicArea: "education",
        },
        {
          en: "The situation seems serious.",
          bn: "পরিস্থিতি গুরুতর মনে হচ্ছে।",
          slotValues: { THING: "The situation", ADJ: "serious" },
          topicArea: "daily_life",
        },
        {
          en: "Your idea seems brilliant.",
          bn: "তোমার ধারণা দুর্দান্ত মনে হচ্ছে।",
          slotValues: { THING: "Your idea", ADJ: "brilliant" },
          topicArea: "work",
        },
        {
          en: "The price seems reasonable.",
          bn: "দাম যুক্তিসঙ্গত মনে হচ্ছে।",
          slotValues: { THING: "The price", ADJ: "reasonable" },
          topicArea: "shopping",
        },
        {
          en: "He seems nervous about the interview.",
          bn: "সে ইন্টারভিউ নিয়ে নার্ভাস মনে হচ্ছে।",
          slotValues: { THING: "He", ADJ: "nervous about the interview" },
          topicArea: "work",
        },
        {
          en: "The food seems fresh.",
          bn: "খাবার তাজা মনে হচ্ছে।",
          slotValues: { THING: "The food", ADJ: "fresh" },
          topicArea: "food",
        },
        {
          en: "This job seems perfect for you.",
          bn: "এই চাকরি তোমার জন্য নিখুঁত মনে হচ্ছে।",
          slotValues: { THING: "This job", ADJ: "perfect for you" },
          topicArea: "work",
        },
        {
          en: "The movie seems interesting.",
          bn: "সিনেমাটি আকর্ষণীয় মনে হচ্ছে।",
          slotValues: { THING: "The movie", ADJ: "interesting" },
          topicArea: "entertainment",
        },
        {
          en: "The traffic seems worse than usual.",
          bn: "ট্রাফিক স্বাভাবিকের চেয়ে খারাপ মনে হচ্ছে।",
          slotValues: { THING: "The traffic", ADJ: "worse than usual" },
          topicArea: "travel",
        },
        {
          en: "The patient seems better now.",
          bn: "রোগী এখন ভালো মনে হচ্ছে।",
          slotValues: { THING: "The patient", ADJ: "better now" },
          topicArea: "health",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
    },
    {
      id: "S14.2",
      formula: "It appears that [CLAUSE]",
      formula_bn: "মনে হচ্ছে যে [উপবাক্য]",
      patternName: "It Appears That (Formal Observation)",
      patternName_bn: "মনে হচ্ছে যে (আনুষ্ঠানিক পর্যবেক্ষণ)",
      slots: [
        {
          name: "CLAUSE",
          description: "The observation or conclusion",
          description_bn: "পর্যবেক্ষণ বা উপসংহার",
          acceptedTypes: ["clause"],
          examples: ["we were wrong", "the system has failed", "he left early"],
        },
      ],
      examples: [
        {
          en: "It appears that we were wrong.",
          bn: "মনে হচ্ছে আমরা ভুল ছিলাম।",
          slotValues: { CLAUSE: "we were wrong" },
          topicArea: "daily_life",
        },
        {
          en: "It appears that the system has failed.",
          bn: "মনে হচ্ছে সিস্টেম বিকল হয়ে গেছে।",
          slotValues: { CLAUSE: "the system has failed" },
          topicArea: "work",
        },
        {
          en: "It appears that he left early.",
          bn: "মনে হচ্ছে সে তাড়াতাড়ি চলে গেছে।",
          slotValues: { CLAUSE: "he left early" },
          topicArea: "work",
        },
        {
          en: "It appears that the meeting has been canceled.",
          bn: "মনে হচ্ছে সভা বাতিল করা হয়েছে।",
          slotValues: { CLAUSE: "the meeting has been canceled" },
          topicArea: "work",
        },
        {
          en: "It appears that nobody knows the answer.",
          bn: "মনে হচ্ছে কেউ উত্তর জানে না।",
          slotValues: { CLAUSE: "nobody knows the answer" },
          topicArea: "education",
        },
        {
          en: "It appears that the train is delayed.",
          bn: "মনে হচ্ছে ট্রেন দেরি হবে।",
          slotValues: { CLAUSE: "the train is delayed" },
          topicArea: "travel",
        },
        {
          en: "It appears that she has already left the country.",
          bn: "মনে হচ্ছে সে ইতিমধ্যে দেশ ছেড়ে চলে গেছে।",
          slotValues: { CLAUSE: "she has already left the country" },
          topicArea: "travel",
        },
        {
          en: "It appears that the problem is more serious than we thought.",
          bn: "মনে হচ্ছে সমস্যাটি আমরা যা ভেবেছিলাম তার চেয়ে বেশি গুরুতর।",
          slotValues: { CLAUSE: "the problem is more serious than we thought" },
          topicArea: "work",
        },
        {
          en: "It appears that they have reached an agreement.",
          bn: "মনে হচ্ছে তারা একটি চুক্তিতে পৌঁছেছে।",
          slotValues: { CLAUSE: "they have reached an agreement" },
          topicArea: "work",
        },
        {
          en: "It appears that the store is closed today.",
          bn: "মনে হচ্ছে দোকানটি আজ বন্ধ।",
          slotValues: { CLAUSE: "the store is closed today" },
          topicArea: "shopping",
        },
        {
          en: "It appears that someone broke into the office.",
          bn: "মনে হচ্ছে কেউ অফিসে ঢুকেছে।",
          slotValues: { CLAUSE: "someone broke into the office" },
          topicArea: "daily_life",
        },
        {
          en: "It appears that the results are positive.",
          bn: "মনে হচ্ছে ফলাফল ইতিবাচক।",
          slotValues: { CLAUSE: "the results are positive" },
          topicArea: "health",
        },
        {
          en: "It appears that the economy is recovering.",
          bn: "মনে হচ্ছে অর্থনীতি পুনরুদ্ধার হচ্ছে।",
          slotValues: { CLAUSE: "the economy is recovering" },
          topicArea: "daily_life",
        },
        {
          en: "It appears that both teams are equally strong.",
          bn: "মনে হচ্ছে দুটি দলই সমান শক্তিশালী।",
          slotValues: { CLAUSE: "both teams are equally strong" },
          topicArea: "entertainment",
        },
        {
          en: "It appears that the medication is working.",
          bn: "মনে হচ্ছে ওষুধ কাজ করছে।",
          slotValues: { CLAUSE: "the medication is working" },
          topicArea: "health",
        },
      ],
      formality: "formal",
      difficulty: "advanced",
    },
    {
      id: "S14.3",
      formula: "It turns out that [CLAUSE]",
      formula_bn: "জানা গেল যে [উপবাক্য]",
      patternName: "It Turns Out That (Unexpected Discovery)",
      patternName_bn: "জানা গেল যে (অপ্রত্যাশিত আবিষ্কার)",
      slots: [
        {
          name: "CLAUSE",
          description: "The unexpected discovery or fact",
          description_bn: "অপ্রত্যাশিত আবিষ্কার বা তথ্য",
          acceptedTypes: ["clause"],
          examples: ["he was right all along", "they are related", "it was a mistake"],
        },
      ],
      examples: [
        {
          en: "It turns out that he was right all along.",
          bn: "জানা গেল যে সে সবসময়ই সঠিক ছিল।",
          slotValues: { CLAUSE: "he was right all along" },
          topicArea: "daily_life",
        },
        {
          en: "It turns out that they are cousins.",
          bn: "জানা গেল যে তারা কাজিন।",
          slotValues: { CLAUSE: "they are cousins" },
          topicArea: "relationships",
        },
        {
          en: "It turns out that it was a mistake.",
          bn: "জানা গেল যে এটা একটি ভুল ছিল।",
          slotValues: { CLAUSE: "it was a mistake" },
          topicArea: "work",
        },
        {
          en: "It turns out that the restaurant is closed on Mondays.",
          bn: "জানা গেল যে রেস্তোরাঁটি সোমবারে বন্ধ থাকে।",
          slotValues: { CLAUSE: "the restaurant is closed on Mondays" },
          topicArea: "food",
        },
        {
          en: "It turns out that we took the wrong road.",
          bn: "জানা গেল যে আমরা ভুল রাস্তায় গিয়েছিলাম।",
          slotValues: { CLAUSE: "we took the wrong road" },
          topicArea: "travel",
        },
        {
          en: "It turns out that she had already paid the bill.",
          bn: "জানা গেল যে সে ইতিমধ্যে বিল পরিশোধ করেছিল।",
          slotValues: { CLAUSE: "she had already paid the bill" },
          topicArea: "daily_life",
        },
        {
          en: "It turns out that the rumor was true.",
          bn: "জানা গেল যে গুজবটি সত্য ছিল।",
          slotValues: { CLAUSE: "the rumor was true" },
          topicArea: "daily_life",
        },
        {
          en: "It turns out that the test results were mixed up.",
          bn: "জানা গেল যে পরীক্ষার ফলাফল গুলিয়ে গিয়েছিল।",
          slotValues: { CLAUSE: "the test results were mixed up" },
          topicArea: "health",
        },
        {
          en: "It turns out that he never received my email.",
          bn: "জানা গেল যে সে কখনও আমার ইমেইল পায়নি।",
          slotValues: { CLAUSE: "he never received my email" },
          topicArea: "work",
        },
        {
          en: "It turns out that the hotel was fully booked.",
          bn: "জানা গেল যে হোটেলটি পুরোপুরি বুক হয়ে গিয়েছিল।",
          slotValues: { CLAUSE: "the hotel was fully booked" },
          topicArea: "travel",
        },
        {
          en: "It turns out that she speaks three languages.",
          bn: "জানা গেল যে সে তিনটি ভাষায় কথা বলে।",
          slotValues: { CLAUSE: "she speaks three languages" },
          topicArea: "education",
        },
        {
          en: "It turns out that the medicine had side effects.",
          bn: "জানা গেল যে ওষুধটির পার্শ্বপ্রতিক্রিয়া ছিল।",
          slotValues: { CLAUSE: "the medicine had side effects" },
          topicArea: "health",
        },
        {
          en: "It turns out that we have mutual friends.",
          bn: "জানা গেল যে আমাদের পারস্পরিক বন্ধু আছে।",
          slotValues: { CLAUSE: "we have mutual friends" },
          topicArea: "relationships",
        },
        {
          en: "It turns out that the deadline was extended.",
          bn: "জানা গেল যে সময়সীমা বাড়ানো হয়েছে।",
          slotValues: { CLAUSE: "the deadline was extended" },
          topicArea: "work",
        },
        {
          en: "It turns out that the concert was free.",
          bn: "জানা গেল যে কনসার্টটি বিনামূল্যে ছিল।",
          slotValues: { CLAUSE: "the concert was free" },
          topicArea: "entertainment",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
    },
    {
      id: "S14.4",
      formula: "[PERSON] seems to [ACTION]",
      formula_bn: "[ব্যক্তি] [কাজ] করছে বলে মনে হচ্ছে",
      patternName: "Seems To + Verb",
      patternName_bn: "করছে বলে মনে হচ্ছে",
      slots: [
        {
          name: "PERSON",
          description: "The person who appears to be doing something",
          description_bn: "যে ব্যক্তি কিছু করছে বলে মনে হচ্ছে",
          acceptedTypes: ["person", "noun_phrase"],
          examples: ["He", "She", "The children"],
        },
        {
          name: "ACTION",
          description: "The action they appear to be doing",
          description_bn: "যে কাজ তারা করছে বলে মনে হচ্ছে",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["enjoy it", "know the answer", "understand"],
        },
      ],
      examples: [
        {
          en: "He seems to enjoy his new job.",
          bn: "সে তার নতুন চাকরি উপভোগ করছে বলে মনে হচ্ছে।",
          slotValues: { PERSON: "He", ACTION: "enjoy his new job" },
          topicArea: "work",
        },
        {
          en: "She seems to know the answer.",
          bn: "সে উত্তর জানে বলে মনে হচ্ছে।",
          slotValues: { PERSON: "She", ACTION: "know the answer" },
          topicArea: "education",
        },
        {
          en: "The children seem to understand the lesson.",
          bn: "বাচ্চারা পাঠটি বুঝেছে বলে মনে হচ্ছে।",
          slotValues: { PERSON: "The children", ACTION: "understand the lesson" },
          topicArea: "education",
        },
        {
          en: "He seems to have forgotten about the meeting.",
          bn: "সে সভার কথা ভুলে গেছে বলে মনে হচ্ছে।",
          slotValues: { PERSON: "He", ACTION: "have forgotten about the meeting" },
          topicArea: "work",
        },
        {
          en: "They seem to like this restaurant.",
          bn: "তারা এই রেস্তোরাঁ পছন্দ করে বলে মনে হচ্ছে।",
          slotValues: { PERSON: "They", ACTION: "like this restaurant" },
          topicArea: "food",
        },
        {
          en: "She seems to be feeling better.",
          bn: "সে ভালো অনুভব করছে বলে মনে হচ্ছে।",
          slotValues: { PERSON: "She", ACTION: "be feeling better" },
          topicArea: "health",
        },
        {
          en: "The manager seems to agree with us.",
          bn: "ম্যানেজার আমাদের সাথে একমত বলে মনে হচ্ছে।",
          slotValues: { PERSON: "The manager", ACTION: "agree with us" },
          topicArea: "work",
        },
        {
          en: "He seems to be hiding something.",
          bn: "সে কিছু লুকাচ্ছে বলে মনে হচ্ছে।",
          slotValues: { PERSON: "He", ACTION: "be hiding something" },
          topicArea: "relationships",
        },
        {
          en: "The students seem to prefer online classes.",
          bn: "শিক্ষার্থীরা অনলাইন ক্লাস পছন্দ করে বলে মনে হচ্ছে।",
          slotValues: { PERSON: "The students", ACTION: "prefer online classes" },
          topicArea: "education",
        },
        {
          en: "She seems to care about the environment.",
          bn: "সে পরিবেশ নিয়ে চিন্তিত বলে মনে হচ্ছে।",
          slotValues: { PERSON: "She", ACTION: "care about the environment" },
          topicArea: "daily_life",
        },
        {
          en: "He seems to be lost.",
          bn: "সে হারিয়ে গেছে বলে মনে হচ্ছে।",
          slotValues: { PERSON: "He", ACTION: "be lost" },
          topicArea: "travel",
        },
        {
          en: "The dog seems to miss its owner.",
          bn: "কুকুরটি তার মালিককে মিস করছে বলে মনে হচ্ছে।",
          slotValues: { PERSON: "The dog", ACTION: "miss its owner" },
          topicArea: "daily_life",
        },
        {
          en: "They seem to be having a good time.",
          bn: "তারা ভালো সময় কাটাচ্ছে বলে মনে হচ্ছে।",
          slotValues: { PERSON: "They", ACTION: "be having a good time" },
          topicArea: "entertainment",
        },
        {
          en: "She seems to have a lot of experience.",
          bn: "তার অনেক অভিজ্ঞতা আছে বলে মনে হচ্ছে।",
          slotValues: { PERSON: "She", ACTION: "have a lot of experience" },
          topicArea: "work",
        },
        {
          en: "He seems to be improving gradually.",
          bn: "সে ধীরে ধীরে উন্নতি করছে বলে মনে হচ্ছে।",
          slotValues: { PERSON: "He", ACTION: "be improving gradually" },
          topicArea: "health",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
    },
    {
      id: "S14.5",
      formula: "It seems like [CLAUSE]",
      formula_bn: "মনে হচ্ছে [উপবাক্য]",
      patternName: "It Seems Like (Informal Impression)",
      patternName_bn: "মনে হচ্ছে (অনানুষ্ঠানিক ধারণা)",
      slots: [
        {
          name: "CLAUSE",
          description: "The impression or feeling you have",
          description_bn: "আপনার ধারণা বা অনুভূতি",
          acceptedTypes: ["clause"],
          examples: ["it's going to rain", "everyone is busy", "he doesn't care"],
        },
      ],
      examples: [
        {
          en: "It seems like it's going to rain.",
          bn: "মনে হচ্ছে বৃষ্টি হবে।",
          slotValues: { CLAUSE: "it's going to rain" },
          topicArea: "daily_life",
        },
        {
          en: "It seems like everyone is busy.",
          bn: "মনে হচ্ছে সবাই ব্যস্ত।",
          slotValues: { CLAUSE: "everyone is busy" },
          topicArea: "work",
        },
        {
          en: "It seems like he doesn't care.",
          bn: "মনে হচ্ছে সে পরোয়া করে না।",
          slotValues: { CLAUSE: "he doesn't care" },
          topicArea: "relationships",
        },
        {
          en: "It seems like the project is behind schedule.",
          bn: "মনে হচ্ছে প্রকল্পটি সময়সূচির পিছনে পড়ে গেছে।",
          slotValues: { CLAUSE: "the project is behind schedule" },
          topicArea: "work",
        },
        {
          en: "It seems like a good idea.",
          bn: "মনে হচ্ছে এটা একটা ভালো ধারণা।",
          slotValues: { CLAUSE: "a good idea" },
          topicArea: "daily_life",
        },
        {
          en: "It seems like she's upset about something.",
          bn: "মনে হচ্ছে সে কিছু নিয়ে মন খারাপ।",
          slotValues: { CLAUSE: "she's upset about something" },
          topicArea: "relationships",
        },
        {
          en: "It seems like we've been waiting forever.",
          bn: "মনে হচ্ছে আমরা অনন্তকাল ধরে অপেক্ষা করছি।",
          slotValues: { CLAUSE: "we've been waiting forever" },
          topicArea: "daily_life",
        },
        {
          en: "It seems like the price has gone up.",
          bn: "মনে হচ্ছে দাম বেড়ে গেছে।",
          slotValues: { CLAUSE: "the price has gone up" },
          topicArea: "shopping",
        },
        {
          en: "It seems like they are not coming.",
          bn: "মনে হচ্ছে তারা আসছে না।",
          slotValues: { CLAUSE: "they are not coming" },
          topicArea: "daily_life",
        },
        {
          en: "It seems like summer came early this year.",
          bn: "মনে হচ্ছে এবার গ্রীষ্ম তাড়াতাড়ি এসেছে।",
          slotValues: { CLAUSE: "summer came early this year" },
          topicArea: "daily_life",
        },
        {
          en: "It seems like you need some rest.",
          bn: "মনে হচ্ছে তোমার একটু বিশ্রাম দরকার।",
          slotValues: { CLAUSE: "you need some rest" },
          topicArea: "health",
        },
        {
          en: "It seems like the traffic is getting worse.",
          bn: "মনে হচ্ছে ট্রাফিক আরও খারাপ হচ্ছে।",
          slotValues: { CLAUSE: "the traffic is getting worse" },
          topicArea: "travel",
        },
        {
          en: "It seems like nobody is home.",
          bn: "মনে হচ্ছে বাড়িতে কেউ নেই।",
          slotValues: { CLAUSE: "nobody is home" },
          topicArea: "daily_life",
        },
        {
          en: "It seems like the exam was easy for everyone.",
          bn: "মনে হচ্ছে পরীক্ষা সবার জন্য সহজ ছিল।",
          slotValues: { CLAUSE: "the exam was easy for everyone" },
          topicArea: "education",
        },
        {
          en: "It seems like we made the right decision.",
          bn: "মনে হচ্ছে আমরা সঠিক সিদ্ধান্ত নিয়েছি।",
          slotValues: { CLAUSE: "we made the right decision" },
          topicArea: "work",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
    },
    {
      id: "S14.6",
      formula: "[THING] is growing [ADJECTIVE]",
      formula_bn: "[জিনিস] ক্রমশ [বিশেষণ] হচ্ছে",
      patternName: "Gradual Change (Growing + Adjective)",
      patternName_bn: "ক্রমান্বয়ে পরিবর্তন (ক্রমশ + বিশেষণ)",
      slots: [
        {
          name: "THING",
          description: "The subject that is gradually changing",
          description_bn: "যে বিষয়টি ধীরে ধীরে পরিবর্তন হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase", "person"],
          examples: ["The city", "She", "The problem"],
        },
        {
          name: "ADJECTIVE",
          description: "The adjective describing the gradual change",
          description_bn: "ক্রমান্বয়ে পরিবর্তন বর্ণনাকারী বিশেষণ",
          acceptedTypes: ["adjective", "adjective_phrase"],
          examples: ["bigger", "more confident", "worse"],
        },
      ],
      examples: [
        {
          en: "The city is growing bigger.",
          bn: "শহর ক্রমশ বড় হচ্ছে।",
          slotValues: { THING: "The city", ADJECTIVE: "bigger" },
          topicArea: "daily_life",
        },
        {
          en: "She is growing more confident.",
          bn: "সে ক্রমশ আরও আত্মবিশ্বাসী হচ্ছে।",
          slotValues: { THING: "She", ADJECTIVE: "more confident" },
          topicArea: "daily_life",
        },
        {
          en: "The problem is growing worse.",
          bn: "সমস্যা ক্রমশ আরও খারাপ হচ্ছে।",
          slotValues: { THING: "The problem", ADJECTIVE: "worse" },
          topicArea: "daily_life",
        },
        {
          en: "He is growing impatient.",
          bn: "সে ক্রমশ অধৈর্য হচ্ছে।",
          slotValues: { THING: "He", ADJECTIVE: "impatient" },
          topicArea: "daily_life",
        },
        {
          en: "The company is growing stronger every year.",
          bn: "কোম্পানি প্রতি বছর ক্রমশ শক্তিশালী হচ্ছে।",
          slotValues: { THING: "The company", ADJECTIVE: "stronger every year" },
          topicArea: "work",
        },
        {
          en: "The traffic is growing heavier during rush hour.",
          bn: "ব্যস্ত সময়ে ট্রাফিক ক্রমশ ভারী হচ্ছে।",
          slotValues: { THING: "The traffic", ADJECTIVE: "heavier during rush hour" },
          topicArea: "travel",
        },
        {
          en: "The list of ingredients is growing longer.",
          bn: "উপকরণের তালিকা ক্রমশ লম্বা হচ্ছে।",
          slotValues: { THING: "The list of ingredients", ADJECTIVE: "longer" },
          topicArea: "food",
        },
        {
          en: "The student is growing more interested in science.",
          bn: "ছাত্রটি ক্রমশ বিজ্ঞানে আরও আগ্রহী হচ্ছে।",
          slotValues: { THING: "The student", ADJECTIVE: "more interested in science" },
          topicArea: "education",
        },
        {
          en: "His health is growing better with the treatment.",
          bn: "চিকিৎসায় তার স্বাস্থ্য ক্রমশ ভালো হচ্ছে।",
          slotValues: { THING: "His health", ADJECTIVE: "better with the treatment" },
          topicArea: "health",
        },
        {
          en: "The cost of living is growing higher.",
          bn: "জীবনযাত্রার খরচ ক্রমশ বেশি হচ্ছে।",
          slotValues: { THING: "The cost of living", ADJECTIVE: "higher" },
          topicArea: "shopping",
        },
        {
          en: "Their friendship is growing deeper.",
          bn: "তাদের বন্ধুত্ব ক্রমশ গভীর হচ্ছে।",
          slotValues: { THING: "Their friendship", ADJECTIVE: "deeper" },
          topicArea: "relationships",
        },
        {
          en: "The demand for online courses is growing rapidly.",
          bn: "অনলাইন কোর্সের চাহিদা ক্রমশ দ্রুত বাড়ছে।",
          slotValues: { THING: "The demand for online courses", ADJECTIVE: "rapidly" },
          topicArea: "education",
        },
        {
          en: "The weather is growing colder.",
          bn: "আবহাওয়া ক্রমশ ঠান্ডা হচ্ছে।",
          slotValues: { THING: "The weather", ADJECTIVE: "colder" },
          topicArea: "daily_life",
        },
        {
          en: "The team is growing tired of the delays.",
          bn: "দল ক্রমশ বিলম্বে ক্লান্ত হচ্ছে।",
          slotValues: { THING: "The team", ADJECTIVE: "tired of the delays" },
          topicArea: "work",
        },
        {
          en: "The children are growing taller every month.",
          bn: "বাচ্চারা প্রতি মাসে ক্রমশ লম্বা হচ্ছে।",
          slotValues: { THING: "The children", ADJECTIVE: "taller every month" },
          topicArea: "health",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
      usageNote:
        "'Growing + adjective' describes a gradual, ongoing change. It emphasizes that the change is happening progressively over time.",
      usageNote_bn:
        "'Growing + adjective' একটি ক্রমান্বয়ে, চলমান পরিবর্তন বর্ণনা করে। এটি জোর দেয় যে পরিবর্তনটি সময়ের সাথে ধীরে ধীরে ঘটছে।",
    },
  ],
};
