import { PatternCategory } from "@/types/pattern";

export const categoryS17: PatternCategory = {
  id: "S17",
  slug: "as-if-as-though",
  name: "As If / As Though Patterns",
  name_bn: "যেন / মনে হচ্ছে প্যাটার্ন",
  description:
    "Describe appearances and behaviors using as if and as though",
  description_bn:
    "as if এবং as though ব্যবহার করে চেহারা ও আচরণ বর্ণনা করুন",
  icon: "🎭",
  group: "S",
  groupName: "Advanced Structural Patterns",
  groupName_bn: "উন্নত গঠনমূলক প্যাটার্ন",
  difficulty: "advanced",
  patterns: [
    {
      id: "S17.1",
      formula: "[PERSON] looks as if [CLAUSE]",
      formula_bn: "[ব্যক্তি] দেখে মনে হচ্ছে যেন [উপবাক্য]",
      patternName: "Looks As If (Appearance)",
      patternName_bn: "দেখে মনে হচ্ছে যেন (চেহারা)",
      slots: [
        {
          name: "PERSON",
          description: "The person or thing being observed",
          description_bn: "যে ব্যক্তি বা জিনিস পর্যবেক্ষণ করা হচ্ছে",
          acceptedTypes: ["person", "noun_phrase"],
          examples: ["He", "She", "The building"],
        },
        {
          name: "CLAUSE",
          description: "What their appearance suggests",
          description_bn: "তাদের চেহারা কী বোঝাচ্ছে",
          acceptedTypes: ["clause"],
          examples: ["he hasn't slept", "she's been crying", "it might rain"],
        },
      ],
      examples: [
        {
          en: "He looks as if he hasn't slept all night.",
          bn: "তাকে দেখে মনে হচ্ছে যেন সে সারারাত ঘুমায়নি।",
          slotValues: { PERSON: "He", CLAUSE: "he hasn't slept all night" },
          topicArea: "health",
        },
        {
          en: "She looks as if she's been crying.",
          bn: "তাকে দেখে মনে হচ্ছে যেন সে কাঁদছিল।",
          slotValues: { PERSON: "She", CLAUSE: "she's been crying" },
          topicArea: "relationships",
        },
        {
          en: "The sky looks as if it might rain.",
          bn: "আকাশ দেখে মনে হচ্ছে যেন বৃষ্টি হতে পারে।",
          slotValues: { PERSON: "The sky", CLAUSE: "it might rain" },
          topicArea: "daily_life",
        },
        {
          en: "He looks as if he's seen a ghost.",
          bn: "তাকে দেখে মনে হচ্ছে যেন সে ভূত দেখেছে।",
          slotValues: { PERSON: "He", CLAUSE: "he's seen a ghost" },
          topicArea: "daily_life",
        },
        {
          en: "She looks as if she doesn't feel well.",
          bn: "তাকে দেখে মনে হচ্ছে যেন তার শরীর ভালো নেই।",
          slotValues: { PERSON: "She", CLAUSE: "she doesn't feel well" },
          topicArea: "health",
        },
        {
          en: "The food looks as if it's been sitting there for hours.",
          bn: "খাবারটি দেখে মনে হচ্ছে যেন ঘণ্টার পর ঘণ্টা ধরে রাখা আছে।",
          slotValues: { PERSON: "The food", CLAUSE: "it's been sitting there for hours" },
          topicArea: "food",
        },
        {
          en: "He looks as if he just woke up.",
          bn: "তাকে দেখে মনে হচ্ছে যেন সে এইমাত্র ঘুম থেকে উঠেছে।",
          slotValues: { PERSON: "He", CLAUSE: "he just woke up" },
          topicArea: "daily_life",
        },
        {
          en: "The car looks as if it needs a wash.",
          bn: "গাড়িটি দেখে মনে হচ্ছে যেন ধোয়া দরকার।",
          slotValues: { PERSON: "The car", CLAUSE: "it needs a wash" },
          topicArea: "daily_life",
        },
        {
          en: "She looks as if she's expecting good news.",
          bn: "তাকে দেখে মনে হচ্ছে যেন সে ভালো খবর আশা করছে।",
          slotValues: { PERSON: "She", CLAUSE: "she's expecting good news" },
          topicArea: "daily_life",
        },
        {
          en: "The house looks as if nobody lives there.",
          bn: "বাড়িটি দেখে মনে হচ্ছে যেন সেখানে কেউ থাকে না।",
          slotValues: { PERSON: "The house", CLAUSE: "nobody lives there" },
          topicArea: "daily_life",
        },
        {
          en: "He looks as if he's in a hurry.",
          bn: "তাকে দেখে মনে হচ্ছে যেন তার তাড়া আছে।",
          slotValues: { PERSON: "He", CLAUSE: "he's in a hurry" },
          topicArea: "daily_life",
        },
        {
          en: "The garden looks as if it hasn't been watered.",
          bn: "বাগানটি দেখে মনে হচ্ছে যেন পানি দেওয়া হয়নি।",
          slotValues: { PERSON: "The garden", CLAUSE: "it hasn't been watered" },
          topicArea: "daily_life",
        },
        {
          en: "She looks as if she wants to say something.",
          bn: "তাকে দেখে মনে হচ্ছে যেন সে কিছু বলতে চায়।",
          slotValues: { PERSON: "She", CLAUSE: "she wants to say something" },
          topicArea: "relationships",
        },
        {
          en: "The road looks as if it was recently repaired.",
          bn: "রাস্তাটি দেখে মনে হচ্ছে যেন সম্প্রতি মেরামত করা হয়েছে।",
          slotValues: { PERSON: "The road", CLAUSE: "it was recently repaired" },
          topicArea: "travel",
        },
        {
          en: "He looks as if he's lost weight.",
          bn: "তাকে দেখে মনে হচ্ছে যেন সে ওজন কমিয়েছে।",
          slotValues: { PERSON: "He", CLAUSE: "he's lost weight" },
          topicArea: "health",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
    },
    {
      id: "S17.2",
      formula: "It seems as though [CLAUSE]",
      formula_bn: "মনে হচ্ছে যেন [উপবাক্য]",
      patternName: "Seems As Though (Impression)",
      patternName_bn: "মনে হচ্ছে যেন (ধারণা)",
      slots: [
        {
          name: "CLAUSE",
          description: "The impression or feeling",
          description_bn: "ধারণা বা অনুভূতি",
          acceptedTypes: ["clause"],
          examples: ["nothing has changed", "time flies", "everyone is tired"],
        },
      ],
      examples: [
        {
          en: "It seems as though nothing has changed.",
          bn: "মনে হচ্ছে যেন কিছুই বদলায়নি।",
          slotValues: { CLAUSE: "nothing has changed" },
          topicArea: "daily_life",
        },
        {
          en: "It seems as though time flies when you're having fun.",
          bn: "মনে হচ্ছে যেন মজা করলে সময় উড়ে যায়।",
          slotValues: { CLAUSE: "time flies when you're having fun" },
          topicArea: "daily_life",
        },
        {
          en: "It seems as though everyone is tired today.",
          bn: "মনে হচ্ছে যেন আজ সবাই ক্লান্ত।",
          slotValues: { CLAUSE: "everyone is tired today" },
          topicArea: "work",
        },
        {
          en: "It seems as though the problem is getting worse.",
          bn: "মনে হচ্ছে যেন সমস্যা আরও খারাপ হচ্ছে।",
          slotValues: { CLAUSE: "the problem is getting worse" },
          topicArea: "work",
        },
        {
          en: "It seems as though he doesn't want to participate.",
          bn: "মনে হচ্ছে যেন সে অংশগ্রহণ করতে চায় না।",
          slotValues: { CLAUSE: "he doesn't want to participate" },
          topicArea: "work",
        },
        {
          en: "It seems as though the economy is improving.",
          bn: "মনে হচ্ছে যেন অর্থনীতির উন্নতি হচ্ছে।",
          slotValues: { CLAUSE: "the economy is improving" },
          topicArea: "daily_life",
        },
        {
          en: "It seems as though they've already decided.",
          bn: "মনে হচ্ছে যেন তারা ইতিমধ্যে সিদ্ধান্ত নিয়েছে।",
          slotValues: { CLAUSE: "they've already decided" },
          topicArea: "work",
        },
        {
          en: "It seems as though spring has arrived.",
          bn: "মনে হচ্ছে যেন বসন্ত এসেছে।",
          slotValues: { CLAUSE: "spring has arrived" },
          topicArea: "daily_life",
        },
        {
          en: "It seems as though the rain will never stop.",
          bn: "মনে হচ্ছে যেন বৃষ্টি কখনো থামবে না।",
          slotValues: { CLAUSE: "the rain will never stop" },
          topicArea: "daily_life",
        },
        {
          en: "It seems as though she's not interested.",
          bn: "মনে হচ্ছে যেন সে আগ্রহী নয়।",
          slotValues: { CLAUSE: "she's not interested" },
          topicArea: "relationships",
        },
        {
          en: "It seems as though the meeting will be postponed.",
          bn: "মনে হচ্ছে যেন সভা স্থগিত হবে।",
          slotValues: { CLAUSE: "the meeting will be postponed" },
          topicArea: "work",
        },
        {
          en: "It seems as though we've made the wrong choice.",
          bn: "মনে হচ্ছে যেন আমরা ভুল পছন্দ করেছি।",
          slotValues: { CLAUSE: "we've made the wrong choice" },
          topicArea: "daily_life",
        },
        {
          en: "It seems as though the patient is recovering well.",
          bn: "মনে হচ্ছে যেন রোগী ভালোভাবে সুস্থ হচ্ছে।",
          slotValues: { CLAUSE: "the patient is recovering well" },
          topicArea: "health",
        },
        {
          en: "It seems as though prices keep going up.",
          bn: "মনে হচ্ছে যেন দাম বাড়তেই থাকছে।",
          slotValues: { CLAUSE: "prices keep going up" },
          topicArea: "shopping",
        },
        {
          en: "It seems as though the whole world is watching.",
          bn: "মনে হচ্ছে যেন সারা পৃথিবী দেখছে।",
          slotValues: { CLAUSE: "the whole world is watching" },
          topicArea: "daily_life",
        },
      ],
      formality: "polite",
      difficulty: "advanced",
    },
    {
      id: "S17.3",
      formula: "[PERSON] acts as if [CLAUSE]",
      formula_bn: "[ব্যক্তি] এমনভাবে আচরণ করে যেন [উপবাক্য]",
      patternName: "Acts As If (Behavior)",
      patternName_bn: "এমনভাবে আচরণ করে যেন (আচরণ)",
      slots: [
        {
          name: "PERSON",
          description: "The person whose behavior is being described",
          description_bn: "যে ব্যক্তির আচরণ বর্ণনা করা হচ্ছে",
          acceptedTypes: ["person", "noun_phrase"],
          examples: ["He", "She", "They"],
        },
        {
          name: "CLAUSE",
          description: "What their behavior suggests",
          description_bn: "তাদের আচরণ কী বোঝাচ্ছে",
          acceptedTypes: ["clause"],
          examples: ["he owns the place", "nothing happened", "she's the boss"],
        },
      ],
      examples: [
        {
          en: "He acts as if he owns the place.",
          bn: "সে এমনভাবে আচরণ করে যেন জায়গাটা তার।",
          slotValues: { PERSON: "He", CLAUSE: "he owns the place" },
          topicArea: "work",
        },
        {
          en: "She acts as if nothing happened.",
          bn: "সে এমনভাবে আচরণ করে যেন কিছুই হয়নি।",
          slotValues: { PERSON: "She", CLAUSE: "nothing happened" },
          topicArea: "relationships",
        },
        {
          en: "They act as if they don't know each other.",
          bn: "তারা এমনভাবে আচরণ করে যেন তারা একে অপরকে চেনে না।",
          slotValues: { PERSON: "They", CLAUSE: "they don't know each other" },
          topicArea: "relationships",
        },
        {
          en: "He acts as if he knows everything.",
          bn: "সে এমনভাবে আচরণ করে যেন সে সবকিছু জানে।",
          slotValues: { PERSON: "He", CLAUSE: "he knows everything" },
          topicArea: "work",
        },
        {
          en: "She acts as if she doesn't care.",
          bn: "সে এমনভাবে আচরণ করে যেন সে পরোয়া করে না।",
          slotValues: { PERSON: "She", CLAUSE: "she doesn't care" },
          topicArea: "relationships",
        },
        {
          en: "He acts as if the rules don't apply to him.",
          bn: "সে এমনভাবে আচরণ করে যেন নিয়ম তার জন্য প্রযোজ্য নয়।",
          slotValues: { PERSON: "He", CLAUSE: "the rules don't apply to him" },
          topicArea: "work",
        },
        {
          en: "She acts as if she's the boss.",
          bn: "সে এমনভাবে আচরণ করে যেন সে বস।",
          slotValues: { PERSON: "She", CLAUSE: "she's the boss" },
          topicArea: "work",
        },
        {
          en: "They act as if money grows on trees.",
          bn: "তারা এমনভাবে আচরণ করে যেন গাছে টাকা ফলে।",
          slotValues: { PERSON: "They", CLAUSE: "money grows on trees" },
          topicArea: "daily_life",
        },
        {
          en: "He acts as if he's never made a mistake.",
          bn: "সে এমনভাবে আচরণ করে যেন সে কখনো ভুল করেনি।",
          slotValues: { PERSON: "He", CLAUSE: "he's never made a mistake" },
          topicArea: "work",
        },
        {
          en: "She acts as if we're strangers.",
          bn: "সে এমনভাবে আচরণ করে যেন আমরা অপরিচিত।",
          slotValues: { PERSON: "She", CLAUSE: "we're strangers" },
          topicArea: "relationships",
        },
        {
          en: "He acts as if he's still a child.",
          bn: "সে এমনভাবে আচরণ করে যেন সে এখনও একটা বাচ্চা।",
          slotValues: { PERSON: "He", CLAUSE: "he's still a child" },
          topicArea: "daily_life",
        },
        {
          en: "She acts as if she has no worries.",
          bn: "সে এমনভাবে আচরণ করে যেন তার কোনো চিন্তা নেই।",
          slotValues: { PERSON: "She", CLAUSE: "she has no worries" },
          topicArea: "daily_life",
        },
        {
          en: "They act as if they've won the lottery.",
          bn: "তারা এমনভাবে আচরণ করে যেন তারা লটারি জিতেছে।",
          slotValues: { PERSON: "They", CLAUSE: "they've won the lottery" },
          topicArea: "daily_life",
        },
        {
          en: "He acts as if he didn't hear me.",
          bn: "সে এমনভাবে আচরণ করে যেন সে আমার কথা শোনেনি।",
          slotValues: { PERSON: "He", CLAUSE: "he didn't hear me" },
          topicArea: "relationships",
        },
        {
          en: "She acts as if she's always right.",
          bn: "সে এমনভাবে আচরণ করে যেন সে সবসময় সঠিক।",
          slotValues: { PERSON: "She", CLAUSE: "she's always right" },
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
    },
    {
      id: "S17.4",
      formula: "It feels as though [CLAUSE]",
      formula_bn: "মনে হচ্ছে যেন [উপবাক্য]",
      patternName: "Feels As Though (Sensation/Emotion)",
      patternName_bn: "অনুভব হচ্ছে যেন (অনুভূতি/আবেগ)",
      slots: [
        {
          name: "CLAUSE",
          description: "The feeling or sensation being described",
          description_bn: "যে অনুভূতি বা সংবেদন বর্ণনা করা হচ্ছে",
          acceptedTypes: ["clause"],
          examples: ["the world has stopped", "we've been here before", "nothing is real"],
        },
      ],
      examples: [
        {
          en: "It feels as though the world has stopped.",
          bn: "মনে হচ্ছে যেন পৃথিবী থেমে গেছে।",
          slotValues: { CLAUSE: "the world has stopped" },
          topicArea: "daily_life",
        },
        {
          en: "It feels as though we've been here before.",
          bn: "মনে হচ্ছে যেন আমরা আগে এখানে এসেছি।",
          slotValues: { CLAUSE: "we've been here before" },
          topicArea: "travel",
        },
        {
          en: "It feels as though summer will never end.",
          bn: "মনে হচ্ছে যেন গ্রীষ্ম কখনো শেষ হবে না।",
          slotValues: { CLAUSE: "summer will never end" },
          topicArea: "daily_life",
        },
        {
          en: "It feels as though I've known you forever.",
          bn: "মনে হচ্ছে যেন আমি তোমাকে চিরকাল ধরে চিনি।",
          slotValues: { CLAUSE: "I've known you forever" },
          topicArea: "relationships",
        },
        {
          en: "It feels as though this day will never end.",
          bn: "মনে হচ্ছে যেন এই দিন কখনো শেষ হবে না।",
          slotValues: { CLAUSE: "this day will never end" },
          topicArea: "work",
        },
        {
          en: "It feels as though nobody understands me.",
          bn: "মনে হচ্ছে যেন কেউ আমাকে বোঝে না।",
          slotValues: { CLAUSE: "nobody understands me" },
          topicArea: "relationships",
        },
        {
          en: "It feels as though we're going in circles.",
          bn: "মনে হচ্ছে যেন আমরা ঘুরে ঘুরে একই জায়গায় আসছি।",
          slotValues: { CLAUSE: "we're going in circles" },
          topicArea: "work",
        },
        {
          en: "It feels as though everything is falling apart.",
          bn: "মনে হচ্ছে যেন সবকিছু ভেঙে পড়ছে।",
          slotValues: { CLAUSE: "everything is falling apart" },
          topicArea: "daily_life",
        },
        {
          en: "It feels as though the exam was only yesterday.",
          bn: "মনে হচ্ছে যেন পরীক্ষা গতকালই হয়েছিল।",
          slotValues: { CLAUSE: "the exam was only yesterday" },
          topicArea: "education",
        },
        {
          en: "It feels as though time is running out.",
          bn: "মনে হচ্ছে যেন সময় ফুরিয়ে যাচ্ছে।",
          slotValues: { CLAUSE: "time is running out" },
          topicArea: "work",
        },
        {
          en: "It feels as though the meeting lasted forever.",
          bn: "মনে হচ্ছে যেন সভা অনন্তকাল ধরে চলেছে।",
          slotValues: { CLAUSE: "the meeting lasted forever" },
          topicArea: "work",
        },
        {
          en: "It feels as though I'm dreaming.",
          bn: "মনে হচ্ছে যেন আমি স্বপ্ন দেখছি।",
          slotValues: { CLAUSE: "I'm dreaming" },
          topicArea: "daily_life",
        },
        {
          en: "It feels as though things are getting better.",
          bn: "মনে হচ্ছে যেন অবস্থার উন্নতি হচ্ছে।",
          slotValues: { CLAUSE: "things are getting better" },
          topicArea: "daily_life",
        },
        {
          en: "It feels as though the cold weather will never pass.",
          bn: "মনে হচ্ছে যেন শীতের আবহাওয়া কখনো যাবে না।",
          slotValues: { CLAUSE: "the cold weather will never pass" },
          topicArea: "daily_life",
        },
        {
          en: "It feels as though we just arrived, but it's been hours.",
          bn: "মনে হচ্ছে যেন আমরা এইমাত্র এসেছি, কিন্তু ঘণ্টা পেরিয়ে গেছে।",
          slotValues: { CLAUSE: "we just arrived, but it's been hours" },
          topicArea: "travel",
        },
      ],
      formality: "polite",
      difficulty: "advanced",
    },
    {
      id: "S17.5",
      formula: "[PERSON] spoke as if [CLAUSE]",
      formula_bn: "[ব্যক্তি] এমনভাবে কথা বলেছে যেন [উপবাক্য]",
      patternName: "Spoke As If (Past Manner)",
      patternName_bn: "এমনভাবে কথা বলেছে যেন (অতীত পদ্ধতি)",
      slots: [
        {
          name: "PERSON",
          description: "The person who spoke in a certain way",
          description_bn: "যে ব্যক্তি একটি নির্দিষ্ট উপায়ে কথা বলেছে",
          acceptedTypes: ["person", "noun_phrase"],
          examples: ["He", "She", "The minister"],
        },
        {
          name: "CLAUSE",
          description: "What their manner of speaking suggested",
          description_bn: "তাদের কথা বলার ধরন কী বোঝাচ্ছিল",
          acceptedTypes: ["clause"],
          examples: ["he were an expert", "she had all the answers", "it didn't matter"],
        },
      ],
      examples: [
        {
          en: "He spoke as if he were an expert.",
          bn: "সে এমনভাবে কথা বলেছে যেন সে একজন বিশেষজ্ঞ।",
          slotValues: { PERSON: "He", CLAUSE: "he were an expert" },
          topicArea: "work",
        },
        {
          en: "She spoke as if she had all the answers.",
          bn: "সে এমনভাবে কথা বলেছে যেন সব উত্তর তার কাছে আছে।",
          slotValues: { PERSON: "She", CLAUSE: "she had all the answers" },
          topicArea: "education",
        },
        {
          en: "He spoke as if it didn't matter.",
          bn: "সে এমনভাবে কথা বলেছে যেন এটা কোনো ব্যাপার নয়।",
          slotValues: { PERSON: "He", CLAUSE: "it didn't matter" },
          topicArea: "daily_life",
        },
        {
          en: "The minister spoke as if the crisis were over.",
          bn: "মন্ত্রী এমনভাবে কথা বলেছে যেন সংকট শেষ হয়ে গেছে।",
          slotValues: { PERSON: "The minister", CLAUSE: "the crisis were over" },
          topicArea: "daily_life",
        },
        {
          en: "She spoke as if she knew me personally.",
          bn: "সে এমনভাবে কথা বলেছে যেন সে আমাকে ব্যক্তিগতভাবে চেনে।",
          slotValues: { PERSON: "She", CLAUSE: "she knew me personally" },
          topicArea: "relationships",
        },
        {
          en: "He spoke as if he had been there himself.",
          bn: "সে এমনভাবে কথা বলেছে যেন সে নিজে সেখানে ছিল।",
          slotValues: { PERSON: "He", CLAUSE: "he had been there himself" },
          topicArea: "travel",
        },
        {
          en: "She spoke as if she were the only one affected.",
          bn: "সে এমনভাবে কথা বলেছে যেন একমাত্র সে-ই ক্ষতিগ্রস্ত।",
          slotValues: { PERSON: "She", CLAUSE: "she were the only one affected" },
          topicArea: "work",
        },
        {
          en: "He spoke as if he didn't care about the consequences.",
          bn: "সে এমনভাবে কথা বলেছে যেন পরিণতি নিয়ে তার কোনো পরোয়া নেই।",
          slotValues: { PERSON: "He", CLAUSE: "he didn't care about the consequences" },
          topicArea: "daily_life",
        },
        {
          en: "The teacher spoke as if the students already understood.",
          bn: "শিক্ষক এমনভাবে কথা বলেছে যেন শিক্ষার্থীরা ইতিমধ্যে বুঝে গেছে।",
          slotValues: { PERSON: "The teacher", CLAUSE: "the students already understood" },
          topicArea: "education",
        },
        {
          en: "She spoke as if she were saying goodbye forever.",
          bn: "সে এমনভাবে কথা বলেছে যেন চিরদিনের জন্য বিদায় বলছে।",
          slotValues: { PERSON: "She", CLAUSE: "she were saying goodbye forever" },
          topicArea: "relationships",
        },
        {
          en: "He spoke as if money were no object.",
          bn: "সে এমনভাবে কথা বলেছে যেন টাকা কোনো বিষয়ই নয়।",
          slotValues: { PERSON: "He", CLAUSE: "money were no object" },
          topicArea: "shopping",
        },
        {
          en: "She spoke as if the whole thing were a joke.",
          bn: "সে এমনভাবে কথা বলেছে যেন পুরো ব্যাপারটা একটা রসিকতা।",
          slotValues: { PERSON: "She", CLAUSE: "the whole thing were a joke" },
          topicArea: "daily_life",
        },
        {
          en: "The doctor spoke as if there were nothing to worry about.",
          bn: "ডাক্তার এমনভাবে কথা বলেছে যেন চিন্তার কিছু নেই।",
          slotValues: { PERSON: "The doctor", CLAUSE: "there were nothing to worry about" },
          topicArea: "health",
        },
        {
          en: "He spoke as if he had already made up his mind.",
          bn: "সে এমনভাবে কথা বলেছে যেন সে ইতিমধ্যে সিদ্ধান্ত নিয়ে ফেলেছে।",
          slotValues: { PERSON: "He", CLAUSE: "he had already made up his mind" },
          topicArea: "work",
        },
        {
          en: "She spoke as if we owed her something.",
          bn: "সে এমনভাবে কথা বলেছে যেন আমরা তার কাছে ঋণী।",
          slotValues: { PERSON: "She", CLAUSE: "we owed her something" },
          topicArea: "relationships",
        },
      ],
      formality: "polite",
      difficulty: "advanced",
    },
  ],
};
