import { PatternCategory } from "@/types/pattern";

export const categoryS18: PatternCategory = {
  id: "S18",
  slug: "have-something-done",
  name: "Have/Get Something Done (Causative)",
  name_bn: "কাউকে দিয়ে কিছু করানো (কর্তৃকারক)",
  description:
    "Express getting someone else to do something for you using causative structures",
  description_bn:
    "কর্তৃকারক কাঠামো ব্যবহার করে অন্য কাউকে দিয়ে কিছু করানো প্রকাশ করুন",
  icon: "🔧",
  group: "S",
  groupName: "Advanced Structural Patterns",
  groupName_bn: "উন্নত গঠনমূলক প্যাটার্ন",
  difficulty: "advanced",
  patterns: [
    {
      id: "S18.1",
      formula: "I had [THING] [PP]",
      formula_bn: "আমি [বস্তু] [পিপি] করিয়েছি",
      patternName: "Had + Object + Past Participle",
      patternName_bn: "করিয়েছি + কর্ম + অতীত কৃদন্ত",
      slots: [
        {
          name: "THING",
          description: "The thing that was done by someone else",
          description_bn: "যে জিনিসটি অন্য কেউ করেছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["my car", "the house", "my hair"],
        },
        {
          name: "PP",
          description: "The past participle of the action done",
          description_bn: "যে কাজটি করা হয়েছে তার অতীত কৃদন্ত",
          acceptedTypes: ["past_participle"],
          examples: ["repaired", "painted", "cut"],
        },
      ],
      examples: [
        {
          en: "I had my car repaired.",
          bn: "আমি আমার গাড়ি মেরামত করিয়েছি।",
          slotValues: { THING: "my car", PP: "repaired" },
          topicArea: "daily_life",
        },
        {
          en: "I had the house painted.",
          bn: "আমি বাড়ি রং করিয়েছি।",
          slotValues: { THING: "the house", PP: "painted" },
          topicArea: "daily_life",
        },
        {
          en: "I had my hair cut.",
          bn: "আমি আমার চুল কাটিয়েছি।",
          slotValues: { THING: "my hair", PP: "cut" },
          topicArea: "daily_life",
        },
        {
          en: "I had my phone screen replaced.",
          bn: "আমি আমার ফোনের স্ক্রিন বদলিয়েছি।",
          slotValues: { THING: "my phone screen", PP: "replaced" },
          topicArea: "daily_life",
        },
        {
          en: "I had my suit dry-cleaned.",
          bn: "আমি আমার স্যুট ড্রাই-ক্লিন করিয়েছি।",
          slotValues: { THING: "my suit", PP: "dry-cleaned" },
          topicArea: "daily_life",
        },
        {
          en: "I had the documents notarized.",
          bn: "আমি কাগজপত্র নোটারি করিয়েছি।",
          slotValues: { THING: "the documents", PP: "notarized" },
          topicArea: "work",
        },
        {
          en: "I had the fence fixed.",
          bn: "আমি বেড়া ঠিক করিয়েছি।",
          slotValues: { THING: "the fence", PP: "fixed" },
          topicArea: "daily_life",
        },
        {
          en: "I had my blood pressure checked.",
          bn: "আমি আমার রক্তচাপ পরীক্ষা করিয়েছি।",
          slotValues: { THING: "my blood pressure", PP: "checked" },
          topicArea: "health",
        },
        {
          en: "I had the windows cleaned.",
          bn: "আমি জানালা পরিষ্কার করিয়েছি।",
          slotValues: { THING: "the windows", PP: "cleaned" },
          topicArea: "daily_life",
        },
        {
          en: "I had my passport renewed.",
          bn: "আমি আমার পাসপোর্ট নবায়ন করিয়েছি।",
          slotValues: { THING: "my passport", PP: "renewed" },
          topicArea: "travel",
        },
        {
          en: "I had the report proofread.",
          bn: "আমি রিপোর্ট প্রুফরিড করিয়েছি।",
          slotValues: { THING: "the report", PP: "proofread" },
          topicArea: "work",
        },
        {
          en: "I had the dress altered.",
          bn: "আমি পোশাক পরিবর্তন করিয়েছি।",
          slotValues: { THING: "the dress", PP: "altered" },
          topicArea: "shopping",
        },
        {
          en: "I had my teeth whitened.",
          bn: "আমি আমার দাঁত সাদা করিয়েছি।",
          slotValues: { THING: "my teeth", PP: "whitened" },
          topicArea: "health",
        },
        {
          en: "I had the air conditioner serviced.",
          bn: "আমি এয়ার কন্ডিশনার সার্ভিস করিয়েছি।",
          slotValues: { THING: "the air conditioner", PP: "serviced" },
          topicArea: "daily_life",
        },
        {
          en: "I had my vision tested.",
          bn: "আমি আমার দৃষ্টি পরীক্ষা করিয়েছি।",
          slotValues: { THING: "my vision", PP: "tested" },
          topicArea: "health",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
    },
    {
      id: "S18.2",
      formula: "I need to get [THING] [PP]",
      formula_bn: "আমাকে [বস্তু] [পিপি] করাতে হবে",
      patternName: "Need To Get + Object + Past Participle",
      patternName_bn: "করাতে হবে + কর্ম + অতীত কৃদন্ত",
      slots: [
        {
          name: "THING",
          description: "The thing that needs to be done",
          description_bn: "যে জিনিসটি করাতে হবে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["my car", "this document", "my eyes"],
        },
        {
          name: "PP",
          description: "The action that needs to be done",
          description_bn: "যে কাজটি করা দরকার",
          acceptedTypes: ["past_participle"],
          examples: ["serviced", "translated", "checked"],
        },
      ],
      examples: [
        {
          en: "I need to get my car serviced.",
          bn: "আমাকে আমার গাড়ি সার্ভিস করাতে হবে।",
          slotValues: { THING: "my car", PP: "serviced" },
          topicArea: "daily_life",
        },
        {
          en: "I need to get this document translated.",
          bn: "আমাকে এই কাগজটি অনুবাদ করাতে হবে।",
          slotValues: { THING: "this document", PP: "translated" },
          topicArea: "work",
        },
        {
          en: "I need to get my eyes checked.",
          bn: "আমাকে আমার চোখ পরীক্ষা করাতে হবে।",
          slotValues: { THING: "my eyes", PP: "checked" },
          topicArea: "health",
        },
        {
          en: "I need to get the roof repaired.",
          bn: "আমাকে ছাদ মেরামত করাতে হবে।",
          slotValues: { THING: "the roof", PP: "repaired" },
          topicArea: "daily_life",
        },
        {
          en: "I need to get my laptop fixed.",
          bn: "আমাকে আমার ল্যাপটপ ঠিক করাতে হবে।",
          slotValues: { THING: "my laptop", PP: "fixed" },
          topicArea: "work",
        },
        {
          en: "I need to get the garden cleaned up.",
          bn: "আমাকে বাগান পরিষ্কার করাতে হবে।",
          slotValues: { THING: "the garden", PP: "cleaned up" },
          topicArea: "daily_life",
        },
        {
          en: "I need to get my suit pressed.",
          bn: "আমাকে আমার স্যুট ইস্ত্রি করাতে হবে।",
          slotValues: { THING: "my suit", PP: "pressed" },
          topicArea: "daily_life",
        },
        {
          en: "I need to get the contract reviewed.",
          bn: "আমাকে চুক্তি পর্যালোচনা করাতে হবে।",
          slotValues: { THING: "the contract", PP: "reviewed" },
          topicArea: "work",
        },
        {
          en: "I need to get my blood work done.",
          bn: "আমাকে আমার রক্ত পরীক্ষা করাতে হবে।",
          slotValues: { THING: "my blood work", PP: "done" },
          topicArea: "health",
        },
        {
          en: "I need to get my nails done.",
          bn: "আমাকে আমার নখ করাতে হবে।",
          slotValues: { THING: "my nails", PP: "done" },
          topicArea: "daily_life",
        },
        {
          en: "I need to get the locks changed.",
          bn: "আমাকে তালা বদলাতে হবে।",
          slotValues: { THING: "the locks", PP: "changed" },
          topicArea: "daily_life",
        },
        {
          en: "I need to get my visa extended.",
          bn: "আমাকে আমার ভিসা বাড়াতে হবে।",
          slotValues: { THING: "my visa", PP: "extended" },
          topicArea: "travel",
        },
        {
          en: "I need to get these photos printed.",
          bn: "আমাকে এই ছবিগুলো প্রিন্ট করাতে হবে।",
          slotValues: { THING: "these photos", PP: "printed" },
          topicArea: "daily_life",
        },
        {
          en: "I need to get the plumbing fixed.",
          bn: "আমাকে প্লাম্বিং ঠিক করাতে হবে।",
          slotValues: { THING: "the plumbing", PP: "fixed" },
          topicArea: "daily_life",
        },
        {
          en: "I need to get my prescription filled.",
          bn: "আমাকে আমার প্রেসক্রিপশন অনুযায়ী ওষুধ আনাতে হবে।",
          slotValues: { THING: "my prescription", PP: "filled" },
          topicArea: "health",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
    },
    {
      id: "S18.3",
      formula: "Where can I get [THING] [PP]?",
      formula_bn: "আমি কোথায় [বস্তু] [পিপি] করাতে পারি?",
      patternName: "Where Can I Get + Object + PP (Service Question)",
      patternName_bn: "কোথায় করাতে পারি + কর্ম + পিপি (সেবা প্রশ্ন)",
      slots: [
        {
          name: "THING",
          description: "The thing you need serviced",
          description_bn: "যে জিনিসটি আপনি সেবা করাতে চান",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["my shoes", "this shirt", "my watch"],
        },
        {
          name: "PP",
          description: "The service needed",
          description_bn: "যে সেবা প্রয়োজন",
          acceptedTypes: ["past_participle"],
          examples: ["repaired", "dry-cleaned", "fixed"],
        },
      ],
      examples: [
        {
          en: "Where can I get my shoes repaired?",
          bn: "আমি কোথায় আমার জুতা মেরামত করাতে পারি?",
          slotValues: { THING: "my shoes", PP: "repaired" },
          topicArea: "shopping",
        },
        {
          en: "Where can I get this shirt dry-cleaned?",
          bn: "আমি কোথায় এই শার্ট ড্রাই-ক্লিন করাতে পারি?",
          slotValues: { THING: "this shirt", PP: "dry-cleaned" },
          topicArea: "daily_life",
        },
        {
          en: "Where can I get my watch fixed?",
          bn: "আমি কোথায় আমার ঘড়ি ঠিক করাতে পারি?",
          slotValues: { THING: "my watch", PP: "fixed" },
          topicArea: "shopping",
        },
        {
          en: "Where can I get my hair done?",
          bn: "আমি কোথায় আমার চুল করাতে পারি?",
          slotValues: { THING: "my hair", PP: "done" },
          topicArea: "daily_life",
        },
        {
          en: "Where can I get my clothes tailored?",
          bn: "আমি কোথায় আমার কাপড় সেলাই করাতে পারি?",
          slotValues: { THING: "my clothes", PP: "tailored" },
          topicArea: "shopping",
        },
        {
          en: "Where can I get these keys copied?",
          bn: "আমি কোথায় এই চাবি কপি করাতে পারি?",
          slotValues: { THING: "these keys", PP: "copied" },
          topicArea: "daily_life",
        },
        {
          en: "Where can I get my phone unlocked?",
          bn: "আমি কোথায় আমার ফোন আনলক করাতে পারি?",
          slotValues: { THING: "my phone", PP: "unlocked" },
          topicArea: "daily_life",
        },
        {
          en: "Where can I get my car washed?",
          bn: "আমি কোথায় আমার গাড়ি ধোয়াতে পারি?",
          slotValues: { THING: "my car", PP: "washed" },
          topicArea: "daily_life",
        },
        {
          en: "Where can I get my passport photos taken?",
          bn: "আমি কোথায় পাসপোর্ট ছবি তুলতে পারি?",
          slotValues: { THING: "my passport photos", PP: "taken" },
          topicArea: "travel",
        },
        {
          en: "Where can I get this document certified?",
          bn: "আমি কোথায় এই কাগজ সত্যায়িত করাতে পারি?",
          slotValues: { THING: "this document", PP: "certified" },
          topicArea: "work",
        },
        {
          en: "Where can I get my bicycle repaired?",
          bn: "আমি কোথায় আমার সাইকেল মেরামত করাতে পারি?",
          slotValues: { THING: "my bicycle", PP: "repaired" },
          topicArea: "travel",
        },
        {
          en: "Where can I get my ring resized?",
          bn: "আমি কোথায় আমার আংটির সাইজ ঠিক করাতে পারি?",
          slotValues: { THING: "my ring", PP: "resized" },
          topicArea: "shopping",
        },
        {
          en: "Where can I get my laptop screen replaced?",
          bn: "আমি কোথায় আমার ল্যাপটপের স্ক্রিন বদলাতে পারি?",
          slotValues: { THING: "my laptop screen", PP: "replaced" },
          topicArea: "work",
        },
        {
          en: "Where can I get my teeth cleaned?",
          bn: "আমি কোথায় আমার দাঁত পরিষ্কার করাতে পারি?",
          slotValues: { THING: "my teeth", PP: "cleaned" },
          topicArea: "health",
        },
        {
          en: "Where can I get my furniture delivered?",
          bn: "আমি কোথায় আমার আসবাবপত্র ডেলিভারি করাতে পারি?",
          slotValues: { THING: "my furniture", PP: "delivered" },
          topicArea: "shopping",
        },
      ],
      formality: "polite",
      difficulty: "advanced",
    },
    {
      id: "S18.4",
      formula: "I'm having [THING] [PP]",
      formula_bn: "আমি [বস্তু] [পিপি] করাচ্ছি",
      patternName: "Having + Object + PP (In Progress)",
      patternName_bn: "করাচ্ছি + কর্ম + পিপি (চলমান)",
      slots: [
        {
          name: "THING",
          description: "The thing currently being done",
          description_bn: "যে জিনিসটি বর্তমানে করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["my kitchen", "the roof", "my portrait"],
        },
        {
          name: "PP",
          description: "The action being done",
          description_bn: "যে কাজটি করা হচ্ছে",
          acceptedTypes: ["past_participle"],
          examples: ["renovated", "repaired", "painted"],
        },
      ],
      examples: [
        {
          en: "I'm having my kitchen renovated.",
          bn: "আমি আমার রান্নাঘর সংস্কার করাচ্ছি।",
          slotValues: { THING: "my kitchen", PP: "renovated" },
          topicArea: "daily_life",
        },
        {
          en: "I'm having the roof repaired.",
          bn: "আমি ছাদ মেরামত করাচ্ছি।",
          slotValues: { THING: "the roof", PP: "repaired" },
          topicArea: "daily_life",
        },
        {
          en: "I'm having my portrait painted.",
          bn: "আমি আমার প্রতিকৃতি আঁকাচ্ছি।",
          slotValues: { THING: "my portrait", PP: "painted" },
          topicArea: "entertainment",
        },
        {
          en: "I'm having my car inspected.",
          bn: "আমি আমার গাড়ি পরিদর্শন করাচ্ছি।",
          slotValues: { THING: "my car", PP: "inspected" },
          topicArea: "daily_life",
        },
        {
          en: "I'm having the bathroom remodeled.",
          bn: "আমি বাথরুম পুনর্নির্মাণ করাচ্ছি।",
          slotValues: { THING: "the bathroom", PP: "remodeled" },
          topicArea: "daily_life",
        },
        {
          en: "I'm having my suit tailored.",
          bn: "আমি আমার স্যুট সেলাই করাচ্ছি।",
          slotValues: { THING: "my suit", PP: "tailored" },
          topicArea: "shopping",
        },
        {
          en: "I'm having the garden landscaped.",
          bn: "আমি বাগান ল্যান্ডস্কেপ করাচ্ছি।",
          slotValues: { THING: "the garden", PP: "landscaped" },
          topicArea: "daily_life",
        },
        {
          en: "I'm having my website redesigned.",
          bn: "আমি আমার ওয়েবসাইট পুনরায় ডিজাইন করাচ্ছি।",
          slotValues: { THING: "my website", PP: "redesigned" },
          topicArea: "work",
        },
        {
          en: "I'm having my eyes tested tomorrow.",
          bn: "আমি আগামীকাল আমার চোখ পরীক্ষা করাচ্ছি।",
          slotValues: { THING: "my eyes", PP: "tested tomorrow" },
          topicArea: "health",
        },
        {
          en: "I'm having the floors polished.",
          bn: "আমি মেঝে পালিশ করাচ্ছি।",
          slotValues: { THING: "the floors", PP: "polished" },
          topicArea: "daily_life",
        },
        {
          en: "I'm having my wedding dress made.",
          bn: "আমি আমার বিয়ের পোশাক বানাচ্ছি।",
          slotValues: { THING: "my wedding dress", PP: "made" },
          topicArea: "relationships",
        },
        {
          en: "I'm having the office furniture replaced.",
          bn: "আমি অফিসের আসবাবপত্র বদলাচ্ছি।",
          slotValues: { THING: "the office furniture", PP: "replaced" },
          topicArea: "work",
        },
        {
          en: "I'm having my hair colored.",
          bn: "আমি আমার চুল রং করাচ্ছি।",
          slotValues: { THING: "my hair", PP: "colored" },
          topicArea: "daily_life",
        },
        {
          en: "I'm having the wiring checked.",
          bn: "আমি তারের সংযোগ পরীক্ষা করাচ্ছি।",
          slotValues: { THING: "the wiring", PP: "checked" },
          topicArea: "daily_life",
        },
        {
          en: "I'm having a new fence installed.",
          bn: "আমি একটি নতুন বেড়া লাগাচ্ছি।",
          slotValues: { THING: "a new fence", PP: "installed" },
          topicArea: "daily_life",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
    },
    {
      id: "S18.5",
      formula: "You should get [THING] [PP]",
      formula_bn: "তোমার [বস্তু] [পিপি] করানো উচিত",
      patternName: "Should Get + Object + PP (Advice)",
      patternName_bn: "করানো উচিত + কর্ম + পিপি (পরামর্শ)",
      slots: [
        {
          name: "THING",
          description: "The thing that should be done",
          description_bn: "যে জিনিসটি করানো উচিত",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["your car", "that mole", "the lock"],
        },
        {
          name: "PP",
          description: "The action that should be done",
          description_bn: "যে কাজটি করা উচিত",
          acceptedTypes: ["past_participle"],
          examples: ["checked", "examined", "replaced"],
        },
      ],
      examples: [
        {
          en: "You should get your car checked before the trip.",
          bn: "তোমার ট্রিপের আগে গাড়ি চেক করানো উচিত।",
          slotValues: { THING: "your car", PP: "checked before the trip" },
          topicArea: "travel",
        },
        {
          en: "You should get that mole examined.",
          bn: "তোমার ওই তিলটি পরীক্ষা করানো উচিত।",
          slotValues: { THING: "that mole", PP: "examined" },
          topicArea: "health",
        },
        {
          en: "You should get the lock replaced.",
          bn: "তোমার তালা বদলানো উচিত।",
          slotValues: { THING: "the lock", PP: "replaced" },
          topicArea: "daily_life",
        },
        {
          en: "You should get your teeth cleaned regularly.",
          bn: "তোমার নিয়মিত দাঁত পরিষ্কার করানো উচিত।",
          slotValues: { THING: "your teeth", PP: "cleaned regularly" },
          topicArea: "health",
        },
        {
          en: "You should get the brakes inspected.",
          bn: "তোমার ব্রেক পরীক্ষা করানো উচিত।",
          slotValues: { THING: "the brakes", PP: "inspected" },
          topicArea: "travel",
        },
        {
          en: "You should get your hair trimmed.",
          bn: "তোমার চুল ছেঁটে নেওয়া উচিত।",
          slotValues: { THING: "your hair", PP: "trimmed" },
          topicArea: "daily_life",
        },
        {
          en: "You should get that stain removed.",
          bn: "তোমার ওই দাগ মুছে ফেলানো উচিত।",
          slotValues: { THING: "that stain", PP: "removed" },
          topicArea: "daily_life",
        },
        {
          en: "You should get the pipes fixed before winter.",
          bn: "তোমার শীতের আগে পাইপ ঠিক করানো উচিত।",
          slotValues: { THING: "the pipes", PP: "fixed before winter" },
          topicArea: "daily_life",
        },
        {
          en: "You should get your blood pressure monitored.",
          bn: "তোমার রক্তচাপ পর্যবেক্ষণ করানো উচিত।",
          slotValues: { THING: "your blood pressure", PP: "monitored" },
          topicArea: "health",
        },
        {
          en: "You should get the software updated.",
          bn: "তোমার সফটওয়্যার আপডেট করানো উচিত।",
          slotValues: { THING: "the software", PP: "updated" },
          topicArea: "work",
        },
        {
          en: "You should get your resume reviewed.",
          bn: "তোমার জীবনবৃত্তান্ত পর্যালোচনা করানো উচিত।",
          slotValues: { THING: "your resume", PP: "reviewed" },
          topicArea: "work",
        },
        {
          en: "You should get the air quality tested.",
          bn: "তোমার বায়ুর মান পরীক্ষা করানো উচিত।",
          slotValues: { THING: "the air quality", PP: "tested" },
          topicArea: "health",
        },
        {
          en: "You should get your tires rotated.",
          bn: "তোমার টায়ার ঘুরিয়ে লাগানো উচিত।",
          slotValues: { THING: "your tires", PP: "rotated" },
          topicArea: "daily_life",
        },
        {
          en: "You should get the contract signed.",
          bn: "তোমার চুক্তি স্বাক্ষর করানো উচিত।",
          slotValues: { THING: "the contract", PP: "signed" },
          topicArea: "work",
        },
        {
          en: "You should get your vaccinations done.",
          bn: "তোমার টিকা দেওয়া উচিত।",
          slotValues: { THING: "your vaccinations", PP: "done" },
          topicArea: "health",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
    },
  ],
};
