import { PatternCategory } from "@/types/pattern";

export const categoryS4: PatternCategory = {
  id: "S4",
  slug: "gerund-as-subject",
  name: "Gerund as Subject",
  name_bn: "কর্তা হিসেবে জেরান্ড",
  description: "Use -ing forms as the subject of a sentence",
  description_bn: "বাক্যের কর্তা হিসেবে -ing রূপ ব্যবহার করুন",
  icon: "🎯",
  group: "S",
  groupName: "Advanced Structural Patterns",
  groupName_bn: "উন্নত গঠনমূলক প্যাটার্ন",
  difficulty: "advanced",
  patterns: [
    {
      id: "S4.1",
      formula: "[DOING] is [ADJECTIVE]",
      formula_bn: "[করা] [বিশেষণ]",
      patternName: "Gerund + is + Adjective",
      patternName_bn: "জেরান্ড + হওয়া + বিশেষণ",
      slots: [
        {
          name: "DOING",
          description: "An activity in -ing form",
          description_bn: "-ing রূপে একটি কাজ",
          acceptedTypes: ["gerund", "verb_phrase"],
          examples: ["Swimming", "Learning new things", "Traveling alone"],
        },
        {
          name: "ADJECTIVE",
          description: "A quality or characteristic",
          description_bn: "একটি গুণ বা বৈশিষ্ট্য",
          acceptedTypes: ["adjective", "adjective_phrase"],
          examples: ["fun", "challenging", "rewarding"],
        },
      ],
      examples: [
        { en: "Swimming is excellent exercise.", bn: "সাঁতার কাটা চমৎকার ব্যায়াম।", slotValues: { DOING: "Swimming", ADJECTIVE: "excellent exercise" } },
        { en: "Learning new things is exciting.", bn: "নতুন জিনিস শেখা উত্তেজনাপূর্ণ।", slotValues: { DOING: "Learning new things", ADJECTIVE: "exciting" } },
        { en: "Traveling alone is liberating.", bn: "একা ভ্রমণ করা মুক্তিদায়ক।", slotValues: { DOING: "Traveling alone", ADJECTIVE: "liberating" } },
        { en: "Cooking at home is healthier.", bn: "বাড়িতে রান্না করা স্বাস্থ্যকর।", slotValues: { DOING: "Cooking at home", ADJECTIVE: "healthier" } },
        { en: "Reading before bed is relaxing.", bn: "ঘুমানোর আগে পড়া আরামদায়ক।", slotValues: { DOING: "Reading before bed", ADJECTIVE: "relaxing" } },
        { en: "Running in the morning is refreshing.", bn: "সকালে দৌড়ানো সতেজকারী।", slotValues: { DOING: "Running in the morning", ADJECTIVE: "refreshing" } },
        { en: "Working from home is convenient.", bn: "বাড়ি থেকে কাজ করা সুবিধাজনক।", slotValues: { DOING: "Working from home", ADJECTIVE: "convenient" } },
        { en: "Speaking in public is nerve-wracking.", bn: "জনসম্মুখে বক্তৃতা দেওয়া স্নায়ু-চাপকর।", slotValues: { DOING: "Speaking in public", ADJECTIVE: "nerve-wracking" } },
        { en: "Playing chess is intellectually stimulating.", bn: "দাবা খেলা বুদ্ধিবৃত্তিকভাবে উদ্দীপক।", slotValues: { DOING: "Playing chess", ADJECTIVE: "intellectually stimulating" } },
        { en: "Volunteering is deeply fulfilling.", bn: "স্বেচ্ছাসেবা গভীরভাবে পরিতৃপ্তিদায়ক।", slotValues: { DOING: "Volunteering", ADJECTIVE: "deeply fulfilling" } },
        { en: "Gardening is therapeutic.", bn: "বাগান করা থেরাপিউটিক।", slotValues: { DOING: "Gardening", ADJECTIVE: "therapeutic" } },
        { en: "Learning a language is time-consuming.", bn: "একটি ভাষা শেখা সময়সাপেক্ষ।", slotValues: { DOING: "Learning a language", ADJECTIVE: "time-consuming" } },
        { en: "Meditating daily is beneficial.", bn: "প্রতিদিন ধ্যান করা উপকারী।", slotValues: { DOING: "Meditating daily", ADJECTIVE: "beneficial" } },
        { en: "Driving in heavy rain is dangerous.", bn: "ভারী বৃষ্টিতে গাড়ি চালানো বিপজ্জনক।", slotValues: { DOING: "Driving in heavy rain", ADJECTIVE: "dangerous" } },
        { en: "Painting is a wonderful hobby.", bn: "ছবি আঁকা একটি চমৎকার শখ।", slotValues: { DOING: "Painting", ADJECTIVE: "a wonderful hobby" } },
      ],
      formality: "polite",
      difficulty: "advanced",
    },
    {
      id: "S4.2",
      formula: "[DOING] takes [TIME/EFFORT]",
      formula_bn: "[করতে] [সময়/প্রচেষ্টা] লাগে",
      patternName: "Gerund + takes + Time/Effort",
      patternName_bn: "জেরান্ড + লাগে + সময়/প্রচেষ্টা",
      slots: [
        {
          name: "DOING",
          description: "An activity in -ing form",
          description_bn: "-ing রূপে একটি কাজ",
          acceptedTypes: ["gerund", "verb_phrase"],
          examples: ["Building a house", "Learning to code", "Mastering a skill"],
        },
        {
          name: "TIME/EFFORT",
          description: "Amount of time or effort required",
          description_bn: "প্রয়োজনীয় সময় বা প্রচেষ্টার পরিমাণ",
          acceptedTypes: ["noun_phrase", "time_expression"],
          examples: ["a lot of time", "years of practice", "tremendous effort"],
        },
      ],
      examples: [
        { en: "Building a house takes months of planning.", bn: "একটি বাড়ি তৈরি করতে মাসের পর মাস পরিকল্পনা লাগে।", slotValues: { DOING: "Building a house", "TIME/EFFORT": "months of planning" } },
        { en: "Learning to code takes a lot of patience.", bn: "কোড শিখতে অনেক ধৈর্য লাগে।", slotValues: { DOING: "Learning to code", "TIME/EFFORT": "a lot of patience" } },
        { en: "Mastering a musical instrument takes years of practice.", bn: "একটি বাদ্যযন্ত্র আয়ত্ত করতে বছরের পর বছর অনুশীলন লাগে।", slotValues: { DOING: "Mastering a musical instrument", "TIME/EFFORT": "years of practice" } },
        { en: "Writing a novel takes tremendous dedication.", bn: "একটি উপন্যাস লিখতে প্রচণ্ড নিষ্ঠা লাগে।", slotValues: { DOING: "Writing a novel", "TIME/EFFORT": "tremendous dedication" } },
        { en: "Recovering from surgery takes several weeks.", bn: "অস্ত্রোপচার থেকে সুস্থ হতে কয়েক সপ্তাহ লাগে।", slotValues: { DOING: "Recovering from surgery", "TIME/EFFORT": "several weeks" } },
        { en: "Preparing for the exam takes at least a month.", bn: "পরীক্ষার প্রস্তুতি নিতে কমপক্ষে এক মাস লাগে।", slotValues: { DOING: "Preparing for the exam", "TIME/EFFORT": "at least a month" } },
        { en: "Running a business takes enormous energy.", bn: "একটি ব্যবসা চালাতে বিশাল শক্তি লাগে।", slotValues: { DOING: "Running a business", "TIME/EFFORT": "enormous energy" } },
        { en: "Raising children takes unconditional love.", bn: "সন্তান লালন-পালন করতে নিঃশর্ত ভালোবাসা লাগে।", slotValues: { DOING: "Raising children", "TIME/EFFORT": "unconditional love" } },
        { en: "Getting a visa takes about two months.", bn: "ভিসা পেতে প্রায় দুই মাস লাগে।", slotValues: { DOING: "Getting a visa", "TIME/EFFORT": "about two months" } },
        { en: "Becoming a doctor takes many years of study.", bn: "ডাক্তার হতে বহু বছর পড়াশোনা লাগে।", slotValues: { DOING: "Becoming a doctor", "TIME/EFFORT": "many years of study" } },
        { en: "Losing weight takes consistent effort.", bn: "ওজন কমাতে ধারাবাহিক প্রচেষ্টা লাগে।", slotValues: { DOING: "Losing weight", "TIME/EFFORT": "consistent effort" } },
        { en: "Moving to a new country takes a lot of courage.", bn: "একটি নতুন দেশে যেতে অনেক সাহস লাগে।", slotValues: { DOING: "Moving to a new country", "TIME/EFFORT": "a lot of courage" } },
        { en: "Organizing a wedding takes months of preparation.", bn: "একটি বিয়ে আয়োজন করতে মাসের পর মাস প্রস্তুতি লাগে।", slotValues: { DOING: "Organizing a wedding", "TIME/EFFORT": "months of preparation" } },
        { en: "Learning to drive takes proper training.", bn: "গাড়ি চালানো শিখতে সঠিক প্রশিক্ষণ লাগে।", slotValues: { DOING: "Learning to drive", "TIME/EFFORT": "proper training" } },
        { en: "Building trust takes a long time.", bn: "বিশ্বাস তৈরি করতে দীর্ঘ সময় লাগে।", slotValues: { DOING: "Building trust", "TIME/EFFORT": "a long time" } },
      ],
      formality: "polite",
      difficulty: "advanced",
    },
    {
      id: "S4.3",
      formula: "[DOING] can help [PERSON] [ACTION]",
      formula_bn: "[করা] [ব্যক্তিকে] [কাজ] করতে সাহায্য করতে পারে",
      patternName: "Gerund + can help",
      patternName_bn: "জেরান্ড + সাহায্য করতে পারে",
      slots: [
        {
          name: "DOING",
          description: "An activity in -ing form",
          description_bn: "-ing রূপে একটি কাজ",
          acceptedTypes: ["gerund", "verb_phrase"],
          examples: ["Exercising regularly", "Reading daily", "Eating well"],
        },
        {
          name: "PERSON",
          description: "Who benefits",
          description_bn: "কে উপকৃত হয়",
          acceptedTypes: ["person", "noun_phrase"],
          examples: ["you", "children", "students"],
        },
        {
          name: "ACTION",
          description: "The benefit or result",
          description_bn: "সুবিধা বা ফলাফল",
          acceptedTypes: ["verb_phrase"],
          examples: ["stay healthy", "improve their vocabulary", "feel better"],
        },
      ],
      examples: [
        { en: "Exercising regularly can help you stay healthy.", bn: "নিয়মিত ব্যায়াম করা আপনাকে সুস্থ থাকতে সাহায্য করতে পারে।", slotValues: { DOING: "Exercising regularly", PERSON: "you", ACTION: "stay healthy" } },
        { en: "Reading daily can help children improve their vocabulary.", bn: "প্রতিদিন পড়া শিশুদের শব্দভাণ্ডার উন্নত করতে সাহায্য করতে পারে।", slotValues: { DOING: "Reading daily", PERSON: "children", ACTION: "improve their vocabulary" } },
        { en: "Eating well can help you feel more energetic.", bn: "ভালো খাওয়া আপনাকে আরও শক্তিশালী অনুভব করতে সাহায্য করতে পারে।", slotValues: { DOING: "Eating well", PERSON: "you", ACTION: "feel more energetic" } },
        { en: "Meditating can help people reduce stress.", bn: "ধ্যান করা মানুষকে মানসিক চাপ কমাতে সাহায্য করতে পারে।", slotValues: { DOING: "Meditating", PERSON: "people", ACTION: "reduce stress" } },
        { en: "Writing a journal can help you organize your thoughts.", bn: "জার্নাল লেখা আপনাকে চিন্তা গুছিয়ে নিতে সাহায্য করতে পারে।", slotValues: { DOING: "Writing a journal", PERSON: "you", ACTION: "organize your thoughts" } },
        { en: "Practicing English daily can help students pass the exam.", bn: "প্রতিদিন ইংরেজি অনুশীলন করা ছাত্রদের পরীক্ষায় পাস করতে সাহায্য করতে পারে।", slotValues: { DOING: "Practicing English daily", PERSON: "students", ACTION: "pass the exam" } },
        { en: "Getting enough sleep can help you think clearly.", bn: "পর্যাপ্ত ঘুমানো আপনাকে পরিষ্কারভাবে চিন্তা করতে সাহায্য করতে পারে।", slotValues: { DOING: "Getting enough sleep", PERSON: "you", ACTION: "think clearly" } },
        { en: "Drinking green tea can help people lose weight.", bn: "গ্রিন টি পান করা মানুষকে ওজন কমাতে সাহায্য করতে পারে।", slotValues: { DOING: "Drinking green tea", PERSON: "people", ACTION: "lose weight" } },
        { en: "Taking breaks can help employees be more productive.", bn: "বিরতি নেওয়া কর্মচারীদের আরও উৎপাদনশীল হতে সাহায্য করতে পারে।", slotValues: { DOING: "Taking breaks", PERSON: "employees", ACTION: "be more productive" } },
        { en: "Traveling can help you broaden your perspective.", bn: "ভ্রমণ করা আপনার দৃষ্টিভঙ্গি বিস্তৃত করতে সাহায্য করতে পারে।", slotValues: { DOING: "Traveling", PERSON: "you", ACTION: "broaden your perspective" } },
        { en: "Listening to podcasts can help learners improve their listening skills.", bn: "পডকাস্ট শোনা শিক্ষার্থীদের শ্রবণ দক্ষতা উন্নত করতে সাহায্য করতে পারে।", slotValues: { DOING: "Listening to podcasts", PERSON: "learners", ACTION: "improve their listening skills" } },
        { en: "Saving money can help families prepare for emergencies.", bn: "টাকা সঞ্চয় করা পরিবারগুলোকে জরুরি অবস্থার জন্য প্রস্তুতি নিতে সাহায্য করতে পারে।", slotValues: { DOING: "Saving money", PERSON: "families", ACTION: "prepare for emergencies" } },
        { en: "Stretching can help athletes avoid injuries.", bn: "স্ট্রেচিং করা ক্রীড়াবিদদের আঘাত এড়াতে সাহায্য করতে পারে।", slotValues: { DOING: "Stretching", PERSON: "athletes", ACTION: "avoid injuries" } },
        { en: "Planning ahead can help you manage your time better.", bn: "আগে থেকে পরিকল্পনা করা আপনাকে সময় ভালোভাবে পরিচালনা করতে সাহায্য করতে পারে।", slotValues: { DOING: "Planning ahead", PERSON: "you", ACTION: "manage your time better" } },
        { en: "Talking to friends can help you feel less lonely.", bn: "বন্ধুদের সাথে কথা বলা আপনাকে কম একাকী অনুভব করতে সাহায্য করতে পারে।", slotValues: { DOING: "Talking to friends", PERSON: "you", ACTION: "feel less lonely" } },
      ],
      formality: "polite",
      difficulty: "advanced",
    },
    {
      id: "S4.4",
      formula: "[DOING] makes me [ADJECTIVE]",
      formula_bn: "[করা] আমাকে [বিশেষণ] করে",
      patternName: "Gerund + makes me + Adjective",
      patternName_bn: "জেরান্ড + আমাকে করে + বিশেষণ",
      slots: [
        {
          name: "DOING",
          description: "An activity in -ing form",
          description_bn: "-ing রূপে একটি কাজ",
          acceptedTypes: ["gerund", "verb_phrase"],
          examples: ["Listening to music", "Studying all night", "Helping others"],
        },
        {
          name: "ADJECTIVE",
          description: "A feeling or state",
          description_bn: "একটি অনুভূতি বা অবস্থা",
          acceptedTypes: ["adjective", "adjective_phrase"],
          examples: ["happy", "tired", "proud"],
        },
      ],
      examples: [
        { en: "Listening to music makes me happy.", bn: "গান শোনা আমাকে সুখী করে।", slotValues: { DOING: "Listening to music", ADJECTIVE: "happy" } },
        { en: "Studying all night makes me exhausted.", bn: "সারারাত পড়া আমাকে ক্লান্ত করে।", slotValues: { DOING: "Studying all night", ADJECTIVE: "exhausted" } },
        { en: "Helping others makes me feel fulfilled.", bn: "অন্যদের সাহায্য করা আমাকে পরিতৃপ্ত অনুভব করায়।", slotValues: { DOING: "Helping others", ADJECTIVE: "feel fulfilled" } },
        { en: "Waking up early makes me more productive.", bn: "ভোরে ওঠা আমাকে আরও উৎপাদনশীল করে।", slotValues: { DOING: "Waking up early", ADJECTIVE: "more productive" } },
        { en: "Watching horror movies makes me nervous.", bn: "হরর সিনেমা দেখা আমাকে নার্ভাস করে।", slotValues: { DOING: "Watching horror movies", ADJECTIVE: "nervous" } },
        { en: "Walking in the rain makes me feel alive.", bn: "বৃষ্টিতে হাঁটা আমাকে জীবন্ত অনুভব করায়।", slotValues: { DOING: "Walking in the rain", ADJECTIVE: "feel alive" } },
        { en: "Working under pressure makes me anxious.", bn: "চাপের মধ্যে কাজ করা আমাকে উদ্বিগ্ন করে।", slotValues: { DOING: "Working under pressure", ADJECTIVE: "anxious" } },
        { en: "Spending time with family makes me grateful.", bn: "পরিবারের সাথে সময় কাটানো আমাকে কৃতজ্ঞ করে।", slotValues: { DOING: "Spending time with family", ADJECTIVE: "grateful" } },
        { en: "Cooking for friends makes me joyful.", bn: "বন্ধুদের জন্য রান্না করা আমাকে আনন্দিত করে।", slotValues: { DOING: "Cooking for friends", ADJECTIVE: "joyful" } },
        { en: "Sitting in traffic makes me frustrated.", bn: "যানজটে বসে থাকা আমাকে হতাশ করে।", slotValues: { DOING: "Sitting in traffic", ADJECTIVE: "frustrated" } },
        { en: "Traveling to new places makes me curious.", bn: "নতুন জায়গায় ভ্রমণ করা আমাকে কৌতূহলী করে।", slotValues: { DOING: "Traveling to new places", ADJECTIVE: "curious" } },
        { en: "Playing with my children makes me feel young.", bn: "আমার বাচ্চাদের সাথে খেলা আমাকে তরুণ অনুভব করায়।", slotValues: { DOING: "Playing with my children", ADJECTIVE: "feel young" } },
        { en: "Missing a deadline makes me stressed.", bn: "ডেডলাইন মিস করা আমাকে চাপে ফেলে।", slotValues: { DOING: "Missing a deadline", ADJECTIVE: "stressed" } },
        { en: "Learning something new makes me confident.", bn: "নতুন কিছু শেখা আমাকে আত্মবিশ্বাসী করে।", slotValues: { DOING: "Learning something new", ADJECTIVE: "confident" } },
        { en: "Being alone sometimes makes me thoughtful.", bn: "কখনো কখনো একা থাকা আমাকে চিন্তাশীল করে।", slotValues: { DOING: "Being alone sometimes", ADJECTIVE: "thoughtful" } },
      ],
      formality: "casual",
      difficulty: "advanced",
    },
    {
      id: "S4.5",
      formula: "[DOING] requires [THING]",
      formula_bn: "[করতে] [বস্তু] প্রয়োজন",
      patternName: "Gerund + requires",
      patternName_bn: "জেরান্ড + প্রয়োজন",
      slots: [
        {
          name: "DOING",
          description: "An activity in -ing form",
          description_bn: "-ing রূপে একটি কাজ",
          acceptedTypes: ["gerund", "verb_phrase"],
          examples: ["Teaching", "Starting a business", "Learning to fly"],
        },
        {
          name: "THING",
          description: "What is required",
          description_bn: "কী প্রয়োজন",
          acceptedTypes: ["noun_phrase"],
          examples: ["patience", "a lot of capital", "extensive training"],
        },
      ],
      examples: [
        { en: "Teaching requires patience and creativity.", bn: "শিক্ষাদান করতে ধৈর্য এবং সৃজনশীলতা প্রয়োজন।", slotValues: { DOING: "Teaching", THING: "patience and creativity" } },
        { en: "Starting a business requires a lot of capital.", bn: "ব্যবসা শুরু করতে অনেক পুঁজি প্রয়োজন।", slotValues: { DOING: "Starting a business", THING: "a lot of capital" } },
        { en: "Learning to fly requires extensive training.", bn: "উড়তে শিখতে ব্যাপক প্রশিক্ষণ প্রয়োজন।", slotValues: { DOING: "Learning to fly", THING: "extensive training" } },
        { en: "Performing surgery requires steady hands.", bn: "অস্ত্রোপচার করতে স্থির হাত প্রয়োজন।", slotValues: { DOING: "Performing surgery", THING: "steady hands" } },
        { en: "Leading a team requires excellent communication skills.", bn: "একটি দল নেতৃত্ব দিতে চমৎকার যোগাযোগ দক্ষতা প্রয়োজন।", slotValues: { DOING: "Leading a team", THING: "excellent communication skills" } },
        { en: "Writing professionally requires constant practice.", bn: "পেশাদারভাবে লিখতে নিরন্তর অনুশীলন প্রয়োজন।", slotValues: { DOING: "Writing professionally", THING: "constant practice" } },
        { en: "Maintaining good health requires a balanced diet.", bn: "সুস্বাস্থ্য বজায় রাখতে সুষম খাদ্য প্রয়োজন।", slotValues: { DOING: "Maintaining good health", THING: "a balanced diet" } },
        { en: "Climbing Mount Everest requires physical and mental strength.", bn: "এভারেস্ট আরোহণ করতে শারীরিক ও মানসিক শক্তি প্রয়োজন।", slotValues: { DOING: "Climbing Mount Everest", THING: "physical and mental strength" } },
        { en: "Managing finances requires discipline.", bn: "অর্থ ব্যবস্থাপনা করতে শৃঙ্খলা প্রয়োজন।", slotValues: { DOING: "Managing finances", THING: "discipline" } },
        { en: "Developing software requires technical knowledge.", bn: "সফটওয়্যার তৈরি করতে প্রযুক্তিগত জ্ঞান প্রয়োজন।", slotValues: { DOING: "Developing software", THING: "technical knowledge" } },
        { en: "Raising a child requires endless love.", bn: "সন্তান বড় করতে অসীম ভালোবাসা প্রয়োজন।", slotValues: { DOING: "Raising a child", THING: "endless love" } },
        { en: "Playing professional sports requires natural talent and hard work.", bn: "পেশাদার খেলাধুলা করতে স্বাভাবিক প্রতিভা এবং কঠোর পরিশ্রম প্রয়োজন।", slotValues: { DOING: "Playing professional sports", THING: "natural talent and hard work" } },
        { en: "Negotiating a deal requires strong interpersonal skills.", bn: "একটি চুক্তি আলোচনা করতে শক্তিশালী আন্তঃব্যক্তিক দক্ষতা প্রয়োজন।", slotValues: { DOING: "Negotiating a deal", THING: "strong interpersonal skills" } },
        { en: "Recovering from an illness requires proper rest.", bn: "অসুস্থতা থেকে সুস্থ হতে সঠিক বিশ্রাম প্রয়োজন।", slotValues: { DOING: "Recovering from an illness", THING: "proper rest" } },
        { en: "Building a career requires long-term commitment.", bn: "ক্যারিয়ার গড়তে দীর্ঘমেয়াদী প্রতিশ্রুতি প্রয়োজন।", slotValues: { DOING: "Building a career", THING: "long-term commitment" } },
      ],
      formality: "polite",
      difficulty: "advanced",
    },
  ],
};
