import { PatternCategory } from "@/types/pattern";

export const categoryS5: PatternCategory = {
  id: "S5",
  slug: "ellipsis-substitution",
  name: "Ellipsis & Substitution",
  name_bn: "উপবৃত্তি ও প্রতিস্থাপন",
  description: "Avoid repetition using 'so', 'not', 'too', and 'neither'",
  description_bn: "'so', 'not', 'too', এবং 'neither' ব্যবহার করে পুনরাবৃত্তি এড়ান",
  icon: "✂️",
  group: "S",
  groupName: "Advanced Structural Patterns",
  groupName_bn: "উন্নত গঠনমূলক প্যাটার্ন",
  difficulty: "advanced",
  patterns: [
    {
      id: "S5.1",
      formula: "I think so / I hope so / I believe so",
      formula_bn: "আমি তাই মনে করি / আমি তাই আশা করি / আমি তাই বিশ্বাস করি",
      patternName: "Affirmative 'so' Substitution",
      patternName_bn: "ইতিবাচক 'so' প্রতিস্থাপন",
      slots: [],
      examples: [
        { en: "A: Will it rain today? B: I think so.", bn: "ক: আজ কি বৃষ্টি হবে? খ: আমি তাই মনে করি।", slotValues: {} },
        { en: "A: Is the store open? B: I believe so.", bn: "ক: দোকান কি খোলা? খ: আমি তাই বিশ্বাস করি।", slotValues: {} },
        { en: "A: Will she come to the party? B: I hope so.", bn: "ক: সে কি পার্টিতে আসবে? খ: আমি তাই আশা করি।", slotValues: {} },
        { en: "A: Is the meeting at 3 PM? B: I think so.", bn: "ক: মিটিং কি বিকাল ৩টায়? খ: আমি তাই মনে করি।", slotValues: {} },
        { en: "A: Can we finish by Friday? B: I hope so.", bn: "ক: আমরা কি শুক্রবারের মধ্যে শেষ করতে পারব? খ: আমি তাই আশা করি।", slotValues: {} },
        { en: "A: Will the price go down? B: I believe so.", bn: "ক: দাম কি কমবে? খ: আমি তাই বিশ্বাস করি।", slotValues: {} },
        { en: "A: Is this the right bus? B: I think so.", bn: "ক: এটা কি সঠিক বাস? খ: আমি তাই মনে করি।", slotValues: {} },
        { en: "A: Will the doctor see me today? B: I hope so.", bn: "ক: ডাক্তার কি আজ আমাকে দেখবেন? খ: আমি তাই আশা করি।", slotValues: {} },
        { en: "A: Has the package arrived? B: I believe so.", bn: "ক: পার্সেল কি এসেছে? খ: আমি তাই বিশ্বাস করি।", slotValues: {} },
        { en: "A: Will the weather clear up? B: I hope so.", bn: "ক: আবহাওয়া কি পরিষ্কার হবে? খ: আমি তাই আশা করি।", slotValues: {} },
        { en: "A: Are they hiring new people? B: I think so.", bn: "ক: তারা কি নতুন লোক নিয়োগ করছে? খ: আমি তাই মনে করি।", slotValues: {} },
        { en: "A: Did he pass the test? B: I believe so.", bn: "ক: সে কি পরীক্ষায় পাস করেছে? খ: আমি তাই বিশ্বাস করি।", slotValues: {} },
        { en: "A: Will they accept our offer? B: I hope so.", bn: "ক: তারা কি আমাদের প্রস্তাব গ্রহণ করবে? খ: আমি তাই আশা করি।", slotValues: {} },
        { en: "A: Is the restaurant still open? B: I think so.", bn: "ক: রেস্তোরাঁ কি এখনও খোলা? খ: আমি তাই মনে করি।", slotValues: {} },
        { en: "A: Will the project succeed? B: I certainly hope so.", bn: "ক: প্রকল্পটি কি সফল হবে? খ: আমি অবশ্যই তাই আশা করি।", slotValues: {} },
      ],
      formality: "casual",
      difficulty: "advanced",
    },
    {
      id: "S5.2",
      formula: "I don't think so / I hope not / I'm afraid not",
      formula_bn: "আমি তা মনে করি না / আমি আশা করি না / দুঃখিত, না",
      patternName: "Negative 'so/not' Substitution",
      patternName_bn: "নেতিবাচক 'so/not' প্রতিস্থাপন",
      slots: [],
      examples: [
        { en: "A: Will it snow tomorrow? B: I don't think so.", bn: "ক: আগামীকাল কি তুষারপাত হবে? খ: আমি তা মনে করি না।", slotValues: {} },
        { en: "A: Is she coming? B: I'm afraid not.", bn: "ক: সে কি আসছে? খ: দুঃখিত, না।", slotValues: {} },
        { en: "A: Will the train be late? B: I hope not.", bn: "ক: ট্রেন কি দেরি করবে? খ: আমি আশা করি না।", slotValues: {} },
        { en: "A: Can we get a refund? B: I don't think so.", bn: "ক: আমরা কি রিফান্ড পেতে পারি? খ: আমি তা মনে করি না।", slotValues: {} },
        { en: "A: Is there any chance of winning? B: I'm afraid not.", bn: "ক: জেতার কোনো সম্ভাবনা আছে? খ: দুঃখিত, না।", slotValues: {} },
        { en: "A: Will they cancel the event? B: I hope not.", bn: "ক: তারা কি অনুষ্ঠান বাতিল করবে? খ: আমি আশা করি না।", slotValues: {} },
        { en: "A: Is this going to be expensive? B: I hope not.", bn: "ক: এটা কি ব্যয়বহুল হবে? খ: আমি আশা করি না।", slotValues: {} },
        { en: "A: Did he get the job? B: I'm afraid not.", bn: "ক: সে কি চাকরি পেয়েছে? খ: দুঃখিত, না।", slotValues: {} },
        { en: "A: Will there be a traffic jam? B: I hope not.", bn: "ক: কি যানজট হবে? খ: আমি আশা করি না।", slotValues: {} },
        { en: "A: Is the pharmacy open on Sunday? B: I don't think so.", bn: "ক: রবিবারে কি ফার্মেসি খোলা থাকে? খ: আমি তা মনে করি না।", slotValues: {} },
        { en: "A: Can we still register? B: I'm afraid not.", bn: "ক: আমরা কি এখনও নিবন্ধন করতে পারি? খ: দুঃখিত, না।", slotValues: {} },
        { en: "A: Will the power go out again? B: I hope not.", bn: "ক: আবার কি বিদ্যুৎ যাবে? খ: আমি আশা করি না।", slotValues: {} },
        { en: "A: Is this seat taken? B: I don't think so.", bn: "ক: এই আসনটি কি নেওয়া? খ: আমি তা মনে করি না।", slotValues: {} },
        { en: "A: Will we have homework tonight? B: I hope not.", bn: "ক: আজ রাতে কি আমাদের হোমওয়ার্ক থাকবে? খ: আমি আশা করি না।", slotValues: {} },
        { en: "A: Are there any tickets left? B: I'm afraid not.", bn: "ক: কোনো টিকেট কি বাকি আছে? খ: দুঃখিত, না।", slotValues: {} },
      ],
      formality: "casual",
      difficulty: "advanced",
    },
    {
      id: "S5.3",
      formula: "So do I / So am I / So did I",
      formula_bn: "আমিও / আমিও তাই / আমিও করেছি",
      patternName: "Agreement with 'So'",
      patternName_bn: "'So' দিয়ে সম্মতি",
      slots: [],
      examples: [
        { en: "A: I love chocolate. B: So do I.", bn: "ক: আমি চকলেট ভালোবাসি। খ: আমিও।", slotValues: {} },
        { en: "A: I'm tired. B: So am I.", bn: "ক: আমি ক্লান্ত। খ: আমিও।", slotValues: {} },
        { en: "A: I went to the concert. B: So did I.", bn: "ক: আমি কনসার্টে গিয়েছিলাম। খ: আমিও।", slotValues: {} },
        { en: "A: I can speak French. B: So can I.", bn: "ক: আমি ফরাসি বলতে পারি। খ: আমিও পারি।", slotValues: {} },
        { en: "A: I have finished my work. B: So have I.", bn: "ক: আমি আমার কাজ শেষ করেছি। খ: আমিও করেছি।", slotValues: {} },
        { en: "A: I would like some tea. B: So would I.", bn: "ক: আমি কিছু চা চাই। খ: আমিও চাই।", slotValues: {} },
        { en: "A: She enjoys reading. B: So does he.", bn: "ক: সে পড়তে পছন্দ করে। খ: সেও পছন্দ করে।", slotValues: {} },
        { en: "A: We arrived early. B: So did they.", bn: "ক: আমরা তাড়াতাড়ি পৌঁছেছি। খ: তারাও।", slotValues: {} },
        { en: "A: I need a vacation. B: So do I.", bn: "ক: আমার ছুটি দরকার। খ: আমারও।", slotValues: {} },
        { en: "A: I was surprised. B: So was I.", bn: "ক: আমি অবাক হয়েছিলাম। খ: আমিও।", slotValues: {} },
        { en: "A: He will attend the meeting. B: So will she.", bn: "ক: সে মিটিংয়ে যোগ দেবে। খ: সেও দেবে।", slotValues: {} },
        { en: "A: I enjoy cooking. B: So does my wife.", bn: "ক: আমি রান্না উপভোগ করি। খ: আমার স্ত্রীও করে।", slotValues: {} },
        { en: "A: I had a wonderful time. B: So did we.", bn: "ক: আমি দারুণ সময় কাটিয়েছি। খ: আমরাও।", slotValues: {} },
        { en: "A: I should study more. B: So should I.", bn: "ক: আমার আরও পড়া উচিত। খ: আমারও উচিত।", slotValues: {} },
        { en: "A: I'm looking forward to the weekend. B: So am I.", bn: "ক: আমি সপ্তাহান্তের জন্য অপেক্ষা করছি। খ: আমিও।", slotValues: {} },
      ],
      formality: "casual",
      difficulty: "advanced",
    },
    {
      id: "S5.4",
      formula: "Neither do I / Neither am I / Neither did I",
      formula_bn: "আমিও না / আমিও তা নই / আমিও করিনি",
      patternName: "Agreement with 'Neither'",
      patternName_bn: "'Neither' দিয়ে সম্মতি",
      slots: [],
      examples: [
        { en: "A: I don't like spicy food. B: Neither do I.", bn: "ক: আমি ঝাল খাবার পছন্দ করি না। খ: আমিও না।", slotValues: {} },
        { en: "A: I'm not ready yet. B: Neither am I.", bn: "ক: আমি এখনও প্রস্তুত নই। খ: আমিও নই।", slotValues: {} },
        { en: "A: I didn't see the movie. B: Neither did I.", bn: "ক: আমি সিনেমাটি দেখিনি। খ: আমিও দেখিনি।", slotValues: {} },
        { en: "A: I can't swim. B: Neither can I.", bn: "ক: আমি সাঁতার পারি না। খ: আমিও পারি না।", slotValues: {} },
        { en: "A: I haven't finished yet. B: Neither have I.", bn: "ক: আমি এখনও শেষ করিনি। খ: আমিও করিনি।", slotValues: {} },
        { en: "A: I wouldn't do that. B: Neither would I.", bn: "ক: আমি সেটা করতাম না। খ: আমিও না।", slotValues: {} },
        { en: "A: She doesn't drink coffee. B: Neither does he.", bn: "ক: সে কফি পান করে না। খ: সেও করে না।", slotValues: {} },
        { en: "A: I wasn't invited. B: Neither was I.", bn: "ক: আমাকে আমন্ত্রণ জানানো হয়নি। খ: আমাকেও না।", slotValues: {} },
        { en: "A: I don't understand this. B: Neither do I.", bn: "ক: আমি এটা বুঝি না। খ: আমিও না।", slotValues: {} },
        { en: "A: I won't be there tomorrow. B: Neither will I.", bn: "ক: আমি আগামীকাল সেখানে থাকব না। খ: আমিও না।", slotValues: {} },
        { en: "A: I didn't know about the change. B: Neither did we.", bn: "ক: আমি পরিবর্তনের কথা জানতাম না। খ: আমরাও জানতাম না।", slotValues: {} },
        { en: "A: He hasn't called yet. B: Neither has she.", bn: "ক: সে এখনও ফোন করেনি। খ: সেও করেনি।", slotValues: {} },
        { en: "A: I don't want to go out. B: Neither do I.", bn: "ক: আমি বাইরে যেতে চাই না। খ: আমিও না।", slotValues: {} },
        { en: "A: I shouldn't eat too much. B: Neither should I.", bn: "ক: আমার বেশি খাওয়া উচিত না। খ: আমারও না।", slotValues: {} },
        { en: "A: I couldn't sleep last night. B: Neither could I.", bn: "ক: গত রাতে আমি ঘুমাতে পারিনি। খ: আমিও পারিনি।", slotValues: {} },
      ],
      formality: "casual",
      difficulty: "advanced",
    },
    {
      id: "S5.5",
      formula: "I [VERB] too / I don't [VERB] either",
      formula_bn: "আমিও [ক্রিয়া] / আমিও [ক্রিয়া] না",
      patternName: "Too & Either Agreement",
      patternName_bn: "Too ও Either দিয়ে সম্মতি",
      slots: [
        {
          name: "VERB",
          description: "The verb being agreed with",
          description_bn: "যে ক্রিয়ার সাথে সম্মত হচ্ছেন",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["like", "want", "need"],
        },
      ],
      examples: [
        { en: "A: I like tea. B: I like tea too.", bn: "ক: আমি চা পছন্দ করি। খ: আমিও চা পছন্দ করি।", slotValues: { VERB: "like tea" } },
        { en: "A: I don't eat meat. B: I don't eat meat either.", bn: "ক: আমি মাংস খাই না। খ: আমিও মাংস খাই না।", slotValues: { VERB: "eat meat" } },
        { en: "A: I want to travel more. B: I want to travel more too.", bn: "ক: আমি আরও ভ্রমণ করতে চাই। খ: আমিও আরও ভ্রমণ করতে চাই।", slotValues: { VERB: "want to travel more" } },
        { en: "A: I don't like waiting. B: I don't like waiting either.", bn: "ক: আমি অপেক্ষা করতে পছন্দ করি না। খ: আমিও পছন্দ করি না।", slotValues: { VERB: "like waiting" } },
        { en: "A: I need a break. B: I need a break too.", bn: "ক: আমার বিরতি দরকার। খ: আমারও বিরতি দরকার।", slotValues: { VERB: "need a break" } },
        { en: "A: I don't understand the question. B: I don't understand it either.", bn: "ক: আমি প্রশ্নটি বুঝি না। খ: আমিও বুঝি না।", slotValues: { VERB: "understand" } },
        { en: "A: I enjoy cooking. B: I enjoy cooking too.", bn: "ক: আমি রান্না উপভোগ করি। খ: আমিও রান্না উপভোগ করি।", slotValues: { VERB: "enjoy cooking" } },
        { en: "A: I don't have time. B: I don't have time either.", bn: "ক: আমার সময় নেই। খ: আমারও সময় নেই।", slotValues: { VERB: "have time" } },
        { en: "A: I missed the class. B: I missed it too.", bn: "ক: আমি ক্লাস মিস করেছি। খ: আমিও মিস করেছি।", slotValues: { VERB: "missed" } },
        { en: "A: I didn't know about the exam. B: I didn't know either.", bn: "ক: আমি পরীক্ষার কথা জানতাম না। খ: আমিও জানতাম না।", slotValues: { VERB: "know" } },
        { en: "A: I feel hungry. B: I feel hungry too.", bn: "ক: আমি ক্ষুধার্ত অনুভব করছি। খ: আমিও।", slotValues: { VERB: "feel hungry" } },
        { en: "A: I don't trust him. B: I don't trust him either.", bn: "ক: আমি তাকে বিশ্বাস করি না। খ: আমিও করি না।", slotValues: { VERB: "trust him" } },
        { en: "A: I think she's right. B: I think so too.", bn: "ক: আমি মনে করি সে ঠিক। খ: আমিও তাই মনে করি।", slotValues: { VERB: "think so" } },
        { en: "A: I can't wait for the holidays. B: I can't wait either.", bn: "ক: ছুটির জন্য আমি অপেক্ষা করতে পারছি না। খ: আমিও পারছি না।", slotValues: { VERB: "wait" } },
        { en: "A: I love this song. B: I love it too.", bn: "ক: আমি এই গানটি ভালোবাসি। খ: আমিও ভালোবাসি।", slotValues: { VERB: "love it" } },
      ],
      formality: "casual",
      difficulty: "advanced",
    },
  ],
};
