import { PatternCategory } from "@/types/pattern";

export const categoryS6: PatternCategory = {
  id: "S6",
  slug: "noun-clause-patterns",
  name: "Noun Clause Patterns",
  name_bn: "বিশেষ্য উপবাক্য প্যাটার্ন",
  description: "Use what/whether/that clauses as subjects and objects",
  description_bn: "what/whether/that উপবাক্য কর্তা এবং কর্ম হিসেবে ব্যবহার করুন",
  icon: "📦",
  group: "S",
  groupName: "Advanced Structural Patterns",
  groupName_bn: "উন্নত গঠনমূলক প্যাটার্ন",
  difficulty: "advanced",
  patterns: [
    {
      id: "S6.1",
      formula: "What [PERSON] [ACTION+S] is [DESCRIPTION]",
      formula_bn: "[ব্যক্তি] যা [ক্রিয়া] তা [বর্ণনা]",
      patternName: "What-Clause as Subject",
      patternName_bn: "What-উপবাক্য কর্তা হিসেবে",
      slots: [
        {
          name: "PERSON",
          description: "The person doing the action",
          description_bn: "কাজটি করছে এমন ব্যক্তি",
          acceptedTypes: ["person", "noun_phrase"],
          examples: ["he", "she", "the teacher"],
        },
        {
          name: "ACTION+S",
          description: "The action verb (third person singular)",
          description_bn: "ক্রিয়াপদ (তৃতীয় পুরুষ একবচন)",
          acceptedTypes: ["verb_phrase"],
          examples: ["needs", "wants", "said"],
        },
        {
          name: "DESCRIPTION",
          description: "A description or explanation",
          description_bn: "একটি বর্ণনা বা ব্যাখ্যা",
          acceptedTypes: ["adjective", "adjective_phrase", "noun_phrase", "description"],
          examples: ["important", "a good idea", "absolutely true"],
        },
      ],
      examples: [
        { en: "What he said is absolutely true.", bn: "সে যা বলেছে তা সম্পূর্ণ সত্য।", slotValues: { PERSON: "he", "ACTION+S": "said", DESCRIPTION: "absolutely true" } },
        { en: "What she needs is a good rest.", bn: "তার যা দরকার তা হলো একটি ভালো বিশ্রাম।", slotValues: { PERSON: "she", "ACTION+S": "needs", DESCRIPTION: "a good rest" } },
        { en: "What the teacher explained is very clear.", bn: "শিক্ষক যা ব্যাখ্যা করেছেন তা খুব স্পষ্ট।", slotValues: { PERSON: "the teacher", "ACTION+S": "explained", DESCRIPTION: "very clear" } },
        { en: "What we discovered is shocking.", bn: "আমরা যা আবিষ্কার করেছি তা চমকপ্রদ।", slotValues: { PERSON: "we", "ACTION+S": "discovered", DESCRIPTION: "shocking" } },
        { en: "What he wants is more time.", bn: "সে যা চায় তা হলো আরও সময়।", slotValues: { PERSON: "he", "ACTION+S": "wants", DESCRIPTION: "more time" } },
        { en: "What they achieved is remarkable.", bn: "তারা যা অর্জন করেছে তা অসাধারণ।", slotValues: { PERSON: "they", "ACTION+S": "achieved", DESCRIPTION: "remarkable" } },
        { en: "What she cooked is delicious.", bn: "সে যা রান্না করেছে তা সুস্বাদু।", slotValues: { PERSON: "she", "ACTION+S": "cooked", DESCRIPTION: "delicious" } },
        { en: "What the doctor recommended is sensible.", bn: "ডাক্তার যা সুপারিশ করেছেন তা বিচক্ষণ।", slotValues: { PERSON: "the doctor", "ACTION+S": "recommended", DESCRIPTION: "sensible" } },
        { en: "What I learned from the experience is invaluable.", bn: "অভিজ্ঞতা থেকে আমি যা শিখেছি তা অমূল্য।", slotValues: { PERSON: "I", "ACTION+S": "learned from the experience", DESCRIPTION: "invaluable" } },
        { en: "What bothers me is his attitude.", bn: "যেটা আমাকে বিরক্ত করে সেটা হলো তার মনোভাব।", slotValues: { PERSON: "me", "ACTION+S": "bothers", DESCRIPTION: "his attitude" } },
        { en: "What the report reveals is concerning.", bn: "রিপোর্ট যা প্রকাশ করেছে তা উদ্বেগজনক।", slotValues: { PERSON: "the report", "ACTION+S": "reveals", DESCRIPTION: "concerning" } },
        { en: "What she decided is final.", bn: "সে যা সিদ্ধান্ত নিয়েছে তা চূড়ান্ত।", slotValues: { PERSON: "she", "ACTION+S": "decided", DESCRIPTION: "final" } },
        { en: "What we need is better communication.", bn: "আমাদের যা দরকার তা হলো আরও ভালো যোগাযোগ।", slotValues: { PERSON: "we", "ACTION+S": "need", DESCRIPTION: "better communication" } },
        { en: "What he promised is exactly what he delivered.", bn: "সে যা প্রতিশ্রুতি দিয়েছিল তা-ই সে সরবরাহ করেছে।", slotValues: { PERSON: "he", "ACTION+S": "promised", DESCRIPTION: "exactly what he delivered" } },
        { en: "What happened yesterday is unbelievable.", bn: "গতকাল যা ঘটেছে তা অবিশ্বাস্য।", slotValues: { PERSON: "yesterday", "ACTION+S": "happened", DESCRIPTION: "unbelievable" } },
      ],
      formality: "polite",
      difficulty: "advanced",
    },
    {
      id: "S6.2",
      formula: "Whether [CLAUSE] depends on [THING]",
      formula_bn: "[উপবাক্য] কিনা তা [বিষয়ের] উপর নির্ভর করে",
      patternName: "Whether-Clause as Subject",
      patternName_bn: "Whether-উপবাক্য কর্তা হিসেবে",
      slots: [
        {
          name: "CLAUSE",
          description: "A condition or situation in question",
          description_bn: "প্রশ্নে থাকা একটি শর্ত বা পরিস্থিতি",
          acceptedTypes: ["clause"],
          examples: ["we go or not", "she accepts", "the plan works"],
        },
        {
          name: "THING",
          description: "The determining factor",
          description_bn: "নির্ধারক বিষয়",
          acceptedTypes: ["noun_phrase", "clause"],
          examples: ["the weather", "her decision", "many factors"],
        },
      ],
      examples: [
        { en: "Whether we go or not depends on the weather.", bn: "আমরা যাব কি না তা আবহাওয়ার উপর নির্ভর করে।", slotValues: { CLAUSE: "we go or not", THING: "the weather" } },
        { en: "Whether she accepts depends on the salary.", bn: "সে গ্রহণ করবে কি না তা বেতনের উপর নির্ভর করে।", slotValues: { CLAUSE: "she accepts", THING: "the salary" } },
        { en: "Whether the plan works depends on everyone's cooperation.", bn: "পরিকল্পনা কাজ করবে কি না তা সবার সহযোগিতার উপর নির্ভর করে।", slotValues: { CLAUSE: "the plan works", THING: "everyone's cooperation" } },
        { en: "Whether he passes depends on how much he studies.", bn: "সে পাস করবে কি না তা নির্ভর করে সে কতটা পড়ে।", slotValues: { CLAUSE: "he passes", THING: "how much he studies" } },
        { en: "Whether we can afford it depends on our budget.", bn: "আমরা এটা বহন করতে পারব কি না তা আমাদের বাজেটের উপর নির্ভর করে।", slotValues: { CLAUSE: "we can afford it", THING: "our budget" } },
        { en: "Whether the event happens depends on the sponsors.", bn: "অনুষ্ঠান হবে কি না তা স্পনসরদের উপর নির্ভর করে।", slotValues: { CLAUSE: "the event happens", THING: "the sponsors" } },
        { en: "Whether they get married depends on their families.", bn: "তারা বিয়ে করবে কি না তা তাদের পরিবারের উপর নির্ভর করে।", slotValues: { CLAUSE: "they get married", THING: "their families" } },
        { en: "Whether I take the job depends on the location.", bn: "আমি চাকরিটি নেব কি না তা অবস্থানের উপর নির্ভর করে।", slotValues: { CLAUSE: "I take the job", THING: "the location" } },
        { en: "Whether the project succeeds depends on the team leader.", bn: "প্রকল্প সফল হবে কি না তা দলনেতার উপর নির্ভর করে।", slotValues: { CLAUSE: "the project succeeds", THING: "the team leader" } },
        { en: "Whether we travel by train or bus depends on the cost.", bn: "আমরা ট্রেনে না বাসে যাব তা খরচের উপর নির্ভর করে।", slotValues: { CLAUSE: "we travel by train or bus", THING: "the cost" } },
        { en: "Whether she recovers quickly depends on the treatment.", bn: "সে দ্রুত সুস্থ হবে কি না তা চিকিৎসার উপর নির্ভর করে।", slotValues: { CLAUSE: "she recovers quickly", THING: "the treatment" } },
        { en: "Whether the business grows depends on market conditions.", bn: "ব্যবসা বৃদ্ধি পাবে কি না তা বাজার পরিস্থিতির উপর নির্ভর করে।", slotValues: { CLAUSE: "the business grows", THING: "market conditions" } },
        { en: "Whether he apologizes depends on his pride.", bn: "সে ক্ষমা চাইবে কি না তা তার অহংকারের উপর নির্ভর করে।", slotValues: { CLAUSE: "he apologizes", THING: "his pride" } },
        { en: "Whether the flight is delayed depends on the fog.", bn: "ফ্লাইট বিলম্ব হবে কি না তা কুয়াশার উপর নির্ভর করে।", slotValues: { CLAUSE: "the flight is delayed", THING: "the fog" } },
        { en: "Whether we need a visa depends on our nationality.", bn: "আমাদের ভিসা লাগবে কি না তা আমাদের জাতীয়তার উপর নির্ভর করে।", slotValues: { CLAUSE: "we need a visa", THING: "our nationality" } },
      ],
      formality: "polite",
      difficulty: "advanced",
    },
    {
      id: "S6.3",
      formula: "The fact that [CLAUSE] [VERB] [DESCRIPTION]",
      formula_bn: "যে [উপবাক্য] এই সত্যটি [ক্রিয়া] [বর্ণনা]",
      patternName: "The fact that + Clause",
      patternName_bn: "যে সত্য + উপবাক্য",
      slots: [
        {
          name: "CLAUSE",
          description: "A factual statement",
          description_bn: "একটি তথ্যগত বিবৃতি",
          acceptedTypes: ["clause"],
          examples: ["he lied", "she got promoted", "they won"],
        },
        {
          name: "VERB",
          description: "The main verb",
          description_bn: "মূল ক্রিয়া",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["proves", "shows", "suggests"],
        },
        {
          name: "DESCRIPTION",
          description: "The conclusion or observation",
          description_bn: "উপসংহার বা পর্যবেক্ষণ",
          acceptedTypes: ["clause", "noun_phrase"],
          examples: ["his dishonesty", "that hard work pays off", "their strength"],
        },
      ],
      examples: [
        { en: "The fact that he lied proves his dishonesty.", bn: "সে মিথ্যা বলেছে এই সত্যটি তার অসততা প্রমাণ করে।", slotValues: { CLAUSE: "he lied", VERB: "proves", DESCRIPTION: "his dishonesty" } },
        { en: "The fact that she got promoted shows her dedication.", bn: "সে পদোন্নতি পেয়েছে এই সত্যটি তার নিষ্ঠা দেখায়।", slotValues: { CLAUSE: "she got promoted", VERB: "shows", DESCRIPTION: "her dedication" } },
        { en: "The fact that they won surprised everyone.", bn: "তারা জিতেছে এই সত্যটি সবাইকে অবাক করেছে।", slotValues: { CLAUSE: "they won", VERB: "surprised", DESCRIPTION: "everyone" } },
        { en: "The fact that he apologized means a lot to me.", bn: "সে ক্ষমা চেয়েছে এই সত্যটি আমার কাছে অনেক মানে।", slotValues: { CLAUSE: "he apologized", VERB: "means", DESCRIPTION: "a lot to me" } },
        { en: "The fact that prices have risen concerns many people.", bn: "দাম বেড়ে গেছে এই সত্যটি অনেক মানুষকে উদ্বিগ্ন করে।", slotValues: { CLAUSE: "prices have risen", VERB: "concerns", DESCRIPTION: "many people" } },
        { en: "The fact that she speaks three languages impresses employers.", bn: "সে তিনটি ভাষায় কথা বলে এই সত্যটি নিয়োগকর্তাদের মুগ্ধ করে।", slotValues: { CLAUSE: "she speaks three languages", VERB: "impresses", DESCRIPTION: "employers" } },
        { en: "The fact that nobody came disappointed her.", bn: "কেউ আসেনি এই সত্যটি তাকে হতাশ করেছে।", slotValues: { CLAUSE: "nobody came", VERB: "disappointed", DESCRIPTION: "her" } },
        { en: "The fact that he survived is a miracle.", bn: "সে বেঁচে গেছে এই সত্যটি একটি অলৌকিক ঘটনা।", slotValues: { CLAUSE: "he survived", VERB: "is", DESCRIPTION: "a miracle" } },
        { en: "The fact that the team worked together made the difference.", bn: "দল একসাথে কাজ করেছে এই সত্যটি পার্থক্য তৈরি করেছে।", slotValues: { CLAUSE: "the team worked together", VERB: "made", DESCRIPTION: "the difference" } },
        { en: "The fact that she helped without asking shows her kindness.", bn: "সে না চাইতেই সাহায্য করেছে এই সত্যটি তার দয়া দেখায়।", slotValues: { CLAUSE: "she helped without asking", VERB: "shows", DESCRIPTION: "her kindness" } },
        { en: "The fact that we lost doesn't mean we failed.", bn: "আমরা হেরে গেছি এই সত্যটি মানে এই নয় যে আমরা ব্যর্থ হয়েছি।", slotValues: { CLAUSE: "we lost", VERB: "doesn't mean", DESCRIPTION: "we failed" } },
        { en: "The fact that he remembered my birthday made me happy.", bn: "সে আমার জন্মদিন মনে রেখেছে এই সত্যটি আমাকে খুশি করেছে।", slotValues: { CLAUSE: "he remembered my birthday", VERB: "made", DESCRIPTION: "me happy" } },
        { en: "The fact that crime has decreased is encouraging.", bn: "অপরাধ কমেছে এই সত্যটি উৎসাহজনক।", slotValues: { CLAUSE: "crime has decreased", VERB: "is", DESCRIPTION: "encouraging" } },
        { en: "The fact that the bridge collapsed raises safety concerns.", bn: "সেতু ধসে পড়েছে এই সত্যটি নিরাপত্তা উদ্বেগ বাড়ায়।", slotValues: { CLAUSE: "the bridge collapsed", VERB: "raises", DESCRIPTION: "safety concerns" } },
        { en: "The fact that you tried is what counts.", bn: "তুমি চেষ্টা করেছ এই সত্যটিই গুরুত্বপূর্ণ।", slotValues: { CLAUSE: "you tried", VERB: "is", DESCRIPTION: "what counts" } },
      ],
      formality: "formal",
      difficulty: "advanced",
    },
    {
      id: "S6.4",
      formula: "I don't know [QUESTION WORD] [CLAUSE]",
      formula_bn: "আমি জানি না [প্রশ্নবোধক শব্দ] [উপবাক্য]",
      patternName: "Embedded Question (Object)",
      patternName_bn: "সংযুক্ত প্রশ্ন (কর্ম)",
      slots: [
        {
          name: "QUESTION WORD",
          description: "A question word introducing the clause",
          description_bn: "উপবাক্য শুরু করা প্রশ্নবোধক শব্দ",
          acceptedTypes: ["noun"],
          examples: ["what", "where", "why"],
        },
        {
          name: "CLAUSE",
          description: "The embedded question",
          description_bn: "সংযুক্ত প্রশ্ন",
          acceptedTypes: ["clause"],
          examples: ["to do next", "she went", "he left early"],
        },
      ],
      examples: [
        { en: "I don't know what to do next.", bn: "আমি জানি না পরবর্তীতে কী করতে হবে।", slotValues: { "QUESTION WORD": "what", CLAUSE: "to do next" } },
        { en: "I don't know where she went.", bn: "আমি জানি না সে কোথায় গেছে।", slotValues: { "QUESTION WORD": "where", CLAUSE: "she went" } },
        { en: "I don't know why he left early.", bn: "আমি জানি না সে কেন তাড়াতাড়ি চলে গেছে।", slotValues: { "QUESTION WORD": "why", CLAUSE: "he left early" } },
        { en: "I don't know how to fix this.", bn: "আমি জানি না এটা কীভাবে ঠিক করতে হবে।", slotValues: { "QUESTION WORD": "how", CLAUSE: "to fix this" } },
        { en: "I don't know when the train arrives.", bn: "আমি জানি না ট্রেন কখন আসবে।", slotValues: { "QUESTION WORD": "when", CLAUSE: "the train arrives" } },
        { en: "I don't know who called last night.", bn: "আমি জানি না গত রাতে কে ফোন করেছিল।", slotValues: { "QUESTION WORD": "who", CLAUSE: "called last night" } },
        { en: "I don't know which one to choose.", bn: "আমি জানি না কোনটা বেছে নেব।", slotValues: { "QUESTION WORD": "which one", CLAUSE: "to choose" } },
        { en: "I don't know how long the meeting will last.", bn: "আমি জানি না মিটিং কতক্ষণ চলবে।", slotValues: { "QUESTION WORD": "how long", CLAUSE: "the meeting will last" } },
        { en: "I don't know whether he's coming or not.", bn: "আমি জানি না সে আসছে কি না।", slotValues: { "QUESTION WORD": "whether", CLAUSE: "he's coming or not" } },
        { en: "I don't know what she meant by that.", bn: "আমি জানি না সে ওই কথা দিয়ে কী বোঝাতে চেয়েছে।", slotValues: { "QUESTION WORD": "what", CLAUSE: "she meant by that" } },
        { en: "I don't know how much it costs.", bn: "আমি জানি না এর দাম কত।", slotValues: { "QUESTION WORD": "how much", CLAUSE: "it costs" } },
        { en: "I don't know where to park the car.", bn: "আমি জানি না গাড়ি কোথায় পার্ক করতে হবে।", slotValues: { "QUESTION WORD": "where", CLAUSE: "to park the car" } },
        { en: "I don't know why the system crashed.", bn: "আমি জানি না সিস্টেম কেন ক্র্যাশ করেছে।", slotValues: { "QUESTION WORD": "why", CLAUSE: "the system crashed" } },
        { en: "I don't know how she managed to finish so quickly.", bn: "আমি জানি না সে কীভাবে এত দ্রুত শেষ করতে পেরেছে।", slotValues: { "QUESTION WORD": "how", CLAUSE: "she managed to finish so quickly" } },
        { en: "I don't know what time the store opens.", bn: "আমি জানি না দোকান কটায় খোলে।", slotValues: { "QUESTION WORD": "what time", CLAUSE: "the store opens" } },
      ],
      formality: "casual",
      difficulty: "advanced",
    },
    {
      id: "S6.5",
      formula: "That [CLAUSE] is [DESCRIPTION]",
      formula_bn: "যে [উপবাক্য] তা [বর্ণনা]",
      patternName: "That-Clause as Subject",
      patternName_bn: "That-উপবাক্য কর্তা হিসেবে",
      slots: [
        {
          name: "CLAUSE",
          description: "A statement or fact",
          description_bn: "একটি বিবৃতি বা সত্য",
          acceptedTypes: ["clause"],
          examples: ["he passed", "she is leaving", "they agreed"],
        },
        {
          name: "DESCRIPTION",
          description: "A comment about the statement",
          description_bn: "বিবৃতি সম্পর্কে একটি মন্তব্য",
          acceptedTypes: ["adjective", "adjective_phrase", "description"],
          examples: ["great news", "very surprising", "well known"],
        },
      ],
      examples: [
        { en: "That he passed the exam is great news.", bn: "সে পরীক্ষায় পাস করেছে এটা দারুণ খবর।", slotValues: { CLAUSE: "he passed the exam", DESCRIPTION: "great news" } },
        { en: "That she is leaving is very surprising.", bn: "সে চলে যাচ্ছে এটা খুব অবাক করার মতো।", slotValues: { CLAUSE: "she is leaving", DESCRIPTION: "very surprising" } },
        { en: "That they agreed so quickly is unexpected.", bn: "তারা এত দ্রুত রাজি হয়েছে এটা অপ্রত্যাশিত।", slotValues: { CLAUSE: "they agreed so quickly", DESCRIPTION: "unexpected" } },
        { en: "That the earth is round is well known.", bn: "পৃথিবী গোলাকার এটা সর্বজনবিদিত।", slotValues: { CLAUSE: "the earth is round", DESCRIPTION: "well known" } },
        { en: "That he forgot her birthday is unforgivable.", bn: "সে তার জন্মদিন ভুলে গেছে এটা ক্ষমার অযোগ্য।", slotValues: { CLAUSE: "he forgot her birthday", DESCRIPTION: "unforgivable" } },
        { en: "That she completed the marathon is impressive.", bn: "সে ম্যারাথন সম্পন্ন করেছে এটা চিত্তাকর্ষক।", slotValues: { CLAUSE: "she completed the marathon", DESCRIPTION: "impressive" } },
        { en: "That they cancelled the event is disappointing.", bn: "তারা অনুষ্ঠান বাতিল করেছে এটা হতাশাজনক।", slotValues: { CLAUSE: "they cancelled the event", DESCRIPTION: "disappointing" } },
        { en: "That he recovered so fast is a relief.", bn: "সে এত দ্রুত সুস্থ হয়েছে এটা স্বস্তির বিষয়।", slotValues: { CLAUSE: "he recovered so fast", DESCRIPTION: "a relief" } },
        { en: "That the company is profitable is obvious.", bn: "কোম্পানি লাভজনক এটা স্পষ্ট।", slotValues: { CLAUSE: "the company is profitable", DESCRIPTION: "obvious" } },
        { en: "That he donated all his savings is truly generous.", bn: "সে তার সব সঞ্চয় দান করেছে এটা সত্যিই মহানুভব।", slotValues: { CLAUSE: "he donated all his savings", DESCRIPTION: "truly generous" } },
        { en: "That she speaks four languages is remarkable.", bn: "সে চারটি ভাষায় কথা বলে এটা অসাধারণ।", slotValues: { CLAUSE: "she speaks four languages", DESCRIPTION: "remarkable" } },
        { en: "That the train was late again is frustrating.", bn: "ট্রেন আবার দেরি করেছে এটা হতাশাজনক।", slotValues: { CLAUSE: "the train was late again", DESCRIPTION: "frustrating" } },
        { en: "That he won the award is well-deserved.", bn: "সে পুরস্কার জিতেছে এটা যথার্থ।", slotValues: { CLAUSE: "he won the award", DESCRIPTION: "well-deserved" } },
        { en: "That they managed to escape is miraculous.", bn: "তারা পালাতে পেরেছে এটা অলৌকিক।", slotValues: { CLAUSE: "they managed to escape", DESCRIPTION: "miraculous" } },
        { en: "That the economy is improving is good news for everyone.", bn: "অর্থনীতি উন্নতি করছে এটা সবার জন্য ভালো খবর।", slotValues: { CLAUSE: "the economy is improving", DESCRIPTION: "good news for everyone" } },
      ],
      formality: "formal",
      difficulty: "advanced",
    },
  ],
};
