import { PatternCategory } from "@/types/pattern";

export const categoryS7: PatternCategory = {
  id: "S7",
  slug: "appositive-patterns",
  name: "Appositive Patterns",
  name_bn: "সমার্থক পদ প্যাটার্ন",
  description: "Add extra identity information using commas and noun phrases",
  description_bn: "কমা এবং বিশেষ্য পদবন্ধ ব্যবহার করে অতিরিক্ত পরিচয় তথ্য যোগ করুন",
  icon: "🏷️",
  group: "S",
  groupName: "Advanced Structural Patterns",
  groupName_bn: "উন্নত গঠনমূলক প্যাটার্ন",
  difficulty: "advanced",
  patterns: [
    {
      id: "S7.1",
      formula: "[PERSON], a [JOB/ROLE], [ACTION+ED]",
      formula_bn: "[ব্যক্তি], একজন [পেশা/ভূমিকা], [ক্রিয়া]",
      patternName: "Appositive with Job/Role",
      patternName_bn: "পেশা/ভূমিকা সহ সমার্থক পদ",
      slots: [
        { name: "PERSON", description: "A specific named person", description_bn: "একটি নির্দিষ্ট নামযুক্ত ব্যক্তি", acceptedTypes: ["person", "noun_phrase"], examples: ["Mr. Hasan", "Dr. Sultana", "My father"] },
        { name: "JOB/ROLE", description: "Their profession or role", description_bn: "তাদের পেশা বা ভূমিকা", acceptedTypes: ["noun_phrase"], examples: ["a retired teacher", "a well-known doctor", "an experienced engineer"] },
        { name: "ACTION+ED", description: "What the person did", description_bn: "ব্যক্তি কী করেছে", acceptedTypes: ["verb_phrase"], examples: ["gave a speech", "helped the community", "published a book"] },
      ],
      examples: [
        { en: "Mr. Hasan, a retired teacher, volunteers at the local school.", bn: "মি. হাসান, একজন অবসরপ্রাপ্ত শিক্ষক, স্থানীয় স্কুলে স্বেচ্ছাসেবা করেন।", slotValues: { PERSON: "Mr. Hasan", "JOB/ROLE": "a retired teacher", "ACTION+ED": "volunteers at the local school" } },
        { en: "Dr. Sultana, a well-known cardiologist, saved his life.", bn: "ডাঃ সুলতানা, একজন সুপরিচিত হৃদরোগ বিশেষজ্ঞ, তার জীবন বাঁচিয়েছেন।", slotValues: { PERSON: "Dr. Sultana", "JOB/ROLE": "a well-known cardiologist", "ACTION+ED": "saved his life" } },
        { en: "My father, a farmer all his life, understands the land.", bn: "আমার বাবা, সারাজীবন একজন কৃষক, জমি বোঝেন।", slotValues: { PERSON: "My father", "JOB/ROLE": "a farmer all his life", "ACTION+ED": "understands the land" } },
        { en: "Sarah, a talented musician, performed at the festival.", bn: "সারাহ, একজন প্রতিভাবান সঙ্গীতশিল্পী, উৎসবে পরিবেশন করেছে।", slotValues: { PERSON: "Sarah", "JOB/ROLE": "a talented musician", "ACTION+ED": "performed at the festival" } },
        { en: "Ahmed, an experienced lawyer, won the difficult case.", bn: "আহমেদ, একজন অভিজ্ঞ আইনজীবী, কঠিন মামলাটি জিতেছেন।", slotValues: { PERSON: "Ahmed", "JOB/ROLE": "an experienced lawyer", "ACTION+ED": "won the difficult case" } },
        { en: "My neighbor, a former soldier, tells fascinating stories.", bn: "আমার প্রতিবেশী, একজন প্রাক্তন সৈনিক, চমকপ্রদ গল্প বলেন।", slotValues: { PERSON: "My neighbor", "JOB/ROLE": "a former soldier", "ACTION+ED": "tells fascinating stories" } },
        { en: "Karim, a software engineer, developed the new app.", bn: "করিম, একজন সফটওয়্যার ইঞ্জিনিয়ার, নতুন অ্যাপটি তৈরি করেছেন।", slotValues: { PERSON: "Karim", "JOB/ROLE": "a software engineer", "ACTION+ED": "developed the new app" } },
        { en: "Ms. Akhter, a dedicated nurse, worked through the night.", bn: "মিস আখতার, একজন নিবেদিত নার্স, সারারাত কাজ করেছেন।", slotValues: { PERSON: "Ms. Akhter", "JOB/ROLE": "a dedicated nurse", "ACTION+ED": "worked through the night" } },
        { en: "Prof. Islam, a Nobel nominee, delivered the lecture.", bn: "প্রফ. ইসলাম, একজন নোবেল মনোনীত, বক্তৃতাটি দিয়েছেন।", slotValues: { PERSON: "Prof. Islam", "JOB/ROLE": "a Nobel nominee", "ACTION+ED": "delivered the lecture" } },
        { en: "Rima, a professional dancer, teaches at the academy.", bn: "রিমা, একজন পেশাদার নর্তকী, একাডেমিতে শেখান।", slotValues: { PERSON: "Rima", "JOB/ROLE": "a professional dancer", "ACTION+ED": "teaches at the academy" } },
        { en: "My uncle, a skilled carpenter, built this table.", bn: "আমার চাচা, একজন দক্ষ কাঠমিস্ত্রি, এই টেবিলটি তৈরি করেছেন।", slotValues: { PERSON: "My uncle", "JOB/ROLE": "a skilled carpenter", "ACTION+ED": "built this table" } },
        { en: "Nadia, a young entrepreneur, started her business at twenty.", bn: "নাদিয়া, একজন তরুণ উদ্যোক্তা, বিশ বছর বয়সে তার ব্যবসা শুরু করেছে।", slotValues: { PERSON: "Nadia", "JOB/ROLE": "a young entrepreneur", "ACTION+ED": "started her business at twenty" } },
        { en: "The mayor, a former journalist, addressed the crowd.", bn: "মেয়র, একজন প্রাক্তন সাংবাদিক, জনতাকে সম্বোধন করেছেন।", slotValues: { PERSON: "The mayor", "JOB/ROLE": "a former journalist", "ACTION+ED": "addressed the crowd" } },
        { en: "His mother, a school principal, values education deeply.", bn: "তার মা, একজন স্কুল অধ্যক্ষ, শিক্ষাকে গভীরভাবে মূল্য দেন।", slotValues: { PERSON: "His mother", "JOB/ROLE": "a school principal", "ACTION+ED": "values education deeply" } },
        { en: "Rahim, a firefighter for twenty years, received a medal of honor.", bn: "রহিম, বিশ বছর ধরে একজন দমকলকর্মী, সম্মানসূচক পদক পেয়েছেন।", slotValues: { PERSON: "Rahim", "JOB/ROLE": "a firefighter for twenty years", "ACTION+ED": "received a medal of honor" } },
      ],
      formality: "formal",
      difficulty: "advanced",
    },
    {
      id: "S7.2",
      formula: "[PLACE], the [DESCRIPTION], is [ADJECTIVE]",
      formula_bn: "[স্থান], [বর্ণনা], [বিশেষণ]",
      patternName: "Appositive with Place Description",
      patternName_bn: "স্থান বর্ণনা সহ সমার্থক পদ",
      slots: [
        { name: "PLACE", description: "A specific place name", description_bn: "একটি নির্দিষ্ট স্থানের নাম", acceptedTypes: ["place", "noun_phrase"], examples: ["Dhaka", "The Sundarbans", "Cox's Bazar"] },
        { name: "DESCRIPTION", description: "An identifying description of the place", description_bn: "স্থানের একটি চিহ্নিতকারী বর্ণনা", acceptedTypes: ["noun_phrase", "description"], examples: ["the capital of Bangladesh", "the largest mangrove forest", "a popular tourist spot"] },
        { name: "ADJECTIVE", description: "A quality of the place", description_bn: "স্থানের একটি গুণ", acceptedTypes: ["adjective", "adjective_phrase"], examples: ["always crowded", "incredibly beautiful", "well-known worldwide"] },
      ],
      examples: [
        { en: "Dhaka, the capital of Bangladesh, is always busy.", bn: "ঢাকা, বাংলাদেশের রাজধানী, সবসময় ব্যস্ত।", slotValues: { PLACE: "Dhaka", DESCRIPTION: "the capital of Bangladesh", ADJECTIVE: "always busy" } },
        { en: "The Sundarbans, the largest mangrove forest in the world, is home to Bengal tigers.", bn: "সুন্দরবন, বিশ্বের সবচেয়ে বড় ম্যানগ্রোভ বন, বেঙ্গল টাইগারের আবাসস্থল।", slotValues: { PLACE: "The Sundarbans", DESCRIPTION: "the largest mangrove forest in the world", ADJECTIVE: "home to Bengal tigers" } },
        { en: "Cox's Bazar, the longest sea beach in the world, attracts millions of visitors.", bn: "কক্সবাজার, বিশ্বের দীর্ঘতম সমুদ্র সৈকত, লক্ষ লক্ষ পর্যটককে আকৃষ্ট করে।", slotValues: { PLACE: "Cox's Bazar", DESCRIPTION: "the longest sea beach in the world", ADJECTIVE: "attracts millions of visitors" } },
        { en: "Tokyo, the most populous city in Japan, is incredibly modern.", bn: "টোকিও, জাপানের সবচেয়ে জনবহুল শহর, অবিশ্বাস্যভাবে আধুনিক।", slotValues: { PLACE: "Tokyo", DESCRIPTION: "the most populous city in Japan", ADJECTIVE: "incredibly modern" } },
        { en: "The Amazon, the largest river by volume, flows through South America.", bn: "আমাজন, আয়তনে সবচেয়ে বড় নদী, দক্ষিণ আমেরিকার মধ্য দিয়ে প্রবাহিত হয়।", slotValues: { PLACE: "The Amazon", DESCRIPTION: "the largest river by volume", ADJECTIVE: "flows through South America" } },
        { en: "Sylhet, a land of tea gardens, is known for its natural beauty.", bn: "সিলেট, চা বাগানের ভূমি, তার প্রাকৃতিক সৌন্দর্যের জন্য পরিচিত।", slotValues: { PLACE: "Sylhet", DESCRIPTION: "a land of tea gardens", ADJECTIVE: "known for its natural beauty" } },
        { en: "Rome, the Eternal City, is rich in history.", bn: "রোম, চিরন্তন শহর, ইতিহাসে সমৃদ্ধ।", slotValues: { PLACE: "Rome", DESCRIPTION: "the Eternal City", ADJECTIVE: "rich in history" } },
        { en: "The Taj Mahal, a symbol of love, is breathtakingly beautiful.", bn: "তাজমহল, ভালোবাসার প্রতীক, শ্বাসরুদ্ধকরভাবে সুন্দর।", slotValues: { PLACE: "The Taj Mahal", DESCRIPTION: "a symbol of love", ADJECTIVE: "breathtakingly beautiful" } },
        { en: "Cambridge, a world-famous university city, is small but prestigious.", bn: "কেমব্রিজ, একটি বিশ্ববিখ্যাত বিশ্ববিদ্যালয় শহর, ছোট কিন্তু মর্যাদাপূর্ণ।", slotValues: { PLACE: "Cambridge", DESCRIPTION: "a world-famous university city", ADJECTIVE: "small but prestigious" } },
        { en: "Mount Everest, the highest peak on Earth, is extremely dangerous to climb.", bn: "মাউন্ট এভারেস্ট, পৃথিবীর সর্বোচ্চ শিখর, আরোহণ করা অত্যন্ত বিপজ্জনক।", slotValues: { PLACE: "Mount Everest", DESCRIPTION: "the highest peak on Earth", ADJECTIVE: "extremely dangerous to climb" } },
        { en: "Venice, the city of canals, is slowly sinking.", bn: "ভেনিস, খালের শহর, ধীরে ধীরে ডুবে যাচ্ছে।", slotValues: { PLACE: "Venice", DESCRIPTION: "the city of canals", ADJECTIVE: "slowly sinking" } },
        { en: "Rajshahi, the silk city of Bangladesh, is famous for its mangoes.", bn: "রাজশাহী, বাংলাদেশের রেশম শহর, তার আমের জন্য বিখ্যাত।", slotValues: { PLACE: "Rajshahi", DESCRIPTION: "the silk city of Bangladesh", ADJECTIVE: "famous for its mangoes" } },
        { en: "The Great Wall, a wonder of the ancient world, stretches for thousands of miles.", bn: "মহাপ্রাচীর, প্রাচীন বিশ্বের একটি বিস্ময়, হাজার হাজার মাইল বিস্তৃত।", slotValues: { PLACE: "The Great Wall", DESCRIPTION: "a wonder of the ancient world", ADJECTIVE: "stretches for thousands of miles" } },
        { en: "Dubai, a city of skyscrapers, has transformed rapidly.", bn: "দুবাই, গগনচুম্বী ভবনের শহর, দ্রুত রূপান্তরিত হয়েছে।", slotValues: { PLACE: "Dubai", DESCRIPTION: "a city of skyscrapers", ADJECTIVE: "has transformed rapidly" } },
        { en: "Lake Kaptai, the largest artificial lake in Bangladesh, is a popular destination.", bn: "কাপ্তাই হ্রদ, বাংলাদেশের সবচেয়ে বড় কৃত্রিম হ্রদ, একটি জনপ্রিয় গন্তব্য।", slotValues: { PLACE: "Lake Kaptai", DESCRIPTION: "the largest artificial lake in Bangladesh", ADJECTIVE: "a popular destination" } },
      ],
      formality: "formal",
      difficulty: "advanced",
    },
    {
      id: "S7.3",
      formula: "[THING], one of the [SUPERLATIVE], [ACTION]",
      formula_bn: "[বস্তু], সবচেয়ে [চরম বিশেষণ] এক, [ক্রিয়া]",
      patternName: "Appositive with Superlative",
      patternName_bn: "চরম বিশেষণ সহ সমার্থক পদ",
      slots: [
        { name: "THING", description: "The thing being described", description_bn: "যা বর্ণনা করা হচ্ছে", acceptedTypes: ["noun", "noun_phrase"], examples: ["Python", "Chess", "The Quran"] },
        { name: "SUPERLATIVE", description: "A superlative description", description_bn: "একটি চরম বিশেষণ বর্ণনা", acceptedTypes: ["adjective_phrase", "noun_phrase"], examples: ["most popular programming languages", "oldest games", "most widely read books"] },
        { name: "ACTION", description: "What it does or what happened", description_bn: "এটি কী করে বা কী ঘটেছে", acceptedTypes: ["verb_phrase", "clause"], examples: ["is used by millions", "requires deep thinking", "has influenced billions"] },
      ],
      examples: [
        { en: "Python, one of the most popular programming languages, is easy to learn.", bn: "পাইথন, সবচেয়ে জনপ্রিয় প্রোগ্রামিং ভাষাগুলোর একটি, শেখা সহজ।", slotValues: { THING: "Python", SUPERLATIVE: "most popular programming languages", ACTION: "is easy to learn" } },
        { en: "Chess, one of the oldest games in the world, requires deep thinking.", bn: "দাবা, বিশ্বের সবচেয়ে পুরোনো খেলাগুলোর একটি, গভীর চিন্তা প্রয়োজন।", slotValues: { THING: "Chess", SUPERLATIVE: "oldest games in the world", ACTION: "requires deep thinking" } },
        { en: "Water, one of the most essential resources, is becoming scarce.", bn: "পানি, সবচেয়ে অপরিহার্য সম্পদের একটি, দুর্লভ হয়ে যাচ্ছে।", slotValues: { THING: "Water", SUPERLATIVE: "most essential resources", ACTION: "is becoming scarce" } },
        { en: "Rice, one of the most important crops in Asia, feeds billions.", bn: "চাল, এশিয়ার সবচেয়ে গুরুত্বপূর্ণ ফসলগুলোর একটি, বিলিয়ন মানুষকে খাওয়ায়।", slotValues: { THING: "Rice", SUPERLATIVE: "most important crops in Asia", ACTION: "feeds billions" } },
        { en: "The internet, one of the greatest inventions, has changed the world.", bn: "ইন্টারনেট, সবচেয়ে বড় আবিষ্কারগুলোর একটি, বিশ্ব পরিবর্তন করেছে।", slotValues: { THING: "The internet", SUPERLATIVE: "greatest inventions", ACTION: "has changed the world" } },
        { en: "Football, one of the most watched sports globally, unites people.", bn: "ফুটবল, বিশ্বব্যাপী সবচেয়ে বেশি দেখা খেলাগুলোর একটি, মানুষকে একত্রিত করে।", slotValues: { THING: "Football", SUPERLATIVE: "most watched sports globally", ACTION: "unites people" } },
        { en: "Shakespeare, one of the greatest writers in history, wrote thirty-seven plays.", bn: "শেক্সপিয়ার, ইতিহাসের সবচেয়ে মহান লেখকদের একজন, সাতত্রিশটি নাটক লিখেছেন।", slotValues: { THING: "Shakespeare", SUPERLATIVE: "greatest writers in history", ACTION: "wrote thirty-seven plays" } },
        { en: "The Nile, one of the longest rivers in the world, flows through eleven countries.", bn: "নীল নদ, বিশ্বের দীর্ঘতম নদীগুলোর একটি, এগারোটি দেশের মধ্য দিয়ে প্রবাহিত হয়।", slotValues: { THING: "The Nile", SUPERLATIVE: "longest rivers in the world", ACTION: "flows through eleven countries" } },
        { en: "English, one of the most widely spoken languages, connects people globally.", bn: "ইংরেজি, সবচেয়ে বেশি কথিত ভাষাগুলোর একটি, বিশ্বব্যাপী মানুষকে সংযুক্ত করে।", slotValues: { THING: "English", SUPERLATIVE: "most widely spoken languages", ACTION: "connects people globally" } },
        { en: "Gold, one of the most precious metals, has been valued for centuries.", bn: "সোনা, সবচেয়ে মূল্যবান ধাতুগুলোর একটি, শতাব্দী ধরে মূল্যবান।", slotValues: { THING: "Gold", SUPERLATIVE: "most precious metals", ACTION: "has been valued for centuries" } },
        { en: "Diabetes, one of the most common diseases, affects millions worldwide.", bn: "ডায়াবেটিস, সবচেয়ে সাধারণ রোগগুলোর একটি, বিশ্বব্যাপী লক্ষ লক্ষ মানুষকে প্রভাবিত করে।", slotValues: { THING: "Diabetes", SUPERLATIVE: "most common diseases", ACTION: "affects millions worldwide" } },
        { en: "The smartphone, one of the most transformative technologies, is now ubiquitous.", bn: "স্মার্টফোন, সবচেয়ে রূপান্তরকারী প্রযুক্তিগুলোর একটি, এখন সর্বব্যাপী।", slotValues: { THING: "The smartphone", SUPERLATIVE: "most transformative technologies", ACTION: "is now ubiquitous" } },
        { en: "Mozart, one of the most brilliant composers, created timeless music.", bn: "মোৎসার্ট, সবচেয়ে মেধাবী সুরকারদের একজন, কালজয়ী সঙ্গীত সৃষ্টি করেছেন।", slotValues: { THING: "Mozart", SUPERLATIVE: "most brilliant composers", ACTION: "created timeless music" } },
        { en: "The printing press, one of the most important inventions, revolutionized knowledge sharing.", bn: "মুদ্রণযন্ত্র, সবচেয়ে গুরুত্বপূর্ণ আবিষ্কারগুলোর একটি, জ্ঞান বিনিময়ে বিপ্লব এনেছে।", slotValues: { THING: "The printing press", SUPERLATIVE: "most important inventions", ACTION: "revolutionized knowledge sharing" } },
        { en: "Honey, one of the healthiest natural sweeteners, has medicinal properties.", bn: "মধু, স্বাস্থ্যকর প্রাকৃতিক মিষ্টিকারকগুলোর একটি, ঔষধি গুণ রয়েছে।", slotValues: { THING: "Honey", SUPERLATIVE: "healthiest natural sweeteners", ACTION: "has medicinal properties" } },
      ],
      formality: "formal",
      difficulty: "advanced",
    },
    {
      id: "S7.4",
      formula: "[PERSON], my [RELATIONSHIP], [ACTION+ED]",
      formula_bn: "[ব্যক্তি], আমার [সম্পর্ক], [ক্রিয়া]",
      patternName: "Appositive with Relationship",
      patternName_bn: "সম্পর্ক সহ সমার্থক পদ",
      slots: [
        { name: "PERSON", description: "A named person", description_bn: "একটি নামযুক্ত ব্যক্তি", acceptedTypes: ["person"], examples: ["Rina", "Alam", "Fatima"] },
        { name: "RELATIONSHIP", description: "The relationship to the speaker", description_bn: "বক্তার সাথে সম্পর্ক", acceptedTypes: ["noun_phrase"], examples: ["best friend", "older sister", "childhood hero"] },
        { name: "ACTION+ED", description: "What the person did", description_bn: "ব্যক্তি কী করেছে", acceptedTypes: ["verb_phrase"], examples: ["moved abroad", "got married", "always supported me"] },
      ],
      examples: [
        { en: "Rina, my best friend, moved to Australia last year.", bn: "রিনা, আমার সবচেয়ে ভালো বন্ধু, গত বছর অস্ট্রেলিয়ায় চলে গেছে।", slotValues: { PERSON: "Rina", RELATIONSHIP: "best friend", "ACTION+ED": "moved to Australia last year" } },
        { en: "Alam, my older brother, always gives me good advice.", bn: "আলম, আমার বড় ভাই, সবসময় আমাকে ভালো পরামর্শ দেয়।", slotValues: { PERSON: "Alam", RELATIONSHIP: "older brother", "ACTION+ED": "always gives me good advice" } },
        { en: "Fatima, my childhood friend, became a successful doctor.", bn: "ফাতিমা, আমার শৈশবের বন্ধু, একজন সফল ডাক্তার হয়েছে।", slotValues: { PERSON: "Fatima", RELATIONSHIP: "childhood friend", "ACTION+ED": "became a successful doctor" } },
        { en: "Sakib, my roommate, cooks the best biryani.", bn: "সাকিব, আমার রুমমেট, সবচেয়ে ভালো বিরিয়ানি রান্না করে।", slotValues: { PERSON: "Sakib", RELATIONSHIP: "roommate", "ACTION+ED": "cooks the best biryani" } },
        { en: "Jaya, my youngest cousin, just got into medical school.", bn: "জয়া, আমার সবচেয়ে ছোট কাজিন, সবেমাত্র মেডিকেল স্কুলে ভর্তি হয়েছে।", slotValues: { PERSON: "Jaya", RELATIONSHIP: "youngest cousin", "ACTION+ED": "just got into medical school" } },
        { en: "Mr. Khan, my first boss, taught me the value of hard work.", bn: "মি. খান, আমার প্রথম বস, আমাকে কঠোর পরিশ্রমের মূল্য শিখিয়েছেন।", slotValues: { PERSON: "Mr. Khan", RELATIONSHIP: "first boss", "ACTION+ED": "taught me the value of hard work" } },
        { en: "Nazmul, my neighbor since childhood, got married last month.", bn: "নাজমুল, আমার শৈশব থেকে প্রতিবেশী, গত মাসে বিয়ে করেছে।", slotValues: { PERSON: "Nazmul", RELATIONSHIP: "neighbor since childhood", "ACTION+ED": "got married last month" } },
        { en: "Amina, my grandmother, tells the most wonderful stories.", bn: "আমিনা, আমার দাদি, সবচেয়ে চমৎকার গল্প বলেন।", slotValues: { PERSON: "Amina", RELATIONSHIP: "grandmother", "ACTION+ED": "tells the most wonderful stories" } },
        { en: "Rafiq, my former classmate, is now a pilot.", bn: "রফিক, আমার সাবেক সহপাঠী, এখন একজন পাইলট।", slotValues: { PERSON: "Rafiq", RELATIONSHIP: "former classmate", "ACTION+ED": "is now a pilot" } },
        { en: "Lipi, my mentor, inspired me to pursue writing.", bn: "লিপি, আমার পরামর্শদাতা, আমাকে লেখালেখি করতে অনুপ্রাণিত করেছেন।", slotValues: { PERSON: "Lipi", RELATIONSHIP: "mentor", "ACTION+ED": "inspired me to pursue writing" } },
        { en: "Arif, my partner, supports all my decisions.", bn: "আরিফ, আমার সঙ্গী, আমার সব সিদ্ধান্তকে সমর্থন করে।", slotValues: { PERSON: "Arif", RELATIONSHIP: "partner", "ACTION+ED": "supports all my decisions" } },
        { en: "Selina, my aunt, raised me like her own child.", bn: "সেলিনা, আমার খালা, আমাকে নিজের সন্তানের মতো বড় করেছেন।", slotValues: { PERSON: "Selina", RELATIONSHIP: "aunt", "ACTION+ED": "raised me like her own child" } },
        { en: "Tanvir, my colleague, always helps me with presentations.", bn: "তানভীর, আমার সহকর্মী, সবসময় আমাকে উপস্থাপনায় সাহায্য করে।", slotValues: { PERSON: "Tanvir", RELATIONSHIP: "colleague", "ACTION+ED": "always helps me with presentations" } },
        { en: "Nusrat, my daughter, won the science competition.", bn: "নুসরাত, আমার মেয়ে, বিজ্ঞান প্রতিযোগিতায় জিতেছে।", slotValues: { PERSON: "Nusrat", RELATIONSHIP: "daughter", "ACTION+ED": "won the science competition" } },
        { en: "Hossain, my father-in-law, is the kindest person I know.", bn: "হোসেন, আমার শ্বশুর, আমি যাদের চিনি তাদের মধ্যে সবচেয়ে দয়ালু।", slotValues: { PERSON: "Hossain", RELATIONSHIP: "father-in-law", "ACTION+ED": "is the kindest person I know" } },
      ],
      formality: "polite",
      difficulty: "advanced",
    },
    {
      id: "S7.5",
      formula: "[EVENT], a [DESCRIPTION], [ACTION]",
      formula_bn: "[ঘটনা], একটি [বর্ণনা], [ক্রিয়া]",
      patternName: "Appositive with Event Description",
      patternName_bn: "ঘটনা বর্ণনা সহ সমার্থক পদ",
      slots: [
        { name: "EVENT", description: "A named event or occasion", description_bn: "একটি নামযুক্ত ঘটনা বা উপলক্ষ", acceptedTypes: ["event", "noun_phrase"], examples: ["The 1971 Liberation War", "Eid", "The World Cup"] },
        { name: "DESCRIPTION", description: "A description of the event", description_bn: "ঘটনার একটি বর্ণনা", acceptedTypes: ["noun_phrase", "description"], examples: ["turning point in history", "celebration of joy", "global sporting event"] },
        { name: "ACTION", description: "What the event does or did", description_bn: "ঘটনা কী করে বা কী করেছে", acceptedTypes: ["verb_phrase", "clause"], examples: ["shaped the nation", "brings families together", "attracts billions of viewers"] },
      ],
      examples: [
        { en: "The 1971 Liberation War, a defining moment in our history, shaped the nation.", bn: "১৯৭১ সালের মুক্তিযুদ্ধ, আমাদের ইতিহাসের একটি সংজ্ঞায়িত মুহূর্ত, জাতিকে গঠন করেছে।", slotValues: { EVENT: "The 1971 Liberation War", DESCRIPTION: "a defining moment in our history", ACTION: "shaped the nation" } },
        { en: "Eid, a celebration of joy and gratitude, brings families together.", bn: "ঈদ, আনন্দ ও কৃতজ্ঞতার উৎসব, পরিবারগুলোকে একত্রিত করে।", slotValues: { EVENT: "Eid", DESCRIPTION: "a celebration of joy and gratitude", ACTION: "brings families together" } },
        { en: "The World Cup, the biggest football tournament, attracts billions of viewers.", bn: "বিশ্বকাপ, সবচেয়ে বড় ফুটবল টুর্নামেন্ট, বিলিয়ন দর্শককে আকৃষ্ট করে।", slotValues: { EVENT: "The World Cup", DESCRIPTION: "the biggest football tournament", ACTION: "attracts billions of viewers" } },
        { en: "Pahela Baishakh, the Bengali New Year, is celebrated with great enthusiasm.", bn: "পহেলা বৈশাখ, বাংলা নববর্ষ, অনেক উৎসাহের সাথে উদযাপিত হয়।", slotValues: { EVENT: "Pahela Baishakh", DESCRIPTION: "the Bengali New Year", ACTION: "is celebrated with great enthusiasm" } },
        { en: "The Industrial Revolution, a period of rapid change, transformed economies worldwide.", bn: "শিল্প বিপ্লব, দ্রুত পরিবর্তনের একটি সময়কাল, বিশ্বব্যাপী অর্থনীতি রূপান্তরিত করেছে।", slotValues: { EVENT: "The Industrial Revolution", DESCRIPTION: "a period of rapid change", ACTION: "transformed economies worldwide" } },
        { en: "Ramadan, a month of fasting and reflection, is observed by Muslims worldwide.", bn: "রমজান, রোজা ও চিন্তার একটি মাস, বিশ্বব্যাপী মুসলমানদের দ্বারা পালিত হয়।", slotValues: { EVENT: "Ramadan", DESCRIPTION: "a month of fasting and reflection", ACTION: "is observed by Muslims worldwide" } },
        { en: "The Olympics, a celebration of athletic excellence, occurs every four years.", bn: "অলিম্পিক, ক্রীড়া শ্রেষ্ঠত্বের উদযাপন, প্রতি চার বছরে অনুষ্ঠিত হয়।", slotValues: { EVENT: "The Olympics", DESCRIPTION: "a celebration of athletic excellence", ACTION: "occurs every four years" } },
        { en: "International Mother Language Day, a tribute to language martyrs, was recognized by UNESCO.", bn: "আন্তর্জাতিক মাতৃভাষা দিবস, ভাষা শহীদদের প্রতি শ্রদ্ধাঞ্জলি, ইউনেস্কো কর্তৃক স্বীকৃত।", slotValues: { EVENT: "International Mother Language Day", DESCRIPTION: "a tribute to language martyrs", ACTION: "was recognized by UNESCO" } },
        { en: "The Renaissance, a cultural rebirth in Europe, produced great art and thinkers.", bn: "রেনেসাঁ, ইউরোপে সাংস্কৃতিক পুনর্জন্ম, মহান শিল্প ও চিন্তাবিদ তৈরি করেছে।", slotValues: { EVENT: "The Renaissance", DESCRIPTION: "a cultural rebirth in Europe", ACTION: "produced great art and thinkers" } },
        { en: "Victory Day, a national holiday in Bangladesh, is celebrated on December 16th.", bn: "বিজয় দিবস, বাংলাদেশের একটি জাতীয় ছুটি, ১৬ ডিসেম্বর পালিত হয়।", slotValues: { EVENT: "Victory Day", DESCRIPTION: "a national holiday in Bangladesh", ACTION: "is celebrated on December 16th" } },
        { en: "The moon landing, a historic achievement, inspired generations.", bn: "চাঁদে অবতরণ, একটি ঐতিহাসিক অর্জন, প্রজন্মকে অনুপ্রাণিত করেছে।", slotValues: { EVENT: "The moon landing", DESCRIPTION: "a historic achievement", ACTION: "inspired generations" } },
        { en: "Durga Puja, a major Hindu festival, is celebrated with elaborate rituals.", bn: "দুর্গাপূজা, একটি প্রধান হিন্দু উৎসব, বিশদ আচার-অনুষ্ঠানের সাথে উদযাপিত হয়।", slotValues: { EVENT: "Durga Puja", DESCRIPTION: "a major Hindu festival", ACTION: "is celebrated with elaborate rituals" } },
        { en: "The pandemic, a global health crisis, affected every country.", bn: "মহামারী, একটি বৈশ্বিক স্বাস্থ্য সংকট, প্রতিটি দেশকে প্রভাবিত করেছে।", slotValues: { EVENT: "The pandemic", DESCRIPTION: "a global health crisis", ACTION: "affected every country" } },
        { en: "The book fair, an annual literary event, promotes reading culture.", bn: "বইমেলা, একটি বার্ষিক সাহিত্য অনুষ্ঠান, পড়ার সংস্কৃতিকে উন্নীত করে।", slotValues: { EVENT: "The book fair", DESCRIPTION: "an annual literary event", ACTION: "promotes reading culture" } },
        { en: "Graduation day, a milestone in every student's life, was unforgettable.", bn: "স্নাতক দিবস, প্রতিটি ছাত্রের জীবনের একটি মাইলফলক, অবিস্মরণীয় ছিল।", slotValues: { EVENT: "Graduation day", DESCRIPTION: "a milestone in every student's life", ACTION: "was unforgettable" } },
      ],
      formality: "formal",
      difficulty: "advanced",
    },
  ],
};
