import { PatternCategory } from "@/types/pattern";

export const categoryT12: PatternCategory = {
  id: "T12",
  slug: "technology",
  name: "Technology",
  name_bn: "প্রযুক্তি",
  description:
    "Learn how to talk about tech issues, devices, and digital tasks in English.",
  description_bn:
    "ইংরেজিতে প্রযুক্তি সমস্যা, ডিভাইস এবং ডিজিটাল কাজ নিয়ে কথা বলতে শিখুন।",
  icon: "💻",
  group: "T",
  groupName: "Situational Patterns",
  groupName_bn: "পরিস্থিতিগত প্যাটার্ন",
  difficulty: "intermediate",
  patterns: [
    {
      id: "T12.1",
      formula: "[THING] isn't working",
      formula_bn: "[জিনিস] কাজ করছে না",
      patternName: "Reporting a Tech Problem",
      patternName_bn: "প্রযুক্তি সমস্যা জানানো",
      slots: [
        { name: "THING", description: "The device or feature that has stopped working", description_bn: "যে ডিভাইস বা ফিচার কাজ বন্ধ করেছে", acceptedTypes: ["noun", "noun_phrase"], examples: ["my phone", "the wifi", "the printer"] },
      ],
      examples: [
        { en: "My phone isn't working.", bn: "আমার ফোন কাজ করছে না।", slotValues: { THING: "My phone" }, topicArea: "daily_life" },
        { en: "The wifi isn't working.", bn: "ওয়াইফাই কাজ করছে না।", slotValues: { THING: "The wifi" }, topicArea: "daily_life" },
        { en: "The printer isn't working.", bn: "প্রিন্টার কাজ করছে না।", slotValues: { THING: "The printer" }, topicArea: "work" },
        { en: "My laptop isn't working.", bn: "আমার ল্যাপটপ কাজ করছে না।", slotValues: { THING: "My laptop" }, topicArea: "work" },
        { en: "The microphone isn't working.", bn: "মাইক্রোফোন কাজ করছে না।", slotValues: { THING: "The microphone" }, topicArea: "work" },
        { en: "The app isn't working.", bn: "অ্যাপটি কাজ করছে না।", slotValues: { THING: "The app" }, topicArea: "daily_life" },
        { en: "The camera isn't working.", bn: "ক্যামেরা কাজ করছে না।", slotValues: { THING: "The camera" }, topicArea: "daily_life" },
        { en: "The AC isn't working.", bn: "এসি কাজ করছে না।", slotValues: { THING: "The AC" }, topicArea: "daily_life" },
        { en: "My charger isn't working.", bn: "আমার চার্জার কাজ করছে না।", slotValues: { THING: "My charger" }, topicArea: "daily_life" },
        { en: "The Bluetooth isn't working.", bn: "ব্লুটুথ কাজ করছে না।", slotValues: { THING: "The Bluetooth" }, topicArea: "daily_life" },
        { en: "The projector isn't working.", bn: "প্রজেক্টর কাজ করছে না।", slotValues: { THING: "The projector" }, topicArea: "education" },
        { en: "The speaker isn't working.", bn: "স্পিকার কাজ করছে না।", slotValues: { THING: "The speaker" }, topicArea: "daily_life" },
        { en: "The GPS isn't working.", bn: "জিপিএস কাজ করছে না।", slotValues: { THING: "The GPS" }, topicArea: "travel" },
        { en: "The remote control isn't working.", bn: "রিমোট কন্ট্রোল কাজ করছে না।", slotValues: { THING: "The remote control" }, topicArea: "daily_life" },
        { en: "My mouse isn't working.", bn: "আমার মাউস কাজ করছে না।", slotValues: { THING: "My mouse" }, topicArea: "work" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "A simple and direct way to report that something is broken or malfunctioning. Very common in daily life.",
      usageNote_bn: "কিছু ভাঙা বা ত্রুটিপূর্ণ বলার একটি সহজ ও সরাসরি উপায়। দৈনন্দিন জীবনে খুবই সাধারণ।",
      combinableWith: ["T12.2"],
      banglaStructureMap: "[THING] (Subject) + কাজ করছে না (Verb - Negative Progressive)",
    },
    {
      id: "T12.2",
      formula: "How do I [ACTION] on [DEVICE]?",
      formula_bn: "[ডিভাইসে] কীভাবে [কাজ] করব?",
      patternName: "Asking for Tech Help",
      patternName_bn: "প্রযুক্তি সাহায্য চাওয়া",
      slots: [
        { name: "ACTION", description: "The task or action you want to perform", description_bn: "যে কাজ আপনি করতে চান", acceptedTypes: ["verb_phrase", "to_verb"], examples: ["change the password", "take a screenshot", "connect"] },
        { name: "DEVICE", description: "The device or platform you are using", description_bn: "যে ডিভাইস বা প্ল্যাটফর্ম আপনি ব্যবহার করছেন", acceptedTypes: ["noun", "noun_phrase"], examples: ["my phone", "this computer", "WhatsApp"] },
      ],
      examples: [
        { en: "How do I change the password on my phone?", bn: "আমার ফোনে কীভাবে পাসওয়ার্ড পরিবর্তন করব?", slotValues: { ACTION: "change the password", DEVICE: "my phone" }, topicArea: "daily_life" },
        { en: "How do I take a screenshot on this computer?", bn: "এই কম্পিউটারে কীভাবে স্ক্রিনশট নেব?", slotValues: { ACTION: "take a screenshot", DEVICE: "this computer" }, topicArea: "work" },
        { en: "How do I connect to the wifi on my laptop?", bn: "আমার ল্যাপটপে কীভাবে ওয়াইফাই কানেক্ট করব?", slotValues: { ACTION: "connect to the wifi", DEVICE: "my laptop" }, topicArea: "daily_life" },
        { en: "How do I send a file on WhatsApp?", bn: "হোয়াটসঅ্যাপে কীভাবে ফাইল পাঠাব?", slotValues: { ACTION: "send a file", DEVICE: "WhatsApp" }, topicArea: "daily_life" },
        { en: "How do I update the software on my phone?", bn: "আমার ফোনে কীভাবে সফটওয়্যার আপডেট করব?", slotValues: { ACTION: "update the software", DEVICE: "my phone" }, topicArea: "daily_life" },
        { en: "How do I print a document on this printer?", bn: "এই প্রিন্টারে কীভাবে ডকুমেন্ট প্রিন্ট করব?", slotValues: { ACTION: "print a document", DEVICE: "this printer" }, topicArea: "work" },
        { en: "How do I create a group on Messenger?", bn: "মেসেঞ্জারে কীভাবে গ্রুপ তৈরি করব?", slotValues: { ACTION: "create a group", DEVICE: "Messenger" }, topicArea: "daily_life" },
        { en: "How do I download an app on my tablet?", bn: "আমার ট্যাবলেটে কীভাবে অ্যাপ ডাউনলোড করব?", slotValues: { ACTION: "download an app", DEVICE: "my tablet" }, topicArea: "daily_life" },
        { en: "How do I set an alarm on my phone?", bn: "আমার ফোনে কীভাবে অ্যালার্ম সেট করব?", slotValues: { ACTION: "set an alarm", DEVICE: "my phone" }, topicArea: "daily_life" },
        { en: "How do I delete a file on this computer?", bn: "এই কম্পিউটারে কীভাবে ফাইল ডিলিট করব?", slotValues: { ACTION: "delete a file", DEVICE: "this computer" }, topicArea: "work" },
        { en: "How do I zoom in on Google Maps?", bn: "গুগল ম্যাপসে কীভাবে জুম ইন করব?", slotValues: { ACTION: "zoom in", DEVICE: "Google Maps" }, topicArea: "travel" },
        { en: "How do I record a video on my camera?", bn: "আমার ক্যামেরায় কীভাবে ভিডিও রেকর্ড করব?", slotValues: { ACTION: "record a video", DEVICE: "my camera" }, topicArea: "daily_life" },
        { en: "How do I share my screen on Zoom?", bn: "জুমে কীভাবে স্ক্রিন শেয়ার করব?", slotValues: { ACTION: "share my screen", DEVICE: "Zoom" }, topicArea: "work" },
        { en: "How do I transfer photos on this USB?", bn: "এই ইউএসবিতে কীভাবে ছবি ট্রান্সফার করব?", slotValues: { ACTION: "transfer photos", DEVICE: "this USB" }, topicArea: "daily_life" },
        { en: "How do I change the language on my phone?", bn: "আমার ফোনে কীভাবে ভাষা পরিবর্তন করব?", slotValues: { ACTION: "change the language", DEVICE: "my phone" }, topicArea: "daily_life" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "A practical question format for getting tech support. Works for any device or platform.",
      usageNote_bn: "প্রযুক্তি সহায়তা পাওয়ার জন্য একটি ব্যবহারিক প্রশ্নের ফর্ম্যাট। যেকোনো ডিভাইস বা প্ল্যাটফর্মের জন্য কাজ করে।",
      combinableWith: ["T12.1"],
      banglaStructureMap: "[DEVICE]-এ (Device + Postposition) + কীভাবে (Question word) + [ACTION] (Verb phrase) + করব (Verb - Future)?",
    },
    {
      id: "T12.3",
      formula: "I need to charge my [DEVICE]",
      formula_bn: "আমার [ডিভাইস] চার্জ দিতে হবে",
      patternName: "Charging Devices",
      patternName_bn: "ডিভাইস চার্জ দেওয়া",
      slots: [
        { name: "DEVICE", description: "The electronic device that needs charging", description_bn: "যে ইলেকট্রনিক ডিভাইসে চার্জ দিতে হবে", acceptedTypes: ["noun", "noun_phrase"], examples: ["phone", "laptop", "earbuds"] },
      ],
      examples: [
        { en: "I need to charge my phone.", bn: "আমার ফোন চার্জ দিতে হবে।", slotValues: { DEVICE: "phone" }, topicArea: "daily_life" },
        { en: "I need to charge my laptop.", bn: "আমার ল্যাপটপ চার্জ দিতে হবে।", slotValues: { DEVICE: "laptop" }, topicArea: "work" },
        { en: "I need to charge my earbuds.", bn: "আমার ইয়ারবাড চার্জ দিতে হবে।", slotValues: { DEVICE: "earbuds" }, topicArea: "daily_life" },
        { en: "I need to charge my smartwatch.", bn: "আমার স্মার্টওয়াচ চার্জ দিতে হবে।", slotValues: { DEVICE: "smartwatch" }, topicArea: "daily_life" },
        { en: "I need to charge my tablet.", bn: "আমার ট্যাবলেট চার্জ দিতে হবে।", slotValues: { DEVICE: "tablet" }, topicArea: "daily_life" },
        { en: "I need to charge my power bank.", bn: "আমার পাওয়ার ব্যাংক চার্জ দিতে হবে।", slotValues: { DEVICE: "power bank" }, topicArea: "travel" },
        { en: "I need to charge my camera.", bn: "আমার ক্যামেরা চার্জ দিতে হবে।", slotValues: { DEVICE: "camera" }, topicArea: "travel" },
        { en: "I need to charge my Bluetooth speaker.", bn: "আমার ব্লুটুথ স্পিকার চার্জ দিতে হবে।", slotValues: { DEVICE: "Bluetooth speaker" }, topicArea: "daily_life" },
        { en: "I need to charge my electric toothbrush.", bn: "আমার ইলেকট্রিক টুথব্রাশ চার্জ দিতে হবে।", slotValues: { DEVICE: "electric toothbrush" }, topicArea: "health" },
        { en: "I need to charge my kindle.", bn: "আমার কিন্ডল চার্জ দিতে হবে।", slotValues: { DEVICE: "kindle" }, topicArea: "education" },
        { en: "I need to charge my wireless mouse.", bn: "আমার ওয়্যারলেস মাউস চার্জ দিতে হবে।", slotValues: { DEVICE: "wireless mouse" }, topicArea: "work" },
        { en: "I need to charge my gaming controller.", bn: "আমার গেমিং কন্ট্রোলার চার্জ দিতে হবে।", slotValues: { DEVICE: "gaming controller" }, topicArea: "daily_life" },
        { en: "I need to charge my drone.", bn: "আমার ড্রোন চার্জ দিতে হবে।", slotValues: { DEVICE: "drone" }, topicArea: "daily_life" },
        { en: "I need to charge my headphones.", bn: "আমার হেডফোন চার্জ দিতে হবে।", slotValues: { DEVICE: "headphones" }, topicArea: "daily_life" },
        { en: "I need to charge my electric scooter.", bn: "আমার ইলেকট্রিক স্কুটার চার্জ দিতে হবে।", slotValues: { DEVICE: "electric scooter" }, topicArea: "travel" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "A very common everyday phrase. Useful when looking for a charger or power outlet.",
      usageNote_bn: "একটি খুবই সাধারণ দৈনন্দিন বাক্যাংশ। চার্জার বা পাওয়ার আউটলেট খোঁজার সময় উপযোগী।",
      combinableWith: ["T12.1"],
      banglaStructureMap: "আমার (Subject + Possessive) + [DEVICE] (Object) + চার্জ দিতে হবে (Verb + Need)",
    },
    {
      id: "T12.4",
      formula: "Can you help me with [TECH ISSUE]?",
      formula_bn: "আপনি কি আমাকে [প্রযুক্তি সমস্যায়] সাহায্য করতে পারবেন?",
      patternName: "Requesting Tech Support",
      patternName_bn: "প্রযুক্তি সহায়তা চাওয়া",
      slots: [
        { name: "TECH ISSUE", description: "The technical problem or task you need help with", description_bn: "যে প্রযুক্তি সমস্যা বা কাজে আপনার সাহায্য দরকার", acceptedTypes: ["noun", "noun_phrase", "gerund"], examples: ["setting up my email", "this error message", "installing the software"] },
      ],
      examples: [
        { en: "Can you help me with setting up my email?", bn: "আপনি কি আমাকে ইমেইল সেটআপ করতে সাহায্য করতে পারবেন?", slotValues: { "TECH ISSUE": "setting up my email" }, topicArea: "work" },
        { en: "Can you help me with this error message?", bn: "আপনি কি আমাকে এই এরর মেসেজ নিয়ে সাহায্য করতে পারবেন?", slotValues: { "TECH ISSUE": "this error message" }, topicArea: "daily_life" },
        { en: "Can you help me with installing the software?", bn: "আপনি কি আমাকে সফটওয়্যার ইনস্টল করতে সাহায্য করতে পারবেন?", slotValues: { "TECH ISSUE": "installing the software" }, topicArea: "work" },
        { en: "Can you help me with connecting to the wifi?", bn: "আপনি কি আমাকে ওয়াইফাই কানেক্ট করতে সাহায্য করতে পারবেন?", slotValues: { "TECH ISSUE": "connecting to the wifi" }, topicArea: "daily_life" },
        { en: "Can you help me with transferring my data?", bn: "আপনি কি আমাকে ডাটা ট্রান্সফার করতে সাহায্য করতে পারবেন?", slotValues: { "TECH ISSUE": "transferring my data" }, topicArea: "daily_life" },
        { en: "Can you help me with this spreadsheet?", bn: "আপনি কি আমাকে এই স্প্রেডশিট নিয়ে সাহায্য করতে পারবেন?", slotValues: { "TECH ISSUE": "this spreadsheet" }, topicArea: "work" },
        { en: "Can you help me with resetting my password?", bn: "আপনি কি আমাকে পাসওয়ার্ড রিসেট করতে সাহায্য করতে পারবেন?", slotValues: { "TECH ISSUE": "resetting my password" }, topicArea: "daily_life" },
        { en: "Can you help me with backing up my files?", bn: "আপনি কি আমাকে ফাইল ব্যাকআপ করতে সাহায্য করতে পারবেন?", slotValues: { "TECH ISSUE": "backing up my files" }, topicArea: "work" },
        { en: "Can you help me with updating my phone?", bn: "আপনি কি আমাকে ফোন আপডেট করতে সাহায্য করতে পারবেন?", slotValues: { "TECH ISSUE": "updating my phone" }, topicArea: "daily_life" },
        { en: "Can you help me with creating a presentation?", bn: "আপনি কি আমাকে প্রেজেন্টেশন তৈরি করতে সাহায্য করতে পারবেন?", slotValues: { "TECH ISSUE": "creating a presentation" }, topicArea: "education" },
        { en: "Can you help me with fixing the printer?", bn: "আপনি কি আমাকে প্রিন্টার ঠিক করতে সাহায্য করতে পারবেন?", slotValues: { "TECH ISSUE": "fixing the printer" }, topicArea: "work" },
        { en: "Can you help me with this online form?", bn: "আপনি কি আমাকে এই অনলাইন ফর্ম নিয়ে সাহায্য করতে পারবেন?", slotValues: { "TECH ISSUE": "this online form" }, topicArea: "daily_life" },
        { en: "Can you help me with booking tickets online?", bn: "আপনি কি আমাকে অনলাইনে টিকেট বুক করতে সাহায্য করতে পারবেন?", slotValues: { "TECH ISSUE": "booking tickets online" }, topicArea: "travel" },
        { en: "Can you help me with using this new app?", bn: "আপনি কি আমাকে এই নতুন অ্যাপ ব্যবহার করতে সাহায্য করতে পারবেন?", slotValues: { "TECH ISSUE": "using this new app" }, topicArea: "daily_life" },
        { en: "Can you help me with removing a virus?", bn: "আপনি কি আমাকে ভাইরাস রিমুভ করতে সাহায্য করতে পারবেন?", slotValues: { "TECH ISSUE": "removing a virus" }, topicArea: "daily_life" },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote: "A polite way to ask for technical assistance from a friend, colleague, or support agent.",
      usageNote_bn: "বন্ধু, সহকর্মী বা সাপোর্ট এজেন্টের কাছে প্রযুক্তিগত সহায়তা চাওয়ার বিনয়ী উপায়।",
      combinableWith: ["T12.1"],
      banglaStructureMap: "আপনি কি (Subject + Question) + আমাকে (Indirect Object) + [TECH ISSUE] (Topic) + সাহায্য করতে পারবেন (Verb)?",
    },
    {
      id: "T12.5",
      formula: "I just downloaded [APP/SOFTWARE]",
      formula_bn: "আমি এইমাত্র [অ্যাপ/সফটওয়্যার] ডাউনলোড করেছি",
      patternName: "Sharing Tech Updates",
      patternName_bn: "প্রযুক্তি আপডেট শেয়ার",
      slots: [
        { name: "APP/SOFTWARE", description: "The app, software, or digital tool you downloaded", description_bn: "যে অ্যাপ, সফটওয়্যার বা ডিজিটাল টুল আপনি ডাউনলোড করেছেন", acceptedTypes: ["noun", "noun_phrase"], examples: ["a new game", "the latest update", "a language app"] },
      ],
      examples: [
        { en: "I just downloaded a new game.", bn: "আমি এইমাত্র একটি নতুন গেম ডাউনলোড করেছি।", slotValues: { "APP/SOFTWARE": "a new game" }, topicArea: "daily_life" },
        { en: "I just downloaded the latest update.", bn: "আমি এইমাত্র সর্বশেষ আপডেট ডাউনলোড করেছি।", slotValues: { "APP/SOFTWARE": "the latest update" }, topicArea: "daily_life" },
        { en: "I just downloaded a language learning app.", bn: "আমি এইমাত্র একটি ভাষা শেখার অ্যাপ ডাউনলোড করেছি।", slotValues: { "APP/SOFTWARE": "a language learning app" }, topicArea: "education" },
        { en: "I just downloaded a fitness tracker.", bn: "আমি এইমাত্র একটি ফিটনেস ট্র্যাকার ডাউনলোড করেছি।", slotValues: { "APP/SOFTWARE": "a fitness tracker" }, topicArea: "health" },
        { en: "I just downloaded a recipe app.", bn: "আমি এইমাত্র একটি রেসিপি অ্যাপ ডাউনলোড করেছি।", slotValues: { "APP/SOFTWARE": "a recipe app" }, topicArea: "food" },
        { en: "I just downloaded a travel guide app.", bn: "আমি এইমাত্র একটি ট্রাভেল গাইড অ্যাপ ডাউনলোড করেছি।", slotValues: { "APP/SOFTWARE": "a travel guide app" }, topicArea: "travel" },
        { en: "I just downloaded Microsoft Office.", bn: "আমি এইমাত্র মাইক্রোসফট অফিস ডাউনলোড করেছি।", slotValues: { "APP/SOFTWARE": "Microsoft Office" }, topicArea: "work" },
        { en: "I just downloaded a photo editing app.", bn: "আমি এইমাত্র একটি ফটো এডিটিং অ্যাপ ডাউনলোড করেছি।", slotValues: { "APP/SOFTWARE": "a photo editing app" }, topicArea: "daily_life" },
        { en: "I just downloaded a meditation app.", bn: "আমি এইমাত্র একটি মেডিটেশন অ্যাপ ডাউনলোড করেছি।", slotValues: { "APP/SOFTWARE": "a meditation app" }, topicArea: "health" },
        { en: "I just downloaded Zoom.", bn: "আমি এইমাত্র জুম ডাউনলোড করেছি।", slotValues: { "APP/SOFTWARE": "Zoom" }, topicArea: "work" },
        { en: "I just downloaded a budgeting app.", bn: "আমি এইমাত্র একটি বাজেটিং অ্যাপ ডাউনলোড করেছি।", slotValues: { "APP/SOFTWARE": "a budgeting app" }, topicArea: "daily_life" },
        { en: "I just downloaded a music streaming app.", bn: "আমি এইমাত্র একটি মিউজিক স্ট্রিমিং অ্যাপ ডাউনলোড করেছি।", slotValues: { "APP/SOFTWARE": "a music streaming app" }, topicArea: "daily_life" },
        { en: "I just downloaded an antivirus program.", bn: "আমি এইমাত্র একটি অ্যান্টিভাইরাস প্রোগ্রাম ডাউনলোড করেছি।", slotValues: { "APP/SOFTWARE": "an antivirus program" }, topicArea: "daily_life" },
        { en: "I just downloaded a shopping app.", bn: "আমি এইমাত্র একটি শপিং অ্যাপ ডাউনলোড করেছি।", slotValues: { "APP/SOFTWARE": "a shopping app" }, topicArea: "shopping" },
        { en: "I just downloaded a ride-sharing app.", bn: "আমি এইমাত্র একটি রাইড-শেয়ারিং অ্যাপ ডাউনলোড করেছি।", slotValues: { "APP/SOFTWARE": "a ride-sharing app" }, topicArea: "travel" },
      ],
      formality: "casual",
      difficulty: "intermediate",
      usageNote: "A casual way to share that you have installed something new. Great for recommending apps or software.",
      usageNote_bn: "নতুন কিছু ইনস্টল করেছেন তা শেয়ার করার অনানুষ্ঠানিক উপায়। অ্যাপ বা সফটওয়্যার সুপারিশ করার জন্য দুর্দান্ত।",
      combinableWith: ["T12.2"],
      banglaStructureMap: "আমি (Subject) + এইমাত্র (Time adverb) + [APP/SOFTWARE] (Object) + ডাউনলোড করেছি (Verb - Past)",
    },
  ],
};
