import { PatternCategory } from "@/types/pattern";

export const categoryT33: PatternCategory = {
  id: "T33",
  slug: "housing-rent",
  name: "Housing & Rent",
  name_bn: "বাসস্থান ও ভাড়া",
  description:
    "Patterns for finding housing, discussing rent, dealing with landlords, and home maintenance.",
  description_bn:
    "বাসস্থান খোঁজা, ভাড়া আলোচনা, বাড়িওয়ালার সাথে কথা বলা এবং বাড়ি রক্ষণাবেক্ষণের প্যাটার্ন।",
  icon: "🏠",
  group: "T",
  groupName: "Situational Patterns",
  groupName_bn: "পরিস্থিতিগত প্যাটার্ন",
  difficulty: "beginner",
  patterns: [
    {
      id: "T33.1",
      formula: "I'm looking for a [TYPE] apartment in [AREA]",
      formula_bn: "আমি [এলাকায়] একটি [ধরনের] অ্যাপার্টমেন্ট খুঁজছি",
      patternName: "Apartment Inquiry",
      patternName_bn: "অ্যাপার্টমেন্ট অনুসন্ধান",
      slots: [
        {
          name: "TYPE",
          description: "The type or size of apartment",
          description_bn: "অ্যাপার্টমেন্টের ধরন বা আকার",
          acceptedTypes: ["noun", "noun_phrase", "adjective"],
          examples: ["two-bedroom", "furnished", "studio"],
        },
        {
          name: "AREA",
          description: "The neighborhood or area",
          description_bn: "পাড়া বা এলাকা",
          acceptedTypes: ["place", "noun_phrase"],
          examples: ["downtown", "near the university", "a quiet neighborhood"],
        },
      ],
      examples: [
        {
          en: "I'm looking for a two-bedroom apartment in downtown.",
          bn: "আমি ডাউনটাউনে একটি দুই বেডরুমের অ্যাপার্টমেন্ট খুঁজছি।",
          slotValues: { TYPE: "two-bedroom", AREA: "downtown" },
          topicArea: "housing",
        },
        {
          en: "I'm looking for a furnished apartment near the university.",
          bn: "আমি বিশ্ববিদ্যালয়ের কাছে একটি আসবাবপত্র সহ অ্যাপার্টমেন্ট খুঁজছি।",
          slotValues: { TYPE: "furnished", AREA: "near the university" },
          topicArea: "housing",
        },
        {
          en: "Is this apartment still available?",
          bn: "এই অ্যাপার্টমেন্টটি কি এখনো পাওয়া যায়?",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "I'm looking for a studio apartment in a quiet neighborhood.",
          bn: "আমি একটি শান্ত পাড়ায় একটি স্টুডিও অ্যাপার্টমেন্ট খুঁজছি।",
          slotValues: { TYPE: "studio", AREA: "a quiet neighborhood" },
          topicArea: "housing",
        },
        {
          en: "Can I schedule a viewing of the apartment?",
          bn: "আমি কি অ্যাপার্টমেন্ট দেখার জন্য একটি সময় ঠিক করতে পারি?",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "Does the apartment come with parking?",
          bn: "অ্যাপার্টমেন্টের সাথে কি পার্কিং আছে?",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "I'm looking for a pet-friendly apartment.",
          bn: "আমি পোষা প্রাণী রাখা যায় এমন একটি অ্যাপার্টমেন্ট খুঁজছি।",
          slotValues: { TYPE: "pet-friendly" },
          topicArea: "housing",
        },
        {
          en: "How many square feet is this apartment?",
          bn: "এই অ্যাপার্টমেন্ট কত বর্গফুট?",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "Is there a washer and dryer in the unit?",
          bn: "ইউনিটে কি ওয়াশিং মেশিন ও ড্রায়ার আছে?",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "I'm looking for a one-bedroom apartment near public transit.",
          bn: "আমি গণপরিবহনের কাছে একটি এক বেডরুমের অ্যাপার্টমেন্ট খুঁজছি।",
          slotValues: { TYPE: "one-bedroom", AREA: "near public transit" },
          topicArea: "housing",
        },
        {
          en: "What floor is the apartment on?",
          bn: "অ্যাপার্টমেন্টটি কত তলায়?",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "I need an apartment with at least two bathrooms.",
          bn: "আমার অন্তত দুটি বাথরুম সহ একটি অ্যাপার্টমেন্ট দরকার।",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "Is the apartment available from next month?",
          bn: "অ্যাপার্টমেন্টটি কি আগামী মাস থেকে পাওয়া যাবে?",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "I'm looking for a three-bedroom house in the suburbs.",
          bn: "আমি শহরতলিতে একটি তিন বেডরুমের বাড়ি খুঁজছি।",
          slotValues: { TYPE: "three-bedroom", AREA: "the suburbs" },
          topicArea: "housing",
        },
        {
          en: "Does the building have an elevator?",
          bn: "বিল্ডিংয়ে কি লিফট আছে?",
          slotValues: {},
          topicArea: "housing",
        },
      ],
      formality: "polite",
      difficulty: "beginner",
      usageNote:
        "Used when searching for a new place to live, talking to real estate agents, or browsing listings.",
      usageNote_bn:
        "নতুন বাসস্থান খোঁজার সময়, রিয়েল এস্টেট এজেন্টের সাথে কথা বলার সময়, বা তালিকা দেখার সময় ব্যবহৃত হয়।",
      combinableWith: ["T33.2"],
      banglaStructureMap:
        "আমি (Subject) + [এলাকায়] (Location + Postposition) + একটি [TYPE] অ্যাপার্টমেন্ট (Object) + খুঁজছি (Verb)",
    },
    {
      id: "T33.2",
      formula: "How much is the rent for [PROPERTY]?",
      formula_bn: "[সম্পত্তি]-এর ভাড়া কত?",
      patternName: "Rent Discussion",
      patternName_bn: "ভাড়া আলোচনা",
      slots: [
        {
          name: "PROPERTY",
          description: "The property or unit being rented",
          description_bn: "যে সম্পত্তি বা ইউনিট ভাড়া নেওয়া হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["this apartment", "the studio", "the two-bedroom unit"],
        },
      ],
      examples: [
        {
          en: "How much is the rent for this apartment?",
          bn: "এই অ্যাপার্টমেন্টের ভাড়া কত?",
          slotValues: { PROPERTY: "this apartment" },
          topicArea: "housing",
        },
        {
          en: "How much is the security deposit?",
          bn: "নিরাপত্তা জামানত কত?",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "Are utilities included in the rent?",
          bn: "ভাড়ার মধ্যে কি ইউটিলিটি অন্তর্ভুক্ত?",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "How long is the lease term?",
          bn: "লিজের মেয়াদ কতদিন?",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "Is the rent negotiable?",
          bn: "ভাড়া কি আলোচনাসাপেক্ষ?",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "How much is the rent for the studio on the second floor?",
          bn: "দ্বিতীয় তলার স্টুডিওর ভাড়া কত?",
          slotValues: { PROPERTY: "the studio on the second floor" },
          topicArea: "housing",
        },
        {
          en: "When is the rent due each month?",
          bn: "প্রতি মাসে ভাড়া কবে দিতে হয়?",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "Is there a late fee for paying rent after the due date?",
          bn: "নির্ধারিত তারিখের পরে ভাড়া দিলে কি বিলম্ব ফি আছে?",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "Does the rent increase every year?",
          bn: "প্রতি বছর কি ভাড়া বাড়ে?",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "Can I pay the rent online?",
          bn: "আমি কি অনলাইনে ভাড়া দিতে পারি?",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "How much is the rent for the two-bedroom unit?",
          bn: "দুই বেডরুম ইউনিটের ভাড়া কত?",
          slotValues: { PROPERTY: "the two-bedroom unit" },
          topicArea: "housing",
        },
        {
          en: "What is the penalty for breaking the lease early?",
          bn: "আগে লিজ ভাঙলে জরিমানা কত?",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "Do I need to pay first and last month's rent upfront?",
          bn: "আমাকে কি আগে থেকে প্রথম ও শেষ মাসের ভাড়া দিতে হবে?",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "Is there a discount for signing a longer lease?",
          bn: "দীর্ঘ মেয়াদের লিজ সাইন করলে কি ছাড় আছে?",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "How much are the average monthly utility costs?",
          bn: "গড় মাসিক ইউটিলিটি খরচ কত?",
          slotValues: {},
          topicArea: "housing",
        },
      ],
      formality: "polite",
      difficulty: "beginner",
      usageNote:
        "Used when discussing rental costs, lease terms, and financial aspects of renting a property.",
      usageNote_bn:
        "ভাড়ার খরচ, লিজের শর্তাবলি এবং সম্পত্তি ভাড়া নেওয়ার আর্থিক বিষয়গুলো আলোচনা করতে ব্যবহৃত হয়।",
      combinableWith: ["T33.1", "T33.4"],
      banglaStructureMap:
        "[সম্পত্তি]-এর (Object + Possessive) + ভাড়া (Subject) + কত (Question word)?",
    },
    {
      id: "T33.3",
      formula: "The [THING] in my apartment is [PROBLEM]",
      formula_bn: "আমার অ্যাপার্টমেন্টের [জিনিস] [সমস্যা]",
      patternName: "Maintenance Issues",
      patternName_bn: "রক্ষণাবেক্ষণ সমস্যা",
      slots: [
        {
          name: "THING",
          description: "The item or fixture that has a problem",
          description_bn: "যে জিনিস বা ফিক্সচারে সমস্যা আছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["faucet", "AC", "toilet"],
        },
        {
          name: "PROBLEM",
          description: "The issue or malfunction",
          description_bn: "সমস্যা বা ত্রুটি",
          acceptedTypes: ["adjective", "adjective_phrase", "description"],
          examples: ["leaking", "not working", "broken"],
        },
      ],
      examples: [
        {
          en: "The faucet in my apartment is leaking.",
          bn: "আমার অ্যাপার্টমেন্টের কল থেকে পানি পড়ছে।",
          slotValues: { THING: "faucet", PROBLEM: "leaking" },
          topicArea: "housing",
        },
        {
          en: "The AC is not working properly.",
          bn: "এসি ঠিকমতো কাজ করছে না।",
          slotValues: { THING: "AC", PROBLEM: "not working properly" },
          topicArea: "housing",
        },
        {
          en: "The toilet is clogged.",
          bn: "টয়লেট বন্ধ হয়ে গেছে।",
          slotValues: { THING: "toilet", PROBLEM: "clogged" },
          topicArea: "housing",
        },
        {
          en: "The light in the kitchen is broken.",
          bn: "রান্নাঘরের বাতি নষ্ট হয়ে গেছে।",
          slotValues: { THING: "light in the kitchen", PROBLEM: "broken" },
          topicArea: "housing",
        },
        {
          en: "The heater in the bedroom is not turning on.",
          bn: "বেডরুমের হিটার চালু হচ্ছে না।",
          slotValues: { THING: "heater in the bedroom", PROBLEM: "not turning on" },
          topicArea: "housing",
        },
        {
          en: "The window in the living room is stuck.",
          bn: "বসার ঘরের জানালা আটকে গেছে।",
          slotValues: { THING: "window in the living room", PROBLEM: "stuck" },
          topicArea: "housing",
        },
        {
          en: "The ceiling is leaking when it rains.",
          bn: "বৃষ্টি হলে ছাদ থেকে পানি পড়ে।",
          slotValues: { THING: "ceiling", PROBLEM: "leaking when it rains" },
          topicArea: "housing",
        },
        {
          en: "The refrigerator is making a strange noise.",
          bn: "ফ্রিজ অদ্ভুত শব্দ করছে।",
          slotValues: { THING: "refrigerator", PROBLEM: "making a strange noise" },
          topicArea: "housing",
        },
        {
          en: "The front door lock is jammed.",
          bn: "সামনের দরজার তালা আটকে গেছে।",
          slotValues: { THING: "front door lock", PROBLEM: "jammed" },
          topicArea: "housing",
        },
        {
          en: "The hot water is not working in the bathroom.",
          bn: "বাথরুমে গরম পানি আসছে না।",
          slotValues: { THING: "hot water", PROBLEM: "not working in the bathroom" },
          topicArea: "housing",
        },
        {
          en: "The garbage disposal is broken.",
          bn: "গারবেজ ডিসপোজাল নষ্ট হয়ে গেছে।",
          slotValues: { THING: "garbage disposal", PROBLEM: "broken" },
          topicArea: "housing",
        },
        {
          en: "The smoke detector keeps beeping.",
          bn: "স্মোক ডিটেক্টর ক্রমাগত বিপ করছে।",
          slotValues: { THING: "smoke detector", PROBLEM: "keeps beeping" },
          topicArea: "housing",
        },
        {
          en: "There are ants coming through the kitchen wall.",
          bn: "রান্নাঘরের দেয়াল দিয়ে পিঁপড়া আসছে।",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "The washing machine is overflowing.",
          bn: "ওয়াশিং মেশিন থেকে পানি উপচে পড়ছে।",
          slotValues: { THING: "washing machine", PROBLEM: "overflowing" },
          topicArea: "housing",
        },
        {
          en: "The paint on the walls is peeling off.",
          bn: "দেয়ালের রং উঠে যাচ্ছে।",
          slotValues: { THING: "paint on the walls", PROBLEM: "peeling off" },
          topicArea: "housing",
        },
      ],
      formality: "polite",
      difficulty: "beginner",
      usageNote:
        "Used to report maintenance problems in your apartment to the landlord or property management.",
      usageNote_bn:
        "আপনার অ্যাপার্টমেন্টের রক্ষণাবেক্ষণ সমস্যা বাড়িওয়ালা বা সম্পত্তি ব্যবস্থাপনাকে জানাতে ব্যবহৃত হয়।",
      combinableWith: ["T33.4"],
      banglaStructureMap:
        "আমার অ্যাপার্টমেন্টের (Possessive) + [জিনিস] (Subject) + [সমস্যা] (Predicate)",
    },
    {
      id: "T33.4",
      formula: "I'd like to [REQUEST] regarding my [LEASE/APARTMENT]",
      formula_bn: "আমি আমার [লিজ/অ্যাপার্টমেন্ট] সম্পর্কে [অনুরোধ] করতে চাই",
      patternName: "Landlord Communication",
      patternName_bn: "বাড়িওয়ালার সাথে যোগাযোগ",
      slots: [
        {
          name: "REQUEST",
          description: "The request or action you want",
          description_bn: "আপনি যে অনুরোধ বা পদক্ষেপ চান",
          acceptedTypes: ["verb_phrase", "noun_phrase"],
          examples: ["request a repair", "discuss the lease renewal", "give notice"],
        },
        {
          name: "LEASE/APARTMENT",
          description: "The subject of your communication",
          description_bn: "আপনার যোগাযোগের বিষয়",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["lease", "apartment", "rental agreement"],
        },
      ],
      examples: [
        {
          en: "I'd like to request a repair for the kitchen sink.",
          bn: "আমি রান্নাঘরের সিঙ্ক মেরামতের অনুরোধ করতে চাই।",
          slotValues: { REQUEST: "request a repair", "LEASE/APARTMENT": "kitchen sink" },
          topicArea: "housing",
        },
        {
          en: "I'd like to discuss renewing my lease.",
          bn: "আমি আমার লিজ নবায়ন নিয়ে আলোচনা করতে চাই।",
          slotValues: { REQUEST: "discuss renewing", "LEASE/APARTMENT": "lease" },
          topicArea: "housing",
        },
        {
          en: "I'd like to give my 30-day notice.",
          bn: "আমি আমার ৩০ দিনের নোটিশ দিতে চাই।",
          slotValues: { REQUEST: "give my 30-day notice" },
          topicArea: "housing",
        },
        {
          en: "Can we discuss the terms of the new lease?",
          bn: "আমরা কি নতুন লিজের শর্তাবলি নিয়ে আলোচনা করতে পারি?",
          slotValues: { REQUEST: "discuss the terms", "LEASE/APARTMENT": "new lease" },
          topicArea: "housing",
        },
        {
          en: "I'd like to ask about getting permission to have a pet.",
          bn: "আমি পোষা প্রাণী রাখার অনুমতি সম্পর্কে জানতে চাই।",
          slotValues: { REQUEST: "ask about getting permission to have a pet" },
          topicArea: "housing",
        },
        {
          en: "I'd like to report a noise complaint about my neighbor.",
          bn: "আমি আমার প্রতিবেশীর শব্দ নিয়ে অভিযোগ জানাতে চাই।",
          slotValues: { REQUEST: "report a noise complaint" },
          topicArea: "housing",
        },
        {
          en: "Can I sublet my apartment for two months?",
          bn: "আমি কি দুই মাসের জন্য আমার অ্যাপার্টমেন্ট সাবলেট দিতে পারি?",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "I'd like to request an extension on my lease.",
          bn: "আমি আমার লিজের মেয়াদ বাড়ানোর অনুরোধ করতে চাই।",
          slotValues: { REQUEST: "request an extension", "LEASE/APARTMENT": "lease" },
          topicArea: "housing",
        },
        {
          en: "I'd like to discuss reducing the rent.",
          bn: "আমি ভাড়া কমানো নিয়ে আলোচনা করতে চাই।",
          slotValues: { REQUEST: "discuss reducing the rent" },
          topicArea: "housing",
        },
        {
          en: "Can I install a shelf in the living room?",
          bn: "আমি কি বসার ঘরে একটি তাক লাগাতে পারি?",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "I'd like to add my partner to the lease.",
          bn: "আমি আমার সঙ্গীকে লিজে যোগ করতে চাই।",
          slotValues: { REQUEST: "add my partner", "LEASE/APARTMENT": "lease" },
          topicArea: "housing",
        },
        {
          en: "I'd like to discuss the parking arrangement for my apartment.",
          bn: "আমি আমার অ্যাপার্টমেন্টের পার্কিং ব্যবস্থা নিয়ে আলোচনা করতে চাই।",
          slotValues: { REQUEST: "discuss the parking arrangement", "LEASE/APARTMENT": "apartment" },
          topicArea: "housing",
        },
        {
          en: "I need to inform you that I'll be moving out next month.",
          bn: "আমি আপনাকে জানাতে চাই যে আমি আগামী মাসে চলে যাব।",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "I'd like to request a copy of my lease agreement.",
          bn: "আমি আমার লিজ চুক্তির একটি কপি চাইতে চাই।",
          slotValues: { REQUEST: "request a copy", "LEASE/APARTMENT": "lease agreement" },
          topicArea: "housing",
        },
        {
          en: "Can we schedule a time to do a walk-through of the apartment?",
          bn: "আমরা কি অ্যাপার্টমেন্ট পরিদর্শনের জন্য একটি সময় ঠিক করতে পারি?",
          slotValues: { REQUEST: "schedule a time to do a walk-through", "LEASE/APARTMENT": "apartment" },
          topicArea: "housing",
        },
      ],
      formality: "polite",
      difficulty: "beginner",
      usageNote:
        "Used for formal and polite communication with landlords or property managers about lease and apartment matters.",
      usageNote_bn:
        "লিজ ও অ্যাপার্টমেন্ট বিষয়ে বাড়িওয়ালা বা সম্পত্তি ব্যবস্থাপকের সাথে আনুষ্ঠানিক ও বিনয়ী যোগাযোগের জন্য ব্যবহৃত হয়।",
      combinableWith: ["T33.2", "T33.3"],
      banglaStructureMap:
        "আমি (Subject) + আমার [LEASE/APARTMENT] সম্পর্কে (Topic + Postposition) + [REQUEST] করতে চাই (Verb)",
    },
    {
      id: "T33.5",
      formula: "I'm [MOVING IN/MOVING OUT] on [DATE]",
      formula_bn: "আমি [তারিখে] [উঠছি/চলে যাচ্ছি]",
      patternName: "Moving In/Out",
      patternName_bn: "ওঠা/চলে যাওয়া",
      slots: [
        {
          name: "MOVING IN/MOVING OUT",
          description: "Whether you are moving in or moving out",
          description_bn: "আপনি উঠছেন নাকি চলে যাচ্ছেন",
          acceptedTypes: ["verb_phrase"],
          examples: ["moving in", "moving out", "relocating"],
        },
        {
          name: "DATE",
          description: "The date of the move",
          description_bn: "ওঠার/চলে যাওয়ার তারিখ",
          acceptedTypes: ["time", "time_expression"],
          examples: ["January 1st", "the end of this month", "next Saturday"],
        },
      ],
      examples: [
        {
          en: "I'm moving in on January 1st.",
          bn: "আমি ১লা জানুয়ারি উঠছি।",
          slotValues: { "MOVING IN/MOVING OUT": "moving in", DATE: "January 1st" },
          topicArea: "housing",
        },
        {
          en: "I'm moving out at the end of this month.",
          bn: "আমি এই মাসের শেষে চলে যাচ্ছি।",
          slotValues: { "MOVING IN/MOVING OUT": "moving out", DATE: "the end of this month" },
          topicArea: "housing",
        },
        {
          en: "When can I get my security deposit back?",
          bn: "আমি কখন আমার নিরাপত্তা জামানত ফেরত পাব?",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "I'll return the keys on the day I move out.",
          bn: "আমি চলে যাওয়ার দিন চাবি ফেরত দেব।",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "Can we schedule a final inspection before I leave?",
          bn: "আমি চলে যাওয়ার আগে কি আমরা একটি চূড়ান্ত পরিদর্শনের সময় ঠিক করতে পারি?",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "I'm moving in next Saturday — can I pick up the keys on Friday?",
          bn: "আমি আগামী শনিবার উঠছি — আমি কি শুক্রবার চাবি নিতে পারি?",
          slotValues: { "MOVING IN/MOVING OUT": "moving in", DATE: "next Saturday" },
          topicArea: "housing",
        },
        {
          en: "I need to hire movers for my move-out day.",
          bn: "আমার চলে যাওয়ার দিনের জন্য মুভার ভাড়া করতে হবে।",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "Is there an elevator I can use on moving day?",
          bn: "বাসা বদলের দিন কি আমি ব্যবহার করতে পারি এমন লিফট আছে?",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "I'll clean the apartment before handing over the keys.",
          bn: "চাবি হস্তান্তর করার আগে আমি অ্যাপার্টমেন্ট পরিষ্কার করব।",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "I'm moving out on March 15th — here is my written notice.",
          bn: "আমি ১৫ই মার্চ চলে যাচ্ছি — এই যে আমার লিখিত নোটিশ।",
          slotValues: { "MOVING IN/MOVING OUT": "moving out", DATE: "March 15th" },
          topicArea: "housing",
        },
        {
          en: "What condition should the apartment be in when I move out?",
          bn: "চলে যাওয়ার সময় অ্যাপার্টমেন্ট কেমন অবস্থায় থাকা উচিত?",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "Will my full deposit be refunded if there's no damage?",
          bn: "কোনো ক্ষতি না থাকলে কি আমার পুরো জামানত ফেরত দেওয়া হবে?",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "I'm relocating to a new city next month.",
          bn: "আমি আগামী মাসে নতুন শহরে স্থানান্তরিত হচ্ছি।",
          slotValues: { "MOVING IN/MOVING OUT": "relocating", DATE: "next month" },
          topicArea: "housing",
        },
        {
          en: "Can I do a final walkthrough with the landlord before moving out?",
          bn: "চলে যাওয়ার আগে আমি কি বাড়িওয়ালার সাথে একটি চূড়ান্ত পরিদর্শন করতে পারি?",
          slotValues: {},
          topicArea: "housing",
        },
        {
          en: "I need to forward my mail to my new address after moving out.",
          bn: "চলে যাওয়ার পরে আমাকে আমার নতুন ঠিকানায় ডাক ফরওয়ার্ড করতে হবে।",
          slotValues: {},
          topicArea: "housing",
        },
      ],
      formality: "polite",
      difficulty: "beginner",
      usageNote:
        "Used when communicating about moving in or out of a rental property, including key handover and deposit returns.",
      usageNote_bn:
        "ভাড়া সম্পত্তিতে ওঠা বা চলে যাওয়ার বিষয়ে যোগাযোগ করতে ব্যবহৃত হয়, চাবি হস্তান্তর ও জামানত ফেরত সহ।",
      combinableWith: ["T33.2", "T33.4"],
      banglaStructureMap:
        "আমি (Subject) + [তারিখে] (Time + Postposition) + [উঠছি/চলে যাচ্ছি] (Verb)",
    },
  ],
};
