import { PatternCategory } from "@/types/pattern";

export const categoryU11: PatternCategory = {
  id: "U11",
  slug: "do-vs-make-distinction",
  name: "\"Do\" vs \"Make\" Distinction",
  name_bn: "\"Do\" বনাম \"Make\" পার্থক্য",
  description: "Master the difference between 'do' and 'make' collocations in English",
  description_bn: "ইংরেজিতে 'do' এবং 'make' collocation-এর পার্থক্য আয়ত্ত করুন",
  icon: "⚖️",
  group: "U",
  groupName: "Idiom-Based Structural Patterns",
  groupName_bn: "বাগধারা-ভিত্তিক গঠনমূলক প্যাটার্ন",
  difficulty: "advanced",
  patterns: [
    {
      id: "U11.1",
      formula: "Do [TASK]",
      formula_bn: "[কাজ] করো",
      patternName: "Do + Task/Activity",
      patternName_bn: "Do + কাজ/কার্যকলাপ",
      slots: [
        { name: "TASK", description: "A task, chore, or activity (not creating something new)", description_bn: "একটি কাজ, গৃহকর্ম বা কার্যকলাপ (নতুন কিছু তৈরি নয়)", acceptedTypes: ["noun", "noun_phrase"], examples: ["homework", "the dishes", "business"] },
      ],
      examples: [
        { en: "I need to do my homework.", bn: "আমার হোমওয়ার্ক করতে হবে।", slotValues: { TASK: "my homework" }, topicArea: "education" },
        { en: "Can you do the dishes?", bn: "তুমি কি বাসন ধুতে পারবে?", slotValues: { TASK: "the dishes" }, topicArea: "daily_life" },
        { en: "We do business with several countries.", bn: "আমরা বিভিন্ন দেশের সাথে ব্যবসা করি।", slotValues: { TASK: "business with several countries" }, topicArea: "work" },
        { en: "She does the laundry every Saturday.", bn: "সে প্রতি শনিবার কাপড় ধোয়।", slotValues: { TASK: "the laundry every Saturday" }, topicArea: "daily_life" },
        { en: "I'll do my best.", bn: "আমি আমার সর্বোচ্চ চেষ্টা করব।", slotValues: { TASK: "my best" }, topicArea: "daily_life" },
        { en: "He does research at the university.", bn: "সে বিশ্ববিদ্যালয়ে গবেষণা করে।", slotValues: { TASK: "research at the university" }, topicArea: "education" },
        { en: "Can you do me a favor?", bn: "তুমি কি আমাকে একটা উপকার করতে পারবে?", slotValues: { TASK: "me a favor" }, topicArea: "relationships" },
        { en: "She does yoga every morning.", bn: "সে প্রতিদিন সকালে যোগব্যায়াম করে।", slotValues: { TASK: "yoga every morning" }, topicArea: "health" },
        { en: "Do the right thing.", bn: "সঠিক কাজটি করো।", slotValues: { TASK: "the right thing" }, topicArea: "daily_life" },
        { en: "He does the cooking in our house.", bn: "আমাদের বাড়িতে রান্না সে করে।", slotValues: { TASK: "the cooking in our house" }, topicArea: "food" },
        { en: "I need to do some shopping.", bn: "আমার কিছু কেনাকাটা করতে হবে।", slotValues: { TASK: "some shopping" }, topicArea: "shopping" },
        { en: "She's doing a great job.", bn: "সে দারুণ কাজ করছে।", slotValues: { TASK: "a great job" }, topicArea: "work" },
        { en: "I'll do the cleaning before the guests arrive.", bn: "অতিথি আসার আগে আমি পরিষ্কার করব।", slotValues: { TASK: "the cleaning before the guests arrive" }, topicArea: "daily_life" },
        { en: "Do some exercise after lunch.", bn: "দুপুরের খাবারের পর কিছু ব্যায়াম করো।", slotValues: { TASK: "some exercise after lunch" }, topicArea: "health" },
        { en: "I need to do some sightseeing.", bn: "আমার কিছু দর্শনীয় স্থান দেখতে হবে।", slotValues: { TASK: "some sightseeing" }, topicArea: "travel" },
      ],
      formality: "casual", difficulty: "advanced",
      usageNote: "'Do' is used for tasks, chores, activities, and work. It focuses on the process, not the result of creating something.",
      usageNote_bn: "'Do' কাজ, গৃহকর্ম, কার্যকলাপ ও কর্মের জন্য ব্যবহৃত। এটি প্রক্রিয়ায় মনোযোগ দেয়, কিছু তৈরির ফলাফলে নয়।",
      combinableWith: ["U11.2"], banglaStructureMap: "[কাজ] (Task) + করো (Do)",
    },
    {
      id: "U11.2",
      formula: "Make [PRODUCT/RESULT]",
      formula_bn: "[পণ্য/ফলাফল] তৈরি করো / করো",
      patternName: "Make + Product/Result",
      patternName_bn: "Make + পণ্য/ফলাফল",
      slots: [
        { name: "PRODUCT/RESULT", description: "Something being created, produced, or caused", description_bn: "কিছু যা তৈরি, উৎপাদিত বা সৃষ্ট হচ্ছে", acceptedTypes: ["noun", "noun_phrase"], examples: ["a decision", "a mistake", "progress"] },
      ],
      examples: [
        { en: "We need to make a decision.", bn: "আমাদের একটা সিদ্ধান্ত নিতে হবে।", slotValues: { "PRODUCT/RESULT": "a decision" }, topicArea: "work" },
        { en: "I made a mistake.", bn: "আমি একটা ভুল করেছি।", slotValues: { "PRODUCT/RESULT": "a mistake" }, topicArea: "daily_life" },
        { en: "We're making progress on the project.", bn: "আমরা প্রজেক্টে অগ্রগতি করছি।", slotValues: { "PRODUCT/RESULT": "progress on the project" }, topicArea: "work" },
        { en: "She made a great impression.", bn: "সে দারুণ ছাপ ফেলেছে।", slotValues: { "PRODUCT/RESULT": "a great impression" }, topicArea: "relationships" },
        { en: "I'll make breakfast.", bn: "আমি সকালের নাস্তা তৈরি করব।", slotValues: { "PRODUCT/RESULT": "breakfast" }, topicArea: "food" },
        { en: "Don't make noise in the library.", bn: "লাইব্রেরিতে শব্দ করো না।", slotValues: { "PRODUCT/RESULT": "noise in the library" }, topicArea: "education" },
        { en: "He made a lot of money.", bn: "সে অনেক টাকা উপার্জন করেছে।", slotValues: { "PRODUCT/RESULT": "a lot of money" }, topicArea: "work" },
        { en: "Let me make a suggestion.", bn: "আমাকে একটা পরামর্শ দিতে দাও।", slotValues: { "PRODUCT/RESULT": "a suggestion" }, topicArea: "daily_life" },
        { en: "She made a plan for the trip.", bn: "সে ভ্রমণের জন্য একটা পরিকল্পনা করেছে।", slotValues: { "PRODUCT/RESULT": "a plan for the trip" }, topicArea: "travel" },
        { en: "The medicine made a difference.", bn: "ওষুধটি পরিবর্তন এনেছে।", slotValues: { "PRODUCT/RESULT": "a difference" }, topicArea: "health" },
        { en: "They made arrangements for the event.", bn: "তারা অনুষ্ঠানের ব্যবস্থা করেছে।", slotValues: { "PRODUCT/RESULT": "arrangements for the event" }, topicArea: "daily_life" },
        { en: "I need to make a phone call.", bn: "আমাকে একটা ফোন করতে হবে।", slotValues: { "PRODUCT/RESULT": "a phone call" }, topicArea: "daily_life" },
        { en: "She made an effort to be friendly.", bn: "সে বন্ধুত্বপূর্ণ হওয়ার চেষ্টা করেছে।", slotValues: { "PRODUCT/RESULT": "an effort to be friendly" }, topicArea: "relationships" },
        { en: "Make a list before going shopping.", bn: "কেনাকাটায় যাওয়ার আগে একটা তালিকা তৈরি করো।", slotValues: { "PRODUCT/RESULT": "a list before going shopping" }, topicArea: "shopping" },
        { en: "He made a promise.", bn: "সে একটা প্রতিশ্রুতি দিয়েছে।", slotValues: { "PRODUCT/RESULT": "a promise" }, topicArea: "relationships" },
      ],
      formality: "casual", difficulty: "advanced",
      usageNote: "'Make' is used when something is being created, produced, or caused as a result. Focuses on the outcome.",
      usageNote_bn: "'Make' ব্যবহৃত হয় যখন কিছু তৈরি, উৎপাদিত বা ফলাফল হিসেবে সৃষ্ট হয়। ফলাফলে মনোযোগ দেয়।",
      combinableWith: ["U11.1"], banglaStructureMap: "[পণ্য/ফলাফল] (Product/Result) + তৈরি করো / করো (Make)",
    },
    {
      id: "U11.3",
      formula: "Do well / Do badly",
      formula_bn: "ভালো করো / খারাপ করো",
      patternName: "Do + Performance Adverb",
      patternName_bn: "Do + কর্মক্ষমতা ক্রিয়াবিশেষণ",
      slots: [],
      examples: [
        { en: "She did well on the exam.", bn: "সে পরীক্ষায় ভালো করেছে।", slotValues: {}, topicArea: "education" },
        { en: "The company is doing well this quarter.", bn: "কোম্পানি এই ত্রৈমাসিকে ভালো করছে।", slotValues: {}, topicArea: "work" },
        { en: "He did badly in the interview.", bn: "সে সাক্ষাৎকারে খারাপ করেছে।", slotValues: {}, topicArea: "work" },
        { en: "How did you do on the test?", bn: "পরীক্ষায় তুমি কেমন করেছ?", slotValues: {}, topicArea: "education" },
        { en: "The patient is doing well after surgery.", bn: "সার্জারির পর রোগী ভালো করছে।", slotValues: {}, topicArea: "health" },
        { en: "The restaurant is doing well since it opened.", bn: "রেস্তোরাঁটি খোলার পর থেকে ভালো করছে।", slotValues: {}, topicArea: "food" },
        { en: "I did well in the negotiations.", bn: "আমি আলোচনায় ভালো করেছি।", slotValues: {}, topicArea: "work" },
        { en: "How are you doing?", bn: "তুমি কেমন আছ?", slotValues: {}, topicArea: "daily_life" },
        { en: "The team did poorly last season.", bn: "দল গত মৌসুমে খারাপ করেছে।", slotValues: {}, topicArea: "daily_life" },
        { en: "She's doing better now.", bn: "সে এখন ভালো করছে।", slotValues: {}, topicArea: "health" },
        { en: "The shop is doing good business.", bn: "দোকানটি ভালো ব্যবসা করছে।", slotValues: {}, topicArea: "shopping" },
        { en: "He did great during the presentation.", bn: "সে প্রেজেন্টেশনে দারুণ করেছে।", slotValues: {}, topicArea: "work" },
        { en: "We're doing fine, thank you.", bn: "আমরা ভালো আছি, ধন্যবাদ।", slotValues: {}, topicArea: "relationships" },
        { en: "The flight booking did well to get us a cheap fare.", bn: "ফ্লাইট বুকিংয়ে সস্তা ভাড়া পেয়ে ভালো হয়েছে।", slotValues: {}, topicArea: "travel" },
        { en: "The new recipe did well at the dinner party.", bn: "নতুন রেসিপি ডিনার পার্টিতে ভালো করেছে।", slotValues: {}, topicArea: "food" },
      ],
      formality: "casual", difficulty: "advanced",
      usageNote: "'Do' is used with adverbs to describe performance or how something is going. 'Do well' = succeed.",
      usageNote_bn: "'Do' কর্মক্ষমতা বা কিছু কেমন চলছে বর্ণনা করতে ক্রিয়াবিশেষণের সাথে ব্যবহৃত। 'Do well' = সফল হওয়া।",
      combinableWith: ["U11.1"], banglaStructureMap: "ভালো / খারাপ (Well / Badly) + করো (Do)",
    },
    {
      id: "U11.4",
      formula: "Make [PERSON] [FEELING]",
      formula_bn: "[ব্যক্তি]-কে [অনুভূতি] করো",
      patternName: "Make Someone Feel (Causative)",
      patternName_bn: "কাউকে অনুভব করানো (কারণমূলক)",
      slots: [
        { name: "PERSON", description: "The person affected", description_bn: "যে ব্যক্তি প্রভাবিত হচ্ছে", acceptedTypes: ["person", "noun"], examples: ["me", "her", "everyone"] },
        { name: "FEELING", description: "The emotion or state caused", description_bn: "যে আবেগ বা অবস্থা সৃষ্ট হচ্ছে", acceptedTypes: ["adjective", "feeling"], examples: ["happy", "angry", "uncomfortable"] },
      ],
      examples: [
        { en: "You make me happy.", bn: "তুমি আমাকে সুখী করো।", slotValues: { PERSON: "me", FEELING: "happy" }, topicArea: "relationships" },
        { en: "That made her angry.", bn: "এটা তাকে রাগান্বিত করেছে।", slotValues: { PERSON: "her", FEELING: "angry" }, topicArea: "relationships" },
        { en: "The news made everyone worried.", bn: "খবরটি সবাইকে চিন্তিত করেছে।", slotValues: { PERSON: "everyone", FEELING: "worried" }, topicArea: "daily_life" },
        { en: "His speech made the audience proud.", bn: "তার বক্তৃতা শ্রোতাদের গর্বিত করেছে।", slotValues: { PERSON: "the audience", FEELING: "proud" }, topicArea: "work" },
        { en: "Good food makes me feel satisfied.", bn: "ভালো খাবার আমাকে তৃপ্ত করে।", slotValues: { PERSON: "me", FEELING: "satisfied" }, topicArea: "food" },
        { en: "The delay made the passengers frustrated.", bn: "বিলম্ব যাত্রীদের হতাশ করেছে।", slotValues: { PERSON: "the passengers", FEELING: "frustrated" }, topicArea: "travel" },
        { en: "The medicine made me drowsy.", bn: "ওষুধটি আমাকে তন্দ্রাচ্ছন্ন করেছে।", slotValues: { PERSON: "me", FEELING: "drowsy" }, topicArea: "health" },
        { en: "The teacher made the lesson interesting.", bn: "শিক্ষক পাঠটিকে আকর্ষণীয় করেছেন।", slotValues: { PERSON: "the lesson", FEELING: "interesting" }, topicArea: "education" },
        { en: "That makes me uncomfortable.", bn: "এটা আমাকে অস্বস্তিতে ফেলে।", slotValues: { PERSON: "me", FEELING: "uncomfortable" }, topicArea: "daily_life" },
        { en: "The sale prices made customers excited.", bn: "সেলের দাম গ্রাহকদের উত্তেজিত করেছে।", slotValues: { PERSON: "customers", FEELING: "excited" }, topicArea: "shopping" },
        { en: "Your kindness made me grateful.", bn: "তোমার দয়া আমাকে কৃতজ্ঞ করেছে।", slotValues: { PERSON: "me", FEELING: "grateful" }, topicArea: "relationships" },
        { en: "The project deadline makes us stressed.", bn: "প্রজেক্টের সময়সীমা আমাদের চাপে ফেলে।", slotValues: { PERSON: "us", FEELING: "stressed" }, topicArea: "work" },
        { en: "The sunset made the trip memorable.", bn: "সূর্যাস্ত ভ্রমণটিকে স্মরণীয় করেছে।", slotValues: { PERSON: "the trip", FEELING: "memorable" }, topicArea: "travel" },
        { en: "That noise makes me nervous.", bn: "ওই শব্দ আমাকে নার্ভাস করে।", slotValues: { PERSON: "me", FEELING: "nervous" }, topicArea: "daily_life" },
        { en: "The exam results made the students relieved.", bn: "পরীক্ষার ফলাফল শিক্ষার্থীদের স্বস্তি দিয়েছে।", slotValues: { PERSON: "the students", FEELING: "relieved" }, topicArea: "education" },
      ],
      formality: "casual", difficulty: "advanced",
      usageNote: "'Make' is used as a causative verb to describe causing someone to feel a certain way. Make + object + adjective.",
      usageNote_bn: "'Make' কারণমূলক ক্রিয়া হিসেবে কাউকে একটি নির্দিষ্ট উপায়ে অনুভব করানো বর্ণনায় ব্যবহৃত। Make + object + adjective।",
      combinableWith: ["U11.2"], banglaStructureMap: "[ব্যক্তি]-কে (Person + Accusative) + [অনুভূতি] (Feeling) + করো (Make)",
    },
    {
      id: "U11.5",
      formula: "Make up [THING] / Make up for [THING]",
      formula_bn: "[জিনিস] তৈরি করো / [জিনিস]-এর ক্ষতিপূরণ করো",
      patternName: "Make Up / Make Up For",
      patternName_bn: "তৈরি করা / ক্ষতিপূরণ করা",
      slots: [
        { name: "THING", description: "Something to invent or compensate for", description_bn: "কিছু আবিষ্কার করা বা ক্ষতিপূরণ করা", acceptedTypes: ["noun", "noun_phrase"], examples: ["an excuse", "lost time", "a story"] },
      ],
      examples: [
        { en: "Don't make up excuses.", bn: "অজুহাত তৈরি করো না।", slotValues: { THING: "excuses" }, topicArea: "daily_life" },
        { en: "I need to make up for lost time.", bn: "আমাকে হারানো সময়ের ক্ষতিপূরণ করতে হবে।", slotValues: { THING: "lost time" }, topicArea: "work" },
        { en: "She made up a story.", bn: "সে একটা গল্প তৈরি করেছে।", slotValues: { THING: "a story" }, topicArea: "daily_life" },
        { en: "He's trying to make up for his mistake.", bn: "সে তার ভুলের ক্ষতিপূরণ করার চেষ্টা করছে।", slotValues: { THING: "his mistake" }, topicArea: "relationships" },
        { en: "Can we make up the missed class?", bn: "আমরা কি মিস করা ক্লাসটি পূরণ করতে পারি?", slotValues: { THING: "the missed class" }, topicArea: "education" },
        { en: "She made up for the bad service with a discount.", bn: "সে ছাড় দিয়ে খারাপ সেবার ক্ষতিপূরণ করেছে।", slotValues: { THING: "the bad service" }, topicArea: "shopping" },
        { en: "I'll make it up to you.", bn: "আমি তোমার কাছে এর ক্ষতিপূরণ করব।", slotValues: { THING: "it" }, topicArea: "relationships" },
        { en: "They made up after the argument.", bn: "তারা তর্কের পর মিটমাট করেছে।", slotValues: { THING: "after the argument" }, topicArea: "relationships" },
        { en: "He made up a recipe with whatever was in the fridge.", bn: "সে ফ্রিজে যা ছিল তা দিয়ে একটা রেসিপি তৈরি করেছে।", slotValues: { THING: "a recipe" }, topicArea: "food" },
        { en: "I'll make up for the delay.", bn: "আমি বিলম্বের ক্ষতিপূরণ করব।", slotValues: { THING: "the delay" }, topicArea: "work" },
        { en: "She made up for missing the trip by planning a new one.", bn: "সে নতুন একটা পরিকল্পনা করে ভ্রমণ মিস করার ক্ষতিপূরণ করেছে।", slotValues: { THING: "missing the trip" }, topicArea: "travel" },
        { en: "The extra rest made up for the tiring week.", bn: "অতিরিক্ত বিশ্রাম ক্লান্তিকর সপ্তাহের ক্ষতিপূরণ করেছে।", slotValues: { THING: "the tiring week" }, topicArea: "health" },
        { en: "He made up an excuse to leave early.", bn: "সে তাড়াতাড়ি যাওয়ার জন্য একটা অজুহাত তৈরি করেছে।", slotValues: { THING: "an excuse to leave early" }, topicArea: "work" },
        { en: "I need to make up the exam I missed.", bn: "আমাকে যে পরীক্ষা মিস করেছি তা পূরণ করতে হবে।", slotValues: { THING: "the exam I missed" }, topicArea: "education" },
        { en: "Good quality makes up for a higher price.", bn: "ভালো মান উচ্চ দামের ক্ষতিপূরণ করে।", slotValues: { THING: "a higher price" }, topicArea: "shopping" },
      ],
      formality: "casual", difficulty: "advanced",
      usageNote: "'Make up' can mean to invent/fabricate, to reconcile, or (with 'for') to compensate for something.",
      usageNote_bn: "'Make up' মানে হতে পারে আবিষ্কার/তৈরি করা, মিটমাট করা, বা ('for' সহ) কিছুর ক্ষতিপূরণ করা।",
      combinableWith: ["U11.2"], banglaStructureMap: "[জিনিস] (Object) + তৈরি করো / ক্ষতিপূরণ করো (Make up / Make up for)",
    },
  ],
};
