import { PatternCategory } from "@/types/pattern";

export const categoryU14: PatternCategory = {
  id: "U14",
  slug: "have-patterns",
  name: "\"Have\" Multi-Use Patterns",
  name_bn: "\"Have\" বহু-ব্যবহারিক প্যাটার্ন",
  description:
    "Master 'have' beyond possession: meals, experiences, commonalities, obligations, and greetings",
  description_bn:
    "অধিকারের বাইরে 'have'-এর বিভিন্ন ব্যবহার আয়ত্ত করুন: খাবার, অভিজ্ঞতা, মিল, বাধ্যবাধকতা এবং শুভেচ্ছা",
  icon: "🤲",
  group: "U",
  groupName: "Idiom-Based Structural Patterns",
  groupName_bn: "বাগধারা-ভিত্তিক গঠনমূলক প্যাটার্ন",
  difficulty: "advanced",
  patterns: [
    {
      id: "U14.1",
      formula: "Let's have [MEAL]",
      formula_bn: "চলো [খাবার] খাই",
      patternName: "Have + Meal (Eating Together)",
      patternName_bn: "Have + খাবার (একসাথে খাওয়া)",
      slots: [
        {
          name: "MEAL",
          description: "The meal or food item to share",
          description_bn: "যে খাবার একসাথে খাওয়া হবে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["lunch", "dinner", "some tea"],
        },
      ],
      examples: [
        {
          en: "Let's have lunch together.",
          bn: "চলো একসাথে দুপুরের খাবার খাই।",
          slotValues: { MEAL: "lunch together" },
          topicArea: "food",
        },
        {
          en: "Let's have dinner at that new restaurant.",
          bn: "চলো সেই নতুন রেস্তোরাঁয় রাতের খাবার খাই।",
          slotValues: { MEAL: "dinner at that new restaurant" },
          topicArea: "food",
        },
        {
          en: "Let's have some tea.",
          bn: "চলো চা খাই।",
          slotValues: { MEAL: "some tea" },
          topicArea: "food",
        },
        {
          en: "Let's have breakfast before we leave.",
          bn: "চলো যাওয়ার আগে নাস্তা করি।",
          slotValues: { MEAL: "breakfast before we leave" },
          topicArea: "food",
        },
        {
          en: "Let's have coffee and catch up.",
          bn: "চলো কফি খাই এবং খোঁজ-খবর নিই।",
          slotValues: { MEAL: "coffee and catch up" },
          topicArea: "relationships",
        },
        {
          en: "Let's have a snack.",
          bn: "চলো হালকা কিছু খাই।",
          slotValues: { MEAL: "a snack" },
          topicArea: "food",
        },
        {
          en: "Let's have some ice cream.",
          bn: "চলো আইসক্রিম খাই।",
          slotValues: { MEAL: "some ice cream" },
          topicArea: "food",
        },
        {
          en: "Let's have a picnic this weekend.",
          bn: "চলো এই সপ্তাহান্তে পিকনিক করি।",
          slotValues: { MEAL: "a picnic this weekend" },
          topicArea: "entertainment",
        },
        {
          en: "Let's have biryani tonight.",
          bn: "চলো আজ রাতে বিরিয়ানি খাই।",
          slotValues: { MEAL: "biryani tonight" },
          topicArea: "food",
        },
        {
          en: "Let's have a quick bite.",
          bn: "চলো দ্রুত কিছু খেয়ে নিই।",
          slotValues: { MEAL: "a quick bite" },
          topicArea: "food",
        },
        {
          en: "Let's have some fruit.",
          bn: "চলো ফল খাই।",
          slotValues: { MEAL: "some fruit" },
          topicArea: "health",
        },
        {
          en: "Let's have dessert.",
          bn: "চলো মিষ্টি খাই।",
          slotValues: { MEAL: "dessert" },
          topicArea: "food",
        },
        {
          en: "Let's have a barbecue.",
          bn: "চলো বারবিকিউ করি।",
          slotValues: { MEAL: "a barbecue" },
          topicArea: "food",
        },
        {
          en: "Let's have something warm to drink.",
          bn: "চলো গরম কিছু পান করি।",
          slotValues: { MEAL: "something warm to drink" },
          topicArea: "food",
        },
        {
          en: "Let's have a family dinner on Friday.",
          bn: "চলো শুক্রবারে পারিবারিক ডিনার করি।",
          slotValues: { MEAL: "a family dinner on Friday" },
          topicArea: "relationships",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
    },
    {
      id: "U14.2",
      formula: "I had a [ADJ] [EXPERIENCE]",
      formula_bn: "আমার একটি [বিশেষণ] [অভিজ্ঞতা] হয়েছে",
      patternName: "Had + Adjective + Experience",
      patternName_bn: "হয়েছে + বিশেষণ + অভিজ্ঞতা",
      slots: [
        {
          name: "ADJ",
          description: "How the experience was",
          description_bn: "অভিজ্ঞতা কেমন ছিল",
          acceptedTypes: ["adjective"],
          examples: ["wonderful", "terrible", "great"],
        },
        {
          name: "EXPERIENCE",
          description: "The type of experience",
          description_bn: "অভিজ্ঞতার ধরন",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["time", "day", "trip"],
        },
      ],
      examples: [
        {
          en: "I had a wonderful time.",
          bn: "আমার চমৎকার সময় কেটেছে।",
          slotValues: { ADJ: "wonderful", EXPERIENCE: "time" },
          topicArea: "daily_life",
        },
        {
          en: "I had a terrible day at work.",
          bn: "কর্মক্ষেত্রে আমার একটি ভয়ানক দিন কেটেছে।",
          slotValues: { ADJ: "terrible", EXPERIENCE: "day at work" },
          topicArea: "work",
        },
        {
          en: "I had a great trip to Cox's Bazar.",
          bn: "কক্সবাজারে আমার একটি দুর্দান্ত ভ্রমণ হয়েছে।",
          slotValues: { ADJ: "great", EXPERIENCE: "trip to Cox's Bazar" },
          topicArea: "travel",
        },
        {
          en: "I had a really good experience at the hospital.",
          bn: "হাসপাতালে আমার সত্যিই ভালো অভিজ্ঞতা হয়েছে।",
          slotValues: { ADJ: "really good", EXPERIENCE: "experience at the hospital" },
          topicArea: "health",
        },
        {
          en: "I had a lovely evening with friends.",
          bn: "বন্ধুদের সাথে আমার একটি সুন্দর সন্ধ্যা কেটেছে।",
          slotValues: { ADJ: "lovely", EXPERIENCE: "evening with friends" },
          topicArea: "relationships",
        },
        {
          en: "I had a rough week.",
          bn: "আমার একটি কঠিন সপ্তাহ কেটেছে।",
          slotValues: { ADJ: "rough", EXPERIENCE: "week" },
          topicArea: "work",
        },
        {
          en: "I had a fantastic meal.",
          bn: "আমার একটি চমৎকার খাবার হয়েছে।",
          slotValues: { ADJ: "fantastic", EXPERIENCE: "meal" },
          topicArea: "food",
        },
        {
          en: "I had a difficult exam.",
          bn: "আমার একটি কঠিন পরীক্ষা হয়েছে।",
          slotValues: { ADJ: "difficult", EXPERIENCE: "exam" },
          topicArea: "education",
        },
        {
          en: "I had a pleasant surprise.",
          bn: "আমার একটি আনন্দদায়ক চমক পেয়েছি।",
          slotValues: { ADJ: "pleasant", EXPERIENCE: "surprise" },
          topicArea: "daily_life",
        },
        {
          en: "I had a bad dream last night.",
          bn: "গত রাতে আমার একটি খারাপ স্বপ্ন দেখেছি।",
          slotValues: { ADJ: "bad", EXPERIENCE: "dream last night" },
          topicArea: "daily_life",
        },
        {
          en: "I had a productive morning.",
          bn: "আমার একটি ফলপ্রসূ সকাল কেটেছে।",
          slotValues: { ADJ: "productive", EXPERIENCE: "morning" },
          topicArea: "work",
        },
        {
          en: "I had an amazing adventure.",
          bn: "আমার একটি অসাধারণ অভিযান হয়েছে।",
          slotValues: { ADJ: "amazing", EXPERIENCE: "adventure" },
          topicArea: "travel",
        },
        {
          en: "I had a peaceful weekend.",
          bn: "আমার একটি শান্তিপূর্ণ সপ্তাহান্ত কেটেছে।",
          slotValues: { ADJ: "peaceful", EXPERIENCE: "weekend" },
          topicArea: "daily_life",
        },
        {
          en: "I had an interesting conversation.",
          bn: "আমার একটি আকর্ষণীয় কথোপকথন হয়েছে।",
          slotValues: { ADJ: "interesting", EXPERIENCE: "conversation" },
          topicArea: "relationships",
        },
        {
          en: "I had a long and tiring journey.",
          bn: "আমার একটি দীর্ঘ ও ক্লান্তিকর যাত্রা হয়েছে।",
          slotValues: { ADJ: "long and tiring", EXPERIENCE: "journey" },
          topicArea: "travel",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
    },
    {
      id: "U14.3",
      formula: "We have [THING] in common",
      formula_bn: "আমাদের মধ্যে [বস্তু] মিল আছে",
      patternName: "Have In Common (Shared Traits)",
      patternName_bn: "মিল আছে (সাধারণ বৈশিষ্ট্য)",
      slots: [
        {
          name: "THING",
          description: "The shared trait or interest",
          description_bn: "সাধারণ বৈশিষ্ট্য বা আগ্রহ",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["a lot", "the same hobbies", "nothing"],
        },
      ],
      examples: [
        {
          en: "We have a lot in common.",
          bn: "আমাদের মধ্যে অনেক মিল আছে।",
          slotValues: { THING: "a lot" },
          topicArea: "relationships",
        },
        {
          en: "We have the same hobbies in common.",
          bn: "আমাদের একই শখ মিল আছে।",
          slotValues: { THING: "the same hobbies" },
          topicArea: "relationships",
        },
        {
          en: "We have nothing in common.",
          bn: "আমাদের মধ্যে কিছুই মিল নেই।",
          slotValues: { THING: "nothing" },
          topicArea: "relationships",
        },
        {
          en: "We have our love of music in common.",
          bn: "আমাদের মধ্যে গানের প্রতি ভালোবাসার মিল আছে।",
          slotValues: { THING: "our love of music" },
          topicArea: "entertainment",
        },
        {
          en: "We have similar backgrounds in common.",
          bn: "আমাদের মধ্যে একই রকম পটভূমির মিল আছে।",
          slotValues: { THING: "similar backgrounds" },
          topicArea: "relationships",
        },
        {
          en: "We have the same taste in food in common.",
          bn: "আমাদের খাবারের রুচি এক।",
          slotValues: { THING: "the same taste in food" },
          topicArea: "food",
        },
        {
          en: "We have very little in common.",
          bn: "আমাদের মধ্যে খুব কম মিল আছে।",
          slotValues: { THING: "very little" },
          topicArea: "relationships",
        },
        {
          en: "We have a passion for travel in common.",
          bn: "আমাদের মধ্যে ভ্রমণের প্রতি আবেগের মিল আছে।",
          slotValues: { THING: "a passion for travel" },
          topicArea: "travel",
        },
        {
          en: "We have our childhood memories in common.",
          bn: "আমাদের মধ্যে শৈশবের স্মৃতির মিল আছে।",
          slotValues: { THING: "our childhood memories" },
          topicArea: "relationships",
        },
        {
          en: "We have the same problems in common.",
          bn: "আমাদের একই সমস্যা মিল আছে।",
          slotValues: { THING: "the same problems" },
          topicArea: "daily_life",
        },
        {
          en: "We have a shared interest in technology in common.",
          bn: "আমাদের মধ্যে প্রযুক্তিতে সাধারণ আগ্রহের মিল আছে।",
          slotValues: { THING: "a shared interest in technology" },
          topicArea: "work",
        },
        {
          en: "We have our values in common.",
          bn: "আমাদের মূল্যবোধের মিল আছে।",
          slotValues: { THING: "our values" },
          topicArea: "relationships",
        },
        {
          en: "We have the same hometown in common.",
          bn: "আমাদের জন্মশহর একই।",
          slotValues: { THING: "the same hometown" },
          topicArea: "relationships",
        },
        {
          en: "We have similar goals in common.",
          bn: "আমাদের মধ্যে একই রকম লক্ষ্যের মিল আছে।",
          slotValues: { THING: "similar goals" },
          topicArea: "work",
        },
        {
          en: "We have a love of books in common.",
          bn: "আমাদের মধ্যে বই পড়ার ভালোবাসার মিল আছে।",
          slotValues: { THING: "a love of books" },
          topicArea: "education",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
    },
    {
      id: "U14.4",
      formula: "I have to [ACTION]",
      formula_bn: "আমাকে [কাজ] করতে হবে",
      patternName: "Have To (Obligation/Necessity)",
      patternName_bn: "করতে হবে (বাধ্যবাধকতা/প্রয়োজনীয়তা)",
      slots: [
        {
          name: "ACTION",
          description: "The obligatory action",
          description_bn: "বাধ্যতামূলক কাজ",
          acceptedTypes: ["verb", "verb_phrase"],
          examples: ["go now", "finish this", "wake up early"],
        },
      ],
      examples: [
        {
          en: "I have to go now.",
          bn: "আমাকে এখন যেতে হবে।",
          slotValues: { ACTION: "go now" },
          topicArea: "daily_life",
        },
        {
          en: "I have to finish this report by Friday.",
          bn: "আমাকে শুক্রবারের মধ্যে এই রিপোর্ট শেষ করতে হবে।",
          slotValues: { ACTION: "finish this report by Friday" },
          topicArea: "work",
        },
        {
          en: "I have to wake up early tomorrow.",
          bn: "আমাকে আগামীকাল তাড়াতাড়ি উঠতে হবে।",
          slotValues: { ACTION: "wake up early tomorrow" },
          topicArea: "daily_life",
        },
        {
          en: "I have to study for my exam.",
          bn: "আমাকে পরীক্ষার জন্য পড়তে হবে।",
          slotValues: { ACTION: "study for my exam" },
          topicArea: "education",
        },
        {
          en: "I have to pay the electricity bill.",
          bn: "আমাকে বিদ্যুৎ বিল দিতে হবে।",
          slotValues: { ACTION: "pay the electricity bill" },
          topicArea: "daily_life",
        },
        {
          en: "I have to see a doctor.",
          bn: "আমাকে ডাক্তার দেখাতে হবে।",
          slotValues: { ACTION: "see a doctor" },
          topicArea: "health",
        },
        {
          en: "I have to buy groceries.",
          bn: "আমাকে মুদিখানার জিনিস কিনতে হবে।",
          slotValues: { ACTION: "buy groceries" },
          topicArea: "shopping",
        },
        {
          en: "I have to attend the meeting.",
          bn: "আমাকে সভায় উপস্থিত থাকতে হবে।",
          slotValues: { ACTION: "attend the meeting" },
          topicArea: "work",
        },
        {
          en: "I have to pick up my kids from school.",
          bn: "আমাকে স্কুল থেকে বাচ্চাদের আনতে হবে।",
          slotValues: { ACTION: "pick up my kids from school" },
          topicArea: "daily_life",
        },
        {
          en: "I have to renew my passport.",
          bn: "আমাকে আমার পাসপোর্ট নবায়ন করতে হবে।",
          slotValues: { ACTION: "renew my passport" },
          topicArea: "travel",
        },
        {
          en: "I have to cook dinner tonight.",
          bn: "আমাকে আজ রাতে রান্না করতে হবে।",
          slotValues: { ACTION: "cook dinner tonight" },
          topicArea: "food",
        },
        {
          en: "I have to apologize to her.",
          bn: "আমাকে তার কাছে ক্ষমা চাইতে হবে।",
          slotValues: { ACTION: "apologize to her" },
          topicArea: "relationships",
        },
        {
          en: "I have to take my medicine.",
          bn: "আমাকে আমার ওষুধ খেতে হবে।",
          slotValues: { ACTION: "take my medicine" },
          topicArea: "health",
        },
        {
          en: "I have to submit the assignment.",
          bn: "আমাকে অ্যাসাইনমেন্ট জমা দিতে হবে।",
          slotValues: { ACTION: "submit the assignment" },
          topicArea: "education",
        },
        {
          en: "I have to catch the 8 o'clock train.",
          bn: "আমাকে ৮টার ট্রেন ধরতে হবে।",
          slotValues: { ACTION: "catch the 8 o'clock train" },
          topicArea: "travel",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
    },
    {
      id: "U14.5",
      formula: "Have a [ADJ] [TIME]",
      formula_bn: "[বিশেষণ] [সময়] কাটাও",
      patternName: "Have A + Adjective + Time (Greeting/Wish)",
      patternName_bn: "কাটাও + বিশেষণ + সময় (শুভেচ্ছা/কামনা)",
      slots: [
        {
          name: "ADJ",
          description: "The quality you wish for them",
          description_bn: "আপনি তাদের জন্য যে গুণ কামনা করেন",
          acceptedTypes: ["adjective"],
          examples: ["good", "great", "wonderful"],
        },
        {
          name: "TIME",
          description: "The time period you are wishing about",
          description_bn: "যে সময়কাল সম্পর্কে আপনি কামনা করছেন",
          acceptedTypes: ["noun", "noun_phrase", "time"],
          examples: ["day", "weekend", "trip"],
        },
      ],
      examples: [
        {
          en: "Have a good day!",
          bn: "ভালো দিন কাটাও!",
          slotValues: { ADJ: "good", TIME: "day" },
          topicArea: "daily_life",
        },
        {
          en: "Have a great weekend!",
          bn: "দুর্দান্ত সপ্তাহান্ত কাটাও!",
          slotValues: { ADJ: "great", TIME: "weekend" },
          topicArea: "daily_life",
        },
        {
          en: "Have a wonderful trip!",
          bn: "চমৎকার ভ্রমণ হোক!",
          slotValues: { ADJ: "wonderful", TIME: "trip" },
          topicArea: "travel",
        },
        {
          en: "Have a nice evening!",
          bn: "সুন্দর সন্ধ্যা কাটাও!",
          slotValues: { ADJ: "nice", TIME: "evening" },
          topicArea: "daily_life",
        },
        {
          en: "Have a safe journey!",
          bn: "নিরাপদ যাত্রা হোক!",
          slotValues: { ADJ: "safe", TIME: "journey" },
          topicArea: "travel",
        },
        {
          en: "Have a happy birthday!",
          bn: "শুভ জন্মদিন হোক!",
          slotValues: { ADJ: "happy", TIME: "birthday" },
          topicArea: "relationships",
        },
        {
          en: "Have a relaxing holiday!",
          bn: "আরামদায়ক ছুটি কাটাও!",
          slotValues: { ADJ: "relaxing", TIME: "holiday" },
          topicArea: "travel",
        },
        {
          en: "Have a productive day!",
          bn: "ফলপ্রসূ দিন কাটাও!",
          slotValues: { ADJ: "productive", TIME: "day" },
          topicArea: "work",
        },
        {
          en: "Have a pleasant flight!",
          bn: "আনন্দদায়ক ফ্লাইট হোক!",
          slotValues: { ADJ: "pleasant", TIME: "flight" },
          topicArea: "travel",
        },
        {
          en: "Have a blessed Eid!",
          bn: "বরকতময় ঈদ হোক!",
          slotValues: { ADJ: "blessed", TIME: "Eid" },
          topicArea: "daily_life",
        },
        {
          en: "Have a lovely morning!",
          bn: "সুন্দর সকাল হোক!",
          slotValues: { ADJ: "lovely", TIME: "morning" },
          topicArea: "daily_life",
        },
        {
          en: "Have a fantastic vacation!",
          bn: "অসাধারণ ছুটি কাটাও!",
          slotValues: { ADJ: "fantastic", TIME: "vacation" },
          topicArea: "travel",
        },
        {
          en: "Have a peaceful night!",
          bn: "শান্তিপূর্ণ রাত হোক!",
          slotValues: { ADJ: "peaceful", TIME: "night" },
          topicArea: "daily_life",
        },
        {
          en: "Have a merry Christmas!",
          bn: "আনন্দময় ক্রিসমাস হোক!",
          slotValues: { ADJ: "merry", TIME: "Christmas" },
          topicArea: "daily_life",
        },
        {
          en: "Have a speedy recovery!",
          bn: "দ্রুত সুস্থ হও!",
          slotValues: { ADJ: "speedy", TIME: "recovery" },
          topicArea: "health",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
    },
  ],
};
