import { PatternCategory } from "@/types/pattern";

export const categoryU15: PatternCategory = {
  id: "U15",
  slug: "give-patterns",
  name: "\"Give\" Idiomatic Patterns",
  name_bn: "\"Give\" বাগধারামূলক প্যাটার্ন",
  description:
    "Master idiomatic uses of 'give': a hand, a call, a chance, up, and a try",
  description_bn:
    "'Give'-এর বাগধারামূলক ব্যবহার আয়ত্ত করুন: a hand, a call, a chance, up, এবং a try",
  icon: "🎁",
  group: "U",
  groupName: "Idiom-Based Structural Patterns",
  groupName_bn: "বাগধারা-ভিত্তিক গঠনমূলক প্যাটার্ন",
  difficulty: "advanced",
  patterns: [
    {
      id: "U15.1",
      formula: "Give [PERSON] a hand",
      formula_bn: "[ব্যক্তি]-কে সাহায্য করো",
      patternName: "Give a Hand (Help Someone)",
      patternName_bn: "সাহায্য করো (কাউকে সাহায্য)",
      slots: [
        {
          name: "PERSON",
          description: "The person who needs help",
          description_bn: "যে ব্যক্তির সাহায্য দরকার",
          acceptedTypes: ["person", "noun_phrase"],
          examples: ["me", "her", "your brother"],
        },
      ],
      examples: [
        {
          en: "Can you give me a hand with this box?",
          bn: "তুমি কি এই বাক্সটা নিয়ে আমাকে সাহায্য করতে পারো?",
          slotValues: { PERSON: "me" },
          topicArea: "daily_life",
        },
        {
          en: "Give her a hand with the cooking.",
          bn: "রান্নায় তাকে সাহায্য করো।",
          slotValues: { PERSON: "her" },
          topicArea: "food",
        },
        {
          en: "Can someone give me a hand?",
          bn: "কেউ কি আমাকে সাহায্য করতে পারো?",
          slotValues: { PERSON: "me" },
          topicArea: "daily_life",
        },
        {
          en: "Give your brother a hand with his homework.",
          bn: "তোমার ভাইকে তার হোমওয়ার্কে সাহায্য করো।",
          slotValues: { PERSON: "your brother" },
          topicArea: "education",
        },
        {
          en: "I'll give you a hand with the luggage.",
          bn: "আমি তোমাকে মালপত্র নিয়ে সাহায্য করব।",
          slotValues: { PERSON: "you" },
          topicArea: "travel",
        },
        {
          en: "Let's give them a hand setting up.",
          bn: "চলো তাদের সেটআপ করতে সাহায্য করি।",
          slotValues: { PERSON: "them" },
          topicArea: "work",
        },
        {
          en: "Give the new employee a hand on the first day.",
          bn: "প্রথম দিন নতুন কর্মচারীকে সাহায্য করো।",
          slotValues: { PERSON: "the new employee" },
          topicArea: "work",
        },
        {
          en: "Could you give me a hand moving this table?",
          bn: "তুমি কি এই টেবিলটা সরাতে আমাকে সাহায্য করতে পারো?",
          slotValues: { PERSON: "me" },
          topicArea: "daily_life",
        },
        {
          en: "Give your mother a hand in the kitchen.",
          bn: "রান্নাঘরে তোমার মাকে সাহায্য করো।",
          slotValues: { PERSON: "your mother" },
          topicArea: "food",
        },
        {
          en: "I need someone to give me a hand with the garden.",
          bn: "আমার বাগানে কেউ সাহায্য করুক দরকার।",
          slotValues: { PERSON: "me" },
          topicArea: "daily_life",
        },
        {
          en: "Give the old lady a hand crossing the road.",
          bn: "বৃদ্ধ মহিলাকে রাস্তা পার হতে সাহায্য করো।",
          slotValues: { PERSON: "the old lady" },
          topicArea: "daily_life",
        },
        {
          en: "Can you give us a hand with the decorations?",
          bn: "তুমি কি সাজসজ্জায় আমাদের সাহায্য করতে পারো?",
          slotValues: { PERSON: "us" },
          topicArea: "relationships",
        },
        {
          en: "Give him a hand carrying the groceries.",
          bn: "তাকে মুদিখানার জিনিস বহন করতে সাহায্য করো।",
          slotValues: { PERSON: "him" },
          topicArea: "shopping",
        },
        {
          en: "I'll give you a hand with the report.",
          bn: "আমি তোমাকে রিপোর্টে সাহায্য করব।",
          slotValues: { PERSON: "you" },
          topicArea: "work",
        },
        {
          en: "Give your classmate a hand with the project.",
          bn: "তোমার সহপাঠীকে প্রকল্পে সাহায্য করো।",
          slotValues: { PERSON: "your classmate" },
          topicArea: "education",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
    },
    {
      id: "U15.2",
      formula: "Give [PERSON] a call",
      formula_bn: "[ব্যক্তি]-কে ফোন করো",
      patternName: "Give a Call (Contact by Phone)",
      patternName_bn: "ফোন করো (ফোনে যোগাযোগ)",
      slots: [
        {
          name: "PERSON",
          description: "The person to call",
          description_bn: "যে ব্যক্তিকে ফোন করতে হবে",
          acceptedTypes: ["person", "noun_phrase"],
          examples: ["me", "the doctor", "your parents"],
        },
      ],
      examples: [
        {
          en: "Give me a call when you arrive.",
          bn: "পৌঁছে আমাকে ফোন করো।",
          slotValues: { PERSON: "me" },
          topicArea: "travel",
        },
        {
          en: "Give the doctor a call tomorrow.",
          bn: "আগামীকাল ডাক্তারকে ফোন করো।",
          slotValues: { PERSON: "the doctor" },
          topicArea: "health",
        },
        {
          en: "Give your parents a call this evening.",
          bn: "আজ সন্ধ্যায় তোমার বাবা-মাকে ফোন করো।",
          slotValues: { PERSON: "your parents" },
          topicArea: "relationships",
        },
        {
          en: "Give me a call if you need anything.",
          bn: "কিছু দরকার হলে আমাকে ফোন করো।",
          slotValues: { PERSON: "me" },
          topicArea: "daily_life",
        },
        {
          en: "Give the restaurant a call to make a reservation.",
          bn: "রিজার্ভেশন করতে রেস্তোরাঁয় ফোন করো।",
          slotValues: { PERSON: "the restaurant" },
          topicArea: "food",
        },
        {
          en: "Give her a call and wish her happy birthday.",
          bn: "তাকে ফোন করো এবং জন্মদিনের শুভেচ্ছা জানাও।",
          slotValues: { PERSON: "her" },
          topicArea: "relationships",
        },
        {
          en: "Give the hotel a call to confirm the booking.",
          bn: "বুকিং নিশ্চিত করতে হোটেলে ফোন করো।",
          slotValues: { PERSON: "the hotel" },
          topicArea: "travel",
        },
        {
          en: "Give your boss a call and let him know.",
          bn: "তোমার বসকে ফোন করো এবং তাকে জানাও।",
          slotValues: { PERSON: "your boss" },
          topicArea: "work",
        },
        {
          en: "Give me a call later.",
          bn: "পরে আমাকে ফোন করো।",
          slotValues: { PERSON: "me" },
          topicArea: "daily_life",
        },
        {
          en: "Give the school a call about the admission.",
          bn: "ভর্তি সম্পর্কে স্কুলে ফোন করো।",
          slotValues: { PERSON: "the school" },
          topicArea: "education",
        },
        {
          en: "Give the plumber a call, the sink is leaking.",
          bn: "প্লাম্বারকে ফোন করো, সিঙ্ক লিক করছে।",
          slotValues: { PERSON: "the plumber" },
          topicArea: "daily_life",
        },
        {
          en: "Give your friend a call and invite him.",
          bn: "তোমার বন্ধুকে ফোন করো এবং তাকে আমন্ত্রণ জানাও।",
          slotValues: { PERSON: "your friend" },
          topicArea: "relationships",
        },
        {
          en: "Give the mechanic a call about the car.",
          bn: "গাড়ির ব্যাপারে মেকানিককে ফোন করো।",
          slotValues: { PERSON: "the mechanic" },
          topicArea: "daily_life",
        },
        {
          en: "Give the pharmacy a call to check if the medicine is available.",
          bn: "ওষুধ পাওয়া যাচ্ছে কিনা জানতে ফার্মেসিতে ফোন করো।",
          slotValues: { PERSON: "the pharmacy" },
          topicArea: "health",
        },
        {
          en: "Give me a call before you come.",
          bn: "আসার আগে আমাকে ফোন করো।",
          slotValues: { PERSON: "me" },
          topicArea: "daily_life",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
    },
    {
      id: "U15.3",
      formula: "Give [PERSON] a chance",
      formula_bn: "[ব্যক্তি]-কে একটি সুযোগ দাও",
      patternName: "Give a Chance (Opportunity)",
      patternName_bn: "সুযোগ দাও (সুযোগ)",
      slots: [
        {
          name: "PERSON",
          description: "The person who deserves an opportunity",
          description_bn: "যে ব্যক্তি একটি সুযোগ পাওয়ার যোগ্য",
          acceptedTypes: ["person", "noun_phrase"],
          examples: ["him", "her", "the new guy"],
        },
      ],
      examples: [
        {
          en: "Give him a chance to explain.",
          bn: "তাকে ব্যাখ্যা করার সুযোগ দাও।",
          slotValues: { PERSON: "him" },
          topicArea: "relationships",
        },
        {
          en: "Give her a chance to prove herself.",
          bn: "তাকে নিজেকে প্রমাণ করার সুযোগ দাও।",
          slotValues: { PERSON: "her" },
          topicArea: "work",
        },
        {
          en: "Give the new guy a chance.",
          bn: "নতুন ছেলেটাকে একটি সুযোগ দাও।",
          slotValues: { PERSON: "the new guy" },
          topicArea: "work",
        },
        {
          en: "Give me a chance to make it right.",
          bn: "আমাকে সব ঠিক করার সুযোগ দাও।",
          slotValues: { PERSON: "me" },
          topicArea: "relationships",
        },
        {
          en: "Give them a chance to improve.",
          bn: "তাদের উন্নতি করার সুযোগ দাও।",
          slotValues: { PERSON: "them" },
          topicArea: "education",
        },
        {
          en: "Everyone deserves a chance. Give him one.",
          bn: "সবাই একটি সুযোগ পাওয়ার যোগ্য। তাকে একটা দাও।",
          slotValues: { PERSON: "him" },
          topicArea: "daily_life",
        },
        {
          en: "Give the student a chance to answer.",
          bn: "শিক্ষার্থীকে উত্তর দেওয়ার সুযোগ দাও।",
          slotValues: { PERSON: "the student" },
          topicArea: "education",
        },
        {
          en: "Give yourself a chance to rest.",
          bn: "নিজেকে বিশ্রামের সুযোগ দাও।",
          slotValues: { PERSON: "yourself" },
          topicArea: "health",
        },
        {
          en: "Give the new restaurant a chance.",
          bn: "নতুন রেস্তোরাঁটিকে একটি সুযোগ দাও।",
          slotValues: { PERSON: "the new restaurant" },
          topicArea: "food",
        },
        {
          en: "Give her a second chance.",
          bn: "তাকে দ্বিতীয় সুযোগ দাও।",
          slotValues: { PERSON: "her" },
          topicArea: "relationships",
        },
        {
          en: "Give the plan a chance to work.",
          bn: "পরিকল্পনাকে কাজ করার সুযোগ দাও।",
          slotValues: { PERSON: "the plan" },
          topicArea: "work",
        },
        {
          en: "Give me one more chance.",
          bn: "আমাকে আরেকটা সুযোগ দাও।",
          slotValues: { PERSON: "me" },
          topicArea: "relationships",
        },
        {
          en: "Give the young players a chance.",
          bn: "তরুণ খেলোয়াড়দের সুযোগ দাও।",
          slotValues: { PERSON: "the young players" },
          topicArea: "entertainment",
        },
        {
          en: "Give the medicine a chance to work.",
          bn: "ওষুধকে কাজ করার সুযোগ দাও।",
          slotValues: { PERSON: "the medicine" },
          topicArea: "health",
        },
        {
          en: "Give the applicant a fair chance.",
          bn: "আবেদনকারীকে ন্যায্য সুযোগ দাও।",
          slotValues: { PERSON: "the applicant" },
          topicArea: "work",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
    },
    {
      id: "U15.4",
      formula: "I gave up [DOING]",
      formula_bn: "আমি [করা] ছেড়ে দিয়েছি",
      patternName: "Gave Up (Quit/Stop)",
      patternName_bn: "ছেড়ে দিয়েছি (বন্ধ/ত্যাগ)",
      slots: [
        {
          name: "DOING",
          description: "The activity you stopped doing",
          description_bn: "যে কাজ আপনি বন্ধ করেছেন",
          acceptedTypes: ["gerund", "noun_phrase"],
          examples: ["smoking", "trying", "sugar"],
        },
      ],
      examples: [
        {
          en: "I gave up smoking two years ago.",
          bn: "আমি দুই বছর আগে ধূমপান ছেড়ে দিয়েছি।",
          slotValues: { DOING: "smoking two years ago" },
          topicArea: "health",
        },
        {
          en: "I gave up trying to fix the old computer.",
          bn: "আমি পুরোনো কম্পিউটার ঠিক করার চেষ্টা ছেড়ে দিয়েছি।",
          slotValues: { DOING: "trying to fix the old computer" },
          topicArea: "daily_life",
        },
        {
          en: "I gave up sugar last month.",
          bn: "আমি গত মাসে চিনি ছেড়ে দিয়েছি।",
          slotValues: { DOING: "sugar last month" },
          topicArea: "health",
        },
        {
          en: "I gave up waiting and left.",
          bn: "আমি অপেক্ষা ছেড়ে দিয়ে চলে গেছি।",
          slotValues: { DOING: "waiting and left" },
          topicArea: "daily_life",
        },
        {
          en: "I gave up eating junk food.",
          bn: "আমি জাঙ্ক ফুড খাওয়া ছেড়ে দিয়েছি।",
          slotValues: { DOING: "eating junk food" },
          topicArea: "food",
        },
        {
          en: "I gave up looking for the keys.",
          bn: "আমি চাবি খোঁজা ছেড়ে দিয়েছি।",
          slotValues: { DOING: "looking for the keys" },
          topicArea: "daily_life",
        },
        {
          en: "I gave up my dream of becoming a pilot.",
          bn: "আমি পাইলট হওয়ার স্বপ্ন ছেড়ে দিয়েছি।",
          slotValues: { DOING: "my dream of becoming a pilot" },
          topicArea: "work",
        },
        {
          en: "I gave up arguing with him.",
          bn: "আমি তার সাথে তর্ক করা ছেড়ে দিয়েছি।",
          slotValues: { DOING: "arguing with him" },
          topicArea: "relationships",
        },
        {
          en: "I gave up caffeine.",
          bn: "আমি ক্যাফেইন ছেড়ে দিয়েছি।",
          slotValues: { DOING: "caffeine" },
          topicArea: "health",
        },
        {
          en: "I gave up trying to learn guitar.",
          bn: "আমি গিটার শেখার চেষ্টা ছেড়ে দিয়েছি।",
          slotValues: { DOING: "trying to learn guitar" },
          topicArea: "entertainment",
        },
        {
          en: "I gave up my seat on the bus.",
          bn: "আমি বাসে আমার আসন ছেড়ে দিয়েছি।",
          slotValues: { DOING: "my seat on the bus" },
          topicArea: "travel",
        },
        {
          en: "I gave up staying up late.",
          bn: "আমি রাত জাগা ছেড়ে দিয়েছি।",
          slotValues: { DOING: "staying up late" },
          topicArea: "health",
        },
        {
          en: "I gave up complaining about the weather.",
          bn: "আমি আবহাওয়া নিয়ে অভিযোগ করা ছেড়ে দিয়েছি।",
          slotValues: { DOING: "complaining about the weather" },
          topicArea: "daily_life",
        },
        {
          en: "I gave up social media for a month.",
          bn: "আমি এক মাসের জন্য সোশ্যাল মিডিয়া ছেড়ে দিয়েছি।",
          slotValues: { DOING: "social media for a month" },
          topicArea: "daily_life",
        },
        {
          en: "I gave up hope of finding a solution.",
          bn: "আমি সমাধান পাওয়ার আশা ছেড়ে দিয়েছি।",
          slotValues: { DOING: "hope of finding a solution" },
          topicArea: "work",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
    },
    {
      id: "U15.5",
      formula: "Give [THING] a try",
      formula_bn: "[বস্তু] একবার চেষ্টা করো",
      patternName: "Give a Try (Attempt Something New)",
      patternName_bn: "চেষ্টা করো (নতুন কিছু চেষ্টা)",
      slots: [
        {
          name: "THING",
          description: "The thing to try or attempt",
          description_bn: "যে জিনিস চেষ্টা করতে হবে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["it", "this recipe", "the new software"],
        },
      ],
      examples: [
        {
          en: "Give it a try! You might like it.",
          bn: "একবার চেষ্টা করো! তোমার পছন্দ হতে পারে।",
          slotValues: { THING: "it" },
          topicArea: "daily_life",
        },
        {
          en: "Give this recipe a try.",
          bn: "এই রেসিপিটা একবার চেষ্টা করো।",
          slotValues: { THING: "this recipe" },
          topicArea: "food",
        },
        {
          en: "Give the new software a try.",
          bn: "নতুন সফটওয়্যারটা একবার চেষ্টা করো।",
          slotValues: { THING: "the new software" },
          topicArea: "work",
        },
        {
          en: "Give yoga a try for your back pain.",
          bn: "পিঠের ব্যথার জন্য যোগ একবার চেষ্টা করো।",
          slotValues: { THING: "yoga" },
          topicArea: "health",
        },
        {
          en: "Give this restaurant a try.",
          bn: "এই রেস্তোরাঁটা একবার চেষ্টা করো।",
          slotValues: { THING: "this restaurant" },
          topicArea: "food",
        },
        {
          en: "Give the local bus a try instead of a taxi.",
          bn: "ট্যাক্সির বদলে লোকাল বাস একবার চেষ্টা করো।",
          slotValues: { THING: "the local bus" },
          topicArea: "travel",
        },
        {
          en: "Give online learning a try.",
          bn: "অনলাইন শিক্ষা একবার চেষ্টা করো।",
          slotValues: { THING: "online learning" },
          topicArea: "education",
        },
        {
          en: "Give the herbal tea a try.",
          bn: "ভেষজ চা একবার চেষ্টা করো।",
          slotValues: { THING: "the herbal tea" },
          topicArea: "health",
        },
        {
          en: "Give this book a try. It's really good.",
          bn: "এই বইটা একবার পড়ে দেখো। সত্যিই ভালো।",
          slotValues: { THING: "this book" },
          topicArea: "education",
        },
        {
          en: "Give the cheaper option a try first.",
          bn: "আগে সস্তা বিকল্পটা একবার চেষ্টা করো।",
          slotValues: { THING: "the cheaper option" },
          topicArea: "shopping",
        },
        {
          en: "Give swimming a try this summer.",
          bn: "এই গ্রীষ্মে সাঁতার একবার চেষ্টা করো।",
          slotValues: { THING: "swimming" },
          topicArea: "health",
        },
        {
          en: "Give the new approach a try.",
          bn: "নতুন পদ্ধতিটা একবার চেষ্টা করো।",
          slotValues: { THING: "the new approach" },
          topicArea: "work",
        },
        {
          en: "Give meditation a try for stress relief.",
          bn: "মানসিক চাপ কমাতে মেডিটেশন একবার চেষ্টা করো।",
          slotValues: { THING: "meditation" },
          topicArea: "health",
        },
        {
          en: "Give the local cuisine a try when you travel.",
          bn: "ভ্রমণের সময় স্থানীয় রান্না একবার চেষ্টা করো।",
          slotValues: { THING: "the local cuisine" },
          topicArea: "travel",
        },
        {
          en: "Give this game a try. It's fun.",
          bn: "এই গেমটা একবার চেষ্টা করো। এটা মজার।",
          slotValues: { THING: "this game" },
          topicArea: "entertainment",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
    },
  ],
};
