import { PatternCategory } from "@/types/pattern";

export const categoryU7: PatternCategory = {
  id: "U7",
  slug: "keep-patterns",
  name: "\"Keep\" Patterns",
  name_bn: "\"Keep\" প্যাটার্ন",
  description: "Express continuation, maintenance, and reminders with 'keep' patterns",
  description_bn: "'keep' প্যাটার্ন দিয়ে ধারাবাহিকতা, রক্ষণাবেক্ষণ ও স্মারক প্রকাশ করুন",
  icon: "🔁",
  group: "U",
  groupName: "Idiom-Based Structural Patterns",
  groupName_bn: "বাগধারা-ভিত্তিক গঠনমূলক প্যাটার্ন",
  difficulty: "advanced",
  patterns: [
    {
      id: "U7.1",
      formula: "Keep [DOING]",
      formula_bn: "[করা] চালিয়ে যাও",
      patternName: "Keep Doing (Continue)",
      patternName_bn: "চালিয়ে যাও (ধারাবাহিকতা)",
      slots: [
        { name: "DOING", description: "A gerund for an action to continue", description_bn: "একটি gerund যে কাজ চালিয়ে যেতে হবে", acceptedTypes: ["gerund", "verb_phrase"], examples: ["going", "trying", "practicing"] },
      ],
      examples: [
        { en: "Keep going! You're almost there.", bn: "চালিয়ে যাও! প্রায় পৌঁছে গেছ।", slotValues: { DOING: "going" }, topicArea: "daily_life" },
        { en: "Keep trying until you succeed.", bn: "সফল না হওয়া পর্যন্ত চেষ্টা চালিয়ে যাও।", slotValues: { DOING: "trying until you succeed" }, topicArea: "daily_life" },
        { en: "Keep practicing your English every day.", bn: "প্রতিদিন তোমার ইংরেজি অনুশীলন চালিয়ে যাও।", slotValues: { DOING: "practicing your English every day" }, topicArea: "education" },
        { en: "Keep working hard and you'll get promoted.", bn: "কঠোর পরিশ্রম চালিয়ে যাও এবং পদোন্নতি পাবে।", slotValues: { DOING: "working hard" }, topicArea: "work" },
        { en: "Keep eating healthy foods.", bn: "স্বাস্থ্যকর খাবার খাওয়া চালিয়ে যাও।", slotValues: { DOING: "eating healthy foods" }, topicArea: "food" },
        { en: "Keep taking your medicine regularly.", bn: "নিয়মিত ওষুধ খাওয়া চালিয়ে যাও।", slotValues: { DOING: "taking your medicine regularly" }, topicArea: "health" },
        { en: "Keep smiling no matter what happens.", bn: "যাই হোক হাসি চালিয়ে যাও।", slotValues: { DOING: "smiling no matter what happens" }, topicArea: "daily_life" },
        { en: "Keep saving money for the trip.", bn: "ভ্রমণের জন্য টাকা জমানো চালিয়ে যাও।", slotValues: { DOING: "saving money for the trip" }, topicArea: "travel" },
        { en: "Keep looking for better deals.", bn: "ভালো ডিল খোঁজা চালিয়ে যাও।", slotValues: { DOING: "looking for better deals" }, topicArea: "shopping" },
        { en: "Keep supporting each other.", bn: "একে অপরকে সমর্থন দেওয়া চালিয়ে যাও।", slotValues: { DOING: "supporting each other" }, topicArea: "relationships" },
        { en: "Keep reading as much as you can.", bn: "যতটা পারো পড়া চালিয়ে যাও।", slotValues: { DOING: "reading as much as you can" }, topicArea: "education" },
        { en: "Keep updating the spreadsheet.", bn: "স্প্রেডশিট আপডেট করা চালিয়ে যাও।", slotValues: { DOING: "updating the spreadsheet" }, topicArea: "work" },
        { en: "Keep drinking water throughout the day.", bn: "সারাদিন পানি পান করা চালিয়ে যাও।", slotValues: { DOING: "drinking water throughout the day" }, topicArea: "health" },
        { en: "Keep exploring new places.", bn: "নতুন জায়গা অন্বেষণ চালিয়ে যাও।", slotValues: { DOING: "exploring new places" }, topicArea: "travel" },
        { en: "Keep cooking at home; it's healthier.", bn: "বাড়িতে রান্না চালিয়ে যাও; এটা স্বাস্থ্যকর।", slotValues: { DOING: "cooking at home" }, topicArea: "food" },
      ],
      formality: "casual",
      difficulty: "advanced",
      usageNote: "Encourages someone to continue an action. Always followed by a gerund.",
      usageNote_bn: "কাউকে একটি কাজ চালিয়ে যেতে উৎসাহিত করে। সবসময় gerund দ্বারা অনুসৃত।",
      combinableWith: ["U7.2"],
      banglaStructureMap: "[কাজ] (Action) + চালিয়ে যাও (Keep doing)",
    },
    {
      id: "U7.2",
      formula: "Keep [THING] [ADJECTIVE]",
      formula_bn: "[জিনিস] [বিশেষণ] রাখো",
      patternName: "Keep Something in a State",
      patternName_bn: "কিছু একটা অবস্থায় রাখা",
      slots: [
        { name: "THING", description: "The object to maintain in a state", description_bn: "যে বস্তুকে একটি অবস্থায় রাখতে হবে", acceptedTypes: ["noun", "noun_phrase"], examples: ["the room", "your phone", "the food"] },
        { name: "ADJECTIVE", description: "The desired state", description_bn: "কাঙ্ক্ষিত অবস্থা", acceptedTypes: ["adjective", "adjective_phrase"], examples: ["clean", "charged", "warm"] },
      ],
      examples: [
        { en: "Keep the room clean.", bn: "ঘরটি পরিষ্কার রাখো।", slotValues: { THING: "the room", ADJECTIVE: "clean" }, topicArea: "daily_life" },
        { en: "Keep your phone charged.", bn: "তোমার ফোন চার্জ দেওয়া রাখো।", slotValues: { THING: "your phone", ADJECTIVE: "charged" }, topicArea: "daily_life" },
        { en: "Keep the food warm.", bn: "খাবার গরম রাখো।", slotValues: { THING: "the food", ADJECTIVE: "warm" }, topicArea: "food" },
        { en: "Keep the door closed.", bn: "দরজা বন্ধ রাখো।", slotValues: { THING: "the door", ADJECTIVE: "closed" }, topicArea: "daily_life" },
        { en: "Keep the workspace organized.", bn: "কর্মক্ষেত্র গোছানো রাখো।", slotValues: { THING: "the workspace", ADJECTIVE: "organized" }, topicArea: "work" },
        { en: "Keep the patient comfortable.", bn: "রোগীকে আরামে রাখো।", slotValues: { THING: "the patient", ADJECTIVE: "comfortable" }, topicArea: "health" },
        { en: "Keep the information confidential.", bn: "তথ্যটি গোপনীয় রাখো।", slotValues: { THING: "the information", ADJECTIVE: "confidential" }, topicArea: "work" },
        { en: "Keep your passport safe.", bn: "তোমার পাসপোর্ট নিরাপদ রাখো।", slotValues: { THING: "your passport", ADJECTIVE: "safe" }, topicArea: "travel" },
        { en: "Keep your receipts handy.", bn: "তোমার রসিদগুলো কাছে রাখো।", slotValues: { THING: "your receipts", ADJECTIVE: "handy" }, topicArea: "shopping" },
        { en: "Keep the children quiet during the movie.", bn: "সিনেমার সময় বাচ্চাদের শান্ত রাখো।", slotValues: { THING: "the children", ADJECTIVE: "quiet" }, topicArea: "daily_life" },
        { en: "Keep your notes updated.", bn: "তোমার নোটস আপডেট রাখো।", slotValues: { THING: "your notes", ADJECTIVE: "updated" }, topicArea: "education" },
        { en: "Keep the relationship strong.", bn: "সম্পর্কটি মজবুত রাখো।", slotValues: { THING: "the relationship", ADJECTIVE: "strong" }, topicArea: "relationships" },
        { en: "Keep the wound dry.", bn: "ক্ষতস্থান শুকনো রাখো।", slotValues: { THING: "the wound", ADJECTIVE: "dry" }, topicArea: "health" },
        { en: "Keep the ingredients fresh.", bn: "উপকরণগুলো তাজা রাখো।", slotValues: { THING: "the ingredients", ADJECTIVE: "fresh" }, topicArea: "food" },
        { en: "Keep your luggage light.", bn: "তোমার লাগেজ হালকা রাখো।", slotValues: { THING: "your luggage", ADJECTIVE: "light" }, topicArea: "travel" },
      ],
      formality: "casual",
      difficulty: "advanced",
      usageNote: "Means to maintain something in a particular state or condition. Object + adjective complement.",
      usageNote_bn: "কিছু একটি নির্দিষ্ট অবস্থায় রাখা বোঝায়। Object + adjective complement।",
      combinableWith: ["U7.1"],
      banglaStructureMap: "[জিনিস] (Object) + [বিশেষণ] (Adjective) + রাখো (Keep)",
    },
    {
      id: "U7.3",
      formula: "Keep in mind that [CLAUSE]",
      formula_bn: "মনে রেখো যে [বাক্যাংশ]",
      patternName: "Keep In Mind (Remember)",
      patternName_bn: "মনে রাখো (স্মরণ)",
      slots: [
        { name: "CLAUSE", description: "Something important to remember", description_bn: "কিছু গুরুত্বপূর্ণ যা মনে রাখতে হবে", acceptedTypes: ["clause"], examples: ["the store closes at 9", "not everyone agrees", "prices may change"] },
      ],
      examples: [
        { en: "Keep in mind that the store closes at 9.", bn: "মনে রেখো যে দোকানটি ৯টায় বন্ধ হয়।", slotValues: { CLAUSE: "the store closes at 9" }, topicArea: "shopping" },
        { en: "Keep in mind that not everyone will agree.", bn: "মনে রেখো যে সবাই একমত হবে না।", slotValues: { CLAUSE: "not everyone will agree" }, topicArea: "work" },
        { en: "Keep in mind that prices may change.", bn: "মনে রেখো যে দাম পরিবর্তন হতে পারে।", slotValues: { CLAUSE: "prices may change" }, topicArea: "shopping" },
        { en: "Keep in mind that she's still learning.", bn: "মনে রেখো যে সে এখনও শিখছে।", slotValues: { CLAUSE: "she's still learning" }, topicArea: "education" },
        { en: "Keep in mind that the deadline is next Monday.", bn: "মনে রেখো যে সময়সীমা আগামী সোমবার।", slotValues: { CLAUSE: "the deadline is next Monday" }, topicArea: "work" },
        { en: "Keep in mind that spicy food may upset your stomach.", bn: "মনে রেখো যে ঝাল খাবার পেট খারাপ করতে পারে।", slotValues: { CLAUSE: "spicy food may upset your stomach" }, topicArea: "food" },
        { en: "Keep in mind that the weather can change quickly.", bn: "মনে রেখো যে আবহাওয়া দ্রুত পরিবর্তন হতে পারে।", slotValues: { CLAUSE: "the weather can change quickly" }, topicArea: "travel" },
        { en: "Keep in mind that prevention is better than cure.", bn: "মনে রেখো যে প্রতিকারের চেয়ে প্রতিরোধ ভালো।", slotValues: { CLAUSE: "prevention is better than cure" }, topicArea: "health" },
        { en: "Keep in mind that first impressions matter.", bn: "মনে রেখো যে প্রথম ধারণা গুরুত্বপূর্ণ।", slotValues: { CLAUSE: "first impressions matter" }, topicArea: "relationships" },
        { en: "Keep in mind that the exam covers all chapters.", bn: "মনে রেখো যে পরীক্ষায় সব অধ্যায় অন্তর্ভুক্ত।", slotValues: { CLAUSE: "the exam covers all chapters" }, topicArea: "education" },
        { en: "Keep in mind that we have a budget limit.", bn: "মনে রেখো যে আমাদের বাজেটের সীমা আছে।", slotValues: { CLAUSE: "we have a budget limit" }, topicArea: "work" },
        { en: "Keep in mind that this is a one-time offer.", bn: "মনে রেখো যে এটা একবারের অফার।", slotValues: { CLAUSE: "this is a one-time offer" }, topicArea: "shopping" },
        { en: "Keep in mind that honesty builds trust.", bn: "মনে রেখো যে সততা আস্থা তৈরি করে।", slotValues: { CLAUSE: "honesty builds trust" }, topicArea: "relationships" },
        { en: "Keep in mind that you need a visa for that country.", bn: "মনে রেখো যে সেই দেশের জন্য ভিসা লাগবে।", slotValues: { CLAUSE: "you need a visa for that country" }, topicArea: "travel" },
        { en: "Keep in mind that rest is part of recovery.", bn: "মনে রেখো যে বিশ্রাম সুস্থতার অংশ।", slotValues: { CLAUSE: "rest is part of recovery" }, topicArea: "health" },
      ],
      formality: "polite",
      difficulty: "advanced",
      usageNote: "Used to remind someone of an important fact or consideration. More formal than 'remember that.'",
      usageNote_bn: "কাউকে একটি গুরুত্বপূর্ণ তথ্য বা বিবেচনার কথা মনে করাতে ব্যবহৃত। 'remember that'-এর চেয়ে বেশি আনুষ্ঠানিক।",
      combinableWith: ["U7.1"],
      banglaStructureMap: "মনে রেখো যে (Keep in mind that) + [বাক্যাংশ] (Clause)",
    },
    {
      id: "U7.4",
      formula: "Keep up with [THING]",
      formula_bn: "[জিনিস]-এর সাথে তাল মেলাও",
      patternName: "Keep Up With (Stay Current)",
      patternName_bn: "তাল মেলানো (হালনাগাদ থাকা)",
      slots: [
        { name: "THING", description: "Something to stay current or competitive with", description_bn: "কিছু যার সাথে হালনাগাদ বা প্রতিযোগী থাকতে হবে", acceptedTypes: ["noun", "noun_phrase"], examples: ["the latest trends", "technology", "the news"] },
      ],
      examples: [
        { en: "It's hard to keep up with the latest trends.", bn: "সর্বশেষ প্রবণতার সাথে তাল মেলানো কঠিন।", slotValues: { THING: "the latest trends" }, topicArea: "daily_life" },
        { en: "You need to keep up with technology.", bn: "তোমাকে প্রযুক্তির সাথে তাল মেলাতে হবে।", slotValues: { THING: "technology" }, topicArea: "work" },
        { en: "I can barely keep up with the news.", bn: "আমি খবরের সাথে কোনোমতে তাল মেলাতে পারি।", slotValues: { THING: "the news" }, topicArea: "daily_life" },
        { en: "She tries to keep up with her classmates.", bn: "সে তার সহপাঠীদের সাথে তাল মেলানোর চেষ্টা করে।", slotValues: { THING: "her classmates" }, topicArea: "education" },
        { en: "It's important to keep up with market changes.", bn: "বাজারের পরিবর্তনের সাথে তাল মেলানো গুরুত্বপূর্ণ।", slotValues: { THING: "market changes" }, topicArea: "work" },
        { en: "I can't keep up with all the new restaurants.", bn: "সব নতুন রেস্তোরাঁর সাথে আমি তাল মেলাতে পারি না।", slotValues: { THING: "all the new restaurants" }, topicArea: "food" },
        { en: "Keep up with your medication schedule.", bn: "তোমার ওষুধের সময়সূচির সাথে তাল মেলাও।", slotValues: { THING: "your medication schedule" }, topicArea: "health" },
        { en: "It's hard to keep up with fashion.", bn: "ফ্যাশনের সাথে তাল মেলানো কঠিন।", slotValues: { THING: "fashion" }, topicArea: "shopping" },
        { en: "I try to keep up with my friends on social media.", bn: "আমি সামাজিক মাধ্যমে বন্ধুদের সাথে তাল মেলানোর চেষ্টা করি।", slotValues: { THING: "my friends on social media" }, topicArea: "relationships" },
        { en: "Keep up with the travel advisories.", bn: "ভ্রমণ পরামর্শগুলোর সাথে তাল মেলাও।", slotValues: { THING: "the travel advisories" }, topicArea: "travel" },
        { en: "It's tough to keep up with the workload.", bn: "কাজের বোঝার সাথে তাল মেলানো কঠিন।", slotValues: { THING: "the workload" }, topicArea: "work" },
        { en: "Keep up with your assignments.", bn: "তোমার অ্যাসাইনমেন্টগুলোর সাথে তাল মেলাও।", slotValues: { THING: "your assignments" }, topicArea: "education" },
        { en: "I struggle to keep up with the prices.", bn: "দামের সাথে তাল মেলাতে আমার কষ্ট হয়।", slotValues: { THING: "the prices" }, topicArea: "shopping" },
        { en: "Keep up with your health checkups.", bn: "তোমার স্বাস্থ্য পরীক্ষার সাথে তাল মেলাও।", slotValues: { THING: "your health checkups" }, topicArea: "health" },
        { en: "She keeps up with all the food blogs.", bn: "সে সব ফুড ব্লগের সাথে তাল মেলায়।", slotValues: { THING: "all the food blogs" }, topicArea: "food" },
      ],
      formality: "casual",
      difficulty: "advanced",
      usageNote: "Means to stay at the same level or pace as something that's changing. Can imply difficulty.",
      usageNote_bn: "পরিবর্তনশীল কিছুর সাথে একই স্তরে বা গতিতে থাকা বোঝায়। কঠিনতা বোঝাতে পারে।",
      combinableWith: ["U7.1"],
      banglaStructureMap: "[জিনিস]-এর সাথে (Object + Postposition) + তাল মেলাও (Keep up with)",
    },
    {
      id: "U7.5",
      formula: "Keep [PERSON] from [DOING]",
      formula_bn: "[ব্যক্তি]-কে [করা] থেকে বিরত রাখো",
      patternName: "Keep From Doing (Prevent)",
      patternName_bn: "বিরত রাখা (প্রতিরোধ)",
      slots: [
        { name: "PERSON", description: "The person to be prevented", description_bn: "যাকে বিরত রাখতে হবে", acceptedTypes: ["person", "noun"], examples: ["me", "the children", "him"] },
        { name: "DOING", description: "The action to be prevented", description_bn: "যে কাজ থেকে বিরত রাখতে হবে", acceptedTypes: ["gerund", "verb_phrase"], examples: ["making mistakes", "going out", "eating junk food"] },
      ],
      examples: [
        { en: "Nothing can keep me from achieving my goals.", bn: "কিছুই আমাকে আমার লক্ষ্য অর্জন থেকে বিরত রাখতে পারবে না।", slotValues: { PERSON: "me", DOING: "achieving my goals" }, topicArea: "daily_life" },
        { en: "Keep the children from playing near the road.", bn: "বাচ্চাদের রাস্তার কাছে খেলা থেকে বিরত রাখো।", slotValues: { PERSON: "the children", DOING: "playing near the road" }, topicArea: "daily_life" },
        { en: "He couldn't keep himself from laughing.", bn: "সে নিজেকে হাসি থেকে বিরত রাখতে পারেনি।", slotValues: { PERSON: "himself", DOING: "laughing" }, topicArea: "daily_life" },
        { en: "The rain kept us from going outside.", bn: "বৃষ্টি আমাদের বাইরে যাওয়া থেকে বিরত রাখলো।", slotValues: { PERSON: "us", DOING: "going outside" }, topicArea: "daily_life" },
        { en: "Keep him from eating too much sugar.", bn: "তাকে বেশি চিনি খাওয়া থেকে বিরত রাখো।", slotValues: { PERSON: "him", DOING: "eating too much sugar" }, topicArea: "health" },
        { en: "The traffic kept me from arriving on time.", bn: "ট্র্যাফিক আমাকে সময়মতো পৌঁছানো থেকে বিরত রাখলো।", slotValues: { PERSON: "me", DOING: "arriving on time" }, topicArea: "travel" },
        { en: "Keep the students from cheating.", bn: "শিক্ষার্থীদের নকল করা থেকে বিরত রাখো।", slotValues: { PERSON: "the students", DOING: "cheating" }, topicArea: "education" },
        { en: "I couldn't keep myself from buying that dress.", bn: "আমি নিজেকে সেই ড্রেসটি কেনা থেকে বিরত রাখতে পারিনি।", slotValues: { PERSON: "myself", DOING: "buying that dress" }, topicArea: "shopping" },
        { en: "Keep your dog from barking at night.", bn: "তোমার কুকুরকে রাতে ঘেউ ঘেউ থেকে বিরত রাখো।", slotValues: { PERSON: "your dog", DOING: "barking at night" }, topicArea: "daily_life" },
        { en: "Nothing kept her from pursuing her dream.", bn: "কিছুই তাকে তার স্বপ্ন অনুসরণ করা থেকে বিরত রাখতে পারেনি।", slotValues: { PERSON: "her", DOING: "pursuing her dream" }, topicArea: "work" },
        { en: "Keep the cat from scratching the furniture.", bn: "বিড়ালকে আসবাবপত্রে আঁচড় দেওয়া থেকে বিরত রাখো।", slotValues: { PERSON: "the cat", DOING: "scratching the furniture" }, topicArea: "daily_life" },
        { en: "The cold weather kept them from traveling.", bn: "ঠান্ডা আবহাওয়া তাদের ভ্রমণ থেকে বিরত রাখলো।", slotValues: { PERSON: "them", DOING: "traveling" }, topicArea: "travel" },
        { en: "Keep the employees from gossiping.", bn: "কর্মীদের গসিপ করা থেকে বিরত রাখো।", slotValues: { PERSON: "the employees", DOING: "gossiping" }, topicArea: "work" },
        { en: "She kept me from making a big mistake.", bn: "সে আমাকে একটা বড় ভুল করা থেকে বিরত রাখলো।", slotValues: { PERSON: "me", DOING: "making a big mistake" }, topicArea: "relationships" },
        { en: "Keep yourself from overthinking.", bn: "নিজেকে অতিরিক্ত চিন্তা থেকে বিরত রাখো।", slotValues: { PERSON: "yourself", DOING: "overthinking" }, topicArea: "health" },
      ],
      formality: "casual",
      difficulty: "advanced",
      usageNote: "Means to prevent someone or something from doing an action. 'From' is followed by a gerund.",
      usageNote_bn: "কাউকে বা কিছুকে একটি কাজ করা থেকে বিরত রাখা বোঝায়। 'From'-এর পরে gerund আসে।",
      combinableWith: ["U7.1"],
      banglaStructureMap: "[ব্যক্তি]-কে (Person + Accusative) + [কাজ] থেকে (Action + From) + বিরত রাখো (Keep from)",
    },
  ],
};
