import { PatternCategory } from "@/types/pattern";

export const categoryU8: PatternCategory = {
  id: "U8",
  slug: "come-patterns",
  name: "\"Come\" Patterns",
  name_bn: "\"Come\" প্যাটার্ন",
  description: "Express topics, questions, and situations with idiomatic 'come' patterns",
  description_bn: "বাগধারামূলক 'come' প্যাটার্ন দিয়ে বিষয়, প্রশ্ন ও পরিস্থিতি প্রকাশ করুন",
  icon: "👋",
  group: "U",
  groupName: "Idiom-Based Structural Patterns",
  groupName_bn: "বাগধারা-ভিত্তিক গঠনমূলক প্যাটার্ন",
  difficulty: "advanced",
  patterns: [
    {
      id: "U8.1",
      formula: "When it comes to [THING], [CLAUSE]",
      formula_bn: "[জিনিস]-এর ব্যাপারে, [বাক্যাংশ]",
      patternName: "When It Comes To (Regarding)",
      patternName_bn: "যখন ব্যাপারটা আসে (সম্পর্কে)",
      slots: [
        { name: "THING", description: "A topic or subject being discussed", description_bn: "একটি বিষয় যা আলোচনা করা হচ্ছে", acceptedTypes: ["noun", "noun_phrase", "gerund"], examples: ["cooking", "technology", "honesty"] },
        { name: "CLAUSE", description: "A statement about that topic", description_bn: "সেই বিষয় সম্পর্কে একটি বক্তব্য", acceptedTypes: ["clause"], examples: ["she's the best", "I'm very particular", "nobody beats them"] },
      ],
      examples: [
        { en: "When it comes to cooking, she's the best.", bn: "রান্নার ব্যাপারে, সে সেরা।", slotValues: { THING: "cooking", CLAUSE: "she's the best" }, topicArea: "food" },
        { en: "When it comes to technology, I'm not very good.", bn: "প্রযুক্তির ব্যাপারে, আমি খুব ভালো না।", slotValues: { THING: "technology", CLAUSE: "I'm not very good" }, topicArea: "daily_life" },
        { en: "When it comes to honesty, he never disappoints.", bn: "সততার ব্যাপারে, সে কখনো হতাশ করে না।", slotValues: { THING: "honesty", CLAUSE: "he never disappoints" }, topicArea: "relationships" },
        { en: "When it comes to deadlines, our team is very strict.", bn: "সময়সীমার ব্যাপারে, আমাদের দল খুব কঠোর।", slotValues: { THING: "deadlines", CLAUSE: "our team is very strict" }, topicArea: "work" },
        { en: "When it comes to health, prevention is key.", bn: "স্বাস্থ্যের ব্যাপারে, প্রতিরোধ হলো মূল চাবিকাঠি।", slotValues: { THING: "health", CLAUSE: "prevention is key" }, topicArea: "health" },
        { en: "When it comes to saving money, she's an expert.", bn: "টাকা জমানোর ব্যাপারে, সে একজন বিশেষজ্ঞ।", slotValues: { THING: "saving money", CLAUSE: "she's an expert" }, topicArea: "shopping" },
        { en: "When it comes to learning languages, practice is everything.", bn: "ভাষা শেখার ব্যাপারে, অনুশীলনই সব।", slotValues: { THING: "learning languages", CLAUSE: "practice is everything" }, topicArea: "education" },
        { en: "When it comes to traveling, I prefer trains.", bn: "ভ্রমণের ব্যাপারে, আমি ট্রেন পছন্দ করি।", slotValues: { THING: "traveling", CLAUSE: "I prefer trains" }, topicArea: "travel" },
        { en: "When it comes to fashion, she knows everything.", bn: "ফ্যাশনের ব্যাপারে, সে সবকিছু জানে।", slotValues: { THING: "fashion", CLAUSE: "she knows everything" }, topicArea: "shopping" },
        { en: "When it comes to teamwork, communication is essential.", bn: "দলগত কাজের ব্যাপারে, যোগাযোগ অপরিহার্য।", slotValues: { THING: "teamwork", CLAUSE: "communication is essential" }, topicArea: "work" },
        { en: "When it comes to breakfast, I like it simple.", bn: "সকালের নাস্তার ব্যাপারে, আমি সাধারণ পছন্দ করি।", slotValues: { THING: "breakfast", CLAUSE: "I like it simple" }, topicArea: "food" },
        { en: "When it comes to relationships, trust is everything.", bn: "সম্পর্কের ব্যাপারে, আস্থাই সবকিছু।", slotValues: { THING: "relationships", CLAUSE: "trust is everything" }, topicArea: "relationships" },
        { en: "When it comes to exercise, consistency matters most.", bn: "ব্যায়ামের ব্যাপারে, ধারাবাহিকতা সবচেয়ে গুরুত্বপূর্ণ।", slotValues: { THING: "exercise", CLAUSE: "consistency matters most" }, topicArea: "health" },
        { en: "When it comes to exams, preparation is half the battle.", bn: "পরীক্ষার ব্যাপারে, প্রস্তুতি অর্ধেক যুদ্ধ।", slotValues: { THING: "exams", CLAUSE: "preparation is half the battle" }, topicArea: "education" },
        { en: "When it comes to adventure, nothing beats scuba diving.", bn: "অ্যাডভেঞ্চারের ব্যাপারে, স্কুবা ডাইভিংয়ের সাথে কিছু তুলনা হয় না।", slotValues: { THING: "adventure", CLAUSE: "nothing beats scuba diving" }, topicArea: "travel" },
      ],
      formality: "casual", difficulty: "advanced",
      usageNote: "Introduces a specific topic for discussion or comparison. Very natural in spoken English.",
      usageNote_bn: "আলোচনা বা তুলনার জন্য একটি নির্দিষ্ট বিষয় পরিচয় করায়। কথ্য ইংরেজিতে খুবই স্বাভাবিক।",
      combinableWith: ["U8.2"],
      banglaStructureMap: "[জিনিস]-এর ব্যাপারে (Topic + About) + [বাক্যাংশ] (Clause)",
    },
    {
      id: "U8.2",
      formula: "How come [CLAUSE]?",
      formula_bn: "কেন [বাক্যাংশ]?",
      patternName: "How Come (Informal Why)",
      patternName_bn: "কেন (অনানুষ্ঠানিক)",
      slots: [
        { name: "CLAUSE", description: "A situation you want explained", description_bn: "একটি পরিস্থিতি যার ব্যাখ্যা আপনি চান", acceptedTypes: ["clause"], examples: ["you're late", "they changed the plan", "the price went up"] },
      ],
      examples: [
        { en: "How come you're late?", bn: "তুমি দেরি করলে কেন?", slotValues: { CLAUSE: "you're late" }, topicArea: "daily_life" },
        { en: "How come they changed the plan?", bn: "তারা পরিকল্পনা পরিবর্তন করল কেন?", slotValues: { CLAUSE: "they changed the plan" }, topicArea: "work" },
        { en: "How come the price went up?", bn: "দাম বাড়ল কেন?", slotValues: { CLAUSE: "the price went up" }, topicArea: "shopping" },
        { en: "How come you didn't call me?", bn: "তুমি আমাকে ফোন করোনি কেন?", slotValues: { CLAUSE: "you didn't call me" }, topicArea: "relationships" },
        { en: "How come the food is cold?", bn: "খাবার ঠান্ডা কেন?", slotValues: { CLAUSE: "the food is cold" }, topicArea: "food" },
        { en: "How come the flight is delayed?", bn: "ফ্লাইট বিলম্বিত কেন?", slotValues: { CLAUSE: "the flight is delayed" }, topicArea: "travel" },
        { en: "How come you're not studying?", bn: "তুমি পড়ছ না কেন?", slotValues: { CLAUSE: "you're not studying" }, topicArea: "education" },
        { en: "How come the pharmacy is closed?", bn: "ফার্মেসি বন্ধ কেন?", slotValues: { CLAUSE: "the pharmacy is closed" }, topicArea: "health" },
        { en: "How come nobody told me about the meeting?", bn: "কেউ আমাকে মিটিংয়ের কথা বলল না কেন?", slotValues: { CLAUSE: "nobody told me about the meeting" }, topicArea: "work" },
        { en: "How come you look so tired?", bn: "তোমাকে এত ক্লান্ত দেখাচ্ছে কেন?", slotValues: { CLAUSE: "you look so tired" }, topicArea: "health" },
        { en: "How come the bus is empty today?", bn: "আজ বাস খালি কেন?", slotValues: { CLAUSE: "the bus is empty today" }, topicArea: "travel" },
        { en: "How come you don't like pizza?", bn: "তুমি পিৎজা পছন্দ করো না কেন?", slotValues: { CLAUSE: "you don't like pizza" }, topicArea: "food" },
        { en: "How come the store is out of stock?", bn: "দোকানে স্টক শেষ কেন?", slotValues: { CLAUSE: "the store is out of stock" }, topicArea: "shopping" },
        { en: "How come she didn't come to the party?", bn: "সে পার্টিতে আসেনি কেন?", slotValues: { CLAUSE: "she didn't come to the party" }, topicArea: "relationships" },
        { en: "How come the test was so hard?", bn: "পরীক্ষা এত কঠিন ছিল কেন?", slotValues: { CLAUSE: "the test was so hard" }, topicArea: "education" },
      ],
      formality: "casual", difficulty: "advanced",
      usageNote: "An informal alternative to 'why.' Unlike 'why,' the word order after 'how come' is the same as a statement (not inverted).",
      usageNote_bn: "'why'-এর একটি অনানুষ্ঠানিক বিকল্প। 'why'-এর বিপরীতে, 'how come'-এর পরে শব্দ ক্রম বিবৃতির মতোই থাকে (উল্টানো নয়)।",
      combinableWith: ["U8.1"],
      banglaStructureMap: "[বাক্যাংশ] (Clause) + কেন (Why)?",
    },
    {
      id: "U8.3",
      formula: "Come to think of it, [CLAUSE]",
      formula_bn: "এখন ভেবে দেখলে, [বাক্যাংশ]",
      patternName: "Come To Think Of It (Realization)",
      patternName_bn: "ভেবে দেখলে (উপলব্ধি)",
      slots: [
        { name: "CLAUSE", description: "A thought or realization", description_bn: "একটি চিন্তা বা উপলব্ধি", acceptedTypes: ["clause"], examples: ["you might be right", "I did see him", "that explains everything"] },
      ],
      examples: [
        { en: "Come to think of it, you might be right.", bn: "এখন ভেবে দেখলে, তুমি হয়তো ঠিক বলছ।", slotValues: { CLAUSE: "you might be right" }, topicArea: "daily_life" },
        { en: "Come to think of it, I did see him there.", bn: "এখন ভেবে দেখলে, আমি তাকে সেখানে দেখেছিলাম।", slotValues: { CLAUSE: "I did see him there" }, topicArea: "daily_life" },
        { en: "Come to think of it, that explains everything.", bn: "এখন ভেবে দেখলে, সেটা সব ব্যাখ্যা করে।", slotValues: { CLAUSE: "that explains everything" }, topicArea: "daily_life" },
        { en: "Come to think of it, the deadline is tomorrow.", bn: "এখন ভেবে দেখলে, সময়সীমা কাল।", slotValues: { CLAUSE: "the deadline is tomorrow" }, topicArea: "work" },
        { en: "Come to think of it, I haven't eaten lunch.", bn: "এখন ভেবে দেখলে, আমি দুপুরের খাবার খাইনি।", slotValues: { CLAUSE: "I haven't eaten lunch" }, topicArea: "food" },
        { en: "Come to think of it, she did mention a trip.", bn: "এখন ভেবে দেখলে, সে একটা ভ্রমণের কথা বলেছিল।", slotValues: { CLAUSE: "she did mention a trip" }, topicArea: "travel" },
        { en: "Come to think of it, I need to renew my prescription.", bn: "এখন ভেবে দেখলে, আমার প্রেসক্রিপশন নবায়ন করতে হবে।", slotValues: { CLAUSE: "I need to renew my prescription" }, topicArea: "health" },
        { en: "Come to think of it, that store had better prices.", bn: "এখন ভেবে দেখলে, সেই দোকানে দাম ভালো ছিল।", slotValues: { CLAUSE: "that store had better prices" }, topicArea: "shopping" },
        { en: "Come to think of it, I forgot to submit the assignment.", bn: "এখন ভেবে দেখলে, আমি অ্যাসাইনমেন্ট জমা দিতে ভুলে গেছি।", slotValues: { CLAUSE: "I forgot to submit the assignment" }, topicArea: "education" },
        { en: "Come to think of it, we do have a lot in common.", bn: "এখন ভেবে দেখলে, আমাদের অনেক কিছু মিল আছে।", slotValues: { CLAUSE: "we do have a lot in common" }, topicArea: "relationships" },
        { en: "Come to think of it, I should have taken the earlier bus.", bn: "এখন ভেবে দেখলে, আমার আগের বাসটা ধরা উচিত ছিল।", slotValues: { CLAUSE: "I should have taken the earlier bus" }, topicArea: "travel" },
        { en: "Come to think of it, the recipe did call for garlic.", bn: "এখন ভেবে দেখলে, রেসিপিতে রসুনের কথা ছিল।", slotValues: { CLAUSE: "the recipe did call for garlic" }, topicArea: "food" },
        { en: "Come to think of it, maybe I should see a doctor.", bn: "এখন ভেবে দেখলে, হয়তো আমার ডাক্তার দেখানো উচিত।", slotValues: { CLAUSE: "maybe I should see a doctor" }, topicArea: "health" },
        { en: "Come to think of it, the project does need more funding.", bn: "এখন ভেবে দেখলে, প্রজেক্টে আরও তহবিল দরকার।", slotValues: { CLAUSE: "the project does need more funding" }, topicArea: "work" },
        { en: "Come to think of it, he was acting strangely.", bn: "এখন ভেবে দেখলে, সে অদ্ভুত আচরণ করছিল।", slotValues: { CLAUSE: "he was acting strangely" }, topicArea: "relationships" },
      ],
      formality: "casual", difficulty: "advanced",
      usageNote: "Used when you suddenly remember or realize something during a conversation. Very natural in spoken English.",
      usageNote_bn: "কথোপকথনের সময় হঠাৎ কিছু মনে পড়লে বা উপলব্ধি হলে ব্যবহৃত। কথ্য ইংরেজিতে খুবই স্বাভাবিক।",
      combinableWith: ["U8.2"],
      banglaStructureMap: "এখন ভেবে দেখলে (Come to think of it) + [বাক্যাংশ] (Clause)",
    },
    {
      id: "U8.4",
      formula: "It comes down to [THING]",
      formula_bn: "মূল বিষয় হলো [জিনিস]",
      patternName: "Comes Down To (Essence)",
      patternName_bn: "মূল বিষয় (সারমর্ম)",
      slots: [
        { name: "THING", description: "The essential factor or point", description_bn: "মূল কারণ বা বিষয়", acceptedTypes: ["noun", "noun_phrase", "gerund"], examples: ["money", "hard work", "personal choice"] },
      ],
      examples: [
        { en: "It all comes down to money.", bn: "সবকিছু মূলত টাকার ব্যাপার।", slotValues: { THING: "money" }, topicArea: "daily_life" },
        { en: "It comes down to hard work and dedication.", bn: "মূল বিষয় হলো কঠোর পরিশ্রম ও নিষ্ঠা।", slotValues: { THING: "hard work and dedication" }, topicArea: "work" },
        { en: "It comes down to personal choice.", bn: "মূল বিষয় হলো ব্যক্তিগত পছন্দ।", slotValues: { THING: "personal choice" }, topicArea: "daily_life" },
        { en: "In the end, it comes down to trust.", bn: "শেষ পর্যন্ত, মূল বিষয় হলো আস্থা।", slotValues: { THING: "trust" }, topicArea: "relationships" },
        { en: "It comes down to how much effort you put in.", bn: "মূল বিষয় হলো তুমি কতটা প্রচেষ্টা দাও।", slotValues: { THING: "how much effort you put in" }, topicArea: "education" },
        { en: "It comes down to taste.", bn: "মূল বিষয় হলো স্বাদ।", slotValues: { THING: "taste" }, topicArea: "food" },
        { en: "It comes down to planning ahead.", bn: "মূল বিষয় হলো আগে থেকে পরিকল্পনা করা।", slotValues: { THING: "planning ahead" }, topicArea: "travel" },
        { en: "It comes down to your overall lifestyle.", bn: "মূল বিষয় হলো তোমার সামগ্রিক জীবনযাত্রা।", slotValues: { THING: "your overall lifestyle" }, topicArea: "health" },
        { en: "It comes down to quality vs. price.", bn: "মূল বিষয় হলো মান বনাম দাম।", slotValues: { THING: "quality vs. price" }, topicArea: "shopping" },
        { en: "It comes down to teamwork.", bn: "মূল বিষয় হলো দলগত কাজ।", slotValues: { THING: "teamwork" }, topicArea: "work" },
        { en: "It comes down to respect.", bn: "মূল বিষয় হলো সম্মান।", slotValues: { THING: "respect" }, topicArea: "relationships" },
        { en: "It comes down to consistency.", bn: "মূল বিষয় হলো ধারাবাহিকতা।", slotValues: { THING: "consistency" }, topicArea: "education" },
        { en: "It comes down to location.", bn: "মূল বিষয় হলো অবস্থান।", slotValues: { THING: "location" }, topicArea: "travel" },
        { en: "It comes down to discipline.", bn: "মূল বিষয় হলো শৃঙ্খলা।", slotValues: { THING: "discipline" }, topicArea: "health" },
        { en: "It comes down to what you value most.", bn: "মূল বিষয় হলো তুমি কীসে সবচেয়ে বেশি মূল্য দাও।", slotValues: { THING: "what you value most" }, topicArea: "daily_life" },
      ],
      formality: "casual", difficulty: "advanced",
      usageNote: "Used to identify the most important or essential factor in a situation.",
      usageNote_bn: "একটি পরিস্থিতিতে সবচেয়ে গুরুত্বপূর্ণ বা মূল বিষয় চিহ্নিত করতে ব্যবহৃত।",
      combinableWith: ["U8.1"],
      banglaStructureMap: "মূল বিষয় হলো (Comes down to) + [জিনিস] (Thing)",
    },
    {
      id: "U8.5",
      formula: "[THING] comes in handy",
      formula_bn: "[জিনিস] কাজে আসে",
      patternName: "Comes In Handy (Useful)",
      patternName_bn: "কাজে আসে (উপকারী)",
      slots: [
        { name: "THING", description: "Something that turns out to be useful", description_bn: "কিছু যা উপকারী বলে প্রমাণিত হয়", acceptedTypes: ["noun", "noun_phrase"], examples: ["a flashlight", "knowing a second language", "this tool"] },
      ],
      examples: [
        { en: "A flashlight always comes in handy during power cuts.", bn: "বিদ্যুৎ না থাকলে একটা টর্চ সবসময় কাজে আসে।", slotValues: { THING: "A flashlight" }, topicArea: "daily_life" },
        { en: "Knowing a second language comes in handy when traveling.", bn: "ভ্রমণের সময় দ্বিতীয় ভাষা জানা কাজে আসে।", slotValues: { THING: "Knowing a second language" }, topicArea: "travel" },
        { en: "This tool will come in handy for the project.", bn: "এই টুলটি প্রজেক্টে কাজে আসবে।", slotValues: { THING: "This tool" }, topicArea: "work" },
        { en: "An umbrella comes in handy on rainy days.", bn: "বৃষ্টির দিনে ছাতা কাজে আসে।", slotValues: { THING: "An umbrella" }, topicArea: "daily_life" },
        { en: "A good recipe book comes in handy.", bn: "একটা ভালো রেসিপি বই কাজে আসে।", slotValues: { THING: "A good recipe book" }, topicArea: "food" },
        { en: "First aid knowledge comes in handy in emergencies.", bn: "জরুরি পরিস্থিতিতে প্রাথমিক চিকিৎসা জ্ঞান কাজে আসে।", slotValues: { THING: "First aid knowledge" }, topicArea: "health" },
        { en: "A credit card comes in handy when shopping online.", bn: "অনলাইনে কেনাকাটায় ক্রেডিট কার্ড কাজে আসে।", slotValues: { THING: "A credit card" }, topicArea: "shopping" },
        { en: "Extra notes come in handy before exams.", bn: "পরীক্ষার আগে অতিরিক্ত নোটস কাজে আসে।", slotValues: { THING: "Extra notes" }, topicArea: "education" },
        { en: "Having good connections comes in handy in business.", bn: "ব্যবসায় ভালো যোগাযোগ থাকা কাজে আসে।", slotValues: { THING: "Having good connections" }, topicArea: "work" },
        { en: "A portable charger comes in handy while traveling.", bn: "ভ্রমণের সময় পোর্টেবল চার্জার কাজে আসে।", slotValues: { THING: "A portable charger" }, topicArea: "travel" },
        { en: "Patience comes in handy when dealing with children.", bn: "বাচ্চাদের সামলাতে ধৈর্য কাজে আসে।", slotValues: { THING: "Patience" }, topicArea: "relationships" },
        { en: "A Swiss army knife comes in handy outdoors.", bn: "বাইরে সুইস আর্মি ছুরি কাজে আসে।", slotValues: { THING: "A Swiss army knife" }, topicArea: "daily_life" },
        { en: "Having a map comes in handy in unfamiliar areas.", bn: "অপরিচিত এলাকায় মানচিত্র থাকা কাজে আসে।", slotValues: { THING: "Having a map" }, topicArea: "travel" },
        { en: "Basic cooking skills come in handy for everyone.", bn: "সবার জন্য মৌলিক রান্নার দক্ষতা কাজে আসে।", slotValues: { THING: "Basic cooking skills" }, topicArea: "food" },
        { en: "A good dictionary comes in handy for language learners.", bn: "ভাষা শিক্ষার্থীদের জন্য একটা ভালো অভিধান কাজে আসে।", slotValues: { THING: "A good dictionary" }, topicArea: "education" },
      ],
      formality: "casual", difficulty: "advanced",
      usageNote: "Describes something that proves useful in a particular situation. Very common in casual conversation.",
      usageNote_bn: "একটি নির্দিষ্ট পরিস্থিতিতে কিছু উপকারী প্রমাণিত হওয়া বর্ণনা করে। সাধারণ কথোপকথনে খুবই প্রচলিত।",
      combinableWith: ["U8.1"],
      banglaStructureMap: "[জিনিস] (Subject) + কাজে আসে (Comes in handy)",
    },
  ],
};
