import { PatternCategory } from "@/types/pattern";

export const categoryV10: PatternCategory = {
  id: "V10",
  slug: "sarcasm-irony",
  name: "Sarcasm & Irony",
  name_bn: "ব্যঙ্গ ও বিদ্রূপ",
  description:
    "Sarcastic and ironic expressions where the intended meaning is opposite to the literal meaning",
  description_bn:
    "ব্যঙ্গাত্মক ও বিদ্রূপমূলক প্রকাশ যেখানে উদ্দেশ্যমূলক অর্থ আক্ষরিক অর্থের বিপরীত",
  icon: "🙄",
  group: "V",
  groupName: "Politeness & Register",
  groupName_bn: "ভদ্রতা ও ভাষার স্তর",
  difficulty: "advanced",
  patterns: [
    {
      id: "V10.1",
      formula: "Oh, great, [NEGATIVE THING]",
      formula_bn: "ওহ, দারুণ, [নেতিবাচক বিষয়]",
      patternName: "Oh Great (Sarcastic)",
      patternName_bn: "ওহ দারুণ (ব্যঙ্গাত্মক)",
      slots: [
        {
          name: "NEGATIVE THING",
          description: "An undesirable situation stated with mock enthusiasm",
          description_bn: "ভান করা উৎসাহের সাথে বলা একটি অনাকাঙ্ক্ষিত পরিস্থিতি",
          acceptedTypes: ["clause", "noun_phrase"],
          examples: [
            "another meeting",
            "the printer is broken again",
            "it's raining",
          ],
        },
      ],
      examples: [
        {
          en: "Oh, great, another meeting that could have been an email.",
          bn: "ওহ, দারুণ, আরেকটি মিটিং যেটা একটি ইমেইল হতে পারত।",
          slotValues: { "NEGATIVE THING": "another meeting that could have been an email" },
          topicArea: "work",
        },
        {
          en: "Oh, great, the printer is broken again.",
          bn: "ওহ, দারুণ, প্রিন্টার আবার নষ্ট।",
          slotValues: { "NEGATIVE THING": "the printer is broken again" },
          topicArea: "work",
        },
        {
          en: "Oh, great, it's raining on our picnic day.",
          bn: "ওহ, দারুণ, আমাদের পিকনিকের দিনে বৃষ্টি হচ্ছে।",
          slotValues: { "NEGATIVE THING": "it's raining on our picnic day" },
          topicArea: "daily_life",
        },
        {
          en: "Oh, great, the train is delayed again.",
          bn: "ওহ, দারুণ, ট্রেন আবার দেরি হচ্ছে।",
          slotValues: { "NEGATIVE THING": "the train is delayed again" },
          topicArea: "travel",
        },
        {
          en: "Oh, great, I forgot my wallet at home.",
          bn: "ওহ, দারুণ, আমি বাড়িতে মানিব্যাগ ফেলে এসেছি।",
          slotValues: { "NEGATIVE THING": "I forgot my wallet at home" },
          topicArea: "shopping",
        },
        {
          en: "Oh, great, the restaurant is fully booked.",
          bn: "ওহ, দারুণ, রেস্তোরাঁটি সম্পূর্ণ বুক হয়ে গেছে।",
          slotValues: { "NEGATIVE THING": "the restaurant is fully booked" },
          topicArea: "food",
        },
        {
          en: "Oh, great, we have a pop quiz today.",
          bn: "ওহ, দারুণ, আজ আমাদের হুট করে কুইজ আছে।",
          slotValues: { "NEGATIVE THING": "we have a pop quiz today" },
          topicArea: "education",
        },
        {
          en: "Oh, great, my phone just died.",
          bn: "ওহ, দারুণ, আমার ফোনের চার্জ শেষ হয়ে গেল।",
          slotValues: { "NEGATIVE THING": "my phone just died" },
          topicArea: "daily_life",
        },
        {
          en: "Oh, great, the dentist appointment got moved to Monday.",
          bn: "ওহ, দারুণ, ডেন্টিস্টের অ্যাপয়েন্টমেন্ট সোমবারে সরে গেছে।",
          slotValues: { "NEGATIVE THING": "the dentist appointment got moved to Monday" },
          topicArea: "health",
        },
        {
          en: "Oh, great, we're stuck in traffic again.",
          bn: "ওহ, দারুণ, আমরা আবার যানজটে আটকা পড়েছি।",
          slotValues: { "NEGATIVE THING": "we're stuck in traffic again" },
          topicArea: "travel",
        },
        {
          en: "Oh, great, the boss wants to see me.",
          bn: "ওহ, দারুণ, বস আমাকে দেখতে চান।",
          slotValues: { "NEGATIVE THING": "the boss wants to see me" },
          topicArea: "work",
        },
        {
          en: "Oh, great, my neighbor is playing loud music again.",
          bn: "ওহ, দারুণ, আমার প্রতিবেশী আবার জোরে গান বাজাচ্ছে।",
          slotValues: { "NEGATIVE THING": "my neighbor is playing loud music again" },
          topicArea: "daily_life",
        },
        {
          en: "Oh, great, the wifi is down.",
          bn: "ওহ, দারুণ, ওয়াইফাই বন্ধ।",
          slotValues: { "NEGATIVE THING": "the wifi is down" },
          topicArea: "daily_life",
        },
        {
          en: "Oh, great, they changed the deadline to tomorrow.",
          bn: "ওহ, দারুণ, তারা সময়সীমা আগামীকালে পরিবর্তন করেছে।",
          slotValues: { "NEGATIVE THING": "they changed the deadline to tomorrow" },
          topicArea: "work",
        },
        {
          en: "Oh, great, I burned the dinner.",
          bn: "ওহ, দারুণ, আমি রাতের খাবার পুড়িয়ে ফেলেছি।",
          slotValues: { "NEGATIVE THING": "I burned the dinner" },
          topicArea: "food",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
      usageNote:
        "Classic sarcasm where 'great' means the opposite. Tone of voice is crucial -- a flat, unenthusiastic delivery signals sarcasm.",
      usageNote_bn:
        "ক্লাসিক ব্যঙ্গ যেখানে 'great' বিপরীত অর্থে ব্যবহৃত। কণ্ঠস্বর গুরুত্বপূর্ণ -- সমান, উৎসাহহীন উচ্চারণ ব্যঙ্গের সংকেত দেয়।",
      combinableWith: ["V10.3"],
      banglaStructureMap:
        "ওহ, দারুণ (Oh, Great - Sarcastic), + [নেতিবাচক বিষয়] (Negative Situation)",
    },
    {
      id: "V10.2",
      formula: "Yeah, right",
      formula_bn: "হ্যাঁ, তাই নাকি",
      patternName: "Yeah Right (Disbelief)",
      patternName_bn: "হ্যাঁ তাই নাকি (অবিশ্বাস)",
      slots: [],
      examples: [
        {
          en: "Yeah, right, like you've ever been on time.",
          bn: "হ্যাঁ, তাই নাকি, যেন তুমি কখনো সময়মতো এসেছ।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Yeah, right, he's going to clean the entire house.",
          bn: "হ্যাঁ, তাই নাকি, সে পুরো বাড়ি পরিষ্কার করবে।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Yeah, right, the project will be done by Friday.",
          bn: "হ্যাঁ, তাই নাকি, প্রকল্প শুক্রবারের মধ্যে শেষ হবে।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "Yeah, right, you'll start going to the gym tomorrow.",
          bn: "হ্যাঁ, তাই নাকি, তুমি আগামীকাল থেকে জিমে যাওয়া শুরু করবে।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "Yeah, right, you can eat just one chip.",
          bn: "হ্যাঁ, তাই নাকি, তুমি শুধু একটা চিপস খেতে পারবে।",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "Yeah, right, they'll fix the roads this year.",
          bn: "হ্যাঁ, তাই নাকি, তারা এই বছর রাস্তা ঠিক করবে।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "Yeah, right, the bus will come on time.",
          bn: "হ্যাঁ, তাই নাকি, বাস সময়মতো আসবে।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "Yeah, right, she said she'd call back in five minutes.",
          bn: "হ্যাঁ, তাই নাকি, সে বলেছিল পাঁচ মিনিটে কল ব্যাক করবে।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "Yeah, right, you didn't eat the last piece of cake.",
          bn: "হ্যাঁ, তাই নাকি, তুমি কেকের শেষ টুকরো খাওনি।",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "Yeah, right, the sale is 90% off everything.",
          bn: "হ্যাঁ, তাই নাকি, সেলে সবকিছুতে ৯০% ছাড়।",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "Yeah, right, you read the entire textbook in one night.",
          bn: "হ্যাঁ, তাই নাকি, তুমি এক রাতে পুরো পাঠ্যবই পড়েছ।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "Yeah, right, he's going to quit social media.",
          bn: "হ্যাঁ, তাই নাকি, সে সোশ্যাল মিডিয়া ছাড়বে।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Yeah, right, the meeting will only take ten minutes.",
          bn: "হ্যাঁ, তাই নাকি, মিটিং মাত্র দশ মিনিট লাগবে।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "Yeah, right, you're going to wake up at 5 AM.",
          bn: "হ্যাঁ, তাই নাকি, তুমি সকাল ৫টায় উঠবে।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Yeah, right, the doctor said I should eat more chocolate.",
          bn: "হ্যাঁ, তাই নাকি, ডাক্তার বলেছেন আমার আরও চকলেট খাওয়া উচিত।",
          slotValues: {},
          topicArea: "health",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
      usageNote:
        "Expresses disbelief or sarcastic agreement. The speaker does NOT actually agree. Relies heavily on tone -- without the sarcastic tone, it sounds like genuine agreement.",
      usageNote_bn:
        "অবিশ্বাস বা ব্যঙ্গাত্মক সম্মতি প্রকাশ করে। বক্তা আসলে সম্মত নন। কণ্ঠস্বরের উপর অনেক নির্ভর করে -- ব্যঙ্গাত্মক সুর ছাড়া এটা সত্যিকারের সম্মতির মতো শোনায়।",
      combinableWith: ["V10.1"],
      banglaStructureMap:
        "হ্যাঁ, তাই নাকি (Yeah, Right - Sarcastic)",
    },
    {
      id: "V10.3",
      formula: "What a surprise",
      formula_bn: "কী আশ্চর্য",
      patternName: "What A Surprise (Sarcastic)",
      patternName_bn: "কী আশ্চর্য (ব্যঙ্গাত্মক)",
      slots: [],
      examples: [
        {
          en: "What a surprise, he's late again.",
          bn: "কী আশ্চর্য, সে আবার দেরি করেছে।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "What a surprise, the software crashed during the presentation.",
          bn: "কী আশ্চর্য, প্রেজেন্টেশনের সময় সফটওয়্যার ক্র্যাশ করেছে।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "What a surprise, the food is cold again.",
          bn: "কী আশ্চর্য, খাবার আবার ঠান্ডা।",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "What a surprise, the flight is delayed.",
          bn: "কী আশ্চর্য, ফ্লাইট দেরি হচ্ছে।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "What a surprise, the meeting ran overtime.",
          bn: "কী আশ্চর্য, মিটিং সময়ের বেশি চলেছে।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "What a surprise, it started raining as soon as I washed my car.",
          bn: "কী আশ্চর্য, গাড়ি ধোয়ার সাথে সাথে বৃষ্টি শুরু হলো।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "What a surprise, the test was harder than expected.",
          bn: "কী আশ্চর্য, পরীক্ষা প্রত্যাশার চেয়ে কঠিন ছিল।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "What a surprise, the product doesn't match the advertisement.",
          bn: "কী আশ্চর্য, পণ্যটি বিজ্ঞাপনের সাথে মেলেনি।",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "What a surprise, there's no parking available.",
          bn: "কী আশ্চর্য, পার্কিং পাওয়া যাচ্ছে না।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "What a surprise, the waiting room is packed.",
          bn: "কী আশ্চর্য, ওয়েটিং রুম ভর্তি।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "What a surprise, he forgot our anniversary again.",
          bn: "কী আশ্চর্য, সে আবার আমাদের বার্ষিকী ভুলে গেছে।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "What a surprise, the customer service line is busy.",
          bn: "কী আশ্চর্য, কাস্টমার সার্ভিস লাইন ব্যস্ত।",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "What a surprise, the homework was assigned on a Friday.",
          bn: "কী আশ্চর্য, শুক্রবারে হোমওয়ার্ক দেওয়া হয়েছে।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "What a surprise, the elevator is out of order.",
          bn: "কী আশ্চর্য, লিফট নষ্ট।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "What a surprise, the budget was underestimated.",
          bn: "কী আশ্চর্য, বাজেট কম ধরা হয়েছিল।",
          slotValues: {},
          topicArea: "work",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
      usageNote:
        "Used when something predictable happens and you pretend to be surprised. The flat, dry tone indicates you're not surprised at all.",
      usageNote_bn:
        "যখন কিছু পূর্বানুমানযোগ্য ঘটে এবং আপনি অবাক হওয়ার ভান করেন। সমতল, শুষ্ক সুর নির্দেশ করে আপনি মোটেও অবাক নন।",
      combinableWith: ["V10.1"],
      banglaStructureMap:
        "কী আশ্চর্য (What A Surprise - Sarcastic)",
    },
    {
      id: "V10.4",
      formula: "Like that's going to work",
      formula_bn: "যেন সেটা কাজ করবে",
      patternName: "Like That's Going To Work",
      patternName_bn: "যেন কাজ করবে",
      slots: [],
      examples: [
        {
          en: "Like that's going to work. We've tried that approach three times.",
          bn: "যেন সেটা কাজ করবে। আমরা সেই পদ্ধতি তিনবার চেষ্টা করেছি।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "Like that's going to work. The last diet didn't help either.",
          bn: "যেন সেটা কাজ করবে। শেষ ডায়েটও কাজে আসেনি।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "Like that's going to work. He never listens to advice.",
          bn: "যেন সেটা কাজ করবে। সে কখনো পরামর্শ শোনে না।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "Like that's going to work. The recipe clearly says to use butter.",
          bn: "যেন সেটা কাজ করবে। রেসিপিতে স্পষ্ট লেখা মাখন ব্যবহার করতে।",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "Like that's going to work. You can't fix a car with duct tape.",
          bn: "যেন সেটা কাজ করবে। টেপ দিয়ে গাড়ি ঠিক করা যায় না।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Like that's going to work. Studying the night before never helps.",
          bn: "যেন সেটা কাজ করবে। আগের রাতে পড়া কখনো কাজে আসে না।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "Like that's going to work. A shorter deadline won't improve quality.",
          bn: "যেন সেটা কাজ করবে। কম সময়সীমা মান উন্নত করবে না।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "Like that's going to work. You can't negotiate with that vendor.",
          bn: "যেন সেটা কাজ করবে। সেই বিক্রেতার সাথে দরকষাকষি করা যায় না।",
          slotValues: {},
          topicArea: "shopping",
        },
        {
          en: "Like that's going to work. Taking a shortcut always takes longer.",
          bn: "যেন সেটা কাজ করবে। শর্টকাট নিলে সবসময় বেশি সময় লাগে।",
          slotValues: {},
          topicArea: "travel",
        },
        {
          en: "Like that's going to work. Ignoring the problem won't make it go away.",
          bn: "যেন সেটা কাজ করবে। সমস্যা উপেক্ষা করলে তা চলে যাবে না।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Like that's going to work. They rejected the same idea last month.",
          bn: "যেন সেটা কাজ করবে। গত মাসে তারা একই ধারণা প্রত্যাখ্যান করেছে।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "Like that's going to work. Yelling at the computer won't fix it.",
          bn: "যেন সেটা কাজ করবে। কম্পিউটারে চিৎকার করলে ঠিক হবে না।",
          slotValues: {},
          topicArea: "daily_life",
        },
        {
          en: "Like that's going to work. Skipping meals isn't a healthy strategy.",
          bn: "যেন সেটা কাজ করবে। খাবার বাদ দেওয়া স্বাস্থ্যকর কৌশল নয়।",
          slotValues: {},
          topicArea: "health",
        },
        {
          en: "Like that's going to work. You can't grow tomatoes in winter.",
          bn: "যেন সেটা কাজ করবে। শীতকালে টমেটো চাষ করা যায় না।",
          slotValues: {},
          topicArea: "food",
        },
        {
          en: "Like that's going to work. Sending another email won't get a response.",
          bn: "যেন সেটা কাজ করবে। আরেকটি ইমেইল পাঠালে উত্তর আসবে না।",
          slotValues: {},
          topicArea: "work",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
      usageNote:
        "Expresses skepticism about a plan or idea. 'Like' at the beginning signals that what follows is obviously not going to happen. Very dismissive.",
      usageNote_bn:
        "কোনো পরিকল্পনা বা ধারণা সম্পর্কে সন্দেহ প্রকাশ করে। শুরুতে 'Like' সংকেত দেয় যে পরবর্তী বিষয়টি স্পষ্টতই ঘটবে না। খুবই উপেক্ষামূলক।",
      combinableWith: ["V10.2"],
      banglaStructureMap:
        "যেন (Like/As If) + সেটা কাজ করবে (That Will Work - Sarcastic)",
    },
    {
      id: "V10.5",
      formula: "Sure, because [OBVIOUS CONTRADICTION]",
      formula_bn: "অবশ্যই, কারণ [সুস্পষ্ট বিরোধ]",
      patternName: "Sure Because (Ironic)",
      patternName_bn: "অবশ্যই কারণ (বিদ্রূপমূলক)",
      slots: [
        {
          name: "OBVIOUS CONTRADICTION",
          description: "A clearly false or absurd statement that highlights the irony",
          description_bn: "একটি স্পষ্টতই ভুল বা অযৌক্তিক বিবৃতি যা বিদ্রূপ তুলে ধরে",
          acceptedTypes: ["clause"],
          examples: [
            "that always works out perfectly",
            "people love working on weekends",
            "money grows on trees",
          ],
        },
      ],
      examples: [
        {
          en: "Sure, because that always works out perfectly.",
          bn: "অবশ্যই, কারণ সেটা সবসময় নিখুঁতভাবে কাজ করে।",
          slotValues: { "OBVIOUS CONTRADICTION": "that always works out perfectly" },
          topicArea: "daily_life",
        },
        {
          en: "Sure, because people love working on weekends.",
          bn: "অবশ্যই, কারণ মানুষ সাপ্তাহিক ছুটিতে কাজ করতে ভালোবাসে।",
          slotValues: { "OBVIOUS CONTRADICTION": "people love working on weekends" },
          topicArea: "work",
        },
        {
          en: "Sure, because money grows on trees.",
          bn: "অবশ্যই, কারণ গাছে টাকা ধরে।",
          slotValues: { "OBVIOUS CONTRADICTION": "money grows on trees" },
          topicArea: "daily_life",
        },
        {
          en: "Sure, because adding more people to a late project makes it faster.",
          bn: "অবশ্যই, কারণ দেরি হওয়া প্রকল্পে আরও লোক যোগ করলে দ্রুত হয়।",
          slotValues: { "OBVIOUS CONTRADICTION": "adding more people to a late project makes it faster" },
          topicArea: "work",
        },
        {
          en: "Sure, because eating junk food every day is totally healthy.",
          bn: "অবশ্যই, কারণ প্রতিদিন জাংক ফুড খাওয়া পুরোপুরি স্বাস্থ্যকর।",
          slotValues: { "OBVIOUS CONTRADICTION": "eating junk food every day is totally healthy" },
          topicArea: "health",
        },
        {
          en: "Sure, because everyone finishes their homework on time.",
          bn: "অবশ্যই, কারণ সবাই সময়মতো হোমওয়ার্ক শেষ করে।",
          slotValues: { "OBVIOUS CONTRADICTION": "everyone finishes their homework on time" },
          topicArea: "education",
        },
        {
          en: "Sure, because the cheaper option is always better.",
          bn: "অবশ্যই, কারণ সস্তা অপশন সবসময় ভালো।",
          slotValues: { "OBVIOUS CONTRADICTION": "the cheaper option is always better" },
          topicArea: "shopping",
        },
        {
          en: "Sure, because flights are never delayed.",
          bn: "অবশ্যই, কারণ ফ্লাইট কখনো দেরি হয় না।",
          slotValues: { "OBVIOUS CONTRADICTION": "flights are never delayed" },
          topicArea: "travel",
        },
        {
          en: "Sure, because a five-minute fix never takes three hours.",
          bn: "অবশ্যই, কারণ পাঁচ মিনিটের কাজে কখনো তিন ঘণ্টা লাগে না।",
          slotValues: { "OBVIOUS CONTRADICTION": "a five-minute fix never takes three hours" },
          topicArea: "daily_life",
        },
        {
          en: "Sure, because all restaurants serve perfect food every time.",
          bn: "অবশ্যই, কারণ সব রেস্তোরাঁ প্রতিবার নিখুঁত খাবার পরিবেশন করে।",
          slotValues: { "OBVIOUS CONTRADICTION": "all restaurants serve perfect food every time" },
          topicArea: "food",
        },
        {
          en: "Sure, because promising to change always means actual change.",
          bn: "অবশ্যই, কারণ পরিবর্তনের প্রতিশ্রুতি সবসময় প্রকৃত পরিবর্তন বোঝায়।",
          slotValues: { "OBVIOUS CONTRADICTION": "promising to change always means actual change" },
          topicArea: "relationships",
        },
        {
          en: "Sure, because reading the manual is what everyone does first.",
          bn: "অবশ্যই, কারণ ম্যানুয়াল পড়া সবাই প্রথমে করে।",
          slotValues: { "OBVIOUS CONTRADICTION": "reading the manual is what everyone does first" },
          topicArea: "daily_life",
        },
        {
          en: "Sure, because one more meeting will solve everything.",
          bn: "অবশ্যই, কারণ আরেকটি মিটিং সবকিছু সমাধান করবে।",
          slotValues: { "OBVIOUS CONTRADICTION": "one more meeting will solve everything" },
          topicArea: "work",
        },
        {
          en: "Sure, because sleeping for three hours is enough rest.",
          bn: "অবশ্যই, কারণ তিন ঘণ্টা ঘুম যথেষ্ট বিশ্রাম।",
          slotValues: { "OBVIOUS CONTRADICTION": "sleeping for three hours is enough rest" },
          topicArea: "health",
        },
        {
          en: "Sure, because cramming the night before always leads to top marks.",
          bn: "অবশ্যই, কারণ আগের রাতে মুখস্ত করলে সবসময় সেরা নম্বর পাওয়া যায়।",
          slotValues: { "OBVIOUS CONTRADICTION": "cramming the night before always leads to top marks" },
          topicArea: "education",
        },
      ],
      formality: "casual",
      difficulty: "advanced",
      usageNote:
        "Heavy irony. The speaker says 'sure' as if agreeing, then follows with something obviously untrue to mock the original idea. Very common in everyday sarcasm.",
      usageNote_bn:
        "ভারী বিদ্রূপ। বক্তা সম্মত হওয়ার ভান করে 'sure' বলে, তারপর মূল ধারণাকে উপহাস করতে স্পষ্টতই অসত্য কিছু বলে। দৈনন্দিন ব্যঙ্গে খুবই সাধারণ।",
      combinableWith: ["V10.2", "V10.4"],
      banglaStructureMap:
        "অবশ্যই (Sure - Sarcastic), + কারণ (Because) + [সুস্পষ্ট বিরোধ] (Obvious Contradiction)",
    },
  ],
};
