import { PatternCategory } from "@/types/pattern";

export const categoryV2: PatternCategory = {
  id: "V2",
  slug: "formal-email-openings",
  name: "Formal Email Openings",
  name_bn: "আনুষ্ঠানিক ইমেইল শুরু",
  description:
    "Professional ways to begin formal emails and business correspondence",
  description_bn:
    "আনুষ্ঠানিক ইমেইল ও ব্যবসায়িক চিঠিপত্র শুরু করার পেশাদার উপায়",
  icon: "📧",
  group: "V",
  groupName: "Politeness & Register",
  groupName_bn: "ভদ্রতা ও ভাষার স্তর",
  difficulty: "intermediate",
  patterns: [
    {
      id: "V2.1",
      formula: "I am writing to [PURPOSE]",
      formula_bn: "আমি [উদ্দেশ্য]-এর জন্য লিখছি",
      patternName: "I Am Writing To",
      patternName_bn: "আমি লিখছি",
      slots: [
        {
          name: "PURPOSE",
          description: "The purpose of the email",
          description_bn: "ইমেইলের উদ্দেশ্য",
          acceptedTypes: ["verb_phrase", "clause"],
          examples: ["inquire about", "request information", "apply for the position"],
        },
      ],
      examples: [
        {
          en: "I am writing to inquire about the job vacancy.",
          bn: "আমি চাকরির শূন্যপদ সম্পর্কে জানতে লিখছি।",
          slotValues: { PURPOSE: "inquire about the job vacancy" },
          topicArea: "work",
        },
        {
          en: "I am writing to request a meeting with your team.",
          bn: "আমি আপনার দলের সাথে একটি মিটিংয়ের অনুরোধ করতে লিখছি।",
          slotValues: { PURPOSE: "request a meeting with your team" },
          topicArea: "work",
        },
        {
          en: "I am writing to apply for the marketing position.",
          bn: "আমি মার্কেটিং পদে আবেদন করতে লিখছি।",
          slotValues: { PURPOSE: "apply for the marketing position" },
          topicArea: "work",
        },
        {
          en: "I am writing to confirm my attendance at the conference.",
          bn: "আমি সম্মেলনে আমার উপস্থিতি নিশ্চিত করতে লিখছি।",
          slotValues: { PURPOSE: "confirm my attendance at the conference" },
          topicArea: "work",
        },
        {
          en: "I am writing to express my interest in the internship.",
          bn: "আমি ইন্টার্নশিপে আমার আগ্রহ প্রকাশ করতে লিখছি।",
          slotValues: { PURPOSE: "express my interest in the internship" },
          topicArea: "education",
        },
        {
          en: "I am writing to follow up on our previous discussion.",
          bn: "আমি আমাদের আগের আলোচনার অনুসরণে লিখছি।",
          slotValues: { PURPOSE: "follow up on our previous discussion" },
          topicArea: "work",
        },
        {
          en: "I am writing to submit my project proposal.",
          bn: "আমি আমার প্রকল্প প্রস্তাব জমা দিতে লিখছি।",
          slotValues: { PURPOSE: "submit my project proposal" },
          topicArea: "work",
        },
        {
          en: "I am writing to seek clarification on the new policy.",
          bn: "আমি নতুন নীতি সম্পর্কে স্পষ্টতা চাইতে লিখছি।",
          slotValues: { PURPOSE: "seek clarification on the new policy" },
          topicArea: "work",
        },
        {
          en: "I am writing to invite you to our annual event.",
          bn: "আমি আপনাকে আমাদের বার্ষিক অনুষ্ঠানে আমন্ত্রণ জানাতে লিখছি।",
          slotValues: { PURPOSE: "invite you to our annual event" },
          topicArea: "daily_life",
        },
        {
          en: "I am writing to request an extension on the assignment.",
          bn: "আমি অ্যাসাইনমেন্টের সময়সীমা বাড়ানোর অনুরোধ করতে লিখছি।",
          slotValues: { PURPOSE: "request an extension on the assignment" },
          topicArea: "education",
        },
        {
          en: "I am writing to inform you of a change in schedule.",
          bn: "আমি সময়সূচিতে পরিবর্তনের বিষয়ে জানাতে লিখছি।",
          slotValues: { PURPOSE: "inform you of a change in schedule" },
          topicArea: "work",
        },
        {
          en: "I am writing to complain about the service I received.",
          bn: "আমি আমার প্রাপ্ত সেবা সম্পর্কে অভিযোগ জানাতে লিখছি।",
          slotValues: { PURPOSE: "complain about the service I received" },
          topicArea: "daily_life",
        },
        {
          en: "I am writing to recommend a colleague for the award.",
          bn: "আমি পুরস্কারের জন্য একজন সহকর্মীকে সুপারিশ করতে লিখছি।",
          slotValues: { PURPOSE: "recommend a colleague for the award" },
          topicArea: "work",
        },
        {
          en: "I am writing to ask about admission requirements.",
          bn: "আমি ভর্তির প্রয়োজনীয়তা সম্পর্কে জানতে লিখছি।",
          slotValues: { PURPOSE: "ask about admission requirements" },
          topicArea: "education",
        },
        {
          en: "I am writing to update you on the project status.",
          bn: "আমি প্রকল্পের অবস্থা সম্পর্কে আপনাকে জানাতে লিখছি।",
          slotValues: { PURPOSE: "update you on the project status" },
          topicArea: "work",
        },
      ],
      formality: "formal",
      difficulty: "intermediate",
      usageNote:
        "The most common way to open a formal email. Immediately states your purpose, which is considered professional and respectful of the reader's time.",
      usageNote_bn:
        "আনুষ্ঠানিক ইমেইল শুরু করার সবচেয়ে সাধারণ উপায়। তাৎক্ষণিকভাবে উদ্দেশ্য জানায়, যা পেশাদার এবং পাঠকের সময়ের প্রতি সম্মানজনক।",
      combinableWith: ["V3.1"],
      banglaStructureMap:
        "আমি (Subject) + [উদ্দেশ্য]-এর জন্য (Purpose + Postposition) + লিখছি (Verb + Progressive)",
    },
    {
      id: "V2.2",
      formula: "I am writing in regard to [THING]",
      formula_bn: "আমি [বিষয়] সম্পর্কে লিখছি",
      patternName: "Writing In Regard To",
      patternName_bn: "সম্পর্কে লিখছি",
      slots: [
        {
          name: "THING",
          description: "The subject or matter being referenced",
          description_bn: "যে বিষয় বা প্রসঙ্গ উল্লেখ করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase", "topic"],
          examples: ["your advertisement", "the open position", "the recent incident"],
        },
      ],
      examples: [
        {
          en: "I am writing in regard to your advertisement in the newspaper.",
          bn: "আমি পত্রিকায় আপনার বিজ্ঞাপন সম্পর্কে লিখছি।",
          slotValues: { THING: "your advertisement in the newspaper" },
          topicArea: "work",
        },
        {
          en: "I am writing in regard to the open position of accountant.",
          bn: "আমি হিসাবরক্ষকের শূন্যপদ সম্পর্কে লিখছি।",
          slotValues: { THING: "the open position of accountant" },
          topicArea: "work",
        },
        {
          en: "I am writing in regard to the recent incident at the office.",
          bn: "আমি অফিসে সাম্প্রতিক ঘটনা সম্পর্কে লিখছি।",
          slotValues: { THING: "the recent incident at the office" },
          topicArea: "work",
        },
        {
          en: "I am writing in regard to your order number 4521.",
          bn: "আমি আপনার অর্ডার নম্বর ৪৫২১ সম্পর্কে লিখছি।",
          slotValues: { THING: "your order number 4521" },
          topicArea: "shopping",
        },
        {
          en: "I am writing in regard to the partnership proposal.",
          bn: "আমি অংশীদারি প্রস্তাব সম্পর্কে লিখছি।",
          slotValues: { THING: "the partnership proposal" },
          topicArea: "work",
        },
        {
          en: "I am writing in regard to the scholarship application.",
          bn: "আমি বৃত্তির আবেদন সম্পর্কে লিখছি।",
          slotValues: { THING: "the scholarship application" },
          topicArea: "education",
        },
        {
          en: "I am writing in regard to the lease agreement.",
          bn: "আমি লিজ চুক্তি সম্পর্কে লিখছি।",
          slotValues: { THING: "the lease agreement" },
          topicArea: "daily_life",
        },
        {
          en: "I am writing in regard to the complaint filed last week.",
          bn: "আমি গত সপ্তাহে দাখিল করা অভিযোগ সম্পর্কে লিখছি।",
          slotValues: { THING: "the complaint filed last week" },
          topicArea: "work",
        },
        {
          en: "I am writing in regard to the upcoming training session.",
          bn: "আমি আসন্ন প্রশিক্ষণ সেশন সম্পর্কে লিখছি।",
          slotValues: { THING: "the upcoming training session" },
          topicArea: "work",
        },
        {
          en: "I am writing in regard to the damaged goods we received.",
          bn: "আমি আমাদের প্রাপ্ত ক্ষতিগ্রস্ত পণ্য সম্পর্কে লিখছি।",
          slotValues: { THING: "the damaged goods we received" },
          topicArea: "shopping",
        },
        {
          en: "I am writing in regard to your request for a transfer.",
          bn: "আমি আপনার স্থানান্তরের অনুরোধ সম্পর্কে লিখছি।",
          slotValues: { THING: "your request for a transfer" },
          topicArea: "work",
        },
        {
          en: "I am writing in regard to the health insurance claim.",
          bn: "আমি স্বাস্থ্য বীমার দাবি সম্পর্কে লিখছি।",
          slotValues: { THING: "the health insurance claim" },
          topicArea: "health",
        },
        {
          en: "I am writing in regard to the course registration issue.",
          bn: "আমি কোর্স নিবন্ধনের সমস্যা সম্পর্কে লিখছি।",
          slotValues: { THING: "the course registration issue" },
          topicArea: "education",
        },
        {
          en: "I am writing in regard to the renovation of the office.",
          bn: "আমি অফিস সংস্কার সম্পর্কে লিখছি।",
          slotValues: { THING: "the renovation of the office" },
          topicArea: "work",
        },
        {
          en: "I am writing in regard to the annual budget review.",
          bn: "আমি বার্ষিক বাজেট পর্যালোচনা সম্পর্কে লিখছি।",
          slotValues: { THING: "the annual budget review" },
          topicArea: "work",
        },
      ],
      formality: "very_formal",
      difficulty: "intermediate",
      usageNote:
        "More formal than 'about.' Used to reference a specific topic or prior communication. Common in legal, HR, and official correspondence.",
      usageNote_bn:
        "'about'-এর চেয়ে বেশি আনুষ্ঠানিক। একটি নির্দিষ্ট বিষয় বা পূর্বের যোগাযোগ উল্লেখ করতে ব্যবহৃত। আইনি, এইচআর এবং সরকারি চিঠিপত্রে সাধারণ।",
      combinableWith: ["V2.1"],
      banglaStructureMap:
        "আমি (Subject) + [বিষয়] সম্পর্কে (Topic + Postposition) + লিখছি (Verb + Progressive)",
    },
    {
      id: "V2.3",
      formula: "I hope this email finds you well",
      formula_bn: "আশা করি আপনি ভালো আছেন",
      patternName: "Hope This Finds You Well",
      patternName_bn: "আশা করি ভালো আছেন",
      slots: [],
      examples: [
        {
          en: "I hope this email finds you well. I wanted to discuss the project timeline.",
          bn: "আশা করি আপনি ভালো আছেন। আমি প্রকল্পের সময়সীমা নিয়ে আলোচনা করতে চেয়েছিলাম।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "I hope this email finds you well. I am reaching out regarding our partnership.",
          bn: "আশা করি আপনি ভালো আছেন। আমি আমাদের অংশীদারি বিষয়ে যোগাযোগ করছি।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "I hope this email finds you well. Thank you for your prompt response last time.",
          bn: "আশা করি আপনি ভালো আছেন। গতবার দ্রুত সাড়া দেওয়ার জন্য ধন্যবাদ।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "I hope this email finds you well. I have a quick question about the budget.",
          bn: "আশা করি আপনি ভালো আছেন। বাজেট নিয়ে আমার একটি সংক্ষিপ্ত প্রশ্ন আছে।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "I hope this email finds you well. I am writing to share some good news.",
          bn: "আশা করি আপনি ভালো আছেন। কিছু ভালো খবর জানাতে লিখছি।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "I hope this email finds you well. Could we schedule a call this week?",
          bn: "আশা করি আপনি ভালো আছেন। আমরা কি এই সপ্তাহে একটি কল করতে পারি?",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "I hope this email finds you well. I wanted to introduce myself as the new manager.",
          bn: "আশা করি আপনি ভালো আছেন। আমি নতুন ম্যানেজার হিসেবে নিজের পরিচয় দিতে চেয়েছিলাম।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "I hope this email finds you well. Please find the attached document.",
          bn: "আশা করি আপনি ভালো আছেন। অনুগ্রহ করে সংযুক্ত নথিটি দেখুন।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "I hope this email finds you well. It has been a while since we last spoke.",
          bn: "আশা করি আপনি ভালো আছেন। আমাদের শেষ কথা বলার পর বেশ কিছুদিন হয়ে গেছে।",
          slotValues: {},
          topicArea: "relationships",
        },
        {
          en: "I hope this email finds you well. I would like to request your guidance.",
          bn: "আশা করি আপনি ভালো আছেন। আমি আপনার পরামর্শ চাইতে চাই।",
          slotValues: {},
          topicArea: "education",
        },
        {
          en: "I hope this email finds you well. I am following up on my previous email.",
          bn: "আশা করি আপনি ভালো আছেন। আমি আমার আগের ইমেইলের অনুসরণে লিখছি।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "I hope this email finds you well. We have an exciting opportunity to share.",
          bn: "আশা করি আপনি ভালো আছেন। আমাদের একটি চমৎকার সুযোগ শেয়ার করার আছে।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "I hope this email finds you well. I am writing on behalf of the committee.",
          bn: "আশা করি আপনি ভালো আছেন। আমি কমিটির পক্ষ থেকে লিখছি।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "I hope this email finds you well. I look forward to your valuable input.",
          bn: "আশা করি আপনি ভালো আছেন। আপনার মূল্যবান মতামতের অপেক্ষায় আছি।",
          slotValues: {},
          topicArea: "work",
        },
        {
          en: "I hope this email finds you well. I wanted to check in about the delivery.",
          bn: "আশা করি আপনি ভালো আছেন। ডেলিভারি সম্পর্কে জানতে চেয়েছিলাম।",
          slotValues: {},
          topicArea: "shopping",
        },
      ],
      formality: "formal",
      difficulty: "intermediate",
      usageNote:
        "A universally used email greeting. While some consider it a cliche, it remains the standard professional opening in English-language emails.",
      usageNote_bn:
        "একটি সর্বজনীনভাবে ব্যবহৃত ইমেইল অভিবাদন। কেউ কেউ এটিকে গৎবাঁধা মনে করলেও ইংরেজি ভাষার ইমেইলে এটি মানসম্মত পেশাদার শুরু হিসেবে রয়ে গেছে।",
      combinableWith: ["V2.1", "V2.2"],
      banglaStructureMap:
        "আশা করি (Hope) + আপনি (Subject) + ভালো আছেন (Well + Copula)",
    },
    {
      id: "V2.4",
      formula: "Further to our conversation, [CLAUSE]",
      formula_bn: "আমাদের কথোপকথনের পরিপ্রেক্ষিতে, [বাক্য]",
      patternName: "Further To Our Conversation",
      patternName_bn: "আমাদের কথোপকথনের পরিপ্রেক্ষিতে",
      slots: [
        {
          name: "CLAUSE",
          description: "The follow-up statement or action being taken",
          description_bn: "পরবর্তী বিবৃতি বা যে পদক্ষেপ নেওয়া হচ্ছে",
          acceptedTypes: ["clause"],
          examples: [
            "I am sending the documents",
            "please find the details below",
            "I have arranged the meeting",
          ],
        },
      ],
      examples: [
        {
          en: "Further to our conversation, I am sending the required documents.",
          bn: "আমাদের কথোপকথনের পরিপ্রেক্ষিতে, আমি প্রয়োজনীয় নথি পাঠাচ্ছি।",
          slotValues: { CLAUSE: "I am sending the required documents" },
          topicArea: "work",
        },
        {
          en: "Further to our conversation, please find the details below.",
          bn: "আমাদের কথোপকথনের পরিপ্রেক্ষিতে, অনুগ্রহ করে নিচে বিবরণ দেখুন।",
          slotValues: { CLAUSE: "please find the details below" },
          topicArea: "work",
        },
        {
          en: "Further to our conversation, I have arranged the meeting for Thursday.",
          bn: "আমাদের কথোপকথনের পরিপ্রেক্ষিতে, আমি বৃহস্পতিবারের জন্য মিটিং ঠিক করেছি।",
          slotValues: { CLAUSE: "I have arranged the meeting for Thursday" },
          topicArea: "work",
        },
        {
          en: "Further to our conversation, I wanted to confirm the budget allocation.",
          bn: "আমাদের কথোপকথনের পরিপ্রেক্ষিতে, আমি বাজেট বরাদ্দ নিশ্চিত করতে চেয়েছিলাম।",
          slotValues: { CLAUSE: "I wanted to confirm the budget allocation" },
          topicArea: "work",
        },
        {
          en: "Further to our conversation, the revised proposal is attached.",
          bn: "আমাদের কথোপকথনের পরিপ্রেক্ষিতে, সংশোধিত প্রস্তাবটি সংযুক্ত আছে।",
          slotValues: { CLAUSE: "the revised proposal is attached" },
          topicArea: "work",
        },
        {
          en: "Further to our conversation, I have spoken with the vendor.",
          bn: "আমাদের কথোপকথনের পরিপ্রেক্ষিতে, আমি বিক্রেতার সাথে কথা বলেছি।",
          slotValues: { CLAUSE: "I have spoken with the vendor" },
          topicArea: "work",
        },
        {
          en: "Further to our conversation, here is the list of candidates.",
          bn: "আমাদের কথোপকথনের পরিপ্রেক্ষিতে, এখানে প্রার্থীদের তালিকা দেওয়া হলো।",
          slotValues: { CLAUSE: "here is the list of candidates" },
          topicArea: "work",
        },
        {
          en: "Further to our conversation, I would like to proceed with plan B.",
          bn: "আমাদের কথোপকথনের পরিপ্রেক্ষিতে, আমি পরিকল্পনা বি নিয়ে এগিয়ে যেতে চাই।",
          slotValues: { CLAUSE: "I would like to proceed with plan B" },
          topicArea: "work",
        },
        {
          en: "Further to our conversation, I have updated the schedule accordingly.",
          bn: "আমাদের কথোপকথনের পরিপ্রেক্ষিতে, আমি সে অনুযায়ী সময়সূচি আপডেট করেছি।",
          slotValues: { CLAUSE: "I have updated the schedule accordingly" },
          topicArea: "work",
        },
        {
          en: "Further to our conversation, please review the terms and conditions.",
          bn: "আমাদের কথোপকথনের পরিপ্রেক্ষিতে, অনুগ্রহ করে শর্তাবলি পর্যালোচনা করুন।",
          slotValues: { CLAUSE: "please review the terms and conditions" },
          topicArea: "work",
        },
        {
          en: "Further to our conversation, I can confirm the dates are available.",
          bn: "আমাদের কথোপকথনের পরিপ্রেক্ষিতে, আমি নিশ্চিত করতে পারি তারিখগুলো পাওয়া যাচ্ছে।",
          slotValues: { CLAUSE: "I can confirm the dates are available" },
          topicArea: "work",
        },
        {
          en: "Further to our conversation, the team has agreed to the changes.",
          bn: "আমাদের কথোপকথনের পরিপ্রেক্ষিতে, দল পরিবর্তনগুলোতে সম্মত হয়েছে।",
          slotValues: { CLAUSE: "the team has agreed to the changes" },
          topicArea: "work",
        },
        {
          en: "Further to our conversation, I have forwarded your request to HR.",
          bn: "আমাদের কথোপকথনের পরিপ্রেক্ষিতে, আমি আপনার অনুরোধ এইচআর-এ পাঠিয়ে দিয়েছি।",
          slotValues: { CLAUSE: "I have forwarded your request to HR" },
          topicArea: "work",
        },
        {
          en: "Further to our conversation, the delivery will be on Monday.",
          bn: "আমাদের কথোপকথনের পরিপ্রেক্ষিতে, ডেলিভারি সোমবার হবে।",
          slotValues: { CLAUSE: "the delivery will be on Monday" },
          topicArea: "shopping",
        },
        {
          en: "Further to our conversation, I have enrolled in the course you suggested.",
          bn: "আমাদের কথোপকথনের পরিপ্রেক্ষিতে, আপনি যে কোর্সটি সুপারিশ করেছিলেন তাতে ভর্তি হয়েছি।",
          slotValues: { CLAUSE: "I have enrolled in the course you suggested" },
          topicArea: "education",
        },
      ],
      formality: "very_formal",
      difficulty: "intermediate",
      usageNote:
        "Used to reference a prior discussion, phone call, or meeting. Signals continuity and professionalism. More common in British English.",
      usageNote_bn:
        "পূর্বের আলোচনা, ফোন কল বা মিটিং উল্লেখ করতে ব্যবহৃত। ধারাবাহিকতা ও পেশাদারিত্বের সংকেত দেয়। ব্রিটিশ ইংরেজিতে বেশি প্রচলিত।",
      combinableWith: ["V3.1"],
      banglaStructureMap:
        "আমাদের কথোপকথনের (Our Conversation + Genitive) + পরিপ্রেক্ষিতে (Context + Postposition), + [বাক্য] (Clause)",
    },
    {
      id: "V2.5",
      formula: "Thank you for your email regarding [THING]",
      formula_bn: "[বিষয়] সম্পর্কে আপনার ইমেইলের জন্য ধন্যবাদ",
      patternName: "Thank You For Your Email Regarding",
      patternName_bn: "আপনার ইমেইলের জন্য ধন্যবাদ",
      slots: [
        {
          name: "THING",
          description: "The topic of the email being responded to",
          description_bn: "যে বিষয়ের ইমেইলের জবাব দেওয়া হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase", "topic"],
          examples: ["the job application", "the invoice", "the event planning"],
        },
      ],
      examples: [
        {
          en: "Thank you for your email regarding the job application.",
          bn: "চাকরির আবেদন সম্পর্কে আপনার ইমেইলের জন্য ধন্যবাদ।",
          slotValues: { THING: "the job application" },
          topicArea: "work",
        },
        {
          en: "Thank you for your email regarding the invoice discrepancy.",
          bn: "চালানের গরমিল সম্পর্কে আপনার ইমেইলের জন্য ধন্যবাদ।",
          slotValues: { THING: "the invoice discrepancy" },
          topicArea: "work",
        },
        {
          en: "Thank you for your email regarding the event planning.",
          bn: "অনুষ্ঠান পরিকল্পনা সম্পর্কে আপনার ইমেইলের জন্য ধন্যবাদ।",
          slotValues: { THING: "the event planning" },
          topicArea: "work",
        },
        {
          en: "Thank you for your email regarding the contract renewal.",
          bn: "চুক্তি নবায়ন সম্পর্কে আপনার ইমেইলের জন্য ধন্যবাদ।",
          slotValues: { THING: "the contract renewal" },
          topicArea: "work",
        },
        {
          en: "Thank you for your email regarding the delivery delay.",
          bn: "ডেলিভারি বিলম্ব সম্পর্কে আপনার ইমেইলের জন্য ধন্যবাদ।",
          slotValues: { THING: "the delivery delay" },
          topicArea: "shopping",
        },
        {
          en: "Thank you for your email regarding the new policy updates.",
          bn: "নতুন নীতি আপডেট সম্পর্কে আপনার ইমেইলের জন্য ধন্যবাদ।",
          slotValues: { THING: "the new policy updates" },
          topicArea: "work",
        },
        {
          en: "Thank you for your email regarding the patient's records.",
          bn: "রোগীর রেকর্ড সম্পর্কে আপনার ইমেইলের জন্য ধন্যবাদ।",
          slotValues: { THING: "the patient's records" },
          topicArea: "health",
        },
        {
          en: "Thank you for your email regarding the scholarship decision.",
          bn: "বৃত্তির সিদ্ধান্ত সম্পর্কে আপনার ইমেইলের জন্য ধন্যবাদ।",
          slotValues: { THING: "the scholarship decision" },
          topicArea: "education",
        },
        {
          en: "Thank you for your email regarding the product feedback.",
          bn: "পণ্যের প্রতিক্রিয়া সম্পর্কে আপনার ইমেইলের জন্য ধন্যবাদ।",
          slotValues: { THING: "the product feedback" },
          topicArea: "work",
        },
        {
          en: "Thank you for your email regarding the team restructuring.",
          bn: "দল পুনর্গঠন সম্পর্কে আপনার ইমেইলের জন্য ধন্যবাদ।",
          slotValues: { THING: "the team restructuring" },
          topicArea: "work",
        },
        {
          en: "Thank you for your email regarding the travel arrangements.",
          bn: "ভ্রমণ ব্যবস্থা সম্পর্কে আপনার ইমেইলের জন্য ধন্যবাদ।",
          slotValues: { THING: "the travel arrangements" },
          topicArea: "travel",
        },
        {
          en: "Thank you for your email regarding the maintenance request.",
          bn: "রক্ষণাবেক্ষণ অনুরোধ সম্পর্কে আপনার ইমেইলের জন্য ধন্যবাদ।",
          slotValues: { THING: "the maintenance request" },
          topicArea: "daily_life",
        },
        {
          en: "Thank you for your email regarding the exam schedule.",
          bn: "পরীক্ষার সময়সূচি সম্পর্কে আপনার ইমেইলের জন্য ধন্যবাদ।",
          slotValues: { THING: "the exam schedule" },
          topicArea: "education",
        },
        {
          en: "Thank you for your email regarding the warranty claim.",
          bn: "ওয়ারেন্টি দাবি সম্পর্কে আপনার ইমেইলের জন্য ধন্যবাদ।",
          slotValues: { THING: "the warranty claim" },
          topicArea: "shopping",
        },
        {
          en: "Thank you for your email regarding the annual review.",
          bn: "বার্ষিক পর্যালোচনা সম্পর্কে আপনার ইমেইলের জন্য ধন্যবাদ।",
          slotValues: { THING: "the annual review" },
          topicArea: "work",
        },
      ],
      formality: "formal",
      difficulty: "intermediate",
      usageNote:
        "A polite way to acknowledge someone's email when replying. Shows you have read and understood the context of their message.",
      usageNote_bn:
        "উত্তর দেওয়ার সময় কারো ইমেইল স্বীকার করার একটি ভদ্র উপায়। দেখায় যে আপনি তাদের বার্তার প্রসঙ্গ পড়েছেন এবং বুঝেছেন।",
      combinableWith: ["V2.3"],
      banglaStructureMap:
        "[বিষয়] সম্পর্কে (Topic + Postposition) + আপনার ইমেইলের জন্য (Your Email + Postposition) + ধন্যবাদ (Thanks)",
    },
  ],
};
