import { PatternCategory } from "@/types/pattern";

export const categoryV4: PatternCategory = {
  id: "V4",
  slug: "softening-negative",
  name: "Softening Negative News",
  name_bn: "নেতিবাচক খবর নরমভাবে বলা",
  description:
    "Polite ways to deliver bad news, refusals, and negative information",
  description_bn:
    "খারাপ খবর, প্রত্যাখ্যান ও নেতিবাচক তথ্য ভদ্রভাবে জানানোর উপায়",
  icon: "🤝",
  group: "V",
  groupName: "Politeness & Register",
  groupName_bn: "ভদ্রতা ও ভাষার স্তর",
  difficulty: "intermediate",
  patterns: [
    {
      id: "V4.1",
      formula: "I'm afraid [CLAUSE]",
      formula_bn: "দুঃখিত, [বাক্য]",
      patternName: "I'm Afraid (Softener)",
      patternName_bn: "দুঃখিত (নরম করা)",
      slots: [
        {
          name: "CLAUSE",
          description: "The negative news or information being softened",
          description_bn: "যে নেতিবাচক খবর বা তথ্য নরমভাবে বলা হচ্ছে",
          acceptedTypes: ["clause"],
          examples: [
            "we can't help you",
            "the position has been filled",
            "that won't be possible",
          ],
        },
      ],
      examples: [
        {
          en: "I'm afraid we can't process your request at this time.",
          bn: "দুঃখিত, আমরা এই মুহূর্তে আপনার অনুরোধ প্রক্রিয়া করতে পারছি না।",
          slotValues: { CLAUSE: "we can't process your request at this time" },
          topicArea: "work",
        },
        {
          en: "I'm afraid the position has already been filled.",
          bn: "দুঃখিত, পদটি ইতিমধ্যে পূরণ হয়ে গেছে।",
          slotValues: { CLAUSE: "the position has already been filled" },
          topicArea: "work",
        },
        {
          en: "I'm afraid that won't be possible.",
          bn: "দুঃখিত, সেটা সম্ভব হবে না।",
          slotValues: { CLAUSE: "that won't be possible" },
          topicArea: "daily_life",
        },
        {
          en: "I'm afraid we're fully booked for today.",
          bn: "দুঃখিত, আজকের জন্য আমাদের সব বুকিং হয়ে গেছে।",
          slotValues: { CLAUSE: "we're fully booked for today" },
          topicArea: "travel",
        },
        {
          en: "I'm afraid the item is out of stock.",
          bn: "দুঃখিত, পণ্যটি স্টকে নেই।",
          slotValues: { CLAUSE: "the item is out of stock" },
          topicArea: "shopping",
        },
        {
          en: "I'm afraid I have some bad news about the project.",
          bn: "দুঃখিত, প্রকল্প সম্পর্কে আমার কিছু খারাপ খবর আছে।",
          slotValues: { CLAUSE: "I have some bad news about the project" },
          topicArea: "work",
        },
        {
          en: "I'm afraid the doctor is not available today.",
          bn: "দুঃখিত, ডাক্তার আজ পাওয়া যাচ্ছে না।",
          slotValues: { CLAUSE: "the doctor is not available today" },
          topicArea: "health",
        },
        {
          en: "I'm afraid your application was not successful.",
          bn: "দুঃখিত, আপনার আবেদন সফল হয়নি।",
          slotValues: { CLAUSE: "your application was not successful" },
          topicArea: "work",
        },
        {
          en: "I'm afraid we've run into a problem with the delivery.",
          bn: "দুঃখিত, ডেলিভারিতে একটি সমস্যা হয়েছে।",
          slotValues: { CLAUSE: "we've run into a problem with the delivery" },
          topicArea: "shopping",
        },
        {
          en: "I'm afraid the flight has been cancelled.",
          bn: "দুঃখিত, ফ্লাইটটি বাতিল করা হয়েছে।",
          slotValues: { CLAUSE: "the flight has been cancelled" },
          topicArea: "travel",
        },
        {
          en: "I'm afraid I can't attend the meeting tomorrow.",
          bn: "দুঃখিত, আমি আগামীকালের মিটিংয়ে উপস্থিত থাকতে পারব না।",
          slotValues: { CLAUSE: "I can't attend the meeting tomorrow" },
          topicArea: "work",
        },
        {
          en: "I'm afraid the deadline cannot be extended.",
          bn: "দুঃখিত, সময়সীমা বাড়ানো সম্ভব নয়।",
          slotValues: { CLAUSE: "the deadline cannot be extended" },
          topicArea: "work",
        },
        {
          en: "I'm afraid the restaurant is closed on Mondays.",
          bn: "দুঃখিত, রেস্তোরাঁটি সোমবার বন্ধ থাকে।",
          slotValues: { CLAUSE: "the restaurant is closed on Mondays" },
          topicArea: "food",
        },
        {
          en: "I'm afraid you've missed the registration deadline.",
          bn: "দুঃখিত, আপনি নিবন্ধনের সময়সীমা মিস করেছেন।",
          slotValues: { CLAUSE: "you've missed the registration deadline" },
          topicArea: "education",
        },
        {
          en: "I'm afraid there's been a misunderstanding.",
          bn: "দুঃখিত, একটি ভুল বোঝাবুঝি হয়েছে।",
          slotValues: { CLAUSE: "there's been a misunderstanding" },
          topicArea: "daily_life",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "A gentle way to introduce bad news. Does not mean literal fear; it's a politeness softener. Very common in British English.",
      usageNote_bn:
        "খারাপ খবর জানানোর একটি মৃদু উপায়। আক্ষরিক ভয় বোঝায় না; এটি একটি ভদ্রতামূলক নরমকারী। ব্রিটিশ ইংরেজিতে খুবই সাধারণ।",
      combinableWith: ["V4.2"],
      banglaStructureMap:
        "দুঃখিত (Sorry/Afraid), + [বাক্য] (Clause)",
    },
    {
      id: "V4.2",
      formula: "Unfortunately, [CLAUSE]",
      formula_bn: "দুর্ভাগ্যবশত, [বাক্য]",
      patternName: "Unfortunately (Bad News Opener)",
      patternName_bn: "দুর্ভাগ্যবশত (খারাপ খবরের শুরু)",
      slots: [
        {
          name: "CLAUSE",
          description: "The unfortunate news or situation",
          description_bn: "দুর্ভাগ্যজনক খবর বা পরিস্থিতি",
          acceptedTypes: ["clause"],
          examples: [
            "we cannot offer you the job",
            "the event has been postponed",
            "we are unable to assist",
          ],
        },
      ],
      examples: [
        {
          en: "Unfortunately, we cannot offer you the position at this time.",
          bn: "দুর্ভাগ্যবশত, আমরা এই মুহূর্তে আপনাকে পদটি দিতে পারছি না।",
          slotValues: { CLAUSE: "we cannot offer you the position at this time" },
          topicArea: "work",
        },
        {
          en: "Unfortunately, the event has been postponed indefinitely.",
          bn: "দুর্ভাগ্যবশত, অনুষ্ঠানটি অনির্দিষ্টকালের জন্য স্থগিত করা হয়েছে।",
          slotValues: { CLAUSE: "the event has been postponed indefinitely" },
          topicArea: "daily_life",
        },
        {
          en: "Unfortunately, we are unable to process a refund.",
          bn: "দুর্ভাগ্যবশত, আমরা ফেরত প্রক্রিয়া করতে অক্ষম।",
          slotValues: { CLAUSE: "we are unable to process a refund" },
          topicArea: "shopping",
        },
        {
          en: "Unfortunately, the course is already full.",
          bn: "দুর্ভাগ্যবশত, কোর্সটি ইতিমধ্যে পূর্ণ।",
          slotValues: { CLAUSE: "the course is already full" },
          topicArea: "education",
        },
        {
          en: "Unfortunately, your request has been denied.",
          bn: "দুর্ভাগ্যবশত, আপনার অনুরোধ প্রত্যাখ্যান করা হয়েছে।",
          slotValues: { CLAUSE: "your request has been denied" },
          topicArea: "work",
        },
        {
          en: "Unfortunately, the weather forecast is not looking good.",
          bn: "দুর্ভাগ্যবশত, আবহাওয়ার পূর্বাভাস ভালো দেখাচ্ছে না।",
          slotValues: { CLAUSE: "the weather forecast is not looking good" },
          topicArea: "travel",
        },
        {
          en: "Unfortunately, we have to cancel the order.",
          bn: "দুর্ভাগ্যবশত, আমাদের অর্ডারটি বাতিল করতে হবে।",
          slotValues: { CLAUSE: "we have to cancel the order" },
          topicArea: "shopping",
        },
        {
          en: "Unfortunately, the test results were not positive.",
          bn: "দুর্ভাগ্যবশত, পরীক্ষার ফলাফল ইতিবাচক ছিল না।",
          slotValues: { CLAUSE: "the test results were not positive" },
          topicArea: "health",
        },
        {
          en: "Unfortunately, I will not be able to join you for dinner.",
          bn: "দুর্ভাগ্যবশত, আমি রাতের খাবারে আপনাদের সাথে যোগ দিতে পারব না।",
          slotValues: { CLAUSE: "I will not be able to join you for dinner" },
          topicArea: "food",
        },
        {
          en: "Unfortunately, the budget has been reduced.",
          bn: "দুর্ভাগ্যবশত, বাজেট কমানো হয়েছে।",
          slotValues: { CLAUSE: "the budget has been reduced" },
          topicArea: "work",
        },
        {
          en: "Unfortunately, your luggage has been misplaced.",
          bn: "দুর্ভাগ্যবশত, আপনার লাগেজ হারিয়ে গেছে।",
          slotValues: { CLAUSE: "your luggage has been misplaced" },
          topicArea: "travel",
        },
        {
          en: "Unfortunately, the professor is on leave this semester.",
          bn: "দুর্ভাগ্যবশত, অধ্যাপক এই সেমিস্টারে ছুটিতে আছেন।",
          slotValues: { CLAUSE: "the professor is on leave this semester" },
          topicArea: "education",
        },
        {
          en: "Unfortunately, the warranty has expired.",
          bn: "দুর্ভাগ্যবশত, ওয়ারেন্টির মেয়াদ শেষ হয়ে গেছে।",
          slotValues: { CLAUSE: "the warranty has expired" },
          topicArea: "shopping",
        },
        {
          en: "Unfortunately, we experienced a system failure.",
          bn: "দুর্ভাগ্যবশত, আমাদের একটি সিস্টেম ব্যর্থতা হয়েছে।",
          slotValues: { CLAUSE: "we experienced a system failure" },
          topicArea: "work",
        },
        {
          en: "Unfortunately, the train service has been disrupted.",
          bn: "দুর্ভাগ্যবশত, ট্রেন সেবা ব্যাহত হয়েছে।",
          slotValues: { CLAUSE: "the train service has been disrupted" },
          topicArea: "travel",
        },
      ],
      formality: "formal",
      difficulty: "intermediate",
      usageNote:
        "A direct but empathetic way to deliver bad news. Placing 'unfortunately' at the beginning prepares the listener for negative information.",
      usageNote_bn:
        "খারাপ খবর জানানোর একটি সরাসরি কিন্তু সহানুভূতিশীল উপায়। শুরুতে 'unfortunately' রাখলে শ্রোতা নেতিবাচক তথ্যের জন্য প্রস্তুত হয়।",
      combinableWith: ["V4.1"],
      banglaStructureMap:
        "দুর্ভাগ্যবশত (Unfortunately), + [বাক্য] (Clause)",
    },
    {
      id: "V4.3",
      formula: "I regret to inform you that [CLAUSE]",
      formula_bn: "দুঃখের সাথে জানাচ্ছি যে [বাক্য]",
      patternName: "Regret To Inform",
      patternName_bn: "দুঃখের সাথে জানাচ্ছি",
      slots: [
        {
          name: "CLAUSE",
          description: "The formal negative news being communicated",
          description_bn: "যে আনুষ্ঠানিক নেতিবাচক খবর জানানো হচ্ছে",
          acceptedTypes: ["clause"],
          examples: [
            "your application has been rejected",
            "the service will be discontinued",
            "the contract will not be renewed",
          ],
        },
      ],
      examples: [
        {
          en: "I regret to inform you that your application has been rejected.",
          bn: "দুঃখের সাথে জানাচ্ছি যে আপনার আবেদন প্রত্যাখ্যান করা হয়েছে।",
          slotValues: { CLAUSE: "your application has been rejected" },
          topicArea: "work",
        },
        {
          en: "I regret to inform you that the service will be discontinued.",
          bn: "দুঃখের সাথে জানাচ্ছি যে সেবাটি বন্ধ করা হবে।",
          slotValues: { CLAUSE: "the service will be discontinued" },
          topicArea: "work",
        },
        {
          en: "I regret to inform you that the contract will not be renewed.",
          bn: "দুঃখের সাথে জানাচ্ছি যে চুক্তি নবায়ন করা হবে না।",
          slotValues: { CLAUSE: "the contract will not be renewed" },
          topicArea: "work",
        },
        {
          en: "I regret to inform you that the event has been cancelled.",
          bn: "দুঃখের সাথে জানাচ্ছি যে অনুষ্ঠানটি বাতিল করা হয়েছে।",
          slotValues: { CLAUSE: "the event has been cancelled" },
          topicArea: "daily_life",
        },
        {
          en: "I regret to inform you that there will be layoffs next month.",
          bn: "দুঃখের সাথে জানাচ্ছি যে আগামী মাসে ছাঁটাই হবে।",
          slotValues: { CLAUSE: "there will be layoffs next month" },
          topicArea: "work",
        },
        {
          en: "I regret to inform you that the scholarship has been withdrawn.",
          bn: "দুঃখের সাথে জানাচ্ছি যে বৃত্তি প্রত্যাহার করা হয়েছে।",
          slotValues: { CLAUSE: "the scholarship has been withdrawn" },
          topicArea: "education",
        },
        {
          en: "I regret to inform you that we are closing the branch.",
          bn: "দুঃখের সাথে জানাচ্ছি যে আমরা শাখাটি বন্ধ করছি।",
          slotValues: { CLAUSE: "we are closing the branch" },
          topicArea: "work",
        },
        {
          en: "I regret to inform you that the product has been recalled.",
          bn: "দুঃখের সাথে জানাচ্ছি যে পণ্যটি প্রত্যাহার করা হয়েছে।",
          slotValues: { CLAUSE: "the product has been recalled" },
          topicArea: "shopping",
        },
        {
          en: "I regret to inform you that your insurance claim has been denied.",
          bn: "দুঃখের সাথে জানাচ্ছি যে আপনার বীমা দাবি প্রত্যাখ্যান করা হয়েছে।",
          slotValues: { CLAUSE: "your insurance claim has been denied" },
          topicArea: "health",
        },
        {
          en: "I regret to inform you that the project has been terminated.",
          bn: "দুঃখের সাথে জানাচ্ছি যে প্রকল্পটি বন্ধ করা হয়েছে।",
          slotValues: { CLAUSE: "the project has been terminated" },
          topicArea: "work",
        },
        {
          en: "I regret to inform you that the tour has been cancelled due to weather.",
          bn: "দুঃখের সাথে জানাচ্ছি যে আবহাওয়ার কারণে ট্যুর বাতিল করা হয়েছে।",
          slotValues: { CLAUSE: "the tour has been cancelled due to weather" },
          topicArea: "travel",
        },
        {
          en: "I regret to inform you that we cannot accommodate your request.",
          bn: "দুঃখের সাথে জানাচ্ছি যে আমরা আপনার অনুরোধ পূরণ করতে পারছি না।",
          slotValues: { CLAUSE: "we cannot accommodate your request" },
          topicArea: "work",
        },
        {
          en: "I regret to inform you that the class has been permanently cancelled.",
          bn: "দুঃখের সাথে জানাচ্ছি যে ক্লাসটি স্থায়ীভাবে বাতিল করা হয়েছে।",
          slotValues: { CLAUSE: "the class has been permanently cancelled" },
          topicArea: "education",
        },
        {
          en: "I regret to inform you that your visa application was unsuccessful.",
          bn: "দুঃখের সাথে জানাচ্ছি যে আপনার ভিসা আবেদন সফল হয়নি।",
          slotValues: { CLAUSE: "your visa application was unsuccessful" },
          topicArea: "travel",
        },
        {
          en: "I regret to inform you that the funding has been cut.",
          bn: "দুঃখের সাথে জানাচ্ছি যে তহবিল কমানো হয়েছে।",
          slotValues: { CLAUSE: "the funding has been cut" },
          topicArea: "work",
        },
      ],
      formality: "very_formal",
      difficulty: "intermediate",
      usageNote:
        "The most formal way to deliver bad news. Common in official letters, HR communications, and legal notices.",
      usageNote_bn:
        "খারাপ খবর জানানোর সবচেয়ে আনুষ্ঠানিক উপায়। সরকারি চিঠি, এইচআর যোগাযোগ এবং আইনি নোটিশে সাধারণ।",
      combinableWith: ["V4.1", "V4.2"],
      banglaStructureMap:
        "দুঃখের সাথে (With Regret) + জানাচ্ছি (Informing) + যে (That) + [বাক্য] (Clause)",
    },
    {
      id: "V4.4",
      formula: "I'm sorry to say that [CLAUSE]",
      formula_bn: "দুঃখিতভাবে বলছি যে [বাক্য]",
      patternName: "Sorry To Say That",
      patternName_bn: "দুঃখিতভাবে বলছি",
      slots: [
        {
          name: "CLAUSE",
          description: "The negative information being conveyed with sympathy",
          description_bn: "যে নেতিবাচক তথ্য সহানুভূতির সাথে জানানো হচ্ছে",
          acceptedTypes: ["clause"],
          examples: [
            "you didn't pass the test",
            "we have to let you go",
            "the plan didn't work out",
          ],
        },
      ],
      examples: [
        {
          en: "I'm sorry to say that you didn't pass the final exam.",
          bn: "দুঃখিতভাবে বলছি যে তুমি চূড়ান্ত পরীক্ষায় পাস করনি।",
          slotValues: { CLAUSE: "you didn't pass the final exam" },
          topicArea: "education",
        },
        {
          en: "I'm sorry to say that we have to let you go.",
          bn: "দুঃখিতভাবে বলছি যে আমাদের আপনাকে ছেড়ে দিতে হবে।",
          slotValues: { CLAUSE: "we have to let you go" },
          topicArea: "work",
        },
        {
          en: "I'm sorry to say that the plan didn't work out.",
          bn: "দুঃখিতভাবে বলছি যে পরিকল্পনাটি কার্যকর হয়নি।",
          slotValues: { CLAUSE: "the plan didn't work out" },
          topicArea: "work",
        },
        {
          en: "I'm sorry to say that the shop is closing down.",
          bn: "দুঃখিতভাবে বলছি যে দোকানটি বন্ধ হয়ে যাচ্ছে।",
          slotValues: { CLAUSE: "the shop is closing down" },
          topicArea: "shopping",
        },
        {
          en: "I'm sorry to say that your performance has declined.",
          bn: "দুঃখিতভাবে বলছি যে আপনার কর্মক্ষমতা হ্রাস পেয়েছে।",
          slotValues: { CLAUSE: "your performance has declined" },
          topicArea: "work",
        },
        {
          en: "I'm sorry to say that the treatment didn't have the expected results.",
          bn: "দুঃখিতভাবে বলছি যে চিকিৎসায় প্রত্যাশিত ফলাফল হয়নি।",
          slotValues: { CLAUSE: "the treatment didn't have the expected results" },
          topicArea: "health",
        },
        {
          en: "I'm sorry to say that we can't approve the loan.",
          bn: "দুঃখিতভাবে বলছি যে আমরা ঋণ অনুমোদন করতে পারছি না।",
          slotValues: { CLAUSE: "we can't approve the loan" },
          topicArea: "daily_life",
        },
        {
          en: "I'm sorry to say that the trip has been cancelled.",
          bn: "দুঃখিতভাবে বলছি যে ভ্রমণটি বাতিল করা হয়েছে।",
          slotValues: { CLAUSE: "the trip has been cancelled" },
          topicArea: "travel",
        },
        {
          en: "I'm sorry to say that the food didn't meet our standards.",
          bn: "দুঃখিতভাবে বলছি যে খাবারটি আমাদের মানদণ্ড পূরণ করেনি।",
          slotValues: { CLAUSE: "the food didn't meet our standards" },
          topicArea: "food",
        },
        {
          en: "I'm sorry to say that we won't be able to attend your wedding.",
          bn: "দুঃখিতভাবে বলছি যে আমরা আপনার বিয়েতে উপস্থিত থাকতে পারব না।",
          slotValues: { CLAUSE: "we won't be able to attend your wedding" },
          topicArea: "relationships",
        },
        {
          en: "I'm sorry to say that the project is behind schedule.",
          bn: "দুঃখিতভাবে বলছি যে প্রকল্পটি সময়সূচির পিছনে আছে।",
          slotValues: { CLAUSE: "the project is behind schedule" },
          topicArea: "work",
        },
        {
          en: "I'm sorry to say that your complaint was not upheld.",
          bn: "দুঃখিতভাবে বলছি যে আপনার অভিযোগ গ্রহণ করা হয়নি।",
          slotValues: { CLAUSE: "your complaint was not upheld" },
          topicArea: "daily_life",
        },
        {
          en: "I'm sorry to say that the internship program has been suspended.",
          bn: "দুঃখিতভাবে বলছি যে ইন্টার্নশিপ প্রোগ্রাম স্থগিত করা হয়েছে।",
          slotValues: { CLAUSE: "the internship program has been suspended" },
          topicArea: "education",
        },
        {
          en: "I'm sorry to say that we need to downsize the team.",
          bn: "দুঃখিতভাবে বলছি যে আমাদের দলের আকার কমাতে হবে।",
          slotValues: { CLAUSE: "we need to downsize the team" },
          topicArea: "work",
        },
        {
          en: "I'm sorry to say that we've lost the client.",
          bn: "দুঃখিতভাবে বলছি যে আমরা ক্লায়েন্ট হারিয়েছি।",
          slotValues: { CLAUSE: "we've lost the client" },
          topicArea: "work",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "A sympathetic way to deliver bad news. Slightly less formal than 'I regret to inform you' but still professional.",
      usageNote_bn:
        "খারাপ খবর জানানোর একটি সহানুভূতিশীল উপায়। 'I regret to inform you'-এর চেয়ে একটু কম আনুষ্ঠানিক কিন্তু তবুও পেশাদার।",
      combinableWith: ["V4.1"],
      banglaStructureMap:
        "দুঃখিতভাবে (Sadly) + বলছি (Saying) + যে (That) + [বাক্য] (Clause)",
    },
    {
      id: "V4.5",
      formula: "It's with regret that [CLAUSE]",
      formula_bn: "দুঃখের সাথে [বাক্য]",
      patternName: "With Regret That",
      patternName_bn: "দুঃখের সাথে",
      slots: [
        {
          name: "CLAUSE",
          description: "The regrettable news or decision",
          description_bn: "দুঃখজনক খবর বা সিদ্ধান্ত",
          acceptedTypes: ["clause"],
          examples: [
            "I must resign",
            "we announce the closure",
            "I inform you of the cancellation",
          ],
        },
      ],
      examples: [
        {
          en: "It's with regret that I must submit my resignation.",
          bn: "দুঃখের সাথে আমাকে আমার পদত্যাগপত্র জমা দিতে হচ্ছে।",
          slotValues: { CLAUSE: "I must submit my resignation" },
          topicArea: "work",
        },
        {
          en: "It's with regret that we announce the closure of the factory.",
          bn: "দুঃখের সাথে আমরা কারখানা বন্ধের ঘোষণা দিচ্ছি।",
          slotValues: { CLAUSE: "we announce the closure of the factory" },
          topicArea: "work",
        },
        {
          en: "It's with regret that I inform you of the cancellation.",
          bn: "দুঃখের সাথে আমি আপনাকে বাতিলের বিষয়ে জানাচ্ছি।",
          slotValues: { CLAUSE: "I inform you of the cancellation" },
          topicArea: "daily_life",
        },
        {
          en: "It's with regret that we must decline your offer.",
          bn: "দুঃখের সাথে আমাদের আপনার প্রস্তাব প্রত্যাখ্যান করতে হচ্ছে।",
          slotValues: { CLAUSE: "we must decline your offer" },
          topicArea: "work",
        },
        {
          en: "It's with regret that we confirm the redundancies.",
          bn: "দুঃখের সাথে আমরা ছাঁটাই নিশ্চিত করছি।",
          slotValues: { CLAUSE: "we confirm the redundancies" },
          topicArea: "work",
        },
        {
          en: "It's with regret that I must report the loss.",
          bn: "দুঃখের সাথে আমাকে ক্ষতির রিপোর্ট করতে হচ্ছে।",
          slotValues: { CLAUSE: "I must report the loss" },
          topicArea: "work",
        },
        {
          en: "It's with regret that we withdraw from the competition.",
          bn: "দুঃখের সাথে আমরা প্রতিযোগিতা থেকে সরে যাচ্ছি।",
          slotValues: { CLAUSE: "we withdraw from the competition" },
          topicArea: "daily_life",
        },
        {
          en: "It's with regret that I announce my departure from the company.",
          bn: "দুঃখের সাথে আমি কোম্পানি থেকে আমার বিদায়ের ঘোষণা দিচ্ছি।",
          slotValues: { CLAUSE: "I announce my departure from the company" },
          topicArea: "work",
        },
        {
          en: "It's with regret that we inform you the program has ended.",
          bn: "দুঃখের সাথে জানাচ্ছি প্রোগ্রামটি শেষ হয়ে গেছে।",
          slotValues: { CLAUSE: "we inform you the program has ended" },
          topicArea: "education",
        },
        {
          en: "It's with regret that the hospital must reduce visiting hours.",
          bn: "দুঃখের সাথে হাসপাতালকে দেখা করার সময় কমাতে হচ্ছে।",
          slotValues: { CLAUSE: "the hospital must reduce visiting hours" },
          topicArea: "health",
        },
        {
          en: "It's with regret that we have to postpone the launch.",
          bn: "দুঃখের সাথে আমাদের লঞ্চ পিছিয়ে দিতে হচ্ছে।",
          slotValues: { CLAUSE: "we have to postpone the launch" },
          topicArea: "work",
        },
        {
          en: "It's with regret that the airline cancels the route.",
          bn: "দুঃখের সাথে এয়ারলাইন রুটটি বাতিল করছে।",
          slotValues: { CLAUSE: "the airline cancels the route" },
          topicArea: "travel",
        },
        {
          en: "It's with regret that I share this disappointing update.",
          bn: "দুঃখের সাথে আমি এই হতাশাজনক আপডেট শেয়ার করছি।",
          slotValues: { CLAUSE: "I share this disappointing update" },
          topicArea: "work",
        },
        {
          en: "It's with regret that the restaurant will no longer serve breakfast.",
          bn: "দুঃখের সাথে রেস্তোরাঁ আর সকালের নাস্তা পরিবেশন করবে না।",
          slotValues: { CLAUSE: "the restaurant will no longer serve breakfast" },
          topicArea: "food",
        },
        {
          en: "It's with regret that we must end our partnership.",
          bn: "দুঃখের সাথে আমাদের অংশীদারি শেষ করতে হচ্ছে।",
          slotValues: { CLAUSE: "we must end our partnership" },
          topicArea: "work",
        },
      ],
      formality: "very_formal",
      difficulty: "intermediate",
      usageNote:
        "Extremely formal. Often used in official announcements, press releases, and corporate communications. Conveys genuine regret.",
      usageNote_bn:
        "অত্যন্ত আনুষ্ঠানিক। প্রায়ই সরকারি ঘোষণা, প্রেস রিলিজ এবং কর্পোরেট যোগাযোগে ব্যবহৃত। প্রকৃত দুঃখ প্রকাশ করে।",
      combinableWith: ["V4.3"],
      banglaStructureMap:
        "দুঃখের সাথে (With Regret) + [বাক্য] (Clause)",
    },
  ],
};
