import { PatternCategory } from "@/types/pattern";

export const categoryV8: PatternCategory = {
  id: "V8",
  slug: "formal-gratitude",
  name: "Formal Gratitude",
  name_bn: "আনুষ্ঠানিক কৃতজ্ঞতা",
  description:
    "Formal and heartfelt ways to express deep gratitude and appreciation",
  description_bn:
    "গভীর কৃতজ্ঞতা ও প্রশংসা প্রকাশের আনুষ্ঠানিক ও আন্তরিক উপায়",
  icon: "🙏",
  group: "V",
  groupName: "Politeness & Register",
  groupName_bn: "ভদ্রতা ও ভাষার স্তর",
  difficulty: "intermediate",
  patterns: [
    {
      id: "V8.1",
      formula: "I would like to express my gratitude for [THING]",
      formula_bn: "[বিষয়]-এর জন্য আমার কৃতজ্ঞতা প্রকাশ করতে চাই",
      patternName: "Express My Gratitude For",
      patternName_bn: "কৃতজ্ঞতা প্রকাশ করতে চাই",
      slots: [
        {
          name: "THING",
          description: "What you are grateful for",
          description_bn: "যার জন্য আপনি কৃতজ্ঞ",
          acceptedTypes: ["noun", "noun_phrase", "gerund"],
          examples: ["your help", "the opportunity", "your generous donation"],
        },
      ],
      examples: [
        {
          en: "I would like to express my gratitude for your help during the project.",
          bn: "প্রকল্পের সময় আপনার সাহায্যের জন্য আমার কৃতজ্ঞতা প্রকাশ করতে চাই।",
          slotValues: { THING: "your help during the project" },
          topicArea: "work",
        },
        {
          en: "I would like to express my gratitude for the opportunity to work here.",
          bn: "এখানে কাজ করার সুযোগের জন্য আমার কৃতজ্ঞতা প্রকাশ করতে চাই।",
          slotValues: { THING: "the opportunity to work here" },
          topicArea: "work",
        },
        {
          en: "I would like to express my gratitude for your generous donation.",
          bn: "আপনার উদার অনুদানের জন্য আমার কৃতজ্ঞতা প্রকাশ করতে চাই।",
          slotValues: { THING: "your generous donation" },
          topicArea: "daily_life",
        },
        {
          en: "I would like to express my gratitude for your excellent teaching.",
          bn: "আপনার চমৎকার শিক্ষাদানের জন্য আমার কৃতজ্ঞতা প্রকাশ করতে চাই।",
          slotValues: { THING: "your excellent teaching" },
          topicArea: "education",
        },
        {
          en: "I would like to express my gratitude for your patience and understanding.",
          bn: "আপনার ধৈর্য ও বোঝাপড়ার জন্য আমার কৃতজ্ঞতা প্রকাশ করতে চাই।",
          slotValues: { THING: "your patience and understanding" },
          topicArea: "relationships",
        },
        {
          en: "I would like to express my gratitude for your support during a difficult time.",
          bn: "কঠিন সময়ে আপনার সমর্থনের জন্য আমার কৃতজ্ঞতা প্রকাশ করতে চাই।",
          slotValues: { THING: "your support during a difficult time" },
          topicArea: "relationships",
        },
        {
          en: "I would like to express my gratitude for the warm hospitality.",
          bn: "উষ্ণ আতিথেয়তার জন্য আমার কৃতজ্ঞতা প্রকাশ করতে চাই।",
          slotValues: { THING: "the warm hospitality" },
          topicArea: "travel",
        },
        {
          en: "I would like to express my gratitude for your prompt attention to this matter.",
          bn: "এই বিষয়ে আপনার তাৎক্ষণিক মনোযোগের জন্য আমার কৃতজ্ঞতা প্রকাশ করতে চাই।",
          slotValues: { THING: "your prompt attention to this matter" },
          topicArea: "work",
        },
        {
          en: "I would like to express my gratitude for the scholarship.",
          bn: "বৃত্তির জন্য আমার কৃতজ্ঞতা প্রকাশ করতে চাই।",
          slotValues: { THING: "the scholarship" },
          topicArea: "education",
        },
        {
          en: "I would like to express my gratitude for the wonderful meal.",
          bn: "চমৎকার খাবারের জন্য আমার কৃতজ্ঞতা প্রকাশ করতে চাই।",
          slotValues: { THING: "the wonderful meal" },
          topicArea: "food",
        },
        {
          en: "I would like to express my gratitude for the exceptional care I received.",
          bn: "আমি যে ব্যতিক্রমী যত্ন পেয়েছি তার জন্য আমার কৃতজ্ঞতা প্রকাশ করতে চাই।",
          slotValues: { THING: "the exceptional care I received" },
          topicArea: "health",
        },
        {
          en: "I would like to express my gratitude for your team's hard work.",
          bn: "আপনার দলের কঠোর পরিশ্রমের জন্য আমার কৃতজ্ঞতা প্রকাশ করতে চাই।",
          slotValues: { THING: "your team's hard work" },
          topicArea: "work",
        },
        {
          en: "I would like to express my gratitude for the beautiful gift.",
          bn: "সুন্দর উপহারের জন্য আমার কৃতজ্ঞতা প্রকাশ করতে চাই।",
          slotValues: { THING: "the beautiful gift" },
          topicArea: "shopping",
        },
        {
          en: "I would like to express my gratitude for your mentorship over the years.",
          bn: "বছরের পর বছর আপনার পরামর্শদানের জন্য আমার কৃতজ্ঞতা প্রকাশ করতে চাই।",
          slotValues: { THING: "your mentorship over the years" },
          topicArea: "education",
        },
        {
          en: "I would like to express my gratitude for your cooperation.",
          bn: "আপনার সহযোগিতার জন্য আমার কৃতজ্ঞতা প্রকাশ করতে চাই।",
          slotValues: { THING: "your cooperation" },
          topicArea: "work",
        },
      ],
      formality: "very_formal",
      difficulty: "intermediate",
      usageNote:
        "Very formal. Used in speeches, official letters, and formal thank-you messages. The phrase 'express my gratitude' elevates simple thanks to a formal level.",
      usageNote_bn:
        "খুবই আনুষ্ঠানিক। বক্তৃতা, সরকারি চিঠি এবং আনুষ্ঠানিক ধন্যবাদ বার্তায় ব্যবহৃত। 'express my gratitude' বাক্যাংশটি সাধারণ ধন্যবাদকে আনুষ্ঠানিক পর্যায়ে উন্নীত করে।",
      combinableWith: ["V8.2"],
      banglaStructureMap:
        "[বিষয়]-এর জন্য (Thing + Postposition) + আমার কৃতজ্ঞতা (My Gratitude) + প্রকাশ করতে চাই (Express + Want)",
    },
    {
      id: "V8.2",
      formula: "I am deeply grateful for [THING]",
      formula_bn: "[বিষয়]-এর জন্য আমি গভীরভাবে কৃতজ্ঞ",
      patternName: "Deeply Grateful For",
      patternName_bn: "গভীরভাবে কৃতজ্ঞ",
      slots: [
        {
          name: "THING",
          description: "What you feel deep gratitude for",
          description_bn: "যার জন্য আপনি গভীর কৃতজ্ঞতা অনুভব করেন",
          acceptedTypes: ["noun", "noun_phrase", "gerund"],
          examples: ["your kindness", "the second chance", "everything you've done"],
        },
      ],
      examples: [
        {
          en: "I am deeply grateful for your kindness during my illness.",
          bn: "আমার অসুস্থতার সময় আপনার দয়ার জন্য আমি গভীরভাবে কৃতজ্ঞ।",
          slotValues: { THING: "your kindness during my illness" },
          topicArea: "health",
        },
        {
          en: "I am deeply grateful for the second chance you gave me.",
          bn: "আপনি আমাকে যে দ্বিতীয় সুযোগ দিয়েছেন তার জন্য আমি গভীরভাবে কৃতজ্ঞ।",
          slotValues: { THING: "the second chance you gave me" },
          topicArea: "work",
        },
        {
          en: "I am deeply grateful for everything you've done for our family.",
          bn: "আমাদের পরিবারের জন্য আপনি যা কিছু করেছেন তার জন্য আমি গভীরভাবে কৃতজ্ঞ।",
          slotValues: { THING: "everything you've done for our family" },
          topicArea: "relationships",
        },
        {
          en: "I am deeply grateful for the training opportunities provided.",
          bn: "প্রদত্ত প্রশিক্ষণের সুযোগের জন্য আমি গভীরভাবে কৃতজ্ঞ।",
          slotValues: { THING: "the training opportunities provided" },
          topicArea: "work",
        },
        {
          en: "I am deeply grateful for your guidance throughout my career.",
          bn: "আমার পুরো কর্মজীবনে আপনার দিকনির্দেশনার জন্য আমি গভীরভাবে কৃতজ্ঞ।",
          slotValues: { THING: "your guidance throughout my career" },
          topicArea: "work",
        },
        {
          en: "I am deeply grateful for the love and support of my friends.",
          bn: "আমার বন্ধুদের ভালোবাসা ও সমর্থনের জন্য আমি গভীরভাবে কৃতজ্ঞ।",
          slotValues: { THING: "the love and support of my friends" },
          topicArea: "relationships",
        },
        {
          en: "I am deeply grateful for the scholarship that changed my life.",
          bn: "যে বৃত্তি আমার জীবন বদলে দিয়েছে তার জন্য আমি গভীরভাবে কৃতজ্ঞ।",
          slotValues: { THING: "the scholarship that changed my life" },
          topicArea: "education",
        },
        {
          en: "I am deeply grateful for the delicious meal you prepared.",
          bn: "আপনি যে সুস্বাদু খাবার তৈরি করেছেন তার জন্য আমি গভীরভাবে কৃতজ্ঞ।",
          slotValues: { THING: "the delicious meal you prepared" },
          topicArea: "food",
        },
        {
          en: "I am deeply grateful for the safe journey.",
          bn: "নিরাপদ যাত্রার জন্য আমি গভীরভাবে কৃতজ্ঞ।",
          slotValues: { THING: "the safe journey" },
          topicArea: "travel",
        },
        {
          en: "I am deeply grateful for your honest feedback.",
          bn: "আপনার সৎ মতামতের জন্য আমি গভীরভাবে কৃতজ্ঞ।",
          slotValues: { THING: "your honest feedback" },
          topicArea: "work",
        },
        {
          en: "I am deeply grateful for the medical team's dedication.",
          bn: "চিকিৎসা দলের নিবেদনের জন্য আমি গভীরভাবে কৃতজ্ঞ।",
          slotValues: { THING: "the medical team's dedication" },
          topicArea: "health",
        },
        {
          en: "I am deeply grateful for the time you spent teaching me.",
          bn: "আমাকে শেখানোর জন্য আপনি যে সময় দিয়েছেন তার জন্য আমি গভীরভাবে কৃতজ্ঞ।",
          slotValues: { THING: "the time you spent teaching me" },
          topicArea: "education",
        },
        {
          en: "I am deeply grateful for your thoughtful gift.",
          bn: "আপনার চিন্তাশীল উপহারের জন্য আমি গভীরভাবে কৃতজ্ঞ।",
          slotValues: { THING: "your thoughtful gift" },
          topicArea: "shopping",
        },
        {
          en: "I am deeply grateful for the community's support.",
          bn: "সম্প্রদায়ের সমর্থনের জন্য আমি গভীরভাবে কৃতজ্ঞ।",
          slotValues: { THING: "the community's support" },
          topicArea: "daily_life",
        },
        {
          en: "I am deeply grateful for your willingness to listen.",
          bn: "আপনার শোনার ইচ্ছার জন্য আমি গভীরভাবে কৃতজ্ঞ।",
          slotValues: { THING: "your willingness to listen" },
          topicArea: "relationships",
        },
      ],
      formality: "formal",
      difficulty: "intermediate",
      usageNote:
        "Conveys strong, sincere gratitude. 'Deeply' intensifies the feeling. Suitable for both written and spoken formal contexts.",
      usageNote_bn:
        "শক্তিশালী, আন্তরিক কৃতজ্ঞতা প্রকাশ করে। 'Deeply' অনুভূতিকে তীব্র করে। লিখিত ও মৌখিক উভয় আনুষ্ঠানিক প্রেক্ষাপটে উপযুক্ত।",
      combinableWith: ["V8.1", "V8.3"],
      banglaStructureMap:
        "[বিষয়]-এর জন্য (Thing + Postposition) + আমি গভীরভাবে কৃতজ্ঞ (I + Deeply + Grateful)",
    },
    {
      id: "V8.3",
      formula: "I truly appreciate [THING]",
      formula_bn: "আমি সত্যিই [বিষয়]-এর প্রশংসা করি",
      patternName: "Truly Appreciate",
      patternName_bn: "সত্যিই প্রশংসা করি",
      slots: [
        {
          name: "THING",
          description: "What you genuinely appreciate",
          description_bn: "যার প্রকৃতই প্রশংসা করেন",
          acceptedTypes: ["noun", "noun_phrase", "gerund"],
          examples: ["your effort", "the kind words", "you taking the time"],
        },
      ],
      examples: [
        {
          en: "I truly appreciate your effort in completing this task.",
          bn: "এই কাজ সম্পন্ন করতে আপনার প্রচেষ্টার সত্যিই প্রশংসা করি।",
          slotValues: { THING: "your effort in completing this task" },
          topicArea: "work",
        },
        {
          en: "I truly appreciate the kind words you shared.",
          bn: "আপনি যে সদয় কথাগুলো বলেছেন তার সত্যিই প্রশংসা করি।",
          slotValues: { THING: "the kind words you shared" },
          topicArea: "relationships",
        },
        {
          en: "I truly appreciate you taking the time to help me.",
          bn: "আমাকে সাহায্য করতে আপনি যে সময় দিয়েছেন তার সত্যিই প্রশংসা করি।",
          slotValues: { THING: "you taking the time to help me" },
          topicArea: "daily_life",
        },
        {
          en: "I truly appreciate your dedication to the team.",
          bn: "দলের প্রতি আপনার নিবেদনের সত্যিই প্রশংসা করি।",
          slotValues: { THING: "your dedication to the team" },
          topicArea: "work",
        },
        {
          en: "I truly appreciate the feedback you provided.",
          bn: "আপনি যে মতামত দিয়েছেন তার সত্যিই প্রশংসা করি।",
          slotValues: { THING: "the feedback you provided" },
          topicArea: "work",
        },
        {
          en: "I truly appreciate your honesty on this matter.",
          bn: "এই বিষয়ে আপনার সততার সত্যিই প্রশংসা করি।",
          slotValues: { THING: "your honesty on this matter" },
          topicArea: "relationships",
        },
        {
          en: "I truly appreciate the wonderful hospitality during our visit.",
          bn: "আমাদের সফরের সময় চমৎকার আতিথেয়তার সত্যিই প্রশংসা করি।",
          slotValues: { THING: "the wonderful hospitality during our visit" },
          topicArea: "travel",
        },
        {
          en: "I truly appreciate the homemade cookies you brought.",
          bn: "আপনি যে ঘরে তৈরি কুকিজ এনেছেন তার সত্যিই প্রশংসা করি।",
          slotValues: { THING: "the homemade cookies you brought" },
          topicArea: "food",
        },
        {
          en: "I truly appreciate you explaining the lesson again.",
          bn: "আপনি আবার পাঠটি ব্যাখ্যা করেছেন তার সত্যিই প্রশংসা করি।",
          slotValues: { THING: "you explaining the lesson again" },
          topicArea: "education",
        },
        {
          en: "I truly appreciate the care I received at the hospital.",
          bn: "হাসপাতালে আমি যে যত্ন পেয়েছি তার সত্যিই প্রশংসা করি।",
          slotValues: { THING: "the care I received at the hospital" },
          topicArea: "health",
        },
        {
          en: "I truly appreciate your flexibility with the schedule.",
          bn: "সময়সূচিতে আপনার নমনীয়তার সত্যিই প্রশংসা করি।",
          slotValues: { THING: "your flexibility with the schedule" },
          topicArea: "work",
        },
        {
          en: "I truly appreciate the discount you offered.",
          bn: "আপনি যে ছাড় দিয়েছেন তার সত্যিই প্রশংসা করি।",
          slotValues: { THING: "the discount you offered" },
          topicArea: "shopping",
        },
        {
          en: "I truly appreciate your loyalty over the years.",
          bn: "বছরের পর বছর আপনার আনুগত্যের সত্যিই প্রশংসা করি।",
          slotValues: { THING: "your loyalty over the years" },
          topicArea: "relationships",
        },
        {
          en: "I truly appreciate you keeping me informed.",
          bn: "আমাকে জানিয়ে রেখেছেন তার সত্যিই প্রশংসা করি।",
          slotValues: { THING: "you keeping me informed" },
          topicArea: "work",
        },
        {
          en: "I truly appreciate the warm welcome from everyone.",
          bn: "সবার কাছ থেকে উষ্ণ অভ্যর্থনার সত্যিই প্রশংসা করি।",
          slotValues: { THING: "the warm welcome from everyone" },
          topicArea: "daily_life",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "Slightly less formal than 'express my gratitude' but still respectful. 'Truly' adds sincerity. Works well in both speech and writing.",
      usageNote_bn:
        "'express my gratitude'-এর চেয়ে সামান্য কম আনুষ্ঠানিক কিন্তু তবুও সম্মানজনক। 'Truly' আন্তরিকতা যোগ করে। কথা ও লেখা উভয়েই ভালো কাজ করে।",
      combinableWith: ["V8.2"],
      banglaStructureMap:
        "আমি সত্যিই (I Truly) + [বিষয়]-এর (Thing + Genitive) + প্রশংসা করি (Appreciate)",
    },
    {
      id: "V8.4",
      formula: "I can't thank you enough for [THING]",
      formula_bn: "[বিষয়]-এর জন্য আপনাকে যথেষ্ট ধন্যবাদ দিতে পারব না",
      patternName: "Can't Thank You Enough",
      patternName_bn: "যথেষ্ট ধন্যবাদ দিতে পারব না",
      slots: [
        {
          name: "THING",
          description: "What you are overwhelmingly thankful for",
          description_bn: "যার জন্য আপনি অত্যন্ত কৃতজ্ঞ",
          acceptedTypes: ["noun", "noun_phrase", "gerund"],
          examples: ["your help", "what you've done", "saving my life"],
        },
      ],
      examples: [
        {
          en: "I can't thank you enough for your help with the move.",
          bn: "বাসা বদলে আপনার সাহায্যের জন্য আপনাকে যথেষ্ট ধন্যবাদ দিতে পারব না।",
          slotValues: { THING: "your help with the move" },
          topicArea: "daily_life",
        },
        {
          en: "I can't thank you enough for what you've done for our family.",
          bn: "আমাদের পরিবারের জন্য আপনি যা করেছেন তার জন্য আপনাকে যথেষ্ট ধন্যবাদ দিতে পারব না।",
          slotValues: { THING: "what you've done for our family" },
          topicArea: "relationships",
        },
        {
          en: "I can't thank you enough for saving my life.",
          bn: "আমার জীবন বাঁচানোর জন্য আপনাকে যথেষ্ট ধন্যবাদ দিতে পারব না।",
          slotValues: { THING: "saving my life" },
          topicArea: "health",
        },
        {
          en: "I can't thank you enough for recommending me for the job.",
          bn: "চাকরির জন্য আমাকে সুপারিশ করার জন্য আপনাকে যথেষ্ট ধন্যবাদ দিতে পারব না।",
          slotValues: { THING: "recommending me for the job" },
          topicArea: "work",
        },
        {
          en: "I can't thank you enough for being there when I needed you.",
          bn: "যখন আমার প্রয়োজন ছিল তখন পাশে থাকার জন্য আপনাকে যথেষ্ট ধন্যবাদ দিতে পারব না।",
          slotValues: { THING: "being there when I needed you" },
          topicArea: "relationships",
        },
        {
          en: "I can't thank you enough for the surprise birthday party.",
          bn: "সারপ্রাইজ জন্মদিনের পার্টির জন্য আপনাকে যথেষ্ট ধন্যবাদ দিতে পারব না।",
          slotValues: { THING: "the surprise birthday party" },
          topicArea: "relationships",
        },
        {
          en: "I can't thank you enough for lending me your car.",
          bn: "আপনার গাড়ি ধার দেওয়ার জন্য আপনাকে যথেষ্ট ধন্যবাদ দিতে পারব না।",
          slotValues: { THING: "lending me your car" },
          topicArea: "daily_life",
        },
        {
          en: "I can't thank you enough for cooking such a delicious dinner.",
          bn: "এত সুস্বাদু রাতের খাবার রান্না করার জন্য আপনাকে যথেষ্ট ধন্যবাদ দিতে পারব না।",
          slotValues: { THING: "cooking such a delicious dinner" },
          topicArea: "food",
        },
        {
          en: "I can't thank you enough for showing me around the city.",
          bn: "আমাকে শহর ঘুরিয়ে দেখানোর জন্য আপনাকে যথেষ্ট ধন্যবাদ দিতে পারব না।",
          slotValues: { THING: "showing me around the city" },
          topicArea: "travel",
        },
        {
          en: "I can't thank you enough for tutoring my child.",
          bn: "আমার সন্তানকে টিউশনি দেওয়ার জন্য আপনাকে যথেষ্ট ধন্যবাদ দিতে পারব না।",
          slotValues: { THING: "tutoring my child" },
          topicArea: "education",
        },
        {
          en: "I can't thank you enough for your generosity.",
          bn: "আপনার উদারতার জন্য আপনাকে যথেষ্ট ধন্যবাদ দিতে পারব না।",
          slotValues: { THING: "your generosity" },
          topicArea: "daily_life",
        },
        {
          en: "I can't thank you enough for staying late to help finish the project.",
          bn: "প্রকল্প শেষ করতে সাহায্য করার জন্য দেরি পর্যন্ত থাকার জন্য আপনাকে যথেষ্ট ধন্যবাদ দিতে পারব না।",
          slotValues: { THING: "staying late to help finish the project" },
          topicArea: "work",
        },
        {
          en: "I can't thank you enough for the lovely gift.",
          bn: "চমৎকার উপহারের জন্য আপনাকে যথেষ্ট ধন্যবাদ দিতে পারব না।",
          slotValues: { THING: "the lovely gift" },
          topicArea: "shopping",
        },
        {
          en: "I can't thank you enough for believing in me.",
          bn: "আমার উপর বিশ্বাস রাখার জন্য আপনাকে যথেষ্ট ধন্যবাদ দিতে পারব না।",
          slotValues: { THING: "believing in me" },
          topicArea: "relationships",
        },
        {
          en: "I can't thank you enough for taking care of my parents.",
          bn: "আমার বাবা-মায়ের যত্ন নেওয়ার জন্য আপনাকে যথেষ্ট ধন্যবাদ দিতে পারব না।",
          slotValues: { THING: "taking care of my parents" },
          topicArea: "relationships",
        },
      ],
      formality: "polite",
      difficulty: "intermediate",
      usageNote:
        "Expresses that no amount of thanks would be sufficient. Emotionally powerful and sincere. Common in both formal and informal heartfelt expressions.",
      usageNote_bn:
        "প্রকাশ করে যে কোনো পরিমাণ ধন্যবাদই যথেষ্ট হবে না। আবেগপূর্ণভাবে শক্তিশালী ও আন্তরিক। আনুষ্ঠানিক ও অনানুষ্ঠানিক উভয় আন্তরিক প্রকাশে সাধারণ।",
      combinableWith: ["V8.3"],
      banglaStructureMap:
        "[বিষয়]-এর জন্য (Thing + Postposition) + আপনাকে যথেষ্ট ধন্যবাদ দিতে পারব না (You + Enough Thank + Can't)",
    },
    {
      id: "V8.5",
      formula: "Your [THING] is greatly appreciated",
      formula_bn: "আপনার [বিষয়] অত্যন্ত প্রশংসিত",
      patternName: "Greatly Appreciated",
      patternName_bn: "অত্যন্ত প্রশংসিত",
      slots: [
        {
          name: "THING",
          description: "The action, quality, or contribution being appreciated",
          description_bn: "যে কাজ, গুণ বা অবদানের প্রশংসা করা হচ্ছে",
          acceptedTypes: ["noun", "noun_phrase"],
          examples: ["support", "contribution", "assistance"],
        },
      ],
      examples: [
        {
          en: "Your support during this difficult period is greatly appreciated.",
          bn: "এই কঠিন সময়ে আপনার সমর্থন অত্যন্ত প্রশংসিত।",
          slotValues: { THING: "support during this difficult period" },
          topicArea: "work",
        },
        {
          en: "Your contribution to the project is greatly appreciated.",
          bn: "প্রকল্পে আপনার অবদান অত্যন্ত প্রশংসিত।",
          slotValues: { THING: "contribution to the project" },
          topicArea: "work",
        },
        {
          en: "Your assistance with the arrangements is greatly appreciated.",
          bn: "ব্যবস্থাপনায় আপনার সহায়তা অত্যন্ত প্রশংসিত।",
          slotValues: { THING: "assistance with the arrangements" },
          topicArea: "work",
        },
        {
          en: "Your patience throughout this process is greatly appreciated.",
          bn: "এই প্রক্রিয়া জুড়ে আপনার ধৈর্য অত্যন্ত প্রশংসিত।",
          slotValues: { THING: "patience throughout this process" },
          topicArea: "work",
        },
        {
          en: "Your feedback on the proposal is greatly appreciated.",
          bn: "প্রস্তাবে আপনার মতামত অত্যন্ত প্রশংসিত।",
          slotValues: { THING: "feedback on the proposal" },
          topicArea: "work",
        },
        {
          en: "Your generous donation is greatly appreciated.",
          bn: "আপনার উদার অনুদান অত্যন্ত প্রশংসিত।",
          slotValues: { THING: "generous donation" },
          topicArea: "daily_life",
        },
        {
          en: "Your hospitality during our stay is greatly appreciated.",
          bn: "আমাদের থাকার সময় আপনার আতিথেয়তা অত্যন্ত প্রশংসিত।",
          slotValues: { THING: "hospitality during our stay" },
          topicArea: "travel",
        },
        {
          en: "Your hard work this semester is greatly appreciated.",
          bn: "এই সেমিস্টারে আপনার কঠোর পরিশ্রম অত্যন্ত প্রশংসিত।",
          slotValues: { THING: "hard work this semester" },
          topicArea: "education",
        },
        {
          en: "Your prompt response is greatly appreciated.",
          bn: "আপনার দ্রুত সাড়া অত্যন্ত প্রশংসিত।",
          slotValues: { THING: "prompt response" },
          topicArea: "work",
        },
        {
          en: "Your care and attention to detail is greatly appreciated.",
          bn: "আপনার যত্ন ও বিস্তারিত মনোযোগ অত্যন্ত প্রশংসিত।",
          slotValues: { THING: "care and attention to detail" },
          topicArea: "health",
        },
        {
          en: "Your cooperation in this matter is greatly appreciated.",
          bn: "এই বিষয়ে আপনার সহযোগিতা অত্যন্ত প্রশংসিত।",
          slotValues: { THING: "cooperation in this matter" },
          topicArea: "work",
        },
        {
          en: "Your willingness to volunteer is greatly appreciated.",
          bn: "স্বেচ্ছাসেবা করার আপনার ইচ্ছা অত্যন্ত প্রশংসিত।",
          slotValues: { THING: "willingness to volunteer" },
          topicArea: "daily_life",
        },
        {
          en: "Your understanding during this transition is greatly appreciated.",
          bn: "এই পরিবর্তনকালে আপনার বোঝাপড়া অত্যন্ত প্রশংসিত।",
          slotValues: { THING: "understanding during this transition" },
          topicArea: "work",
        },
        {
          en: "Your recommendation is greatly appreciated.",
          bn: "আপনার সুপারিশ অত্যন্ত প্রশংসিত।",
          slotValues: { THING: "recommendation" },
          topicArea: "food",
        },
        {
          en: "Your loyalty as a customer is greatly appreciated.",
          bn: "একজন গ্রাহক হিসেবে আপনার আনুগত্য অত্যন্ত প্রশংসিত।",
          slotValues: { THING: "loyalty as a customer" },
          topicArea: "shopping",
        },
      ],
      formality: "formal",
      difficulty: "intermediate",
      usageNote:
        "A passive construction that sounds official and respectful. Often used in formal emails, certificates, and public acknowledgments.",
      usageNote_bn:
        "একটি কর্মবাচ্য গঠন যা সরকারি ও সম্মানজনক শোনায়। প্রায়ই আনুষ্ঠানিক ইমেইল, সনদপত্র এবং প্রকাশ্য স্বীকৃতিতে ব্যবহৃত।",
      combinableWith: ["V8.1", "V8.3"],
      banglaStructureMap:
        "আপনার [বিষয়] (Your + Thing) + অত্যন্ত প্রশংসিত (Greatly + Appreciated)",
    },
  ],
};
