import { PatternCategory } from "@/types/pattern";

export const categoryW1: PatternCategory = {
  id: "W1",
  slug: "presenting-explaining",
  name: "Presenting & Explaining",
  name_bn: "উপস্থাপনা ও ব্যাখ্যা",
  description:
    "Academic patterns for presenting topics and explaining ideas in lectures, seminars, and presentations",
  description_bn:
    "বক্তৃতা, সেমিনার এবং উপস্থাপনায় বিষয় উপস্থাপন ও ধারণা ব্যাখ্যা করার একাডেমিক প্যাটার্ন",
  icon: "🎓",
  group: "W",
  groupName: "Academic & Professional",
  groupName_bn: "একাডেমিক ও পেশাদার",
  difficulty: "advanced",
  patterns: [
    {
      id: "W1.1",
      formula: "Today I'm going to talk about [TOPIC]",
      formula_bn: "আজ আমি [বিষয়] নিয়ে কথা বলতে যাচ্ছি",
      patternName: "Opening a Presentation",
      patternName_bn: "উপস্থাপনা শুরু করা",
      slots: [
        {
          name: "TOPIC",
          description: "The subject or theme of the presentation",
          description_bn: "উপস্থাপনার বিষয় বা থিম",
          acceptedTypes: ["topic", "noun_phrase"],
          examples: ["climate change", "the impact of AI", "renewable energy"],
        },
      ],
      examples: [
        {
          en: "Today I'm going to talk about climate change.",
          bn: "আজ আমি জলবায়ু পরিবর্তন নিয়ে কথা বলতে যাচ্ছি।",
          slotValues: { TOPIC: "climate change" },
          topicArea: "environment",
        },
        {
          en: "Today I'm going to talk about the impact of artificial intelligence.",
          bn: "আজ আমি কৃত্রিম বুদ্ধিমত্তার প্রভাব নিয়ে কথা বলতে যাচ্ছি।",
          slotValues: { TOPIC: "the impact of artificial intelligence" },
          topicArea: "technology",
        },
        {
          en: "Today I'm going to talk about renewable energy sources.",
          bn: "আজ আমি নবায়নযোগ্য শক্তির উৎস নিয়ে কথা বলতে যাচ্ছি।",
          slotValues: { TOPIC: "renewable energy sources" },
          topicArea: "science",
        },
        {
          en: "Today I'm going to talk about global economic trends.",
          bn: "আজ আমি বৈশ্বিক অর্থনৈতিক প্রবণতা নিয়ে কথা বলতে যাচ্ছি।",
          slotValues: { TOPIC: "global economic trends" },
          topicArea: "economics",
        },
        {
          en: "Today I'm going to talk about mental health awareness.",
          bn: "আজ আমি মানসিক স্বাস্থ্য সচেতনতা নিয়ে কথা বলতে যাচ্ছি।",
          slotValues: { TOPIC: "mental health awareness" },
          topicArea: "health",
        },
        {
          en: "Today I'm going to talk about the history of the internet.",
          bn: "আজ আমি ইন্টারনেটের ইতিহাস নিয়ে কথা বলতে যাচ্ছি।",
          slotValues: { TOPIC: "the history of the internet" },
          topicArea: "technology",
        },
        {
          en: "Today I'm going to talk about sustainable development.",
          bn: "আজ আমি টেকসই উন্নয়ন নিয়ে কথা বলতে যাচ্ছি।",
          slotValues: { TOPIC: "sustainable development" },
          topicArea: "environment",
        },
        {
          en: "Today I'm going to talk about the education system in Bangladesh.",
          bn: "আজ আমি বাংলাদেশের শিক্ষাব্যবস্থা নিয়ে কথা বলতে যাচ্ছি।",
          slotValues: { TOPIC: "the education system in Bangladesh" },
          topicArea: "education",
        },
        {
          en: "Today I'm going to talk about the benefits of exercise.",
          bn: "আজ আমি ব্যায়ামের উপকারিতা নিয়ে কথা বলতে যাচ্ছি।",
          slotValues: { TOPIC: "the benefits of exercise" },
          topicArea: "health",
        },
        {
          en: "Today I'm going to talk about data privacy.",
          bn: "আজ আমি ডেটা গোপনীয়তা নিয়ে কথা বলতে যাচ্ছি।",
          slotValues: { TOPIC: "data privacy" },
          topicArea: "technology",
        },
        {
          en: "Today I'm going to talk about urbanization and its effects.",
          bn: "আজ আমি নগরায়ণ এবং এর প্রভাব নিয়ে কথা বলতে যাচ্ছি।",
          slotValues: { TOPIC: "urbanization and its effects" },
          topicArea: "environment",
        },
        {
          en: "Today I'm going to talk about the role of women in leadership.",
          bn: "আজ আমি নেতৃত্বে নারীদের ভূমিকা নিয়ে কথা বলতে যাচ্ছি।",
          slotValues: { TOPIC: "the role of women in leadership" },
          topicArea: "work",
        },
        {
          en: "Today I'm going to talk about food security.",
          bn: "আজ আমি খাদ্য নিরাপত্তা নিয়ে কথা বলতে যাচ্ছি।",
          slotValues: { TOPIC: "food security" },
          topicArea: "food",
        },
        {
          en: "Today I'm going to talk about childhood development.",
          bn: "আজ আমি শিশু বিকাশ নিয়ে কথা বলতে যাচ্ছি।",
          slotValues: { TOPIC: "childhood development" },
          topicArea: "education",
        },
        {
          en: "Today I'm going to talk about cross-cultural communication.",
          bn: "আজ আমি আন্তঃসাংস্কৃতিক যোগাযোগ নিয়ে কথা বলতে যাচ্ছি।",
          slotValues: { TOPIC: "cross-cultural communication" },
          topicArea: "education",
        },
      ],
      formality: "formal",
      difficulty: "advanced",
      usageNote:
        "A standard opening phrase for presentations and lectures. Sets the agenda clearly for the audience.",
      usageNote_bn:
        "উপস্থাপনা ও বক্তৃতার জন্য একটি আদর্শ শুরুর বাক্যাংশ। শ্রোতাদের জন্য পরিষ্কারভাবে এজেন্ডা নির্ধারণ করে।",
    },
    {
      id: "W1.2",
      formula: "Let me start by [DOING]",
      formula_bn: "আমাকে [কাজ] দিয়ে শুরু করতে দিন",
      patternName: "Starting with an Action",
      patternName_bn: "একটি কাজ দিয়ে শুরু করা",
      slots: [
        {
          name: "DOING",
          description: "A gerund phrase describing the opening action",
          description_bn: "শুরুর কাজটি বর্ণনাকারী একটি জেরান্ড বাক্যাংশ",
          acceptedTypes: ["gerund", "verb_phrase"],
          examples: ["defining the key terms", "giving you some background", "showing a graph"],
        },
      ],
      examples: [
        {
          en: "Let me start by defining the key terms.",
          bn: "আমাকে মূল পরিভাষাগুলো সংজ্ঞায়িত করে শুরু করতে দিন।",
          slotValues: { DOING: "defining the key terms" },
          topicArea: "education",
        },
        {
          en: "Let me start by giving you some background information.",
          bn: "আমাকে আপনাদের কিছু পটভূমির তথ্য দিয়ে শুরু করতে দিন।",
          slotValues: { DOING: "giving you some background information" },
          topicArea: "education",
        },
        {
          en: "Let me start by showing you a graph.",
          bn: "আমাকে আপনাদের একটি গ্রাফ দেখিয়ে শুরু করতে দিন।",
          slotValues: { DOING: "showing you a graph" },
          topicArea: "science",
        },
        {
          en: "Let me start by outlining the main objectives.",
          bn: "আমাকে প্রধান উদ্দেশ্যগুলো তুলে ধরে শুরু করতে দিন।",
          slotValues: { DOING: "outlining the main objectives" },
          topicArea: "work",
        },
        {
          en: "Let me start by asking a question.",
          bn: "আমাকে একটি প্রশ্ন জিজ্ঞাসা করে শুরু করতে দিন।",
          slotValues: { DOING: "asking a question" },
          topicArea: "education",
        },
        {
          en: "Let me start by reviewing what we discussed last time.",
          bn: "আমাকে গত বারের আলোচনা পর্যালোচনা করে শুরু করতে দিন।",
          slotValues: { DOING: "reviewing what we discussed last time" },
          topicArea: "education",
        },
        {
          en: "Let me start by sharing some statistics.",
          bn: "আমাকে কিছু পরিসংখ্যান শেয়ার করে শুরু করতে দিন।",
          slotValues: { DOING: "sharing some statistics" },
          topicArea: "science",
        },
        {
          en: "Let me start by introducing the research team.",
          bn: "আমাকে গবেষণা দলের পরিচয় দিয়ে শুরু করতে দিন।",
          slotValues: { DOING: "introducing the research team" },
          topicArea: "work",
        },
        {
          en: "Let me start by explaining the methodology.",
          bn: "আমাকে পদ্ধতি ব্যাখ্যা করে শুরু করতে দিন।",
          slotValues: { DOING: "explaining the methodology" },
          topicArea: "science",
        },
        {
          en: "Let me start by summarizing the current situation.",
          bn: "আমাকে বর্তমান পরিস্থিতি সংক্ষেপে বলে শুরু করতে দিন।",
          slotValues: { DOING: "summarizing the current situation" },
          topicArea: "work",
        },
        {
          en: "Let me start by telling you a story.",
          bn: "আমাকে আপনাদের একটি গল্প বলে শুরু করতে দিন।",
          slotValues: { DOING: "telling you a story" },
          topicArea: "education",
        },
        {
          en: "Let me start by presenting the data.",
          bn: "আমাকে তথ্য উপস্থাপন করে শুরু করতে দিন।",
          slotValues: { DOING: "presenting the data" },
          topicArea: "science",
        },
        {
          en: "Let me start by clarifying the scope of this study.",
          bn: "আমাকে এই গবেষণার পরিধি স্পষ্ট করে শুরু করতে দিন।",
          slotValues: { DOING: "clarifying the scope of this study" },
          topicArea: "science",
        },
        {
          en: "Let me start by addressing the most common misconception.",
          bn: "আমাকে সবচেয়ে সাধারণ ভুল ধারণাটি দূর করে শুরু করতে দিন।",
          slotValues: { DOING: "addressing the most common misconception" },
          topicArea: "education",
        },
        {
          en: "Let me start by setting the context.",
          bn: "আমাকে প্রসঙ্গ নির্ধারণ করে শুরু করতে দিন।",
          slotValues: { DOING: "setting the context" },
          topicArea: "education",
        },
      ],
      formality: "formal",
      difficulty: "advanced",
      usageNote:
        "Used to transition into the first point or section of a presentation. Signals structure to the audience.",
      usageNote_bn:
        "উপস্থাপনার প্রথম পয়েন্ট বা বিভাগে প্রবেশ করতে ব্যবহৃত। শ্রোতাদের কাছে গঠন সংকেত দেয়।",
    },
    {
      id: "W1.3",
      formula: "As you can see, [CLAUSE]",
      formula_bn: "আপনারা দেখতে পাচ্ছেন, [বাক্যাংশ]",
      patternName: "Referring to Visual Evidence",
      patternName_bn: "দৃশ্যমান প্রমাণের উল্লেখ",
      slots: [
        {
          name: "CLAUSE",
          description: "A statement about what the evidence shows",
          description_bn: "প্রমাণ কী দেখায় সে সম্পর্কে একটি বিবৃতি",
          acceptedTypes: ["clause"],
          examples: ["the numbers have increased", "there is a clear trend", "the results are significant"],
        },
      ],
      examples: [
        {
          en: "As you can see, the numbers have increased dramatically.",
          bn: "আপনারা দেখতে পাচ্ছেন, সংখ্যাগুলো নাটকীয়ভাবে বেড়েছে।",
          slotValues: { CLAUSE: "the numbers have increased dramatically" },
          topicArea: "science",
        },
        {
          en: "As you can see, there is a clear trend in the data.",
          bn: "আপনারা দেখতে পাচ্ছেন, তথ্যে একটি স্পষ্ট প্রবণতা আছে।",
          slotValues: { CLAUSE: "there is a clear trend in the data" },
          topicArea: "science",
        },
        {
          en: "As you can see, the results are statistically significant.",
          bn: "আপনারা দেখতে পাচ্ছেন, ফলাফলগুলো পরিসংখ্যানগতভাবে তাৎপর্যপূর্ণ।",
          slotValues: { CLAUSE: "the results are statistically significant" },
          topicArea: "science",
        },
        {
          en: "As you can see, the graph shows a sharp decline.",
          bn: "আপনারা দেখতে পাচ্ছেন, গ্রাফটি একটি তীব্র পতন দেখাচ্ছে।",
          slotValues: { CLAUSE: "the graph shows a sharp decline" },
          topicArea: "economics",
        },
        {
          en: "As you can see, both variables are correlated.",
          bn: "আপনারা দেখতে পাচ্ছেন, উভয় চলক পরস্পর সম্পর্কযুক্ত।",
          slotValues: { CLAUSE: "both variables are correlated" },
          topicArea: "science",
        },
        {
          en: "As you can see, the situation has improved since 2020.",
          bn: "আপনারা দেখতে পাচ্ছেন, ২০২০ সাল থেকে পরিস্থিতির উন্নতি হয়েছে।",
          slotValues: { CLAUSE: "the situation has improved since 2020" },
          topicArea: "economics",
        },
        {
          en: "As you can see, the majority of respondents agreed.",
          bn: "আপনারা দেখতে পাচ্ছেন, বেশিরভাগ উত্তরদাতা একমত হয়েছেন।",
          slotValues: { CLAUSE: "the majority of respondents agreed" },
          topicArea: "science",
        },
        {
          en: "As you can see, the chart illustrates a steady growth.",
          bn: "আপনারা দেখতে পাচ্ছেন, চার্টটি একটি স্থিতিশীল প্রবৃদ্ধি দেখাচ্ছে।",
          slotValues: { CLAUSE: "the chart illustrates a steady growth" },
          topicArea: "economics",
        },
        {
          en: "As you can see, there are significant differences between the two groups.",
          bn: "আপনারা দেখতে পাচ্ছেন, দুটি গ্রুপের মধ্যে উল্লেখযোগ্য পার্থক্য রয়েছে।",
          slotValues: { CLAUSE: "there are significant differences between the two groups" },
          topicArea: "science",
        },
        {
          en: "As you can see, the project is on track.",
          bn: "আপনারা দেখতে পাচ্ছেন, প্রকল্পটি সঠিক পথে আছে।",
          slotValues: { CLAUSE: "the project is on track" },
          topicArea: "work",
        },
        {
          en: "As you can see, the budget has been exceeded.",
          bn: "আপনারা দেখতে পাচ্ছেন, বাজেট অতিক্রম করা হয়েছে।",
          slotValues: { CLAUSE: "the budget has been exceeded" },
          topicArea: "work",
        },
        {
          en: "As you can see, the pie chart breaks down the demographics.",
          bn: "আপনারা দেখতে পাচ্ছেন, পাই চার্টটি জনসংখ্যা বিশ্লেষণ করেছে।",
          slotValues: { CLAUSE: "the pie chart breaks down the demographics" },
          topicArea: "science",
        },
        {
          en: "As you can see, pollution levels have dropped.",
          bn: "আপনারা দেখতে পাচ্ছেন, দূষণের মাত্রা কমেছে।",
          slotValues: { CLAUSE: "pollution levels have dropped" },
          topicArea: "environment",
        },
        {
          en: "As you can see, the timeline is very tight.",
          bn: "আপনারা দেখতে পাচ্ছেন, সময়সীমা খুবই সংক্ষিপ্ত।",
          slotValues: { CLAUSE: "the timeline is very tight" },
          topicArea: "work",
        },
        {
          en: "As you can see, the experiment confirms our hypothesis.",
          bn: "আপনারা দেখতে পাচ্ছেন, পরীক্ষাটি আমাদের অনুমান নিশ্চিত করে।",
          slotValues: { CLAUSE: "the experiment confirms our hypothesis" },
          topicArea: "science",
        },
      ],
      formality: "formal",
      difficulty: "advanced",
      usageNote:
        "Draws the audience's attention to visual aids like slides, charts, or graphs during a presentation.",
      usageNote_bn:
        "উপস্থাপনার সময় স্লাইড, চার্ট বা গ্রাফের মতো ভিজ্যুয়াল এইডের প্রতি শ্রোতাদের মনোযোগ আকর্ষণ করে।",
    },
    {
      id: "W1.4",
      formula: "To illustrate this point, [CLAUSE]",
      formula_bn: "এই বিষয়টি চিত্রিত করতে, [বাক্যাংশ]",
      patternName: "Illustrating a Point",
      patternName_bn: "একটি বিষয় চিত্রিত করা",
      slots: [
        {
          name: "CLAUSE",
          description: "An example or explanation that supports the point",
          description_bn: "একটি উদাহরণ বা ব্যাখ্যা যা বিষয়টিকে সমর্থন করে",
          acceptedTypes: ["clause"],
          examples: ["let me share an example", "consider this scenario", "look at the following data"],
        },
      ],
      examples: [
        {
          en: "To illustrate this point, let me share an example.",
          bn: "এই বিষয়টি চিত্রিত করতে, আমাকে একটি উদাহরণ শেয়ার করতে দিন।",
          slotValues: { CLAUSE: "let me share an example" },
          topicArea: "education",
        },
        {
          en: "To illustrate this point, consider the case of Japan.",
          bn: "এই বিষয়টি চিত্রিত করতে, জাপানের উদাহরণ বিবেচনা করুন।",
          slotValues: { CLAUSE: "consider the case of Japan" },
          topicArea: "economics",
        },
        {
          en: "To illustrate this point, look at the following data.",
          bn: "এই বিষয়টি চিত্রিত করতে, নিম্নলিখিত তথ্য দেখুন।",
          slotValues: { CLAUSE: "look at the following data" },
          topicArea: "science",
        },
        {
          en: "To illustrate this point, I'll use a real-world scenario.",
          bn: "এই বিষয়টি চিত্রিত করতে, আমি একটি বাস্তব উদাহরণ ব্যবহার করব।",
          slotValues: { CLAUSE: "I'll use a real-world scenario" },
          topicArea: "education",
        },
        {
          en: "To illustrate this point, imagine you are a teacher.",
          bn: "এই বিষয়টি চিত্রিত করতে, কল্পনা করুন আপনি একজন শিক্ষক।",
          slotValues: { CLAUSE: "imagine you are a teacher" },
          topicArea: "education",
        },
        {
          en: "To illustrate this point, here is a photograph from the field.",
          bn: "এই বিষয়টি চিত্রিত করতে, এখানে মাঠ থেকে একটি ছবি রয়েছে।",
          slotValues: { CLAUSE: "here is a photograph from the field" },
          topicArea: "science",
        },
        {
          en: "To illustrate this point, let's compare two countries.",
          bn: "এই বিষয়টি চিত্রিত করতে, চলুন দুটি দেশের তুলনা করি।",
          slotValues: { CLAUSE: "let's compare two countries" },
          topicArea: "economics",
        },
        {
          en: "To illustrate this point, think about your own experience.",
          bn: "এই বিষয়টি চিত্রিত করতে, আপনার নিজের অভিজ্ঞতার কথা ভাবুন।",
          slotValues: { CLAUSE: "think about your own experience" },
          topicArea: "daily_life",
        },
        {
          en: "To illustrate this point, the diagram on the right is helpful.",
          bn: "এই বিষয়টি চিত্রিত করতে, ডানদিকের চিত্রটি সহায়ক।",
          slotValues: { CLAUSE: "the diagram on the right is helpful" },
          topicArea: "science",
        },
        {
          en: "To illustrate this point, sales doubled in just one year.",
          bn: "এই বিষয়টি চিত্রিত করতে, মাত্র এক বছরে বিক্রি দ্বিগুণ হয়েছে।",
          slotValues: { CLAUSE: "sales doubled in just one year" },
          topicArea: "economics",
        },
        {
          en: "To illustrate this point, we conducted a survey.",
          bn: "এই বিষয়টি চিত্রিত করতে, আমরা একটি জরিপ পরিচালনা করেছি।",
          slotValues: { CLAUSE: "we conducted a survey" },
          topicArea: "science",
        },
        {
          en: "To illustrate this point, the unemployment rate fell by 3%.",
          bn: "এই বিষয়টি চিত্রিত করতে, বেকারত্বের হার ৩% কমেছে।",
          slotValues: { CLAUSE: "the unemployment rate fell by 3%" },
          topicArea: "economics",
        },
        {
          en: "To illustrate this point, let me read a quote.",
          bn: "এই বিষয়টি চিত্রিত করতে, আমাকে একটি উদ্ধৃতি পড়তে দিন।",
          slotValues: { CLAUSE: "let me read a quote" },
          topicArea: "education",
        },
        {
          en: "To illustrate this point, the patient's recovery was remarkably fast.",
          bn: "এই বিষয়টি চিত্রিত করতে, রোগীর সুস্থতা অসাধারণ দ্রুত ছিল।",
          slotValues: { CLAUSE: "the patient's recovery was remarkably fast" },
          topicArea: "health",
        },
        {
          en: "To illustrate this point, notice how the color changes over time.",
          bn: "এই বিষয়টি চিত্রিত করতে, লক্ষ্য করুন কীভাবে রঙ সময়ের সাথে পরিবর্তিত হয়।",
          slotValues: { CLAUSE: "notice how the color changes over time" },
          topicArea: "science",
        },
      ],
      formality: "formal",
      difficulty: "advanced",
      usageNote:
        "Used to introduce an example, analogy, or visual that supports a claim being made in a presentation.",
      usageNote_bn:
        "উপস্থাপনায় করা দাবিকে সমর্থন করে এমন উদাহরণ, সাদৃশ্য বা ভিজ্যুয়াল পরিচয় করাতে ব্যবহৃত।",
    },
    {
      id: "W1.5",
      formula: "In conclusion, [CLAUSE]",
      formula_bn: "উপসংহারে, [বাক্যাংশ]",
      patternName: "Concluding a Presentation",
      patternName_bn: "উপস্থাপনা শেষ করা",
      slots: [
        {
          name: "CLAUSE",
          description: "A summary statement or final thought",
          description_bn: "একটি সারসংক্ষেপ বিবৃতি বা চূড়ান্ত চিন্তা",
          acceptedTypes: ["clause"],
          examples: ["we can say that", "the evidence clearly shows", "it is important to remember"],
        },
      ],
      examples: [
        {
          en: "In conclusion, we can say that technology has transformed education.",
          bn: "উপসংহারে, আমরা বলতে পারি যে প্রযুক্তি শিক্ষাকে রূপান্তরিত করেছে।",
          slotValues: { CLAUSE: "we can say that technology has transformed education" },
          topicArea: "education",
        },
        {
          en: "In conclusion, the evidence clearly supports our hypothesis.",
          bn: "উপসংহারে, প্রমাণ স্পষ্টভাবে আমাদের অনুমানকে সমর্থন করে।",
          slotValues: { CLAUSE: "the evidence clearly supports our hypothesis" },
          topicArea: "science",
        },
        {
          en: "In conclusion, climate change remains the greatest challenge of our time.",
          bn: "উপসংহারে, জলবায়ু পরিবর্তন আমাদের সময়ের সবচেয়ে বড় চ্যালেঞ্জ।",
          slotValues: { CLAUSE: "climate change remains the greatest challenge of our time" },
          topicArea: "environment",
        },
        {
          en: "In conclusion, early intervention is key to success.",
          bn: "উপসংহারে, প্রাথমিক হস্তক্ষেপ সাফল্যের চাবিকাঠি।",
          slotValues: { CLAUSE: "early intervention is key to success" },
          topicArea: "health",
        },
        {
          en: "In conclusion, more research is needed in this area.",
          bn: "উপসংহারে, এই ক্ষেত্রে আরও গবেষণা প্রয়োজন।",
          slotValues: { CLAUSE: "more research is needed in this area" },
          topicArea: "science",
        },
        {
          en: "In conclusion, collaboration is essential for innovation.",
          bn: "উপসংহারে, উদ্ভাবনের জন্য সহযোগিতা অপরিহার্য।",
          slotValues: { CLAUSE: "collaboration is essential for innovation" },
          topicArea: "work",
        },
        {
          en: "In conclusion, the data speaks for itself.",
          bn: "উপসংহারে, তথ্যই নিজের পক্ষে কথা বলে।",
          slotValues: { CLAUSE: "the data speaks for itself" },
          topicArea: "science",
        },
        {
          en: "In conclusion, we must take action now.",
          bn: "উপসংহারে, আমাদের এখনই পদক্ষেপ নিতে হবে।",
          slotValues: { CLAUSE: "we must take action now" },
          topicArea: "environment",
        },
        {
          en: "In conclusion, investing in education pays off in the long run.",
          bn: "উপসংহারে, শিক্ষায় বিনিয়োগ দীর্ঘমেয়াদে ফল দেয়।",
          slotValues: { CLAUSE: "investing in education pays off in the long run" },
          topicArea: "education",
        },
        {
          en: "In conclusion, the project has achieved all its objectives.",
          bn: "উপসংহারে, প্রকল্পটি তার সমস্ত উদ্দেশ্য অর্জন করেছে।",
          slotValues: { CLAUSE: "the project has achieved all its objectives" },
          topicArea: "work",
        },
        {
          en: "In conclusion, poverty reduction requires a multi-faceted approach.",
          bn: "উপসংহারে, দারিদ্র্য হ্রাসের জন্য বহুমুখী পদ্ধতির প্রয়োজন।",
          slotValues: { CLAUSE: "poverty reduction requires a multi-faceted approach" },
          topicArea: "economics",
        },
        {
          en: "In conclusion, prevention is better than cure.",
          bn: "উপসংহারে, প্রতিকারের চেয়ে প্রতিরোধ ভালো।",
          slotValues: { CLAUSE: "prevention is better than cure" },
          topicArea: "health",
        },
        {
          en: "In conclusion, the findings have important implications for policy.",
          bn: "উপসংহারে, এই ফলাফলগুলো নীতির জন্য গুরুত্বপূর্ণ প্রভাব রাখে।",
          slotValues: { CLAUSE: "the findings have important implications for policy" },
          topicArea: "science",
        },
        {
          en: "In conclusion, globalization has both positive and negative effects.",
          bn: "উপসংহারে, বিশ্বায়নের ইতিবাচক ও নেতিবাচক উভয় প্রভাব রয়েছে।",
          slotValues: { CLAUSE: "globalization has both positive and negative effects" },
          topicArea: "economics",
        },
        {
          en: "In conclusion, I hope this presentation has been informative.",
          bn: "উপসংহারে, আমি আশা করি এই উপস্থাপনাটি তথ্যবহুল হয়েছে।",
          slotValues: { CLAUSE: "I hope this presentation has been informative" },
          topicArea: "education",
        },
      ],
      formality: "formal",
      difficulty: "advanced",
      usageNote:
        "A classic conclusion phrase for wrapping up presentations, essays, or speeches. Signals the end of the talk.",
      usageNote_bn:
        "উপস্থাপনা, প্রবন্ধ বা বক্তৃতা শেষ করার জন্য একটি ক্লাসিক উপসংহার বাক্যাংশ। আলোচনার সমাপ্তি সংকেত দেয়।",
    },
  ],
};
