import { PatternCategory } from "@/types/pattern";

export const categoryW13: PatternCategory = {
  id: "W13",
  slug: "technical-processes",
  name: "Describing Technical Processes",
  name_bn: "প্রযুক্তিগত প্রক্রিয়া বর্ণনা",
  description: "Patterns for describing how things work, processes, and technical procedures",
  description_bn: "বিষয়গুলো কীভাবে কাজ করে, প্রক্রিয়া এবং প্রযুক্তিগত পদ্ধতি বর্ণনার প্যাটার্ন",
  icon: "⚙️",
  group: "W",
  groupName: "Academic & Professional",
  groupName_bn: "একাডেমিক ও পেশাদার",
  difficulty: "advanced",
  patterns: [
    {
      id: "W13.1", formula: "[THING] consists of [PARTS]", formula_bn: "[বিষয়] [অংশ] নিয়ে গঠিত",
      patternName: "Describing Components", patternName_bn: "উপাদান বর্ণনা",
      slots: [
        { name: "THING", description: "The whole system or object", description_bn: "সম্পূর্ণ সিস্টেম বা বস্তু", acceptedTypes: ["noun", "noun_phrase"], examples: ["the system", "the device", "the process"] },
        { name: "PARTS", description: "The components or elements", description_bn: "উপাদান বা উপকরণ", acceptedTypes: ["noun_phrase"], examples: ["three main modules", "hardware and software", "several stages"] },
      ],
      examples: [
        { en: "The system consists of three main modules.", bn: "সিস্টেমটি তিনটি প্রধান মডিউল নিয়ে গঠিত।", slotValues: { THING: "The system", PARTS: "three main modules" }, topicArea: "technology" },
        { en: "The device consists of a sensor, a processor, and a display.", bn: "ডিভাইসটি একটি সেন্সর, একটি প্রসেসর এবং একটি ডিসপ্লে নিয়ে গঠিত।", slotValues: { THING: "The device", PARTS: "a sensor, a processor, and a display" }, topicArea: "technology" },
        { en: "The process consists of five sequential steps.", bn: "প্রক্রিয়াটি পাঁচটি ধারাবাহিক ধাপ নিয়ে গঠিত।", slotValues: { THING: "The process", PARTS: "five sequential steps" }, topicArea: "science" },
        { en: "The human body consists of multiple organ systems.", bn: "মানবদেহ একাধিক অঙ্গ সিস্টেম নিয়ে গঠিত।", slotValues: { THING: "The human body", PARTS: "multiple organ systems" }, topicArea: "health" },
        { en: "The curriculum consists of core and elective courses.", bn: "পাঠ্যক্রমটি মূল ও ঐচ্ছিক কোর্স নিয়ে গঠিত।", slotValues: { THING: "The curriculum", PARTS: "core and elective courses" }, topicArea: "education" },
        { en: "A computer consists of hardware and software components.", bn: "একটি কম্পিউটার হার্ডওয়্যার ও সফটওয়্যার উপাদান নিয়ে গঠিত।", slotValues: { THING: "A computer", PARTS: "hardware and software components" }, topicArea: "technology" },
        { en: "The report consists of an introduction, methodology, and findings.", bn: "প্রতিবেদনটি ভূমিকা, পদ্ধতি ও ফলাফল নিয়ে গঠিত।", slotValues: { THING: "The report", PARTS: "an introduction, methodology, and findings" }, topicArea: "science" },
        { en: "The ecosystem consists of living and non-living components.", bn: "বাস্তুতন্ত্রটি জীবিত ও নির্জীব উপাদান নিয়ে গঠিত।", slotValues: { THING: "The ecosystem", PARTS: "living and non-living components" }, topicArea: "environment" },
        { en: "The training program consists of online and in-person sessions.", bn: "প্রশিক্ষণ কর্মসূচিটি অনলাইন ও সশরীর সেশন নিয়ে গঠিত।", slotValues: { THING: "The training program", PARTS: "online and in-person sessions" }, topicArea: "work" },
        { en: "The solar panel consists of photovoltaic cells.", bn: "সোলার প্যানেলটি ফটোভোল্টাইক সেল নিয়ে গঠিত।", slotValues: { THING: "The solar panel", PARTS: "photovoltaic cells" }, topicArea: "science" },
        { en: "The vaccine consists of weakened virus particles.", bn: "টিকাটি দুর্বল ভাইরাস কণা নিয়ে গঠিত।", slotValues: { THING: "The vaccine", PARTS: "weakened virus particles" }, topicArea: "health" },
        { en: "The database consists of multiple interconnected tables.", bn: "ডেটাবেসটি একাধিক আন্তঃসংযুক্ত টেবিল নিয়ে গঠিত।", slotValues: { THING: "The database", PARTS: "multiple interconnected tables" }, topicArea: "technology" },
        { en: "The assessment consists of written and oral components.", bn: "মূল্যায়নটি লিখিত ও মৌখিক উপাদান নিয়ে গঠিত।", slotValues: { THING: "The assessment", PARTS: "written and oral components" }, topicArea: "education" },
        { en: "The supply chain consists of suppliers, manufacturers, and distributors.", bn: "সাপ্লাই চেইনটি সরবরাহকারী, প্রস্তুতকারক ও পরিবেশক নিয়ে গঠিত।", slotValues: { THING: "The supply chain", PARTS: "suppliers, manufacturers, and distributors" }, topicArea: "work" },
        { en: "The atmosphere consists of several layers of gases.", bn: "বায়ুমণ্ডলটি গ্যাসের বেশ কয়েকটি স্তর নিয়ে গঠিত।", slotValues: { THING: "The atmosphere", PARTS: "several layers of gases" }, topicArea: "science" },
      ],
      formality: "formal", difficulty: "advanced",
      usageNote: "Used to break down a system or object into its constituent parts.",
      usageNote_bn: "একটি সিস্টেম বা বস্তুকে এর গঠনকারী অংশে ভেঙে বর্ণনা করতে ব্যবহৃত।",
    },
    {
      id: "W13.2", formula: "The process involves [DOING]", formula_bn: "প্রক্রিয়াটি [কাজ] অন্তর্ভুক্ত করে",
      patternName: "Describing Process Steps", patternName_bn: "প্রক্রিয়ার ধাপ বর্ণনা",
      slots: [
        { name: "DOING", description: "The actions or steps in the process", description_bn: "প্রক্রিয়ার কাজ বা ধাপ", acceptedTypes: ["gerund", "verb_phrase"], examples: ["collecting data", "heating the mixture", "reviewing applications"] },
      ],
      examples: [
        { en: "The process involves collecting data from multiple sources.", bn: "প্রক্রিয়াটি একাধিক উৎস থেকে তথ্য সংগ্রহ অন্তর্ভুক্ত করে।", slotValues: { DOING: "collecting data from multiple sources" }, topicArea: "science" },
        { en: "The process involves heating the mixture to 100 degrees.", bn: "প্রক্রিয়াটি মিশ্রণটি ১০০ ডিগ্রিতে গরম করা অন্তর্ভুক্ত করে।", slotValues: { DOING: "heating the mixture to 100 degrees" }, topicArea: "science" },
        { en: "The process involves reviewing all applications carefully.", bn: "প্রক্রিয়াটি সব আবেদন সাবধানে পর্যালোচনা করা অন্তর্ভুক্ত করে।", slotValues: { DOING: "reviewing all applications carefully" }, topicArea: "work" },
        { en: "The process involves filtering impurities from the water.", bn: "প্রক্রিয়াটি পানি থেকে অশুদ্ধতা ফিল্টার করা অন্তর্ভুক্ত করে।", slotValues: { DOING: "filtering impurities from the water" }, topicArea: "environment" },
        { en: "The process involves testing the product at each stage.", bn: "প্রক্রিয়াটি প্রতিটি পর্যায়ে পণ্য পরীক্ষা করা অন্তর্ভুক্ত করে।", slotValues: { DOING: "testing the product at each stage" }, topicArea: "work" },
        { en: "The process involves analyzing blood samples.", bn: "প্রক্রিয়াটি রক্তের নমুনা বিশ্লেষণ করা অন্তর্ভুক্ত করে।", slotValues: { DOING: "analyzing blood samples" }, topicArea: "health" },
        { en: "The process involves writing and debugging code.", bn: "প্রক্রিয়াটি কোড লেখা ও ডিবাগ করা অন্তর্ভুক্ত করে।", slotValues: { DOING: "writing and debugging code" }, topicArea: "technology" },
        { en: "The process involves interviewing candidates.", bn: "প্রক্রিয়াটি প্রার্থীদের সাক্ষাৎকার নেওয়া অন্তর্ভুক্ত করে।", slotValues: { DOING: "interviewing candidates" }, topicArea: "work" },
        { en: "The process involves extracting DNA from cells.", bn: "প্রক্রিয়াটি কোষ থেকে DNA নিষ্কাশন করা অন্তর্ভুক্ত করে।", slotValues: { DOING: "extracting DNA from cells" }, topicArea: "science" },
        { en: "The process involves peer review and revision.", bn: "প্রক্রিয়াটি পিয়ার রিভিউ ও সংশোধন অন্তর্ভুক্ত করে।", slotValues: { DOING: "peer review and revision" }, topicArea: "science" },
        { en: "The process involves training machine learning models.", bn: "প্রক্রিয়াটি মেশিন লার্নিং মডেল প্রশিক্ষণ অন্তর্ভুক্ত করে।", slotValues: { DOING: "training machine learning models" }, topicArea: "technology" },
        { en: "The process involves planting seeds and monitoring growth.", bn: "প্রক্রিয়াটি বীজ রোপণ ও বৃদ্ধি পর্যবেক্ষণ অন্তর্ভুক্ত করে।", slotValues: { DOING: "planting seeds and monitoring growth" }, topicArea: "environment" },
        { en: "The process involves verifying identity documents.", bn: "প্রক্রিয়াটি পরিচয় নথি যাচাই করা অন্তর্ভুক্ত করে।", slotValues: { DOING: "verifying identity documents" }, topicArea: "work" },
        { en: "The process involves sterilizing equipment before surgery.", bn: "প্রক্রিয়াটি অস্ত্রোপচারের আগে সরঞ্জাম জীবাণুমুক্ত করা অন্তর্ভুক্ত করে।", slotValues: { DOING: "sterilizing equipment before surgery" }, topicArea: "health" },
        { en: "The process involves compiling and interpreting survey results.", bn: "প্রক্রিয়াটি জরিপ ফলাফল সংকলন ও ব্যাখ্যা করা অন্তর্ভুক্ত করে।", slotValues: { DOING: "compiling and interpreting survey results" }, topicArea: "science" },
      ],
      formality: "formal", difficulty: "advanced",
      usageNote: "Describes what actions a process includes. Essential for technical and scientific writing.",
      usageNote_bn: "একটি প্রক্রিয়া কী কাজ অন্তর্ভুক্ত করে তা বর্ণনা করে। প্রযুক্তিগত ও বৈজ্ঞানিক লেখার জন্য অপরিহার্য।",
    },
    {
      id: "W13.3", formula: "[THING] works by [DOING]", formula_bn: "[বিষয়] [কাজ] করে কাজ করে",
      patternName: "Explaining Mechanism", patternName_bn: "কৌশল ব্যাখ্যা",
      slots: [
        { name: "THING", description: "The device or system", description_bn: "ডিভাইস বা সিস্টেম", acceptedTypes: ["noun", "noun_phrase"], examples: ["the engine", "the algorithm", "the vaccine"] },
        { name: "DOING", description: "How it operates", description_bn: "এটি কীভাবে কাজ করে", acceptedTypes: ["gerund", "verb_phrase"], examples: ["converting heat into energy", "matching patterns", "stimulating the immune system"] },
      ],
      examples: [
        { en: "The engine works by converting heat into mechanical energy.", bn: "ইঞ্জিনটি তাপকে যান্ত্রিক শক্তিতে রূপান্তরিত করে কাজ করে।", slotValues: { THING: "The engine", DOING: "converting heat into mechanical energy" }, topicArea: "science" },
        { en: "The algorithm works by matching patterns in large datasets.", bn: "অ্যালগরিদমটি বড় ডেটাসেটে প্যাটার্ন মিলিয়ে কাজ করে।", slotValues: { THING: "The algorithm", DOING: "matching patterns in large datasets" }, topicArea: "technology" },
        { en: "The vaccine works by stimulating the immune system.", bn: "টিকাটি রোগ প্রতিরোধ ব্যবস্থাকে উদ্দীপিত করে কাজ করে।", slotValues: { THING: "The vaccine", DOING: "stimulating the immune system" }, topicArea: "health" },
        { en: "Solar energy works by capturing sunlight and converting it to electricity.", bn: "সৌরশক্তি সূর্যালোক ধরে বিদ্যুতে রূপান্তরিত করে কাজ করে।", slotValues: { THING: "Solar energy", DOING: "capturing sunlight and converting it to electricity" }, topicArea: "environment" },
        { en: "The filter works by trapping particles larger than 0.1 microns.", bn: "ফিল্টারটি ০.১ মাইক্রনের চেয়ে বড় কণা আটকে কাজ করে।", slotValues: { THING: "The filter", DOING: "trapping particles larger than 0.1 microns" }, topicArea: "science" },
        { en: "Blockchain works by creating a decentralized ledger of transactions.", bn: "ব্লকচেইন লেনদেনের একটি বিকেন্দ্রীকৃত লেজার তৈরি করে কাজ করে।", slotValues: { THING: "Blockchain", DOING: "creating a decentralized ledger of transactions" }, topicArea: "technology" },
        { en: "The thermostat works by sensing temperature changes.", bn: "থার্মোস্ট্যাটটি তাপমাত্রা পরিবর্তন অনুভব করে কাজ করে।", slotValues: { THING: "The thermostat", DOING: "sensing temperature changes" }, topicArea: "technology" },
        { en: "The kidney works by filtering waste from the blood.", bn: "কিডনি রক্ত থেকে বর্জ্য ফিল্টার করে কাজ করে।", slotValues: { THING: "The kidney", DOING: "filtering waste from the blood" }, topicArea: "health" },
        { en: "Machine learning works by training models on labeled data.", bn: "মেশিন লার্নিং লেবেলকৃত ডেটায় মডেল প্রশিক্ষণ দিয়ে কাজ করে।", slotValues: { THING: "Machine learning", DOING: "training models on labeled data" }, topicArea: "technology" },
        { en: "A wind turbine works by converting wind energy into electricity.", bn: "একটি বায়ু টারবাইন বায়ু শক্তিকে বিদ্যুতে রূপান্তরিত করে কাজ করে।", slotValues: { THING: "A wind turbine", DOING: "converting wind energy into electricity" }, topicArea: "environment" },
        { en: "GPS works by communicating with satellites in orbit.", bn: "GPS কক্ষপথের স্যাটেলাইটের সাথে যোগাযোগ করে কাজ করে।", slotValues: { THING: "GPS", DOING: "communicating with satellites in orbit" }, topicArea: "technology" },
        { en: "Photosynthesis works by converting light energy into chemical energy.", bn: "সালোকসংশ্লেষণ আলোক শক্তিকে রাসায়নিক শক্তিতে রূপান্তরিত করে কাজ করে।", slotValues: { THING: "Photosynthesis", DOING: "converting light energy into chemical energy" }, topicArea: "science" },
        { en: "The search engine works by indexing web pages.", bn: "সার্চ ইঞ্জিনটি ওয়েব পেজ ইনডেক্স করে কাজ করে।", slotValues: { THING: "The search engine", DOING: "indexing web pages" }, topicArea: "technology" },
        { en: "An MRI works by using magnetic fields to create images of the body.", bn: "একটি MRI চৌম্বক ক্ষেত্র ব্যবহার করে শরীরের ছবি তৈরি করে কাজ করে।", slotValues: { THING: "An MRI", DOING: "using magnetic fields to create images of the body" }, topicArea: "health" },
        { en: "A water purifier works by removing bacteria and chemicals.", bn: "একটি পানি বিশোধনকারী ব্যাকটেরিয়া ও রাসায়নিক অপসারণ করে কাজ করে।", slotValues: { THING: "A water purifier", DOING: "removing bacteria and chemicals" }, topicArea: "environment" },
      ],
      formality: "formal", difficulty: "advanced",
      usageNote: "Explains the mechanism of how something operates. Common in technical descriptions.",
      usageNote_bn: "কোনো কিছু কীভাবে কাজ করে তার কৌশল ব্যাখ্যা করে। প্রযুক্তিগত বর্ণনায় সাধারণ।",
    },
    {
      id: "W13.4", formula: "The first step is to [ACTION]", formula_bn: "প্রথম ধাপ হলো [কাজ] করা",
      patternName: "Sequencing Steps", patternName_bn: "ধাপ সাজানো",
      slots: [
        { name: "ACTION", description: "The initial action in a sequence", description_bn: "ক্রমানুসারে প্রাথমিক কাজ", acceptedTypes: ["verb_phrase"], examples: ["identify the problem", "gather materials", "define the scope"] },
      ],
      examples: [
        { en: "The first step is to identify the problem clearly.", bn: "প্রথম ধাপ হলো সমস্যাটি স্পষ্টভাবে চিহ্নিত করা।", slotValues: { ACTION: "identify the problem clearly" }, topicArea: "work" },
        { en: "The first step is to gather all necessary materials.", bn: "প্রথম ধাপ হলো সব প্রয়োজনীয় উপকরণ সংগ্রহ করা।", slotValues: { ACTION: "gather all necessary materials" }, topicArea: "science" },
        { en: "The first step is to define the scope of the project.", bn: "প্রথম ধাপ হলো প্রকল্পের পরিধি নির্ধারণ করা।", slotValues: { ACTION: "define the scope of the project" }, topicArea: "work" },
        { en: "The first step is to conduct a needs assessment.", bn: "প্রথম ধাপ হলো একটি প্রয়োজন মূল্যায়ন পরিচালনা করা।", slotValues: { ACTION: "conduct a needs assessment" }, topicArea: "work" },
        { en: "The first step is to clean the surface thoroughly.", bn: "প্রথম ধাপ হলো পৃষ্ঠটি ভালোভাবে পরিষ্কার করা।", slotValues: { ACTION: "clean the surface thoroughly" }, topicArea: "science" },
        { en: "The first step is to create a hypothesis.", bn: "প্রথম ধাপ হলো একটি অনুমান তৈরি করা।", slotValues: { ACTION: "create a hypothesis" }, topicArea: "science" },
        { en: "The first step is to install the necessary software.", bn: "প্রথম ধাপ হলো প্রয়োজনীয় সফটওয়্যার ইনস্টল করা।", slotValues: { ACTION: "install the necessary software" }, topicArea: "technology" },
        { en: "The first step is to review the patient's medical history.", bn: "প্রথম ধাপ হলো রোগীর চিকিৎসা ইতিহাস পর্যালোচনা করা।", slotValues: { ACTION: "review the patient's medical history" }, topicArea: "health" },
        { en: "The first step is to set clear objectives.", bn: "প্রথম ধাপ হলো স্পষ্ট উদ্দেশ্য নির্ধারণ করা।", slotValues: { ACTION: "set clear objectives" }, topicArea: "work" },
        { en: "The first step is to select an appropriate sample.", bn: "প্রথম ধাপ হলো একটি উপযুক্ত নমুনা নির্বাচন করা।", slotValues: { ACTION: "select an appropriate sample" }, topicArea: "science" },
        { en: "The first step is to understand the requirements.", bn: "প্রথম ধাপ হলো প্রয়োজনীয়তাগুলো বোঝা।", slotValues: { ACTION: "understand the requirements" }, topicArea: "work" },
        { en: "The first step is to preheat the oven to 200 degrees.", bn: "প্রথম ধাপ হলো ওভেন ২০০ ডিগ্রিতে আগে থেকে গরম করা।", slotValues: { ACTION: "preheat the oven to 200 degrees" }, topicArea: "food" },
        { en: "The first step is to back up all existing data.", bn: "প্রথম ধাপ হলো সব বিদ্যমান ডেটার ব্যাকআপ নেওয়া।", slotValues: { ACTION: "back up all existing data" }, topicArea: "technology" },
        { en: "The first step is to consult with stakeholders.", bn: "প্রথম ধাপ হলো স্টেকহোল্ডারদের সাথে পরামর্শ করা।", slotValues: { ACTION: "consult with stakeholders" }, topicArea: "work" },
        { en: "The first step is to measure the initial variables.", bn: "প্রথম ধাপ হলো প্রাথমিক চলকগুলো পরিমাপ করা।", slotValues: { ACTION: "measure the initial variables" }, topicArea: "science" },
      ],
      formality: "formal", difficulty: "advanced",
      usageNote: "Used to begin describing a sequential process. Follow with 'The next step...', 'Then...', 'Finally...'.",
      usageNote_bn: "ক্রমানুক্রমিক প্রক্রিয়া বর্ণনা শুরু করতে ব্যবহৃত। পরে 'The next step...', 'Then...', 'Finally...' ব্যবহার করুন।",
    },
    {
      id: "W13.5", formula: "[THING] is converted into [THING]", formula_bn: "[বিষয়] [বিষয়]-এ রূপান্তরিত হয়",
      patternName: "Describing Conversion", patternName_bn: "রূপান্তর বর্ণনা",
      slots: [
        { name: "THING", description: "The input and output of a conversion", description_bn: "রূপান্তরের ইনপুট ও আউটপুট", acceptedTypes: ["noun", "noun_phrase"], examples: ["sunlight", "electricity", "raw materials", "finished products"] },
      ],
      examples: [
        { en: "Sunlight is converted into electricity by solar panels.", bn: "সোলার প্যানেল দ্বারা সূর্যালোক বিদ্যুতে রূপান্তরিত হয়।", slotValues: { THING: "Sunlight / electricity" }, topicArea: "environment" },
        { en: "Raw materials are converted into finished products.", bn: "কাঁচামাল সমাপ্ত পণ্যে রূপান্তরিত হয়।", slotValues: { THING: "Raw materials / finished products" }, topicArea: "work" },
        { en: "Chemical energy is converted into kinetic energy.", bn: "রাসায়নিক শক্তি গতিশক্তিতে রূপান্তরিত হয়।", slotValues: { THING: "Chemical energy / kinetic energy" }, topicArea: "science" },
        { en: "Sound waves are converted into electrical signals.", bn: "শব্দ তরঙ্গ বৈদ্যুতিক সংকেতে রূপান্তরিত হয়।", slotValues: { THING: "Sound waves / electrical signals" }, topicArea: "technology" },
        { en: "Glucose is converted into energy during cellular respiration.", bn: "কোষীয় শ্বসনের সময় গ্লুকোজ শক্তিতে রূপান্তরিত হয়।", slotValues: { THING: "Glucose / energy" }, topicArea: "science" },
        { en: "Wind energy is converted into mechanical power.", bn: "বায়ু শক্তি যান্ত্রিক শক্তিতে রূপান্তরিত হয়।", slotValues: { THING: "Wind energy / mechanical power" }, topicArea: "environment" },
        { en: "Data is converted into actionable insights.", bn: "ডেটা কার্যকর অন্তর্দৃষ্টিতে রূপান্তরিত হয়।", slotValues: { THING: "Data / actionable insights" }, topicArea: "technology" },
        { en: "Water is converted into steam at 100 degrees Celsius.", bn: "১০০ ডিগ্রি সেলসিয়াসে পানি বাষ্পে রূপান্তরিত হয়।", slotValues: { THING: "Water / steam" }, topicArea: "science" },
        { en: "Carbon dioxide is converted into oxygen by trees.", bn: "গাছ দ্বারা কার্বন ডাইঅক্সাইড অক্সিজেনে রূপান্তরিত হয়।", slotValues: { THING: "Carbon dioxide / oxygen" }, topicArea: "environment" },
        { en: "Analog signals are converted into digital format.", bn: "অ্যানালগ সংকেত ডিজিটাল ফর্ম্যাটে রূপান্তরিত হয়।", slotValues: { THING: "Analog signals / digital format" }, topicArea: "technology" },
        { en: "Food is converted into nutrients during digestion.", bn: "হজমের সময় খাদ্য পুষ্টিতে রূপান্তরিত হয়।", slotValues: { THING: "Food / nutrients" }, topicArea: "health" },
        { en: "Heat is converted into work in a steam engine.", bn: "বাষ্প ইঞ্জিনে তাপ কাজে রূপান্তরিত হয়।", slotValues: { THING: "Heat / work" }, topicArea: "science" },
        { en: "Waste products are converted into compost.", bn: "বর্জ্য পদার্থ কম্পোস্টে রূপান্তরিত হয়।", slotValues: { THING: "Waste products / compost" }, topicArea: "environment" },
        { en: "Nuclear energy is converted into thermal energy.", bn: "পারমাণবিক শক্তি তাপ শক্তিতে রূপান্তরিত হয়।", slotValues: { THING: "Nuclear energy / thermal energy" }, topicArea: "science" },
        { en: "Text is converted into speech by the software.", bn: "সফটওয়্যার দ্বারা টেক্সট কথায় রূপান্তরিত হয়।", slotValues: { THING: "Text / speech" }, topicArea: "technology" },
      ],
      formality: "formal", difficulty: "advanced",
      usageNote: "Common in scientific and technical writing to describe transformation processes.",
      usageNote_bn: "রূপান্তর প্রক্রিয়া বর্ণনা করতে বৈজ্ঞানিক ও প্রযুক্তিগত লেখায় সাধারণ।",
    },
  ],
};
