import { PatternCategory } from "@/types/pattern";

export const categoryW4: PatternCategory = {
  id: "W4",
  slug: "academic-possibility",
  name: "Academic Possibility & Probability",
  name_bn: "একাডেমিক সম্ভাবনা ও সম্ভাব্যতা",
  description:
    "Patterns for expressing possibility, probability, and likelihood in academic contexts",
  description_bn:
    "একাডেমিক প্রসঙ্গে সম্ভাবনা, সম্ভাব্যতা এবং সম্ভাবনা প্রকাশের প্যাটার্ন",
  icon: "🔬",
  group: "W",
  groupName: "Academic & Professional",
  groupName_bn: "একাডেমিক ও পেশাদার",
  difficulty: "advanced",
  patterns: [
    {
      id: "W4.1",
      formula: "It is possible that [CLAUSE]",
      formula_bn: "এটা সম্ভব যে [বাক্যাংশ]",
      patternName: "Expressing Possibility",
      patternName_bn: "সম্ভাবনা প্রকাশ",
      slots: [
        {
          name: "CLAUSE",
          description: "A statement about what might be true",
          description_bn: "কী সত্য হতে পারে সে সম্পর্কে একটি বিবৃতি",
          acceptedTypes: ["clause"],
          examples: ["the results are flawed", "other factors are involved", "the theory is incorrect"],
        },
      ],
      examples: [
        {
          en: "It is possible that the results are flawed.",
          bn: "এটা সম্ভব যে ফলাফলগুলো ত্রুটিপূর্ণ।",
          slotValues: { CLAUSE: "the results are flawed" },
          topicArea: "science",
        },
        {
          en: "It is possible that other factors are involved.",
          bn: "এটা সম্ভব যে অন্যান্য কারণ জড়িত।",
          slotValues: { CLAUSE: "other factors are involved" },
          topicArea: "science",
        },
        {
          en: "It is possible that the theory needs revision.",
          bn: "এটা সম্ভব যে তত্ত্বটির সংশোধন প্রয়োজন।",
          slotValues: { CLAUSE: "the theory needs revision" },
          topicArea: "science",
        },
        {
          en: "It is possible that the sample size was too small.",
          bn: "এটা সম্ভব যে নমুনার আকার খুব ছোট ছিল।",
          slotValues: { CLAUSE: "the sample size was too small" },
          topicArea: "science",
        },
        {
          en: "It is possible that climate change will accelerate.",
          bn: "এটা সম্ভব যে জলবায়ু পরিবর্তন ত্বরান্বিত হবে।",
          slotValues: { CLAUSE: "climate change will accelerate" },
          topicArea: "environment",
        },
        {
          en: "It is possible that the economy will recover by next year.",
          bn: "এটা সম্ভব যে আগামী বছরের মধ্যে অর্থনীতি পুনরুদ্ধার হবে।",
          slotValues: { CLAUSE: "the economy will recover by next year" },
          topicArea: "economics",
        },
        {
          en: "It is possible that the medication has side effects.",
          bn: "এটা সম্ভব যে ওষুধটির পার্শ্বপ্রতিক্রিয়া আছে।",
          slotValues: { CLAUSE: "the medication has side effects" },
          topicArea: "health",
        },
        {
          en: "It is possible that the data was misinterpreted.",
          bn: "এটা সম্ভব যে তথ্যটি ভুলভাবে ব্যাখ্যা করা হয়েছে।",
          slotValues: { CLAUSE: "the data was misinterpreted" },
          topicArea: "science",
        },
        {
          en: "It is possible that alternative methods would yield better results.",
          bn: "এটা সম্ভব যে বিকল্প পদ্ধতি ভালো ফলাফল দেবে।",
          slotValues: { CLAUSE: "alternative methods would yield better results" },
          topicArea: "science",
        },
        {
          en: "It is possible that the trend will reverse.",
          bn: "এটা সম্ভব যে প্রবণতাটি উল্টে যাবে।",
          slotValues: { CLAUSE: "the trend will reverse" },
          topicArea: "economics",
        },
        {
          en: "It is possible that cultural factors play a role.",
          bn: "এটা সম্ভব যে সাংস্কৃতিক কারণগুলো ভূমিকা রাখে।",
          slotValues: { CLAUSE: "cultural factors play a role" },
          topicArea: "education",
        },
        {
          en: "It is possible that the solution lies in education.",
          bn: "এটা সম্ভব যে সমাধান শিক্ষায় নিহিত।",
          slotValues: { CLAUSE: "the solution lies in education" },
          topicArea: "education",
        },
        {
          en: "It is possible that new evidence will emerge.",
          bn: "এটা সম্ভব যে নতুন প্রমাণ উঠে আসবে।",
          slotValues: { CLAUSE: "new evidence will emerge" },
          topicArea: "science",
        },
        {
          en: "It is possible that the policy will be revised.",
          bn: "এটা সম্ভব যে নীতিটি সংশোধন করা হবে।",
          slotValues: { CLAUSE: "the policy will be revised" },
          topicArea: "work",
        },
        {
          en: "It is possible that technology will solve this problem.",
          bn: "এটা সম্ভব যে প্রযুক্তি এই সমস্যার সমাধান করবে।",
          slotValues: { CLAUSE: "technology will solve this problem" },
          topicArea: "technology",
        },
      ],
      formality: "formal",
      difficulty: "advanced",
      usageNote:
        "A hedging expression common in academic writing to avoid overly strong claims.",
      usageNote_bn:
        "অতিরিক্ত শক্তিশালী দাবি এড়াতে একাডেমিক লেখায় সাধারণ একটি হেজিং অভিব্যক্তি।",
    },
    {
      id: "W4.2",
      formula: "It is probable that [CLAUSE]",
      formula_bn: "এটা সম্ভাব্য যে [বাক্যাংশ]",
      patternName: "Expressing Probability",
      patternName_bn: "সম্ভাব্যতা প্রকাশ",
      slots: [
        {
          name: "CLAUSE",
          description: "A statement that is likely true based on evidence",
          description_bn: "প্রমাণের ভিত্তিতে সম্ভবত সত্য একটি বিবৃতি",
          acceptedTypes: ["clause"],
          examples: ["the experiment will succeed", "there is a connection", "demand will increase"],
        },
      ],
      examples: [
        {
          en: "It is probable that the experiment will succeed.",
          bn: "এটা সম্ভাব্য যে পরীক্ষাটি সফল হবে।",
          slotValues: { CLAUSE: "the experiment will succeed" },
          topicArea: "science",
        },
        {
          en: "It is probable that there is a connection between the two variables.",
          bn: "এটা সম্ভাব্য যে দুটি চলকের মধ্যে একটি সংযোগ আছে।",
          slotValues: { CLAUSE: "there is a connection between the two variables" },
          topicArea: "science",
        },
        {
          en: "It is probable that demand will increase next quarter.",
          bn: "এটা সম্ভাব্য যে আগামী প্রান্তিকে চাহিদা বাড়বে।",
          slotValues: { CLAUSE: "demand will increase next quarter" },
          topicArea: "economics",
        },
        {
          en: "It is probable that the vaccine is effective.",
          bn: "এটা সম্ভাব্য যে টিকাটি কার্যকর।",
          slotValues: { CLAUSE: "the vaccine is effective" },
          topicArea: "health",
        },
        {
          en: "It is probable that early intervention reduces risk.",
          bn: "এটা সম্ভাব্য যে প্রাথমিক হস্তক্ষেপ ঝুঁকি কমায়।",
          slotValues: { CLAUSE: "early intervention reduces risk" },
          topicArea: "health",
        },
        {
          en: "It is probable that urbanization will continue.",
          bn: "এটা সম্ভাব্য যে নগরায়ণ অব্যাহত থাকবে।",
          slotValues: { CLAUSE: "urbanization will continue" },
          topicArea: "environment",
        },
        {
          en: "It is probable that the species will adapt.",
          bn: "এটা সম্ভাব্য যে প্রজাতিটি অভিযোজিত হবে।",
          slotValues: { CLAUSE: "the species will adapt" },
          topicArea: "science",
        },
        {
          en: "It is probable that renewable energy will replace fossil fuels.",
          bn: "এটা সম্ভাব্য যে নবায়নযোগ্য শক্তি জীবাশ্ম জ্বালানির জায়গা নেবে।",
          slotValues: { CLAUSE: "renewable energy will replace fossil fuels" },
          topicArea: "environment",
        },
        {
          en: "It is probable that the new policy will have positive effects.",
          bn: "এটা সম্ভাব্য যে নতুন নীতির ইতিবাচক প্রভাব থাকবে।",
          slotValues: { CLAUSE: "the new policy will have positive effects" },
          topicArea: "work",
        },
        {
          en: "It is probable that the findings can be replicated.",
          bn: "এটা সম্ভাব্য যে ফলাফলগুলো পুনরুৎপাদন করা যাবে।",
          slotValues: { CLAUSE: "the findings can be replicated" },
          topicArea: "science",
        },
        {
          en: "It is probable that AI will transform healthcare.",
          bn: "এটা সম্ভাব্য যে AI স্বাস্থ্যসেবা রূপান্তরিত করবে।",
          slotValues: { CLAUSE: "AI will transform healthcare" },
          topicArea: "technology",
        },
        {
          en: "It is probable that students perform better with smaller class sizes.",
          bn: "এটা সম্ভাব্য যে ছোট ক্লাসে শিক্ষার্থীরা ভালো পারফর্ম করে।",
          slotValues: { CLAUSE: "students perform better with smaller class sizes" },
          topicArea: "education",
        },
        {
          en: "It is probable that the correlation is not coincidental.",
          bn: "এটা সম্ভাব্য যে সম্পর্কটি কাকতালীয় নয়।",
          slotValues: { CLAUSE: "the correlation is not coincidental" },
          topicArea: "science",
        },
        {
          en: "It is probable that inflation will stabilize.",
          bn: "এটা সম্ভাব্য যে মুদ্রাস্ফীতি স্থিতিশীল হবে।",
          slotValues: { CLAUSE: "inflation will stabilize" },
          topicArea: "economics",
        },
        {
          en: "It is probable that the treatment group will show improvement.",
          bn: "এটা সম্ভাব্য যে চিকিৎসা গ্রুপ উন্নতি দেখাবে।",
          slotValues: { CLAUSE: "the treatment group will show improvement" },
          topicArea: "health",
        },
      ],
      formality: "very_formal",
      difficulty: "advanced",
      usageNote:
        "Stronger than 'possible' but still hedged. Used when evidence supports a claim but certainty is not absolute.",
      usageNote_bn:
        "'possible'-এর চেয়ে শক্তিশালী কিন্তু এখনও হেজড। প্রমাণ একটি দাবি সমর্থন করলে কিন্তু নিশ্চয়তা পরম না হলে ব্যবহৃত।",
    },
    {
      id: "W4.3",
      formula: "There is a likelihood that [CLAUSE]",
      formula_bn: "[বাক্যাংশ] হওয়ার সম্ভাবনা আছে",
      patternName: "Expressing Likelihood",
      patternName_bn: "সম্ভাবনা প্রকাশ",
      slots: [
        {
          name: "CLAUSE",
          description: "A statement about what is expected to happen",
          description_bn: "কী ঘটবে বলে প্রত্যাশিত সে সম্পর্কে একটি বিবৃতি",
          acceptedTypes: ["clause"],
          examples: ["the trend will continue", "outcomes will vary", "more data is needed"],
        },
      ],
      examples: [
        {
          en: "There is a likelihood that the trend will continue.",
          bn: "প্রবণতাটি অব্যাহত থাকার সম্ভাবনা আছে।",
          slotValues: { CLAUSE: "the trend will continue" },
          topicArea: "economics",
        },
        {
          en: "There is a strong likelihood that outcomes will vary by region.",
          bn: "অঞ্চলভেদে ফলাফল ভিন্ন হওয়ার প্রবল সম্ভাবনা আছে।",
          slotValues: { CLAUSE: "outcomes will vary by region" },
          topicArea: "science",
        },
        {
          en: "There is a likelihood that more data is needed.",
          bn: "আরও তথ্য প্রয়োজন হওয়ার সম্ভাবনা আছে।",
          slotValues: { CLAUSE: "more data is needed" },
          topicArea: "science",
        },
        {
          en: "There is a likelihood that the project will be delayed.",
          bn: "প্রকল্পটি বিলম্বিত হওয়ার সম্ভাবনা আছে।",
          slotValues: { CLAUSE: "the project will be delayed" },
          topicArea: "work",
        },
        {
          en: "There is a high likelihood that sea levels will rise.",
          bn: "সমুদ্রের স্তর বাড়ার উচ্চ সম্ভাবনা আছে।",
          slotValues: { CLAUSE: "sea levels will rise" },
          topicArea: "environment",
        },
        {
          en: "There is a likelihood that the hypothesis is correct.",
          bn: "অনুমানটি সঠিক হওয়ার সম্ভাবনা আছে।",
          slotValues: { CLAUSE: "the hypothesis is correct" },
          topicArea: "science",
        },
        {
          en: "There is a likelihood that new jobs will be created.",
          bn: "নতুন কর্মসংস্থান সৃষ্টি হওয়ার সম্ভাবনা আছে।",
          slotValues: { CLAUSE: "new jobs will be created" },
          topicArea: "work",
        },
        {
          en: "There is a likelihood that the disease will spread further.",
          bn: "রোগটি আরও ছড়িয়ে পড়ার সম্ভাবনা আছে।",
          slotValues: { CLAUSE: "the disease will spread further" },
          topicArea: "health",
        },
        {
          en: "There is a likelihood that costs will increase over time.",
          bn: "সময়ের সাথে খরচ বাড়ার সম্ভাবনা আছে।",
          slotValues: { CLAUSE: "costs will increase over time" },
          topicArea: "economics",
        },
        {
          en: "There is a likelihood that the law will be amended.",
          bn: "আইনটি সংশোধন হওয়ার সম্ভাবনা আছে।",
          slotValues: { CLAUSE: "the law will be amended" },
          topicArea: "education",
        },
        {
          en: "There is a likelihood that test scores will improve.",
          bn: "পরীক্ষার ফলাফল উন্নত হওয়ার সম্ভাবনা আছে।",
          slotValues: { CLAUSE: "test scores will improve" },
          topicArea: "education",
        },
        {
          en: "There is a likelihood that the market will stabilize.",
          bn: "বাজার স্থিতিশীল হওয়ার সম্ভাবনা আছে।",
          slotValues: { CLAUSE: "the market will stabilize" },
          topicArea: "economics",
        },
        {
          en: "There is a low likelihood that the error was intentional.",
          bn: "ভুলটি ইচ্ছাকৃত হওয়ার কম সম্ভাবনা আছে।",
          slotValues: { CLAUSE: "the error was intentional" },
          topicArea: "work",
        },
        {
          en: "There is a likelihood that technology will disrupt traditional industries.",
          bn: "প্রযুক্তি ঐতিহ্যবাহী শিল্পকে ব্যাহত করার সম্ভাবনা আছে।",
          slotValues: { CLAUSE: "technology will disrupt traditional industries" },
          topicArea: "technology",
        },
        {
          en: "There is a reasonable likelihood that the experiment can be replicated.",
          bn: "পরীক্ষাটি পুনরুৎপাদন করা যাওয়ার যুক্তিসঙ্গত সম্ভাবনা আছে।",
          slotValues: { CLAUSE: "the experiment can be replicated" },
          topicArea: "science",
        },
      ],
      formality: "very_formal",
      difficulty: "advanced",
      usageNote:
        "A formal academic way to express that something is expected based on evidence. Can be modified with 'strong', 'high', 'low', etc.",
      usageNote_bn:
        "প্রমাণের ভিত্তিতে কিছু প্রত্যাশিত বোঝাতে একটি আনুষ্ঠানিক একাডেমিক উপায়। 'strong', 'high', 'low' ইত্যাদি দিয়ে পরিবর্তন করা যায়।",
    },
    {
      id: "W4.4",
      formula: "It is conceivable that [CLAUSE]",
      formula_bn: "এটা কল্পনীয় যে [বাক্যাংশ]",
      patternName: "Expressing Conceivability",
      patternName_bn: "কল্পনীয়তা প্রকাশ",
      slots: [
        {
          name: "CLAUSE",
          description: "A hypothetical or theoretically possible scenario",
          description_bn: "একটি কাল্পনিক বা তত্ত্বগতভাবে সম্ভব পরিস্থিতি",
          acceptedTypes: ["clause"],
          examples: ["the model is incomplete", "a different approach could work", "the opposite is true"],
        },
      ],
      examples: [
        {
          en: "It is conceivable that the model is incomplete.",
          bn: "এটা কল্পনীয় যে মডেলটি অসম্পূর্ণ।",
          slotValues: { CLAUSE: "the model is incomplete" },
          topicArea: "science",
        },
        {
          en: "It is conceivable that a different approach could work better.",
          bn: "এটা কল্পনীয় যে একটি ভিন্ন পদ্ধতি ভালো কাজ করতে পারে।",
          slotValues: { CLAUSE: "a different approach could work better" },
          topicArea: "science",
        },
        {
          en: "It is conceivable that the opposite is true.",
          bn: "এটা কল্পনীয় যে বিপরীতটি সত্য।",
          slotValues: { CLAUSE: "the opposite is true" },
          topicArea: "science",
        },
        {
          en: "It is conceivable that humans will colonize Mars.",
          bn: "এটা কল্পনীয় যে মানুষ মঙ্গলে বসতি স্থাপন করবে।",
          slotValues: { CLAUSE: "humans will colonize Mars" },
          topicArea: "science",
        },
        {
          en: "It is conceivable that artificial intelligence could surpass human intelligence.",
          bn: "এটা কল্পনীয় যে কৃত্রিম বুদ্ধিমত্তা মানব বুদ্ধিমত্তাকে ছাড়িয়ে যেতে পারে।",
          slotValues: { CLAUSE: "artificial intelligence could surpass human intelligence" },
          topicArea: "technology",
        },
        {
          en: "It is conceivable that the cure already exists.",
          bn: "এটা কল্পনীয় যে প্রতিকার ইতিমধ্যেই বিদ্যমান।",
          slotValues: { CLAUSE: "the cure already exists" },
          topicArea: "health",
        },
        {
          en: "It is conceivable that the two events are unrelated.",
          bn: "এটা কল্পনীয় যে দুটি ঘটনা সম্পর্কহীন।",
          slotValues: { CLAUSE: "the two events are unrelated" },
          topicArea: "science",
        },
        {
          en: "It is conceivable that future generations will find solutions.",
          bn: "এটা কল্পনীয় যে ভবিষ্যৎ প্রজন্ম সমাধান খুঁজে পাবে।",
          slotValues: { CLAUSE: "future generations will find solutions" },
          topicArea: "environment",
        },
        {
          en: "It is conceivable that the entire framework needs rethinking.",
          bn: "এটা কল্পনীয় যে সম্পূর্ণ কাঠামোটি পুনর্বিবেচনা করা দরকার।",
          slotValues: { CLAUSE: "the entire framework needs rethinking" },
          topicArea: "science",
        },
        {
          en: "It is conceivable that economic growth can be sustainable.",
          bn: "এটা কল্পনীয় যে অর্থনৈতিক প্রবৃদ্ধি টেকসই হতে পারে।",
          slotValues: { CLAUSE: "economic growth can be sustainable" },
          topicArea: "economics",
        },
        {
          en: "It is conceivable that the study's limitations affected the results.",
          bn: "এটা কল্পনীয় যে গবেষণার সীমাবদ্ধতা ফলাফলকে প্রভাবিত করেছে।",
          slotValues: { CLAUSE: "the study's limitations affected the results" },
          topicArea: "science",
        },
        {
          en: "It is conceivable that remote learning will become the norm.",
          bn: "এটা কল্পনীয় যে দূরশিক্ষা স্বাভাবিক হয়ে যাবে।",
          slotValues: { CLAUSE: "remote learning will become the norm" },
          topicArea: "education",
        },
        {
          en: "It is conceivable that the drug has undiscovered benefits.",
          bn: "এটা কল্পনীয় যে ওষুধটির অনাবিষ্কৃত উপকারিতা আছে।",
          slotValues: { CLAUSE: "the drug has undiscovered benefits" },
          topicArea: "health",
        },
        {
          en: "It is conceivable that our understanding of the universe is incomplete.",
          bn: "এটা কল্পনীয় যে মহাবিশ্ব সম্পর্কে আমাদের বোধগম্যতা অসম্পূর্ণ।",
          slotValues: { CLAUSE: "our understanding of the universe is incomplete" },
          topicArea: "science",
        },
        {
          en: "It is conceivable that a breakthrough will happen soon.",
          bn: "এটা কল্পনীয় যে শীঘ্রই একটি অগ্রগতি ঘটবে।",
          slotValues: { CLAUSE: "a breakthrough will happen soon" },
          topicArea: "science",
        },
      ],
      formality: "very_formal",
      difficulty: "advanced",
      usageNote:
        "Used for more speculative possibilities. Weaker than 'probable' but acknowledges a scenario is within the realm of possibility.",
      usageNote_bn:
        "আরও অনুমানমূলক সম্ভাবনার জন্য ব্যবহৃত। 'probable'-এর চেয়ে দুর্বল কিন্তু একটি পরিস্থিতি সম্ভাবনার পরিসরের মধ্যে আছে তা স্বীকার করে।",
    },
    {
      id: "W4.5",
      formula: "Evidence suggests that [CLAUSE]",
      formula_bn: "প্রমাণ ইঙ্গিত করে যে [বাক্যাংশ]",
      patternName: "Evidence-Based Claim",
      patternName_bn: "প্রমাণ-ভিত্তিক দাবি",
      slots: [
        {
          name: "CLAUSE",
          description: "A claim supported by evidence",
          description_bn: "প্রমাণ দ্বারা সমর্থিত একটি দাবি",
          acceptedTypes: ["clause"],
          examples: ["regular exercise improves mental health", "the approach is effective", "there is a link"],
        },
      ],
      examples: [
        {
          en: "Evidence suggests that regular exercise improves mental health.",
          bn: "প্রমাণ ইঙ্গিত করে যে নিয়মিত ব্যায়াম মানসিক স্বাস্থ্যের উন্নতি করে।",
          slotValues: { CLAUSE: "regular exercise improves mental health" },
          topicArea: "health",
        },
        {
          en: "Evidence suggests that the approach is effective.",
          bn: "প্রমাণ ইঙ্গিত করে যে পদ্ধতিটি কার্যকর।",
          slotValues: { CLAUSE: "the approach is effective" },
          topicArea: "science",
        },
        {
          en: "Evidence suggests that there is a link between diet and disease.",
          bn: "প্রমাণ ইঙ্গিত করে যে খাদ্য ও রোগের মধ্যে একটি সংযোগ আছে।",
          slotValues: { CLAUSE: "there is a link between diet and disease" },
          topicArea: "health",
        },
        {
          en: "Evidence suggests that bilingual children develop cognitive advantages.",
          bn: "প্রমাণ ইঙ্গিত করে যে দ্বিভাষী শিশুরা জ্ঞানীয় সুবিধা অর্জন করে।",
          slotValues: { CLAUSE: "bilingual children develop cognitive advantages" },
          topicArea: "education",
        },
        {
          en: "Evidence suggests that sleep deprivation affects productivity.",
          bn: "প্রমাণ ইঙ্গিত করে যে ঘুমের অভাব উৎপাদনশীলতাকে প্রভাবিত করে।",
          slotValues: { CLAUSE: "sleep deprivation affects productivity" },
          topicArea: "health",
        },
        {
          en: "Evidence suggests that early education has long-term benefits.",
          bn: "প্রমাণ ইঙ্গিত করে যে প্রাথমিক শিক্ষার দীর্ঘমেয়াদী সুবিধা আছে।",
          slotValues: { CLAUSE: "early education has long-term benefits" },
          topicArea: "education",
        },
        {
          en: "Evidence suggests that green spaces improve well-being.",
          bn: "প্রমাণ ইঙ্গিত করে যে সবুজ স্থান সুস্থতার উন্নতি করে।",
          slotValues: { CLAUSE: "green spaces improve well-being" },
          topicArea: "environment",
        },
        {
          en: "Evidence suggests that the policy has reduced inequality.",
          bn: "প্রমাণ ইঙ্গিত করে যে নীতিটি বৈষম্য কমিয়েছে।",
          slotValues: { CLAUSE: "the policy has reduced inequality" },
          topicArea: "economics",
        },
        {
          en: "Evidence suggests that music therapy aids recovery.",
          bn: "প্রমাণ ইঙ্গিত করে যে সঙ্গীত থেরাপি সুস্থতায় সাহায্য করে।",
          slotValues: { CLAUSE: "music therapy aids recovery" },
          topicArea: "health",
        },
        {
          en: "Evidence suggests that deforestation accelerates climate change.",
          bn: "প্রমাণ ইঙ্গিত করে যে বন উজাড় জলবায়ু পরিবর্তনকে ত্বরান্বিত করে।",
          slotValues: { CLAUSE: "deforestation accelerates climate change" },
          topicArea: "environment",
        },
        {
          en: "Evidence suggests that flexible working hours increase satisfaction.",
          bn: "প্রমাণ ইঙ্গিত করে যে নমনীয় কাজের সময় সন্তুষ্টি বাড়ায়।",
          slotValues: { CLAUSE: "flexible working hours increase satisfaction" },
          topicArea: "work",
        },
        {
          en: "Evidence suggests that poverty is linked to poor health outcomes.",
          bn: "প্রমাণ ইঙ্গিত করে যে দারিদ্র্য খারাপ স্বাস্থ্য ফলাফলের সাথে যুক্ত।",
          slotValues: { CLAUSE: "poverty is linked to poor health outcomes" },
          topicArea: "health",
        },
        {
          en: "Evidence suggests that social media affects teenagers' self-esteem.",
          bn: "প্রমাণ ইঙ্গিত করে যে সোশ্যাল মিডিয়া কিশোরদের আত্মসম্মানকে প্রভাবিত করে।",
          slotValues: { CLAUSE: "social media affects teenagers' self-esteem" },
          topicArea: "technology",
        },
        {
          en: "Evidence suggests that the training program is successful.",
          bn: "প্রমাণ ইঙ্গিত করে যে প্রশিক্ষণ কর্মসূচিটি সফল।",
          slotValues: { CLAUSE: "the training program is successful" },
          topicArea: "work",
        },
        {
          en: "Evidence suggests that reading aloud benefits young learners.",
          bn: "প্রমাণ ইঙ্গিত করে যে জোরে পড়া তরুণ শিক্ষার্থীদের উপকার করে।",
          slotValues: { CLAUSE: "reading aloud benefits young learners" },
          topicArea: "education",
        },
      ],
      formality: "formal",
      difficulty: "advanced",
      usageNote:
        "One of the most important academic hedging phrases. Connects claims to evidence without absolute certainty.",
      usageNote_bn:
        "সবচেয়ে গুরুত্বপূর্ণ একাডেমিক হেজিং বাক্যাংশগুলোর একটি। পরম নিশ্চয়তা ছাড়াই দাবিকে প্রমাণের সাথে সংযুক্ত করে।",
    },
  ],
};
