import { PatternCategory } from "@/types/pattern";

export const categoryW6: PatternCategory = {
  id: "W6",
  slug: "academic-cause-effect",
  name: "Academic Cause & Effect",
  name_bn: "একাডেমিক কারণ ও ফলাফল",
  description:
    "Patterns for expressing causal relationships in academic writing and analysis",
  description_bn:
    "একাডেমিক লেখা ও বিশ্লেষণে কার্যকারণ সম্পর্ক প্রকাশের প্যাটার্ন",
  icon: "🔗",
  group: "W",
  groupName: "Academic & Professional",
  groupName_bn: "একাডেমিক ও পেশাদার",
  difficulty: "advanced",
  patterns: [
    {
      id: "W6.1",
      formula: "[THING] causes [THING]",
      formula_bn: "[বিষয়] [বিষয়]-এর কারণ হয়",
      patternName: "Direct Cause",
      patternName_bn: "প্রত্যক্ষ কারণ",
      slots: [
        {
          name: "THING",
          description: "The cause and effect (two different things)",
          description_bn: "কারণ এবং ফলাফল (দুটি ভিন্ন বিষয়)",
          acceptedTypes: ["noun", "noun_phrase", "gerund"],
          examples: ["pollution", "health problems", "deforestation", "flooding"],
        },
      ],
      examples: [
        { en: "Pollution causes health problems.", bn: "দূষণ স্বাস্থ্য সমস্যার কারণ হয়।", slotValues: { THING: "Pollution / health problems" }, topicArea: "health" },
        { en: "Deforestation causes flooding.", bn: "বন উজাড় বন্যার কারণ হয়।", slotValues: { THING: "Deforestation / flooding" }, topicArea: "environment" },
        { en: "Smoking causes lung cancer.", bn: "ধূমপান ফুসফুসের ক্যান্সারের কারণ হয়।", slotValues: { THING: "Smoking / lung cancer" }, topicArea: "health" },
        { en: "Poverty causes malnutrition.", bn: "দারিদ্র্য অপুষ্টির কারণ হয়।", slotValues: { THING: "Poverty / malnutrition" }, topicArea: "health" },
        { en: "Stress causes insomnia.", bn: "চাপ অনিদ্রার কারণ হয়।", slotValues: { THING: "Stress / insomnia" }, topicArea: "health" },
        { en: "Overfishing causes ecological imbalance.", bn: "অতিরিক্ত মাছ ধরা পরিবেশগত ভারসাম্যহীনতার কারণ হয়।", slotValues: { THING: "Overfishing / ecological imbalance" }, topicArea: "environment" },
        { en: "Inflation causes a decrease in purchasing power.", bn: "মুদ্রাস্ফীতি ক্রয়ক্ষমতা হ্রাসের কারণ হয়।", slotValues: { THING: "Inflation / a decrease in purchasing power" }, topicArea: "economics" },
        { en: "Lack of sleep causes poor concentration.", bn: "ঘুমের অভাব দুর্বল মনোযোগের কারণ হয়।", slotValues: { THING: "Lack of sleep / poor concentration" }, topicArea: "health" },
        { en: "Urbanization causes habitat destruction.", bn: "নগরায়ণ আবাসস্থল ধ্বংসের কারণ হয়।", slotValues: { THING: "Urbanization / habitat destruction" }, topicArea: "environment" },
        { en: "High unemployment causes social unrest.", bn: "উচ্চ বেকারত্ব সামাজিক অস্থিরতার কারণ হয়।", slotValues: { THING: "High unemployment / social unrest" }, topicArea: "economics" },
        { en: "Excessive screen time causes eye strain.", bn: "অতিরিক্ত স্ক্রিন টাইম চোখের ক্লান্তির কারণ হয়।", slotValues: { THING: "Excessive screen time / eye strain" }, topicArea: "health" },
        { en: "Climate change causes rising sea levels.", bn: "জলবায়ু পরিবর্তন সমুদ্রের স্তর বৃদ্ধির কারণ হয়।", slotValues: { THING: "Climate change / rising sea levels" }, topicArea: "environment" },
        { en: "Poor governance causes corruption.", bn: "দুর্বল শাসন দুর্নীতির কারণ হয়।", slotValues: { THING: "Poor governance / corruption" }, topicArea: "education" },
        { en: "Noise pollution causes hearing loss.", bn: "শব্দ দূষণ শ্রবণ ক্ষমতা হ্রাসের কারণ হয়।", slotValues: { THING: "Noise pollution / hearing loss" }, topicArea: "health" },
        { en: "Rapid industrialization causes environmental degradation.", bn: "দ্রুত শিল্পায়ন পরিবেশ অবক্ষয়ের কারণ হয়।", slotValues: { THING: "Rapid industrialization / environmental degradation" }, topicArea: "environment" },
      ],
      formality: "formal",
      difficulty: "advanced",
      usageNote: "A direct and simple way to express causation in academic writing.",
      usageNote_bn: "একাডেমিক লেখায় কার্যকারণ প্রকাশের একটি প্রত্যক্ষ ও সরল উপায়।",
    },
    {
      id: "W6.2",
      formula: "[THING] results from [THING]",
      formula_bn: "[বিষয়] [বিষয়] থেকে ফলাফল হয়",
      patternName: "Effect from Cause",
      patternName_bn: "কারণ থেকে ফলাফল",
      slots: [
        {
          name: "THING",
          description: "The effect and its cause",
          description_bn: "ফলাফল এবং এর কারণ",
          acceptedTypes: ["noun", "noun_phrase", "gerund"],
          examples: ["obesity", "overeating", "soil erosion", "deforestation"],
        },
      ],
      examples: [
        { en: "Obesity results from overeating and lack of exercise.", bn: "স্থূলতা অতিরিক্ত খাওয়া এবং ব্যায়ামের অভাব থেকে ফলাফল হয়।", slotValues: { THING: "Obesity / overeating and lack of exercise" }, topicArea: "health" },
        { en: "Soil erosion results from deforestation.", bn: "মাটি ক্ষয় বন উজাড় থেকে ফলাফল হয়।", slotValues: { THING: "Soil erosion / deforestation" }, topicArea: "environment" },
        { en: "Poverty results from unequal distribution of resources.", bn: "দারিদ্র্য সম্পদের অসম বন্টন থেকে ফলাফল হয়।", slotValues: { THING: "Poverty / unequal distribution of resources" }, topicArea: "economics" },
        { en: "Water scarcity results from overconsumption.", bn: "পানির সংকট অতিরিক্ত ব্যবহার থেকে ফলাফল হয়।", slotValues: { THING: "Water scarcity / overconsumption" }, topicArea: "environment" },
        { en: "Academic failure results from lack of preparation.", bn: "একাডেমিক ব্যর্থতা প্রস্তুতির অভাব থেকে ফলাফল হয়।", slotValues: { THING: "Academic failure / lack of preparation" }, topicArea: "education" },
        { en: "Traffic congestion results from poor urban planning.", bn: "যানজট দুর্বল নগর পরিকল্পনা থেকে ফলাফল হয়।", slotValues: { THING: "Traffic congestion / poor urban planning" }, topicArea: "daily_life" },
        { en: "Economic growth results from investment in infrastructure.", bn: "অর্থনৈতিক প্রবৃদ্ধি অবকাঠামোতে বিনিয়োগ থেকে ফলাফল হয়।", slotValues: { THING: "Economic growth / investment in infrastructure" }, topicArea: "economics" },
        { en: "Innovation results from creative thinking.", bn: "উদ্ভাবন সৃজনশীল চিন্তা থেকে ফলাফল হয়।", slotValues: { THING: "Innovation / creative thinking" }, topicArea: "work" },
        { en: "Burnout results from chronic workplace stress.", bn: "বার্নআউট দীর্ঘস্থায়ী কর্মক্ষেত্রের চাপ থেকে ফলাফল হয়।", slotValues: { THING: "Burnout / chronic workplace stress" }, topicArea: "work" },
        { en: "Cultural change results from globalization.", bn: "সাংস্কৃতিক পরিবর্তন বিশ্বায়ন থেকে ফলাফল হয়।", slotValues: { THING: "Cultural change / globalization" }, topicArea: "education" },
        { en: "Low productivity results from inadequate training.", bn: "কম উৎপাদনশীলতা অপর্যাপ্ত প্রশিক্ষণ থেকে ফলাফল হয়।", slotValues: { THING: "Low productivity / inadequate training" }, topicArea: "work" },
        { en: "Species extinction results from habitat loss.", bn: "প্রজাতির বিলুপ্তি আবাসস্থল হারানো থেকে ফলাফল হয়।", slotValues: { THING: "Species extinction / habitat loss" }, topicArea: "environment" },
        { en: "Improved health results from regular exercise.", bn: "উন্নত স্বাস্থ্য নিয়মিত ব্যায়াম থেকে ফলাফল হয়।", slotValues: { THING: "Improved health / regular exercise" }, topicArea: "health" },
        { en: "Social isolation results from excessive technology use.", bn: "সামাজিক বিচ্ছিন্নতা অতিরিক্ত প্রযুক্তি ব্যবহার থেকে ফলাফল হয়।", slotValues: { THING: "Social isolation / excessive technology use" }, topicArea: "technology" },
        { en: "High dropout rates result from financial difficulties.", bn: "উচ্চ ঝরে পড়ার হার আর্থিক সমস্যা থেকে ফলাফল হয়।", slotValues: { THING: "High dropout rates / financial difficulties" }, topicArea: "education" },
      ],
      formality: "formal",
      difficulty: "advanced",
      usageNote: "Emphasizes the effect first, then traces back to the cause. Useful in analytical writing.",
      usageNote_bn: "প্রথমে ফলাফলের উপর জোর দেয়, তারপর কারণে ফিরে যায়। বিশ্লেষণাত্মক লেখায় উপযোগী।",
    },
    {
      id: "W6.3",
      formula: "[THING] leads to [THING]",
      formula_bn: "[বিষয়] [বিষয়]-এর দিকে নিয়ে যায়",
      patternName: "Cause Leading to Effect",
      patternName_bn: "কারণ ফলাফলের দিকে নিয়ে যাওয়া",
      slots: [
        {
          name: "THING",
          description: "The cause and its resulting effect",
          description_bn: "কারণ এবং এর ফলাফল",
          acceptedTypes: ["noun", "noun_phrase", "gerund"],
          examples: ["education", "better opportunities", "corruption", "social distrust"],
        },
      ],
      examples: [
        { en: "Education leads to better opportunities.", bn: "শিক্ষা ভালো সুযোগের দিকে নিয়ে যায়।", slotValues: { THING: "Education / better opportunities" }, topicArea: "education" },
        { en: "Corruption leads to social distrust.", bn: "দুর্নীতি সামাজিক অবিশ্বাসের দিকে নিয়ে যায়।", slotValues: { THING: "Corruption / social distrust" }, topicArea: "education" },
        { en: "Poor nutrition leads to weakened immunity.", bn: "দুর্বল পুষ্টি দুর্বল রোগ প্রতিরোধের দিকে নিয়ে যায়।", slotValues: { THING: "Poor nutrition / weakened immunity" }, topicArea: "health" },
        { en: "Innovation leads to economic growth.", bn: "উদ্ভাবন অর্থনৈতিক প্রবৃদ্ধির দিকে নিয়ে যায়।", slotValues: { THING: "Innovation / economic growth" }, topicArea: "economics" },
        { en: "Lack of regulation leads to market instability.", bn: "নিয়ন্ত্রণের অভাব বাজার অস্থিতিশীলতার দিকে নিয়ে যায়।", slotValues: { THING: "Lack of regulation / market instability" }, topicArea: "economics" },
        { en: "Overuse of antibiotics leads to drug resistance.", bn: "অ্যান্টিবায়োটিকের অতিরিক্ত ব্যবহার ওষুধ প্রতিরোধের দিকে নিয়ে যায়।", slotValues: { THING: "Overuse of antibiotics / drug resistance" }, topicArea: "health" },
        { en: "Globalization leads to cultural exchange.", bn: "বিশ্বায়ন সাংস্কৃতিক বিনিময়ের দিকে নিয়ে যায়।", slotValues: { THING: "Globalization / cultural exchange" }, topicArea: "education" },
        { en: "Climate change leads to extreme weather events.", bn: "জলবায়ু পরিবর্তন চরম আবহাওয়া ঘটনার দিকে নিয়ে যায়।", slotValues: { THING: "Climate change / extreme weather events" }, topicArea: "environment" },
        { en: "Teamwork leads to better results.", bn: "দলগত কাজ ভালো ফলাফলের দিকে নিয়ে যায়।", slotValues: { THING: "Teamwork / better results" }, topicArea: "work" },
        { en: "Sedentary lifestyle leads to obesity.", bn: "বসে থাকা জীবনযাত্রা স্থূলতার দিকে নিয়ে যায়।", slotValues: { THING: "Sedentary lifestyle / obesity" }, topicArea: "health" },
        { en: "Investment in research leads to scientific breakthroughs.", bn: "গবেষণায় বিনিয়োগ বৈজ্ঞানিক অগ্রগতির দিকে নিয়ে যায়।", slotValues: { THING: "Investment in research / scientific breakthroughs" }, topicArea: "science" },
        { en: "Discrimination leads to social inequality.", bn: "বৈষম্য সামাজিক অসমতার দিকে নিয়ে যায়।", slotValues: { THING: "Discrimination / social inequality" }, topicArea: "education" },
        { en: "Technological advancement leads to job displacement.", bn: "প্রযুক্তিগত অগ্রগতি কর্মসংস্থান স্থানচ্যুতির দিকে নিয়ে যায়।", slotValues: { THING: "Technological advancement / job displacement" }, topicArea: "technology" },
        { en: "Early intervention leads to better patient outcomes.", bn: "প্রাথমিক হস্তক্ষেপ ভালো রোগীর ফলাফলের দিকে নিয়ে যায়।", slotValues: { THING: "Early intervention / better patient outcomes" }, topicArea: "health" },
        { en: "Deregulation leads to increased competition.", bn: "নিয়ন্ত্রণহীনতা বর্ধিত প্রতিযোগিতার দিকে নিয়ে যায়।", slotValues: { THING: "Deregulation / increased competition" }, topicArea: "economics" },
      ],
      formality: "formal",
      difficulty: "advanced",
      usageNote: "One of the most versatile cause-effect connectors in academic English.",
      usageNote_bn: "একাডেমিক ইংরেজিতে সবচেয়ে বহুমুখী কারণ-ফলাফল সংযোগকারীগুলোর একটি।",
    },
    {
      id: "W6.4",
      formula: "As a consequence of [THING], [CLAUSE]",
      formula_bn: "[বিষয়]-এর ফলস্বরূপ, [বাক্যাংশ]",
      patternName: "Consequence Expression",
      patternName_bn: "পরিণতি প্রকাশ",
      slots: [
        {
          name: "THING",
          description: "The cause or event",
          description_bn: "কারণ বা ঘটনা",
          acceptedTypes: ["noun", "noun_phrase", "gerund"],
          examples: ["the pandemic", "rapid industrialization", "the new policy"],
        },
        {
          name: "CLAUSE",
          description: "The resulting consequence",
          description_bn: "ফলস্বরূপ পরিণতি",
          acceptedTypes: ["clause"],
          examples: ["millions lost their jobs", "air quality deteriorated", "the economy slowed down"],
        },
      ],
      examples: [
        { en: "As a consequence of the pandemic, millions lost their jobs.", bn: "মহামারীর ফলস্বরূপ, লক্ষ লক্ষ মানুষ চাকরি হারিয়েছে।", slotValues: { THING: "the pandemic", CLAUSE: "millions lost their jobs" }, topicArea: "economics" },
        { en: "As a consequence of rapid industrialization, air quality deteriorated.", bn: "দ্রুত শিল্পায়নের ফলস্বরূপ, বায়ুর মান খারাপ হয়েছে।", slotValues: { THING: "rapid industrialization", CLAUSE: "air quality deteriorated" }, topicArea: "environment" },
        { en: "As a consequence of the new policy, enrollment increased.", bn: "নতুন নীতির ফলস্বরূপ, ভর্তি বেড়েছে।", slotValues: { THING: "the new policy", CLAUSE: "enrollment increased" }, topicArea: "education" },
        { en: "As a consequence of deforestation, many species became endangered.", bn: "বন উজাড়ের ফলস্বরূপ, অনেক প্রজাতি বিপন্ন হয়েছে।", slotValues: { THING: "deforestation", CLAUSE: "many species became endangered" }, topicArea: "environment" },
        { en: "As a consequence of globalization, local businesses face more competition.", bn: "বিশ্বায়নের ফলস্বরূপ, স্থানীয় ব্যবসা আরও প্রতিযোগিতার সম্মুখীন।", slotValues: { THING: "globalization", CLAUSE: "local businesses face more competition" }, topicArea: "economics" },
        { en: "As a consequence of the earthquake, thousands were displaced.", bn: "ভূমিকম্পের ফলস্বরূপ, হাজার হাজার মানুষ বাস্তুচ্যুত হয়েছে।", slotValues: { THING: "the earthquake", CLAUSE: "thousands were displaced" }, topicArea: "environment" },
        { en: "As a consequence of budget cuts, research funding was reduced.", bn: "বাজেট কাটছাঁটের ফলস্বরূপ, গবেষণা তহবিল হ্রাস পেয়েছে।", slotValues: { THING: "budget cuts", CLAUSE: "research funding was reduced" }, topicArea: "science" },
        { en: "As a consequence of automation, many manual jobs disappeared.", bn: "স্বয়ংক্রিয়করণের ফলস্বরূপ, অনেক ম্যানুয়াল কাজ হারিয়ে গেছে।", slotValues: { THING: "automation", CLAUSE: "many manual jobs disappeared" }, topicArea: "work" },
        { en: "As a consequence of poor hygiene, diseases spread rapidly.", bn: "দুর্বল স্বাস্থ্যবিধির ফলস্বরূপ, রোগ দ্রুত ছড়িয়ে পড়ে।", slotValues: { THING: "poor hygiene", CLAUSE: "diseases spread rapidly" }, topicArea: "health" },
        { en: "As a consequence of rising tuition fees, student debt has increased.", bn: "বাড়তি টিউশন ফির ফলস্বরূপ, শিক্ষার্থী ঋণ বেড়েছে।", slotValues: { THING: "rising tuition fees", CLAUSE: "student debt has increased" }, topicArea: "education" },
        { en: "As a consequence of social media, information spreads faster than ever.", bn: "সোশ্যাল মিডিয়ার ফলস্বরূপ, তথ্য আগের চেয়ে দ্রুত ছড়ায়।", slotValues: { THING: "social media", CLAUSE: "information spreads faster than ever" }, topicArea: "technology" },
        { en: "As a consequence of the war, the economy collapsed.", bn: "যুদ্ধের ফলস্বরূপ, অর্থনীতি ভেঙে পড়েছে।", slotValues: { THING: "the war", CLAUSE: "the economy collapsed" }, topicArea: "economics" },
        { en: "As a consequence of overpopulation, resources are strained.", bn: "অতিরিক্ত জনসংখ্যার ফলস্বরূপ, সম্পদ চাপে পড়েছে।", slotValues: { THING: "overpopulation", CLAUSE: "resources are strained" }, topicArea: "environment" },
        { en: "As a consequence of the reforms, healthcare access improved.", bn: "সংস্কারের ফলস্বরূপ, স্বাস্থ্যসেবা প্রবেশাধিকার উন্নত হয়েছে।", slotValues: { THING: "the reforms", CLAUSE: "healthcare access improved" }, topicArea: "health" },
        { en: "As a consequence of climate change, harvests have declined.", bn: "জলবায়ু পরিবর্তনের ফলস্বরূপ, ফসল হ্রাস পেয়েছে।", slotValues: { THING: "climate change", CLAUSE: "harvests have declined" }, topicArea: "environment" },
      ],
      formality: "very_formal",
      difficulty: "advanced",
      usageNote: "A very formal way to show cause and effect. Common in academic essays and research papers.",
      usageNote_bn: "কারণ ও ফলাফল দেখানোর একটি অত্যন্ত আনুষ্ঠানিক উপায়। একাডেমিক প্রবন্ধ ও গবেষণা পত্রে সাধারণ।",
    },
    {
      id: "W6.5",
      formula: "[THING] contributes to [THING]",
      formula_bn: "[বিষয়] [বিষয়]-এ অবদান রাখে",
      patternName: "Contributing Factor",
      patternName_bn: "অবদানকারী কারণ",
      slots: [
        {
          name: "THING",
          description: "The contributing factor and the outcome",
          description_bn: "অবদানকারী কারণ এবং ফলাফল",
          acceptedTypes: ["noun", "noun_phrase", "gerund"],
          examples: ["exercise", "good health", "social media", "misinformation"],
        },
      ],
      examples: [
        { en: "Exercise contributes to good health.", bn: "ব্যায়াম ভালো স্বাস্থ্যে অবদান রাখে।", slotValues: { THING: "Exercise / good health" }, topicArea: "health" },
        { en: "Social media contributes to the spread of misinformation.", bn: "সোশ্যাল মিডিয়া ভুল তথ্য ছড়ানোতে অবদান রাখে।", slotValues: { THING: "Social media / the spread of misinformation" }, topicArea: "technology" },
        { en: "Education contributes to social mobility.", bn: "শিক্ষা সামাজিক গতিশীলতায় অবদান রাখে।", slotValues: { THING: "Education / social mobility" }, topicArea: "education" },
        { en: "Tourism contributes to the local economy.", bn: "পর্যটন স্থানীয় অর্থনীতিতে অবদান রাখে।", slotValues: { THING: "Tourism / the local economy" }, topicArea: "economics" },
        { en: "Air pollution contributes to global warming.", bn: "বায়ু দূষণ বৈশ্বিক উষ্ণায়নে অবদান রাখে।", slotValues: { THING: "Air pollution / global warming" }, topicArea: "environment" },
        { en: "Good leadership contributes to team success.", bn: "ভালো নেতৃত্ব দলগত সাফল্যে অবদান রাখে।", slotValues: { THING: "Good leadership / team success" }, topicArea: "work" },
        { en: "Research contributes to scientific progress.", bn: "গবেষণা বৈজ্ঞানিক অগ্রগতিতে অবদান রাখে।", slotValues: { THING: "Research / scientific progress" }, topicArea: "science" },
        { en: "Fast food contributes to the obesity epidemic.", bn: "ফাস্ট ফুড স্থূলতা মহামারীতে অবদান রাখে।", slotValues: { THING: "Fast food / the obesity epidemic" }, topicArea: "health" },
        { en: "Reading contributes to language development.", bn: "পড়া ভাষা বিকাশে অবদান রাখে।", slotValues: { THING: "Reading / language development" }, topicArea: "education" },
        { en: "Volunteer work contributes to community development.", bn: "স্বেচ্ছাসেবী কাজ সম্প্রদায় উন্নয়নে অবদান রাখে।", slotValues: { THING: "Volunteer work / community development" }, topicArea: "daily_life" },
        { en: "Technology contributes to increased productivity.", bn: "প্রযুক্তি বর্ধিত উৎপাদনশীলতায় অবদান রাখে।", slotValues: { THING: "Technology / increased productivity" }, topicArea: "work" },
        { en: "Adequate sleep contributes to better cognitive function.", bn: "পর্যাপ্ত ঘুম ভালো জ্ঞানীয় কার্যকারিতায় অবদান রাখে।", slotValues: { THING: "Adequate sleep / better cognitive function" }, topicArea: "health" },
        { en: "Cultural diversity contributes to creativity.", bn: "সাংস্কৃতিক বৈচিত্র্য সৃজনশীলতায় অবদান রাখে।", slotValues: { THING: "Cultural diversity / creativity" }, topicArea: "work" },
        { en: "Renewable energy contributes to reducing carbon emissions.", bn: "নবায়নযোগ্য শক্তি কার্বন নির্গমন হ্রাসে অবদান রাখে।", slotValues: { THING: "Renewable energy / reducing carbon emissions" }, topicArea: "environment" },
        { en: "Parental support contributes to a child's academic success.", bn: "পিতামাতার সমর্থন সন্তানের একাডেমিক সাফল্যে অবদান রাখে।", slotValues: { THING: "Parental support / a child's academic success" }, topicArea: "education" },
      ],
      formality: "formal",
      difficulty: "advanced",
      usageNote: "Softer than 'causes' - indicates a factor is one of several contributors to an outcome.",
      usageNote_bn: "'causes'-এর চেয়ে নরম - নির্দেশ করে যে একটি কারণ ফলাফলের বেশ কয়েকটি অবদানকারীর একটি।",
    },
  ],
};
