import { PatternCategory } from "@/types/pattern";

export const categoryW7: PatternCategory = {
  id: "W7",
  slug: "making-generalizations",
  name: "Making Generalizations",
  name_bn: "সাধারণীকরণ করা",
  description:
    "Academic patterns for making broad statements and generalizations based on evidence",
  description_bn:
    "প্রমাণের ভিত্তিতে বিস্তৃত বিবৃতি ও সাধারণীকরণ করার একাডেমিক প্যাটার্ন",
  icon: "🌐",
  group: "W",
  groupName: "Academic & Professional",
  groupName_bn: "একাডেমিক ও পেশাদার",
  difficulty: "advanced",
  patterns: [
    {
      id: "W7.1",
      formula: "[THINGS] tend to [ACTION]",
      formula_bn: "[বিষয়গুলো] [কাজ] করতে থাকে",
      patternName: "General Tendency",
      patternName_bn: "সাধারণ প্রবণতা",
      slots: [
        { name: "THINGS", description: "The group or category being described", description_bn: "যে গোষ্ঠী বা বিভাগ বর্ণনা করা হচ্ছে", acceptedTypes: ["noun", "noun_phrase"], examples: ["students", "older adults", "developing countries"] },
        { name: "ACTION", description: "The typical behavior or characteristic", description_bn: "সাধারণ আচরণ বা বৈশিষ্ট্য", acceptedTypes: ["verb_phrase"], examples: ["perform better", "prefer stability", "rely on agriculture"] },
      ],
      examples: [
        { en: "Students tend to perform better with regular feedback.", bn: "শিক্ষার্থীরা নিয়মিত প্রতিক্রিয়ায় ভালো পারফর্ম করতে থাকে।", slotValues: { THINGS: "Students", ACTION: "perform better with regular feedback" }, topicArea: "education" },
        { en: "Older adults tend to prefer stability over change.", bn: "বয়স্ক ব্যক্তিরা পরিবর্তনের চেয়ে স্থিতিশীলতা পছন্দ করতে থাকে।", slotValues: { THINGS: "Older adults", ACTION: "prefer stability over change" }, topicArea: "daily_life" },
        { en: "Developing countries tend to rely on agriculture.", bn: "উন্নয়নশীল দেশগুলো কৃষির উপর নির্ভর করতে থাকে।", slotValues: { THINGS: "Developing countries", ACTION: "rely on agriculture" }, topicArea: "economics" },
        { en: "Children tend to learn languages faster than adults.", bn: "শিশুরা প্রাপ্তবয়স্কদের চেয়ে দ্রুত ভাষা শিখতে থাকে।", slotValues: { THINGS: "Children", ACTION: "learn languages faster than adults" }, topicArea: "education" },
        { en: "Companies tend to invest more in R&D during economic booms.", bn: "কোম্পানিগুলো অর্থনৈতিক সমৃদ্ধির সময় R&D-তে বেশি বিনিয়োগ করতে থাকে।", slotValues: { THINGS: "Companies", ACTION: "invest more in R&D during economic booms" }, topicArea: "economics" },
        { en: "People tend to resist change initially.", bn: "মানুষ প্রাথমিকভাবে পরিবর্তনে প্রতিরোধ করতে থাকে।", slotValues: { THINGS: "People", ACTION: "resist change initially" }, topicArea: "daily_life" },
        { en: "Urban areas tend to have better healthcare facilities.", bn: "শহরাঞ্চলে ভালো স্বাস্থ্যসেবা সুবিধা থাকতে থাকে।", slotValues: { THINGS: "Urban areas", ACTION: "have better healthcare facilities" }, topicArea: "health" },
        { en: "Researchers tend to use quantitative methods in this field.", bn: "গবেষকরা এই ক্ষেত্রে পরিমাণগত পদ্ধতি ব্যবহার করতে থাকে।", slotValues: { THINGS: "Researchers", ACTION: "use quantitative methods in this field" }, topicArea: "science" },
        { en: "Women tend to live longer than men.", bn: "নারীরা পুরুষদের তুলনায় বেশি দিন বাঁচতে থাকে।", slotValues: { THINGS: "Women", ACTION: "live longer than men" }, topicArea: "health" },
        { en: "Small businesses tend to struggle with cash flow.", bn: "ছোট ব্যবসাগুলো নগদ প্রবাহ নিয়ে সংগ্রাম করতে থাকে।", slotValues: { THINGS: "Small businesses", ACTION: "struggle with cash flow" }, topicArea: "work" },
        { en: "Introverts tend to prefer working alone.", bn: "অন্তর্মুখী ব্যক্তিরা একা কাজ করতে পছন্দ করতে থাকে।", slotValues: { THINGS: "Introverts", ACTION: "prefer working alone" }, topicArea: "work" },
        { en: "Economies tend to grow faster after recessions.", bn: "মন্দার পরে অর্থনীতি দ্রুত বাড়তে থাকে।", slotValues: { THINGS: "Economies", ACTION: "grow faster after recessions" }, topicArea: "economics" },
        { en: "Tropical regions tend to have higher biodiversity.", bn: "গ্রীষ্মমণ্ডলীয় অঞ্চলে উচ্চতর জীববৈচিত্র্য থাকতে থাকে।", slotValues: { THINGS: "Tropical regions", ACTION: "have higher biodiversity" }, topicArea: "environment" },
        { en: "New employees tend to need more guidance.", bn: "নতুন কর্মীদের বেশি নির্দেশনা প্রয়োজন হতে থাকে।", slotValues: { THINGS: "New employees", ACTION: "need more guidance" }, topicArea: "work" },
        { en: "Educated populations tend to have lower birth rates.", bn: "শিক্ষিত জনগোষ্ঠীতে জন্মহার কম থাকতে থাকে।", slotValues: { THINGS: "Educated populations", ACTION: "have lower birth rates" }, topicArea: "education" },
      ],
      formality: "formal",
      difficulty: "advanced",
      usageNote: "A hedged generalization that avoids absolute claims. Very common in academic writing.",
      usageNote_bn: "একটি হেজড সাধারণীকরণ যা পরম দাবি এড়ায়। একাডেমিক লেখায় অত্যন্ত সাধারণ।",
    },
    {
      id: "W7.2",
      formula: "As a rule, [CLAUSE]",
      formula_bn: "নিয়ম হিসেবে, [বাক্যাংশ]",
      patternName: "General Rule",
      patternName_bn: "সাধারণ নিয়ম",
      slots: [
        { name: "CLAUSE", description: "A general statement that is usually true", description_bn: "একটি সাধারণ বিবৃতি যা সাধারণত সত্য", acceptedTypes: ["clause"], examples: ["larger companies have more resources", "democracies are more stable", "practice improves performance"] },
      ],
      examples: [
        { en: "As a rule, larger companies have more resources for research.", bn: "নিয়ম হিসেবে, বড় কোম্পানিগুলোর গবেষণার জন্য আরও সম্পদ থাকে।", slotValues: { CLAUSE: "larger companies have more resources for research" }, topicArea: "work" },
        { en: "As a rule, regular practice improves performance.", bn: "নিয়ম হিসেবে, নিয়মিত অনুশীলন কর্মক্ষমতা উন্নত করে।", slotValues: { CLAUSE: "regular practice improves performance" }, topicArea: "education" },
        { en: "As a rule, prevention is cheaper than treatment.", bn: "নিয়ম হিসেবে, প্রতিরোধ চিকিৎসার চেয়ে সস্তা।", slotValues: { CLAUSE: "prevention is cheaper than treatment" }, topicArea: "health" },
        { en: "As a rule, diversified portfolios are less risky.", bn: "নিয়ম হিসেবে, বৈচিত্র্যপূর্ণ পোর্টফোলিও কম ঝুঁকিপূর্ণ।", slotValues: { CLAUSE: "diversified portfolios are less risky" }, topicArea: "economics" },
        { en: "As a rule, higher education leads to higher income.", bn: "নিয়ম হিসেবে, উচ্চ শিক্ষা বেশি আয়ের দিকে নিয়ে যায়।", slotValues: { CLAUSE: "higher education leads to higher income" }, topicArea: "education" },
        { en: "As a rule, early intervention yields better outcomes.", bn: "নিয়ম হিসেবে, প্রাথমিক হস্তক্ষেপ ভালো ফলাফল দেয়।", slotValues: { CLAUSE: "early intervention yields better outcomes" }, topicArea: "health" },
        { en: "As a rule, transparency builds trust.", bn: "নিয়ম হিসেবে, স্বচ্ছতা আস্থা তৈরি করে।", slotValues: { CLAUSE: "transparency builds trust" }, topicArea: "work" },
        { en: "As a rule, warmer climates support greater biodiversity.", bn: "নিয়ম হিসেবে, উষ্ণতর জলবায়ু বৃহত্তর জীববৈচিত্র্য সমর্থন করে।", slotValues: { CLAUSE: "warmer climates support greater biodiversity" }, topicArea: "environment" },
        { en: "As a rule, children need at least 10 hours of sleep.", bn: "নিয়ম হিসেবে, শিশুদের কমপক্ষে ১০ ঘন্টা ঘুম প্রয়োজন।", slotValues: { CLAUSE: "children need at least 10 hours of sleep" }, topicArea: "health" },
        { en: "As a rule, peer review improves research quality.", bn: "নিয়ম হিসেবে, পিয়ার রিভিউ গবেষণার মান উন্নত করে।", slotValues: { CLAUSE: "peer review improves research quality" }, topicArea: "science" },
        { en: "As a rule, first impressions are formed within seconds.", bn: "নিয়ম হিসেবে, প্রথম ধারণা সেকেন্ডের মধ্যে তৈরি হয়।", slotValues: { CLAUSE: "first impressions are formed within seconds" }, topicArea: "daily_life" },
        { en: "As a rule, active learning is more effective than passive learning.", bn: "নিয়ম হিসেবে, সক্রিয় শিক্ষা নিষ্ক্রিয় শিক্ষার চেয়ে বেশি কার্যকর।", slotValues: { CLAUSE: "active learning is more effective than passive learning" }, topicArea: "education" },
        { en: "As a rule, rural areas have less access to technology.", bn: "নিয়ম হিসেবে, গ্রামীণ এলাকায় প্রযুক্তিতে কম অ্যাক্সেস থাকে।", slotValues: { CLAUSE: "rural areas have less access to technology" }, topicArea: "technology" },
        { en: "As a rule, complex problems require collaborative solutions.", bn: "নিয়ম হিসেবে, জটিল সমস্যার সমবায়ী সমাধান প্রয়োজন।", slotValues: { CLAUSE: "complex problems require collaborative solutions" }, topicArea: "work" },
        { en: "As a rule, healthy ecosystems are more resilient.", bn: "নিয়ম হিসেবে, স্বাস্থ্যকর বাস্তুতন্ত্র আরও স্থিতিস্থাপক।", slotValues: { CLAUSE: "healthy ecosystems are more resilient" }, topicArea: "environment" },
      ],
      formality: "formal",
      difficulty: "advanced",
      usageNote: "Introduces a general principle while implying there may be exceptions.",
      usageNote_bn: "একটি সাধারণ নীতি পরিচয় করায় এবং ব্যতিক্রম থাকতে পারে বোঝায়।",
    },
    {
      id: "W7.3",
      formula: "In most cases, [CLAUSE]",
      formula_bn: "বেশিরভাগ ক্ষেত্রে, [বাক্যাংশ]",
      patternName: "Majority Pattern",
      patternName_bn: "সংখ্যাগরিষ্ঠ প্যাটার্ন",
      slots: [
        { name: "CLAUSE", description: "A statement true for the majority", description_bn: "সংখ্যাগরিষ্ঠের জন্য সত্য একটি বিবৃতি", acceptedTypes: ["clause"], examples: ["treatment is successful", "students pass the exam", "the method works well"] },
      ],
      examples: [
        { en: "In most cases, the treatment is successful.", bn: "বেশিরভাগ ক্ষেত্রে, চিকিৎসা সফল।", slotValues: { CLAUSE: "the treatment is successful" }, topicArea: "health" },
        { en: "In most cases, students pass the final exam.", bn: "বেশিরভাগ ক্ষেত্রে, শিক্ষার্থীরা চূড়ান্ত পরীক্ষায় পাশ করে।", slotValues: { CLAUSE: "students pass the final exam" }, topicArea: "education" },
        { en: "In most cases, the method produces reliable results.", bn: "বেশিরভাগ ক্ষেত্রে, পদ্ধতিটি নির্ভরযোগ্য ফলাফল তৈরি করে।", slotValues: { CLAUSE: "the method produces reliable results" }, topicArea: "science" },
        { en: "In most cases, companies benefit from investing in training.", bn: "বেশিরভাগ ক্ষেত্রে, কোম্পানিগুলো প্রশিক্ষণে বিনিয়োগ থেকে উপকৃত হয়।", slotValues: { CLAUSE: "companies benefit from investing in training" }, topicArea: "work" },
        { en: "In most cases, early detection improves survival rates.", bn: "বেশিরভাগ ক্ষেত্রে, প্রাথমিক শনাক্তকরণ বেঁচে থাকার হার উন্নত করে।", slotValues: { CLAUSE: "early detection improves survival rates" }, topicArea: "health" },
        { en: "In most cases, negotiation is preferable to litigation.", bn: "বেশিরভাগ ক্ষেত্রে, মামলার চেয়ে আলোচনা ভালো।", slotValues: { CLAUSE: "negotiation is preferable to litigation" }, topicArea: "work" },
        { en: "In most cases, renewable energy is cost-effective in the long run.", bn: "বেশিরভাগ ক্ষেত্রে, নবায়নযোগ্য শক্তি দীর্ঘমেয়াদে সাশ্রয়ী।", slotValues: { CLAUSE: "renewable energy is cost-effective in the long run" }, topicArea: "environment" },
        { en: "In most cases, patients recover within two weeks.", bn: "বেশিরভাগ ক্ষেত্রে, রোগীরা দুই সপ্তাহের মধ্যে সুস্থ হয়।", slotValues: { CLAUSE: "patients recover within two weeks" }, topicArea: "health" },
        { en: "In most cases, a balanced diet provides sufficient nutrients.", bn: "বেশিরভাগ ক্ষেত্রে, সুষম খাদ্য পর্যাপ্ত পুষ্টি সরবরাহ করে।", slotValues: { CLAUSE: "a balanced diet provides sufficient nutrients" }, topicArea: "food" },
        { en: "In most cases, the hypothesis is supported by the data.", bn: "বেশিরভাগ ক্ষেত্রে, অনুমানটি তথ্য দ্বারা সমর্থিত।", slotValues: { CLAUSE: "the hypothesis is supported by the data" }, topicArea: "science" },
        { en: "In most cases, democratic systems are more stable.", bn: "বেশিরভাগ ক্ষেত্রে, গণতান্ত্রিক ব্যবস্থা আরও স্থিতিশীল।", slotValues: { CLAUSE: "democratic systems are more stable" }, topicArea: "education" },
        { en: "In most cases, mediation resolves disputes faster.", bn: "বেশিরভাগ ক্ষেত্রে, মধ্যস্থতা দ্রুত বিরোধ নিষ্পত্তি করে।", slotValues: { CLAUSE: "mediation resolves disputes faster" }, topicArea: "work" },
        { en: "In most cases, children benefit from bilingual education.", bn: "বেশিরভাগ ক্ষেত্রে, শিশুরা দ্বিভাষিক শিক্ষা থেকে উপকৃত হয়।", slotValues: { CLAUSE: "children benefit from bilingual education" }, topicArea: "education" },
        { en: "In most cases, exercise helps manage chronic conditions.", bn: "বেশিরভাগ ক্ষেত্রে, ব্যায়াম দীর্ঘস্থায়ী রোগ নিয়ন্ত্রণে সাহায্য করে।", slotValues: { CLAUSE: "exercise helps manage chronic conditions" }, topicArea: "health" },
        { en: "In most cases, the new software performs better than the old version.", bn: "বেশিরভাগ ক্ষেত্রে, নতুন সফটওয়্যার পুরোনো সংস্করণের চেয়ে ভালো কাজ করে।", slotValues: { CLAUSE: "the new software performs better than the old version" }, topicArea: "technology" },
      ],
      formality: "formal",
      difficulty: "advanced",
      usageNote: "Indicates that a statement applies to the majority of situations, allowing for exceptions.",
      usageNote_bn: "নির্দেশ করে যে একটি বিবৃতি অধিকাংশ পরিস্থিতিতে প্রযোজ্য, ব্যতিক্রমের অনুমতি দিয়ে।",
    },
    {
      id: "W7.4",
      formula: "By and large, [CLAUSE]",
      formula_bn: "মোটামুটিভাবে, [বাক্যাংশ]",
      patternName: "Overall Generalization",
      patternName_bn: "সামগ্রিক সাধারণীকরণ",
      slots: [
        { name: "CLAUSE", description: "A general assessment or observation", description_bn: "একটি সাধারণ মূল্যায়ন বা পর্যবেক্ষণ", acceptedTypes: ["clause"], examples: ["the policy has been successful", "people support the idea", "the results are positive"] },
      ],
      examples: [
        { en: "By and large, the policy has been successful.", bn: "মোটামুটিভাবে, নীতিটি সফল হয়েছে।", slotValues: { CLAUSE: "the policy has been successful" }, topicArea: "education" },
        { en: "By and large, people support the idea of free education.", bn: "মোটামুটিভাবে, মানুষ বিনামূল্যে শিক্ষার ধারণা সমর্থন করে।", slotValues: { CLAUSE: "people support the idea of free education" }, topicArea: "education" },
        { en: "By and large, the results are positive.", bn: "মোটামুটিভাবে, ফলাফল ইতিবাচক।", slotValues: { CLAUSE: "the results are positive" }, topicArea: "science" },
        { en: "By and large, the economy has recovered well.", bn: "মোটামুটিভাবে, অর্থনীতি ভালোভাবে পুনরুদ্ধার হয়েছে।", slotValues: { CLAUSE: "the economy has recovered well" }, topicArea: "economics" },
        { en: "By and large, employees are satisfied with the new system.", bn: "মোটামুটিভাবে, কর্মীরা নতুন ব্যবস্থায় সন্তুষ্ট।", slotValues: { CLAUSE: "employees are satisfied with the new system" }, topicArea: "work" },
        { en: "By and large, the experiment confirmed our predictions.", bn: "মোটামুটিভাবে, পরীক্ষাটি আমাদের ভবিষ্যদ্বাণী নিশ্চিত করেছে।", slotValues: { CLAUSE: "the experiment confirmed our predictions" }, topicArea: "science" },
        { en: "By and large, healthcare standards have improved.", bn: "মোটামুটিভাবে, স্বাস্থ্যসেবার মান উন্নত হয়েছে।", slotValues: { CLAUSE: "healthcare standards have improved" }, topicArea: "health" },
        { en: "By and large, renewable energy is the future.", bn: "মোটামুটিভাবে, নবায়নযোগ্য শক্তিই ভবিষ্যৎ।", slotValues: { CLAUSE: "renewable energy is the future" }, topicArea: "environment" },
        { en: "By and large, students prefer interactive learning.", bn: "মোটামুটিভাবে, শিক্ষার্থীরা ইন্টারেক্টিভ শিক্ষা পছন্দ করে।", slotValues: { CLAUSE: "students prefer interactive learning" }, topicArea: "education" },
        { en: "By and large, the reforms have had a positive impact.", bn: "মোটামুটিভাবে, সংস্কারগুলোর ইতিবাচক প্রভাব পড়েছে।", slotValues: { CLAUSE: "the reforms have had a positive impact" }, topicArea: "economics" },
        { en: "By and large, international cooperation has increased.", bn: "মোটামুটিভাবে, আন্তর্জাতিক সহযোগিতা বেড়েছে।", slotValues: { CLAUSE: "international cooperation has increased" }, topicArea: "education" },
        { en: "By and large, customers are happy with the product.", bn: "মোটামুটিভাবে, গ্রাহকরা পণ্যটি নিয়ে সন্তুষ্ট।", slotValues: { CLAUSE: "customers are happy with the product" }, topicArea: "work" },
        { en: "By and large, the project was completed on time.", bn: "মোটামুটিভাবে, প্রকল্পটি সময়মতো সম্পন্ন হয়েছে।", slotValues: { CLAUSE: "the project was completed on time" }, topicArea: "work" },
        { en: "By and large, the evidence supports the theory.", bn: "মোটামুটিভাবে, প্রমাণ তত্ত্বটি সমর্থন করে।", slotValues: { CLAUSE: "the evidence supports the theory" }, topicArea: "science" },
        { en: "By and large, public opinion favors environmental protection.", bn: "মোটামুটিভাবে, জনমত পরিবেশ সুরক্ষার পক্ষে।", slotValues: { CLAUSE: "public opinion favors environmental protection" }, topicArea: "environment" },
      ],
      formality: "formal",
      difficulty: "advanced",
      usageNote: "An idiomatic expression meaning 'on the whole' or 'generally speaking.' Suitable for academic contexts.",
      usageNote_bn: "'সামগ্রিকভাবে' বা 'সাধারণভাবে বলতে গেলে' অর্থের একটি বাগধারা। একাডেমিক প্রসঙ্গে উপযুক্ত।",
    },
    {
      id: "W7.5",
      formula: "It is generally accepted that [CLAUSE]",
      formula_bn: "সাধারণভাবে গৃহীত যে [বাক্যাংশ]",
      patternName: "Accepted Knowledge",
      patternName_bn: "গৃহীত জ্ঞান",
      slots: [
        { name: "CLAUSE", description: "A widely accepted fact or principle", description_bn: "একটি ব্যাপকভাবে গৃহীত তথ্য বা নীতি", acceptedTypes: ["clause"], examples: ["education is important", "climate change is real", "diversity has benefits"] },
      ],
      examples: [
        { en: "It is generally accepted that education is a fundamental right.", bn: "সাধারণভাবে গৃহীত যে শিক্ষা একটি মৌলিক অধিকার।", slotValues: { CLAUSE: "education is a fundamental right" }, topicArea: "education" },
        { en: "It is generally accepted that climate change is caused by human activity.", bn: "সাধারণভাবে গৃহীত যে জলবায়ু পরিবর্তন মানব কর্মকাণ্ড দ্বারা সৃষ্ট।", slotValues: { CLAUSE: "climate change is caused by human activity" }, topicArea: "environment" },
        { en: "It is generally accepted that diversity in the workplace has benefits.", bn: "সাধারণভাবে গৃহীত যে কর্মক্ষেত্রে বৈচিত্র্যের সুবিধা আছে।", slotValues: { CLAUSE: "diversity in the workplace has benefits" }, topicArea: "work" },
        { en: "It is generally accepted that smoking is harmful to health.", bn: "সাধারণভাবে গৃহীত যে ধূমপান স্বাস্থ্যের জন্য ক্ষতিকর।", slotValues: { CLAUSE: "smoking is harmful to health" }, topicArea: "health" },
        { en: "It is generally accepted that exercise improves well-being.", bn: "সাধারণভাবে গৃহীত যে ব্যায়াম সুস্থতার উন্নতি করে।", slotValues: { CLAUSE: "exercise improves well-being" }, topicArea: "health" },
        { en: "It is generally accepted that the Earth is approximately 4.5 billion years old.", bn: "সাধারণভাবে গৃহীত যে পৃথিবীর বয়স প্রায় ৪.৫ বিলিয়ন বছর।", slotValues: { CLAUSE: "the Earth is approximately 4.5 billion years old" }, topicArea: "science" },
        { en: "It is generally accepted that clean water is essential for public health.", bn: "সাধারণভাবে গৃহীত যে বিশুদ্ধ পানি জনস্বাস্থ্যের জন্য অপরিহার্য।", slotValues: { CLAUSE: "clean water is essential for public health" }, topicArea: "health" },
        { en: "It is generally accepted that poverty is a complex issue.", bn: "সাধারণভাবে গৃহীত যে দারিদ্র্য একটি জটিল সমস্যা।", slotValues: { CLAUSE: "poverty is a complex issue" }, topicArea: "economics" },
        { en: "It is generally accepted that technology is transforming the workplace.", bn: "সাধারণভাবে গৃহীত যে প্রযুক্তি কর্মক্ষেত্রকে রূপান্তরিত করছে।", slotValues: { CLAUSE: "technology is transforming the workplace" }, topicArea: "technology" },
        { en: "It is generally accepted that early childhood experiences shape personality.", bn: "সাধারণভাবে গৃহীত যে প্রাথমিক শৈশবের অভিজ্ঞতা ব্যক্তিত্ব গঠন করে।", slotValues: { CLAUSE: "early childhood experiences shape personality" }, topicArea: "education" },
        { en: "It is generally accepted that vaccines are safe and effective.", bn: "সাধারণভাবে গৃহীত যে টিকা নিরাপদ ও কার্যকর।", slotValues: { CLAUSE: "vaccines are safe and effective" }, topicArea: "health" },
        { en: "It is generally accepted that biodiversity is essential for ecosystem stability.", bn: "সাধারণভাবে গৃহীত যে বাস্তুতন্ত্রের স্থিতিশীলতার জন্য জীববৈচিত্র্য অপরিহার্য।", slotValues: { CLAUSE: "biodiversity is essential for ecosystem stability" }, topicArea: "environment" },
        { en: "It is generally accepted that globalization has both advantages and disadvantages.", bn: "সাধারণভাবে গৃহীত যে বিশ্বায়নের সুবিধা ও অসুবিধা উভয়ই আছে।", slotValues: { CLAUSE: "globalization has both advantages and disadvantages" }, topicArea: "economics" },
        { en: "It is generally accepted that sleep is crucial for brain function.", bn: "সাধারণভাবে গৃহীত যে মস্তিষ্কের কার্যকারিতার জন্য ঘুম অত্যন্ত গুরুত্বপূর্ণ।", slotValues: { CLAUSE: "sleep is crucial for brain function" }, topicArea: "health" },
        { en: "It is generally accepted that the internet has revolutionized communication.", bn: "সাধারণভাবে গৃহীত যে ইন্টারনেট যোগাযোগে বিপ্লব ঘটিয়েছে।", slotValues: { CLAUSE: "the internet has revolutionized communication" }, topicArea: "technology" },
      ],
      formality: "very_formal",
      difficulty: "advanced",
      usageNote: "Used to present established knowledge or consensus in academic writing without needing a specific citation.",
      usageNote_bn: "নির্দিষ্ট উদ্ধৃতি ছাড়াই একাডেমিক লেখায় প্রতিষ্ঠিত জ্ঞান বা ঐকমত্য উপস্থাপন করতে ব্যবহৃত।",
    },
  ],
};
