import { PatternCategory } from "@/types/pattern";

export const categoryX1: PatternCategory = {
  id: "X1",
  slug: "article-mistakes",
  name: "Article Mistakes (A/An/The)",
  name_bn: "আর্টিকেল ভুল (A/An/The)",
  description:
    "Fix the most common mistake Bangla speakers make — missing or wrong articles. Bangla has no articles, so this needs special practice.",
  description_bn:
    "বাংলা ভাষীদের সবচেয়ে সাধারণ ভুল ঠিক করুন — আর্টিকেল বাদ দেওয়া বা ভুল ব্যবহার। বাংলায় আর্টিকেল নেই, তাই এটি বিশেষ অনুশীলন প্রয়োজন।",
  icon: "📝",
  group: "X",
  groupName: "Common Mistakes by Bangla Speakers",
  groupName_bn: "বাংলা ভাষীদের সাধারণ ভুল",
  difficulty: "beginner",
  patterns: [
    {
      id: "X1.1",
      formula: "I am a [NOUN]",
      formula_bn: "আমি একজন [বিশেষ্য]",
      patternName: "Missing 'A/An' Before Singular Countable Nouns",
      patternName_bn: "একবচন গণনাযোগ্য বিশেষ্যের আগে 'A/An' বাদ পড়া",
      slots: [
        {
          name: "NOUN",
          description: "A singular countable noun that requires an indefinite article",
          description_bn: "একটি একবচন গণনাযোগ্য বিশেষ্য যার আগে অনির্দিষ্ট আর্টিকেল দরকার",
          acceptedTypes: ["noun"],
          examples: ["student", "doctor", "good idea"],
        },
      ],
      examples: [
        {
          en: "I am a student.",
          bn: "আমি একজন ছাত্র।",
          slotValues: { NOUN: "student" },
          topicArea: "education",
        },
        {
          en: "She is a doctor.",
          bn: "সে একজন ডাক্তার।",
          slotValues: { NOUN: "doctor" },
          topicArea: "work",
        },
        {
          en: "He is a teacher.",
          bn: "সে একজন শিক্ষক।",
          slotValues: { NOUN: "teacher" },
          topicArea: "work",
        },
        {
          en: "It is a good idea.",
          bn: "এটা একটা ভালো আইডিয়া।",
          slotValues: { NOUN: "good idea" },
          topicArea: "daily_life",
        },
        {
          en: "I need a pen.",
          bn: "আমার একটা কলম দরকার।",
          slotValues: { NOUN: "pen" },
          topicArea: "education",
        },
        {
          en: "She has a brother.",
          bn: "তার একজন ভাই আছে।",
          slotValues: { NOUN: "brother" },
          topicArea: "relationships",
        },
        {
          en: "It was a difficult exam.",
          bn: "এটা একটা কঠিন পরীক্ষা ছিল।",
          slotValues: { NOUN: "difficult exam" },
          topicArea: "education",
        },
        {
          en: "He is a kind person.",
          bn: "সে একজন দয়ালু মানুষ।",
          slotValues: { NOUN: "kind person" },
          topicArea: "relationships",
        },
        {
          en: "I saw a movie.",
          bn: "আমি একটা সিনেমা দেখলাম।",
          slotValues: { NOUN: "movie" },
          topicArea: "daily_life",
        },
        {
          en: "She wants a glass of water.",
          bn: "সে এক গ্লাস পানি চায়।",
          slotValues: { NOUN: "glass of water" },
          topicArea: "food",
        },
        {
          en: "This is a beautiful place.",
          bn: "এটা একটা সুন্দর জায়গা।",
          slotValues: { NOUN: "beautiful place" },
          topicArea: "travel",
        },
        {
          en: "He became a manager.",
          bn: "সে একজন ম্যানেজার হয়েছে।",
          slotValues: { NOUN: "manager" },
          topicArea: "work",
        },
        {
          en: "I have a question.",
          bn: "আমার একটা প্রশ্ন আছে।",
          slotValues: { NOUN: "question" },
          topicArea: "education",
        },
        {
          en: "She is a housewife.",
          bn: "সে একজন গৃহিণী।",
          slotValues: { NOUN: "housewife" },
          topicArea: "daily_life",
        },
        {
          en: "It is an interesting book.",
          bn: "এটা একটা আকর্ষণীয় বই।",
          slotValues: { NOUN: "interesting book" },
          topicArea: "education",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Bangla speakers often say 'I am student' or 'She is doctor' because Bangla has no article system. In English, singular countable nouns almost always need 'a' or 'an' before them. Wrong: 'I am student.' Correct: 'I am a student.'",
      usageNote_bn:
        "বাংলা ভাষীরা প্রায়ই 'I am student' বা 'She is doctor' বলে কারণ বাংলায় আর্টিকেল নেই। ইংরেজিতে একবচন গণনাযোগ্য বিশেষ্যের আগে প্রায় সবসময় 'a' বা 'an' দরকার। ভুল: 'I am student।' সঠিক: 'I am a student।'",
    },
    {
      id: "X1.2",
      formula: "[ACTION] the [NOUN]",
      formula_bn: "[ক্রিয়া] [বিশেষ্য]-টা",
      patternName: "Missing 'The' When Referring to Specific Things",
      patternName_bn: "নির্দিষ্ট জিনিস বোঝাতে 'The' বাদ পড়া",
      slots: [
        {
          name: "ACTION",
          description: "A verb or action to perform",
          description_bn: "একটি ক্রিয়া বা কাজ",
          acceptedTypes: ["verb"],
          examples: ["close", "open", "pass"],
        },
        {
          name: "NOUN",
          description: "A specific noun that both speaker and listener know about",
          description_bn: "একটি নির্দিষ্ট বিশেষ্য যা বক্তা ও শ্রোতা উভয়ই জানে",
          acceptedTypes: ["noun"],
          examples: ["door", "window", "salt"],
        },
      ],
      examples: [
        {
          en: "Close the door.",
          bn: "দরজাটা বন্ধ করো।",
          slotValues: { ACTION: "close", NOUN: "door" },
          topicArea: "daily_life",
        },
        {
          en: "Open the window.",
          bn: "জানালাটা খোলো।",
          slotValues: { ACTION: "open", NOUN: "window" },
          topicArea: "daily_life",
        },
        {
          en: "Pass the salt.",
          bn: "লবণটা দাও।",
          slotValues: { ACTION: "pass", NOUN: "salt" },
          topicArea: "food",
        },
        {
          en: "Turn off the light.",
          bn: "বাতিটা নেভাও।",
          slotValues: { ACTION: "turn off", NOUN: "light" },
          topicArea: "daily_life",
        },
        {
          en: "Read the book I gave you.",
          bn: "আমি তোমাকে যে বইটা দিয়েছিলাম সেটা পড়ো।",
          slotValues: { ACTION: "read", NOUN: "book I gave you" },
          topicArea: "education",
        },
        {
          en: "Where is the bathroom?",
          bn: "বাথরুমটা কোথায়?",
          slotValues: { ACTION: "where is", NOUN: "bathroom" },
          topicArea: "daily_life",
        },
        {
          en: "The bus is late.",
          bn: "বাসটা লেট হয়ে গেছে।",
          slotValues: { ACTION: "is late", NOUN: "bus" },
          topicArea: "travel",
        },
        {
          en: "I like the food here.",
          bn: "আমি এখানকার খাবারটা পছন্দ করি।",
          slotValues: { ACTION: "like", NOUN: "food here" },
          topicArea: "food",
        },
        {
          en: "Put it on the table.",
          bn: "এটা টেবিলের উপর রাখো।",
          slotValues: { ACTION: "put it on", NOUN: "table" },
          topicArea: "daily_life",
        },
        {
          en: "The children are playing.",
          bn: "বাচ্চারা খেলছে।",
          slotValues: { ACTION: "are playing", NOUN: "children" },
          topicArea: "daily_life",
        },
        {
          en: "She is in the kitchen.",
          bn: "সে রান্নাঘরে আছে।",
          slotValues: { ACTION: "is in", NOUN: "kitchen" },
          topicArea: "daily_life",
        },
        {
          en: "The weather is nice today.",
          bn: "আজকে আবহাওয়াটা সুন্দর।",
          slotValues: { ACTION: "is nice", NOUN: "weather" },
          topicArea: "daily_life",
        },
        {
          en: "I went to the market.",
          bn: "আমি বাজারে গিয়েছিলাম।",
          slotValues: { ACTION: "went to", NOUN: "market" },
          topicArea: "shopping",
        },
        {
          en: "The teacher is very good.",
          bn: "শিক্ষকটি খুব ভালো।",
          slotValues: { ACTION: "is very good", NOUN: "teacher" },
          topicArea: "education",
        },
        {
          en: "Can you see the moon?",
          bn: "তুমি কি চাঁদটা দেখতে পাচ্ছো?",
          slotValues: { ACTION: "can you see", NOUN: "moon" },
          topicArea: "daily_life",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Bangla speakers often drop 'the' when talking about a specific thing. In Bangla, '-টা' or '-টি' is added to the noun itself, but in English you must put 'the' before the noun. Wrong: 'Close door.' Correct: 'Close the door.'",
      usageNote_bn:
        "বাংলা ভাষীরা নির্দিষ্ট জিনিস বোঝাতে প্রায়ই 'the' বাদ দেয়। বাংলায় বিশেষ্যের সাথে '-টা' বা '-টি' যোগ হয়, কিন্তু ইংরেজিতে বিশেষ্যের আগে 'the' বসাতে হয়। ভুল: 'Close door।' সঠিক: 'Close the door।'",
    },
    {
      id: "X1.3",
      formula: "Give me some [THING]",
      formula_bn: "আমাকে কিছু [জিনিস] দাও",
      patternName: "Wrong Article with Uncountable Nouns",
      patternName_bn: "অগণনীয় বিশেষ্যের সাথে ভুল আর্টিকেল",
      slots: [
        {
          name: "THING",
          description: "An uncountable noun — use 'some' instead of 'a/an'",
          description_bn: "একটি অগণনীয় বিশেষ্য — 'a/an' এর বদলে 'some' ব্যবহার করুন",
          acceptedTypes: ["noun"],
          examples: ["water", "information", "advice"],
        },
      ],
      examples: [
        {
          en: "Give me some water.",
          bn: "আমাকে কিছু পানি দাও।",
          slotValues: { THING: "water" },
          topicArea: "food",
        },
        {
          en: "I need some information.",
          bn: "আমার কিছু তথ্য দরকার।",
          slotValues: { THING: "information" },
          topicArea: "daily_life",
        },
        {
          en: "She gave me some advice.",
          bn: "সে আমাকে কিছু পরামর্শ দিয়েছে।",
          slotValues: { THING: "advice" },
          topicArea: "daily_life",
        },
        {
          en: "Can I have some rice?",
          bn: "আমি কি কিছু ভাত পেতে পারি?",
          slotValues: { THING: "rice" },
          topicArea: "food",
        },
        {
          en: "We need some furniture.",
          bn: "আমাদের কিছু আসবাবপত্র দরকার।",
          slotValues: { THING: "furniture" },
          topicArea: "shopping",
        },
        {
          en: "I want some milk.",
          bn: "আমি কিছু দুধ চাই।",
          slotValues: { THING: "milk" },
          topicArea: "food",
        },
        {
          en: "He needs some help.",
          bn: "তার কিছু সাহায্য দরকার।",
          slotValues: { THING: "help" },
          topicArea: "daily_life",
        },
        {
          en: "She bought some bread.",
          bn: "সে কিছু রুটি কিনেছে।",
          slotValues: { THING: "bread" },
          topicArea: "food",
        },
        {
          en: "Can you give me some money?",
          bn: "তুমি কি আমাকে কিছু টাকা দিতে পারো?",
          slotValues: { THING: "money" },
          topicArea: "daily_life",
        },
        {
          en: "I need some time.",
          bn: "আমার কিছু সময় দরকার।",
          slotValues: { THING: "time" },
          topicArea: "daily_life",
        },
        {
          en: "We have some homework.",
          bn: "আমাদের কিছু হোমওয়ার্ক আছে।",
          slotValues: { THING: "homework" },
          topicArea: "education",
        },
        {
          en: "She needs some practice.",
          bn: "তার কিছু অনুশীলন দরকার।",
          slotValues: { THING: "practice" },
          topicArea: "education",
        },
        {
          en: "I'd like some coffee.",
          bn: "আমি কিছু কফি চাইতাম।",
          slotValues: { THING: "coffee" },
          topicArea: "food",
        },
        {
          en: "He gave me some feedback.",
          bn: "সে আমাকে কিছু মতামত দিয়েছে।",
          slotValues: { THING: "feedback" },
          topicArea: "work",
        },
        {
          en: "They need some training.",
          bn: "তাদের কিছু প্রশিক্ষণ দরকার।",
          slotValues: { THING: "training" },
          topicArea: "work",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Bangla speakers often add 'a' before uncountable nouns because in Bangla, 'একটু' or 'কিছু' works for everything. In English, uncountable nouns like water, information, advice, furniture cannot take 'a/an'. Use 'some' instead. Wrong: 'Give me a water.' Correct: 'Give me some water.'",
      usageNote_bn:
        "বাংলা ভাষীরা প্রায়ই অগণনীয় বিশেষ্যের আগে 'a' যোগ করে কারণ বাংলায় 'একটু' বা 'কিছু' সবকিছুর জন্য কাজ করে। ইংরেজিতে water, information, advice, furniture-এর মতো অগণনীয় বিশেষ্যের আগে 'a/an' বসে না। 'some' ব্যবহার করুন। ভুল: 'Give me a water।' সঠিক: 'Give me some water।'",
    },
    {
      id: "X1.4",
      formula: "I like [THING]",
      formula_bn: "আমি [জিনিস] পছন্দ করি",
      patternName: "Zero Article — No Article for General/Abstract Things",
      patternName_bn: "শূন্য আর্টিকেল — সাধারণ/বিমূর্ত জিনিসে আর্টিকেল নেই",
      slots: [
        {
          name: "THING",
          description:
            "An uncountable noun or plural noun used in a general sense — no article needed",
          description_bn:
            "সাধারণ অর্থে ব্যবহৃত অগণনীয় বা বহুবচন বিশেষ্য — কোনো আর্টিকেল লাগে না",
          acceptedTypes: ["noun", "gerund"],
          examples: ["music", "cooking", "cricket"],
        },
      ],
      examples: [
        {
          en: "I like music.",
          bn: "আমি গান পছন্দ করি।",
          slotValues: { THING: "music" },
          topicArea: "daily_life",
        },
        {
          en: "She loves cooking.",
          bn: "সে রান্না করতে ভালোবাসে।",
          slotValues: { THING: "cooking" },
          topicArea: "food",
        },
        {
          en: "He plays cricket.",
          bn: "সে ক্রিকেট খেলে।",
          slotValues: { THING: "cricket" },
          topicArea: "daily_life",
        },
        {
          en: "Education is important.",
          bn: "শিক্ষা গুরুত্বপূর্ণ।",
          slotValues: { THING: "education" },
          topicArea: "education",
        },
        {
          en: "Water is essential for life.",
          bn: "জীবনের জন্য পানি অপরিহার্য।",
          slotValues: { THING: "water" },
          topicArea: "health",
        },
        {
          en: "They study English.",
          bn: "তারা ইংরেজি পড়ে।",
          slotValues: { THING: "English" },
          topicArea: "education",
        },
        {
          en: "I enjoy travelling.",
          bn: "আমি ভ্রমণ উপভোগ করি।",
          slotValues: { THING: "travelling" },
          topicArea: "travel",
        },
        {
          en: "Money can't buy happiness.",
          bn: "টাকা দিয়ে সুখ কেনা যায় না।",
          slotValues: { THING: "happiness" },
          topicArea: "daily_life",
        },
        {
          en: "Health is wealth.",
          bn: "স্বাস্থ্যই সম্পদ।",
          slotValues: { THING: "health" },
          topicArea: "health",
        },
        {
          en: "She teaches mathematics.",
          bn: "সে গণিত পড়ায়।",
          slotValues: { THING: "mathematics" },
          topicArea: "education",
        },
        {
          en: "I prefer tea over coffee.",
          bn: "আমি কফির চেয়ে চা পছন্দ করি।",
          slotValues: { THING: "tea" },
          topicArea: "food",
        },
        {
          en: "Birds fly south in winter.",
          bn: "শীতকালে পাখিরা দক্ষিণে উড়ে যায়।",
          slotValues: { THING: "birds" },
          topicArea: "daily_life",
        },
        {
          en: "Children need love.",
          bn: "শিশুদের ভালোবাসা দরকার।",
          slotValues: { THING: "love" },
          topicArea: "relationships",
        },
        {
          en: "Knowledge is power.",
          bn: "জ্ঞানই শক্তি।",
          slotValues: { THING: "knowledge" },
          topicArea: "education",
        },
        {
          en: "Life is beautiful.",
          bn: "জীবন সুন্দর।",
          slotValues: { THING: "life" },
          topicArea: "daily_life",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "Bangla speakers sometimes add 'the' before general or abstract nouns because Bangla doesn't distinguish between specific and general references the same way. When talking about something in general (not a specific one), don't use any article. Wrong: 'I like the music' (when meaning music in general). Correct: 'I like music.'",
      usageNote_bn:
        "বাংলা ভাষীরা কখনো কখনো সাধারণ বা বিমূর্ত বিশেষ্যের আগে 'the' যোগ করে কারণ বাংলায় নির্দিষ্ট ও সাধারণ একইভাবে বোঝায়। সাধারণভাবে কিছু বোঝাতে (নির্দিষ্ট কোনো একটা নয়) কোনো আর্টিকেল ব্যবহার করবেন না। ভুল: 'I like the music' (সাধারণভাবে গান বোঝাতে)। সঠিক: 'I like music।'",
    },
    {
      id: "X1.5",
      formula: "[A/AN] [NOUN]",
      formula_bn: "[A/AN] [বিশেষ্য]",
      patternName: "A vs An — Based on Sound, Not Spelling",
      patternName_bn: "A বনাম An — বানান নয়, উচ্চারণ অনুযায়ী",
      slots: [
        {
          name: "A/AN",
          description: "Use 'a' before consonant sounds and 'an' before vowel sounds",
          description_bn: "ব্যঞ্জনধ্বনির আগে 'a' এবং স্বরধ্বনির আগে 'an' ব্যবহার করুন",
          acceptedTypes: ["noun"],
          examples: ["a", "an"],
        },
        {
          name: "NOUN",
          description: "A singular countable noun",
          description_bn: "একটি একবচন গণনাযোগ্য বিশেষ্য",
          acceptedTypes: ["noun"],
          examples: ["umbrella", "university", "hour"],
        },
      ],
      examples: [
        {
          en: "I need an umbrella.",
          bn: "আমার একটা ছাতা দরকার।",
          slotValues: { "A/AN": "an", NOUN: "umbrella" },
          topicArea: "daily_life",
        },
        {
          en: "She goes to a university.",
          bn: "সে একটি বিশ্ববিদ্যালয়ে যায়।",
          slotValues: { "A/AN": "a", NOUN: "university" },
          topicArea: "education",
        },
        {
          en: "I'll be there in an hour.",
          bn: "আমি এক ঘণ্টার মধ্যে সেখানে পৌঁছাব।",
          slotValues: { "A/AN": "an", NOUN: "hour" },
          topicArea: "daily_life",
        },
        {
          en: "They live in a house.",
          bn: "তারা একটা বাড়িতে থাকে।",
          slotValues: { "A/AN": "a", NOUN: "house" },
          topicArea: "daily_life",
        },
        {
          en: "He is an honest person.",
          bn: "সে একজন সৎ মানুষ।",
          slotValues: { "A/AN": "an", NOUN: "honest person" },
          topicArea: "relationships",
        },
        {
          en: "This is a one-way street.",
          bn: "এটা একটা একমুখী রাস্তা।",
          slotValues: { "A/AN": "a", NOUN: "one-way street" },
          topicArea: "travel",
        },
        {
          en: "I had an egg for breakfast.",
          bn: "আমি সকালে একটা ডিম খেয়েছি।",
          slotValues: { "A/AN": "an", NOUN: "egg" },
          topicArea: "food",
        },
        {
          en: "France is a European country.",
          bn: "ফ্রান্স একটি ইউরোপীয় দেশ।",
          slotValues: { "A/AN": "a", NOUN: "European country" },
          topicArea: "education",
        },
        {
          en: "She ate an apple.",
          bn: "সে একটা আপেল খেয়েছে।",
          slotValues: { "A/AN": "an", NOUN: "apple" },
          topicArea: "food",
        },
        {
          en: "This is a useful tool.",
          bn: "এটা একটা দরকারি যন্ত্র।",
          slotValues: { "A/AN": "a", NOUN: "useful tool" },
          topicArea: "work",
        },
        {
          en: "I want an orange.",
          bn: "আমি একটা কমলা চাই।",
          slotValues: { "A/AN": "an", NOUN: "orange" },
          topicArea: "food",
        },
        {
          en: "He is an uncle of mine.",
          bn: "সে আমার একজন চাচা।",
          slotValues: { "A/AN": "an", NOUN: "uncle" },
          topicArea: "relationships",
        },
        {
          en: "She wears a uniform.",
          bn: "সে একটা ইউনিফর্ম পরে।",
          slotValues: { "A/AN": "a", NOUN: "uniform" },
          topicArea: "work",
        },
        {
          en: "We saw an elephant at the zoo.",
          bn: "আমরা চিড়িয়াখানায় একটা হাতি দেখেছি।",
          slotValues: { "A/AN": "an", NOUN: "elephant" },
          topicArea: "daily_life",
        },
        {
          en: "It is an honor to meet you.",
          bn: "আপনার সাথে দেখা হওয়াটা সম্মানের।",
          slotValues: { "A/AN": "an", NOUN: "honor" },
          topicArea: "daily_life",
        },
      ],
      formality: "casual",
      difficulty: "beginner",
      usageNote:
        "The choice between 'a' and 'an' depends on the SOUND, not the letter. Use 'an' before vowel sounds (an umbrella, an hour, an honest person) and 'a' before consonant sounds (a university, a one-way street, a European). Wrong: 'a umbrella', 'a hour'. Correct: 'an umbrella', 'an hour'.",
      usageNote_bn:
        "'A' এবং 'an'-এর পছন্দ অক্ষর নয়, ধ্বনির উপর নির্ভর করে। স্বরধ্বনির আগে 'an' (an umbrella, an hour, an honest person) এবং ব্যঞ্জনধ্বনির আগে 'a' (a university, a one-way street, a European) ব্যবহার করুন। ভুল: 'a umbrella', 'a hour'। সঠিক: 'an umbrella', 'an hour'।",
    },
  ],
};
