import type { Pattern } from "@/types/pattern";

export const patternA2_5: Pattern = {
  id: "A2.5",
  formula: "Is it possible to get [THING]?",
  formula_bn: "[জিনিস] পাওয়া কি সম্ভব?",
  patternName: "Polite Possibility Request",
  patternName_bn: "সম্ভব কিনা জিজ্ঞেস করা",
  formulaPronunciation_bn: "ইজ ইট পসিবল টু গেট [জিনিস]?",
  concept_bn: "সম্ভব কিনা",
  bridgeRuleIds: ["BR1", "BR3", "BR5", "BR7"],
  slots: [
    {
      name: "THING",
      description: "A noun or noun phrase you want to know if it's possible to receive",
      description_bn: "যে জিনিস পাওয়া সম্ভব কিনা জানতে চাইছো",
      acceptedTypes: ["noun"],
      examples: ["an upgrade", "a late checkout", "a replacement"],
    },
  ],
  examples: [
    {
      en: "Is it possible to get an upgrade?",
      bn: "আপগ্রেড পাওয়া কি সম্ভব?",
      pronunciation_bn: "ইজ ইট পসিবল টু গেট অ্যান আপগ্রেড?",
      slotValues: { THING: "an upgrade" },
      topicArea: "travel",
      stage: 1,
      miniStory: {
        situation_bn: "তুমি হোটেলে চেক-ইন করছো। ছোট রুম পেয়েছো। রিসেপশনিস্টকে জিজ্ঞেস করছো বড় রুম পাওয়া যাবে কিনা।",
        icon: "🏨",
      },
    },
    {
      en: "Is it possible to get a late checkout?",
      bn: "লেট চেকআউট পাওয়া কি সম্ভব?",
      pronunciation_bn: "ইজ ইট পসিবল টু গেট এ লেট চেকআউট?",
      slotValues: { THING: "a late checkout" },
      topicArea: "travel",
      stage: 1,
    },
    {
      en: "Is it possible to get a replacement?",
      bn: "বদলে নতুন একটা পাওয়া কি সম্ভব?",
      pronunciation_bn: "ইজ ইট পসিবল টু গেট এ রিপ্লেসমেন্ট?",
      slotValues: { THING: "a replacement" },
      topicArea: "shopping",
      stage: 1,
      miniStory: {
        situation_bn: "তুমি দোকান থেকে একটা ফোনের চার্জার কিনেছিলে। বাসায় এনে দেখো কাজ করে না। দোকানে ফেরত গেছো।",
        icon: "🔌",
      },
    },
    {
      en: "Is it possible to get a table for four?",
      bn: "চারজনের জন্য একটা টেবিল পাওয়া কি সম্ভব?",
      pronunciation_bn: "ইজ ইট পসিবল টু গেট এ টেবল ফর ফোর?",
      slotValues: { THING: "a table for four" },
      topicArea: "food",
      stage: 1,
    },
    {
      en: "Is it possible to get an earlier appointment?",
      bn: "আরও আগে একটা অ্যাপয়েন্টমেন্ট পাওয়া কি সম্ভব?",
      pronunciation_bn: "ইজ ইট পসিবল টু গেট অ্যান আর্লিয়ার অ্যাপয়েন্টমেন্ট?",
      slotValues: { THING: "an earlier appointment" },
      topicArea: "health",
      stage: 1,
      miniStory: {
        situation_bn: "তুমি হাসপাতালে গেছো। রিসেপশন বলছে ডাক্তারের অ্যাপয়েন্টমেন্ট আগামী সপ্তাহে। তুমি আরও আগে চাও।",
        icon: "🏥",
      },
    },
    {
      en: "Is it possible to get a transfer to another department?",
      bn: "অন্য বিভাগে বদলি পাওয়া কি সম্ভব?",
      pronunciation_bn: "ইজ ইট পসিবল টু গেট এ ট্রান্সফার টু অ্যানাদার ডিপার্টমেন্ট?",
      slotValues: { THING: "a transfer to another department" },
      topicArea: "work",
      stage: 2,
      miniStory: {
        situation_bn: "তুমি গার্মেন্টস ফ্যাক্টরিতে কাজ করো। তোমার সেকশনে অনেক চাপ। অন্য সেকশনে যেতে চাও। সুপারভাইজারকে বলছো।",
        icon: "🏭",
      },
    },
    {
      en: "Is it possible to get some extra time for the assignment?",
      bn: "অ্যাসাইনমেন্টের জন্য কিছু বাড়তি সময় পাওয়া কি সম্ভব?",
      pronunciation_bn: "ইজ ইট পসিবল টু গেট সাম এক্সট্রা টাইম ফর দা অ্যাসাইনমেন্ট?",
      slotValues: { THING: "some extra time for the assignment" },
      topicArea: "education",
      stage: 2,
    },
    {
      en: "Is it possible to get a discount?",
      bn: "ছাড় পাওয়া কি সম্ভব?",
      pronunciation_bn: "ইজ ইট পসিবল টু গেট এ ডিসকাউন্ট?",
      slotValues: { THING: "a discount" },
      topicArea: "shopping",
      stage: 2,
    },
    {
      en: "Is it possible to get a non-smoking room?",
      bn: "ধূমপান-মুক্ত রুম পাওয়া কি সম্ভব?",
      pronunciation_bn: "ইজ ইট পসিবল টু গেট এ নন-স্মোকিং রুম?",
      slotValues: { THING: "a non-smoking room" },
      topicArea: "travel",
      stage: 2,
    },
    {
      en: "Is it possible to get your advice on this?",
      bn: "এই বিষয়ে আপনার পরামর্শ পাওয়া কি সম্ভব?",
      pronunciation_bn: "ইজ ইট পসিবল টু গেট ইয়োর অ্যাডভাইস অন দিস?",
      slotValues: { THING: "your advice on this" },
      topicArea: "relationships",
      stage: 2,
      miniStory: {
        situation_bn: "তুমি নতুন ব্যবসা শুরু করতে চাও। তোমার চাচা অভিজ্ঞ ব্যবসায়ী। তাঁর পরামর্শ নিতে চাও।",
        icon: "💡",
      },
    },
    {
      en: "Is it possible to get a halal meal?",
      bn: "হালাল খাবার পাওয়া কি সম্ভব?",
      pronunciation_bn: "ইজ ইট পসিবল টু গেট এ হালাল মিল?",
      slotValues: { THING: "a halal meal" },
      topicArea: "food",
      stage: 3,
    },
    {
      en: "Is it possible to get some water?",
      bn: "কিছু পানি পাওয়া কি সম্ভব?",
      pronunciation_bn: "ইজ ইট পসিবল টু গেট সাম ওয়াটার?",
      slotValues: { THING: "some water" },
      topicArea: "daily_life",
      stage: 3,
    },
    {
      en: "Is it possible to get a reference letter?",
      bn: "একটা রেফারেন্স লেটার পাওয়া কি সম্ভব?",
      pronunciation_bn: "ইজ ইট পসিবল টু গেট এ রেফারেন্স লেটার?",
      slotValues: { THING: "a reference letter" },
      topicArea: "work",
      stage: 3,
      miniStory: {
        situation_bn: "তুমি নতুন চাকরির জন্য আবেদন করছো। আগের অফিসের বসের কাছে রেফারেন্স লেটার চাইতে গেছো।",
        icon: "📄",
      },
    },
    {
      en: "Is it possible to get a blood test done today?",
      bn: "আজকে রক্ত পরীক্ষা করানো কি সম্ভব?",
      pronunciation_bn: "ইজ ইট পসিবল টু গেট এ ব্লাড টেস্ট ডান টুডে?",
      slotValues: { THING: "a blood test done today" },
      topicArea: "health",
      stage: 3,
    },
    {
      en: "Is it possible to get the notes from yesterday's class?",
      bn: "গতকালের ক্লাসের নোটস পাওয়া কি সম্ভব?",
      pronunciation_bn: "ইজ ইট পসিবল টু গেট দা নোটস ফ্রম ইয়েস্টারডেজ ক্লাস?",
      slotValues: { THING: "the notes from yesterday's class" },
      topicArea: "education",
      stage: 3,
    },
  ],
  formality: "polite",
  difficulty: "beginner",
  usageNote: "A very polite, indirect way to make a request. Shows consideration for whether it's feasible.",
  usageNote_bn: "খুব ভদ্রভাবে কিছু চাইতে 'ইজ ইট পসিবল টু গেট' বলো। এটা বললে মনে হয় তুমি অন্যজনের কষ্টের কথা ভাবছো — খুবই সম্মানজনক উপায়।",
  combinableWith: ["A2.2", "A2.3"],
  responsePatterns: ["B2.1"],
  banglaStructureMap: "বাংলা: [জিনিস] পাওয়া কি সম্ভব? → English: Is it possible to get [THING]?",

  // Teaching fields
  conversionSteps: {
    banglaThought: "তুমি বাংলায় বলো: 'এটা কি আজকে ডাক্তারের অ্যাপয়েন্টমেন্ট পাওয়া সম্ভব?'",
    steps: [
      {
        step_bn: "'সম্ভব কিনা' জিজ্ঞেস করতে → 'Is it possible' দিয়ে শুরু করো",
        result: "Is it possible",
      },
      {
        step_bn: "'পাওয়া' = 'to get' — মাঝে যোগ করো",
        result: "Is it possible to get",
      },
      {
        step_bn: "'ডাক্তারের অ্যাপয়েন্টমেন্ট আজকে' = 'a doctor's appointment today' — শেষে বলো",
        result: "Is it possible to get a doctor's appointment today?",
      },
    ],
    finalResult: "Is it possible to get a doctor's appointment today?",
    finalResult_bn: "আজকে ডাক্তারের অ্যাপয়েন্টমেন্ট পাওয়া কি সম্ভব?",
  },

  commonMistakes: [
    {
      wrong: "Is possible to get a discount?",
      correct: "Is it possible to get a discount?",
      explanation_bn: "'Is' আর 'possible'-এর মাঝে 'it' বসাতেই হবে — 'ইজ ইট পসিবল'",
    },
    {
      wrong: "Is it possible get a table?",
      correct: "Is it possible to get a table?",
      explanation_bn: "'possible'-এর পর 'to' লাগে — 'পসিবল টু গেট'",
    },
    {
      wrong: "Is it possible to getting a room?",
      correct: "Is it possible to get a room?",
      explanation_bn: "'to'-এর পর সবসময় 'get' বলো, 'getting' না — 'টু গেট'",
    },
    {
      wrong: "Is it possible to get discount?",
      correct: "Is it possible to get a discount?",
      explanation_bn: "ইংরেজিতে জিনিসের আগে 'a' বা 'the' লাগে — 'এ ডিসকাউন্ট'",
    },
  ],

  simpleRules: [
    {
      rule_bn: "'Is it possible to get' হলো খুব ভদ্র ভাবে জিজ্ঞেস করা — যখন তুমি নিশ্চিত না পাবে কিনা",
      example: "Is it possible to get an earlier appointment?",
    },
    {
      rule_bn: "'Is it possible to get' + জিনিসের নাম — ব্যস, এটুকুই",
      example: "Is it possible to get a discount?",
    },
    {
      rule_bn: "এটা 'Can I have'-এর চেয়ে বেশি ভদ্র — অফিস, হাসপাতাল, দূতাবাসে বলো",
      example: "Is it possible to get a reference letter?",
    },
    {
      rule_bn: "আরও বেশি ভদ্র করতে চাইলে 'Would it be possible to get' বলো",
      example: "Would it be possible to get a late checkout?",
    },
  ],

  usageSituations: [
    {
      situation_bn: "হাসপাতালে বিশেষজ্ঞ ডাক্তারের কাছে",
      situation_en: "At the hospital for a specialist",
      exampleSentence: "Is it possible to get an earlier appointment?",
      exampleSentence_bn: "আরও আগে একটা অ্যাপয়েন্টমেন্ট পাওয়া কি সম্ভব?",
    },
    {
      situation_bn: "সরকারি অফিসে কাগজপত্রের জন্য",
      situation_en: "At the government office for documents",
      exampleSentence: "Is it possible to get a copy of the certificate today?",
      exampleSentence_bn: "আজকে সার্টিফিকেটের কপি পাওয়া কি সম্ভব?",
    },
    {
      situation_bn: "ট্রেনের টিকিট কাউন্টারে ভিড়ের সময়",
      situation_en: "At the train ticket counter during rush",
      exampleSentence: "Is it possible to get two tickets for the next train?",
      exampleSentence_bn: "পরের ট্রেনের দুটো টিকিট পাওয়া কি সম্ভব?",
    },
    {
      situation_bn: "বিদেশে ভিসার জন্য দূতাবাসে",
      situation_en: "At the embassy for a visa",
      exampleSentence: "Is it possible to get a faster visa processing?",
      exampleSentence_bn: "দ্রুত ভিসা প্রসেসিং পাওয়া কি সম্ভব?",
    },
  ],

  sentenceBuilding: [
    {
      previousPatternId: "A2.1",
      previousFormula: "Can I have [THING]?",
      previousFormula_bn: "আমি কি [জিনিস] পেতে পারি?",
      combined: "Can I have an appointment? Or is it possible to get one today?",
      combined_bn: "আমি কি অ্যাপয়েন্টমেন্ট পেতে পারি? অথবা আজকে পাওয়া কি সম্ভব?",
    },
    {
      previousPatternId: "A2.2",
      previousFormula: "Could I get [THING]?",
      previousFormula_bn: "আমি কি [জিনিস] পেতে পারতাম?",
      combined: "Could I get a room? Is it possible to get one with a view?",
      combined_bn: "আমি কি একটা রুম পেতে পারি? ভিউ সহ একটা পাওয়া কি সম্ভব?",
    },
  ],

  memoryTrick_bn:
    "'ইজ ইট পসিবল টু গেট' = 'পাওয়া কি সম্ভব?' — যখন কঠিন কিছু চাও, নিশ্চিত না পাবে কিনা, তখন এটা বলো। 'পসিবল' মানে 'সম্ভব' — এটা মনে রাখো!",

  chunks: [
    { en: "Is it possible", bn: "সম্ভব কি", pronunciation_bn: "ইজ ইট পসিবল" },
    { en: "Is it possible to get", bn: "পাওয়া কি সম্ভব", pronunciation_bn: "ইজ ইট পসিবল টু গেট" },
    { en: "Is it possible to get a", bn: "একটা পাওয়া কি সম্ভব", pronunciation_bn: "ইজ ইট পসিবল টু গেট এ" },
    { en: "Would it be possible to get", bn: "পাওয়া কি সম্ভব হতো", pronunciation_bn: "উড ইট বি পসিবল টু গেট" },
  ],

  wordMap: {
    bn_sentence: "আজকে ডাক্তারের অ্যাপয়েন্টমেন্ট পাওয়া কি সম্ভব?",
    en_sentence: "Is it possible to get a doctor's appointment today?",
    mappings: [
      { bn_word: "কি সম্ভব", en_word: "Is it possible", type: "moved", bridgeRuleId: "BR1" },
      { bn_word: "(বাংলায় নেই)", en_word: "it", type: "added", bridgeRuleId: "BR3" },
      { bn_word: "পাওয়া", en_word: "to get", type: "direct" },
      { bn_word: "(বাংলায় নেই)", en_word: "a", type: "added", bridgeRuleId: "BR4" },
      { bn_word: "ডাক্তারের", en_word: "doctor's", type: "direct" },
      { bn_word: "অ্যাপয়েন্টমেন্ট", en_word: "appointment", type: "direct" },
      { bn_word: "আজকে", en_word: "today", type: "moved", bridgeRuleId: "BR1" },
    ],
  },

  answerTemplates: [
    {
      situation_bn: "যখন হাসপাতালের রিসেপশনিস্ট জবাব দেয়",
      question: "Is it possible to get an earlier appointment?",
      question_bn: "আরও আগে অ্যাপয়েন্টমেন্ট পাওয়া কি সম্ভব?",
      answerFormula: "Yes, we have a slot at [TIME].",
      answerFormula_bn: "হ্যাঁ, [সময়]-তে একটা জায়গা আছে।",
      pronunciation_bn: "ইয়েস, উই হ্যাভ এ স্লট অ্যাট [সময়]।",
      examples: [
        { answer: "Yes, we have a slot at 3 PM.", answer_bn: "হ্যাঁ, বিকাল ৩টায় একটা জায়গা আছে।", pronunciation_bn: "ইয়েস, উই হ্যাভ এ স্লট অ্যাট থ্রি পিএম।" },
        { answer: "I'm sorry, the doctor is fully booked today.", answer_bn: "দুঃখিত, আজকে ডাক্তারের সব অ্যাপয়েন্টমেন্ট ভর্তি।", pronunciation_bn: "আইম সরি, দা ডক্টর ইজ ফুলি বুকড টুডে।" },
        { answer: "Let me check for you.", answer_bn: "আমি আপনার জন্য দেখছি।", pronunciation_bn: "লেট মি চেক ফর ইউ।" },
      ],
      notes_bn: "হাসপাতালে ভদ্রভাবে জিজ্ঞেস করলে তারাও ভদ্রভাবে জবাব দেয়।",
    },
    {
      situation_bn: "যখন সরকারি অফিসের কর্মচারী জবাব দেয়",
      question: "Is it possible to get the certificate today?",
      question_bn: "আজকে সার্টিফিকেট পাওয়া কি সম্ভব?",
      answerFormula: "It usually takes [TIME]. Come back on [DAY].",
      answerFormula_bn: "সাধারণত [সময়] লাগে। [দিন]-এ আসুন।",
      pronunciation_bn: "ইট ইউজুয়ালি টেইকস [সময়]। কাম ব্যাক অন [দিন]।",
      examples: [
        { answer: "It usually takes three days.", answer_bn: "সাধারণত তিন দিন লাগে।", pronunciation_bn: "ইট ইউজুয়ালি টেইকস থ্রি ডেজ।" },
        { answer: "Come back on Thursday.", answer_bn: "বৃহস্পতিবার আসুন।", pronunciation_bn: "কাম ব্যাক অন থার্সডে।" },
        { answer: "Yes, if you pay the express fee.", answer_bn: "হ্যাঁ, জরুরি ফি দিলে হবে।", pronunciation_bn: "ইয়েস, ইফ ইউ পে দা এক্সপ্রেস ফি।" },
      ],
      notes_bn: "সরকারি অফিসে কিছু চাইলে সময় লাগার কথা বলতে পারে।",
    },
    {
      situation_bn: "যখন ট্রেনের কাউন্টারের লোক জবাব দেয়",
      question: "Is it possible to get two tickets for the next train?",
      question_bn: "পরের ট্রেনের দুটো টিকিট পাওয়া কি সম্ভব?",
      answerFormula: "Let me see... [RESPONSE].",
      answerFormula_bn: "দেখি... [জবাব]।",
      pronunciation_bn: "লেট মি সি... [জবাব]।",
      examples: [
        { answer: "Yes, there are two seats available.", answer_bn: "হ্যাঁ, দুটো সিট খালি আছে।", pronunciation_bn: "ইয়েস, দেয়ার আর টু সিটস অ্যাভেইলেবল।" },
        { answer: "Sorry, this train is full. The next one is at 5 PM.", answer_bn: "দুঃখিত, এই ট্রেন ভর্তি। পরেরটা বিকাল ৫টায়।", pronunciation_bn: "সরি, দিস ট্রেন ইজ ফুল। দা নেক্সট ওয়ান ইজ অ্যাট ফাইভ পিএম।" },
        { answer: "Only standing tickets are available.", answer_bn: "শুধু দাঁড়ানো টিকিট আছে।", pronunciation_bn: "ওনলি স্ট্যান্ডিং টিকেটস আর অ্যাভেইলেবল।" },
      ],
      notes_bn: "ট্রেনের কাউন্টারে ভিড়ে ভদ্রভাবে বললে ভালো জবাব পাবে।",
    },
    {
      situation_bn: "যখন দূতাবাসের কর্মকর্তা জবাব দেয়",
      question: "Is it possible to get a faster visa processing?",
      question_bn: "দ্রুত ভিসা প্রসেসিং পাওয়া কি সম্ভব?",
      answerFormula: "Yes, you can apply for express processing for [AMOUNT].",
      answerFormula_bn: "হ্যাঁ, [পরিমাণ] টাকা দিয়ে এক্সপ্রেস আবেদন করতে পারেন।",
      pronunciation_bn: "ইয়েস, ইউ ক্যান অ্যাপ্লাই ফর এক্সপ্রেস প্রসেসিং ফর [পরিমাণ]।",
      examples: [
        { answer: "Yes, express processing takes 3 working days.", answer_bn: "হ্যাঁ, এক্সপ্রেস প্রসেসিং-এ ৩ কার্যদিবস লাগে।", pronunciation_bn: "ইয়েস, এক্সপ্রেস প্রসেসিং টেইকস থ্রি ওয়ার্কিং ডেজ।" },
        { answer: "I'm afraid not. Standard processing is 15 days.", answer_bn: "দুঃখিত, না। সাধারণ প্রসেসিং-এ ১৫ দিন লাগে।", pronunciation_bn: "আইম অ্যাফ্রেইড নট। স্ট্যান্ডার্ড প্রসেসিং ইজ ফিফটিন ডেজ।" },
        { answer: "Please fill out the express application form.", answer_bn: "দয়া করে এক্সপ্রেস আবেদন ফর্ম পূরণ করুন।", pronunciation_bn: "প্লিজ ফিল আউট দা এক্সপ্রেস অ্যাপ্লিকেশন ফর্ম।" },
      ],
      notes_bn: "দূতাবাসে খুব ভদ্র ভাষা ব্যবহার করতে হয়। 'Is it possible' এখানে একদম সঠিক।",
    },
  ],

  dialogueChains: [
    {
      id: "dc-a2.5-1",
      title_bn: "হাসপাতালে অ্যাপয়েন্টমেন্ট",
      title_en: "Hospital appointment",
      situation_bn: "তুমি ঢাকা মেডিকেলে গেছো। ডাক্তার দেখাতে অ্যাপয়েন্টমেন্ট চাও কিন্তু অনেক ভিড়।",
      icon: "🏥",
      turns: [
        { speaker_bn: "তুমি", en: "Is it possible to get an appointment today?", bn: "আজকে অ্যাপয়েন্টমেন্ট পাওয়া কি সম্ভব?", pronunciation_bn: "ইজ ইট পসিবল টু গেট অ্যান অ্যাপয়েন্টমেন্ট টুডে?", patternId: "A2.5" },
        { speaker_bn: "রিসেপশনিস্ট", en: "Let me check. Which doctor do you need?", bn: "দেখি। কোন ডাক্তার লাগবে?", pronunciation_bn: "লেট মি চেক। হুইচ ডক্টর ডু ইউ নিড?" },
        { speaker_bn: "তুমি", en: "I need the medicine specialist. Is it possible to get an earlier slot?", bn: "মেডিসিন বিশেষজ্ঞ লাগবে। আরও আগের সময় পাওয়া কি সম্ভব?", pronunciation_bn: "আই নিড দা মেডিসিন স্পেশালিস্ট। ইজ ইট পসিবল টু গেট অ্যান আর্লিয়ার স্লট?", patternId: "A2.5" },
        { speaker_bn: "রিসেপশনিস্ট", en: "The earliest slot is at 2 PM. Is that okay?", bn: "সবচেয়ে আগে বিকাল ২টায়। হবে?", pronunciation_bn: "দা আর্লিয়েস্ট স্লট ইজ অ্যাট টু পিএম। ইজ দ্যাট ওকে?" },
        { speaker_bn: "তুমি", en: "Yes, that's fine. Is it possible to get a blood test done too?", bn: "হ্যাঁ, ঠিক আছে। রক্ত পরীক্ষাও করানো কি সম্ভব?", pronunciation_bn: "ইয়েস, দ্যাটস ফাইন। ইজ ইট পসিবল টু গেট এ ব্লাড টেস্ট ডান টু?", patternId: "A2.5" },
        { speaker_bn: "রিসেপশনিস্ট", en: "Yes, the lab is on the second floor.", bn: "হ্যাঁ, ল্যাব দোতলায়।", pronunciation_bn: "ইয়েস, দা ল্যাব ইজ অন দা সেকেন্ড ফ্লোর।" },
      ],
      patternsUsed: ["A2.5"],
    },
    {
      id: "dc-cross-a2.5-a2.1-a2.3",
      title_bn: "ঢাকা মেডিকেলে চিকিৎসা",
      title_en: "Getting treatment at Dhaka Medical College",
      situation_bn: "তুমি ঢাকা মেডিকেল কলেজ হাসপাতালে গেছো। প্রথমে রিসেপশনে, তারপর ডাক্তারের কাছে, তারপর ল্যাবে।",
      icon: "🏥",
      turns: [
        { speaker_bn: "তুমি", en: "Is it possible to get an appointment with the medicine specialist today?", bn: "আজকে মেডিসিন বিশেষজ্ঞের অ্যাপয়েন্টমেন্ট পাওয়া কি সম্ভব?", pronunciation_bn: "ইজ ইট পসিবল টু গেট অ্যান অ্যাপয়েন্টমেন্ট উইথ দা মেডিসিন স্পেশালিস্ট টুডে?", patternId: "A2.5" },
        { speaker_bn: "রিসেপশনিস্ট", en: "Yes, there's a slot at 11 AM. Please take a token.", bn: "হ্যাঁ, সকাল ১১টায় একটা সময় আছে। টোকেন নিন।", pronunciation_bn: "ইয়েস, দেয়ারস এ স্লট অ্যাট ইলেভেন এএম। প্লিজ টেইক এ টোকেন।" },
        { speaker_bn: "তুমি", en: "Can I have the token, please?", bn: "আমি কি টোকেনটা পেতে পারি, প্লিজ?", pronunciation_bn: "ক্যান আই হ্যাভ দা টোকেন, প্লিজ?", patternId: "A2.1" },
        { speaker_bn: "রিসেপশনিস্ট", en: "Here you go. Room 205, second floor.", bn: "এই নিন। ২০৫ নম্বর রুম, দোতলায়।", pronunciation_bn: "হিয়ার ইউ গো। রুম টু ও ফাইভ, সেকেন্ড ফ্লোর।" },
        { speaker_bn: "তুমি (ডাক্তারকে)", en: "May I have a prescription for my fever?", bn: "আমি কি জ্বরের জন্য একটা প্রেসক্রিপশন পেতে পারি?", pronunciation_bn: "মে আই হ্যাভ এ প্রেসক্রিপশন ফর মাই ফিভার?", patternId: "A2.3" },
        { speaker_bn: "ডাক্তার", en: "Let me check first. I'll need some blood tests.", bn: "আগে দেখি। কিছু রক্ত পরীক্ষা লাগবে।", pronunciation_bn: "লেট মি চেক ফার্স্ট। আই'ল নিড সাম ব্লাড টেস্টস।" },
        { speaker_bn: "তুমি", en: "Is it possible to get the test results today?", bn: "আজকেই পরীক্ষার ফলাফল পাওয়া কি সম্ভব?", pronunciation_bn: "ইজ ইট পসিবল টু গেট দা টেস্ট রেজাল্টস টুডে?", patternId: "A2.5" },
        { speaker_bn: "ডাক্তার", en: "Yes, the lab can give you the results in 2 hours. Come back after that.", bn: "হ্যাঁ, ল্যাব ২ ঘণ্টায় ফলাফল দিতে পারবে। তারপর আসুন।", pronunciation_bn: "ইয়েস, দা ল্যাব ক্যান গিভ ইউ দা রেজাল্টস ইন টু আওয়ারস। কাম ব্যাক আফটার দ্যাট।" },
      ],
      patternsUsed: ["A2.5", "A2.1", "A2.3"],
    },
  ],

  variations: [
    {
      variant: "past",
      label: "Past (অতীত)",
      label_bn: "অতীত",
      formula: "Was it possible to get [THING]?",
      formula_bn: "[জিনিস] পাওয়া কি সম্ভব ছিল?",
      examples: [
        {
          en: "Was it possible to get an upgrade?",
          bn: "আপগ্রেড পাওয়া কি সম্ভব ছিল?",
          pronunciation_bn: "ওয়াজ ইট পসিবল টু গেট অ্যান আপগ্রেড?",
          slotValues: { THING: "an upgrade" },
          topicArea: "travel",
        },
        {
          en: "Was it possible to get a discount?",
          bn: "ছাড় পাওয়া কি সম্ভব ছিল?",
          pronunciation_bn: "ওয়াজ ইট পসিবল টু গেট এ ডিসকাউন্ট?",
          slotValues: { THING: "a discount" },
          topicArea: "shopping",
        },
        {
          en: "Was it possible to get an earlier appointment?",
          bn: "আগে অ্যাপয়েন্টমেন্ট পাওয়া কি সম্ভব ছিল?",
          pronunciation_bn: "ওয়াজ ইট পসিবল টু গেট অ্যান আর্লিয়ার অ্যাপয়েন্টমেন্ট?",
          slotValues: { THING: "an earlier appointment" },
          topicArea: "health",
        },
      ],
    },
    {
      variant: "negative",
      label: "Negative (না)",
      label_bn: "না",
      formula: "Isn't it possible to get [THING]?",
      formula_bn: "[জিনিস] পাওয়া কি সম্ভব না?",
      examples: [
        {
          en: "Isn't it possible to get a replacement?",
          bn: "বদলে নতুন একটা পাওয়া কি সম্ভব না?",
          pronunciation_bn: "ইজন্ট ইট পসিবল টু গেট এ রিপ্লেসমেন্ট?",
          slotValues: { THING: "a replacement" },
          topicArea: "shopping",
        },
        {
          en: "Isn't it possible to get a late checkout?",
          bn: "লেট চেকআউট পাওয়া কি সম্ভব না?",
          pronunciation_bn: "ইজন্ট ইট পসিবল টু গেট এ লেট চেকআউট?",
          slotValues: { THING: "a late checkout" },
          topicArea: "travel",
        },
        {
          en: "Isn't it possible to get some extra time?",
          bn: "বাড়তি সময় পাওয়া কি সম্ভব না?",
          pronunciation_bn: "ইজন্ট ইট পসিবল টু গেট সাম এক্সট্রা টাইম?",
          slotValues: { THING: "some extra time" },
          topicArea: "education",
        },
      ],
    },
    {
      variant: "future",
      label: "Future (ভবিষ্যৎ)",
      label_bn: "ভবিষ্যৎ",
      formula: "Will it be possible to get [THING]?",
      formula_bn: "[জিনিস] পাওয়া কি সম্ভব হবে?",
      examples: [
        {
          en: "Will it be possible to get an upgrade next time?",
          bn: "পরেরবার আপগ্রেড পাওয়া কি সম্ভব হবে?",
          pronunciation_bn: "উইল ইট বি পসিবল টু গেট অ্যান আপগ্রেড নেক্সট টাইম?",
          slotValues: { THING: "an upgrade next time" },
          topicArea: "travel",
        },
        {
          en: "Will it be possible to get a table for tomorrow?",
          bn: "আগামীকালের জন্য টেবিল পাওয়া কি সম্ভব হবে?",
          pronunciation_bn: "উইল ইট বি পসিবল টু গেট এ টেবল ফর টুমরো?",
          slotValues: { THING: "a table for tomorrow" },
          topicArea: "food",
        },
        {
          en: "Will it be possible to get a transfer next month?",
          bn: "আগামী মাসে বদলি পাওয়া কি সম্ভব হবে?",
          pronunciation_bn: "উইল ইট বি পসিবল টু গেট এ ট্রান্সফার নেক্সট মান্থ?",
          slotValues: { THING: "a transfer next month" },
          topicArea: "work",
        },
      ],
    },
    {
      variant: "he_she",
      label: "He/She (সে)",
      label_bn: "সে",
      formula: "Is it possible for him/her to get [THING]?",
      formula_bn: "তার পক্ষে কি [জিনিস] পাওয়া সম্ভব?",
      examples: [
        {
          en: "Is it possible for her to get a discount?",
          bn: "তার পক্ষে কি ছাড় পাওয়া সম্ভব?",
          pronunciation_bn: "ইজ ইট পসিবল ফর হার টু গেট এ ডিসকাউন্ট?",
          slotValues: { THING: "a discount" },
          topicArea: "shopping",
        },
        {
          en: "Is it possible for him to get a transfer?",
          bn: "তার পক্ষে কি বদলি পাওয়া সম্ভব?",
          pronunciation_bn: "ইজ ইট পসিবল ফর হিম টু গেট এ ট্রান্সফার?",
          slotValues: { THING: "a transfer" },
          topicArea: "work",
        },
        {
          en: "Is it possible for her to get an appointment?",
          bn: "তার পক্ষে কি অ্যাপয়েন্টমেন্ট পাওয়া সম্ভব?",
          pronunciation_bn: "ইজ ইট পসিবল ফর হার টু গেট অ্যান অ্যাপয়েন্টমেন্ট?",
          slotValues: { THING: "an appointment" },
          topicArea: "health",
        },
      ],
    },
    {
      variant: "name",
      label: "By Name (নাম দিয়ে)",
      label_bn: "নাম দিয়ে",
      formula: "Is it possible for [NAME] to get [THING]?",
      formula_bn: "[নাম]-এর পক্ষে কি [জিনিস] পাওয়া সম্ভব?",
      examples: [
        {
          en: "Is it possible for Milon to get a transfer?",
          bn: "মিলনের পক্ষে কি বদলি পাওয়া সম্ভব?",
          pronunciation_bn: "ইজ ইট পসিবল ফর মিলন টু গেট এ ট্রান্সফার?",
          slotValues: { THING: "a transfer" },
          topicArea: "work",
        },
        {
          en: "Is it possible for Ayesha to get a discount?",
          bn: "আয়েশার পক্ষে কি ছাড় পাওয়া সম্ভব?",
          pronunciation_bn: "ইজ ইট পসিবল ফর আয়েশা টু গেট এ ডিসকাউন্ট?",
          slotValues: { THING: "a discount" },
          topicArea: "shopping",
        },
        {
          en: "Is it possible for Rahim to get an earlier appointment?",
          bn: "রহিমের পক্ষে কি আগে অ্যাপয়েন্টমেন্ট পাওয়া সম্ভব?",
          pronunciation_bn: "ইজ ইট পসিবল ফর রহিম টু গেট অ্যান আর্লিয়ার অ্যাপয়েন্টমেন্ট?",
          slotValues: { THING: "an earlier appointment" },
          topicArea: "health",
        },
      ],
    },
    {
      variant: "polite",
      label: "Polite (বিনয়ী)",
      label_bn: "বিনয়ী",
      formula: "Would it be possible to get [THING]?",
      formula_bn: "[জিনিস] পাওয়া কি সম্ভব হতো?",
      examples: [
        {
          en: "Would it be possible to get an upgrade?",
          bn: "আপগ্রেড পাওয়া কি সম্ভব হতো?",
          pronunciation_bn: "উড ইট বি পসিবল টু গেট অ্যান আপগ্রেড?",
          slotValues: { THING: "an upgrade" },
          topicArea: "travel",
        },
        {
          en: "Would it be possible to get a late checkout?",
          bn: "লেট চেকআউট পাওয়া কি সম্ভব হতো?",
          pronunciation_bn: "উড ইট বি পসিবল টু গেট এ লেট চেকআউট?",
          slotValues: { THING: "a late checkout" },
          topicArea: "travel",
        },
        {
          en: "Would it be possible to get a discount?",
          bn: "ছাড় পাওয়া কি সম্ভব হতো?",
          pronunciation_bn: "উড ইট বি পসিবল টু গেট এ ডিসকাউন্ট?",
          slotValues: { THING: "a discount" },
          topicArea: "shopping",
        },
      ],
    },
  ],
};
