import type { Pattern } from "@/types/pattern";

export const patternA2_3: Pattern = {
  id: "A2.3",
  formula: "May I have [THING]?",
  formula_bn: "আমি কি [জিনিস] পেতে পারি?",
  patternName: "Formal Request",
  patternName_bn: "ভদ্রভাবে চাওয়া",
  formulaPronunciation_bn: "মে আই হ্যাভ [জিনিস]?",
  concept_bn: "ভদ্রভাবে চাওয়া",
  bridgeRuleIds: ["BR1", "BR3", "BR4", "BR8"],
  slots: [
    {
      name: "THING",
      description: "A noun or noun phrase you are politely requesting",
      description_bn: "যে জিনিস তুমি ভদ্রভাবে চাইছো",
      acceptedTypes: ["noun"],
      examples: ["your attention", "a moment", "the check"],
    },
  ],
  examples: [
    {
      en: "May I have your attention, please?",
      bn: "আমি কি আপনার দৃষ্টি আকর্ষণ করতে পারি?",
      pronunciation_bn: "মে আই হ্যাভ ইয়োর অ্যাটেনশন, প্লিজ?",
      slotValues: { THING: "your attention" },
      topicArea: "work",
      stage: 1,
      miniStory: {
        situation_bn: "তুমি অফিসে মিটিংয়ে দাঁড়িয়ে আছো। সবাই নিজেদের মধ্যে কথা বলছে। তোমাকে একটা জরুরি তথ্য জানাতে হবে।",
        icon: "📢",
      },
    },
    {
      en: "May I have a moment of your time?",
      bn: "আমি কি আপনার একটু সময় পেতে পারি?",
      pronunciation_bn: "মে আই হ্যাভ এ মোমেন্ট অফ ইয়োর টাইম?",
      slotValues: { THING: "a moment of your time" },
      topicArea: "work",
      stage: 1,
      miniStory: {
        situation_bn: "তুমি অফিসে বসের রুমের সামনে দাঁড়িয়ে আছো। বস ব্যস্ত। তোমার একটু কথা বলা দরকার।",
        icon: "🚪",
      },
    },
    {
      en: "May I have the bill, please?",
      bn: "আমি কি বিলটা পেতে পারি?",
      pronunciation_bn: "মে আই হ্যাভ দা বিল, প্লিজ?",
      slotValues: { THING: "the bill" },
      topicArea: "food",
      stage: 1,
      miniStory: {
        situation_bn: "তুমি রেস্টুরেন্টে খাওয়া শেষ করেছো। ওয়েটারকে ভদ্রভাবে বিল চাইতে চাও।",
        icon: "🧾",
      },
    },
    {
      en: "May I have a cup of tea?",
      bn: "আমি কি এক কাপ চা পেতে পারি?",
      pronunciation_bn: "মে আই হ্যাভ এ কাপ অফ টি?",
      slotValues: { THING: "a cup of tea" },
      topicArea: "food",
      stage: 1,
      miniStory: {
        situation_bn: "তুমি শ্বশুরবাড়িতে গেছো। বাড়ির লোকজন বসতে বলেছে। তুমি ভদ্রভাবে চা চাইতে চাও।",
        icon: "☕",
      },
    },
    {
      en: "May I have a glass of water?",
      bn: "আমি কি এক গ্লাস পানি পেতে পারি?",
      pronunciation_bn: "মে আই হ্যাভ এ গ্লাস অফ ওয়াটার?",
      slotValues: { THING: "a glass of water" },
      topicArea: "daily_life",
      stage: 1,
      miniStory: {
        situation_bn: "তুমি হাসপাতালে ডাক্তারের চেম্বারে বসে আছো। গরমে গলা শুকিয়ে গেছে। নার্সকে পানি চাইতে চাও।",
        icon: "💧",
      },
    },
    {
      en: "May I have the report by tomorrow?",
      bn: "আমি কি আগামীকালের মধ্যে রিপোর্টটি পেতে পারি?",
      pronunciation_bn: "মে আই হ্যাভ দা রিপোর্ট বাই টুমরো?",
      slotValues: { THING: "the report by tomorrow" },
      topicArea: "work",
      stage: 2,
    },
    {
      en: "May I have the receipt?",
      bn: "আমি কি রসিদটা পেতে পারি?",
      pronunciation_bn: "মে আই হ্যাভ দা রিসিট?",
      slotValues: { THING: "the receipt" },
      topicArea: "finance",
      stage: 2,
      miniStory: {
        situation_bn: "তুমি দোকানে জিনিস কিনেছো। অফিসে বিল দেখাতে হবে। দোকানদারের কাছে রসিদ চাইছো।",
        icon: "🧾",
      },
    },
    {
      en: "May I have your name?",
      bn: "আমি কি আপনার নামটি জানতে পারি?",
      pronunciation_bn: "মে আই হ্যাভ ইয়োর নেইম?",
      slotValues: { THING: "your name" },
      topicArea: "daily_life",
      stage: 2,
    },
    {
      en: "May I have a copy of the form?",
      bn: "আমি কি ফর্মের একটা কপি পেতে পারি?",
      pronunciation_bn: "মে আই হ্যাভ এ কপি অফ দা ফর্ম?",
      slotValues: { THING: "a copy of the form" },
      topicArea: "education",
      stage: 2,
    },
    {
      en: "May I have some more time?",
      bn: "আমি কি আরেকটু সময় পেতে পারি?",
      pronunciation_bn: "মে আই হ্যাভ সাম মোর টাইম?",
      slotValues: { THING: "some more time" },
      topicArea: "work",
      stage: 2,
    },
    {
      en: "May I have a second opinion?",
      bn: "আমি কি আরেকজন ডাক্তারের মতামত পেতে পারি?",
      pronunciation_bn: "মে আই হ্যাভ এ সেকেন্ড ওপিনিয়ন?",
      slotValues: { THING: "a second opinion" },
      topicArea: "health",
      stage: 3,
      miniStory: {
        situation_bn: "ডাক্তার বলেছে অপারেশন লাগবে। তুমি নিশ্চিত হতে চাও। আরেকজন ডাক্তারের মতামত চাইছো।",
        icon: "🏥",
      },
    },
    {
      en: "May I have the directions to the nearest mosque?",
      bn: "আমি কি নিকটতম মসজিদের দিকনির্দেশনা পেতে পারি?",
      pronunciation_bn: "মে আই হ্যাভ দা ডাইরেকশনস টু দা নিয়ারেস্ট মস্ক?",
      slotValues: { THING: "the directions to the nearest mosque" },
      topicArea: "religion",
      stage: 3,
    },
    {
      en: "May I have this gift-wrapped?",
      bn: "আমি কি এটি উপহার মোড়কে পেতে পারি?",
      pronunciation_bn: "মে আই হ্যাভ দিস গিফট-র‍্যাপড?",
      slotValues: { THING: "this gift-wrapped" },
      topicArea: "shopping",
      stage: 3,
    },
    {
      en: "May I have a seat by the window?",
      bn: "আমি কি জানালার পাশে একটা সিট পেতে পারি?",
      pronunciation_bn: "মে আই হ্যাভ এ সিট বাই দা উইন্ডো?",
      slotValues: { THING: "a seat by the window" },
      topicArea: "travel",
      stage: 3,
    },
    {
      en: "May I have a doctor's note?",
      bn: "আমি কি ডাক্তারের সার্টিফিকেট পেতে পারি?",
      pronunciation_bn: "মে আই হ্যাভ এ ডক্টরস নোট?",
      slotValues: { THING: "a doctor's note" },
      topicArea: "health",
      stage: 3,
    },
  ],
  formality: "formal",
  difficulty: "beginner",
  usageNote: "'May I have' is the most formal of the three request patterns. Use in professional settings or with strangers.",
  usageNote_bn: "'মে আই হ্যাভ' হলো সবচেয়ে ভদ্র চাওয়ার উপায়। বস, শিক্ষক, ডাক্তার বা অচেনা মানুষের কাছে কিছু চাইতে হলে এটা বলো। বাজারে বন্ধুর কাছে চাইতে 'ক্যান আই হ্যাভ' বলো — সেটা সহজ।",
  combinableWith: ["A2.1", "A2.2"],
  responsePatterns: ["B2.1"],
  banglaStructureMap: "বাংলা: আমি কি [জিনিস] পেতে পারি? → English: May I have [THING]?",

  // ===== TEACHING FIELDS =====

  conversionSteps: {
    banglaThought: "তুমি বাংলায় বলো: 'আমি কি একটু পানি পেতে পারি?'",
    steps: [
      {
        step_bn: "'অনুমতি চাইছি' = 'May' — ইংরেজিতে ভদ্রভাবে অনুমতি চাইতে 'May' দিয়ে শুরু করো",
        result: "May",
      },
      {
        step_bn: "'আমি' = 'I' — তারপর 'আমি' বসাও",
        result: "May I",
      },
      {
        step_bn: "'পেতে পারি' = 'have' — তারপর 'have' বলো আর জিনিসের নাম বলো",
        result: "May I have some water?",
      },
    ],
    finalResult: "May I have some water?",
    finalResult_bn: "আমি কি একটু পানি পেতে পারি?",
  },

  commonMistakes: [
    {
      wrong: "May I having water?",
      correct: "May I have water?",
      explanation_bn: "'May I'-এর পরে সবসময় 'have' বসে — 'having' না। 'May I have' একসাথে মনে রাখো।",
    },
    {
      wrong: "May I has the report?",
      correct: "May I have the report?",
      explanation_bn: "'May I'-এর পরে সবসময় 'have' বসে — কখনো 'has' না। 'I'-এর সাথে সবসময় 'have'।",
    },
    {
      wrong: "Can I have the report?",
      correct: "May I have the report?",
      explanation_bn: "'Can I have' ভুল না, কিন্তু বসের কাছে বা অচেনা লোকের কাছে 'May I have' বললে বেশি ভদ্র শোনায়।",
    },
    {
      wrong: "I may have water?",
      correct: "May I have water?",
      explanation_bn: "প্রশ্ন করতে 'May' আগে বসে — 'May I have...'। 'I may have' বললে মানে বদলে যায়।",
    },
  ],

  simpleRules: [
    {
      rule_bn: "ভদ্রভাবে কিছু চাইতে → 'May I have' + জিনিসের নাম",
      example: "May I have the bill?",
    },
    {
      rule_bn: "'May I have' হলো সবচেয়ে ভদ্র — বড়দের সাথে, অফিসে, হাসপাতালে এটা বলো",
      example: "May I have a glass of water? (ডাক্তারের কাছে)",
    },
    {
      rule_bn: "বন্ধু বা পরিবারের সাথে 'Can I have' বলো — সেটা সহজ, 'May I have' বেশি ফর্মাল",
      example: "Can I have tea? (বন্ধুর কাছে) vs May I have tea? (বসের কাছে)",
    },
    {
      rule_bn: "আরও ভদ্র করতে শেষে 'please' যোগ করো",
      example: "May I have the receipt, please?",
    },
  ],

  usageSituations: [
    {
      situation_bn: "হাসপাতালে ডাক্তারের কাছে",
      situation_en: "At the hospital with the doctor",
      exampleSentence: "May I have a doctor's note?",
      exampleSentence_bn: "আমি কি ডাক্তারের সার্টিফিকেট পেতে পারি?",
    },
    {
      situation_bn: "অফিসে বসের কাছে",
      situation_en: "At the office with the boss",
      exampleSentence: "May I have the report by tomorrow?",
      exampleSentence_bn: "আমি কি আগামীকালের মধ্যে রিপোর্টটি পেতে পারি?",
    },
    {
      situation_bn: "সরকারি দফতরে (ইউনিয়ন পরিষদ, ডিসি অফিস)",
      situation_en: "At a government office",
      exampleSentence: "May I have a copy of the form?",
      exampleSentence_bn: "আমি কি ফর্মের একটা কপি পেতে পারি?",
    },
    {
      situation_bn: "বিমানবন্দরে বা বাস কাউন্টারে",
      situation_en: "At the airport or bus counter",
      exampleSentence: "May I have a seat by the window?",
      exampleSentence_bn: "আমি কি জানালার পাশে একটা সিট পেতে পারি?",
    },
  ],

  sentenceBuilding: [
    {
      previousPatternId: "A2.1",
      previousFormula: "Can I have [THING]?",
      previousFormula_bn: "আমি কি [জিনিস] পেতে পারি?",
      combined: "বন্ধুকে: Can I have some water? বসকে: May I have some water?",
      combined_bn: "বন্ধুকে: আমি কি পানি পেতে পারি? বসকে: আমি কি একটু পানি পেতে পারি?",
    },
    {
      previousPatternId: "A2.2",
      previousFormula: "Could I have [THING]?",
      previousFormula_bn: "আমি কি [জিনিস] পেতে পারতাম?",
      combined: "Could I have the form? May I have a pen to fill it out?",
      combined_bn: "আমি কি ফর্মটা পেতে পারি? আমি কি সেটা পূরণ করতে একটা কলম পেতে পারি?",
    },
  ],

  memoryTrick_bn:
    "'May' মানে 'অনুমতি' — বড় কাউকে বলতে হলে 'May I have' বলো, বন্ধুকে বলতে হলে 'Can I have' বলো। মনে রাখো: বড় লোক = 'May', ছোট/বন্ধু = 'Can'।",

  chunks: [
    { en: "May I have", bn: "আমি কি পেতে পারি", pronunciation_bn: "মে আই হ্যাভ" },
    { en: "May I have some", bn: "আমি কি কিছু পেতে পারি", pronunciation_bn: "মে আই হ্যাভ সাম" },
    { en: "May I have the", bn: "আমি কি ওইটা পেতে পারি", pronunciation_bn: "মে আই হ্যাভ দা" },
    { en: "May I have a", bn: "আমি কি একটা পেতে পারি", pronunciation_bn: "মে আই হ্যাভ এ" },
  ],

  wordMap: {
    bn_sentence: "আমি কি রসিদটা পেতে পারি?",
    en_sentence: "May I have the receipt?",
    mappings: [
      { bn_word: "পারি", en_word: "May", type: "moved", bridgeRuleId: "BR3" },
      { bn_word: "আমি", en_word: "I", type: "direct", bridgeRuleId: "BR8" },
      { bn_word: "পেতে", en_word: "have", type: "direct", bridgeRuleId: "BR1" },
      { bn_word: "রসিদটা", en_word: "the receipt", type: "split", bridgeRuleId: "BR4" },
      { bn_word: "কি", en_word: "", type: "added" },
    ],
  },

  answerTemplates: [
    {
      situation_bn: "যখন হাসপাতালে ডাক্তার বা নার্সকে কিছু চাইছো",
      question: "May I have a glass of water?",
      question_bn: "আমি কি এক গ্লাস পানি পেতে পারি?",
      answerFormula: "Sure / Of course / Certainly",
      answerFormula_bn: "অবশ্যই / হ্যাঁ নিশ্চয়ই",
      pronunciation_bn: "শিওর / অফ কোর্স / সার্টেনলি",
      examples: [
        { answer: "Of course. Here you go.", answer_bn: "অবশ্যই। এই নিন।", pronunciation_bn: "অফ কোর্স। হিয়ার ইউ গো।" },
        { answer: "Sure, just a moment.", answer_bn: "নিশ্চয়ই, একটু অপেক্ষা করুন।", pronunciation_bn: "শিওর, জাস্ট এ মোমেন্ট।" },
        { answer: "Certainly, I'll bring it right away.", answer_bn: "অবশ্যই, এখনই আনছি।", pronunciation_bn: "সার্টেনলি, আইল ব্রিং ইট রাইট অ্যাওয়ে।" },
      ],
      notes_bn: "ডাক্তার, নার্স বা অফিসের লোক সাধারণত 'Sure', 'Of course', বা 'Certainly' বলে।",
    },
    {
      situation_bn: "যখন সরকারি অফিসে কাগজপত্র চাইছো",
      question: "May I have a copy of the form?",
      question_bn: "আমি কি ফর্মের একটা কপি পেতে পারি?",
      answerFormula: "Yes, here it is. / Please fill this out.",
      answerFormula_bn: "হ্যাঁ, এই নিন। / এটা পূরণ করুন।",
      pronunciation_bn: "ইয়েস, হিয়ার ইট ইজ। / প্লিজ ফিল দিস আউট।",
      examples: [
        { answer: "Yes, here it is.", answer_bn: "হ্যাঁ, এই নিন।", pronunciation_bn: "ইয়েস, হিয়ার ইট ইজ।" },
        { answer: "Please fill this out and submit at counter 3.", answer_bn: "এটা পূরণ করে ৩ নম্বর কাউন্টারে জমা দিন।", pronunciation_bn: "প্লিজ ফিল দিস আউট অ্যান্ড সাবমিট অ্যাট কাউন্টার থ্রি।" },
        { answer: "I'm sorry, we're out of forms. Come back tomorrow.", answer_bn: "দুঃখিত, ফর্ম শেষ। আগামীকাল আসুন।", pronunciation_bn: "আইম সরি, উই আর আউট অফ ফর্মস। কাম ব্যাক টুমরো।" },
      ],
      notes_bn: "সরকারি অফিসে 'May I have' বললে তারা সাধারণত 'Here it is' বা 'Please fill this out' বলে।",
    },
    {
      situation_bn: "যখন বিমানবন্দর বা বাস কাউন্টারে কিছু চাইছো",
      question: "May I have a seat by the window?",
      question_bn: "আমি কি জানালার পাশে সিট পেতে পারি?",
      answerFormula: "Let me check. / Yes, we have one available.",
      answerFormula_bn: "দেখছি। / হ্যাঁ, একটা খালি আছে।",
      pronunciation_bn: "লেট মি চেক। / ইয়েস, উই হ্যাভ ওয়ান অ্যাভেইলেবল।",
      examples: [
        { answer: "Let me check. Yes, seat 14A is available.", answer_bn: "দেখছি। হ্যাঁ, ১৪A সিট খালি আছে।", pronunciation_bn: "লেট মি চেক। ইয়েস, সিট ফোর্টিন-এ ইজ অ্যাভেইলেবল।" },
        { answer: "Sorry, all window seats are taken.", answer_bn: "দুঃখিত, জানালার সব সিট ভর্তি।", pronunciation_bn: "সরি, অল উইন্ডো সিটস আর টেকেন।" },
        { answer: "Sure, that will be an extra 200 taka.", answer_bn: "নিশ্চয়ই, এটার জন্য আরও ২০০ টাকা লাগবে।", pronunciation_bn: "শিওর, দ্যাট উইল বি অ্যান এক্সট্রা টু হান্ড্রেড টাকা।" },
      ],
      notes_bn: "কাউন্টারের লোক 'Let me check' বলে দেখে, তারপর 'Yes' বা 'Sorry' বলে।",
    },
    {
      situation_bn: "যখন শিক্ষককে কিছু চাইছো",
      question: "May I have some more time?",
      question_bn: "আমি কি আরেকটু সময় পেতে পারি?",
      answerFormula: "Yes, you can have [TIME]. / Sorry, the deadline is fixed.",
      answerFormula_bn: "হ্যাঁ, [সময়] পাবে। / দুঃখিত, সময়সীমা নির্ধারিত।",
      pronunciation_bn: "ইয়েস, ইউ ক্যান হ্যাভ [টাইম]। / সরি, দা ডেডলাইন ইজ ফিক্সড।",
      examples: [
        { answer: "Yes, you can have two more days.", answer_bn: "হ্যাঁ, আরও দুইদিন সময় পাবে।", pronunciation_bn: "ইয়েস, ইউ ক্যান হ্যাভ টু মোর ডেইজ।" },
        { answer: "Sorry, I can't extend the deadline.", answer_bn: "দুঃখিত, সময়সীমা বাড়ানো যাবে না।", pronunciation_bn: "সরি, আই ক্যান্ট এক্সটেন্ড দা ডেডলাইন।" },
        { answer: "Okay, but submit by Friday.", answer_bn: "ঠিক আছে, তবে শুক্রবারের মধ্যে জমা দাও।", pronunciation_bn: "ওকে, বাট সাবমিট বাই ফ্রাইডে।" },
      ],
      notes_bn: "শিক্ষক বা বস সাধারণত 'Yes, you can have...' বা 'Sorry, I can't...' বলে।",
    },
  ],

  dialogueChains: [
    {
      id: "dc-a2.3-1",
      title_bn: "হাসপাতালে ডাক্তারের চেম্বারে",
      title_en: "At the doctor's chamber in the hospital",
      situation_bn: "তুমি হাসপাতালে গেছো। ডাক্তার দেখার পরে তোমার কিছু জিনিস দরকার।",
      icon: "🏥",
      turns: [
        { speaker_bn: "তুমি", en: "May I have a glass of water?", bn: "আমি কি এক গ্লাস পানি পেতে পারি?", pronunciation_bn: "মে আই হ্যাভ এ গ্লাস অফ ওয়াটার?", patternId: "A2.3" },
        { speaker_bn: "নার্স", en: "Of course. Here you go.", bn: "অবশ্যই। এই নিন।", pronunciation_bn: "অফ কোর্স। হিয়ার ইউ গো।" },
        { speaker_bn: "তুমি", en: "Thank you. May I have a doctor's note?", bn: "ধন্যবাদ। আমি কি ডাক্তারের সার্টিফিকেট পেতে পারি?", pronunciation_bn: "থ্যাংক ইউ। মে আই হ্যাভ এ ডক্টরস নোট?", patternId: "A2.3" },
        { speaker_bn: "নার্স", en: "Sure, I'll ask the doctor to write one.", bn: "নিশ্চয়ই, ডাক্তারকে বলি লিখে দিতে।", pronunciation_bn: "শিওর, আইল আস্ক দা ডক্টর টু রাইট ওয়ান।" },
        { speaker_bn: "তুমি", en: "May I have a second opinion?", bn: "আমি কি আরেকজন ডাক্তারের মতামত পেতে পারি?", pronunciation_bn: "মে আই হ্যাভ এ সেকেন্ড ওপিনিয়ন?", patternId: "A2.3" },
        { speaker_bn: "নার্স", en: "Yes, I can arrange that. Please wait.", bn: "হ্যাঁ, ব্যবস্থা করছি। অনুগ্রহ করে অপেক্ষা করুন।", pronunciation_bn: "ইয়েস, আই ক্যান অ্যারেঞ্জ দ্যাট। প্লিজ ওয়েট।" },
      ],
      patternsUsed: ["A2.3"],
    },
    {
      id: "dc-a2.3-2",
      title_bn: "সরকারি অফিসে (ডিসি অফিস)",
      title_en: "At the government office (DC office)",
      situation_bn: "তুমি ডিসি অফিসে জমির কাগজপত্রের জন্য গেছো।",
      icon: "🏛️",
      turns: [
        { speaker_bn: "তুমি", en: "May I have a copy of the form?", bn: "আমি কি ফর্মের একটা কপি পেতে পারি?", pronunciation_bn: "মে আই হ্যাভ এ কপি অফ দা ফর্ম?", patternId: "A2.3" },
        { speaker_bn: "কর্মকর্তা", en: "Yes, here it is. Fill it out properly.", bn: "হ্যাঁ, এই নিন। ঠিকমতো পূরণ করুন।", pronunciation_bn: "ইয়েস, হিয়ার ইট ইজ। ফিল ইট আউট প্রোপারলি।" },
        { speaker_bn: "তুমি", en: "May I have a pen, please?", bn: "আমি কি একটা কলম পেতে পারি?", pronunciation_bn: "মে আই হ্যাভ এ পেন, প্লিজ?", patternId: "A2.3" },
        { speaker_bn: "কর্মকর্তা", en: "Sure, use this one.", bn: "নিশ্চয়ই, এটা ব্যবহার করুন।", pronunciation_bn: "শিওর, ইউজ দিস ওয়ান।" },
        { speaker_bn: "তুমি", en: "May I have the receipt?", bn: "আমি কি রসিদটা পেতে পারি?", pronunciation_bn: "মে আই হ্যাভ দা রিসিট?", patternId: "A2.3" },
        { speaker_bn: "কর্মকর্তা", en: "Yes, come to counter 3.", bn: "হ্যাঁ, ৩ নম্বর কাউন্টারে আসুন।", pronunciation_bn: "ইয়েস, কাম টু কাউন্টার থ্রি।" },
      ],
      patternsUsed: ["A2.3"],
    },
  ],

  variations: [
    {
      variant: "past",
      label: "Past (অতীত)",
      label_bn: "অতীত",
      formula: "Might I have had [THING]?",
      formula_bn: "আমি কি [জিনিস] পেতে পারতাম?",
      examples: [
        {
          en: "Might I have had a word with you earlier?",
          bn: "আমি কি আগে আপনার সাথে একটু কথা বলতে পারতাম?",
          pronunciation_bn: "মাইট আই হ্যাভ হ্যাড এ ওয়ার্ড উইথ ইউ আর্লিয়ার?",
          slotValues: { THING: "a word with you earlier" },
          topicArea: "work",
        },
        {
          en: "Might I have had the report yesterday?",
          bn: "আমি কি গতকাল রিপোর্টটা পেতে পারতাম?",
          pronunciation_bn: "মাইট আই হ্যাভ হ্যাড দা রিপোর্ট ইয়েস্টারডে?",
          slotValues: { THING: "the report yesterday" },
          topicArea: "work",
        },
        {
          en: "Might I have had a copy of the form?",
          bn: "আমি কি ফর্মের কপি পেতে পারতাম?",
          pronunciation_bn: "মাইট আই হ্যাভ হ্যাড এ কপি অফ দা ফর্ম?",
          slotValues: { THING: "a copy of the form" },
          topicArea: "education",
        },
      ],
    },
    {
      variant: "negative",
      label: "Negative (না)",
      label_bn: "না",
      formula: "May I not have [THING]?",
      formula_bn: "আমি কি [জিনিস] পেতে পারি না?",
      examples: [
        {
          en: "May I not have some more time?",
          bn: "আমি কি আরেকটু সময় পেতে পারি না?",
          pronunciation_bn: "মে আই নট হ্যাভ সাম মোর টাইম?",
          slotValues: { THING: "some more time" },
          topicArea: "education",
        },
        {
          en: "May I not have a different option?",
          bn: "আমি কি অন্য কোনো অপশন পেতে পারি না?",
          pronunciation_bn: "মে আই নট হ্যাভ এ ডিফারেন্ট অপশন?",
          slotValues: { THING: "a different option" },
          topicArea: "shopping",
        },
        {
          en: "May I not have a second chance?",
          bn: "আমি কি আরেকটা সুযোগ পেতে পারি না?",
          pronunciation_bn: "মে আই নট হ্যাভ এ সেকেন্ড চান্স?",
          slotValues: { THING: "a second chance" },
          topicArea: "work",
        },
      ],
    },
    {
      variant: "future",
      label: "Future (ভবিষ্যৎ)",
      label_bn: "ভবিষ্যৎ",
      formula: "Will I be able to have [THING]?",
      formula_bn: "আমি কি [জিনিস] পেতে পারবো?",
      examples: [
        {
          en: "Will I be able to have the report by Monday?",
          bn: "আমি কি সোমবারের মধ্যে রিপোর্টটা পেতে পারবো?",
          pronunciation_bn: "উইল আই বি এবল টু হ্যাভ দা রিপোর্ট বাই মান্ডে?",
          slotValues: { THING: "the report by Monday" },
          topicArea: "work",
        },
        {
          en: "Will I be able to have a word with the manager?",
          bn: "আমি কি ম্যানেজারের সাথে একটু কথা বলতে পারবো?",
          pronunciation_bn: "উইল আই বি এবল টু হ্যাভ এ ওয়ার্ড উইথ দা ম্যানেজার?",
          slotValues: { THING: "a word with the manager" },
          topicArea: "work",
        },
        {
          en: "Will I be able to have a doctor's note tomorrow?",
          bn: "আমি কি আগামীকাল ডাক্তারের সার্টিফিকেট পেতে পারবো?",
          pronunciation_bn: "উইল আই বি এবল টু হ্যাভ এ ডক্টরস নোট টুমরো?",
          slotValues: { THING: "a doctor's note tomorrow" },
          topicArea: "health",
        },
      ],
    },
    {
      variant: "he_she",
      label: "He/She (সে)",
      label_bn: "সে",
      formula: "May he/she have [THING]?",
      formula_bn: "সে কি [জিনিস] পেতে পারে?",
      examples: [
        {
          en: "May she have a cup of tea?",
          bn: "সে কি এক কাপ চা পেতে পারে?",
          pronunciation_bn: "মে শি হ্যাভ এ কাপ অফ টি?",
          slotValues: { THING: "a cup of tea" },
          topicArea: "food",
        },
        {
          en: "May he have the directions?",
          bn: "সে কি দিকনির্দেশনা পেতে পারে?",
          pronunciation_bn: "মে হি হ্যাভ দা ডাইরেকশনস?",
          slotValues: { THING: "the directions" },
          topicArea: "travel",
        },
        {
          en: "May she have a copy of the form?",
          bn: "সে কি ফর্মের একটা কপি পেতে পারে?",
          pronunciation_bn: "মে শি হ্যাভ এ কপি অফ দা ফর্ম?",
          slotValues: { THING: "a copy of the form" },
          topicArea: "education",
        },
      ],
    },
    {
      variant: "casual",
      label: "Casual (সহজ)",
      label_bn: "সহজ",
      formula: "Can I have [THING]?",
      formula_bn: "আমি কি [জিনিস] পেতে পারি?",
      examples: [
        {
          en: "Can I have a cup of tea?",
          bn: "আমি কি এক কাপ চা পেতে পারি?",
          pronunciation_bn: "ক্যান আই হ্যাভ এ কাপ অফ টি?",
          slotValues: { THING: "a cup of tea" },
          topicArea: "food",
        },
        {
          en: "Can I have the bill?",
          bn: "আমি কি বিলটা পেতে পারি?",
          pronunciation_bn: "ক্যান আই হ্যাভ দা বিল?",
          slotValues: { THING: "the bill" },
          topicArea: "food",
        },
        {
          en: "Can I have your name?",
          bn: "আমি কি তোমার নামটা জানতে পারি?",
          pronunciation_bn: "ক্যান আই হ্যাভ ইয়োর নেইম?",
          slotValues: { THING: "your name" },
          topicArea: "daily_life",
        },
      ],
    },
  ],
};
